### ISSUE TITLE
Adding URL / link to an image?

### ISSUE THREAD

**Issue by JoshLCove** [airbnb/lottie-web#1000]
Hi, sorry if this has been asked before! I've had a look and couldn't find it.

Is it possible to ad a link to an animation / img? I have setup a banner ad and need the ending button (an image file) to link to a web address. Would that be possible / has it been done before?

**Comment by Shirkit** [comment]
While I do not know if it's possible, you can easily make the whole banner clickable instead of just the button.

Or you could add an eventListener through Javascript to listen for click events.

And, combining with that, you can manually traverse the output HTML and do a cursor:pointer on the specific element. The tree is always the same, so once you've found that it's the 3rd child of the 7th child of the root element, you can target that.

Not ideal, but it's something.

**Comment by JoshLCove** [comment]
Thanks! I think we've found a potential solution, the difficulty is that there's two buttons that will have different links (I didn't mention that).

Some guys in the office that are a lot smarter with this than me are testing now and if it works I'll post the solution here for others to see too - it has something to do with setting an ID tag in AE and then using JS to reference the ID - I think maybe similar to what you've suggested.

**Comment by Shirkit** [comment]
Nice! Although I do not know if the IDs are exported to the final HTML. That you'll have to test and confirm, because I recall it doesn't, that's why I did it by manually finding the position of the element I was interested.

**Comment by bodymovin** [comment]
You can name your AE layers in a particular way and they'll get exported with class names or ids
https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript

**Comment by JoshLCove** [comment]
That's the one! That's what we've done, it seems to be working so far.

**Comment by Shirkit** [comment]
Ah, that's why! Great news then Hernan. I always thought that this would be a thing, but I didn't know about it. Great work on this awesome project. It's really pushing the web forward in my view!

**Comment by mesmaili151** [comment]
Can we use the image link map?
i want to create a Animation with buttons !

**Comment by robtoloy** [comment]
im renaming layers in After Effects and seeing no such ID or class name in the output bodymovin JSON file..
