### ISSUE TITLE
Is it possible to decrease file?

### ISSUE THREAD

**Issue by szwaggier** [airbnb/lottie-web#1001]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
have you tried serving them gzipped?

**Comment by szwaggier** [comment]
yes
I need export file to google adwords, 
My file have 250 kb but i need have file 150 kb,

**Comment by bodymovin** [comment]
you can replace the png files in the images folder with some optimized versions of them.
Try uploading them to [https://tinypng.com/](https://tinypng.com/) for example and see how they look.

**Comment by szwaggier** [comment]
ok, file lottie.js have 60 kb, but html have 245 kb, can I decrease this html file?

**Comment by bodymovin** [comment]
you don't need both.
The demo.html already includes the json and the lottie player.

**Comment by szwaggier** [comment]
[BANER TEST 2.zip](https://github.com/airbnb/lottie-web/files/1960580/BANER.TEST.2.zip)

**Comment by szwaggier** [comment]
I need file lottie.js and file images to google adwords ?

**Comment by bodymovin** [comment]
it depends on how you need to provide your fijes.
I'd suggest that you select the standalone option when exporting and only provide the exported js file and images folder

**Comment by Shirkit** [comment]
For loading the Lottie Web, you only need the player, which servers around ~60KB, and the JSON or the PNG images, which ever you prefer

The HTML file is the demo file, and you don't need it on production, it's there just as a testing example.

I'm serving both the Player and the JSON (I'm using SVG isntead of PNG) as a single file, being loaded asynchronously so it doesn't block the initial load. I've heavily optimized and simplified the animation for that, and the delivery process.

But why you say you need the files TO Google Adwords @szwaggier ?

**Comment by deraalex** [comment]
cant you bind in the player via cdnjs so its hostet external and doesnt count in your file weight?

@Shirkit i think you have to deliver the ad to the adserver in a zipped html

**Comment by deraalex** [comment]
i will do some research in Ad producing with Lottie and try to get it running. i think it depends on the Adserver what features are supported, but i think external hosted js-libraries wont be a problem. Will keep you updated.
