### ISSUE TITLE
BodyMovin Render

### ISSUE THREAD

**Issue by oghaz001** [airbnb/lottie-web#1002]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? I created a few complex animations (icon morph + jello-split using the fast blur and simple choker effects).**

**What did you expect to happen? I expected to have the same effects rendered using the bodymovin tool**

**What actually happened? The jello-split effect didn't show up at all, I attached the files below, you will need to download the asset files as well ... the composition I am trying to render is Background@2x**

**https://drive.google.com/drive/folders/1CjPoWvFdp2U3gzAE4wMoNXiUYZ7Al27s?usp=sharing**

**Comment by bodymovin** [comment]
Hi, many of the After Effects effects are not supported by the player.
You can check the wiki to see which ones are the supported ones currently.
https://github.com/airbnb/lottie-web/wiki/Effects

**Comment by oghaz001** [comment]
Thanks
