### ISSUE TITLE
Duik IK not getting exported as SVG. 

### ISSUE THREAD

**Issue by karanmintzip** [airbnb/lottie-web#1003]
**Windows 10.1**

* **After Effects CC:**

**I created the bones using DUIK and then converted them to IK. When exported to .JSON and html, it's not working.**

**I expected it to work as Lottie supports IK.**

**Duik IK is not exporting as SVG. The animation done using IK is not working.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by karanmintzip** [comment]
[support.zip](https://github.com/airbnb/lottie-web/files/1963957/support.zip)

**Comment by bodymovin** [comment]
I'll check it later today.
But make sure you're including guided and hidden layers on the comp settings of the bodymovin panel,  since Duik relies on them.

**Comment by oghaz001** [comment]
Hi,
I actually have an issue rendering some complex effects in  Ae. Trying to render the Jello-split effect using the fast blur and simple choker effects but it doesn't show up in the render.
[Archive.zip](https://github.com/airbnb/lottie-web/files/1964894/Archive.zip)

**Comment by karanmintzip** [comment]
@bodymovin I did included the guided layers and hidden layers. It doesn't works.

**Comment by bodymovin** [comment]
@karanmintzip unfortunately Puppet Pin is not supported by the plugin

**Comment by karanmintzip** [comment]
@bodymovin I've converted the puppet pins to IK. IK is supported by Bodymovin. Why isn't it working then?
