### ISSUE TITLE
Chars is null

### ISSUE THREAD

**Issue by igor-nikolic** [airbnb/lottie-web#1008]
Hi,
I have a problem when rendering using canvas. When I use SVG renderer, it works fine, but when I use canvas, it says THIS.CHARS is NULL. Can someone help ?

**Comment by bodymovin** [comment]
Hi, the canvas renderer doesn't support exporting text, it only supports the glyphs option.
Can that be the reason of the error?

**Comment by igor-nikolic** [comment]
I will try that. Can the method "updateDocumentData" be used when renderer is CANVAS? I have figured out how to check which layer has text and how I can update them, but only when the renderer is SVG.

**Comment by igor-nikolic** [comment]
Thank you @bodymovin ! Great library. :)
