### ISSUE TITLE
Image missing from animation — specify a path to it?

### ISSUE THREAD

**Issue by BDKNYC** [airbnb/lottie-web#1009]
Hello,

The AE animation I've rendered has a jpg image in it. When I run the demo file, everything looks perfect. But when I install the code on my website, the image is missing (everything else is good to go). I'm assuming this is because the image path is no longer correct?

I'm loading this onto a SquareSpace website, so the JSON data is in an inline script. Is there a way for me to specify the path to that image, since it isn't in a folder relative to the JSON data file?

Thanks!
BK

**Comment by bodymovin** [comment]
Hi, can you sahre a link with the implementation?

**Comment by BDKNYC** [comment]
Yes, sorry!

https://www.bdk.nyc/body

The image is missing from the background here (right now it shows a blue gradient, which is a background for that webpage). If you click the word TEST, that's a link to the image.

Thanks!

**Comment by BDKNYC** [comment]
I just realized that, in this particular instance, I could put the image as a background image in the div itself. But, I was looking to use multiple images for another animation and that solution wouldn't work.

Wondering if there's a place in the code that Bodymoving generates that I could specify the image path.

**Comment by BDKNYC** [comment]
I figured out how to use the assetsPath param. All good.

**Comment by gqbre** [comment]
@BDKNYC How to fix it ? By edit data.json files ?
