### ISSUE TITLE
Hidden text layers are showing since 5.1.0

### ISSUE THREAD

**Issue by friday** [airbnb/lottie-web#1010]
Browser: Chrome 66 or Firefox 59
After Effects Version: Unknown (sorry, this is an old export and not by me)

I have an export with a hidden (not sure how) text layer containing letters in order to be able to make the text replaceable (#146).

Since 5.1.0 these are showing:
https://jsfiddle.net/9e3ehspw/1/

With 5.0.6 it's not happening:
https://jsfiddle.net/acfs1aqa/

Note: The missing image error is unrelated and only because I can't upload images to the fiddle or use my server (lottie doesn't support cors afaik).

**Comment by bodymovin** [comment]
Found the issue. Will have it fixed on the next deploy.

**Comment by friday** [comment]
Awesome! Thank you :)
