### ISSUE TITLE
Bodymovin animation loops incorrectly

### ISSUE THREAD

**Issue by skaggetse** [airbnb/lottie-web#1012]
**Tell us about your environment**

* **Browser and Browser Version:**
Chrome Version 66.0.3359.139
* **After Effects Version:**
Version 15.1.1

**What did you do? Please explain the steps you took before you encountered the problem.**
Im making a looping loading animation. Have copied shape-data from an illustration to make it morph between steps.
Works flawlessly in After Effects, when I export the Json or the demo-file, it works the first time, but when it loops it breaks completely.

**What did you expect to happen?**
A seamless loop between a ball, a puck and a tennisball.

**What actually happened? Please include as much _relevant_ detail as possible.**
After the animation is done and starts to loop, some keyframes seams to be overlooked, and things seem to animate in the wrong order.

**Please provide a download link to the After Effects file that demonstrates the problem.**
[loading.zip](https://github.com/airbnb/lottie-web/files/1983295/loading.zip)

**Comment by bodymovin** [comment]
found the issue.
Will be fixed in the next deploy.
Thanks for reporting it!

**Comment by skaggetse** [comment]
Awesome! Thanks.
