### ISSUE TITLE
Chrome Version 66.0.3359.139 (Official Build) (64-bit) Performance and Artifact issues

### ISSUE THREAD

**Issue by thegeminisociety** [airbnb/lottie-web#1013]
macOS: 10.13.3
Chrome: 66.0.3359.139
AE: 2018 v15.0.0

We have been developing a site that uses a lot of heavy fullscreen lottie animation. We had optimized performance really well and things were looking great.

The latest release of Chrome introduced some pretty significant performance decreases along with severe artifacts. We are strictly using SVG renderer.

I cannot share the project due to privacy issues, but I would encourage you to look into the latest release of Chrome and SVG performance/rendering issues.

**Comment by bodymovin** [comment]
I'll take a look.
Meanwhile can you use the canvas renderer?

**Comment by thegeminisociety** [comment]
When i set the renderer to 'canvas' we don't see anything. We are using a lot of shape layers in AE...

**Comment by bodymovin** [comment]
It depends of the features you're using.
Do you know if you're using track matte masks from AE?

**Comment by thegeminisociety** [comment]
We are using many features that are SVG only I think. Which may be why none of it wants to work in canvas. Hoping the new chrome issue is not a major one!

**Comment by thegeminisociety** [comment]
Know you are busy and we really appreciate all you have done on this library! Wanted to see if you had a chance to look into SVG renderer performance on the latest release of Chrome, thanks!

**Comment by bodymovin** [comment]
I'm having trouble finding out what might be going on.
I've tried animations on my own and they seems to work fine.
A couple of questions:
- does it work well in the latest Chrome version on Windows?
- can you share a reduced example that doesn't violate privacy issues?

**Comment by thegeminisociety** [comment]
The issue has been resolved.

Turns out the culprit was a shape with merged paths. It has previously worked in Chrome but the new update broke it.
