### ISSUE TITLE
Transparent objects shows unwanted white fill around its bounding box

### ISSUE THREAD

**Issue by leocantarelli** [airbnb/lottie-web#1014]
Hi there.

I'm testing Lottie to export an After Effects animation using bodymovin plugin. I don't know why, but it's displaying an unwanted white fill around the objects with transparencies around its bounding box.

I've used Illustrator to create the illustrations, imported inside After Effects and created shapes from vector layer.

I've done this image with the original (how it should look) and the Lottie version (with the issue) to help explain it: https://drive.google.com/open?id=1gehGN5ZiF8RNLqopkrcofqJdx3Sw8Vjq

This are the properties for the objects inside AE: https://drive.google.com/file/d/1faryM75LqIayIStXUrkfde_9LYwGFoR_/view

I've tried a few things but, every time I use transparency, it happens.

Does anyone knows how to fix it?

Thanks in advance

**Comment by leocantarelli** [comment]
I still don't know why it happens, but I found a solution that worked for me and probably can help others with the same issue.

I found a plugin call Overlord from Battle Axe that does all the trick of redrawing AI shapes into AE easily. http://www.battleaxe.co/overlord/

**Comment by bodymovin** [comment]
Yes, Overlord is the best option for this.
But if you go through the regular way you need to erase the unnecessary extra shapes and merge paths that AE adds when converting from ai to shapes

**Comment by leocantarelli** [comment]
Is there a easily way to identify and erase?

**Comment by bodymovin** [comment]
there is a tool called explode shape layers that I think does it automatically.
To do it manually, it's usually a Merge Path together with a large square extra path.

**Comment by leocantarelli** [comment]
Great! Thank you for your help.
