### ISSUE TITLE
Animation Artifacts and Lines

### ISSUE THREAD

**Issue by anneOlice** [airbnb/lottie-web#1017]
**Mac OS**
10.13.3

**Browser and Browser Version:**
Chrome Version Version 66.0.3359.139

**After Effects Version:**
15.0.0

I have been working with this json file for the last month or so but only recently noticed that artifacts and lines appear when the animation plays.  

I see this in Chrome and not Safari.  

Any idea why and how to get over it?  I attach the AE exported json for you.

![lottie-artefacts-01](https://user-images.githubusercontent.com/33221464/39826056-654e7b56-53ab-11e8-81bf-42a1eb7fe160.png)
![lottie-artefacts-02](https://user-images.githubusercontent.com/33221464/39826057-6563293e-53ab-11e8-8f02-2326f61750b5.png)

[logo.json.zip](https://github.com/airbnb/lottie-web/files/1988578/logo.json.zip)

**Comment by anneOlice** [comment]
Sure.  
.aep attached.

[olice-logo-to-send.zip](https://github.com/airbnb/lottie-web/files/2001036/olice-logo-to-send.zip)

**Comment by bodymovin** [comment]
Hi, not sure if you closed the issue because you've found a solution.
Anyway, it's probably related to large paths which are also affecting performance too.
For example on layer `"e 2" > Contents > Group 19 `
you should remove `Group 1` and `Merge Paths`

**Comment by anneOlice** [comment]
Thanks.  We'll have a look into this and let you know if it solves our problem.
