### ISSUE TITLE
Doesn't render all components in a composition!

### ISSUE THREAD

**Issue by navidnajm** [airbnb/lottie-web#1019]
![comp-1_3](https://user-images.githubusercontent.com/39187187/39917907-2e8771c0-5524-11e8-94c0-ab3d66f3f303.gif)
Worked on a 5 sec splash screen. there are about 5 components in the composition but Bodymovin doesn't render them completely and some components have totally vanished.
I got no problem in GIF version of my composition but when export the JSON file some components are being lost.

**Comment by bodymovin** [comment]
Hi, can you share a link with the issue and the .aep?

**Comment by navidnajm** [comment]
yeah I'm tranna share a link but it wont upload

**Comment by navidnajm** [comment]
How can I upload the ZIP files here?

**Comment by navidnajm** [comment]
[3.zip](https://github.com/airbnb/lottie-web/files/1998819/3.zip)

**Comment by navidnajm** [comment]
Hey i succeeded 
This is my compsition

**Comment by navidnajm** [comment]
[JSON3.zip](https://github.com/airbnb/lottie-web/files/1998822/JSON3.zip)
and this is the JSON file

**Comment by navidnajm** [comment]
Can you help me, please? I'm working in AE CC 2018 15.1.1

**Comment by bodymovin** [comment]
Hi, there seems to be some missing files in the zip

**Comment by navidnajm** [comment]
[JSON.zip](https://github.com/airbnb/lottie-web/files/1998900/JSON.zip)

**Comment by navidnajm** [comment]
[1.zip](https://github.com/airbnb/lottie-web/files/1998903/1.zip)
and this

**Comment by bodymovin** [comment]
Still missing files. "logo.ai" for example.
Can you share them?

**Comment by navidnajm** [comment]
[logo.zip](https://github.com/airbnb/lottie-web/files/1998905/logo.zip)

**Comment by navidnajm** [comment]
[piggy-bank.zip](https://github.com/airbnb/lottie-web/files/1998907/piggy-bank.zip)

**Comment by navidnajm** [comment]
I've also updated my Bodymovin.

**Comment by navidnajm** [comment]
And I've got another problem with rendering AE effects for example Box Blur and Matte>Simple Choker effects aren't rendered in Bodymovin!!

**Comment by navidnajm** [comment]
![____](https://user-images.githubusercontent.com/39187187/39971691-992f4c04-5714-11e8-8ced-eb8c84ae052b.gif)
I've designed sth like this but Matte and Box Blur effects won't render and the circles in this loading animation appear like two simple circles without any gradient or blur effect...

**Comment by navidnajm** [comment]
My problem is with JSON files not GIFs

**Comment by navidnajm** [comment]
Hi @RubenEscribanoMartin 
Yeah exactly the same issue and it's very annoying. I hope Bodymovin team resolve this ASAP.

**Comment by RubenEscribanoMartin** [comment]
Same here @navidnajm  ... 
We will see how they can resolve this because I haven't found anything related with this issue. 
Anyway if I found the way to resolve this I will post here. ;)

**Comment by bodymovin** [comment]
Hi, AE effects have very little support by the library.
Only a couple of them are, here is the list
https://github.com/airbnb/lottie-web/wiki/Effects

**Comment by navidnajm** [comment]
@RubenEscribanoMartin 
Thx bro cuz all my designs are pending :(

**Comment by navidnajm** [comment]
@bodymovin Thx, could you check the files I sent you? Can you help me with my first issue?

**Comment by bodymovin** [comment]
@navidnajm still missing files.
Can you do a collect and share everything together?

**Comment by bodymovin** [comment]
@RubenEscribanoMartin yes, probably that's the reason.

**Comment by kudanai** [comment]
Hello! Since this issue has been stale for quite a while, I'm going to close it. Please re-open or file a new one if necessary if relevant.
