### ISSUE TITLE
Windows Firefox issue

### ISSUE THREAD

**Issue by xinyou90** [airbnb/lottie-web#1020]
I used this plugin to create some animations on the Angular5 based website.

Please check this.

It works well on all mac os browsers but not on windows firefox

**Comment by bodymovin** [comment]
Hi, I'm trying it in windows firefox and it seems to work fine.
Can you indicate what is it that is failing?

**Comment by xinyou90** [comment]
Please check rocket trail after clicking 'Start' button.

**Comment by bodymovin** [comment]
I see, can you share the .aep so I can take a look at it?

**Comment by xinyou90** [comment]
Sorry, my client does not allow to share it.

Please check the site in Safari (Mac). All the animations are not rendered properly.

This plugin does not work in Safari?

**Comment by bodymovin** [comment]
It should work fine, but there might be an issue to fix.
Could you share a reduced version of the project that reflects the issue but is not bound to your client?

**Comment by bodymovin** [comment]
Hi, this might be solved on the latest version 5.1.18
