### ISSUE TITLE
How to switch animation after initialization?

### ISSUE THREAD

**Issue by laulaaa** [airbnb/lottie-web#1021]
Hello.
I'm trying to figure out how to switch animation after initialization, but I don't see it in the documentation. Is it possible?

I found the same question in airbnb/ios. Here is the reference: [LINK](https://github.com/airbnb/lottie-ios/pull/347)

**Comment by bodymovin** [comment]
Hi, what do you mean switch animation?
Load a new animation in the same container?

**Comment by laulaaa** [comment]
Hello Hernan. Thank you for your answer and time. 
Yes, exactly that.

**Comment by bodymovin** [comment]
you can call `animation.destroy()` to remove the previous animation, and then load a new one the same way you did the first time.

**Comment by ankushgoel** [comment]
Hi @bodymovin 

Using destroy and loading the animation again creates performance issues, Please suggest a better way.
Thanks

**Comment by ankushgoel** [comment]
> you can call `animation.destroy()` to remove the previous animation, and then load a new one the same way you did the first time.

Hi @bodymovin

Using destroy and loading the animation again creates performance issues, Please suggest a better way.
Thanks

**Comment by bodymovin** [comment]
@ankushgoel what kind of performance issues?

**Comment by ankushgoel** [comment]
After clicking the left arrow, the map vanishes, but it shouldn't.
![lottie-performance-issue](https://user-images.githubusercontent.com/16498576/60155137-f63e1400-9806-11e9-9e18-6b5f71a33d3b.gif)

**Comment by Desintegrator** [comment]
Why were it closed? It is still a problem. I need sometimes to switch between two animations. One animation to another and then switch back. I do not want to load same json each time

**Comment by bodymovin** [comment]
@Desintegrator you can also hide one and show the other one without destroying them. The issue is closed because that functionality is not part of the library, but you can build it on top of it.
