### ISSUE TITLE
Resize div according to animation

### ISSUE THREAD

**Issue by thefiend** [airbnb/lottie-web#1022]
I have a floating button with SVG animation where it is a circular button (something like the Go to top button) and it animates, expands sideways showing a text.

However, I would like to know if it is possible to resize the div according to the animation, so it starts as a 90x90 div and expands to 90x 150 when the animation gets triggered in pure javascript.

**Comment by bodymovin** [comment]
Hi, you can play around with the viewBox property of the animation in order to resize the animation together with the container element
