### ISSUE TITLE
Bad Performance for Simple Animation

### ISSUE THREAD

**Issue by chrsalctra** [airbnb/lottie-web#1023]
**Tell us about your environment**
MacBook Pro 2017, iPhone X
* **Browser and Browser Version:**
Safari Latest
* **After Effects Version:**
CC 2018
**What did you do? Please explain the steps you took before you encountered the problem.**
It was quite confusing but I finally was able to get the 3 files needed to get this animation to be on a web page. Low FPS.
**What did you expect to happen?**
Low FPS
**What actually happened? Please include as much _relevant_ detail as possible.**
On every device the frame rate is slow. In after effects I did 120fps options and 60. Also tried making the animation longer to include more fps per second and still not luck. Rendering a .mov also renders is very smooth. 
**Please provide a download link to the After Effects file that demonstrates the problem.**
[christian.zip](https://github.com/airbnb/lottie-web/files/1998867/christian.zip)

**Comment by bodymovin** [comment]
Hi, is this only happening on Safari?
Are other browsers working fine?

**Comment by chrsalctra** [comment]
All browsers its iffy. I’m going to check AE settings or try to find more.

**Comment by chrsalctra** [comment]
@bodymovin Here is a link to a code pen, I modified the animation to 120 fps in AE and animation is still eh. Maybe its the performence but I have tried a few browsers with the same output. Also did proper file organization calling the json file. If you could check it out, thankyou! https://codepen.io/chrsalctra/project/editor/ZmVVgk

**Comment by chrsalctra** [comment]
I changed background to black and performence is better. Odd!
