### ISSUE TITLE
Animate Using Stroke Dash Gap

### ISSUE THREAD

**Issue by brandonmakes** [airbnb/lottie-web#1026]
Hey there, 

For a particular animation, I'm keyframing stroke dash gaps to animate the spreading of a dashed line ([Example](https://www.dropbox.com/s/wmf2s22u9xufkvu/delivery.mp4?dl=0)). When I export via Bodymovin, it doesn't seem to support this feature.

Codepen for example: https://codepen.io/brandonmakes/project/editor/ArxxEJ

Any ideas?

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by brandonmakes** [comment]
Sure thing! 
Here you go: https://www.dropbox.com/s/6lodw2r04akfu28/delivery-test.aep?dl=0

**Comment by bodymovin** [comment]
Hi, I found the issue.
It's gonna be fixed on the next deploy.
Thanks!

**Comment by brandonmakes** [comment]
Awesome! Any idea on when the next deploy will be? Looking to launch the project this will be featured in today/tomorrow.

**Comment by bodymovin** [comment]
I'll do it later today when I get home.

**Comment by brandonmakes** [comment]
Perfect, can you let me know when you've deployed and where I can find the latest? Thank you!

**Comment by bodymovin** [comment]
Deployed.
You can get it here or on the aescripts site.
You just need to update the player, no need to reexport animations.

**Comment by brandonmakes** [comment]
Thanks a bunch!
