### ISSUE TITLE
Canvas renderer - Alpha Mattes issues

### ISSUE THREAD

**Issue by RanSlidely** [airbnb/lottie-web#1028]
Hi,
I testing the Lottie-web canvas renderer with animation that includes alpha matte that reveals an image.
the animation work great with the SVG render but when switching to canvas render it work differently.
In the canvas render the matte is cover the image not applying mask like the SVG render.
The reason that I need the canvas renderer is that Edge browser has a lot of issues with SVG masks.

The questions are: 
1. does the canvas render should render mattes like the SVG render? (I think it should)
2. do you have any solution or a way that I can fix it?

Thanks,
Ran

**Comment by bodymovin** [comment]
1. The canvas renderer doesn't support mattes right now.
2. can you use regular AE masks instead of mattes?

**Comment by zhengs** [comment]
Hi @bodymovin ,

This page seems to indicate canvas renderer *does* support matte (at least alpha matte and alpha inverted matte are supported): http://airbnb.io/lottie/supported-features.html. Could you explain why the inconsistency?

One more question: the same page show "track matte" isn't supported for canvas and HTML renderers but "alpha matte" is.    Isn't "alpha matte" just one type of "track matte"?

**Comment by bodymovin** [comment]
@zhengs you're right, both are not correctly indicated.
I'll ask the team to change it.

**Comment by zhengs** [comment]
If possible, @bodymovin , maybe also let the team change the markers of luma matte and luma inverted matte for svg, canvas, html renderers. Right now they just show 3 question marks that are a bit unclear what they exactly mean (i.e. the support is still being developed? the support is case-by-case? the support is unstable? etc.)
