### ISSUE TITLE
Gradients from after effects to .JSON

### ISSUE THREAD

**Issue by Oivaidas** [airbnb/lottie-web#1029]
hey, i have a problem and dont know how to solve it does anyone tried to export gradients from after effects with bodymoving? Seems like gradient data is somehow lost and set to default black and white.
Tried saving before export, restarting resaving project, checked lenguage OS and AE, tried different PC's.
Nothing worked so far. 
![image](https://user-images.githubusercontent.com/39297116/40046832-9066b42c-5836-11e8-981e-d72167e572a6.png)

**Comment by bodymovin** [comment]
Hi, could it be some kind of user permission limitation on the project file? Or is it located in a different disk than the AE installation?
Can you share the .aep?

**Comment by Oivaidas** [comment]
hi,
no the project file and installation on the same disk.
https://drive.google.com/drive/folders/1i58uYBLVYOrpswOGHXuyZSpB-dUKcwXF?usp=sharing

**Comment by Oivaidas** [comment]
hi,
sorry i have closed it accidentally, but the problem still not solved.
Yes they are both on same disk.
here is a link to project file:
https://drive.google.com/drive/folders/1i58uYBLVYOrpswOGHXuyZSpB-dUKcwXF?usp=sharing

**Comment by bodymovin** [comment]
I've seen this before but I haven't been able to figure out what is going on.
I just tested it and it renders correctly.
Here is the exported json from my PC.
[data.zip](https://github.com/airbnb/lottie-web/files/2007106/data.zip)

I see you have different versions of AE installed. Which one are you using to export it?
