### ISSUE TITLE
Joysticks and sliders, a second joystick does not work

### ISSUE THREAD

**Issue by Gorusss** [airbnb/lottie-web#1030]
Hi, there. I have a little problem I don't know how to solve.

Do it in a Macbook pro. Last chrome update. AE 2015. Last JnS and BoM update.

I created a animation with the plugin joystick and sliders, in which face and eyes are controlled by two different joysticks.

The animation works correctly in AE but when exporting to bodymovin the eyes stop animating. I have exported by clicking on the export guides option. The head animation works perfectly.

Edited: Maybe it is important to know that the joysticks are in different compositions and I have used the option to upload them to the parent one. To control them better.

I include a download link to the file in case it's useful "macario_2.aep".

https://drive.google.com/drive/folders/1FsM5g7oa4FXXQFP7QYl1Mv3AwOGWR8q2?usp=sharing

Thank you

**Comment by bodymovin** [comment]
Hi, I requested access to the drive folder

**Comment by Gorusss** [comment]
Sorry. I've already given you access.

**Comment by Gorusss** [comment]
![oh-no](http://www.surfingmylife.com/wp-content/uploads/2018/04/oh-no.jpg)

Thanks anyway for your time
