### ISSUE TITLE
Rendering Issues on Edge

### ISSUE THREAD

**Issue by ergo-neil** [airbnb/lottie-web#1031]
Hi 

**Tell us about your environment**
We have some animations that work in all browsers apart from Edge on Windows 10.  http://dev.thebrandwalk.com/

* **Browser and Browser Version:**
Edge 41.16299.402.0
* **After Effects Version:**
15.0.1 build 73

**What did you do? Please explain the steps you took before you encountered the problem.**
Exported animation from After Effects using Bodymovin plugin version 5.1.11. Uploaded the json to webserver and initialised using the lottie library.

**What did you expect to happen?**
Animation to play cleanly, as experienced in other browsers. 
![find-your-chrome](https://user-images.githubusercontent.com/17163800/40065222-2fd9833c-5859-11e8-9f74-33f8fd13b8d5.png)

**What actually happened? Please include as much _relevant_ detail as possible.**
Animation is slow and broken up
![find-your-edge](https://user-images.githubusercontent.com/17163800/40065184-0e38c562-5859-11e8-8576-2b5dcadbaa4f.png)

Has anyone else experienced similar issues?

**Comment by bodymovin** [comment]
Edge has some issues with svg mask tags and filter tags.
Can you replace easily your track matte masks in AE with regular AE additive masks?

**Comment by neil-emblime** [comment]
Thanks, we seem to be getting there with this now.
