### ISSUE TITLE
Where to "updateDocumentData()"?

### ISSUE THREAD

**Issue by frankbiemans** [airbnb/lottie-web#1032]
Good afternoon,

Together with our AE-animators i've been messing around with Lottie today. On thing i can't figure out is the "updateDocumentData()" method. I'm able to change the text once by changing the 't'-var in the 'layers'-collection... But where- or however the try the "updateDocumentData()"-method i get a error: "Cannot read property 'updateDocumentData' of undefined". 

The wiki says "(Example in next section)" but there is no "next section" :(

This is my script:

	var animation = bodymovin.loadAnimation({
		container: document.getElementById("bm"),
		renderer: "svg",
		loop: true,
		autoplay: true,
		path: "json-animation/animated-text.json"
	});

	animation.addEventListener('data_ready', function(){
		animation.layers[0].t.d.k[0].s.t = 'Lorem';
		animation.renderer.elements[0].updateDocumentData({t:'new text', s:20},0);
	});

I've zipped and attached the JSON file i'm using. 

Can anybody tell me what i'm doing wrong?
Thank you.

[animated-text.zip](https://github.com/airbnb/lottie-web/files/2005680/animated-text.zip)

~ Frank

**Comment by frankbiemans** [comment]
@levon93 Nope :-( Do you have the same problem?

**Comment by levon93** [comment]
Yeah, and the bad thing is I am trying to load html  on android, because it's hard to modify animation dinamicly with lottie andoird library  and have no idea about js,html and so)))

**Comment by bodymovin** [comment]
Hi, do you still need help on this?
@frankbiemans regarding your example, is the text layer the first layer of the animation?

**Comment by robbbsen** [comment]
This is still an issue. I've searched my ass off for that function, just can't find it. Did something change since the end of 2018?

**Comment by bodymovin** [comment]
@robbbsen do you have a link with the animation working you are trying to update?

**Comment by robbbsen** [comment]
@bodymovin that reaction was faster than expected. I've got a very minimal animation for testing purposes. I've saved it with and without the glyphs-setting. I hope lottiefiles.com is fine for that.
Without glyphs: https://lottiefiles.com/share/cZuYsB
With glyphs: https://lottiefiles.com/share/Rzz6kV

I don't know which dependency changes the availability of "updateDocumentData()". I've got a very small project for this testing. I've used this cdn: https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.4.4/lottie.js. 

Further I've used `let anim = lottie.loadAnimation({ ... animationData: animation.json ... })`. I've then logged anim to the console and inspected it from the browser. Thats the point where I've seen there is no such function to call.

Maybe I'm doing something wrong in here?

**Comment by bodymovin** [comment]
@robbbsen can you try doing `anim.renderer.elements[2].updateDocumentData({t:'60'})`?

**Comment by twentyfiveframes** [comment]
Did you find a solution?

**Comment by jinjie1010** [comment]
@frankbiemans Hey, have you find the solution?

**Comment by frankbiemans** [comment]
Hi @jinjie1010, nope, I haven't. I used the workaround (`animation.layers[0].t.d.k[0].s.t = 'Lorem';`) and actually haven't been using Lottie since. If i remember correctly i was able to set the text on initialization once and that was enough for me. 

Maybe @robbbsen did?

**Comment by frankbiemans** [comment]
Hi @jinjie1010, nope, I haven't. I used the workaround (`animation.layers[0].t.d.k[0].s.t = 'Lorem';`) and actually haven't been using Lottie since. If i remember correctly i was able to set the text on initialization once and that was enough for me. 

Maybe @robbbsen did?
