### ISSUE TITLE
Doesn't show masks that are used in Illustrator

### ISSUE THREAD

**Issue by DJkuiper** [airbnb/lottie-web#1035]
Using After effects CC 15.0.0
on Windows 10 machine

Created a cookie that gets eaten in illustrator.
I have used clipping mask in my design.
added animations on after effects with layers and keyframes.
Didn't use masks inside after effects.

![naamloos](https://user-images.githubusercontent.com/32675972/40116893-71cf1e7a-5915-11e8-9214-3c849924c216.jpg)
![naamloos2](https://user-images.githubusercontent.com/32675972/40116894-71e79716-5915-11e8-8cad-b197af13ee7e.jpg)

Link to AE file : 
https://drive.google.com/file/d/1iXpOz85rBfGABolVPiVRQiWj11pxtVUE/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, I requested permission to access the drive folder.
It's probably related to how AE converts ai layers to shapes sometimes.
If you open the contents of the shape layers and remove the extra merge path and large square path from each group it will work fine.

**Comment by DJkuiper** [comment]
Hey there,

You should have access to the file
I will check the paths.

Greetings
Dennis

**Comment by bodymovin** [comment]
Yes, it's related to the merge paths indeed.
There is a plugin called explode shape layers that I think does this automatically.
https://aescripts.com/explode-shape-layers/
If not, you unfortunately you have to do it manually.
