### ISSUE TITLE
Go to link when animation complete

### ISSUE THREAD

**Issue by chrsalctra** [airbnb/lottie-web#1036]
**Tell us about your environment**
MacBook Pro 2017
* **Browser and Browser Version:**
* **After Effects Version:**
CC 2018
**What did you do? Please explain the steps you took before you encountered the problem.**
Click on "PORTFOLIO"
**What did you expect to happen?**
Animation on "PORTFOLIO" to play and complete, the to open the link.
**What actually happened? Please include as much _relevant_ detail as possible.**
Jumps to link. I want to play animation, then jump to link when animation completes. In Atom app, it works, but that is probably because the speed is slower showing my desired effect. In a broswer it behaves normally, where the click will not pause a link jump (expected, but I want a pause).
**Please provide a download link to the After Effects file that demonstrates the problem.**
[christian.zip](https://github.com/airbnb/lottie-web/files/2009839/christian.zip)

**Comment by chrsalctra** [comment]
I may be asking a stupid question, just not sure where to approach. I tried putting the event in a function but I don't think it would work. Please check it out, even adding a pause for a set time is fine instead of the animation on complete.

**Comment by vinniejames** [comment]
You probably need:

```
animation.addEventListener('complete', function(){   
    window.location.href = 'https://www.dribbble.com/chrsalctra'; 
});
```

**Comment by chrsalctra** [comment]
@vinniejames Thank you! for some reason, elem2 (the container) works for on hover, but 'animation' is needed for on click. Thank you again!

**Comment by voyceatlas** [comment]
This doesn't work when playing in reverse.

**Comment by vinniejames** [comment]
Yes it does, you need to find the correct event to listen to
