### ISSUE TITLE
Animation effect does not take effect

### ISSUE THREAD

**Issue by guoleifei** [airbnb/lottie-web#1037]
**win10 **

* **Browser and Browser Version:**
* **After Effects CC  15.01:**

**I am not a designer. When our designers gave me AE files, I used Bodymovin to export json files. Preview does not have any animation effects in the plugin.**

**Animation effect does not take effect**

This is the effect of ae playback

![image](https://user-images.githubusercontent.com/16201257/40153280-a65d9ab2-59bb-11e8-898a-f8bdd143f0e2.png)

This is a preview of the plugin export.

![image](https://user-images.githubusercontent.com/16201257/40153304-cfd59048-59bb-11e8-9b00-40a93ad9b865.png)

[波浪线条1.zip](https://github.com/airbnb/lottie-web/files/2011389/1.zip)

.**
I uploaded the ae file. Can you tell me exactly what went wrong? Thank you
My English is not very good, this text comes from Google Translate

**Comment by bodymovin** [comment]
Hi, there are very few AE effects supported for the moment
you can check the list here
https://github.com/airbnb/lottie-web/wiki/Effects

**Comment by guoleifei** [comment]
Can you tell me what kind of unsupported effects are used in this animation?

**Comment by guoleifei** [comment]
Thank you. The designer used waveform transforms. I let her change Bessel curve and solve the problem.
