### ISSUE TITLE
using with React give error Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by stevanus-id** [airbnb/lottie-web#1038]
Hello, i'm using lottie-web with your sample data.json (from https://codepen.io/airnan/project/editor/ZeNONO) to my HelloWorld react project. I found an error and here is the details. Can you give me a guidance?

## Here is the error

VM4628:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (<anonymous>)
    at XMLHttpRequest.xhr.onreadystatechange (lottie.js:8739)

## Here is the code section
Here is the import code.
`import Lottie from 'lottie-web';`

I call this on componentDidMount.
```
Lottie.loadAnimation({
      container: document.getElementById('lottie-container'), // the dom element that will contain the animation
      renderer: 'svg',
      loop: true,
      autoplay: true,
      path: './menu_to_right.json' // the path to the animation json
    });
```
The element inside render()
`div id="lottie-container"></div>`

**Comment by bodymovin** [comment]
Hi, it seems it's not finding the json file in that location.
Can you share a link to the implementation to confirm?

**Comment by Mujaddadi** [comment]
If you are using webpack, just add this in your webpack configuration. 

`{
        type: 'javascript/auto',
        test: /\.json$/,
        use: [
            {
              loader: 'file-loader',
              options: {
                  name: "./plugin-config/[name].[ext]"
              }
            }
        ]
      }, `
This error is related to Webpack

**Comment by bmac1993** [comment]
Added the snippet above to my webpack.config and still getting the error. Anyone else run into this?
