### ISSUE TITLE
PlaySegments not working with Json-File, but with animationData

### ISSUE THREAD

**Issue by TIIUNDER** [airbnb/lottie-web#1039]
Hi,

I'm trying to trigger segments of a json file using this code:

```
var paramsAnim1 = {
    container: document.getElementById('anim1'),
    renderer: 'svg',
    loop: true,
    autoplay: false,
    path: 'anim/anim1.json',
};

var anim1;
anim1 = lottie.loadAnimation(paramsAnim1);
anim1.playSegments([0,100], true);
```

But it's playing the whole animation, not from 0 to 100. Like it should.

When using this code, it's working:

```
var animationData = '{...}';
var paramsAnim1 = {
    container: document.getElementById('anim1'),
    renderer: 'svg',
    loop: true,
    autoplay: false,
    animationData: animationData,
};

var anim1;
anim1 = lottie.loadAnimation(paramsAnim1);
anim1.playSegments([0,100], true);
```

Why is it working with the animationData variable, but not with the json file?

**Comment by bodymovin** [comment]
Hi, when using a path, the setup of the animation is done asynchronously when the json file is loaded. And at that time, the segment gets overwritten by the data on the json.
You can add a listener to the DOMLoaded event of the animation and then set the new segment.

**Comment by TIIUNDER** [comment]
Thanks! That works

I did it like this:

```
var anim;
anim = lottie.loadAnimation(params);

anim.addEventListener('DOMLoaded',function(){
    anim.playSegments(segmentBasic, true);
});
```
