### ISSUE TITLE
Track matte with roughen edges not working

### ISSUE THREAD

**Issue by m-ehrlich** [airbnb/lottie-web#1041]
Hello!

I'm new to bodymovin / lottie and I tried to simulate a brush stroke svg animation. I used a track matte with roughen edges to make the feeling of a brush.

What I got from bodymovin was only the track matte without the roughen edges effect.

Which means I got this:
<img width="449" alt="screen shot 2018-05-17 at 20 50 02" src="https://user-images.githubusercontent.com/39385219/40197531-fbf8b72e-5a13-11e8-92cd-6cf39a227ef5.png">

Instead of this:
<img width="478" alt="screen shot 2018-05-17 at 20 50 32" src="https://user-images.githubusercontent.com/39385219/40197540-02995ad4-5a14-11e8-87d4-22953b0ec065.png">

Here's the after effects file:
[plus-brush.aep.zip](https://github.com/airbnb/lottie-web/files/2014381/plus-brush.aep.zip)

Thanks in advance!

**Comment by bodymovin** [comment]
Hi, not many AE effects are available to the players.
Here is a list of the only ones supported.
https://github.com/airbnb/lottie-web/wiki/Effects

**Comment by bodymovin** [comment]
IT depends on your use case, but perhaps you can use a png with the effect already applied as mask
