### ISSUE TITLE
Adobe Character Animator - saving layers out in After Effects

### ISSUE THREAD

**Issue by RanLearns** [airbnb/lottie-web#1043]
<img width="2043" alt="ae-scene" src="https://user-images.githubusercontent.com/18236852/40260493-daa80fba-5ac8-11e8-84dd-063eeadfbb31.png">
Hi There!

I have made my animation using Adobe Character Animator. I saved the project (.chproj file) and then opened the project and its scene in After Effects [as shown in this video](https://video.tv.adobe.com/v/19841/?quality=6&hidetitle=true).

When I then used Bodymovin to Render the project, the resulting json does not include the assets that would allow for this to be used with Lottie.

Any suggestions about Adobe Character Animator -> Lottie or about why the project in After Effects resulted in the following json file which has a blank assets [] and only shows the "chproj" Character Animator project file in "layers" as opposed to the vector shapes of the project?

`{"v":"5.1.1","fr":24,"ip":0,"op":96,"w":898,"h":912,"nm":"Scene - Character 2/SayingHello","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":9,"nm":"Scene - Character 2/SayingHello.chproj","cl":"chproj","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[449,456,0],"ix":2},"a":{"a":0,"k":[449,456,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ip":0,"op":96,"st":0,"bm":0}],"markers":[]}`

Attached image shows how the scene looks in After Effects.

Any help would be greatly appreciated here!

**Comment by RanLearns** [comment]
I have made a feature request for Character Animator to add the ability to save vector animations so that it could be used with Lottie...

**Comment by bodymovin** [comment]
Voted. :)
closing for now since there is not much that can be done on the extension side.
