### ISSUE TITLE
[Request] Lists of expensive tasks for Bodymovin

### ISSUE THREAD

**Issue by aenfr** [airbnb/lottie-web#1044]
I've been reading some issues about the slow performing of Bodymovin in mobile devices, and it seems to be related to the use of expensive animation tasks. I'm just wondering if Hernan is able to breakdown a list of the most expensive tasks that affects Bodymovin on perform.

Thanks!

**Comment by bodymovin** [comment]
Two big performance hits on the player side are any kind of effect or mask that generates svg filter or mask tags.
for example:
- track matte masks
- fill effect
- subtractive masks
- stroke effect
