### ISSUE TITLE
Thread Blocking on init

### ISSUE THREAD

**Issue by Adam-Burke** [airbnb/lottie-web#1047]
Hi, 

I have a  Bodymovin export of 300kb and it causes lottie-web to block the browser thread (all ui is frozen) on initialisation for quite a long time ( 5 - 15 seconds). The ae file does have a fair few expressions in it so I assume that is part of the issue but it's surprising that it's so much worse than other examples I have which don't seem far less complex. I could made it faster by progressively loading however that breaks a few other things I'm trying to do. Have you seen anything like this before? 

I would upload the after effects file but it's fairly large and I don't know if there is a specific area in it causing an issue or I'm just reaching the performance limit.

**Comment by bodymovin** [comment]
Hi. If you can, share the aep and the main files. I'll take a look at them.

**Comment by Adam-Burke** [comment]
Actually I can't replicate the issue when I do a demo export. I thought it may be fonts related but doesn't seem to be.

[scoreboard2 (1).aep.zip](https://github.com/airbnb/lottie-web/files/2025392/scoreboard2.1.aep.zip)

**Comment by bodymovin** [comment]
Hi, what is the composition that's failing?
And can you share a link where I can see the issue happening?

**Comment by Adam-Burke** [comment]
It's the "all" composition. Here is a link where it occurs. https://live.staging.ligrsystems.com/basketball/?screenKey=dc478b43-01e1-45af-a5fe-151b37f75718

**Comment by bodymovin** [comment]
Doing a quick revision, I see:
`document.getElementsByTagName('path').length` : 8277
`document.getElementsByTagName('text').length` : 13788 (one per char)
`document.getElementsByTagName('clipPath').length` : 2233
It's probably taking a lot on startup because it's creating all those elements.
Is there any way you can load some of them on demand instead of all at once?
Also, there seem to be 8 final svgs that measure 2001 x 1125 which are probably not helping.
I'll check the animation when I get home to see if I find anything more.

**Comment by Adam-Burke** [comment]
Yeah there are 8 seperate animations but if you remove the problem one the 7 remaining show instantly. Also the problem doesn't occur on the demo export.

**Comment by Adam-Burke** [comment]
Is there a way to stop the text exporting as individual characters?

**Comment by bodymovin** [comment]
If your text layers have text animators, or are part of AE text boxes (boxText vs pointText) there is not.
I've checked for example the layer "MELBOURNE  .awayTextColor" and it has an animator called "Line Height" but it doesn't seem to be using it.
If you can remove those type of animators and set those layers as point texts, the number of text elements will be reduced.
But I'm not sure if that is the only reason for the delay.
cal you try adding this to the options when you load the animation?
````javascript
rendererSettings: {
  progressiveLoad:true
}
````

**Comment by Adam-Burke** [comment]
Yeah I tried progressiveLoad before and it did work. But it makes it harder to do all the image and text finding on initialisation to allow dynamically updating stuff later. I may look into that again though if I have to.  

I think most of the issue was in the ####showVideoAd precomp which I didn't actually need to export. Since removing it the problem is mostly gone. 

Thanks again for your help .
