### ISSUE TITLE
Using JS to add hyperlink to ID after render

### ISSUE THREAD

**Issue by BDKNYC** [airbnb/lottie-web#1048]
At the end of a long, full-screen animation sequence, I have a "learn more" arrow pop up at the bottom of the screen. I'm trying to turn that arrow into a hyperlink, which I believe can be done by naming the AE layer starting with "#" (I have named the layer #arrow) and querying that ID via javascript. Is this correct? If so, would you have any advice on how to go about doing that via .js?

Here's a link to my animation: https://www.bdk.nyc/sheumack4

BTW — You've done amazing work here! I'm constantly impressed by what I've been able to do with After Effects and your plugin. Thanks!

**Comment by bodymovin** [comment]
You can you something like:
`document.getElementById('arrow').addEventListener('click', function(){location.href = '#preFooterBlocks'})`
That for example will navigate to your section called `#preFooterBlocks`
Let me know if it helps.

**Comment by BDKNYC** [comment]
Yes, that's exactly what I was looking for. Works perfectly. Thank you!

**Comment by Aditya88922** [comment]
The issues I have with this method is that I get an error "Uncaught TypeError: Cannot read property 'addEventListener' of null" for the main project file where I have separate json file for the animation in a different folder and referred to it in the animation path in the actual HTML file

If I use the same code in an HTML file that I have generated via Bodymvin (the Demo.html file) it works perfectly fine
