### ISSUE TITLE
Export and preview not working due to colors and expressions

### ISSUE THREAD

**Issue by AntonOta** [airbnb/lottie-web#1049]
**Tell us about your environment**
MacBook Pro 2015

**Browser and Browser Version: Chrome V.66**
After Effects Version: 15.0

**What did you do? Please explain the steps you took before you encountered the problem.**
Downloaded lottie from aescripts, then imported files to export.

**What did you expect to happen?**
The animations to run in the browser.

**What actually happened? Please include as much _relevant_ detail as possible.**
This error: 

![screen shot 2018-05-21 at 11 04 50 pm](https://user-images.githubusercontent.com/20153517/40340132-7b59bf1a-5d4b-11e8-84f5-c324407cf3c8.png)

I believe this is because my after effects composition has shape color chosers and expressions.
The error file is "Question Mark 2"

[mainFiles.aep.zip](https://github.com/airbnb/lottie-web/files/2024824/mainFiles.aep.zip)

Thanks!

**Comment by bodymovin** [comment]
Hi, the layer "COLOR EDIT HERE" is set as an Adjustment Layer, which are not supported by the plugin.
If you convert it to a regular layer and set it's transparency to 0, it should work fine.

**Comment by AntonOta** [comment]
Worked Great! Thanks!
