### ISSUE TITLE
Alpha Matte Export Issue - Trim Paths

### ISSUE THREAD

**Issue by bryanicholas** [airbnb/lottie-web#1050]
I'm using a mac High Sierra 10.13.4, After Effects CC 2018, trying to create an icon reveal animation, using an Alpha Matte layer drawn on top of the original icon. The top layer contains the trim path animation and is hidden, but when I export to JSON that hidden layer containing the path on the Alpha Matte is still showing.

Here's what the shape should look like, with the mask applied so that corners are round and even:

<img width="1320" alt="screen shot 2018-05-22 at 10 10 22" src="https://user-images.githubusercontent.com/39517367/40353042-63df8312-5da8-11e8-9591-521cf4c1d47c.png">

Here's what the exported version looks like, showing just the rough path I traced with the pen:

<img width="854" alt="screen shot 2018-05-22 at 10 11 28" src="https://user-images.githubusercontent.com/39517367/40353096-89cee34c-5da8-11e8-8dd6-a3e096d0d767.png">

Here's the AE file (the canvas is set to 500x700 just so I can work better on a big display, but the final size will be 50x70):
[1-bulb.zip](https://github.com/airbnb/lottie-web/files/2025838/1-bulb.zip)

Thanks in advance for your help!

**Comment by bodymovin** [comment]
Hi, merge paths are not supported by the player.
On your layer `1-bulb Outlines > Contents > Group 6` delete "Merge Paths 1", "Path 3" and "Merge Paths 2" and it should work fine.

**Comment by bryanicholas** [comment]
Wow that's fantastic, worked right away! :D Thank you very much for that. Before closing this thread, could I ask one more question? How do I set up the SVG so that the animation won't be a loop, playing only once?

**Comment by bodymovin** [comment]
you should set `loop: false` as part of the loading options.

**Comment by bryanicholas** [comment]
Perfect! Thank you so much for the incredibly quick reply, your product is awesome :)
