### ISSUE TITLE
blink bug

### ISSUE THREAD

**Issue by BrookShuihuaLee** [airbnb/lottie-web#1051]
**Tell us about your environment**

* **Browser and Browser Version:** Chome 66.0.3359.181
* **After Effects Version:** the ui designer give me those json files

**What did you do? Please explain the steps you took before you encountered the problem.**
First of all, please open the two links: https://codepen.io/brookshuihualee/pen/Jvzvmy  https://codepen.io/brookshuihualee/pen/xjBWyb
The animation will blink while lottie 5.1.15 is changing animation data. But, if we use lottie 5.1.13, it will not happen.

**What did you expect to happen?**
lottie 5.1.15 should work as well as lottie 5.1.13

**What actually happened? Please include as much _relevant_ detail as possible.**
The animation will blink while lottie 5.1.15 is changing animation data. 

**Please provide a download link to the After Effects file that demonstrates the problem.**
please open the two links: https://codepen.io/brookshuihualee/pen/Jvzvmy  https://codepen.io/brookshuihualee/pen/xjBWyb

Thanks!

**Comment by bodymovin** [comment]
I have a fix ready.
I'll upload it on the next deploy.
Probably later today or tomorrow.

**Comment by BrookShuihuaLee** [comment]
ok, thanks

**Comment by bodymovin** [comment]
I've updated a new build of the player that should solve this issue
https://github.com/airbnb/lottie-web/tree/master/build/player

**Comment by BrookShuihuaLee** [comment]
great! it's fixed.
