### ISSUE TITLE
Text characters and colour not rendering correctly

### ISSUE THREAD

**Issue by m3tamode** [airbnb/lottie-web#1053]
Screenshots:

http://prntscr.com/jl4zn1 
http://prntscr.com/jl4z1v 

* **Browser and Browser Version:**

Chrome 66.0.3359.181

* **After Effects Version:**

CC 2018 latest update.

**What did you do? Please explain the steps you took before you encountered the problem.**

I am using the typewriter effect to progressively display the text in the code window/box.
I've tested different fonts - poppins, arial, helvetica, roboto - same result.
I've tested removing tabs - same result.
I've rendered through bodymovin with glyphs enabled and disabled - same result.

**What did you expect to happen?**

I expected the text to render as per the screenshot inside AE.

**What actually happened? Please include as much _relevant_ detail as possible.**

When playing back the rendered file at https://lottie.cloud/app/, the font/characters are not displaying as they are in AE. So the issue is with the formatting of the characters, the rendering of the correct characters, as well as the styling/colour of the characters. Completely different result to what AE produces.

**Please provide a download link to the After Effects file that demonstrates the problem.**

https://www.dropbox.com/s/x8i6v94y714ipo8/home-api.aep?dl=0

**Comment by bodymovin** [comment]
Hi, can you share a link with the issue so I can check what might be going on?
I exported the animation and it seems to work better than on the screenshots.
btw, multiple colors are not supported on a single text box, AE doesn't expose that data. 
And tabs might have a strange behavior.

**Comment by m3tamode** [comment]
I'm just running the json file through https://lottie.cloud/app/ to preview which is where I'm experiencing the strange text output.

Would there be any easy workaround to support the multiple text colours?

Also tried without tabs - same result.

**Comment by bodymovin** [comment]
Can you share the json file?

**Comment by m3tamode** [comment]
https://www.dropbox.com/s/u17reft4b5j05wz/data.json?dl=0

**Comment by bodymovin** [comment]
player version on that site is 4.11.1 but your animation is exported with version 5.1.14
You should try using a newer player.
It's work fine there.

**Comment by m3tamode** [comment]
Aaah yes you're right! I just tested it here https://www.lottiefiles.com/share/SkuCVq and worked a treat.

**Comment by m3tamode** [comment]
Got any ideas how to deal with those 2 text colors?
