### ISSUE TITLE
Hey @bodymovin

### ISSUE THREAD

**Issue by karlsimon** [airbnb/lottie-web#1054]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

Im trying to make an animation with the Duik plugin and bodymovin for a mobile app.

And it seems to work fine when i preview for web, but when I preview in mobile its totally broken, maybe its not supported?

Heres my AEP file:
https://we.tl/XN77kWli4U

Heres my bodymovin/json file:
https://we.tl/2drmlyUgcM

**Comment by bodymovin** [comment]
yes, lottie-android and lottie-ios don't support expressions unfortunately
