### ISSUE TITLE
Unable to execute script at line 293

### ISSUE THREAD

**Issue by SwissNuff** [airbnb/lottie-web#1057]
Hello,
I just installed Bodymovin Ver 5.1.15 and alongside with Adobe After Effects CC 2015. When I try to export an animation this error occurs:

'Unable to execute script at line 293. After Effects Error: the section name and key (Auto Save, Enable Auto Save RQ2) could not be found in the preference.'

**Comment by bodymovin** [comment]
Hi, found the issue.
It will be fixed on the next release.
Probably tomorrow EOD
