### ISSUE TITLE
Mask Issue when preview on smartphone

### ISSUE THREAD

**Issue by augustoconde** [airbnb/lottie-web#1058]
I have created a logo animation and when i upload to LottieFiles and preview on desktop, mask animation works fine. But when i preview on Lottie APP or upload to my app, mask seems to be inverted.

* **Browser and Browser Version:**
Google Chrome
Versão 66.0.3359.181 (Versão oficial) 64 bits

* **After Effects Version:**
After Effects CC 2017.0

**What did you do? Please explain the steps you took before you encountered the problem.**
I create the mask and animated it. Using adding and inverted setup
![captura de tela 2018-05-24 10 33 59](https://user-images.githubusercontent.com/39591831/40488841-0f3684cc-5f3e-11e8-8959-89bb4d8e145d.png)

**What did you expect to happen?**
I expect that animation works on smartphone exactly like on desktop

**What actually happened? Please include as much _relevant_ detail as possible.**
Center logo should be drawing and appearing. On APP center logo is disappearing

**Please provide a download link to the After Effects file that demonstrates the problem.**
Above attached a zip file with json and after effects file.

[Arquivo Comprimido.zip](https://github.com/airbnb/lottie-web/files/2035550/Arquivo.Comprimido.zip)

Thanks.

**Comment by bodymovin** [comment]
Hi, this looks like a lottie-android / lottie-ios issue
Can you post the issue over there?

**Comment by augustoconde** [comment]
I already posted. Is just pending review.
![captura de tela 2018-05-24 10 45 49](https://user-images.githubusercontent.com/39591831/40489545-beadc7ca-5f3f-11e8-8616-5fd9bcab767c.png)
