### ISSUE TITLE
Wrong path to image

### ISSUE THREAD

**Issue by AntonOta** [airbnb/lottie-web#1059]
Hey,

I have created an animation in after effects and exported it with bodymovin. Everything works works well in the demo. However, the image is not loading in the real project and directory. 

I believe this is because, in the demo, the image path is set to data:image/png... 
In the final directory, the path for the image is set to http://localhost:3000/img/rocket_simple/data:image/png...

What should I do?
Thanks,
Anton

**Comment by bodymovin** [comment]
Hi, can you share the json file?

**Comment by AntonOta** [comment]
[data.json.zip](https://github.com/airbnb/lottie-web/files/2037493/data.json.zip)

**Comment by bodymovin** [comment]
I see it working even when loading the json from a subfolder.
Are you using the latest player?

**Comment by AntonOta** [comment]
Im using the one available on cloudflare. If I go to the link, it says cannot get: /img/rocket_simple/data:image/png...

**Comment by bodymovin** [comment]
The player on cloudflare is outdated, that's why it's not working.
You need to use the latest player.

**Comment by AntonOta** [comment]
Thanks!
