### ISSUE TITLE
Very Bad Framerate

### ISSUE THREAD

**Issue by chrsalctra** [airbnb/lottie-web#1061]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**
CC 2018
**What did you do? Please explain the steps you took before you encountered the problem.**
Uploading to host site, and lag! everywhere. Does not lag in local development with Atom
**What did you expect to happen?**
Lag
**What actually happened? Please include as much _relevant_ detail as possible.**
Lag
**Please provide a download link to the After Effects file that demonstrates the problem.**
[Site.zip](https://github.com/airbnb/lottie-web/files/2042960/Site.zip)

**Comment by chrsalctra** [comment]
Not  sure if it has to do with the gzip player (cannot find a tutorial on how to do this)

**Comment by bodymovin** [comment]
Hi, the gzip player shouldn't affect on performance.
I'm trying it and it seems to work fine.
Can you share a link to the host site to try it out?

**Comment by chrsalctra** [comment]
Sure its chrsalctra.com. Runs fine on Chrome but bad in Safari even on a high end rig. Maybe its just a limitation on Safari’s part.

**Comment by felippenardi** [comment]
@bodymovin Is there a different player for gzip jsons?

**Comment by bodymovin** [comment]
@felippenardi no, it's the same
