### ISSUE TITLE
Gradient to Transparent

### ISSUE THREAD

**Issue by jojobe1111** [airbnb/lottie-web#1062]
**Tell us about your environment**
After Effects
* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**
Hi, I'm able to use gradient fill in After Effects & export with bodymovin but when I try to make agradient thats ends with a transparent it doesnt work & just has white, I've also saved the .aep as suggested in other post,from everything else I've read technically it should work so wondering if there's a solution for this. Thanks@
**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by bodymovin** [comment]
@Cadoc unfortunately, those effects (Gaussian Blur) are not supported. 
And the Gradient Overlay style isn't supported either.
If you need to use a gradient, you can create one with a shape layer, using a rectangle and a gradient fill.

**Comment by kudanai** [comment]
Hey there. As this issue has been stale for some time, I'm closing it. Please re-open it if you feel it still relevant or open a new issue.
