### ISSUE TITLE
Can't render text

### ISSUE THREAD

**Issue by janschloss** [airbnb/lottie-web#1063]
**Tell us about your environment**
Windows 10

**After Effects Version:**
Current

**What did you do? Please explain the steps you took before you encountered the problem.**
Add text to After Effects composition. (Arial Regular)

**What did you expect to happen?**
Render.

**What actually happened? Please include as much _relevant_ detail as possible.**
Render process stuck, on cancel alert with "Unable to execute script at line 280. null is not an object" shows.

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by janschloss** [comment]
[text.zip](https://github.com/airbnb/lottie-web/files/2044608/text.zip)

**Comment by bodymovin** [comment]
Just tried it and it works fine.
Could you tell me AE and OS version and language?

**Comment by janschloss** [comment]
AE CC: Version 15.1.11 (Build 12)
OS: Windows 10 Pro, Version 1700, Build 16299.431
Bodymovin Version: 5.1.1

**Comment by janschloss** [comment]
Sorry, no.

* Windows is German
* After Effects is English

**Comment by bodymovin** [comment]
ok, thanks.
I'll check if the issue is related to windows language.

**Comment by janschloss** [comment]
Hoping to reduce your workload I just tried changing my Windows language to English (UK). Sadly it didn't work.

**Comment by bodymovin** [comment]
[bodymovin.zip](https://github.com/airbnb/lottie-web/files/2044799/bodymovin.zip)
cound you try this build?

**Comment by janschloss** [comment]
Sorry for the late reply.

**The new version works!**

**Comment by janschloss** [comment]
Allright, thank you for fixing it!
