### ISSUE TITLE
First iteration of animation has quirks

### ISSUE THREAD

**Issue by janschloss** [airbnb/lottie-web#1066]
First of all thanks for this great project. I got a small problem:

**Tell us about your environment**

* **Browser and Browser Version:** Chrome Version 66.0.3359.181 (Official Build) (64-bit)
* **After Effects Version:** AE CC 15.1.1 Build 12
* **Bodymovin Version:** 5.1.16

**What did you do? Please explain the steps you took before you encountered the problem.**
Created an animation containing text and images, rendered them using Bodymovin and implemented them on an empty html page.

**What did you expect to happen?**
I expected the animation to be displayed similar to AE on the first iteration.

**What actually happened? Please include as much _relevant_ detail as possible.**
The animation works perfectly fine but only after the first run of 20 seconds. In the first run there are artifacts on the top of the animation and a text layer that shoulnd't even be visible is displayed. These two quirks don't happen anymore after the first iteration.
![lottie](https://user-images.githubusercontent.com/16768495/40644808-97d95da6-6324-11e8-9af3-ff4c01b3b4e6.png)
(Please be aware that I edited the text in PS afterwards)

**Please provide a download link to the After Effects file that demonstrates the problem.**
If you need the AE to respond properly please send me a mail address or something similar as I can't share this project publicly.

**Comment by bodymovin** [comment]
Hi. Can you share the project to hernantorrisi(at)gmail.com ?

**Comment by janschloss** [comment]
@bodymovin I've sent a mail to the address above.

**Comment by janschloss** [comment]
@bodymovin Could you find a solution/the problem?

**Comment by bodymovin** [comment]
I'll check it out later today when I get home from work

**Comment by janschloss** [comment]
Allright, thank you very much!

**Comment by janschloss** [comment]
The issue was fixed by downloading the newest lottie.js file.
