### ISSUE TITLE
Not the same animation for android

### ISSUE THREAD

**Issue by karlsimon** [airbnb/lottie-web#1067]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

Hello Bodymovin!

We're having an issue with our animation for an application, its not right on android devices. Works fine on iOS. 

Heres json + ae file:

https://we.tl/FRAfq79F5Y

**Comment by bodymovin** [comment]
Hi, can you post the issue on the lottie-android github?
https://github.com/airbnb/lottie-android
