### ISSUE TITLE
PolyStar roundness doesn't render well (while using expression)

### ISSUE THREAD

**Issue by blobinabottle** [airbnb/lottie-web#1068]
**Environment**
OS X

* **Browser and Browser Version:**
ALL 

* **After Effects Version:**
AE 15.0

**What did you do? Please explain the steps you took before you encountered the problem.**
Shapes "Polystar" with Outer Roundness + Outer linked between layers by expression.

**What did you expect to happen?**
Should work on all layers.

**What actually happened? Please include as much _relevant_ detail as possible.**
Only the "master" layer apply the roundness. (But it's pretty slow in web browser player).
The connected layer doesn't apply the roundness.

Screenshot in AE 
![image](https://user-images.githubusercontent.com/8090162/40651638-8202dcac-6336-11e8-8bc5-88279d8ede0c.png)

Screenshot in bodymovin preview panel
![image](https://user-images.githubusercontent.com/8090162/40651668-919c774a-6336-11e8-97a3-40e103372c6a.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/ynjhhgs6507pzgi/geometricShapes.aep?dl=0

**Comment by bodymovin** [comment]
Hi, I'm trying it and it seems to work fine.
What version of Bodymovin are you using?
