### ISSUE TITLE
Canvas Render TINT/FILL not working

### ISSUE THREAD

**Issue by Thayonn** [airbnb/lottie-web#1073]
**Tell us about your environment**

* **Browser and Browser Version:**
IE Chrome Mobile devices
* **After Effects Version:**
AE CC v 15
**What did you do? Please explain the steps you took before you encountered the problem.**
I have been using the SVG and using the Tint or Fill  with a lot of sucess, but due to bad performance on low end mobiles I moved to canvas, and it seems that the tint is not working.
Changed it to a Fill just n case and still the same..

I tried a simple comp, 1 Sold (green) and a blue tint.
It stayed green :(

**What did you expect to happen?**
Colour Change
**What actually happened? Please include as much _relevant_ detail as possible.**
Nothing
**Please provide a download link to the After Effects file that demonstrates the problem.**
Any AE project, I made a solid and added a tint.

Just as a side not, this is an AMAZING app, I am using it to create some fantastic animations, your a legend, keep it up...

**Comment by bodymovin** [comment]
Yes, unfortunately effects are not supported on the canvas renderer.
And on svg, this kind of effect has a big performance hit.
Can't you use the solid or a shape layer in the final color you need?

**Comment by Thayonn** [comment]
Thank you for your fast reply.
I am unable to replace the assets as the colours are dynamic data driven.
Could you suggest any alternative I can look into to achieve the same effect.
I need to colourise text and some PNG objects to the relevant team colour's

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bodymovin** [comment]
can you do it with css filters and the svg renderer?

**Comment by Thayonn** [comment]
Time to find out :)
Does lottie export css classes for a single object?

**Comment by bodymovin** [comment]
if you prefix the layer with a ".", it will add the layer name as a class.
"#" will add an id
here's an example
https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript

**Comment by Thayonn** [comment]
Fantastic, be back soon off testing

**Comment by Thayonn** [comment]
The CSS hue-rotate works ok, in SVG with some messing.
But it is still very slow on some mobile, but the Canvas is 100%, but it wont use CSS as it is a canvas object.
I going to use 500+ assets to make this work, as the cpu cycles on the any tinting is horrendous, and mobile performance is upmost in this project.

Thank you for all you great work.
And keep it up :))

**Comment by Thayonn** [comment]
Just to keep you informed,it is working just fine now.
The issue was with png background gradients.
once removed those assets , I got the animation to run on a S4 mini with no lag using canvas.
