### ISSUE TITLE
Gradient fills and strokes are not working anymore

### ISSUE THREAD

**Issue by pegeseus** [airbnb/lottie-web#1074]
In AE
![image](https://user-images.githubusercontent.com/25020666/40858296-bfe1f9a0-6592-11e8-92a8-0147a6a2e21e.png)  
![image](https://user-images.githubusercontent.com/25020666/40858467-36e7d2d6-6593-11e8-95c3-250c83dfe225.png)

In browser (chrome)
![image](https://user-images.githubusercontent.com/25020666/40858311-cbbd742a-6592-11e8-9593-cf54c1f8a0f8.png)
![image](https://user-images.githubusercontent.com/25020666/40858483-42630a7c-6593-11e8-96e3-a8544bbdc970.png)

**Tell us about your environment**
Windows 10
Chrome browser (up to date)

* **Browser and Browser Version:**
* **After Effects Version:**
AE CC2018

**What did you do? Please explain the steps you took before you encountered the problem.**
Added a gradient fill to a shape layer rectangle and changed the colors.

**What did you expect to happen?**
The colors would translate over.

**What actually happened? Please include as much _relevant_ detail as possible.**
The gradient disregards color information and only renders as two-node black and white.

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, did you save the project before exporting?
Gradient data is located in the .aep file.

**Comment by pegeseus** [comment]
Fastest fix ever!!  Thanks! :D

**Comment by bodymovin** [comment]
:)

**Comment by maximus8891** [comment]
Thanks! Worked for me too.
