### ISSUE TITLE
How to implement delay time between loops

### ISSUE THREAD

**Issue by electruxxanimations** [airbnb/lottie-web#1075]
How do i implement delay time between loops in html?kindly advice as am new to html coding.

**Comment by bodymovin** [comment]
Hi, you'll have to do it manually by setting loop to false and then you can do something like:
````javascript
anim.addEventListener('complete', function() {
  setTimeout(function(){
    anim.goToAndPlay(0);
  }, 2000);
})
````
Or if it's a fixed delay, you can add it on the AE composition and export it with the corresponding delay.
