### ISSUE TITLE
Closed issue: Method updateDocumentData (explain) #978

### ISSUE THREAD

**Issue by didikunz** [airbnb/lottie-web#1076]
There is the issue #978 that poses the question on how to use "updateDocumentData". It has been closed whitout answering it, why? I

In the wiki it sais: "For now, you'll need to find the path of the text you want to update on your own. (Example in next section)" As a absolute beginner in JavaScript that helps nothing. And the "example in the next section" is missing. There is the code snippet with "anim.renderer.elements" array, but I get back an "undefined" when I try to access one of the elements in it. So can anyone post a simple example javascript on how to get the text instance or the elements number to access it?

**Comment by bodymovin** [comment]
Hi, if you have a snippet of your implementation, I can try to build an example on top of it.

**Comment by didikunz** [comment]
I don't have any existing stuff, I am a beginner with lottie and was starting to test it. I try to use it to create templates for [CasparCG ](www.casparcg.com)  a broadacst charater generator. To be usefull for this it must be posible to change text (and images) dynamically from js. So I was searchning and found this traed, that is closed without any further answer. In other repos treads only get closed if they are answered or solved.

**Comment by marcowi** [comment]
Issue #978 was closed by it's author and thereforein my opinion there is no reason the maintainers have to reopen it. Your question is why you got "undefined" when trying to access "anim.renderer.elements" and to answer this it is necessary to have a snippet the error occurs with. I use it for CasparCG as well and it does work like a charm to export animations and alter text dynamically by either using the updateDocumentData(), which is pre-render, or by using simple DOM-manipulation after the rendering. You could for example name the  text layers something like "#thisismytextineedtochange" and use document.getElementById("thisismytextineedtochange") to change the content.

**Comment by didikunz** [comment]
Thank you for this answer, it points me the way for further experiments. Very much appreciated.
