### ISSUE TITLE
Exporting Bounding box - from .ai, aep and bodymovin

### ISSUE THREAD

**Issue by maxvizard** [airbnb/lottie-web#1077]
Hey, so I have exporting .ai files into after effects and then turned them into shape layers. With a mix of importing in as compositions and footage. Exporting with PNG works fine, which brings me to my first question;

is it possible to implement the animation online to our website and the animations still work? or do I need to export all the files as SVG?

Secondly, now that everything is a shape layer it exports with what I believe to be bounding boxes, but it gives them fills so that there are loads of shapes around the animations. I have tried deleting some of these boxes, but it does not seem to be working. Any help would be much appreciated. 

Also, would just like to say that this is a super super useful plug-in, thanks for all your hard work. Now I just need to make sure I use it properly in the future!  

[Vit_web_animation.zip](https://github.com/airbnb/lottie-web/files/2065770/Vit_web_animation.zip)

![image](https://user-images.githubusercontent.com/6536950/40884515-532521c8-6715-11e8-95cc-a5861e5c3bbf.png)

Let me know of any more information you need, thanks in advance for all your help!

**Comment by bodymovin** [comment]
Hi, unfortunately you need to remove those boxes, and I see you have a lot of them in your composition.
On each layer inside each `Content > Group`, if you see a Group and a Merge Path, you should remove them.
There is a tool called explode shape layers that I think does this automatically.

**Comment by maxvizard** [comment]
Hey, thanks so much for the feedback. That is a time consuming method but it is a solution and I really appreciate it!! Might buy the tool if it will do it automatically - rendered out a test to see if this works and it seems to have done the trick. Thanks again!
