### ISSUE TITLE
Image filenames

### ISSUE THREAD

**Issue by janschloss** [airbnb/lottie-web#1079]
Hey, 

according to #183 you planned on taking the layer name as image filename. Right now it is img_2.png etc.

Is there a way to change this already or is this feature not implemented yet?

**Comment by bodymovin** [comment]
Hi, you can set it on the bodymovin AE panel under the Assets dropdown.

**Comment by janschloss** [comment]
Wow, thanks, sorry for missing that.

Btw: This is the best managed open source project I've ever seen, thank you very much for your insanely fast support!
