### ISSUE TITLE
After effects issues with stroke animation in 3D layer mode. 

### ISSUE THREAD

**Issue by rezasoniquete** [airbnb/lottie-web#1080]
Hi,

I have a issue which I found out whats the problem is, but I don't know how to fix it.

I have a logo build up animation with lines stroke animation with After effects shapes Line and trim path animation. Everything works well when I export it as Bodymovin file. 
I did a slightly change and used elements moving as 3D layer. 
As soon I turn on the 3D layer in my comp, the background lines dissapears. 
I don't know what to do, how to go around this issue. 

hope u guys can help me .

Thanks

**Comment by rezasoniquete** [comment]
Hi Thanks, Please find attached the file. I just saw also the shape layer (Play.) looks like a png image. 
[SSR-Logo animation.aep.zip](https://github.com/airbnb/lottie-web/files/2075504/SSR-Logo.animation.aep.zip)

**Comment by bodymovin** [comment]
Hi, the html renderer relies on measuring shape layers in order to adjust the container.
Unfortunately, strokes don't return width at all so size is 0.
If you replace the stroke with a rectangle of 1 px width, it should work fine.
