### ISSUE TITLE
Playing multiple segments when loop is disabled breaks animation

### ISSUE THREAD

**Issue by chrigi** [airbnb/lottie-web#1084]
lottie-web Version: 5.1.15
Browser: Chrome 66

Codepen: https://codepen.io/anon/pen/OEXqGN

When I start an animation with:
`
var animData = {
  container: container,
  renderer: 'svg',
  loop: false,
  autoplay: false,
  animationData: data
};
`

and then play the first segment like so:
`
anim.addEventListener('DOMLoaded',function () {
  anim.playSegments([[0,130]], true);
});
`

It will correctly play the first segment and then pause. When I then later (timeout, click) try to run the next parts as follows:
`
anim.playSegments([[131,200],[201,224]], true);
`

It will run the first new segment [131,200] but will break on the second segment and just display the last frame.

It seems to work just fine on 4.13.0 (from the cdn)

**Comment by bodymovin** [comment]
found the issue.
It'll be fixed on the next deploy.

**Comment by ivanjeremic** [comment]
What are multiple sequences for when the animation does't stop in between them? `anim.playSegments([[131,200],[201,224]], true);` What I want is to play first array then after second click play second array how would I do that?
