### ISSUE TITLE
The SVG and canvas players don't render beveled line joins correctly

### ISSUE THREAD

**Issue by karip** [airbnb/lottie-web#1085]
Beveled line joins are not rendered correctly by the SVG and canvas players. This json file is drawn without beveled corners: [join-bevel.json.zip](https://github.com/airbnb/lottie-web/files/2079948/join-bevel.json.zip)

Here's a screenshot of the SVG player:

![join-bevel-web](https://user-images.githubusercontent.com/6185066/41093437-f71df552-6a53-11e8-8d93-2b04285fd0fd.png)

Below is a screenshot of the Lottie Mac Viewer from lottie-ios, which renders the beveled corners correctly.

![join-bevel-mac](https://user-images.githubusercontent.com/6185066/41093469-1770b150-6a54-11e8-82d5-545afe2c2dbd.png)

Changing the line below to 'bevel' fixes the issue, but I don't how changing that code affects other parts of the renderer.

https://github.com/airbnb/lottie-web/blob/0491cc0899a8f503fe4ab2eaef05fe4e1b52ac2e/player/js/elements/ShapeElement.js#L42

Here's a link to the SVG stroke-linejoin property and its values: https://www.w3.org/TR/SVG11/painting.html#StrokeLinejoinProperty

**Comment by bodymovin** [comment]
Thanks for looking into it!
I'll upload the fix on the next deploy..
