### ISSUE TITLE
I am having trouble targeting the JSON file with Bodymovin

### ISSUE THREAD

**Issue by CarelessCourage** [airbnb/lottie-web#1088]
Hey, I am new to bodymovin. I am having trouble putting the outputted JSON file onto the webpage. 

Currently I have this set up: 

```javascript
var animation = bodymovin.loadAnimation({
    container: document.getElementById('bm'),
    renderer: 'svg',
    loop: true,
    autoplay: false,
    path: 'logo.json'
  })
```

And the logo.json file is stored right next to the main.js file, that the above code is in (attached image of my file structure). I keep getting this error: 

    "Unexpected token < in JSON at position 0". 

Which, I guess that means that it is receiving HTML where it expects JSON. Problem is that I have already checked the JSON file and it's definitely SVG data. In addition, I get the same error no matter where I put the JSON file - even if I delete it I get the same error which leads me to believe that the path that I have set up is not looking in the right place. But I have no idea how to make it look in the right place and I can't find any information on it either. 

In addition, it works perfectly well when I give it a URL path to a JSON file. like this: 

    path: 'https://labs.nearpod.com/bodymovin/demo/pixi/bm_pixi.json' 

So I know that everything else is fine. It just can't figure out how to target any specific JSON files stored in my project folders. 

Everyone seems to tell me to write the path the way that I have but it's not working for me. Notably, I am using Vue.js and when I look into the network tab in the sources in the inspect view in the browser I can see that there is a data.json file with some HTML inside it hosted up, maybe its targeting that file somehow? But the path name I wrote is called logo.json so I don't know why bodymovin would be looking into that JSON file anyway. 

Can anyone figure this out? Is the above path targeting the file correctly? 

![screenshot 123](https://user-images.githubusercontent.com/12764398/41207577-bfe4aaa0-6d18-11e8-8309-943e99f7b10c.png)
![screenshot 124](https://user-images.githubusercontent.com/12764398/41207668-ec3ead20-6d19-11e8-84ea-c054498a5297.png)
![screenshot 125](https://user-images.githubusercontent.com/12764398/41207831-77dc7022-6d1c-11e8-939b-fd1528424732.png)

**Comment by bodymovin** [comment]
Hi, if you can share a link with the implementation it will be easier to debug.
My guess is that you should put the logo.json at the same level than the index.html, not the js file.

**Comment by CarelessCourage** [comment]
Thanks for the reply. 

I already tried to put the JSON file in the same level as the index.html file but I got the same result(Tried it again just now just to recheck and it still does not work). 

I am pretty new to all of this, how do I give you a link with the implementation? 

The project is still in development so I don't have it hosted anywhere. It's all in my local environment at the moment. Is there a service that allows me to temporarily share the current implementation with you? Sorry if thats a dumb question, lol.

**Comment by CarelessCourage** [comment]
I set it up in codepen using some sort of codepen beta service that allows you to set up a file structure. But I have not figured out how to include Vue in a practical way. However, this code runs as I want it to which further suggests that my problem is specific to the way VueJs sets things up. 

https://codepen.io/samuel-mork-bednarz/project/editor/DadLYP

**Comment by CarelessCourage** [comment]
Sure thing. Here's the screenshot: 

![screenshot 128](https://user-images.githubusercontent.com/12764398/41283955-3dad13bc-6e38-11e8-8ec2-9522dc96c7d3.png)

**Comment by CarelessCourage** [comment]
Here's the response it gets from logo.json. This is clearly HTML, but thats not the code thats in the actual logo.json file. I don't know why it puts that code inside logo.json. Its the same code that I found inside the data.json file that Vue serves up in the browser. In my project files it matches the code in the index.html file. 

So, it seems like vue presents the index.html file as a data.json file in the browser, and then, for some reason, my JSON files inside the project turn into the data.json file in the browser, which is really the index.html file in the project. 


![screenshot 130](https://user-images.githubusercontent.com/12764398/41284259-1066412a-6e39-11e8-9994-bbd121d3a58a.png)

**Comment by bodymovin** [comment]
Depending on how your server is configured, when it doesn't find a file it defaults to the root, so that's probably the reason why it's returning the index.html content.
What are you using as your web server?

**Comment by CarelessCourage** [comment]
I am just using npm run dev

**Comment by bodymovin** [comment]
can you share your package.json?

**Comment by CarelessCourage** [comment]
Here you go, 

{
  "name": "alexandria",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "Samuel M. Bednarz <samuelmorkbednarz@gmail.com>",
  "private": true,
  "scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "unit": "jest --config test/unit/jest.conf.js --coverage",
    "test": "npm run unit",
    "lint": "eslint --ext .js,.vue src test/unit",
    "build": "node build/build.js"
  },
  "dependencies": {
    "bodymovin": "^4.13.0",
    "firebase": "^5.0.4",
    "slugify": "^1.3.0",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^8.2.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-jest": "^21.0.2",
    "babel-loader": "^7.1.1",
    "babel-plugin-dynamic-import-node": "^1.2.0",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eslint": "^4.15.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.7.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.2.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "jest": "^22.0.4",
    "jest-serializer-vue": "^0.3.0",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-jest": "^1.0.2",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 6.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}

**Comment by bodymovin** [comment]
Ok, since you're using webpack and webpack-dev-server, you probably need to use a plugin that copies all the static external files to the final build destination.
check something like "CopyWebpackPlugin"

**Comment by CarelessCourage** [comment]
Alright, thanks. I'll look into that
