### ISSUE TITLE
[Feature Request] Path Point Access / External Data

### ISSUE THREAD

**Issue by edwardchanjw** [airbnb/lottie-web#1091]
Seem great for Application usage to bridge developer and designer.

Youtube link for the feature in After Effect: [Path Point Access](https://www.youtube.com/watch?v=HMcqUEnOYr0)

**Comment by bodymovin** [comment]
Hi, this is supported by the player.
What feature are you thinking of specifically to bridge dev and designer?

**Comment by edwardchanjw** [comment]
It sound great. 
What categories it is under? I guess it under expression right? But we don't have player category in [features list](http://airbnb.io/lottie/supported-features.html)

I would thinking it would be great for Data Visualization.
It would be great if able to trigger other animation on other layer/other animations loaded in page when the graph/chart on bottom and, top range to highlight, or even fireworks if the data in peak.
I am actually haven test with bodymovin, i am no sure any existing API already able to done this, basically would like to see if possible to work with chart designed and exported in bodymovin, then depend on dynamic data, then able display chart with data. and to trigger animation in other layer, other file for animation control.

**Comment by kudanai** [comment]
Hello! Since this issue has been stale for quite a while, I'm going to close it. Please re-open or file a new one if necessary if relevant.
