### ISSUE TITLE
Ae to svg not work

### ISSUE THREAD

**Issue by omaga3** [airbnb/lottie-web#1092]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by omaga3** [comment]
I tried many times, but it just cannot work.
I have no idea.

I use inspect to check and it shows as below:
lottie.js:3 Failed to load file:///Users/Downloads/ani/js/data.json: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

Can anyone help me to check?
[ani.zip](https://github.com/airbnb/lottie-web/files/2096068/ani.zip)

Even all the demo I downloaded from official website cannot work for me.

But only when the export named demo.html works.......

**Comment by bodymovin** [comment]
Hi, you need to use a web server to load json files locally.

**Comment by omaga3** [comment]
@bodymovin 
can you tell me how to do that????

**Comment by bodymovin** [comment]
I don't know how familiar you are with web dev, but you can take a look at xampp to start

**Comment by jaredstanley** [comment]
@omaga3 this isn't a lottie-specific problem, this is just webserver stuff. look up tutorials on how to develop locally. Here's an example: https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server

**Comment by omaga3** [comment]
how can I just work it directly on my computer?
any simple way to solve it?

**Comment by bodymovin** [comment]
@omaga3 not sure how much I can help you if you're not familiar with web dev.
Have you looked at xampp? You can try installing it and follow some simple tutorials.

**Comment by omaga3** [comment]
@igor-nikolic thanks a lot! it is useful to me!!!
Originally, I tried to code ...JQuery to load JSON locally, but it might difficult to me.
