### ISSUE TITLE
exporting dynamic text with custom font

### ISSUE THREAD

**Issue by samiam2017** [airbnb/lottie-web#1093]
Attempting to output a determinate progress bar with a dynamic text counter of 0%->100%

goal is to have something that works for iOS and Android, but currently it's not even working for demo test.
 
After Effects Version 15.1.1
Bodymovin Version 5.1.10

I build the animated text using two different techniques for testing neither seems to work:

1.  the Numbers Effect on a shape layer

2. an expression on a text layer

When I export as Glyphs all of the animation plays except text counter just flashes between 0 and 100 rather than playing the sequence. 

When I export without Glyph I get the dialog box for the font families, css class, font path, font family, font weight, font style. 

I'm not sure what to do here. 

Not sure if I supposed to select None (since I have a custom font) or what I'm supposed to put in for font path. I also have multiple instances of the font in different sizes how do I know that everything will be output correctly. What if I wanted to output 2 different font styles?

Regardless when I render it out using this method I get a blank screen, I don't even get the progress bar loading in this instance so I'm not sure what to do.

Any help would be appreciated.

**Comment by bodymovin** [comment]
Hi, iOS and Android don't support effects or expressions so probably this two solutions won't work.
Regarding web, if you export glyphs, you need to provide every char that is going to get rendered.
You can use a separate text layer with all numbers for example.
If you export as text, you can provide the font yourself by loading it to the page, in that case filling the classname should be fine.
Or you can provide a path to load the font, and the player will load it before rendering.
Depending on what you need, you should fill those fields.
If you have more than one font, you'll get one form per font.
Regarding font size, it gets rescaled.

**Comment by samiam2017** [comment]
Thank you Hernan, for iOS and Android I ended up just manually doing the countdown (1 layer for each character (was something like 80 layers to sequence)) a bit laborious but seems to be working. If there are any better work arounds please share.

**Comment by bodymovin** [comment]
Probably not, text is not well supported in ios and android yet and expression either.

**Comment by samiam2017** [comment]
thank you again for your help!
