### ISSUE TITLE
Pulling my animation into a website

### ISSUE THREAD

**Issue by tommytime123** [airbnb/lottie-web#1094]
Hi..

I've used Body Movin to export my animation and now I'm trying to pull this into my Wordpress website, DIVI theme to be specific.

They have a code *module* where you can cut & paste .js but when I do this the animation is over-powering the whole WP theme and filling the screen.. Are there some specific settings I can possibly over-ride to keep this from happening?

**Example link here:**  
http://am1.creelit.com/test/

**.js code by itself:** 
https://www.dropbox.com/s/9nj11frb2j5yiie/animation.js?dl=0

Thank you!

T

Wordpress / DIVI Theme
Mac OS
AE CC 2018

**Comment by bodymovin** [comment]
Hi, can you try adding an element with class "bodymovin" or "lottie" to your page?

**Comment by tommytime123** [comment]
That did something! -- but now its too small..!!  :)   Is there something in the .js that might be constraining full-width?    

You can see the animation on the webpage here: http://am1.creelit.com/
Scroll down to the 3rd section where it says "Launch an entire marketing campaign in less than 24 hours!".

Your help is really appreciated!

T

**Comment by tommytime123** [comment]
Great.. one last question for ya ---   Is there code in the .js that might be preventing the animation from looping?   It was looping fine on the demo.html preview... 

Thanks so much!

**Comment by bodymovin** [comment]
add an attribute data-anim-loop="true" in your html element
