### ISSUE TITLE
Export frame-range doesn't seem to change .json data filesize

### ISSUE THREAD

**Issue by floq-design** [airbnb/lottie-web#1097]
**Tell us about your environment**
MacOS 10.13.5

* **Browser and Browser Version:**
Chrome
* **After Effects Version:**
15.1.1

**What did you do? Please explain the steps you took before you encountered the problem.**
Changed the Composition **Start Frame / Duration** settings to restrict frame-range.

**What did you expect to happen?**
Expected output data to be reduced due to less keyframe data.

**What actually happened? Please include as much _relevant_ detail as possible.**
No filesize change to `data.json`

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by floq-design** [comment]
Additions:
- actually - setting frame-range _**does**_ work - perhaps not as expected. Apologies for not testing.

As the file-size isn't changing - despite what the composition Start/Duration settings are - this implies all keyframes are being exported?

**Comment by bodymovin** [comment]
Yes, all composition gets exported.
There are two reasons for that.
One, it's not easy to break an animation in the middle.
You can update the workspace programatically with javascript to render different parts of the animation.

**Comment by floq-design** [comment]
Good points to know.

I've gone back to AfterEffects and deleted the unwanted frames which has reduced `data.json` filesize considerably.

New to bodymovin api - `playSegments` is just what I needed.

Cheers
