### ISSUE TITLE
Trying to play and pause a precomp

### ISSUE THREAD

**Issue by Mar-jon** [airbnb/lottie-web#1098]
Hi,

Is it possible to pause a precomp on load and play it when the parent is clicked?
I know how the click part works.

What I want to achieve:
I have a moving ball (animation 1). And when the ball is clicked a text will pop up and hoover above the ball (animation 2). But I want the text to follow the position of the ball. And I want the ball to loop at all times, no jumps after clicking.
I know how to get the animation (with text pop up and following ball) to work in After Effects.
But can I it be made interactive?

Thanks in advance!

**Comment by bodymovin** [comment]
Hi, unfortunately it's not easy.
You can play around using the time remaping feature of AE and editing the value dynamically.
