### ISSUE TITLE
Gradient Stoke + Trim path

### ISSUE THREAD

**Issue by macZielinski** [airbnb/lottie-web#1100]
Dear Lottie Team,

Windows 10x64 PL  + AE CC2018

I have created a project  that contains circle with Trim Path and Gradient Stroke (Radial)

I wanted to gain effect of progress bar, that has multiple colors (in this case 3).

I have lost first color in grandient graph, second one was very transparent, and circle had last color from gradient graph in the animation.
Second problem is, that results in demo.html and in the bodymovin (in AE) looks OK. Problems appear in the Lottie Viewer and are similar in our application.
I have tryed to create 3 obects with transparent objects, with gradients that contains only one of 3 chosen colors. These objets intermigle each other to get fluent color change. I've got flickering effects.

If I don't use Trim Path Obect is OK.

Prj file:
https://drive.google.com/file/d/1I72ciulCsNjZVYFop2Bsb7LwnD3LF9v-/view?usp=sharing
Prj View:
![test_3_colors_stroke_gradient](https://user-images.githubusercontent.com/40344925/41540717-08ae8cf8-7311-11e8-9abb-e6cdafc95829.JPG)

Thank You for Your help
Maciej Zielinski
Codivia Team

**Comment by bodymovin** [comment]
Hi, indeed there are small discrepancies between the way AE renders gradients and browsers render them.
Also, Chrome has some artifacts when Highlight Length = 100%
If you use Highlight Length at a maximum of 99% it should look like the .aep project.

**Comment by macZielinski** [comment]
Thanks for Your help.

I had to use 3 path with trim path. Terrible effect is in lottie viewer. Gradient moves, flickers .... 
Below I give You reproduced problem in json file, html and project file:

https://drive.google.com/file/d/1Px2AOLDJWvaDdgJ7Ui79Z-gkWiGWUCa1/view?usp=sharing

Thank You for Your help
Maciej Zielinski
Codivia Team

**Comment by bodymovin** [comment]
@macZielinski what lottie viewer are you using? the android/ios version or the one from the extension?

**Comment by macZielinski** [comment]
Lottie viewer on Android. Aplication that uses animation - Android.

**Comment by bodymovin** [comment]
I see, can you post the issue on the lottie-android repo?
https://github.com/airbnb/lottie-android

**Comment by jwjoeywalsh** [comment]
Anyone figure out to the gradient stroke not showing in Lottie? I am having the same issue. My project is saved.

**Comment by bodymovin** [comment]
@jwjoeywalsh can you share the .aep?

**Comment by jwjoeywalsh** [comment]
> @jwjoeywalsh can you share the .aep?


[LottieAnimations.aep.zip](https://github.com/airbnb/lottie-web/files/3444699/LottieAnimations.aep.zip)


The composition that is not working is titled "Home Icon". The one called HomeIconOutlined isthe one that is not a stroke and that one works... but i need it to be a gradient stroke it order to animate with trim paths
