### ISSUE TITLE
Multiple SVG Animation hover effects

### ISSUE THREAD

**Issue by HowellDesigned** [airbnb/lottie-web#1101]
I am working in HTML/CSS locally.
Using Chrome Version 67.0.3396.87 (Official Build) (64-bit)
After Effects CC 2018 (I don't think AE is the problem)
I am experimenting with SVG Animations on rollover/hover.

I expected both my of my icons to animate separately upon rollover, but I believe my javascript is somehow cancelling itself out for the second animation. After adding my second animation, it now activates when rolling over both icons instead of just one. I know very little javascript and rely on copy pasting other people's code, so I am not too surprised I screwed this up.

Any help would be great, thank you!
[SVG_Sandbox.zip](https://github.com/airbnb/lottie-web/files/2111779/SVG_Sandbox.zip)

**Comment by bodymovin** [comment]
Hi, your variable "animation" is targetting the second animation because both instances have the same name.
You can name each animation differently ("animation1" and "animation2") and it should work fine
