### ISSUE TITLE
export from Illustrator: .ai converted into low quality (pixelized)

### ISSUE THREAD

**Issue by clementfalchier** [airbnb/lottie-web#1104]
Hi,

First of all thanks a lot for this amazing tool/solution.
I have an issue related to the quality of my assets.

When I'm exported my .svg (from Sketch) into .ai from Illustration it seems I lost in quality and my assets are pixelized when I imported in After Effect.

I try to follow the solution provided by gregoryalthoff here: https://github.com/airbnb/lottie-web/issues/589 but it's not working.

PS: when I'm opening my .ai file with Illustrator it's ok.

Thanks by advance.

**Comment by bodymovin** [comment]
Hi, where are you losing quality? when viewing in AE or after exporting with bodymovin?

**Comment by clementfalchier** [comment]
Hi, viewing in AE then the final export of my animation is not perfect (pixelized) 
![screen shot 2018-06-19 at 16 47 31](https://user-images.githubusercontent.com/8928826/41604863-80ae7d4c-73e0-11e8-8c04-4ee9bd2cdd41.png)

**Comment by bodymovin** [comment]
can you share the .aep?

**Comment by clementfalchier** [comment]
May I send you the .aep by email?

**Comment by bodymovin** [comment]
sure
hernantorrisi[at]gmail.com

**Comment by clementfalchier** [comment]
done :)

**Comment by bodymovin** [comment]
Hi, I just checked the animation and it doesn't seem to be pixelated.
It might look like so if your zoom in After Effects is over 100%, but if you export the animation or scale your layers, for example layer "Pro 3 Outlines", you'll see they are fine.

**Comment by clementfalchier** [comment]
Perfect, thanks a lot :)
