### ISSUE TITLE
Poor rendering performance after $.animate scrollTop

### ISSUE THREAD

**Issue by phmasek** [airbnb/lottie-web#1105]
**Tell us about your environment**

* **Browser and Browser Version:** Google Chrome Mac OS Version 67.0.3396.87
* **After Effects Version:** After Effects CC 2018 version 15.1.1

**What did you do? Please explain the steps you took before you encountered the problem.**
Loaded animation using ajax using this code:

```
$.ajax({
	url: <PATH TO .JSON>,
	success: function(data) {
		var anim = lottie.loadAnimation({
			container: $('.svg-animation-container').get(0),
			renderer: 'svg',
			loop: true,
			autoplay: true,
			speed: 1,
			animationData: JSON.parse(data)
		});
		anim.addEventListener('loaded_images', function() {
			$(val).find('img.img-fluid').remove();
			$(val).find('svg').show();
		});
	}
});
```

After loading the animation and let it run (smoothly) I press an anchor link which triggers this code:

```
$('a[href^="#"]').on('click', function(e) {
	e.preventDefault();
	if (!$(this).hasClass('collapse-link')) {
		var $linkedElement = $($(this).attr('href'));
		var top = $linkedElement.position().top + $('header').innerHeight();
		$('#s4-workspace').animate({
			scrollTop: top
		}, 600);
	}
});
```

**What did you expect to happen?**

Scroll back up after triggering $.animate scrollTop and having the animation run smoothly.

**What actually happened? Please include as much _relevant_ detail as possible.**

When scrolling back up the loaded animation is rendering very poorly. It is giving me roughly 2fps according to Chrome Performance check and spending a lot of resources painting.

**Please provide a download link to the After Effects file that demonstrates the problem.**

Nothing to do with After Effects.

**Comment by bodymovin** [comment]
Hi, can you share a link with the implementation?

**Comment by phmasek** [comment]
https://gemalto.biometrics.melkercompany.se/
User: lottie
Pass: rules

I've noticed that the performance drops occur in long composition layer events. It also seems as if it is not specifically caused by the `.animate` function.

**Comment by phmasek** [comment]
I found that the issue was in the animation created in AE. There was a lot of small vector shapes to shape a jagged edge around three circles (ca 150 of them per circle). All these had to be repainted when the animation moved which caused the bad performance. I decided to remove these and clean up the project and the animation is running smoothly now.
