### ISSUE TITLE
Bodymovin - Rotation issue when parenting layers

### ISSUE THREAD

**Issue by alsegra** [airbnb/lottie-web#1108]
Hi, guys, I'm trying to parent the bamboo layer (which already has the rotation keyframed) to the wrist layer so it follows the position of it. In after effects, the bamboo starts and ends straight which is the result I need, but when I render the animation with Bodymovin and open it in Chrome, the bamboo starts and end rotated, specifically: 150,5º.

* **Browser and Browser Version:**
Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)
* **After Effects Version:**
15.1.1 (Build 12)

**What did you do? Please explain the steps you took before you encountered the problem.**
I parented the Bamboo layer which already had the rotation keyframed to the New Left arm::Wrist layer and it seems to be influencing the rotation for some reason.

**What did you expect to happen?**
The bamboo layer should follow the Wrist (because it's parented to it) without changes in the rotation.

**Please provide a download link to the After Effects file that demonstrates the problem.**
[Bamboo.aep.zip](https://github.com/airbnb/lottie-web/files/2124138/Bamboo.aep.zip)

Thank you so much in advance!

**Comment by bodymovin** [comment]
Hi, there was an issue with the linear method used by expressions.
I've fixed it and updated the players.
Thanks for reporting!

**Comment by alsegra** [comment]
Great, thank you for your quick response! :)
