### ISSUE TITLE
Using shapes as parented alpha channels are ignored

### ISSUE THREAD

**Issue by JamesWB98** [airbnb/lottie-web#1109]
Hi there,

I have a composition that uses many alpha channels of shapes that are parented. When exported in bodymovin

Have attach my ae file, thanks in advance!!

James
[Bird.aep.zip](https://github.com/airbnb/lottie-web/files/2125455/Bird.aep.zip)

**Comment by bodymovin** [comment]
Hi, unfortunately track matte masks and 3d don' t work together
