### ISSUE TITLE
loopComplete & complete is triggered immediately when direction is -1

### ISSUE THREAD

**Issue by JasonHHQ** [airbnb/lottie-web#1115]
**environment:**

* **lottie-web:** 5.1.16
* **Browser and Browser Version:**  chrome  67.0.3396.87

**What did you do? Please explain the steps you took before you encountered the problem.**
I create a animation by useing `loadAnimation`, and then `setDirection(-1)` . The code is like this:
```
const anim = lottie.loadAnimation(currentOption);
// console.log('anim is created at :', +new Date());
anim.setDirection(-1);
const complete = (a) => {
  // console.log('anim is loopComplete at :', +new Date());
  anim.destroy();
  next();
}
if (currentOption.loop) {
  anim.addEventListener('loopComplete', complete);
} else {
  anim.addEventListener('complete', complete);
}
```
and the `loopComplete` or `complete` event was triggered immediately.

**What did you expect to happen?**
I hope `loopComplete` or `complete` event was triggered after the animation is done, just as the behavior when direction is 1.

**What actually happened? Please include as much _relevant_ detail as possible.**

<img width="370" alt="2018-06-25 18 42 02" src="https://user-images.githubusercontent.com/16536898/41845855-82186802-78a7-11e8-99d0-eaf957da9217.png">

<img width="747" alt="2018-06-25 18 38 13" src="https://user-images.githubusercontent.com/16536898/41845819-600e76ca-78a7-11e8-8c4b-b0e1c037b155.png">

**Please provide a download link to the After Effects file that demonstrates the problem.**
[https://www.lottiefiles.com/download/1370](https://www.lottiefiles.com/download/1370)

**Comment by bodymovin** [comment]
Hi, you're right, when `loop` is set to false the complete event should be triggered after a cycle has been completed.
Regarding looping, it is not so straightforward when playing backwards, but I've done a workaround that should work for most cases.
I'll upload the fix on the next deploy.

**Comment by voyceatlas** [comment]
Complete does not wor when playing in reverse to the start.
