### ISSUE TITLE
 Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by konradcieslukowski** [airbnb/lottie-web#1117]
Hi, can you take a look into my aep file, please?
https://www.filemail.com/d/osaizfzujuerwdd

I have an error:
<img width="605" alt="zrzut ekranu 2018-06-25 o 16 50 36" src="https://user-images.githubusercontent.com/16174106/41857539-101d1acc-7898-11e8-884b-2dcbe5a59383.png">

None of previously mentioned solutions helped.

**Comment by bodymovin** [comment]
Hi, there seem to be some missing compositions in your project:
"Element Settings v2" for example

**Comment by konradcieslukowski** [comment]
let me check

**Comment by konradcieslukowski** [comment]
It seems above composition is imported, but animation  is  still not working. Any other idea why? Maybe you see there a feature which is not supported by lottie ?

**Comment by bodymovin** [comment]
Closing issue. Reopen if necessary.
