### ISSUE TITLE
Bug with gradient on export

### ISSUE THREAD

**Issue by vmoureu** [airbnb/lottie-web#1118]
Hello,
I have some trouble with the export of my work on AE. All my gradients are in black and white, sometimes the shape are strange too. I tried to uninstall my french Version of AE and install in English (North America) but that didn't work. 

I used After Effect 2018 15.1.1 on a mac.
[After Effect File](https://drive.google.com/open?id=10UcP8_DLNV4RCHwEWeU9mTKSIH2FedzO)

Thanks for your help.

<img width="2048" alt="capture d ecran 2018-06-26 a 13 56 15" src="https://user-images.githubusercontent.com/40568705/41910318-95c2b50e-7949-11e8-8dca-104e11670bb0.png">
<img width="899" alt="capture d ecran 2018-06-26 a 14 04 12" src="https://user-images.githubusercontent.com/40568705/41910410-d734e930-7949-11e8-9876-92a8481bd817.png">

**Comment by bodymovin** [comment]
Hi, unfortunately drop shadows on layer styles and merge paths are not supported.
Regarding gradients, I think it's related to having some characters in your contents with accents.
This breaks when trying to retrieve gradient data from the .aep file.
I exported it here and gradients export ok.

**Comment by vmoureu** [comment]
Thanks, that works without the accents and without the merge paths !
