### ISSUE TITLE
Loop not working even though autoplay & loop are set to true

### ISSUE THREAD

**Issue by brmi** [airbnb/lottie-web#1119]
**Tell us about your environment**
Mac OS High Sierra 10.13.4
Using lottie_light.min.js

* **Browser and Browser Version:**
Google Chrome Version 67.0.3396.87
* **After Effects Version:**
Unknown, get this from a designer at another company.

**What did you do? Please explain the steps you took before you encountered the problem.**
import * as lottie from 'lottie-web/build/player/lottie_light.min.js';

let logoAnimation = lottie.loadAnimation({
  container: document.querySelector('.lottie-logo'), 
  renderer: 'svg',
  loop: true,
  autoplay: true,
  assetsPath: '/images/animation_images/',
  path: '/images/splash_logo.json'
});

**What did you expect to happen?**
The animation to loop infinitely. 

**What actually happened? Please include as much _relevant_ detail as possible.**
The animation only happens once on first load. If the animation is already loaded or cached, it will not play at all. I have to use hard refresh for it to play. It also does not loop at all.

I thought it would loop with this alone, but maybe I need to use the play() method? I have tried this as such
lottie.play(logoAnimation);
but maybe I am using it wrong?

Thanks so much!
Desiree

**Please provide a download link to the After Effects file that demonstrates the problem.**
Don't have it at the moment.

**Comment by bodymovin** [comment]
Hi, it should work correctly
Can you post a reduced example with the issue so I can take a look?

**Comment by brmi** [comment]
@bodymovin What do you mean by reduced example? o:

**Comment by bodymovin** [comment]
do you have a link online to check it out?

**Comment by brmi** [comment]
hmmm, well it's a project that is not released yet so i cannot post it online. do you have any pointers or areas you think i should check?

**Comment by bodymovin** [comment]
not sure what could be happening.
Can you share the animation?

**Comment by kudanai** [comment]
Hey there. As this issue has been stale for some time, I'm closing it. Please re-open it if you feel it still relevant or open a new issue.
