### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by 7oot** [airbnb/lottie-web#1120]
**Environment:**
A Vue.js SPA. Bundled with Webpack.

**Browser and Browser Version:**
Global problem

**After Effects Version:**
CC 2018, Version 15.1.1 (Build 12)

**What did you do? Please explain the steps you took before you encountered the problem.**
- The app contains a somewhat complex intro animation (which uses expressions, if that's a factor) in addition to a few small animations
- While developing, everything runs smoothly and I see no errors in the console.
- However, in the production version (`webpack -p --env=production`) where the JS bundle is minified, the following happens:
    - An error appears twice in the console (stack trace below).
    - Then the complex intro animation runs till about half way through, then stops.
    - The other smaller animations can NOT be played anymore.
- If I remove the intro animation and do a production build again, the errors disappear and the small animations run as expected.

**Error Stack Trace:**
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at length (bundle.js:39)
    at _expression_function (eval at initiateExpression (bundle.js:39), <anonymous>:15:10)
    at h.executeExpression (bundle.js:39)
    at h.o [as getValue] (bundle.js:39)
    at t.iterateDynamicProperties (bundle.js:31)
    at t.getValue (bundle.js:39)
    at SVGCompElement.prepareProperties (bundle.js:39)
    at SVGCompElement.ICompElement.prepareFrame (bundle.js:39)
    at SVGCompElement.ICompElement.prepareFrame (bundle.js:39)
    at SVGRenderer.renderFrame (bundle.js:39)
```

**Please provide a download link to the After Effects file that demonstrates the problem.**
http://www.db-n.com/lu/intro.json

**Comment by bodymovin** [comment]
Do you have a link where I can check where the issue comes from?
Have you tried excluding the lottie.js from the bundle and loading it separately. Not a real solution, but at least to identify if the problem comes from bundling the player.
Also, are you bundling the minified version or the full extended version?

**Comment by 7oot** [comment]
@bodymovin thank you for the quick response. 

- I'm bundling the full version. like I said, without compressing the bundle everything is fine.
- Everything works fine in the compressed bundle when I removed the lottie-web import, but I wouldn't go for that solution unless there was no other way.
- Tried changing the intro animation for the SVG to the canvas renderer and got similar errors from the canvas renderer.

can I e-mail you the files? I'm not supposed to post a public link to the unfinished product

**Comment by bodymovin** [comment]
sure
hernantorrisi[]gmail[]com

**Comment by 7oot** [comment]
Closing. 

The issue appears upon production bundling with `webpack -p` which internally uses the `uglifyjs-webpack-plugin`. For some reason an initial value in one of the loops is considered irrelevant and gets deleted, which is throwing the Lottie renderer off!

I tried changing the UglifyJS flags, but nothing resolved the issue, so I had no other option but to separate the Lottie player from my bundle and include a new script tag for it in my HTML.

Here are the latest 2 comments I got per e-mail from @bodymovin 

> Hi, I'm not sure what minifer you're using, but apparently it's converting this for loop:
> `var i,lenA=a.length;var retArr=[];for(i=0;i<lenA;i+=1){retArr[i]=-a[i];}return retArr;`
> to this:
> `for(var n,r=t.length,i=[];n<r;n+=1)i[n]=-t[n];`

> It's really strange that it is being minfied incorrectly.
> My guess is that it is related to having an eval invocation near that code, but I can't be sure.
> I can't think of anything better than loading the minified version separately.
> It might be better in the long run because you don't need to deploy that file every time, so users might have it cached even if you update your codebase.
