### ISSUE TITLE
animate properties using Js

### ISSUE THREAD

**Issue by thahir007cp** [airbnb/lottie-web#1123]
Hi,

How can I manipulate some properties using javascript? I saw a pen here https://codepen.io/ssanthos/pen/VbpwmY where we can move hand with mousemove event I have tried a simple shape to move here https://codepen.io/cpthahir/pen/OEBQwe. but it's not working. 

Could you please help. ?

Here is AEP AEP attached

[boxjson.aep.zip](https://github.com/airbnb/lottie-web/files/2145926/boxjson.aep.zip)

Thanks!

**Comment by thahir007cp** [comment]
@bodymovin could you please help?

**Comment by bodymovin** [comment]
Hi, I suggest that for updating animation properties you use the lottie api library.
https://github.com/bodymovin/lottie-api
If you have any questions about it, let me know.

**Comment by thahir007cp** [comment]
Thank you very much @bodymovin . You are just awesome .😍
