### ISSUE TITLE
Exporting assets to JSON failing.

### ISSUE THREAD

**Issue by fingerpuk** [airbnb/lottie-web#1124]
Running on Adobe AEX CC 15.1.1 Build 12 on Mac OSX 10.13.15

Exporting assets into the JSON is failing. The JSON shows the assets but they render as the missing asset question mark icon. If I choose to render with the assets as PNG it works fine, and yesterday I got JSON only exporting working, but today it fails on the same AEX file.

Settings are:

<img width="727" alt="screen shot 2018-06-29 at 11 12 13" src="https://user-images.githubusercontent.com/6772532/42087180-5073a7d8-7b8d-11e8-81cb-35e2ef995420.png">

Start of the JSON showing included assets:

`{"v":"5.1.16","fr":24,"ip":0,"op":48,"w":800,"h":600,"nm":"Missed Payment Lottie","ddd":1,"assets":[{"id":"image_0","w":221,"h":221,"u":"","p":"data:image/png;base64,iVBORw0KGgoAAA...` etc

My workflow is to build shapes in Illustrator, release to layers and name them, import that .ai file as a composition, animate and export. I'm happy to share the .ai and .ae files if that would help?

Cheers.

**Comment by bodymovin** [comment]
hi, can you share the JSON file?
Also, are you using the latest player?

**Comment by fingerpuk** [comment]
[overLimit_2.json.zip](https://github.com/airbnb/lottie-web/files/2148968/overLimit_2.json.zip)

JSON attached. I'm using the latest version, downloaded yesterday. Thanks for the impressively fast response. :)

**Comment by bodymovin** [comment]
Hi, I just tried it and it seems to be working.
Do you have a link with the implementation that I can check?
By the way, I suggest that you convert your .ai layers to shapes in After effects, that way they won't be exported as pngs, but as vectors instead. They'll be much lighter and responsive.

**Comment by fingerpuk** [comment]
Sadly I can't share the implementation. I'll talk to the developers and see what they can share. I'll try the shape conversion now. Thanks for the help :)

**Comment by bodymovin** [comment]
Ok, my bet is still on an outdated lottie player :)
