### ISSUE TITLE
Incomplet (freeze) svg animation (html export)

### ISSUE THREAD

**Issue by Alexundo** [airbnb/lottie-web#1125]
**Tell us about your environment**
Windows 10

* **Browser and Browser Version:**
Chrome 67

* **After Effects Version:**
AE CC 2018 (version 15.1.1 build 12)

**What did you do? Please explain the steps you took before you encountered the problem.**
Imported from AI, used trim path and offset path for animation. I know there are issues with offset path but even without that I have the same issue.

**What did you expect to happen?**
The export should have rendered the whole animation.

**What actually happened? Please include as much _relevant_ detail as possible.**
In the Bodymovin player I see all the 80 frames but the html freezes after a few frames. I think it has something do to with trim path but I am not sure.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://we.tl/HLuAjS3foA

**Comment by bodymovin** [comment]
Hi
On layer "volum scris albastru/CRM pentru AE Outlines" > "Contents" > "Group 4", the path named "Path 2" has no nodes and it breaks.
I'll fix it on the next deploy, but for now, if you remove it, it should work.

**Comment by bodymovin** [comment]
There is also an issue on layer " fill grafic mare/CRM pentru AE Outlines" because Offset Paths are not supported by the player.

**Comment by Alexundo** [comment]
Removed that path and replaced Offset Paths with Stroke. Works like a charm, thanks a lot for the help. Great plugin, great job.
Have a nice day!
