### ISSUE TITLE
Is varying vertex count supported yet?

### ISSUE THREAD

**Issue by troyceratops** [airbnb/lottie-web#1126]
I am creating an animation that would be much easier to achieve if I could delete vertices throughout the animation.

I tried to export with Bodymovin and got an error :"Unable to execute script at line 245. undefined is not an object "

I've done a bit of research and wondering of this is still an issue? Thanks!

MacBook Pro 2017
After EffectsCC

[Logo transition folder.zip](https://github.com/airbnb/lottie-web/files/2160930/Logo.transition.folder.zip)

**Comment by bodymovin** [comment]
Hi, I've tried exporting the animation and it worked.
What version of the plugin are you using?

**Comment by bodymovin** [comment]
Hi this problem was related to exporting the standalone or demo files on version 5.1.19.
It's been fixed on version 5.1.20

**Comment by troyceratops** [comment]
Thanks @bodymovin! I just downloaded the plugin off Github, so I assume it is the latest, could you point me to the latest version?

**Comment by bodymovin** [comment]
can you download it again?
I did an updated yesterday

**Comment by troyceratops** [comment]
Got it working thx!
