### ISSUE TITLE
the Position Expression is not working 

### ISSUE THREAD

**Issue by teddymartadinata** [airbnb/lottie-web#1127]
**My AE Assets Contains 2 .ai File, and using only Position Expression with Opacity Keyframe on the other layer**

* **Browser and Browser Version: Chrome V 67.0.3396.99 (Official Build) (64-bit)**
* **After Effects Version: CC 2018**

**What did you do? Please explain the steps you took before you encountered the problem.**
Hi, i just exported this AE project into bodymovin format and already made html files to play it, but the animation not working as supposed to be like in AE (attached the AE project file)

**What did you expect to happen?**
The animation should works like bounce to the top and flippin as the AE Results

**What actually happened? Please include as much _relevant_ detail as possible.**
on my browser seems the logo not bouncing properly, and the spinning animations seems working fine 

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/open?id=1SXkGfYIq-NqkyfofQXveQoQqIYs5vQk4

**Comment by bodymovin** [comment]
Hi, I've found the issue. It's related to using `instanceof` for validating the array.
I'll have it fixed for the next deploy.

**Comment by bodymovin** [comment]
Hi this is fixed on version 5.1.20

**Comment by teddymartadinata** [comment]
hi, on the latest release, it seems the expression isn't working again.. can you please check it? thanks

**Comment by hananafif** [comment]
did you fix the issue?
