### ISSUE TITLE
Animations render inconsistently on chrome and firefox from original

### ISSUE THREAD

**Issue by mwelche** [airbnb/lottie-web#1128]
**Tell us about your environment**

mac and windows

* **Browser and Browser Version:**

Firefox 61.0 and Chrome 67.0.3 on 

* **After Effects Version:**

CC 51.1.1

**What did you do? Please explain the steps you took before you encountered the problem.**

We create after effects text style animations for the browser and incorporate expressions to sync text: size, position, alignment, etc., with background layers and stylistic elements.

**What did you expect to happen?**

The expectation is that the animation consistently renders the way it appears in the after effects file and most animated previews. We also expect text leading to be consistent on sequential renders.

**What actually happened? Please include as much _relevant_ detail as possible.**

The animations are inconsistently rendering on firefox, and also on a headless browser like slimerjs. Pausing on a specific point of the animation also seems to sometimes render incorrectly, for example a background shape layer will be incorrectly offset, but then correct itself when you play the animation.
On firefox we occasionally get renders that seem to have double the letter spacing than on the original composition or seen in chrome.

**Please provide a download link to the After Effects file that demonstrates the problem.**

I can send videos directly preferably via email.

thanks!

**Comment by bodymovin** [comment]
Hi, can you email me the exported json file?

**Comment by mwelche** [comment]
absolutely. thanks for the quick reply

**Comment by bodymovin** [comment]
Chrome renders text differently than other browsers because unfortunately they don't respect the letter spacing defined by the font file itself.
I've been discussing this with their team but for now I don't have an answer to this.
If you need them to look the same, it's probably better to export them as glyphs.
Regarding the background image, I'm not sure I follow what is not working.
