### ISSUE TITLE
Problem: Fill is outside the shape

### ISSUE THREAD

**Issue by Mikola35** [airbnb/lottie-web#1129]
Please help with this issue.

![image](https://user-images.githubusercontent.com/4017693/42277281-8421fe2a-7f9f-11e8-809f-67942e252415.png)

Resource files (AEP, AI, JSON):
[Boy.zip](https://github.com/airbnb/lottie-web/files/2163201/Boy.zip)

**Comment by Mikola35** [comment]
How I can do correct pathes? What rules I broke?

**Comment by bodymovin** [comment]
Hi, what version of bodymovin are you using?

**Comment by Mikola35** [comment]
@bodymovin, Hi

I use version 5.1.18

**Comment by bodymovin** [comment]
Can you try version 5.1.19?
It should be working there.

**Comment by Mikola35** [comment]
Yes. Now I tried new version and all works correctly. Thanks!

**Comment by bodymovin** [comment]
sure
