### ISSUE TITLE
Exporting "sz" & "ps" properties 

### ISSUE THREAD

**Issue by Abukodonosor** [airbnb/lottie-web#1130]
Hi, can anyone tell me  what i need to set in my .aep file to get json who have those properties ?

"s": {
                        "sz": [603.246704101563, 237.191314697266],
                        "ps": [-464.5400390625, -82.8349533081055],
                        "s": 51,
                        "f": "Lato-HeavyItalic",
                        "t": "text bot is static, pe",
                        "j": 2,
                        "tr": 0,
                        "lh": 61.1999969482422,
                        "ls": 0,
                        "fc": [0, 0, 0]
                    }

sz & ps are important !!

This is from text layer.
http://prntscr.com/k2iwds

**Comment by bodymovin** [comment]
Hi
After Effects has two different text layer types.
Point and Paragraph text.
https://helpx.adobe.com/after-effects/using/creating-editing-text-layers.html
For those properties, you need to create a Paragraph text.
