### ISSUE TITLE
render PNG but not SVG

### ISSUE THREAD

**Issue by omaga3** [airbnb/lottie-web#1132]
After I import my AI file into AE
then I render the PNG animation

Finally, I found that previous comment mention that should convert to vector in AE.

But my question is ..... that I already set all action in ai.file......
is this means that I should re-set again?
oh no!!!???

**Comment by omaga3** [comment]
finally...........it can export but got a lot of bug!!!

my composition is 1000x1000
but after convert to vector.......than I got a lot of bug
the image is not clear render and the animation got bug and can not work

**Comment by omaga3** [comment]
Finally, I found that should be click convert to vector in AE.
Due to at first, I did not do that , ....so it just render with PNG file.

But I draw a lot of vector from illustrator, then it is not very smooth
when displaying the animation in the script.

I really do not know why.

But it can display nicely when just in AE.....

2018-07-05 3:21 GMT+01:00 hernan <notifications@github.com>:

**Comment by bodymovin** [comment]
Can you share a link?
