### ISSUE TITLE
Rubberhose to Bodymovin - Paths not rendering correctly

### ISSUE THREAD

**Issue by MrLizer** [airbnb/lottie-web#1133]
Hey, so I have a character with Rubberhose arms and legs and for some reason non of them are rendering out as they should. The arms are missing the outer outline path and the legs are rendering very odd, maybe because of the tapering?

Using Rubberhose 2.08

Bodymovin 5.1.20

https://www.dropbox.com/home/Bodymovin?preview=Sam_02.aep

**Comment by bodymovin** [comment]
Hi, indeed rubberhose tapering is not supported by the player.

**Comment by MrLizer** [comment]
Ok but what about the arms?

**Comment by bodymovin** [comment]
I'll have to check it when I get home.
Have you added to export hidden and guided layers in the settings?

**Comment by MrLizer** [comment]
Yeah I have, its a bit odd. I am going to update the file with the tapered legs removed. 

Thanks for your help

**Comment by MrLizer** [comment]
https://www.dropbox.com/s/5enepecrfweplgm/Sam_03.aep?dl=0

Updated AE file

**Comment by MrLizer** [comment]
Evening, just wanted to check to see if you had the time to look at the issue?

Thanks

**Comment by bodymovin** [comment]
Hi, it's basically a similar issue, this effect and tapering both rely on AE's shape Offset Path.
That's what is not supported by the player yet.

**Comment by MrLizer** [comment]
there is actually no need to have offset paths on the outer arm stroke as I can just make the stroke thicker...not sure why that is there in the first place. But I still get an odd red path error

**Comment by bodymovin** [comment]
Yes, the red path is easy to fix.
Since you're exporting hidden layers, it's also including hidden fills and strokes.
There is a hidden Red Fill if you go to rightArm > Style > Outer > Fill
if you remove it, it should work fine.

**Comment by MrLizer** [comment]
<img width="373" alt="screen shot 2018-07-05 at 23 22 10" src="https://user-images.githubusercontent.com/25539820/42350886-521e7b22-80aa-11e8-9b6b-57c800bdbb1b.png">

**Comment by bodymovin** [comment]
Probably not in the short term, supporting offset paths (hence tapered strokes) is a very complicated task

**Comment by MrLizer** [comment]
Ok, well thanks for your prompt help, much appreciated as always.
