### ISSUE TITLE
lottie-web with AE bullet train effect

### ISSUE THREAD

**Issue by coingenexchange** [airbnb/lottie-web#1135]
Hi,

Just wondering if the library supports the bullet train effect?

**Comment by bodymovin** [comment]
Hi, no, unfortunately not many effects are supported at this time.

**Comment by zaynzafar** [comment]
@bodymovin Thanks, is there anything similar i can do with bodymovin to get close to the bullet train effect?

Thanks

**Comment by bodymovin** [comment]
probably not. Rasterized effects for now are not possible.

**Comment by zaynzafar** [comment]
@bodymovin If i export as glyphs then it would it work? I guess that defeats my idea of dynamically updating the text but would be useful to know

**Comment by bodymovin** [comment]
Not sure what effect you're talking about. If it's a text animator, it might work.
Can you share an .aep with an example?

**Comment by kudanai** [comment]
Hey there. As this issue has been stale for some time, I'm closing it. Please re-open it if you feel it still relevant or open a new issue.
