### ISSUE TITLE
The JSON file is incorrect when using gradient fill and gradient stroke at the same time

### ISSUE THREAD

**Issue by fanyinan** [airbnb/lottie-web#1140]
The color in gradient Fill layer is the same as the color in gradient stroke layer. But then should be different.
[gradientFillRule.aep.zip](https://github.com/airbnb/lottie-web/files/2179325/gradientFillRule.aep.zip)

**Comment by bodymovin** [comment]
Hi, the problem seems to be related to using the default black/white gradient.
I'll take a look at it when I can.
Meanwhile can you change the black value from #000000 to #000001 and see if it works?

**Comment by fanyinan** [comment]
Thank you for your reply. It works.By the way, bodymovin is not an open source, right?

**Comment by bodymovin** [comment]
yes, it is
https://github.com/bodymovin/bodymovin-extension

**Comment by fanyinan** [comment]
Thank you very much.
I'm implementing some functions of lottie with metal in iOS.
The code is most helpful. 
Thank you again.
