### ISSUE TITLE
problem render bodymovin/after effects

### ISSUE THREAD

**Issue by AndreaG91** [airbnb/lottie-web#1141]
bodymovin render my project wrong...the projrct is cut

![body](https://user-images.githubusercontent.com/41064309/42515320-cd48ccbc-845b-11e8-9633-a332c22bb853.PNG)

**Comment by bodymovin** [comment]
Hi, can you give some more info?

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
