### ISSUE TITLE
Keeping up with the latest versions

### ISSUE THREAD

**Issue by nickmadedesign** [airbnb/lottie-web#1143]
Hi @bodymovin ,

In the past I've installed via aescripts + aeplugins, and recently using the Creative Cloud Adobe Store. Each time I've downloaded the versions have been mismatched.

Is it possible to get the latest version up (5.1.20) on the Adobe store seen here?https://creative.adobe.com/addons/products/12557

If the aescripts + aeplugins is updated more consistently, I'll uninstall the Adobe CC route and rely on the other option from now on.

Thanks for the rad plugin!

**Comment by bodymovin** [comment]
Hi, usually aescripts + aeplugins is a couple of versions ahead until I deploy a new version to the creative cloud, but they are never too far apart between each other.

**Comment by nickmadedesign** [comment]
Thanks. I just jumped back over to the aescripts program to keep updated for now. Thank you again!
