### ISSUE TITLE
Font and text properties

### ISSUE THREAD

**Issue by igor-nikolic** [airbnb/lottie-web#1145]
Hi,
Can you explain me these properties in these pictures: 
![textproperty](https://user-images.githubusercontent.com/23365903/42628255-da50282c-85cf-11e8-8fb9-1c83addfa17e.png)
![fontproperty](https://user-images.githubusercontent.com/23365903/42628270-e7a2cd9a-85cf-11e8-8b16-66135de02b06.png)
Also when I put the URL of the google font in **fPath** I get the error _**illegal character**_ in the console.

**Comment by bodymovin** [comment]
Hi, can you share a link where you get that error?

**Comment by igor-nikolic** [comment]
Sorry, I didn't know what is this "origin" property for. I have to set it to 1 in order to use google fonts. 
Is there a posibility to add a line break to a text? I tried to "hardcode" it into JSON with **\r** and it works, but when I insert it from text field using script into JSON it renders as \r not as line break.

**Comment by bodymovin** [comment]
Yes, line breaks should work.
Try adding a line break from AE and see how it exports so you can reproduce it.
