### ISSUE TITLE
Uncaught TypeError: Cannot read property 'keyframes' of undefined

### ISSUE THREAD

**Issue by CelineThiry** [airbnb/lottie-web#1146]
Hi there !

I recently started to use your super cool bodymovin extension.  It worked well with a simple animation but I’ve got an error with a more complex animation… I've searched in the issues if someone else had the same bug as I encountered but found nothing.  Please find below, the explanation of the issues I encountered.

Hope you'll find what's going on. 
Thanks a lot in advance.

### Tell us about your environment
**Client/Server environment:**
WampServer 3.1.0 (64 bits)
**Browser and Browser Version:**  
Google Chrome Version 67.0.3396.99 (64 bits)
**After Effects Version:**
After Effects CC 2018 – Version 15.1.1 (Build 12)
**Bodymovin:**
Version 5.1.16

### What did you do? Please explain the steps you took before you encountered the problem.
1.	I create an animation in After Effect. (see link below for the AE composition DL link)
2.	I launched bodymovin extension in AE.
3.	I checked the composition I wanted to render and click the button render. It generates a data.json file that I save in a folder.
4.	I download the last version of lottie player with the button “get the player” in the bodymovin extension panel. I save it in the same folder as my json file, just next to it.
5.	I download the zipped repository on https://github.com/airbnb/lottie-web to get content of the player folder : index.html file + js folder.
6.	I paste the index.html in the same folder as the json and the js files.
7.	I paste the folder containing the data.json, index.html and lottie.js in a folder at the root of my WampServer (the WampServer is switch on).
8.	In the index.html file, I changed the path of the json file and removed the comment around the <script src="lottie.js"></script>
9.	I start Google Chrome browser and type http://localhost/nameofmyfolder. Nothing happens. I refresh the page. Nothing happens.
10.	I checked the console of Google Chrome and here is the error I get :
![error](https://user-images.githubusercontent.com/8962949/42681639-818eec50-8688-11e8-9de9-ae84ce68a525.PNG)

```
Uncaught TypeError: Cannot read property 'keyframes' of undefined
    at a.e [as getValue] (lottie.js:2)
    at SVGCompElement.prepareProperties (lottie.js:4)
    at SVGCompElement.ICompElement.prepareFrame (lottie.js:5)
    at SVGCompElement.ICompElement.prepareFrame (lottie.js:5)
    at SVGCompElement.ICompElement.prepareFrame (lottie.js:5)
    at SVGRenderer.renderFrame (lottie.js:4)
    at AnimationItem.renderFrame (lottie.js:5)
    at AnimationItem.gotoFrame (lottie.js:5)
    at AnimationItem.checkLoaded (lottie.js:5)
    at AnimationItem.completeData (lottie.js:5)
e @ lottie.js:2
prepareProperties @ lottie.js:4
ICompElement.prepareFrame @ lottie.js:5
ICompElement.prepareFrame @ lottie.js:5
ICompElement.prepareFrame @ lottie.js:5
SVGRenderer.renderFrame @ lottie.js:4
AnimationItem.renderFrame @ lottie.js:5
AnimationItem.gotoFrame @ lottie.js:5
AnimationItem.checkLoaded @ lottie.js:5
AnimationItem.completeData @ lottie.js:5
AnimationItem.waitForFontsLoaded @ lottie.js:5
AnimationItem.configAnimation @ lottie.js:5
a.onreadystatechange @ lottie.js:3
XMLHttpRequest.send (async)
e @ lottie.js:3
AnimationItem.setParams @ lottie.js:5
n @ lottie.js:5
loadAnimation @ lottie.js:1
(anonymous) @ (index):204e @ lottie.js:3
AnimationItem.setParams @ lottie.js:5
n @ lottie.js:5
loadAnimation @ lottie.js:1
(anonymous) @ (index):205
```

### What did you expect to happen?
I expect the animation to start, at least to preview the first frame.

### What actually happened? Please include as much _relevant_ detail as possible.
My page stays and remains blank, even after refreshing it. And I get this error in the console : 
```
lottie.js:2 Uncaught TypeError: Cannot read property 'keyframes' of undefined
    at a.e [as getValue] (lottie.js:2)
    at SVGCompElement.prepareProperties (lottie.js:4)
    at SVGCompElement.ICompElement.prepareFrame (lottie.js:5)
    at SVGCompElement.ICompElement.prepareFrame (lottie.js:5)
    at SVGCompElement.ICompElement.prepareFrame (lottie.js:5)
    at SVGRenderer.renderFrame (lottie.js:4)
    at AnimationItem.renderFrame (lottie.js:5)
    at AnimationItem.gotoFrame (lottie.js:5)
    at AnimationItem.checkLoaded (lottie.js:5)
    at AnimationItem.completeData (lottie.js:5)
e @ lottie.js:2
prepareProperties @ lottie.js:4
ICompElement.prepareFrame @ lottie.js:5
ICompElement.prepareFrame @ lottie.js:5
ICompElement.prepareFrame @ lottie.js:5
SVGRenderer.renderFrame @ lottie.js:4
AnimationItem.renderFrame @ lottie.js:5
AnimationItem.gotoFrame @ lottie.js:5
AnimationItem.checkLoaded @ lottie.js:5
AnimationItem.completeData @ lottie.js:5
AnimationItem.waitForFontsLoaded @ lottie.js:5
AnimationItem.configAnimation @ lottie.js:5
a.onreadystatechange @ lottie.js:3
XMLHttpRequest.send (async)
e @ lottie.js:3
AnimationItem.setParams @ lottie.js:5
n @ lottie.js:5
loadAnimation @ lottie.js:1
(anonymous) @ (index):204
```

### Please provide a download link to the After Effects file that demonstrates the problem.
**After Effect Animation**
https://drive.google.com/drive/folders/1aQyK2LKEyKj1JKBvsOMKgrybJAelIe4f?usp=sharing
**Bodymovin Render**
https://drive.google.com/drive/folders/1dTTZQJFmALrSokXf9ZOiQFYJntC1Rpbo?usp=sharing

**Comment by bodymovin** [comment]
Hi, by the end of day today, I'll upload a new version that will handle this error.
But there are some other things that are not supported by the player, for example adjustment layers and black and white effect.

**Comment by CelineThiry** [comment]
Hi, thanks a lot for your quick reply ! I will try the new version without the After Effect features that are not supported. I'm coming back to you whatever it works or not ;) ( hope it will work)

Thanks again.
