### ISSUE TITLE
Bug on Huawei

### ISSUE THREAD

**Issue by vmoureu** [airbnb/lottie-web#1147]
Hello, 
I have some trouble with my animation on Huawei phones. That work greatly on all android phones except the Huawei. 

I used After Effect 2018 15.1.1 on a mac. 
Thanks for your help.
![lotti](https://user-images.githubusercontent.com/40568705/42685674-eea236e8-8693-11e8-91ef-23bff427bed2.png)

**Comment by bodymovin** [comment]
Hi, are you using the native android player or are you running them in the browser?

**Comment by vmoureu** [comment]
I use the native android player.

**Comment by bodymovin** [comment]
Can you post the issue on the android repo?
https://github.com/airbnb/lottie-android
