### ISSUE TITLE
lottie.playSegments playing twice when playing in reverse

### ISSUE THREAD

**Issue by leantide** [airbnb/lottie-web#1149]
**Tell us about your environment**

* **Browser and Browser Version:** Chrome 67.0.3396.99
* **After Effects Version:** 15.1.1

**What did you do? Please explain the steps you took before you encountered the problem.**
lottie.playSegments([30, 0], false)

**What did you expect to happen?**
lottie would play segments 0 to 30 in reverse a single time

**What actually happened? Please include as much _relevant_ detail as possible.**
lottie played segments 0 to 30 in reverse, but played it twice. Previous versions only played it once.

**Comment by arthursday0413** [comment]
I have the same issue :(

**Comment by leantide** [comment]
My present work around is to create the animation within After Effects so that it includes a both forward and reverse animation segment, so by playing these segment in Lottie-web in a forward direction, I get both the forward and reverse effect. Inconvenient and inefficient but functional.

**Comment by leantide** [comment]
Just retried this in v5.2.0 and unfortunately the issue continues to exist: segments played in reverse erroneously play twice in reverse.
