### ISSUE TITLE
Miter limit exports current current miter limit value, not animation

### ISSUE THREAD

**Issue by gpeal** [airbnb/lottie-web#1150]
If you have an animated miter limit, it will export the float value at whatever point is currently rendered in After Effects when you export the animation, not the keyframe values as you would expect.

[Miter Limit.aep.zip](https://github.com/airbnb/lottie-web/files/2196557/Miter.Limit.aep.zip)

**Comment by bodymovin** [comment]
Fixed.
Will be deployed on the next release.
