### ISSUE TITLE
Inline SVG

### ISSUE THREAD

**Issue by aakey7** [airbnb/lottie-web#1151]
I am importing SVG into my animation with img tags

`<image width="144px" height="144px" xlink:href="images/test.svg"></image>`

I was wondering if anyone knows a way of importing these so the colours are editable. I want to be able to change the fill colours of the svgs, however there is a large range of possible svgs so ideally I wouldn't have to add them all as inline elements.

**Comment by nickmadedesign** [comment]
This relates more to CSS than Bodymovin as an issue. Your inline SVG markup is deprecated. I'd suggest doing a search for inline SVG best practice.

From there you can apply color to the Fill property via CSS.

It would be nice to have class names generated per layer based on the layer's name and possibly a global prefix via Bodymovin but for now, you can add them manually in the final code.

**Comment by bodymovin** [comment]
@nickmadedesign you can add classes and ids to layers from AE
https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript
