### ISSUE TITLE
Bodymovin after effects from illustrator - "frames" everywhere

### ISSUE THREAD

**Issue by sebRingrose** [airbnb/lottie-web#1152]
Hi there,

My bodymovin export looks perfect in the preview, and if I export with a HTML demo file that demo file runs fine locally. But when running the JSON animation I see frame looking objects with a blue sky moving around the scene. 

Thanks for your help

What it should look like:
<img width="1047" alt="screen shot 2018-07-16 at 12 32 07" src="https://user-images.githubusercontent.com/10160507/42756504-50ff424c-88f4-11e8-86a7-6b3807f957de.png">

What it does look like:
<img width="639" alt="screen shot 2018-07-16 at 12 32 23" src="https://user-images.githubusercontent.com/10160507/42756508-537022bc-88f4-11e8-95db-5852ad668be6.png">

**Comment by bodymovin** [comment]
Hi, the images folder seem to be missing.
By the way, have you tried converting your .ai layers to shapes?

**Comment by sebRingrose** [comment]
Oops - did not realise I needed the images folder. Thanks :p 

I have converted the layers. Works perfectly with the images folder in the directory
