### ISSUE TITLE
Animation of dashed/ dotted line doesn't work

### ISSUE THREAD

**Issue by dimkotr** [airbnb/lottie-web#1153]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

After Effects version: 14.1.0.57

**What did you do? Please explain the steps you took before you encountered the problem.**

Tried to animate a dotted line by going to:

Contents/ Stroke 1/ Dashes / **Offset**

**What did you expect to happen?**

I expected the animation in the exported file to play the same way as in the After Effects. Meaning the offset animation seems like it doesn't work. 

**What actually happened? Please include as much _relevant_ detail as possible.**

The rest of the animations work properly in the exported json file except from what I mentioned above. 

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by dimkotr** [comment]
https://drive.google.com/open?id=13M4F4Z0kfchzKCkT4qZHUOkrippDzJkA

**Comment by dimkotr** [comment]
Let me know should you need anything else. Thank you!

**Comment by bodymovin** [comment]
I've tried the animation and it seems to be working fine.
Can you share a reduced example of what isn't working?

**Comment by dimkotr** [comment]
I will make 2 short videos, one of how it should work and one of how it works, to point out the issue. 

Thank you for being prompt to help!

**Comment by dimkotr** [comment]
Here you can find 2 short videos regarding the issue, check the distinction, between those 2, of how the purple dots are animated in both videos: https://drive.google.com/drive/folders/1DEqJfZcpBvDBliMYFxTxVnACrkkY3QrT?usp=sharing

The json video is the bodymovin export and the after-effects video is the after effects export that shows how the animation should properly work.

**Comment by bodymovin** [comment]
Hi, I've tried it and the dots animate correctly.
Can you share a working link?
