### ISSUE TITLE
Not exporting shape effects

### ISSUE THREAD

**Issue by Ludmilarr** [airbnb/lottie-web#1156]
Hi! 

**Tell us about your environment**
I'm working on a mac with the last update

* **Browser and Browser Version:**
Chrome Latest version (67.0.3396.99 )

* **After Effects Version:**
cc 2018

**What did you do? Please explain the steps you took before you encountered the problem.**
I have a fairly simple animation created on AF of a squiggle line. 
Is a line shape on to i applied a Zig Zag and Trim Path shape effects. 
The animation in AE works perfectly ( in the link below you have all the attachments) 

**What did you expect to happen?**
That will report the SVG as per animation.

**What actually happened? Please include as much _relevant_ detail as possible.**
I have the line, the colours, but not the zig-zag or the trim path effects. 
there is a very little animation tho.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/sh/7ye0xxph3oxtlvq/AADVajgQ6IUEFQNomk4xke7ga?dl=0

Thank you!

**Comment by bodymovin** [comment]
Hi, Zig Zag is not supported unfortunately.
The rest seems to be working fine.

**Comment by kudanai** [comment]
ZigZag support has been added in v5.10.0
