### ISSUE TITLE
Two (or more) bodymovin code on one page?

### ISSUE THREAD

**Issue by thechoperpilot** [airbnb/lottie-web#1157]
Greetings!

I managed to export animation to HTML, and then to add the HTML to wordpress page. I had to change <body> to <div id=""> tag, remove style from <head> of lottie and apply it to wp css and made it work online!

However, I was unable to make it full width (I will figure it out eventually)

The problem is: My plan was to make 2 separate animations (or more) and place them at 2 different sections of page. Even I gave different <div id="">, those are withing #lottie ID and on screen two separate animations are connected into one (one bellow other). I tried to add some section between them, but as they have same ID, browser sees them as one animation.

I tried to change #lottie of one of them to something else, but then animation just disappear. 

Is there a way to add two separate, independet animations on one page and to change <div id="lottie"> of at least one of them to different ID? Is there something I can do withing AE to avoid id to be set to lottie? Or maybe to change it in code itself (and how to do it)?

Best regards and many thanks for a plugin!!

**Comment by bodymovin** [comment]
Hi, can you share a link with your implementation?

**Comment by thechoperpilot** [comment]
Sure! Here it is

http://supremedesignstudio.com/120-2/

this is (obviously) test website. I tried to add image between these two animations. 
First animation should be blue wording (with "tools and knowledge for it" at the end) and second one is with all the png images flying around.

**Comment by bodymovin** [comment]
each animation can be loaded using this code you already have implemented:
````javascript
var params = {
  container: document.getElementById('lottie'),
  renderer: 'svg',
  //loop: true,
  autoplay: true,
  animationData: animationData
  };
  var anim;
  anim = lottie.loadAnimation(params);
````
Specifying on each case a different container and a different animationData.

**Comment by thechoperpilot** [comment]
Great! This was helpful, thank you very much!
I am not beginner coder, but still managed to fix animation with your instructions.

Thank you and best regards!
