### ISSUE TITLE
Question: gradient (fill) performance

### ISSUE THREAD

**Issue by nickmadedesign** [airbnb/lottie-web#1158]
Hi,

Is there a hit/penalty to performance for the use of gradients on shape layers for SVG rendering?

I'm thinking of adding gradients to shape layers to add visual interest but I don't want to go through the trouble if it is known to degrade animation performance.

Thanks!

**Comment by bodymovin** [comment]
It shouldn't have a performance penalty unless you use opacity controls that don't match the position of the color controls in AE.

**Comment by nickmadedesign** [comment]
Perfect. Thank you!
