### ISSUE TITLE
Can Resize Font

### ISSUE THREAD

**Issue by aakey7** [airbnb/lottie-web#1160]
I was wondering if anyone has been able to get .canResizeFont(true); to work?

Do we have to call `anim.renderer.elements[0].canResizeFont(true) ` via javascript once the element is rendered or before?

I haven't been able to implement it. Does it automatically resize the font size to fit into a text box?

**Comment by bodymovin** [comment]
Yes, it will automatically resize the font if the new text doesn't fix inside the text box.
You should be able to call it at any time.

**Comment by aakey7** [comment]
Does it work with glyph characters? or does it need to be font characters?

**Comment by bodymovin** [comment]
It works with glyph characters too.
