### ISSUE TITLE
Text not masking /revealing as intended

### ISSUE THREAD

**Issue by Visabull** [airbnb/lottie-web#1161]
**Tell us about your environment**
MacOS 10.13.6 
* **Browser and Browser Version:**
n/a
* **After Effects Version:**
15.1.2 (Build 69)
**What did you do? Please explain the steps you took before you encountered the problem.**
Created Animations as normal, then tried to add a text mask (path/stoke). I tried this with live text and converting the text to shapes.
**What did you expect to happen?**
The text to reveal as the mask animates/ to match the AE animation
**What actually happened? Please include as much _relevant_ detail as possible.**
Text never reveals, then only the "!" at the end becomes visible.
**Please provide a download link to the After Effects file that demonstrates the problem.**

PS - this is my first post...

**Comment by bodymovin** [comment]
Hi, can you share the implementation or the animation?

**Comment by kudanai** [comment]
Hey there. As this issue has been stale for some time, I'm closing it. Please re-open it if you feel it still relevant or open a new issue.
