### ISSUE TITLE
Doesn’t work with Gatsby

### ISSUE THREAD

**Issue by emilbruckner** [airbnb/lottie-web#1163]
Sorry if this is a problem with Gatsby instead of Lottie. I don’t really know where to ask this.

**Tell us about your environment**

* **Browser and Browser Version:** Chrome 67
* **After Effects Version:** 15.1.1

**What did you do? Please explain the steps you took before you encountered the problem.**
Add lottie-web to gatsbyjs project. I have an example with the gatsbyjs starter here: [https://github.com/emilbruckner/gatsby-lottie-test](https://github.com/emilbruckner/gatsby-lottie-test)

The site works with `gatsby develop`, but doesn’t show the animation and somehow freezes on the build version.

**Comment by bodymovin** [comment]
Can you try disabling the expressions in AE and see if it compiles correctly?

**Comment by emilbruckner** [comment]
I uploaded my project here: https://www.dropbox.com/sh/p1phb2pt4c9q7pz/AACFx7fh_9GbqQfjP_Et28J8a?dl=0

I tried turning off the expressions, but that didn’t help. What should we try next?

I also created a very simple animation [here](https://github.com/emilbruckner/gatsby-lottie-test/tree/minimal-animation), which works. So it must be something with my AE file.

By the way, I got it to work on my [landing page](http://findbetterquestions.com/) with importing the lib via script tag.

**Comment by bodymovin** [comment]
I've installed the gatsby project and it requires dependencies that are not defined in the package.json
after installing those and running the project, I'm getting react router errors in the console:
`Uncaught Error: You should not use <Route> or withRouter() outside a <Router>`

**Comment by emilbruckner** [comment]
@bodymovin Sorry about that. One probably has to install Gatsby globally with: `npm install --global gatsby-cli`
https://www.gatsbyjs.org/docs/

You shouldn’t need any other dependencies. Which ones did you add? React-Router?

Thanks for having a look!

**Comment by bodymovin** [comment]
I'm visiting http://localhost:8000/ and I'm getting errors:
`Uncaught Error: You should not use <Route> or withRouter() outside a <Router>`

**Comment by emilbruckner** [comment]
@bodymovin Could you try installing the dependencies with yarn instead of with npm? Thanks

**Comment by bodymovin** [comment]
After simplifying the method to it's minimum, it seems that the minification used by gatsby is doing strange things.
And the resulting for loop never ends.

````javascript
function sub(value_a) {
  var i = 0;
  var lenA = value_a.length;
  var retArr = [];
  while(i < lenA){
    retArr.push(0);
    i += 1;
  }
  return retArr;
  }
````
gets compiled into this
````javascript
function sub(t) {
  for (var e = t.length, i = []; 0 < e; )
    i.push(0);
    return i
 }
````
