### ISSUE TITLE
Masked layered are not exporting in the output

### ISSUE THREAD

**Issue by Shivaprasad222** [airbnb/lottie-web#1168]
I have tried changing the mode of the mask to add and exporting and tried keeping image in the file But I could do any and I have added the FILL effect to the masked layers .

Please help with this regard 

I am attaching my project file, json file and output images
[To lottie people.zip](https://github.com/airbnb/lottie-web/files/2244092/To.lottie.people.zip)

**Comment by Shivaprasad222** [comment]
Please someone report this problem

**Comment by bodymovin** [comment]
Hi, the Fill effect is not fully supported.
I suggest that you convert masks to shapes and it should work fine.

**Comment by Shivaprasad222** [comment]
Hey thanks for the suggestion but I could convert masks into shapes but their are plenty of them. Could you give me a suggestion in which way I could convert it fast (Like all the mask converting into shapes at once )or can you make it and send me the project

**Comment by kudanai** [comment]
Hey there. As this issue has been stale for some time, I'm closing it. Please re-open it if you feel it still relevant or open a new issue.

**Comment by Shivaprasad222** [comment]
done no need to reopen
