### ISSUE TITLE
Animation Renders wrongly on Mobile

### ISSUE THREAD

**Issue by Felixchip** [airbnb/lottie-web#1169]
[Loader.zip](https://github.com/airbnb/lottie-web/files/2245234/Loader.zip)

* **I use Google Chrome and Lottie Preview for iOS:**
* **After Effects Version 15.1.1:**

I created a loading animation using After Effects and rendered with Bodymovin Version 5.2.0.
Now, when I preview the animation on my browser, it plays well, as well as on the Lottie website Previewer. But, when I preview it on my mobile phone, it shows something completely different.

And, from my experience, if it doesn't render well on mobile preview, it won't when implemented into an app. 

The animation is supposed to be a path revealing the image.
But instead, it renders something different. Entirely.

I attached the JSON file.

**After Effects file: https://www.datafilehost.com/d/c1ccbf85**

**Comment by bodymovin** [comment]
Hi, the lottie-ios and android players don't support the same features than the web player.
Here is the supported features table
http://airbnb.io/lottie/supported-features.html

Can you post the issue on the repo it corresponds if necessary?
https://github.com/airbnb/lottie-ios
https://github.com/airbnb/lottie-android
