### ISSUE TITLE
IOS mobile not rendering properly - https://codepen.io/jasbirsandhu43/project/editor/XobnaY

### ISSUE THREAD

**Issue by jasbirintelligaia** [airbnb/lottie-web#1170]
**Tell us about your environment**
>> IOS all mobile device 

* **Browser and Browser Version:**
>> All browser -  Safari, Chrome

* **After Effects Version:** 
>> After effect cc 2018

**What did you do? Please explain the steps you took before you encountered the problem.**
>> Render=  html, working fine on android and desktop.

**What did you expect to happen?**
>> Proper render.

**What actually happened? Please include as much _relevant_ detail as possible.**
>> I am creating a animation which contains 5 images and these images are zooming out with an angle and then explode.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://codepen.io/jasbirsandhu43/project/editor/XobnaY

**Comment by bodymovin** [comment]
Hi, can you post the issue on the ios repo?
https://github.com/airbnb/lottie-ios
