### ISSUE TITLE
Change color of icon based off the progress of the animation

### ISSUE THREAD

**Issue by aditya2705** [airbnb/lottie-web#1171]
**I'm trying to change the color of an icon while it animates from non-slash to slash animation. I want it to change from black to white. I'm not sure how to go about it. https://jsfiddle.net/49z5rnjf/260/**

**Can you help as to how I can achieve it?**

**Comment by bodymovin** [comment]
Hi, can you animate the color change in after effects?

**Comment by bodymovin** [comment]
the most straightforward way is doing it with lottie-api.
Trying to do it manually means traversing the json tree and making sure it has keyframes to modify.
Another option might be using css targetting the element via javascript.

**Comment by aditya2705** [comment]
If I were to target the css. How do I do that with respect to the progress of the animation? For instance, in the link I shared, I'd like the icon to change color gradually depending upon the progress of the animation

**Comment by bodymovin** [comment]
You can add an event listener to the animation.
`anim.addEventListener('enterFrame', function(ev){})`
the event contains the current frame and total frames of the animation

**Comment by aditya2705** [comment]
Thanks @bodymovin! That seems really helpful. And how would I get the particular element? Through the renderer? I'm asking this because changing anim.renderer.elements[0].data in the js (of link I shared) doesn't really affect the actual element.

**Comment by bodymovin** [comment]
If it's not keyframed, you won't be able to update the value.
Via js, you can name the layer in AE with a . or a # and it will add a class or an id to it.
Do you have access to the ae project?

**Comment by aditya2705** [comment]
No, I do not. The only other option if this does not work is to ask our motion designer to create the new animation (with the color transition). I just hoped to do that without any other dependencies (though lottie-api is useful indeed)

**Comment by aditya2705** [comment]
Hi @bodymovin, is there a way to remove the fill attribute from the rendered svg path by removing some lines (corresponding to type - fill) from the animation json?

**Comment by aditya2705** [comment]
I've been able to resolve this by adding class with a ".". Thanks for all the help. You may close this.
