### ISSUE TITLE
Wrong text range selector keyframe timestamps

### ISSUE THREAD

**Issue by zhengs** [airbnb/lottie-web#1172]
It's a pretty simple layer, just a text with a range selector and two keyframes that move the range from 0% at frame#3, to 100% at frame 1s:08 at 25fps, i.e. frame#33.

However, the exported animation runs much faster than inside AE, either shown in a browser or through the plugin's Preview function.

The start frame seems right, at Frame#3, but the moment at which the selector achieves 100% seems at Frame#9, vs. Frame#33 in the template. i.e. about >3X faster.

The layer is 02_text_hero_a_op01 in the attached template. Did I miss anything?

[simple_bodymovin.aep.zip](https://github.com/airbnb/lottie-web/files/2248015/simple_bodymovin.aep.zip)

**Comment by bodymovin** [comment]
Thanks for reporting. It was related to using range selector based on words and percentage.
It's been fixed and pushed on master.
You can use the updated player from the build folder.
