### ISSUE TITLE
Help Wanted: With After Effects to Bodymovin [Lottie] Rendering fractal noise

### ISSUE THREAD

**Issue by alok-aks50** [airbnb/lottie-web#1173]
Hey Guys,

Have an issue with the @lottie conversion of one of my projects.

i am trying to create grunge kind of texture and i was hoping after effect fractal noise with levels effects will work. but its not rendering in Bodymovin plugin. 

Below is the images showing how i created grunge using two different effects.
![screen shot 2018-08-01 at 5 53 57 pm](https://user-images.githubusercontent.com/41997645/43521700-a39f26ee-95b4-11e8-9800-48e96ef200eb.png)
![screen shot 2018-08-01 at 5 57 28 pm](https://user-images.githubusercontent.com/41997645/43521702-a3cedb96-95b4-11e8-8a66-c0edace801af.png)

Is their any other way to create like above effect?(whick can be exported using Bodymovin plugin)

i tried creating it in AI and bring it as vector shapes. but due to the heavy details in noise its creating hundreds of shapes in aftereffects and file is becoming heavy.

Don't know how to solve it. :) Any help would be appreciated.

Im Using Adobe After Effects CC 2018 & Bodymovin V5.1.1

Thanks & Regards
Alok

**Comment by bodymovin** [comment]
Hi, unfortunately those kind of effects are not supported by the player.
But if you're not animating the fractal properties, you could create the effect in photoshop and export it as a rasterized image.

**Comment by alok-aks50** [comment]
Thanks. i did the same. :)
