### ISSUE TITLE
Android animations fail to render exported json synchronously. 

### ISSUE THREAD

**Issue by matthewbahr** [airbnb/lottie-web#1174]
* **Tell us about your environment**
Android Lottie 2.5.1

* **Browser and Browser Version:**
Compared with Codepen.io in Chrome

* **After Effects Version:**
AE CC 2018

**What did you do? Please explain the steps you took before you encountered the problem.**
Exported normally, grabbed json and tried it in android.

**What did you expect to happen?**
[This is a correct version of the animation, using the exact same json file in a codepen environment](https://codepen.io/crowbahr/project/editor/XobKYG)

**What actually happened? Please include as much _relevant_ detail as possible.**
Tested on physical devices and emulator, had the following animation instead:
https://gfycat.com/IncomparableBetterArcticwolf

Note that the animation has several problems:
1. The check boxes skip ahead of the broadcast animation.
2. The animation does not complete correctly with the peeling effect shown, but rather stops without peeling the boxes.

**Please provide a download link to the After Effects file that demonstrates the problem.**
[Google Drive Download Link](https://drive.google.com/file/d/1RxPUIww47_a9fH61aHBVWet6_xU7EuGP/view?usp=sharing)

**Comment by kudanai** [comment]
Thank you :D If this is a persisting problem, can you file it on lottie-android and we'll keep track of it there?. Closing this issue for now.
