### ISSUE TITLE
issue when loading several animations on the same page

### ISSUE THREAD

**Issue by luispedromograph** [airbnb/lottie-web#1176]
Hi all,
I'm writing you because I'm trying to load several animations on the same page, and I'm having an issue with the last one.

there are 6 animations, each on its very own div, and all working but the last one, which is not even loading.
I'm using Chrome Version 67.0.3396.99 (Official Build) (64-bit), After Effects CC2018 Version 15.1.2 (Build 69).
I'm getting this error message on the Dev Console

Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at SVGRenderer.configAnimation (bodymovin.min.js:4)
    at AnimationItem.configAnimation (bodymovin.min.js:5)
    at XMLHttpRequest.r.onreadystatechange (bodymovin.min.js:5)
  | SVGRenderer.configAnimation | @ | bodymovin.min.js:4
  | AnimationItem.configAnimation | @ | bodymovin.min.js:5
  | r.onreadystatechange | @ | bodymovin.min.js:5
  | XMLHttpRequest.send (async) |   |  
  | AnimationItem.setParams | @ | bodymovin.min.js:5
  | a | @ | bodymovin.min.js:5
  | loadAnimation | @ | bodymovin.min.js:1
  | (anonymous) | @ | animations.js:50

Initially I thought it would be something related to the number of animations, but if I comment a random animated element, or a random piece of the animations script from the js script -where I have 1 var for each animated element-, I'm getting the same message on the console.

This is the [website](http://www.luispedro.net/gradulus/index-animations.html) and the faulty animation is quite below, almost at the end of the document. The rest work perfectly fine.

Any clue would be much appreciated.

Thanks!

**Comment by bodymovin** [comment]
Hi, it seems the last animation is looking for an element with id "options".
Running `document.getElementById('options')` in the console returns null, so it seems that the element doesn't exist on the DOM.

**Comment by luispedromograph** [comment]
Oh! there was a gap on the element's id after "options" no wonder why it was returning the error. 

Thank you so much!

**Comment by bodymovin** [comment]
hi, can you share the link?
it seems like it's not finding the json in the specified url

**Comment by luispedromograph** [comment]
Never mind, I managed to fix it. I just removed the old json and re-rendered from AFX, and it worked.

Thanks anyway @bodymovin!

Cheers
