### ISSUE TITLE
Function to translate lottie object property values?

### ISSUE THREAD

**Issue by justswim** [airbnb/lottie-web#1178]
Hi,

I'm trying to understand what the properties in the lottie file map to. 

For example, if the shape object has `ty: 5` that means that it is a text type according to the JSON docs. However, how can I find what 1, 2, 3, 4 would mean?

I know I can look through the json docs (https://github.com/airbnb/lottie-web/issues/575), but is there a function that I can call to translate the key / values instead?

Apologies if this is not the correct forum to ask this question - any help would be much appreciated!

**Comment by BillyTheGit** [comment]
Not sure what you are trying to achieve, but you might want to look at TextLayer.UpdateDocumentData and the Lottie API.

https://github.com/airbnb/lottie-web/wiki/TextLayer.updateDocumentData
https://github.com/bodymovin/lottie-api

**Comment by kudanai** [comment]
Please refer to [LottieFiles lottie-docs](https://lottiefiles.github.io/lottie-docs/)
or the [animation community documentation](https://github.com/lottie-animation-community/docs)

Hope that helps.
I'm going to close this issue for now please feel free to re-open it
