### ISSUE TITLE
There is stroke that I didn't use.

### ISSUE THREAD

**Issue by melonstar** [airbnb/lottie-web#1180]
Hello.
I made an progress animation for iOS/Android.

I only used 4 circle shapes and they don't have stroke option.
But after I gave json file to my coworker(developer), there is white stroke in circle. 

How can I fix it? Do I have to change Bodymovin render setting?

**Comment by alexbradt** [comment]
Have you tried selecting "hidden layers" that worked for me.

**Comment by alexbradt** [comment]
or unselect "hidden layers" I forget which one

**Comment by alexbradt** [comment]
trial and error is the best medicine ;P
