### ISSUE TITLE
High CPU usage (180%)

### ISSUE THREAD

**Issue by samday26** [airbnb/lottie-web#1181]
**Tell us about your environment**
Wordpress CMS running on LEMP stack
* **Browser and Browser Version:**
Chrome Version 67.0.3396.99
* **After Effects Version:**
After Effects CC 15.00
**What did you do? Please explain the steps you took before you encountered the problem.**
We're working on this site: https://eatgenesis.herdl.com/ and experiencing issues with extremely high CPU usage. There are a lot of animations, but they're paused when they're not in the viewport. 

**Please provide a download link to the After Effects file that demonstrates the problem.**
Is there an email address I can send the After Effects file to?

**Comment by samday26** [comment]
Forgot to mention that we are loving lottie other than this issue!

**Comment by bodymovin** [comment]
Hi, I've been checking the site and it seems that around 15 animations are running at the same time when the scroll is at the top.
Can you confirm the animations that are not showing are paused?

**Comment by samday26** [comment]
Thanks for getting back to me so quickly.

Yeah, that's correct. When the animations aren't in view they are paused. 

The sections below only have 1 animation looping when in view but CPU usage is still at around 160 - 200% through "Google Chrome Helper".  Just not sure what's causing it.

**Comment by bodymovin** [comment]
Can you verify they are really paused?
From my inspection, all of them are playing at the same time.

**Comment by samday26** [comment]
They should all pause when offscreen. When on screen, all the large animations have the class "scrlMagicActive" - so you can check if they're playing or not. Alternatively, in the video below you can see that the "snakeman" stops animating when off screen as shown by inspecting the animation.

https://drive.google.com/file/d/1vJ3DXzoZt_-kS4pxiynMLb2eTWkq_6l2/view?usp=sharing

**Comment by bodymovin** [comment]
"Burger","enter","snake","Fire","woman Comp 1","man Comp","Stars","moon Comp","Sun","Comp 1","Comp 1","hands"
These are all the animations I see animating when the scroll is at the top.
Should all of them be animating?

**Comment by samday26** [comment]
Yes they should all be animating when you're at the top of the page but they all pause when you scroll. The CPU usage at this point is not as high as when you scroll down to section 3 (opening times) where there is only one animation taking place.

**Comment by bodymovin** [comment]
"enter", "snake","Fire","woman Comp 1","man Comp","Stars","moon Comp","Sun","Comp 1","Comp 1","Comp 1","hands"
these are all animating when I'm scrolled down to 03. Opening Times.
Checking only one of them, I see it has 1122 vertices animating at the same time. 
Projecting that value x10 is > 10K vertices animating. This is probably the reason of the high CPU usage.
Can you try removing all the animations from the page and leaving only the one on section 3 to confirm if CPU usage is still up?

**Comment by kudanai** [comment]
Hey there. As this issue has been stale for some time, I'm closing it. Please re-open it if you feel it still relevant or open a new issue.
