### ISSUE TITLE
Inconsistent Speed on iOS

### ISSUE THREAD

**Issue by olohere** [airbnb/lottie-web#1182]
I made a simple "spinning" globe animation (for iOS) by passing a flat map through a circle mask. No effects, nothing special, just a position change (2 keyframes) and an alpha matte.

[https://www.lottiefiles.com/share/gJamPA](https://www.lottiefiles.com/share/gJamPA)

It plays correctly (consistent speed) on chrome, safari, and android... but not iOS. **On iOS it slows down as though there's an ease when it gets to the end of the loop.** The keyframes are plain and the graph is straight as shown in the screen below.

Any idea what could be happening?

![image](https://user-images.githubusercontent.com/42187443/43864979-0c87db7c-9b16-11e8-945c-9a5aa4b09500.png)

[After Effects file](https://drive.google.com/file/d/1821VFni3ws2B25G4sT9TbBD0UdDP0gS6/view?usp=sharing) (v14.0.1.5) (Bodymovin v5.1.20)

Thanks!

**Comment by bodymovin** [comment]
if it's the native app, I suggest that you post the issue on the lottie-ios repository
https://github.com/airbnb/lottie-ios

**Comment by olohere** [comment]
Ah ok, thank you.
