### ISSUE TITLE
Weird issue with layers stacked on top of each other after rendering.

### ISSUE THREAD

**Issue by Arteau** [airbnb/lottie-web#1183]
* **Browser and Browser Version:**
Chrome Version 67.0.3396.99
Firefox Version 61.0.1

* **After Effects Version:**
After Effects CC 2018

**What did you do? Please explain the steps you took before you encountered the problem.**
I made a simple animation of an arm and hand moving a mouse around using Duik for the IK skeleton.
I rendered my comp with Bodymovin with the settings "hidden" and "guides" checked, and looked at the preview within the Bodymovin extension.

**What did you expect to happen?**
I expected to see my animation as I made it in the preview section of Bodymovin, it did instead appear as such:
<img src="https://i.imgur.com/uylqnnY.png" width="400px" height="auto"></img>

The animation should look like this:
<img src="https://i.imgur.com/mQcYHHJ.gif" width="400px" height="auto"></img>

**What actually happened? Please include as much _relevant_ detail as possible.**
The preview within the Bodymovin window didn't look as expected.
However, when scrubbing through the timeline *within* the Bodymovin preview window, the animation suddenly played correctly as displayed in <a href="https://youtu.be/vHov29U0YIc">this youtube video</a>

When trying to get the animation working in a browser (firefox and chrome) the same problem as in the preview window appeared:

<img src="https://i.imgur.com/3M4d3hW.png" width="400" height="auto"></img>

**Please provide a download link to the After Effects file that demonstrates the problem.**

<a href="https://we.tl/pxAzwFCQeN">here is a WeTransfer link to the project</a> (I used Duik for the animation, keep that in mind.

<hr>

**Thank you very very much**
Both for the help with this issue, and for this amazing extension.

**Comment by bodymovin** [comment]
Hi, have you included Hidden and Guided layers on export?

**Comment by Arteau** [comment]
Yes I did check the hidden and guided layers settings :(

**Comment by bodymovin** [comment]
are you using the latest DUIK version?

**Comment by Arteau** [comment]
do you reckon that will solve this?

**Comment by bodymovin** [comment]
yes.
I've already uploaded it.
You can download the new version and try it now.

**Comment by Arteau** [comment]
Nice, going to try it out immediately

**Comment by Arteau** [comment]
I'm afraid the problem persists. Nothing has changed.

I installed both DUIK and Bodymovin again, I Installed Bodymovin straight out of the repository you updated about 40 minutes ago, and DUIK from the official website.

**Comment by Arteau** [comment]
Nevermind! It works!
I forgot to download the player again.

**Thank you so much!!**

**Comment by bodymovin** [comment]
Glad it works.
I suggest that you convert your .ai layer to shapes in AE.
That way they'll get exported as vectors and won't lose quality.
