### ISSUE TITLE
Expression not rendering

### ISSUE THREAD

**Issue by schmoollala** [airbnb/lottie-web#1185]
<img width="1170" alt="screen shot 2018-08-09 at 7 24 36 am" src="https://user-images.githubusercontent.com/42224490/43871120-51ee572e-9ba5-11e8-960e-ce9d40de3c4d.png">

* **After Effects Version:**
Adobe After Effects CC 2018

**What did you do? Please explain the steps you took before you encountered the problem.**
I made an animation using xAmp, xFreq, xSpeed expression but the animation failed to render.

**What actually happened? Please include as much _relevant_ detail as possible.**
When the composition is rendered the position is random and the animation did not show.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://we.tl/s0n0Ri2Elw

**Comment by bodymovin** [comment]
Hi, I've added the position expression and pushed a new player.
