### ISSUE TITLE
Gradient change to black and white when I export the json

### ISSUE THREAD

**Issue by fuguangliang** [airbnb/lottie-web#1186]
[demo.zip](https://github.com/airbnb/lottie-web/files/2272535/demo.zip)
here is my aep,plz

**Comment by bodymovin** [comment]
Hi, unfortunately there is a problem and I can't get to export gradients if AE is in Chinese and some other languages.

**Comment by kudanai** [comment]
Hey there. As this issue has been stale for some time, I'm closing it. Please re-open it if you feel it still relevant or open a new issue.
