### ISSUE TITLE
Resize text issues

### ISSUE THREAD

**Issue by Adam-Burke** [airbnb/lottie-web#1187]
* **Browser and Browser Version:**
chrome 67, mac high sierra 10.13.6.

* **After Effects Version:**
15.1.2

**What did you do? Please explain the steps you took before you encountered the problem.**
Updated from 5.0.9 to any ^5.0.9.

**What did you expect to happen?**
Resize text correctly and render text updates correctly across all precomps in the after effects timeline exported to lottie-web.

**What actually happened? Please include as much _relevant_ detail as possible.**
Text resizes correctly at some points in the composition and incorrectly at others composition(uploaded). Its consistent in that respect.

**Please provide a download link to the After Effects file that demonstrates the problem.**

[playercomparison.aep.zip](https://github.com/airbnb/lottie-web/files/2272989/playercomparison.aep.zip)

Here is a link that highlights the issue. https://drive.google.com/file/d/1hAnsZnK4toG0uiQCHFdooS_KoUcmROMc/view
I'm looping the animations over a single frame to allow them to update while appearing static. Not sure if there is a better solution to this. Notice how when on large it always works correctly.

**Comment by bodymovin** [comment]
Hi, can you share a sample code or a link to see how you're implementing it?

**Comment by Adam-Burke** [comment]
Not easily unfortunately. It's built into a react component and there is a fair bit going on to make it dynamic and handle our specific use case. 

I've uploaded the main file below just in case it helps. Basically I'm using the playSegments function to find which segments of the main composition I want to play and then just looping over the last two frames so the text can update immediately upon. I'm sure I could make this more efficient but I still think I'd need to just loop a portion of the graphic to get the text to update if I understand correctly. 

[index.js.zip](https://github.com/airbnb/lottie-web/files/2285588/index.js.zip)

**Comment by bodymovin** [comment]
Are you exporting text as font or glyphs?
Can you copy here a sample of the code you're using?

**Comment by Adam-Burke** [comment]
The issue seems to be with line height and text opacity when added to the text layers does strange things when running updateDocumentData. That and I was running updateDocumentData after canResizeFont. Interesting that these didn't cause any issues prior to version 5.1.9. I'm just happy to be on 5.3 now with everything working great. Thanks for all your work!

**Comment by bodymovin** [comment]
@Adam-Burke glad it works.
A little concerned that something stopped working that worked before though.
If you can share a reduced example of the issue I'll take a look at it.

**Comment by Adam-Burke** [comment]
I have the same issue now with a text layer actually. I think its the fill rgb animator causing it, although this works on versions up to 5.1.9 I believe. It also doesn't always happen. 

Here is an example - https://drive.google.com/file/d/1dn4BQc-qHkWX6Aswx8fmufuvtxJOudjr/view.

I'm animating over two frames on a loop so it updates immediately.

Here is the file in question.
[formationSingle.aep.zip](https://github.com/airbnb/lottie-web/files/2419247/formationSingle.aep.zip)

**Comment by Adam-Burke** [comment]
Yep. That has fixed it!
