### ISSUE TITLE
New issue when exporting with shape layers.

### ISSUE THREAD

**Issue by Arteau** [airbnb/lottie-web#1190]
* **Browser and Browser Version:**
Chrome Version 67.0.3396.99
Firefox Version 61.0.1

* **After Effects Version:**
After Effects CC 2018

**What did you do? Please explain the steps you took before you encountered the problem.**
After posting and resolving <a href="https://github.com/airbnb/lottie-web/issues/1183">this issue</a> yesterday, and following your advice of switching to shape layers instead of illustrator layers, a new issue emerged.
Something weird is going on with my paths when I export, while it looks good in After Effects, it only starts getting weird after rendering.

It now looks like this after rendering: 
<img src="https://imgur.com/i3WlB6i.png" height="auto" width="400px"></img>

instead of:
<img src="https://i.imgur.com/gLxHV7K.png" height="auto" width="400px"></img>

The animation itself plays fine, it's just the shapes that are all mangled.

**What did you expect to happen?**
After converting the illustrator layers to shape layers I expected my export to be the same but with vector shapes as svg instead of png images.

**What actually happened? Please include as much _relevant_ detail as possible.**
After rendering something weird happened with the paths and most shapes got mangled/turned inside out almost.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://we.tl/ysFCTVOcfC

**Comment by Arteau** [comment]
I think it has something to do with the gradient fills of the shapes that got mangled. Only shapes that had a gradient were bugged, and I just tried a version without gradients and that one has no problems whatsoever.

**Comment by henriqrossatto** [comment]
Hi Arteau. I believe this happens because the Merge Layers. Take a look in each group and delete the merge layers and the rectangular paths inside them. When you import AI Files for AE, some layers has this merges and Lottie doesn't support it.

**Comment by Arteau** [comment]
Ok thanks for the reply! I'll look into it.

**Comment by henriqrossatto** [comment]
hand+mouse>group 3 (delete path 1 and merge)
body>group 1 (delete path 1 and merge)
table>group 1 (delete path 1 and merge)

**Comment by Arteau** [comment]
I did, and now the shapes work but the colors are incorrect:

<img src="https://i.imgur.com/gYC6kZ5.png" height="auto" width="400px"></img>

**Comment by henriqrossatto** [comment]
Ok, for gradient, don't use the effect. Change in the fill options on top of AE or add the a gradient fill inside the layer. . After it, edit the color inside the layers

**Comment by Arteau** [comment]
Weirdly enough that's what I did. I went inside the layer and changed the fill into gradient there.

**Comment by henriqrossatto** [comment]
Try to change the name of the layer gradient or the gradient. Gradient it's a little bugged on Lottie yet.

**Comment by Arteau** [comment]
Deleting te paths and renaming the gradient layers actually worked! This is solved! Thanks so much!

**Comment by henriqrossatto** [comment]
Great!
