### ISSUE TITLE
Ways to force exporting in "svg" renderer?

### ISSUE THREAD

**Issue by zhengs** [airbnb/lottie-web#1191]
As title says, is there a way to force BM always specify renderer as "svg", rather than "html"?

My template relies on some effects that only work under "svg", and it's annoying to have to manually rewrite "html" to "svg" each time.

**Comment by bodymovin** [comment]
Are you referring to the demo file?
If so, it usually defaults to svg, but if you have 3d layers it will switch to the html renderer.

**Comment by zhengs** [comment]
I see. Make sense. Thanks!
