### ISSUE TITLE
Animation not previewing or exporting in demo

### ISSUE THREAD

**Issue by leiterl** [airbnb/lottie-web#1193]
**Tell us about your environment**

* **Browser and Browser Version:** google chrome
* **After Effects Version:** Version 15.1.0 (Build 166)

**What did you do? Please explain the steps you took before you encountered the problem.**
Downloaded the bodymovin extension so I could export my animation as a json file but the animation is not previewing or demoing.
**What did you expect to happen?**
I expected it to preview.
**What actually happened? Please include as much _relevant_ detail as possible.**
Nothing showed up. I used trapcode particular to make the animation. Is that an issue?
**Please provide a download link to the After Effects file that demonstrates the problem.**

[Explosions.zip](https://github.com/airbnb/lottie-web/files/2284917/Explosions.zip)

**Comment by bodymovin** [comment]
Hi, Particular effect is not supported by the extension.
Not many AE effects are. Here is a list of the few supported.
https://github.com/airbnb/lottie-web/wiki/Effects
