### ISSUE TITLE
Lottie stop working with Gatsbyjs v2

### ISSUE THREAD

**Issue by tmark-work** [airbnb/lottie-web#1194]
**Tell us about your environment**

* **Browser and Browser Version:** Google Chrome 68
* **After Effects Version:** -

**What did you do? Please explain the steps you took before you encountered the problem.**
Used lottie with gatsby on version 1.9.277 and everything was ok. From gatsby version v2.0.0 (beta 1-99) stops working with error "Cannot read property 'propType' of undefined" or "Cannot read property 'constructor' of undefined"

**What did you expect to happen?**
Render animations without error

**What actually happened? Please include as much _relevant_ detail as possible.**
Just right after update animations stops working. Some of them play 1 cycle and raise an error, some of them crash at start. **Only happens after build**. In development mode it's okay.

Links:
https://dazzling-kowalevski-0cd029.netlify.com/foundation/philosophy ('constructor' error)
https://dazzling-kowalevski-0cd029.netlify.com/services/magnus ('propType' error)

**Comment by bodymovin** [comment]
Hi, can you share the .aep project?

**Comment by tmark-work** [comment]
@bodymovin Hello, 
[mag.aep.zip](https://github.com/airbnb/lottie-web/files/2289972/mag.aep.zip)

sure, here it is.
Designer said that he exported composition with name 'placeholder' and used 'Sketch to AE' plugin 

thank you!

**Comment by tmark-work** [comment]
Probably something goes wrong on bundle building stage with webpack.
When I use CDN to load lottie and exclude lottie npm package from bundle - it works..

**Comment by bodymovin** [comment]
Hi, I've been tracking a similar issue here
https://github.com/airbnb/lottie-web/issues/1163
apparently gatsby does some weird things when minifying the code.
It might be related to where lottie is being imported, but I'm not familiar with gatsby development workflow

**Comment by kudanai** [comment]
Hope this issue is solved. Closing this for now since it's been a while. Please feel free to re-open it if it's still relevant.
