### ISSUE TITLE
[Export Plugin] Wrong color values in json file

### ISSUE THREAD

**Issue by ferusinfo** [airbnb/lottie-web#1197]
In some situations (we believe that might be connected to shape layers that are really thin), the color values are not represented equally in the json file.

While in, for example - text layers - the colors are encoded in following way:
```json
"fc": [1,0.9,0.3]
```

The colors in Shape Layer are encoded with more precision using decimal spaces:
```json
"k": [1,0.898039215686,0.301960784314,1]
```
So even though we set the same hex values in AE project, the outcome of the plugin gives us slightly different color in the result - that is kind of painful when you want to display a list of colors used in the template (you have 2 almost identical colors then).

I am attaching an example project that we have problems with. 
[example_project.zip](https://github.com/airbnb/lottie-web/files/2293987/b81.zip)

**Comment by ferusinfo** [comment]
Besides the palette, the less precise option for text layers etc. make it very difficult to create a well performing visual editor that we are working at right now.
Would that be a problem to add the level of precision that you have in shape layers so the colors would be consistent throughout the JSON file?

**Comment by bodymovin** [comment]
it makes sense to add one more digit to the color precision. In order to support all 256 color values per channel.
I'll do it on the next deploy.
But I don't want to add more than that so I don't increase filesize when not necessary.
Would that be enough?

**Comment by bodymovin** [comment]
fixed and uploaded

**Comment by ferusinfo** [comment]
Hey again. I am reopening the issue, taken that the colors that we are rounding to 3 decimal places are wrong.

Taken the same example (json attached to this comment), the colors arrays are different. For text layers, that previously had 2 decimal places, the third digit is represented differently than the value described in the shape layer colors array, even that we are setting the same color there.

Text layer: `fc: [1, 0.899, 0.302]`
Shape layer (more precision): `k: [1, 0.898039215686, 0.301960784314, 1]`

As you can see, the the third digit in the `k` array is different for second color, event thought the 4th digit is 0.

Could you please investigate? I am working on the same aep file that was attached to the first post of this issue.

[animation_issue_rounding.json.zip](https://github.com/airbnb/lottie-web/files/2472879/animation_issue_rounding.json.zip)
