### ISSUE TITLE
Masks not preserved on iOS devices and Safari.

### ISSUE THREAD

**Issue by xelaint** [airbnb/lottie-web#1198]
**Tell us about your environment**
After Effects, Chrome, Apple iPhone 8 Plus (Chrome and Safari browsers), macOS High Sierra (Safari)

* **Browser and Browser Version:**
Chrome Version 68.0.3440.106 (Official Build) (64-bit), Safari Version 11.0.2 (13604.4.7.1.3)
* **After Effects Version:**
15.12 (Build 69)

**What did you do? Please explain the steps you took before you encountered the problem.**
Created masking animation with After Effects and rendered it using Bodymovin.

**What did you expect to happen?**
Masking should be applied to all browsers on all devices as noted in http://airbnb.io/lottie/supported-features.html

**What actually happened? Please include as much _relevant_ detail as possible.**
Works as expected on Chrome and Firefox browser on desktop devices. Safari on desktop, Chrome and Safari on iOS devices do not preserve masks. Animation can be viewed on https://www.graycore.io/services/for-marketers (globe animation)

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/file/d/1AKVpae4qxqUnLvcvf67eczG-9Mam8fuw/view?usp=sharing

![image from ios](https://user-images.githubusercontent.com/15809918/44214532-650a0580-a13e-11e8-9638-93539f86ba41.png)

**Comment by bodymovin** [comment]
Hi, the link doesn't seem to work.
And the drive folder is private.
Can you update them?

**Comment by xelaint** [comment]
@bodymovin hi, the link has been updated and drive made public.

**Comment by bodymovin** [comment]
Him I don't have an iOS device and I'm having trouble debugging this.
Also. the link redirects me to https://www.graycore.io/not-found
But from the project it seems you're using a CC effect: CC Sphere which is not supported by the player.

**Comment by xelaint** [comment]
@bodymovin The link should be working again. I don't believe I am using a CC effect? Where is the CC Sphere being applied? I've only used masks.

**Comment by xelaint** [comment]
@bodymovin I searched the code to find the CC sphere effect, but do not see anything in my file. The only effect I'm using is mask on the problem layer. I've re-attached an updated file.

[marketer-globe-2.aep.zip](https://github.com/airbnb/lottie-web/files/2376143/marketer-globe-2.aep.zip)

**Comment by damienwebdev** [comment]
@bodymovin This can be closed. This is a result of a bug in a down-stream angular package for lottie. This is a result of the <base href="/"> bug creeping back in. You can see the resolution here: https://github.com/chenqingspring/ng-lottie/pull/35

**Comment by bodymovin** [comment]
Nice!
@xelaint can you confirm if this was the issue?

**Comment by xelaint** [comment]
@bodymovin yes, it was the issue. closing!
