### ISSUE TITLE
The Position Expression isn't working again on 5.2.1

### ISSUE THREAD

**Issue by teddymartadinata** [airbnb/lottie-web#1202]
**My AE Assets Contains 2 .ai File, and using only Position Expression with Opacity Keyframe on the other layer**

* **Browser and Browser Version: Chrome V 67.0.3396.99 (Official Build) (64-bit)**
* **After Effects Version: CC 2018**

**What did you do? Please explain the steps you took before you encountered the problem.**
Hi, i just exported this AE project into bodymovin format and already made html files to play it, but the animation not working as supposed to be like in AE (attached the AE project file)

**What did you expect to happen?**
The animation should works like bounce to the top and flippin as the AE Results

**What actually happened? Please include as much _relevant_ detail as possible.**
on my browser seems the logo not bouncing properly, and the spinning animations seems working fine 

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/open?id=1SXkGfYIq-NqkyfofQXveQoQqIYs5vQk4

**Comment by bodymovin** [comment]
Hi, I see it working fine.
Do you have a working link where it fails?

**Comment by teddymartadinata** [comment]
i tried to preview this on https://www.lottiefiles.com/preview : https://drive.google.com/open?id=1G6t9NS57pRsYgefD3xN6kSOmISMcoAJv and nothing happened with the animation.. just like static image

**Comment by bodymovin** [comment]
might be a older player, but the animation seems to work fine with the latest player
