### ISSUE TITLE
Cannot render animation with bodymovin

### ISSUE THREAD

**Issue by Sidstumple** [airbnb/lottie-web#1205]
* **After Effects Version:**
After Effects CC 2018 (15.1.1) 

I made an animation from paths only and wanted to render it using Bodymovin, unfortunately it will not render and I get an error: "unable to execute script at line ..." (The line number keeps changing with every render). Can you tell me what I'm doing wrong?

Link to After Effects file:
https://www.dropbox.com/s/hcxp2rnkhswcyz7/henris.aep?dl=0

**Comment by bodymovin** [comment]
Hi, I finally found the issue.
Some shapes change the number of nodes between keyframes
and some keyframes don't any nodes, which is making the exporter to break.
I'll have it fixed on the next deploy

**Comment by Sidstumple** [comment]
Wow great thanks!
