### ISSUE TITLE
How to make canvas renderer sharp on Retina display

### ISSUE THREAD

**Issue by zadlo** [airbnb/lottie-web#1209]
I need to output the animation to canvas element, but can't find any info how to enable HiDPI support. On svg/html all images are sharp.

Thanks,
Karol

**Comment by zadlo** [comment]
Ok, it seems it's a bug on macOS Safari 11.1.2 (13605.3.8). Testing in chrome everything looks clear and sharp.

**Comment by bodymovin** [comment]
Hi, can you share a link with the issue?
