### ISSUE TITLE
Problems with repeater

### ISSUE THREAD

**Issue by rafaelabp** [airbnb/lottie-web#1210]
* **Browser and Browser Version:**
Chrome v68.0.3440.106
* **After Effects Version:**
v15.1.2

**What did you do? Please explain the steps you took before you encountered the problem.**
I tried to make a really simple loading animation using repeater and it doesnt work.
[https://ibb.co/iCq3se](url)

**What did you expect to happen?**
I was expecting it to be animated as it should.

**What actually happened? Please include as much _relevant_ detail as possible.**
After exporting it, there's no animation, it's a static image like a png. I tried making it without the repeater and it runs fine and as expected. 

**Please provide a download link to the After Effects file that demonstrates the problem.**
[http://fromsmash.com/856f99f3-a642-11e8-b1ff-06d04ae87646](url)

**Comment by bodymovin** [comment]
Hi, it's actually animating, but the start opacity and end opacity of repeaters is not supported.
I have it fixed and will be available on the next build.

**Comment by rafaelabp** [comment]
Thank you very much!
