### ISSUE TITLE
Load multiple object in a lottie canvas

### ISSUE THREAD

**Issue by sbala69gmail** [airbnb/lottie-web#1215]
Hii,

Is it possible to load the object in existing canvas

**Comment by bodymovin** [comment]
Yes, you can pass a `rendererSettings` object with a `context` property when you initiate the animation
You probably also want to pass a property `clearCanvas: false` so you can handle when to clear the canvas.
https://github.com/airbnb/lottie-web/wiki/Renderer-Settings

**Comment by sbala69gmail** [comment]
Thank you @bodymovin  i have another one question. can we able to achieve this in fabric canvas.

**Comment by alexr4** [comment]
@bodymovin do you have more specification for the rendererSettings object ?
I tried to pass the canvas to the object in order to draw them into a same pre-existing canvas but it's always creating a new canvas per animation.

**Comment by alexr4** [comment]
I found the solution. It seems if we want to use a custom canvas for multiple lottie animation we do not need to set a ```container``` object.
