### ISSUE TITLE
Yet another Uncaught TypeError: Cannot read property 'layer' of undefined

### ISSUE THREAD

**Issue by MuhsinFatih** [airbnb/lottie-web#1216]
**Tell us about your environment**
MacOS 10.14 Beta (18A336e). Trying to export for iOS
* **After Effects Version:**
15.1.2
**What did you do? Please explain the steps you took before you encountered the problem.**
 I purchased [this](https://videohive.net/item/150-animated-hand-gestures/9718552) AE project and I am trying to export some of the animations in the project for my teams iOS project. I am not an AE expert, I made some animations before but nothing professional. Could you help me export these animations? 

**What did you expect to happen?**
Animations should look like this:
![image](https://user-images.githubusercontent.com/8341386/44634206-851e9d80-a964-11e8-9a83-10427b6f0b8b.png)

**What actually happened? Please include as much _relevant_ detail as possible.**
They don't render on web preview and I get `Uncaught TypeError: Cannot read property 'layer' of undefined`, and they render like this on [iOS Lottie Preview App](https://itunes.apple.com/us/app/lottie-preview/id1231821260?mt=8):
![image](https://user-images.githubusercontent.com/8341386/44634232-ee9eac00-a964-11e8-82f1-443748b02e70.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
[aep files](https://github.com/airbnb/lottie-web/files/2321992/videohive-9718552-150-animated-hand-gestures.zip) (includes the same file for different AE versions)
 (What I pay for is the licence, not the files so I assume it wouldn't be an issue. Files are already available online)

**Comment by bodymovin** [comment]
Hi, what composition are you exporting?

**Comment by MuhsinFatih** [comment]
Several, but for example `Finger_Thumb_Right > Tap` is one of them
