### ISSUE TITLE
Stop looping the animation

### ISSUE THREAD

**Issue by wonglo** [airbnb/lottie-web#1217]
Hi, im new to coding. 
I've successfully pulled the animation to my website,
but i want my animation to stop looping (stops at end frame), how can i achieve that?

Thanks a lot.

**Comment by bodymovin** [comment]
Hi, do you have a link with your implementation?

**Comment by wonglo** [comment]
what if i want to freeze the end frame of the animation?
I don't want the animation to disappear.

**Comment by bodymovin** [comment]
it won't disappear, it will stop at the last frame

**Comment by wonglo** [comment]
big thanks! i got it.

**Comment by andrefauri** [comment]
Hi! I'm new to coding too and having the same issue. The animation disappears after 1 cycle. The loop parameter is already 'false'.

https://codepen.io/andrefauri/project/editor/ALxdym

**Comment by bodymovin** [comment]
@andrefauri apparently the animation has some extra time where there is nothing visible. Can you check the .aep?

**Comment by andrefauri** [comment]
I don't think so.. If I put the time bar indicator on the last frame it shows my logo all showing up as I wish to set the last frame. I'm new to animation too (haha), but here is the .aep

https://www.dropbox.com/s/j8tmm9w214pcmml/P%C3%A1tio%20Logo%20Animado%204.aep?dl=0

**Comment by bodymovin** [comment]
What composition are you exporting?
`Pátio Logo Animado` duration is 0:00:05:00 , but the pre composition is cut at 0:00:03:19

**Comment by andrefauri** [comment]
True. I adjusted the time of composition and now it's working. Thanks!

**Comment by ezequielleonzybert** [comment]
Hi. Same issue here.

animation.playSegments([420, 610], true);
  animation.addEventListener('loopComplete', ()=>{
    animation.setDirection(-1);
  })
  
  It flashes the first segment frame before changing direction and play it in reverse
