### ISSUE TITLE
Animation is not loading properly on mobile

### ISSUE THREAD

**Issue by juanferdiaz** [airbnb/lottie-web#1218]
I'm on After Effects 15.1.2
Bodymovin 5.2.1
Previewing on Mac (Safari 11.1.1 and Chrome 68.0.3440.106) and Lottie Preview 1.0.4 on iPhone X

I exported the JSON file according to the instructions, when i preview on browser the animation runs perfectly. But when I preview on the iPhone app the animation is not displaying properly, some parts are distorted or not displaying at all. I'm actually new to after effects, and I'm making this for a website, not an app. I attached a ZIP file with the JSON document. Thanks!

[guffogg-red-gold.zip](https://github.com/airbnb/lottie-web/files/2325063/guffogg-red-gold.zip)

**Comment by juanferdiaz** [comment]
Here's a link with the file http://guffogg.staging.wpengine.com/wp-content/themes/uncode-child/liq/indexlogo.html

**Comment by bodymovin** [comment]
Hi, if the issue is with the native player, can you post it in the lottie-ios repo?
If you only need it for web, you shouldn't worry about the lottie-preview app.
