### ISSUE TITLE
Track Matte Not Working

### ISSUE THREAD

**Issue by abardue** [airbnb/lottie-web#1220]
* **Browser and Browser Version:** Chrome 68
* **After Effects Version:** CC 2018

I created a file in after effects that includes track matting. Using bodymovin, I created a .json file and attempted to use it in lottie and found that the track matting was not being applied to the shapes in the file.

.AEP file: https://drive.google.com/open?id=1tKXbJ2sNJGVBHJ8LTgucHlNNOx7AIvjd
.JSON file: https://drive.google.com/open?id=1ViUEcO8bmltt8b7aWeAaYSZdrQr_l0ke

**Comment by bodymovin** [comment]
Hi unfortunately the Set Matte effect is partially supported.
Track Matte has better support. You can try that one out.

**Comment by abardue** [comment]
That explains it! I didn't realize the difference between the two (I'm very new to using after effects). Thank you for your help! :)
