### ISSUE TITLE
canvas render incorrectly but svg render  works well

### ISSUE THREAD

**Issue by kimown** [airbnb/lottie-web#1221]
**Tell us about your environment**

* **Browser and Browser Version:** chrome
* **After Effects Version:** 14.2.1.34

**What did you do? Please explain the steps you took before you encountered the problem.**

When I use `svg` renderer, it works well, then I use `canvas` renderer, it pause suddenly after play three pictures. 

https://codesandbox.io/s/n97x1volyl

![image](https://user-images.githubusercontent.com/7932380/44700942-9bd90780-aabe-11e8-90ef-49d9e26edff7.png)

**What did you expect to happen?**

the effect of canvas renderer should be same as  svg renderer

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

[Archive.zip](https://github.com/airbnb/lottie-web/files/2326436/Archive.zip)

**Comment by bodymovin** [comment]
Hi, svg and canvas don't support the same combinations of masks.
I think the problem is related to stacking multiple subtracting masks in canvas.

**Comment by bodymovin** [comment]
Usually, the `canvas` renderer is more performant, but it depends on many factors, like the type of animation, browser, size of workspace, size of assets.
I would use the `canvas` renderer if you don't need the extra features that the `svg` renderer provides and if you are not using very large assets.

**Comment by Linyan-ma** [comment]
@bodymovin I have exactly the same problem, but in our case I have to use canvas renderer. Can you explain in detail?
When I use svg renderer, it works well, when I use canvas renderer,The pictures are gone.

here is my demo exported:
[2.zip](https://github.com/airbnb/lottie-web/files/3002903/2.zip)

**Comment by bodymovin** [comment]
@Linyan-ma track-matte masks are not supported by the canvas renderer

**Comment by Linyan-ma** [comment]
Thanks for your reply. I tried subtracting masks，there is the same problem as the issuer, is there any solution in canvas renderer?

**Comment by kimown** [comment]
@Linyan-ma 

Can you tell me your scene, why do you insist on `canvas`,  also I am from JiangSu too. (^_^)

**Comment by Linyan-ma** [comment]
@kimown hello there.cause i use lottie in the node environment. why dont we use chinese directly.haha

**Comment by kimown** [comment]
@Linyan-ma 

你们场景是制作视频吗?建议使用puppeteer, 不推荐使用node-canvas, 字体这块是个很麻烦的问题

**Comment by Linyan-ma** [comment]
是的，我们想对视频进行简单编辑。谢谢推荐，我尝试一下puppeteer。我想请教问题的话可以发163邮件给您吗^_^

**Comment by kimown** [comment]
@Linyan-ma 

当然可以

**Comment by headfire94** [comment]
> @kimown why dont we use chinese directly.haha

@Linyan-ma because i can't understand now what solution was :(
