### ISSUE TITLE
Animated SVG is too fast on the browser (:

### ISSUE THREAD

**Issue by bekircanaydin** [airbnb/lottie-web#1222]
Hello there! I have an issue with the Animated SVG. SVG animation is too faster than after effects project. I take a look on after effects cc 2018 it's okay but on the browser it's too fast. How can i fix this ? Thanks...

**Browser and Browser Version: Google Chrome 68.0.3440.106 64 Bit**

**After Effects Version : After Effects CC 2018**

**When im export the html and json files SVG is not the same with the after effects project (its faster than Ae project)**

**Ae and SVG files:**

**https://www.dropbox.com/s/imxqgix6vc8dcfr/Aeandsvg.rar?dl=0**

**Best Regards!**

**Comment by duzst** [comment]
I solved the issue i changed the .playSpeed=1 to .playSpeed=0.3 

THANKS!

**Comment by duzst** [comment]
If anyone got this issue in future [https://i.hizliresim.com/AzvpMr.png](url) change this value

Hope someone can benefit from it :)
