### ISSUE TITLE
Cannot export 3D rotated shapes from AI

### ISSUE THREAD

**Issue by EnixCoda** [airbnb/lottie-web#1223]
**Tell us about your environment**
macOS 10.13.6, Adobe After Effects CC 2018, Adobe Illustrator CC 2018

* **Browser and Browser Version:**
Chrome v69
* **After Effects Version:**
CC 2018

**What did you do? Please explain the steps you took before you encountered the problem.**
In Illustrator:
1. Create a rectangle
1. Rotate it with `Effects -> 3D -> rotate`
1. Save as `.ai` file

In After Effects:
1. Import the `.ai` file as `composition`.
1. Right click the `.ai` file, `Create -> Create shapes from Factor Layer`
1. Export with bodymovin with `demo` in settings is checked.

Open the exported html file with Chrome.

**What did you expect to happen?**
The output demo should looks the same as in AE preview window:
![image](https://user-images.githubusercontent.com/7480839/44826057-efbf2a00-ac3f-11e8-9632-544929dcc126.png)

**What actually happened? Please include as much _relevant_ detail as possible.**
In browser, it looks like this:
![image](https://user-images.githubusercontent.com/7480839/44826067-fb125580-ac3f-11e8-989e-3a9bf0363e8c.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
[AI3DRotate.zip](https://www.dropbox.com/s/qlgu65i8k58w8fn/AI3DRotate.zip?dl=0)

**Comment by bodymovin** [comment]
Hi, when you convert ai layers to shapes, sometimes it adds an unnecessary extra path and a merge path. Can you try removing them from the layer contents?

**Comment by EnixCoda** [comment]
@bodymovin Hi! I removed `Contents -> Group 1 -> Group 1 -> Path 1 & Path 2` and it works!

Thank you!
