### ISSUE TITLE
gotoAndStop doesn't always seek to frame correctly

### ISSUE THREAD

**Issue by kjlubick** [airbnb/lottie-web#1224]
**Tell us about your environment**

* **Browser and Browser Version:** Chrome 68 and Firefox 52.8.1
* **After Effects Version:** Unknown

**What did you do? Please explain the steps you took before you encountered the problem.**
See https://jsfiddle.net/2wqt5omk/6/ for reproducing test case.

**What did you expect to happen?**

I expected to see the animation render frame 400, which looks like 
![image](https://user-images.githubusercontent.com/6819944/44856956-b6d18600-ac3c-11e8-801d-7bbb64e38596.png)

**What actually happened? Please include as much _relevant_ detail as possible.**

The animation stays blank.  What's interesting is an `<svg>` with several `<g clip-path>` are created, they just don't seem to be visible (?)

Additionally, if I start the animation playing and then tell it to go to frame 400, it does that properly. https://jsfiddle.net/2wqt5omk/10

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.lottiefiles.com/428-blahblah
context: I did not make this file.  I was testing a bunch of lottie files and noticed this one rendered strangely.

**Comment by bodymovin** [comment]
Fixed the issue in version 5.3.0
Effects and masks were being rendered in the inverse order.
But frame 400 of the animation actually looks like this:
![screenshot](https://user-images.githubusercontent.com/11096607/45602777-f85e8100-b9f1-11e8-8bf0-abbe54ddc8f9.jpg)
Thanks!

**Comment by wrbing728** [comment]
What is the cdn url of version 5.3.0 please?  I only find cdn url of bodymovin and the newest is https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.13.0/bodymovin_light.js

**Comment by bodymovin** [comment]
@wrbing728 there is not yet a cdn version of the player. It's still expecting approval from cdnjs
https://github.com/cdnjs/cdnjs/pull/12905
