### ISSUE TITLE
SSR: Uncaught TypeError: Cannot read property 'layer' of undefined

### ISSUE THREAD

**Issue by TanelVari** [airbnb/lottie-web#1225]
I'm using https://github.com/chenqingspring/react-lottie which has lottie-web as a dependency (the latest). Everything runs fine locally however after building and running from server, animation data is passed not as object but as a path to json data file (`AnimationItem.prototype.configAnimation = function (animData) { ... }`). That's when the TypeError kicks in because function excpects an object not a reference to the file. I don't know if this is something to do with the building or something with the lottie-web source code...

**Comment by bodymovin** [comment]
Hi, do you have a link with the implementation?

**Comment by TanelVari** [comment]
Issue resolved using json-loader and webpack config
