### ISSUE TITLE
mask[mask-type="luminance"] breaking animation on IE/Edge

### ISSUE THREAD

**Issue by danielocdh** [airbnb/lottie-web#1229]
**Tell us about your environment**
Windows 10 x64 fully updated

* **Browser and Browser Version:**
Microsoft Edge 42.17134.1.0
IE 11.228.17134

* **After Effects Version:**
N/A

**What did you do? Please explain the steps you took before you encountered the problem.**
Just play the animation on IE or Edge

**What did you expect to happen?**
Animation to be shown just as in chrome/firefox

**What actually happened? Please include as much _relevant_ detail as possible.**
The animation is not shown. 
If I remove (with devtools) the last mask inside defs inside the svg (mask[mask-type="luminance"]) it works correctly

**Please provide a download link to the After Effects file that demonstrates the problem.**
I don't have the source file, just the resulting animation. I uploaded a simplified version of the animation here: https://jsfiddle.net/njwbekt2/1/

**Comment by bodymovin** [comment]
It looks like the mask is of type inverted alpha and not luminance, can you confirm if that is correct?

**Comment by danielocdh** [comment]
@bodymovin not really as I don't have the source for this one

**Comment by kudanai** [comment]
Hello! Since this issue has been stale for quite a while, I'm going to close it. Please re-open or file a new one if necessary if relevant.
