### ISSUE TITLE
can't export images

### ISSUE THREAD

**Issue by richiepu** [airbnb/lottie-web#1231]
sorry, @bodymovin
I can't export images in bodymovin

- windows 10
- AE 2018 CC
![image](https://user-images.githubusercontent.com/8892158/45358202-3ecf6c80-b5fb-11e8-9105-82ac843c31bd.png)
![image](https://user-images.githubusercontent.com/8892158/45358206-43942080-b5fb-11e8-811b-bdaebbafe941.png)

**Comment by bodymovin** [comment]
Hi, nto sure what could be going on.
Are you getting any error at all?

**Comment by bodymovin** [comment]
Closing.
Reopen if needed
