### ISSUE TITLE
The animation in json file didn't add up to the ae file ( Dash )

### ISSUE THREAD

**Issue by Willy-Chuang** [airbnb/lottie-web#1232]
Hi there, I'm using After Effect 2018cc on a macOS High Sierra 10.13.6

ISSUE:
I'm not sure if the issue occurred due to the usage of Dashes function under Stroke ( Assuming it is )
In this project I used Trim Path,Size,Position and Rotation, which all works just fine before I add in Dashes.

Here is what it reveals with Dashes
https://www.lottiefiles.com/share/FHYwVi

And after I remove Dashes
https://www.lottiefiles.com/share/8jHhyt

This is the actual aep.file
https://drive.google.com/file/d/1kXWwZUkwAey9C7JgEju7Wxyvlm4TSN0A/view?usp=sharing

thank you for your patience.

**Comment by bodymovin** [comment]
Hi, indeed it seems it's related to using dashes and inverting start and end values of trim path.
I had never noticed that behavior.
I'll try to take a look at it and see if I can fix it

**Comment by ws1895** [comment]
@bodymovin 
Thank you for your update
**FIX: dashed lines were not resetted in some scenarios**

**Comment by bodymovin** [comment]
@ws1895 did this fix your case?

**Comment by kudanai** [comment]
Hello! Since this issue has been stale for quite a while, I'm going to close it. Please re-open or file a new one if necessary if relevant.
