### ISSUE TITLE
Canvas renderer yields wrong stroke width on HiDPI

### ISSUE THREAD

**Issue by ishitatsuyuki** [airbnb/lottie-web#1233]
**Tell us about your environment**

* **Browser and Browser Version:** Firefox Nightly on Linux, Chromium 69 on Linux
* **After Effects Version:** CC

**What did you do? Please explain the steps you took before you encountered the problem.**

Play the attached JSON file. It uses a stroke path with width for the text revealing effect.

**What did you expect to happen?**

The stroke should be almost the same height as the text.

**What actually happened? Please include as much _relevant_ detail as possible.**

On SVG renderer, this works as expected.
On canvas renderer and this WQHD monitor with 2x HiDPI, the stroke is double the width.

**JSON file**: https://gist.github.com/02426c878942e79d52e25215e33f5e85

**Comment by bodymovin** [comment]
Well, after spending the weekend thinking how to fix it and working on a big refactor of shape rendering in canvas, version 5.3.0 now supports scaling strokes correctly :)
