### ISSUE TITLE
SVG viewBox on iOS vs Desktop

### ISSUE THREAD

**Issue by storywise** [airbnb/lottie-web#1238]
Hi, not to long ago i discovered the project, loving it so far!
Have got everything working as expected, though some questions remain:

- When viewing a fullscreen SVG animation on a mobile device (meet, not slice), i notice there is 'overshoot' of the composition bounding box. The animation viewbox is 1280x1280, and it scales nicely retaining its square, keeping it in the middle x and y as expected. However this only happens on desktop, on mobile it still retains it square but also shows what goes on in the negative coordinates of the composition, you could say desktop=overflow:hidden and mobile=overflow:visible.

My questions are, is this a feature? Can i sync this behavior between devices/browsers? 
// Just noticed that Safari desktop also shows the 'overshoot', firefox and chrome keeps it hidden

Slice does not do the same trick, keeping the square meet viewbox is perfect. With the overshoot feature as seen in various browsers, it allows for a more neat treatment of the additional space which various device screens/dimensions present.

--

Another question is, are cuepoints (like in oldtime Flash videos) supported? For example an animation throws a capturable Javascript event at certain marker times within the AE animation.

Thanks for your time and patience.

**Comment by storywise** [comment]
I seem to understand whats happening with the first issue, the clip-path="url()" attribute on the first element within the 'svg > g' is not understood by all browsers. So sometimes the viewbox is masked, and sometimes it isnt.

**Comment by bodymovin** [comment]
Hi, can you share a link with the clip issue?

**Comment by kudanai** [comment]
Closing this for now since it's been a while. Please feel free to re-open it if it's still relevant.
