### ISSUE TITLE
The path animation become linear which one frame change at a time.

### ISSUE THREAD

**Issue by Danjuanlab** [airbnb/lottie-web#1239]
I’m currently doing a cartoon animation, some of which is the engine rotation animation of the airplane. I dragged the engine into 5 separate paths in the AI and then animated it in the AE. The animation is frame animation, and the keyframes are similar (1,1,1,2,2,2,3,3,3,4,4,4...). There is no problem in previewing in AE, but when I export it as a json file, I saw the demo web that the animation speed is abnormal, and the animation changes are always weird. So I adjust the frame length and observe the result. I found that the frame change is only 1 frame, but the animation does change linearly when drawn in the web page. I changed the playback speed of the animation to 0.2, and the change became more obvious. I don't know if this is a bug or if I have a problem with the export operation. If anyone knows, please give me a reply.
![keyframe](https://user-images.githubusercontent.com/42509669/45586129-0a71ee00-b924-11e8-8bac-7aaf02bab317.png)
![0 2speed](https://user-images.githubusercontent.com/42509669/45586133-12ca2900-b924-11e8-959d-1176ee32ba7f.gif)
[aep and json.zip](https://github.com/airbnb/lottie-web/files/2385673/aep.and.json.zip)

**Comment by Danjuanlab** [comment]
> Hi, I'm not sure I understand the issue, but if you don't want the animation to interpolate between subframes you can set `anim.setSubframe(false)` in the browser and it should work fine.

After adding anim.setSubframe(false), there is no longer a interpolate between the two frames. But this is just a part of the whole animation. If I don't have an intermediate difference for the animation, then other part will also be affected, so it seems that it is not a sensible solution.

**Comment by bodymovin** [comment]
Can you use hold keyframes in after effects then?

**Comment by Danjuanlab** [comment]
The hold keyframes really solved this problem! Thank you, Teach me new tip.
