### ISSUE TITLE
Gradeint Isuue

### ISSUE THREAD

**Issue by guestywaste** [airbnb/lottie-web#1240]
Hi Guys.

A few months ago I animated some pre loaders with gradients changes.  its was working just fine using lottie, now after 4 months I've reopened the file and made some updates (no colour changes) and no none of the gradients are working, im just getting solid colours, any help would be awesome.
[Pre_Loader_may_v4c.aep.zip](https://github.com/airbnb/lottie-web/files/2389503/Pre_Loader_may_v4c.aep.zip)

**Comment by bodymovin** [comment]
Hi, this should be fixed now.
