### ISSUE TITLE
Text resize vertical alignment?

### ISSUE THREAD

**Issue by Adam-Burke** [airbnb/lottie-web#1242]
Is it possible to change how the text resize works in regards to its alignment. It seems too resize from the top and so if you have two text elements horizontally positioned and one resizes it looks strange. Is there a way (other than expressions) to keep it vertically centered or resize along the baseline when text resizes?

**Comment by bodymovin** [comment]
Hi, unfortunately there is not.
Probably the best solution is using expressions.
