### ISSUE TITLE
Scaling animation not fully exporting

### ISSUE THREAD

**Issue by DrSuave** [airbnb/lottie-web#1243]
I'm running MacOS 10.13.6, with Chrome Version 69.0.3497.100 (Official Build) (64-bit) and After Effects version 15.

I made an animation with a few seperately animated components. One component is animated to scale to a certain size and then gently scale up and down. Here's a screenshot of the graph view:
<img width="632" alt="screen shot 2018-09-18 at 6 34 05 pm" src="https://user-images.githubusercontent.com/1854222/45705450-8b71f500-bb71-11e8-9d36-5b926c282cdd.png">
This works fine in After Effects and when exported as a .mov, but when exported with Bodymovin the scaling stops at the 04s mark. I expected the scaling to be exported in bodymovin the same way it is to mov.

[Here's the AE file packaged with dependencies.
](https://thisiswilf.com/Githubbug/package.zip)
Thanks

**Comment by bodymovin** [comment]
I can't check it right now, but it seems that all keyframes have the same value.
If that's the case, unfortunately the player doesn't support that scenario.
Can you alternate between `100%` and `99.9%` between keyframes and see if it works?

**Comment by DrSuave** [comment]
That sorted it! Thanks a lot. Pretty in love with this plugin.
