### ISSUE TITLE
Bodymovin Interface Error

### ISSUE THREAD

**Issue by aakey7** [airbnb/lottie-web#1246]
I am having an issue when I open the bodymovin extension and I cannot select a destination folder or the settings. 

This means I cannot export the file as it keeps asking to select destination folder. I have tried restarting, reopening after effects but the same issue keeps happening.

I have the most up to date version. Is there anything known that could cause this type of behaviour?

**Comment by bodymovin** [comment]
Hi, I've never seen this behavior.
Do you have both the latest version of AE and latest version of bodymovin?

**Comment by aakey7** [comment]
I have the latest versions. It just started happening all of a sudden. It
might be related to operating system. Weird though as bodymovin loads and
it shows the comp and it allows you to select it, but just not the options
or destination folder

**Comment by aakey7** [comment]
Mac. It has worked fine in the past, so i will try uninstall and reinstall
and hope that fixes it

**Comment by bodymovin** [comment]
ok, let me know if it works.

**Comment by yigitersoy87** [comment]
Hi, i got the same issue, open zxp installer and reset bodymovin plugin. It worked for me.

**Comment by jaredclarkgay** [comment]
Just ran into same issue, and ^ this exact thing worked for me. Thanks!

**Comment by surya-finch** [comment]
> Hi, i got the same issue, open zxp installer and reset bodymovin plugin. It worked for me.

You saved my day!

**Comment by 1213gdg** [comment]
I have the same issue. what do you mean by reset? does it mean uninstall/install again? It didn't work for me :(
