### ISSUE TITLE
help , animation cannot be showed blank html 

### ISSUE THREAD

**Issue by kerolesthrwat** [airbnb/lottie-web#1247]
[bodymovin.zip](https://github.com/airbnb/lottie-web/files/2396500/bodymovin.zip)

its cannot be showed or load json file any help

**Comment by bodymovin** [comment]
Hi, where did you get that minified version of the player?
It's missing part of the code.

**Comment by kerolesthrwat** [comment]
[body_movin v2.zip](https://github.com/airbnb/lottie-web/files/2396769/body_movin.v2.zip)
 i put it from codepen example it was minified , 
now i put it from cdnjs but it give me 
""Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.""

**Comment by bodymovin** [comment]
can you try using this player?
https://github.com/airbnb/lottie-web/tree/master/build/player

**Comment by kerolesthrwat** [comment]
![1](https://user-images.githubusercontent.com/27146201/45751034-62a13c80-bc11-11e8-966f-2a82efb3b9fb.png)
it give me same one at send of the http request is it need to be a server to run ?
i downloaded codepen example  https://codepen.io/airnan/project/editor/ZeNONO
the basic one and just run it and give me same problem

**Comment by bodymovin** [comment]
yes, you need to run the code through a web server

**Comment by kerolesthrwat** [comment]
thnaks for your effort , i am tried to put the json file to js file and it worked but with black color only and some shapes differences  
![123](https://user-images.githubusercontent.com/27146201/45760946-896c6c80-bc2b-11e8-974d-9ff72819eac0.png)

**Comment by kudanai** [comment]
Hey there. As this issue has been stale for some time, I'm closing it. If this issue is still present in more a more recent version, please feel free to re-open it or create a new issue.
