### ISSUE TITLE
Gradient not working

### ISSUE THREAD

**Issue by mauriciotpo** [airbnb/lottie-web#1248]
Hi!
I'm having some troubles with gradient export. For some reason when i export the data.json, it doesn't recognise the gradient. Am i doing something wrong here? Thank you!

Here goes a screenshot:

<img width="2347" alt="screen shot 2018-09-19 at 18 58 26" src="https://user-images.githubusercontent.com/35453431/45771987-7f079e00-bc3e-11e8-8692-ca338d2d9887.png">

**Comment by bodymovin** [comment]
can you update to version 5.3.1?
there was a gradient issue on v 5.3.0

**Comment by mauriciotpo** [comment]
I got it the problem!

I was using GRADIENT RAMP, instead i used GRADIENT FILL. Them i had the trouble of the gradient being black to white, i saved the changes on AE and it's working fine! 

Issue solved :D
<img width="2341" alt="screen shot 2018-09-19 at 19 13 06" src="https://user-images.githubusercontent.com/35453431/45772634-289b5f00-bc40-11e8-8528-4ceeb388f1ca.png">
