### ISSUE TITLE
ph_onboarding draws incorrectly in 5.3.1, is fine in 5.2.1

### ISSUE THREAD

**Issue by kjlubick** [airbnb/lottie-web#1250]
**Tell us about your environment**

* **Browser and Browser Version:** Chrome Version 69.0.3497.92 (Official Build) (64-bit)
* **After Effects Version:** Unknown

**What did you do? Please explain the steps you took before you encountered the problem.**
Animation drawing correctly with 5.2.1: https://jsfiddle.net/nfyu5k42/1/

Animation drawing incorrectly with 5.3.1: https://jsfiddle.net/4nh05yfg/

**What actually happened? Please include as much _relevant_ detail as possible.**

Notice the colored hexes around the people are white with some artifacts in 5.3.1

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.lottiefiles.com/1964-ph-onboarding2 I didn't make this, just noticed the behavior difference.

**Comment by bodymovin** [comment]
Hi, version 5.3.1 is the correct one.
Version 5.2.0 had an issue with animated gradients that was fixed from version 5.2.1
