### ISSUE TITLE
3D layer orientation export problem

### ISSUE THREAD

**Issue by PavelPMarts** [airbnb/lottie-web#1252]
**Tell us about your environment**
AE 15.1.2, Bodymovin 5.1.3, MacOS 10.13.6
* **Browser and Browser Version:**
Chrome 69.... the latest one
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**
I have made an animation, flat. It was drawn in AI first and then animated in AE.
The scene successfully rendered with BodyMovin 4.10.2 and with minor bugs with 5.3.1

Then I had to make a new composition and add the flat composition there to change its Orientation in 3D. 

![screen shot 2018-09-20 at 21 32 25](https://user-images.githubusercontent.com/43453980/45845381-db40ef80-bd1c-11e8-9323-8ac254f1a725.png)

**What did you expect to happen?**

I expected to see well-done perspective view animation, the same as it looks in AE and if I render a video.
![screen shot 2018-09-20 at 21 32 07](https://user-images.githubusercontent.com/43453980/45845383-db40ef80-bd1c-11e8-9e9d-d7a10d79643d.png)

**What actually happened? Please include as much _relevant_ detail as possible.**
But once rendered with BodyMovin it completely changed the proportions and perspective. You can see that in screenshots. 

![screen shot 2018-09-20 at 21 32 35](https://user-images.githubusercontent.com/43453980/45845379-db40ef80-bd1c-11e8-881f-9ff676d295b0.png)

Has someone come across this? Thank you so much!
**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by kudanai** [comment]
Hey there. As this issue has been stale for some time, I'm closing it. Please feel free to re-open it or create a new issue.
