### ISSUE TITLE
No png images on Canvas Render

### ISSUE THREAD

**Issue by aakey7** [airbnb/lottie-web#1254]
When I use canvas render, none of my images are showing up. Is this normal behaviour? or is there a solution to this happening?

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by aakey7** [comment]
Here it is. It seems to show properly in svg mode, but not in canvas mode. I need it as a canvas though as I am trying to convert it to a screenshot / png. which can be done with plain svg.

[Goal Alert.zip](https://github.com/airbnb/lottie-web/files/2408535/Goal.Alert.zip)

**Comment by aakey7** [comment]
Here is also the link with it set to 'canvas'. It works fine when svg, but i need canvas for my project

http://kick-push.co.uk/goal/canvas.html

**Comment by aakey7** [comment]
Any ideas why they would not show in the canvas render?

**Comment by bodymovin** [comment]
can you try the latest version? 5.3.3
this should be fixed

**Comment by aakey7** [comment]
It seems to be a bit better. A weird one though, it doesn't seem to scale the svg image anymore? (when you change team)

http://kick-push.co.uk/goal/canvas.html

However it does on mobile devices (iphone), but it won't show .webp

Any idea why it renders so different across different devices?

**Comment by bodymovin** [comment]
Hi, I'm not sure I follow. What do you mean by the svg image?
Regarding webp, this is the current support:
https://caniuse.com/#feat=webp

**Comment by kudanai** [comment]
Hey there. As this issue has been stale for some time, I'm closing it. Please feel free to re-open it or create a new issue.
