### ISSUE TITLE
Is there an event or way to tell if all external images have been loaded into a lottie animation?

### ISSUE THREAD

**Issue by thegeminisociety** [airbnb/lottie-web#1255]
I know there is "data_ready" event but this does not account for image load. Would be great to receive an event after all images have been successfully loaded into the lottie animation, is there a way? Thanks!

**Comment by kwilliams-curago** [comment]
There is an event triggered on the animation.

https://github.com/airbnb/lottie-web/blob/3c31c2fe8bfdbd665ba87bcac69e54cf6cf0db2a/build/player/bodymovin.js#L8464

Usage: 

```
animation.addEventListener('loaded_images', () => { 
    //
});
```

**Comment by gujral1997** [comment]
@kwilliams-curago @thegeminisociety  
This event is getting fired before the image gets loaded completely in one of my cases. Can you please help?

**Comment by kvzivn** [comment]
> @kwilliams-curago @thegeminisociety
> This event is getting fired before the image gets loaded completely in one of my cases. Can you please help?

I have the same problem.
