### ISSUE TITLE
multiple animations picked randomly

### ISSUE THREAD

**Issue by kiriss91** [airbnb/lottie-web#1256]
I have 3 animations for 1 object and I want them to be picked randomly.
I am not sure what is the best way to do it...

I could have 3 .json files and randomly loop between them...
..or I could have the animations run from frame [0-100] [100-200] [200-300] and when the animation reaches frame 100/200/300 to randomly jump to frame 0/100/200.
Is any of these options possible?

I couldn`t find any similar examples... Any suggestions are welcome.

**Comment by bitwisp** [comment]
How can I add an `addEventListener` that calls up a function when the animation reaches a certain frame?
I could not figure out how the enterFrame or onEnterFrame works...

This works, but I have 0 control where the animation jumps.
```
var params = {
        container: document.getElementById('lottie'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        animationData: animationData
    };

    var anim = lottie.loadAnimation(params);
		
	function func1() {
		anim.playSegments([[0, 100]], true)
	}
	function func2() {
		anim.playSegments([[100, 200]], true)
	}
	function func3() {
		anim.playSegments([[200, 300]], true)
	}
	function random(){
		var i  = Math.floor(Math.random()*20)%4;
		if(i<=0) return random();
	return i;
	}
	function execute(){
		var i = random();
		eval('func'+i+'()');
	}
	
	anim.addEventListener('DOMLoaded', execute);
	anim.addEventListener('loopComplete', execute);`
```
For example if I have 2 functions execute1(); execute2(); when animation reaches frame 100/200 to execute1(), when animation reaches frame 300/400 to execute2();

**Comment by bodymovin** [comment]
you can use the `enterFrame` event to check when the animation reaches a certain frame.

**Comment by bitwisp** [comment]
> you can use the `enterFrame` event to check when the animation reaches a certain frame.

Can you give me a short example...  I could not make it work.

**Comment by bodymovin** [comment]
if you have an implementation uploaded somewhere I can take a look.

**Comment by bitwisp** [comment]
Just a simple example. When frame = 10 to execute function animation2();
I don`t understand how this works... anim.addEventListener('enterFrame', ...); ?

**Comment by bodymovin** [comment]
the `enterFrame` event passes an object to the function as the first argument.
that object has a property with the current frame you can use to trigger animation2

**Comment by bodymovin** [comment]
````javascript
var params = {
        container: document.getElementById('lottie'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        animationData: animationData
    };
 
var anim = lottie.loadAnimation(params);
function execute(ev){
		console.log(ev)
}
anim.addEventListener('enterFrame', execute);
````
try that

**Comment by bitwisp** [comment]
My message might have been missunderstood. Here is a more complex example.
I have 2 animations for email and 2 animations for documents.
When the current frame equals to 100 or 200 I want it to randomly jump to 200 or 300 and continue to play. When current frame equals 300 or 400 I want it to randomly jump to 0 or 100 and continue to play.
```
    var params = {
        container: document.getElementById('lottie'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        animationData: animationData
    };
    
    var anim = lottie.loadAnimation(params);
    	
    function email1() {
    	anim.playSegments([[0, 100]], true)
    }
    function email2() {
    	anim.playSegments([[100, 200]], true)
    }
    function doc1() {
    	anim.playSegments([[200, 300]], true)
    }
    function doc2() {
    	anim.playSegments([[300, 400]], true)
    }
    function random(){
    	var i  = Math.floor(Math.random()*20)%4;
    	if(i<=0) return random();
    return i;
    }
    function jumpToDoc(){
    	var i = random();
    	eval('doc'+i+'()');
    }
    function jumpToEmail(){
    	var i = random();
    	eval('email'+i+'()');
    }
```
and now I should use a addEventListener?

**Comment by bodymovin** [comment]
yes, you can use the enterFrame or the loopComplete event

**Comment by Preethi2706** [comment]
@kiriss91 I am trying to use multiple animations which should be picked randomly but not run them frame wise . I have them as separate JSON files . Did you implement like me? If not , how did you implement the above? Could you pls share the code you used?

**Comment by kiriss91** [comment]
> m

Here is the code: https://codepen.io/kiriss91/pen/MWbVbmr
I have used only one. JSON and I have played random segments.

On this one, I have used multiple .json files, they are picked randomly and looped twice if I remember well...
https://codepen.io/kiriss91/pen/MWrJNow

**Comment by kiriss91** [comment]
> @kiriss91 I am trying to use multiple animations which should be picked randomly but not run them frame wise . I have them as separate JSON files . Did you implement like me? If not , how did you implement the above? Could you pls share the code you used?
> 
> Sorry to post this in a closed issue. I am in search of the code to implement multiple animations to get picked randomly .

Here is the code: https://codepen.io/kiriss91/pen/MWbVbmr
I have used only one. JSON and I have played random segments.

On this one, I have used multiple .json files, they are picked randomly and looped twice if I remember well...
https://codepen.io/kiriss91/pen/MWrJNow

**Comment by Preethi2706** [comment]
@kiriss91 Thank you for your response! Will we able to Edit the whole animation (the combinations of  multiple .JSON files) as a single video? 

In your code , I could see all the animations are displayed as separate DIV . so I was wondering if we can display it as single video to the user?

**Comment by Preethi2706** [comment]
@bodymovin Would appreciate your inputs on the above too!

**Comment by Preethi2706** [comment]
@kiriss91 I referred your code from here : https://codepen.io/kiriss91/pen/MWrJNow on using multiple JSONs to be picked randomly. It was really helpful  , Thank you! My scenario in my application is also similar , except the fact that when multiple JSONs load randomly , it would also take a part of user given text and display that in the JSON as animation. For instance , when user gives us 10 lines to display , we will want to separate into 2 lines per animations and display it.  

Do you think its possible to add dynamic text when looping through animations randomly ? 

@bodymovin If you can help me here pls.

**Comment by kiriss91** [comment]
I am not a developer, but probably it is possible...
This is a closed post; you should create a new one. 
I don`t know if anyone will check this one.

**Comment by Preethi2706** [comment]
Created a new issue : https://github.com/airbnb/lottie-web/issues/2755

Thank you for your guidance @kiriss91
