### ISSUE TITLE
Laggy when dimensions enlarged

### ISSUE THREAD

**Issue by Sawyeraltman** [airbnb/lottie-web#1257]
**Tell us about your environment**
macbook pro 2017, latest osx

* **Browser and Browser Version:** Updated firefox and chrome both
* **After Effects Version:** cc 2018

**What did you do? Please explain the steps you took before you encountered the problem.**

I am trying to animate in a full-viewport lottie. It activates on scroll: upon entering a threshold, the file begins playing. When the screen dimensions are small, there is no lag. Where I raise browser viewport dimensions, though, the file skips frames and lags up the whole browser (such that other code is not even being executed as the browser tries to catch up).

I know my file size isn't exactly small (275kb), but surely this is unexpected for a 1-second clip. I can hear the fans in my machine going nuts.

**Please provide a download link to the After Effects file that demonstrates the problem.**

See attached.
[Archive.zip](https://github.com/airbnb/lottie-web/files/2406989/Archive.zip)

How can I get it to quit lagging? Why does the screen dimension matter?

Thanks,
Sawyer

**Comment by Sawyeraltman** [comment]
I solved my problem by switching from html to a canvas renderer. Any sense what may have been afoot?

**Comment by bodymovin** [comment]
Hi, canvas for this type of animations is more performant indeed.
Regarding it being laggy on svg, I've tested it on 2 computers and it works well even enlarging the screen.
But if you want to improve performance I would try to reduce the amount of vertices (which are around 3000 right now).
For example your layers `Mailbox/HIW 1 Deconstructed Outlines` and `Hand/HIW 1 Deconstructed Outlines` seem to have a big amount of unnecessary extra vertices that you could remove.
If you have a link of your implementation with the scrolling event, I can take a further look.

btw, filesize and duration is not necessarily an indication of performace. Performance is more related to what is being drawn and how.

**Comment by Sawyeraltman** [comment]
Hi Hernan,

Facing this problem again, suddenly. Performance was great with canvas, I left it alone for a while, came back, and it was weak again. The entire page becomes choppy.

At small resolutions, however, it works great. Quite a conundrum.

I went through and deleted as many vertices as I could from the 3 1-second segments I'm rendering at fullscreen. See attached:

[Archive.zip](https://github.com/airbnb/lottie-web/files/2448605/Archive.zip)

What could be going on here?

Thanks,
Sawyer
