### ISSUE TITLE
Drop frames for animation play

### ISSUE THREAD

**Issue by zaiMoe** [airbnb/lottie-web#1264]
* **Browser and Browser Version:**
69.0.3497.100

**What did you do? Please explain the steps you took before you encountered the problem.**
http://wow.techbrood.com/fiddle/32208

I replace the  bodymovin version `<script src="/uploads/170101/bodymovin.js"></script>` with `https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.13.0/bodymovin.js` in the demo above，then it not working properly。

**Comment by bodymovin** [comment]
version 4.13.0 is pretty old
can't you use a newer one?

**Comment by zaiMoe** [comment]
I use the latest form ‘build/player/lottie.js’, but the problem still exists.
Only the first time is normal.
look this gif
![test](https://user-images.githubusercontent.com/31397840/46158733-14dfa080-c2b1-11e8-9845-b86ceced736b.gif)

**Comment by bodymovin** [comment]
Can you share the .aep?

**Comment by zaiMoe** [comment]
sorry，This demo is not written by me，I will try to contact the author.

**Comment by bodymovin** [comment]
Found the issue.
I'll fix it during the weekend.

**Comment by zaiMoe** [comment]
OK， thanks

**Comment by bodymovin** [comment]
Fixed on version 5.3.2
