### ISSUE TITLE
No Gradient in JSON after exporting  

### ISSUE THREAD

**Issue by eatlovecode** [airbnb/lottie-web#1265]
**Tell us about your environment**
- Windows 10 Home
**Browser and Browser Version:**
Chrome and Version 69.0.3497.100 (Official Build) (64-bit)
**After Effects Version:**
15.1.2 - CC 2018 
**Bodymovin Version**
5.3.1
**What did you do? Please explain the steps you took before you encountered the problem.**
1. Created a new composition 
2. Create a shape
3. Apply Effect- _4-Color Gradient_
4. Save File
[AEPfile.zip](https://github.com/airbnb/lottie-web/files/2423356/AEPfile.zip)
5. Windows-> Extension-> Bodymovin
6. Settings (Demo) of Bodymovin
7. Render
[DemoAndJSON.zip](https://github.com/airbnb/lottie-web/files/2423355/DemoAndJSON.zip)
**What did you expect to happen?**
![this](https://user-images.githubusercontent.com/43629374/46135960-1d5dba00-c264-11e8-9092-7b6c5a5e36c4.png)
**What actually happened? Please include as much _relevant_ detail as possible.**
![result](https://user-images.githubusercontent.com/43629374/46135980-31092080-c264-11e8-90e3-e23f70784393.png)
**Please provide a download link to the After Effects file that demonstrates the problem.**
[AEPfile.zip](https://github.com/airbnb/lottie-web/files/2423356/AEPfile.zip)

**Comment by eatlovecode** [comment]
@bodymovin 
so, do you have any solution for the result(please refer, 'What did you expect to happen?
' question) which I want to achieve?

**Comment by eatlovecode** [comment]
@bodymovin how do you apply gradient property for the shape layer? by doing that, can we achieve the result which I want?
![this](https://user-images.githubusercontent.com/43629374/46135960-1d5dba00-c264-11e8-9092-7b6c5a5e36c4.png)

**Comment by bodymovin** [comment]
this video explains how to apply a gradient fill to a shape layer
https://www.youtube.com/watch?v=8wI5bWYBgYs
REgarding that result, maybe you can get to it by stacking multiple gradient fills together

**Comment by eatlovecode** [comment]
@bodymovin thank you, it seems work now 👍
