### ISSUE TITLE
How to get the load progress of animation frames

### ISSUE THREAD

**Issue by wrbing728** [airbnb/lottie-web#1268]
I need to play a loading animation with the main lottie animation's loading progress.
How to get the progress when loading the lottie animation?

**Comment by bodymovin** [comment]
Hi, what do you mean by getting the progress when loading the animation?

**Comment by wrbing728** [comment]
I meat the value of loading schedule like '20%'

**Comment by bodymovin** [comment]
I see. This is not supported. It would depend on files getting the appropriate headers so percentage of download can be calculated.
If you need this, you can load the json externally to retrieve this information and then pass it as an object to the animation instead of a path.

**Comment by wrbing728** [comment]
> pass it as an object to the animation instead of a path
What's the object look like?  Is there any sample?

**Comment by bodymovin** [comment]
the object is the exported json copied as a js object:
```js
var anim = bodymovin.loadAnimation({
  container: svgContainer,
  renderer: 'svg',
  loop: true,
  animationData: {data}
});
```
