### ISSUE TITLE
Fail to goto the right frame

### ISSUE THREAD

**Issue by wrbing728** [airbnb/lottie-web#1269]
To emersion the case, first, call the playSegments method, then call another playSegments, the frame index will be in the mess((the same as called goToAndPlay)) ,for example:

```javascript
loadingAnim.playSegments([[10, 30]], true);
setTimeout(() => {
    loadingAnim.playSegments([[31, 40]], true);
}, 10) // won't goto and play from the real 31 to 40, 

```
I think it is because that the first playSegments hasn't finish when the second is called. 

version: 5.3.1

**Comment by bodymovin** [comment]
Hi, I couldn't reproduce the issue, but I did a fix on playSegments that might be related to this.
Could you try the latest player to see if it's fixed?
https://github.com/airbnb/lottie-web/tree/master/build/player

**Comment by wrbing728** [comment]
I tried the latest version but had no effect, the problem still reproduced.
The key step to reproduce this is to **break the playing** segments and start to play a new one.
Maybe you can try a more complex animation to reproduce this.

**Comment by bodymovin** [comment]
Can you share a link with the issue?

**Comment by kudanai** [comment]
Closing this for now since it's been a while. Please feel free to re-open it if it's still relevant.
