### ISSUE TITLE
Lottie color changes for shapes in json

### ISSUE THREAD

**Issue by sbala69gmail** [airbnb/lottie-web#1270]
I have been changing the color in lottie object for shapes, i thought it was rgba color type so when i changed that into rgba but the color of my object has not be changed even i tried in cmyk color type also. Kindly let me know what type of color should i want to add for lottie objects

> if(objectLayer[i].shapes[k].it[j].c != undefined) {
> 
>    objectLayer[i].shapes[k].it[j].c.k[0] = Number(($scope.ADCntl.rgbaColor[0]*100)/100);
>    objectLayer[i].shapes[k].it[j].c.k[1] = Number(($scope.ADCntl.rgbaColor[1]*100)/100);
>    objectLayer[i].shapes[k].it[j].c.k[2] = Number(($scope.ADCntl.rgbaColor[2]*100)/100);
>    objectLayer[i].shapes[k].it[j].c.k[3] = Number(($scope.ADCntl.rgbaColor[3]*100)/100);
> 
> };

the above example i have tried in rgba color, in my array(i will change hex-rgba conversion). Kindly help me in this what type of color i want to add ?

@sonaye

**Comment by sonaye** [comment]
They are unit vectors, please see:
https://github.com/sonaye/lottie-editor/blob/dev/src/configs/utils.js#L9-L12
https://github.com/sonaye/lottie-editor/blob/dev/src/components/Root.js#L119-L124
