### ISSUE TITLE
Mobile phone is overheating while lottie animation is playing?

### ISSUE THREAD

**Issue by wrbing728** [airbnb/lottie-web#1271]
Is it normal that my iPhone6s overheated immediatly when playing the lottie animation?
BTW, I use svg renderer. Does this affected by renderer?

**Comment by bodymovin** [comment]
It might change with the renderer but it's mainly affected by the animation itself.
Can you share it so I can take a look?

**Comment by wrbing728** [comment]
Really sorry that it is not allowed for me to share the lottie file bescause our company is preparing for a business activity.
But I can say something about it. 
The file size is nearly 1.5M which the total animation time lasts about 10-15 seconds.And there are 500 frames in total. I'm not sure if it is kind of LARGE? 
What I have to mentioned is , even if the file size is large, after loaded the animation file, I just playSegments between 0-30 frames, with about 10 sprites to do some small movements. 
Hope for some experience for it.

**Comment by wrbing728** [comment]
Some more infomation as a supplement:

```javascript
...
  "fr": 25,
  "ip": 0,
  "op": 500,
  "w": 750,
  "h": 1334,
...

```

And are there some documents to explain the lottie's json file? Maybe I can do some optimize by modify the file.

**Comment by bodymovin** [comment]
can you try using `animation.setSubframe(false)`?
It will respect the original animation frame rate instead of refreshing the animation at 60fps.
regarding documentation of the json file, it's a little outdated, but here is some info:
https://github.com/airbnb/lottie-web/tree/master/docs/json

**Comment by wrbing728** [comment]
I think it works for me! After using `animation.setSubframe(false)`, overheating seems like not that quick.
But what confused is , actually I have already set subframeEnabled property to false when invoke `loadAnimation`, but when I check it at the console , the value of `subframeEnabled` is still true.

```javascript
     mainAnim = lottieGame && bodymovin.loadAnimation({
          container: lottieGame,
          renderer: 'svg',
          loop: true,
          autoplay: false,
          // progressiveLoad: true,
          subframeEnabled: false,
          path: animationUrl
        });
        // mainAnim.setSubframe(false);
        mainAnim.addEventListener('DOMLoaded', () => {
          loadingAnim.playSegments([[16, 40]], true);
        });
        console.log(mainAnim); // subframeEnabled: true
```

**Comment by bodymovin** [comment]
`subframeEnabled` is not a valid property for the animation configuration.
I could add it as well.
But for now you need to set it calling `setSubframe`
