### ISSUE TITLE
Lottie Render deleting AE keyframes

### ISSUE THREAD

**Issue by biobronco** [airbnb/lottie-web#1273]
**SYSTEM**
macOS Mojave
After Effects 15.1.2
Lottie 5.3.1

I have used AE and Lottie in the past to build several animations that worked perfectly! But, now when outputting AE comps with Lottie Render in the AE Lottie plug-in window, Lottie is deleting AE keyframes.

**ISSUE:** I added opacity keyframes to an animated layer in AE, so that the AE layer fades on. When I click Render in the Lottie plug-in window, Lottie removes my AE opacity keyframes step-by-step while rendering.

It's like watching Lottie play a movie in reverse of all the keyframes I just created in AE.

At the end of the render, no error message appears. Lottie generates a JSON files as normal, but all my new AE animation has been removed.

I've only had this problem since updating my Mac to macOS Mojave. Not sure if it's a Mojave issue or Lottie issue.

Also, since updating to macOS Mojave, I have built other AE animations without using Lottie and had no problems. I've been able to render out AE comps as video files and they've worked as expected.

**Comment by bodymovin** [comment]
that's odd, I'll have to take a look.
Are you using rove across time by chance?
Can you share the animation?

**Comment by biobronco** [comment]
No, I'm not using Rove Across Time at all.

Later today I will post a screen recording of what's happening and upload the project.

**Comment by biobronco** [comment]
Attached is a .ZIP folder containing a screen recording of what's happening and the AE project file.
[AE Lottie.zip](https://github.com/airbnb/lottie-web/files/2435282/AE.Lottie.zip)

**Comment by biobronco** [comment]
If I create a new AE comp and copy my animation to it and attempt a Lottie Render, I get the error message: "Unable to execute script at line 278. Object is invalid"

**Comment by biobronco** [comment]
Fixed it! There were indeed AE layers using "Rove Across Time". I've never really used that AE feature much, and must have been experimenting and forgot I had. I removed all the "Rove Across Time" keyframes and Lottie renders perfectly now.

**Comment by bodymovin** [comment]
Nevertheless, this shouldn't be happening.
I'll look into it.

**Comment by biobronco** [comment]
Yeah, it's very strange to see AE keyframes being deleted. Thanks for your response and help! I'm happy to test things on my end, as well.
