### ISSUE TITLE
Export Alpha inverted mat into JSON

### ISSUE THREAD

**Issue by eatlovecode** [airbnb/lottie-web#1274]
Browser and Browser Version:
Chrome and Version 69.0.3497.100 (Official Build) (64-bit)
After Effects Version:
15.0.0 - CC 2018
Bodymovin Version
5.3.1

**What did you do? Please explain the steps you took before you encountered the problem.**
Created a new composition
Create a circle shape
Apply trim path to stock
applied Alpha inverted mat 
Save File

**What did you expect to happen?**
![sample_alpha-inverted-mat](https://user-images.githubusercontent.com/43629374/46307821-a1ea6880-c5d5-11e8-8361-e4f838921679.gif)

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**
[sample (1).zip](https://github.com/airbnb/lottie-web/files/2435117/sample.1.zip)

**Comment by eatlovecode** [comment]
@bodymovin any inputs?

**Comment by kudanai** [comment]
Closing this for now since it's been a while. Please feel free to re-open it if it's still relevant.
