### ISSUE TITLE
lottie_light.min.js ballooned in size between 5.3.1 and 5.3.2

### ISSUE THREAD

**Issue by TAGraves** [airbnb/lottie-web#1275]
We use lottie light because we only need the SVG renderer and we're pretty sensitive about our delivered file sizes. With the latest patch version, the size has increased pretty significantly - almost 2x gzipped. To get these numbers, I hit lottie_light.min.js on unpkg using Firefox and looked in the network tab.

version | minified_size | gzipped_size
--|--|--
5.2.0 | 38.99 | 144.47
5.3.1 | 39.28 | 145.61
5.3.2 | 57.82 | 240.56

Anecdotally, `canvas` appears 4 times in 5.3.1, and it appears 140 times in 5.3.2, so something presumably went wrong with stripping out the canvas renderer in bundling.

**Comment by bodymovin** [comment]
fixed in v5.3.3
need to work on the gulp task
thanks
