### ISSUE TITLE
Bodymovin - HTML beginner

### ISSUE THREAD

**Issue by KatherineFardell** [airbnb/lottie-web#1277]
Hello...

I am a complete novice at HTML and I am trying to export some banner ads for a media agency.

I have created my ads in AE and have converted them using Bodymovin.. all fine.

However, once I have sent it to the agency they said all the files need to be in one single folder and the demo.html needs to be index.html. Again this is all ok to do but when I moved the images from the subfolder bodymovin creates on export to the main as the HTML the images are then lost on my anmation.. how is it best to sort this? Or is there another way?   HELP PLEASE.

<img width="670" alt="screen shot 2018-10-04 at 09 46 58" src="https://user-images.githubusercontent.com/43844335/46462885-7b395700-c7ba-11e8-9b3f-e56c9be1f9a7.png">

**Comment by bodymovin** [comment]
Hi, if you moved the images you'll need to edit the exported demo.html file. Open the file, scroll to the bottom and where it says:
```js
var params = {
        container: document.getElementById('lottie'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        animationData: animationData
    };
```
you need to add `assetsPath: './'`
```js
var params = {
        container: document.getElementById('lottie'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        animationData: animationData,
        assetsPath: './'
    };
```

**Comment by KatherineFardell** [comment]
Hello - thank you for the quick response.

I have attached a screenshot - the code is staying white have I written it in wrong? Also, I am presuming I need to do the same for each image?

Many thanks!

<img width="621" alt="screen shot 2018-10-04 at 11 45 59" src="https://user-images.githubusercontent.com/43844335/46469377-16d2c380-c7cb-11e8-92d7-0c9a150aeece.png">

**Comment by bodymovin** [comment]
you missed a comma on the previous line `animationData:animationData,`  
also on assetsPath just pass './' it will take care of all images

**Comment by KatherineFardell** [comment]
Thank you for your help =)
