### ISSUE TITLE
Generated json is not good 

### ISSUE THREAD

**Issue by Umar3x** [airbnb/lottie-web#1278]
Hello,

Im using bodymovin since one year now and it always worked great. 

I'm loading a png sequence of like 50 images, and creating a composition from here. From the composition I use bodymovin extension to export as json.

Latest chrome 
After effects 2015 CC => version 13.5.0.347

- When trying to export GLYPHS and demo from my composition, bodymovin tell me rendering finished and ok but if I check the json its not good. Moreover I should have a folder (as it always did before) with exported png images to be able to play the animation in lottie (for xamarin c#)  

Here is the generated json which should be like 50x times bigger with a reference to each image. Of course when playing it don"t see anything. 

`{"v":"5.3.3","fr":25,"ip":0,"op":56,"w":1280,"h":720,"nm":"Sun-SemiDarkCloud","ddd":0,"assets":[],"layers":[{"ddd":0,"ind":1,"ty":9,"nm":"Sun-SemiDarkCloud_{00000-00055}.png","cl":"png","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[640,360,0],"ix":2},"a":{"a":0,"k":[640,360,0],"ix":1},"s":{"a":0,"k":[100,100,100],"ix":6}},"ao":0,"ip":0,"op":56,"st":0,"bm":0}],"markers":[]}`

**Comment by bodymovin** [comment]
Hi, can you share the project?

**Comment by Umar3x** [comment]
Hello,

There we go => 

https://drive.google.com/open?id=1yB7w1iLcSRu5sSBZp6RMGO4C3meAJI0d

I'm using latest version 5.3.3

**Comment by bodymovin** [comment]
Image sequences are not supported by the player or the exporter unfortunately.

**Comment by Umar3x** [comment]
Are you sure ? I've been doing that already and it was working thats where I'm confused. 

For example this json : https://drive.google.com/open?id=1kxTlJJ5frH82eA0IDWqzISWEQuctZJlC

**Comment by bodymovin** [comment]
yes, on the second example all images are imported individually and each one correspond to a layer instead of a single sequence.

**Comment by bodymovin** [comment]
when you import the sequence, you should import each image individually
then add them ll to the composition
and there are some commands in AE that let you sequence layers as you need
