### ISSUE TITLE
Feasibility of adding grain and noise texture to shape layer

### ISSUE THREAD

**Issue by Danjuanlab** [airbnb/lottie-web#1279]
At present, the effect supported by bodymovin can make a very powerful mograph animation, but whether the animation is simple or complicated, The style is basically clean or cartoon. Recently i tried to add some grain texture to the shape layer to increase some depth.But I tried a lot of methods have all failed, I will list the methods I tried, I would like to ask if there is a method I do not know can add grain texture on the shape layer .
![p1](https://user-images.githubusercontent.com/42509669/46474645-fb40da80-c815-11e8-864a-0337c30f3007.png)
![p2](https://user-images.githubusercontent.com/42509669/46474646-fb40da80-c815-11e8-98e2-14119bd7eaa3.png)

1. Add grain texture png file - mask   

- successfully, but will increase the file size, and can not animated it.
2. Add a new shape layer - mix mode to dissolve - reduce transparency.  

- Failed, because dissolve mode is not supported.
3. shape layer-add layer styles-Bevel and Emboss-high light/shadow-mixing mode to the shape layer. 

-  Failed,because layer styles is not supported.
4. shape layer-noise HLS-gradient ramp.

- Failed,because the build-in effect is not suppport. 

5.Make grain textures in AI - import AE and convert to shape.

- Failed,because there are too many shape groups, up to several thousand groups, and it is impossible to perform rendering efficiently.

If you have a solution to add grain texture, I hope you can tell me, I believe many people want to use bodymovin to make more styled animations.

**Comment by nickmadedesign** [comment]
Hi,

You can choose between vector or raster-based assets.

A noise vector layer will have a lot of paths so unless you're using some advanced options to drastically reduce path counts, you'll have issues with performance.

A noise raster PNG should work, especially if you're optimizing the PNGs. It will depend on whether you need blending modes (e.g. varied color shades).

**Comment by Loreto17** [comment]
me pregunto lo mismo, a esta fecha habra algo?

**Comment by Danjuanlab** [comment]
> me pregunto lo mismo, a esta fecha habra algo?

No he encontrado una solución adecuada hasta ahora, y no he visto animaciones SVG con ruido de movimiento en el codepen. Como dijo Nickmadedesign, la solución actual es separar la capa de ruido y rasterizarla en una imagen PNG, luego integrar la imagen en los datos json al exportar.

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. Please re-open it or file a new issue if this is still relevant.
