### ISSUE TITLE
Color gradients broken in export from After Effects 2017

### ISSUE THREAD

**Issue by Herbmull** [airbnb/lottie-web#1281]
Windows 8.1 Pro and 10
After Effects 2017 and 2018
Bodymovin 5.3.2 and 5.3.3

I created a empty composition with a vector form layer, including a single rectangle shape and a color gradient fill from red to green.
After exporting from After Effects 2017 the color gradient is alway black/white regardless of the color settings. The alignment of the gradient however is correct.
The export from After Effects 2018 shows the right color gradient without any error.

I compared the data. js and demo.html of both versions and there were differences:

Export from After Effects 2017:
ADBE Vector Shape - Rect","hd":false},{"ty":"gf","o":{"a":0,"k":100,"ix":10},"r":1,"g":{"p":2,"k":{"a":0,"k":[0,1,1,1,1,0,0,0],"ix":9}},"s":{"a":0,"k":[-33,-10],"ix":5},"e":{"a":0,"k":[42,5],"ix":6},"t":1,"nm":"gradient fill 1"

Export from After Effects 2018:
"ADBE Vector Shape - Rect","hd":false},{"ty":"gf","o":{"a":0,"k":100,"ix":10},"r":1,"g":{"p":3,"k":{"a":0,"k":[0,0.941,0.022,0.022,0.5,0.768,0.47,0.178,1,0.595,0.918,0.335],"ix":9}},"s":{"a":0,"k":[-33,-10],"ix":5},"e":{"a":0,"k":[42,5],"ix":6},"t":1,"nm":"gradient fill 1"

The same code is at the end of the demo.html.

The difference is in the second line:
[0,1,1,1,1,0,0,0]
vs
[0,0.941,0.022,0.022,0.5,0.768,0.47,0.178,1,0.595,0.918,0.335]

**Comment by bodymovin** [comment]
did you save the project before exporting?

**Comment by Herbmull** [comment]
Yes.
I just found the solution. I had a special character in the gradients name (ü), renamed it for better reading.
Now it works fine with 2017 too. :)
