### ISSUE TITLE
 The render goes wrong

### ISSUE THREAD

**Issue by chi1080** [airbnb/lottie-web#1285]
**Tell us about your environment**

* **Browser and Browser Version:** Chrome Version 69.0.3497.100 
* **After Effects Version:** 15.1.2

**What did you do? Please explain the steps you took before you encountered the problem.**
Precomposed my animation and then proceed to render it with bodymovin but neither the bodymovin preview nor the .json file show the animation correctly.

**What did you expect to happen?** 
The animation have to look like this:
https://goo.gl/vxkMd3

**What actually happened? Please include as much _relevant_ detail as possible.**
The .json doesn't look the same:
https://goo.gl/fAPspU

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://goo.gl/Rt8z6E

**Comment by bodymovin** [comment]
Yes, there is an issue with dashed strokes with trim path when Start value > End value.
I'm still looking into it but I don't have a fix yet.

**Comment by chi1080** [comment]
Ooh, ok! Thank you so much for your prompt response!

**Comment by LizzieMT** [comment]
I'm also having a similar issue but my trim paths are not dashed strokes, just normal strokes.

**Comment by bodymovin** [comment]
@LizzieMT hi, can you share the .aep?

**Comment by bodymovin** [comment]
@LizzieMT Hi, I've fixed an issue with trim paths related to what I guess was your issue.
If you try it with the latest player, it should work fine.
https://github.com/airbnb/lottie-web/tree/master/build/player
