### ISSUE TITLE
Animation partly freezes in demo.html

### ISSUE THREAD

**Issue by floredegunst** [airbnb/lottie-web#1295]
**Tell us about your environment**

* **Browser and Browser Version:**
Chrome Version 69.0.3497.10
(safari en firefox is the same problem)

* **After Effects Version:**
Version 15.1.1

**What did you do? Please explain the steps you took before you encountered the problem.**
I made a simple vector based animation in exported it via bodymovin. The demo does quitte well actually but 1 letter that is made out of two layers isn't doing anything. The other letter are working perfectly. I tried changing my framerate, copying layers and animating them again and even make the whole animation again. The letter 'T' still freezes when I export the demo.html

**What did you expect to happen?**
I expected the whole thing to work haha! I find it strange that most of the animation is working except for the 'T' 

**What actually happened? Please include as much _relevant_ detail as possible.**
see the gif below:
Right > a gif with the animation
Left > the demo.html whit the frozen T

![2018-10-11 09 40 06](https://user-images.githubusercontent.com/44051903/46790112-70447080-cd3e-11e8-9ca8-512c3c3440b4.gif)

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by floredegunst** [comment]
Sure!

[ARTIFEX .zip](https://github.com/airbnb/lottie-web/files/2468727/ARTIFEX.zip)

**Comment by bodymovin** [comment]
hi, there was an issue with multiple groups and the stroke effect.
I've just uploaded a new player if you want to test it.
https://github.com/airbnb/lottie-web/tree/master/build/player

**Comment by floredegunst** [comment]
Hi!

The problem with the 'T' is solved! Unfortunately the letter 'F' has a little glitch now. I wanted to upload an mp4 with the problem because in a gif it doesn't show because of the framerate

**Comment by bodymovin** [comment]
Can you describe the glitch?

**Comment by floredegunst** [comment]
The layer seems to be playing twice. The animation looks correct but its really fast and repeats itself for a second time. You can see the layer I'm talking about in the screenshot below.


![schermafbeelding 2018-10-16 om 08 35 28](https://user-images.githubusercontent.com/44051903/46996906-75c6ff80-d11e-11e8-98a8-0492e17e893d.png)

**Comment by bodymovin** [comment]
Hi I've tested it and it seems to work fine.
Can you share a link with the issue?

**Comment by floredegunst** [comment]
Sorry for the late response but I saw it happen 3 or 4 times but after that it never happend again! Strange but good news! Thanks for all your help
