### ISSUE TITLE
Rubberhose RubberRig issue

### ISSUE THREAD

**Issue by bcbio23** [airbnb/lottie-web#1296]
Is RubberRig compatible with Bodymovin? I have animated a walk cycle which works fine in AE, but when it's exported out using Bodymovin it becomes a straight legged walk instead of having a nice bend?

Just trying to decide if only the hoses are compatible or whether I might have set something up wrong in AE.

Thanks.

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by bodymovin** [comment]
I'm seeing the animation exported fine.
Can you share your export?

**Comment by bcbio23** [comment]
That is strange, here is the JSON file: https://we.tl/t-993qAfhNWl

Could it be a version issue, I am using version 5.3.4 for AE, and version 4.13.9 for the player. 

Thanks :)

**Comment by bodymovin** [comment]
Yes, it's definitely it.
You need to use a newer player.
