### ISSUE TITLE
If I understand correctly, I think you need to measure the full height of your site and divide scrollTop by the height so you can sync the scroll to the animation.

### ISSUE THREAD

**Issue by yshu94** [airbnb/lottie-web#1297]
Here is my code

<section id="banner">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.13.0/bodymovin.min.js"></script>
		<script src="js/index.js"></script>
		
		</section>

/*js*/

var animation = bodymovin.loadAnimation({
  container: document.getElementById('banner_two'),
  renderer: 'svg',
  loop: true,
  autoplay: true,
  
  path:'svg/2/data.json'
})

pls help out

**Comment by bodymovin** [comment]
Hi, I'm not sure I understand the problem. Can you elaborate?

**Comment by yshu94** [comment]
i need the svg animation to start only when its been scrolled to a division or a section but it's not working out after trying out many ways

below is is my code

**HTML**
<section  id="banner">
	<div id="banner_one">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.13.0/bodymovin.min.js </script>
<script src="js/index 6.js"></script>
	</div>
	</section>

**JS**
var animation = bodymovin.loadAnimation({
  container: document.getElementById('banner_one'),
  renderer: 'svg',
  loop:true,
  autoplay: true,
  path:'svg/3/data.json'
})

i've tried out different ways but it ain't working out please help out

**Comment by bodymovin** [comment]
can you share a link with the implementation?

**Comment by yshu94** [comment]
https://www.conceptionsinc.com/demo/generic.html

**Comment by bodymovin** [comment]
I see you're loading all of them when loading the page.
You probably need to hook each animation loading to your scroll event.

**Comment by yshu94** [comment]
can u help me with the code ?

**Comment by bodymovin** [comment]
I think it's better if you look for some tutorials online to do this. There's many ways to solve it and it depends on your needs and experience.

**Comment by kudanai** [comment]
Please have a look at [https://lottiefiles.github.io/lottie-docs/advanced_interactions/](https://lottiefiles.github.io/lottie-docs/advanced_interactions/) and [https://lottiefiles.com/interactivity](https://lottiefiles.com/interactivity) which may have some helpful information.

for the time being, I'm closing this issue as it's been stale for some time. Please feel free to re-open it or file a new one if this is still a relevant issue.
