### ISSUE TITLE
Bodymovin renders – fine in ios Lottie preview app one minute, not the next

### ISSUE THREAD

**Issue by AliNord** [airbnb/lottie-web#1298]
Hi everyone,

I was hoping someone could help me. In July, I started a project for a client where they required animated badges for their app. I created a few for their prototype and all was well.

Yesterday, I came to develop these badges and do more and all rendered out fine as .json and .html files. I could see the html in chrome, view the .json file fine in Lottie Preview, and see it fine on my ios app on my iPhone. This morning, I noticed one minor thing wrong on the badges which is where I had shapes spelling goal instead of streak. This is all I changed. Yet, in ios Lottie app, these have all gone to pot... Outlined, no animation, no gradients, just not working... 

I've been trying all sorts, testing individual compositions, saving before rendering, renaming comps and then rendering, making sure cache goes to hard drive etc.... Can't do anything that makes the .json files work on ios. And what's worse is that this prompted me to open the original files from July and even though these were fine then and used in the prototype successfully, now these are not working! I am absolutely baffled in every sense of the word. I've downloaded and installed the latest Bodymovin plugin to see if it made a difference. It didn't. 

Anyone who could chat through/look into this with me, I would be SO grateful!

Many thanks,

Ali

**Comment by bodymovin** [comment]
Hi, can you share the .aep?
@gpeal can you think of anything?

**Comment by AliNord** [comment]
In this ZIP folder are the html files (as should look) and the json files which aren't looking correct at all. And yet yesterday they were absolutely fine! Mirror image of the html files everywhere. Nothing is different! These badges were at an earlier stage in July and had no gradients. Completely flat and simple. They rendered fine then but these also don't this morning, just like the attached. 

[Lottie tests.zip](https://github.com/airbnb/lottie-web/files/2468536/Lottie.tests.zip)

**Comment by AliNord** [comment]
Hi =) Thank you for your response. Here is a zipfile with aep files. Ones from now and also a folder with the July, simpler work, which rendered fine at the time but now don't...
[Lottie files.zip](https://github.com/airbnb/lottie-web/files/2468892/Lottie.files.zip)

Thank you so much.

**Comment by AliNord** [comment]
We will probably stick with the flat look (done in July) if gradients pose more of an issue/more complicated files etc. So, so long as I can figure why my ios previews are no longer happy even on simple ones, that will be ideal. Thanks xx

**Comment by bodymovin** [comment]
Did you share any that do work fine or all of them are not working?
Do you have one json file that works?

**Comment by bodymovin** [comment]
I think I've found one issue that is probably related to this.
If you go to layer "tri outline" > "Contents" > "Shape 1", there is a hidden "Fill", which is being exported anyway.
If you remove it, you'll probably see the animation closer to what it should look like.
I don't know how many are there like this one, but this seems to be the problem.

**Comment by AliNord** [comment]
Hi guys. Thanks for you message last night. Here is a folder of past working ones and now as they currently are, none working. But even the original files I had in July, rendering these now, they no longer work either and they were absolutely fine in July and I've changed nothing on those original files. So weird. 
[json files.zip](https://github.com/airbnb/lottie-web/files/2473272/json.files.zip)

**Comment by AliNord** [comment]
Hmm, I didn't realise that hidden items are part of the render process. I'll have a look into what you're looking at regarding the fills. Maybe this will solve all... Thanks

**Comment by AliNord** [comment]
I've had a look. Removing hidden fills as you said, has made a difference. I'll attach latest json file on one of the badges. It's still not 100% right though and can't find any other hidden fills. Just weird that these hidden features were there before when all the .json files were fine. Thanks for bearing with me! x
[distance fills.json.zip](https://github.com/airbnb/lottie-web/files/2473343/distance.fills.json.zip)

**Comment by AliNord** [comment]
I'm finding a few more actually... these hidden layers really might be the ticket to winning at this!

**Comment by AliNord** [comment]
That has totally worked on the current file I've got open – seeking and binning all these hidden stroke fills! You are a life saver! What made you think to look for that kind of thing? This project is my first time using Bodymovin and Lottie files, so as you can tell I'm not clued up on what to look out for. Thanks a million!
