### ISSUE TITLE
HELP! MY RENDER IS CROPPED

### ISSUE THREAD

**Issue by adeloo** [airbnb/lottie-web#1299]
Hi, I dont know if it is the right place to post but anyway ! 

I am a graphic designer and I'm trying to export an HTML5 banner size 728X90 with bodymovin. In AE my render is fine but when I look at the demo my banner is cropped. 

I am new to coding and stuff so it is hard to explain my issue but I have looked at the code and it does not seem to come from here or from the video export. 
can you help me ? 

I am adding screenshots to show you: 
The first one is how it should look like: 
<img width="1353" alt="capture d ecran 2018-10-12 a 18 31 10" src="https://user-images.githubusercontent.com/43993087/46881911-2eeeb680-ce4d-11e8-87f9-9cb0394b8f85.png">

This is how it actually looks like: 
<img width="723" alt="cropped on the right 2" src="https://user-images.githubusercontent.com/43993087/46881935-4463e080-ce4d-11e8-861a-c1f2464e85ff.png">

Here is also a dropbox link to my AE file: https://www.dropbox.com/s/ndfegw2ddvsgqh5/BUG.aep?dl=0

thanks a lot !!

**Comment by bodymovin** [comment]
It seems to be a font issue.
Can you share the .aep?

**Comment by adeloo** [comment]
Thanks ! 
Here is a dropbox link to my AE file: https://www.dropbox.com/s/ndfegw2ddvsgqh5/BUG.aep?dl=0 

I must add that i ma new to after effects as well (i used to do print only) so i apologize in advance if my file is messy !
