### ISSUE TITLE
Lottie's website is missing fallback for icons in the "Supported Features" table.

### ISSUE THREAD

**Issue by EliezerB123** [airbnb/lottie-web#1302]
**Tell us about your environment**
Ubuntu 14.04
* **Browser and Browser Version:**
Chrome 68.0.3440.106
Firefox 57.0

**What did you do? Please explain the steps you took before you encountered the problem.**
I went to check Lottie's compatibility list:
Go to http://airbnb.io/lottie/supported-features.html

**What actually happened? Please include as much _relevant_ detail as possible.**
The table fails to load properly because I'm missing the required icon from my system fonts, as seen in this screenshot here:

![selection_618](https://user-images.githubusercontent.com/30175427/46937628-743bff80-d06a-11e8-9c94-2ebe5f96c800.png)

Edit: I feel pretty embarassed. I was **very** upset that I wasn't able to check compatibility, because this seems to be a very useful tool.... and in the end it appears to be a problem with my system fonts.

**Comment by kudanai** [comment]
Hope this issue is fixed now.
If not, please re-open an issue for this on [https://github.com/airbnb/lottie](https://github.com/airbnb/lottie)

**Comment by mbasaglia** [comment]
Also note that now there's https://canilottie.com/ which might be a better alternative to that table
