### ISSUE TITLE
Unable to execute script at line 320. p is undefined

### ISSUE THREAD

**Issue by InternetbureauForwart** [airbnb/lottie-web#1303]
Hi!
I'm working on OSX with _After Effects CC 2018 (V 15.1.2) (Dutch Language)._
Previously the plugin worked fine, but since last week I'll get an error when trying to open the Bodymovin plugin. The Bodymobin panel is showing up but isn't filling up with all the regular settings. 

When I click on the panel, the error **Unable to execute script at line 320. p is undefined** pops up. And when I try to click okay, it pop ups again. So I have to restart after effects.

You can download the file over here: https://we.tl/t-hbatSSfzeP

Do you have any idea what is causing the error?

**Comment by bodymovin** [comment]
Hi, what version of Bodymovin are you using?

**Comment by bodymovin** [comment]
Apparently there is a conflict between the two extensions.
I need to look into it, but they don't work when both are installed.

**Comment by InternetbureauForwart** [comment]
ah okay!
We will bypass it for now by using an other laptop to export the animations. But it would be nice if you'll be able to fix it.

Thanks for the quick response.

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
