### ISSUE TITLE
Font issue ? 

### ISSUE THREAD

**Issue by adeloo** [airbnb/lottie-web#1304]
Hi, I dont know if it is the right place to post but anyway ! 

I am a graphic designer and I'm trying to export an HTML5 banner size 728X90 with bodymovin. In AE my render is fine but when I look at the demo my banner is cropped. 

I am new to coding and animation on aftereffects so it is hard to explain my issue but I have looked at the code and it does not seem to come from here or from the video export. 
can you help me ? 

I am adding screenshots to show you: 
The first one is how it should look like: 
<img width="1353" alt="capture d ecran 2018-10-12 a 18 31 10" src="https://user-images.githubusercontent.com/43993087/46881911-2eeeb680-ce4d-11e8-87f9-9cb0394b8f85.png">

This is how it actually looks like: 
<img width="723" alt="cropped on the right 2" src="https://user-images.githubusercontent.com/43993087/46881935-4463e080-ce4d-11e8-861a-c1f2464e85ff.png">

Here is also a dropbox link to my AE file: https://www.dropbox.com/s/ndfegw2ddvsgqh5/BUG.aep?dl=0

thanks a lot !!

**Comment by bodymovin** [comment]
Hi, there seems to be many missing files.
Can you attach them as well?

**Comment by bodymovin** [comment]
Hi, the property Horizontal Scale from the Character panel in AE is not supported.
That's why it looks larger that it should be.

**Comment by adeloo** [comment]
Hi, thank you for your answer ! 

I am not sure to understand what you mean by horizontal scale ? 
What do you recommande I should do to avoid this problem ? 
It seems to be happening everytime I create my text into ae, but if I export it from illustrator it does not render in a good quality. 

Thanks again

**Comment by bodymovin** [comment]
If you open the Character panel in AE, you'll see there is a property called **Horizontal Scale**
The icon is a horizontal T with an arrow underneath.
That property is not supported, so it will get exported as if it had 100% as value.

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
