### ISSUE TITLE
Position Tween jumping on loop

### ISSUE THREAD

**Issue by DrSuave** [airbnb/lottie-web#1305]
Tested in Chrome Version 69.0.3497.100 (Official Build) (64-bit) MacOS and on Chrome for Android.
I'm running After Effects 15.0.0.

I created [this animation](https://thisiswilf.com/jenny/4/small/stretched/demo.html) using shapes drawn natively in After Effects. The animation works as expected on the first playthrough, but on subsequent playthroughs when the eye looks to the left it jumps to position rather than tweens. This happened after I changed the position the eye tweens to - on [previous drafts](http://thisiswilf.com/jenny/3/demo.html) of the animation this jump didn't happen.

Here's a screenshot of the keyframes:
<img width="1437" alt="screen shot 2018-10-15 at 5 38 11 pm" src="https://user-images.githubusercontent.com/1854222/46964906-3c9c7a00-d0a1-11e8-9ccc-a2e2711813c3.png">

I expected the animation to loop identically each time.

Here's a link to the AE file: http://thisiswilf.com/jenny/4/small/stretched/finalround.aep

Thanks a lot.

**Comment by bodymovin** [comment]
Hi, can you update to the latest version?
It should be fixed already

**Comment by DrSuave** [comment]
> Hi, can you update to the latest version?
> It should be fixed already

Thanks, will do - is this the latest version of Bodymovin or the latest version of AE that I should update to?

**Comment by bodymovin** [comment]
latest version of bodymovin

**Comment by DrSuave** [comment]
Great, that seems to have done it - thanks!
