### ISSUE TITLE
I cannot understand THIS! OnLoopComplete event

### ISSUE THREAD

**Issue by guipinheeiro** [airbnb/lottie-web#1307]
Seriously this is nuts. I'm not a programmer but I'm pretty sure this is not supposed to happen. 

Everything is working fine, but the cacos event is not working with parenthesis. Isnt it supposed to be:

anim.onLoopComplete = cacos();

?????

Heres the code

```
    var expMillerData = {
        container: document.getElementById('expMillerDiv'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        autoloadSegments: true,
        rendererSettings:{
            progressLoad: false
        },
        animationData: expMiller,
       
    }
    ;
    var anim;

    anim = lottie.loadAnimation(expMillerData);

    function cacos(){
        anim.goToAndPlay(450,true);
    }

    anim.onLoopComplete = cacos;
```

**Comment by bodymovin** [comment]
Hi, if you pass it with parenthesis, you are invoking the method instead of assigning it to the property, so it will get immediately called and also will be called only once.

**Comment by guipinheeiro** [comment]
Thank you so much

> Hi, if you pass it with parenthesis, you are invoking the method instead of assigning it to the property, so it will get immediately called and also will be called only once.

You're the best, such a fast reply. Thank you so much for the attention
