### ISSUE TITLE
Reselling

### ISSUE THREAD

**Issue by wildekin** [airbnb/lottie-web#1310]
Is this person authorized to resell this library? – https://aescripts.com/bodymovin

Just thought I'd report it anyway. Thanks

**Comment by bodymovin** [comment]
Hi, thanks for reporting it.  
Yes, I've published the bodymovin extension in aescripts because that's where AE users look for scripts.  
And the price is set as **Name Your Own Price** so you can get it for free there too or pay what you want to support the development.
