### ISSUE TITLE
App preview issue

### ISSUE THREAD

**Issue by EsFrD** [airbnb/lottie-web#1311]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, can you check if you are using any feature not supported by the ios player?  
https://airbnb.io/lottie/supported-features.html  
If not, can you post an issue in the lottie-ios repo?  
https://github.com/airbnb/lottie-ios
