### ISSUE TITLE
Nulls Paths no longer rounded

### ISSUE THREAD

**Issue by AntoineW** [airbnb/lottie-web#1313]
Chrome / Firefox
AE CC 2019 / Lottie 5.3.4

We use AE's "create nulls from path" feature to animate shapes. It worked well in version 5.1.7 but now the shapes are no longer rounded and instead we have straight angles between points.

How it should look: ![image](https://user-images.githubusercontent.com/3490277/47162584-816c1f00-d2f4-11e8-8550-611203c5566a.png)

How it looks: ![image](https://user-images.githubusercontent.com/3490277/47162900-2b4bab80-d2f5-11e8-8bb3-3bec6f27eaef.png)

http://nerisson.fr/player/test2/

AE file: [[ZP] animation-v4 [home for Hernan].zip](https://github.com/airbnb/lottie-web/files/2492345/ZP.animation-v4.home.for.Hernan.zip)

Is it a bug or are we doing something wrong?

**Comment by bodymovin** [comment]
There seems to be a problem between the expression and the keyframes on the Path in the layer BRAS.
I'll look into it.
Meanwhile, if you erase the keyframes, it should work fine and it seems the animation remains the same.
