### ISSUE TITLE
play on click, playback on second click

### ISSUE THREAD

**Issue by mrtolix** [airbnb/lottie-web#1315]
I already solved the problem with playing the animation on click, but now I want to playback on the second click, I'm creating a simple animation for a hamburger menu...

`<script>
    var menu = bodymovin.loadAnimation({
      container: document.getElementById('hamburguer'),
      renderer: 'svg',
      loop: false,
      autoplay: false,
      path: 'hamburguer.json',
    })
document.getElementById('hamburguer').addEventListener('click', function(){ menu.play(); })  `

**Comment by bodymovin** [comment]
you can call `animation.goToAndPlay(0)`

**Comment by mrtolix** [comment]
Solved already, here's the code
`var hamburger= document.getElementById('hamburger');
hamburger.addEventListener('click', function(){
  hamburger = !hamburger
  if(hamburger) {
    console.log('Second Click');
    menu.setDirection(-1);  
    menu.play(); 
  }else {
    console.log('First click');
    menu.setDirection(1);  
    menu.play();
  } 
})`

However, I tried the 'toggle' function and its not working, thanks so much for all your help guys

**Comment by FreshImmuc** [comment]
Omg this helped me so much there is no code that does this online except this one!! thank you i've searched for hours
