### ISSUE TITLE
[Loop Issue] Animation freezes the first time

### ISSUE THREAD

**Issue by andre94** [airbnb/lottie-web#1318]
* **Browser and Browser Version:**
Google Chrome

* **After Effects Version:**
Last

**What did you do? Please explain the steps you took before you encountered the problem.**
I create a json file with bodymovin AE script

**What did you expect to happen?**
I want the image correct looping from 0 to 180

**What actually happened? Please include as much _relevant_ detail as possible.**
The image have a first play, it freezes and then start the correct looping from 0 to 180 without freezing anymore. I've noticed that, without playSegments() function, the animation freezes every time before another loop.

Screen: https://imgur.com/a/uD5rKiR

Code: 

```
let home_isometric_animation = lottie.loadAnimation({
    container: document.getElementById("home-isometric"),
     renderer: 'svg',
     loop: true,
     path: '../assets/lottie-files/home-isometric.json'
 });
 home_isometric_animation.playSegments([[1,180],[180,1]], true);  
```

**Comment by bodymovin** [comment]
Hi, can you share the .aep or the json file?

**Comment by andre94** [comment]
Hi! Thanks for reply! Here the json https://www.lottiefiles.com/andre94

**Comment by bodymovin** [comment]
I think the problem is that you're not waiting for the animation to be loaded before setting segments.
Can you try doing something like:
```js
home_isometric_animation.addEventListener('DOMLoaded', function(){
 home_isometric_animation.playSegments([[1,180],[180,1]], true);
})
```

**Comment by andre94** [comment]
Yes! now it is working 👍 😄  Many Thanks guys for the plugin and the professional support you provide us with.
