### ISSUE TITLE
"renderableEffectsManager" in newest version "lottie.js" file is not useable?

### ISSUE THREAD

**Issue by ClaymanTwinkle** [airbnb/lottie-web#1319]
"renderableEffectsManager" in newest version "lottie.js" file is not useable?

**Comment by bodymovin** [comment]
Hi, what kind of usage do you have in mind?
In order to improve performance it is only added as a renderable component only if it has one or more effects.
If not, it's renderFrame method will not be invoked.

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
