### ISSUE TITLE
Class name not showing up

### ISSUE THREAD

**Issue by aung-barto** [airbnb/lottie-web#1321]
Hi,
I can see in JSON file that there's a class name and an ID exported from AE file, but I'm not sure why only the ID shows up in HTML and not the class name.

![screen shot 2018-10-23 at 7 00 05 pm](https://user-images.githubusercontent.com/11380180/47395748-e90bdb00-d6f5-11e8-9edb-d2f2199e79ca.png)

```
"nm":".light_cheerio#group35","np":6,"cix":2,"ix":30,"mn":"ADBE Vector Group","hd":false,"ln":"group35","cl":"light_cheerio"}]
```
AE version: 15.0.0
I downloaded Bodymovin version directly from AE (v 5.2.1).

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by aung-barto** [comment]
@bodymovin 
[Datagram_Cereal_02 (converted).aep.zip](https://github.com/airbnb/lottie-web/files/2511549/Datagram_Cereal_02.converted.aep.zip)

**Comment by aung-barto** [comment]
@bodymovin Also, is there a way to give an ID to the `<svg>`?

**Comment by bodymovin** [comment]
@aung-barto I can't find a layer with an id and a class applied in that project.
Can you help me identify the layer?

Regarding assigning an id to the svg, you can assign a className, but not id.

**Comment by aung-barto** [comment]
@bodymovin For the svg className, do I do that in the composition name?

**Comment by bodymovin** [comment]
when you load the animation
.loadAnimation({
className: "name-of-class",
...
}
