### ISSUE TITLE
After exporting with png image, png image has black strokes

### ISSUE THREAD

**Issue by wyfang** [airbnb/lottie-web#1325]
Original Image:
![8](https://user-images.githubusercontent.com/17900420/47420636-7ceead00-d7b1-11e8-9edd-8ad41332edbb.png)

Exported:
![img_15](https://user-images.githubusercontent.com/17900420/47420650-85df7e80-d7b1-11e8-9fe6-1001551a233c.png)

![qq20181024-172452](https://user-images.githubusercontent.com/17900420/47420757-c17a4880-d7b1-11e8-8e7d-5a9b7a93f9d0.png)

**Comment by bodymovin** [comment]
Hi, what version of Bodymovin are you using?
Can you share the .aep?

**Comment by wyfang** [comment]
5.3.4 This problem is gone! It is my negligence, not updated to the latest version.
