### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined bodymovin.js:11757 

### ISSUE THREAD

**Issue by SPavelV** [airbnb/lottie-web#1326]
**Tell us about your environment**

* **Browser and Browser Version:**  Google Chrome version 69.0.3497.100
* **After Effects Version:** ??

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**
Playing animation

**What actually happened? Please include as much _relevant_ detail as possible.**
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/open?id=1BBfLQLz0rZ0o4qDvwodNSMg-LtefAAR6
http://katren.chunks.ru/landing-start.html
https://yadi.sk/i/oXi7anL67mDL7w

**Comment by bodymovin** [comment]
Hi, you're using a really old version of the player.
Can you update to the latest one?

**Comment by SPavelV** [comment]
Thanks Hernan, it works! I updated to the latest version.
