### ISSUE TITLE
Graphic dissappers when played on Lottie mobile app

### ISSUE THREAD

**Issue by 2bbr** [airbnb/lottie-web#1332]
I am using After effect CC 2019
BodyMovin Vers. 5.3.4
AEUX Ver 0.6.2

MacBook Pro (15-inch, 2018)
Processor 2.2 GHz Intel Core i7
Memory 16 GB 2400 MHz DDR4
Strartup Disk Macintosh HD
Graphics Radeon Pro 555X 4096 MB Intel UHD Graphics 630 1536 MB

I used AEUX to transfer SKetch assets to AE and then I animated it. After completing the animation I used BodyMovin to export JSON file.

I used Lottiefiles

Here is the screenshot of web and attached is also QR code to access that JSON with mobile app
<img width="632" alt="screen shot 2018-10-26 at 6 14 23 pm" src="https://user-images.githubusercontent.com/19526395/47560542-12717480-d94b-11e8-883e-7582e49ed380.png">
<img width="215" alt="screen shot 2018-10-26 at 6 14 16 pm" src="https://user-images.githubusercontent.com/19526395/47560543-130a0b00-d94b-11e8-8e5a-8ba513464e18.png">

You can clearly see in the mobile app that the buns are missing but when played on web they appear perfectly.

[Onboarding.zip](https://github.com/airbnb/lottie-web/files/2518790/Onboarding.zip)

Can this issue be resolved ASAP. We are on verge of launching the product

**Comment by bodymovin** [comment]
Hi, is the issue related to the mobile version?
Have you checked if you're using any features that are not supported there?
https://airbnb.io/lottie/supported-features.html

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
