### ISSUE TITLE
Bodymovin Alpha mate issue 

### ISSUE THREAD

**Issue by intergalacticaligator** [airbnb/lottie-web#1333]
Hi fellas, 

Got some struggle with a export for logo reveal here. Trying reveal with alpha matte a letter O which is made by a two circle shape layers. The export looks kinda cutted by a square and dont know why... Am using CC 2018 with  bodymovin version 5.3.4

Do anyone have any idea how can I fix it?

This is how the shape is looking an AE:

![screen shot 2018-10-28 at 13 41 49](https://user-images.githubusercontent.com/44545521/47615427-48336c00-dab7-11e8-97f6-d4f14c07d36c.png)

And this in how demo looks: 

![screen shot 2018-10-28 at 13 32 55](https://user-images.githubusercontent.com/44545521/47615318-03f39c00-dab6-11e8-9320-fe1dc230fcc0.png)

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by intergalacticaligator** [comment]
Thanks for a fast reply. 🙏

Here it is:
https://we.tl/t-P344Kp42Vz

**Comment by bodymovin** [comment]
Masked stroked don't work well on browsers.
On your layer "Shape Layer 40" > "Contents"
below "Trim Paths 1", try adding a new group, with a rectangle and a fill with opacity at 0.
Make sure the rectangle stretches enough to cover the whole surface of the stroke.
