### ISSUE TITLE
Keep getting the error after updating to 5.4.1 version

### ISSUE THREAD

**Issue by yellow1912** [airbnb/lottie-web#1334]
**Tell us about your environment**
I'm running the latest Chrome on Windows 10 at the time of the test

* **Browser and Browser Version:**
Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

* **After Effects Version:**
Version 16

**What did you do? Please explain the steps you took before you encountered the problem.**
After upgrading from bodymovin 4.x to the latest lottie, I keep getting this error even though I updated the After Effects plugin and re-exported the file.

**What did you expect to happen?**
Animation should run as before

**What actually happened? Please include as much _relevant_ detail as possible.**
I get this error: Cannot read property '1' of undefined
![image](https://user-images.githubusercontent.com/374134/47630754-1b458e80-db75-11e8-9060-b245ea8f70ef.png)

![image](https://user-images.githubusercontent.com/374134/47630765-24cef680-db75-11e8-9b4c-4b499bc29c60.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://gist.github.com/yellow1912/384c7b6e6e8be01a90716d6af8107f73

(Please note imageUrl is a variable I assigned outside so it does exist)

**Comment by bodymovin** [comment]
Hi, I've found the bug, it's related to setting auto-orient to true on a layer that has no keyframes.
I'll fix it on the next version.
Meanwhile if you remove the auto-orient it should work fine.

**Comment by yellow1912** [comment]
Thanks, how do I remove the auto-orient? In the exported file I don't see it anywhere?

https://gist.github.com/yellow1912/384c7b6e6e8be01a90716d6af8107f73

**Comment by bodymovin** [comment]
https://gist.github.com/yellow1912/384c7b6e6e8be01a90716d6af8107f73#file-sample_lottie-json-L206
