### ISSUE TITLE
Animation doesn't work well in IE

### ISSUE THREAD

**Issue by designplanet** [airbnb/lottie-web#1336]
Hello, 

I read about the alpha mask issue in IE/Edge, but I've 2 animations and both using alpha mask and 1 of them play good and another not good http://take.ms/W6PDG. Is there any idea?

Thank you.

AE files of 2 animations - https://drive.google.com/file/d/1acAo_NLtJXITaqr3o1x8qUVIYeXIe8D3/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, can you specify which are the two comps you're exporting?

**Comment by designplanet** [comment]
Hi, comp 1 and 6.

**Comment by bodymovin** [comment]
I can't find Comp 6.
Are both in the same .aep project?

**Comment by bodymovin** [comment]
Hi, inverted alpha masks are not supported in Edge.
I haven't found a way to support them since their mask implementation is not complete.
Any suggestions welcome :)

**Comment by designplanet** [comment]
Hi, I'm confused. Both animations are use alpha masks, how can it be that only one doesn't work? :)

**Comment by bodymovin** [comment]
do they use **inverted** alpha masks?

**Comment by designplanet** [comment]
HI, 
Yes, we replaced the simple alpha mask. Thanks!
