### ISSUE TITLE
Be not appear animation after text update by TextLayer.updateDocumentData.

### ISSUE THREAD

**Issue by pororia** [airbnb/lottie-web#1339]
Be not appear animation after text update by TextLayer.updateDocumentData.

I testing textlayer update using updateDocumentData method.
Animation normal appear before update text. But be not appear animation after text update by TextLayer.updateDocumentData.

I checked json data that correct text update by console.log .

Could you share me the issue?

Source is same below.-------------------------------------------------
<div id="bm" style="background-color:white"> </div>  
  

  <script src="scripts/lottie.js"></script>
  <script>
      let anim;
      $.getJSON('http://localhost:3000/public/text/animation/times.json', function(animationData){
        
        const elem = document.getElementById('bm');
        const animData = {
          container: elem,
          renderer: 'svg',
          loop: true,
          autoplay: true,
          rendererSettings: {
            progressiveLoad: false
          },
          animationData,
        };
        anim = lottie.loadAnimation(animData);

		 anim.renderer.elements[0].updateDocumentData({t: 'ZZZZZZ', s:20}, 0);
		 console.log("anim.renderer.elements[0] === " + anim.renderer.elements[0]);
		 console.log(anim.renderer.elements[0]);
        });
           
    </script>

**Comment by bodymovin** [comment]
hi, can you share a link with the issue so I can check it?

**Comment by pororia** [comment]
It doesn't have link because I testing my laptop.
So, I uploaded index.html and json file in dorpbox.

https://www.dropbox.com/sh/6583nkj4dqtnb3i/AAChJegh_gaeDgJOPXpUkKb3a?dl=0


> hi, can you share a link with the issue so I can check it?
