### ISSUE TITLE
Animation disappears after initial load

### ISSUE THREAD

**Issue by JaceHensley** [airbnb/lottie-web#1340]
**Tell us about your environment**
React + Typescript

* **Browser and Browser Version:**
Chrome 69

**What did you do? Please explain the steps you took before you encountered the problem.**
- Using lottie-web through npm
- Created a component that interacts with `lottie-web`
- Try rendering that within my app
- Try rendering that within my app's storybook

**What did you expect to happen?**
The animation to play

**What actually happened? Please include as much _relevant_ detail as possible.**
The animation works flawlessly in storybook, but it stops and disappears after it initially renders 

I'm using the svg renderer and notice that `display: none` is on the `<g>`s. I also noticed that `currentFrame` and `currentRawFrame` are set to `NaN`

I dug around and saw that it lottie-web uses `eval` so I added `unsafe-eval` to my page's `script-src` CSP direction but that didn't seem to change anything

<details><summary>React Component:</summary>

```typescript
import * as React from 'react'
import * as lottie from 'lottie-web'

import {BaseComponent} from '@client/utils'

type Options = lottie.AnimationConfig & {
  animationData: any
}

type LottieProps = {
  options: Options
  width?: string
  height?: string
}

class Lottie extends BaseComponent<LottieProps> {
  static defaultProps = {
    width: '100%',
    height: '100%',
  }

  private anim: lottie.AnimationItem
  private containerRef: React.RefObject<HTMLDivElement>

  constructor(props: LottieProps) {
    super(props)

    this.containerRef = React.createRef()
  }

  componentDidMount() {
    const defaultedOptions = {
      ...this.props.options,
      container: this.containerRef.current,
      renderer: 'svg',
      loop: this.props.options.loop || true,
      autoplay: this.props.options.autoplay || true,
    }

    this.anim = lottie.loadAnimation(defaultedOptions)
  }

  componentWillUnmount() {
    this.anim.destroy()
  }

  render() {
    const lottieStyles: React.CSSProperties = {
      width: this.props.width,
      height: this.props.height,
      overflow: 'hidden',
      margin: '0 auto',
      outline: 'none',
      ...this.props.style,
    }

    return (
      <div
        ref={this.containerRef}
        style={lottieStyles}
        tabIndex={0}
        {...this.props}
      />
    )
  }
}

export {Lottie}
```

</details>

&nbsp;
Thanks for any help!

**Comment by bodymovin** [comment]
Hi, can you share a link with the issue?

**Comment by bodymovin** [comment]
if currentFrame is NaN I suspect it's related to `requestAnimationFrame`.
https://github.com/airbnb/lottie-web/blob/0bf7483657a08208e044a6b7085009304ceddbc9/player/js/animation/AnimationManager.js#L98

Can you add a log there to see `nowTime`'s value?
here is the same line on the build:
https://github.com/airbnb/lottie-web/blob/0bf7483657a08208e044a6b7085009304ceddbc9/build/player/lottie.js#L8751

**Comment by JaceHensley** [comment]
OMG, I love you! For some reason we have a polyfill for requestAnimationFrame and I removed that and it works!! Thank you so much 😄
