### ISSUE TITLE
Cannot play the JSON file

### ISSUE THREAD

**Issue by kurniawanj26** [airbnb/lottie-web#1342]
I've created an animation contains 1 image and 2 sentences. I'm using some presets to animate those files. Then I render it with Bodymovin. But, the animation doesn't play correctly when I play it on the browser. Like this : 
![screen shot 2018-11-01 at 17 41 25](https://user-images.githubusercontent.com/6804018/47847328-6d004a00-ddfd-11e8-92bd-fa42387c6a66.png)

Here's my json file 
[data.json.zip](https://github.com/airbnb/lottie-web/files/2538133/data.json.zip)

Here' my AE file
[Splash.aep.zip](https://github.com/airbnb/lottie-web/files/2538161/Splash.aep.zip)

**Comment by bodymovin** [comment]
Hi, next to the json file you should see an images folder with the exported images

**Comment by JayKurniawan** [comment]
yeah, what should I do with that folder?

**Comment by bodymovin** [comment]
try placing it next to the json file in your project

**Comment by JayKurniawan** [comment]
it only show the image, and not animating as in AE

**Comment by bodymovin** [comment]
can you share the .aep?

**Comment by JayKurniawan** [comment]
[Splash.aep.zip](https://github.com/airbnb/lottie-web/files/2538201/Splash.aep.zip)

**Comment by bodymovin** [comment]
can you share the image?

**Comment by JayKurniawan** [comment]
[images.zip](https://github.com/airbnb/lottie-web/files/2538205/images.zip)

**Comment by bodymovin** [comment]
the problem is that markers are not supported in expressions yet.

**Comment by JayKurniawan** [comment]
do you mean the presets?

**Comment by bodymovin** [comment]
The expressions you're using are relying on markers to work, for example:
`if (bL.marker.numKeys > 0) {`
and markers are not supported unfortunately

**Comment by JayKurniawan** [comment]
So the problem is the presets. I've created a new project and animate it without the presets. Working fine.
