### ISSUE TITLE
SVG Render Bug on Android

### ISSUE THREAD

**Issue by samsandr** [airbnb/lottie-web#1343]
My SVG animation works perfectly in desktop browsers except mobile browsers (Android, iOS) I tested on latest Safari, Chrome, Opera Mobile. 

Some of the SVG paths or shapes don't render properly and only show a 1 pixel line where they should be. The only way to stop this glitch is to remove the viewport meta tag, but I need this for the rest of the site to display properly so can't remove it: 
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
Changing the renderer from SVG to Canvas does not help too.

I attach codepen that you can run on desktop and mobile screens to see the issue.

Codepen here: https://codepen.io/samsandr/pen/QZezRw

I saw simirar issues described here, but I have not seen solutions.

I attach .aep file too. Maybe you will see the issue in aep file, fixing which will solve issue.

[strumer preloader.aep.zip](https://github.com/airbnb/lottie-web/files/2538826/strumer.preloader.aep.zip)

**Comment by jpetitte** [comment]
I'm hitting this issue as well. Did you ever find a solution? 

@bodymovin , how is everyone dealing with this on mobile chrome?

Mobile chrome is one of the most used browsers in the world, so I feel like there must be a solution we're missing that others are using.
