### ISSUE TITLE
AE export issue

### ISSUE THREAD

**Issue by designplanet** [airbnb/lottie-web#1344]
Hi,

I tried to export animations from AE to .html but the animation doesn't work. Is there any idea?

Thanks.

AE source file - [AE_source.zip](https://github.com/airbnb/lottie-web/files/2539253/AE_source.zip)
Final html - [file_sample.zip](https://github.com/airbnb/lottie-web/files/2539254/file_sample.zip)

**Comment by bodymovin** [comment]
Hi that html seems broken or corrupted.
Can you provide the original html exported by the plugin?

**Comment by designplanet** [comment]
Hi, it's original html.
Here is the source AE files https://github.com/airbnb/lottie-web/files/2539253/AE_source.zip, 
maybe the problem is in some settings?
