### ISSUE TITLE
Cannot read property 'p' of undefined

### ISSUE THREAD

**Issue by hannebaumsaway** [airbnb/lottie-web#1347]
I've exported 9 JSON files from 3 AE compositions (AE 16.0). The files from one comp work great; but the other two (so six JSON files) are throwing the following error:

![image001](https://user-images.githubusercontent.com/32681212/47942050-99c86600-debe-11e8-9cfc-9dd9596652a7.png)

The elements in the comps are all converted to shapes from AI layers, and the animations look fine when I preview them via the Bodymovin plugin in AE after rendering them.

**Comment by bodymovin** [comment]
it seems you're using a very old version of the lottie player.
Can you try updating it to the latest version?

**Comment by hannebaumsaway** [comment]
@bodymovin So the 4.13 version in the CDN (https://cdnjs.com/libraries/bodymovin) is old? What's the latest version and where do I get it? The dev team implementing this doesn't have After Effects.

**Comment by bodymovin** [comment]
I suggest that you use npm to install it.
But if you need to download it, you c an get it from here
https://github.com/airbnb/lottie-web/tree/master/build/player

**Comment by hannebaumsaway** [comment]
Thanks, let me see if this solves their problem.

**Comment by bodymovin** [comment]
Hi the cdnjs version is updated
https://cdnjs.com/libraries/bodymovin

**Comment by hannebaumsaway** [comment]
Thanks @bodymovin, using the latest player seems to have solved the issue.
