### ISSUE TITLE
this.addTo3dContainer is not a function bug

### ISSUE THREAD

**Issue by saruzaru** [airbnb/lottie-web#1348]
Hi, i'm getting the "this.addTo3dContainer is not a function" 
after i set the renderer to html, after it asked to do so from svg initially.
demo.html that was generated works fine, but when i try loading it via js, i get these problems.
i've attached the html and the json:
[demo.zip](https://github.com/airbnb/lottie-web/files/2544522/demo.zip)

**Comment by bodymovin** [comment]
Hi, are you using an old player?
Can you share a link with the error?

**Comment by saruzaru** [comment]
im loading it here:
http://startleworks.com/new-home/

**Comment by saruzaru** [comment]
yep. that was it, thanks. but why doesn't the cdn have latest?
