### ISSUE TITLE
Bodymovin 5.4.1 text alignment issues persist

### ISSUE THREAD

**Issue by VinnyPachengo** [airbnb/lottie-web#1352]
I'm using CC2018 of AE with the most recent version of Bodymovin. I'm using AMP to have these animations appear on a webpage. 

Below is the result is for one of the json's that actually appeared. My other animation won't even load for some reason, a single jpg appears . The text moved several pixels to the right and gets caught off at a few areas. I don't know what I could have done wrong putting it through the plugin. I changed all fonts to glyphs and used the appropriate script to call it. 

Does bodymovin have problems rendering precomps into json's? I can't figure out what else could be going wrong when I've removed all layer styles and effects from my comps.
<img width="369" alt="screen shot 2018-11-06 at 10 17 18 am" src="https://user-images.githubusercontent.com/40451282/48085032-118fdc80-e1ae-11e8-8d93-581fc38b9b83.png">

**Comment by bodymovin** [comment]
hi, can you share the .aep so I can take a look?
