### ISSUE TITLE
FONT Problem - Always ON Black Stroke

### ISSUE THREAD

**Issue by rokilovar** [airbnb/lottie-web#1354]
**Tell us about your environment**
MacOS Mojave
Bodymovin version 5.4.1
* **Browser and Browser Version:**
Chrome Version 70.0.3538.77
* **After Effects Version:**
Adobe After Effects CC 2018
**What did you do? Please explain the steps you took before you encountered the problem.**
I have a composition with fonts in it. I created a test composition to simulate the problem. Before rendering with bodymovin the composition in After Effects looks like this: 
![how it looks in ae](https://user-images.githubusercontent.com/44864426/48191565-b5f85700-e345-11e8-9bc1-d866f7774d68.jpg)

**What did you expect to happen?**
Fonts to have no stroke, if not set otherwise.
**What actually happened? Please include as much _relevant_ detail as possible.**
After rendering my composition with bodymovin, I've noticed that all fonts have a black stroke, no matter the font, no matter the size. Strokes are turned off on all of the fonts and have all been converted to shapes. I've tried on numerous computers from macs to pcs, all have the same problem. Any help would be much appreciated! Thank you!

How it looks rendered with bodymovin and previewed with Lottie Viewer:
![how it looks in lottie viewer](https://user-images.githubusercontent.com/44864426/48191622-e63ff580-e345-11e8-9f33-47178d5d8337.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/sh/l01of8w8uiqsia0/AABB59tP0PLUU9na1qg2w2Lfa?dl=0

**Comment by Danjuanlab** [comment]
I use your AEP file to export JSON file directly. It's normal in demo page and in preview.I don't know why your preview shows a stroke.But you can try to delete the strokes before converting them into shapes, instead of disabling them or hidding them.

**Comment by rokilovar** [comment]
Thank you so much! It works now! The reason I didn't delete them manually before is, that in older versions of After Effects (I recently upgraded to CC 2018) with bodymovin, fonts all worked fine. Maybe if the stroke was disabled, it wasn't added to the shape layer. Thank you again for your quick answer and help!
