### ISSUE TITLE
Wordpress plugin extra option to render SVG, CANVAS or HTML inside span element?

### ISSUE THREAD

**Issue by Sebasschmidt** [airbnb/lottie-web#1359]
I'm working inside a wordpress template for my website and I'm using the bodymovin plugin to render my After Effects JSON files. I'm having a problem because a themes function is applied on my animation because it is a DIV element. What happens is that when you scroll down, the animation scrolls twice as fast as it should do. you can see it in action right [here](https://signatured.nl/photography/). 
The problem is being caused because this code: `[bodymovin anim_id="8141" autoplay_viewport="true" width="100px" align="center"]` gets rendered as: `<div id="anim-5be9f3db8c300" class="wpbdmv-animation align-center renderer-canvas playing" style="max-width: 100px; margin-right: auto; margin-left: auto; transform: translate3d(0px, 0px, 0px); opacity: 3.15; pointer-events: none; transition: all 0ms ease-out 0s;"><canvas width="200" height="112" style="width: 100%; height: 100%; transform-origin: 0px 0px 0px;"></canvas></div>` 
And the themes function will automatically add some styles to every DIV beneath a certain DIV. 
These elements get added by the script: ` transform: translate3d(0px, 0px, 0px); opacity: 3.15; pointer-events: none; transition: all 0ms ease-out 0s;`. It causes the animation to scroll twice as fast because it is being called double. 

Was wondering if there is a way to work around this in the case of an option to place the animation inside a CANVAS element. Also when someone has got a solution for this I would love to hear it. Thankful for every help

**Comment by bodymovin** [comment]
Closing. Reopen if necessary.
