### ISSUE TITLE
5.4.1 中文版如何解决颜色变黑白？

### ISSUE THREAD

**Issue by wyfang** [airbnb/lottie-web#1360]
作者貌似无法解决，很长一段时间更新中都有同样问题，所以求问大家有什么解决方法？我现在是正好更新cc 2019，所以2018是英文版，正常使用。但是就是得多留个ae 2018。

**Comment by yamsoil** [comment]
MAC 版本下把渐变层的名称“渐变”改成“glinte”

**Comment by yamsoil** [comment]
之前的版本在mac下直接把渐变层的名称改成glinte就行，但是刚才真是手欠啊，更新了个新版本就不好用了，干！

**Comment by yamsoil** [comment]
看来是2019的问题，2018版本就没事，

**Comment by weiesky** [comment]
暂时无法解决的字符问题.mark一下，改层的命名为英文，绕过去吧。

**Comment by hhzx** [comment]
图层改为英文无效，使用引文AE无效 只有把系统Unicode设置为美国才行
