### ISSUE TITLE
Lottie create animated banner

### ISSUE THREAD

**Issue by euppi98** [airbnb/lottie-web#1362]
Is it possible to use Lottie as an animated banner? For example, when you hover the mouse over an object, another composition will go. Or if you click on an object, another composition will also go?

**Comment by bodymovin** [comment]
you can add interactivity to elements in the animation.  
perhaps this can help https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript
