### ISSUE TITLE
How to convert .MOV file to .JSON file?

### ISSUE THREAD

**Issue by AhmedSalahKhodair** [airbnb/lottie-web#1364]
I created .MOV file with After Effects and I am wondering how to convert it to .JSON file?
I don't find an converter tool online.

**Comment by bodymovin** [comment]
video files can't be converted to json.
What is your use case?

**Comment by bodymovin** [comment]
Why do you need to convert it to json?
I don't think there is a way to do it , but I can't think of a reason to do it either.

**Comment by AhmedSalahKhodair** [comment]
As Lottie uses .json files in Xamarin.Forms.

**Comment by YogeshYo** [comment]
@AhmedSalahKhodair, any luck on this? I am also unable to get this

**Comment by SpEcHiDe** [comment]
@bodymovin  My use case would be like Telegram recently introduced https://telegram.dog/AnimatedStickers So I would like a way to convert existing GIFs to lottie JSON format. I went through the documentation, but could not find any leads. Any help would be appreciated. Thanks.

**Comment by bodymovin** [comment]
You could export video / gif as a png sequence and then reimport the sequence with each file individually.
But the exported json would be huge.
It probably would defeat all purpose of using the json format.

**Comment by TechFinity-Designs** [comment]
In order to convert mp4 to json, do the following steps:
1) convert the mp4 to key frames using adobe media encoder or any other encoding software
2) open the key-frames as a adobe after effects project (just import the keyframes)
3) Download bodymovin plugin (its FREE) for after effects 
4) And yeah, so just convert the keyframes into JSON using bodymovin

It's pretty simple so i'm not giving a step-by-step instruction. Just search for bodymovin plugin for After Effects.

**Comment by Drjacky** [comment]
Use this: https://observablehq.com/@forresto/video-to-lottie

**Comment by isotropicdesign** [comment]
You can use [this](https://isotropic.co/video-to-lottie/), which is just a "prettified" version of ForrestO's great tool.
Though I would not recommend this. You'll typically get flickering of frames. If you have the source file, use Bodymovin to do it the "right" way.

**Comment by berlain84** [comment]
Visit the [Lottie Files ](https://lottiefiles.com/plugins/after-effects) website, download and use the After Effects Plugin to convert your animation to json file. It won't fail you.

**Comment by lxrcan** [comment]
If you have the after effects project, open it and reexport with the bodymovin plugin.If you don’t have the project files and you are skilled, you best just remake the animation yourself using after effects and export it as Lottie directly. If you aren’t skilled and don’t have the project, you have to create a very heavy json which is just a series of still frames rendering quickly. Obviously playing a compressed mp4 is much more efficient than this.If you must use image sequence method just dig around the setting for bodymovin, it’s self explanatory Best of luckLorcan OSOn Feb 14, 2024, at 23:47, berlain84 ***@***.***> wrote:﻿
Visit the Lottie Files  website, download and use the After Effects Plugin to convert your animation to json file. It won't fail you.
