### ISSUE TITLE
Unable to Defer parsing of JavaScript

### ISSUE THREAD

**Issue by Cloudchoice** [airbnb/lottie-web#1365]
Hi,

Incredible script. I am using it for multiple animations, but I can not Defer parsing.

`<script defer src="xxx-xxx/scripts/lottie_light.min.js"></script>`

When I try it results in multiple errors like these:

`Uncaught ReferenceError: bodymovin is not defined
    at VM349:14
(anonymous) @ VM349:14
VM352:14 Uncaught ReferenceError: bodymovin is not defined
    at VM352:14
(anonymous) @ VM352:14
(index):14 Uncaught ReferenceError: bodymovin is not defined
    at (index):14
(anonymous) @ (index):14
(index):15 Uncaught ReferenceError: bodymovin is not defined
    at (index):15`

Is there an alternative?

**Comment by bodymovin** [comment]
where is your script that loads the animations?
If you're not waiting for the document ready event from the browser before loading the animations, `defer` is going to have this result.
