### ISSUE TITLE
Snapshot names mess

### ISSUE THREAD

**Issue by Murrzeak** [airbnb/lottie-web#1367]
Plugin version 5.3.4
AE 2018 CC (15.0)

When saving a still snapshot SVG, plugin forcefully adds a weird .svg extension to the name even if it has it already, resulting in names like `**UK-step3.svg.*.*.*.svg.*.*.*.svg.*.*.svg** `

**Comment by bodymovin** [comment]
hi, what OS are you using?

**Comment by Murrzeak** [comment]
Hey. Sorry, Mac OS 10.13.6 High Sierra

**Comment by Murrzeak** [comment]
Basically it's this dialog that appears every time
![image](https://user-images.githubusercontent.com/30624771/48563170-9c2db580-e8eb-11e8-9519-7bd1b87134e4.png)

**Comment by bodymovin** [comment]
Hi, this should be fixed on the latest extension (v5.4.3).
I'm closing it, but feel free to reopen if the problem persists.
