### ISSUE TITLE
Bodymovin' gradient Malfunctioning

### ISSUE THREAD

**Issue by iamsibtehassan** [airbnb/lottie-web#1370]
Hey,
I'm using Bodymovin' in after effects and it keep getting gradients from some file I rendered in the past. 

Here is teh Link:
https://www.lottiefiles.com/share/nE4msn

The color in the cup is supposed to be Golden but in the past I must've renderd a file with this gradent.
It happend to me before and I cleared th chache and all and It fixed but it also took all settings with it so I'm not whilling to do this again. 
Is there any proper way to fix it?

**Comment by bodymovin** [comment]
Hi, make sure you save the .aep project before exporting the json file.
Gradients are read from the .aep itself and it needs to be saved before exporting.
