### ISSUE TITLE
Hide complete layer 

### ISSUE THREAD

**Issue by knowBalpreet** [airbnb/lottie-web#1371]
Hi @bodymovin, Need to disable a complete layer on runtime based on some condition. I saw an earlier issue which suggests updating "tm" value to 0. But i don't find this variable in my exported JSON file. Is there a way to manipulate/edit json file in such a way that i can remove layers if needed

**Comment by bodymovin** [comment]
If you prefix the layer name in AE with a "#" or a "." it will get exported with an id or class, so you can manipulate it with javascript.
https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript

**Comment by knowBalpreet** [comment]
I understand that this is one way to do it. But I want to do this prior to rendering in the browser. Is there any way to manipulate the JSON file before rendering.

**Comment by bodymovin** [comment]
if you know how to traverse the json object, each layer has an "ip" (in point) and an "op" (out point) property.
if those two are equal, it will never render.

**Comment by knowBalpreet** [comment]
Thanks @bodymovin .Its really helpful and solves the purpose. Is it also possible to enable resizing on text layers directly in the JSON file?

**Comment by bodymovin** [comment]
not right now, dynamic resizing needs to be activated via javascript.
