### ISSUE TITLE
Question: Possible to clip images or movies into shapes within Lottie animations? (Web)

### ISSUE THREAD

**Issue by Cybourgeoisie** [airbnb/lottie-web#1373]
We're looking to use Lottie to provide animations to a vectorized cartoon character. However, we need to make extensive use of dynamic alterations to the character depending on how we want to render it.

We are using web and HTML5 as our medium, and the characters will be rendered in a desktop or mobile browser.

We have a few pre-determined animations that we can apply to the character vector, so we don't need to change the animations on the fly. However, the appearance of the characters can change:

(1) We may want to change the stroke or fill color of a shape on the character
(2) We may want to apply an image as the fill contents inside of an arbitrary shape within the character (this could be per shape, not for the entire object)
(3) We may want to apply a gif or HTML5 movie as the fill contents inside of an arbitrary shape within the character (also could be per shape rather than the entire character)

It is OK if we modify the contents of the JSON data prior to loading into Lottie. From my understanding, the ideal way to change the stroke or fill colors would be to modify the raw JSON object before loaded into Lottie. However, we're not sure if there is support or are any examples of loading an image or movie within the Lottie player.

Our major question right now is, is it possible to achieve either appearance alteration (2) or (3) using Lottie (either out of the box, or with non-significant changes to the codebase), or is this perhaps a significant task? We're debating whether we should continue with Lottie, look into Spine's HTML5 capabilities, investigate a homebrew solution, or alter our requirements.

**Comment by Danjuanlab** [comment]
hello,Your first and second questions can be answered here. [click here](https://github.com/airbnb/lottie-web/wiki) and you can use JS + CSS to change what you want.
As for your third question, GIF can be effectively filled into mask shape, but movie clips can't. I hope this information will be helpful to you.

**Comment by Cybourgeoisie** [comment]
Thanks Danjuanlab - we found that we could insert images and animated gifs into the object shapes in After Effects, and export the entire object with the images included. For anyone who stumbles across this issue with a similar question, the images can be included in the Bodymovin exported file either by referencing the image by filename (pulling the image separately via the JavaScript Bodymovin / Lottie player), or can be inserted directly into the JSON file in Base64 format.

The end result is really cool. We're currently building out a game that uses animated gifs within animated characters, and it looks something like this:

![Example of Lottie SVG with Animated Gifs (still image)](https://i.imgur.com/EEnqlAY.png)
