### ISSUE TITLE
Contrl is not a function

### ISSUE THREAD

**Issue by ShagunParikh** [airbnb/lottie-web#1375]
https://drive.google.com/file/d/1qZh4FccgDNGyhtEuz5NY2bjQvOrghT8h/view?usp=sharing
Here is my animated json file.

I am facing an exception when using it in lottie-web : "**contrl is not a function**". 
I am unable to find the cause of the issue. Please help!

**Comment by bodymovin** [comment]
Hi, if you can share the .aep I can take a look.
But it looks like it's not finding a layer called 'Face Turn'.
Is it possible that the layer is hidden, guided, or is set as an Adjustment Layer?

**Comment by Shakthidgr** [comment]
Hi, this is Shakthi from Shagun team, as instructed by here
Here is the AE file link - https://drive.google.com/file/d/1uW9xKEqSYHNe_hq26tVcSRzJ4U2UBIBK/view?usp=sharing

Please advise to solve the issues. Thanks in advance.

**Comment by bodymovin** [comment]
@Shakthidgr Hi, I can't look into it right now, did you check the possibilities I sent above?

**Comment by Shakthidgr** [comment]
Thanks for the quick reply. yes, we tried to enable the layer, but still we face the same issue. Your advise will definitely solve the issues. Thanks again.

**Comment by bodymovin** [comment]
@ShagunParikh @Shakthidgr are you refering to the same project?

**Comment by bodymovin** [comment]
they don't look like the same project
@ShagunParikh can you confirm?

**Comment by ShagunParikh** [comment]
Yes we are referring to the same project @bodymovin Thanks

**Comment by bodymovin** [comment]
that .aep has no expressions and has only one comp called gotit

**Comment by Shakthidgr** [comment]
Hi @bodymovin - here is the file  https://drive.google.com/open?id=1U6awSo7YXYhy8HBrjft22RLC1UIPItjz

Thanks

**Comment by Shakthidgr** [comment]
Hello @bodymovin i am waiting for the reply. Please do the needful. Thanks a ton.

**Comment by Shakthidgr** [comment]
Here is the open link to edit/download the file - https://drive.google.com/file/d/1U6awSo7YXYhy8HBrjft22RLC1UIPItjz/view?usp=sharing

Thanks and awaiting for the response.

**Comment by ShagunParikh** [comment]
@bodymovin Could you pls check the above file and helps us out if you can! Thanks

**Comment by bodymovin** [comment]
Hi, I exported the animation and it seems to work fine.
Have you included hidden and guided layers in the settings of the export?
