### ISSUE TITLE
Overlay animation on each other

### ISSUE THREAD

**Issue by euppi98** [airbnb/lottie-web#1377]
I am trying to make an animated banner (according to the already prepared reference). But then I ran into a problem (even most likely, I did not provide for this problem).

Banner structure:
1) Intro
2) Looping moment (because of the lights on the sticks)
3) The appearance of the button, as this button must be interactive. I.e. When pointing, the button should increase, so there should be a link on the button.

I made the first two points, but here's the button? Any idea how to do this?

- Reference: http://188.226.237.72/banners/18.10.Grindeval/300x600_2_4/index.html
- how it works now: https://signal-exchange.ru/final/
- My source: [lott_prem.zip](https://github.com/airbnb/lottie-web/files/2602133/lott_prem.zip)

**Comment by bodymovin** [comment]
Hi, not sure I understand exactly what you need.
Do you need to add functionality to an element of the animation so it behaves as a button?

**Comment by euppi98** [comment]
Sorry.
I need to add a button to the banner. And that the button has increased on mouse hover.

**Comment by bodymovin** [comment]
there are many ways to do this.
I'd suggest that you add the button as a separate layer on top of the animation.
You could eventually hook to the `enterFrame` event of the animation to decide when to display it.

**Comment by euppi98** [comment]
Could you help me?
How to do this, I have a bad understanding of js.
I rendered the button separately and dredged the container in place with the animation.
![screen shot 2018-12-03 at 20 21 08](https://user-images.githubusercontent.com/23306157/49390083-ff677680-f738-11e8-98d9-2de4b68292ac.png)
![screen shot 2018-12-03 at 20 19 50](https://user-images.githubusercontent.com/23306157/49390086-0098a380-f739-11e8-93e0-d5fb569334c9.png)
