### ISSUE TITLE
lottie.searchAnimations()

### ISSUE THREAD

**Issue by herrmanneffe** [airbnb/lottie-web#1380]
Hi,
I don't understand what lottie.searchAnimations() does...
The only clue I found is this line of explanation: looks for elements with class "lottie" or "bodymovin" 
Where can I find some examples on how to use this method?
Does bodymovin.searchAnimations() also work?
Thank you

**Comment by herrmanneffe** [comment]
I foud more infos, but I can't make it work..

> Another way to load animations is adding specific attributes to a dom element.
> You have to include a div and set it's class to bodymovin.
> If you do it before page load, it will automatically search for all tags with the class "bodymovin".
> Or you can call bodymovin.searchAnimations() after page load and it will search all elements with the class "bodymovin".
> - add the data.json to a folder relative to the html
> - create a div that will contain the animation.
> 
> **Required**
>  . a class called "bodymovin"
>  . a "data-animation-path" attribute with relative path to the data.json
> 
> **Optional**
>  . a "data-anim-loop" attribute
>  . a "data-name" attribute to specify a name to target play controls specifically

I created a DIV like this:

`<div style="width: 500px; height: 500px;" class="bodymovin" data-animation-path="js/jsonData/animation1.json" data-anim-loop="true" data-name="ninja"></div>`

After I tried to play the animation using the method: **bodymovin.play(ninja);**

There is something that I am missing....... because it does't work :(

**Comment by bodymovin** [comment]
Hi, first thing I see is that you're calling bodymovin.play passing a variable and not a string.
`bodymovin.play(ninja);` should be `bodymovin.play('ninja');`
If that is not the issue, can you share a link with the implementation?

**Comment by herrmanneffe** [comment]
Hi Hernan,
I implemented your correction but still I'm not able to make it work... 
Here's the codepen:
[https://codepen.io/FedMann/project/editor/AoxoLN](url)

Thank You

**Comment by bodymovin** [comment]
That animation uses fonts which are not supported by the canvas renderer. Add an extra attribute "data-anim-type" and set it to "svg" and it should work.

**Comment by chaopan** [comment]
"data-anim-type" is not in the docs. Could that be added?

**Comment by MarcGuay** [comment]
You can also use `data-anim-autoplay` and possibly others.
