### ISSUE TITLE
Changing aspect ratio

### ISSUE THREAD

**Issue by mskogly** [airbnb/lottie-web#1381]
Is there a way to to change aspect ratio depending on device width. From 16:9 on desktop til 9:16 on mobile. 

Is the solution to create two different animations in aftereffects, and use js to swap between them based on resolution/screen orientation? Or is there a way to set it up in aftereffects before export?

**Comment by bodymovin** [comment]
Hi, the animation uses AE original composition size as canvas size.
You can play around with the viewBox and preserveAspectRatio attributes of the svg to get some flexibility.
