### ISSUE TITLE
Problem with some composition and export

### ISSUE THREAD

**Issue by badafra** [airbnb/lottie-web#1382]
I have a problem with my AF cc 2019
some compositions are not exported correctly. I tested the animation on this website https://nicolasjengler.github.io/bodymovins-json-tester/dist/
For example this clock works well. https://cl.ly/e07a05eca40d here in after effect
https://cl.ly/6231eaeb5bca here on the website
But this character instead not. here in after effect https://cl.ly/9141d5aac711
and here on the website, how you can see, the character is not visible, why? https://cl.ly/2d9446c68bc6
I have bodymoving version 5.4.1

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by badafra** [comment]
yeah sure
I'm the guy who wrote you on github but i'll paste my problem here

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno gio 22 nov 2018 alle ore 20:58 hernan <notifications@github.com>
ha scritto:

**Comment by badafra** [comment]
I have a problem with my AF cc 2019
some compositions are not exported correctly. I tested the animation on
this website https://nicolasjengler.github.io/bodymovins-json-tester/dist/
For example this clock works well. https://cl.ly/e07a05eca40d here in after
effect
https://cl.ly/6231eaeb5bca here on the website
But this character instead not. here in after effect
https://cl.ly/9141d5aac711
and here on the website, how you can see, the character is not visible,
why? https://cl.ly/2d9446c68bc6
I have bodymoving version 5.4.1

Il giorno gio 22 nov 2018 alle ore 21:09 bada fra <badafra2001@gmail.com>
ha scritto:

**Comment by badafra** [comment]
yeah I sent a winrar with aep inside on your email!

**Comment by bodymovin** [comment]
The puppet pin effect is not supported unfortunately.

**Comment by badafra** [comment]
Oh i understand! Di You think Will You add this updating in the future?Inviato dal mio dispositivo mobile Huawei-------- Messaggio originale --------Oggetto: Re: [airbnb/lottie-web] Problem with some composition and export (#1382)Da: hernan A: airbnb/lottie-web CC: badafra ,Author The puppet pin effect is not supported unfortunately.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/airbnb/lottie-web","title":"airbnb/lottie-web","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/airbnb/lottie-web"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bodymovin in #1382: The puppet pin effect is not supported unfortunately."}],"action":{"name":"View Issue","url":"https://github.com/airbnb/lottie-web/issues/1382#issuecomment-441123317"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/airbnb/lottie-web/issues/1382#issuecomment-441123317",
"url": "https://github.com/airbnb/lottie-web/issues/1382#issuecomment-441123317",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [airbnb/lottie-web] Problem with some composition and export (#1382)",
"sections": [
{
"text": "",
"activityTitle": "**hernan**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@bodymovin",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"airbnb/lottie-web\",\n\"issueId\": 1382,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"airbnb/lottie-web\",\n\"issueId\": 1382\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/airbnb/lottie-web/issues/1382#issuecomment-441123317"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 415190823\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by bodymovin** [comment]
Unfortunately not. Puppet pin is very complicated to reproduce and it probably wouldn't have great performance for real time animations.

**Comment by badafra** [comment]
Hello, i need an information! I create this animation with my vector file,
but when i try to export with bodymoving, the export ins't complete, or
better only some part of my character are moving, i think the problem is
the puppet of after effect! How can i resolve?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Il giorno dom 19 mag 2019 alle ore 03:40 hernan <notifications@github.com>
ha scritto:

**Comment by bodymovin** [comment]
Hi, puppet effect is not supported by the player unfrotunately.
