### ISSUE TITLE
Issue with loading animation

### ISSUE THREAD

**Issue by Sebasschmidt** [airbnb/lottie-web#1384]
Hi there, 
I'm using the bodymovin plugin in Wordpress for my portfolio website. But having some issues here. It's still full of demo content but I did load some custom animations in it. You can see it [here](https://signatured.nl/), problem is that when I visite the contact page from the homepage and go back again, the animation won't load.. 
This is how i load it `[bodymovin anim_id="8124" loop="true" lazyload="true" autoplay_viewport="true" autostop_viewport="true" width="300px" align="center"]` But changing these values won't help.

**Comment by bodymovin** [comment]
From what I can see [here](https://signatured.nl/wp-content/plugins/wp-bodymovin/assets/js/wpbodymovin.min.js?ver=2.0.1) , you are loading the animation on the `jQuery(document).ready` function. But that method is invoked only once when the page loads.
Once you navigate within the pages, your theme handles the url navigation and that event is not dispatched anymore.
I don't know how this wordpress web works, but you should look for some page change event that lets you load the animation every time you visit this view.

**Comment by Sebasschmidt** [comment]
Must be this part, found this in the editor of the plugin:
`jQuery( document ).ready(function( $ ) {

	wpbdmv.animations = {};

	if ( typeof( wpbdm_preview_data ) !== 'undefined' ) {
		var animData = {
			container: document.getElementById('wpbdmv-anim-preview'),
			renderer: jQuery('#wpbdmv_renderer').val(),
			loop: true,
			assetsPath: jQuery('#wpbdmv_assets_path').val(),
			autoplay: true,
			rendererSettings: {
				progressiveLoad:false
			},
			animationData: wpbdm_preview_data
		};

		wpbdmv.animations.wpbdm_preview = bodymovin.loadAnimation(animData);

		wpbdmv.animations.wpbdm_preview.onLoopComplete = function() {
			if ( !$('.wpbdmv-anim-controls').hasClass('repeat') ) {
				$('.wpbdmv-anim-controls').removeClass('playing');
				wpbdmv.animations.wpbdm_preview.stop();
			}
		};

		$('.wpbdmv-anim-controls').addClass('playing');
	}`
I'm not into coding though, what should I change?

**Comment by Sebasschmidt** [comment]
Fixed it;)
