### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by mendax47** [airbnb/lottie-web#1385]
Uncaught SyntaxError: Invalid or unexpected token
    at _expression_function (eval at initiateExpression (lottie.min.js:7), <anonymous>:4:59)
    at l.executeExpression (lottie.min.js:7)
    at l.n [as getValue] (lottie.min.js:2)
    at a.iterateDynamicProperties (lottie.min.js:2)
    at a.e [as getValue] (lottie.min.js:2)
    at SVGShapeElement.prepareProperties (lottie.min.js:4)
    at SVGShapeElement.prepareFrame (lottie.min.js:4)
    at SVGRenderer.renderFrame (lottie.min.js:4)
    at AnimationItem.renderFrame (lottie.min.js:6)
    at AnimationItem.gotoFrame (lottie.min.js:6)
_expression_function @ VM1054:4
executeExpression @ lottie.min.js:7
n @ lottie.min.js:2
iterateDynamicProperties @ lottie.min.js:2
e @ lottie.min.js:2
prepareProperties @ lottie.min.js:4
prepareFrame @ lottie.min.js:4
SVGRenderer.renderFrame @ lottie.min.js:4
AnimationItem.renderFrame @ lottie.min.js:6
AnimationItem.gotoFrame @ lottie.min.js:6
AnimationItem.checkLoaded @ lottie.min.js:6
AnimationItem.waitForFontsLoaded @ lottie.min.js:5
AnimationItem.configAnimation @ lottie.min.js:5
a.onreadystatechange @ lottie.min.js:3
XMLHttpRequest.send (async)
e @ lottie.min.js:3
AnimationItem.setParams @ lottie.min.js:5
n @ lottie.min.js:5
loadAnimation @ lottie.min.js:1
(anonymous) @ app.js:3

Here is the demo file..

[data.zip](https://github.com/airbnb/lottie-web/files/2610882/data.zip)

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by bodymovin** [comment]
It seems there are expressions in the json created with tools that encrypt / obfuscate them.
Unfortunately, those type of expressions are not supported since they can' t be read by the player.

**Comment by mendax47** [comment]
Thanks Bro... For Your Quick Answser.. Actually I Don't Have Much Experience In after Effect.. So I Brought Some Pack From videohive and try to convert one of the effect... most of them works pretty well.. but not all of them.. :)

**Comment by bodymovin** [comment]
yes, unfortunately, some of those templates use this type of unsupported features
