### ISSUE TITLE
Control animations loaded from divs

### ISSUE THREAD

**Issue by herrmanneffe** [airbnb/lottie-web#1386]
Hi,
if I load an animation inside a div, like this:
`<div class="bodymovin" data-animation-path="JS/Step1.json" data-anim-loop="true" data-anim-type="svg" data-name="ninja"></div>`

How can I address this animation with "relative" methods like this?
playSegments(segments, forceFlag); 
goToAndPlay(value, isFrame);
setSpeed(speed);
ecc.

This does't work...
`var anim2 = bodymovin.play('ninja');
anim2.playSegments([[10,40],[20,50]],true);`

here is the codepen: [https://codepen.io/FedMann/project/editor/AoxoLN](url)

Thank you for the help

**Comment by bodymovin** [comment]
`goToAndPlay` supports calling it by name.
but `playSegments` does not.

**Comment by herrmanneffe** [comment]
how do I call `goToAndPlay();` by name?  I see that you can pass only a value and a bolean...

**Comment by herrmanneffe** [comment]
Hi Danjuanlab,

this is what I was looking for 👍 thank you, unfortunately I am not able to answer your question... I don't know if there is a more "correct" calling method...

**Comment by Danjuanlab** [comment]
> Hi, im having the same issue as op. I'm still not clear on how to call an animation to play by name. The documentation states:
> 
> bodymovin.play() -- with 1 optional parameter name to target a specific animation
> 
> So im calling bodymovin.play('ninja') but nothing happens

you need to check the sample code:https://codepen.io/collection/nVYWZR/

**Comment by glynthink** [comment]
@Danjuanlab none of those example are initialing the animations from the html, all use bodymovin.loadAnimation()

Am I missing something between calling the lottie.js file and calling the .play() method on an animation i defined in the html ?

**Comment by bodymovin** [comment]
@glynthink hi, do you have a link with your implementation to check it out?

**Comment by glynthink** [comment]
@bodymovin here is a live link: http://intra.think.com.mt/think.mt

**Comment by bodymovin** [comment]
I guess the problem is that the animation's `loop` property is set to false, so calling play(), being already at the end of the animation, won't play again.
try doing:
`lottie.goToAndStop(0,true,'ninja');lottie.play('ninja');`
and it should work

**Comment by glynthink** [comment]
I understand, yeah that works.

Thanks
