### ISSUE TITLE
Animations stop at 1st frame

### ISSUE THREAD

**Issue by djkato** [airbnb/lottie-web#1387]
![image](https://user-images.githubusercontent.com/25299243/48979975-1b2ca600-f0c3-11e8-9790-069c542e919a.png)
I use PHPStorm for coding; after effects ver.14.0.1.5, 2017 release, newest bodymovin;Chrome Version 70.0.3538.110 (official build) (64-bit version)
Im trying to make a website, but I cant even load multiple animations onto it at once. Ive been banging my head against the wall for the past 3 days, trying custom .js to make it work, trying suggested scripts for it to work, and right now Im trying to use a prewritten script written by someone from the examples page. The grid 9 animations one. Im quite new to JS and a bit experienced with CSS and HTML, so I have no idea what Im doing wrong.
I expected my animations to start playing at the load of the page, but only one does what its suppose to do. Rest is obviously stuck at the 1st frame of playback. I only replaced the path from the preset the guy wrote on his site, so my animations would play instead of his, because I probably have written something wrong in my script attempts.

[Website.zip](https://github.com/airbnb/lottie-web/files/2613144/Website.zip)

**Comment by bodymovin** [comment]
there seems to be a problem with an expression looking for a layer that doesn't exist.
I think it's because in your composition: `grid Comp 1` you have an expression on each layer that targets the following layer.
But the second to last layer is targeting the layer "grid" which is hidden and hence, not exported.

**Comment by djkato** [comment]
Omgosh it works now! Im so happy. Thank youu <3
