### ISSUE TITLE
RubberHose render with Bodymovin - animation not working

### ISSUE THREAD

**Issue by inguuuna** [airbnb/lottie-web#1388]
**Tell us about your environment**

* **Browser and Browser Version:** Chrome Version 70.0.3538.102 (Official Build) (64-bit)
* **After Effects Version:** 16.0.0 (Build 235)

**What did you do? Please explain the steps you took before you encountered the problem.** I'm trying to create a simple limb movement with RubberHose 2 to be rendered with Bodymovin by animating ankle position and hose length. However, when rendered through Bodymovin and open the json file with lottie files or in the built in previewer no animation happens - the limb stands still.

I'm fairly new to the rubberhose and bodymovin. It seems fairly easy and straight forward but this has been a massive road block for me for days now and I cannot seem to figure out what's wrong. Been scraping the internet for answers but cannot find the right solution for this. Please help out! Am I missing something simple?

**Please provide a download link to the After Effects file that demonstrates the problem.** I cannot share the original ae file but I have created a simple version of what I am trying to do and it has the same problem. 
Here is the link to the ae file: https://we.tl/t-9st1V8mXvx
And Lottie Files preview: https://lottiefiles.com/share/5vULHV

Thanks in advance! :)

**Comment by bodymovin** [comment]
Hi, unfortunately, the Puppet Pin effect is not supported by the player.

**Comment by inguuuna** [comment]
Hey! Thanks!

Really needed something like pupper pin effect for this project and hoped that RubberPin would be a good solution. It seems like Bodymovin only supports RubberRig then, am I right?

**Comment by bodymovin** [comment]
Hi, not sure about the naming, but bodymovin doesn't support puppet effect indeed.

**Comment by inguuuna** [comment]
ah :(

ok! Thanks a lot anyway !

**Comment by Strange-love** [comment]
so bodymovin doesn't export rubberhose animations period? Or only Rubber rig? I really wish they told you this stuff

**Comment by Strange-love** [comment]
I'm having a really hard time figuring out what is and is not compatible for rendering svg animations using bodymovin. The documentation is kind of thick and I'm still reading through it but there is very little information online covering this topic
