### ISSUE TITLE
How to Replace Json file path by Json content

### ISSUE THREAD

**Issue by KetanKatariya** [airbnb/lottie-web#1389]
How do I replace JsonFile name by JsonContent in loadAnimation(),
Ex:
var anim = lottie.loadAnimation({
                container: document.getElementById('dome'),
                renderer: 'svg',
                loop: false,
                autoplay: false,
                **path: 'fileName.json'**  -> here I want to set something like this 
               **data: '{JSON Object}'** });
Please guide for the same or give me some alternative so that I can set JsonObject directly instead of JsonFile Path.

**Comment by bodymovin** [comment]
use 'animationData' instead of 'path' and pass it as an object, not a string

**Comment by KetanKatariya** [comment]
Hi,
Thanks for the support and this awesome plugin...
