### ISSUE TITLE
Vector icons are not exporting correctly

### ISSUE THREAD

**Issue by floredegunst** [airbnb/lottie-web#1390]
**Tell us about your environment**

* **Browser and Browser Version:**
Chrome Version 69.0.3497.10
(safari en firefox is the same problem)

* **After Effects Version:**
Version 16.0.0

**What did you do? Please explain the steps you took before you encountered the problem.**
It was a complicated animation so i pre-composed some of the layers. In those layers I created vector shapes from the icons and in After effects it looked great. The same as in illustrator.

**What did you expect to happen?**
The icons don't export correctly. The browser icon and the data icons are missing layers and colors. It is al the same vector shape layer so I don't know what happend here. The other icons seem to work fine.

**What actually happened? Please include as much _relevant_ detail as possible.**
This: (left is after effects and right is demo.html) The icons are missing details and colors.
![2018-11-26 17 10 38](https://user-images.githubusercontent.com/44051903/49026798-07ef0880-f19f-11e8-845f-9a9353609163.gif)

**Please provide a download link to the After Effects file that demonstrates the problem.**
[GXS dit doen wij 5. finetuning.aep.zip](https://github.com/airbnb/lottie-web/files/2616423/GXS.dit.doen.wij.5.finetuning.aep.zip)

**Comment by bodymovin** [comment]
Hi I can't open the project.
It might be related to some missing files.
Can you share them?

**Comment by floredegunst** [comment]
Sorry! My bad...

[GXS github.zip](https://github.com/airbnb/lottie-web/files/2619211/GXS.github.zip)

**Comment by bodymovin** [comment]
Hi, there is a bug in AE 2019 which prevents me from opening projects that have the project files unlinked.
So I can't open this project on my computer.
Can you try saving it for AE 2018 or linking the files in the project and saving it again?

**Comment by floredegunst** [comment]
This file should work, there is no files attached now. Everything was vector based anyway so the files were useless. I took another look at the problem and it seems to be having some trouble exporting the masks. But in after effects they look perfectly fine. I added a jpg with an example:
![schermafbeelding 2018-12-03 om 17 01 22](https://user-images.githubusercontent.com/44051903/49385185-20ba6980-f71d-11e8-9da3-9790cefadeee.png)


[GXS dit doen wij github.aep.zip](https://github.com/airbnb/lottie-web/files/2640169/GXS.dit.doen.wij.github.aep.zip)

**Comment by bodymovin** [comment]
I still can't open the project.
I know they're fixing the issue but meanwhile there's many CC 2019 projects I can't verify.
Can you save it for an older version of AE?

**Comment by floredegunst** [comment]
Hmmm strange...

Do you know a quick way to export it for an older version?

**Comment by bodymovin** [comment]
Can you check if there's an option in Save As..?

**Comment by floredegunst** [comment]
Not quite sure if this is it but we can try! haha 

[GXS dit doen wij github copy CC (15.x).aep.zip](https://github.com/airbnb/lottie-web/files/2653281/GXS.dit.doen.wij.github.copy.CC.15.x.aep.zip)

**Comment by bodymovin** [comment]
Ok, I managed to open that last file.
Those layers are using Merge Path which unfortunately is not supported by the player.
Foe Example on Composition 3. browser, layer 3 Outlines > Contents > Group 2 and Group 3, if you remove the Merge Path of each and Path 2, I think the drawing looks the same and the animation will be fixed.
