### ISSUE TITLE
Animation with masks problem with HTML5 on SPA

### ISSUE THREAD

**Issue by p3pp8** [airbnb/lottie-web#1391]
Animations with masks are corrupting on single page application when the animation persists over HTML5 location changes. In a single page app(SPA) i've a surrounding frame where some animation remains always visible(so, initialized once and left playing continuously) and a main content body that changes based on current location address. The problem, i think, is that i've initialized the persistent animation using an URL that changes in time based on content that should be displayed and this is causing trouble to the Lottie player on animations that use masks where the URL is different from the one the animations are initialized with. I hope the problem is enough  clear, sorry for the naive english. Any suggestion is really appreciated!!!

**Comment by bodymovin** [comment]
It's an interesting scenario, not sure if there is a workaround right now.
Can you share a link so I can look into it some more?

**Comment by p3pp8** [comment]
@bodymovin confirmed, going back to the same  URL to when the animation is initially created the problem disappears. I've found a workaround to this, just hide the DOM node used to render the animation whenever the URL changes and than show it back, masks turn to be fine again. There must be some hash used by the player that involve the URL to do retrieve data or something else, very strange anyway...
Thanx
