### ISSUE TITLE
Do you have how to remove animation after completed loading ?

### ISSUE THREAD

**Issue by pororia** [airbnb/lottie-web#1395]
I try to load user selected animation  after check each interval time.
So, I looking for remove animation on browser after complete loading animation.

I tried use lottie.destory(). 
But, It occur problem because of each animation different of loading time.

Do you have how to remove animation after completed loading?
For example...
1. how to remove after completed loading.
2. how to catch event about completed loading.
3. ........

**Comment by bodymovin** [comment]
you can add a listener to the animation instance: `anim.addEventListener('complete',()=>{anim.destroy()})`

**Comment by pororia** [comment]
Thank you for your quick and correct answer.
I resolved, thanks to your answer.
