### ISSUE TITLE
Bodymovin Render : geometric effect

### ISSUE THREAD

**Issue by juliettebdec** [airbnb/lottie-web#1396]
Hello everyone !

First of all, I want to say Bodymovin is a great tool for design and developper, especially to collaborate better. Thanks a lot !

However, I have an issue when I export my long animation.
I used Geometric effect on layers and compositions to create a isometric view of an element, but when I export it with Bodymovin and my developper uses it, it doesn't work, it's still in 2D.
<img width="265" alt="capture d ecran 2018-11-27 a 16 01 21" src="https://user-images.githubusercontent.com/40021558/49090337-c6716280-f25d-11e8-94cb-2654045801c6.png">
<img width="260" alt="capture d ecran 2018-11-27 a 16 01 52" src="https://user-images.githubusercontent.com/40021558/49090338-c6716280-f25d-11e8-98a5-43ac19318f4a.png">

Do you guys ever have this kind of issue ?

Many thanks,

Juliette

**Comment by Danjuanlab** [comment]
The Geometric effect is currently not supported by bodymovin. If you want an isometric effect, you can try to simulate it with 3D rotation, or by rotating the camera.

**Comment by julietteformonet** [comment]
Hi Danjuanlab ! 
Thanks for your answer. 
The point is I can't do it, I don't find any solution when I transform my layer / composition in 3D layer and try to rotate it to create a perfect isometric position. Do you have any idea how I could do ? Any coordinates I could put for X Y Z rotation ?

Thanks a lot

**Comment by Danjuanlab** [comment]
> 嗨Danjuanlab！
> 感谢您的回答。
> 关键是我无法做到，当我在3D图层中转换图层/合成并尝试旋转它以创建完美的等距位置时，我找不到任何解决方案。你知道我怎么办吗？我可以用于XYZ旋转的任何坐标？
> 
> 非常感谢


[Isometry Shape right.zip](https://github.com/airbnb/lottie-web/files/2628839/Isometry.Shape.right.zip)

**Comment by bodymovin** [comment]
@julietteformonet Hi, 3d support has limited support with the player. It works if you don't have nested 3d layers.
If you have an .aep you can share, I'll take a look at it.

**Comment by julietteformonet** [comment]
> @julietteformonet Hi, 3d support has limited support with the player. It works if you don't have nested 3d layers.
> If you have an .aep you can share, I'll take a look at it.

Thanks !!! It would be great ! Where can I write to you ?

**Comment by bodymovin** [comment]
@julietteformonet hernantorrisi[at]gmail.com

**Comment by Zavarski** [comment]
Please see attached the comparison. Stroke Lines are slightly cropped.

![comparison](https://user-images.githubusercontent.com/30810912/49276368-ffd8e680-f486-11e8-9e62-a109317ba710.jpg)

**Comment by bodymovin** [comment]
@Zavarski can you share the .aep?

**Comment by Zavarski** [comment]
Sure, I attached in my first message, but please see on the link https://drive.google.com/open?id=1qIPUEqupR8cIC__Up06cmn6qVqSkqwAV 
Also I sent you file via email

**Comment by bodymovin** [comment]
@Zavarski Are you using the html renderer by any chance?
When I try the svg renderer it seems to work fine.

**Comment by Zavarski** [comment]
@bodymovin Thank you! 
Yes, I use HTML renderer. 
I just checked the JSON version it is work correct as you wrote. 
Please let me know if this can be fixed. In certain cases I need html

**Comment by bodymovin** [comment]
When using the html renderer, strokes sometimes don't get rendered correctly.
If you add a rectangle with a transparent fill on each layer where the stroke doesn't look ok, it should fix it.

**Comment by Zavarski** [comment]
@bodymovin It works. Thank you very much for your help!
