### ISSUE TITLE
Morphing shape is not exporting correctly for json.

### ISSUE THREAD

**Issue by izatagarela** [airbnb/lottie-web#1398]
Hi,

I’m using the last version of after effect. I create animation using shape morphing but when I export for json the animation doesn’t perform correctly. On after effect the animation is good and exporting to video everything goes fine. I need help with this issue, please. I have the morphing in 4 layers? Can that be the problem?

**Comment by bodymovin** [comment]
can you share the .aep?

**Comment by bodymovin** [comment]
@izatagarela it didn't come through. Github doesn't support attachments from emails.

**Comment by izatagarela** [comment]
[liquid_Go_Loader_IZA.aep.zip](https://github.com/airbnb/lottie-web/files/2628959/liquid_Go_Loader_IZA.aep.zip)

**Comment by bodymovin** [comment]
There is a bug in AE 2019 that prevents me from opening the project. Does it have unlinked files by chance?
Can you try saving it for an older AE version?

**Comment by izatagarela** [comment]
I only used shapes.  Try open this file: 
[liquid_Go_Loader_IZA.aet.zip](https://github.com/airbnb/lottie-web/files/2629008/liquid_Go_Loader_IZA.aet.zip)

**Comment by Karennnnn** [comment]
Maybe you are using experssion on path. ?
