### ISSUE TITLE
Animation not rendering in rails app

### ISSUE THREAD

**Issue by willyGitHub18** [airbnb/lottie-web#1402]
Hi, 
 I want to render an animated map in a ruby on rails app but I can't figure out how to organize the files for it to work.
I've followed the tutorial and the animation is working correctly on a simple web page but as soon as I am trying it inside the rails app, it doesn't.
I am pretty sure it comes from my file's tree but I don't know how to do it.

Would you have any recommendation?

PS: Enclosed are all my files and an "images" folder (this way the index file renders the animation)

[Test.zip](https://github.com/airbnb/lottie-web/files/2633302/Test.zip)

**Comment by bodymovin** [comment]
Hi, I've tried the project in the zip and everything seems to work fine.
Can you share a link where it fails?

**Comment by willyGitHub18** [comment]
Hi,

Thank you for your quick reply.
I can’t say that it’s not wirking per say, it’s more that I don’t really know how to organize my files into my project.
If you take for exemple this project 
https://github.com/willyGitHub18/fantastic-pointers-lyon?files=1
I’ve tried to put the files into the assets/JavaScript or the Views.

**Comment by mtgentry** [comment]
UPDATE:  My images were indeed on the wrong path : P All good now. When adding an animation to your rails project, your paths may need to be different from the folder structure you used when making your animation. Just had to update the JSON file with correct image paths.

**Comment by ihortrypolskyi** [comment]
@willyGitHub18 according to '"u":"images/"' in data.json, try to put assets to public/images or public/MODEL_NAME/images
