### ISSUE TITLE
Problème Bodymovin

### ISSUE THREAD

**Issue by Pacha4** [airbnb/lottie-web#1403]
Bonjour, j'ai un problème avec bodymovin, j'ai fais une anim de cycle de marche avec l'outil marionnette sur AE mais lorsque je fais le rendu demo.html avec Bodymovin rien ne s'affiche. L'outil marionnette est pris en compte par la plugin? Une solution par pitié ?

**Comment by Pacha4** [comment]
Hello, I have a problem with bodymovin, I animated a cycle of walking with the puppet tool on After Effect but when I export the file in demo.html with Bodymovin nothing is displayed. The puppet tool is taken into account by the plugin? A solution please?

**Comment by bodymovin** [comment]
salut, le puppet tool n'est pas supporté par le plugin malheureusement.

**Comment by Pacha4** [comment]
Ok merci beaucoup de votre aide.
