### ISSUE TITLE
Issues with animation in browsers in iOS 12.1

### ISSUE THREAD

**Issue by elvintsang** [airbnb/lottie-web#1406]
**Tell us about your environment**
iOS 12.1
MacOS High Sierra 10.13.6

* **Browser and Browser Version:**
Safari / Chrome
Firefox 63.0.3

* **After Effects Version:**
After Effects CC 2019 Version 16.0.0 (Build 235)

**What did you do? Please explain the steps you took before you encountered the problem.**
I created an animation, exported it using the Bodymovin plugin with the Demo setting to generate an html file.

**What did you expect to happen?**
The animation plays as expected

**What actually happened? Please include as much _relevant_ detail as possible.**
The animation plays fine on desktop browsers, however on the latest iOS 12.1 there seems to be an issue in both Safari and Chrome, where some of the elements seem to invert to black after briefly showing correctly in the right colours. The issue seems to be happening only in iOS 12.1 as I have tested in an older version of iOS and on Android and its working fine. It seems like the issue is due to use of alpha matte masks, as removing them seems to rectify it. Are there any known issues with iOS and alpha matte masks? Also, in Firefox on desktop, the colour masked in the bottom half of the phone appears masked but in a smaller square rather than the desired shape, and the 2 lines at the top sometimes don't animate in. Resizing the browser to scale the animation corrects it but not when the animation loops again.

Slightly separately, I was having issues where border of the phone would disappear when scaled in Safari above a certain size – when I removed the drop shadow (applied as an effect) this seemed to fix this particular issues. Should the drop shadow effect be supported?

**Please provide a download link to the After Effects file that demonstrates the problem.**
Animation can be found here: http://dekoanim.madebytaylorthomas.co.uk/homepage-anim-hero.html
After effects file attached – composition in question is home-hero
[Deko.aep.zip](https://github.com/airbnb/lottie-web/files/2643559/Deko.aep.zip)

**Comment by elvintsang** [comment]
I've managed to resolve most of the issues by removing all alpha mattes and using vector masks instead. The only issue that remains now is how to achieve drop shadows.

Using the drop shadow applied as an effect doesn't work very well in Safari, or at all on iOS. Using a png of the shadow set to encode in the json causes some strange artifacts to appear, faint grey vertical and horizontal lines around the shadow area. This seems to happen only when masks are involved, when masked shapes are transforming.

**Comment by bodymovin** [comment]
Have you tried applying the drop shadow via css?

**Comment by jackbbhua** [comment]
same not working on ios 12.1.2
