### ISSUE TITLE
Call to loadAnimation takes 6 seconds when deployed

### ISSUE THREAD

**Issue by JaceHensley** [airbnb/lottie-web#1408]
**Tell us about your environment**

Using webpack 4 to bundle my JS.

Importing .json files via:
```
import * as lottie from 'lottie-web/build/player/lottie_light'

import * as data from './animation.json'

lottie.loadAnimation({animationData: data, renderer: 'svg'})
```

* **Browser and Browser Version:**
- Chrome 71
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

Call `lottie.loadAniation` (using lottie_light.js)

**What did you expect to happen?**

local and prod having the same behavior

**What actually happened? Please include as much _relevant_ detail as possible.**

Locally the call to `lottie.loadAnimation` takes >1s but when I deploy to prod it takes ~6s

I don't think this a problem with lottie, but I'm wondering if someone else has had this happen or any ideas on where to look. Thank you for any help 😄

Local:
<img width="830" alt="screen shot 2018-12-05 at 12 51 36 pm" src="https://user-images.githubusercontent.com/6597117/49540592-b412ac80-f88d-11e8-9564-2874a2175f13.png">

Prod:
<img width="1656" alt="screen shot 2018-12-05 at 12 49 44 pm" src="https://user-images.githubusercontent.com/6597117/49540593-b412ac80-f88d-11e8-9afc-028ab02a640b.png">

**Comment by bodymovin** [comment]
Hi, can you share the json file?

**Comment by JaceHensley** [comment]
Yeah, it's quite large haha. And I'm totally fine with how long it takes locally or even if they were both slow we'd probably make a smaller animation overtop a static img or something. 

Yeah this is up live [here](https://bloom.co/), thanks again for taking a look

**Comment by JaceHensley** [comment]
Friendly bump 😄

**Comment by bodymovin** [comment]
I don't think it's related to the animation.
There seems to be some stalling when loading this file:
https://bloom.co/api/sessions
Which apparently doesn't allow the document ready event to be fired and in consequence, the rest of the page and the animation don't load until that request returns a 404.
Can you try removing that request or making sure it doesn't return a 404 after the timeout?

**Comment by JaceHensley** [comment]
It's only loading the visible ones at the start and then it starts with the hidden ones after a few seconds or when they are about to be scrolled into view

**Comment by bodymovin** [comment]
From a quick look the other svgs seem to be loaded right from the beginning,
Can you try not loading the others ones at all to see if someting changes?

**Comment by JaceHensley** [comment]
Just tried with only that animation and it still takes ~6 seconds in loadAnimation

**Comment by bodymovin** [comment]
Can you update the link?

**Comment by JaceHensley** [comment]
I can't deploy that to our live site since it basically breaks the page's design. But the performance flame chart of the single loadAnimation looks the same whether it's just that animation or what's on that link right now

**Comment by JaceHensley** [comment]
Hmm okay so this is really weird. I turned off minimization and it works as expected. I'm using UglifyJsPlugin for webpack. Will report back when I figure out which option is breaking it 😄.

**Comment by JaceHensley** [comment]
Switched to terser-webpack-plugin and it worked! Thanks for helping me debug this

**Comment by bodymovin** [comment]
Glad it worked, but really curious as to why using the uglify plugin broke it int he first place.
I'll try to look into it.
