### ISSUE TITLE
Masks and Gradients not working in Safari

### ISSUE THREAD

**Issue by Deeangelo** [airbnb/lottie-web#1409]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by Deeangelo** [comment]
http://ncc.dev.zgm.ca/en/

The masks and gradients aren't working when view on safari after exporting with bodymovin. Just wondering what I should do to fix this?

**Comment by bodymovin** [comment]
Hi, sorry about the delay, did you finally got it working?
