### ISSUE TITLE
error line 256 object is invalid bodymovin

### ISSUE THREAD

**Issue by Folkati** [airbnb/lottie-web#1412]
Hi,

I got this message as a bug for my project. It's made by the newest AE (2019) and I can't find a solution. It's a scene with a camera moving over object. Could you please help me? 

gr

Folkert
![image](https://user-images.githubusercontent.com/45401074/49746604-d3507600-fca1-11e8-85d6-3822c40f396d.png)

**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by Folkati** [comment]
Did i send it?

**Comment by Folkati** [comment]
How do I do that?
[MAO's - Copy.zip](https://github.com/airbnb/lottie-web/files/2667154/MAO.s.-.Copy.zip)

Ok, I think you can open it now wright?

**Comment by Folkati** [comment]
Hi, can you send a reply if you read the last post. I can really use youre help.

gr

**Comment by bodymovin** [comment]
Yes, I'll try to look into it later today

**Comment by Folkati** [comment]
Thanx a lot!!

**Comment by Folkati** [comment]
[MAO's.zip](https://github.com/airbnb/lottie-web/files/2676688/MAO.s.zip)

Hi, I deleted all AI files. I'm sharing this through a adobe libary. 
I'm also working directly from a google cloud file? maybe thats whats bugging the system?

what are nested 3d elements

**Comment by Theodoralu** [comment]
Hi, I happened to have the same problem. Has this been solved yet?

Thanks!

**Comment by bodymovin** [comment]
Hi @Theodoralu , can you share an .aep with the issue?
