### ISSUE TITLE
Chrome Issue?

### ISSUE THREAD

**Issue by yoob96** [airbnb/lottie-web#1413]
**Tell us about your environment**
Mac OS Sierra 10.12.6 
* **Browser and Browser Version:**
Google Chrome

* **After Effects Version:**
16.0.0

I've rendered my animation and trying to employ it in my website, but it keeps popping up the error in inspector saying it's invalid?
<img width="1432" alt="screen shot 2018-12-10 at 6 39 32 pm" src="https://user-images.githubusercontent.com/43386927/49768776-7eb1f880-fcab-11e8-8a2e-38899ac399a7.png">

**Comment by bodymovin** [comment]
you need to use a web server, 
for security reasons browsers don't allow to load json files when executing the html directly from the file system.
