### ISSUE TITLE
Ease and Wizz Export Issue  

### ISSUE THREAD

**Issue by samnielsen17** [airbnb/lottie-web#1415]
**Tell us about your environment**
Mac OS High Sierra

* **Browser and Browser Version:**
Chrome 71 

* **After Effects Version:**
After Effects CC v 16.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**
I built a simple comp employing Ease & Wizz for easing rules. I exported the JSON file and tested the animation locally, as well as on the Lottie Preview site. In each environment, the Ease & Wizz effect was jumpy and not as it appeared in AE. 

**What did you expect to happen?**
I expected the animation to render in browser exactly as it plays in After Effects.

**What actually happened? Please include as much _relevant_ detail as possible.**
After reading that this was an issue in previous Bodymovin versions (I am using 5.4.2), I deleted the 'use strict' lines from the lottie.js file I was using. The problem still persisted after doing this. 

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/9txti8p8wa7ji7b/Device-Transition-Test.aep?dl=0

**Comment by bodymovin** [comment]
Hi, this was a problem with the valueAtTime function for shapes.
It's going to be fixed in the next deploy.

**Comment by Eklor** [comment]
In After effect 
Do a copy of your comp for backup in case you want to change the Ease and wizz,

Select all the properties that have expressions applied (position, rotation... etc) 
And go to : ANIMATION > Keyframe assistant > Convert Expressions to keyframes

And then your animation should export properly with BM.

**Comment by samnielsen17** [comment]
Oh awesome @bodymovin  

Do you have an ETA for the next deployment?

**Comment by bodymovin** [comment]
some day this week.
