### ISSUE TITLE
Question: Is where ios-lottie addSubview toKeypath analogue?

### ISSUE THREAD

**Issue by zinoviev** [airbnb/lottie-web#1417]
Hi! In Lottie for ios where is an option to add subview for some keypath to animate image, what was not a part of source animation. Just like this in docs http://airbnb.io/lottie/ios/addsubviews.html Can we do the same for lottie-web?

**Comment by bodymovin** [comment]
Hi, there is nothing built-in.
But if you use the svg or html renderer, it should be pretty simple to replace a layer content with custom markup like images.
You can name your layers in AE with a dot or a hash and that might simplify the process to target them.
https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript

**Comment by zinoviev** [comment]
@bodymovin Thx a lot!  One more question, if we need to change layer colors like https://airbnb.io/lottie/ios/dynamic.html we can use came approach - query named layers via selectors and manipulate svg attributes, right?
