### ISSUE TITLE
Trim Paths issues in Firefox & Edge

### ISSUE THREAD

**Issue by helloidevthings** [airbnb/lottie-web#1418]
5 of the animations we are using aren't working well with: Edge and Firefox

Animation created with: Trim paths and opacity (are not actually animating in these browsers)

Ex: 
[https://drive.google.com/file/d/1a_UQiZ9K5rfGZt-SLL2uzKtKW3dFEbn3/view?usp=sharing](url)

Works great in Chrome: 
[https://accessventures.org/our-approach/investment-approach/](url)

**Comment by bodymovin** [comment]
I see the animation might be using effects or track matte masks that might be affecting performance.
Do you know if you're using any of those?

**Comment by joyannahirst** [comment]
I'm not using any effects or any masks to those specific parts of the animation. Only imported illustrator drawings, creating shapes from them, and used trim paths, opacity, and positioning.

Would you like me to send the file?

**Comment by bodymovin** [comment]
yes, please

**Comment by joyannahirst** [comment]
[https://www.dropbox.com/s/attqpocqzdsu6ak/AV_One%20Pocket%20165x165.aep?dl=0](url)

**Comment by bodymovin** [comment]
the composition `02_Equity` has three layers that are set with alpha masks: `Mask`, `Mask 2`, `Mask 3`

**Comment by joyannahirst** [comment]
Ok, so what should I have the designer do about those? (I am a developer)

**Comment by bodymovin** [comment]
I'd ask the designer to replace those alpha masks with regular masks or remove them altogether. It looks like they can be easily removed.
But it seems the main problem is with trim paths that are taking a lot of time.
I'll need more time to look into it.
Perhaps there's many layers with trim path applied to them?

**Comment by joyannahirst** [comment]
Ok, sounds good. I have let the designer know this.

**Comment by bodymovin** [comment]
One thing you can do is call `lottie.setQuality('low')`.
It will reduce the amount of paths it calculates improving performance and in your case it won't be noticeable.
