### ISSUE TITLE
Wordpress directions?

### ISSUE THREAD

**Issue by moodonis** [airbnb/lottie-web#1419]
Are there any up to date directions for how to use this with Wordpress, without using the existing Bodymovin Wordpress Plugin? I know the plugin works, but it doesn't provide full control over the animations, plus it's another plugin to install and track. 

I am using:

WP 4.98
Divi theme

Despite my best efforts and following the directions posted in the issues here (older issues, 1+ year), I cannot get the lottie animations to load natively. Again this needs to be without the existing Wordpress plugin.

**Comment by bodymovin** [comment]
Hi, I'm not very familiar with Wordpress dev, but as long as you can add custom script tags and host the json somewhere, I think it should work.
Do you have a link I can take a look at to see what is failing?
