### ISSUE TITLE
Json and demo file not exporting as proper animation

### ISSUE THREAD

**Issue by wesleyphung1** [airbnb/lottie-web#1421]
Hi, my json and demo file are not exporting as the proper animations. 

I'm not sure if the settings are off but I have had difficulties dealing with this.

Please LMK if any of you have a solution.

I've linked the project file and assets below.

THANKS! 
https://drive.google.com/open?id=1tvGz79d4gvM46tLPMBxyOZXTagsHvz8i

**Comment by bodymovin** [comment]
Hi, unfortunately those type of raster effects like Venetial Blinds are not supported by the player.
And the pineapple has an inverted mask which in that particular scenario, because of scaling of the comp, doesn't work right.
