### ISSUE TITLE
Lottie animation lags on iOS

### ISSUE THREAD

**Issue by dmoczydlowski** [airbnb/lottie-web#1422]
** Where it happens?
- Ionic app with lottie 
- Only on iOS app deployed on device

** What did you do? Please explain the steps you took before you encountered the problem.**
- When animation is played, the app starting to have a lot of lags. When I'm testing on android device or web preview it's working fine..

** Link to download aep file
- https://drive.google.com/file/d/16-wkz1dZtK2lT-fsozvIRijdKuOgElQq/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, can you try using the latest player (v5.4.3) with the canvas renderer?
