### ISSUE TITLE
Trim Paths & Generated Stroke Masking Issues

### ISSUE THREAD

**Issue by waltercoots** [airbnb/lottie-web#1423]
I'm using macOS 10.14.2 (18C54)

* **Browser and Browser Version:**
Tested in Safari, Chrome, and Firefox. 

* **After Effects Version:**
Adobe After Effects 16.0.0 (build 235)

**What did you do? Please explain the steps you took before you encountered the problem.**
I'm creating a simple logo mark animation involving a masking effect. I've tried to achieve the effect two ways: one, using the Generate > Stroke effect on a mask path, and two, by creating a separate layer using an alpha track matte. 

**What did you expect to happen?**
I expected the unmasking animation to work, and appear as it did in After Effects.

**What actually happened? Please include as much _relevant_ detail as possible.**
The animation works with the exception of the unmasking effect. Oddly, if I take an SVG snapshot in Bodymovin's preview and open it with Adobe Illustrator, it appears as I'd expect it to. 

**Please provide a download link to the After Effects file that demonstrates the problem.**
[EverlyWell Logo Mark Animation.zip](https://github.com/airbnb/lottie-web/files/2681880/EverlyWell.Logo.Mark.Animation.zip)

**Comment by waltercoots** [comment]
Thank you! 

That layer mask is actually just an open vector shape which tells After Effects where to draw the stroke, so it doesn't need to be closed. But for the purpose of getting this to work, I closed it in a way that the stroke would overlap an already drawn area, which worked out. 

It would be nice if Lottie and Bodymovin would allow open paths for effects like this.

**Comment by bodymovin** [comment]
yes, it's a bug that I need to look into.

**Comment by bodymovin** [comment]
This should be fixed. Reopen if necessary.
