### ISSUE TITLE
Bodymovin render not .json but somehow .logo file.

### ISSUE THREAD

**Issue by xazisanamijator** [airbnb/lottie-web#1424]
* **After Effects Version:**
AE CC 2017

**What did you do? Please explain the steps you took before you encountered the problem.**
Hey, im using Bodymovin to export .json file. But it exports to me not .json but somehow .logo i dont know whats going on here. how to fix it. Take a look at my project.

**Please provide a download link to the After Effects file that demonstrates the problem.**

[logo.zip](https://github.com/airbnb/lottie-web/files/2687091/logo.zip)

**Comment by bodymovin** [comment]
Hi, I tried exporting the animation and it seems to work fine.
Can you try closing the extension and opening it again?
