### ISSUE TITLE
Custom font issue

### ISSUE THREAD

**Issue by hayhamLT** [airbnb/lottie-web#1426]
https://www.dropbox.com/s/njxsgrf2ao2y39b/Screen%20Shot%202018-12-17%20at%2010.53.37%20PM.png?dl=0

I create html banner and use custom font "Soleil" which is a web font, and I have a link Typekits CSS,

but when i fill it like I show in screenshot, I have got a white screen , can you help me with this?

**Comment by bodymovin** [comment]
Adobe has changed the way Typekit fonts work.
I'll try to have a fox for this soon.
