### ISSUE TITLE
Can't export correct animation with stroke dash and gap

### ISSUE THREAD

**Issue by jixuansun** [airbnb/lottie-web#1427]
**Tell us about your environment**
* **Browser and Browser Version:**
Xcode Version 10.1
* **After Effects Version:**
After Effects CC Version 16.0.1
**What did you do? Please explain the steps you took before you encountered the problem.**
I'm trying to export one composition contains three shape layers, all of them are stroke line. Two stroke is using Dash and Gap to animate, one is using Trim Path.
**What did you expect to happen?**
Export exactly animation in Preview window
**What actually happened? Please include as much _relevant_ detail as possible.**
I test the JSON file exported from the Lottie in Xcode, the animation moves super fast (around 2.5*)with one layer disappear, only two stroke is animated and the whole animation seems stop half way.
**Please provide a download link to the After Effects file that demonstrates the problem.**
[RingAnimation.aep.zip](https://github.com/airbnb/lottie-web/files/2699717/RingAnimation.aep.zip)

**Comment by bodymovin** [comment]
I'm checking the animation and it seems to work fine.
Can you share a link with the implementation?
