### ISSUE TITLE
Trail glitch in firefox when scrolling

### ISSUE THREAD

**Issue by willdelphia** [airbnb/lottie-web#1428]
**Tell us about your environment**
Mac 10.14 Mojave 

* **Browser and Browser Version:**
Firefox 64.0 (64-bit)

* **After Effects Version:**
After Effects 16.0.0

**What did you do? Please explain the steps you took before you encountered the problem.**

I have a bodymovin json file exported from simple scene where a line is revealed using trim paths and circle moves along the same path. 

I am using Scrollmagic to scrub through a lottie scene using the following code:
```
homelineLottie =lottie.loadAnimation({
    container: animbg,
    renderer: 'svg',
    loop: false,
    autoplay: false,
    path: av_data.themeUrl + '/images/homeline.json'
    });

var homeController = new ScrollMagic.Controller();
var homelineScene = new ScrollMagic.Scene({triggerElement: animbg, duration: 3160})
.addTo(homeController)
.on("progress", function (e) {
    var duration = homelineLottie.getDuration(true);
    var newTime = (duration * e.progress).toFixed(2);
    homelineLottie.goToAndStop(newTime, true);
});
```

**What did you expect to happen?**

I expect that my scene plays forward as I scroll down the page and reverses as I scroll up the page. 

**What actually happened? Please include as much _relevant_ detail as possible.**

Everything works in Chrome and Safari. However in firefox I get a glitch where the circle element leaves behind trails of itself as I scroll up. Here's a video of that happening:

https://www.youtube.com/watch?v=NFXpLtQFJPQ

I thought that perhaps it was being caused by some interaction with another layer or element of my page, but I was able to reproduce the error in a barer context, on codesandbox (https://codesandbox.io/s/4rwr8l7lp7)  as seen in this video:

https://www.youtube.com/watch?v=8YUiD7zP90Y

**Please provide a download link to the After Effects file that demonstrates the problem.**

https://drive.google.com/open?id=1e9i0yhN5yeIyzKhZdpU4Uk-Y1fbAcDBf

**Comment by willdelphia** [comment]
It's worth mentioning that if I switch renderer to `canvas` the trail effect disappears, but the motion is much more jolty, jumpy.

**Comment by bodymovin** [comment]
I can't reproduce the issue in Firefox, but because of the type of glitch, my guess is that it's related to the graphics card not being able to refresh fast enough.
Since the exported animation size is 1060x3160, it is a pretty large texture to upload to the GPU on each tick.
If you open the console or inspect the element does it get fixed?

**Comment by willdelphia** [comment]
The next day the error stopped. Seemingly on its own. I don’t think I did anything to fix it.
