### ISSUE TITLE
How to use Typekit  to export custom font

### ISSUE THREAD

**Issue by hayhamLT** [airbnb/lottie-web#1429]
I want to use "Soleil" font, witch exists in Adobe fonts, but when I export the project, in browser i've got blank page, please help me understand where I get wrong
<img width="741" alt="screen shot 2018-12-20 at 4 11 23 pm" src="https://user-images.githubusercontent.com/36948756/50317797-575ce780-0472-11e9-998f-ec972b7037ef.png">
<img width="1185" alt="screen shot 2018-12-20 at 4 10 39 pm" src="https://user-images.githubusercontent.com/36948756/50317798-575ce780-0472-11e9-886e-b34b63db6e6c.png">

**Comment by bodymovin** [comment]
Adobe has changed the way Typekit fonts are loaded.
I'll try to have a fix for this this week.

**Comment by hayhamLT** [comment]
Thank you so much, Is there any other way to have a custom font in a
project using bodymovin?

**Comment by hayhamLT** [comment]
Thank you very much

**Comment by hayhamLT** [comment]
Thanks for update, I tried to use it, but it still doesn't work, or I do something wrong? I attached screenshots

<img width="859" alt="screen shot 2019-01-02 at 10 44 50 am" src="https://user-images.githubusercontent.com/36948756/50606787-c75c6c00-0e7b-11e9-996e-09aced1db1e5.png">
<img width="607" alt="screen shot 2019-01-02 at 10 44 36 am" src="https://user-images.githubusercontent.com/36948756/50606788-c75c6c00-0e7b-11e9-932c-877edceabbc6.png">

**Comment by bodymovin** [comment]
just add the font path (https://url) in the Font Path field

**Comment by hayhamLT** [comment]
> just add the font path (https://url) in the Font Path field

The same result(
<img width="862" alt="screen shot 2019-01-02 at 10 55 36 am" src="https://user-images.githubusercontent.com/36948756/50607112-f9ba9900-0e7c-11e9-8cf4-a3799e17a05a.png">

**Comment by hayhamLT** [comment]
WORKS! Thank you
