### ISSUE TITLE
playSegments flag false don't work

### ISSUE THREAD

**Issue by vinera** [airbnb/lottie-web#1432]
Hello!
I use playSegment with flag false, but segment change immediately.

**Comment by bodymovin** [comment]
Hi, can you share a link with the implementation?

**Comment by vinera** [comment]
example code:
  anim.addEventListener('DOMLoaded', function () {

    anim.playSegments([[0, 55]], false);

    $(window).bind('mousewheel', function (event) { 
      if (event.originalEvent.wheelDelta >= 0) {
        if ( scrollTop <= sectionFirstTop) {
          if (!animBox.classList.contains('start')) {
            anim.playSegments([[83, 56], [1, 55]], false);
            animBox.classList.add('start');
            animBox.classList.remove('end');
          }
        }
      }
      else {
        if ( scrollTop >= sectionSecondTop) {
          if (!animBox.classList.contains('end')) {            
            anim.playSegments([[56, 83], [84, 122]], false);
            animBox.classList.add('end');
            animBox.classList.remove('start');
          }
        }
      }
    });

  });

**Comment by bodymovin** [comment]
@vinera can you share a working link with the full implementation?
Not sure how you're getting some of the values in your example
