### ISSUE TITLE
Lag at first loading

### ISSUE THREAD

**Issue by katalea02** [airbnb/lottie-web#1433]
**Tell us about your environment**
MacOS Mojave 10.14.2

**Browser and Browser Version:**
Safari / Chrome

* **After Effects Version:**
After Effects CC 2019 

**What did you do? Please explain the steps you took before you encountered the problem.**
My teammate has created an animation and he exported it by using the Bodymovin plugin with the Demo setting to generate an html file.

**What did you expect to happen?**
Animation to play smoothly.
The animation has some lag at the begging of the loading, once it loads then it goes on smoothly. This is a problem that appears both on Safari and Chrome. We tried minimizing the number of layers and some other little shapes, but nothing changed. 

**Please provide a download link to the After Effects file that demonstrates the problem.**
[Problem.zip](https://github.com/airbnb/lottie-web/files/2710539/Problem.zip)

**Comment by bodymovin** [comment]
Hi, I see the animation is using around 40 images.
I guess the problem is related to the time it takes to load all of them.
Can you convert all or some of them to shapes instead of using them as rasterized images?
