### ISSUE TITLE
Lottie is not defined.

### ISSUE THREAD

**Issue by OsamaAlnory** [airbnb/lottie-web#1434]
I have downloaded and put lottie.json file inside my project folder. I then added these lines of code:
`        <script src="../js/lottie/lottie.json"></script>

        <script>
            try {
                lottie.loadAnimation({
                    container: document.getElementById('eee'), renderer: 'svg',
                    loop: true,
                    autoplay: true,
                    path: '../check.json'
                });
            } catch (e) {
                alert(e);
            }
        </script>`
Whenever i run this code, it shows 'lottie is not defined'. Am i missing something or doing something wrong. I have used lottiefiles without any problem in xamarin.forms, but this is the first time i use it on my/my friend's website.
I also tried running "loadAnimation" without the "lottie".
Note that "eee" is the name of a div that i created.

* **Browser and Browser Version:**
Google Chrome
* **After Effects Version:**

**What did you expect to happen?**
The animated image (json file) would display.

**What actually happened? Please include as much _relevant_ detail as possible.**
Nothing was shown.

**Comment by bodymovin** [comment]
it's lottie.js, not lottie.json.
Could that be the problem?

**Comment by OsamaAlnory** [comment]
Oh my!
I just noticed that. Thanks! It's working now.
