### ISSUE TITLE
Gradient cannot be exported correctly.Follow-up issues on this issue.

### ISSUE THREAD

**Issue by hhzx** [airbnb/lottie-web#1436]
If your system or your AE language version is not in English, you may encounter situations where gradients do not work.In this answer ↓, the solution is given. That's to change the Unicode settings in your system.

https://github.com/airbnb/lottie-web/issues/1201

Is there any way to output normally without modifying Unicode, because changing Unicode will have many unexpected chain reactions, modifying Unicode will cause a lot of software chaos, which will cause great inconvenience.

I sincerely hope to solve this problem, thank you!

**Comment by Danjuanlab** [comment]
Hello  hhzx, 
As far as I know, it may take a long time to fix this BUG. If you are a programmer, you will know that when the program is finished, the method of adapting the code will involve a lot of code issue. 

As you said, the change of Unicode will make a lot of other programs scrambling. To solve these two problems, you can manually modify the gradient information in the JSON file.

**Comment by BBxufo** [comment]
2021求后续解决办法
