### ISSUE TITLE
JSON file not play while html file work fine exported by Bodymovin

### ISSUE THREAD

**Issue by vishnu2711991** [airbnb/lottie-web#1437]

**Comment by vishnu2711991** [comment]
I have created a simple animation with teh help of After Effect and export it into .json and .html.
The problem is .jason file not working while .html file works fine on browser.

Help to to sort out this problem.

**Comment by bodymovin** [comment]
The animation seems to work fine.
Can you share a link with the implementation that doesn't work?

**Comment by vishnu2711991** [comment]
> The animation seems to work fine.
> Can you share a link with the implementation that doesn't work?

Actually, the  .json file is to be used in ios app, currently it is under development.

Is there any way to check .json file is working fine or not apart from lottie preview?

**Comment by bodymovin** [comment]
Here is a list for supported features for each library:
https://airbnb.io/lottie/supported-features.html
I think you are using expressions and that's why it doesn't work on ios.

**Comment by vishnu2711991** [comment]
> Here is a list for supported features for each library:
> https://airbnb.io/lottie/supported-features.html
> I think you are using expressions and that's why it doesn't work on ios.


I used a png image and rotate it simple. Have you checked that Aep file, I already submit for review to you on above comment?
Please check once and let me know that - is there any mistake done by my side.

Thank you for supporting and help me on this.

**Comment by bodymovin** [comment]
I have
check the rotation property
it has an expression: `time*100`

**Comment by vishnu2711991** [comment]
Well noticed. Am not aware on this.
Thanks
