### ISSUE TITLE
Différence de position entre la preview dans afx et celle de bodymovin

### ISSUE THREAD

**Issue by Xationch** [airbnb/lottie-web#1439]
macOS Mojave
AFX cc 2018
DUIK 16.0.11
Bodymovin 5.4.3

Hello,

Quand j'exporte l'animation avec bodymovin, le résultat est légèrement différent de la preview dans after effects. J'ai essayer plusieurs rig différent et j'arrive toujours au même résultat. Est-ce que je fais quelque chose de faux?

<img width="896" alt="capture d ecran 2019-01-02 a 16 57 35" src="https://user-images.githubusercontent.com/24409229/50599967-e7a61e00-0eaf-11e9-8e1e-6dd5dc6e1c90.png">
<img width="896" alt="capture d ecran 2019-01-02 a 16 55 50" src="https://user-images.githubusercontent.com/24409229/50599968-e7a61e00-0eaf-11e9-96dc-5ca6915fa282.png">

Je t'ai envoyé un mail avec le fichier afx.

**Comment by Xationch** [comment]
J'ai essayé d'importer l'animation dans mon app Vue.js et la position est juste. Donc je ne sais pas pourquoi il y a une différence dans la preview sur bodymovin dans afx. Cependant les dégradées de la tête sont faux comme dans la preview sur bodymovin. C'est à dire jaune au lieu d'être couleur chair. Une idée?

**Comment by bodymovin** [comment]
J'ai un mauvais francais, mais je vais essayer: 
pour les dégradées, l'exportation a parfois des problèmes si les couches ont les mêmes noms. Peux-tu essayer de changer le nom de la couche qui ne s'exporte bien?
Aussi, sauve le projet avant d'exporter.

**Comment by Xationch** [comment]
Sorry, I thought you were French because I saw you speak French so well in different issue :)

I've already all the layer with a different name. But not the name of the gradient. When I create a gradient the default name is Gradient Fill 1. You're correct, it's the same name has the yellow gradient. If I change the gradient name it's working well.

Thank you for your help and this amazing plugin.
