### ISSUE TITLE
Does not export the right colors by the bodymovin in the gradient

### ISSUE THREAD

**Issue by manchasan** [airbnb/lottie-web#1440]
USING:

Windows 10
Adobe After Effects CC 2019
Bodymovin 5.4.2

I'm having some problems with gradients.

I have an illustration in ".AI" when I import into After Effects and I create vector layers they stay in solid gray fill and lose the gradient, so I recreate the gradients by going to "Add> Gradient Fill" I select the right colors, I do the animation, when I export through the bodymovin the gradient turns black and white or it generates a totally random color, the worst I do not understand is that some the gradient works and another does not.

I have already switched the unicode language from the system to English (USA), the language of the software is in English as well.

![image](https://user-images.githubusercontent.com/46319224/50604504-554d4c80-0ea6-11e9-84e5-fa9c20a0ff4b.png)

Example 01:
     • On After Effects:

![sem titulo-1](https://user-images.githubusercontent.com/46319224/50603964-904e8080-0ea4-11e9-8883-e372ad338ad3.png)

     • Exported (Demo web):

![sem titulo-2](https://user-images.githubusercontent.com/46319224/50604144-24b8e300-0ea5-11e9-83ab-d8be8925c701.png)

     • Exported (Preview Lottie):

![snapshot](https://user-images.githubusercontent.com/46319224/50604227-5f228000-0ea5-11e9-9607-36b1822ee1e7.png)

- - - - - - - - - - - - - - - - - - - - - - - - - - - -

Exemple 02:

     • On After Effects:

![sem titulo-1](https://user-images.githubusercontent.com/46319224/50604879-92660e80-0ea7-11e9-8aef-9317c7e67fc5.png)

     • Exported (Demo web):

![sem titulo-2](https://user-images.githubusercontent.com/46319224/50604893-9db93a00-0ea7-11e9-8191-95c875b5207c.png)

@bodymovin  Please Help me guys.

**Comment by bodymovin** [comment]
There's usually two reasons why it won't find the correct gradient color:
First, if layers or gradient properties have the same name, it might find an incorrect value.
Second, make sure the project is saved before exporting.

If it still fails, can you share the .aep?

**Comment by manchasan** [comment]
Here the zip with .aep and .ai

[Archive.zip](https://github.com/airbnb/lottie-web/files/2723423/Archive.zip)

**Comment by bodymovin** [comment]
Try changing the names of gradient properties that don't work.
For example in layer CABEÇA HOMEM > Contents > Grupo 1
I changed "Preenchimento de gradiente 1" to "Gradient 1" and it got fixed.

**Comment by manchasan** [comment]
I've change the names take a look

![image](https://user-images.githubusercontent.com/46319224/50636223-72345f00-0f3c-11e9-89e8-7a2d71c35ae7.png)

Some change but other take a random color, the skin and hair of the man fixed but de sunset doesn't :(

![image](https://user-images.githubusercontent.com/46319224/50636259-91cb8780-0f3c-11e9-8c30-67d97610ab46.png)

**Comment by manchasan** [comment]
I solve my problem importing the .ai again now with my after effects in english, when I begin in the project my after was in Portuguese :)

Thanks

**Comment by ppcD-er** [comment]
> There's usually two reasons why it won't find the correct gradient color:
> First, if layers or gradient properties have the same name, it might find an incorrect value.
> Second, make sure the project is saved before exporting.
> 
> If it still fails, can you share the .aep?

hi I'm also facing this issue can help me pls!

**Comment by bodymovin** [comment]
@ppcD-er hi, can you provide more info?

**Comment by ppcD-er** [comment]
> @ppcD-er hi, can you provide more info?

hi, Thanks for responding, I found out the reason already :) My Gradient was having an issue because there was a clash in my assets folder when I imported the ai files from a few files. After deleting all the ai files, the gradient issues were resolved. Could be because of conflicts in similar file names.

thxs again for responding

**Comment by samdiener** [comment]
There is a feature in the Lottiefiles Preview Window (German):
<img width="186" alt="Bildschirmfoto 2020-03-31 um 18 24 55" src="https://user-images.githubusercontent.com/10726410/78051628-40e45200-737e-11ea-9871-9e1c794849ed.png">

There you are able to change the gradients of single objects:
<img width="842" alt="Bildschirmfoto 2020-03-31 um 18 27 30" src="https://user-images.githubusercontent.com/10726410/78051719-62ddd480-737e-11ea-9fbf-f04cb17ad173.png">

**Comment by d-korolkov** [comment]
The solution is to rename all gradients "Gradients Fill 1" into Gradient Fill_1, Gradient Fill_2,Gradient Fill_3.... AND ALSO what had closed all still remaining problems after that is to rename all sublayerd Groups from Group 1, Group 2, Group 3 where gradients are presented to Group_1, Group_2, Group_3. This closed my problems.

**Comment by pradipvaghasiya** [comment]
> The solution is to rename all gradients "Gradients Fill 1" into Gradient Fill_1, Gradient Fill_2,Gradient Fill_3.... AND ALSO what had closed all still remaining problems after that is to rename all sublayerd Groups from Group 1, Group 2, Group 3 where gradients are presented to Group_1, Group_2, Group_3. This closed my problems.

Thank you very much. This worked.

**Comment by googincheng** [comment]
> The solution is to rename all gradients "Gradients Fill 1" into Gradient Fill_1, Gradient Fill_2,Gradient Fill_3.... AND ALSO what had closed all still remaining problems after that is to rename all sublayerd Groups from Group 1, Group 2, Group 3 where gradients are presented to Group_1, Group_2, Group_3. This closed my problems.

Work for me. Thanks

**Comment by leighagius** [comment]
How do you rename gradients? are we just talking about renaming the layer?
I'm using gradient fills and gradient strokes, can someone please provide clarification?

**Comment by javierpose** [comment]
The solution is not to rename the gradients, but to rename the layers of the entire project, to give each layer a different name. Use AE Global renamer 2 to rename the layers of each precomposition as it can be seen in the screenshot:
in red: It is necessary to give a different name in each precomposition
green: it will add a different number to each layer

![Group](https://user-images.githubusercontent.com/210588/229353613-c977b6cf-c90e-4a09-b484-f6aea61e389f.png)

**Comment by whitehat102** [comment]
To anyone who is still having issues even with the solutions mentioned here. I fixed my gradient by just manually editing the SVG using Notepad with the help of ChatGPT. However I only tried it with linear gradients, I'm not sure if it works on other gradient types.

**Comment by d-korolkov** [comment]
> To anyone who is still having issues even with the solutions mentioned here. I fixed my gradient by just manually editing the SVG using Notepad with the help of ChatGPT. However I only tried it with linear gradients, I'm not sure if it works on other gradient types.

SVG? Do you really export animated SVG from AE ?
