### ISSUE TITLE
HTML file after Bodymovin has incorrect animation.

### ISSUE THREAD

**Issue by anybodyhelpmeplz** [airbnb/lottie-web#1442]
**Tell us about your environment**

* **Browser and Browser Version:**
Google Chrome 71.0.3578.98
* **After Effects Version:**
After Effects 16.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**
I've make a simple animation which works wrong in HTML file after bodymovin using

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**
I add two screenshots how it looks in AE and in Browser. Pretty sure it's enough.
http://prntscr.com/m2hctb
http://prntscr.com/m2hd8l

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/9jz2yr7occx5fxn/Logo%202%20red%20parts.rar?dl=0   - AE project

**Comment by bodymovin** [comment]
Hi, on your composition "Top_part", there is a layer "BG_only.ai" that has an alpha mask "Lm_Symbol-Color Outlines 2"  which in turn has another alpha mask "Line_02".
That doesn't work in AE and lottie doesn't know how to interpret it.
If hou remove the alpha mask mode from "Lm_Symbol-Color Outlines 2", it should work fine.

**Comment by anybodyhelpmeplz** [comment]
Huge respect you, buddy!

I've follow your advece and it works!
