### ISSUE TITLE
Artifacts left during animation. 

### ISSUE THREAD

**Issue by cecherry1** [airbnb/lottie-web#1444]
Hi! We are really enjoying diving into bodymovin/Lottie. We have however come across an issue when running our animations linked to scroll and wondered if you could help. 

Only on Safari. 
Artifacts left after motion.

We are sure this isn’t specifically a bodymovin issue but hoped you might see something we are missing. 

https://www.zuora.com/industries/internet-of-things/

Thank You!

**Comment by bodymovin** [comment]
Hi, indeed Safari has some artifacts when dealing with svgs.
Have you tried the canvas renderer instead of the svg?
it seems your animation works fine with both.

**Comment by cecherry1** [comment]
That worked perfectly. Thanks so much for helping us out!
