### ISSUE TITLE
CSS parameters

### ISSUE THREAD

**Issue by foguetes** [airbnb/lottie-web#1445]
I exported a comp where each element has a separate CSS ID.

When I tried to style these elements I noticed only certain parameters like `display:none!important` were working, but whe I try to change `width:50%`, for example, it doesn't work. Is there any documentation relating to which parameters work and which ones don't?

Also, what's the best way to make a comp responsive, where each element scales independently.

**Comment by bodymovin** [comment]
Hi you probably want to look into svg element's properties and styles they support.
width and height don't work on svgs for example.
Regarding making comps responsive, I don't think lottie is the right tool for that, but you can play around with the 'html' renderer and see if it fits your needs.
