### ISSUE TITLE
Pixelation occurring when the composition is scaled

### ISSUE THREAD

**Issue by DYNSTy** [airbnb/lottie-web#1446]
**Tell us about your environment**
Working on the latest version of Adobe After Effects on mac as well as windows.

I needed to export a separate version of my composition for retina and bigger screens at 2x scale. The 1x render was perfect  and I used the after effects script to scale the required compositions at 2x (continuously rasterise was on across every layer). The bodymovin export of the scaled composition is highly pixelated. 

Would welcome advice on how to ensure smooth multiple scale exports

AE file link: https://adobe.ly/2sbWWW2

**Comment by bodymovin** [comment]
Hi, I can't download that file.
Can you share it in a different way?

**Comment by bodymovin** [comment]
Hi, a couple of questions:
- what composition are you referring to?
- are you using rasterized assets? If not, you shouldn't need to export different sizes because everything is vectors.
If you are using .ai layers, make sure to convert them to shapes in AE so they don't get exported as pngs.
