### ISSUE TITLE
sourceRectAtTime().width can not working in the web

### ISSUE THREAD

**Issue by Danjuanlab** [airbnb/lottie-web#1449]
Recently I was trying to dynamically adjust the scale of the image. In AE2018, the result of the calculation is accurate. But when exporting the animation, I found the image to be enlarged. I use the expression below to calculate the scale.

> OW=thisLayer.sourceRectAtTime().width;
> TW=60;
> R=TW/OW*100;
> [R,R];

![p2](https://user-images.githubusercontent.com/42509669/50817256-347d6f00-135e-11e9-8aa3-36130f600241.png)
![p1](https://user-images.githubusercontent.com/42509669/50817258-36473280-135e-11e9-96c8-54cd17eb0a7c.png)

In the demo page, comparing the two matrices can be seen that the scaling value of the one is 0.6X and the other one is 0.5. This should be a BUG when render.

[follower.zip](https://github.com/airbnb/lottie-web/files/2735654/follower.zip)

**Comment by Danjuanlab** [comment]
![223](https://user-images.githubusercontent.com/42509669/51068113-84a54b80-1654-11e9-8539-8d1b524a47cb.png)
![33](https://user-images.githubusercontent.com/42509669/51068114-85d67880-1654-11e9-92fa-a8e00fc6567e.png)
Today, I tried to compare the results of each part of the expression. I found that the function sourceRectAtTime (). width was correctly calculated in AE, but it was wrong when it was rendered on the web. When it was displayed on the web, the value was 100, which led to the calculation error of the scale value of the whole graph.

So I wanted to know if it was scaled for some reason, and then I did the following test. The test found that the value of this function in WEB is constant to 100. This function can't work correctly in web. Please see what it is.
![13](https://user-images.githubusercontent.com/42509669/51068320-67be4780-1657-11e9-8fe9-b29c6b6f6e1d.png)
![32](https://user-images.githubusercontent.com/42509669/51068321-68ef7480-1657-11e9-81b5-b67ae09b70b3.png)
@bodymovin

**Comment by bodymovin** [comment]
supporting sourceRectAtTime is not simple because I needs to render the layer to get the actual size.
But apparently from my quick tests, images `sourceRectAtTime` only need the width and height of the layer so I did a fix only for this type of layers.
If you test it, let me know how it goes.
