### ISSUE TITLE
Define a set number of loops?

### ISSUE THREAD

**Issue by NoLooseEnds** [airbnb/lottie-web#1450]
Hi,

I'm new to lottie/bodymovin and not very fluent in JS. So I would love to get a bit of help getting my animation to run twice (or loop once if you like) – or preferably a way to define a set amount of loops.

Javascript:
```
var animation = bodymovin.loadAnimation({
    container: document.getElementById('animation-test'),
    renderer: 'svg',
    loop: false,
    autoplay: true,
    path: 'data.json'
})
```

This works as expected, and it runs once. 

Is there a way to define a set amount of loops?

Thank you!

**Comment by bodymovin** [comment]
you can pass a number to the loop param instead of `false`.

**Comment by NoLooseEnds** [comment]
Thank you for the answer! 

Is it possible to show a code example?

**Comment by bodymovin** [comment]
```js
var animation = bodymovin.loadAnimation({
    container: document.getElementById('animation-test'),
    renderer: 'svg',
    loop: 4,
    autoplay: true,
    path: 'data.json'
})
```

**Comment by NoLooseEnds** [comment]
Thank you. Can't believe it was that easy, I was looking at all sorts of complicated solutions.

Much appreciated.

**Comment by JanSzidat** [comment]
This only works the first time I play my animation. If I goToAndPlay(0) after that it only plays once, even if I set anim.loop = 2 before playing again.

**Comment by markcor11** [comment]
Updated the thinking.json with additional spins  between each exchange which is working correctly TODO is to make the animation only play once. 


```
 "markers": [
    {
      "tm": 0,
      "cm": "spin_r",
      "dr": 50
    },
    {
      "tm": 60,
      "cm": "exchange",
      "dr": 50
    },
    {
      "tm": 0,
      "cm": "spin_r",
      "dr": 50
    },
    {
      "tm": 120,
      "cm": "exchange2",
      "dr": 50
    },
    {
      "tm": 0,
      "cm": "spin_r",
      "dr": 50
    },
    {
      "tm": 180,
      "cm": "exchange 3",
      "dr": 50
    }
  ]
```

**Comment by cheestudio** [comment]
@bodymovin 4 years later and this advice still works. Amazing how the docs list the "loop" property as a simple boolean in the React docs, yet passing an integer worked perfectly!

https://docs.lottiefiles.com/lottie-player/components/lottie-react/properties

**Comment by reatlat** [comment]
new link here https://developers.lottiefiles.com/docs/dotlottie-player/dotlottie-web/properties/
