### ISSUE TITLE
After Effects 3d Camera

### ISSUE THREAD

**Issue by brenantacio** [airbnb/lottie-web#1451]
Hi i've used a 3d camera on my after effects, does it render also the 3d camera animation?

**Comment by bodymovin** [comment]
Hi, it only supports 3d cameras on the mail comp.

**Comment by alexkog10** [comment]
does lottie really support after effects 3d camera? I do have a camera on the main comp but it doesn't see any objects when previewing. If it turn the camera off it does work. Do you know what might be the issue?

**Comment by notthesame23** [comment]
Same issue here. Did you find a solution for this? Is it a newly introduced bug in lottie or did it simply never support 3d cameras?
