### ISSUE TITLE
Buggs in animation when previewing in Lottie. The lines do not smoothly animate as in the AE file.

### ISSUE THREAD

**Issue by vleezer** [airbnb/lottie-web#1452]
Dear Lottie team & Bodymovin team,

Today I've animated an Icon. It works well in mp4 version. You can view how it should look and how it looks in context here: https://we.tl/t-JC1jFDKArf

You can download the svg animation file here: https://we.tl/t-LLQKgwKhPo

Only I see that it bugs during the animation. Everything animates smoothly, only the dotted lines just suddenly appear. They don't animate in their lines as in the mp4. View the animation here: https://codepen.io/dragnipur/pen/QzWRPQ

I use google chrome and safari.
Aftereffects cc 15.0.1 is the one I use.

Thank you for your time and attention on this matter.
Looking forward to your response.
With kind regards,

Viviane Leezer

**Comment by Danjuanlab** [comment]
I just see it everything normal.The svg animation is render correctly.

**Comment by vleezer** [comment]
hmmm that's strange, the dotted lines still just pop up instead of animating smoothly like the mp4.

**Comment by vleezer** [comment]
I still see the error.

**Comment by vleezer** [comment]
Are you sure you checked the dotted line?

**Comment by bodymovin** [comment]
Can you share the .aep?

**Comment by vleezer** [comment]
Here is the AE file: https://we.tl/t-36yXsQKZ7K

Here is a video that highlights were it goes wrong and how it should be: https://we.tl/t-sFc0hvrZUY
There you see the error in the dotted lines.

**Comment by bodymovin** [comment]
The stroke effect is not fully supported. I suggest that you use trim path for this type of animation. It will work correctly and performance will be much better.
