### ISSUE TITLE
looping shape layers

### ISSUE THREAD

**Issue by Interacy** [airbnb/lottie-web#1453]
Using this expression for looping shape layers doesn't work properly in Lottie. The animation still loops but not in the same way it does in after effects.

`if (numKeys >1 && time > key(numKeys).time){
  t1 = key(1).time;
  t2 = key(numKeys).time;
  span = t2 - t1;
  delta = time - t2;
  t = delta%span;
  valueAtTime(t1 + t)
}else
  value`

**Comment by bodymovin** [comment]
can you send an .aep project with a reduced example?
