### ISSUE TITLE
3d camera error. - Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rabbitdan** [airbnb/lottie-web#1454]
**Environment**
Very simple implementation of lottie-web running on http-server locally on my macbook pro.

* **Browser and Browser Version:**
I am running the latest version of Google Chrome

* **After Effects Version:**
cc2019

**What did you do? Please explain the steps you took before you encountered the problem.**
Super simple lottie implementation running http-server locally. There is an SVG in the DOM but it's not visible and the console has the error below. 

**What did you expect to happen?**
I expected my json files to animate in the div with the class of background. There are quite a lot of 3d elements in the files and (I think they are in the file as exported) also some gradients etc. There are several files exported and all have the same issue with the 3d camera error detailed below.

**What actually happened? Please include as much _relevant_ detail as possible.**
The json files did not animate. The SVG has been loaded into the div and there is markup there in the DOM so it is getting a fair way through the process. However I have the following error:

`Uncaught TypeError: Cannot read property 'length' of undefined
    at HCompElement.HybridRenderer.getThreeDContainerByPos (lottie.js:6542)
    at HCompElement.HybridRenderer.appendElementInPos (lottie.js:6477)
    at HCompElement.SVGRenderer.buildItem (lottie.js:6012)
    at HCompElement.BaseRenderer.buildAllItems (lottie.js:5790)
    at HCompElement.ICompElement.initElement (lottie.js:8134)
    at new HCompElement (lottie.js:10306)
    at HybridRenderer.createComp (lottie.js:6528)
    at HybridRenderer.BaseRenderer.createItem (lottie.js:5768)
    at HybridRenderer.SVGRenderer.buildItem (lottie.js:6003)
    at HybridRenderer.BaseRenderer.buildAllItems (lottie.js:5790)`

**Please provide a download link to the After Effects file that demonstrates the problem.**
I don't have the ae file available unfortunately though I will ask tomorrow if that is possible. I am uploading one of the exported json files though in case that helps.

[part_1.json.zip](https://github.com/airbnb/lottie-web/files/2746583/part_1.json.zip)

Apart from that lottie is a great thing so thanks for the great work. We'd really love to get this working as the file size is so much smaller.

**Comment by rabbitdan** [comment]
Hi Hernan, 
apparently this is a stripped down version of one of the slides.
Thanks!
Dan

[Website_Breakdown.zip](https://github.com/airbnb/lottie-web/files/2749371/Website_Breakdown.zip)

**Comment by bodymovin** [comment]
@rabbitdan did you close the issue because you don't need this anymore?

**Comment by rabbitdan** [comment]
In case this helps, we tried exporting a version without the 3d camera earlier and that returned the same error.

**Comment by bodymovin** [comment]
Hi, there are several things that the project is using that are not supported by the player.
From a quick look I idenfitified the Inverted effect, Gradient Ramp, Glow effects.
And the error is triggering because it's using 3d and non 3d layers combined within a 3d precomp layer.
Unfortunately, not many raster effects are supported by the player.
And 3d has limited support as well.
