### ISSUE TITLE
Exported JSON contains image files despite all layers beind shape layers

### ISSUE THREAD

**Issue by julietennett** [airbnb/lottie-web#1455]
* **After Effects Version:**
CC version 16.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**
I created my illustration in Illustrator, imported the file into After Effects, converted each ai layer to a shape layer, and animated each layer. I then attempted to export a JSON file, which contains .img files not found and does not animate.

**What did you expect to happen?**
I expected a usable JSON file with no image files inside that animates 

**What actually happened? Please include as much _relevant_ detail as possible.**
The file exported with image files, and it doesn't render in the browser, and the preview image on the BodyMovin window doesn't show aniamtion happening

I tried troubleshooting:
✔️ All layers are shape layers
✔️ All unecessary additional paths/groups deleted from each shape layer
✔️ Same export results with or without expressions on the layers (and FWIF, the same expressions are used in another AE file that I exported successfully and animates correctly on web)
✔️ Duplicated the file to try exporting from a new file
But all of the above resulted in the same export results

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/drive/folders/1BAlzv0J-R6XOKZzX1alYF3lWI4b8IlZZ?usp=sharing

**Comment by Danjuanlab** [comment]
I can export your rocket animation correctly with your AE file. It doesn't contain any picture layers. I think your choice is wrong when you using bodymovin to export animation. You just need to export the comp you want. You don't need to export your original AI comp together.
