### ISSUE TITLE
Uncaught TypeError: Cannot read property 'layer' of undefined

### ISSUE THREAD

**Issue by skoota** [airbnb/lottie-web#1456]
**Tell us about your environment**

macOS Mojave 10.14.2

**Browser and Browser Version:**

Google Chrome 71.0.3578.98

**After Effects Version:**

After Effects 16.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**

I am a complete newbie to Bodymovin (along with Lottie) and want to export the **LOWER THIRD 2 + 1 lower BLUE** composition in the attached AE file (see below). However, upon exporting and either including the `data.json` in my own project, or ticking the option to have a demo file created, the following error appears in the console:

```
Uncaught TypeError: Cannot read property 'layer' of undefined
    at _expression_function (eval at initiateExpression (demo.html:1), <anonymous>:2:32)
    at n.executeExpression (demo.html:1)
    at n.u [as getValue] (demo.html:1)
    at GroupEffect.iterateDynamicProperties (demo.html:1)
    at SVGShapeElement.prepareProperties (demo.html:1)
    at SVGShapeElement.prepareFrame (demo.html:1)
    at SVGCompElement.ICompElement.prepareFrame (demo.html:1)
    at SVGRenderer.renderFrame (demo.html:1)
    at AnimationItem.renderFrame (demo.html:1)
    at AnimationItem.gotoFrame (demo.html:1)
```

I have read through similar issues from other users (e.g. external comps, etc.) but haven't been able to solve the problem with this project. Thanks in advance for any guidance!

**What did you expect to happen?**

The comp to export correctly and work in the `demo.html` file.

**What actually happened? Please include as much _relevant_ detail as possible.**

The above `Cannot read property 'layer' of undefined` error appeared in the browser console.

**Please provide a download link to the After Effects file that demonstrates the problem.**

https://drive.google.com/open?id=1nAOR86seVfCKqjghNYyq6Wgix_1VAYtR

**Comment by Danjuanlab** [comment]
Most of the time it is because AE files use expressions or plug-ins that are not currently [View the expressions and plug-ins that are supported by now](https://github.com/airbnb/lottie-web/wiki)

**Comment by skoota** [comment]
Thanks for your reply, but as far as I can tell (albeit being reasonably new to AE as well) there are no plugins or expressions being used for that composition which I am trying to export using Bodymovin.

**Comment by skoota** [comment]
Thanks for that, I understand now!

**Comment by bodymovin** [comment]
@skoota I requested access to the folder to take a look.
If the expression is targetting a composition that is not part of the comp tree, you can include it as a extra comp in the export settings.

**Comment by skoota** [comment]
Thanks for offering to take a look @bodymovin . Sorry about the file access, I accidentally unshared it - that's been fixed now so you should be able to download it.
