### ISSUE TITLE
Bodymovin creating a flicker within animation

### ISSUE THREAD

**Issue by TheOrangeFish** [airbnb/lottie-web#1463]
Heyo hoping for a bit of help,

I'm currently creating an animation for a slider on a website with lots of quickly moving shapes and outlines. The animation plays back fine in after effects and when rendered out as a video, but when demo'd in HTML it has lots of flickering almost ghosting?

I am also trying to implement this animation on a Wordpress site using the following plugin: https://wordpress.org/plugins/wp-bodymovin/

If the way to fix this is by editing the player, I'm assuming there would be a way to edit the player in the plugin also?

Here is a Wetransfer to the project files

https://we.tl/t-TZgSdPytZR

Thanks in advance!

**Comment by bodymovin** [comment]
try calling `anim.setSubframe(false);` after loading the animation
