### ISSUE TITLE
HELP! MY RENDER IS CROPPED

### ISSUE THREAD

**Issue by litoondev** [airbnb/lottie-web#1464]
Here is folder link : https://drive.google.com/drive/folders/1zW2O7mmOeIAg6UVywSr85tILowTYUWUc?usp=sharing

When i'm render in bodymovin I see it's cropped. Please help me to solve this 

![image](https://user-images.githubusercontent.com/11003869/51275051-0c93a880-19fb-11e9-9695-cee59601b808.png)

Thanks all

**Comment by bodymovin** [comment]
Browsers don't handle well filters and masks on strokes.
Can you replace the fill effect with changing the stroke color and see if it helps?

**Comment by litoondev** [comment]
Hello, 
are you open after effect file, I don't use masks on stocks

**Comment by bodymovin** [comment]
Yes, I did open the file.
You are using the fill effect which translates into svg filters.
If you inspect the console and check the svg, you'll see

**Comment by litoondev** [comment]
Can you please full detail, sorry I can't understand

**Comment by bodymovin** [comment]
I don't know how I can help.
Try removing the Fill Effect from After Effects.

**Comment by litoondev** [comment]
Hello, 
I already delete fill effect again render but the same result. if you don't mind can you please share your skype id please.

**Comment by bodymovin** [comment]
can you share the new project?

**Comment by litoondev** [comment]
Hello bro, 
Thanks bro,  without your help, I can't solve that. another question bro when I use the 3d layer that time facing the same problem. 

Thanks again bro
