### ISSUE TITLE
Export color error and html can't be displayed

### ISSUE THREAD

**Issue by wyfang** [airbnb/lottie-web#1465]
* Tell us about your environment
MacOS 10.14.2
* Browser and Browser Version:
Chrome  71.0.3578.98
* After Effects Version:
AE 16.0.0
* what have you done? Please explain the steps taken before you encounter a problem. 
I made a simple gradient rectangle, exported the json file, and tried to make the html.
* What do you expect to happen? 
The json file is displayed normally, and the html animation is displayed normally.
* What happened? Please include as much _relevant_ details as possible.
However, the gradient rectangle is displayed in black and white. Html cannot display any image at it.
* Please provide a download link to the After Effects file that demonstrates the problem.

###           [----------Download.zip----------](https://github.com/airbnb/lottie-web/files/2766958/test.zip)

![qq20190117-104814](https://user-images.githubusercontent.com/17900420/51292415-95373680-1a45-11e9-82d1-e7f9d7aae7cb.jpg)
![qq20190117-104901](https://user-images.githubusercontent.com/17900420/51292416-9700fa00-1a45-11e9-8e4b-b343e74278c3.jpg)

**Comment by bodymovin** [comment]
Hi, there is a problem with OS in some languages.
Perhaps this issue can help solving it
https://github.com/airbnb/lottie-web/issues/1201

**Comment by wyfang** [comment]
Then the web can't be displayed and what is going on?
