### ISSUE TITLE
JSON and HTML data does not play animation some animations don't work well

### ISSUE THREAD

**Issue by Alfinamn** [airbnb/lottie-web#1466]
Hi, I also have the same problem. I made an animation using duik. when I export to json, the whole body doesn't go well just the legs. what's the solution? Hope you can help. thank you
[TEST KARAKTER.zip](https://github.com/airbnb/lottie-web/files/2767179/TEST.KARAKTER.zip)

**Comment by bodymovin** [comment]
Hi, can you explain what do you mean with doesn't go well?

**Comment by Alfinamn** [comment]
Hello, I made an animation when people walked using duik, when I exported
json, the limbs could not walk properly, only the ankle could run well. how
is the solution that you provide, hopefully it can be useful for me, I hope
you help. thank you

Pada tanggal Kam, 17 Jan 2019 19.20 hernan <notifications@github.com
menulis:
