### ISSUE TITLE
Building a Dynamic Progress Loader with Lottie

### ISSUE THREAD

**Issue by Ronalses** [airbnb/lottie-web#1468]
Hello,  I have a problem to make animations be progressive.

I would like to do the same as they did in this [tutorial](https://github.com/airbnb/lottie-web/issues/1268)
But the methods are not the same.
I want to do it in lottie-web and this is for ios.

**Comment by bodymovin** [comment]
Hi, that example is lottie-web.
What is it exactly what you want to do?

**Comment by Ronalses** [comment]
I am sorry, i want to do this https://airbnb.io/lottie/ios/dynamic_properties.html

In lottie-web

**Comment by Ronalses** [comment]
I  want to make a progress bar that advances with respect to the percentage.

Example 10% 20% 30% ... 100%

**Comment by bodymovin** [comment]
you can use the lottie-api
https://github.com/bodymovin/lottie-api
it has a similar API that the ios one
and here is a working example that can help
https://codepen.io/airnan/pen/gvBMPV

**Comment by Ronalses** [comment]
Thank you very much for your help!
Happy day or night!
:+1:  :100:
