### ISSUE TITLE
Feature request: Add <title> and <desc> when SVG rendered

### ISSUE THREAD

**Issue by nrbacch** [airbnb/lottie-web#1469]
Hi!
Is there a way to the make the SVG that is rendered more accessible? I would like to be able to add a <title> and <desc> to the SVG. Is this something I can do in Render Settings (like the way I am able to add a class name)? 

Or is this something I have to do with separate javascript? Would it be somehting like this:
anim.addEventListener('DOMLoaded', function(){
  console.log('loaded');
  var $svg = document.querySelector('.svg-animation');
  $svg.prop('title', 'my title');
});

Thanks!

**Comment by DBjelovuk** [comment]
This is imperative for accessibility.

**Comment by bodymovin** [comment]
Hi I missed this issue.
I'll try to work on it.
I think it makes sense to add it as a new property for the animation config.

**Comment by DBjelovuk** [comment]
I've gotten away with just adding `role="img"` with an `aria-label` on the container element.

**Comment by nrbacch** [comment]
Thank you both!
