### ISSUE TITLE
Loader progress

### ISSUE THREAD

**Issue by manchasan** [airbnb/lottie-web#1471]
Hello peoples I need a help here @bodymovin

I'm a motion designer in the company I work for, I'm trying to make a progress loader for web, I've even assembled the animation that will loop. What I do not know is how to leave a progress bar that according to which page is loading it will be filled. I already tried to understand a page here of GitHub but I did not understand much that it was this one: https://github.com/bodymovin/lottie-api please help me

**Comment by bodymovin** [comment]
Sorry, I missed this message.
Reopen if necessary.
