### ISSUE TITLE
when display is none, offsetWidth and offsetHeight are 0 in CanvasRenderer.prototype.updateContainerSize

### ISSUE THREAD

**Issue by newbieYoung** [airbnb/lottie-web#1472]
Here is my optimization when set animation wrapper size.

var display = this.animationItem.wrapper.style.display;
if(display=='none'||display==''||!display){
    var style = window.getComputedStyle(this.animationItem.wrapper);
    elementWidth = parseFloat(style.getPropertyValue('width'));
    elementHeight = parseFloat(style.getPropertyValue('height'));
}else{
    elementWidth = this.animationItem.wrapper.offsetWidth;
    elementHeight = this.animationItem.wrapper.offsetHeight;
}

**Comment by newbieYoung** [comment]
If the **display** property of **container** element  is **none** and the **render** is **canvas**,then you will find the **width** property and the **height** property of canvas element are both **0**. 
The reason is that lottie use offsetWidth and offsetHeight to set size of animationItem.wrapper in CanvasRenderer.prototype.updateContainerSize.
But when display is none, offsetWidth and offsetHeight are 0.

**Comment by bodymovin** [comment]
ok now I understand.
Whenever the container size changes, if using the canvas renderer, it needs to have it's `resize()` method called manually.
Same thing can be used when switching the container from dosplay `none` to any other type of display.

**Comment by newbieYoung** [comment]
OK I understand it.
Thanks.
