### ISSUE TITLE
Update documentation to add example of using preserveAspectRatio with rendererSettings

### ISSUE THREAD

**Issue by patrick-wc** [airbnb/lottie-web#1477]
Hi,

I feel like a simple code snippet here - https://github.com/airbnb/lottie-web/wiki/Renderer-Settings would really help people starting to use Lottie on the web.

Something like:

```
var animation = bodymovin.loadAnimation({
  ...
  rendererSettings: {
  	preserveAspectRatio: 'xMidYMid meet'
  }
})
```

I believe `preserveAspectRatio: 'xMidYMid meet'` is the default example when I was shared a Lottie example by my designer, and it took me longer than it should have done to figure out how to get the svg responsive on the page.

**Comment by bodymovin** [comment]
Included. Thanks for the suggestion.
