### ISSUE TITLE
How do I avoid image folder with json export

### ISSUE THREAD

**Issue by Murradis** [airbnb/lottie-web#1478]
Hi, I'm a designer providing Json files for a client. I have had a complaint from the client that a folder filled with empty .png's called images/image_0.png, images/image_1.png etc. is called on in their project. I have deleted all raster files from the project and converted my animated layers to shape layers. I still can't seem to get rid of the folder on the client's side. What do i do ?

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by Murradis** [comment]
I’m afraid that I can’t it’s sensitive information. Is there any way to gage what the problem might be without looking at the ae files ?

Thank you so much, I don’t want to be difficult, it is just that the client information is confidential.

Any help or guidance would be appreciated.
Best wishes.

On 25 Jan 2019, at 13.44, hernan <notifications@github.com<mailto:notifications@github.com>> wrote:


hi, can you share the .aep?

**Comment by bodymovin** [comment]
Can you share a similar example reduced as much as possible so it doesn't have sensitive information?
