### ISSUE TITLE
Stop animation after one loop and display the last frame

### ISSUE THREAD

**Issue by ofirrifo** [airbnb/lottie-web#1479]
I want to stop animation after one loop and display the last frame
here is a [StackBlitz example](https://stackblitz.com/edit/lottie-cnbcp6?file=app%2Fapp.component.ts)

I'm using the [ng-lottie](https://github.com/chenqingspring/ng-lottie) npm package

**Tell us about your environment**
I'm using macOS
* **Browser and Browser Version:**
latest chrome browser

**What did you do? Please explain the steps you took before you encountered the problem.**
I just want to display 1 loop and after that to display the last frame

**What did you expect to happen?**
after 1 loop and after that to display the last frame like 
I read from this [issue](https://github.com/airbnb/lottie-web/issues/1217) 

**What actually happened? Please include as much _relevant_ detail as possible.**
after one loop the last frame disappear

**Comment by ofirrifo** [comment]
the .aep file is the source file ?
with this file, you can check if the last frame exist?

**Comment by bodymovin** [comment]
Hi, I tried that animation and it doesn't dissapear in the last frame.

**Comment by ofirrifo** [comment]
but the [example](https://stackblitz.com/edit/lottie-cnbcp6?file=app%2Fapp.component.ts):
is disappear after one loop

**Comment by bodymovin** [comment]
I can't find the version of lottie, but it seems it's using an old version of the player.
Can you try updating it to a newer one?

**Comment by ofirrifo** [comment]
it use the "lottie-web": "^5.1.3"

I'm using a wrapper calling [ng-lottie](https://www.npmjs.com/package/ng-lottie)
since I'm using Angular
which use the "lottie-web": "^5.1.3"

is the json I have has the last frame as a visible frame?

**Comment by ofirrifo** [comment]
I try the 5.4.3 without the 3pt I'm using and yes it work as should.
[example work](https://codepen.io/ofirrifo/project/editor/AORJbG)

I will check with the 3pt ng-lottie if they can update the version to "lottie-web": "^5.1.3".

thanks for your help
