### ISSUE TITLE
problem with duik

### ISSUE THREAD

**Issue by mostafafallahi** [airbnb/lottie-web#1481]
i have a simple animation with duik . when  i preview it the hand is not moving .  why ?

**Comment by mostafafallahi** [comment]
[Untitled Project.zip](https://github.com/airbnb/lottie-web/files/2804452/Untitled.Project.zip)

**Comment by bodymovin** [comment]
Hi, unfortunately Puppet effect is not supported by the player

**Comment by mostafafallahi** [comment]
how can i make svg animation with duik ?

**Comment by bodymovin** [comment]
duik is supported, but puppet effect is not
