### ISSUE TITLE
Merging multiple JSON files into one JSON file

### ISSUE THREAD

**Issue by alok-aks50** [airbnb/lottie-web#1484]
* **Browser and Browser Version: Chrome and IE**
* **After Effects Version: CC 2018**
I have created 8 different motion graphics clips in After Effects and exported as JSON. Unfortunately, I have lost the AE files and no possible way to get it back. 
Now I got a new requirement to merge all those 8 different animations into a single JSON file. and all I have is those 8 JSON files.
*My Requirements: Needs only one JSON file which contains all 8 animations. 
Please, someone, guide me how can I do this. if there is a possible way or not, If not I should create those animations from scratch in AE again.
Thanks!

**Comment by bodymovin** [comment]
Hi, unfortunately there is no easy way to do this and would require a lot of manual work.
If you need to overlap them or set them sequentially why don't you do it via code?

**Comment by alok-aks50** [comment]
Hi. thanks for your response. I guess I need to re-create all animations again in AE. Can you Please tell me if I can convert JSON into video for reference?

**Comment by bodymovin** [comment]
you can screen record your browser to use as a reference

**Comment by knowBalpreet** [comment]
> Hi, unfortunately there is no easy way to do this and would require a lot of manual work.
> If you need to overlap them or set them sequentially why don't you do it via code?

Hi @bodymovin , How to do this kind of thing via code?

**Comment by bodymovin** [comment]
@knowBalpreet what exactly do you need?

**Comment by MB00design** [comment]
Hi . I created animated character in after effects (11/sec) .and exported to json with bodymovin . But my json file is too heavy for my work ( 4 MG) . Why that happend and how can I fix it????
Please help me....

**Comment by MB00design** [comment]
@bodymovin  please answer my q..

**Comment by knowBalpreet** [comment]
@bodymovin , I have a library of different animations built with lottie and aftereffects. And I want to display combinations of these dynamically as per user's request. Is this something lottie supports?

Really appreciate your swift response!

**Comment by weiesky** [comment]
@MB00design image? You need to optimize the image with tinypng。https://tinypng.com/

**Comment by knowBalpreet** [comment]
> @bodymovin , I have a library of different animations built with lottie and aftereffects. And I want to display combinations of these dynamically as per user's request. Is this something lottie supports?
> 
> Really appreciate your swift response!

Hi @bodymovin, Please revert!

**Comment by bodymovin** [comment]
@knowBalpreet unfortunately not easily. Merging multiple separate animations might get complicated because of naming collisions.
And it is not supported by lottie either, you'd need to build some tool around it.
