### ISSUE TITLE
Can't open animation on web

### ISSUE THREAD

**Issue by elazdilamyaa** [airbnb/lottie-web#1488]
**Tell us about your environment**
MacOS Mojave

* **Browser and Browser Version:**
Safari 12.0.2
* **After Effects Version:**
16.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**

I downloaded an ae online and I opened it with my ae, it work fine but I can't use in my website in html5
**What did you expect to happen?**
animation should work on html

**What actually happened? Please include as much _relevant_ detail as possible.**
I'm trying to use an animation on my website, I rendered an ae by Bodymovin as described, but I got an error TypeError: null is not an object (evaluating 'thisComp.layer('COMP CONTROLS').effect') at $bm_rt = thisComp.layer('COMP CONTROLS').effect('Background Color')('ADBE Color Control-0001');
    ;
**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/open?id=1JZ-xxeSw28hG6e-OX0Y5EHZPZNjxKlhc 

Appreciate your help!

**Comment by bodymovin** [comment]
Hi, Lottie doesn't support Adjustment Layers. Try changing the Comps Control layer to a regular layer and setting it's opacity to 0.
