### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'className' of object '#<SVGTextElement>'

### ISSUE THREAD

**Issue by pjpalomaki** [airbnb/lottie-web#1489]
**Tell us about your environment**
OS X 10.14.2 (18C54) (Mojave)

* **Browser and Browser Version:**
Chrome Version 71.0.3578.98

* **After Effects Version:**
16.0.1 (Build 48)

**What did you do? Please explain the steps you took before you encountered the problem.**
Exported animation without glyphs.

**What did you expect to happen?**
Chrome to render text using external font.

**What actually happened? Please include as much _relevant_ detail as possible.**
Nothing displayed in Chrome, console gives the following error:
```
Uncaught TypeError: Cannot assign to read only property 'className' of object '#<SVGTextElement>'
    at e.addFonts (lottie.js:1)
    at SVGRenderer.BaseRenderer.setupGlobalData (lottie.js:1)
    at SVGRenderer.configAnimation (lottie.js:1)
    at AnimationItem.configAnimation (lottie.js:1)
    at XMLHttpRequest.s.onreadystatechange (lottie.js:1)
```

**Please provide a download link to the After Effects file that demonstrates the problem.**
[test.aep.zip](https://github.com/airbnb/lottie-web/files/2821200/test.aep.zip)

I'm trying to export without glyphs, using an external font but keep getting the error above in Chrome dev console. These are my font export settings:

![screenshot 2019-02-01 at 10 39 35](https://user-images.githubusercontent.com/9024380/52118383-0d892480-260e-11e9-8960-66960889cf4c.png)

Am I doing something wrong? Is this something I can fix in my js?

Thanks!

**Comment by pjpalomaki** [comment]
The reason I wanted to try if I can get it running without glyphs is because with glyphs, although everything looks right and all fonts seems ok, I get this in the console:
```
Missing character from exported characters list:  
 Regular Slate Std
e.getCharData | @ | lottie.js:1
-- | -- | --
  | TextProperty.completeTextData | @ | lottie.js:1
  | TextProperty | @ | lottie.js:1
  | ITextElement.initElement | @ | lottie.js:1
  | SVGTextElement | @ | lottie.js:1
  | SVGRenderer.createText | @ | lottie.js:1
  | BaseRenderer.createItem | @ | lottie.js:1
  | SVGRenderer.buildItem | @ | lottie.js:1
  | BaseRenderer.buildAllItems | @ | lottie.js:1
  | BaseRenderer.initItems | @ | lottie.js:1
  | AnimationItem.checkLoaded | @ | lottie.js:1
  | AnimationItem.waitForFontsLoaded | @ | lottie.js:1
  | AnimationItem.configAnimation | @ | lottie.js:1
  | s.onreadystatechange | @ | lottie.js:1
  | XMLHttpRequest.send (async) |   |  
  | load | @ | lottie.js:1
  | AnimationItem.setParams | @ | lottie.js:1
  | t.loadAnimation | @ | lottie.js:1
  | loadAnimation | @ | lottie.js:1
  | (anonymous) | @ | script.js:1
```

**Comment by bodymovin** [comment]
Hi I exported the animation and it seems to work fine.
But I don't have that font.
Can you share a link with the implementation so I can check the error?

**Comment by pjpalomaki** [comment]
Here it is;
[6.2.zip](https://github.com/airbnb/lottie-web/files/2821448/6.2.zip)

**Comment by bodymovin** [comment]
Not sure why in your context there is an svg attribute `classname` that is readonly.
I've changed it to use `setAttribute` instead.
It'll be available for the next deploy.

**Comment by laygir** [comment]
Hi peoples, I'm having the same issue here. Any estimation for the next deploy?
