### ISSUE TITLE
svg scaling and color rendering 

### ISSUE THREAD

**Issue by jpetitte** [airbnb/lottie-web#1490]
Quick question I hope. We've designed a rectangle in AE on a 4K screen to be 10px high (according to AE). 

When we test the rectangle in bodymovin on a 1080p screen, it is 2px high (which is fine), but the color is oddly off.  The ends of the rectangle are closer to the correct color than the center, especially when the rectangle is white. 

(this is an example when the rectangle is black)
![img_20190201_163023](https://user-images.githubusercontent.com/1114754/52164401-cf980900-26be-11e9-8401-4502c4ff1cf5.jpg)

We suspect this is due to some estimation that the browser must do when scaling the svg to different px heights, but we're curious if there is something else we could fix from our side. Ideally every pixel in the rectangle shows up the same (desired) color. 

Thanks!

**Comment by bodymovin** [comment]
Hi, it's probably related to scaling on the browser indeed.
Have you tried with the canvas renderer to see if it looks better?

**Comment by jpetitte** [comment]
I'll give that a try and report back.

**Comment by jpetitte** [comment]
Hey, I just wanted to follow up that our solution was to make the lines a bit thicker. The color seems to be solid now. 

Sorry I wasn't able to test the canvas option when the lines were thinner. You can go ahead and close this.
