### ISSUE TITLE
Issues with Exporting & Exporting Gradients

### ISSUE THREAD

**Issue by samday26** [airbnb/lottie-web#1491]
**Tell us about your environment**
Macbook Pro 2018
AE CC
AI CC

* **Browser and Browser Version:**
Chrome Version 71.0.3578.98

* **After Effects Version:**
16.01

**What did you do? Please explain the steps you took before you encountered the problem.**
I'm using overlord to bring my AI files into AE. But I'm having lots of issues once they are exported (viewing in the demo export). I have not animated the files yet, I'm just trying to export them as static files for placeholders on the site I'm working on.

**What actually happened? Please include as much _relevant_ detail as possible.**
Either the gradients aren't coming through correctly, coming through as completely different colours or the entire file is exporting with lots of errors. I've looked in the forums and seen that saving the file before exporting can fix the problems with gradients but this isn't working for me.

**Please provide a download link to the After Effects file that demonstrates the problem.**
Here is an example of one that is exporting with lots of errors:
https://drive.google.com/drive/folders/1x40bhsuu4Pp3xpnn8YTMbbKXrAI5qOwI?usp=sharing
Here is an example where the colour of the gradients are different:
https://drive.google.com/drive/folders/1Of3_VfD4qR3WrjbXnl9huTw27OwHvhhp?usp=sharing

**Comment by samday26** [comment]
I've figured it out. I have to name every layer and group!

**Comment by bodymovin** [comment]
Hi, unfortunately overlord seems to be using merge paths which are not supported by the player yet.
