### ISSUE TITLE
Uncaught TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by waelabdrabbo** [airbnb/lottie-web#1494]
[image](https://user-images.githubusercontent.com/25639647/52521858-86c7ed80-2c86-11e9-8fe0-36f144250645.png)

**Tell us about your environment**
Windows 10

* **Browser and Browser Version:**
in all browsers

* **After Effects Version:**
16.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**
i rendered the comp from after effects as json file and i implement it like the other files, all of them works except this one

**What did you expect to happen?**
logo should be animating

**What actually happened? Please include as much _relevant_ detail as possible.**
Uncaught TypeError: Cannot read property 'constructor' of undefined

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/drive/folders/1XO_kCgOQ5cNeAyFnkM6kRNtuxunOMdPS

**Comment by bodymovin** [comment]
Hi, there are some expressions that are not supported.
I've just added them for the next deploy.
There is one more thing that won't work which is negative stretching of layers. If you change it to time remap, it should work fine.

**Comment by waelabdrabbo** [comment]
> Hi, there are some expressions that are not supported.
> I've just added them for the next deploy.
> There is one more thing that won't work which is negative stretching of layers. If you change it to time remap, it should work fine.

so should i remove the negative stretching and wait for the next deploy?
Thanks.

**Comment by bodymovin** [comment]
yes
