### ISSUE TITLE
Bodymovin not rendering gradients correct

### ISSUE THREAD

**Issue by Avagart** [airbnb/lottie-web#1495]
Hi I have a problem with bodymovin.

I created an animation in After Effects using gradients with color and transparency.
But when I export it, the .json and the demo file just show them black and white and without transparency.

Thanks for your help

**Comment by bodymovin** [comment]
Hi, have you saved the project before exporting?

**Comment by Avagart** [comment]
Yes I did. I also set the language on english. didn't fixed anything..

**Comment by bodymovin** [comment]
can you share the .aep?

**Comment by Avagart** [comment]
[BFU_Animation_Spurwechsel Ordner.zip](https://github.com/airbnb/lottie-web/files/2849060/BFU_Animation_Spurwechsel.Ordner.zip)

**Comment by bodymovin** [comment]
what's the layer and gradient that isn't working?

**Comment by Avagart** [comment]
every gradient isn't working. they're all black and white after exporting

**Comment by bodymovin** [comment]
I just tried it and it seems to work fine.
What language is your OS?

**Comment by Avagart** [comment]
german

**Comment by bodymovin** [comment]
it might be related to that.
can you try on layer "Radar" > "Contents" > "Verlaufsfüllung 1" rename it to "GradientRadar" to see if it fixes that one?

**Comment by Avagart** [comment]
still no difference. looks still like this:
<img width="1281" alt="bildschirmfoto 2019-02-10 um 17 03 13" src="https://user-images.githubusercontent.com/47500579/52536028-db866980-2d55-11e9-8972-f7b46122ada0.png">

**Comment by bodymovin** [comment]
[render.zip](https://github.com/airbnb/lottie-web/files/2849084/render.zip)
this is how I see it

**Comment by Avagart** [comment]
can you send me a demo file too?

**Comment by Avagart** [comment]
your .json seems ok.
so what can I do?

**Comment by Avagart** [comment]
Any Idea what I can do to solve the problem?

**Comment by bodymovin** [comment]
there are some issues addressing this problem, perhaps they can help.

**Comment by VeiZhang** [comment]
@Avagart Is the gradients solved? It also happend in my project.

**Comment by VeiZhang** [comment]
@Avagart https://github.com/airbnb/lottie-web/issues/1201 is good job! You can try it

**Comment by nomisum** [comment]
@bodymovin i had the same problem (german AE) and renaming to `GradientRadar` fixed it for me. Thanks a lot.

**Comment by loewin1** [comment]
Hey @nomisum which object directly did you change? 🙃

**Comment by d-korolkov** [comment]
The solution is to rename all gradients "Gradients Fill 1" into Gradient Fill_1, Gradient Fill_2,Gradient Fill_3.... AND ALSO what had closed all still remaining problems after that is to rename all sublayerd Groups from Group 1, Group 2, Group 3 where gradients are presented to Group_1, Group_2, Group_3. This closed my problems.

**Comment by rutraq** [comment]
Hello. I have a problem. When I want to export to json file I have a problem with one picture. It didn't export, I'm waiting about 5 minutes and nothing happens
![Безымянный](https://user-images.githubusercontent.com/25290984/80191561-8a8f2800-861e-11ea-80fe-278dd321485b.png)

**Comment by Wifesteal3r** [comment]
@d-korolkov Thanks a lot, it solved my problem.

**Comment by loewin1** [comment]
so unfortunately the renaming didn't work from my side, but it looks like for me it's working to simply change the language of AE to English. I'm working on a German Macbook.

**Comment by julien288** [comment]
Bonjour @bodymovin,

**Comment by julien288** [comment]
Bonjour @bodymovin, (désoler de parler en français) j'ai un problème du rendu des dégradés (noir et blanc) et de transparence quand j'exporte en .json avec bodymovin V5.6.9 J'ai mis mon AE 2020 en anglais, j'ai sauvé avant d'exporter, rien ne se passe... Pouvez-vous m'aider, merci d'avance ! Voici mon fichier :
[help-animation.aep.zip](https://github.com/airbnb/lottie-web/files/4545506/help-animation.aep.zip)

**Comment by d-korolkov** [comment]
Bonjour! You can fix the color problem by renaming all French named layers
to unique Latin/numerical names without special characters like "à". The
problem of further brightness of the "route-01 Silhouettes" layer you can
fix by duplicating it (with new sub layers names of-course)

[image: 1.jpg]

Sincerely,
Dmytro Korolkov.
--
Follow me on Facebook <https://www.facebook.com/d.y.korolkov>
Follow me on Linkedin <https://linkedin.com/in/dmytro-korolkov-78b1b2123>
My Skype is d.y.korolkov

**Comment by whizzkkid** [comment]
I made a moving gradient background on ae and tried to export it by bodymovin and in preview, it shows it in form of blue as it was my composition color.

i am using macos which language is set to English us and ae is in English.

i tried few more steps to solve this precomposing or renaming gradient i used 4 layer gradient
same like this 
[https://youtu.be/xlFsfHF3Yb4](url)

few snaps:
![Screen Shot 2020-12-16 at 11 01 41 PM](https://user-images.githubusercontent.com/54703305/102384446-b9fe0500-3ff2-11eb-9b00-04c24dc526b6.png)
I want to achieve this

![Screen Shot 2020-12-16 at 11 01 56 PM](https://user-images.githubusercontent.com/54703305/102384476-c5513080-3ff2-11eb-8a98-dd40d7d031e6.png)
preview

please help asap!!

**Comment by RytisJonikas** [comment]
> 

How do you renamce inside the content? I can't seem to ble able to do it.
![image](https://user-images.githubusercontent.com/63051244/173581818-eb598942-eacf-4615-8456-19ac2122c675.png)

**Comment by bodymovin** [comment]
@RytisJonikas select the property and hit Enter on your keyboard

**Comment by Ritick-cloud** [comment]
my gradient is not showing please tell me the solution

**Comment by Ritick-cloud** [comment]
I did every solution but nothing is working

**Comment by d-korolkov** [comment]
Please share the project file.

**Comment by Agustin-Bulzomi** [comment]
For people still experiencing problems after all of the aforementioned troubleshooting: if you have different gradients, give each of them a different number. Adobe will name all of them "Gradient Fill 1" by default... only when I had "Gradient Fill_1", "Gradient Fill_2", "Gradient Fill_3", etc. across all objects (no repeating numbers) it finally worked.

**Comment by JSRM1018** [comment]
SAD...Not work every time :(

Windos
After effects 2023

1.Swich English Mode > X
2.Rename Gradient_1
3.Render before save aep.
![擷取](https://github.com/user-attachments/assets/1e5bb44a-a160-48ee-970b-882f656d11b3)

**Comment by JSRM1018** [comment]
SAD...Not work every time :(
![Capture](https://github.com/user-attachments/assets/20fedc8c-7d5a-446c-a0b6-b7d4acb36bac)

Windos
After effects 2023

1.Swich English Mode > X
2.Rename Gradient_1
3.Render before save aep.
4.Set key gradient fill start and end,include color.

**Comment by JJmw0** [comment]
SAME ISSUE

**Comment by whitehat102** [comment]
To anyone who is still having issues even with the solutions mentioned here. I fixed my gradient by just manually editing the SVG using Notepad with the help of ChatGPT. However I only tried it with linear gradients, I'm not sure if it works on other gradient types.
