### ISSUE TITLE
Any way to trigger bodymovin animation after the page is loaded

### ISSUE THREAD

**Issue by akashrwx** [airbnb/lottie-web#1496]
Hello,

Is there any way I can trigger bodymovin animation after the page is loaded till then it just shows poster image. The animation which I am using is decreasing the google page speed very much.

Attached is my JSON file which I am using. Please help

[banner.zip](https://github.com/airbnb/lottie-web/files/2850537/banner.zip)

**Comment by bodymovin** [comment]
yes, you can load it once the page is loaded using window.onload for example

**Comment by akashrwx** [comment]
Thanks a lot for replying. But I really think that the poster feature will be great for loading complex animation as it will reduce website loading speed a lot. Please do let me know what you think.

**Comment by bodymovin** [comment]
yo can get a "poster" of the animation by reading the innerHtml of a rendered svg frame and display it until the player is loaded.

**Comment by akashrwx** [comment]
Hello,

I understood what you just said but writing the javascript is a bit tough task for me as I am a complete newbie in the javascript part. 

It will be very much helpful for me if you can share a full <script> for it.

Thanks a lot in advance
