### ISSUE TITLE
Dynamic text animation with animography

### ISSUE THREAD

**Issue by johnconnorskynet** [airbnb/lottie-web#1497]
Hi,

Would it be possible to export animography typefaces composition [https://animography.net/collections/typefaces ](https://animography.net/collections/typefaces) then change text and tweak animation parameters the way it is done with their after effect scripts [https://animography.net/collections/extras](https://animography.net/collections/extras) with bodymovin and lottie?

Thanks.

**Comment by charlesbail** [comment]
I don't think you will be able to access any of the expressions on this plugin.
You could create your animation, then bake it with https://aescripts.com/easy-bake/ for example, then export it with bodymovin. But I don't think there is any compatibility with bodymovin and animography so you won't be able to edit it through code (or even display it)

**Comment by johnconnorskynet** [comment]
Hi Charles,

Thanks for your answer, i tried to export animography mobilo typeface example composition and it worked, you can check it out here [https://lottiefiles.com/4232-animography-mobilo](url). Maybe controlling the animation paramaters is not possible but at least would it be possible to change the text
like in this example [https://codepen.io/airnan/pen/ZLVJmq?editors=0010](url) and create multilines. Ultimately what i am trying to achieve is to allow mobile and web users to create a custom animated text object like in the legend app renamed text animated you can find here [https://play.google.com/store/apps/details?id=appiz.textonvideo.animated.animatedtext](url)

**Comment by charlesbail** [comment]
It's only possible to edit the text if it's a text in After Effects in the first place. But the plugin you use and the baking of the expression makes each part of a letter as a shape. See in the screenshot as it's considered as a shape.

In the past I did a multilang animation. But my text was a text layer with no plugin or baking. Then I could just access the content as a normal text

![image](https://user-images.githubusercontent.com/12492829/52600039-aadc2800-2e5a-11e9-8c7e-bbf861cc773a.png)

**Comment by johnconnorskynet** [comment]
Hi @charlesbail ,

Thanks for the answer. Yep this is what i discovered as well. A solution would be to embed all characters in the json file and compose words from character shapes. The problem would be that the json file would be too big as the aep file with all the characters is already 170 Mo.
So the good news is  it could be possible to create a composition with text placeholder and change it programmatically afterwards. I guess the text must have a maximum length constraint and i am wondering how multiline text could be done like this : 


![](https://freefrontend.com/assets/img/css-text-animations/Pure-CSS-Text-Animation.gif)


To give you an vizualization of what i am trying to achieve with lottie here are some examples

![](https://pa1.narvii.com/6808/b5cbb16a842158a17bf3ed288860b777c820da72_hq.gif)


![](https://pa1.narvii.com/6808/f64ccb75aa0634de0106bb6ee564d33f34e8702c_hq.gif)

**Comment by adberard** [comment]
Any progress on this ? @johnconnorskynet
