### ISSUE TITLE
Host Images on S3

### ISSUE THREAD

**Issue by aakey7** [airbnb/lottie-web#1498]
I have some svg's that I would like to load from an S3 bucket. Is it possible to have some images loaded from the /images folder but then also images from S3? How would I go about achieving this?

**Comment by laygir** [comment]
Hey!

I just did that yesterday.
The way I approached was to set id's in After Effects for each image I like to replace later on. Then picked all those images on the javascript side then replaced it before I start playing the animation.

`const thumbnail = document.getElementById(previewCircles[i]).getElementsByClassName('thumbnail');
thumbnail[0].firstChild.href.baseVal = circles[i].thumbnail;`

**Comment by bodymovin** [comment]
Hi, I can't think of a simple way to do it.
@laygir solution might be the simplest right now.
Another option, if you are comfortable editing the exported json file, you can search for the assets array and replace the relative urls with absolute ones.
