### ISSUE TITLE
black background

### ISSUE THREAD

**Issue by jingyebuchen** [airbnb/lottie-web#1499]
I became a black background when I used the json preview generated by bodymovin in ae. Why?

**Comment by bodymovin** [comment]
Hi can you share the .aep?

**Comment by jingyebuchen** [comment]
[aep.zip](https://github.com/airbnb/lottie-web/files/2863701/aep.zip)
First of all, thank you very much. I just want to take the special effects out and convert them into json for my web page, but the json I converted can't display normally.

**Comment by bodymovin** [comment]
Hi, adjustment layers and the effects you are using are not supported by the player unfortunately.

**Comment by jingyebuchen** [comment]
Ok, thank you too. Does this mean that this cool and complex effect can not be directly applied to the web page after being made by ae?

**Comment by bodymovin** [comment]
Unfortunately, it means exactly that.

**Comment by jingyebuchen** [comment]
Ok, I know, I hope that we can break through one day, thank you very much.
