### ISSUE TITLE
Layer stroke on a pre-composed composition

### ISSUE THREAD

**Issue by Peter-Spare5** [airbnb/lottie-web#1500]
I have an animation with 2 main things going on:

1. One composition with some shapes that rotate and move (with parenting) which have been converted to shapes from an imported Illustrator file.
2. A parent composition which contains the first composition and which applies a layer style > stroke to the first composition.

When I export with Bodymotion I get the shapes rotating and moving, but I don't get the stroke from the layer style. I looked in the supported features page and made sure the things I'm using are supported:

- Parenting
- Pre-comps
- Stroke layer style

Is it possible to do what I'm trying to do? 

Image of the result I want
![image](https://user-images.githubusercontent.com/20564054/52891618-f6cfeb00-3140-11e9-9ed5-17f0220b8c1f.png)

Image of the result I'm getting:
![image](https://user-images.githubusercontent.com/20564054/52891578-bd977b00-3140-11e9-889a-3762b7235970.png)

Image of my child composition:
![image](https://user-images.githubusercontent.com/20564054/52891596-d43dd200-3140-11e9-9d7a-739f7d4fa9a4.png)

Image of my parent composition (with the stroke on it):
![image](https://user-images.githubusercontent.com/20564054/52891611-eae42900-3140-11e9-9312-ab53500a4194.png)

**Comment by bodymovin** [comment]
Unfortunately layer stroke is not supported.
Even if supported, for real time rendering, performance would be terrible.

**Comment by Peter-Spare5** [comment]
Thanks so much for the insight! I've got another idea about how to make this work (create the offset strokes as separate, filled shape layers in Illustrator, and then parent them under their corresponding shape in After Effects).
