### ISSUE TITLE
Animation Choppy with all Browsers at Large Window Sizes

### ISSUE THREAD

**Issue by daniel-pluckvermont** [airbnb/lottie-web#1504]
**Tell us about your environment**
Mac, Mojave

* **Browser and Browser Version:**
Chrome, Firefox, Safari—Latest Versions

* **After Effects Version:**
CC19

**What did you do? Please explain the steps you took before you encountered the problem.**
Rendered 4 second animation using solely Shape Layers with Generate Stroke Effect.

**What did you expect to happen?**
Continuous looping smooth animation of Rain drops at all browser sizes

**What actually happened? Please include as much _relevant_ detail as possible.**
Continuous looping choppy animation of rain drops that gets less choppy at smaller browser sizes and increasingly choppy the larger the browser window.

**Please provide a download link to the After Effects file that demonstrates the problem.**
[Zip](https://www43.zippyshare.com/v/XMkDZX81/file.html)

**Comment by bodymovin** [comment]
Hi I can't use that file transfer system. Can you attach the zip here?
Regarding the stroke effect, it uses svg masks under the hood that don't have a great performance on some browsers, specially with large assets.
