### ISSUE TITLE
What all Properties can we change through JSON?

### ISSUE THREAD

**Issue by knowBalpreet** [airbnb/lottie-web#1505]
Hi @bodymovin,

Just wanted to know what all things one can change by parsing the JSON file?
Can one change size, position, font color, font background color, font family, etc. of the assets layers in the JSON?

Your revert to this would be highly appreciated!

**Comment by bodymovin** [comment]
yes, as long as the animation hasn't been loaded yet, you can change all that.
Here are all json props if you're interested
https://github.com/airbnb/lottie-web/tree/master/docs/json

**Comment by knowBalpreet** [comment]
Hi @bodymovin , the documentation seems great. But I am not able to find options for changing background color, size and option? Can you point me in the right direction?

**Comment by bodymovin** [comment]
background color size and option of the svg container?

**Comment by knowBalpreet** [comment]
Hi @bodymovin , thank you for reverting. 
My use case is I have an SVG container whose background color needs to be changed. 
And complete layers which contain text layers and stroke layers. 
1. Now I want to resize the complete layer such that all the other layers in between gets resized accordingly. 
2. Also, I want to change the position of these elements( drag and drop ). 

I want to these changes in JSON before viewing the animation. From the docs, I understand the capability to do changes in the text layer. But need certain clarity to perform above operations.

Thanks in advance!

**Comment by himanshu-thakur-7** [comment]
Hi @bodymovin  ... Can I just change some text of a Lottie animation file ... Given that text is not in any layer but exported as glyph???... Plz acknowledge it will be very helpful
