### ISSUE TITLE
Lottie animation file Not working on self hosted site

### ISSUE THREAD

**Issue by bhoomi1711** [airbnb/lottie-web#1506]
**What did you do? Please explain the steps you took before you encountered the problem.**
I've made Character animation. Only shapes, masks.

**What did you expect to happen?**
I expected to get working animation on self hosted site

**What actually happened? Please include as much _relevant_ detail as possible.**
Lottie animation is working fine in my localhost. It doesnt work on self hosted site.
Also .Json file is working fine in Lottie preview site.

**Please provide a download link to the After Effects file that demonstrates the problem.**
[character_waiting_animation.zip](https://github.com/airbnb/lottie-web/files/2883492/character_waiting_animation.zip)

**Comment by bodymovin** [comment]
Hi, can you share a link to your hosted site?

**Comment by bhoomi1711** [comment]
Hi,

Click on below link and then click on **SIGNIN** button from top header menu. After click on Signin button, one popup dialog open and animation block will display which is not working.

https://devapp.teetra.com/marketplace

**Comment by bodymovin** [comment]
I'm not sure it's related to that, but is it possible that you're loading the player multiple times in your site?

**Comment by bhoomi1711** [comment]
I don't think that, because the other animations of using lottie is completely working. 
You can check on click of **WORK** dropdown and select **Fffffffffffff** category, and then display **No works found** animation which is also using Lottie animation.

**Comment by bodymovin** [comment]
It seems that you're not just loading multiple animations, you're loading the player multiple times.
Where are you getting the animations json data from?
