### ISSUE TITLE
Option to export Demo with parameter loop: false

### ISSUE THREAD

**Issue by tinogithub** [airbnb/lottie-web#1507]
Hi,

I am exporting many animations out of After Effects which are implemented directly in a web page. However these animations aren't loops. Therefore I have to change in every demo.html the parameter **loop** to false manually. Could there be an option in the export panel to decide if the animation should be a loop or not?

Or is there already an option that I don't know of?

thank you,
Konstantin

**Comment by bodymovin** [comment]
hi, the demo.html file is intended for quick view, but it's not recommended for loading them on final webpages because it includes the full player on each export.
You should try to export the json files and load them the documented way.

**Comment by tinogithub** [comment]
Hi,
unfortunately I just hand over the files. It is uploaded on an e-learning system called MoKick. I don't understand this workflow either. However I would have changed the source demo.html myself but it is all XML signatured :-)

**Comment by bodymovin** [comment]
if you only need to change the loop value, you can scroll to the bottom of the html and you'll see it says `loop: true`.  
You just need to change it to false.

**Comment by tinogithub** [comment]
Thank you for your participation, 

As I mentioned in my first comment I know this process. However because of exporting many animations and versions through the day I just wanted to ask if it could be an option to decide on the user side whether it is a loop or not. When I change in your source files the assets\player\demo.html, the extension won't startup anymore in After Effects. It is because of the PackageSignature. I don't understand why you use it? It would be nice to experiment with the code.

Thank you for your help,

**Comment by bodymovin** [comment]
The code is here, https://github.com/bodymovin/bodymovin-extension if you want to make your own build.
Package Signature is needed to distribute the extension.
Regarding changing the loop to false, you can write a script that replaces all your files with a `false` value

**Comment by tinogithub** [comment]
Hi,
thank you for your help. And yes till now I replaced the files manually by a script.

So, I managed to create a build out of the source code with "npm run build". However I still have to package the build with ZXPSignCmd, right? 
I looked at http://wwwimages.adobe.com/www.adobe.com/content/dam/acom/en/devnet/creativesuite/pdfs/SigningTechNote_CC.pdf and downloaded ZXPSignCmd. But I still need the p12 and p12-password. Or do I missunderstand something?

thank you.

**Comment by tinogithub** [comment]
Sorry,
after having found some other information I managed to create my certificate and verify the .ZXP.
Now I will try to change the source referring to the creation of the demo.html. Still couldn't find the place where it is generated in the source.

thank you for your help.

**Comment by tinogithub** [comment]
Okay, finally, happy to announce :-) I managed to solve my problem.
Thank you bodymovin for your assistance.
You do a good job.
