### ISSUE TITLE
Animation is frozen and not displaying elements properly

### ISSUE THREAD

**Issue by sulemanshahjahan** [airbnb/lottie-web#1508]
**Tell us about your environment**
I have animations in AE and I tried converting them to SVG Lottie Animations.
One works 100% fine: http://suleman.website/illustration-2/lottie.html
And other doesn't work at all it is being displayed improperly and also the animation is not working: http://suleman.website/illustration-3/lottie.html

* **Browser and Browser Version:**
Any Browser

* **After Effects Version:**
After Effects CC 2018

**What did you do? Please explain the steps you took before you encountered the problem.**
I opened animation in AE and rendered it but didn't work and when I open console it shows me an error which is https://ibb.co/BnqK2V7

**What did you expect to happen?**
I expected it to animate like https://ibb.co/LpFwMKT

**What actually happened? Please include as much _relevant_ detail as possible.**
But it's not displaying the elements properly plus it's not animating I have tried converting Vectors to shapes but no success. 

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://wetransfer.com/downloads/23ab86a13c0d39ae4362b514515964a320190220090235/729e307065efb568ce023628a6c0c67320190220090235/66ee36

**Comment by bodymovin** [comment]
hi, you're using an older player that the exported animation. (5.4.3 vs 5.4.4)
Try updating the player to the latest version and it should work fine.

**Comment by sulemanshahjahan** [comment]
Do you mean the the player extension inside AE?

**Comment by sulemanshahjahan** [comment]
OK so I've updated the player to 5.4.4 but it doesn't work now it shows error in console "Cannot read property 'constructor' of undefined". 

http://suleman.website/illustration-3/lottie.html

**Comment by sulemanshahjahan** [comment]
Please help me, I have already completed a website and only thing remaining is the lottie animations. It's been around a week I am trying to figure out how to make them work.

**Comment by bodymovin** [comment]
Can you share the missing files to complete the project?

**Comment by sulemanshahjahan** [comment]
Can you please let me know which missing files? are you talking about the website missing files or missing files in AE project?

**Comment by bodymovin** [comment]
ae project

**Comment by sulemanshahjahan** [comment]
There's no missing files and I only have few illustrator files which animator gave me along the ae project file.

**Comment by bodymovin** [comment]
yes, those are the missing files

**Comment by sulemanshahjahan** [comment]
Here are the complete files: https://we.tl/t-bs518rbPKN

**Comment by bodymovin** [comment]
Ok, I'll take a look later today when I get back from work.

**Comment by sulemanshahjahan** [comment]
Thank you so much, it will be an huge help. My client has been waiting for more than a week this is the only remaining part in the project.

**Comment by sulemanshahjahan** [comment]
Hi, any quick help would be really appreciated.

**Comment by bodymovin** [comment]
Hi, unfortunately you're using effects and expressions that are not supported by the player.

**Comment by sulemanshahjahan** [comment]
Is there anything we can do about it, are you going to update in the future so it supports those effects?

**Comment by bodymovin** [comment]
Not in the short term unfortunately. Performance is not good with the supported web technologies.
For this type of animation you probably should use regular formats like video or gifs.
