### ISSUE TITLE
Safari Webarchive files display two copies of each animation

### ISSUE THREAD

**Issue by Joolyan** [airbnb/lottie-web#1509]
**Tell us about your environment**
macOS High Sierra 10.13.6

**Browser and Browser Version:**
Safari 12.0.3

To present examples of website pages when offline, the Safari save as 'Web Archive' is very useful. However, pages which include bodymovin/lottie-web animations, display one static copy of the animation and below a fully working copy of the same animation.

To reproduce the issue, use Safari to visit https://airbnb.design/lottie/ save as 'Web Archive' then double click the saved  'Lottie.webarchive' file to open in Safari. Everything works perfectly, however the animations are in the wrong place because there are two copies, one static and one animated.

NB. Both svg and canvas renderers have the same issue.

Using Safari 'Inspect Element' it's possible to select and delete the first "<svg..." node, however it's not possible to re-save the edited Webarchive (the Save As option is greyed out)

I've attached a zipped copy of 'Lottie.webarchive' for reference.
[Lottie.webarchive.zip](https://github.com/airbnb/lottie-web/files/2884628/Lottie.webarchive.zip)

Thanks for any help.

**Comment by bodymovin** [comment]
Hi, Safari must be copying all the html present at time of saving, which has the inline svg of the rendered frame.
Before saving as Web Archive, you could remove the svg element so you wouldn't get both copies.

**Comment by Joolyan** [comment]
Fantastic service. Your solution worked!

I've only just seen your reply and have only tested using https://airbnb.design/lottie/ but I'm sure it will also work for my own content.

I'm not sure how issues are closed, but very happy to see this issue as resolved.
Thank you.

**Comment by bodymovin** [comment]
Glad it worked.
