### ISSUE TITLE
demo.html works, .json path in browser shows nothing; no errors in console

### ISSUE THREAD

**Issue by 3milychu** [airbnb/lottie-web#1510]
Chrome Version 72.0.3626.109 
AE CC

Works in demo.html, but data.json shows nothing on web; no errors in console. Also shows nothing when testing data.json in lottiefiles.com

web:
https://3milychu.github.io/thesis/kairos/prototype/assets/animations/onboarding.html

json: https://3milychu.github.io/thesis/kairos/prototype/assets/animations/data.json

demo file: https://3milychu.github.io/thesis/kairos/prototype/assets/animations/demo.html

**Comment by bodymovin** [comment]
Hi, you're using a canvas as the container to the svg animation.
Canvas won't display DOM elements rendered in them.
If you change it to a div, it should work fine.

**Comment by 3milychu** [comment]
Thank you,, that was the issue.

**Comment by mahnueldev** [comment]
Hello, i have a similar issue but the difference is that i used a div and the animation still doesn't show and also no errors on the console. What else can i do to fix this?

**Comment by bodymovin** [comment]
@mahnueldev can you share a link with the implementation?

**Comment by mahnueldev** [comment]
@bodymovin Here
[https://github.com/mahnueldev/myfirstweb](url)

**Comment by bodymovin** [comment]
Your script tag is before the div element is present in the DOM.
So `document.getElementById('bm')` returns null.
Try moving the tag to the end:
`<script src="index.js"></script>`
or you can load the animation when the window onload event is fired:
```js
window.onload = function() {
	var animation = lottie.loadAnimation({
	    container:document.getElementById('bm'),
	    renderer: 'svg',
	    loop: true,
	    autoplay: true,
	    path: 'jump.json'
	})
}
```

**Comment by mahnueldev** [comment]
Thank you. It got fixed
