### ISSUE TITLE
Can't render the file

### ISSUE THREAD

**Issue by joyjoyjoyjoyjoy** [airbnb/lottie-web#1512]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by joyjoyjoyjoyjoy** [comment]
Hi, I am using AE CC 16.0.1
I tried to render the animation in bodymovin. It kept showing  there are no compositions to render.....
[sample.aep.zip](https://github.com/airbnb/lottie-web/files/2893108/sample.aep.zip)

**Comment by bodymovin** [comment]
did you select the composition you want to render and set a destination path?
