### ISSUE TITLE
Wordpress Bodymovin: No preview or shortcode generated.

### ISSUE THREAD

**Issue by jinxer15** [airbnb/lottie-web#1513]
I have been making animated SVGs with Bodymovin and I have successfully made and uploaded simple animation to my Wordpress site using the WP Bodymovin plugin. 

However I made a more complex animation and exported the JSON file and the demo file to test it. The demo works flawlessly. But I left clueless as to why it won't preview or generate a shortcode in Wordpress when I upload the JSON file. The Preview panel will scale to fit the animation as if it is there, but nothing plays and the shortcode panel is blank. 

I tried this on another Wordpress site I have and it does the same thing. 

Does anyone have a clue as to what is wrong and how to correct it?

**Comment by jinxer15** [comment]
Here are my files.
[heroanimation.zip](https://github.com/airbnb/lottie-web/files/2894936/heroanimation.zip)

**Comment by bodymovin** [comment]
Hi, can you share the link to your wordpress site?

**Comment by jinxer15** [comment]
https://www.joshualeeterrell.com/sample-page/

**Comment by jinxer15** [comment]
On this sample page I have two animations made through the same method. But this new one won't even show like I said.

**Comment by bodymovin** [comment]
I see the animation working in that link. What should I be looking for?

**Comment by jinxer15** [comment]
Thats just it, I use WP Bodymovin to upload my json files. I have 3 uploaded. This new (third one) does preview in that plug-in.

**Comment by bodymovin** [comment]
I don't know exactly how the plugin works.
But I see it's loading an old version of the player(5.2.1).
What version of the exporter are you using in AE? could it be related to that?

**Comment by jinxer15** [comment]
I just tried something else. It works in Wordpress if I render the file without the guides selected in the Bodymovin plug-in (After Effects), but it looks like a hot mess. 

Version shows 5.4.3

**Comment by Sandstedt** [comment]
@jinxer15 Is this resolved? Then please close this issue. Else as Hernan suggested, make sure the Bodymovin player in the WordPress plugin and the exporter in AfterEffects is compatible. Else maybe contact the Wordpress plugin author and see if they can help.

**Comment by asimbhuta** [comment]
Was there a proper solution to this? I have the exact same issue.

I have one rendered and works fine but the second animation doesn't preview or generate shortcode in the wp backend but works perfectly fine in the demo.html

**Comment by Sandstedt** [comment]
@asimbhuta Not sure. It's a third party plugin for Bodymovin that is not supported by anyone here. Please contact that creator instead. If that doesn't work, don't use that Wordpress Plugin and write your own instead with an up to date version of the player (or just incorporate it in your theme), or fork the plugin and try to make it work (and publish a PR to that repo).

**Comment by asimbhuta** [comment]
Yes I have it working. 

The bodymovin player versions did not match up between the export from ae and the bodymovin plugin. 

So I edited the plugin by updating lottie js files. 

All works now

**Comment by AustinEvery** [comment]
Can someone explain this to me. Im having the same exact issue. I have a designer sending me a json files to add to this WP BodyMovin plugin and all i'm getting is a blank window, without short code. @asimbhuta what do you mean you updated the lottie js files? Is that exported via AE? or is my designer exporting the wrong stuff?

**Comment by Sandstedt** [comment]
In the WordPress plugin, there is some bodymovin / Lottie ja file for the
player somewhere. Replace them with the same version as your designer has
exported with.

Else, ask the WordPress plugin author if they could fix it. Or write your
own.

Den mån 13 maj 2019 06:45Austin Every <notifications@github.com> skrev:

**Comment by Jackmile** [comment]
Hello to the experts. I ask for help. I've been trying to fix the problem for days, but I can not go on. If I export the file with bodymovin after effects and upload to Wordpress bodymovin, I get only a white area. The demo works, but it does not generate shortcodes on Wordpress. PLEASE HELP ME:

**Comment by AustinEvery** [comment]
Use the link I added above. It has two files. Lottie.js and Lottie.min.js. Go into your website files and replace those files with the ones from the link. That did it for me!

**Comment by Jackmile** [comment]
AustinEvery: Thank you for your help first. Unfortunately, I'm still inexperienced, can you explain to me how I can replace that please?

**Comment by AustinEvery** [comment]
No big deal. Im new to this stuff too. If you're using a web hosting service. just look up **how to replace database files on that hosting service.** The bodymovin files should be under wp-content/plugins/bodymovin/js/... in your website database. The link I sent above has two files I mentioned previously. You should copy and paste those codes in an editor. then when you find the identical files in your database, just replace them with the new ones.

**Comment by Jackmile** [comment]
Thank you, my friend. I'll try, and let you know. Many Thanks

**Comment by Sandstedt** [comment]
Great you solved it. Just note that all files you changes in the WordPress plugins directory could be overwritten if you update the plugin in the future.

**Comment by M-S-Huss** [comment]
> @Sandstedt i fixed this by replacing my lottie.js and lottie.min.js with the files from this github - https://github.com/airbnb/lottie-web/tree/master/build/player

I have tried Austin's trick by replacing the 2 .js files within my Wordpress plugin, but that DID NOT work for me, instead after doing that none of my 12 animations worked, so I reverted back the original plugin's .js files.
So after stripping/experimenting my After Effects animation layer-by-layer I have **SOLVED** the issue, actually 3 of my layers had the "Expressions", and **I had to convert the expressions to frames**, and then the animation worked straight-away within Wordpress.
