### ISSUE TITLE
createNS is not defined

### ISSUE THREAD

**Issue by Sahil5963** [airbnb/lottie-web#1514]
I am using lottie web 

Google Chrome - Version 72.0.3626.109
After Effects CC 2018

I Simply added the CDN to my project an it gave me a console error

whole project seems broken (no animation)

[Corporate Logo Reveal ( CS5 and above ).zip](https://github.com/airbnb/lottie-web/files/2896994/Corporate.Logo.Reveal.CS5.and.above.zip)
![capture](https://user-images.githubusercontent.com/30194141/53289035-30df6380-37b7-11e9-8cb8-96d1c1bb0e3d.JPG)

**Comment by bodymovin** [comment]
Hi, the canvas renderer doesn't support text as font, it only supports glyphs.

**Comment by Sahil5963** [comment]
can you please suggest some fix to that?

**Comment by Sandstedt** [comment]
@Sahil5963 I haven't checked your provided file, nut I guess you could convert the text to shapes and then provide an alternative text in the html element later for screen readers and search engine bots.

**Comment by bodymovin** [comment]
@Sahil5963 can you use the svg renderer instead of canvas?

**Comment by olonade43** [comment]
@bodymovin having this same issue with svg or canvas render options

**Comment by bodymovin** [comment]
@olonade43 can you share the json file?
