### ISSUE TITLE
updating assetsPath while animation is running

### ISSUE THREAD

**Issue by derbalint** [airbnb/lottie-web#1515]
First, thanks for this amazing piece of software!

I am using an external link for my assetsPath to load a png in my animation which works great.
my problem is, that I want to change to another external url after an input was entered, to display a different png.

I have no problem updating text while the animation is running or change autoplay/loop etc.
But I can't update the assetsPath on the fly. Any tips?

Here is my code, working except for updating assetsPath.

```
let animation;

  fetch("https://api.myjson.com/bins/1fwn1a")
    .then(response => response.json())
    .then(animationJson => {
    animation = lottie.loadAnimation({
      container: document.getElementById('prototype'),
      autoplay: true,
      loop: true,
      animationData: animationJson,
      assetsPath: 'URL1',
    });

    let input = document.getElementById('test_input');
    input.addEventListener("keydown", (event) => {
      if(event.key === 'Enter') {
        if (input.value != "") {
          animation.renderer.elements[2].updateDocumentData({t:input.value});
        } else {
          animation.renderer.elements[2].updateDocumentData({t:"Nothing entered"});
        }
        input.value = "";
       animation.assetsPath='URL2';
      }
    });
});
```

**Comment by bodymovin** [comment]
Hi, unfortunately that won't work because image attributes are already set.
You can change the image path yourself by querying the DOM and updating it manually.

**Comment by derbalint** [comment]
Thanks Hernan, for anyone being interested in the solution, I solved it by executing this after a click event.

This selects the first <image> which is part of the <svg> element which contains the animation.
If you work with multiple animations / svgs you have to query a specific one.
Usually the <svg> element doesn't appear in your html document, but in the svg DOM, thats why this code works.

`document.querySelector("image").setAttributeNS('http://www.w3.org/1999/xlink', 'href', 'YOUR URL');`
