### ISSUE TITLE
Relative asset check

### ISSUE THREAD

**Issue by Interacy** [airbnb/lottie-web#1516]
I Exportet the Animation with Tumult Hype and when I testet it with the HTML Validator i got that error. 
How can I fix that?

![bildschirmfoto 2019-02-25 um 12 18 23](https://user-images.githubusercontent.com/25814516/53336984-55932280-3900-11e9-9959-33f88202ca53.png)

**Comment by bodymovin** [comment]
Apparently you cannot target the cdn version of lottie.
You should try replacing that file with a relative version.

**Comment by Interacy** [comment]
I did a banner ad some time ago, for doubleclick, I think, and I was able to use the CDN. 

Would it work if the script was hosted in Google's CDN?

I saw that Greensock is supported: https://support.google.com/richmedia/answer/6307288

Maybe we could create a feature request?

**Comment by bodymovin** [comment]
Yes, I think people would be interested in having lottie supported by Studio for rich media ads.
