### ISSUE TITLE
Bodymovin export hangs on image export

### ISSUE THREAD

**Issue by Sabinnie** [airbnb/lottie-web#1517]
**Tell us about your environment**
Windows 10, Bodymovin Version: 5.4.4

* **After Effects Version:**
After Effects CC 2019 - 16.0.1

I've had to trash my AE preferences a few days ago and have been trying to re-export an animation with bodymovin that I had already exported previously.

Every single export hangs on the image export, AE becomes unresponsive and I can't do anything but force quit. It exports fine if I only have shapes in my animation and delete images.

I've checked to make sure "Allow scripts to Write Files and Access Network" is checked, and have restarted AE multiple times. I also uninstalled and re-installed the latest version of Bodymovin.

What am I missing?

EDIT: I've now tested this in AE 2018 as well. As soon as I add an image (any image) to a blank comp and try to export it with Bodymovin, it hangs and then AE dies.

**Comment by bodymovin** [comment]
Hi, can you try clering your render queue?

**Comment by bodymovin** [comment]
@grychanyukdo what version of AE are you using?

**Comment by grychanyukdo** [comment]
@bodymovin Thanks:) Everything is worked now. We just added these settings.
<img width="641" alt="Знімок екрана 2020-10-02 о 11 50 32" src="https://user-images.githubusercontent.com/34237110/94905588-cbc91500-04a5-11eb-9a80-d38e8f2513d7.png">

**Comment by raview69** [comment]
> queue

thankyou so much, that is help me too
