### ISSUE TITLE
Missing external object. Unable to execute script at line 13.

### ISSUE THREAD

**Issue by POM-Daniel** [airbnb/lottie-web#1518]
Hello, I'm using After Effects CC 2019.1(16.0.1) and Bodymovin 5.4.4.

When I open the plugin window in AE, there are alert boxes who appears:

First: Missing external object
Second: Unable to execute script at line 13.
Third and infinity: Unable to execute script at line 1. Undefined is not an object.

I use After Effects in French but I don't think this change something right?

Thank you in advance for your help.

**Comment by POM-Daniel** [comment]
Maybe that can help:

That was working before I install Animation Composer and Overlord plugins. But after removing these two plugins, it still stay the same errors.

**Comment by bodymovin** [comment]
Hi, not sure what could be going on.
Have you tried uninstalling it and reinstallig again?

**Comment by POM-Daniel** [comment]
Yes I tried but always the same error. My collaborators have the same issue.
I will try to update my Mac and see if that's going better.
