### ISSUE TITLE
Resize box around text

### ISSUE THREAD

**Issue by thillmann** [airbnb/lottie-web#1519]
Hi!

I have a relatively simple animation: a text layer and a box around it. I want to make the animation dynamic so you can replace the text inside that box. However, I'm having issues getting the box to resize accordingly. I've tried using an expression in the AE animation and this kinda worked for the SVG renderer but not for the canvas renderer (which I am using). Is this a known issue with the canvas renderer? I've also tried to check `animation.renderer.elements[0].sourceRectAtTime()` (`elements[0]` is the text layer) and it always returns the same rectangle (0, 0, 100, 100).

Any advise?

Thanks!

**Comment by bodymovin** [comment]
yes, the canvas renderer doesn't support that expression unfortunately.

**Comment by thillmann** [comment]
Will there be support for this in the future?

**Comment by bodymovin** [comment]
Not for now, measuring text layers is not trivial.
