### ISSUE TITLE
Track matte not working with canvas renderer

### ISSUE THREAD

**Issue by bgirschig** [airbnb/lottie-web#1520]
**Environment**
Chrome 72.0.3626.109
After effects 16.0.1

**What did I do?**
- Created a composition with 2 layers:
   - A shape layer with its position property animated
   - A text layer (any other type of layer behaves the same) with the first layer as its track matte
- Exported with bodymovin, with default settings
- Created an html page with the boilerplate code (import lottie, lottie.loadAnimation)
- Tried with svg and canvas renderers

**Expected behaviour**
- Svg and canvas renderers behave in the same manner
- Both renderers work with track mattes

**Actual behaviour**
- The svg renderer works
![image](https://user-images.githubusercontent.com/6248734/53687011-3b59aa00-3d2f-11e9-85c3-54996c323def.png)
- The canvas renderer behaves as if the shape layer was visible and the track matte option not set
![image](https://user-images.githubusercontent.com/6248734/53687003-2846da00-3d2f-11e9-8949-6b84aba55ead.png)

**Example project**
[track_matte_bug.zip](https://github.com/airbnb/lottie-web/files/2922470/track_matte_bug.zip)

**Comment by bodymovin** [comment]
That is correct, track matte is not supported by the canvas renderer
