### ISSUE TITLE
Web Assembly rendering target

### ISSUE THREAD

**Issue by Sandstedt** [airbnb/lottie-web#1522]
Would be interesting to create a web assembly rendering target for Lottie animations on the web. Then we could benefit from great performance and have even more advanced animations. But maybe the overhead of the engine would be too large?

Has there been any discussion about this @bodymovin

**Comment by bodymovin** [comment]
I haven't looked into web assembly that much but it would probably improve performance indeed.
I've been also working on a webGL renderer which should also help to get advanced animations supported.

**Comment by Sandstedt** [comment]
@bodymovin Okay, just wondered. Was experimenting with [a scen with a lot of bitmap graphics](http://stage.fullystudios.se/news/three-houses/) using the canvas render, but it's not that performant unfortunately (but then I'm using 5 parallel scenes on top of each other to make it responsive, so maybe is not helping :P ). But I'll try the WebGL render when there is something working. Let me know if you need some help testing or need any other help.
