### ISSUE TITLE
Does Bodymovin Change 'JSON' Files to 'After Effects JSON' Files?

### ISSUE THREAD

**Issue by CageForster** [airbnb/lottie-web#1523]
After Effects is not reading my JSON files at all, I import it and it has no data in it.  

All the JSON files I save are being replaced with 'After Effects JSON' files.  I'm wondering if it's Bodymovin' that does that?

I changed the default program of my JSON to stop changing them to AEJSON files but the problem is still the same, no data at all when I import a JSON file.  I'm fishing for answers and this plugin is the only one I use that does anything with JSON so I was wondering if anyone has heard of this problem?

And side note, when i import my JSON AE says the file type is a "ImporterDataStream" I have never seen that and I can''t find anything about it in the documentation.  I am expecting it to say JSON right? 

Any help would be appreciated.

Thanks, 
Greg

**Comment by txirrindulari** [comment]
Bodymovin output gives one way exported file. I do not thing this file can be import again inside after effects. I believe you could render/extract the json to svg then reimported into ae, but I do not how.
