### ISSUE TITLE
Updating text every second

### ISSUE THREAD

**Issue by ScarlettCode** [airbnb/lottie-web#1524]
Hi,

I have an animation that works great and then I have a time display that I'm wanting to update every second.

` animation.renderer.elements[6].elements[0].updateDocumentData({
              t: ts.hours + ":" + ts.minutes + ":" + ts.seconds
            },
            0
          );`

I have a callback that calls this every second and it works for the first 4 seconds but then stops working. The callback is still firing so it's something to do with the updateDocumetnData not running after the first few calls

Is there a way to achieve this?

Thanks
Michael

**Comment by bodymovin** [comment]
hi, Is it possible that the duration of the exported animation is only 4 seconds?
If it reached the end, it will not update anymore.

**Comment by ScarlettCode** [comment]
Oooh yes! That makes sense now that you mention it. Is there any way around that other than just making the animation super long?

**Comment by bodymovin** [comment]
can you set the animation to loop?

**Comment by ScarlettCode** [comment]
Looping won't work in this situation. Just made the animation longer. Thanks!
