### ISSUE TITLE
Export images PNG not cropped

### ISSUE THREAD

**Issue by tombolaso** [airbnb/lottie-web#1525]
Hi all, I am working with Bodymovin in After Effect CC 2017 and I have problem with the export of the images.
I am not working with shapes or any type of vector images. I'm working with a Photoshop file using its layers as After Effect's object. I'm doing a character animation, without using any effect/puppet/external or strange plugin. Only position and rotation animations.

I tried different animation on my character, and , I don't know why, same animations has been exported well, others completly crashed After Effect. I can't figure out what is wrong with this becouse as I wrote before I didn't use any strange tools inside AE.

Apart from that, an other issue occurred... some of the animations that I finally got have different atlas export settings. Some images (png atlas, for example legs, arms, head) are cropped other have the full dimension of the After effect project. 

Is there someone who could help me whit this? 

Thanks

Tommaso

(and sorry for english:))

**Comment by bodymovin** [comment]
Hi, can you share the .aep that you're having problems with?
Please also specify which composition is not working and which one is.

**Comment by tombolaso** [comment]
Hej!
I have just solved the issue. It was not a Lottie related problem.... it was just me...
I noticed that the problem was on the import of the PSD file. I dint' import layers keeping the "level dimension" so Lottie was exporting the full frame becouse of this.

Now everything is working fine!

Thanks for support
