### ISSUE TITLE
Rigging characters with deformations

### ISSUE THREAD

**Issue by evertonguilherme** [airbnb/lottie-web#1531]
So I have some characters I'd like to animate with rubbery arms and legs. For other (non web) projects I usually do this by using puppet tool and Duik for IK. Since lottie doesn't support the puppet tool, for this one I started animating the paths to get the deformations, like so: https://www.dropbox.com/s/dqgzoj6irkfc5e9/2.jpg?dl=0

But then I tried to have it rigged by parenting the points in a path with stroke to nulls. To do that I used this script: https://bit.ly/2FhoWyL which modificates AE's "Create Nulls from Paths" making it possible to have nulls on the bezier handles as well. Like this: https://www.dropbox.com/s/qygxjf49w4wdj9w/3.jpg?dl=0

I exported a json file after using this technique and when our engineers tried to use it the arms and legs were not animated.
This is the kind of error we get: iOSLottiePerformanceTest[39947:691135] -[LOTLayer _mapFromJSON:withAssetGroup:withFramerate:]: Warning: group effect not supported: Pseudo/DUIK controller / Controller
2019-03-13 18:25:43.920

So I assumed lottie doesn't support the script I used. But here is the thing: the json file does run properly in bodymovin's preview and even in https://lottiefiles.com/preview
Since it works in lottie preview, is it at all possible that we make this work in our app?

**Comment by bodymovin** [comment]
Hi, unfortunately lottie-ios and lottie-android don't support any type of expressions.
