### ISSUE TITLE
WeChat Mini-Program support

### ISSUE THREAD

**Issue by florianmonfort** [airbnb/lottie-web#1532]
Hi,

We've been playing around with Lottie for our iOS and Android app, and we were wondering if lottie web would support WeChat Mini-Program one day?

We built ours with WePy, and we noticed AirBnB's also has animations:

![image](https://user-images.githubusercontent.com/1446429/54511659-9b398d00-498c-11e9-9efa-c3eaf83be4d1.png)

![image](https://user-images.githubusercontent.com/1446429/54511686-ad1b3000-498c-11e9-8a17-bb4fadf65965.png)

We were wondering if that means Lottie web supports Mini-Programs and if not, what similar framework does AirBnB use for achieving a similar result in MPs?

**Comment by bodymovin** [comment]
Hi, not sure how mini programs works, and it's not in the pipeline to support them.
But if you are looking into it and need some help, let me know.
Closing issue for now.
