### ISSUE TITLE
Playing segments continiously on scroll.

### ISSUE THREAD

**Issue by zkingdesign** [airbnb/lottie-web#1533]
Hi Everyone,

I'll try to explain a bit what I'm trying to do. But unfortunately I cannot share a live demo as the project is under development.

What I'm doing is basically running the animation on scroll. Currently I have separated the animation in 5 segments, on load I run the first segment, disable the scroll event listener, after it's finished I'm pausing it the animation, and waiting for the next scroll event to happen to run the next segment.

What I would like to do is to run the animation continiously, so for example if the scroll event runs two times the animation runs until the 3rd segment.

How would I do this?

I created a codepen with a really simplified version : https://codepen.io/zkingdesign-the/pen/KEevbJ

So if you have a look, if animation not finished and I scroll again it runs the next segment. Here's also a screencast of the codepen demo: https://www.useloom.com/share/9e0a0e3d87d347a9865afa80bd05ba9f

How can I avoid that jump? I couldn't find any documentation regarding this.

Thanks,
Zoltan

**Comment by bodymovin** [comment]
you can adjust the segment by reaching into animation's frame values.
So instead of calling `animItem.playSegments([50, 80], true)`, you can do `animItem.playSegments([animItem.firstFrame + animItem.currentFrame, 80], true)`

**Comment by zkingdesign** [comment]
thanks @bodymovin , animItem.playSegments([animItem.firstFrame + animItem.currentFrame, 80], true) was exactly what I needed!
