### ISSUE TITLE
No play animation, only code 

### ISSUE THREAD

**Issue by LyubovPosvalyuk** [airbnb/lottie-web#1534]
Hello sir or madame,

I have some issue with creating an animation with help Bodymovin.

I use Bodymonin Extensions in Adobe After Effects 2018 and 2018 to make animation.
I select Demo option in Settings and execute Render.
I expect to receive an html file with animation but i received just code that doesn't play in browser.

Here is link to dropbox with file https://www.dropbox.com/s/89pjdfght9sml5g/DemoHW.html?dl=0

Thank you for support

**Comment by bodymovin** [comment]
Hi that's strange. What version of the bodymovin extension are you using?

**Comment by LyubovPosvalyuk** [comment]
hello, 
I took all files from here today morning 
https://airbnb.io/lottie/after-effects/bodymovin-installation.html

**Comment by LyubovPosvalyuk** [comment]
i found the error, thank you for assistance
