### ISSUE TITLE
Bodymovin doesn't export animation. Only empty demo and json with long encrypted code

### ISSUE THREAD

**Issue by margzims** [airbnb/lottie-web#1535]
Hello, 
I'm a graphic designer - branding and identity expertise.
Beginner in After Effects.

I have used MotionBro ready animations for some logo reveal animations and tried to create animated parts for my website (like a header this time).

While exporting the animation using Bodymovin, the result is an empty demo file and JSON file that doesn't work on my WordPress. It is uploading but the result is empty.

When I've opened the JSON file in script editor it shows a very long code. Looks like encrypted.

Is there any way to export it to SVG or html5 or any other format so I could upload it to the WordPress web?

Attached animation .aep file and screenshots. To be honest, any animation I did, gave the same results.
I've read a lot of posts here and other forums but didn't find a solution.

[FILE LINK](https://drive.google.com/open?id=1nb-z1_qFeGcH29FljgtgQi-gRVmExG31) (google drive)

I've checked the demo file using Chrome and Safari 12.0.
After Effects 16.0.1  Build42

![Bodymovin_settings](https://user-images.githubusercontent.com/48723009/54612521-65160f00-4a59-11e9-8729-366196a5a805.png)
![Bodymovin](https://user-images.githubusercontent.com/48723009/54612525-66dfd280-4a59-11e9-826a-c0d67458feeb.png)
![Render_done](https://user-images.githubusercontent.com/48723009/54612526-66dfd280-4a59-11e9-8cdc-a4e38ce3ed94.png)
![Empty_demo_result](https://user-images.githubusercontent.com/48723009/54612528-66dfd280-4a59-11e9-8903-930a802b423d.png)
![Aftereffects_project](https://user-images.githubusercontent.com/48723009/54612530-67786900-4a59-11e9-8677-95947b248634.png)

**Comment by lairebecca** [comment]
I've been having a similar issue. Bodymovin doesn't preview or properly render the animation into the json file. I am trying to use the animation for an iOS app. When I try to display the animation none of my vectors show.

**Comment by margzims** [comment]
@lairebecca did you find any solution for that? So far I've placed the animation as a mp4 on my site but loading time is killing it. Tried to export it and convert to other formats but none of Creative Suite software can change movie to svg. Or I just don't know how yet

**Comment by bodymovin** [comment]
@margzims I checked your animation and it uses features that are not supported by the player.
For example markers and Fast blur effect.
Unfortunately, I don't think there's a workaround for it.

**Comment by bodymovin** [comment]
@lairebecca can you share the .aep?

**Comment by margzims** [comment]
@bodymovin Do you suggest to simplify it by discarding those features? Is there a problem with specific features or using the motion bro plugin? 
I mean I have a few other animations - logo reveals (created using motion bro) so if they won't have listed features they should work though?

**Comment by bodymovin** [comment]
@margzims I don't know that plugin or what features it uses, so I can't help there. But I suggest starting with a simple animation to get the hang of it and then checking supported features here http://airbnb.io/lottie/#/supported-features

**Comment by margzims** [comment]
@bodymovin I see. Of course, that's what I'm going to do. Thanks anyway for support! For me the thread is closed. I hope you can help @lairebecca :)

**Comment by lairebecca** [comment]
> @lairebecca can you share the .aep?

[animation folder.zip](https://github.com/airbnb/lottie-web/files/2988210/animation.folder.zip)

**Comment by bodymovin** [comment]
@lairebecca the problem is in layer: "Shape Layer 2". You are using multiple repeaters and sequential repeaters are not supported.

**Comment by lairebecca** [comment]
> @lairebecca the problem is in layer: "Shape Layer 2". You are using multiple repeaters and sequential repeaters are not supported.

I removed my Shape Layer 2, but my json is still not working right

**Comment by yeubix** [comment]
guys can you help !! i have same problem, i wanna export aep to json with Bodymovin but the file is not working good !! 
[data.zip](https://github.com/airbnb/lottie-web/files/3921890/data.zip)

**Comment by bodymovin** [comment]
@yeubix Hi, have you checked the supported features?
https://airbnb.io/lottie/#/supported-features

**Comment by yeubix** [comment]
no i didnt checked i will thanks.

**Comment by shantanu0923** [comment]
Hi @bodymovin ,
I am trying to export a json file from my animation which is just a sequence of pngs.
But every time I render it, no json file is created. 
Can you help me figure out what the problem is?
![image](https://user-images.githubusercontent.com/21968446/73589660-51538a00-44ff-11ea-98e4-f7ca75fc32cb.png)

**Comment by bodymovin** [comment]
@shantanu0923 hi, what version of bodymovin are you using?
if it's lower than 5.6.3 can you try upgrading?

**Comment by shantanu0923** [comment]
@bodymovin Thanks!
I had v5.6.2.
Now its working!

**Comment by Camper76** [comment]
@bodymovin why when I have rendered the project, then I display a preview on lottiefiles.com the image is broken? thx

**Comment by bodymovin** [comment]
@Camper76 can you ask the lottiefiles team about it? With that info I don't know what could be going on.

**Comment by aia-sophie** [comment]
@bodymovin Hey I have the same (maybe a little different) problem. I try to render my animation (AE 17.1.4) with Bodymovin (v5.7.6) but it only renders the pngs into the json file and not the animation. Maybe you can help me!

<img width="393" alt="Bildschirmfoto 2021-02-03 um 17 27 55" src="https://user-images.githubusercontent.com/67199605/106777317-2ab1bd00-6645-11eb-8981-df0ef073df25.png">

[Uploading Animation_folder.zip…]()

**Comment by bodymovin** [comment]
@aia-sophie hi, it looks like the file wasn't uploaded correctly

**Comment by aia-sophie** [comment]
[Animation_folder.zip](https://github.com/airbnb/lottie-web/files/5937433/Animation_folder.zip)

**Comment by heyabdullah** [comment]
hi, i used a small video part in my .aep file but after export json file. after uploadig .json file it is not showing the video part in https://lottiefiles.com site. What is the problem, anyone sugget me?

**Comment by IHXX95** [comment]
[FullPath.zip](https://github.com/airbnb/lottie-web/files/10133505/FullPath.zip)

@bodymovin 
Hi everyone,
that's my .AEP file of AE and I wanna use on website but output on bodymovin doesn't work,
I changed img.png's location on website and shown, but stick and doesn't move and without any animated,
anyone can help me to solve the problem or give me output to use on website?
