### ISSUE TITLE
Some shapes not rendering

### ISSUE THREAD

**Issue by zkingdesign** [airbnb/lottie-web#1536]
* **Browser and Browser Version:**
* **After Effects Version:**
AE 2019 CC

**What did you expect to happen?**
I expected the same output as in AE preview.

**What actually happened? Please include as much _relevant_ detail as possible.**
The gears are not rendering properly, some of the shapes are completely missing. screenshot: http://prntscr.com/n02ksv . Did I do something wrong or some of the settings that are in AE aren't supported by lottie?

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://we.tl/t-hP8VsxJyxB

**Comment by bodymovin** [comment]
Hi unfortunately 3d elements have very limited support.
Things like lights and extrusion are not supported.
