### ISSUE TITLE
how do you decrease the HTML file size? 

### ISSUE THREAD

**Issue by 123help** [airbnb/lottie-web#1537]
hi, 
I followed this tutorial  
https://www.youtube.com/watch?v=3PbUL3z9bIs
I only test a simple shape layer, text and backgroung in the after effects file

I have a HTML file that is 249KB
and JSON file that is 6KB

google display ads said the file size should be 150KB max
https://support.google.com/displayspecs/answer/187449?hl=en

I'm wondering what I should to do to decrease the file size?
Thank you!

[test.zip](https://github.com/airbnb/lottie-web/files/2985714/test.zip)

**Comment by bodymovin** [comment]
I think they support 150KB max as compressed files, but I'm not sure. Have you tried delivering the html in a zip?

**Comment by 123help** [comment]
okay! thanks for your response! 
I created a new animation and the HTML file is 573KB and the JSON is 329KB
when I zipped both of these files together it is 164KB which is still over the limit, is there any other ways to reduce the file size?

**Comment by 123help** [comment]
okay that makes sense! thanks so much for your help!

**Comment by 123help** [comment]
I have another question, in my after effects I used AI files, and they converted to PNGS
when I tried to upload to google ads I received this error. I have attached the HTML and images file./
thank you!

demo 2.zip - The ad contains an unsupported file type. Please remove or replace any files in the ad that are not one of the following file types, and then try again: .CSS, .JS, .HTML, .GIF, .PNG, .JPEG and .SVG

[demo 2.zip](https://github.com/airbnb/lottie-web/files/2989880/demo.2.zip)

**Comment by bodymovin** [comment]
The images are converted to pngs, so they should be supported.
Maybe they don't allow to include folders in the zip file.
Having said that, if your ai layers are vectors, it's best if you can convert them to shapes in After Effects before exporting by right clicking on then and selecting Convert to Shapes.
They will become vectors that are lighter and scale better.

**Comment by 123help** [comment]
thanks for your help!
I have made one that is all converted to outlines and it worked!

although I would like to figure out how I can make an HTML file  work with pngs on google ads
because eventually I will need to make one that include an image.

so I took out the png images out of the folder and just zipped the all the images with the demo.html file. when I upload it, it had no error messages but the ad was blank.

please let me know anything else I can try!

**Comment by bodymovin** [comment]
on the bodymovin panel, there is an option under the settings to bundle image assets as part of the json file.
Or you can edit manually the .html and replace all `images/[filename]` with `[filename]`

**Comment by 123help** [comment]
thank you, I was able to bundle the images as part of the json and it worked!
I have another question, 
is it possible to add a clicktag using bodymovin? and how would I do that?

**Comment by bodymovin** [comment]
there is no built-in way of doing it.
You need to edit the exported html manually.

**Comment by 123help** [comment]
oh i see, do you know what I need to write in the code? sorry I'm not familiar with coding I haven't found many resources in google, I really appreciate your help!

**Comment by bodymovin** [comment]
Sorry, I don't really know how to implement clickTag. But I guess there must be examples on the web.

**Comment by 123help** [comment]
no worries, thanks for your help though!
I found the solution now, incase anyone needs to do this in the future! this is the code I added

<html xmlns="http://www.w3.org/1999/xhtml">
<meta charset="UTF-8">
<meta name="ad.size" content="width=###,height=###">
<head>
<script> var clickTag = '{{landingPageUrl}}';</script>
...
</head>
<body>
<a href="javascript:window.open(window.clickTag)">
[everything else]
</a>
</body>
</html>

**Comment by 123help** [comment]
hi! I was able to manually add the click tag code in the HTML code and it worked! (when i viewed my HTML file on a browser and clicked on the ad, it opened up the linked website)

so I sent it to someone to upload the ad to a live website but they are having problem with the clicktag link?

this is the feedback I recieved:
"The issue is the lottie library is being overwritten with the <div id="lottie"> element."

They tried changing that div id to lottie1 but it didn't help.

Please let me know if you have any idea on how to fix this!

**Comment by bodymovin** [comment]
can you share your final html to check it out?

**Comment by 123help** [comment]
here is the file, thanks for helping!
[test.zip](https://github.com/airbnb/lottie-web/files/3018238/test.zip)

**Comment by bodymovin** [comment]
I'm not sure what they mean by overwriting the lottie library, but perhaps if you wrap only the `<div id="lottie"></div>` that is inside the html instead of wrapping all the tags, it will solve the problem:
```html
<a href="javascript:window.open(window.clickTag)">
<div id="lottie"></div>
</a>
```

Look for that tag in the middle of the html.  
If you want to copy me in the emails you are exchanging with your client, feel free to do so.
