### ISSUE TITLE
Problem-json works, but can't implement in the app

### ISSUE THREAD

**Issue by bmweugene** [airbnb/lottie-web#1539]
Hey Bodymovin, 
I build the animation (with trim path and gradient stroke) and successfully export json file and demo. It looks all good when I preview in the lottiefile preview page. However, when I delivered to developer to incorporate it into our app, it doesn't work properly. only one frame shows up. I'm not sure which part is wrong. Could you pls advise? Appreciate your help!

I put the .aep file, .json file and code below for your reference. 

 [AE and Json files](https://drive.google.com/drive/folders/1I9wLa-VPCjqmIm2IzidnZQPZZlDB11lx?usp=sharing )
```
override func viewDidAppear(_ animated: Bool) {
       circleAnimation = LOTAnimationView(name: "circleAnimation")
       if circleAnimation != nil {
           circleAnimation?.frame = circleImage.frame
           view.addSubview(circleAnimation!)
           circleAnimation?.play(completion: { (done) in
               self.circleAnimation?.removeFromSuperview()
               self.circleAnimation = nil
           })
       }
   }
```
Here is the preview of my working file. only have key frame on the path. 
<img width="1451" alt="Screen Shot 2019-03-20 at 4 23 12 PM" src="https://user-images.githubusercontent.com/35147370/54720071-8267dd80-4b2c-11e9-809a-f4950662925b.png">

* **After Effects Version:**
Version 16.0.1 (build 48)

**Comment by bmweugene** [comment]
I pasted the code into a google doc again and share in the same link.

**Comment by bmweugene** [comment]
Hey @bodymovin Hernan, could you pls take a minute to look at the code and advise? 
I guess the problem would be with the code, because the json is all good and can be previewed. But not for sure. Thanks in advance!!!

**Comment by bmweugene** [comment]
I use the lottie preview on my iphone, scan the QR code and try to preview the animation, and it just doesn't work! that's weird because it can be perfectly view in browser.

**Comment by bodymovin** [comment]
Hi, if the problem is with native apps, can you post the issue on the lottie-android or lottie-ios repos?

**Comment by bmweugene** [comment]
> Hi, if the problem is with native apps, can you post the issue on the lottie-android or lottie-ios repos?

Thanks for your reply Hernan!
Lucky, I just realized that it's probably the reason that IOS doesn't support the gradient stroke feature. However, Lottie released a new version and it now support this feature! 
[Here's the migration guide for Lottie 3.0.0:](https://github.com/airbnb/lottie-ios/blob/btw/lottie-swift/Documentation/MIGRATING.md).
