### ISSUE TITLE
What all effects supported by lottie?

### ISSUE THREAD

**Issue by AnishGG** [airbnb/lottie-web#1540]
I am trying to export the `write on` effect on a solid layer from after effects to lottie, but it is not getting rendered when rendered via web(svg). Path to `write on`: `effect/generate/write on`. 
Does this mean it is not yet supported? If yes, is it mentioned somewhere in [supported features](https://airbnb.io/lottie/#/supported-features)? I am not able to find it in supported features. 
Please guide me.

I have uploaded the `.json` file in `.txt` format.
[write_on.txt](https://github.com/airbnb/lottie-web/files/2989937/write_on.txt)

**Comment by AnishGG** [comment]
Also, what about all the blur effects? Are those supported yet?
Thanks

**Comment by bodymovin** [comment]
Hi, write on and blur effects are not supported.
Very few effects are suported unfortunately: https://github.com/airbnb/lottie-web/wiki/Effects

**Comment by AnishGG** [comment]
@bodymovin, Thanks for clarification!
Also, when I export a radial gradient fill, the output is always fixed to black and white color. But when I tweak the values inside the `lottie` format file manually, the output changes and I am able to achieve more color stops and different colors also.
Does that mean that `radial gradient fill` is supported but not exported properly via the bodymovin extension?
Thanks

**Comment by bodymovin** [comment]
gradient data is read from the .aep file itself via some regular expressions.
If you save the .aep before exporting, and there are no issues with your OS or AE language, it should export fine.

**Comment by AnishGG** [comment]
Yes, That works ^__^
Thank you for help!

**Comment by AnishGG** [comment]
@bodymovin, 
Some effects like `bezier warp` are not yet supported. But when `bodymovin` plugin is used on such effects, the output `lottie` format file seems to have all the essentials to draw that effect. Does that mean, the output format is specified but the rendering is still in development phase?
I ask this, as I am writing a plugin to export some animation files(in some other format) to `lottie` format. So can I use this format(for effects like `bezier warp`) or should I expect that this format can change over time(till it gets rendered)?

**Comment by bodymovin** [comment]
It should work when it is implemented.
You can use other supported effects as reference
https://github.com/airbnb/lottie-web/wiki/Effects

**Comment by d-korolkov** [comment]
I understand that lottie not supported blur by default but somehow I've export blur effect on shape once. Here is the file: https://lottiefiles.com/share/CJcFtU
This is no integrated png because there is no truck that was on this image and other stuff. Only shapes!

**Comment by bodymovin** [comment]
@d-korolkov hi, since version 5.5.3 gaussian blur effect is suppoted on the svg renderer
https://github.com/airbnb/lottie-web/blob/master/CHANGELOG.md#v-553

**Comment by d-korolkov** [comment]
Thanks for reply, I'm on 5.5.2 and being confused.

Sincerely,
Dmytro Korolkov.
--
Follow me on Facebook <https://www.facebook.com/d.y.korolkov>
Follow me on Linkedin <https://linkedin.com/in/dmytro-korolkov-78b1b2123>
My Skype is d.y.korolkov

**Comment by d-korolkov** [comment]
Oh, great news! I'm still on 5.5.2 and was being confused.

**Comment by saurabh-ramola** [comment]
@bodymovin Hi!
Has support for blur effect been added ?

**Comment by bodymovin** [comment]
@saurabh-ramola gaussian blur effect has been added since version 5.5.3
https://github.com/airbnb/lottie-web/blob/master/History.md#v-553
