### ISSUE TITLE
Bodymovin - json not supported with AdRoll

### ISSUE THREAD

**Issue by joemotion** [airbnb/lottie-web#1541]
**Tell us about your environment**
I did HTML5 animations for a client using bodymovin. I have worked with this client before using bodymovin without any issues. They are using a different ad hosting company (AdRoll) for the HTML5 Ads. It is not accepting the data.json file.

It works perfectly fine when I preview the ad in firefox and it works on other computers as well. Is there a work around to getting the data.json to work on AdRolls library?

this is the error we received:
• Invalid file format(s) found in Zip file: data.json. Remove unsupported file type and adjust as necessary.

After Effects CC 2019

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/24wcb1t2af6tr0u/TriBuild%20folder.zip?dl=0

**Comment by bodymovin** [comment]
Can you try exporting the demo.html that bundles all in a single .html file?

**Comment by joemotion** [comment]
Excellent. I forgot that was in the settings menu. I will send this off and see if it works

**Comment by joemotion** [comment]
That did the trick. Thank you!

**Comment by rubenbravodesign** [comment]
Any chance I can get more clarification on how to exporting as demo.html? Still having issues with AdRoll. Screenshots would be helpful!
