### ISSUE TITLE
Bodymovin<>AE error: unable to execute script at line 1

### ISSUE THREAD

**Issue by Anikaly** [airbnb/lottie-web#1543]
* After effect 2019 16.0.1 Build 48 (in french)
* bodymovin_version 5.5.0

When I open AE, there is this error modal window which appears:
🖥 👀 https://drive.google.com/file/d/1jSVH2v0eacy-m8_FRjcQV00vVfpJtk-2/view?usp=sharing
*first error window*
***unable to execute script at line 1.
The file or folder doesn't exist.*** 
🖥 👀 https://drive.google.com/file/d/1qlMWQPMYrQol2hh3tcDHXmem2Rq6r0ut/view?usp=sharing
*second error window*
***unable to execute script at line 1.
Undifined isn't an object.*** 

By clicking ok, the window appear again and again, only possibility is to close the window of bodymovin, but then it's stays unusable.

**I try as follow:**
• restart computer (No amount of restarts have helped.)
• do a new file from 0.
• Interestingly a colleague with an exact same setup has never had a problem getting it to run.
• restart AE 😤
• checking the plugin if the script is on (done) and if there is update
• check AE>Setting Allow scripts (1 time with both checked, 1 time without check either)

**What could be, but where??**
🖥👀 https://drive.google.com/file/d/1xFkma7zbScfI1IHs2l2Jad3ZxyJhJUqV/view?usp=sharing

In the AE presets, I already checked all through, also general>
(check) Allow write scripts and 
(check) allow JavaScript debugging 

I thought it was the solution last time. But it isn't this time.

**Thanks for your help**

**Comment by bodymovin** [comment]
Hi, how did you install the extension?

**Comment by Anikaly** [comment]
Hi Hernan, 

How it’s describe here : 
https://airbnb.io/lottie/#/after-effects?id=installing-bodymovin <https://airbnb.io/lottie/#/after-effects?id=installing-bodymovin>

It was working 10 days ago, and last week out of nowhere not anymore. Getting the error I showed on the GitUb ticket.
https://github.com/airbnb/lottie-web/issues/1543 <https://github.com/airbnb/lottie-web/issues/1543>

I reinstall yesterday the last version of the plugin, still doesn’t work. I could be something on the settings who block Bodymovin, but I have no idea beside this
https://drive.google.com/file/d/1xFkma7zbScfI1IHs2l2Jad3ZxyJhJUqV/view <https://drive.google.com/file/d/1xFkma7zbScfI1IHs2l2Jad3ZxyJhJUqV/view>
Which I try once with checked, and once without, error comes the same…

Do you have an idea where could be somewhere else blocking bodymovin ?

Thanks for you support.


Cheers

Anneline




––

Anneline Cachat, Junior User Experience Designer

AdNovum Informatik AG
Roentgenstrasse 22, 8005 Zurich, Switzerland
phone +41 44 272 6111, direct +41 44 270 5003

anneline.cachat@adnovum.ch

www.adnovum.ch


Locations: Zurich (HQ), Bern, Lausanne, Budapest, Ho Chi Minh City, Singapore

**Comment by bodymovin** [comment]
Hmm not sure what could be going on.
Does your colleague have their AE in French too?
Also, have you tried uninstalling it with zxpInstaller before installing it again?

**Comment by Anikaly** [comment]
Hi

> Also, have you tried uninstalling it with zxpInstaller before installing it again?
> 

Yes

**Comment by bodymovin** [comment]
My guess is it is related to user permissions, but I have never encountered this problem before.

**Comment by Anikaly** [comment]
Where could I change user permissions, cause installation went good, and I could use it.. but then after 3 month it stopped one day out of nowhere…

**Comment by Anikaly** [comment]
Problem fixed, the internet connection was not fast enough which constantly blocked the update of After Effect. Having been able to uncover the problem, this issue has disappeared. 
However, it is possible that the it also could be an  user permissions related issue from some case.

**Comment by williamskalison** [comment]
I resolved this problem by creating a whole new AE comp, copying and pasting all assets into the new comp, and re-rendering with bodymoving from the new comp. No idea why this worked but it did. You cant duplicate he comp- only works if you create new comp with same proportions and copy and paste everything in it. Hope this helps someone..
