### ISSUE TITLE
Plugins not showing never

### ISSUE THREAD

**Issue by tahasami2500** [airbnb/lottie-web#1544]
Hello everyone

I tried to export my project on adobe after effect via bodymovin but when I exported and press preview I got this result

test animation only

![a](https://user-images.githubusercontent.com/24863605/54865558-a5ce9a80-4d6f-11e9-9280-ada45cb18d3d.png)

the result there is no anything inside preview 

![b](https://user-images.githubusercontent.com/24863605/54865559-a5ce9a80-4d6f-11e9-81f2-e6e97cfb8b94.png)

if you want to say not supported yet then how people created that animations on [Lottie Files](https://lottiefiles.com/featured)

**Comment by bodymovin** [comment]
Hi, that effect is not supported by the player
