### ISSUE TITLE
Opacity and Gradient not fulfilled in html demo. 

### ISSUE THREAD

**Issue by alexrober1s** [airbnb/lottie-web#1545]
**Tell us about your environment**

* **Browser and Browser Version:**
Chrome Version 72.0.3626.121 (Official Build) (64-bit)
* **After Effects Version:**
CC 2019

**What did you do? Please explain the steps you took before you encountered the problem.**
I have created a simple 6 solid layer side cube with 80% opacity on every side. 
Every side also has a 4 part gradient effect on. 

**What did you expect to happen?**
I expect the demo in browser to look the same as After Effects playback.

**What actually happened? Please include as much _relevant_ detail as possible.**
Each side is a solid color with no transparency. (Maybe the transparency is there but can't see it because of solid colors)

It is also even worse when loaded into application using Lottie on Android. The box is flattened with every side visible. 

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/o2z2kbh2cqzmcmt/Clearbox.aep?dl=0

**Comment by bodymovin** [comment]
The gradient effect is not supported.
You can try using the gradient property of shape layers that is supported.
Regarding 3d, it is not supported by lottie-ios and lottie-android
