### ISSUE TITLE
Whats meaning with "natively"?

### ISSUE THREAD

**Issue by desmeit** [airbnb/lottie-web#1546]
You write in your description:

"Lottie renders them natively on mobile!"

What is exactly meaning with "natively"? Is it rendering with WebGL or how is it working for a good performance? What is the principal web technology behind behind Bodymovin and Lottie?

I ask because I want to use it with Cordova in a Webview and want to know how good the performance is.

**Comment by bodymovin** [comment]
Natively means you can use 
https://github.com/airbnb/lottie-ios
https://github.com/airbnb/lottie-android

But if you need to use a Webview, it will rely on the canvas or svg renderer, depending on which one you use
