### ISSUE TITLE
v5.5.0 causing assets to disappear or glitch

### ISSUE THREAD

**Issue by jadbox** [airbnb/lottie-web#1548]
Some elements of an animation asset seem to disappear in v5.5.0. It doesn't happen all the time when the page loads... it's intermittent. The assets where exported using bodymovin during the v5.4.4 release.

This is what the user should be seeing:
![19-03-25-12-30_1](https://user-images.githubusercontent.com/595843/54948638-62ecfe00-4efa-11e9-99bc-759e2bc589bf.png)

This is the problem I'm seeing since the update:
![19-03-25-12-30](https://user-images.githubusercontent.com/595843/54948639-62ecfe00-4efa-11e9-9bc2-7a30d16e047d.png)

Config:
```json
{
  loop: true,
  autoplay: true,
  subframeEnabled: false,
  path: 'assets/debate/01_RABIT_IDLE.json',
  rendererSettings: {
    preserveAspectRatio: 'xMidYMid meet'
  }
```

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by jadbox** [comment]
Sooo.. this was a Chrome Beta bug when the GPU drawing acceleration flag was set. Crisis averted!
