### ISSUE TITLE
Difference between Lottie.js and Bodymovin.js

### ISSUE THREAD

**Issue by herrmanneffe** [airbnb/lottie-web#1551]
Hi,
I am wondering what's the difference between theese two versions? 
Some times I see documentation about bodymovin.js and some times about lottie.js.
They seem to do the same thing but code is different, e.g. "bodymovin.play() turns into lotty.play()".

Can someone explain me why?
Which should I use and when?
Thanks very much!

**Comment by bodymovin** [comment]
Hi, bodymovin was renamed to lottie, they are basically the same library but you should use lottie which is newer

**Comment by herrmanneffe** [comment]
Ah ok! Thank's :)
