### ISSUE TITLE
Is there plan to add collapse transform info for compositions? 

### ISSUE THREAD

**Issue by MichaelSSky** [airbnb/lottie-web#1553]

**Comment by bodymovin** [comment]
Hi, are you referring to collapsing transforms for 3d elements?

**Comment by MichaelSSky** [comment]
That is collapse transform - for compositions and continuous rasterization -  for vector layers. And this feature is not only for 3d layers. I really need this flag for the stuff I am doing with BM data  ))

**Comment by bodymovin** [comment]
What is your sue case?
For vector layers, using svg it should work as continous rasterization works.
For 3d layers, the only case supported for now is Collapsed Transforms "on"

**Comment by MichaelSSky** [comment]
My use case is that I use custom backend (not lottie) to parse and render you BM files. And I need this prop to make decision on collapsed/non collapsed , cont. raster/or not.

**Comment by bodymovin** [comment]
for now that property is not exported by the extension.
You can add a request on the repository to support it.
https://github.com/bodymovin/bodymovin-extension
