### ISSUE TITLE
My JSON file loads locally in the browser using MAMP but not on my Wordpress site

### ISSUE THREAD

**Issue by motionvideosuk** [airbnb/lottie-web#1554]
I'm new to this site and have some very basic coding knowledge but I've been scratching my head for days trying to get a simple animation to work on my site using the Bodymovin plugin for After Effects.

 iMac Pro (2017)
Safari Version 12.0.3 (14606.4.5)
After Effects 2019 16.0.1 (Build 48)
WordPress 4.9.6 running Norebro Child theme.

**What did you do? Please explain the steps you took before you encountered the problem.**

After a lot of searching and testing I found this tutorial the most helpful at getting my file to at least load locally - https://www.youtube.com/watch?v=FYOOucjdnkY

But when I change the local paths in the HTML file to those on my server, nothing loads

My test file:
https://motionvideos.uk/bodymovin/test.json

My player file:
https://motionvideos.uk/bodymovin/lottie.json

**What did you expect to happen?**

The animation is nothing fancy at the moment, just a simple red spinning star while I test it out.

**What actually happened? Please include as much _relevant_ detail as possible.**
I've tried the WP Bodymovin plugin for Wordpress but the file does not preview.
I thought that maybe SVG's don't work on my site as I couldn't upload one to the media library.
I installed 'SVG Support' plugin for Wordpress and was able to upload a static SVG file, but still having no luck with my Bodymovin files or the WP Bodymovin plugin.

**Please provide a download link to the After Effects file that demonstrates the problem.**

Download my files here if it'll help:
https://www.dropbox.com/s/zy4a9oo75ga35d4/Bodymovin.zip?dl=0

Really hoping someone can help me.

Thank you,
Scott.

**Comment by zkingdesign** [comment]
Hi @motionvideosuk 

I'm also using lottie in a wordpress project and it loads as it should, I presume that that you didn't setup the json and image paths correctly and that's causing you issues.

Here's how I load my lottie animation

`params: {
                    container: document.getElementById('lottie'),
                    renderer: 'svg',
                    loop: false,
                    autoplay: false,
                    path: ANYTHING.themeUrl + '/assets/js/vendors/animation-data.json',
                    assetsPath: ANYTHING.animationImages,
                    autoloadSegments: true,
                    // goToAndStop: 3,

                    rendererSettings: {
                        // context: canvasContext, // the canvas context
                        scaleMode: 'noScale',
                        clearCanvas: false,
                        progressiveLoad: false, // Boolean, only svg renderer, loads dom elements when needed. Might speed up initialization for large number of elements.
                        hideOnTransparent: true, //Boolean, only svg renderer, hides elements when opacity reaches 0 (defaults to true)
                    }
                },

anim = lottie.loadAnimation(this.params);`

functions.php
`
wp_enqueue_script('app', get_stylesheet_directory_uri() . '/assets/js/app.js', '', '', false);

$array = [
		'homeUrl' => home_url('/'),
		'ajaxurl' => admin_url('admin-ajax.php'),
		'themeUrl' => get_stylesheet_directory_uri(),
		'animationImages' => get_stylesheet_directory_uri() . '/assets/img/animation/',
	];

wp_localize_script('app', 'ANYTHING', $array);
`

**Comment by motionvideosuk** [comment]
So is the top part what you would paste into your Wordpress page/post?

**Comment by zkingdesign** [comment]
You shouldn't add inline scripts to your pages, because you'll end up with a mess, create a new js file, and put all your script inits in there.

**Comment by motionvideosuk** [comment]
FYI, I found the solution to all my problems here - https://www.battleaxe.co/rh2-bodymovin

Thank you though :)

**Comment by motionvideosuk** [comment]
If anybody can tell me how to get these three moving stars to appear next to each other instead of below each other that would be ace :)

https://motionvideos.uk/bodymovin-test/

**Comment by zkingdesign** [comment]
That's a css issue, you should float your svg's or use display flex on it's container..
