### ISSUE TITLE
 i am uploading json file it's working  in the animation page but i am copy the  link in new page 

### ISSUE THREAD

**Issue by NarenTI** [airbnb/lottie-web#1556]
Hi while i am uploading json file it's working  in the animation page but i am copy the  link in new page 
bodymovin anim_id="320" loop="true" autoplay_viewport="true" align="left"]
it's not working.can you help me?Ty﻿

**Comment by bodymovin** [comment]
Hi, not sure I understand what is going on.
Can you share a link with the issue?

**Comment by NarenTI** [comment]
[Files.zip](https://github.com/airbnb/lottie-web/files/3037398/Files.zip)
Hi can you check this one. Thank you






``

**Comment by bodymovin** [comment]
Can you share a link instead of the files?
