### ISSUE TITLE
Animation size may change in Safari

### ISSUE THREAD

**Issue by FishBooy** [airbnb/lottie-web#1557]
**Environment**
**macOS  Safari version:12.0.2**

**What did I do?**
note: the `$container` is not specified with width and height.
`
loadingAnimation = lottie.loadAnimation({
    container: $container,
    renderer: 'svg',
    loop: true,
    autoplay: false,
    animationData: globeData
});
loadingAnimation.playSegments([[0, 1688], [104, 1688]], true);
`

**What is expected to happen?**
The animation size should be consistent in all browsers.

**What actually happened?**
When the animation appears in Safari, it's much smaller than in the other browsers by accident.
Such as:
The size is specified with `{..."w":725,"h":443...}` in .json data, then the animation will show a size with 725width and 443height in Chrome or Firefox etc, however, when in Safari it will be likely to appear with a size 300width and 187height.

**And more...**
Why the `data_ready` event can not be triggered? I add the event listener to the animation instance after the `lottie.loadAnimation({configObj})`, but it's not triggered. It seems that the `data_ready` is triggered before it is added by `addEventlistener`.

**Comment by bodymovin** [comment]
Hi, can you share a link with the issue?
