### ISSUE TITLE
Help Wanted: Rendering Fractal Noise and Bend Tool to Bodymovin

### ISSUE THREAD

**Issue by itsai0724** [airbnb/lottie-web#1559]
Hi,

I'm trying to render an AE cloud animation made with fractal noise and some tree animations that use the bend tool to sway back and forth to Bodymovin but I can't get it to work. 
Any help would be appreciated.

Thanks,
Isabelle

**Comment by bodymovin** [comment]
Hi, fractal noise and bend tool are not supported.
There are very few rasterized effects that are supported unfortunately.
https://github.com/airbnb/lottie-web/wiki/Effects
