### ISSUE TITLE
HTML Jitters: Render issues with demo.html just plays good in json built-in player. Why?

### ISSUE THREAD

**Issue by akhilkomath** [airbnb/lottie-web#1560]
I have been working on an animation to be exported to JSON format. The json file works well in the built-in body movin player but the demo.html has not been rendered properly. Would like to know if the JSON file will show the same issue  after being coded into the product screens.

Played demo.html in chrome. Please find the file here: [demo.html](https://drive.google.com/open?id=1osK54P-2hPllgGbdNaY0xXpryVIuyJzG)

Please find the JSON file here: [File.json](https://drive.google.com/open?id=1RleXbtn144ASa1q4UBkgMit1T0sHNZvw)

**Comment by bodymovin** [comment]
Hi, that first link doesn't seem to point to an html.
Can you share the .html again?
