### ISSUE TITLE
Json Keyfame issue

### ISSUE THREAD

**Issue by binsprout05** [airbnb/lottie-web#1561]
Environment: Mac OS High Sierra 10.14.4

AE CC 2019

I created a very simple scaling animation with 3 keyframes. It works perfectly in demo.html but the json file when running it in Expo or Lottie Cloud player shows up as blank and returns the error

java.lang.IllegalStateException: Missing values for keyframe.

Previously I've done animations with bodymovin but the error did not occur. Using previous jsons done in the past worked but when exporting new jsons with bodymovin with older AEP files (which json worked), the error comes up again.

Uploaded
HTML, Json and AEP file. 

[Error.zip](https://github.com/airbnb/lottie-web/files/3054130/Error.zip)

Thank you so much!

**Comment by bodymovin** [comment]
Hi, if you have updated the extension to version 5.5, you need to update players as well. There is a new json format that needs the latest players.
If you don't want to update, you can select in advanced mode to export as the old formal.

**Comment by binsprout05** [comment]
Hi 

Thank you so much!

Finally got it to work again :)

Sorry but may I know if theres a guide on how to update the player?

Thanks!

**Comment by llx547305571** [comment]
> Hi, if you have updated the extension to version 5.5, you need to update players as well. There is a new json format that needs the latest players.
> If you don't want to update, you can select in advanced mode to export as the old format.

sorry,i just still don't understand how to do it.I am using lottie-android 2.7.0  because my project didn't migrate to androidx.I stiil have some questions about the solutions you said.
1.How to update the player with using 2.7.0 version?
2.Or how to export as the old format?Is it the option in AE?

**Comment by binsprout05** [comment]
Hi

> > Hi, if you have updated the extension to version 5.5, you need to update players as well. There is a new json format that needs the latest players.
> > If you don't want to update, you can select in advanced mode to export as the old format.
> 
> sorry,i just still don't understand how to do it.I am using lottie-android 2.7.0 because my project didn't migrate to androidx.I stiil have some questions about the solutions you said.
> 1.How to update the player with using 2.7.0 version?
> 2.Or how to export as the old format?Is it the option in AE?

Hi,

Just wanted to share how i got around this problem. Theres an additional settings in the bodymovin' plugin before u render that u can select (Settings > Advanced > Export Old Json Format) and then it worked for me!

**Comment by llx547305571** [comment]
> Hi
> 
> > > Hi, if you have updated the extension to version 5.5, you need to update players as well. There is a new json format that needs the latest players.
> > > If you don't want to update, you can select in advanced mode to export as the old format.
> > 
> > 
> > sorry,i just still don't understand how to do it.I am using lottie-android 2.7.0 because my project didn't migrate to androidx.I stiil have some questions about the solutions you said.
> > 1.How to update the player with using 2.7.0 version?
> > 2.Or how to export as the old format?Is it the option in AE?
> 
> Hi,
> 
> Just wanted to share how i got around this problem. Theres an additional settings in the bodymovin' plugin before u render that u can select (Settings > Advanced > Export Old Json Format) and then it worked for me!

thanks for sharing. That is very helpful.

**Comment by ganeshpadhayay** [comment]
@llx547305571 
Hi,
How did you solve this in Android? I am having the same issue
Can't migrate to 3.0 as my project is not on AndroidX.
Please share your solution here.
Thanks

**Comment by llx547305571** [comment]
> @llx547305571
> Hi,
> How did you solve this in Android? I am having the same issue
> Can't migrate to 3.0 as my project is not on AndroidX.
> Please share your solution here.
> Thanks

I downloaded the 5.3.4-version bodymovin plugin and it worked.
You may check the commit record to get the older version plugin.

**Comment by pagrawal1407** [comment]
Hey @ganeshpadhayay @llx547305571 How did you guys solve the plugin issue? Do we need to add some library in android build.gradle file to make it work? Where can I find the bodymovin plugin?

**Comment by fadhilmi** [comment]
> Hi, if you have updated the extension to version 5.5, you need to update players as well. There is a new json format that needs the latest players.
> If you don't want to update, you can select in advanced mode to export as the old format.

hi, what extension do i need to upgrade to version 5.5?
