### ISSUE TITLE
Duik -> Lottie animation question

### ISSUE THREAD

**Issue by marcelo15** [airbnb/lottie-web#1562]
Sorry posted in wrong place, please disregard, delete

**Comment by bodymovin** [comment]
Hi, unfortunately, DUIK animations don't work on android because they rely on expressions.

**Comment by marcelo15** [comment]
> Hi, unfortunately, DUIK animations don't work on android because they rely on expressions.

Thanks for taking the time to respond. I figured it out, I had to convert Duik expressions to keyframes.
I also tested the animations on an old KitKat device and it works. Thanks again.
