### ISSUE TITLE
Bodymovin Rendering Issue

### ISSUE THREAD

**Issue by jacobcxdev** [airbnb/lottie-web#1563]
Hello! I've made a loading animation in After Effects, and it looks great. Unfortunately, I'm running into an issue when rendering using Bodymovin.

I've noticed the issue is with mask expansions - I use them to shrink/expand various shapes in the animation, though Bodymovin doesn't seem to like this. Is there any way to fix this, or if not, are there any alternative ways to get the exact same effect I am producing with the mask expansions? I've spent quite a number of hours learning how to do this so it would be quite disappointing if it was for nothing!

A ZIP archive of my After Effects project, the mp4 produced from normal rendering, and the JSON and demo HTML file produced by Bodymovin can be found [here](https://github.com/airbnb/lottie-web/files/3061567/Archive.zip).

**Comment by jacobcxdev** [comment]
I noticed that “expanded masks” are mentioned here https://github.com/airbnb/lottie-web/wiki/Features.

What does it mean to have svg support but not canvas or html support, in terms of whether it should be renderable by Lottie on iOS?

**Comment by bodymovin** [comment]
Hi, mask expansion and shrinking has a rather hacky solution, so it might not work in your case.
If you can share the .ai I'll try to confim.

**Comment by jacobcxdev** [comment]
Hi, thanks for your reply! The project and .ai can be downloaded [here](https://github.com/airbnb/lottie-web/files/3075269/Archive.zip).

**Comment by jacobcxdev** [comment]
5 days later, I’m still not sure why the solution wouldn’t work.

**Comment by bodymovin** [comment]
I've found a bug that will be uploaded on the next deploy.
But even after that fix, with this solution there are issues on different browsers that will render the animation differently than expected, unfortunately.

**Comment by jacobcxdev** [comment]
Thanks for your reply. I will be using it with Lottie iOS - let’s hope it works fine!

**Comment by jacobcxdev** [comment]
Do you have any idea when the fix will be deployed? I'd just like to know (if possible) when I'd be able to check if the fix works :D

**Comment by jacobcxdev** [comment]
Hello! With Bodymovin version 5.5.2 you appear to have fixed most of the issues, though there's currently still an issue with the first and last transitions. Firstly, the YAK glyph (the key-shaped glyph in the centre) just disappears rather than performing a mask expansion as it should and secondly, the two outer dots should perform similar mask expansions to get smaller. For some reason, these aren't being rendered.

My project remains unchanged from the version attached earlier, though I will provide a demo.html file and mp4 of what it should be [here](https://github.com/airbnb/lottie-web/files/3107204/Archive.zip).

**Comment by jacobcxdev** [comment]
Might I add, sometimes when previewing the rendered json in Bodymovin, if I click on the slider where the transition takes place, it sometimes renders the frame correctly, though it then doesn't play correctly.

**Comment by bodymovin** [comment]
Yes, those are browser related issues that are out of my control unfortunately.
If you resize the window it will probably get fixed as well.

**Comment by jacobcxdev** [comment]
Ah understood. I’ve been running into a plethora of issues when trying to render it using Lottie-iOS - the animation is cropped to only the top left quarter of the entire animation for some reason, mask expansion isn’t displaying.. there’s quite a few. You wouldn’t happen to know what the cause of these might be, or am I better off opening a new issue in the Lottie-iOS repo?

**Comment by bodymovin** [comment]
lottie-ios doesn't have support for mask expansion as far as I know, but yes, it's probably better if you ask in that repository directly.

**Comment by jacobcxdev** [comment]
Hi, do you know of a way I could achieve the same animation using supported features? I'm not much of an AE pro, in fact, this is the first project I've made in AE, so any suggestions would be greatly appreciated.

**Comment by jacobcxdev** [comment]
2 weeks later and nobody’s replied to my issue on the Lottie-iOS repo. Do you know of anyone who might be able to help, other than the maintainer who is clearly ignoring the question? https://github.com/airbnb/lottie-ios/issues/896
