### ISSUE TITLE
Bodymovin font weight

### ISSUE THREAD

**Issue by goddeeris** [airbnb/lottie-web#1564]
If I render text without the glyphs setting it only displays the normal font weight, not in bold. Could you help me out? Thanks!

Settings in Typekit:
![Schermafbeelding 2019-04-10 om 10 16 37](https://user-images.githubusercontent.com/49475270/55863466-db9abe00-5b7a-11e9-92ca-f16e8f2da691.png)

Settings in Bodymovin:
![Schermafbeelding 2019-04-10 om 10 16 51](https://user-images.githubusercontent.com/49475270/55863509-f0775180-5b7a-11e9-97bb-a1074ee3c090.png)

Here is the html export:
https://www.d-artagnan.be/files/demo/demo2.html

Here is the .aep file:
https://www.d-artagnan.be/files/demo/ad_some_fun.aep

**Comment by bodymovin** [comment]
Hi, on the CSS Class field you need to set the class value provided by the typekit library.
In this case, it should be "tk-utopia-std"

**Comment by goddeeris** [comment]
Hi bodymovin, thanks but it still doesn't work :/

![Schermafbeelding 2019-04-11 om 18 33 47](https://user-images.githubusercontent.com/49475270/55974623-5ef60580-5c88-11e9-9149-3e7980f48272.png)

I updated the html export for you:
https://www.d-artagnan.be/files/demo/demo2.html

**Comment by bodymovin** [comment]
it should be on the **CSS Class field** not the **Font Family field**

**Comment by bodymovin** [comment]
it should be on the **CSS Class field** not the **Font Family field**

**Comment by goddeeris** [comment]
Doh! Thanks man! It finally works :-) I should read a tutorial next time ;-)

**Comment by stevenyeo1234** [comment]
hi bodymovin,

for the above issue, after entering "tk-utopia-std" into the CSS Class, how would the below string looks like?

<link rel="stylesheet" href="https://use.typekit.net/qsp4uly.css">

many thanks in advance,
