### ISSUE TITLE
Latest version of Bodymovin (5.5.1) is giving me an error, "Cannot Create AVD" when trying to export

### ISSUE THREAD

**Issue by Jenton** [airbnb/lottie-web#1565]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:** 16.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**
trying to export via bodymovin, and selecting the AVD option

**What did you expect to happen?**
an XML file to be created

**What actually happened? Please include as much _relevant_ detail as possible.**
I saw the 'cannot create AVD' error message.

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by marcelo15** [comment]
Had this happen too. Did u convert your layers to to shapes? Right click layer, Create> Create shapes from vector layers. I normally delete the ai layer once converted

**Comment by bodymovin** [comment]
Yes, a fix is coming in the next deploy.
