### ISSUE TITLE
Having difficulty getting the xml file to repeat when implemented with Android Vector Drawable

### ISSUE THREAD

**Issue by Jenton** [airbnb/lottie-web#1566]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, I think AVDs need to be looped programatically
