### ISSUE TITLE
Exported File Path Clipping

### ISSUE THREAD

**Issue by zfalen** [airbnb/lottie-web#1567]
**Tell us about your environment**
OSX 10.14.4 (18E226)
MacBook Pro (15-inch, 2017)

* **Browser and Browser Version:**
Chrome Version 71.0.3578.80

* **After Effects Version:**
AE Version 71.0.3578.80

**What did you do? Please explain the steps you took before you encountered the problem.**
Animation using shape layers & masking is clipping output file. Screens below:
<img width="404" alt="Screen Shot 2019-04-11 at 10 48 58 AM" src="https://user-images.githubusercontent.com/14879054/55979857-fab35180-5c47-11e9-95ac-248dd0b3322b.png">
<img width="332" alt="Screen Shot 2019-04-11 at 10 48 45 AM" src="https://user-images.githubusercontent.com/14879054/55979858-fab35180-5c47-11e9-9562-e949ee3fcd72.png">
<img width="850" alt="Screen Shot 2019-04-11 at 10 48 25 AM" src="https://user-images.githubusercontent.com/14879054/55979860-fb4be800-5c47-11e9-8e8b-c99f98e8799c.png">
<img width="634" alt="Screen Shot 2019-04-11 at 11 04 37 AM" src="https://user-images.githubusercontent.com/14879054/55980607-a9a45d00-5c49-11e9-9362-6d439fc7f5ad.png">

**Please provide a download link to the After Effects file that demonstrates the problem.**
Happy to send one if you don't have a quick / easy suggestion to address the issue.

**Comment by bodymovin** [comment]
Hi, if you are using strokes, browsers don't handle masking them correctly.
What you can do is add an extra group with a rectangle and a fill with opacity 0 that covers the whole surface of the drawing.
That way, browsers should mask the stroke correctly.
If it doesn't work, you can share the .aep and I can take a look.
