### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by iamattamai** [airbnb/lottie-web#1568]
**Tell us about your environment**
i10 processor, Windows 10, 64 Gig RAM, AE 2019CC

* **Browser and Browser Version:**
Chrome 73
* **After Effects Version:**
2019CC

**What did you do? Please explain the steps you took before you encountered the problem.**
Performing the steps per your instructions and YouTube videos. 
I am trying to render the" Final Output" composition. I checked the 'demo' selection in settings.
I have tried including multiple other compositions in various combinations including all with the same result.
It runs through the whole render, creates the files as expected.
**What did you expect to happen?**
I expected to get an animated SVG
**What actually happened? Please include as much _relevant_ detail as possible.**
Screen blank, Console throwing error: Uncaught TypeError: Cannot read property 'layer' of undefined
**Please provide a download link to the After Effects file that demonstrates the problem.**
https://s3.us-east-2.amazonaws.com/image-store-21/SBYS/Jason.aep

**Comment by iamattamai** [comment]
Now, I just tried selecting the Final Output comp, then in settings, all the other comps related and am now getting: Uncaught TypeError: Cannot read property 'length' of undefined
    at SVGCompElement.BaseRenderer.buildAllItems (demo.html:25) - in the console.

**Comment by bodymovin** [comment]
Hi, unfortunately you are using features that are not supported by the player, like video layers and Underlying Transparency
