### ISSUE TITLE
PlaySegments() not working properly in Vue component

### ISSUE THREAD

**Issue by charlesanim** [airbnb/lottie-web#1569]
`handleAnimation2: function(anim2) {
      this.anim2 = anim2;
      this.anim2.playSegments([[138, 147], [148, 212], [212, 276]], true);
    },`

I have this code in myLottie.vue component, but according to Hernan Torsi, the anim.PlaySegments should play the first two segments and loop on the last segment if the loop parameter is set during initialization.

But its not the case for this. The issue I'm having is the animation is skipping the first two segments and playing the last segment only. 

Is there any way to fix this?

**Comment by bodymovin** [comment]
Hi, are you waiting for the DOMLoaded event before setting the segments?

**Comment by charlesanim** [comment]
Probably not. How do i do this?

Here is the methods
`
methods: {
    handleAnimation0: function(anim0) {
      this.anim0 = anim0;
      this.anim0.playSegments([[0, 74], [74, 138]], true);
    },

    handleAnimation1: function(anim1) {
      this.anim1 = anim1;
      this.anim1.playSegments([74, 138], true);
    },

    handleAnimation2: function(anim2) {
      this.anim2 = anim2;
      this.anim2.playSegments([[138, 147], [148, 212], [212, 276]], true);
    },

    handleAnimation3: function(anim3) {
      this.anim3 = anim3;
      this.anim3.playSegments([[138, 147], [148, 212], [212, 276]], true);
    },

    handleAnimation4: function(anim4) {
      this.anim4 = anim4;
      this.anim4.playSegments([[286, 309], [309, 376]], true);
    },

    changeAnimation: function() {
      console.log("entre");
      switch (this.item.value) {
        case 0:
          this.anim0.playSegments(this.item.segment, this.item.segment, true);
          break;

        case 1:
          break;

        case 2:
          this.anim2.playSegments(
            this.item.segment,
            this.item.segment,
            this.item.segment,
            true
          );
          break;

        case 3:
          this.anim3.playSegments(
            this.item.segment,
            this.item.segment,
            this.item.segment,
            true
          );
          break;

        case 4:
          break;
      }
    }
};
`

**Comment by bodymovin** [comment]
something in the lines of:
```js
this.anim0 = anim0;
this.anim0.addEventListener('DOMLoaded', ()=>{
 this.anim0.playSegments([[0, 74], [74, 138]], true);
})
```

**Comment by charlesanim** [comment]
Yes this works. Thank you!
