### ISSUE TITLE
Bodymovin animation fails

### ISSUE THREAD

**Issue by gauthiergardet** [airbnb/lottie-web#1570]
Hi there,

After creating my .json animation with the bodymovin plugin in after effects, I successfully uploaded it on my webpage as canvas. It works fine but when I leave the page and come back to it, the animation doesn't reload except if I manually reload the page.

Any of you would have an idea on how to solve this ? It's driving me crazy ^^.

here is the page : oninikanabo.fr

**Comment by bodymovin** [comment]
Hi, I just tried it and it doesn't seem to disappear.
What do you mean leave the page? Are you switching tabs or navigating away?

**Comment by gauthiergardet** [comment]
Hi there, 

Thanks for answering.
When you click on the « oni »  logo, you will be redirected to the same page (the home). But the animation doesn’t  show up...

**Comment by bodymovin** [comment]
I see a different container with a new id in that place: `anim-5cb360bc1b718` instead of `anim-5cb3609e1ffc7`, after clicking on the oni logo.
are you targetting that new element to load the animation?

**Comment by gauthiergardet** [comment]
Welle that is conserving the fact that the logo is just a mean to come back to the home page.
How could it bring out another code for the animation ?

**Comment by bodymovin** [comment]
not sure, it seems related to the framework you're using.
You should probably look into that

**Comment by gauthiergardet** [comment]
Well I’m sadly using a wordpress theme that I would like not to change.. Any Ideas on how to eventually force the page to reload each time it’s visited ?

**Comment by bodymovin** [comment]
Not really, maybe you can contact the wordpress theme creator?

**Comment by gauthiergardet** [comment]
I’ll go on and do that. Thanks for your time.

Very bests,

Gauthier

**Comment by bodymovin** [comment]
closing issue, reopen if necessary
