### ISSUE TITLE
Bodymovin rendering issue

### ISSUE THREAD

**Issue by RytisFlair** [airbnb/lottie-web#1571]
After effects 2017

Demo shows nothing after rendering, i rendered hidden comps, external comps aswell
Only effect i used as rubberhose 2, i dont know if this is gradient fill problem, but i didnt use any effects.

https://we.tl/t-W4szd3dh48
These are collected files,
Thanks in advance!

**Comment by bodymovin** [comment]
Hi, it seems to be working on my side.
You don't need to select extra comps, just select hidden and guide layers when exporting.

**Comment by RytisFlair** [comment]
thank you, i thought i had to select the extra comps, stupid mistake from my side :)
