### ISSUE TITLE
Where and how are interpolation values calculated?

### ISSUE THREAD

**Issue by AnishGG** [airbnb/lottie-web#1572]
I am learning as how are the interpolation tangents calculated, given some raw points. Consider I have [star layer](https://github.com/airbnb/lottie-web/blob/master/docs/json/shapes/star.json), and I am varying it's outer radius over time. So according to the star layer documentation([link](https://github.com/airbnb/lottie-web/blob/master/docs/json/shapes/star.json)), at every keyframe, a key `"i"` and `"o"` will be calculated([link](https://github.com/airbnb/lottie-web/blob/master/docs/json/properties/valueKeyframe.json)). 

Now my question is where in the code are these values calculated?
It would be much appreciated if someone could explain how these values are calculated or whether these values are constant.
Thanks in Advance! ^__^

**Comment by AnishGG** [comment]
Also the keys `"i"` and `"o"` are dictionaries both consisting of `"x"` and `"y"`. What is `"x"` and `"y"` actually representing?
Does `"x"` represent the time axis and `"y"` represent the progress of animation with time?(similar to http://cubic-bezier.com)
@bodymovin, It would be of much help if you could take a look at this.
Thank you!

**Comment by bodymovin** [comment]
Here is where the star is converted to a regular path
https://github.com/airbnb/lottie-web/blob/98ff0e3094d7d3f595b815fe2d5063d37ee19f18/player/js/utils/shapes/ShapeProperty.js#L322
hot sure where you a referring to regarding "x" and "y", can you provide more details?

**Comment by AnishGG** [comment]
> hot sure where you a referring to regarding "x" and "y", can you provide more details?

I meant to ask whether the `"x"` and `"y"` in `"i"` is one of the control points of the cubic bezier timing function? 
Here I am attaching the screenshot which might describe it more detailed: 
According to my understanding `"x"` represents `input progress`, `"y"` represents `output progress`. 
![Capture](https://user-images.githubusercontent.com/30872212/56288831-2f8a4180-613d-11e9-9c02-637116d4e02e.PNG)
[Screenshot from [w3.org](https://www.w3.org/TR/css-easing-1/)]

**Also**, are these values(`i` and `o`) calculated by bodymovin plugin or are these fed to the plugin by `.ae` file directly?

**Comment by AnishGG** [comment]
> not sure where you a referring to regarding "x" and "y", can you provide more details?

Have I made my point clear? Or should try to provide more details. 
@bodymovin please have a look at this. ^__^

**Comment by bodymovin** [comment]
What property specifically are you looking at?

**Comment by AnishGG** [comment]
> What property specifically are you looking at?

The outer radius(`or`) property of the star layer. ([link](https://github.com/airbnb/lottie-web/blob/cf1342af04325dce9053690f5f496ca8ccdb745e/docs/json/shapes/star.json#L65))

**Comment by AnishGG** [comment]
@bodymovin any progress regarding this.
Any help would be much appreciated. ^_^
