### ISSUE TITLE
Text layers inside sub-compositions have their text alignment exported incorrectly

### ISSUE THREAD

**Issue by joekim** [airbnb/lottie-web#1576]
**Tell us about your environment**:

After Effects to lottie-web.
lottie-web: 5.5.1

**After Effects Version:** 

16.11 (Build 4)

**What did you do? Please explain the steps you took before you encountered the problem.** 

1. Create a composition that includes a sub-composition.
2. Export composition

**What did you expect to happen?**

- Text alignment is correctly exported.

**What actually happened? Please include as much _relevant_ detail as possible.**

- Text layers that are inside of sub-compositions get exported with the text alignment property switched. Ex: if text layer is left aligned, it gets exported as right aligned.
This is not the case with text layers at the main composition level. 
- This bug seems to be introduced in 5.5.1 specifically.

**Please provide a download link to the After Effects file that demonstrates the problem.**

After effects file:
https://drive.google.com/uc?export=download&id=10vPlSivg1ECWS9M6aT_olD7XMaWJU6cK

Generated JSON:
https://drive.google.com/uc?export=download&id=1-QH1Ug7_ZwWcJpLG5_NMK12SfhyFdsoS

**Comment by bodymovin** [comment]
Hi, there is a fix coming on the next deploy for this.
