### ISSUE TITLE
Bodymovin no longer exporting bounce expression

### ISSUE THREAD

**Issue by Kelthazar** [airbnb/lottie-web#1577]
Using after effects, latest version CC 2019. Bodymovin is currently at 5.5.1

For the past few weeks, Bodymovin has been working flawlessly. Bounce Expression and LoopOut have never given me issues on .JSON exports.

I've had a few animations i've exported in the past, haven't touched the after effects files since then.

Came back to them to re-export for another use (again changed nothing about the file) and now the .JSON files dont load. Tested the load on lottiefiles.com and they dont work there either.

Tried to debug, and after digging around and removing layers one by one, it looks like the issue is the bounce expression on my properties. When i remove the bounce expression, they export as JSON just fine. 

But i dont understand why, because the bounce expressions were working before. I have JSON files of the same animation with bounce expression in them...

Any ideas?

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by Kelthazar** [comment]
Hi! Thank you so much for replying so quickly, I was able to repair it with fresh eyes.

I'm not entirely sure what the problem was that was causing it- but re-exporting a fresh copy of the lottie player fixed the issue.

**Comment by iamnathanmiller** [comment]
Using AE 2020 with the LottieFiles Plugin V 0.1.20
 
I have also noticed the bounce expression is preventing my animations from running as they should.

They are animating correctly on the LottieFiles site, but when used on multiple websites using the embed, everything that has the bounce expression applied to doesn't run or partially runs. 

No previous issues with this and removing the bounce expression resolves the issue. Is there something in the code that is no longer compatible? The current expression used is below.

n = 0;
if (numKeys > 0) {
n = nearestKey(time).index;
if (key(n).time > time){
n--;
}
}
if (n == 0) {
t = 0;
} else {
t = time - key(n).time;
}
if (n > 0 && t < 1){
v = velocityAtTime(key(n).time - thisComp.frameDuration/10);
amp = 20;
freq = 2.0;
decay = 6.0;
value + (v/100)*amp*Math.sin(freq*t*2*Math.PI)/Math.exp(decay*t);
}else{
value;
}
