### ISSUE TITLE
Problem with drop shadow

### ISSUE THREAD

**Issue by Yopich10** [airbnb/lottie-web#1578]
**Tell us about your environment**

Ios & Android

* **Browser and Browser Version:**

Works on the web player, but not on iOS and Android

* **After Effects Version:**

After Effect CC Version 16.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**
I made an animation of cards with drop shadows. I used the effect "drop shadow", that are apparently supported 

**What did you expect to happen?**
I rendered the json and it works on the lottie player but only on the web, not on the ios and android player

**What actually happened? Please include as much _relevant_ detail as possible.**
The animation works perfectly, but the shadows don't appear

**Please provide a download link to the After Effects file that demonstrates the problem.**

[Tabbar.aep.zip](https://github.com/airbnb/lottie-web/files/3093844/Tabbar.aep.zip)
https://lottiefiles.com/share/HjV2K6

**Comment by bodymovin** [comment]
Hi, ios and android players don't support drop shadow unfortunately

**Comment by hdinhof1** [comment]
Looks like individual drop shadows are unsupported but you could try tp add a shadow to your entire view. Make sure `masksToBounds = false`

```
        layer.shadowOffset = CGSize(width: 0, height: 20)
        layer.shadowRadius = 20
        layer.shadowColor = UIColor.black.cgColor
        layer.shadowOpacity = 0.30
        layer.masksToBounds = false
```
