### ISSUE TITLE
Bodymovin only contains frames

### ISSUE THREAD

**Issue by atom22** [airbnb/lottie-web#1579]
Hi,

When I export my animation, the json seems to only contains empty frames but no layers. I couldn't figure out why. One thing to mention is that the animation gets imported to AE from Adobe Animates, don't know if it can be a problem.

[Archive.zip](https://github.com/airbnb/lottie-web/files/3095160/Archive.zip)

**Comment by bodymovin** [comment]
Hi, unfortunately bodymovin doesn't support that type of layers or any kind of video layer.

**Comment by atom22** [comment]
Thank you for the quick answer.
