### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token lottie.js:1 

### ISSUE THREAD

**Issue by squashpotato** [airbnb/lottie-web#1581]
Tell us about your environment
Mac OSX Mojave, Google Chrome 73, CC 2019

JS error:
Uncaught SyntaxError: Invalid or unexpected token
index.js:1 Uncaught ReferenceError: lottie is not defined
    at index.js:1

**Comment by bodymovin** [comment]
Hi, it seems you are not loading the animation library
