### ISSUE TITLE
Trying to work with viewbox settings

### ISSUE THREAD

**Issue by sirharjisingh** [airbnb/lottie-web#1582]
Hey all, 

total noob here, we have a json file we are trying to load as an SVG animation on WebFlow, I have a div element named bodymovin-1, and im loading the SVG inside that div... i wanted the animation to fill the div and also align it left.... I figured out the preserve aspect ration stuff, but i can't figure out where to add the viewbox part, or if thats even the right way to do it... any help here would be amazing

`<script>
var loader = document.getElementsByClassName("bodymovin-1");
function loadBMAnimation(loader) {
 var animation = bodymovin.loadAnimation({
   container: loader,
   renderer: "svg",
   loop: true,
   autoplay: true,
   viewBox: '700 0 2400 590', **is this the correct place to add it?**
   rendererSettings: { 
   	progressiveLoad:false, 
   	preserveAspectRatio: 'xMaxYMax slice' },
   path: "https://gist.githubusercontent.com/sirharjisingh/fe3b442b7eaa3cdf3065a97d10596f3a/raw/6df5406fabf2f14d3c1847ecf110735d00ee7b6c/logo.json"
 });
}

for (var i = 0; i < loader.length; i++) {
 loadBMAnimation(loader[i]);
}
</script>'

**Comment by bodymovin** [comment]
Hi, you should do it inside the rendererSettings property, and the name is `viewBoxSize`
```js
var loader = document.getElementsByClassName("bodymovin-1");
function loadBMAnimation(loader) {
var animation = bodymovin.loadAnimation({
container: loader,
renderer: "svg",
loop: true,
autoplay: true,
rendererSettings: {
progressiveLoad:false,
preserveAspectRatio: 'xMaxYMax slice' ,
viewBoxSize: '700 0 2400 590'},
path: "https://gist.githubusercontent.com/sirharjisingh/fe3b442b7eaa3cdf3065a97d10596f3a/raw/6df5406fabf2f14d3c1847ecf110735d00ee7b6c/logo.json"
});
}

for (var i = 0; i < loader.length; i++) {
loadBMAnimation(loader[i]);
}
```

**Comment by sirharjisingh** [comment]
that didn't seem to work... btw you can see the actual site here..
 https://urban-standard.webflow.io/team/camren-ruecker

**Comment by bodymovin** [comment]
You are using a very old version of the player (v.4.10.2), can you update it to a newer one?
https://cdnjs.com/libraries/bodymovin

**Comment by sirharjisingh** [comment]
which one from that list do i use?

**Comment by bodymovin** [comment]
Depending on your animation and configuration you can use
https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.1/lottie_light.min.js
which is the lightest
if not, use
https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.1/lottie.min.js
that should work with any setup

**Comment by sirharjisingh** [comment]
Damn, not all heros wear capes...

haha, thank you.

**Comment by bodymovin** [comment]
closing, reopen if necessary
