### ISSUE TITLE
I am seeing box outlines when rending and displaying on web

### ISSUE THREAD

**Issue by MataFi** [airbnb/lottie-web#1583]
I am animating a letter from the bottom up out of vector boxes (Facebook Icon) in a bit of an 8-bit theme. It seems to work well when transitioning from AI to AE and allows me to do what I want animation wise. After rendering though and displaying either by a live server in my editor or just the preview in the extension I can see the outlines of boxes. It seems to fix itself when I overlap the shapes but it seems like that's going the wrong way about it and also leaves room for error... Not properly aligned and so forth. If that is the only way is there a possibility to speed this along in AE.

![AE_FB_Icon](https://user-images.githubusercontent.com/49795861/56442538-3345d180-62bf-11e9-8180-67d46a99850a.PNG)

![AE_FB_Icon-boxes](https://user-images.githubusercontent.com/49795861/56442499-01346f80-62bf-11e9-8ace-4fe0433260aa.PNG)

**Comment by bodymovin** [comment]
hi, can you share the .aep/

**Comment by MataFi** [comment]
Of course,

https://1drv.ms/u/s!AkR1TGgZEf_VhyKWWJu4WGHLpVup

**Comment by bodymovin** [comment]
If you play the animation at it's original size or at proportional sizes, there are no gaps between the squares.
Unfortunately, as soon as values need to be rounded, browsers render pixels differently.
Not sure if there is a way to change sizes of shapes easily in AE.

**Comment by MataFi** [comment]
Any suggestions for pursing a different route on this type of animation? I've seen it implemented on an navigation overlay so I thought it was odd that it couldn't work on this size without error.

**Comment by bodymovin** [comment]
I would resize the squares 1 pixel wider or higher, but I can't think of another simpler / better way

**Comment by MataFi** [comment]
Fair enough, I'll do this and report back for anyone else.
