### ISSUE TITLE
Bodymovin - My animations are exporting without animation. Shape layer not showing correctly. 

### ISSUE THREAD

**Issue by k3nji2kid** [airbnb/lottie-web#1584]
Hello admin,

Im using Bodymovin to export animation for my android app, json file, images folder included of course.
But the demo file showing incorrectly and i got nothing moving. 
Here the AE project file im working on it: https://imgur.com/Mc7NisN 

[https://i.imgur.com/77Z5Skq.png
](url)

And here the demo, its not running any animation and the effect im using with Generate/Vegas was not showing correctly. 

[https://i.imgur.com/Mc7NisN.png](url)

Im re-do with a bunch of other file, re-start from the ashes but the result are stay the same. Help me please!

**Comment by bodymovin** [comment]
Hi, can you share the .aep and json files?
