### ISSUE TITLE
Stuck in exporting images

### ISSUE THREAD

**Issue by llllllllr** [airbnb/lottie-web#1585]
Hi,
I've prepared simple AE animation for my object.But when I began to export my animation ,it just stuck on exporting images ,lasting almost 1 hour and have no progress. 
Can you give me some advice？
![image](https://user-images.githubusercontent.com/35605494/56456790-f0a9f500-63a3-11e9-9574-45a32b39576c.png)

**Comment by bodymovin** [comment]
Hi, can you try clearing your AE render queue?
there might some pending processes that prevent the renderer to export images.
