### ISSUE TITLE
Bodymovin exports layers that will never play

### ISSUE THREAD

**Issue by dnfield** [airbnb/lottie-web#1586]
I'm noticing that many of the Lottie files I'm working with seem to have layers exported that will never be played, because the layer's `layer.ip > comp.op`.  Removing these layers from the JSON seems to have no impact on the animation rendering.

Is there some reason to not just have the AE plugin remove these layers at export time?

**Comment by dnfield** [comment]
For example, this file: https://lottiefiles.com/63-hamburger-arrow-transition has 12 layers in it, only 3 of which are actually ever used by the player AFAICT. Removing those layers from the json cuts the file size by almost 2/3rds.

**Comment by bodymovin** [comment]
Yes, bodymovin exports any layers that are beyond the work area for a couple of reasons:
- sometimes those layers are referenced by layers within the workarea (for example parenting or expressions)
- work area can be modified during playback, so you might be interested in keeping additional layers.

And it's probably easy for animators to remove layers or hide them if they don't want them exported, so for now that task is delegated to users.

**Comment by dnfield** [comment]
Thanks for the explanation, that makes sense.
