### ISSUE TITLE
Who can provide a demo to run locally?

### ISSUE THREAD

**Issue by wyfang** [airbnb/lottie-web#1587]
Whether I write it myself or download it directly:
https://codepen.io/airnan/project/editor/ZeNONO

I can't see the animation by opening the html via the chrome browser. So who has a demo that works fine to show me the learning?

**Comment by wyfang** [comment]
![QQ20190423-104546](https://user-images.githubusercontent.com/17900420/56549310-03dfdf00-65b5-11e9-9b77-b5fc9fa537c0.jpg)
![QQ20190423-104603](https://user-images.githubusercontent.com/17900420/56549313-05110c00-65b5-11e9-92eb-49bd47a87d7f.jpg)

**Comment by bodymovin** [comment]
Browsers don't allow loading json files from the file system because of security reasons.
You need to serve them via a web server.

**Comment by wyfang** [comment]
wow! https://wangyifang.com/web/demo/

**Comment by bodymovin** [comment]
closing the issue.
Reopen if needed.
