### ISSUE TITLE
some confusion about goToAndStop

### ISSUE THREAD

**Issue by kimown** [airbnb/lottie-web#1589]
If I want to stop anime at first frame, is't right to use `anime.goToAndStop(0, true)`;

If I want to stop anime at last frame, is't right to use `anime.goToAndStop(anime.totalFrames-1, true)`

https://github.com/airbnb/lottie-web/issues/65#issuecomment-187125893
https://github.com/airbnb/lottie-web/issues/246#issuecomment-279905573
https://github.com/airbnb/lottie-web/issues/917#issuecomment-374873357

**Comment by bodymovin** [comment]
Not sure what your issue is, but perhaps you need to do
`anime.goToAndStop(anime.firstFrame + anime.totalFrames-1, true)`

**Comment by kimown** [comment]
@bodymovin 

I ignore `anime.firstFrame`.  I make a test about AE project, the expression of Source Text is `Math.floor(time/thisComp.frameDuration)`, so I can see current frame number, it seems frames number in AE project start at 0.

Like AE project, the only different is `anime.firstFrame`, in lottie-web:

first frame: anime.goToAndStop(anime.firstFrame + 0, true)
last frame:  anime.goToAndStop(anime.firstFrame + anime.totalFrames-1, true)

**Comment by bodymovin** [comment]
Sorry, I can't understand what is the issue.
From what I gather, your animation starts at frame 0 so firstFrame doesn't make a difference.
is that correct?

**Comment by kimown** [comment]
@bodymovin 

No, I just want to know the range of `value`

From [README](https://github.com/airbnb/lottie-web#gotoandstopvalue-isframe), the first parameter `value ` is `numeric value`, I want to know it's range.

Easeljs start at 0, flash as3 start at 1, so lottie start at 0 or 1?

https://forums.adobe.com/thread/2089670
