### ISSUE TITLE
When I export my After Effects file with Bodymovin it's blank

### ISSUE THREAD

**Issue by JemJem09** [airbnb/lottie-web#1591]
I've downloaded Bodymovin to create an HTML5. When I export using the extension the preview is blank. I have tried it on a couple of different files with no luck. 

I'm very new to all this so any help would be great! File is attached. 

[Uploading MREC.zip…]()

**Comment by bodymovin** [comment]
Hi, that link is not working.
Can you share the aep and the exported json file?

**Comment by Jackmile** [comment]
Hello. I ask for help. I use bodymovine via after effects. So far, everything worked fine until I reinstalled after effects. After that, I could no longer export animation to WordPress. The area is completely white and it does not generate a shortcode at the bottom, the area remains empty. What am I doing wrong ? PLEASE helps me

**Comment by Jackmile** [comment]
Without animation of after effects, I can see on wordpress, but as soon as I create an animation, the area becomes white

**Comment by bodymovin** [comment]
@Jackmile you probably installed the latest version of bodymovin, and the WP plugin is using an older version of the player.
You should try editing the plugin files and update the player.

**Comment by Jackmile** [comment]
First of all, many thanks for the quick response. Can you help me how I can change this or install a current plugin? I would be so grateful to you. Unfortunately, I can not find a current version of bodymovin in WP

**Comment by bodymovin** [comment]
@Jackmile I'm not that familiar with the plugin unfortunately, so I can't help you much more than that.
If you have a link with your current implementation I can try to take a look at the error.

**Comment by Jackmile** [comment]
OK. Nevertheless many thanks. I added 2 more images to show that it does not generate a shortcode when I upload bodymovin with WP. I thank you very much.

**Comment by Jackmile** [comment]
![1](https://user-images.githubusercontent.com/50050948/56852035-070cff00-6916-11e9-91d7-1e64c6884413.JPG)
![2](https://user-images.githubusercontent.com/50050948/56852036-070cff00-6916-11e9-98a0-a21c384670e2.JPG)

**Comment by JemJem09** [comment]
Hi, I have re-attached the aep and json files below!

aep: 
[Google Ads - MREC.aep.zip](https://github.com/airbnb/lottie-web/files/3126407/Google.Ads.-.MREC.aep.zip)

json:
[data.json.zip](https://github.com/airbnb/lottie-web/files/3126417/data.json.zip)

psd file that aep is made from:
[Google Ads - MREC.psd.zip](https://github.com/airbnb/lottie-web/files/3126418/Google.Ads.-.MREC.psd.zip)

**Comment by bodymovin** [comment]
Hi, the layers are imported as image sequences which are not supported by the player.

**Comment by JemJem09** [comment]
Is there anyway to convert these?

**Comment by bodymovin** [comment]
@JemJem09 I don't know if After Effects provides that functionality. I'd google it.
