### ISSUE TITLE
Hold keyframes are not animated correctly

### ISSUE THREAD

**Issue by karip** [airbnb/lottie-web#1592]
I have a Lottie animation with a hold keyframe ("h": 1), which doesn't get animated correctly in version 5.5.0 or later.

Below is the JSON file (created with Keyshape) and an animated GIF showing how it should look like. The stroke width property is animated and there should be a jump before it gets smaller. Lottie.js version 5.4.4 displays the animation correctly with the jump, but lottie.js version 5.5.0 doesn't show it correctly. It ignores the hold value and the jump.

[strokehold.json.zip](https://github.com/airbnb/lottie-web/files/3125087/strokehold.json.zip)

![strokehold](https://user-images.githubusercontent.com/6185066/56865922-28d0b980-69dc-11e9-9e64-35ac56a7f263.gif)

It seems that something has changed between 5.4.4 and 5.5.0. The same issue happens also for other properties with hold keyframes, so this isn't related to stroke width. I tested on Safari, Firefox and Chrome browsers using the SVG renderer.

**Comment by bodymovin** [comment]
Hi, I've been checking the file and it seems to be a wrong implementation on the Keyshape app that worked accidentally with the previous format.
Now that the implementation is better aligned with After Effects model, that case doesn't work anymore.
I suggest that you create two consecutive keyframes that jump from the previous value to the new one to reproduce that effect.

**Comment by karip** [comment]
Thanks for checking the file. I will change Keyshape.

Does it mean that there are no more hold keyframes ("h":1)? The [docs](https://github.com/airbnb/lottie-web/tree/master/docs/json/properties) doesn't mention them, but [lottie.js](https://github.com/airbnb/lottie-web/blob/8feae8774b295bd551b68dbbdc88a9020fba156e/build/player/lottie.js#L2855) seems to do something for them.

Is it ok to create two consecutive keyframes with the same time like this? (two keyframes with different values at "t":10)

    "w": {
        "a": 1,
        "k": [{ "t":  0, "s":[1],  "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]}, "e":[30] },
              { "t": 10, "s":[30], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]}, "e":[15] },
              { "t": 10, "s":[15], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]}, "e":[15] },
              { "t": 20, "s":[15], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]}, "e":[1] },
              { "t": 30 }
      ]
    },

Also, I read somewhere that the keyframe format has been changed slightly. Should the example actually look like this, without end values:

    "w": {
        "a": 1,
        "k": [{ "t":  0, "s":[1],  "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]} },
              { "t": 10, "s":[30], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]} },
              { "t": 10, "s":[15], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]} },
              { "t": 20, "s":[15], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]} },
              { "t": 30, "s":[1] }
        ]
    },

Sorry, but it has been a bit difficult to understand how keyframes work, because the json schema doesn't really describe it. Is the new format documented somewhere? Or should I just try to reverse engineer the [render.zip](https://github.com/airbnb/lottie-ios/issues/564) examples and the lottie.js player (without the [isHold](https://github.com/airbnb/lottie-web/blob/8feae8774b295bd551b68dbbdc88a9020fba156e/build/player/lottie.js#L2855) code)..

**Comment by bodymovin** [comment]
hi, the "h" still works but having an "s" value different than the "e"
value of the previous keyframe was never officially supported even if it
worked before.
In you rexample, for the third keyframe, you should do "t": 10.01 for
example

**Comment by karip** [comment]
Thanks for explaining how those keyframes work. I have modified my example. Is this now correct? The goal is that it uses the new json format without end values.

    "w": {
        "a": 1,
        "k": [{ "t":  0,    "s":[1],  "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]} },
              { "t": 10,    "s":[30], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]} },
              { "t": 10.01, "s":[15], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]} },
              { "t": 20,    "s":[15], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]} },
              { "t": 30,    "s":[1] }
        ]
    },

One downside of using t: 10.01 is that if the renderer happens to sample the animation at 10.005, then it will display a wrong value (22.5 between 30 and 15). The value should jump from 30 to 15, not show intermediate values at all. I may have to use hold keyframes.

**Comment by bodymovin** [comment]
you can add "h": 1 in "t": 10

**Comment by karip** [comment]
I tried this in Lottie 5.5.0 and it worked. However, I have learned that it doesn't mean that it is correct. Could you confirm that the keyframes below are correct? I think that hold keyframes don't need "i" and "o" values.

    "w": {
        "a": 1,
        "k": [{ "t":  0,    "s":[1],  "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]} },
              { "t": 10,    "s":[30], "h":1,
              { "t": 10.01, "s":[15], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]} },
              { "t": 20,    "s":[15], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]} },
              { "t": 30,    "s":[1] }
        ]
    },

**Comment by bodymovin** [comment]
yes, this looks good

**Comment by karip** [comment]
I made changes to Keyshape and hold keyframes now animate correctly in Lottie-web 5.5.0!

I made the third keyframe a hold keyframe to make it a bit more compact.

Also, I decided to include end values to support older players. That way, animations will play in Lottie-web 5.4.4, which is only few months old. Generated data should now be backwards and forwards compatible. I will remove end values later when older players are no longer used. So, data looks like this now:

    "w": {
        "a": 1,
        "k": [{ "t":  0,    "s":[1],  "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]}, "e":[30] },
              { "t": 10,    "s":[30], "h":1 },
              { "t": 10.01, "s":[15], "h":1 },
              { "t": 20,    "s":[15], "i":{"x":[0.833],"y":[0.833]}, "o":{"x":[0.167],"y":[0.167]}, "e":[1] },
              { "t": 30,    "s":[1] }
        ]
    },

Thanks a lot for your help, this solved my issues with hold keyframes!
