### ISSUE TITLE
Can I use polar coordinates?

### ISSUE THREAD

**Issue by Junmo-Yin** [airbnb/lottie-web#1594]
I want to use polar effect in AE, and export to json

**Comment by bodymovin** [comment]
Hi, probably not, but can you share an aep so I can take a look?

**Comment by nukovtun** [comment]
Sorry for interrupting, but I have quite the same question. I need to create animation with radar (smt like on picture attached) and it should be rotated. Previously I've created it in AE via polar coordinates, but it doesn't work after export in json. Then I've tried to create radar in Adobe Illustrator and then rotate it in AE, but it doesn't work too. Maybe you know which technique I can use for it?   
![Radar example](https://user-images.githubusercontent.com/52286526/60447342-ede14100-9c2b-11e9-8b63-c59356165608.PNG)

**Comment by bodymovin** [comment]
@nukovtun Hi, unfortunately I can't think of a way to achieve that.
