### ISSUE TITLE
Motion V2 Plugin no longer supported?

### ISSUE THREAD

**Issue by samcreate** [airbnb/lottie-web#1598]
Windows 10, Chrome: 73.0.3683.103, AE: 16.1.1

Using Motion V2 plugin panel's expressions like "excite" work great in Lottie 5.4.4 but when trying lottie 5.5.2 it doesn't work. 

5.4.4 working test:
https://codepen.io/samcreate/pen/zXgaNz

5.5.2 not working test:
https://codepen.io/samcreate/pen/zXgaZz

**Comment by bodymovin** [comment]
Have you tried re exporting the animation?

**Comment by samcreate** [comment]
Thanks for the quick response. Same animation JSON. The difference in the two examples is the Lottie version. Just curious if motion plugin for ae not working anymore in Lottie is intentional?

**Comment by bodymovin** [comment]
Might be a problem with an old json format. I would try re exporting the animation from AE.

**Comment by samcreate** [comment]
Awww, okay. I'll make sure I have the latest bodymovin plug-in and report
back. Thanks!

**Comment by samcreate** [comment]
That was it. I upgraded bodymovin from aescripts and it fixed it. 

(FYI, for others that may read this... I'm leaving the examples up but the "working" one no longer works with the updated JSON file, but as you will see, works perfect with the latest.)

Thank you for the clarification!
