### ISSUE TITLE
Possible to use demo HTML file but reference the .js build from the same directory?

### ISSUE THREAD

**Issue by Wondershock** [airbnb/lottie-web#1599]
**Tell us about your environment**

* **Browser and Browser Version: Chrome 73.0.3683.103**
* **After Effects Version: CC 15.1.2**

**What did you do? Created a banner using the Bodymovin extension in After Effects.**

**What did you expect to happen? Created a clickable animated banner.**

**What actually happened? Generated the banner, but I'd like the HTML file to be less than 250k.**

https://www.dropbox.com/sh/fh7tvqldtnm76fq/AAA7V6eZZVA4IGPSIS6NZSP3a?dl=0

Here's a link to my project, self-contained banner. I'm trying to figure out how to get the HTML and individual .js under 250k—and I know that the .js is redundant with the code inside of the HTML. Is there any way to call the .js code into the HTML on loading so the HTML is reduced under 250k? And to further reduce the .js to be under 250k individually as well?

Thanks for any insight you can provide on this—I know it's likely an elementary problem, but I'm out of my wheelhouse on figuring this out.

Sincere apologies if this isn't the proper etiquette or place to post.

**Comment by bodymovin** [comment]
Hi, it's probably best if you create your own .html instead of using the exported one.
Maybe you can use this as a reference
https://codepen.io/airnan/project/editor/ZeNONO
