### ISSUE TITLE
Animations render with misaligned text

### ISSUE THREAD

**Issue by JordyBoothy** [airbnb/lottie-web#1600]
**Tell us about your environment**
Windows 10

**Browser and Browser Version:**
Chrome 74.0.3729.131

**After Effects Version:**
After Effects CC 16.1.1

**What did you do? Please explain the steps you took before you encountered the problem.**
I created a layer of text in my After Effects composition (Layer > New > Text) with centre alignment, like this example:

![Screenshot](https://user-images.githubusercontent.com/8039819/57133931-53d05a00-6d9c-11e9-992e-f18b7ecebc9c.png)

I then used Bodymovin to render, with the option to turn text into glyphs selected.

**What did you expect to happen?**
I expected the rendered result to look like it does in the After Effects work area.

**What actually happened? Please include as much _relevant_ detail as possible.**
The text is misaligned, like so:

![Screenshot2](https://user-images.githubusercontent.com/8039819/57134112-f12b8e00-6d9c-11e9-94a1-1d624a3cd7d9.png)

Keep in mind I created this file for demonstration. The problem occurs in my professional projects too. Despite the text being centre-aligned in After Effects, it will always move off-centre after rendering with Bodymovin. 

I checked a similar issue report on Github and the user's problem was right-to-left text direction. In my case, the text direction is left-to-right, but the problem still persists. (Feel free to inspect the AE file and make sure I'm not missing anything)

**Please provide a download link to the After Effects file that demonstrates the problem.**

https://drive.google.com/file/d/1pAg-t4jrtMiS1yQ0SomnP7vENjWsjQFv/view?usp=sharing

Any help with this would be much appreciated!

**Comment by bodymovin** [comment]
Hi, you have some paragraph properties set that are not supported by the plugin.
The "Indent first line" value is set to 15 but it's not taken into account by the player.

**Comment by JordyBoothy** [comment]
> Hi, you have some paragraph properties set that are not supported by the plugin.
> The "Indent first line" value is set to 15 but it's not taken into account by the player.

That fixed it! 

I set the indent value to zero and now it works. Thanks a lot! :)
