### ISSUE TITLE
Hindi language

### ISSUE THREAD

**Issue by RanSlidely** [airbnb/lottie-web#1603]
HI,
I have an error in the Lottie player when trying to used and hindi  language.
 currentChar = documentData.finalText[i];
        charCode = currentChar.charCodeAt(0);

the issue is  the wrong string length
आपका लेख this return a length of 8 but it 6 characters.

If there is any why to fixed it or to work around it

Thanks 
Ran

**Comment by bodymovin** [comment]
hi, cna you share a reduced .aep to test?

**Comment by RanSlidely** [comment]
we change dynamically the text in the JSON before we set the JSON file in the player.
it reproduce in any file. 
I will try to send you a file  for the test ASAP.
Thanks

**Comment by RanSlidely** [comment]
HI,
we create a simple animation with Hindi text.
the issue is the text string in count more characters, it is a js issue.
I think that you should loop differently on the string.
I think that it can happen also in a diffrent language 

[hindi animation.zip](https://github.com/airbnb/lottie-web/files/3177765/hindi.animation.zip)

let me know 
we need this ASAP.

Thanks, 
Ran

**Comment by RanSlidely** [comment]
There is any news?

**Comment by bodymovin** [comment]
Hi, this should be fixed on the last player version.

**Comment by RanSlidely** [comment]
Thanks, I check it and it works if we will have any issues I will let you know.
Thanks for the quick fix.
