### ISSUE TITLE
Multiple Animations - Rendering with elements of another animation

### ISSUE THREAD

**Issue by marco-sebek** [airbnb/lottie-web#1606]
Hi, I'm having a problem, I need to use multiple animations in a website. But one of the animations is glitching and rendering with the objects of another animation. I have different names for every json file, and also diferrent names on my ids. 

<div style="width:100%;height:100%;" id="spaceman"></div>
  <div style="width:100%;height:100%;" id="computer"></div>
  <script src="js/lottie.js"></script>

<script>
        var animations = ['spaceman', 'computer'];
        var i, len = animations.length;
        for (i = 0; i < len; i += 1) {
            var anim;
            var elem = document.getElementById(animations[i])
            var animData = {
                container: elem,
                renderer: 'svg',
                loop: true,
                autoplay: true,
                rendererSettings: {
                    progressiveLoad: true,
                    preserveAspectRatio: 'xMidYMid meet'
                },
                path: animations[i] + '.json'
            };
            anim = lottie.loadAnimation(animData);
            anim.setSubframe(false);
        }
    </script>
Can't figure it out, what I'm doing wrong... :(

**Comment by bodymovin** [comment]
hi, can you share a link with the implementation?

**Comment by marco-sebek** [comment]
Thank you for answering, the website is still on production, I have it on my computer, I don't know if that has something to do with the glitch.
<img width="440" alt="Captura de pantalla 2019-05-07 a la(s) 14 01 14" src="https://user-images.githubusercontent.com/25758721/57328945-628a7a00-70d8-11e9-8b5a-2888c63ee9da.png">
<img width="299" alt="Captura de pantalla 2019-05-07 a la(s) 14 00 56" src="https://user-images.githubusercontent.com/25758721/57328953-64543d80-70d8-11e9-8c82-e7f9e6813cea.png">
<img width="515" alt="Captura de pantalla 2019-05-07 a la(s) 14 00 45" src="https://user-images.githubusercontent.com/25758721/57328957-65856a80-70d8-11e9-9f8b-b8993804c9d2.png">
<img width="398" alt="Captura de pantalla 2019-05-07 a la(s) 14 03 47" src="https://user-images.githubusercontent.com/25758721/57328971-6cac7880-70d8-11e9-8524-bfb858af97fc.png">

**Comment by bodymovin** [comment]
can you upload a reduced version of the issue? perhaps in codepen?

**Comment by marco-sebek** [comment]
Hi the problem was with the assets, when i was exporting the animation it was creating an image folder with png files. The pngs of the second animation were overwriting the pngs from the first animation. I read in another post about converting ai files to shape layers, i hope that will solve my problem. Thank you very much for answering :D
