### ISSUE TITLE
Canvas being placed twice within div

### ISSUE THREAD

**Issue by bridgetguckin** [airbnb/lottie-web#1608]
Hi, so I'm working within Wordpress and uploaded my JSON files via FTP. The animations play no-problem, but I've noticed that within the div that's housing it, there are actually two canvases being placed.

![Screen Shot 2019-05-08 at 12 55 34 PM](https://user-images.githubusercontent.com/19233779/57394407-76df7d00-7193-11e9-8ad4-7d1a6ac581d0.png)

Here's the inspector window showing the extra canvas and the html for the page.

![Screen Shot 2019-05-08 at 12 53 59 PM](https://user-images.githubusercontent.com/19233779/57395123-4862a180-7195-11e9-8ffb-70ee608cd4d7.png)
<img width="621" alt="Screen Shot 2019-05-08 at 12 55 20 PM" src="https://user-images.githubusercontent.com/19233779/57395124-48fb3800-7195-11e9-9050-9bd6d2c2d571.png">

I know the issue is probably caused by something I did, but I'm not sure how to fix it.

**Comment by bodymovin** [comment]
Hi, did you figure it out?
