### ISSUE TITLE
How to export the images with the JSON

### ISSUE THREAD

**Issue by eugenergh** [airbnb/lottie-web#1609]
**Tell us about your environment**

OSX 10.14.1

* **Browser and Browser Version:**
* **After Effects Version:**

After Effects CC2019

**What did you do? Please explain the steps you took before you encountered the problem.**

I have an animation (created in Animate, exported as a SWF and then imported to After Effects). I try to export using Bodymovin and while it exports the JSON it doesn't seem to export any imagery/atlas/spritesheet

How do I get the imagery to export?

**What did you expect to happen?**

I expected Bodymovin to export a JSON file and the required atlas/spritesheet

**What actually happened? Please include as much _relevant_ detail as possible.**

I only get a JSON file

**Please provide a download link to the After Effects file that demonstrates the problem.**

[Archive.zip](https://github.com/airbnb/lottie-web/files/3161020/Archive.zip)

**Comment by bodymovin** [comment]
Hi, swfs are not supported unfortunately because they are video layers in AE.

**Comment by eugenergh** [comment]
Thanks - I figured that might be the case so I got it working with a sequence of PNGs.

IN the end I recreated the animation as vectors for a better result, but good to know I can use a PNG sequence too.

Thanks!

**Comment by ShaneCroke** [comment]
Did you ever figure out how to get the atlas file wit the json? I have the same issue
