### ISSUE TITLE
Images missing when render animation

### ISSUE THREAD

**Issue by vdias38** [airbnb/lottie-web#1610]
**Tell us about your environment**

* **Browser and Browser Version:**
- Chrome v74
- lottie-web 5.5.2

* **After Effects Version:**
- AE 16.1.1
- Bodymovin AE plugin 5.5.2

**What did you do? Please explain the steps you took before you encountered the problem.**
I've exported my animation and test it on demo.html and stackblitz demo. On both demos images are missing. But I can see the request on network activity. 
The [link to stackblitz demo](https://stackblitz.com/edit/mmb-lottie-performance) and [.aep](https://drive.google.com/open?id=1-ZkDqXh4NKRalLORHnO7Wu8Pd05tIkrI) of project (export '04 - Title 67_Render Here' Comp).

**Comment by bodymovin** [comment]
Hi I requested access to the project in Drive

**Comment by bodymovin** [comment]
There seems to be missing files, can you share the full project?

**Comment by vdias38** [comment]
Hi @bodymovin, thanks for your support, and congrats for the plugin. 
The aep file is correct, the only diference with demo is the path of images. On demo.html (directly from bodymovin plugin) images are on local `images` folder  and on stackblitz I use urls and set `assetsPath`. But on both cases images are missing.

**Comment by bodymovin** [comment]
can you share the exported demo.html and images folder?
Also, can you share the files the .aep needs?

**Comment by vdias38** [comment]
find [here](https://drive.google.com/file/d/1NPX2R8L-PihqTCn73IC1196lHxbYAXI9/view?usp=sharing) the zip with all assets used on after effects and bodymovin export demo

**Comment by bodymovin** [comment]
Images are not being loaded in the demo.html because of cross origin issues, but if you serve them through a web server, it should work fine.

**Comment by vdias38** [comment]
I don't think it's due to CORS, on local the browser log it as error but works. You could check on others demo exported from bodymovin, I always observe CORS errors but use to display correctly.
But to be sure I've deployed the animation on [stackblitz](https://stackblitz.com/edit/mmb-lottie-performance) using online images, you can observe the images loaded on network activity but continue hidden on animation.
![mmb-lottie-performance_-_StackBlitz](https://user-images.githubusercontent.com/9011612/57496752-7d254480-72cc-11e9-8c4e-da44afd489a5.png)

**Comment by bodymovin** [comment]
On Your composition "02 - Title 67_Edit Text Here", there is a layer "Shape Layer 6" that has it's blend mode set to "Silhouette Alpha", unfortunately, that blend mode is not supported.

**Comment by vdias38** [comment]
ok, I'll try a workaround, some way to update animation to remove this blending mode. Thanks for the support

**Comment by kudanai** [comment]
Hope this is resolved now. I'm going to close this issue for now. Please re-open if it's still relevant.
