### ISSUE TITLE
Bodymovin and Duik - White Screen 

### ISSUE THREAD

**Issue by marco-sebek** [airbnb/lottie-web#1611]
Hello, I'm new to bodymovin plugin, I read all the issues related to my problem but couldn't found a solution, i deleted all merge paths and group1 from shape layers, I also selected Hidden Layers and Guides. I don't know why my animation is not showing. I made a small preview before and it worked but now it doesn't work... :( 
Is because of the complexity of the animation? I hope you can check my file. Thanks in advance.

[astro prueba animacion_vs6.aep.zip](https://github.com/airbnb/lottie-web/files/3164362/astro.prueba.animacion_vs6.aep.zip)

**Comment by bodymovin** [comment]
Hi, I've found the issues.
I'll try to deploy a new build during the weekend that fixes them.

**Comment by marco-sebek** [comment]
Thank you very much. I very much appreciate your help and time to check the issues related to my problem. :)

**Comment by Jackmile** [comment]
Hello. Is there a solution for this ? When I export from after effects to wordpress, I get only a white area, but demo works. Could you please help me ?

**Comment by AustinEvery** [comment]
@Jackmile I'm getting the same thing.

**Comment by marco-sebek** [comment]
> Hi, I've found the issues.
> I'll try to deploy a new build during the weekend that fixes them.

Thank you very much, the animation is now working
