### ISSUE TITLE
[bug]add Color-related effects will trimming half of the shape's stroke

### ISSUE THREAD

**Issue by Danjuanlab** [airbnb/lottie-web#1612]
I found that when adding some color effects on the shape layer, such as levels individual or fill, Part of the strokes on the demo SVG animation will be cuted off.

![image](https://user-images.githubusercontent.com/42509669/57509063-dc6b6f00-7335-11e9-81a5-7d66690240da.png)

From the rendered HTML source code, these effects are applied to a range of rectangles, and the extent of this rectangle is determined by the shape of the trace to determine the smallest rectangle shape. At this point, the stroke is a stroke in the play, so this range cuts off half of the stroke. To solve this problem, you need to calculate the size of the minimum impact rectangle so that the strokes are all included.

By the way， I have sent you an email about the lottie API. when the project contains images, the introduction of lottie_api will report bugs that cannot be run, hope to get your reply.

[color fill bug.zip](https://github.com/airbnb/lottie-web/files/3165322/color.fill.bug.zip)

**Comment by bodymovin** [comment]
Yes, this is the way filters work on svgs unfortunately.
I usually recommend to manuall create a transparent rectangle the size of the stroke in the same shape, which will fix the problem.

**Comment by Danjuanlab** [comment]
> Yes, this is the way filters work on svgs unfortunately.
> I usually recommend to manuall create a transparent rectangle the size of the stroke in the same shape, which will fix the problem.

Get a new trick

**Comment by bodymovin** [comment]
Sorry, not sure I follow what you mean

**Comment by Danjuanlab** [comment]
> Sorry, not sure I follow what you mean

I mean your method works, this is a trick to make the SVG filter work.
