### ISSUE TITLE
Gradient vectors turn grey when converting to shapes

### ISSUE THREAD

**Issue by christophvanochten** [airbnb/lottie-web#1613]
I've got some issues with **converting vector layers to shapes** in AE.  the reason why I wanted to convert my vector layers to shapes was to minimise my Lottie file size --> so that it would export the layers as SVGs instead of PNGs == faster loading time
 
Whenever I do this action all my gradients + glow-effects are being messed up (see screenshot).. is this a familiar issue and are there some solutions for this?

Thanks in advance

![Screenshot 2019-05-08 at 15 19 33](https://user-images.githubusercontent.com/48795404/57514515-fa72a880-7310-11e9-8c38-3ece86987f89.png)
![Screenshot 2019-05-08 at 15 19 38](https://user-images.githubusercontent.com/48795404/57514516-fa72a880-7310-11e9-8877-da34daa4508b.png)

**Comment by Danjuanlab** [comment]
Converting a vector file into a shape in AE does not support grow, and does not support gradient types other than linear and radial. For example, if you use a grid in AI to do a rich gradient, it is not supported in AE. 

If you want to preserve your current style, you can only keep the layers in the AI file and do not convert them into shape layers in AE. Or remove those features that are not supported and convert them into shape layers.
