### ISSUE TITLE
Playback automatically pauses

### ISSUE THREAD

**Issue by garyjacobs** [airbnb/lottie-web#1621]
Running a macbook pro - V10.14.4
Using Bodymovin - V5.5.2
AE - V16.0.1
Chrome - V74.0
Safari - V12.1

• I exported the data.js file from the Bodymovin extension.
• I then uploaded it to the lottie preview site.
• The animation starts to playback but them stops mid way through.
• You can manually scrub the time bar and the rest of the animation plays as you scrub.

I expected the animation to play from beginning to end but as mentioned above - it hangs.

Things to note:

- When I uploaded it to the lottie preview site and then looked at it on my profile page where I have other thumbnails of previous animations auto playing - they all stop playing at the same point as the problem child animation file.

- Playing it back using the iOS lottie preview app works fine.

Here is the link to the lottie preview file:
https://lottiefiles.com/share/rmeYMC

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by garyjacobs** [comment]
Sure.
https://www.dropbox.com/s/ns02kl6sgtul1fn/Golden%20Poo%20%28converted%29.aep?dl=0

**Comment by bodymovin** [comment]
On the composition "Mouth - Mouth Closing", on layer "Teeth", there are 4 expressions set to Path, Feather, Expansion and Opacity.
Only the one set to path is supported. If you remove the other ones, it should work fine.

**Comment by garyjacobs** [comment]
@bodymovin thanks so much for looking into this one! Really appreciate it!
