### ISSUE TITLE
Render problems: combined shapes with round corners

### ISSUE THREAD

**Issue by rvlt** [airbnb/lottie-web#1624]
**Tell us about your environment**
macOS Mojave 10.14.4

**Browser and Browser Version:**
Chrome Version 74.0.3729.131 (Official Build) (64-bit)

**After Effects Version:**
2018 15.1.2 (build 69)

**What did you do? Please explain the steps you took before you encountered the problem.**
I used a plugin called https://aeux.io/ to send my sketch file into after effects, animated the elements with some keyframes and a basic overshoot expression.

**What did you expect to happen?**
The shapes to render exactly like what i was seeing in after effects

**What actually happened? Please include as much _relevant_ detail as possible.**
The design paths contain rounded corners, these come out squared and worst than that the combined shapes renderered as individual elements.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://rvlt.d.pr/f9t0kN

Sketch file:
![empty-state-no-transactions](https://user-images.githubusercontent.com/10879793/57846153-dbbe5700-77d3-11e9-8c79-cddfa1d06ff2.jpg)

AE file:
![image](https://user-images.githubusercontent.com/10879793/57846181-f1338100-77d3-11e9-9fde-d7510b46afe5.png)

Json file:
![image](https://user-images.githubusercontent.com/10879793/57846305-30fa6880-77d4-11e9-8be9-86bf53d0e2f4.png)

**Comment by rvlt** [comment]
Just found out that merging paths has been a huge issue since earlier versions, is this still the problem?

**Comment by bodymovin** [comment]
Indeed, merge paths are not supported.
