### ISSUE TITLE
mask issues with json

### ISSUE THREAD

**Issue by livkelly** [airbnb/lottie-web#1625]
Hello, 

Everytime I try to render an animation through bodymovin, the masks are either only half working or the entire comp is invisible. 

The animation is a little complicated with moving image inside shape layers (created by masks)

Any help on how to get the shapes to stick as they are with the dots moving within would be SO VERY APPRECIATED 👍 

<img width="519" alt="Screenshot 2019-05-16 at 13 50 39" src="https://user-images.githubusercontent.com/50708011/57861288-34025280-77ee-11e9-9d59-a21ae66fc372.png">

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
