### ISSUE TITLE
3D Camera still showing as an error.

### ISSUE THREAD

**Issue by mitulmehra** [airbnb/lottie-web#1626]
**Tell us about your environment**

* **Browser and Browser Version:**
Chrome version 74 
* **After Effects Version:**
AE Version 15.1

**What did you do? Please explain the steps you took before you encountered the problem.**
We created a composition and used the Bodymovin to render the data.json file.
Then played in Chrome browser using (lottie.js)
We dont want just a simple gif , we want a bit longer video to be worked out as SVG ..20+ seconds. We removed all the 3D camera from our project.

**What did you expect to happen?**
It should work with player on Chrome.

**What actually happened? Please include as much _relevant_ detail as possible.**
We getting 3D camera error. We have removed all the 3D camera from our project.
Attach is the screenshot from the browser errors.
![3D Error](https://user-images.githubusercontent.com/25361318/57933288-7e60fd80-78da-11e9-93e3-8145b20ea694.jpg)

**Please provide a download link to the After Effects file that demonstrates the problem.**
Here is the link for AE file
https://drive.google.com/file/d/1hBADwq-tXOOXeWgGSYxhYKjBvPXF17pg/view?usp=sharing

Request your kind help to remove the 3D camera error.

Warm Regards,
Mitul

**Comment by bodymovin** [comment]
Hi, composition "Frame 04" has a Camera.
I haven't checked the full animation but it seems you are using other unsupported features like gradient ramp.

**Comment by mitulmehra** [comment]
Thanks, Will remove these are try.

**Comment by kudanai** [comment]
Hello. Since this issue has become stale I'm going to close it for now. Please re-open it if it's still relevant.
