### ISSUE TITLE
A 'declare' modifier is required for a top level declaration in a .d.ts file.

### ISSUE THREAD

**Issue by johnsonlin** [airbnb/lottie-web#1627]
**Tell us about your environment**

* **Browser and Browser Version:** N/A
* **After Effects Version:** N/A

**What did you do? Please explain the steps you took before you encountered the problem.**
1. Run `npm build` (using Typescript 2.6.2)
2. Error appears in console. Build failed.

![build-error](https://user-images.githubusercontent.com/1911967/57991965-45e93b80-7af5-11e9-9e79-1d0f83f735ea.png)

**What did you expect to happen?**
Build should pass without errors

**What actually happened? Please include as much _relevant_ detail as possible.**
`index.d.ts` contains error and fails to pass validation
![build-error](https://user-images.githubusercontent.com/1911967/57991842-b6438d00-7af4-11e9-8695-1abe31f4bc7a.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
N/A

**Comment by andrewhosgood** [comment]
Should be fixed here: https://github.com/airbnb/lottie-web/pull/1629
