### ISSUE TITLE
Layers with "path" expression not getting exported

### ISSUE THREAD

**Issue by Merialcaraz** [airbnb/lottie-web#1628]
I have the following expression on some After Effects layers:

thickness = 60
path = thisComp.layer("Driver2").content("Trazado 2").path

When I export the animation with bodymovin, those layers disappear from the animation.

If I change the rendering from svg to canvas it shows the mask of each layer as a shape but it still doesn't work.

Here is the .ae file: https://we.tl/t-286wzAiIML
Thanks!

**Comment by bodymovin** [comment]
hi thanks for reporting it!
I've found the issue. It will be fixed on the next deploy.

**Comment by Merialcaraz** [comment]
Thank you very much!
Do you have an estimated date for the next deploy?

**Comment by bodymovin** [comment]
fixed and deployed in version 5.5.4 :)
