### ISSUE TITLE
White flicker mid animation.

### ISSUE THREAD

**Issue by moshun-design** [airbnb/lottie-web#1635]
I'm experiencing white flash frames mid animation, this is not due to a loop and as far as I can see this is not an issue with my AE project.  I Found another thread on this issue but there was no answer due to lack of AEP.

I've stripped my animation down to something basic so I know there are no unsupported effects etc but I'm still encountering the issue on some but not all browsers. Mozilla plays it back fine but Brave and Chrome both have white flashes. Not ideal as Chrome is most used by my clients.

I'm pretty new to this so my process is. Export from AE using Bodymovin (5.5.3), upload my JSON file to Lottiefiles, copy link to Lottie player, paste code on site. Everything works smoothly except this white flash appearing early on in the process.

Code in action can be found here: https://www.moshun.design/bodymovin

Thanks!

[Bodymovin_Test.zip](https://github.com/airbnb/lottie-android/files/3206930/Bodymovin_Test.zip)

**Comment by moshun-design** [comment]
Thanks for moving it over. Anyone got any suggestions on the issue?

**Comment by bodymovin** [comment]
@moshun-design Hi, I'm looking into it. Apparently it's a Chrome issue, because it doesn't happen in Firefox or Edge.
Will see if I find a workaround.

**Comment by bodymovin** [comment]
I've talked with the Chrome team and a fix is coming on their side soon. It's already fixed in the Chrome Canary release.
