### ISSUE TITLE
Script at line 292

### ISSUE THREAD

**Issue by Heitorfp** [airbnb/lottie-web#1640]
When I try to render an animation in bodymovin 5.5.3 it returns the script error line 292

**Comment by bodymovin** [comment]
Hi, is this issue solved?

**Comment by Heitorfp** [comment]
no

**Comment by bodymovin** [comment]
can you share the .aep?

**Comment by Heitorfp** [comment]
https://we.tl/t-lO8aSVtCT4

**Comment by bodymovin** [comment]
Which one is the composition that is not working?

**Comment by Heitorfp** [comment]
all of them

**Comment by bodymovin** [comment]
I've tried all of them and they seems to work fine.
Is your OS or AE in another language?

**Comment by Heitorfp** [comment]
Português

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
