### ISSUE TITLE
Animation froze after a long time running on Raspberry

### ISSUE THREAD

**Issue by danconte72** [airbnb/lottie-web#1641]
**Tell us about your environment**

* **Browser and Browser Version:**
Chromium 72.0.3626.121 - Raspbian 9.8 (32-bit)
gpu
![image](https://user-images.githubusercontent.com/32454870/58354641-74924980-7e48-11e9-98fb-6e7305fb4f87.png)
flags
![image](https://user-images.githubusercontent.com/32454870/58354648-7fe57500-7e48-11e9-8951-49c4c4c7c9fd.png)

* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**
Tried to play [this animation](https://mmb-lottie-performance.stackblitz.io/) (select Modern - 4 Slides with Glyphs) for a long period (more than 3 hours)
**What did you expect to happen?**
It plays properly
**What actually happened? Please include as much _relevant_ detail as possible.**
- It froze after 30~50minutes playing properly, so we have to reboot the Raspberry.
- We've tested this with another [animation](https://codepen.io/airnan/full/GOvebO) and it not happened even after 4 hours running.
- We did a profile as seen [here](https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/) - Profile [File Here](https://firebasestorage.googleapis.com/v0/b/vongadires.appspot.com/o/4slides2.json?alt=media&token=79257240-b19c-4490-b87b-89da4b0d0e52)

**Please provide a download link to the After Effects file that demonstrates the problem.**
[Theme](https://drive.google.com/file/d/1tfy1bWQo4dk_s4ZYPIcn7R18vWZRcYc2/view?usp=sharing)

**Comment by bodymovin** [comment]
Hi, I can't access the profile file. A quota exceeded issue apparently.
Did you figure out something from profiling it?

**Comment by danconte72** [comment]
Hi! Sorry, now the profile file is able to [download](https://firebasestorage.googleapis.com/v0/b/vongadires.appspot.com/o/4slides2.json?alt=media&token=79257240-b19c-4490-b87b-89da4b0d0e52) again.
We have monitored Raspberry hardware and memory usage grows with time, without any different action on the computer.
![image](https://user-images.githubusercontent.com/32454870/58431278-6bd98780-8083-11e9-97fd-00218ad82dcf.png)

**Comment by bodymovin** [comment]
I've been trying to reproduce this but haven't succeeded.
Can you think of anything in that animation that is different from the other one?
Perhaps masks, trim paths, or something?

**Comment by danconte72** [comment]
I've tested this in another OS on Chromium and freeze/memory leak are not happening anymore. thank you :)
