### ISSUE TITLE
No gradient mask displayed

### ISSUE THREAD

**Issue by velkom** [airbnb/lottie-web#1642]
Exporting an animation with a gradient mask.
Only the mask is displayed, but there is no gradient.

It should be like this:
![image](https://user-images.githubusercontent.com/51087530/58427977-de5d5e00-80a9-11e9-9c8a-a2c6165116ed.png)

It turns out like this:
![image](https://user-images.githubusercontent.com/51087530/58428074-1ebcdc00-80aa-11e9-8bb3-73ad1f6ad0cf.png)

How to fix it? The file is saved before export, it does not help, the layers and file name in English.

My aep:
[computer vision.aep.zip](https://github.com/airbnb/lottie-web/files/3224236/computer.vision.aep.zip)

**Comment by Danjuanlab** [comment]
Although the name of your shape layer is English, the nodes in your layer are Russian. If you want the gradient to work properly, please use the English version of AE and adjust the os Unicode to English.

**Comment by velkom** [comment]
> Although the name of your shape layer is English, the nodes in your layer are Russian. If you want the gradient to work properly, please use the English version of AE and adjust the os Unicode to English.

Thank you very much. I reinstalled the afterter with the English language. I also changed the language from Russian to English on my mac.

In addition, the gradient had to be redrawn. And it all worked, thank you!
