### ISSUE TITLE
All elements not showing in the animation?

### ISSUE THREAD

**Issue by Saksham12345** [airbnb/lottie-web#1643]
**Tell us about your environment**
Office enivronment

* **Browser and Browser Version:**
Google Chrome, latest version
* **After Effects Version:**
2019

**What did you do? Please explain the steps you took before you encountered the problem.**
I created a simple text animation, but one of the alphabet is not showing up in the JSON demo file? 

**What did you expect to happen?**
I expected all elements to be shown, since the effects are same for all alphabets but only 1 is not showing up.

**What actually happened? Please include as much _relevant_ detail as possible.**
I don't really know where the problem is coming from, since all the elements have literally the same animation but only this is not showing, rather i would say this was simplest of em all as this only had straight line animation.

**Please provide a download link to the After Effects file that demonstrates the problem.**
Here is the link to folder on my drive, I've uploaded the JSON, demo and the ae file on it:
https://drive.google.com/drive/folders/15lpo6dw4EOh6Z0gp5umozK5CNCFpPzdk?usp=sharing

**Comment by bodymovin** [comment]
Hi, I've requested access to the folder

**Comment by Saksham12345** [comment]
Hi, I have given the access just now

**Comment by bodymovin** [comment]
What is the composition that is not working?
Also, there seems to be some .ai files missing

**Comment by Saksham12345** [comment]
The first i of the animation and the middle drop (above the heart) are not showing in the demo version of JSON. The ai files that are missing were actually the ones that were converted to shapes in ae, so the ai file was not really needed.

**Comment by Saksham12345** [comment]
actually while trying to find the solution, I was messing with the files, and at that time i converted only some of the ai files to shapes, that's why only a couple are missing

**Comment by bodymovin** [comment]
on Composition "innerchef 5" there are layer sources missing.

**Comment by Saksham12345** [comment]
Sorry I couldn't reply earlier, but thanks for the help, I'll look into it

**Comment by Saksham12345** [comment]
Hi, i still couldn't figure out the problem, also that ae file was very cluttered so I've made the animation again neatly, but still the same issue is coming, the 'i' is not showing in the JSON, even though the final gif outcome is perfect, i am sharing the link to the new ae file and also the json and ai file.
Please have a look at it.
link to drive : 
https://drive.google.com/drive/folders/13qkUX751w-QS8MCXfycMl4rnPXFGvyJA?usp=sharing

**Comment by bodymovin** [comment]
Strokes and masks don't work well on browsers.
Also, stroke effect is not fully supported by the extension.
I'd suggest that you use a shape layer instead of a solid and use a trim path to animate the stroke.

**Comment by Saksham12345** [comment]
Oh ok, I'll try doing that, thanks

**Comment by Saksham12345** [comment]
I tried by making it a seperate element and it worked! But is there any other way around this? cause I use stroke effect alot for animating logos and stuff and JSON seems to be only option for high quality low size gifs.
Anyways it's closed for me, thanks alot!
