### ISSUE TITLE
Unable to execute script file at line 256.

### ISSUE THREAD

**Issue by MatheusDidier27** [airbnb/lottie-web#1644]
* **Browser and Browser Version:**
* **After Effects Version:** CC18

**What did you do? Please explain the steps you took before you encountered the problem.**
Not different than common, i select render and in the final of the render shows Unable to execute script file at line 256. Object in invalid and when i click cancel in the Render sector shows 
Unable to execute script file at line 256
**What did you expect to happen?**
To render like usual 

**Please provide a download link to the After Effects file that demonstrates the problem.**

https://drive.google.com/open?id=1rPvnECgMTAefR5-rVedZ-wMs-p7Ycmfg

**Comment by bodymovin** [comment]
Hi, is this issue solved?
