### ISSUE TITLE
Rotating animation works on Firefox, but not Chrome

### ISSUE THREAD

**Issue by trinidadr** [airbnb/lottie-web#1645]
https://www.weareunmethod.com/test/nrgslider/

I'm having an issue where the windmill animations do not properly spin on Chrome (Version 74.0.3729.169). On Firefox (Version 67.0) it runs smoothly and on track. This happens on my local environment and on the server (link above). I thought it might have to do with the size, scaling, transform values, but doesn't seem to be affected by this at all. 

I can get the versions of AE and bodymovin, but loading the json on https://lottie.cloud/app/ shows the json is working perfectly on all browsers. 

Any more knowledgeable soul that can assist?

**Comment by trinidadr** [comment]
Update: Editor is using AE 2019 and the latest version of bodymovin

**Comment by bodymovin** [comment]
Hi, you have a css selector affecting the transform properties:
https://www.weareunmethod.com/test/nrgslider/css/styles.scss
line 227:
```css
svg g{
	transition: 1.5s;
}
```

**Comment by trinidadr** [comment]
Thanks for the reply @bodymovin  I could swear I tested removing the transition, but you were correct.
