### ISSUE TITLE
Android Studio Color shift

### ISSUE THREAD

**Issue by Gusfavoreto** [airbnb/lottie-web#1647]
MacOs
Safari Version 12.1.1
After Effects 16.1.1

I am doing some simple animations to load on Android. But when I load the JSON file on Android Studio the color are changed, Blue turns red, green turns yellow, red stay red. But is I load on LottieFile website works, and I try to change color there, some elements doesn't change its colors.
I exported as old version.

I am not a developer, I am just a motion guy trying so send some files correct ;) 
Thank you,
Gus
![Screen Shot 2019-05-28 at 3 42 21 PM](https://user-images.githubusercontent.com/35354935/58517193-69e4f680-815f-11e9-93de-eb6337e8ed1d.png)

**Comment by bodymovin** [comment]
Hi, can you share the .aep

**Comment by Gusfavoreto** [comment]
Absolutely!

Thank you!!
[Lottie_color.aep.zip](https://github.com/airbnb/lottie-web/files/3230041/Lottie_color.aep.zip)

**Comment by bodymovin** [comment]
Not really sure what could be going on.
Can you post the issue in the lottie-android repository?

**Comment by Gusfavoreto** [comment]
Weird right?
Thank you for looking into that!

I will post there.
Gus
