### ISSUE TITLE
Resizing issue for Android

### ISSUE THREAD

**Issue by Envelion** [airbnb/lottie-web#1651]
Hi there, 

First off, this technology is amazing, thank you for making it!
I just have one issue.
I exported an animation using PNGs in After Effects to a lottie file and they look great on all of our iOS devices.
However, for some reason on an Android device, there's a lot of white space above the animation that pushes the animation down.
I can't really post a screenshot since the animation is private, unfortunately.

**Comment by bodymovin** [comment]
Hi, is this happening with the lottie-android player?

**Comment by Envelion** [comment]
Hello,

No, this looks fine in the player. We only see the issue in our app and
only on the Android device.

**Comment by bodymovin** [comment]
How is your app implementing the animations? What player are you using?

**Comment by Envelion** [comment]
That's a good question. I'll have to ask my dev team and get back to you on
that Monday. I'm just the asset creator.

**Comment by Envelion** [comment]
Good morning Hernan,

My developers said that we are using "com.airbnb.lottie.LottieAnimationView"

**Comment by bodymovin** [comment]
Ok, so it seems you are using the android player
I suggest that you continue this question over there
https://github.com/airbnb/lottie-android
They'll have a better idea of what might be going on.
