### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: color

### ISSUE THREAD

**Issue by SilencerWeb** [airbnb/lottie-web#1652]
I have 4 lottie animations on the page: 1 of them is 3D (contains PNG images) and 3 of them are vector (fully SVG, no PNG images). They all work on local, but in the production, I get such error: `Uncaught TypeError: Cannot redefine property: color`

Here how the work in the production: 
First of them (3D) works as it supposed to work.
Second and third of them **don't work** at all.
The fourth **works** as it supposed to work too so I guess it isn't because they are vector.

I tried to remove all of them and keep only second or third of them, but it didn't change anything.

But if I'll open them separately right after exporting from After Effects, they work fine.

Here is a demo of this page — https://terraforge.netlify.com/
Here is the repository of the project — https://github.com/SilencerWeb/terraforge
A file with lotties initialization — https://github.com/SilencerWeb/terraforge/blob/master/src/scripts/modules/init-lotties.js

`lottie.js` version is 5.5.3, I downloaded it from here — https://cdnjs.com/libraries/bodymovin.
I tried to check in 3 browsers: Safari, Brave and Chrome, everywhere is the same.

**Comment by bodymovin** [comment]
Hi, very strange issue. Never seen this one.
I've cloned the repository but I don't see the issue in my local environment.
How can I reproduce it locally?

**Comment by SilencerWeb** [comment]
@bodymovin, I'm sorry, I just found out the problem, it doesn't work in the production because of `uglifyjs-webpack-plugin`.

**Comment by malaykeshav** [comment]
@SilencerWeb : I have the exact same issue due to the use of uglifyjs. Can you elaborate on how uglifyjs is triggering this? And how you fixed this?
