### ISSUE TITLE
Lottie is not defined in Electron

### ISSUE THREAD

**Issue by igghera** [airbnb/lottie-web#1653]
I'm trying to use Lottie in my Electron project.

I have managed to make Lottie work in a basic HTML page (no Electron), but when I port the code inside my Electron project, things get weird.

The Lottie library is loaded correctly, I can see it in the Network tab of my devtools.

But every time I try and call `lottie.loadAnimation`, I get `Uncaught ReferenceError: lottie is not defined`.

I tried 100 times making all possible changes and still can't get it to work.

I have reproduced the setup in this pen https://codepen.io/igghera/pen/yWZOQg .
That's exactly the same code in my Electron app. Loading the library from an external source.

I'm missing something stupid, but I can't see it. Please help!

Thanks in advance!

**Comment by bodymovin** [comment]
Hi, without the actual code it's difficult to figure out what is going on, but make sure you are including the js library and your scripts are in the correct order.

**Comment by igghera** [comment]
You're right, sorry. I thought maybe you guys had seen something like this before.
While I was preparing a repo with some code I made one last attempt and I found out I can "require" Lottie in Electron if I install it via npm, and it works. 
Still weird as I can't load it via <script> tag in the index.html file, but I don't have time to investigate further.
Closing the issue, thanks anyway
