### ISSUE TITLE
help to understand Bodymovin-TG

### ISSUE THREAD

**Issue by pashigorov** [airbnb/lottie-web#1654]
Hello friends! Help me run Bodymovin-TG!

I import the composition from PNG files into the after effect, I try to create a sticker via Bodymovin-TG, but nothing happens. It turns out an empty file in 1 kb. what to do ?

**Comment by bodymovin** [comment]
Hi, I suggest that you post this question on that repository
https://github.com/TelegramMessenger/bodymovin-extension

**Comment by SwooshyCueb** [comment]
GitHub forks do not have issue repositories, so it is impossible to post a question on that repository.

That said, I'm not sure the appropriate place is here either.
