### ISSUE TITLE
Merge Paths. Bodymovin-TG

### ISSUE THREAD

**Issue by holydaze** [airbnb/lottie-web#1655]
Hello!
I have a problem with Bodymovin-TG. 
The plugin gives an error "Render Failed! Composition should not include any Merge Paths".
I can't understand how to fix it.
Tell me, please, in what could be the problem?

**Comment by bodymovin** [comment]
Hi, it seems the plugin doesn't support Merge Paths.
I suggest to ask for more info on this repository.
https://github.com/TelegramMessenger/bodymovin-extension
