### ISSUE TITLE
There are no Compositions to render. Make sure you have at least one selected and a Destination Path set.

### ISSUE THREAD

**Issue by annyameow** [airbnb/lottie-web#1657]
Hi, I created a short animation without any effects just changed the parametrs, but bodymovin doesnt see it at all. I checked other files and he writes that there are no compositions.
Using CC 2017 14.01
Tried to make them a precomposed, can't use shapes
Thanks

**Comment by bodymovin** [comment]
Hi, that message shows up when you didn't select a composition to render in the extension panel or didn't chose a folder where to save it.
Can you share a screenshot of the bodymovin panel?

**Comment by annyameow** [comment]
Yeah, of course


>Вторник,  4 июня 2019, 12:30 +03:00 от hernan <notifications@github.com>:
>
>Hi, that message shows up when you didn't select a composition to render in the extension panel or didn't chose a folder where to save it.
>Can you share a screenshot of the bodymovin panel?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

С уважением,
Чакина Анна
chakina10@inbox.ru

**Comment by bodymovin** [comment]
If you attached an image to an email as part of the answer, it won't come through.

**Comment by bodymovin** [comment]
It seems that you haven't selected where to save them.
Try clicking on the three dots (...) and choose a destination.

**Comment by bodymovin** [comment]
And you only need to select the main composition, no need to select precomps in that panel.

**Comment by annyameow** [comment]
Now it start rendering but then write "Composition should not include any Images". But every file is from Illustrator

**Comment by bodymovin** [comment]
Not sure how the Telegram version works.
I suggest that you write to them directly.

**Comment by annyameow** [comment]
Thanks for help and for fast answers, you are the best! Good luck
