### ISSUE TITLE
How can I force my lottie animation to fit to the size of the parent ?

### ISSUE THREAD

**Issue by michaelgrc** [airbnb/lottie-web#1658]
I'm using a .json lottie file for a transition between two pages. So I want my lottie animation to cover the whole screen. How can I force my svg to adapt to the size of my viewport and not preserve its original ratio ? Thank you

**Comment by bodymovin** [comment]
when you load the animation you can pass an object rendererSettings with a property "preserveAspectRatio" that takes the same values as the svg native attribute.
https://github.com/airbnb/lottie-web/wiki/Renderer-Settings

**Comment by michaelgrc** [comment]
Thanks for the answer, unfortunately it seems that the preserveAspectRatio attribute doesn't work with the value "none". Do you know how can I make it work ? Thank you very much.

**Comment by bodymovin** [comment]
if you are using the svg renderer, as a workaround, once the animation is loaded you can change the preserveAspectRatio property manually from the element.

**Comment by michaelgrc** [comment]
This is what I just did. Thank you for your time.
