### ISSUE TITLE
Expression not rendering after ElectronJS Packed

### ISSUE THREAD

**Issue by sundong212** [airbnb/lottie-web#1659]
**Tell us about your environment**

MacOS 10.14, Node 10.15, NPM 6

* **Browser and Browser Version:**

Worked in Chrome but not after packed with ElectronJS

* **After Effects Version:**

AE 2019

**What did you do? Please explain the steps you took before you encountered the problem.**

I am developing a software using ElectronJS with ReactJS, it works fine when I am in development mode. And then I pack a package ready for releasing.

I made a run+hurdle animation. I use duik bassel plugin to animate the body movement. When I animate the foot, I use an expression to allow one foot to follow another foot so I can only animate one foot. However, when I export the Json file by using bodymovin, something went wrong....it seems like the front end engineer cannot export the complete animation. The animation was fine when its in the preview mode....

**What did you expect to happen?**

The expressions should work as the leg should be there.

**What actually happened? Please include as much _relevant_ detail as possible.**

The leg part with the expression disappears.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/drive/folders/1JnM3CKfPP4RfR5x0G_ORXaMhGZKNPihW?usp=sharing

**Comment by bodymovin** [comment]
I've seen this happen before and it's usually related to the minify / uglify plugin you might be using. It seems to minify the plugin incorrectly and the code breaks.
Can you share what tool /plugin you are using?

**Comment by sundong212** [comment]
> I've seen this happen before and it's usually related to the minify / uglify plugin you might be using. It seems to minify the plugin incorrectly and the code breaks.
> Can you share what tool /plugin you are using?

Thank you for your reply!  I am using basically the same configuration in dev and prod mode.

const CopyWebpackPlugin = require('copy-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const extractSass = new ExtractTextPlugin({
    filename: "css/styles.css"
});

module.exports = {
    context: __dirname,
    mode: "production",
    entry: {
        "admin.bundle.js": "./src/js/Admin.js",
        "css/styles.css": "./src/scss/styles.scss"
    },
    output: {
        path: __dirname + "/build",
        filename:"[name]"
    },
    devtool: 'source-map',
    node: {
        __filename: false,
        __dirname: false
    },
    resolve: {
        extensions: ['.js', '.jsx']
    },
    target: "electron-renderer",
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                loader: 'babel-loader',
                exclude: /(node_modules)/,
                query: {
                    // cacheDirectory: true,
                    presets: ['env', 'stage-0', 'react'],
                    plugins: ['transform-decorators-legacy']
                }
            },
            {
                test: /\.scss$/,
                use: extractSass.extract({
                    use: [
                        {loader: "css-loader", options: { url:false, minimize: true }},
                        {loader: "sass-loader"}
                    ],
                    // use style-loader in development
                    fallback: "style-loader"
                })
            }
        ]
    },
    plugins: [
        new CleanWebpackPlugin(['build','release'], {
            root: __dirname,
            verbose: true,
            dry: false //, exclude: ['shared.js']
        }),
        extractSass,
        new CopyWebpackPlugin([
            {context: "src", from: "*"},
            {context: "src", from: "img/**/*"},
            {context: "src", from: "fonts/**/*"},
            {context: "src", from: "video/**/*"},
            {context: "src", from: "audio/**/*"},
            {context: "src", from: "lib/**/*"},
            {context: "src", from: "res/**/*"},
            {context: "src", from: "war/**/*"}, 
        ],{
            ignore: ['*.txt','*.scss','*.less','*.md', 'App.js',"Web.html"],
            copyUnmodified: true
        })
    ],
};

**Comment by bodymovin** [comment]
Is the build getting minified / uglyfied?
If so, can you try building without them?

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
