### ISSUE TITLE
demo.html showing error loading images from exported files. Help???

### ISSUE THREAD

**Issue by kamakamaha** [airbnb/lottie-web#1660]
Hi there,

This is my second time using Bodymovin to export animated file from AE. I have all the images linked, and have it exported in the files, along with the demo.html. However, when I preview the demo.html in google chrome. It's showing multiple errors loading images...

How can I fix this??? 
Please help. 

Thank you!!! 
![Screen Shot 2019-06-04 at 3 48 55 PM](https://user-images.githubusercontent.com/51384624/58912710-534f1a00-86e0-11e9-83fb-27e4ed7141c4.png)

**Comment by kamakamaha** [comment]
When I share the link to my co-workers, and have them open on their laptop. Its showing blank images. Where on my screen its fine....

I'm about to pull my hair out on this!!! lol

**Comment by mayorandrew** [comment]
You may be running into this issue: https://security.stackexchange.com/questions/190266/why-chrome-blocks-ajax-locally

In that case you cannot preview HTML file by double clicking on it, and should use a web-server application (like nginx or https://www.npmjs.com/package/serve) to serve it.

Or you can try to upload your bundle to codesandbox.io (use vanilla sandbox)

**Comment by kamakamaha** [comment]
Hi mayorandrew,

When I double click on the demo.html, it pops open in Chrome..It plays perfectly fine. But, the screenshot I show above showed that it fails to load the images. When I zip the folder and uploaded to dropbox. I then share it with my co-worker. He was not able to see the images while in preview in chrome.......

I'm not sure what I should do now!~~~

**Comment by mayorandrew** [comment]
I don't quite understand. Is the screenshot from your machine or from your co-worker's? Do images load when you double click on the file to open it in the browser on your machine?

If you click on the link shown on your screenshot, does chrome open the image?

**Comment by kamakamaha** [comment]
So, the screenshot is from my machine. The animation plays fine when I open from my end. But when I zip everything and share it with my co worker. He then open the demo.html. All the sudden, we are not seeing the images that suppose to show.

**Comment by bodymovin** [comment]
@kamakamaha what browser is your coworker opening the html from?
As @mayorandrew commented, this is related to browser policies regarding loading assets from your file system.
If you can, provide the export from a web server instead.

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
