### ISSUE TITLE
bodymovin: render failed! composition should not include any images

### ISSUE THREAD

**Issue by Frazetty** [airbnb/lottie-web#1663]
I can't render my sticker for Telegram, the plugin says "render failed! composition should not include any images" - Does somebody know what should I do? I'm a beginner in Adobe After Affects
<img width="702" alt="Снимок экрана 2019-06-06 в 10 41 29" src="https://user-images.githubusercontent.com/51437442/59016110-3d109d80-8849-11e9-979e-39747d8a3072.png">

**Comment by bodymovin** [comment]
Hi, apparently Telegram doesn't support layers that have images as source.
If your layers come from illustrator, you can try right clicking on them and convert to shapes.
If not, I don't think there is a solution.

**Comment by monther8184** [comment]
the solution is 
when pull the ai to the render queue right click on ai icon and chose create > create shapes from the vector layer . the icon should become star

**Comment by codemathics** [comment]
This definitely helped, thanks mate!

**Comment by elisamf** [comment]
Can I do the same if it is a picture in the animation?. As I have the same problem, and I don´t know if it is possible to do with a picture.

**Comment by sumiranpradhan** [comment]
> Can I do the same if it is a picture in the animation?. As I have the same problem, and I don´t know if it is possible to do with a picture.

Hey, have you found a solution yet ? I was trying to create a tgs file from a webp, but got the aforementioned error. 
( My purpose: I wanted to move my WhatsApp Animated Stickers to Telegram which needed a tgs file , importing normal stickers as webp was a breeze, it's just the animated ones need to be in the tgs format )
