### ISSUE TITLE
Add <lottie-player> web component

### ISSUE THREAD

**Issue by justinfagnani** [airbnb/lottie-web#1665]
It would be really awesome for approachability and use within frameworks if you published a standard web component wrapper on the player library.

Then without requiring any JS a user could use the element:

```html
<html>
  <head>
    <script type="module" src="/node_modules/lottie-web/lottie-player.js"></script>
  </head>
  <body>
    <lottie-player src="/data.json" loop></lottie-player>
  </body>
</html>
```

A web component can do a lot of nice things automatically, like use a shadow root to encapsulate the DOM from external styling, add default styles so the animation is visible without required external styling, and register a ResizeObserver so the animation resizes automatically.

Web components are also very compatible with most frameworks, so users wouldn't have to create framework wrappers, they could just use the `<lottie-player>` element in their templates.

I have a simple start on `<lottie-player>` in a gist: https://gist.github.com/justinfagnani/49b830898ec2247a6bd609cdbb5ce1c5

**Comment by bodymovin** [comment]
Hi, isn't this a similar approach?
https://github.com/LottieFiles/lottie-player

**Comment by justinfagnani** [comment]
@bodymovin oh, indeed it is.

Would you consider making a web component a first-class product of this library? I think it's much a more approachable way to get started than the JavaScript API. A custom element takes care of selecting the container for you.

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
