### ISSUE TITLE
Lottie preloader resize issue

### ISSUE THREAD

**Issue by TasioC** [airbnb/lottie-web#1668]
Hello guys, 
I’m trying to use a Lottie on my preloader but can’t figure out how to keep the Lottie filling up the div at 100% on resize. I don’t really care about preserving aspect ratio, just want to cover the whole div. 
Thanks in advance

https://codepen.io/ta_io/pen/PvMxzE

**Comment by bodymovin** [comment]
Hi, if you want it to stretch, you'll need to get the svg element via javascript and change it's preserveAspectRatio attribute to "none".

**Comment by webdevnerdstuff** [comment]
Using JavaScript to change the attribute is a big hacky. There should be a way to set the value.
