### ISSUE TITLE
Rendering multiple animations in one canvas context problems

### ISSUE THREAD

**Issue by RenanSgorlom** [airbnb/lottie-web#1671]
Hi, I am using the plugin version `5.5.3`

I am trying to render multiple animations using one **canvas context** but I am having some problems:

1. The **quality** of the render is not as sharp as when you just change the renderer to canvas
2. How can you **change the position** of a certain element on the canvas if you render more than one using the context?
3. What are the options you can pass into the `scaleMode` key inside the redererSettings object? and is it even relevant for when you're rendering using canvas context?
4. When you render more than one element in the same canvas and they have different `preserveAspectRatio` values they start flickering
5. Does `setSubframe` have any impact on `canvas` render?

**For context here's what I am trying to achieve:**

I have a bunch of different characters, they're always facing `right` when I export them from AE, but using the **canvas renderer and the context** I want to be able to position them to the opposite sides of the screen, and also flip one of them similar to what you can achieve by using `transform: scaleX(-1);`

And also I want to be able to render an animated background on that same canvas, is that possible? would it have any performance benefits by doing all in one canvas as opposed to multiple canvas?

my reasoning is: since I want them all to be synced and the same frame rate then it makes more sense to have just one canvas for it and it also sounds like it would be more performant, but I am not 100% sure if this is true.

[Here's a sample link](https://codepen.io/RenanSgorlom/pen/orgxyJ?editors=0010) of what I am trying to do... notice that I am changing the position of the elements inside the canvas using `preserveAspectRatio` which is not ideal... but it was the only way I found of changing the position of the elements

here's what's displayed:
![Jun-11-2019 14-15-07](https://user-images.githubusercontent.com/6893723/59307459-679c9500-8c53-11e9-87a3-ed77135b0854.gif)

love this plugin and any feedback is appreciated thanks!

**Comment by bodymovin** [comment]
1. Hi, regarding canvas quality, make sure you are not scaling the canvas in the DOM, if not, apart from some minor differences, it should look the same.
2. you can translate the canvas context between an animation and the following one to change the origin. In orderto do that you can listen to the enterFrame event of every animation and translate between one and the other.
3. scaleMode doesn't affect if you are providing your own canvas context
4. see 3.
5. yes, it affects the framerate of the rendering

**Comment by RenanSgorlom** [comment]
thanks for the support @bodymovin I will try your suggestions 🎉

**Comment by bodymovin** [comment]
Sure, let me know if you need anything else.

**Comment by karstor** [comment]
Hi @RenanSgorlom and @bodymovin I am trying to achieve a similar thing and have attempted to transform the canvas as advised with no luck. Do you by any chance have a working example you could share?

I want to play 2 animations at the same time in the same canvas side by side. However, I cannot find a working solution.

I have posted this on SO for greater visibility:
https://stackoverflow.com/questions/72816566/lottie-web-play-2-animations-in-the-same-canvas-at-the-same-time
