### ISSUE TITLE
Blend mode 'difference' issue.

### ISSUE THREAD

**Issue by PeerII** [airbnb/lottie-web#1672]
Working on a Macbook Pro 13" MacOSX 10.14.3 with AfterEffects version 16.1.1

I'm trying to create a simple black and white loader. It involves four numbers with two black squares on a white background that move from corner to corner. The idea is that when the black square with a white number on it moves away, the white number will turn black. As you'd expect. 

Instead, the number just vanishes. So the inverting of the numbers is not happening. The difference effect is not working. The weird thing is that when you view the JSON on the Lottie Preview using desktop it works but not on the Lottie Preview using iPhone.

Download link to AfterEffects project:  [20190613_9292 loader animation_NHO_V18_LOOP.aep.zip](https://github.com/airbnb/lottie-web/files/3286049/20190613_9292.loader.animation_NHO_V18_LOOP.aep.zip)

Screenshot preview on desktop: <img width="798" alt="Screenshot 2019-06-13 at 14 39 12" src="https://user-images.githubusercontent.com/33514653/59433243-61402180-8de9-11e9-814c-20c20419ec4b.png">

Sceenshot preview on iPhone: ![IMG_9851](https://user-images.githubusercontent.com/33514653/59433235-5b4a4080-8de9-11e9-96c5-7c594813fe3a.jpg)

**Comment by bodymovin** [comment]
Hi, if the issue is with the lottie-ios player, I suggest that you report it in that repo.
I'm not sure if it supports blend modes.
https://github.com/airbnb/lottie-ios

**Comment by PeerII** [comment]
@bodymovin Will do.
