### ISSUE TITLE
Position Manipulation in JSON file.

### ISSUE THREAD

**Issue by gujral1997** [airbnb/lottie-web#1673]
Hi @bodymovin 
Thanks for this amazing library. It works well with all sorts of use cases.

I am trying to manipulate the position of animation directly from the JSON file. However, sometimes it works and sometimes doesn't. As far as I can see, it is co-related with anchor points value and I am unable to find a correlation. Can you please tell me how to resolve this?

Thanks in advance!

**Comment by Danjuanlab** [comment]
If you want to change some element position ，you can use lottie api （check the exp code）https://github.com/bodymovin/lottie-api
If you want to change the whole animation，I suggest use jquery.

**Comment by bodymovin** [comment]
as @Danjuanlab said, to manipulate values it's best to use the lottie-api library.
The reason why some properties can be modified through the json and some others can't is because some values get cached and are not read from the json anymore.

**Comment by gujral1997** [comment]
Thanks for quick feedback. I want to manipulate the position or size when `a` = 1. 
Like mentioned in a sample portion of a JSON file below: 
```
{
...
  "layers": [
    {
      "ddd": 0,
      "ind": 10,
      "ty": 2,
      "nm": "logo.png",
      "cl": "png",
      "refId": "image_0",
      "sr": 1,
      "ks": {
        "o": { "a": 0, "k": 100, "ix": 11 },
        "r": { "a": 0, "k": 0, "ix": 10 },
        "p": { "a": 0, "k": [540, 864, 0], "ix": 2 },
        "a": { "a": 0, "k": [230, 80, 0], "ix": 1 },
        "s": {
          "a": 1,
          "k": [
            {
              "i": { "x": [0.833, 0.833, 0.833], "y": [0.833, 0.833, 0.833] },
              "o": { "x": [0.167, 0.167, 0.167], "y": [0.167, 0.167, 0.167] },
              "t": 0,
              "s": [0, 0, 100],
              "e": [161, 161, 100]
            },
            {
              "i": { "x": [0.833, 0.833, 0.833], "y": [0.833, 0.833, 0.833] },
              "o": { "x": [0.167, 0.167, 0.167], "y": [0.167, 0.167, 0.167] },
              "t": 10,
              "s": [161, 161, 100],
              "e": [161, 161, 100]
            },
            {
              "i": { "x": [0.833, 0.833, 0.833], "y": [0.833, 0.833, 0.833] },
              "o": { "x": [0.167, 0.167, 0.167], "y": [0.167, 0.167, 0.167] },
              "t": 23,
              "s": [161, 161, 100],
              "e": [0, 0, 100]
            },
            { "t": 30 }
          ],
          "ix": 6
        }
      }
...
}

Here `layers[0].ks.s.k` is an array of objects when a = 1. In such situations, it becomes difficult to find a generalized way to manipulate such properties.
