### ISSUE TITLE
After Effects preferences have changed (update readme)

### ISSUE THREAD

**Issue by gautsch** [airbnb/lottie-web#1677]
**Tell us about your environment**
MacOS 10.14.5

* **After Effects Version:**
CC 2019 (16.1.1.)

No biggie, but it looks like Adobe has moved this option from 'General' preferences to its own submenu, 'Scripting and Expressions'.

> 
> From *'After installing'*
> Windows: Go to Edit > Preferences > General > and check on "Allow Scripts to Write Files and Access Network"
> Mac: Go to Adobe After Effects > Preferences > General > and check on "Allow Scripts to Write Files and Access Network"
> 
It's now:
<img width="736" alt="Screenshot 2019-06-17 08 44 13" src="https://user-images.githubusercontent.com/3241906/59570523-d8710080-90dc-11e9-939c-3f14894f8330.png">

Edit: I don't have access to a Windows machine right now but I assume it's changed there as well

**Comment by gautsch** [comment]
Create a 'lil PR to update this, with the assumption that the menu is in the same place now on Windows (Adobe's help docs haven't updated yet either)
https://github.com/airbnb/lottie-web/pull/1678

**Comment by SamvelUi** [comment]
I have a question, I use default animations from AE and I export json with all guidelines 
Im demo animation working nice but json is not working, what could be happen?

**Comment by SamvelUi** [comment]
Json also not working in Lottie Cloud Json Viewer

**Comment by bodymovin** [comment]
@gautsch Thanks! I've merged the PR.
@SamvelUi Can you create a new issue with more info on what is going on?
