### ISSUE TITLE
My Lottie JSON works in the previewer but not on android app

### ISSUE THREAD

**Issue by J3nova1628** [airbnb/lottie-web#1683]
Hey, guys, can anybody help me out I am trying to create animation with a handwritten effect. When I export to JSON and upload to Lottie files it works perfectly as you can see on this link 

https://lottiefiles.com/share/Zbz8xD

but when I add this to my android Xamarin Forms project this is the result I get:

https://imgur.com/l3kQwhK

Really want this to work thanks

**Comment by bodymovin** [comment]
is it using the android player?
Can you post the issue on the lottie-android repository?

**Comment by J3nova1628** [comment]
@bodymovin I have solved the issue, I was using the stroke tool and images instead of using shape layers and trim paths in AE
