### ISSUE TITLE
Export demo.html not showing the animation but javascript is running the animation

### ISSUE THREAD

**Issue by dnllromao** [airbnb/lottie-web#1694]
Hi,
I'm trying to make the exported demo.html or the data.json file work but whithout sucess.
I'm running my index.html/demo.html from an apache localserver and using google chrome. 
I've tried the same index.html file with your demo data.json and everyhting works fine.
I've inspected the element in the browser and saw that the animation javascript is running and there are no errors in the console.
You can take a look at [https://github.com/dnllromao/bodymovin](https://github.com/dnllromao/bodymovin)

Thanks for your help.

**Comment by bodymovin** [comment]
Hi, can you share the .aep?
I see there are things animating but not sure what is blocking them.

**Comment by dnllromao** [comment]
Hi,
I've uploaded the .aep file to the repository.
Truly appreciate your help.

**Comment by bodymovin** [comment]
Unfortunately CC Twister is not supported by the player.
There are very few raster effects that are supported.

**Comment by dnllromao** [comment]
Many thanks for your help.
