### ISSUE TITLE
Alpha Track Matte not exporting Correctly

### ISSUE THREAD

**Issue by godwinolatunde** [airbnb/lottie-web#1695]
[Writeon folder.zip](https://github.com/airbnb/lottie-web/files/3339448/Writeon.folder.zip)

Hi, currently running a Windows 10 OS Version 1809.
Running on Chrome, version 75, After Effects version is CC 2019

I'm trying to achieve a write on effect, using masks on a solid color layer with alpha track matte on the Illustrator file.

I expected the animation to reveal the word, the only thing happening is other extra animations of some trim paths happening.

Here's a dropbox link 
https://www.dropbox.com/sh/x3w20kgp0pfvp40/AABDetByXj4HFpTmW6H1vGGaa?dl=0

**Comment by bodymovin** [comment]
Hi Stroke effect has very limited support unfortunately.

**Comment by godwinolatunde** [comment]
Thank you!
Fixed my issue by making the mask opacity to 0%, Not sure it's a correct fix, but it sure got it to do what I wanted.
