### ISSUE TITLE
Lottie Background - High CPU Consumption

### ISSUE THREAD

**Issue by onurtahmaz** [airbnb/lottie-web#1697]
I set the div element including Lottie-player html tag as the background. However it consumes too much cpu and I could not find a way to fix it. I decreased the width to 240 px but no change occurred.

Below are my html and css for the animated background:

Html:

`<div id="background"> <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player id="lottie-player"
            src="https://assets1.lottiefiles.com/packages/lf20_pIVAwL.json" mode="bounce" background="transparent"  speed="0.1"  loop  autoplay >
    </lottie-player></div>`

Css:

`#background, #lottie-player{
    position: fixed;
    top: 0;
    left: 0;
}`

<img width="558" alt="Screen Shot 2019-07-02 at 10 37 37 AM" src="https://user-images.githubusercontent.com/47431367/60493626-e1a1c600-9cb5-11e9-9e87-cabff0376f15.png">

**Comment by bodymovin** [comment]
Hi, it seems the player is recalculating the shape on every frame.
Can you share the .aep?

**Comment by bodymovin** [comment]
It's probably related to applying trim paths to a repeated shape

**Comment by onurtahmaz** [comment]
I deleted the repeater, but the cpu usage is still very high. Here is the aep: https://www.dropbox.com/sh/w2wlqsvojsrttwn/AAD1NBF9aHUWItMXqHOw9xj5a?dl=0
