### ISSUE TITLE
Bad display on Edge and Chrome Standalone

### ISSUE THREAD

**Issue by Akta3d** [airbnb/lottie-web#1699]
**Tell us about your environment**
bodymovin version 5.5.5

* **Browser and Browser Version:**
Edge 44
Chrome (only in standalone mode)

* **After Effects Version:**
 (AE 16 / 2019)

**What did you do? Please explain the steps you took before you encountered the problem.**
```
element.append('<div style="width:' + size + 'px;height:' + size + 'px; display:inline-block;"> </div>');

var params = {
  container: element[0].childNodes[0],
  renderer: 'svg',
  loop: true,
  autoplay: true,
  animationData: .... data.txt ....
};

var anim = lottie.loadAnimation(params);

anim.play();
```
[data.txt](https://github.com/airbnb/lottie-web/files/3350094/data.txt)

**What did you expect to happen?**
Want display correctly the animation in all browsers
[GoodDisplay.webm.zip](https://github.com/airbnb/lottie-web/files/3350100/GoodDisplay.webm.zip)
![image](https://user-images.githubusercontent.com/6841666/60514500-e37d8080-9cd9-11e9-80fe-53fb8ec66d31.png)

**What actually happened? Please include as much _relevant_ detail as possible.**
On Edge and Chrome standalone a part of the graphics is missing

[BadDisplay2.webm.zip](https://github.com/airbnb/lottie-web/files/3350098/BadDisplay2.webm.zip)
![image](https://user-images.githubusercontent.com/6841666/60514459-cf398380-9cd9-11e9-85ee-12ccfbff95aa.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
[INFast-anim-loader.aep.zip](https://github.com/airbnb/lottie-web/files/3350133/INFast-anim-loader.aep.zip)

**Comment by bodymovin** [comment]
Hi, unfortunately inverted alpha masks does not work correctly on the current Edge.
I have never user Chrome Standalone, but it might be the same issue.

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
