### ISSUE TITLE
Bodymovin button

### ISSUE THREAD

**Issue by raonicoelho** [airbnb/lottie-web#1707]
Hi.

I created an animation with After Effects and exported using Bodymovin, but there's a button on it an I would like to make it clickable. How can I do that?

Thanks.

**Comment by bodymovin** [comment]
Hi, if you use the svg renderer, you can set classes and ids in AE and refer them later via javascript or css.
This can help.
https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript

**Comment by kudanai** [comment]
I'm closing this issue for now. Please re-open it if it's still relevant.
