### ISSUE TITLE
Alternative for inverted masks?

### ISSUE THREAD

**Issue by AnishGG** [airbnb/lottie-web#1711]
As discussed in #1705, inverted masks are not rendered properly when rotated or translated. Can someone suggest an alternative for inverted masks which might work with Lottie-web.
@bodymovin suggested something [here](https://github.com/airbnb/lottie-web/issues/1705#issuecomment-509426400), but I didn't quite catch what you meant by this. 
Thanks in advance! ^_^

**Comment by bodymovin** [comment]
Answered here
https://github.com/airbnb/lottie-web/issues/1705#issuecomment-511248871

**Comment by AnishGG** [comment]
Thank you!
