### ISSUE TITLE
White Line Under My Animation

### ISSUE THREAD

**Issue by AlexandreGdl** [airbnb/lottie-web#1713]
Hi i'm working on a website, made with React and i have an issue. I want to put an animation at the bottom of the screen. BUT i have a white line that appear I don't know why.

![image](https://user-images.githubusercontent.com/46439935/60976157-80b96400-a32d-11e9-9b9d-1c58667ba4a0.png)

I made an animation that make the "flower" animation goind down ( it's working ) and even during the animation i have this white line. so i can't have my animation at the real bottom of the screen. If i used a position absolute it would work but it's risky, it don't work on different screen.

When i use the inspector, it show that the 

white line is in the svg but in after effect the animation is at the bottom of the screen too.

( I can't provide the After effect file because of the designer ( he don't want to ).

** Its more a "blank" like than a white one it's like a "PNG" line

I linked the demo of the animation if you want to try it

[Archive (2).zip](https://github.com/airbnb/lottie-web/files/3377892/Archive.2.zip)

Thanks for the help !

**Comment by Danjuanlab** [comment]
From the demo page, it is your production problem in AE. Or the parent frame's padding is not 0.

**Comment by AlexandreGdl** [comment]
> From the demo page, it is your production problem in AE. Or the parent frame's padding is not 0.

Thank's for the help, I found my probleme. My animation wasn't "tall" enough to fit my div and it was stick to the top, so I used "display: flex; flex-flow: column; justify-content: flex-end;" and now my animation will always be at the bottom without the white space
