### ISSUE TITLE
Stucked at saving data Bodymovin-TG

### ISSUE THREAD

**Issue by kinzozs** [airbnb/lottie-web#1714]
![5EFbIXTtc1](https://user-images.githubusercontent.com/51392958/61011483-203c1e00-a351-11e9-98a6-4fa47a3657de.png)

Hello im trying to do something very simple, just import a gif and use bodymovin for Telegram Stickers, but it keps getting stuck at ''Saving data'' 

After Effects 2015

aep example

[pepelaugh.zip](https://github.com/airbnb/lottie-web/files/3379702/pepelaugh.zip)

**Comment by Danjuanlab** [comment]
Currently, gif is not supported. You can convert gif to sequence frame and import it, but the file size of such multiple images is not efficient.

**Comment by danilasenko** [comment]
I have the same problem. I prepared a vector file in Ai, imported it into Ae, created shapes from vector layers, animated them and now I'm stuck when trying to render. How to solve it?
[sxs.zip](https://github.com/airbnb/lottie-web/files/3382921/sxs.zip)

**Comment by danilasenko** [comment]
My guess is that Bodymovin-TG is not supported by older versions of AE. 
My friend uses up-to-date version and has no problem exporting .tgs files. While my export is always stuck no matter what.

**Comment by ranapratapvarma** [comment]
We created a video using gif and some AE animations for text. AE animations are working very good but it is not exporting gif. Am I doing it wrong? or there is no support for exporting gif? Will it be available soon?

**Comment by bodymovin** [comment]
@ranapratapvarma unfortunately gifs are not supported by the player.

**Comment by Afarfeel** [comment]
Same problem over here, are there yet any solutions for this issue?
