### ISSUE TITLE
Gradients with too many color stops export incorrectly

### ISSUE THREAD

**Issue by Etherealflux** [airbnb/lottie-web#1715]
**Tell us about your environment**

* Viewing platform isn't relevant; this is a problem with bodymovin. I tried this out on [lottie.cloud](https://lottie.cloud/app), as well as in Telegram (not sure how that renders, exactly)
* After Effects CC 2019 - Version 16.1.2 (Build 55)
* Bodymovin 5.5.2
* Exported animations claim their version is 5.5.6, though

**What did you do? Please explain the steps you took before you encountered the problem.**

Bodymovin correctly handles gradient fills with small numbers of color stops. However, if there are too many color stops in the gradient, then the resulting list of positions and colors will be malformed, and the resulting animation will be wrong.

From my testing, it appears that it starts having problems at around 10 color stops. 

Here's an example of what my gradient settings look like:

![image](https://user-images.githubusercontent.com/7762872/61132132-c0489300-a488-11e9-96cc-a4472c461086.png)

**What did you expect to happen?**

I expect the animation to render like this:

![image](https://user-images.githubusercontent.com/7762872/61132149-c6d70a80-a488-11e9-82c6-3c260dc6fd7f.png)

**What actually happened? Please include as much _relevant_ detail as possible.**

The exported animation's gradient has scrambled color stops, messing up the rendering:

![image](https://user-images.githubusercontent.com/7762872/61133109-c3dd1980-a48a-11e9-94d1-3da68bae9241.png)

The resulting order of the color stops is:

0,0.046,0.093,0.494,0.895,0.947,1,0.596,0.193,0.246,0.3,0.336,0.372,0.4,0.428,0.483,0.538,0.583,0.627,0.671,0.715,0.761,0.807

It looks like the renderer ignores any color stops that come before one it has already seen.

The renderer can handle a large number of color stops. For example, here's the same file, but with the gradient overwritten manually:

![image](https://user-images.githubusercontent.com/7762872/61133130-cc355480-a48a-11e9-8c03-9c83e086d33a.png)

This has a ton of color stops, but obviously still renders properly!

**Please provide a download link to the After Effects file that demonstrates the problem.**

I've attached an example AE project, as well as the malformed result and the example of a working file.

[bug.zip](https://github.com/airbnb/lottie-web/files/3386646/bug.zip)

**Comment by bodymovin** [comment]
Hi, I've found the issue. It is not related to the number of color stops, but it seems to be related to the sorting of them. Apparently in this file, the handles have been reordered in a way that they are not correlative.
The error will be fixed in the next deploy.
Thanks for reporting it!
