### ISSUE TITLE
trouble with effects applying to only the first path in a shape layer

### ISSUE THREAD

**Issue by RickBoing** [airbnb/lottie-web#1716]
**Tell us about your environment**

* **Browser and Browser Version:**

Mozilla Firefox 68.0

* **After Effects Version:**

16.1.2 build 55

**What did you do? Please explain the steps you took before you encountered the problem.**

I've created a simple animation using school of motion's tapered stroke preset (this one: https://www.youtube.com/watch?v=YwC009ESmZI&), the animation works perfectly in after effects, but on exporting to a .JSON file it seems to have trouble applying the effects of a layer to all the paths the sequence goes through.

**What did you expect to happen?**

https://gyazo.com/2d8f2f881da57c7d9f85ca02d1549287

**What actually happened? Please include as much _relevant_ detail as possible.**

The tapered stroke and the write on effect are both part of the effect controls provided by the preset, they seem to only apply to the first path in a shape layer though, the initial line works fine, as it is the only path in the shape layer, but on the second part of the animation, all the effects get applied only to the first path.
https://gyazo.com/e0a11ea17c6e17a980cc5a51e3f85a0e

**Please provide a download link to the After Effects file that demonstrates the problem.**

[tapered stroke 1.zip](https://github.com/airbnb/lottie-web/files/3390466/tapered.stroke.1.zip)

**Comment by bodymovin** [comment]
Hi thanks for reporting it. It's been fixed on version 5.5.7
And trim paths got a huge performance improvement for your type of scenario :)

**Comment by RickBoing** [comment]
Amazing.

thanks for the quick fix!
