### ISSUE TITLE
Possible to render animation locally without a server?

### ISSUE THREAD

**Issue by AnishGG** [airbnb/lottie-web#1719]
I have been rendering the Lottie JSoN animations locally since the last month, but suddenly 2 days back they stopped rendering. I checked the console and it seems that the way to load JSoN files via cross-origin request have been changed.
I have referred previous issues registered(https://github.com/airbnb/lottie-web/issues/33) here, but was not able to solve this.
Could someone suggest a wayaround for this without having to set a local server? @bodymovin 
This will be so much helpful to us here: https://github.com/synfig/synfig/issues/704
Thank you!

**Comment by Danjuanlab** [comment]
Select the demo when exporting, this will generate a demo page, you can preview the animation on demo.html

**Comment by AnishGG** [comment]
Thank you for informing!
