### ISSUE TITLE
Using a template, animation exported but won't play in Lottie preview unless slider is used

### ISSUE THREAD

**Issue by oisinkelly22** [airbnb/lottie-web#1723]
Hi,

I'm using a template composition and have exported the animation, however, the animation won't play in the browser but will play out the animation if I use the slider.

**Comment by oisinkelly22** [comment]
Here's the .json

[NewTest2.json.zip](https://github.com/airbnb/lottie-web/files/3401685/NewTest2.json.zip)

**Comment by bodymovin** [comment]
Hi, can you share a link of your implementation?

**Comment by oisinkelly22** [comment]
Hi,

Are these the link? 

https://lottiefiles.com/share/HcgVDv

https://assets3.lottiefiles.com/packages/lf20_HcgVDv.json

Thanks

**Comment by bodymovin** [comment]
It's firing an error on the expression that is looking for a layer named `layer('Color Control')`, perhaps you need to export it as an extra comp in the animation

**Comment by Tablular** [comment]
Hi there, I'm getting the same issue with my animation. Any thoughts?

https://lottiefiles.com/share/kX7HQr

Thanks!

**Comment by oisinkelly22** [comment]
Worked perfectly, 

Thanks for your help!
