### ISSUE TITLE
Only play animations when visible in viewport

### ISSUE THREAD

**Issue by apfury** [airbnb/lottie-web#1726]
Hi,

I've currently been working on a page which has multiple animations on it. The page itself has a fairly straightforward 100vh slide style set up, with one animation on each slide. (so only one is ever visible within the viewport at any one time).

Everything works great but obviously all of the animations load and play at the same time.

My question is weather there is a way to control the animations so that they only start to play if they are within the viewport?

A link to my setup can be found here – https://studiofury.com/bm-test/multi-scroller.html

My coding knowledge isn't extensive, so any help on coding solutions would be greatly appreciated.

Many thanks in advance.

**Comment by bodymovin** [comment]
Hi, looking at the code here, https://studiofury.com/bm-test/js/main.js it seems you are defining all animations with the same name `animation`, you probably want to store a reference to each one individually so then you can play each one when the section is into view.
Looking at the documentation of scrollify, you probably want to pass a method to the `after` property and every time it is fired, play / stop the animation you need.
https://projects.lukehaas.me/scrollify/#options

**Comment by apfury** [comment]
Hi, thank you for your reply. 

Everything you've mentioned makes perfect sense, but unfortunately for me my javascript and jquery coding knowledge is very limited.

Would anyone with better coding knowledge be able to help demonstrate how I might be able to adjust my setup and callbacks to get this working?

Many thanks in advance.

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
