### ISSUE TITLE
json export with bodymovin doesn't work on Android device

### ISSUE THREAD

**Issue by careyestes** [airbnb/lottie-web#1728]
Im using AE to export an animation with the Bodymovin extension. The json file works perfectly fine on an iOS device, but crashes on Android. I reviewed the Lottie docs to see if I am using an unsupported feature in AE.

Im not applying any unsupported features. I've narrowed it down to a shape layer. Any keyframe animation I apply to the transform options is what causes it to fail in Android. 

As a sanity check, I removed all animations from the shape layer, exported and it works fine. As soon as I add a keyframe tween on anything, ex. Opacity, Rotation, Position, and export, it crashes the app in Android only. 

Is this a known problem and is there a workaround or something I need to do to prep the vectors?

**Comment by bodymovin** [comment]
Hi, can you post the issue in the lottie-android repository? They' ll be able to be more helpful than me.
https://github.com/airbnb/lottie-android

**Comment by careyestes** [comment]
Yes, thank you.
