### ISSUE TITLE
How to make this tutorial work the handwriten part 

### ISSUE THREAD

**Issue by thomasponzo** [airbnb/lottie-web#1731]
https://www.youtube.com/watch?v=zSlXOIsfjLY I made this tutorial with my own text but the handrawn part is not showing at all when I render it with bodymovin how could I fix this?

**Comment by bodymovin** [comment]
Hi, unfortunately the stroke effect is partailly supported, so you can't replicate that tutorial with the player.

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
