### ISSUE TITLE
Forward and Reverse Animated Loading Spinner

### ISSUE THREAD

**Issue by mikevyt** [airbnb/lottie-web#1732]
Hi there,
First of all, just want to say thank you for such an incredible library. It works beautifully.

Basically, I am using my logomark as a loading animation. I want it to complete the animation forwards and backwards until the loading is complete. When it is complete, I want it to finish its animation and show the complete logo.

Below is my current implementation. `loadAnimatedLogo` is called at the beginning of loading and `destroyAnimatedLogo` is called when complete. It currently works, however when `destroyAnimatedLogo` is called, it does not animate to that time. Is there a better way to do this that allows the logo to animate to completion when loading is complete? 

```
loadAnimatedLogo = () => {
        if (this.animation) this.animation.destroy();
        let direction = 1;
        this.animation = lottie.loadAnimation({
            container: this.myRef,
            renderer: 'svg',
            loop: false,
            autoplay: true,
            animationData: animatedLogoData
        });
        this.animation.addEventListener('complete', () => {
            direction *= -1,
            this.animation.setDirection(direction);
            this.animation.play();
        });
}

destroyAnimatedLogo = () => {
        this.animation.setDirection(1);
        this.animation.goToAndStop(3000);
}
```

Thank you.

**Comment by bodymovin** [comment]
Hi, this looks like the right way to do it. There is no "yoyo" feature built in the player.

**Comment by thesunRider** [comment]
> Hi, this looks like the right way to do it. There is no "yoyo" feature built in the player.

lol what is yoyo

**Comment by gravestench** [comment]
@thesunRider `yoyo` will generally play an animation/tween forwards, and upon complete animate/tween back to the original state.
