### ISSUE TITLE
Alternative for slider effect?

### ISSUE THREAD

**Issue by AnishGG** [airbnb/lottie-web#1735]
I want to use a the slider effect on null object and then use this slider effects as expression to influence some other parameter. Just found out that `slider effect` is not supported yet.
Can someone provide an alternative for this effect. ^__^

Also, consider I have 10 layers in a composition and I want to influence all the 10 layers's position paramter using a slider effect(using expressions), then will I have to create 10 NULL layers(and insert a slider in each of them and link to respective positions) or is there some easy way?
I have been stuck here for a while. It would be of so much help if you could provide some insight on this @bodymovin. ^__^
This will help in supporting: https://github.com/synfig/synfig/issues/704

**Comment by bodymovin** [comment]
when you say Slider Effect you mean Slide Control?
Slider Control is supported by the player

**Comment by AnishGG** [comment]
> when you say Slider Effect you mean Slide Control?
> Slider Control is supported by the player

Yes, I meant Slider Control. 
Sorry for raising wrong issue. It worked this time. I made a mistake while exporting last time.

Anyways, could you provide some insight on the following

> Also, consider I have 10 layers in a composition and I want to influence all the 10 layers's position paramter using a slider effect(using expressions), then will I have to create 10 NULL layers(and insert a slider in each of them and link to respective positions) or is there some easy way?

Thanks in advance! 😄

**Comment by bodymovin** [comment]
Not sure what you need exactly, but from that scenario, the null layers seem to be unnecessary, since you can target the slider expression directly from the shape layers.
Other option would be to use a point control (or mutiple ones) that works as the null layers and target them directly from the position property of the layer.

**Comment by AnishGG** [comment]
Thanks for clarifying!
I got what I needed from the above comment.  😃
