### ISSUE TITLE
Flick Lines in animation

### ISSUE THREAD

**Issue by henriqrossatto** [airbnb/lottie-web#1742]
Hi guys, my client is with a little problem in the animation that I created.

When I open the animation in Firefox (v68.0.1) is normal. But when I try with chrome (v75.0.3770.142) a tiny line appear on top of the animation. I test in my android open in chrome and looks okay too.

Some pics attached.
![Pasted File at July 30, 2019 9 01 AM](https://user-images.githubusercontent.com/30601233/62128674-46e3d980-b2ab-11e9-8d0e-644838a5fc01.png)
![Pasted File at July 30, 2019 9 04 AM](https://user-images.githubusercontent.com/30601233/62128675-46e3d980-b2ab-11e9-8648-38334e3ecb7a.png)

**Comment by bodymovin** [comment]
Hi, can you share a link where I can check the animation easily?
I'm trying to pause it before it goes away but it's too fast

**Comment by henriqrossatto** [comment]
Here the file in lottiepreview
https://lottiefiles.com/share/ur3MIq

I will invite the dev for the post to see if he can help in the problem

**Comment by henriqrossatto** [comment]
Hi @bodymovin. I didn't got the help from devs and I believe they will looking for another alternative. Not sure it you got some idea for what could be happening in this case. 

But I believe we can close here.

**Comment by bodymovin** [comment]
It's probably some artifacts of aliasing. In this case since you are using a mask, the mask is not being properly rendered by the svg engines and leave out that thin line on top.

**Comment by henriqrossatto** [comment]
I'm checking the file here and will share with you but I'm not sure that I'm using a mask on this animation. I try to use trim paths but had some errors in some logo corners when trying to preview.

So I recreate the entire animation using just path animation. And create the gradient with a square and alpha matte over the animation comp. Could be that?

**Comment by bodymovin** [comment]
If you inspect the svg, you'll see there are masks being used in the render. If you share the .aep I can check where they come from

**Comment by henriqrossatto** [comment]
AE File with what I was trying and the new try after today's feedback 
[1742 issue.zip](https://github.com/airbnb/lottie-web/files/3512206/1742.issue.zip)

**Comment by bodymovin** [comment]
yes, it's probably the alpha track matte that is causing that artifact

**Comment by henriqrossatto** [comment]
I will wait the feedbacks but I will close the ticket for now. Thanks!
