### ISSUE TITLE
Edge / IE opacity/colour wash out issue

### ISSUE THREAD

**Issue by garbournepagetiger** [airbnb/lottie-web#1743]
* **Browser and Browser Version:**
Edge and IE 11
* **After Effects Version:**
After Effects 2019

Hi, I'm pretty new to Lottie & Bodymovin but loving it so far, however, I've come across a problem today and unable to work out how to solve it.  I have an animation that has 4 scenes, all following the same pattern (each scene has a mask with hidden panels that move into view then off again); two of the scenes work fine in all browsers but the final two seem to look transparent, washing out the colours in Edge and IE11.

I've attached a ZIP containing the After Effects doc and "demo.html" that was generated by Bodymovin so you can see the issue in Edge/IE11 - Any suggestions or help would be great :)

[demo.zip](https://github.com/airbnb/lottie-web/files/3452253/demo.zip)

**Comment by bodymovin** [comment]
Hi, unfortunately Edge doesn't support alpha masks, it only supports luminance masks.
Can you try changing your masks colors to white? For example on layer `MASK-Restaurant > Contents > Rectangle 1 > Fill 1 > Color`
As a better solution (but more changes are needed) I'd suggest that you precompose those layers and use a regular mask. They are much more performant on all browsers than using effects or track matte masks.

**Comment by garbournepagetiger** [comment]
Thanks for the suggestions - I'll give them a try :)
