### ISSUE TITLE
Linux/different programs support? 

### ISSUE THREAD

**Issue by TECHNOFAB11** [airbnb/lottie-web#1744]
So I'm on Linux and would love to create the animations there. As there are many good alternative programs to AE (https://alternativeto.net/software/adobe-after-effects/?platform=linux), it would be awesome if we could have a exporter for such a program. Or some common file type which we could then compile to the json format via the shell or so.
Any way to skip the AE part would be cool.

Thanks :)

**Comment by AndreaMonzini** [comment]
- python-lottie with Blender Addon: https://gitlab.com/mattbas/python-lottie/

- glaxnimate: https://glaxnimate.mattbas.org/

- Synfig: https://www.synfig.org/2019/12/27/whats-coming-to-synfig-1-4-0-part-2/

**Comment by TECHNOFAB11** [comment]
As this will probably never happen, just use [Rive](https://rive.app)
