### ISSUE TITLE
Edge render issue?

### ISSUE THREAD

**Issue by DPHonys** [airbnb/lottie-web#1745]
So I animated my logo... I ran into some problems with the stroke effect but after some digging on the web and in AE settings I managed to resolve my issue, so I was happy that my animation is working correctly. It works flawlessly in Chrome and Firefox, but... In Microsoft's Edge the animation has some weird render issues and I don't know how to fix it.

Chrome / Fox : 
![chromfox](https://user-images.githubusercontent.com/38984391/62243568-d4274b00-b3dd-11e9-87e0-f261022402aa.png)

Edge : 
![edge](https://user-images.githubusercontent.com/38984391/62243581-dab5c280-b3dd-11e9-883c-8086594a5c69.png)

Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763

Adobe AE CC v 15.1.2 (Build 69)

[hgm folder.zip](https://github.com/airbnb/lottie-web/files/3453648/hgm.folder.zip)

**Comment by bodymovin** [comment]
Yes, unfortunately Edge has issues with svg masks. If you resize the browser you'll see they get fixed.
Bot much I can do on my side unfortunately.
