### ISSUE TITLE
Feature Request: getCurrentFrame()

### ISSUE THREAD

**Issue by tafelnl** [airbnb/lottie-web#1755]
Title says it all. There should be something like a `getCurrentFrame()` function that returns an integer.

**Comment by tafelnl** [comment]
Sorry, I somehow missed this issue: https://github.com/airbnb/lottie-web/issues/246

Closing

**Comment by bodymovin** [comment]
Hi, anyway I'll look into exposing this properties as part of the typescript definitions and document them
thanks for the suggestion
