### ISSUE TITLE
/data.json gets appended to the path when the path contains a query string

### ISSUE THREAD

**Issue by Kethatril** [airbnb/lottie-web#1757]
**Tell us about your environment**
* **Browser and Browser Version:**
* **After Effects Version:**
This bug is unrelated to browser version or After Effects version

**What did you do? Please explain the steps you took before you encountered the problem.**
When a path that has a query string is passed to lottie.loadAnimation the request path will have /data.json appended to it.
e.g: 
```
lottie.loadAnimation({
        container: this.element, 
        renderer: 'svg',
        loop: true,
        autoplay: false,
        path: '/content/uploads/2019/07/powerdrill2.json?s=e9a2713e867b53e15ad93af024148f30',
```
The requested url ends up as
`/content/uploads/2019/07/powerdrill2.json?s=e9a2713e867b53e15ad93af024148f30/data.json`
**What did you expect to happen?**
For /data.json not to be appended when the url has a query string in it

**Comment by bodymovin** [comment]
Hi, old decision I had forgotten about. It will be fixed on the next deploy.
Thanks!
