### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by jamie-pudsey** [airbnb/lottie-web#1758]
* **Browser and Browser Version:**
Google Chrome Version 75.0.3770.142

* **After Effects Version:**
CC 2018

I animated this bouncing cactus with a squash and stretch extension from ae. scripts to give a nice bouncy feel to it. I then rendered it out with the bodymovin extension but the animation hasn't come out the same and has lost the nice squash and stretch effect which can be seen in the screen shot. 

Animation in after effects

<img width="222" alt="Screen Shot 2019-08-08 at 10 03 04" src="https://user-images.githubusercontent.com/53897303/62690001-c9634c00-b9c3-11e9-8049-ec7ecdfa3058.png">

<img width="246" alt="Screen Shot 2019-08-08 at 09 53 48" src="https://user-images.githubusercontent.com/53897303/62689341-881e6c80-b9c2-11e9-9874-cb032139bb99.png">

bodymovin extension

<img width="534" alt="Screen Shot 2019-08-08 at 09 54 13" src="https://user-images.githubusercontent.com/53897303/62689368-953b5b80-b9c2-11e9-91d3-79731cfe9a9e.png">

<img width="606" alt="Screen Shot 2019-08-08 at 10 03 10" src="https://user-images.githubusercontent.com/53897303/62690011-cff1c380-b9c3-11e9-8f0a-93396976834a.png">

I'm wondering if it's something to do with bodymovin not liking any other extension used within the animation, well that's the only thing I can think of why it wouldn't work. 

If someone can help me out on this I'd be super happy. 

Cheers

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by jamie-pudsey** [comment]
[https://wetransfer.com/downloads/49c7853ccac4974e36b2b62a525cd38c20190808093753/be9d1998716123ac3e1798c8d532e5e220190808093753/996080](url) Sure

**Comment by jamie-pudsey** [comment]
I cant seem to attach the .aep file to my issue or this chat. What's the best way of sharing the .aep file with you?

**Comment by bodymovin** [comment]
Hi, I just tried it and unfortunately Bezier Warp is  not supported by the player.
There are very few raster effects that are.

**Comment by CHEEPEE** [comment]
Hi, I also have rendering issues
aep file
[UNDERBEHIND_LOGO_ANIMATION_CODE.aep.txt](https://github.com/airbnb/lottie-web/files/3502921/UNDERBEHIND_LOGO_ANIMATION_CODE.aep.txt)

video
[animation render lottie.mov.txt](https://github.com/airbnb/lottie-web/files/3502928/animation.render.lottie.mov.txt)

it only renders the first half.

Thanks :)

**Comment by bodymovin** [comment]
@CHEEPEE Hi, negative layer stretching is not supported unfortunately. But if you use time-remapping it should work fine.

**Comment by kudanai** [comment]
I'm closing this issue for now. Please re-open it if it's still relevant.
