### ISSUE TITLE
Gradient Issue in Safari

### ISSUE THREAD

**Issue by henriqrossatto** [airbnb/lottie-web#1759]
**Tell us about your environment**
I work in a line animation and the dev report that "everything is work correct except Safari browser there is SVG object in black color. When i checked https://lottiefiles.com/share/i89LSi in safari there is gradient correct i dont know why lottie animation doesnt work in safari in our project check screenshot. Thanks."
![62704959-f105e480-b9c2-11e9-8b90-6793802e1839](https://user-images.githubusercontent.com/30601233/63016344-c9eb5f00-be69-11e9-86b8-54e84e8a4b22.png)

* **After Effects Version:**
16.0.0

After it I donwload the last version of bodymovin and try to export again. I rebuild the animation entirely in AE. Here the preview result. 
https://lottiefiles.com/share/bO8C6h
https://lottiefiles.com/share/eEyVBx

AE File attached
[Github_Issue.zip](https://github.com/airbnb/lottie-web/files/3481838/Github_Issue.zip)

**Comment by henriqrossatto** [comment]
Does anyone know about it?

**Comment by bodymovin** [comment]
Do you have an online link where the gradient doesn't work?

**Comment by henriqrossatto** [comment]
I will check with the client

**Comment by henriqrossatto** [comment]
Hi @bodymovin. I already ask the client and they will try to put the animation on a separate url. I will keep you informed as soon I get the new link

**Comment by kudanai** [comment]
Hi there! I'm closing this issue as it hasn't been updated in a while. If this is still relevant, please feel free to re-open this issue or file a new one.
