### ISSUE TITLE
Render bodymovin svg in fabric js canvas

### ISSUE THREAD

**Issue by JenishaDalin** [airbnb/lottie-web#1763]
Hi, I had rendered the Lottie object in SVG renderer but I can't able to load the Lottie object into the fabric js canvas it was added but can't able to view it 

Is it possible to add the SVG renderer into the fabricjs canvas

This is my code which I have loaded the svg:
```
const animItem = bodymovin.loadAnimation({
  container: document.getElementById('fabricCanvas'),
  renderer: 'svg',
  loop: true,
  autoplay: false,
  // animationData: JSON.parse(animationData),
  path: 'https://labs.nearpod.com/bodymovin/demo/al_boardman/articulation/estimate.json',
  rendererSettings: {
    preserveAspectRatio: 'xMidYMid meet',
    // clearCanvas: false,
  }
})
```

HTML: 
```
<canvas id="fabricCanvas" width="300" height="300"></canvas>
```

My expected output is I need to load the SVG Lottie  into the fabricjs canvas

@bodymovin @asturur

**Comment by DebVortex** [comment]
Have you tried changing the `rendere` to `canvas` instead of svg?

**Comment by JenishaDalin** [comment]
yes @DebVortex  we can able to achieve by canvas. I need to load this in svg 

My requirement is I was changing the lottie color in run time so let me know if anyother options is their to change the color dynamically

**Comment by bodymovin** [comment]
Hi, a canvas element in html will not render an svg as an inner child.
Depending on your case you can position a div and a canvas overlapping so they render one on top of the other.

**Comment by kudanai** [comment]
I'm closing this issue for now. Please re-open it if it's still relevant.
