### ISSUE TITLE
Text converted to shapes rendering super bold and black.

### ISSUE THREAD

**Issue by DanECC** [airbnb/lottie-web#1765]
My animation is rendering two sets of text converted to shapes as extra bold and black. I had key-framed the text with masks to give a typing and erasing effect. It is suppose to be gin with blue and then switch to red.

Here is how it is rendering:
![Screen Shot 2019-08-12 at 10 38 26 AM](https://user-images.githubusercontent.com/54032747/62873438-6805ea80-bced-11e9-9b02-9e4e7567f57e.png)

Chrome - Version 76.0.3809.100 (Official Build) (64-bit)
AE v16.1.2

I converted all text to shapes and used masks. Upon upload the colors and weight is not rendering correctly.

I expected to have the "text" remain the same weight and to display the colors based on key-frames.

The "blue type" is suppose to have one line erased, then it is will type in a red line of text. once the red line finished the text changes to red, full line by full line. once the lines have all been turned to red the lines pointing to the devices change to red.  

https://www.dropbox.com/s/a2oqo0zlg2fz7zx/phase1-home-Animation-vector.aep?dl=0

**Comment by henriqrossatto** [comment]
Hi @DanECC 

When I exported your files export normal https://lottiefiles.com/share/tjir7F

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
