### ISSUE TITLE
Add custom events in index.d.ts file

### ISSUE THREAD

**Issue by knowBalpreet** [airbnb/lottie-web#1766]
Hi @bodymovin. Can you please add all event names in index.d.ts file. I want to use `DOMLoaded` but it is not present there. Can you please add it?
Thanks in advance!

**Comment by titoasty** [comment]
seems fixed in **index.d.ts**:

`export type AnimationEventName = 'enterFrame' | 'loopComplete' | 'complete' | 'segmentStart' | 'destroy' | 'config_ready' | 'data_ready' | 'DOMLoaded' | 'error';
`
