### ISSUE TITLE
Unable to execute script at line 288. null is not an object

### ISSUE THREAD

**Issue by markgravity** [airbnb/lottie-web#1767]
**Environment**
- macOS 10.15
- Bodymovin 5.5.7

**After Effects Version:**
AE 2019 16.1.2

**Error**
Got error `Unable to execute script at line 288. null is not an object` when export to .json

<img width="1126" alt="Screen Shot 2019-08-14 at 2 50 25 PM" src="https://user-images.githubusercontent.com/17875522/63003696-f1aae900-bea2-11e9-952c-febdfbaa1a80.png">

**Project Link**
https://www.dropbox.com/s/7shw8jyph11wc4u/pulse-reward-icon.aep?dl=0

**Comment by bodymovin** [comment]
Hi, can you share the missing files used in the project?

**Comment by markgravity** [comment]
Hi, it is here
[https://www.dropbox.com/s/u7eq0jsm1ub20ge/reward-icon.psd?dl=0](url)

**Comment by bodymovin** [comment]
I tried exporting the animation and I worked fine.
I'm closing the issue but feel free to reopen if necessary or can provide more information.
