### ISSUE TITLE
After Effects Mask mode "Subtract" not working on Lottie on Swift (iOS)

### ISSUE THREAD

**Issue by ravin-perera** [airbnb/lottie-web#1769]
<img width="140" alt="Screen Shot 2019-08-14 at 12 29 58 PM" src="https://user-images.githubusercontent.com/25216142/63050147-447aa580-be8f-11e9-8aae-d7f1dfd17f49.png">

**Tell us about your environment**
I made an animation for an icon through after effects, exported through Bodymovin and then loaded it into Swift through Lottie.

* **Browser and Browser Version:**
Swift and iOS
* **After Effects Version:**
Version 1.6.1.2 (Build 55)

**What did you do? Please explain the steps you took before you encountered the problem.**
I created a mask to reveal the shape of the icon using the subtract property. Everything looks great upon exporting (even after loading on to the previewer). 
**What did you expect to happen?**
Expected the mask to work the exact same way as it appeared in After Effects and the bodymovin previewer - revealing the complete shape instead of half.

**What actually happened? Please include as much _relevant_ detail as possible.**
But when it is loaded on to Lottie on Swift, the mask only reveals half of the shape. I've tried multiple times changing the scale and position of the mask, and it gives me the same result. I noticed that when I change the mode to "Add" instead of "Subtract" on AE, it tends to work. But add is not the mode I want for this animation.
**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/open?id=1uUEQ53fDloamMG8HN92wYW3Pdj1s_iGp

**Comment by bodymovin** [comment]
Hi, can you post this issue on the lottie-ios repository?
https://github.com/airbnb/lottie-ios

**Comment by ravin-perera** [comment]
Oops! sorry about that. Didn't know that thread existed.
