### ISSUE TITLE
Gradients and Masks not working on all mobile browsers

### ISSUE THREAD

**Issue by phantomboogie** [airbnb/lottie-web#1771]
I'm working on a few animations on - https://bit.ly/2DQ9WVu

And I'm running into an issue where my animations play and display fine across all browsers on desktop, but when viewed on any mobile browsers (chrome+firefox+safari), the gradients become black and masks don't display. 

Here's how it looks on desktop - https://imgur.com/a/iQd9AWV
Here's how its displaying on mobile - https://imgur.com/a/qgd2uQ2

Here's my AE file too - https://bit.ly/31GgaTl

Thanks

**Comment by bodymovin** [comment]
Hi, I just tried this link https://account.microsoft.com/family on mobile and it seems to work fine.
Is it possible that you are using an SPA and the base tag on the html head?
You might need to use `lottie.setLocationHref()` to specify explicitly a path that the renderer will prepend to id references so it finds them when targetted.
As a quick test, can you see if the canvas renderer renders correctly?

**Comment by kudanai** [comment]
I'm closing this issue for now. Please re-open it if it's still relevant.
