### ISSUE TITLE
Animation freezes intermittently at `TrimModifier.processShapes`

### ISSUE THREAD

**Issue by wuhao1117** [airbnb/lottie-web#1775]
**Tell us about your environment**

* **Browser and Browser Version:**
Chrome 76
* **After Effects Version:**
Unknown but we use lottie-web@5.5.7

**What did you do? Please explain the steps you took before you encountered the problem.**
We load a series of animations in sequence by calling `loadAnimation` right after the previous clip completes. Occasionally (around 30% of the time), the animation freezes in the middle of a random clip (no specific ones).

**What did you expect to happen?**
The whole sequence should play normally

**What actually happened? Please include as much _relevant_ detail as possible.**
stacktrace:
TrimModifier.processShapes
SVGShapeElement.renderModifiers
SVGShapeElement.renderInnerContent
SVGShapeElement.renderFrame
SVGRenderer.renderFrame
AnimationItem.renderFrame
AnimationItem.gotoFrame
AnimationItem.setCurrentRawFrameValue
AnimationItem.advanceTime
...

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, trim paths are expensive because they need to subdivide bezier curves into multiple segments. Are you processing many paths at the same time?

**Comment by wuhao1117** [comment]
Hi! Thank you for replying. I think I forgot to paste the actual error that happened. The error is
`Cannot read property 'c' of undefined` coming from [this line](https://github.com/airbnb/lottie-web/blob/75bfaec722077257dd137dc46c378ee59365073a/player/js/utils/shapes/TrimModifier.js#L182). 

So a more appropriate description of the problem is not animation freezes in the middle, but that it errors out in this line for a random animation clip, causing it to freeze.

Does it help diagnose where the problem is?

**Comment by bodymovin** [comment]
Can you share the .aep animation that has this problem? or a link with the implementation?

**Comment by wuhao1117** [comment]
Sure. We have an animation component that manages the div/canvas of the animation and make lottie calls:
```
const Animation = ({
  options: { loop, autoplay = false, segments, animationData, name },
  eventListeners,
  speed,
  ...props
}: Props) => {
  const container = useRef(null);

  useEffect(() => {
    const options = {
      container: container.current,
      renderer: 'svg',
      loop,
      autoplay,
      animationData,
    };

    const anim = lottie.loadAnimation(options);
    anim.setSpeed(speed);
    registerEvents(anim, eventListeners);

    const play = () => {
      if (segments) {
        anim.playSegments(segments, true);
      } else {
        anim.play();
      }
    };
    anim.addEventListener('DOMLoaded', play);

    return () => {
      deregisterEvents(anim, eventListeners);
      anim.removeEventListener('DOMLoaded', play);
      anim.destroy();
    };
  }, [animationData, autoplay, eventListeners, loop, name, segments, speed]);

  return <div {...props} ref={container} />;
};
```

and a controller component that updates Animation component with a new animation json whenever the previous one finishes
```
const AnimationController = styled(({ className }) => {
  const [currentAnimation, setAnimation] = useState(0);
  const { loop, data, segments, speed, name } = animations[currentAnimation];

  const options = useMemo(
    () => ({
      loop,
      // animationData is mutated everytime it's loaded
      // https://github.com/airbnb/lottie-web/issues/1702#issuecomment-508553873
      animationData: JSON.parse(JSON.stringify(data)),
      segments,
      name,
    }),
    [segments, name, data, loop]
  );

  const listeners = useMemo(
    () => [
      {
        eventName: 'complete',
        callback: () => {
          setAnimation((currentAnimation + 1) % animations.length);
        },
      },
    ],
    [currentAnimation]
  );

  return (
    <Animation
      speed={speed}
      className={className}
      options={options}
      eventListeners={listeners}
    />
  );
})
```

**Comment by bodymovin** [comment]
Hi, I'd need the original project or a link where I can check the triggered error
