### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by Maximepzv** [airbnb/lottie-web#1776]
Hello!
I've an animation who looks great in After Effect but I'm running into an issue when rendering using Bodymovin.

I'm using After Effect's expressions in the project because I need this file to be data driven compliant.
I plan to use it in the browser for a live preview of the animation with specific data chosen by the user.
All my expressions starts with 'use JavaScript', I don't really know if it's changing anything but I thought it may prevent parsing errors from the plugin.

A ZIP archive of my After Effect project can be found here
[Archive.zip](https://github.com/airbnb/lottie-web/files/3541017/Archive.zip)

It also contains the JSON and demo HTML file produced by Bodymovin, a screenshot from the Bodymovin's settings and another pointing the rendering problems.
Two shapes of rectangles are missing and a third shape has a resize problem during the animation.

Is there any way to fix this ?

* **Browser and Browser Version: Chrome 76.0.3809.100 (Build officiel) (64 bits)**
* **After Effects Version: 16.0.1 (Build 48)**
* **Bodymovin Version: 5.5.7**

@Maxou44

**Comment by Danjuanlab** [comment]
Split the rectangular background into two shape layers and use an expression to match the size. The overlay in your source file will cause the second rectangular shape dont get the width and height. Since the second rectangle has a <g> tag width of 0 when rendering, you can't see it.

**Comment by Maximepzv** [comment]
Thanks for your help, so I splited the rectangular background into two shape layers.
Linking expression of the second to match with the first.
Unfortunatly it change nothing. It still renderer with 0 width.
Here is the aep file updated: [Archive.zip](https://github.com/airbnb/lottie-web/files/3545101/Archive.zip)

**Comment by kudanai** [comment]
Hello. I'm closing this issue as it's been stale for some time. If this problem persists in a more recent version, please re-open it or file a new issue.
