### ISSUE TITLE
I'd like to know what's supported by bodymovin and what's not in this animation!

### ISSUE THREAD

**Issue by saraosama49** [airbnb/lottie-web#1781]
**Tell us about your environment** I am a UI/UX designer at a startup.

* **Browser and Browser Version:** Safari: Version 12.1.2 (14607.3.9)
* **After Effects Version:** Version 16.1.2 (Build 55)

**What did you do? Please explain the steps you took before you encountered the problem.**
I am exporting this intro with bodymovin but when i preview it, nothing happens there. I would like to know what features exactly that i'm using that aren't supported at the moment, and if there are any workarounds that i can use.

**Please provide a download link to the After Effects file that demonstrates the problem.**
[Intro.zip](https://github.com/airbnb/lottie-web/files/3564970/Intro.zip)

**Comment by Danjuanlab** [comment]
http://airbnb.io/lottie/#/
https://github.com/airbnb/lottie-web/wiki
Here you can find the information you want.

**Comment by saraosama49** [comment]
@Danjuanlab 
Thank you again!
According to this, the effects i'm using are supported. 
Does having expressions written prevent the whole animation from playing properly?

**Comment by saraosama49** [comment]
I removed the expressions, and on the renderer before exporting, the animation is still not playing..

**Comment by saraosama49** [comment]
This is how it loads on the renderer ..

<img width="942" alt="Screenshot 2019-09-02 at 11 36 59" src="https://user-images.githubusercontent.com/54717005/64105204-0b3ea280-cd76-11e9-9287-b8d64f42b4db.png">

**Comment by Danjuanlab** [comment]
> This is how it loads on the renderer ..
> 
> <img alt="Screenshot 2019-09-02 at 11 36 59" width="942" src="https://user-images.githubusercontent.com/54717005/64105204-0b3ea280-cd76-11e9-9287-b8d64f42b4db.png">

CC ball action is not support by now.All particle effects are not supported. Close the particle layer to export then the animation will be fine.

**Comment by saraosama49** [comment]
@Danjuanlab thanks a lot!

**Comment by Danjuanlab** [comment]
> @Danjuanlab thanks a lot!

You are welcome, you can check out the common mistakes and solutions for making SVG animations in lottie that I wrote. I believe you can help you debug errors better.[check here](https://www.ui.cn/detail/478730.html)

**Comment by kudanai** [comment]
You can also use the LottieFiles plugin, which has a feature-check that can help you diagnose unsupported features on export.

for a better look at supported features, please refer to [https://canilottie.com/](https://canilottie.com/)
