### ISSUE TITLE
Gradient Issues on Logo export

### ISSUE THREAD

**Issue by DenneyDesign** [airbnb/lottie-web#1782]
**Tell us about your environment**
Graphic Designer at a Startup - I'm using a Mac 2017 27"

* **Browser and Browser Version:**
ChromeVersion 76.0.3809.100

* **After Effects Version:**
AfterEffects 16.1.2, BodyMovin 5.5.7

**What did you do? Please explain the steps you took before you encountered the problem.**

First time around I imported AI files and converted them to paths, upon which I did a Trim Path animation and applied gradients to the strokes.

Because there was issues with this, I did a similar thing, but I included the original AI files as well as the path versions and did an Alpha Matt on the AI files and hid the path versions.

**What did you expect to happen?**
I expected it too animated in full but there were issues.

**What actually happened? Please include as much _relevant_ detail as possible.**
On the first attempt, the round ended caps of the paths became chopped off and some of the rest of the animation was chopped off, as if there was a mask on it. This happened both on the HTML demo and WP plugin and only happened when I applied the gradient, it works fine when it's a solid colour.
<img width="779" alt="Gradient Path Bodymovin WP Plugin" src="https://user-images.githubusercontent.com/54811599/64125547-39d27280-cda2-11e9-92c3-811979223466.png">

On the second attempt, the HTML demo worked perfectly and worked on Lottie as well, but didn't work on the WP plugin....the left-hand stem completely disappeared, the shape became 100% transparent and revealed a weird background behind it of which I have no idea where it came from.
<img width="763" alt="AI Bodymovin WP Plugin" src="https://user-images.githubusercontent.com/54811599/64125648-a2b9ea80-cda2-11e9-8ba7-0490ca4fab43.png">

**Please provide a download link to the After Effects file that demonstrates the problem.**
Here is the file, which I changed to Luma Matts at a last attempt to try and fix it, but to no avail.

https://drive.google.com/file/d/1SYwBqIRZ3XcAe1XMVvZM2VjrgRmz88_r/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, the second screenshot looks like it didn't find the image assets, can you check if they are in the right folder?
Regarding the first attempt with trim paths, can you share the .aep?

**Comment by DenneyDesign** [comment]
Hello, thanks so much for your response. 

As regards the image assets, I haven't moved them since I imported them, is there a certain folder that they have to be in? 

I did attach a Drive link, but incase it isn't working, i've attached the collected files in a Zip file.

[20190814_BeMyEye_App Logo Animation.zip](https://github.com/airbnb/lottie-web/files/3566700/20190814_BeMyEye_App.Logo.Animation.zip)

Thanks!!

**Comment by DenneyDesign** [comment]
Sorry, i've just double checked that and it seems to be empty, try this one. 
[20190814_BeMyEye_App Logo Animation EDITABLE V3.aep.zip](https://github.com/airbnb/lottie-web/files/3566710/20190814_BeMyEye_App.Logo.Animation.EDITABLE.V3.aep.zip)

**Comment by DenneyDesign** [comment]
OK, managed to solve this. I was using transparency on the paths to achieve the gradients. After reading up I replaced these transparency's with solid colour gradients to achieve the same effect. Weirdly, an overall transparency on a "transform" section of the path works fine, but not on a gradient.
