### ISSUE TITLE
Image exceeds composition boundary in Canvas renderer in 5.5.7 and 5.5.8

### ISSUE THREAD

**Issue by kfitfk** [airbnb/lottie-web#1783]
**Tell us about your environment**
Mac OS X 10.14.6

* **Browser and Browser Version:**
Google Chrome   76.0.3809.132

* **After Effects Version:**
After Effects CC 2018 (15.1.2 Build 69)
Bodymovin 5.5.8

**What did you do? Please explain the steps you took before you encountered the problem.**
1 Create a composition, set its size to width=500 and height=500, name it "wrapper";
2 Create another composition, set its size to width=200 and height=200, name it "img";
3 Place an image whose size is 800x800 with anchor point (400,400) at 100% scale in the " img" composition;
4 Place the "img" composition to the center of the "wrapper" composition
5 Export the "wrapper" composition using bodymovin v5.5.8, with image embedded. Also creat an HTML demo file at the same time;
6 Modify the HTML file to use canvas renderer;
7 Open the HTML file in Google Chrome and see the results.

**What did you expect to happen?**
![The correct way of rendering](https://img.alicdn.com/tfs/TB1suOgeYj1gK0jSZFOXXc7GpXa-1280-800.jpg)

**What actually happened? Please include as much _relevant_ detail as possible.**
![The wrong way of rendering](https://img.alicdn.com/tfs/TB1SESbeVP7gK0jSZFjXXc5aXXa-1280-800.jpg)

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://ossgw.alicdn.com/creatives-assets/oss/uploads/2019/09/03/50f9ccd0-ce04-11e9-b870-557ae7551529.zip
BTW, this works as expected in the past using Bodymovin v5.4.3 and lottie-web v5.4.4.

**Comment by bodymovin** [comment]
Fixed! Thanks for reporting it.
version 5.5.9
