### ISSUE TITLE
Dynamic resources

### ISSUE THREAD

**Issue by RWOverdijk** [airbnb/lottie-web#1784]
Hey!

I love lottie and everything it solves, but with all these new things I can do I have new questions.

One thing I've been trying, is to get dynamic resources in my lottie file. For example, I have a QR code that will be shown inside of the animation but I need to generate it before playing the.. video? animation? Whatever the terminology is.

Question 1: Is this possible? It's key that every play has a unique QR code.
Question 2: Long shot, but... Is it possible to make elements "clickable"? Even if it's with javascript, I'd be fine with that. That way I could make the whole website in AE and add links for inline animated components afterward.

**Update:** Sorry if these are dumb question. I hesitated a lot before asking them here. I just want to make cool things 😄

**Comment by Danjuanlab** [comment]
Your idea can be done.
First you rename your image when making the animation, such as ".QRcode". This will cause the animation to generate a property of 'class="QRcode" when rendering, and then you can replace the image's SRC with JavaScript.
https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript

**Comment by RWOverdijk** [comment]
And if that happens I could do the same to make elements clickable I guess. 

Awesome! Thanks a lot.
