### ISSUE TITLE
Big differences between render's result [bodymovin] and the actual preview

### ISSUE THREAD

**Issue by mohamedashrafkamal** [airbnb/lottie-web#1786]
![2019-09-04-23-01-03](https://user-images.githubusercontent.com/39669066/64291556-bdd65700-cf68-11e9-92e9-670bc69a8835.gif)

How to solve this issue? please advice

Ae version: CC 2019
Bodymovin -version: 5.5.8

Note: the delay in the attachment due to recording offset

**Comment by mashraf-github** [comment]
Ae project source file:
[Modern_Text_Animation.zip](https://github.com/airbnb/lottie-web/files/3576599/Modern_Text_Animation.zip)

**Comment by Danjuanlab** [comment]
Unfortunately, gradient mapping and fast box blur are not currently supported. You can add gradients to shapes or text and then use Gaussian blur to do what you want. Please read the contents of the wiki first to avoid using unsupported presets.
