### ISSUE TITLE
Bodymovin AE color profile rendering problem.

### ISSUE THREAD

**Issue by fiftar1810** [airbnb/lottie-web#1787]
Hi everyone, recently I had a problem with color rendering and color profile when I’ve tried to export animation from Adobe After Effects.

Have a look at the red hands of the hero - this is a bright juicy red color. [[View picture 1]](https://drive.google.com/file/d/1y66Kf-Z7-gPQqpIdAdeVgQfRCnMzKdGZ/view?usp=sharing)
When I made an animation of the characters and opened it in Lottie Player - The color of the hands CHANGED! It became much brighter and darker. [[View picture 2]](https://drive.google.com/file/d/1y52ULbl3VI8dRB03xOis3U32rkpIPZnu/view?usp=sharing)

The color profile in After Effects is configured correctly. It only becomes faded when I move to it through the body.

How can i solve this problem?

**Comment by Danjuanlab** [comment]
Can you share this Aep file?

**Comment by fiftar1810** [comment]
> Can you share this Aep file?

Yes, upload on Google Drive https://drive.google.com/file/d/1yYazamhpfbV7eXdfJ3uxlaKlUxlpdb1_/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, unfortunately browsers don't support setting color profiles other the sRGB.
There are standards defined but haven't been implemented yet.
