### ISSUE TITLE
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by sogorgor** [airbnb/lottie-web#1789]
Why is it wrong to export JSON from AE using the new version 5.58 of body movin: Error in mounted hook: "TypeError: Cannot read property'0'of undefined"

**Comment by ramusarithak** [comment]
version problem

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
