### ISSUE TITLE
wave.. or gzip?

### ISSUE THREAD

**Issue by juanbuscarons** [airbnb/lottie-web#1791]
Hey Hernan!
first, thank you for all the help you've been giving the Bodymovin users for this whole time! 
the improvement your extension (and your help for using it) on our business is MASSIVE
huge thanks!

now here's my question...
I did this project animating a waving line left to right and passing through some characters in After Effects (16.1.1) and export it with Bodymovin (5.5.3)
(I know, lots of keyframes in there since I can't use wave warp nor Omino Snake to make that.. so I create the whole wave by hand)

the client needs this in .json so they could put it in their website and/or app
I'm a motion designer so I have absolutely no clue on passing it through Gzip
what would you recommend? right now the jsons (2) sizes are 260kb and 650kb and it's too much for them

THANKS A TON!
Juan

[waves.zip](https://github.com/airbnb/lottie-web/files/3584185/waves.zip)

**Comment by bodymovin** [comment]
Hi, it's probably your client who should upload the files gzipped to their server, of configure them to be served gzipped when requested by browsers.
If they intend to use it for an app, when compiled they will automatically get compressed.

**Comment by juanbuscarons** [comment]
Ok I don’t know exactly what that entails hehe
but I’m gonna send them your answer 
Thanks a lot and hope this helps!
Juan
