### ISSUE TITLE
Weird overshoot & rotation glitches? (Bodymovin/AE) Edit: Overshoot fixed, Rotation-issue persists

### ISSUE THREAD

**Issue by eCronik** [airbnb/lottie-web#1792]
Hey there,

first off, thanks for this awesome toolset! :) I am experiencing two issues I can't yet explain myself – hope that somebody can help me out.

(Only reduced to the essential shape layers used, some Nulls for parenting, no layer styles/effects)

1: I am trimming a path and have an arrowhead attached to it. For some reason, the trimming overshoots at some point in the Bodymovin-render even though it looks fine in AE. What could be causing this?

2: Some elements seem to be having a weird rotation glitch at their last keyframe (eased-in). Also looks fine in AE.

Thanks a bunch and best regards,
eC

**Comment by bodymovin** [comment]
@eCronik hi, can you share the .aep?

**Comment by eCronik** [comment]
@bodymovin Thanks for your rapid reply! :) Attached you'll find the .aep

- Comp 1 render seems to have rotation+overshoot issue 

- Com 2 render seems to have overshoot issue

- Comp 3 render seems to have overshoot issue (odd, some renders have it here some not)


Thanks for your help!

[Bodymovin_Glitch.zip](https://github.com/airbnb/lottie-web/files/3584485/Bodymovin_Glitch.zip)

**Comment by eCronik** [comment]
Hey, I've reduced the project file to the Comp with the most significant rotation issue, got rid of everything unnecessary, so reupload.

[Bodymovin_Glitch2.zip](https://github.com/airbnb/lottie-web/files/3595226/Bodymovin_Glitch2.zip)

Hoping somebody has an idea why the arrowheads rotate so weirdly after their last keyframe and how to fix/work around it.


Thanks a bunch and best regards,
e

**Comment by kudanai** [comment]
Hey there. I'd like to close this issue for now since it's been stale for a while. Please re-open it if you feel it is still relevant.
