### ISSUE TITLE
Better color editor

### ISSUE THREAD

**Issue by magna25** [airbnb/lottie-web#1794]
Hey guys,
I just put up a simple web tool to edit the colors of an animation and just wanted to share here.
It supports grouping the colors by layer name then shape name, pause/play controls, allows for redo/undo history.

check it out here: https://magna25.github.io/lottie-editor/

**Comment by Danjuanlab** [comment]
Good job！

**Comment by kudanai** [comment]
Hello! Thank you for the editor and contribution to the Lottie ecosystem! Could you maybe open an issue on [https://github.com/LottieFiles/awesome-lottie](https://github.com/LottieFiles/awesome-lottie) so it could possibly be added there?

I'd like to close this issue for now as it's been sitting stale for a while. Please re-open if you like.
