### ISSUE TITLE
Export animation with png

### ISSUE THREAD

**Issue by Lillo08** [airbnb/lottie-web#1795]
After Effect 2017 CC
Bodymovin 5.5.8

Hi, I have used Bodymovin to export my After Effects project in Json. 
My file is composed of 4 lines (red, as you can see in the image) and 2 png.
When I export the file I can see only the animation created by the 4 lines. PNGs don't work, as you can see in the other image.
What do I have to do?
Thanks

![Screenshot 2019-09-09 22 43 34](https://user-images.githubusercontent.com/55111307/64565128-6151ae00-d353-11e9-89e7-9c6bcde75b52.png)
![Screenshot 2019-09-09 22 43 43](https://user-images.githubusercontent.com/55111307/64565171-79293200-d353-11e9-88d6-321dc1acf975.png)

**Comment by Danjuanlab** [comment]
![image](https://user-images.githubusercontent.com/42509669/64577959-8cb6b600-d3b0-11e9-9f47-bdcd26ffc0cb.png)

**Comment by Lillo08** [comment]
Thank you, it works!!
