### ISSUE TITLE
In lottie.js iam getting the error

### ISSUE THREAD

**Issue by sankarsans** [airbnb/lottie-web#1797]
In my website, I am using lottie.js, but in the console, I am getting an error like - Uncaught TypeError: Cannot read property '0' of undefined.
This is the file what I have used.
**js file:**
 var params = {
        container: document.getElementById('Welcome'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        animationData: animationData
    };
    var anim;
    anim = lottie.loadAnimation(params);

**Json file:**
<script type="text/javascript" src="js/json/Welcome.json"></script>

**lottie.min.js file:**
https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.4.3/lottie.min.js

I tried to fix this but I can't able to do.
Anyone, please help me to fix this.

**Comment by bodymovin** [comment]
Hi, can you share a link to reproduce the error?
