### ISSUE TITLE
Export from Bodymovin is blank -  iOS App

### ISSUE THREAD

**Issue by mparrish91** [airbnb/lottie-web#1803]
I am unable to view my animation in my iOS app. When I run the app the screen is completely blank where the animation should be.

I successfully exported from bodymovin and am accessing the json file in my Xcode project.  I am able to run other animations using Lottie in my XCode app so I know I am doing something  wrong with my animation.

I have attached the AEP file below.  
[Link](https://www.dropbox.com/s/vkj79zo6xyaddlk/Robot%20Animation.aep?dl=0)

Thank you

**Comment by bodymovin** [comment]
Hi, images are missing.
But if the problem only happens with the ios player, can you post the issue here?
https://github.com/airbnb/lottie-ios

**Comment by mparrish91** [comment]
yes thank you I will post there!
