### ISSUE TITLE
Lottie animation not working properly in browsers except for firefox

### ISSUE THREAD

**Issue by devv-il** [airbnb/lottie-web#1806]
**Tell us about your environment**
I am using a windows machine, visual studio code, and adobe after effects

* **After Effects Version:**
after effects 2017

**What did you do? Please explain the steps you took before you encountered the problem.**
In the visual code live server, the animation was working perfectly. Once I hosted the website, some issues started happening. You can look at the website at https://happy-noether-f484bb.netlify.com/ . The animation loads up differently for different browsers.  Though, It works best or perfectly for firefox.

Find the attached after effects file and .json file.
Hope to get this resolved soon.
Thank you

[rendered.zip](https://github.com/airbnb/lottie-web/files/3664306/rendered.zip)

[Mentord animation.zip](https://github.com/airbnb/lottie-web/files/3664304/Mentord.animation.zip)

**Comment by bodymovin** [comment]
Hi, you have in your css set for all your elements:
```css
transitional-property: all;
    /* -webkit-transition-duration: .6s; */
     transition-duration: .6s;
    /* -webkit-transition-timing-function: ease; */
    /* transition-timing-function: ease;
```
that makes all properties to transition when values change.
That affects any property in any element in your page when values change.
Besides the animation itself, you probably shouldn't do that since it's not good for performance.

**Comment by devv-il** [comment]
Thank you so much!
That was so helpful. You're a life saver
