### ISSUE TITLE
Bodymovin not rendering my animation correctly. Animation in Ae doesn't match rendered animation.

### ISSUE THREAD

**Issue by jzfcb** [airbnb/lottie-web#1808]
I created an animation in After Effects (Version 16.1.3 Build 5 | CC 2019) that plays well inside of After Effects. Here is a gif of the animation in after effects:

![AE-anim-example](https://user-images.githubusercontent.com/55997492/65903473-53e77c80-e371-11e9-8226-f789512adadb.gif)

Here is a screenshot of my composition, shape layers and key frames:

<img width="1509" alt="Screen Shot 2019-09-30 at 10 47 38 AM" src="https://user-images.githubusercontent.com/55997492/65903494-5d70e480-e371-11e9-987c-dc69f56c2550.png">

However, once rendered and exported with Bodymovin, this is the result:
![BM-anim-example](https://user-images.githubusercontent.com/55997492/65903882-133c3300-e372-11e9-9ae2-83a44c2bd14f.gif)

In the example, I'm controlling the scrubber because it's not autoplaying, also the arrow became displaced and is not animating correctly. The face is animating in reverse as well.

I can't figure out why this is happening, the animation doesn't contain any crazy effects.

**Comment by bodymovin** [comment]
Hi, can the share the .aep?

**Comment by jzfcb** [comment]
> Hi, can the share the .aep?

Sure! 
[enrollment animation.aep.zip](https://github.com/airbnb/lottie-web/files/3672650/enrollment.animation.aep.zip)

**Comment by bodymovin** [comment]
I've found the issue. It's related to having auto oriented layers with no keyframes on positions.
It will be fixed on the next deploy.

**Comment by jzfcb** [comment]
> I've found the issue. It's related to having auto oriented layers with no keyframes on positions.
> It will be fixed on the next deploy.

Thanks so much for the quick response! In the meantime, is there any possible workarounds for this?

**Comment by bodymovin** [comment]
if you uncheck the auto-orient property from layers that don't need it it should work fine

**Comment by jzfcb** [comment]
> if you uncheck the auto-orient property from layers that don't need it it should work fine

Awesome, that worked! Thank you!

**Comment by makerhas** [comment]
I created an animation in After Effects (Version 22.6) that plays well inside of After Effects. But when Export in json format through bodymovin plugin its not work properly

**Comment by FEE9LOOH** [comment]
https://github.com/airbnb/lottie-web/assets/144218514/1613524a-287b-475b-9409-9527a88bfef4


hi this AE File & not show the effect of the check !!!

https://github.com/airbnb/lottie-web/assets/144218514/fe5baf6e-d27e-482d-a8fa-654ea2bfb948


please Help me
