### ISSUE TITLE
Can't load all the images from bodymovin to lottie

### ISSUE THREAD

**Issue by emilyho88** [airbnb/lottie-web#1813]
**Tell us about your environment**
I am trying to export my after effects animation as a .json file through bodymovin and lottie. After converting all my .png to components (because when I did not, none of the .png for my animations loaded), most elements loaded except my bottom menu and cursor would not load. I tried converting all my .png in Adobe XD to components (symbols) and that fixed most of the problems but the bottom menu and the cursor symbols are not loading on the lottiefile preview.I need urgent help on this thank you! 

* **Browser and Browser Version:**
* **After Effects Version:**
16.1.3
**Please provide a download link to the After Effects file that demonstrates the problem.**
<img width="1680" alt="Screen Shot 2019-10-03 at 5 42 09 PM" src="https://user-images.githubusercontent.com/56141188/66173470-287cc000-e605-11e9-9432-b715983053e3.png">
<img width="1680" alt="Screen Shot 2019-10-03 at 5 41 46 PM" src="https://user-images.githubusercontent.com/56141188/66173471-287cc000-e605-11e9-882d-795b57ee6eb4.png">
<img width="1680" alt="Screen Shot 2019-10-03 at 5 41 23 PM" src="https://user-images.githubusercontent.com/56141188/66173472-287cc000-e605-11e9-8ea5-b813371e1bea.png">
<img width="1680" alt="Screen Shot 2019-10-03 at 2 55 21 PM" src="https://user-images.githubusercontent.com/56141188/66173473-287cc000-e605-11e9-89dc-48eaa5a24219.png">

**Comment by bodymovin** [comment]
hi, can you share the .aep?
