### ISSUE TITLE
Merged paths render

### ISSUE THREAD

**Issue by blottere** [airbnb/lottie-web#1817]
I created an animation with multiple layers of shapes.  All of these consist of merged paths and all of them seem to be rendering fine. I have a couple of shapes in there that are combined shapes. They don't seem to be rendering right. Anyone have any idea on if we have a fix for this, or what I might have to do differently?

The after effects animation
![image](https://user-images.githubusercontent.com/10476512/66349851-a8a96b00-e90e-11e9-862c-4dc13a868ee8.png)

The render
![image](https://user-images.githubusercontent.com/10476512/66349910-caa2ed80-e90e-11e9-879e-850eab4b61b1.png)

**Comment by bodymovin** [comment]
Hi, merge paths are not supported by the player unfortunately

**Comment by blottere** [comment]
Gotcha, I figured a work around by recreating the pieces as separate individual paths. Thank you!
