### ISSUE TITLE
No animation after replacing data.json

### ISSUE THREAD

**Issue by PrzemoDev** [airbnb/lottie-web#1824]
**Tell us about your environment: Widows 10**

* **Browser and Browser Version: Chrome (77.0.3865.90)**
* **After Effects Version: Latest CC**

I exported simple animation to json file (in AE i can toggle it - it's fine). Then I used template files from your code pen ("bodymovin" animation is working on a local project). Next, I replaced data.json with my simple data.json file. 

I Though it should display my animation.but there's only wite background (css file works)... I'm out of ideas what's wrong ... I used tutorials on web etc. 

[test.zip](https://github.com/airbnb/lottie-web/files/3724990/test.zip)

**Comment by bodymovin** [comment]
Hi, can you share a link with the full implementation?

**Comment by PrzemoDev** [comment]
Yeah, sure. 
[test.zip](https://github.com/airbnb/lottie-web/files/3725049/test.zip)

**Comment by bodymovin** [comment]
Sorry, I mean a link online I can check

**Comment by PrzemoDev** [comment]
Ok, I just move all code here: https://repl.it/repls/DroopyAntiqueLists Let me know is it working

**Comment by bodymovin** [comment]
You are loading a very old version of lottie (v4.6.3) and the animation is exported with a newer version (v5.5.8)
Can you try using a newer version?
https://cdnjs.com/libraries/bodymovin

**Comment by PrzemoDev** [comment]
Oh yeah, it worked! Thank You.
