### ISSUE TITLE
Using video files in animations. Is it possible to export using lottie/bodymovin?

### ISSUE THREAD

**Issue by clm93** [airbnb/lottie-web#1825]
I'm trying to use low res video files (.mp4s H264) inside my animations. Is there a way to do this and export using the bodymovin plugin in the same way that it exports images into an image folder?

**Comment by bodymovin** [comment]
Hi, unfortunately this is not in the pipeline for now.
Depending on what you need, you might be able to leverage it by changing an element from the animation with a video and syncing it manually.

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
