### ISSUE TITLE
Nuxt Support with SSR?

### ISSUE THREAD

**Issue by YanDevDe** [airbnb/lottie-web#1827]
I'm currently trying figuring out how to support this thing in nuxt per SSR. According #440 it should be working.

But so far on my project with nuxt, the lottie are still rendered at client side yet.
I'm using lottie-web on latest version. Maybe there is a configuration or something like that for nuxt?

**Comment by YanDevDe** [comment]
It would be good if the svg or html renderer are pre-rendered at server side before the animation plays at client side. 🤔

**Comment by bodymovin** [comment]
Hi, I don't have much experience with nuxt, but are you looking for the first frame of the animation to be prerendered server side?

**Comment by YanDevDe** [comment]
@bodymovin yup!

**Comment by bodymovin** [comment]
I guess it won't work because on the server document methods to create DOM elements wouldn't be exposed

**Comment by YanDevDe** [comment]
Ah, yup that make sense that document/window are not available at server side.

I think there might be, more complicated, ways to prerender the first frame of the animation. 

Maybe adding a function such like "this.anim.getRenderAtFrame(frameIndex)" where we can get string of html/svg from selected frame index? (Or just the first frame) So then we can inject by ourself in the server side.

For Canvas, maybe this.anim.getRenderAtFrame(frameIndex) will just return it as image/base64/buffer  so then it can be used for preview-image before the real canvas plays the animations.

Example:

```js
const anim = lottie.loadAnimation({
  container: element,  //Ignored at server side, when document/window is not available.
  renderer: 'svg',
  loop: true, //Ignored at server side, when document/window is not available.
  autoplay: true, //Ignored at server side, when document/window is not available.
  animationData: animationData, // the animation data
});

const AnimationPreview = anim.getRenderAtFrame(frameIndex);

// Inject the AnimationPreview (based on SVG string) by yourself at server side. As quick example:

HtmlPage = HtmlPage .replace("{{animationPreview}}", AnimationPreview);
```

I hope you understand what I mean 😄

**Comment by bodymovin** [comment]
Once you loaded the animation do you need a  separate preview? You can pause it in the first frame and it would work as a preview.
If you want a snapshot of the animation before the animation and the player load, you probably need to have a separate asset for it. In this case you can use the preview of the AE extension and save a snapshot.

**Comment by YanDevDe** [comment]
The animation may be loaded on server side, but it is useless at the moment because there is no document/window available. So therefore I can't just simply pause the animation and use the preview on server side. Because animation doesn't exists at all due missing window/document.

Thats why `anim.getRenderAtFrame(frameIndex);` comes in play -> You can get the html/svg string where you can inject yourself at server side before the client plays the animation.

I'm currently having the issue that the client is not showing animation for like 1-2 seconds until the DOM is ready to use/loaded. So I'm getting a huge white blank space for 1-2 seconds until animation plays.

See the following example when I'm refreshing the page with F5 ->

![ppW6XUOLkW](https://user-images.githubusercontent.com/1526048/67486434-4f5e6d00-f66c-11e9-9586-8c23b2ec683d.gif)

Using snapshot from AE extension is actually a smart idea. But it is a image which is useless for server renderer because image can be only loaded at client side. SVG/HTML can be already rendered on server side which also allows.

But I'll use raw .svg file which I was working on AE as fallback/preview then. Didn't though about that one. 😄  Still thank you for your time.

**Comment by YanDevDe** [comment]
Btw, the animation are actually loaded twice, it load at server-side and it load again at client-side. Expect that the server-side it is useless since it doesn't have window/document. That's why getting preview/snapshot from server-side could be cool to have.

**Comment by bodymovin** [comment]
so to clarify, when I was talking about snapshot, I meant the bodymovin snapshot feature that exports an svg. Wouldn't that work?

Regarding the getRenderAtFrame, are you thinking of some sort of `document` polyfill that would implement the document methods and return a string that represents the html structure?

**Comment by YanDevDe** [comment]
Ah, didn't know that it exports to svg. Thats nice 😄 I'll use that then 👍
