### ISSUE TITLE
Bodymovin Pause and Play Three Actions-Question

### ISSUE THREAD

**Issue by hanz-ss** [airbnb/lottie-web#1834]
Hello, This is my first time at git.

I'm very new to code..sorry. Which I believe hopefully my questions is a basic one.I love bodymovin is a great plugin.

Here is my pickle... I have animation where I need to create pauses and then play after few seconds. 

ex. 
start on keyframe 1 
then pause on 20, then play and pause on keyframe 30.
repeat for 30-40 and 40-50.

In total they are three pauses. I look at the conversations regarding for segments but that creates loops on certain parts. All I need is a stop and play. 

Thank You.

**Comment by bodymovin** [comment]
Hi, you can call the methods stop() and play() of the animation instance after you load it.
Or if the pauses are all the same, why don't you add them directly in After Effects?

**Comment by hanz-ss** [comment]
Thanks for responding.

1. Option 1 that you mentioned call methods stop() and play(). Could you provide how the code would be written.

2. Do you mean to use expression in after effect. Will bodymovin be able to export the codes.

My goal is that the animation I have is quite long. I'm trying to find a way to reduce file size data best as possible. I figure adding stop and play will reduce seconds of animation significantly.

**Comment by hanz-ss** [comment]
> Thanks for responding.
> 
>     1. Option 1 that you mentioned call methods stop() and play(). Could you provide how the code would be written.
> 
>     2. Do you mean to use expression in after effect. Will bodymovin be able to export the codes.
> 
> 
> My goal is that the animation I have is quite long. I'm trying to find a way to reduce file size data best as possible. I figure adding stop and play will reduce seconds of animation significantly.

**Comment by bodymovin** [comment]
File size is not affected by the duration of your layers, it's mostly affected by the amount of layers, amount of keyframes and complexity of your shapes.
So if you precompose your animation and change the duration of them by using time remapping for example, its size will be almost the same.

**Comment by hanz-ss** [comment]
Got it! 

I appreciated the fast responds and thanks again for your support and work.

I'll see how what solution I can come up with my pickle. 

Best,
Hanz
