### ISSUE TITLE
Radial Wipe Effect issue

### ISSUE THREAD

**Issue by tomektomczuk** [airbnb/lottie-web#1835]
Hi I've noticed that Radial Wipe standard effect from After Effects is not rendering correctly when Transition Completion change percentage.

**Comment by bodymovin** [comment]
Hi, unfortunately radial wipe is not supported for now.
Some people use a stroke and trim path to get a similar effect  as a workaround.

**Comment by kudanai** [comment]
Hi there. I'm closing this issue for the time being, since it's been stale for a while and there have been a significant number of updates. Please feel free to re-open it or file a new issue.
