### ISSUE TITLE
Lottie web player does not work with Internet Explorer

### ISSUE THREAD

**Issue by TiwariShubham** [airbnb/lottie-web#1837]
**Tell us about your environment**
Windows 10, 64 Bit

* **Browser and Browser Version:** IE-11
* **After Effects Version:** N/A

**What did you do? Please explain the steps you took before you encountered the problem.**

I injected the lottie web player in the HTML, with the below snippet:

```
 <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player  src="https://assets9.lottiefiles.com/datafiles/MUp3wlMDGtoK5FK/data.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop  autoplay >
</lottie-player>
```

**What did you expect to happen?**

It should have shown animation like this, which works in Chrome, Firefox and Safari

<img width="1364" alt="Screen Shot 2019-10-25 at 3 34 09 pm" src="https://user-images.githubusercontent.com/8822599/67543482-50ab9a80-f73d-11e9-822a-17be986727c5.png">

**What actually happened? Please include as much _relevant_ detail as possible.**
It showed like this in IE-11

<img width="1377" alt="Screen Shot 2019-10-25 at 3 33 51 pm" src="https://user-images.githubusercontent.com/8822599/67543485-56a17b80-f73d-11e9-910c-24e613ce7817.png">

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, the lottie player web component is maintained by the lottie files team. Can you share this with them?
https://lottiefiles.com/

**Comment by TiwariShubham** [comment]
Thank you for coming back, that's not good for me as I can't find a way to report to them.
