### ISSUE TITLE
Remora Sans and other G type fonts render incorrectly

### ISSUE THREAD

**Issue by nathanwibbitz** [airbnb/lottie-web#1839]
**Tell us about your environment**
* **Browser and Browser Version: Chrome 78.0.3904.70**
* **After Effects Version: 2019 (16.1.2)**

**What did you do? Please explain the steps you took before you encountered the problem.**
Exporting a text inside a paragraph with a specific font (G type) causes lottie player to remove spaces and the font looks different from the way it looks in After Effects. 

**What did you expect to happen?**
Font is expected to look like in After Effects.
Left side is Lottie result and right side is After Effects.
The top text is without using a paragraph and the bottom is with paragraph.
![](https://wbtz-test.s3.amazonaws.com/afx.png)

**What actually happened? Please include as much _relevant_ detail as possible.**
Font is missing spaces.
Please note in other fonts it works well.
It seems there's a problem with g type fonts (https://fonts.adobe.com/foundries/g-type)

**Please provide a download link to the After Effects file that demonstrates the problem.**
AEP: http://wbtz-test.s3.amazonaws.com/textDynamic_18_000.aep
Bodymovin: https://wbtz-test.s3.amazonaws.com/lottie-demo.json
Remora Sans font: http://wbtz-test.s3.amazonaws.com/remora-sans.otf

Thank you! :)

**Comment by bodymovin** [comment]
Hi, the json filed you shared doesn't seem complete so I couldn't check that file.
But I did try to export it myself and it seemed to work fine, as long as the font was already loaded when the animation is loaded.

**Comment by nathanwibbitz** [comment]
@bodymovin thanks! Did you export it with the text being in a paragraph?

**Comment by bodymovin** [comment]
yes, both text layers worked fine.

**Comment by nathanwibbitz** [comment]
@bodymovin Thank you.
Would you mind sharing the aep & the lottie result files so I can compare with mine to see what I doing wrong?

**Comment by nathanwibbitz** [comment]
@bodymovin Hi, I found the issue is caused by a line TextProperty.prototype.completeTextData
```
        if (currentChar === ' '){
            val = '\u00A0';
```
Some fonts are not implementing nbsp and this messes up the char measures.
If I'm changing to
```
        if (currentChar === ' '){
            val = ' ';
```
I'm getting better results and space is not being "lost" in the result.
Any ideas?

**Comment by bodymovin** [comment]
I'm changing this to use a regular space. I don't exactly remember the reason why I needed to use a non breaking space at that time. I think it was related to measuring spaces incorrectly.
But from my tests, things seem to work fine.
