### ISSUE TITLE
Bodymovin not rendering my animation correctly. Animation in Ae doesn't match rendered animation.

### ISSUE THREAD

**Issue by Gopinath6699** [airbnb/lottie-web#1840]
**Hi ! This Plugin is really awesome !!!**

**Google Chrome:** Version 78.0.3904.70 (Official Build) (64-bit)
**After Effects:** Version 15.0.0 (Build 180) 

**This is how it looks in After Effects:**
![issue](https://user-images.githubusercontent.com/53274915/67705983-039a2380-f9de-11e9-8cc9-d6024db9f537.gif)

**But this is how it got rendered:**
![issue 1](https://user-images.githubusercontent.com/53274915/67706435-c3877080-f9de-11e9-9df6-fce71e006ff4.gif)

Please help me ! I can't figure out what's wrong.

**Here is the After Effects File attachment:**
[Gyanith Logo 2.zip](https://github.com/airbnb/lottie-web/files/3780139/Gyanith.Logo.2.zip)

**Comment by Inventsable** [comment]
Hi, you'll need to check the [List of Features](https://github.com/airbnb/lottie-web/wiki/Features) and Effects in the wiki before using too ambitious of raster effects like displacement maps, which are not supported afaik.

**Comment by Gopinath6699** [comment]
Thank you !
