### ISSUE TITLE
Hover issue only in chrome

### ISSUE THREAD

**Issue by anna2890** [airbnb/lottie-web#1841]
* **Browser and Browser Version:**
CHROME 78.0.3904.70

* **After Effects Version:**
LAST

**What did you do? Please explain the steps you took before you encountered the problem.**
I HAVE ADDED A LOTTIE ANIMATION IN MY WEBSITE USING TAG LOTTIE-PLAYER, WITH PROPERTY HOVER

**What did you expect to happen?**
ON MOUSE HOVER ANIMATION STARTS

**What actually happened? Please include as much _relevant_ detail as possible.**
ON THE FIRST MOUSE HOVER THE ANIMATION MOVES DOWN, LIKE A LITTLE JUMP, AND THEN IT STARTS. THIS HAPPENS ONLY ON FIRST TIME, AFTER THAT ON MOUSE OVER IT STARTS NORMALLY. THIS HAPPENS ONLY IN CHROME

**Comment by bodymovin** [comment]
Hi, can you share a link to check the implementation?

**Comment by kudanai** [comment]
Hello! Since this issue has been stale for quite a while, I'm going to close it. Please re-open or file a new one if it's still relevant.
