### ISSUE TITLE
ERROR: updateDocumentData is not a function

### ISSUE THREAD

**Issue by NandiniNayak** [airbnb/lottie-web#1843]
@kayson and @bodymovin thanks for sharing the solution. When I try the code snippet shared by @kayson , it resolves the undefined error, instead I get ' Uncaught TypeError: anim.renderer.elements[0].updateDocumentData is not a function'. is updateDocumentData depricated?? ......please find my code snippet, also i have console logged to ensure I am targeting the right index.
```
  anim.addEventListener("DOMLoaded", function () {
      console.log("BFEORE:", anim.renderer.elements[0].currentTextDocumentData.t);
      anim.renderer.elements[0].updateDocumentData({
         t: 'w'
      });
      anim.play();
      console.log("AFTER:", anim.renderer.elements[0]);
  });
```
_Originally posted by @kayson in https://github.com/airbnb/lottie-web/issues/1040#issuecomment-389868079_

**Comment by bodymovin** [comment]
Hi, do you have a link with the implementation to check?

**Comment by NandiniNayak** [comment]
Hi @bodymovin, I have pushed code to github, here is the link [https://github.com/NandiniNayak/lottie-example](url).

The json example I have used is [https://lottiefiles.com/4142-welcome-animation](url)

**Comment by NandiniNayak** [comment]
@bodymovin : Could you please let me know if there is anything I am missing in using updateDocumentData function??

**Comment by bodymovin** [comment]
You are using a very old version of lottie (v4.6.3). Can you try updating it to the latest version?
You can get it from here:
https://cdnjs.com/libraries/bodymovin

**Comment by NandiniNayak** [comment]
@bodymovin . Thank you so much, version update worked for me, updateDocumentData function is now recognised :)... 

However I get a warning _"Missing character from exported characters list:  w Regular Impact_ ", and the page doesn't render the animation any more. I have used :[https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.9/lottie_svg.min.js.](https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.5.9/lottie_svg.min.js.) 

I have updated my code base on github, please find the link [https://github.com/NandiniNayak/lottie-example.](https://github.com/NandiniNayak/lottie-example.)

**Comment by kudanai** [comment]
Hi there. I'm closing this issue for the time being, since it's been stale for a while and there have been a significant number of updates. Please feel free to re-open it or file a new issue.
