### ISSUE TITLE
Precomp masking issue

### ISSUE THREAD

**Issue by btunick** [airbnb/lottie-web#1846]
Using precomps in an animation, it does export the precomp information but doesn't mask objects that are going off the artboard in the precomp. 

Is this a fixable issue or just something not supported yet?

**Comment by bodymovin** [comment]
Hi, what renderer are you using and what lottie version?

**Comment by btunick** [comment]
After effects version 16.1.3 (build 5)
bodymovin version 5.5.9

**Comment by bodymovin** [comment]
and renderer? svg or canvas?

**Comment by btunick** [comment]
not so sure about this to be honest, my engineer says "We are using lottie iOS library, we don’t really do anything with animations more than loading it from json file"

**Comment by bodymovin** [comment]
Can you post the issue on the lottie-ios repository? They will be able to help you better than here.
https://github.com/airbnb/lottie-ios
