### ISSUE TITLE
Latest web player version

### ISSUE THREAD

**Issue by foguetes** [airbnb/lottie-web#1849]

**Comment by bodymovin** [comment]
Hi, this issue is missing info

**Comment by foguetes** [comment]
Sorry, I submitted it by mistake.

The issue I found is that the lottie library available on the CDN does not include a permanent url to the latest version.

[This tool](https://lottiefiles.com/web-player), for example, provides a url to the latest version:
https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js

**Comment by bodymovin** [comment]
Unfortunately cdnjs doesn't support `latest` yet

**Comment by bodymovin** [comment]
You could use their API to get the latest version and then add the script:
https://api.cdnjs.com/libraries?search=lottie

**Comment by foguetes** [comment]
thanks
