### ISSUE TITLE
Point follow nulls doesn't work

### ISSUE THREAD

**Issue by foguetes** [airbnb/lottie-web#1850]
Lottie doesn't correctly render the Point Follow Nulls expression.

Here's an example. This is how the animation is supposed to look like.
https://streamable.com/6y4fh

And this is how is displayed in Lottie:
https://lottiefiles.com/share/siTxxK

The stroke does not move in the lottie version.

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by foguetes** [comment]
Here it is

[points follow null.zip](https://github.com/airbnb/lottie-web/files/3819771/points.follow.null.zip)

**Comment by bodymovin** [comment]
You need to include hidden layers on export. All nulls are hidden on the comp called `pierrot_logo_2019`

**Comment by kudanai** [comment]
Hello! Since this issue has been stale for quite a while, I'm going to close it. Please re-open or file a new one if it's still relevant.
