### ISSUE TITLE
Lottie window in AE

### ISSUE THREAD

**Issue by CoryHitching** [airbnb/lottie-web#1851]
I'm using MacBook Pro (Retina, 15-inch, Mid 2015) with the latest versions of AE.

My bodymovin window has disappeared from AE. I've tried turning the extension off and on, reinstalling bodymin and updating my OS and still the extension in AE is not appearing. Any help appreciated.

**Comment by bodymovin** [comment]
Hi, how are you installing the extension?

**Comment by CoryHitching** [comment]
Through Anastasiy's Extension Manager

**Comment by bodymovin** [comment]
can you try the zxp installer from aescripts
https://aescripts.com/learn/zxp-installer/

**Comment by kudanai** [comment]
Hello! Since this issue has been stale for quite a while, I'm going to close it. Please re-open or file a new one if it's still relevant.
