### ISSUE TITLE
Feature request: Export png sequences as APNG

### ISSUE THREAD

**Issue by foguetes** [airbnb/lottie-web#1852]
It would be great is Bodymovin could export image sequences as base 64 encoded animated pngs (apng) embedded in the json file.

Right now, there are compatibility issues with IE and older versions of Edge, but this library fixes those problems:
https://github.com/davidmz/apng-canvas

**Comment by bodymovin** [comment]
Can you provide a use case for this?
Since apngs don't have playback control, they would be off sync with the rest of the animation, thus unreliable to work

**Comment by foguetes** [comment]
This could be used for the integration of live footage, 3D animated footage, and all the elements that are available in after effects but are not supported or don't render properly in lottie. we could render these elements separately as png sequence and use them together with vector animation in lottie.

**Comment by bodymovin** [comment]
Couldn't this be solved with regular image sequences?
The apng format is not controllable programatically, so you won't have a reliable playback

**Comment by foguetes** [comment]
Sorry. You're right. Did not know Lottie could do that. I thought only static bitmaps were supported. Cool!
