### ISSUE TITLE
Unable to execute script at line 314. p is undefined

### ISSUE THREAD

**Issue by joao-traini** [airbnb/lottie-web#1853]
**Tell us about your environment**

* **Browser and Browser Version:** bodymovin 5.5.9
* **After Effects Version:** CC 2019 (16.1.3)

**What did you do? Please explain the steps you took before you encountered the problem.**
Simply opened AE and tried to open the bodymovin extension

**What did you expect to happen?**
At least interact with the UI, or normally use the extension.

**What actually happened? Please include as much _relevant_ detail as possible.**
The error in the title appeared, sometimes twice in a row, sometimes once.

**Please provide a download link to the After Effects file that demonstrates the problem.**
It's any blank file. Here's a screen record of the bug: https://streamable.com/in2in

**Comment by halahua** [comment]
Just checked the screen record and realized that the bug pop-up wasn't showing, but it did appear. Everytime I interacted with the UI it gave me this: 
![image](https://user-images.githubusercontent.com/51062520/68783431-be026b00-0619-11ea-9125-3d83f5e0fff8.png)

**Comment by bodymovin** [comment]
Hi, I've heard about this issue before but I haven't been able to reproduce it, unfortunately.

**Comment by halahua** [comment]
Hey! Thanks for the response.
Yes, it seems really random. I've installed 2020, and BM isn't working on it yet, but I tried again in 2019 and now everything is ok... I haven't changed anything in the older version, so I really don't know what happened, hahahaha.
I'll close the issue so that you can focus on more pressing matters, and if it comes up again, I'll let you know.
Thanks again!

**Comment by joao-traini** [comment]
Here am I again!
https://www.loom.com/share/982ec4b6b8364c96a90d402bda7b2d31 this from AE 2019 (which was working before).
https://www.loom.com/share/cc890627a7204506b60f48f8bf2ce649 this is from AE 2020. It isn't showing anything when I open the Bodymovin extension.

Did somebody bumped into something like that?

**Comment by bodymovin** [comment]
@joao-traini it's pretty strange. It's as if the `__adobe_cep__` bridge is not working. What is the error message you get on the 2019 video? It's difficult to read.

**Comment by joao-traini** [comment]
Hey @bodymovin! Sorry for the late reply.
FYI, it is now working flawlessly on AE 2020 (V 17.1.2 (Build 37)) and BM (V 5.7.1, via ZXP Installer, the one from aescripts).
I don't remember trying to reinstall BM again, but when I went to look, it wasn't there. Downlowded it again from aescripts, installed and it all went smoothly.
Thank you for your efforts - this plugin is a life saver, man!

Oh, and btw, the error message on 2019 was the same as in the title: "Unable to execute script at line 314. p is undefined", in case somebody is having the same trouble.

![Annotation 2020-08-18 103609](https://user-images.githubusercontent.com/51062520/90519709-c3f42200-e13e-11ea-93a9-85626ffd3626.png)
![Annotation 2020-08-18 103631](https://user-images.githubusercontent.com/51062520/90519719-c5254f00-e13e-11ea-9329-3e82395f0d5c.png)
