### ISSUE TITLE
JPEG Sequence rendering, but does not display

### ISSUE THREAD

**Issue by mikeb907** [airbnb/lottie-web#1854]
Hey!

I have a jpeg sequence in AE, trying to render with bodymovin and drop the .json in webflow - which Webflow has a video on how to do themselves! But for some reason my json file just shows a corrupt image icon, no animation. I also get the same thing if I test it in lottie.cloud. However, the demo works. 

Here is a screen shot:
![image](https://user-images.githubusercontent.com/8783082/68515117-e1aa6780-024d-11ea-8a71-e131d0443e5f.png)

Here is also my AE file:
https://www.dropbox.com/s/q0gyie5vpqmh5rk/JPEG%20Render%20Lottie.zip?dl=0

Any idea what's going on??

Edit: Here is also some help I've tried to find in webflow's forum, hopefully the conversation can give more context to my problem: 
https://forum.webflow.com/t/json-lottie-animation-shows-a-corrupted-file-icon-in-webflow-however-the-demo-works/100471

Thanks,
Mike

**Comment by mikeb907** [comment]
I've just downloaded assets from a webflow tutorial. I have their json, and then the json i exported from the file they provided. Exact same project, but mine has exported the same way as my previous animations. So maybe something is wrong with my export settings?

Here are the two json files to compare. 
[JSON files.zip](https://github.com/airbnb/lottie-web/files/3826791/JSON.files.zip)

**Comment by michaelcoughlan** [comment]
Hi @mikeb907, did you ever resolve this issue? I am having a similar problem

**Comment by bodymovin** [comment]
@michaelcoughlan can you share a link with the issue?
That error seems related to being unable to find the image assets

**Comment by michaelcoughlan** [comment]
@bodymovin yeah not finding the images in public/ was the issue thank you for clarifying though! As far as I know, an image was imported into AE and then the lines that animate in afterwards were created in AE, does this mean that if the entire animation was created in AE then the image file wouldn't be needed (apologies if this is a silly question I don't know how AE works) as the lines rendered just fine, only the image was the issue?

**Comment by bodymovin** [comment]
@michaelcoughlan correct. You can also import AI layers and convert them to shapes in AE so they don't get exported as images.

**Comment by michaelcoughlan** [comment]
@bodymovin thats great thanks a bunch! Worked like a charm
