### ISSUE TITLE
Bodylovin rendering different animation

### ISSUE THREAD

**Issue by Bowis** [airbnb/lottie-web#1855]
**Tell us about your environment**
* **Browser and Browser Version:**|
Chrome,  Version 78.0.3904.70
* **After Effects Version:**
17.0.0

**What did you do? Please explain the steps you took before you encountered the problem.**
I animated a illustrator logo (.ai) shown here:
![image](https://user-images.githubusercontent.com/26330562/68530551-352dbb80-0309-11ea-8f36-9b8d0a7d84c9.png)
And using multilpe methods: (stroke + trimpath, stroke +normal path and using a mask path) bodylovin renders a completely different animation. 

**What actually happened? Please include as much _relevant_ detail as possible.**
This is what bodylovin outputs: 
![image](https://user-images.githubusercontent.com/26330562/68530565-8c339080-0309-11ea-83e3-bf491d87b4a5.png)
Using mask 
![image](https://user-images.githubusercontent.com/26330562/68530569-9d7c9d00-0309-11ea-98e5-5bac14d16a85.png)
Using stroke
**Please provide a download link to the After Effects file that demonstrates the problem.**
https://gofile.io/?c=ZeAWcy

**Comment by bodymovin** [comment]
Hi, it seems it doesn't find the image that is being masked.
Can you check the exported image is in the right place?

**Comment by Bowis** [comment]
> Can you check the exported image is in the right place?
In the json code? Or where

**Comment by bodymovin** [comment]
there should be a images folder exported in the same folder as the json file
