### ISSUE TITLE
After rendering animation is on the other side

### ISSUE THREAD

**Issue by rmwsd** [airbnb/lottie-web#1857]
**What did you do? Please explain the steps you took before you encountered the problem.**
I created an animated trim path on the left side but after rendering it turns out on the right side. 

Screenshots
http://joxi.ru/Dr8xE0zcoV4KJr

--
version 5.5.9
--
[test.json.zip](https://github.com/airbnb/lottie-web/files/3827677/test.json.zip)
[test.aep.zip](https://github.com/airbnb/lottie-web/files/3827678/test.aep.zip)

Could you help to resolve this?

**Comment by bodymovin** [comment]
This seems to be an AE bug related to trim paths

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
