### ISSUE TITLE
No paths in the xml

### ISSUE THREAD

**Issue by Maxico-iZettle** [airbnb/lottie-web#1859]
Ive rendered an After Effects animation to xml using Bodymovin (Attaching the AE file) and the paths are gone in the xml. Ive only used shapes drawn in AE which I animate the size properties on and cant get the xml to include the paths. So I tried to import Illustrator layers and created vector shapes that I animated the scale instead (since I don't see the size properties on imported vectors, which is not preferred when you don't want the stroke width to scale) and then it works. Any idea why I cant get the first example to work? Just trying to learn. Thanks!
[Pulse.aep.zip](https://github.com/airbnb/lottie-web/files/3832515/Pulse.aep.zip)

**Comment by bodymovin** [comment]
Hi, I've tested the animation and it seems to work fine.
What is it exactly that you see missing?
