### ISSUE TITLE
Bodymovin failed to export animation as it should be

### ISSUE THREAD

**Issue by emmaaho** [airbnb/lottie-web#1861]
**Tell us about your environment**
Window 10

* **Browser and Browser Version:**
Chrome Version 78.0.3904.97 (Official Build) (64-bit)

* **After Effects Version:**
Adobe After Effects CC 2018

**What did you do? Please explain the steps you took before you encountered the problem.**
Stroke and trim path are used for the animation.

**What did you expect to happen?**
Exported Json file as what mov shown.

**What actually happened? Please include as much _relevant_ detail as possible.**
I've attached both the json and mov file below that i exported. Some part of stroke are showing but some are missing. And i found that bodymovin are not supported to stroke effect? (Do i misunderstanding the whole thing or ?)
[https://github.com/airbnb/lottie/blob/master/supported-features.md]

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://we.tl/t-7SOI2PMzYd

**Comment by bodymovin** [comment]
Hi, the transfer is no longer available.
If you haven't solved the issue please reopen.
