### ISSUE TITLE
Doesn't render a bold/black font-weight

### ISSUE THREAD

**Issue by rmwsd** [airbnb/lottie-web#1864]
Hi! I have a font issue - only renders the normal font-weight, but not in bold/black. I tried different options but bold does not display (you can see the last option on the screenshot below). Could you take a look at examples (attached) and help to resolve this?

You can check an example of animation here http://er.tw1.ru/ (number of percentages should be bolder)

After Effects Version: 16.1.2
Bodymovin Version: 5.5.9

[test-font.aep.zip](https://github.com/airbnb/lottie-web/files/3838443/test-font.aep.zip)
[pctest.json.zip](https://github.com/airbnb/lottie-web/files/3838444/pctest.json.zip)
![e65ac155b3](https://user-images.githubusercontent.com/13256989/68715372-e6a34a00-05b2-11ea-97d7-b1be517dc1e0.png)

**Comment by bodymovin** [comment]
Hi, are you rendering text layers as glyphs or as text?

**Comment by bodymovin** [comment]
I think I see the problem, can you set the Font Family value of proxima_nova_black to "Proxima Nova Black"?

**Comment by rmwsd** [comment]
> Hi, are you rendering text layers as glyphs or as text?

Hi! I used different ways but it works correctly just with one style of a font in the project. OK, I will try your option today. Thank you!

**Comment by rmwsd** [comment]
The second font style was generated with an incorrect name – `fFamily":"Proxima Nova",` / When I fixed this inside the .json `"fFamily":"ProximaNova-Black"` the problem was solved. Is this a bug? / Did I make a mistake when setting render?

**Comment by bodymovin** [comment]
Probably not, I will have to combine font family and weight to make unique fonts
