### ISSUE TITLE
Parts of animation missing or clipped in Edge and IE

### ISSUE THREAD

**Issue by pdub23** [airbnb/lottie-web#1865]
Thanks in advanced for your support, I realize IE/Edge is a pain.  
Have tried everything I know, wondering if you can spot something that is wrong...

* **Browser and Browser Version:**
Windows/browserstack using Edge or IE

* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

Created Animation with:
- solid mask on top of ring layer
- solid is animated by Path anchor points
- mask mode is Alpha Matte
- everything is converted into shapes in AE

View rendered animation in Edge browser = :(

**What did you expect to happen?**

Animation should display all it's parts (same as other browsers do).

**Expected:**
<img width="618" alt="expected" src="https://user-images.githubusercontent.com/841407/68811756-3a02b000-0626-11ea-9783-2a06e69d183c.png">

**What actually happened?.**

1. Parts of animation are missing when shadow or not with shadow.
2. When using shadow edges are also clipped.

Without shadow: https://lottiefiles.com/share/18yEHC
With shadow: https://lottiefiles.com/share/5Hk2Z5

**Edge:**
<img width="517" alt="edge" src="https://user-images.githubusercontent.com/841407/68811516-b5179680-0625-11ea-8e70-e88ff4277e7e.png">

**Llink to the After Effects file that demonstrates the problem:**

https://www.dropbox.com/sh/ekcx01wqeay2tfd/AAC7t3bOobU_2VWb1PMI1z99a?dl=0

**Comment by bodymovin** [comment]
Unfortunately Edge has a lot of issues with svg masks. If you resize the window you'll see it gets corrected.

**Comment by pdub23** [comment]
Good news.. these lottie files look correct in the latest version of Edge (80).  I believe you can close this issue.
