### ISSUE TITLE
Why Lottie returns a SVG outside it's parent div?

### ISSUE THREAD

**Issue by WebStormr** [airbnb/lottie-web#1866]
I'm stuck and I spend a whole day on this issue. Basically I'm trying to implement in my website an animation, using Lottie. The format of my animation is 1080*1920. The problem is that, given a div, with:

```
width: auto; 
height: auto; 
```

or

```
width: 100%;  
height: 100%;
```

the exported animation is always bigger than the enclosing parent. This problem arise specially with the smartphone sized-screens. I tried to change all the parameters, unsuccessfully. I even touched the java script code, since in Lottie, you can specify the rendered options (svg, html, canvas), UNSUCCESSFULLY. 

```
import './styles/main.scss'

const lottie = require('lottie-web')
const bodymovin = require('bodymovin')

var svgContainer = document.getElementById('homeSection');

var animData = {
    container: svgContainer,
    renderer: 'svg',
    loop: false,
    autoplay:true,
    path: 'PhoneRotate.json'
};


var anim = lottie.loadAnimation(animData);
```

```
@import "~bootstrap/scss/bootstrap";

html, body {
  background-color: #000;
  overflow: scroll;
}

.section1{
  background-color: black;
  width: 100%;
  height:100%;
}

#homeSection {
  height: auto;
  border-style: solid;
  border-color: yellow;
  position: absolute;
  right: 5px;
  left: 5px;
}
```

```
<div>
    <nav class="navbar navbar-expand-lg navbar-custom" >
        <a class="navbar-brand">
            <img class="logo " src="images/AM_logo.png" href="#">
        </a>
        <a class="navbar-brand" style="color: black"> Arduino Developer </a>

    </nav>
</div>


<div class="container-fluid section1" >
        <div id="homeSection">
            <div>
                <p class="text textH"> TEXT 1</p>
            </div>

            <div>
                <p class="text textT"> TEXT2</p>
            </div>
        </div>
</div>
```

You can see the animation here:
[https://assets6.lottiefiles.com/packages/lf20_XW2oHn.json](url)

Please bear in mind that the animation should be loaded in the yellow box that, for no reason is pushed on the top, when the animation is supposed to be loaded INSIDE it. 
Also, in a desktop size, despite the SVG container returned by the method is bigger than the enclosing `div`, the content fit into the yellow box. 

<img width="496" alt="Screenshot 2019-11-13 at 23 34 29" src="https://user-images.githubusercontent.com/57734233/68814933-eb7b0300-0671-11ea-87d4-f93cd015302c.png">
<img width="496" alt="Screenshot 2019-11-13 at 23 34 36" src="https://user-images.githubusercontent.com/57734233/68814934-eb7b0300-0671-11ea-935e-adc69363e006.png">

**Comment by Inventsable** [comment]
Have you overridden the default user agent style sheet for the SVG tag? e.g.

```css
svg {
    width: 100%;
    max-width: 100%;
}
```

**Comment by kolboch** [comment]
I have the same issue, content is always absolutely positioned, I have no idea why that happens. This way its impossible to design anything. Seems like that is a real issue, I don't know how to deal with it editing css just as a "side task".
