### ISSUE TITLE
AE doesn't save animation with BodyMovin plugin only a picture. 

### ISSUE THREAD

**Issue by Grion** [airbnb/lottie-web#1868]
**Tell us about your environment**
Windows 10 Pro 

* **Browser and Browser Version:**
Google Chrome (Version: 78.0.3904.97) (64 bites)

* **After Effects Version:**
After Effect CC 2018 

**What did you do? Please explain the steps you took before you encountered the problem.**

I made a picture in Adobe Illustrator CS6. Invert into AE. Animated the picture with puppet pin option. Sent the layer into shapes, deleted the vector layers.

**What did you expect to happen?**

Save out a working animation without background for telegram.

**What actually happened? Please include as much _relevant_ detail as possible.**

Export with 'Bodymovin Plugin for Telegram' and it saves a simple picture without the animation. 
If save as a video file, it works. With Bodymovin plugin - it doesn't. Save a simple picture, without the movement. 

**Please provide a download link to the After Effects file that demonstrates the problem.**

https://drive.google.com/drive/folders/1EeYn-vJiJBWSDnx2sV_03rfSZCxpaPVG?usp=sharing

**Comment by bodymovin** [comment]
Hi, puppet pin is not supported unfotunately
