### ISSUE TITLE
Bounce expression on properties doesn't show in jason file

### ISSUE THREAD

**Issue by jonashaxo** [airbnb/lottie-web#1869]
**Tell us about your environment**

* **Browser and Browser Version:**
Firefox 70.0.1 (64-bit)
* **After Effects Version:**
17.0.0
**What did you do? Please explain the steps you took before you encountered the problem.**
I added an expression to some of the layers properties (rotation and scale):

// Inertial Bounce (moves settle into place after bouncing around a little)
n = 0;
if (numKeys > 0){
n = nearestKey(time).index;
if (key(n).time > time){
n--;
}
}
if (n == 0){
t = 0;
}else{
t = time - key(n).time;
}

if (n > 0){
v = velocityAtTime(key(n).time - thisComp.frameDuration/10);
amp = thisComp.layer("bounce control").effect("amp")("Slider");
freq = thisComp.layer("bounce control").effect("freq")("Slider");
decay = thisComp.layer("bounce control").effect("decay")("Slider");
value + v*amp*Math.sin(freq*t*2*Math.PI)/Math.exp(decay*t);
}else{
value;
}
**What did you expect to happen?**
That the properties would bounce the same way in the exportet jason file, as in the after effects project.
**What actually happened? Please include as much _relevant_ detail as possible.**
Rotation and scale didn't animate in the jason file.
**Please provide a download link to the After Effects file that demonstrates the problem.**
[export.zip](https://github.com/airbnb/lottie-web/files/3856052/export.zip)

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by jonashaxo** [comment]
Here is the .aep project:
[export.zip](https://github.com/airbnb/lottie-web/files/3885371/export.zip)

**Comment by bodymovin** [comment]
Hi, your layer "bounce control" is an Adjustment Layer which are not supported by the player.
If you change it to a regular layer (and set the opacity to 0 so it is not rendered), it should work fine.
