### ISSUE TITLE
Multiple masks cause simple path to fully disappear even in panel preview

### ISSUE THREAD

**Issue by Inventsable** [airbnb/lottie-web#1873]
AE 2020 (17.0)
Bodymovin' panel 5.5.9

Using multiple subtract masks causes parent path to fully disappear towards the end of animation and subsequent glitch when playing the animation:

![](https://thumbs.gfycat.com/CapitalSelfishCamel-size_restricted.gif)

[Full resolution here](https://gfycat.com/capitalselfishcamel)

[AE Project here](https://drive.google.com/open?id=1ZkkyEUAvrysKYCCMu9pWQZ4MlBWiSwRd)

Hi hernan, I had someone ask me for a transparent version of this loading animation. Previously I'd used multiple shapes with the same fill color as the bg, but they required the negative space to be transparent -- so masking is needed for the hexagon section of the wrench head along with the small orb at the end of the handle.

I didn't see this as an unsupported feature, and none of the workarounds I'd seen posted in other issues (pasting masks as paths instead of masks) seemed to work. Are multiple masks with subtract not supported?

**Comment by Danjuanlab** [comment]
I remember before hernan said that sometimes it leads to some unexpected results, and the computational complexity of subtrct method is more complicated than the conventional addition. His suggestion is try not to use subtract mask.

**Comment by bodymovin** [comment]
Hi, this is a problem with inverted masks (and subtractive as well) relative to the global coordinates.
When rotated 180 degrees, the inverting mask fails to be correctly drawn.
I'll have to take a look at this to see how to improve it.

**Comment by bodymovin** [comment]
Ok, I've fixed it, it will be working on the next deploy.

**Comment by Inventsable** [comment]
Thank you @bodymovin! You're the best, can't wait to see it
