### ISSUE TITLE
Is there any way to edit something in lottie json file from code?

### ISSUE THREAD

**Issue by akkii922** [airbnb/lottie-web#1877]
Hi Guys,
I am working on some animation in keyshape mac software and exported the animation in Lottie JSON format. Now I need to know is there any way I can edit some text in that exported animation form code.

**Comment by Danjuanlab** [comment]
https://github.com/airbnb/lottie-web/wiki/TextLayer.updateDocumentData

**Comment by akkii922** [comment]
> https://github.com/airbnb/lottie-web/wiki/TextLayer.updateDocumentData

Thanks for the reply.
Can you please tell me if I can edit the Lottie JSON and get the updated JSON so I can save that in somewhere.

**Comment by karip** [comment]
The Lottie plugin for Keyshape exports all texts as paths. It means that it isn't possible to update texts in the JSON file.

**Comment by mofarhand** [comment]
@karip  @akkii922 
Hi Karip, akki
I'm looking for a way to be able to change a **path** params or some position values for my objects to make the movement a bit random.
( Object A should move to position B, what If I want to change the path position a bit? )
what's is the best way to modify the JSON or is there any method to do that?

**Comment by karip** [comment]
Sorry, I don't know how to do it. You may want to open a new issue to get better replies.
