### ISSUE TITLE
Set Id in rendererSettings

### ISSUE THREAD

**Issue by herrmanneffe** [airbnb/lottie-web#1878]
Hi,

in the rendererSettings you can set a Class, and it will add a class to the root element of the animation.
Is it possible to set also an Id?

Thank you

**Comment by Danjuanlab** [comment]
Yes， you can.Just use the "#"mark

**Comment by herrmanneffe** [comment]
I mean setting an Id fot the <svg> from the rendererSettings options, instead of a Class like here:

![Screenshot 2019-11-22 at 14 04 30](https://user-images.githubusercontent.com/43209121/69428474-9013d980-0d31-11ea-9374-d45edfbbd1fb.png)

**Comment by bodymovin** [comment]
ok I've added it. It will be available on the next build.

**Comment by herrmanneffe** [comment]
Great!! Thank You :)
