### ISSUE TITLE
Detecting modal dialogue box

### ISSUE THREAD

**Issue by reubenlara** [airbnb/lottie-web#1879]
this should be finally fixed.

_Originally posted by @bodymovin in https://github.com/airbnb/lottie-web/issues/97#issuecomment-321428915_

Hey there, I am the creator of Marker Remap on aescripts.com and was wondering how you solved the "Cannot run a script while modal dialogue is waiting for a response" error? I can reproduce it exactly: Open a modal dialogue like "Import" then hover over my ScriptUI panel if it's showing in the background and it fires consistently. My panel uses a mouseover event so it makes sense why the error is triggering. But how did you get Bodymovin to ignore mouseover events when a dialogue is open? Any help is appreciated! Thanks! Reuben

**Comment by bodymovin** [comment]
Hi, I think there are no mouseover events on the app.
But I guess you could listen to window.focus and window.blur events to prevent triggering mouseover events when the window is not focused.

**Comment by reubenlara** [comment]
Ok thanks so much for the tip, will give it a shot!
