### ISSUE TITLE
Export issues

### ISSUE THREAD

**Issue by marlonlf** [airbnb/lottie-web#1883]
AE version 17.0 

When I export an animation, one of the compositions does not appear in the final render. When I tried to export it separately for testing, the render was completely blank.

The composition with problem is "Info1"

[SampleFlow.aep.zip](https://github.com/airbnb/lottie-web/files/3888372/SampleFlow.aep.zip)

**Comment by marlonlf** [comment]
And it's just some text elements that don't show up, because some of the composition elements show up in the demo render

**Comment by bodymovin** [comment]
Hi, there seems to be a problem with the animator based on Lines with an offset at 11%
if you change the offset to 0 it should work fine.
I'll try to fix it on my side for the next build.

**Comment by marlonlf** [comment]
> Hi, there seems to be a problem with the animator based on Lines with an offset at 11%
> if you change the offset to 0 it should work fine.
> I'll try to fix it on my side for the next build.

it worked! thank you
