### ISSUE TITLE
Problems rendering on bodymovin

### ISSUE THREAD

**Issue by Xidrovo** [airbnb/lottie-web#1884]
Hi, Just end up an animation when it cames out that it couldn't be well rendered to bodymovin. The animation uses Trim path, zig zag and linear gradient. It is kindly simple but can't be rendered. I mean, when it comes the preview only one single line appear.

This is the simple AE file 

https://send.firefox.com/download/70f9844e8edde8d6/#_rcKKj8nzbBXwTHF1JpIbg

it is simple, but need to upload it

hope to know why didn't upload correctly... thanks!

**Comment by bodymovin** [comment]
Hi, unfortunately zig zag is not supported, but the rest should work fine

**Comment by kudanai** [comment]
Support for zigzag has been added in 5.10.0
