### ISSUE TITLE
A weird distortion coming in the final export

### ISSUE THREAD

**Issue by DYNSTy** [airbnb/lottie-web#1885]
**Composition created on AE and put up on a website for all OS**

* **Browser and Browser Version: All Chromium based browsers like Opera and Chrome**
* **After Effects Version: Build 48 (Windows 10)**

**Created the composition with the Bodymovin rules in mind, all seems to work except there's a line coming of of the mask as the left end of the export. Have tried re-exporting to no avail.**

**A clean execution, you can see the distortion here** 
![image](https://user-images.githubusercontent.com/46441179/69617629-7b4f8280-105e-11ea-9fd6-09ba709d2efa.png)

**The issue doesn't occur on edge or safari. On chrome and opera the line appears and goes as one widens or thins the browser window**

**The composition in question is 'LeaveMan 3' , you can find the AE file and the export here: https://drive.google.com/drive/folders/1eRQ1FKLPGwZtR4EhkYkTcLoouItTEJjR?usp=sharing.**

![image](https://user-images.githubusercontent.com/46441179/69619891-6117a380-1062-11ea-830d-da079b3dba41.png)
**The lottie viewer does not support it at all**

**Comment by bodymovin** [comment]
Hi, are you using the latest version of the web player?

**Comment by DYNSTy** [comment]
> Hi, are you using the latest version of the web player?

You mean from the coding side or from the viewer browser?

**Comment by bodymovin** [comment]
the viewer in the browser
