### ISSUE TITLE
Animation stops after first AE layer

### ISSUE THREAD

**Issue by siddroth** [airbnb/lottie-web#1890]
The animation runs. But only for the first after effects text layer. I checked the HTML preview and the bodymovin preview and they both show the same thing. Perhaps the code is incomplete? Not sure.

I've attached the zip containing the ae file, data.json & demo.html 

Thanks in advance.

[Sid's Project.zip]
(https://github.com/airbnb/lottie-web/files/3907710/Sid.s.Project.zip)

**Comment by bodymovin** [comment]
Hi, there are multiple layers with an Alpha inverted mask selected, but that doesn't work in AE and it translates incorrectly to the player.
If you set their track masks to none, it should work fine

**Comment by siddroth** [comment]
Thank you! It worked 👍
