### ISSUE TITLE
Missing shapes/images from animation

### ISSUE THREAD

**Issue by infactable** [airbnb/lottie-web#1891]
Hello,

I'm graphic designer and animator and I created few simple animations for a new client and exported it with Lottie as json files, but when they test it some images/shapes are missing.

Can you please help us resolve this, I'm not sure what's going on I used lottie for years with other clients and they never complained about it?

This is how animation should look like: 
<img width="306" alt="Screen Shot 2019-12-03 at 11 54 52 AM" src="https://user-images.githubusercontent.com/58468623/70045095-cd932500-15c3-11ea-9318-3e191e038d11.png">

And this is how they see it:
![image_2019_12_02T21_30_23_176Z](https://user-images.githubusercontent.com/58468623/70045156-e996c680-15c3-11ea-8e81-d86ef422e082.png)

I added AfterEffects file and links here: https://drive.google.com/open?id=1p8p_RiXs04KuYqTueljBfGzMx-322Rp6

Thanks a lot!
Milan

**Comment by bodymovin** [comment]
Hi, I've exported it and it seems to work fine. I would suggest that you convert the remaining ai layers into shapes anyway so your animation doesn't depend on rasterized assets.
But if that is not possible, and this is an Android or ios related issue, I recommend that you open an issue on their repository.

**Comment by infactable** [comment]
Thanks for your help!
