### ISSUE TITLE
After Effects warning: Could not create the file. Access was denied

### ISSUE THREAD

**Issue by Gioazch** [airbnb/lottie-web#1892]
Hello there! I'm kind a newbie in coding and I'm trying to implement an animation I've created in AE, but the DEMO I've exported is working fine. But when i tried to do with the data.json it does'nt work at all, it shows a crashed img icon, and I dont know hot to fix it.

![image](https://user-images.githubusercontent.com/58479454/70067104-8bbaac80-15cc-11ea-8b4e-f021c9c10359.png) This is the demo.

![image](https://user-images.githubusercontent.com/58479454/70067326-d9371980-15cc-11ea-82c4-7a36fd8493f1.png)
and this is the crashing one.

I already made a version with gif, but it sucks, you can check here: www.estudiospeak.com
, and the files of the website in case you  want to check out: 
https://www.dropbox.com/s/ab8vl6n0q9rxfi3/Site.rar?dl=0

EDIT*
Actually i think the code is right. I believe the problem is in AE. I tried to render again, and AE showed me this pop-up:
![image](https://user-images.githubusercontent.com/58479454/70069110-00431a80-15d0-11ea-9c9a-1d16f2b8d170.png)
![image](https://user-images.githubusercontent.com/58479454/70069174-1cdf5280-15d0-11ea-96b0-4cca246f0c36.png)

[test.zip](https://github.com/airbnb/lottie-web/files/3917817/test.zip)
Do you have any ideia how to fix it? 
*the tes.zip is the AE file

**Comment by bodymovin** [comment]
Hi, there seems to be some files missing. When you export an animation with illustrator layers, they get converted to raster assets and exported to an "images" folder.
You probably need to upload them as well.
Having said that, it might be better for you to convert your illustrator layers into shapes (By right clicking on them and selecting: Create > Create Shapes from Vector Layers). That way everything will remain vector based

**Comment by samdomo93** [comment]
Hi there, this happens to me as well. Is there any fix for this? im using png images instead of vector layer.

you can view it here: 

https://lottiefiles.com/share/wz3pVd

**Comment by Gioazch** [comment]
I created the shape layers, and worked. Thank you!!!

**Comment by kkncharge** [comment]
@bodymovin 
So, when i have PNG in my AEP file. I have to click "Enter" button 2 times for each PNG in AEP file, that so crazy :( Is there any fix for this?

**Comment by sergioemjr** [comment]
![image](https://user-images.githubusercontent.com/44509331/107546231-0c5b3c80-6bc4-11eb-8672-a80fa1db363a.png)
I got this error, any ideas?

Thanks!

**Comment by bodymovin** [comment]
@sergioemjr what version of bodymovin and AE are you using? That error should be fixed already.
Also, you can click on OK, it won't affect the export.

**Comment by sergioemjr** [comment]
Thanks for answering, my AE is the latest one:
[image: image.png]

And I downloaded the plugin here last week (via adobe exchange):
https://lottiefiles.com/plugins/after-effects

Thanks.


Em dom., 14 de fev. de 2021 às 00:34, hernan <notifications@github.com>
escreveu:

**Comment by bodymovin** [comment]
@sergioemjr the lottiefiles extension is maintained by the lottiefiles team, can you reach out to them?
