### ISSUE TITLE
Convert from GIF animation or multiple images

### ISSUE THREAD

**Issue by AWOL-TECH** [airbnb/lottie-web#1893]
I there, 

I am facing an issue, we have a set of  animated icons in the .json format. However for some reason one of our animated Icons is a GIF... 

I want to convert the gif to the .json animated format like the others. I have managed to split the gif file into multiple images (frames) in both GIF and PNG Format.

Is there a way I can combine all these images and create a .json file for them?  I am aware I will likely need to convert the PNG to SVG. I can get that sorted later

Final issue is that I don't have after effects (or access to it)

I would be really grateful if someone knew a way to convert my separate image frames into a json animated svg

**Comment by bodymovin** [comment]
Hi, without AE it might be difficult to accomplish.
You can take a look at the json format to figure out how to build the json format but it might take you some time.
https://github.com/airbnb/lottie-web/tree/master/docs/json

**Comment by kudanai** [comment]
Hello! Since this issue has been stale for quite a while, I'm going to close it. Please re-open or file a new one if necessary if relevant.
