### ISSUE TITLE
Missing Path When Giving JSON File To Developer

### ISSUE THREAD

**Issue by ducpm1608** [airbnb/lottie-web#1894]
**Tell us about your environment**

Browser and Browser Version: Google Chrome Version 78.0.3904.108
After Effects CC 2019 Version 17.0.0 (Build 557)
Bodymovin Extension for AE Version 5.5.10

I made an animation screen for our mobile app, everything is normal, display on Lottieflies well until I gave the JSON file for our mobile developer, when they put it into the app, some paths were missing
Really need your help for this issue please.
Thank you so much!

Here's the display of it:
https://lottiefiles.com/share/fF4qtU
And the link you can get the .aep file:
https://1drv.ms/u/s!AkXEOH6P5rFJg5Bbvjg-0jZfdXgO1Q?e=lXl5um
When displaying on mobile using JSON file, the circle path around the logo and the twist path around the text logo are disappear

**Comment by bodymovin** [comment]
Hi, if this is an android / ios issue, I suggest that you post it in those repositories:
https://github.com/airbnb/lottie-android
https://github.com/airbnb/lottie-ios
