### ISSUE TITLE
Feature request: Export for Google ads, Double Click etc.

### ISSUE THREAD

**Issue by foguetes** [airbnb/lottie-web#1896]
It would be a huge timesaver when creating banner ads, if I could export an upload-ready zip file directly from Bodymovin.

Essentially, it could be something like the existing demo mode but without the unnecessary code.
The structure of the zip would be:
- html file
- Lottie.min.js
- data.json

The necessary tags would be generated and included in the html file during export, including the resolution of the comp.

I prepared an example that I am attaching to this post.

[adwords_template.zip](https://github.com/airbnb/lottie-web/files/3926959/adwords_template.zip)

**Comment by bodymovin** [comment]
Hi, I have been working today on an initial version of this feature.
Would you be willing to try it out?

**Comment by foguetes** [comment]
of course!

**Comment by bodymovin** [comment]
Thanks!
[bodymovin.zip](https://github.com/airbnb/lottie-web/files/3939447/bodymovin.zip)
On the settings there is an Export Mode option where you have to select Banner and then custmomize it.
Let me know if you have any questions.

**Comment by foguetes** [comment]
it seems to be working great.
I would just change a few things.

1 - The output when choosing this method should be a zip file and the lottie player js file should already be included.
2 - There should be a field in the exporter to add the clicktag url so it doesn't have to be added manually later.

These would be great timesavers when doing large series of banners.

**Comment by bodymovin** [comment]
I was hesitant about exporting as a zip. If users want to check it out, I think it's easier to get all separate and zip them when necessary.
I'll add an option to choose one or the other.
I'll work on the other ones later today.

**Comment by foguetes** [comment]
Thanks a lot!
Zipping them is always necessary. That's the only way we can run them through the validator (https://h5validator.appspot.com/adwords/asset, https://h5validator.appspot.com/dcm/asset) before we upload it to the Google Ads or Doubleclick platform.

**Comment by bodymovin** [comment]
[bodymovin.zip](https://github.com/airbnb/lottie-web/files/3944514/bodymovin.zip)
new version!

**Comment by foguetes** [comment]
Everything seems to be working fine.

The only thing is that bodmovin always exports it as banner.zip, regardless of the filename I write. 

I'd like to be able to export all of the banners to the same folder, so I would have 120x600, 160x600 etc.

One thing that could be improved is the manual input of the comp's resolution. I think it would be much better if bodymovin would automatically recognize it and add it to the html file, if that's possible.

**Comment by bodymovin** [comment]
version three:
[bodymovin.zip](https://github.com/airbnb/lottie-web/files/3948011/bodymovin.zip)
detects comp sizes and saves the zip file with the original name.

**Comment by foguetes** [comment]
This is perfect. 
Except for one minor thing. When I configure the export for one comp and click on the "Remember Settings" button, it remembers the comp size settings too. So when I apply those settings to multiple comps they all change to the same resolution. Would it be possible to keep each comp's individual resolution when applying the remembered settings?

**Comment by bodymovin** [comment]
[bodymovin.zip](https://github.com/airbnb/lottie-web/files/3958994/bodymovin.zip)
So what I did instead of not copying those properties is adding a toggle to use composition's original size.
If checked it will use the default size, if checked, the custom size.

**Comment by foguetes** [comment]
Thanks a lot! It's perfect!
Making banners is easier than ever.

When do you plan to merge this with the main release?

**Comment by bodymovin** [comment]
released on version 5.6.1
thanks for all your help!

**Comment by qaribhaider** [comment]
> released on version 5.6.1
> thanks for all your help!

Hi, has this been added/merged? I can't see any info related to using this, assist please?

**Comment by bodymovin** [comment]
@brybby where are you checking? can you share a screenshot?

**Comment by brybby** [comment]
NVM! I was able to figure it out! It made me look so good at my new job!

**Comment by fleurdeboer** [comment]
Hi! I used the amazing plug-in to export banners. Used the Banner setting,  but now I got feedback from my client/campaign operators that "clicktag" doesn't work. So they can't attach an URL to it. Is there a solution for this? Thanks, big help!

**Comment by editingguy89** [comment]
This extension seems to be exactly what I'm looking for to create banner ads. How do I create animation over images that will be included in the banner ad. Or more specifically - how do I export the animation that is using JPGs as part of the ad?
