### ISSUE TITLE
A slider control effect isn't rendering properly in bodymovin

### ISSUE THREAD

**Issue by kingakobos** [airbnb/lottie-web#1897]
Hello! I'm trying to export a json from ae via bodymovin and I've run into some issues with the slider control. Everything works smoothly in After Effects but after rendering it with bodymovin, the numbers either don't show up (only "%") or they weirdly jump from beginning to the end number. I was able to successfully export a similar file before so I'm wondering why it stopped exporting properly. Attached is my ae file. Thank you for your help!
[About page_continued.aep.zip](https://github.com/airbnb/lottie-web/files/3934201/About.page_continued.aep.zip)

**Comment by Danjuanlab** [comment]
I can export your animation normally without errors.

**Comment by bodymovin** [comment]
Hi, I guess is that you are exporting the font as glyphs, and since you are using an expression you'll need to provide all glyphs that are going to be used.
You can add an extra text layer with characters ranging from 0 to 9 outside of the work area and it should work fine.

**Comment by ision-industries** [comment]
> Hi, I guess is that you are exporting the font as glyphs, and since you are using an expression you'll need to provide all glyphs that are going to be used.
> You can add an extra text layer with characters ranging from 0 to 9 outside of the work area and it should work fine.

What do you mean "provide all glyphs that will be used"? Do you mean just have the exact number of glyphs that will be used?

**Comment by bodymovin** [comment]
correct, all the characters need to be available if exported as glyphs

**Comment by kingakobos** [comment]
Thanks SO much for all of your help! It worked! :)

**Comment by ferthome123** [comment]
Man, this is awesome @bodymovin ! not only it worked like a charm but also solved some oooollllddd problems I've been having
