### ISSUE TITLE
Issues with rotation/timing after rendering and viewing in web

### ISSUE THREAD

**Issue by tjzimm** [airbnb/lottie-web#1898]
Hi there. 

I created an animation in Ae and rendered it through body moving. However, the rendered animation is different from the animation in Ae. I can't seem to fix the problem in After effects. 

Do you know what might be causing issues with rotation on shape layers in after effects? 

Information about my data, there are only 4 shape layers, I have 2 of the layers parented to one of the other two layers. 1 set of the shape layers does everything fine, looks clean but the other two layers rotation is either non existent or delayed, not matching with the other two objects. 

If you don't mind could you let me know some possible workarounds or remedies for this issue? 

Thanks for your time and your awesome plugin. It's a lifesaver.

**Comment by bodymovin** [comment]
Hi. Can you share the .aep?

**Comment by tjzimm** [comment]
Thank you for your quick response! 
Of course, Here you are.
https://www.dropbox.com/s/j69xeo0kzal2mq7/titlesequence.aep?dl=0

**Comment by tjzimm** [comment]
> Hi. Can you share the .aep?

Thank you for your quick response! 
Of course, Here you are.
https://www.dropbox.com/s/j69xeo0kzal2mq7/titlesequence.aep?dl=0

**Comment by bodymovin** [comment]
Unfortunately consecutive keyframes with the same value don't work well.
If you change in layer "Shape Layer 2", in "Rotation", the 5th keyframe to -0.1 instead of 0 and the 7th keframe to 0.1 instead of 0, it should work fine.

**Comment by tjzimm** [comment]
That worked perfectly. 
Thank you so much!
