### ISSUE TITLE
looking for a way to change animations in same container

### ISSUE THREAD

**Issue by lastnigtic** [airbnb/lottie-web#1899]
After searching the issues,I found there are three ways to change animation:

1. Using animation.destory() and the other animation.(This solution cause the container flashing during changing.)

2.Concat the animation files and control the frame.(This makes the thing a bit complicated.)

3.using different container.

So,are there other ways to make things more efficient?

Thank for your help

**Comment by bodymovin** [comment]
I would probably go for option 3 and perhaps load the second animation a little later so they don't compete using resources / bandwith
If you go for option 1, you can preload the json and maybe you might get the flashing to disappear

**Comment by lastnigtic** [comment]
@bodymovin I chose option 3, thank you for your suggestion
