### ISSUE TITLE
Bodymovin ERROR: Access was denied.

### ISSUE THREAD

**Issue by EsztiP** [airbnb/lottie-web#1903]
Hello!
I wanted to render a Jpg sequence (just like here: https://www.youtube.com/watch?time_continue=161&v=2djbqUOtFgg&feature=emb_logo ) but I got this Error :( 
Can someone help me?
![79223157_978685752530423_6592584240251011072_n](https://user-images.githubusercontent.com/58792389/70664322-3f7e0500-1c7b-11ea-9fa7-5b10018287fd.png)

**Comment by Inventsable** [comment]
https://github.com/airbnb/lottie-web#after-installing

> After installing
**Windows:** Go to Edit > Preferences > Scripting & Expressions... > and check on "Allow Scripts to Write Files and Access Network"

**Mac:** Go to Adobe After Effects > Preferences > Scripting & Expressions... > and check on "Allow Scripts to Write Files and Access Network"

**Comment by EsztiP** [comment]
oh I already checked it :/ It didn't solve it unfortunately :/ 
but thank you for your answer :)

**Comment by Inventsable** [comment]
That error is a write access denied though, this is likely to be the problem. Have you tried rebooting AE since doing so?

**Comment by bodymovin** [comment]
Hi that message seems related to AE trying to write a log. Can you try
exporting that composition as a png sequence via the regular render queue
to check if you get that same error?

**Comment by EsztiP** [comment]
Yes I rebooted, I tried as png aswell, the same happens :/

**Comment by EsztiP** [comment]
In the older version, it exported but it's not working :/ https://lottiefiles.com/share/lIBPTK

**Comment by bodymovin** [comment]
Did you update AE or install a new version?
If it happens outside of bodymovin, it's probably unrelated to the extension

**Comment by EsztiP** [comment]
I tried both of it :/ I have no idea what can be the problem :( I hope it's possible to solve it

**Comment by EsztiP** [comment]
my problem solved :) I'm soo happy 
I used AE16.1.3. and I checked in Bodymovin Settings>Assets>Include in json (if you use rasterized images) ...and now it's working hallelujah

**Comment by quidando** [comment]
Hi, we're experiencing the exact same problem.
Including all images in json is not a good option as it increases size and has a performance impact.

**Comment by EsztiP** [comment]
oh I see :/ but still, it's better than nothing :/ please tell me if you find a better solution :)

**Comment by arthurlarin** [comment]
Hey guys,

I had the exact same problem and spent 5 hours with Adobe support including letting a rep control my screen and they didn't get me anywhere. Your best bet is to downgrade to After Effects 2019 (16.0). Good luck.

**Comment by umlearn** [comment]
Same problem here too... I tried Include in json function too
AE 17.0.1
Mac OS X Catalina 10.15.2 (19C57)
and in system privacy setting i already gived AE full disk access.

**Comment by bodymovin** [comment]
This should be fixed on the latest extension, version 5.6.1

**Comment by umlearn** [comment]
> This should be fixed on the latest extension, version 5.6.1

Seems there are still same errorr after testing, did you test it on lastest after effects 2020?
