### ISSUE TITLE
Rendering problems with Bodymovin - please help!!

### ISSUE THREAD

**Issue by AladinBen** [airbnb/lottie-web#1905]
Hi there, I'm running into a error when trying to render the composition using Bodymovin. 
While redering i get a error "Unable to execute script at line 186. undefined is not an object

AE Versionb 17.0.1. Build S2 and Bodymovin 5.5.10

Here a screenshot : https://imgur.com/A033eW8

Source File: https://drive.google.com/file/d/1rNLr080TQ1b16B5WPJTHeOZLYoa1kPBJ/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, there seems to be a problem when naming a layer and a comp in a similar way.
Can you retry renaming your layers to something different instead of "plitka"?
I need to see if I can fix it on the extension side.

**Comment by bodymovin** [comment]
this issues should be solved on the latest exporter.
If it is still happening, please reopen
