### ISSUE TITLE
How does the renderer fill the screen? Don't keep the aspect ratio!

### ISSUE THREAD

**Issue by xiao252** [airbnb/lottie-web#1912]
I want to stretch the page completely, what can I do?
Don't keep the aspect ratio.
I use canvas as a renderer.
![image](https://user-images.githubusercontent.com/32588856/71247095-09174880-2353-11ea-89cd-32f8d6114bf6.png)
![image](https://user-images.githubusercontent.com/32588856/71247147-20eecc80-2353-11ea-8871-a631614f169f.png)

**Comment by bodymovin** [comment]
Hi, have you tried using the preserveAspectRatio?
https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#preserveaspectratio

**Comment by xiao252** [comment]
> Hi, have you tried using the preserveAspectRatio?
> https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#preserveaspectratio

Thank you for responding so quickly!
I tried preserveAspectRatio but he can't meet my needs.😭

**Comment by bodymovin** [comment]
what value did you try?

**Comment by xiao252** [comment]
> Hi, have you tried using the preserveAspectRatio?
> https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#preserveaspectratio



> what value did you try?

I made a stupid mistake, I think ‘ ’ == none.
preserveAspectRatio: 'none' problem solved, he bothered me all afternoon.😤
