### ISSUE TITLE
Can't get json file to play in HTML

### ISSUE THREAD

**Issue by CoreLocus** [airbnb/lottie-web#1914]
**Tell us about your environment**
Mac OS X Catalina 10.15.2

* **Browser and Browser Version:** Google Chrome latest build
* **After Effects Version:** 2020 (17.0.1 Build 52)

**What did you do? Please explain the steps you took before you encountered the problem.**
Exported an animation and followed the documentation exactly as instructed. Did a bunch of troubleshooting for around 4 hours and couldn't get any animation to work in a fresh HTML doc, only the lottie preview and the preview HTML file work.

**What did you expect to happen?**
Test that I could add in the svg elements before I started making more advanced ones. Just want this one to show up.

**What actually happened? Please include as much _relevant_ detail as possible.**
Doesn't show up, regardless of if it's a fresh web page or the environment I'm working on for the website. Tried it on Windows too with no luck.

**Please provide a download link to the After Effects file that demonstrates the problem.**
Full repo is here: https://github.com/CoreLocus/corelocus.com

**Comment by Inventsable** [comment]
Hi, you're loading lottie and glyphs.js in your `<HEAD>` before the HTML elements are defined. If you move these two script tags to the bottom of your body so they run after the HTML is defined, lottie shows as expected. Like so in your `index.html`:

```html
<!-- Page Body -->

<body>
    <div class="hero">
        <div class="hero-header">
            <div id="lottie"></div>
            <h1><b>CoreLocus</b></h1>
            <h2 id="subhero"></h2>
        </div>
    </div>

    <script src="lottie.js" type="text/javascript"></script>
    <script src="glyphs.js" type="text/javascript"></script>
</body>
```

**Comment by CoreLocus** [comment]
> Hi, you're loading lottie and glyphs.js in your `<HEAD>` before the HTML elements are defined. If you move these two script tags to the bottom of your body so they run after the HTML is defined, lottie shows as expected. Like so in your `index.html`:
> 
> ```
> 
> 
> <body>
>     <div class="hero">
>         <div class="hero-header">
>             <div id="lottie"></div>
>             <h1><b>CoreLocus</b></h1>
>             <h2 id="subhero"></h2>
>         </div>
>     </div>
> 
>     <script src="lottie.js" type="text/javascript"></script>
>     <script src="glyphs.js" type="text/javascript"></script>
> </body>
> ```

Already tried this, just tried again to confirm. Doesn't work.

**Comment by bodymovin** [comment]
Hi, I just tried @Inventsable suggestion and the animation shows correctly.
Are you getting an error in the consolo you can share?

**Comment by CoreLocus** [comment]
Oh this is bizarre, wasn't getting this before.

`lottie.js:1 Access to XMLHttpRequest at 'file:///Users/jess/Desktop/CoreLocus/data.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
load @ lottie.js:1
index.html:1 A cookie associated with a cross-site resource at http://fontawesome.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

**Comment by bodymovin** [comment]
I see, in order to load json files on your browser you need to run them through a web server

**Comment by Inventsable** [comment]
@CoreLocus What's your dev environment? I opened your repo in VSCode and used the LiveServer extension on your `index.html` before replying, shows correctly and had no console errors.

**Comment by CoreLocus** [comment]
> I see, in order to load json files on your browser you need to run them through a web server

Been developing for six years and never knew this.
Two drums and a cymbal fall off a cliff

**Comment by CoreLocus** [comment]
Does it work on github pages? Can't seem to play it back at all on there either, so maybe it has to be a proper dedicated nginx environment?

**Comment by CoreLocus** [comment]
Nevermind got it working when I switched OSes
