### ISSUE TITLE
Low web animation performance.

### ISSUE THREAD

**Issue by nuttert** [airbnb/lottie-web#1920]
[chat_.aep.zip](https://github.com/airbnb/lottie-web/files/4012106/chat_.aep.zip)

![image](https://user-images.githubusercontent.com/35408275/71612543-31ecd880-2bb2-11ea-9b41-9fe6d7654ae1.png) with animation
![image](https://user-images.githubusercontent.com/35408275/71612565-521c9780-2bb2-11ea-8b86-5d86e52e7f2b.png) without
Hi :)
I tried animating several svg images using lottie, but all these animations gave low performance ... if without animations the site takes about 7-9% of the processor, then with animation this figure increases 3-4 times (20-30%) and keeps constantly.
(red color indicates system and user blue)

Maybe I'm doing something wrong?

(In AfterEffects, I created masks or track matte over each message in the animation, also painted messages in different colors, I drop the simplified version here - gray messages just pop up)

**Comment by bodymovin** [comment]
Hi, you might want to try to use `anim.setSubframe(false);` so it will only render frames and not sub frames.
Also, track matte masks are performance intensive, that might affect as well.
Do you have a link with the animations implemented so I can take a look?

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
