### ISSUE TITLE
Play Animation when Icon in Mobile Viewport

### ISSUE THREAD

**Issue by lvl12sealclubber** [airbnb/lottie-web#1922]
I was able to get three separate animations to play on mouseenter & mouseleave events, based on a previous issue:
https://github.com/airbnb/lottie-web/issues/676

My goal for the mobile version is to run the animation once the svg's parent element is within the viewport. Is there a way to achieve this?

Please see my codepen:
https://codepen.io/lvl12sealclubber/pen/MWYOxzB

Thank you for your assistance.

**Comment by bodymovin** [comment]
Hi, you might want to take a look at Intersection Observers
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by herrmanneffe** [comment]
I did something similar. The animation starts when it enters the viewport: http://www.federicoherrmann.it/infografica-categora/index.html
I used the **isInViewport.jquery.js** plugin

**Comment by kudanai** [comment]
Closing this issue for now since it's become stale. Please re-open if relevant
