### ISSUE TITLE
Image file not showing on the preview

### ISSUE THREAD

**Issue by DorenBoust** [airbnb/lottie-web#1923]
Hi,
i just starting to use lottie libs.
I rendered After effects file to json.

When i open the json on the preview tool i get the animation but the images file not showing on.
I try use it for Wordpress/when i setupit on Android studio i add assets folder with the mage and then it work perfect.

Now with wordpress i need upload it with the preview tool on LottieFile.

Thanks

**Comment by bodymovin** [comment]
Hi, what preview are you referring to?
Can you share a screenshot?

**Comment by DorenBoust** [comment]
![image](https://user-images.githubusercontent.com/29662366/71974390-0dc87180-321a-11ea-9ce4-24ccbdd0b035.png)

**Comment by bodymovin** [comment]
I see, can you report it on the lottie files site?
This is not related to the lottie-web player or the bodymovin exporter.

**Comment by DorenBoust** [comment]
I though its lottie's git

**Comment by GAvAman-bit** [comment]
Hi DorenBoust
I have the same problem!  How did you resolve this? I'm getting very frustrated!
Thanks for any help
Graham
