### ISSUE TITLE
Not able to make the glow type animation outside the circle. tried in android.

### ISSUE THREAD

**Issue by ankittecholution** [airbnb/lottie-web#1928]
**Tell us about your environment**

* **Browser and Browser Version:**
Chrome and version 79.0.3945.88 
* **After Effects Version:**
V17
**What did you do? Please explain the steps you took before you encountered the problem.**
I was trying to make a glow outside the circle with set alpha but was not able to render it properly.
**What did you expect to happen?**
Proper glow outside the circle.
**What actually happened? Please include as much _relevant_ detail as possible.**
Was not able to see any colour outside the circle. BUt was not able to see any colour outside the circle.
**Please provide a download link to the After Effects file that demonstrates the problem.**
I was not able to upload the files here so 
https://drive.google.com/file/d/1cXGKivo5TrDgAJr2ECn9TFC0NC9WeQvP/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, raster effects are not supported by the players

**Comment by ankittecholution** [comment]
so is there any alternative effect of this, so that I can use and get the same output.
