### ISSUE TITLE
CC 2018 Unable to execute script at line 104. null is not an object

### ISSUE THREAD

**Issue by gigit95** [airbnb/lottie-web#1930]
Hi,
Windows 8.1, AE CC 2018, Bodymovin 5.6.0
"Unable to execute script at line 104. null is not an object"
After I've updated the plugin the message appears.
Even in an empty project, when I execute the plugin
Bodymovin 5.5.8 and 5.5.10 (which I've tried a couple minutes ago) work with no problem

![bodymovinProblem001](https://user-images.githubusercontent.com/11440530/72055332-f3020580-32ca-11ea-9fbe-7019dcc7606f.JPG)

**Comment by bodymovin** [comment]
Hi, it seems that for older AE version, when the project is new it doesn't have a file path and that would trigger this message.
Nothing will break but it will show up anyway.
It's fixed and deployed on version 5.6.1

**Comment by gigit95** [comment]
Thank you!
