### ISSUE TITLE
Bodymovin not loading because of CORS: No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by dpetr0ff** [airbnb/lottie-web#1931]
Hi Bodymovin,

My bodymovin Lottie animation was working fine, until I added SSL to my website. Not sure if that has any relation, but after doing so, I keep getting this error.

See attached screenshot:

<img width="2433" alt="Screen Shot 2020-01-09 at 12 04 13" src="https://user-images.githubusercontent.com/15979081/72062629-71b16f80-32d8-11ea-8933-d393325e5228.png">

This was literally the only thing I 'changed'.

It's a logo that animates on hover — you can see the website here: www.eskildhansen.com

Any ideas you can help with? Thanks!

**Comment by bodymovin** [comment]
Hi, you are loading a file from a different domain:
`Access to XMLHttpRequest at 'https://secureservercdn.net/160.153.138.177/9xr.d28.myftpupload.com/wp-content/uploads/2018/11/data.json' from origin 'http://www.eskildhansen.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
you need to configure `secureservercdn.net` to allow for requests from `http://www.eskildhansen.com`

**Comment by dpetr0ff** [comment]
Hm, okay. But it is the same domain, the data.json is uploaded in the media files of  eskildhansen.com's Wordpress.

How do I configure this secureservercdn? It's the first time I see it.

Thanks a million!

**Comment by bodymovin** [comment]
Hi, it seems you've fixed the issue in your site. Is that correct?

**Comment by dpetr0ff** [comment]
Hi

No, I still have the issue. For the time being, I simply disabled the external domain so my website is running normally.

But the issue is still there when I have the CDN enabled. I would appreciate any help!!

**Comment by bodymovin** [comment]
Perhaps you can try doing the fetch of the file yourself and pass it to the library as animationData instead of the path property.

**Comment by kudanai** [comment]
Hello. Since this issue has become stale I'm going to close it for now. Please re-open it if it's still relevant.
