### ISSUE TITLE
Lottie Light Minified Gets Mangled

### ISSUE THREAD

**Issue by JaceHensley** [airbnb/lottie-web#1936]
**Tell us about your environment**

* **Browser and Browser Version:** FF Dev v73
* **Lottie Web Version:** 5.6.0
* **After Effects Version:** N/A

**What did you do? Please explain the steps you took before you encountered the problem.**
`import {} from 'lottie-web/build/player/lottie_light.min.js'`

**What did you expect to happen?**
Everything to work

**What actually happened? Please include as much _relevant_ detail as possible.**
I'm getting an error in console saying lottie is not defined. After checking out the source code I can see that the minified version has it's variable names mangled.

It's returning `lottie` but the `lottie` variable is getting renamed to `ue`, but not in the return statement.

Switching the import to `'lottie-web/build/player/lottie_light.js'` fixes the problem. This also wasn't a problem at `lottie-web@5.5.7`

**Comment by adrienharnay** [comment]
Can confirm this was introduced with 5.6.0

**Comment by bodymovin** [comment]
should be fixed in version 5.6.2
Reopen if necessary
