### ISSUE TITLE
Bodymovin export issure

### ISSUE THREAD

**Issue by jboydWAFB** [airbnb/lottie-web#1937]
I have no clue what I am doing wrong.

Attached is the AE file, when I export in bodymovin it just doesnt appear. 

I have the stroke effect on it. I know masks arent entirely supported yet, but is there a way to get around this or a way i can get this animation in a json file a different way?

[MardiGrasCentralLogo.aep.zip](https://github.com/airbnb/lottie-web/files/4048653/MardiGrasCentralLogo.aep.zip)

**Comment by bodymovin** [comment]
Hi, adjustment layers aren't supported and stroke effects don't work well with non closed masks.
Not sure there is a workaround for this type of animation.
You might want to export a video or use as an image sequence.

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
