### ISSUE TITLE
3D keyframes not exporting with Bodymovin

### ISSUE THREAD

**Issue by shelli220** [airbnb/lottie-web#1942]
Does anyone know why the 3D keyframes don't export? I'm more experienced with AE, but not so much with Bodymovin. Thanks!

**Comment by MehdiRaash** [comment]
AE conversion into BodyMocin is not what you maybe think. it has its own limitations. check the website out to get familiar with the capabilities .
Supported Features
_**Shapes 
paths, ellipses, stars, rectangles
fills, stroke, gradient fills and gradient strokes
dashes
trim paths (partial)
rounded corners
transforms (position, anchor point, rotate, scale, opacity, skew, skew axis)
Solids
Images
Comps
Nulls
Texts
Most fonts are supported, they can be exported as shapes or as text provided you load the font on the browser
A single text declination is supported per textbox.
Not supported: text decorations like Small caps, or Vertical Scale.
Cameras (partial)
Expressions
Expressions. Partially supported. More and more expressions are supported on each release.
If you have any trouble with one, let us know.
Expression sliders are supported.
General supported properties
transform (rotate,scale,position,anchor point, opacity)
time remap
masks (additive, and in some cases difference, inverted and subtractive)
luma and alpha masks (with the svg renderer)
Supported effects (with the svg/html renderer)
fill
pro levels
drop shadow
tint**_
tritone

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
