### ISSUE TITLE
Could not export files 

### ISSUE THREAD

**Issue by Jazonel** [airbnb/lottie-web#1946]
Im using AE 2019

im trying to export a json file but bodymovin says  "Could not export files is Preferences > scripting & Expressiones > Allow Scripts to write files and access Network enabled?" i dont find these preferences to change.

**Comment by Jazonel** [comment]
![image](https://user-images.githubusercontent.com/46760082/72631833-fcbae700-3922-11ea-8359-3c8bb581e939.png)

**Comment by bodymovin** [comment]
Hi, AE 2019 has that option in that location.
Go to Edit and it should be there.

**Comment by emieljanson** [comment]
I have the same issue but do have the Allow Scripts to Write... option checked. Tried reinstalling bodymovin and lottefiles too.

**Comment by hamza28261** [comment]
go to edit -> Prefrences -> general than click on Allow scripts to write files and access network
![123](https://user-images.githubusercontent.com/25684299/97109337-84285880-16f4-11eb-9c65-c45e1f9d0969.jpg)
