### ISSUE TITLE
Feature Request：Multi Animation Relative Mix

### ISSUE THREAD

**Issue by umlearn** [airbnb/lottie-web#1951]
I'm curious, can bodymovin allow different animation parameters of the same element to be dynamically mixed? For example, the action of a character is switched to another action of this character, so that we can control the action of the character through code more smoothly.

like this demo：
https://dragonbones.github.io/demo/CoreElement/index.html

**Comment by bodymovin** [comment]
There is nothing built in for this, but if you can replicate this behavior in AE (perhaps with expressions and time remapping), you can achieve it.
