### ISSUE TITLE
What is the best way for implementation to HTML

### ISSUE THREAD

**Issue by yigitersoy87** [airbnb/lottie-web#1952]
Hello,

I used Lottie Web Player, it's so easy to implement but not responsive.

Now i render via bodymovin and activate "demo" on settings. Copy and paste this code to HTML

<div id="lottie"></div>
<script>
    var animationData = ...
.....
...
....
</script>

Its working and also responsive. But i wanted to ask if i do right or miss something. 

**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, depending on what you need as responsive.
But you might want to take a look at the preserveAspectRatio property:
https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#preserveaspectratio

**Comment by yigitersoy87** [comment]
> Hi, depending on what you need as responsive.
> But you might want to take a look at the preserveAspectRatio property:
> https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#preserveaspectratio

Thanks for the link. Actually i am happy about being responsive after Bodymovin export demo and copy index.html code into my HTML. But i wanted to ask if my way is right. The above link you shared can help if i use Lottie Web Player? https://lottiefiles.com/web-player

**Comment by bodymovin** [comment]
I'm not sure you can set that property with the player. You should ask the lottie files team.
