### ISSUE TITLE
Unable to preview Animation

### ISSUE THREAD

**Issue by SeanBrodeur** [airbnb/lottie-web#1953]
I'm having problems previewing my animations within Bodymovin. At first, I thought I was using an unsupported feature, but even after creating a simple comp with a scaling shape, I am unable to get anything. 

I am using AE 2020 v17.02 build 26, macOS 10.15.2, and am using the latest version of Bodymovin off of the creative cloud store. 

File is linked below, thanks for any help you guys can offer!

[PS-Logo-Animation-R1.aep.zip](https://github.com/airbnb/lottie-web/files/4091659/PS-Logo-Animation-R1.aep.zip)

**Comment by bodymovin** [comment]
Hi, how are you trying to preview them?

**Comment by SeanBrodeur** [comment]
Thanks for your quick response! 

Using the "preview" button within the extension interface. Nothing populates the screen, and I get 0/0. 

Does this help?

**Comment by bodymovin** [comment]
Did you click on browse and selected the exported animation?

**Comment by SeanBrodeur** [comment]
Ah! It seems like I'm no good at following directions.

That solves that, thank you for your help
