### ISSUE TITLE
Having <text> in my json, and changing the the text 

### ISSUE THREAD

**Issue by MehdiRaash** [airbnb/lottie-web#1954]
Thanks for being available for each issue.
My final exported JSON has text in it, I mean text tag.
How can I change the Text on the fly, without changing the JSON by the hand or changing the text innerHTML by the hand? 
what is the best way to accomplish this?

**Comment by bodymovin** [comment]
Hi, does this help?

**Comment by MehdiRaash** [comment]
Unfortunately there is not such a method, I'm using 5.5.9.

**Comment by bodymovin** [comment]
There should be, can you share a link with your implementation?

**Comment by MehdiRaash** [comment]
Thanks, I've already emailed a rar file to you.

**Comment by bodymovin** [comment]
Do you have an online link I can check?

**Comment by MehdiRaash** [comment]
https://codesandbox.io/s/kind-framework-4c80l

**Comment by MehdiRaash** [comment]
Finally! I found it, But there's a question.
![image](https://user-images.githubusercontent.com/6185507/73118111-c43f8c80-3f64-11ea-84dc-b201c78734e9.png)

In this pic, Do I have 15 **composition**?

I uploaded another JSON file which its **anim.renderer.elements** has 12 item. 

Why some exported JSONs have 1 item and some have more than that in the  **anim.renderer.elements** ?
What does it mean?

Thanks.

**Comment by bodymovin** [comment]
Hi, those are all the layers exported from After Effects.
For example index 4 is a Composition which would have in turn its own set of layers
