### ISSUE TITLE
bodymovin does not export png sequence

### ISSUE THREAD

**Issue by gabrielmazor** [airbnb/lottie-web#1959]
Hi,

I'm trying to export a composition made by single frame png photos, done it before and everything was great.
Lately, when I'm trying to export it does nothing in the end, once I managed to make it work by restarting my computer. However, that seems not to solve the problem anymore.

Any idea what could be the issue? Am I doing something wrong?

<img width="558" alt="Screen Shot 2020-01-28 at 21 19 46" src="https://user-images.githubusercontent.com/60404700/73297363-25d95280-4214-11ea-9213-799eb294267e.png">

Thanks.

**Comment by bodymovin** [comment]
Hi, I think this is related to this issue
https://github.com/airbnb/lottie-web/issues/1944
Does your export file name have a space on it?
Can you try upgrading to version 5.6.3?

**Comment by gabrielmazor** [comment]
Upgrading to version 5.6.3 fixed the issue, thanks again :)
