### ISSUE TITLE
Problem with rounded strokes

### ISSUE THREAD

**Issue by edumaziero** [airbnb/lottie-web#1962]
**Tell us about your environment**
• iMac OSMojave 10.14.6
• Adobe After Effects CC 2017
• Bodymovin 5.5.10
• Google Chrome V9.0.3945.130

**What did you do? Please explain the steps you took before you encountered the problem.**
I made an animation using strokes and trim paths combined with alpha mode to fill a logo shape. This is the configuration of the stroke:

• Line Cap: Round Cap
• Line Join: Round Join

**What did you expect to happen?**
I wanted the logo shape to be filled with rounded strokes.

**What actually happened? Please include as much _relevant_ detail as possible.**
I rendered the file using Bodymovin. In the Lottie preview, what happens is that the stroke gets weird, kind of a squared appearance, right when it starts.

• Lottie preview: https://lottiefiles.com/share/oTvCG8

**Please provide a download link to the After Effects file that demonstrates the problem.**
After Effects file: https://drive.google.com/drive/folders/1uZiE7bB_eF4GG60Tkrhic9AvZZHc78NI?usp=sharing

**Comment by bodymovin** [comment]
Hi, the problem is how svgs mask strokes.
You will need to add a rectangle that covers the full surface of the stroke with a fill with opacity 0 for it to look correctly.

**Comment by edumaziero** [comment]
It worked. Thanks a lot!

**Comment by kpeatuff1** [comment]
> Hi, the problem is how svgs mask strokes.
> You will need to add a rectangle that covers the full surface of the stroke with a fill with opacity 0 for it to look correctly.

I saw your recommendation "add a rectangle that covers the full surface of the stroke with a fill with opacity 0 for it to look correctly.". Where do I need to add a rectangle? Like a new layer or inside the current layer? I tried both ways but it doesn't work. Please, check the preview and explain to me what I did wrong? Thanks.

Lottie preview: https://lottiefiles.com/share/em9h1ch8
Source file: https://www.dropbox.com/s/zziej0pycd5k3y9/Big%20logo%20Collect.zip?dl=0
