### ISSUE TITLE
Gradient rendering problem using BattleAxe Overlord and Bodymovin

### ISSUE THREAD

**Issue by firudenis** [airbnb/lottie-web#1968]
**Tell us about your environment**
* **OS: macOS Catalina Version 10.15.2**
* **Browser and Browser Version: Google Chrome Version 79.0.3945.130**
* **After Effects Version: 17.0.2**
* **Illustrator Version: 24.0.3**
* **Bodymovin Version: 5.6.3**

**What did you do? Please explain the steps you took before you encountered the problem.**

I am working on a project which involves gradients. I export the elements for the animation from Adobe Illustrator (Version 24.0.3) using BattleAxe Overlord. Everything seems to be exported fine, all the gradients look fine in the composition panel, but when I render them using Bodymovin, the gradients get mixed up.

**What did you expect to happen?**

I expected the result to be the same as the one in the composition view
<img width="529" alt="Screen Shot 2020-01-31 at 18 32 15" src="https://user-images.githubusercontent.com/15219672/73557324-a6d55b80-4459-11ea-88d8-31f4d26a378b.png">

**What actually happened? Please include as much _relevant_ detail as possible.**

After the render is complete, I get this result in both, the browser and the render preview of the plugin. I have a lot more elements to add to the scene, but I got into this problem right in the beginning.

<img width="412" alt="Screen Shot 2020-01-31 at 18 43 41" src="https://user-images.githubusercontent.com/15219672/73557430-d6846380-4459-11ea-810f-2dd2cbfe02b4.png">

**Please provide a download link to the After Effects file that demonstrates the problem.**
[animation.zip](https://github.com/airbnb/lottie-web/files/4140493/animation.zip)

**Comment by bodymovin** [comment]
@firudenis Hi, this is happening because gradient data is read dirrctly from the AE file trying to parse the content.
Try renaming the gradient properties on each group to more unique names and it should work fine.
I'll try to improve this on the next release.

**Comment by bodymovin** [comment]
I just tried renaming the 5 groups from Layer 1 to `GroupLayer1 1`, `GroupLayer1 2`, etc and it was enough

**Comment by firudenis** [comment]
Thank you! I just tried what you suggested and it works.

**Comment by meylinbayr** [comment]
Hello, I have tried renaming the Gradience layers, however it renders them in Black&White. I also save each file before exports so it pulls the correct data on colours. Any solution for the black&white?

**Comment by bodymovin** [comment]
@meylinbayr hi, can you share the .aep?

**Comment by meylinbayr** [comment]
Sure thing @bodymovin attaching it here
[Activities_background (1).aep.zip](https://github.com/airbnb/lottie-web/files/4409155/Activities_background.1.aep.zip)

**Comment by bodymovin** [comment]
@meylinbayr I exported it and everything seems to work fine. Is your AE or OS on different language than English?
Can you share your exported json file?

**Comment by meylinbayr** [comment]
Hello, yes exports correctly, but the first frame the gradience should be dark blue, right now is purple, which is correlated to the purple of the mid frame. Unfortunately if you look closely in the first frame, it is  not exported 1:1 with the AE file.

**Comment by bodymovin** [comment]
@meylinbayr I renamed the layer named "3" to "3a" and that layer seems to be fixed.
Because of the way gradient data is retrieved, it might happen that if layers are named similarly, the data is incorrect.
for example layer "3" can be mistaken by layer "33"

**Comment by Storyteller-Adam** [comment]
Im having a similar issue where im trying to import a gradient that has about 20 steps but only the first nine make it through

**Comment by bodymovin** [comment]
@Storyteller-Adam hi can you share the .aep?

**Comment by Storyteller-Adam** [comment]
@bodymovin im afraid i can't since it's under NDA, but you can recreate this by making a gradient in illustrator with over 10 steps and then import it to AE using Overlord

**Comment by bodymovin** [comment]
@Storyteller-Adam I don't have Overlord. Could you create a simple example that doesn't violate the NDA?

**Comment by Storyteller-Adam** [comment]
I could but the issue is with the plugin specifically
