### ISSUE TITLE
Counter text not working

### ISSUE THREAD

**Issue by Pnet-C** [airbnb/lottie-web#1970]
**Tell us about your environment**

* **Firefox 71.0 (64-bit):**
* **After Effects CC19 + 20:**

**What did you do? Please explain the steps you took before you encountered the problem.**
I created a circle graph using trim paths represent a percentage. I then pick whipped a text layer to the trim paths endpoint and used the Math.round number expression to round up the number.
So when the circle went to 75% the text layer counted up to 75%.
I also tried the same thing using the slider effect on the text layer to make a counter. 

**What did you expect to happen?**
The embedded .json animation to could up from 0% to 75% and stop.

**What actually happened? Please include as much _relevant_ detail as possible.**
The number starts at zero than flickers different numbers like it's glitching and the ends on either 75% or in some exports it ends on no number. Inspecting the element, it looks as if it should count normally. 

**Please provide a download link to the After Effects file that demonstrates the problem.**

The text is in white so you may need to change the background colour to see it.
[Web3v1-Beards.html.zip](https://github.com/airbnb/lottie-web/files/4143809/Web3v1-Beards.html.zip)

**Comment by bodymovin** [comment]
Hi, if you are exporting text as glyphs, you need to provide all the necessary glyphs for it to work.
You should create an extra text layer with all number characters from 0 to 9 and put it outside the workspace so it doesn't get rendered but the glyphs get exported.

**Comment by ision-industries** [comment]
> Hi, if you are exporting text as glyphs, you need to provide all the necessary glyphs for it to work.
> You should create an extra text layer with all number characters from 0 to 9 and put it outside the workspace so it doesn't get rendered but the glyphs get exported.
@bodymovin so lets say I have a full sentence full of text as glyphs. So in order for the glyphs to work correctly I need to have an extra hidden layer with numbers 0-9 and then the sentence glyphs will work? Anytime I want to export glyphs with bodymovin I just need to have an extra layer with literally the numbers 0,1,2,3,4,5,6,7,8,9? Thats it?

**Comment by bodymovin** [comment]
@ision-industries you would need to provide all the characters (glyphs) your sentence needs

**Comment by Pnet-C** [comment]
Thank you so much, I wasn't aware of this. Cheers!

**Comment by ision-industries** [comment]
@bodymovin tanks for the clarification but I am still a bit confused. So I will need to have my full sentence as shape layers that are visible layers and I also need to have other shape layers with glyphs 0-9 as hidden layers? I am still slightly confused.

**Comment by bodymovin** [comment]
@ision-industries  you need a text layer with the characters that your text layer will need.
Usually the range "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789" is a common case

**Comment by Avimose** [comment]
> Hi, if you are exporting text as glyphs, you need to provide all the necessary glyphs for it to work. You should create an extra text layer with all number characters from 0 to 9 and put it outside the workspace so it doesn't get rendered but the glyphs get exported.

Thank you so much! You saved me some time!
I didn't thought about it that way. 👍 👍

**Comment by Asim740** [comment]
The number counter animation/expression worked fine in the older bodymovin versions, but it doesn't work in the most recent one. I even tried Version 5.12.1, but it still doesn't work. the numbers don't animate. I added glyphs from 0 to 9

**Comment by bodymovin** [comment]
@Asim740 can you share the .aep?

**Comment by Asim740** [comment]
Here is the AEP file

**Comment by bodymovin** [comment]
@Asim740 email attachments don't go through github, can you post it here?

**Comment by Asim740** [comment]
> @Asim740 can you share the .aep?

Just shared the AEP file  https://drive.google.com/file/d/19Vt9wpYXu5M5hwH_T8ma9f-GrVbyW4xj/view?usp=sharing

**Comment by bodymovin** [comment]
@Asim740 It seems that the expression interface is not working, but I haven't changed that in a long time. You mentioned that it was working in the past, do you have an exported json that works correctly with an older version so I can check it out?
Also, a link with the animation working would be helpful.
