### ISSUE TITLE
How to select a part of animation for hovering over?

### ISSUE THREAD

**Issue by artemdzyuba** [airbnb/lottie-web#1971]
Hello. I use bodymovin+GSAP+Scrollmagic. I need to show a popup while hovering over a part if image. For example, I need to show a popup on hovering a building here: http://doqas.com/scrollmagic/. So, I need to address directly to the part of image, or use somehow coordinates of the object.

Can I somehow do this? Or maybe there is a workaround, like exporting a single-frame svg (how?) and placing it over the bodymovin div?

Hope I can find a solution here.

**Comment by bodymovin** [comment]
Hi, does this help?
https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript

**Comment by Inventsable** [comment]
You could assign an HTML ID (via name like "#building") to the layer, then add an event listener for mouse enter on your window.onload

**Comment by artemdzyuba** [comment]
Sounds too fantastis to believe! I go to check this out.
