### ISSUE TITLE
after rendring, the jason and html file missing elements.

### ISSUE THREAD

**Issue by Asim740** [airbnb/lottie-web#1975]
![Screenshot (73)](https://user-images.githubusercontent.com/60739504/73936147-fdccac00-4903-11ea-832f-e949fd6bc216.png)
![Screenshot (74)](https://user-images.githubusercontent.com/60739504/73936162-045b2380-4904-11ea-95d7-f35f7558a2c0.png)

 Browser Version: Version 80.0.3987.87 (Official Build) (64-bit) * 
After Effects Version: 16.1.01
bodymovin version: 5.6.3

i have created DNA aimation with PNG logos, it doesn't export correctly, after rendring the HTML and JASON file missing elements.

**Comment by rocketluz** [comment]
Have you tried enabling the export of assets?
![image](https://user-images.githubusercontent.com/59647231/73937890-55f4b580-48e6-11ea-9efd-08f929a5bda7.png)

![image](https://user-images.githubusercontent.com/59647231/73937945-7c1a5580-48e6-11ea-8957-f165778788c2.png)

**Comment by Asim740** [comment]
Yes, I tried the export of assets, but still, nothing has changed, i would like to add some info"I have used true duplicator plugin for duplicating composition layers, and I have used beam effect in the middle of two circles, and gradient color over it"

**Comment by bodymovin** [comment]
Hi, can you share the .aep and the assets used on the animation?

**Comment by Asim740** [comment]
> Hi, can you share the .aep and the assets used on the animation?

Hi, here is the link of aep file
https://drive.google.com/file/d/1ArLjUQKgIU7qnvuZhePzeAhMzvx8OqNz/view?usp=sharing

**Comment by Asim740** [comment]
here is zip file
[DNA2 folder.zip.zip](https://github.com/airbnb/lottie-web/files/4199070/DNA2.folder.zip.zip)

**Comment by Asim740** [comment]
I'm waiting, please someone check this problem

**Comment by Asim740** [comment]
Hi, i find out the problem, i have used Beam effect in my After effects file, but bodymovin is not exporting beam layer.
