### ISSUE TITLE
Json not found in my Rails project

### ISSUE THREAD

**Issue by DamienCompere** [airbnb/lottie-web#1979]
I try to render a svg with bodymovin and I have the answer that my json is not found, 
I placed my json file in assets/images/json/economie.json
And in my javascript file I call it like this : 
```
const animation = bodymovin.loadAnimation({
    container: document.getElementById('time-test'),
    renderer: 'svg',
    loop: true, 
    autoplay: true, 
    path: "app/assets/images/json/economie.json"
  })
```
With that, I have the error : 

`sms.js:13 GET http://localhost:3000/app/assets/images/json/economie.json 404 (Not Found)`

Do you know where am I supposed to keep my json file to make it work ?

**Comment by bodymovin** [comment]
hi, it depends on how your web server is setup.
If you have a working link to share, I can check it out

**Comment by DamienCompere** [comment]
I don't have working link, but if you  know what file should I check, i could show you

**Comment by bodymovin** [comment]
It's difficult to help without a working link.
Try comparing the path of your index.html or any other asset with the json path and make sure the path is correctly set.

**Comment by DamienCompere** [comment]
After some tests, turn out that you need to store the json file in the public file otherwise it's not found !
