### ISSUE TITLE
Stroke and Alpha matte

### ISSUE THREAD

**Issue by VyborgSite** [airbnb/lottie-web#1980]
**Tell us about your environment**

* **Browser and Browser Version:**
Google Chrome
Version 80.0.3987.87 (Official Build) (64-bit)

* **After Effects Version:**
17.0.2 (Build 26)

Why it is happening?
1. Tongue
![Screen Shot 2020-02-07 at 4 07 43 PM](https://user-images.githubusercontent.com/16517198/74032927-27e6a280-49c6-11ea-8997-5f8a084aa1d3.png)

![Screen Shot 2020-02-07 at 4 24 54 PM](https://user-images.githubusercontent.com/16517198/74033057-6f6d2e80-49c6-11ea-92c1-a1f2449568aa.png)

Alpha matte
![Screen Shot 2020-02-07 at 4 28 45 PM](https://user-images.githubusercontent.com/16517198/74033345-f6220b80-49c6-11ea-93b9-c0c7b5092762.png)

Alpha inverted matte
![Screen Shot 2020-02-07 at 4 28 22 PM](https://user-images.githubusercontent.com/16517198/74033354-f7ebcf00-49c6-11ea-84e8-3934f0eb3954.png)

2. Eyes. Stroke subtract itself??
![Screen Shot 2020-02-07 at 4 07 31 PM](https://user-images.githubusercontent.com/16517198/74032934-2c12c000-49c6-11ea-838a-877b697d0844.png)

![Screen Shot 2020-02-07 at 4 24 11 PM](https://user-images.githubusercontent.com/16517198/74033070-72681f00-49c6-11ea-9134-ca0b1a426820.png)
![Screen Shot 2020-02-07 at 4 24 23 PM](https://user-images.githubusercontent.com/16517198/74033065-71cf8880-49c6-11ea-8ef0-2f6423b5372a.png)
![Screen Shot 2020-02-07 at 4 24 27 PM](https://user-images.githubusercontent.com/16517198/74033064-7136f200-49c6-11ea-8714-a71599e78dde.png)

No effects, no plugins, no scripts. Just layers and mask.
![Screen Shot 2020-02-07 at 4 33 31 PM](https://user-images.githubusercontent.com/16517198/74033611-9a0bb700-49c7-11ea-87b8-63d16eddc796.png)

**Comment by bodymovin** [comment]
Hi, if you are masking strokes with track matte masks, make sure you add a rectangle with a fill that covers the whole surface of the stroke.
Browsers don't handle correctly masked strokes otherwise.

**Comment by Eklor** [comment]
Hello I have the same issue, 
@bodymovin where should the rectangle with fill be placed? in the shape to be masked? What if I want to mask a stroke on transparent background?

**Comment by Eklor** [comment]
Hello I have the same issue,
@bodymovin where should the rectangle with fill be placed? in the shape to be masked? What if I want to mask a stroke on transparent background?
