### ISSUE TITLE
Cannot export image when rendering

### ISSUE THREAD

**Issue by cropher** [airbnb/lottie-web#1981]
I'm trying to render an AE composition that uses assets from Illustrator.

However, the rendering process in Bodymovin doesn't go beyond "Exporting image":

![Exporting](https://user-images.githubusercontent.com/9518923/74141569-7333c780-4bf7-11ea-8c20-10d29e6a7f10.png)

- The option to allow scripts to write files is active.
- The AE rendering queue is empty.
- I'm using Bodymovin 5.6.3, AE 15.1.2 and IL 22.1 on Windows.

Even when trying to render the composition without any animation present, the result is the same.

I uploaded the project consisting of the AE file and AI image:

[Animation.zip](https://github.com/airbnb/lottie-web/files/4180288/Animation.zip)

Is this a bug or am I missing something?

**Comment by marcinw788** [comment]
Same on OSX. But I have bodymovin-extension repo folder linked to AE. I see connection refused on http://localhost:3119/processImage/ and http://localhost:3119/ping/ (in dev tools). So i don't know if serwer is not starting?

**Comment by marcinw788** [comment]
So it looks like exporting images doesn't work on AE2018. I found in log something like that: 

`imagemin/index.js:42
module.exports = async (input, {glob = true, ...options} = {}) => {
                                             ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:567:28)
    at Object.Module._extensions..js (module.js:610:10)
    at Module.load (module.js:512:32)
    at tryModuleLoad (module.js:471:12)
    at Function.Module._load (module.js:463:3)
    at Module.require (module.js:522:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Volumes/CMX5002TB_DATA/other-repos/bodymovin-extension/build/server/main.js:1:80)`

On 2019 it works.

**Comment by bodymovin** [comment]
Indeed, it seems that the node server running on AE 2018 is not compatible with newer ES features.
Unfortunately fixing this is a very big task.
Not sure when and how I'll be able to fix this.

**Comment by cropher** [comment]
Thanks you for your responses! I updated to AE 17.2 and now it works. :)

**Comment by TheMoskey** [comment]
@bodymovin Is there an update?
Can't export images on AE 2018.

Cheers

**Comment by bodymovin** [comment]
@TheMoskey not yet, I suggest using bodymovin v5.5.x until it is fixed.
