### ISSUE TITLE
Is there any chance that bodymovin making larger files now?

### ISSUE THREAD

**Issue by gabrielmazor** [airbnb/lottie-web#1983]
Hi,

I exported a jpeg sequence using 5.5.8 into JSON that weights 13.5 MB. 
The total size of the jpegs is 36.2 MB.

Today, I managed to compress the size of all jpegs to 9 MB, 278 jpegs, 30 kb each on average.
But when I'm rendering it with bodymovin 5.6.3 the file size is getting over 25 MB!
I remember when I was first working on this animation I did many changes until I made it to weight 13.5 (and I can't remember what exactly), however, no matters what I'm trying now, the file size doesn't get below 25 MB.

There is a chance the newer version renders larger files?
Any tips on how to make the file size smaller? 

Thanks :)

**Comment by gabrielmazor** [comment]
Ok, maybe I have noticed something. I tried to export the JSON file without the images, and I have noticed that it converts the images to png files!! That weight 4 times more. Any solutions?

**Comment by bodymovin** [comment]
Have you tried using the Assets settings to compress the images?

**Comment by gabrielmazor** [comment]
Sure, the last render 5 minutes ago, I exported again the photos separately, with compression set to 70, and it exported jpegs the weight double the original files .

**Comment by bodymovin** [comment]
can you share the project and the required assets?

**Comment by gabrielmazor** [comment]
[Frames.zip](https://github.com/airbnb/lottie-web/files/4181955/Frames.zip)
The project is just a sequence of those images

**Comment by gabrielmazor** [comment]
Any ideas for what could be the problem?

**Comment by bodymovin** [comment]
the library that compresses the images that is being used might not be as efficient as external ones.
I'm adding an option to use original assets as part of the export instead of rerendering them.
It will be available on the next build.

**Comment by gabrielmazor** [comment]
Cool thanks. 
It would be possible to add those original assets to the JSON file?
You are doing a great job, making it better with each update, and giving great attention to the user needs!

**Comment by bodymovin** [comment]
yes, it will be compatible with adding them to the json file.
and thanks!

**Comment by bodymovin** [comment]
Done and available on version 5.6.4!
Feel free to reopen if you have any questions.

**Comment by jarovision** [comment]
@bodymovin hey there and thank you so so much for your work! its really amazing!!

one more thing regarding this topic.. i am using the "copy original assets" function for an image sequence of 300 pngs. the total size of all the pngs is 670kb. when i export through bodymovin with the "original assets" option enabled, i end up having a json file which is about 9mb. do you have an idea why? or any other ways of how to make the file smaller?

[test_image_sequence.zip](https://github.com/airbnb/lottie-web/files/4932575/test_image_sequence.zip)
