### ISSUE TITLE
Dynamically load image from url

### ISSUE THREAD

**Issue by Siddhar109** [airbnb/lottie-web#1988]
**Tell us about your environment**

* **Browser and Browser Version: Chrome 79.0.3945.130 (64 bit)**
* **After Effects Version: 15.0.0**
* **Bodymovin : 5.6.3**

**What did you do? Please explain the steps you took before you encountered the problem.**
I modified the Bodymovin json file image path to a image url.

**What actually happened? Please include as much _relevant_ detail as possible.**
When previewing on the web, the lottie animation works fine, but the image doesn't preload. Is there a way to load the image first then play the animation when using image url in the file.

**Please provide a download link to the After Effects file that demonstrates the problem.**
I have included the modified data.json file also the After Effects file.
[imgtest.zip](https://github.com/airbnb/lottie-web/files/4202587/imgtest.zip)

**Comment by bodymovin** [comment]
Hi, lottie always tries loading the assets relative to the json file location.
you might want to take a look at this if you want to specify a different path
https://github.com/airbnb/lottie-web/wiki/loadAnimation-options#assetspath
