### ISSUE TITLE
 Gradient Effect isn't working when i using after effect

### ISSUE THREAD

**Issue by wonsokoh1019** [airbnb/lottie-web#1989]
Environment
- After effect : 17.0.2 (language : English)
- OS : window 10 enterprise, version 1803 (language : English)
- Bodymovien : 5.6.3
----

![lottie](https://user-images.githubusercontent.com/56017035/74588770-cfa54580-5042-11ea-8dea-f7d265c3eadd.png)

After Effects gradient effects are not properly exposed when exported to json.

I've already applied almost all of the solutions used by people who had similar problems with me on lottie github. But I still didn't solve the problem.

[Methods I have used]

- Change to OS English

- After effect changed to English

- Change gradient color to RGB

- Save aep file before exporting

- AE and aep files on the same drive

- Layer names and attributes without special characters

- 4-color gradient of AE shape layer

Please tell me other ways besides these.
Raise Json file and AE file together.

https://drive.google.com/drive/folders/10qphBcMC1xe9Z6oYy9rSyzunr93HmrrG?usp=sharing

I'm very suffering for a week because of this problem.
Ask for a solution

**Comment by bodymovin** [comment]
Hi, 4-color gradient, or any gradient effect, are not supported by the player unfortunately.
Only supported gradients are the gradient properties for shapes
