### ISSUE TITLE
What effects does Bodymovin Support

### ISSUE THREAD

**Issue by ChristianWust** [airbnb/lottie-web#1991]
Hi there, 

Im trying to export a animation which used CC Bend It as a JSON file but the effect doesn't translate. Does Body moving support this effect and I  need to export with certain settings on does it now support this effect?

Many Thanks, 

Christian

**Comment by bodymovin** [comment]
Hi, unfortunately this type of effects are not supported. Very few are.
https://github.com/airbnb/lottie-web/wiki/Effects

**Comment by therealarikklein** [comment]
Hi, I can't seem to make my Gaussian BLur work on an Image any chance we know why?
