### ISSUE TITLE
Feature Request: Automatically named after the composition name

### ISSUE THREAD

**Issue by umlearn** [airbnb/lottie-web#1992]
Hi
Hoped that Lottie can automatically name according to the comp name, and the destination folder can also let the user specify a default one. It is now inconvenient to set each file for each export...
![image](https://user-images.githubusercontent.com/21360118/74624584-fd45d800-5183-11ea-8531-3ccb9c493cc3.png)

**Comment by bodymovin** [comment]
done! on version 5.6.6

**Comment by umlearn** [comment]
> done! on version 5.6.6

WONDERFUL!!!!

**Comment by umlearn** [comment]
> done! on version 5.6.6

I checked the function, but nothing seems happened?

**Comment by bodymovin** [comment]
it will work with compositions where you haven't set the destination yet

**Comment by umlearn** [comment]
> it will work with compositions where you haven't set the destination yet

Is it the wrong posture for me to open?

[Screen Recording 2020-03-06 at 11.28.58 AM.mov.zip](https://github.com/airbnb/lottie-web/files/4296314/Screen.Recording.2020-03-06.at.11.28.58.AM.mov.zip)

**Comment by bodymovin** [comment]
you are right, it seems that the very first time you do this after installation of this version, you need to select a folder.
After the first time, it should always work.
Can you try selecting a folder once and check with a second composition?
I'll try to fix it for the next build.

**Comment by umlearn** [comment]
It doesn't work either. here is what I thought
![lottie@2x](https://user-images.githubusercontent.com/21360118/76055280-22bd4900-5fae-11ea-9e30-d16261a3c6ce.png)
「destination folder」can store recent use path.
「use comp name」when it checked, it will automatically change the file name below.

**Comment by bodymovin** [comment]
Can you try using this version?
[bodymovin.zip](https://github.com/airbnb/lottie-web/files/4297769/bodymovin.zip)

**Comment by umlearn** [comment]
It works! You are the legend~ ✌️ 👍

**Comment by bodymovin** [comment]
nice!
