### ISSUE TITLE
[Bug Report]sourceRectAtTime() and ValueAtTime()，Incorrect result when passing in fixed parameters

### ISSUE THREAD

**Issue by Danjuanlab** [airbnb/lottie-web#1994]
![like_button_1](https://user-images.githubusercontent.com/42509669/74673391-0b2e4400-51ea-11ea-8001-af67302bcb52.gif)

I'm trying to make UI animations adaptive to content through expressions. In this animation, the relative position of the clap animation is determined only based on the initial state of the animation. Then I use sourceRectAtTime (0) and ValueAtTime (0) to get the width of some elements in the initial frame, and then calculate the clap part. Offset. But when exporting the animation, I found that the offset of the front end was always fixed.
[sourcerectattime introduction](http://expressions.aenhancers.com/layer-sub.html?highlight=sourcerectattime)
[valueattime introduction](http://expressions.aenhancers.com/property.html#valueattime-t)

After looking at the source code, I found that both functions lack support for incoming parameters. Currently takes time as a parameter. New time parameters passed in are ignored. This causes the front end to make errors when evaluating the expression. In addition, the calculation results of these two expressions on the front end are very puzzling to me.

I hope that this bug can be fixed during the next deployment so that this case can work normally.

[like button.zip](https://github.com/airbnb/lottie-web/files/4215102/like.button.zip)

**Comment by bodymovin** [comment]
Hi, unfortunately to make sourceRectAtTime correctly, I would need to render the layer at that specific time to get its bounding box.
In order to do that reliably I would need to have all state of the composition rendered at another point in time.
This is not an easy task and would probably have a big performance impact.
