### ISSUE TITLE
Feature request: Google Ads

### ISSUE THREAD

**Issue by rocketluz** [airbnb/lottie-web#2000]
I noticed the Google Ads platform does not support json files. 
I tried just changing the extension from json to js and it worked.
Another alternative would be to have the animation data inside the html file, I suppose.
@bodymovin 
Could you add a separate banner export option for Google Ads that would export a js file instead of a json file?

Thank you

**Comment by Inventsable** [comment]
I saw a discussion about this a while back here, in case it helps:

https://github.com/airbnb/lottie-web/issues/1896

**Comment by bodymovin** [comment]
Added for version 5.6.5
Will deploy it some time this weekend.
