### ISSUE TITLE
Improvement: base64 Images

### ISSUE THREAD

**Issue by rocketluz** [airbnb/lottie-web#2001]
When I export comps with pngs in them and include the images the json file, the size of the images is enormous. For instance, if I have an 85kb png in a comp, this is converted into base64 string bigger than 200kb! 

If I convert the same png to base64 using this tool (https://www.base64-image.de) The same image converts to a string of just 114kb.

Could the base64 conversion be improved?

**Comment by bodymovin** [comment]
Hi, if your assets are already optimized, you can select `Copy Original Assets` from the Assets menu in the comp settings and the exporter will use them as part of the export instead of generating new ones.

**Comment by foguetes** [comment]
thanks!
