### ISSUE TITLE
The future of lottie player

### ISSUE THREAD

**Issue by MehdiRaash** [airbnb/lottie-web#2003]
It's been about a month that I'm exploring bodyMovin and lottie-web, I have used this lottie in production related to TV broadcasting. 

> Up to now, **Lottie** has satisfied us, mostly. _very thankful of this!_

Web(ly) speaking, we need more control on the animations. 

- More **events** : for each layer (when a layer comes in and when it goes out, when a layer has meet the scale,skew to a desired number).  what do you think of this?

Is lottie gonna be just a player, or a **player + modifier**?

At the end, on What ways and aspects lottie is focusing now and for the future?

**Comment by bodymovin** [comment]
Hi, for some of those requirements you can use
https://github.com/bodymovin/lottie-api
regarding the future of lottie, it's up to the community and what is doable.

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
