### ISSUE TITLE
Alignment issues with render

### ISSUE THREAD

**Issue by ision-industries** [airbnb/lottie-web#2006]
**Tell us about your environment**
Using a 2012 MacBook Pro 13"
* **Browser and Browser Version:**
Didn't view it in browser
* **After Effects Version:**
CC '19

**What did you do? Please explain the steps you took before you encountered the problem.**
I am working on an animated infographic. All text are shape layers and one text shape layer is parented to the animated element. As you can see in the screenshot, all elements are perfectly set up and aligned properly. I even rendered with the option "text as glyphs" on and the problem still persists.  

![half doughnut chart error](https://user-images.githubusercontent.com/58711145/75074507-d5c77600-54c9-11ea-8efb-2778219cb967.png)

**What did you expect to happen?**
I expected the chart to animate with all elements aligned properly.

**What actually happened? Please include as much _relevant_ detail as possible.**

Here you can see the rendered animation and the alignment of all elements are thrown off. The animation still works fine it's just that none of the elements are aligned properly. [https://lottiefiles.com/share/M4g43k]

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by Danjuanlab** [comment]
Can you share your ape file？

**Comment by ision-industries** [comment]
@Danjuanlab yes, here you go
[Bodymovin Infographic Project.aep.zip](https://github.com/airbnb/lottie-web/files/4241495/Bodymovin.Infographic.Project.aep.zip)

**Comment by Danjuanlab** [comment]
> @Danjuanlab yes, here you go
> [Bodymovin Infographic Project.aep.zip](https://github.com/airbnb/lottie-web/files/4241495/Bodymovin.Infographic.Project.aep.zip)

The offset paths is not supported by now.

**Comment by ision-industries** [comment]
@Danjuanlab I just downloaded and installed version 5.6.5 and rendered the doughnut chart again. The alignment of the animated shape is still off. Check out this screenshot

![Screen Shot 2020-02-24 at 9 21 11 AM](https://user-images.githubusercontent.com/58711145/75160778-a6428480-56e8-11ea-9849-74fe5b214872.png)


Also, thank you for taking the time to test out the project for yourself.
I am having trouble rendering the "Animated years" composition. In that composition I have a simple text layer hooked up to a slider control to animate a growing number. It does not render correctly from bodymovin

**Comment by Danjuanlab** [comment]
Don't use **offset paths** to make this fan-shaped background. Use circular path strokes plus trim paths and rotation to achieve it. Use “value” instead of “text.sourceText”, the years expression will work. In addition, do not convert the text into a shape when exporting, otherwise the expression will be invalid.

**Comment by ision-industries** [comment]
@Danjuanlab thank you so much for reviewing my project file and for helping me resolve this issue.
