### ISSUE TITLE
Incorrect mime type when copying original assets into json

### ISSUE THREAD

**Issue by isaacrj** [airbnb/lottie-web#2012]
**Tell us about your environment**
Version 5.6.4

* **After Effects Version:**
AE 2020 

**What did you do? Please explain the steps you took before you encountered the problem.**
Build a simple composition. Drop a jpeg and a png into it. Export selecting "Copy Original Assets"

**What did you expect to happen?**
There should be two embedded image assets in the resulting JSON, one of them should start with "data:image/png;base64,....", the other one should start with "data:**image/jpeg**;base64,..."

**What actually happened? Please include as much _relevant_ detail as possible.**
The jpeg image asset starts with "data:**image/png**;base64,...", although the encoded base64 data is a jpeg image.

**Comment by foguetes** [comment]
I confirm also happening in version 5.6.5

**Comment by bodymovin** [comment]
I'll have a fix on the next version 5.6.6

**Comment by isaacrj** [comment]
Still happening on 5.6.6 when Assets -> Original Asset Names is checked

**Comment by bodymovin** [comment]
@isaacrj this should be fixed, can you share a project with the files?

**Comment by isaacrj** [comment]
You can download an example from [HERE](https://www.dropbox.com/s/incssysaubkj7h7/lottie-mimetype-bug-example.zip?dl=0)

Inside the ZIP file I have included a very simple AE composition, its footage, a screen capture showing the exact export parameters I'm using and the resulting JSON file, where you can see that both assets begin with data:image/png,  although the first one is actually a base64 encoded JPEG file.

**Comment by bodymovin** [comment]
@isaacrj fixed on version 5.6.7
Although using Original Asset Names when including them in the json file doesn't make a real difference.
