### ISSUE TITLE
Inline animation data in template not working

### ISSUE THREAD

**Issue by foguetes** [airbnb/lottie-web#2013]
I tried exporting a banner and checking the "Inline animation data in template" but it does not work.

I tested it in [h5validator](https://h5validator.appspot.com/adwords/asset), [Adform Studio](https://studio.adform.com/), and Brackets. It didn't work in any of them.

Here's an overview of the settings I exported it with:
![image](https://user-images.githubusercontent.com/25814516/75340262-77681200-5892-11ea-9654-dd4314f684e7.png)

You can have a look at the banner zip file here:
[160x600.zip](https://github.com/airbnb/lottie-web/files/4255352/160x600.zip)

**Comment by bodymovin** [comment]
It's the carriage returns from texts that are breaking the export.
`JSON.parse` is not interpreting them correctly.
I'll have a fix on the next release
