### ISSUE TITLE
Wordpress and WP Bodymovin plugin - Add link over animation

### ISSUE THREAD

**Issue by robbpuddu** [airbnb/lottie-web#2016]
Hello,
I have a Wordpress website and I'm using WP Bodymovin plugin to running animations done in After Effects. 

The plugin seems no longer maintained so I can't ask them my questions.

WP Bodymovin allows to add an animation everywhere through a shortcode but I want to add a link over my animations. It seems impossibile to add a link using the <a> tag with the shortcode inside it as text.

Is it possible to do that? 
thank you

**Comment by bodymovin** [comment]
Hi, I'm not sure how the WP plugin works, but I guess you can add an element on top using position absolute and use that as a link tag
