### ISSUE TITLE
Loading using .loadAnimation takes a lot of time on mobiles

### ISSUE THREAD

**Issue by artemdzyuba** [airbnb/lottie-web#2017]
Hello

I have a project with 11 .loadAnimation function calling. This takes huge amount of time (5+ sec) on mobiles, while the screen is completely white. The problem is doubled because I ask the user to rotate the device and reload the page (scrollmagic offset works bad withou that).

How can I load these animation in background so I could show at least all other web page content? 

This is the page (try it from mobile, around 10 Mb):
http://doqas.com/s1/valdai-infographics/bundles.page/media-infographics/media-infographics_eng.html

**Comment by bodymovin** [comment]
Hi, have you considered loading them when scroll reaches a certain part of the page?
Also, consider serving your files gzipped from your server, their filesize will be reduced significantly.

**Comment by artemdzyuba** [comment]
Hello! Sorry for late reply, didn't see the notification.
> Hi, have you considered loading them when scroll reaches a certain part of the page?
Actually, no. Is it a common practice? I've never seen examples with such lazy loading lottie files. Is there anything to read somewhere?

> Also, consider serving your files gzipped from your server, their filesize will be reduced significantly.
I couldn't find any reference on gzipping json files for lottie. Can it be found here https://airbnb.design/lottie/?

**Comment by bodymovin** [comment]
1. I don't know if there is any examples of it, but I think there are JS libraries that handle scrolling events that you can leverage to load animations.
1. Regarding gzipping, it's a standard method of serving any type of file from web servers compressed which reduce transfer bandwidth considerably. You can treat Lottie json files as any other type of files for that matter.
