### ISSUE TITLE
Issues with Shape with Drop Shadow on Safari 13.0.5 - only on retina screens 

### ISSUE THREAD

**Issue by vasso-pats** [airbnb/lottie-web#2019]
<img width="655" alt="with shadow" src="https://user-images.githubusercontent.com/61543641/75442767-d009de80-5968-11ea-826d-22aa33114438.png">
<img width="721" alt="without shadow" src="https://user-images.githubusercontent.com/61543641/75442785-d5ffbf80-5968-11ea-99e0-a6031d78da47.png">

**Tell us about your environment**
Bodymovin 5.6.5

* **Browser and Browser Version:**
Safari 13.0.5

* **After Effects Version:**
17.0.3 (Build 58)

**What did you do? Please explain the steps you took before you encountered the problem.**
I have a rectangle (shape) with a drop shadow (perspective effect) that is not animated. I export the json file of the animation using the bodymovin plug in.

**What did you expect to happen?**
I expected the rectangle and the drop shadow to be visible on all browsers & screens

**What actually happened? Please include as much _relevant_ detail as possible.**
The rectangle with the drop shadow is not visible on Safari on retina screens. I tested it on non-retina and the shadow appears correctly. I don't have any problem with Chrome and Firefox.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://we.tl/t-0oh7LQleOn

**Comment by bodymovin** [comment]
Hi, unfortunately to render drop shadows accurately large textures are used and it seems retina devices are not being able to render such a large one.
If I try to reduce the texture to fit this case I risk breaking other scenarios where distance are larger.
I'll add the possibility to configure this size on the next release.

**Comment by vasso-pats** [comment]
Thank you!
