### ISSUE TITLE
Multiple subtract and add masks

### ISSUE THREAD

**Issue by rocketluz** [airbnb/lottie-web#2020]
I'm having an  issue trying to combine add and subtract masks in one layer.

Here's an example. I have an add mask for the outline of the Robot and a subtract masks to remove the white background from the empty parts. After exporting with lottie the white jpeg background becomes visible.

The After Effects project is attached if you'd like to have a look.

![image](https://user-images.githubusercontent.com/59647231/75462323-5d0e6100-5984-11ea-9b3e-62a69babf615.png)

![image](https://user-images.githubusercontent.com/59647231/75462372-74e5e500-5984-11ea-9db9-ff44882c6bb1.png)

![image](https://user-images.githubusercontent.com/59647231/75462095-fb4df700-5983-11ea-87f9-e252105574cb.png)

[mask_test.zip](https://github.com/airbnb/lottie-web/files/4262622/mask_test.zip)

**Comment by bodymovin** [comment]
Hi, that combination of masks is only supported with the svg renderer, not canvas unfortunately

**Comment by wukongQ** [comment]
> Hi, that combination of masks is only supported with the svg renderer, not canvas unfortunately

What's the reason for canvas renderer doesn't support that combination of masks?

**Comment by bodymovin** [comment]
@wukongQ canvas doesn't have a masking method that can be used, so getting to copy the behavior of an svg mask element is more complex
