### ISSUE TITLE
Keep Stroke Width while scaling animation

### ISSUE THREAD

**Issue by Internet-Wolfgang** [airbnb/lottie-web#2028]
hi guys,
i am really looking for a possibility to maintain the Stroke-Width of my Lottie-Animations while scaling them. So while my animations on desktopish resolutions are for example like 500x500px, they are 100x100px (or whatever) on mobile. Anyway, the stroke-width always should stay at the same width (for example 5px). Anyone got a solution for that?

Thanks, 
Wolfgang

**Comment by bodymovin** [comment]
Hi, not sure there is a way.
You might try to target all strokes using javascript and update the stroke width on resize.
