### ISSUE TITLE
Lottie exporting white animation

### ISSUE THREAD

**Issue by UtkarshSingh5474** [airbnb/lottie-web#2029]
Hi,
First of all i am new to both Lottie And After Effects.
I made an simple loading animation and exported it as .json using Lottie AE plugin , but the exported animation only has white colour, it converted my whole animation into white. While exporting it's showing colours in preview but not in the exported .json file. I ran the file on Lotti Player and it's good with my colours and all. Please help me through this.
Below is the AEP file for my animation:
[https://drive.google.com/open?id=1Z9UNash5uegsTbEONZzoSPovkySavYwL](url)

**Comment by bodymovin** [comment]
Hi, how are you testing the animation? Can you share a link with your implementation?

**Comment by UtkarshSingh5474** [comment]
> Hi, how are you testing the animation? Can you share a link with your implementation?

Thanks for the quick reply but i figured it out myself... Actualy i was using fill effects and later i found out that they were not supported, so i just removed them and coloured the content of my shape layer.
