### ISSUE TITLE
Load too much, it will get stuck; is there any way to optimize

### ISSUE THREAD

**Issue by songxx1990** [airbnb/lottie-web#2030]
when i load too much lottiefile, it will get stuck;  more than 50 files in a page(electron);
singal file size: 350kb
is there any way to optimize

**Comment by bodymovin** [comment]
hi, can you ellaborate some more?
Are you loading 50 animations at the same time?

**Comment by songxx1990** [comment]
hi, thank you for your reply；
Do you know telegram's dynamic emoji pack? We need to make a similar page, there will be multiple dynamic expressions on the same page;
![截屏2020-03-01下午8 24 08](https://user-images.githubusercontent.com/17800811/75626519-bf709700-5bfa-11ea-84f8-e1fd7ac82409.png)
just like this;
But the page will freeze；

**Comment by songxx1990** [comment]
> 50 animations

yes， may be more than 50 animations at the same time，same page；

**Comment by bodymovin** [comment]
50 animations running in the main thread might be too much depending on their complexity.
Unfortunately I don't have a suggestion for this.
