### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by raghavpatnecha** [airbnb/lottie-web#2031]
https://lottiefiles.com/share/p8maAu

I exported the ae(latest 2020 version) animation to lottie json but when I try to play it gives the following error
![image](https://user-images.githubusercontent.com/25167912/75628648-1b3e1e80-5c01-11ea-9e39-ebc7f35f2a76.png)

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by bodymovin** [comment]
The animation seems to work fine in lottiefiles

**Comment by raghavpatnecha** [comment]
Yes , I am sharing the aep file and other files also.
https://www.dropbox.com/sh/k8wy5gctoherrl1/AABfprNIFfF3y8H-kQybL7CVa?dl=0
Basically mission.json is the file that is showing the error.
And Culture+Infographic.json is the modified version of mission.json and is working fine

**Comment by bodymovin** [comment]
Where are you seeing that error? On lottiefiles it seems to work fine

**Comment by raghavpatnecha** [comment]
The animation itself is not displaying. The animation is working fine in lottiefiles. But not on my page. If you can try running the web page I provided in the previously attached link. Maybe you can get a better idea

**Comment by bodymovin** [comment]
that site seems to have many files missing, but in the html file I see you are loading an older version of the library:
`https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.4.3/lottie.min.js`
can you try loading a newer one?
`https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.6.5/lottie.min.js`

**Comment by raghavpatnecha** [comment]
I think that was the issue. Using the latest file helped. Thanks a lot
