### ISSUE TITLE
Scaling Text layer problem on HD and fullHD resolutions  

### ISSUE THREAD

**Issue by MehdiRaash** [airbnb/lottie-web#2032]
I've got a text layer which scales smoothly on 4k screen but in hd and fullHD resolution scaling happens like step by step and has lag. 

Do you know why is that?

**Comment by bodymovin** [comment]
hi, have you tried profiling the performance on those devices?

**Comment by MehdiRaash** [comment]
No, the animation itself is a big deal, so I though there's a problem with text, although I have scales on other shapes with no problem.
