### ISSUE TITLE
Problem with "Wiggle transform" within Shape Layers

### ISSUE THREAD

**Issue by helloAdri** [airbnb/lottie-web#2033]
Hello !

I created an animation, using "wiggle transform" as well as repeaters, within several shape layers. 
From what i see now, Bodymovin cannot render properly a layer with wiggle transform applied in. And I can't convert it thanks to "convert expressions into keyframes" because "Wiggle transform" is not an expression.

The animation was made before I realized wiggle transform wasn't supported. And now the animation is validated by the client.

Here is the layers with wiggle transform applied :
https://imgur.com/LbVqR1G

Here is how the render is supposed to look like :
https://imgur.com/ups0FxM

Here is how Bodymovin renders it :
https://imgur.com/udZUSrj

Do you have any solution ?
Thanks a lot.

Adrien

**Comment by bodymovin** [comment]
Hi, unfortunately I'm not sure there is an easy solution for this.
Perhaps you can add a wiggle expression to the transform that behaves similarly and then convert to keyframes?

**Comment by noorani1373** [comment]
I have a problem with that too!!!

**Comment by helloAdri** [comment]
> Hi, unfortunately I'm not sure there is an easy solution for this.
> Perhaps you can add a wiggle expression to the transform that behaves similarly and then convert to keyframes?

Thanks man for your reply ! I ended up just redoing the animation of the stars from scratch, without using wiggle transform. Guess it's part of the process of knowing Bodymovin ! But thanks for your extension, it's great even though it cannot render everything !!
