### ISSUE TITLE
Bodymovin Animation Disappearing

### ISSUE THREAD

**Issue by UniqSchweick12** [airbnb/lottie-web#2035]
Hey there!
I'm using a bodymovin animation in a simple web page (I need to use the `demo.html` code out of bodymovin as using an embedded lottie player is not in an option in my situation. The tech we're using to display the page doesn't support most embedded formats)

I'd like to have the animation as a background to the page. However, whenever I set the div containing the animation to `position: absolute` in the CSS the animation vanishes, even with the animation element inside of a full page container.

Without the position set in the CSS, the animation appears, but it's pinned to the left side of the page, bumping all other elements on the page to the right of it.

Is there something I'm missing? Pretty much everything I've seen has said to set the element's position to absolute.

**Comment by bodymovin** [comment]
can you share the link of your implementation?
You probably need to set `top: 0; left: 0; width: 100%; height: 100%;`

**Comment by UniqSchweick12** [comment]
Here's the link to the repository: 
[https://github.com/UniqSchweick12/animation-test](url)

I just quickly tried your suggestion on my end. There doesn't seem to be any visual changes.

**Comment by UniqSchweick12** [comment]
I solved the issue. I was setting the lottie container to absolute, when all I needed to do was set the container holding everything else to absolute instead. Thanks for the assistance!
