### ISSUE TITLE
haiku big json file

### ISSUE THREAD

**Issue by yotavm** [airbnb/lottie-web#2036]
Hi, 
designer in my company start trying working with haiku to create animation for Lottie
(to save time study AE)
the problem is that the file is very big and I think more then he needs to be 
this is the animation https://lottiefiles.com/share/19DKza
any idea why

**Comment by bodymovin** [comment]
Hi, it seems that the haiku app doesn't round floating point numbers, so each value has a lot of decimals.
Perhaps you can run a regex to remove the extra digits?

**Comment by yotavm** [comment]
its help to reduce to size to 1mb 
but it still takes more time to see the animation form other animation in the same size 
why this is happening
https://lottiefiles.com/share/qwluds this is file in the same size
 
it's because the animation is more complex?

**Comment by marcinw788** [comment]
Compression on Lottie files is very good. You can us CDN with gzip.

**Comment by bodymovin** [comment]
@yotavm this animation has a base 64 encoded image as part of the json

**Comment by yotavm** [comment]
@bodymovin Thanks!! 
can you explain you found out that there is base 64 encoded image

**Comment by bodymovin** [comment]
If you open the json file you'll see there are base64 encoded assets on it

**Comment by yotavm** [comment]
@bodymovin
sorry for the many questions 
in this one, I don't have base64  -> https://lottiefiles.com/share/cg03D9
and I fix the floating number but it still takes more time to show animation then
https://lottiefiles.com/share/qwluds
(it does not look like the delay is the download time)

Mabey its because https://lottiefiles.com/share/cg03D9 has too many elements?

**Comment by bodymovin** [comment]
Yes, that animation seems to have too many vertices
