### ISSUE TITLE
Json file fails to render strokes correctly

### ISSUE THREAD

**Issue by awove** [airbnb/lottie-web#2040]
I'm exporting an animation made with strokes and the trim path effect (attached bellow) from after effects as a json file using the bodymovin plugin, for some reason when we play the json file as a loading screen animation on our website the stroke masks don't render correctly (example of the failed render bellow) but when we preview it on lottie it looks fine. Any suggestions for a fix ?

Thanks in advance.

[awove.zip](https://github.com/airbnb/lottie-web/files/4303017/awove.zip)

**Comment by bodymovin** [comment]
Hi, can you share a link where I can check the problem?

**Comment by awove** [comment]
Hey thanks for getting back to us.
Here is the link :)
http://34.90.77.55/

**Comment by bodymovin** [comment]
Hi, it seems you are using the html renderer instead of the svg renderer.

**Comment by awove** [comment]
oh sorry I'm new at this could you please point me to as where to find the svg option in the export menu ? because i can't find it, i have bodymovin version 5.6.5

Thanks for the help!

**Comment by awove** [comment]
for anyone interested here's a link of how to export as svg !
https://blog.mazegeek.com/lottie-svg-animation/
thanks for the help much appreciated !
