### ISSUE TITLE
Problem with drop shadow

### ISSUE THREAD

**Issue by rocketluz** [airbnb/lottie-web#2041]
The drop shadow effect is not rendering properly with bodymovin 5.6.6. AE 2020 on Windows 10.

It seemed to be working fine before.

The original comp looks like this:

![300x250_DE (0-00-03-13)](https://user-images.githubusercontent.com/59647231/76162384-84f88400-613d-11ea-9922-b270121d1aa8.png)

But after exporting it with boddymovin the shadows are cropped:

![image](https://user-images.githubusercontent.com/59647231/76161240-a784a000-6131-11ea-83fd-fc49b3c5ace2.png)

You can view the banner here:
https://studio.adform.com/share/bp74407fbbf136511a9fa8a4f18f9b0335

These are the export settings I used:

![image](https://user-images.githubusercontent.com/59647231/76162518-cc334480-613e-11ea-9bf4-dd6282495a66.png)
![image](https://user-images.githubusercontent.com/59647231/76162525-e10fd800-613e-11ea-94ba-1017400e4531.png)

I have uploaded the project file if you need to have a look.

[test.zip](https://github.com/airbnb/lottie-web/files/4303512/test.zip)

**Comment by bodymovin** [comment]
Hi, this has changed of version 5.6.6 indeed.
Now filters sizes need to be set manually. 
The default settings were becoming a problem for large resolutions.
Here is a link on how to set it manually.
https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#filtersize-svg-renderer

**Comment by rocketluz** [comment]
@bodymovin 
Anyway these could be bypassed or reverted back to the previous configuration when exporting banners?

Banners never use large resolutions.

Having to set that manually for each banner will be very time consuming and tedious.

**Comment by rocketluz** [comment]
@bodymovin 
Alternatively, the banner export template could include the filterSize parameter in it, so filters would always be supported.

Banner ads shouldn't be bigger than these resolutions:
https://support.google.com/google-ads/answer/1722096?hl=en#nonani_ads

**Comment by bodymovin** [comment]
Yes, I've added it back to the template. It will be available on the next depoy.

**Comment by kalpeshprithyani** [comment]
Another workaround is to add a fake extended container with opacity zero on the after effects layer itself.

**Comment by RoryVB** [comment]
Confirming what kalpeshprithyani said works. For example: You have a rectangle with drop shadow that doesn't display correctly (Let's call it Rectangle 1). Inside the Rectangle1 go to contents, duplicate Rectangle1, increase the size to 115 and set opacity to 0%. The drop shadow now has space to display.
