### ISSUE TITLE
[QUESTION] Same "ty"(type) constant for multiple effects

### ISSUE THREAD

**Issue by AnishGG** [airbnb/lottie-web#2042]
I have seen multiple effects have the same "ty" constant.
For instance: https://github.com/airbnb/lottie-web/blob/bf8217770e40cedad1f20ed52b24eddea9b82b77/docs/json/effects/slider.json#L24 and https://github.com/airbnb/lottie-web/blob/bf8217770e40cedad1f20ed52b24eddea9b82b77/docs/json/effects/layer.json#L24
Is this intentional or by mistake?
Because according to my understanding "ty" should be unique for each effect.

P.S.
I tried exporting files using bodymovin also. There I got "horizontal feather" and "vertical feather" both of "ty" equal to 0.

**Comment by AnishGG** [comment]
@bodymovin any insights would be much appreciated!

**Comment by bodymovin** [comment]
Only supported effects get exported with a unique type.
The rest are exported as Expression Controls. 
On the other hand, some Expression Controls get exported with the same type, because even if they are defined differently (like radial and slider) they are basically the same thing, a range.
