### ISSUE TITLE
Memory leak when using data:image/png in animation data.

### ISSUE THREAD

**Issue by rajputvai** [airbnb/lottie-web#2043]
**Tell us about your environment**
macOS High sierra 10.13.1
bodymovin/5.5.9/lottie.js

* **Browser and Browser Version:**
Chrome 80.0.3987.122 (Official Build) (64-bit)

* **After Effects Version:**
Cc2019 

**What did you do? Please explain the steps you took before you encountered the problem.**
I have a big dynamic animation loop. If I load them all together, the initial load takes 30-90 secs and the heap size goes up to 700MB and 300% CPU. To optimize this, I have split the entire animation into smaller chunks. I have built an animation Array[n] that has each chunk (a chunk is having animation data). At a time one animation will be playing eg: Array[0] animation will be playing and Array[1] animation will be ready to play (lottie.loadAnimation(nextAnimParams) with autoplay: false). Once Array[0] completes playing Array[1] will start playing and Array[0] will be destroyed and Array[2] will be ready to play, and this goes on. Some of those animation chunks are having data:image/png. 

I have observed that whenever the data:image/png animations play, the heap size grows exponentially even after destroying the old animation. 

**What did you expect to happen?**
Destroying animation should clean up the memory.

**What actually happened? Please include as much _relevant_ detail as possible.**
Head size grows exponentially when data:image/png is used in animation data
![Screen Shot 2020-03-10 at 8 20 27 PM](https://user-images.githubusercontent.com/2168116/76330271-a57a3700-6313-11ea-89cd-d522b524f019.png)

![Screen Shot 2020-03-10 at 8 21 09 PM](https://user-images.githubusercontent.com/2168116/76330312-b5921680-6313-11ea-9f1b-7591bafcdad3.png)

![Screen Shot 2020-03-10 at 8 21 41 PM](https://user-images.githubusercontent.com/2168116/76330337-bd51bb00-6313-11ea-8196-59ecfad2cc5f.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
Sample Link: https://cetaceanenglishspringerspaniel.htmlpasta.com/

**Comment by rajputvai** [comment]
Hi @bodymovin, I shall be most grateful if you can provide us any insights.

**Comment by bodymovin** [comment]
Hi, I've tested this loading 200 times an animation with 200 assets, and memory doesn't increase.
Can you share an example with your implementation?
