### ISSUE TITLE
Uncaught SyntaxError: The requested module '../../node_modules/lottie-web/build/player/lottie.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by vinhnghi223** [airbnb/lottie-web#2044]
**Browser and Browser Version:** Chrome, Version 80.0.3987.122 (Official Build) (64-bit)

**What did you do? Please explain the steps you took before you encountered the problem.**
I followed this tutorial https://josephkhan.me/lottie-web/:
 `npm install lottie-web` and then` import lottie from 'lottie-web';`

Then in the constructor() of the web component, I did the following:

```
this.anim= lottie.loadAnimation({
      container: this.shadowRoot.getElementById('anim'), 
      renderer: 'svg',
      loop: true,
      autoplay: true,
      animationData: './anim.json'
});
```
Later I start playing it: `this.anim.play()`

**What did you expect to happen?**
It works.

**What actually happened? Please include as much _relevant_ detail as possible.**
When the parent component appears, it does not render/show up. Instead there is this red error line in the console: **Uncaught SyntaxError: The requested module '../../node_modules/lottie-web/build/player/lottie.js' does not provide an export named 'default'**

**Comment by bodymovin** [comment]
hi, can you share a link with the project so I can check it out?
Besides this issue, any reason why you are not loading the library via the cdn?
You might get better performance keeping it out of your build.

**Comment by mikicof** [comment]
I’ve encountered the same error, it is because this does not provide a fully ES6 module.

It does when built via Webpack using the package.json main path and converting the file found into an ESM, but now that we have changed to Rollup.js we found out that we are unable to use it as a module.

Can you provide also an ES6 module?

Thank you

**Comment by michtio** [comment]
Bit poor to close this issue @bodymovin I think for modern builds and SSR apps it does need a full ES6 module / support. 

You closed an issue with "just use the CDN" in certain situations, CDN usage isn't preferably. Currently this package is also useless with vite.

**Comment by bodymovin** [comment]
@michtio the issue was closed after 2 months of inactivity and not getting a response from the OP.
But thanks for the comment, I'll try to do better next time.
Any suggestions to help to move this forward?

**Comment by michtio** [comment]
I think all we need is a simple ESM wrapper our the CJS module @bodymovin , that would solve a lot of issues

**Comment by bodymovin** [comment]
@michtio do you have a simple demo project to test it?

**Comment by ebofi** [comment]
.q-cache/vite/capacitor/deps/vue-router.js?v=adcf8f8f - Line 2335 - Msg: SyntaxError: The requested module '/src-capacitor/node_modules/@lottiefiles/vue-lottie-player/dist/vue-lottie-player.common.js' does not provide an export named 'default'

Same Issues Now

**Comment by RahulDey12** [comment]
Guys, I don't understand why it's taking so long to make a simple wrapper of ESM. Is it the man powers or negligence?
