### ISSUE TITLE
[QUESTION] About templating

### ISSUE THREAD

**Issue by loretoparisi** [airbnb/lottie-web#2045]
Supposed to have a set of AE animations, is there any way to load them a template engine so that expressions can be handled at run time? 

According to the docs I could start using `TextLayer.updateDocumentData` to update the text at run time:
https://github.com/airbnb/lottie-web/wiki/TextLayer.updateDocumentData

So assumed to have a text animation, I would use an expression to change the text, while using the same animation template.

**Comment by bodymovin** [comment]
Hi, I'm not sure if I follow exactly what you need. But does updateDocumentData work for your case?

**Comment by loretoparisi** [comment]
@bodymovin so it actually works and it is awesome!
This is my snippet inspired to a previous issue
```javascript
function UpdateGraphics(anim) {
        /**
            t: text value
            s: font size
            fc: fill color - array with RGB values ranging from 0 to 1
            lh: font line height
            sc: stroke color - array with RGB values ranging from 0 to 1
            j: justify
        */
        anim.renderer.elements[0].updateDocumentData({ t: 'Hello World!', s: 24, fc: [0.5, 0.5, 1] }, 0);
    }//UpdateGraphics
    function CreateGraphics() {
        return new Promise((resolve, reject) => {
            $.getJSON('data.json', (animationData) => {
                const elem = document.getElementById('lottie');
                const animData = {
                    container: elem,
                    renderer: 'svg',
                    loop: true,
                    autoplay: true,
                    rendererSettings: {
                        clearCanvas: false,
                        progressiveLoad: false, // Boolean, only svg renderer, loads dom elements when needed. Might speed up initialization for large number of elements.
                        hideOnTransparent: true //Boolean, only svg renderer, hides elements when opacity reaches 0 (defaults to true)
                    },
                    animationData: animationData
                };
                let anim = lottie.loadAnimation(animData);
                resolve(anim);
            })
        });
    }//CreateGraphics
    CreateGraphics()
        .then(anim => {
            UpdateGraphics(anim);
        });
```

Now my aim is to apply the replacement before running the animation, so that I can change the whole text from a placeholder text (coming from AES just to render the animation). Is that possibile? Maybe using `autoplay` and some run api?
Thank you.

**Comment by bodymovin** [comment]
Yes, the best approach is to load the animationData, traverse it to find the properties you want to update, and then pass it to lottie.
If you want to update the properties after the animation has been loaded, you can use the lottie-api library
https://github.com/bodymovin/lottie-api

**Comment by loretoparisi** [comment]
@bodymovin thank you I was thinking to a common parser api to traverse the `animationData` instead of modifying "by hand", so that to avoid any possibile typos or unsupported changes for a certain object type, like modifying a `TextLayer` manually etc.

I will have a look at the api then. In the meanwhile I have put the ongoing project here:
https://github.com/loretoparisi/lottie-adobe-after-effects-json-animation

In this example I would like to change animation speed as well:

```javascript
anim.renderer.elements[0].updateDocumentData({
            t: 'This is keyframe 0', 
            s: 78, 
            fc: Palette.color() 
        }, 0);
        anim.renderer.elements[0].updateDocumentData({
            t: 'This is keyframe 1', 
            s: 78, 
            fc: Palette.color() 
        }, 1);
```
(https://github.com/loretoparisi/lottie-adobe-after-effects-json-animation/blob/master/js/app.js#L252)

Using the  `TextLayer.updateDocumentData` I can change the keyframes 💯 , but how about other properties, can do this with the lottie-api?

Thank you!

**Comment by bodymovin** [comment]
@loretoparisi yes, you should be able to modify most of the properties with lottie-api

**Comment by loretoparisi** [comment]
@bodymovin thanks in advance for your help. As soon as I modify the properties with lottie-api, how can I serialize the animation back to JSON?
My aim is then to re-load the saved animation with all changes in place.

**Comment by bodymovin** [comment]
Hi, unfortunately, you can't serialize it back to JSON since the lottie-api updates values dynamically and doesn't generate a new serializable JSON object.
