### ISSUE TITLE
Rendering of masks taking a very long time...

### ISSUE THREAD

**Issue by mattrudd2020** [airbnb/lottie-web#2046]
**Tell us about your environment** Macbook Pro 16"

* **Browser and Browser Version:** NA
* **After Effects Version: 17.0.0** (down-graded from March 2020 version but still had the issue

**What did you do? Please explain the steps you took before you encountered the problem.**
Auto-traced each layer, to replace a stroke-width build effect with masks (Safari performance bad with stroke build)

**What did you expect to happen?**
For the comp to render fairly quickly

**What actually happened? Please include as much _relevant_ detail as possible.**
The rendering of the comp, with around 30 layers takes a long time. Layers contain nothing other than auto-trace masks.

AE file does seem very large, considering it only contains masks? And the original auto-tracing to create the mask-only layers does take around 60 minutes!

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/file/d/1yjxc-l9WG-dUgyqpVdrdGMWiuAymYtx3/view?usp=sharing

- this AE file is very large - could be an issue? No idea why mask layers on their own would be so big...

Thanks in advance!

**Comment by mattrudd2020** [comment]
Further info - just did a test rendering just one layer - exported after only a few minutes, but then file was over 6MB! So with all 36 layers the .json will be huge! 😫

**Comment by bodymovin** [comment]
Auto-tracing usually generates a keyframe per frame, and the masks have lots of vertices.
You can check it by focusing on any of the traced masks and looking at all the vertices it has.
Lottie exports all vertices as data, and that's why file size is so large.
For an animation like this, you should consider using a regular video.
