### ISSUE TITLE
Feature request: manually select lottie player file

### ISSUE THREAD

**Issue by rocketluz** [airbnb/lottie-web#2047]
Please add the ability to select a custom local lottie-player file from here:

![image](https://user-images.githubusercontent.com/59647231/76503772-be373980-6446-11ea-93c9-b1c3f4159254.png)

**Comment by bodymovin** [comment]
Hi, can you elaborate some more?

**Comment by remissao** [comment]
@bodymovin 

When we select locally from the dropdown menu, the lottie player file that is compiled with the extension is exported with the animation data.

What I would like to do is to be able to select my own .js player file and use that instead, so if something is broken with the current version of the player, I can still pick an older one that was custom made, for example.

**Comment by bodymovin** [comment]
available on version 5.6.7
