### ISSUE TITLE
Bodymovin fails to launch. Grey panel just appears. 

### ISSUE THREAD

**Issue by jakecarabott** [airbnb/lottie-web#2049]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by jakecarabott** [comment]
Hi guys,
Every time I try and launch Bodymovin it fails to load correctly. All that appears is an empty grey panel. I'm using AE 2017 and the latest version of Bodymovin. I've tried uninstalling and reinstalling both AE and Bodymovin - but the problem is still there. I have previously used Bodymovin before, however, this problem just came up today. I haven't installed any other plugins or extensions that could be conflicting with it. I'm hoping someone can shed some light on this. 
Attached is a screenshot and the AE file. 
<img width="1915" alt="Screen Shot 2020-03-14 at 11 09 56 am" src="https://user-images.githubusercontent.com/44606432/76670386-5c143b00-65e4-11ea-8b7e-d800ad9690d8.png">
[GloveheartHello.aep.zip](https://github.com/airbnb/lottie-web/files/4332088/GloveheartHello.aep.zip)

**Comment by bodymovin** [comment]
Hi, that error is not related to the gray panel. I'm not sure what might be the issue, but it's likely related to using an old version of AE.

**Comment by jakecarabott** [comment]
Hi. Thanks for your response. But I don't think its got to with the version of AE. BodyMovin seems to be working fine on my other desktop and it's using the same AE version? It was also working fine on this computer before the this problem occurred...
