### ISSUE TITLE
Nulls attached to Patchs not working (Hooker add-on)

### ISSUE THREAD

**Issue by zadlo** [airbnb/lottie-web#2050]
Hi,

I'm trying to speed up my workflow with simple character animation. Instead of using DuIK or cut-out animation I'm controlling shapes via Null to Path add-on called Hooker (https://aescripts.com/hooker/) you simply select point you want and attach to it a null for further control.

Problem is that Bodymovin does not export the expression/null or whatever and character is static in the parts where the hooker is animating.

![screen](https://user-images.githubusercontent.com/1122464/76678087-464b4980-65d5-11ea-936c-197a48835269.png)

Below I'm attaching a video comparison and aep

[Video](https://youtu.be/LrR1K98YWgg)
[AEP](https://github.com/airbnb/lottie-web/files/4332394/character_animation_hooker.aep.zip)

Thanks in advance,
Karol

**Comment by bodymovin** [comment]
Hi, there are several Null layers hidden in the composition.
You need to check the option `Select if you need HIDDEN layers to be exported` in the export settings for it to work correctly
