### ISSUE TITLE
Lottie animation - white flicker on iOS

### ISSUE THREAD

**Issue by fr8za** [airbnb/lottie-web#2051]
Hi there!

**Tell us about your environment**

I am not a programmer. :) I am building a website with WOCode and want to implement a lottie animation (only JPEGs) via the [Lottie Web Player](https://lottiefiles.com/web-player). This works fine via the html provided by lottiefiles, but I want to change the render mode from 'svg' to 'canvas' and don't know how to do this in the html code. This is the code:

`<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player
    src="https://assets2.lottiefiles.com/packages/lf20_p8gfRh.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;"  loop controls autoplay >
</lottie-player>`

The problem is, that my lottie animation shows a white flickering on iOS devices. This, after searching on the web, might be due to the render mode, which is set to 'svg' by default, and should be changed to 'canvas' to avoid the flickering on iOS. Unfortunately, I am not too much of a programmer, and don't know how to set this in html with the code provided by Lottie web player. Hope you can help! :) Thanks a lot!

* **Browser and Browser Version:**

 iOS 13.3.1

* **After Effects Version:**

CC2020 17.0.4 (Build 59)
Bodymovin 5.5.8

**What did you do? Please explain the steps you took before you encountered the problem.**

Made an Lottie animation with only JPEGs. Plays fine on desktop (Chrome, Edge, Firefox), and also on android mobile devices. On iOS (13) the animation has a permanent white flicker in it, tested on an iPhone 10 and iPhone 8 with the same iOS 13.

**What did you expect to happen?**

I hoped the lottie animation would play as correctly on iOS as on all other devices.

**What actually happened? Please include as much _relevant_ detail as possible.**

White flickering in the animation on iOS. After searching on the web, I found that the issue might be caused by the render mode of the lottie animation, which is usually set to 'svg' as default. But yet I don't know how to change this to 'canvas', as I am not a programmer using a websitebuilder platform (WithoutCode). On webflow the change of the renderer can be made easily, because it is set as an option to click. But in WOCode there is no such option, which is why I wanted to implement the html code directly, but don't know how to advise the animation to be rendered in the other mode.

![lottie_webplayer](https://user-images.githubusercontent.com/62169804/76678161-e30de700-65d5-11ea-80ba-6a7d30508ccc.jpg)

**Comment by bodymovin** [comment]
Hi, can you reach out to the lottiefiles team to get help about this?
I'm not familiar with the player and I don't know if this is possible.
