### ISSUE TITLE
[Question] Is gradient ramp effect supported in lottie-web?

### ISSUE THREAD

**Issue by saurabh-ramola** [airbnb/lottie-web#2052]
I created a solid layer and used the gradient ramp effect on it. I wanted to know if gradient ramp effect is supported as a feature in lottie-web. And if it's not what is the alternative to it if I want a gradient effect in the entire layer ?

**Comment by saurabh-ramola** [comment]
@bodymovin any insights would be much appreciated :smiley:

**Comment by bodymovin** [comment]
Hi, gradient ramp is not supported unfortunately.
