### ISSUE TITLE
How to get the image of each frame from lottie and merge lottie animation into a video?

### ISSUE THREAD

**Issue by mobilesite** [airbnb/lottie-web#2053]
I've got that we can record the lottie animation with puppeteer. But, since puppeteer relies on chromium which is 130Mb+, it's too big to load in a web page. 

Is there any other way that we can get each render frame (not keyframe) info from lottie, with witch we can translate it into base64 image? 

After that I want to merge the lottie animation into a video(video as the background). 

Thanks a lot!

**Comment by bodymovin** [comment]
Hi, if you use the canvas renderer, you could use the Canvas API to get a snapshot of every frame.

**Comment by mobilesite** [comment]
> Hi, if you use the canvas renderer, you could use the Canvas API to get a snapshot of every frame.

But it seems that there is a bug about outside fonts in canvas renderer: https://github.com/airbnb/lottie-web/issues/202

Can I get the accurate frame data by enter frame event?

**Comment by bodymovin** [comment]
the canvas renderer doesn't support text as font, but it does support it as glyphs.
Regarding the accurate frame data, not sure I understand what you mean, but you can use `anim.goToAndStop(frame, true)` iterating on every frame to visit each one of them and take a snapshot.
