### ISSUE TITLE
How should I sync the data change to the lottie JSON when updating text by the 'updateDocumentData' API?

### ISSUE THREAD

**Issue by mobilesite** [airbnb/lottie-web#2054]
I've got that I can edit text in lottie animation by the API 'updateDocumentData', and after that the animation changed. My question is how to sync the data change to lottie JSON or animationData so that I can save it and can continue to edit the lottie JSON next time by program.

**Comment by bodymovin** [comment]
hi, unfortunately that is not possible.
What you can do is traverse the json object and update those values without rendering the animation itself.

**Comment by mobilesite** [comment]
Thanks a lot.
