### ISSUE TITLE
[ERROR] Missing character from exported characters list

### ISSUE THREAD

**Issue by loretoparisi** [airbnb/lottie-web#2056]
In [this](https://lottiefiles.com/4142-welcome-animation) animation 
there is a `TextLayer` which text I can easily update thanks to the `updateDocumentData` api like here:

```javascript
anim.renderer.elements[0].`({
            t: "WCLM", 
            s: 78, 
            fc: Palette.color() 
        }, 0);
```

The problem is this kind of animation have a definition for each char

<img width="660" alt="Schermata 2020-03-17 alle 17 47 01" src="https://user-images.githubusercontent.com/163333/76879989-52eecc80-6877-11ea-87a6-40d3e9015427.png">

so If write a new text having new chars with the api `updateDocumentData` like here:
```javascript
anim.renderer.elements[0].updateDocumentData({ t: "HI" }, 0);
```

the renderer will complain of missing chars:

```
lottie.min.js:13 Missing character from exported characters list:  H Regular Impact
lottie.min.js:13 Missing character from exported characters list:  I Regular Impact
```

Here is the stacktrace

```
e.getCharData @ lottie.min.js:13
TextProperty.completeTextData @ lottie.min.js:13
TextProperty.setCurrentData @ lottie.min.js:13
TextProperty.getValue @ lottie.min.js:13
TextProperty.recalculate @ lottie.min.js:13
TextProperty.updateDocumentData @ lottie.min.js:13
ITextElement.updateDocumentData @ lottie.min.js:13
```

How to support missing chars of newly added text?

**Comment by bodymovin** [comment]
If you are exporting text as glyphs, you'll need to export all the text characters you need in advance.
I usually recommend either export text as text and not glyphs where you also need to provide the font.
Or you can include in your export an additional text layer with all the characters you need. If you go with the second option, consider moving that text layer outside the work area so it doesn't get rendered.

**Comment by loretoparisi** [comment]
@bodymovin thank you I think the best option is then to use `TextLayer` rather than glyphs.
