### ISSUE TITLE
No projects appearing in Bodymovin window

### ISSUE THREAD

**Issue by gossamerjohn** [airbnb/lottie-web#2057]
**Tell us about your environment**
After Effects 2020 Mac Book Pro OS 10.15.3
* **Browser and Browser Version:**
Safari 
* **After Effects Version:**
AE2020 17.0.5 Build 16
**What did you do? Please explain the steps you took before you encountered the problem.**
Initiate Bodymovin extension from Window dropdown menu
**What did you expect to happen?**
The bodymovin window is supposed to populate with all the comps in the project
**What actually happened? Please include as much _relevant_ detail as possible.**
No comps are populated. The window shows nothing.
![Screen Shot 2020-03-18 at 2 33 36 PM](https://user-images.githubusercontent.com/62355502/77000384-48d7d700-6926-11ea-9c1f-ea672562bd17.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/69229khh7vihkio/DL_copy.aep?dl=0

**Comment by GiltyMane** [comment]
same problem...

**Comment by bodymovin** [comment]
Hi, how did you install the extension?

**Comment by iamgilty** [comment]
> Hi, how did you install the extension?

For me, with ZXP installer

**Comment by bodymovin** [comment]
There seems to be some problem loading the dependencies.
From the screenshot, version is not appearing correctly on the bottom right corner. 
@iamgilty are you seeing the same as in the screenshot above?

**Comment by iamgilty** [comment]
> There seems to be some problem loading the dependencies.
> From the screenshot, version is not appearing correctly on the bottom right corner.
> @iamgilty are you seeing the same as in the screenshot above?

Exactly the same
<img width="1492" alt="Capture d’écran 2020-03-28 à 16 16 19" src="https://user-images.githubusercontent.com/50251230/77826429-86e7ae80-710f-11ea-909f-a3c9cf1ddebd.png">

**Comment by iamgilty** [comment]
@bodymovin 

Hi there,
Thank you guys for the last updates with 5.6.7 and 5.6.8. But unfortunately, it's still not working :(

**Comment by bodymovin** [comment]
@iamgilty can you try with version 5.6.9?
If it doesn't work, can you try clicking on the window, clicking away from the window and clicking one more time on the window to see if it gets corrected?

**Comment by JWegener** [comment]
Same problem here. Even if i create a brand new project with a single shape, not seeing the option to render it. 

The render option is greyed out (although if i hover it, it turns half-opacity green...?! What does that mean, and why are there NO error messages or tool tips or anything on this product haha, it's infuriating). Any why is my refresh icon rainbow colored, does that mean anything special? When i click it, it seems to spin and then reset back to original orientation.

Thanks in advance for any help

![image](https://user-images.githubusercontent.com/303602/80288565-985fae80-86ed-11ea-895d-b0d2bb5038f9.png)

**Comment by iamgilty** [comment]
> @iamgilty can you try with version 5.6.9?
> If it doesn't work, can you try clicking on the window, clicking away from the window and clicking one more time on the window to see if it gets corrected?

Hi @bodymovin ,
I won't try this because it's actually working pretty good since the last After Effects update from Adobe !
Thanks for reach me out

**Comment by bodymovin** [comment]
@JWegener you just need to resize the bodymovin panel window. Try enlarging it in height and you should see the compositions listed.

**Comment by JWegener** [comment]
@bodymovin Wowza, brutal UX issue. Totally couldn't figure out the tool, hopefully not too many others are running into that problem too. thanks!
