### ISSUE TITLE
is there any lottie json editor that i can use on my project?

### ISSUE THREAD

**Issue by yigitersoy87** [airbnb/lottie-web#2059]
Hello!

I just wonder if there is a way to use lottie editor "https://lottiefiles.com/editor" like this. Basically i would like to import animations and change dynamic text fields, then with the help of puppeteer and ffmpeg, i would like to download animation as mp4. Is this possible?

**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, as a general answer, yes, that should be possible.
I don't know if the editor can help with that, you should ask the lottiefiles team about it.
