### ISSUE TITLE
Implemented Json file  within the app displays a much smaller animation than in After Effects

### ISSUE THREAD

**Issue by aavisar** [airbnb/lottie-web#2060]
AE

**Comment by bodymovin** [comment]
Hi, can you elaborate on the issue?
If this is related to lottie-ios or lottie-android, can you post it on their repos?

**Comment by aavisar** [comment]
@bodymovin Sure
![image](https://user-images.githubusercontent.com/55395814/77846978-59a80880-71c2-11ea-9c14-7ca4ffcdf265.png)

**Comment by bodymovin** [comment]
is this related to the lottie-ios or lottie-android libraries?
