### ISSUE TITLE
Downsampled SVG rendering

### ISSUE THREAD

**Issue by Voxolotl** [airbnb/lottie-web#2061]
I'm using Lottie/Bodymovin to create a loading animation for a personal project of mine, which takes the form of a loop of clothes sliding across a rack.

However, when looking at the results in my browser, I noticed that the rendering quality suddenly drops.
When the objects start entering the frame, they look fine...
![notblurry](https://user-images.githubusercontent.com/42387308/77446196-5f7ea200-6dee-11ea-906b-a3459904fb4b.png)

...but suddenly they turn all blurry, almost as if they were being rendered at a lower resolution:
![blurry](https://user-images.githubusercontent.com/42387308/77446252-758c6280-6dee-11ea-988b-b4eefa520231.png)

I'm using Microsoft Edge 80.0.361.69. I also tried Firefox 74.0 which has the same issue. In fact, it did slightly worse because it's blurry all the time...
I used AE 17.0.5 to create the animation, if that helps.

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by Voxolotl** [comment]
Hi,
Here's my animation file. I hope it can help you find the issue. :)
Also, after further testing I found out I could use the canvas renderer without this issue.

[clothesline.zip](https://github.com/airbnb/lottie-web/files/4399622/clothesline.zip)

**Comment by bodymovin** [comment]
I've tried it on both Edge and Firefox and they look ok.
Can you share a link with your implementation?

**Comment by Voxolotl** [comment]
Well, while setting up a page that wasn't locally hosted, it fixed itself. I guess I did something wrong the first time, haha!

Thank you for trying to help and sorry for wasting your time! ^^'
