### ISSUE TITLE
XML stroke and animation start error.

### ISSUE THREAD

**Issue by chi1080** [airbnb/lottie-web#2063]
**Tell us about your environment**
MacOSMojave 10.14.6

* **Browser and Browser Version:**
chrome but this animation is for an app

* **After Effects Version:**
Ae CC 2020

**What did you do? Please explain the steps you took before you encountered the problem.**
I have this loading animation and the JSON file is fine but when I sent the XML to the developer there are some problems with that XML file.

**What did you expect to happen?**
 the M icon appears first and then some yellow lines spinning (that is loading), when is already loaded a green line appears, making a full circle. and the stroke line cap should be butt cap. In the Ae file the animation is correct.

**What actually happened? Please include as much _relevant_ detail as possible.**
the M icon and the green line appears at first and then the animation begins and the stroke should have butt cap but instead is changed to round cap.

**Please provide a download link to the After Effects file that demonstrates the problem.**
Ae file: https://drive.google.com/open?id=1HSnmBQ32iZrVgxRYrr0VTyaTTSI_yNH7
LOTTIE JASON: https://lottiefiles.com/share/rEVAKd
Video showing the error: https://drive.google.com/open?id=1FVuzadsE-ZcMIWNYIoiDs3fegQetZxji

Thank you in advance!!

**Comment by bodymovin** [comment]
hi, I see the stroke line fine on lottie-web.
If this is related to lottie-ios or lottie-android can you post the issue on their repos?

**Comment by chi1080** [comment]
the problem is when I export the XML the code change from strokeLineCap="butt" to strokeLineCap="round". I don't know if this is about bodymovin or lottie-android.

**Comment by bodymovin** [comment]
What do you mean by the XML?

**Comment by chi1080** [comment]
XML the file you get when you choose: "AVD Exports an xml for Androids Animated Vector Drawable".
![Screen Shot 2020-04-04 at 11 00 44 AM](https://user-images.githubusercontent.com/36519600/78456865-9f058380-7663-11ea-9220-5151250009f9.png)

**Comment by bodymovin** [comment]
hi, the exporter doesn't support stroke types for the avd format unfortunately.
