### ISSUE TITLE
Error: bodymovin is not defined 

### ISSUE THREAD

**Issue by nicolasbanados** [airbnb/lottie-web#2065]
I've made an animation in After Effects and exported to a json file with Bodymovin.

My file includes index.html and news-animation.json

I received the error 'bodymovin is not defined'
How can I fix this?

This is a link of the test project: http://beatmap.net/lottie/

And this is my html file: 

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Este es un test animación</title>
</head>
<body>
    <div id="container">
        <h1>Figma + AE + Bodymovin</h1>
        <p>Esta animación ha sido creada a partir de un SVG, editada en figma, luego exportada a AE con https://figma.aeux.io/
            y animada en After Effects, luego fué exportada como un json usando el plugin bodymovin.
            La ilustración es del sitio https://www.drawkit.io/ </p>
        <div id="lottie"></div>
    </div>
    <script scr="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.6.4/lottie_svg.min.js"></script>
    <script>
        var animation = bodymovin.loadAnimation({
            container: document.getElementById('lottie'),
            renderer: 'svg',
            loop: true,
            autoplay: true,
            path: 'news-animation.json'
        })
    </script>
</body>
</html>

**Comment by bodymovin** [comment]
hi, you have misspelled ` scr`  instead of ` src` on the script tag
