### ISSUE TITLE
Exporting Images sequence Into Json with bodymovin Blocked ?

### ISSUE THREAD

**Issue by elouakaz** [airbnb/lottie-web#2066]
Hello,

I saw same tutorials and been for a week looking in this forum so that i can have an answer but nothing . I created an C4D animation convert it into Image sequence Png when i export it into Json file using Bodymovin the render begins normally but when it came to " export image 0001 " part it stay like this for a very long time whiteout moving ( 9 hours try) .

For seek of this project in setting i marked " Assets =>Enable Compression and Including Json "

Ps when i Unchecked Enable Compression the render is done correctly but i can't see my animation in lottiefiles preview ?? 

Hellp

**Comment by bodymovin** [comment]
Hi, Can you share the .aep and the lottiefiles link?

**Comment by elouakaz** [comment]
> Hi, Can you share the .aep and the lottiefiles link?


[Json-Animat.zip](https://github.com/airbnb/lottie-web/files/4397916/Json-Animat.zip)

**Comment by bodymovin** [comment]
Files are missing, can you share the related project files.
Also, do you have the lottiefiles link?

**Comment by elouakaz** [comment]
Sorry here is the files .
[C4d-Image.sequence dossier.zip](https://github.com/airbnb/lottie-web/files/4398187/C4d-Image.sequence.dossier.zip)


and here is the lottiefile Link : https://lottiefiles.com/preview

**Comment by elouakaz** [comment]
Thank you very much . But i managed to make it work .

Just a version compatibility problem

**Comment by TheFreezingChicken** [comment]
Hi @elouakaz , I have the same problem, but I didn't get how you solved it, can you tell me what you meant by "just a version compatibilty problem" exactly?

**Comment by TheFreezingChicken** [comment]
of course as soon as I leave this message I do a different google search and I find the problem...
well for anyone else finding this first, the problem might be that you have an AE version older than 16 (I have 15.0).
I hope I've saved a few minutes to someone in the future.
