### ISSUE TITLE
mouseleave wait until animation ends

### ISSUE THREAD

**Issue by kaiquerand** [airbnb/lottie-web#2067]
Hello guys, how do I wait until the animation is finished so users can trigger it again?
This is my code:

var loader = document.getElementsByClassName("mail");

function loadBMAnimation(loader) {
  var animation = bodymovin.loadAnimation({
    container: loader,
    renderer: "svg",
    loop: false,
    autoplay: false,
    path: "../img/mail.json"
  });

  loader.addEventListener("mouseenter", function() {
    animation.play();
  });
  
  loader.addEventListener("mouseleave", function() {
    animation.stop();
  });
}

for (var i = 0; i < loader.length; i++) {
  loadBMAnimation(loader[i]);
}

**Comment by bodymovin** [comment]
hi, you probably want to take a look at the `complete` event and keep a flag or a counter in your `loadBMAnimation` method so you know when it has finished.
https://github.com/airbnb/lottie-web#events
