### ISSUE TITLE
lottie is not defined

### ISSUE THREAD

**Issue by Sahu93** [airbnb/lottie-web#2068]
I'm getting an error saying 'lottie is not defined' and when I preview it the screen is blank with only the bg color visible.
I have tried every possible thing and tried every solution on the issues forum but I can't figure out what's wrong with my code.
![main-css](https://user-images.githubusercontent.com/31320964/77855495-710ce300-720e-11ea-8e3e-4704969e9826.jpg)
![index-html](https://user-images.githubusercontent.com/31320964/77855496-723e1000-720e-11ea-8749-59437e1be9da.jpg)
![index-js](https://user-images.githubusercontent.com/31320964/77855497-72d6a680-720e-11ea-83f9-cc71abe748db.jpg)

**Comment by Sahu93** [comment]
Okay so when I copy/pasted the content of the index.js into the source code, it worked. 
What's the point of the index.js if it works just like that?
Sorry, new to web dev.

**Comment by bodymovin** [comment]
The reason why it is on a separate file is to keep things organized. For small things that is not a problem, but for larger developments it's a good idea to have things in small files.
Not sure why you are getting that error, though. If you can share a link with your implementation, I can check it out.

**Comment by Sahu93** [comment]
[lottie-test.zip](https://github.com/airbnb/lottie-web/files/4408910/lottie-test.zip)
Hey, thanks for the response! :)
here's a zip with all the files. 
The animation has started working. Whereas it wasn't working earlier. But the Error is still there.

**Comment by Sahu93** [comment]
Hey! Thanks for the response. I get it and it makes perfect sense 👍 
The animation has started working now. I noticed that I had chosen 'html' as the renderer but earlier it wasn't even working with 'svg'. It is, now. However, the error is still there. 
Is it okay to ignore this error?
Here's the zip with all the files for you to check out. 
[lottie-test.zip](https://github.com/airbnb/lottie-web/files/4408939/lottie-test.zip)
