### ISSUE TITLE
Safari, Firefox bad performance with SVG and transitions

### ISSUE THREAD

**Issue by SourceEngine** [airbnb/lottie-web#2069]
Hello,
first of all just want to mention iam not a webpage expert so my follwing observations might not be 100% right.

### Introduction
Currently iam making a webpage which obviously has lottie involved.
The lottie animation is controlled by triggers in the html doing the following:
`anim.goToAndStop(value);`

To make the aniamtion smooth every moving lottie object has a transition class assigned in AE. In my case its called **.transition_cubic** and does the following:
`.transition_cubic {
    -webkit-transition: all var(--anim_dur_long) cubic-bezier(.25,.8,.25,1) 0s; 
    transition: all var(--anim_dur_long) cubic-bezier(.25,.8,.25,1) 0s; 
}`
### Problem
**_With renderer SVG:_**
https://senvity.com/lottie-renderer-svg
While the animation is smooth on **Chrome** it is choppy on **Firefox** and **Safari**.
My observations (but keep in mind iam not an expert) are that the transitions are not happening on Firefox and Safari due to **transform: matrix(...)** because when i switch to

**_renderer HTML:_**
https://senvity.com/lottie-renderer-html
it works on all browsers because it **transforms** with **matrix3d**. Can this be?

### My wish
Iam looking for a combination between those 2 rendering types. At one time keeping the responsivnes from svg with `preserveAspectRatio: xMidyMid slice` and have the better perfomance what i get from renderer html.
Is this possible or what might be your ideas? Would love to hear them!

If you need any further information do not hesitate to ask!

Best regards and stay healthy!

** using Bodymovin 5.5.9

**Comment by SourceEngine** [comment]
### Dirty Solution
Iam using now renderer html.
To replicate `preserveAspectRatio: xMidyMid slice` from renderer SVG i just center the main div which lottie creates like here: https://stackoverflow.com/questions/17024364/center-image-that-is-bigger-than-the-screen

This seems to work fine over all devices and browser's.
So if there is no cleaner solution feel free to close this case :)

**Comment by bodymovin** [comment]
Hi, unfortunately I can't think of a better solution.
If I'm not mistaken Firefox doesn't translate the "transform" attribute of svg elements, only the transform css style property.
Perhaps what you can do in your case is interpolate the currentframe value of the animation instead of the inner elements with css classes.
