### ISSUE TITLE
.json isn't playing on web

### ISSUE THREAD

**Issue by damianbednarz** [airbnb/lottie-web#2071]
I'm using After Effects 2020. My colleague is preparing new website and we tried to use Bodymovin and lottie export. After rendering I always check "HTML Preview" and it works fine. It works on Lottie player too. 

After coding and inputing .json file animation doesn't play. It happens on Bodymovin and Lottie export.

Here's AAE and .json file: 
[Bodymovin.zip](https://github.com/airbnb/lottie-web/files/4409713/Bodymovin.zip)

Thanks for help!

**Comment by bodymovin** [comment]
Hi, if it works on the preview, can you share a link where it is not working so I can check the implementation?

**Comment by damianbednarz** [comment]
@bodymovin 
![image](https://user-images.githubusercontent.com/49253181/78109537-ae819400-73f9-11ea-9733-ff467acddec9.png)

**Comment by damianbednarz** [comment]
Worked with changing version of Bodymovin from 5.6.7 to 5.6.0
