### ISSUE TITLE
Bodymovin window is not showing anything

### ISSUE THREAD

**Issue by archelleon** [airbnb/lottie-web#2072]
**After Effects Version: 14.1.0.57**

Hi there!

So, i have successfully installed my bodymovin extension in my after effect using the ZXP Installer but the problem is, when the window popped up, It does not showing anything. What do i have to do for this issue?

<img width="1440" alt="Screen Shot 2020-03-31 at 22 58 00" src="https://user-images.githubusercontent.com/49268086/78047883-1eb0fb00-73a3-11ea-8fd1-66501e10321d.png">

<img width="804" alt="Screen Shot 2020-03-31 at 22 53 20" src="https://user-images.githubusercontent.com/49268086/78047357-713de780-73a2-11ea-97c2-195a3c6b34e9.png">

**Comment by bodymovin** [comment]
yes, there has been some issues with older versions of After Effects, can you try upgrading to a newer version of AE or using an older version of Bodymovin?
