### ISSUE TITLE
reliable enterFrame event

### ISSUE THREAD

**Issue by yonatanmn** [airbnb/lottie-web#2073]
I'm creating an animation and I want to have 2 options for endings and choose the right one based on some logic. 
What I'm doing ATM is:
AE file with that has this structure
start - scene1 - endA - endB  

```
animation.addEventListener("enterFrame", function(){
    /// if this is the end of scene1
   /// check some logic
   /// and jump to endA / endB
})
```

This works usually, but I found that `enterFrame` is no reliable - for slower machines, some frames are skipped, and the callback never gets called!

is there a workaround? (I can use any amount of code necessary).

**Comment by bodymovin** [comment]
how are you checking the end of scene 1 right now?
If you are querying the currentFrame, you could do something like `if currentFrame >= end_frame_of_scene_1` (pseudocode)

**Comment by yonatanmn** [comment]
@bodymovin  - this might work in some specific scenarios. 
But in my case, this won't help. For example:
If I want it to fire an event once it reached the end frame, and I allow a replay or jump to point, I won't know if that happened. Or, I might have several scenarios, so  `currentFrame >= end_frame_of_scene_1` will be true if user ended  frame 2, etc..

**Comment by bodymovin** [comment]
not sure I follow. currentFrame is a floating point unless you set subframe rendering to false. So that means that you will never be able to check for an integer, since chances of that to happen are very low.
If I'm not understanding correctly your issue, can you post a simple example with your code? perhaps in codepen?

**Comment by yonatanmn** [comment]
Let's say I have an animation. It begins with some text, and after some time 2 buttons pops up, lottie is paused, and you need to press one of the buttons. Once you pressed one, the animation continues. 

A similar flow happens later in the video again: animation pauses -other buttons displayed - user gives feedback and animation continues.

My solution was: 

```js
    const animation = lottie.loadAnimation(config)
    animation.setSubframe(false) // setting lottie with it, so I won't have floating number, just .
                                // Could have solved that also with `parseInt` inside the callback

    const BTNS_1_FRAME = 100; // frame from AE where I should pause the animation 
    const BTNS_2_FRAME = 200;

    animation.addEventListener("enterFrame", (a) => {
                if (frame === prevFrame) {  return; } // prevent 100.2 100.8 to recall 
               if(BTNS_1_FRAME === a.currentTime){
                            animation.pause(); 
                            showFirstBtns() // this function handles the btns visibility 
                                              // and continues the animation after the button click. 
                }
             if(BTNS_2_FRAME === a.currentTime){
                            animation.pause(); 
                            showSecondBtns() 
               }

    })
```

This works usually when the FPS is good, every frame is called, and frames 100 and 200 triggers the callback. 
On the opposite, when the video is laggy, some frames are skipped, and the `if` statement never validates. 

That's just an example, any solution like - break the animation to different animation won't help in my real use case. 
What's needed is an event similar to  `enterFrame` that is guaranteed to fire at relevant time.

Hopes this explains more.

**Comment by bodymovin** [comment]
since FPS can never be guaranteed because it depends on factors that are not controllable, I suggest that you compare currentTime not with an exact number, for examply by doing
`if(BTNS_1_FRAME < a.currentTime){` and keeping a state of the animation.

**Comment by yonatanmn** [comment]
I understand. It might be super hard (and ugly code) in my real-world scenario. 

Worth implementing some mechanism that would guarantee events on specific times.

**Comment by lbd226** [comment]
Hi, I came across your profile at Toptal, I have an interesting project that I think you'll like , appreciate if you can get back to me - Lbd226@gmail.com  , Lior

**Comment by Yiidiir** [comment]
@yonatanmn I'm using GSAP (Greensock) timeline with timeline.call() and it works great, you can hook it to lottie too :)
