### ISSUE TITLE
bodymovin window opens but does not show interface

### ISSUE THREAD

**Issue by francoisharik** [airbnb/lottie-web#2074]
hello
I just downloaded bodymovin to use with after effects but the widow opens without showing the interface... I only get a blank grey window
I am using after effects 2017
macOS High Sierra
<img width="611" alt="Screen Shot 2020-04-02 at 21 36 36" src="https://user-images.githubusercontent.com/63072585/78294113-0e775800-752a-11ea-8252-a03ecf403a11.png">

**Comment by bodymovin** [comment]
Hi, I've seen people having trouble with bodymovin on AE 2017. Can you update to a newer verison? I think 2019 should work fine.

**Comment by francoisharik** [comment]
thank you for your reply...
I already thought of that and just downloaded AE 2019 and it seems it is working fine now... will try few more things/tweaks and will update
