### ISSUE TITLE
Multiple Animations side by side

### ISSUE THREAD

**Issue by saket13** [airbnb/lottie-web#2075]
<!--
    Whenever I add multiple animations using this code
           <lottie-player
                            src="https://assets7.lottiefiles.com/private_files/lf30_QLsD8M.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;" hover loop  autoplay>
           </lottie-player>
           <lottie-player
                             src="https://assets7.lottiefiles.com/private_files/lf30_oGbdoA.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;" hover loop  autoplay>
            </lottie-player>

I get both the animations one after the another. I want to get them in the same container side by side. I tried a lot but could not do.. How to get this effect??
    
I am using the lottie files directly from the website for HTML

**Comment by saket13** [comment]
Whenever I add files like these :
<lottie-player
                            src="https://assets7.lottiefiles.com/private_files/lf30_QLsD8M.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;" hover loop  autoplay >
                        </lottie-player>
                        <lottie-player
                             src="https://assets7.lottiefiles.com/private_files/lf30_oGbdoA.json"  background="transparent"  speed="1"  style="width: 300px; height: 300px;" hover loop  autoplay >
                        </lottie-player>

The animations are displayed one after the other but I want to display them side by side .I tried but could not achieve the effect . How to do the same??

**Comment by bodymovin** [comment]
Hi, the issue seems to be missing some info. Can you elaborate some more?

**Comment by saket13** [comment]
I was not able to use multiple lottie files animations side by side in the same div when using lottiefiles.com for html (Copy pasting generated source code). I got around the solution by converting the json animations into gif and then used them side by side. But still I wonder how to do them using lottiefiles for web(HTML). ??
