### ISSUE TITLE
preserveAspectRatio does not work

### ISSUE THREAD

**Issue by akos989** [airbnb/lottie-web#2076]
Hi!

I'm creating a project in which I have a full screen animation.

When opened on smaller screens I'd like to cut the middle of the animation image, so only that part would be displayed. I found that I can use preserveAspectRatio: 'xMidYMid slice' for this problem, but it does not work. In Inspect mode I can see that the value is set but there're no changes on the screen.

I attached 2 pictures of the page: one with full screen, one with a smaller size, there I would like to display the animation image only between the red lines but I want it to fill the full height and width of  the display area.

![lottie_full_screen](https://user-images.githubusercontent.com/48367888/78309287-d9c7c880-754a-11ea-8b12-786938e539d3.png)
![lottie_small](https://user-images.githubusercontent.com/48367888/78309289-db918c00-754a-11ea-88ef-b46e4bb91981.jpg)

Here's a link to my Github repo: https://github.com/akos989/lottieAnimation

Any kind of help would be greatly appreciated!

Thanks in advance!!

**Comment by akos989** [comment]
By the red lines I mean that I would like to display the middle area based on the screen size, which in this case would approximately be between the red lines.

**Comment by bodymovin** [comment]
Hi, you probably want to set the height to 100% of the animation container.

**Comment by akos989** [comment]
Thanks a lot for the quick response. It works great!! 😄😄
