### ISSUE TITLE
How to stop only one ae layer from looping?

### ISSUE THREAD

**Issue by oliver0017** [airbnb/lottie-web#2077]
Hi, I'm trying to make an animation which has a looping background pattern, and a front-element which has an animation. I want the front-element to only play once, but the background pattern to keep looping. Is this possible, and if so, how? I've tried to get it to work for hours.

I am using the lottie web player to load my animation, since my code amount is limited on squarespace. I can share the project in **private** with you.

Kind regards,
Oliver

**Comment by bodymovin** [comment]
hi, can you export two separate animations with same dimensions and position one on top of the other one with two divs?
