### ISSUE TITLE
empty panel

### ISSUE THREAD

**Issue by sjhroo** [airbnb/lottie-web#2079]
**Tell us about your environment**
Aftereffects 2020 versions 17.0.5
bodymovin 5.6.7
Mac mojave 10.14.6 (18G3020)

**What did you do? Please explain the steps you took before you encountered the problem.**
<img width="1438" alt="Screenshot 2020-04-06 at 17 38 20" src="https://user-images.githubusercontent.com/58430621/78582888-eb042400-782d-11ea-9194-274a74deb117.png">

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
hi, how did you install it?

**Comment by sjhroo** [comment]
I used the zxp installer

**Comment by bodymovin** [comment]
the one from aescripts?
Also, can you try opening an AE project andreopen the extension?

**Comment by sjhroo** [comment]
yes that one is what i used.. and also restarted the machin and the AE project
