### ISSUE TITLE
.JSON animations only shows in firefox

### ISSUE THREAD

**Issue by StoreA** [airbnb/lottie-web#2080]
Hello, currently building a webpage with wordpress and elementor and i want to make use of Lottie because i absolutely love the possibilities! 
I am using an elementor widget called "Animentor" to implement the .JSON files into the site - and they show up and work as they should - but ONLY in firefox. 
Is there any workaround for making them show in chrome and safari as well? 
** Error message from console ** 
"has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."
Kind regards
Store A

**Comment by bodymovin** [comment]
Hi, can you share a link with the implementation?
