### ISSUE TITLE
The gradation appears in black and white.

### ISSUE THREAD

**Issue by kwak9435** [airbnb/lottie-web#2082]
I'll upload the file and an example of the result. It should appear in color, but it appear black and white.
Result is the JSON file, how can i fix it??

↓ Expect
![image](https://user-images.githubusercontent.com/63277056/78629777-ff4e2c80-78d2-11ea-8349-9497979b2703.png)

↓ Result
![image](https://user-images.githubusercontent.com/63277056/78629726-d7f75f80-78d2-11ea-86d1-ab032151ab24.png)

[1111.ape.zip](https://github.com/airbnb/lottie-web/files/4442030/1111.ape.zip)

**Comment by bodymovin** [comment]
Hi, I see the gradient correctly exported.
Try to save the project before exporting.
Also, what are your OS and AE languages?

**Comment by kwak9435** [comment]
I did what you said, but the same problem still occurs.
My OS is Window 10 and AE language is used in English.

-----Original Message-----
보낸사람: "hernan"<notifications@github.com>
받는사람: "airbnb/lottie-web"<lottie-web@noreply.github.com>
참조: "kwak9435"<kwak9435@naver.com>, "Author"<author@noreply.github.com>
날짜: 2020. 4. 12 오전 12:20:31
제목: Re: [airbnb/lottie-web] The gradation appears in black and white. (#2082)

Hi, I see the gradient correctly exported.
Try to save the project before exporting.
Also, what are your OS and AE languages?

**Comment by bodymovin** [comment]
is your OS in English too?

**Comment by kwak9435** [comment]
Nope, OS used in Korean

-----Original Message-----
보낸사람: "hernan"<notifications@github.com>
받는사람: "airbnb/lottie-web"<lottie-web@noreply.github.com>
참조: "kwak9435"<kwak9435@naver.com>, "Author"<author@noreply.github.com>
날짜: 2020. 4. 12 오전 12:28:33
제목: Re: [airbnb/lottie-web] The gradation appears in black and white. (#2082)

is your OS in English too?

**Comment by bodymovin** [comment]
Yes, it seems that in certain languages, because of the encoding, gradients are not working.
Here apparently they found a solution, but it' s in Chinese. Perhaps Google Translate can help. :)
https://github.com/airbnb/lottie-web/issues/1201

**Comment by kwak9435** [comment]
Yes, I'll check. It's night here, so I'll check it tomorrow morning and reply again if the same problem occurs.
THANK YOU SO MUCH~!!!😄

-----Original Message-----
보낸사람: "hernan"<notifications@github.com>
받는사람: "airbnb/lottie-web"<lottie-web@noreply.github.com>
참조: "kwak9435"<kwak9435@naver.com>, "Author"<author@noreply.github.com>
날짜: 2020. 4. 12 오전 12:32:36
제목: Re: [airbnb/lottie-web] The gradation appears in black and white. (#2082)

Yes, it seems that in certain languages, because of the encoding, gradients are not working.
Here apparently they found a solution, but it' s in Chinese. Perhaps Google Translate can help. :)
#1201

**Comment by d-korolkov** [comment]
The solution is to rename all gradients "Gradients Fill 1" into Gradient Fill_1, Gradient Fill_2,Gradient Fill_3.... AND ALSO what had closed all still remaining problems after that is to rename all sublayerd Groups from Group 1, Group 2, Group 3 where gradients are presented to Group_1, Group_2, Group_3. This closed my problems.
