### ISSUE TITLE
No option to compress assets?

### ISSUE THREAD

**Issue by cur-tis** [airbnb/lottie-web#2083]
Hi @bodymovin, I'm using the latest version (5.6.8) and I was following this tutorial on how to use the plugin, however in my version, there is no option for me compress my assets like in the video below? 

https://www.youtube.com/watch?v=2djbqUOtFgg

Has this feature been removed? I can't seem to find the option to compress, I have a small image sequence and it is 75mb which is way too large for me. I don't have and issue about the quality being lost, my main concern is having a small filesize.

Apologies in advance if this was a dumb question, any assistance would be appreciated. 

Thanks :)

**Comment by bodymovin** [comment]
Hi, you should see it on the Assets drop down in the settings of the composition. Can you share a screenshot of what you are seeing?

**Comment by cur-tis** [comment]
> Hi, you should see it on the Assets drop down in the settings of the composition. Can you share a screenshot of what you are seeing?

Thanks for the speedy reply @bodymovin,

Here's what I can see in the assets dropdown, nothing about compression anywhere. I had the same issue on 5.6.5 too.

I did eventually manage to get it working but only by reverting back to an older build (5.5.10). The compression worked fine with JPEG but didn't do anything with PNG, still ended up with a really large file - is there anything I can do to compress the JSON filesize down whilst still using PNG images, as I would like to keep the transparent alpha layer of my image if possible?

Again, sorry if that was a stupid question, this is all a learning curve for me.

Thanks!

Version 5.6.5
<img width="1440" alt="Screen Shot 2020-04-08 at 01 54 34" src="https://user-images.githubusercontent.com/63312389/78733014-1aa15200-793c-11ea-85e9-8a7347b20d6d.png">

Version 5.5.10
<img width="1440" alt="Screen Shot 2020-04-08 at 02 01 25" src="https://user-images.githubusercontent.com/63312389/78733302-f5611380-793c-11ea-98b6-43f3ef6f93de.png">

**Comment by bodymovin** [comment]
that's strange. Can you try checking and unchecking Copy original assets?

**Comment by cur-tis** [comment]
@bodymovin 

Sure, tried checking and unchecking all the options in the assets menu and it still wouldn't appear, still got the same issue.

As I said it seems to be working fine on 5.5.10 so I can just revert back to that one, although it would be nice to be able to use the new version too. I noticed in the changelog that something to do with compression changed after 5.5.10 in the transition to 5.6.X which is why I decided to try that backlog specifically, and that's when it started working. Hope this helps.

Also in reference to my other question, would you be able to shed some light on it at all?

> I did eventually manage to get it working but only by reverting back to a much older build (5.5.10). The compression worked fine with JPEG but didn't do anything with PNG, still ended up with a really large file - is there anything I can do to compress the JSON filesize down whilst still using PNG images, as I would like to keep the transparent alpha layer of my image if possible?

Thanks a lot for your support!

**Comment by cur-tis** [comment]
Hi @bodymovin, did you have any ideas about either of my questions? Still trying to figure this one out. 

I've been searching the issues page for other people having similar problems but haven't been able to make any progress - any help would be greatly appreciated! 

Also still stuck with my JSON files being ridiculously huge when using PNG too.

**Comment by bodymovin** [comment]
I've found the issue, I'll deploy a new version tonight.
Regarding the compression problem, once this is working you should have more compression options available.

**Comment by cur-tis** [comment]
@bodymovin 

Amazing, thank you so much for your help! I'll keep my eyes peeled for the new version.

**Comment by bodymovin** [comment]
pushed! Should be working now.
