### ISSUE TITLE
Animation very slow in Safari

### ISSUE THREAD

**Issue by Klemen2801** [airbnb/lottie-web#2084]
Hi,

I have a logo animation and it plays very smooth in Chrome and Firefox, but it is very laggy in Safari. I am using AE masks for revealing the logo and I have 4 layers all together. Is there any way maybe to resolve this maybe? AE file is attached.

Thank you in advance!

Klemen
[FH-LogoAnimation-Web.aep.zip](https://github.com/airbnb/lottie-web/files/4449047/FH-LogoAnimation-Web.aep.zip)

**Comment by bodymovin** [comment]
Hi, unfortunately safari doesn't have good performance with mask elements, and the combination of dash arrays with masks is even worse.
