### ISSUE TITLE
text not showing the correct font running in https://lottiefiles.com/

### ISSUE THREAD

**Issue by stevenyeo1234** [airbnb/lottie-web#2085]
hi bodymovin,

i created a webproject in adobe for fira-sans font:
https://use.typekit.net/vsy6mme.css

When i export the font, what do i put in CSS Class and Font Path?
What i have now after searching through the web:
CSS Class : `<link rel=“stylesheet” href=“https://use.typekit.net/vsy6mme.css”>`
Font Path : https://use.typekit.net/vsy6mme.css

I read in https://github.com/airbnb/lottie-web/issues/1564 that the CSS Class needs to include "tk-fira-sans", but i have no idea how to include it.

regards and many thanks.

**Comment by bodymovin** [comment]
Hi, on the export settings you should uncheck the Glyphs option.
On the text form you need to set the `Typekit` checkbox
on Font Path add `https://use.typekit.net/vsy6mme.css`
and on Font Family `"fira-sans",sans-serif;`
you don't need to add anything on the CSS Class input.

**Comment by stevenyeo1234** [comment]
hi bodymovin,

Thanks for the quick reply. I had tested again with your comments and the outcome is still the same.
I had included the following screenshots below. Please let me know where i had done wrongly. Many thanks in advance.

regards,
Steven


This is the image of what i entered during export.
<img width="1028" alt="Screen Shot 2020-04-13 at 12 57 49 PM" src="https://user-images.githubusercontent.com/63344698/79093607-5c405b80-7d87-11ea-82f3-128b11137f25.png">

This is the image of mp4 from aftereffect (on the left) and in lotties (on the right).
![Screenshot 2020-04-13 at 1 07 53 PM](https://user-images.githubusercontent.com/63344698/79093757-dcff5780-7d87-11ea-9c7a-5de20cf6ac19.png)

Attached is the json file. I added in a .txt extension behind to upload here.
[data.json.txt](https://github.com/airbnb/lottie-web/files/4468095/data.json.txt)

**Comment by bodymovin** [comment]
can you share a link with your implementation that I can check?

**Comment by stevenyeo1234** [comment]
hi, i am not sure what implementation u r refering to. Sorry, still nub at this. i get the data.json and throw into https://lottiefiles.com/

I attached the zipped aep file from my designer. 

[F&B#5_Cater_Catrina'sCatering1.aep.zip](https://github.com/airbnb/lottie-web/files/4472537/F.B.5_Cater_Catrina.sCatering1.aep.zip)

**Comment by bodymovin** [comment]
Can you share a lottiefiles link where you uploaded the json?

**Comment by stevenyeo1234** [comment]
https://lottiefiles.com/share/mua1KA

**Comment by stevenyeo1234** [comment]
hi bodymovin, have u check the lottiesfiles link? Any idea what i did incorrectly?

**Comment by bodymovin** [comment]
can you try removing the semicolon on the Font Family field?
From my tests that should fix it.

**Comment by stevenyeo1234** [comment]
hi bodymovin,

Tested and its resolved. Thanks a million.
