### ISSUE TITLE
IOS-web animation stuck on running

### ISSUE THREAD

**Issue by sandeshsyadav** [airbnb/lottie-web#2086]
am using lottie-web in angular 8 application. I have created a custom angular component which loads the lottie animation. The animation loads and works fine in chrome and safari and andriod. But when I try to load it in IOS web (using chrome emulator in developers tool) the animation is stuck on the first frame.

Following is the code:
```
lottie.default.setLocationHref(location.href);
const animation = lottie.default.loadAnimation({
  container: nativeEle, // the dom element that will contain the animation
  renderer: 'svg',
  loop: true,
  autoplay: false,
  path: '/assets/img/lottie/ball.json', // the path to the animation json
  rendererSettings: {
    progressiveLoad: false,
    viewBoxOnly: true //  make sure paths were loaded after DOMLoaded event
  }
});
animation.setSubframe(false);
animation.play();
```
Animation are working fine on safari, andriod, chrome.
I tried using different lottie files, but I am having the same issue

**Comment by jhndflpp** [comment]
i am also seeing this issue for any ios emulated devices in chrome within a similar application, though the [ng-lottie demo](https://chenqingspring.github.io/ng-lottie/demo/) seems to work fine.  in inspecting the element, after the first frame of the animation is displayed, all the `<g transform...` animation elements get the attribute of `style="display: none;"`.

**Comment by bodymovin** [comment]
Hi, you should probably wait for the animation to be loaded before playing it.
try something like:
```js
animation.addEventListener('DOMLoaded', () => {
    animation.setSubframe(false);
    animation.play();
})

```

**Comment by sandeshsyadav** [comment]
Thank you for your replay. I tried your suggestion but it yields the same result. 
Attached are the screenshot for reference
![local](https://user-images.githubusercontent.com/48367547/79079162-76bcfb00-7cdb-11ea-95e1-1630642b225c.png)
![server](https://user-images.githubusercontent.com/48367547/79079163-76bcfb00-7cdb-11ea-8cdc-68a4cbfe7d29.png)

**Comment by bodymovin** [comment]
Can you share a link with a simple example?
