### ISSUE TITLE
bodymovin is empty

### ISSUE THREAD

**Issue by 4ly-a** [airbnb/lottie-web#2088]
When I open bodymovin, no button or interface appears, just an empty tab, I am using after effects cc 2015 and installed bodymovin through the lottie-web repository, I used ZXP.
Can you help me pls;-;

![error bodymovin](https://user-images.githubusercontent.com/26152669/78846801-59d6ae00-79e3-11ea-98e2-7827ab4a6b74.png)

**Comment by cur-tis** [comment]
I had this same issue. It's a problem with older versions of after effects. Updating should fix it, as far as I am aware 2019 and 2020 should work fine, and 2017 doesn't. I'm not sure about 2018.

**Comment by 4ly-a** [comment]
@cur-tis Have Is there any other way to create animations or export them in json, my computer does not support after effects in current versions ;-;

**Comment by bodymovin** [comment]
Hi, you can try using an older release.
Perhaps version 5.5.10 will work.
https://github.com/airbnb/lottie-web/releases
Download the zip, go to build/extension and try installing that version.

**Comment by 4ly-a** [comment]
It worked perfectly, thanks for the help <3
