### ISSUE TITLE
dotLottie PreComp Issue

### ISSUE THREAD

**Issue by alihs** [airbnb/lottie-web#2089]
So I understand that dotLottie is an extension of Lottie Web only coupled with js-zip and js-lit for compression and a few minutes extra tweaks to make it work compressed.

Now i do understand that lottie works fine with pre-comps (atleast the animation i used showed fine on lottiefiles which means the animation is working just finne.) though when i use the same animation on for dotLottie, i get the following issue.

![image](https://user-images.githubusercontent.com/7601181/78866827-8b8a5c00-7a59-11ea-8c63-7b830451baee.png)

Attached is the ZIP with the JSON/dotLottie/AE files
[Archive.zip](https://github.com/airbnb/lottie-web/files/4454562/Archive.zip)

Any help would be appreciated as i do believe that dotLottie would make a difference in the World. Already has made my world better with super fast loading animations.

My workaround is removing the Pre-Comps but that just increases the time overall.

**Tell us about your environment**
Tried Windows/Mac

* **Browser and Browser Version:**
Chrome Latest

* **After Effects Version:**
AE 2020

**Comment by bodymovin** [comment]
Hi, can you contact the LottieFiles team? they are the maintainers of that player.

**Comment by alihs** [comment]
Sure, will do.
Thanks
