### ISSUE TITLE
Image and vector layers are missing from exported json.

### ISSUE THREAD

**Issue by elenniko** [airbnb/lottie-web#2090]
Here's the AE file and the exported json

https://www.dropbox.com/s/z6fhx7pttyt3ywm/coupon_select.zip?dl=0

**Comment by bodymovin** [comment]
Hi, merge paths are not supported by the player, and on your `phone` layer, each shape group is composed by a path a group and a merge path.
If you remove manually both the merge math and the group layer it should probably work

**Comment by elenniko** [comment]
Thank you! Gonna give it a try!
