### ISSUE TITLE
Failed to read the 'responseText' property from 'XMLHttpRequest' (bodymovin)

### ISSUE THREAD

**Issue by saadpasta** [airbnb/lottie-web#2091]
Hello, i'm using bodymovin to load an animation but 
I found an error and here is the details. Can you give me a guidance?

Here is the error

> Uncaught DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'json').
>     at formatResponse (https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.6.8/lottie.js:4356:17)
>     at XMLHttpRequest.xhr.onreadystatechange (https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.6.8/lottie.js:4374:26)

Here is the code section

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.6.8/lottie.js"></script>

     var animation = bodymovin.loadAnimation({
              container: document.getElementById('lottie-animation'), // Required
              path: './cycle.json', // Required
              renderer: 'svg', // Required
              loop: true, // Optional
              autoplay: true, // Optional
      })


div id="lottie-animation"></div>
```

**Comment by saadpasta** [comment]
@bodymovin  please have a look

**Comment by bodymovin** [comment]
Hi, can you share a link where I can see the error?

**Comment by saadpasta** [comment]
@bodymovin sorry I don't have it on any hosting right I am attaching a screenshot where you can have a look. 
<img width="1432" alt="Screen Shot 2020-04-09 at 7 35 13 PM" src="https://user-images.githubusercontent.com/23307811/78906871-5867bd00-7a99-11ea-86e5-5a66f5c003ba.png">

**Comment by bodymovin** [comment]
it's difficult to assess only with that. Can you make sure the json is in the right location?

**Comment by saadpasta** [comment]
@bodymovin It's was the issue with path of Json Thanks
