### ISSUE TITLE
Animation starts as display none for a few ms when using playSegments()

### ISSUE THREAD

**Issue by rotem227** [airbnb/lottie-web#2092]
Hi,

When I use the playSegments() function I get a weird behavior, the animation starts as a 'display none' and only after a few milliseconds it changes to 'display block'. 
I use the playSegments in the following way: lottie.playSegments([0, 315], true).

Seems that it happens only in some animation (maybe only in 5.6.2 version but not sure).
+
When I use the play() function instead of playSegments(), the same animation is working properly.

You can see the weird behavior in the following CodePen, click on the animation to activate it:
https://codepen.io/rotem227/pen/qBOBPrz

Please advice,
Thanks in advance.

**Comment by bodymovin** [comment]
Hi, the original segment of that animation is [60, 141], so you probably want to use that as the playing values

**Comment by rotem227** [comment]
Thank you, but is there a way of somehow getting this info from the animation instance itself? a data of the 'active' frames of each animation? and then use this data as part of the playSegments()?
example for my question:
lottie.playSegments( lottie.firstActiveFrame, lottie.lastActiveFrame );
