### ISSUE TITLE
 重复运行动画会造成卡顿  Running the animation repeatedly can cause a jam

### ISSUE THREAD

**Issue by webWangjin** [airbnb/lottie-web#2093]
After the animation is run, it is destroyed, but the memory is not released. Running the animation repeatedly will cause a jam

**Comment by bodymovin** [comment]
Hi, can you share an example of you code?

**Comment by Gaia-Ultraman** [comment]
Single page application of VUE。
`<template>
      <div
        style="height: 550px; width: 550px"
        id="developing_lottie_container"
      ></div>
      <div class="tips">功能开发中...敬请期待！({{ second }}秒后返回)</div>
<script>

import jsonData from "@/assets/lottie/medical-shield.json";
import lottie from "lottie-web";
export default {
  data() {
    return {
      second: 5,
    };
  },
  mounted() {
    let that=this;
    let anim = lottie.loadAnimation({
      container: document.getElementById("developing_lottie_container"), // the dom element that will contain the animation
      renderer: "svg",
      loop: true,
      autoplay: true,
      animationData: jsonData, // the path to the animation json
    });
    let timer = setInterval(() => {
      --that.second;
      if (that.second == 0) {
        anim.stop();
        anim.destroy();
        clearInterval(timer);
      }
    }, 1000);
    anim = null;
  },
};
</script>`

**Comment by Gaia-Ultraman** [comment]
我也遇到了这个问题，但我解决了。
我的情况是VUE的单页面应用,lottie动画页面在我一个子路由下，我多次与动画页面切换路由就会出现卡顿。页面destroy的时候，调用了lottie的stop，destroy的。
看着JS内存堆栈，是lottie.js这个文件里面使太多闭包，导致很多对象和变量没有回收，应该是内存泄漏了。
解决办法就是 利用iframe嵌入一个html，这个html放专门用来放动画。
