### ISSUE TITLE
How to clear Bodymovin setting cache?

### ISSUE THREAD

**Issue by xuhong** [airbnb/lottie-web#2094]
**Tell us about your environment**
Mac
* **Bodymovin Version:**
5.6.8
* **After Effects Version:**
17.0.5

**What did you do? Please explain the steps you took before you encountered the problem.**
I delete the default font-family and font-style value in setting pane, and it will always be empty even I rerun the plugin.

**What did you expect to happen?**
I wan't the default value back after I rerun the plugin or reopen the file, or provide a way to clear the cache.

**Comment by bodymovin** [comment]
On chrome you can go to
chrome://inspect
on configure add localhost:8092
and then inspect the window

**Comment by xuhong** [comment]
Thank you, It works!

**Comment by msongz** [comment]
hi~once I defined the output path for some comps, I can't remove the paths from bodymovin
just can rename it
also the defined output path comps can not benefit from the project setting which auto rename the json file
any suggestion?
