### ISSUE TITLE
This solution for freezing on the last frame doesn't work for me

### ISSUE THREAD

**Issue by Sahu93** [airbnb/lottie-web#2096]
var container = document.getElementById("logo"),
            anim = lottie.loadAnimation({
            container: container,
            renderer: "svg",
            loop: false,
            autoplay: true,
            path: "static/logo.08.json"
    });

    anim.addEventListener("enterFrame", function (animation) {
         if (animation.currentTime > (anim.totalFrames - 1)) {
            anim.pause();
         }
    });

Here's my version:

var animation = lottie.loadAnimation({
container: document.getElementById('logo-anim'),
path: 'logo.json',
renderer: 'svg',
autoplay: true,
loop: false,
});

animation.addEventListener('enterFrame', function (animation) {
     if (animation.currentTime > (anim.totalFrames - 1)) {
        anim.pause();
     }
});

**Comment by bodymovin** [comment]
Hi, what is it exactly what you are trying to achieve?
By default, it should stop automatically on the last frame if loop is set to false.

**Comment by Sahu93** [comment]
Hey so my logo animation is a png sequence of 300 frames or smth that I made using bodymovin.
The animation works fine but it disappears after it's finished. I read your comment on the other post about the update that kills the need for this workaround but it doesn't work for me, even with this bit of code. Could there be something wrong with the animation? I put the sequence in after effects and used bodymovin on it cuz some of the effects weren't being translated to the json as is. As far as I can see the last image in the sequence is not empty so I thought maybe it's an issue with the lottie player but I guess I'm wrong

**Comment by Sahu93** [comment]
Okay so I went into after effects and removed 1 frame and now it's working fine. I guess the previous bodymovin render had an extra frames that were blank. This latest render had only 1 frame blank. Anyway it works now so I'm gonna close this.
