### ISSUE TITLE
Can't render my animation gradient background properly

### ISSUE THREAD

**Issue by tsz1412** [airbnb/lottie-web#2097]
Hey, we are running into some problems with the Bodymovin Plugin.
Here is the description as requested in the issues ticket template:

* **Tell us about your environment**
AE CC 2018 and after that uploading the JSON file to a Wordpress website and rendering the JSON file later to SVG using JS. The Bug can be also seen in the HTML Demo file.
* **Browser and Browser Version:**
All versions including Chrome, Firefox, and Explorer
* **After Effects Version:**
cc 2018 and also Adobe Creative Cloud Version
* **What did you do?**
I rendered the composition using BodyMovin
* **What did you expect to happen?**
The render of the JSON file would look like the composition in AE
* **What actually happened? Please include as much _relevant_ detail as possible.**
There is a problem with the coloring. Gradient layer to be exact
* **Download Link for the Project(Including screenshots of what suppose to be and what happens)**
https://drive.google.com/drive/folders/1SLQ1UriDk5x8Sq7W7rsJqNQPJLmOEJY2?usp=sharing

**Comment by bodymovin** [comment]
Hi, the gradient ramp effect is not supported unfortunately. Very few raster effects are supported by the extension.
The supported gradients are the shape layer gradient properties.
