### ISSUE TITLE
Any way to optimize  the size of Lottie JSON?

### ISSUE THREAD

**Issue by abhi06991** [airbnb/lottie-web#2100]
I needed a 35 sec loader. So, at the end, when the designer gave me the animation JSON file, it came around 1.2Mb file size. It takes around 4-5 seconds to load and by the time it loads, I have lost those 4 seconds of animation and then the animation begins from the 4th or 5th second.

I guess the JSON file is already minimized. So, even the online JSON minify tools are just giving me the same output. I searched a lot, but I could not find a suitable solution. Is there any way I could optimize this ?

**Comment by bodymovin** [comment]
hi, can you share the .aep or the json file? 1.2Mb seems pretty large.
But if you serve the file gzipped, it should reduce the filesize significantly.

**Comment by abhi06991** [comment]
Hi, Can I mail you the json, as I am not allowed to share it due to some privacy issues, as we have not yet launched.

**Comment by bodymovin** [comment]
sure, my email is in the main page

**Comment by bodymovin** [comment]
hi, I checked the animation and it's pretty long, it makes sense the 1.2Mb size.
But as I said, if you serve it gzipped, it's only 120kb.

**Comment by abhi06991** [comment]
Hi, 
Yes, this works. Gzip has greatly reduced the size of the response. But still, the initial time to render the animation takes at least 3 seconds of time. Any way to make it render instantly ?
 I tried `progressiveLoad: true`  in the `renderSettings`. This works well. Animation renders instantly, but it isn't smooth. As the animation progresses, there are some places where it stucks while it loads the needed elements.

Anyway, I can make the animation render instantly and also make it run smoothly ?

**Comment by bodymovin** [comment]
have you tried the canvas renderer?

**Comment by abhi06991** [comment]
Yeah, I tried that, but that setting completely messes up my animation.  :(

**Comment by bodymovin** [comment]
I can't think of another solution unfortunately

**Comment by abhi06991** [comment]
Is it possible to break up this entire animation file into small json files and load them up one by one? will it work?

**Comment by bodymovin** [comment]
yes, as long as you make sure you pause all the pieces that are not animating, it should work better

**Comment by ilyassesalama** [comment]
It seems like LottieFiles released their own Lotties optimizer.
https://lottiefiles.com/features/optimize-lottie

**Comment by kde-neon** [comment]
It was good, Now it added some texts that we don't need, It was optmize and small size json file before  update. After update all become large file and new option created "**OPTMIZE**" **it paid.**

**Comment by kde-neon** [comment]
- [ ] Codign

**Comment by PsHye** [comment]
try to minimize your .json thats improve a lot the size :)

**Comment by artrayd** [comment]
maybe we can use older bodymovin plugin

> It was good, Now it added some texts that we don't need, It was optmize and small size json file before update. After update all become large file and new option created "**OPTMIZE**" **it paid.**

Maybe we can find older version of bodymovin plugin?

**Comment by Maximillion195** [comment]
I used [Lottiemizer](https://lottiemizer.com/) to optimize my lottie files

**Comment by mtriu** [comment]
Is there a way to somehow compress a 40 mb json? [https://github.com/airbnb/lottie-web/issues/3118](url)
