### ISSUE TITLE
Bodymovin export error

### ISSUE THREAD

**Issue by wmonteiro26** [airbnb/lottie-web#2104]
I did a character animation in after effects using duik, it works normally in the preview, but when I render in bodymovin layers are all out of place. I made 03 animations, only 01 worked well and the other two are with the same error. Below is an image of how they are getting when exporting. I really don't know what is wrong.

This is a screenshot of the character

![2020-04-12 00_30_41-Adobe After Effects - D__DOCUMENTOS_Jobs_Juris_Animação_Footer Folder_TESTAR ESS](https://user-images.githubusercontent.com/63527104/79075086-deb51680-7cc6-11ea-8f58-b25353ff4b58.png)

and this is how it looks like before I export

![2020-04-12 00_31_14-footer_ html](https://user-images.githubusercontent.com/63527104/79075089-e4126100-7cc6-11ea-9f82-4e7851c58b31.png)

* **After Effects Version 2019

I used these export settings

![2020-04-12 14_23_39-](https://user-images.githubusercontent.com/63527104/79075450-597f3100-7cc9-11ea-8e1b-e21d79d9af49.png)

After effects link
https://drive.google.com/drive/folders/1725l6LuM0L055AmsbXyOVqWgY9DTVis4?usp=sharing

Thank you

**Comment by bodymovin** [comment]
H, you need to include guided layers, and maybe hidden layers too, as part of the export since Duik relies on those to perform the animations.

**Comment by wmonteiro26** [comment]
Do you know how I can do this?

**Comment by bodymovin** [comment]
on the settings menu (the screenshot you shared) there are two options: Hidden and Guides, if you switch them on, you should be good to go.

**Comment by wmonteiro26** [comment]
Thank yooooou so much! I got it :D
