### ISSUE TITLE
Error Loading the Animation on Chrome

### ISSUE THREAD

**Issue by LukeThomas00** [airbnb/lottie-web#2105]
I tried creating an animation with after affects and implement it into an html file locally. My animation works fine. I rendered, and got the player. I implemented the the lottie.js and personal .js file, as well as the data.json file which are all located in the same directory. When I inspect on Chrome it shows the two errors:

Access to XMLHttpRequest at 'file:///Users/lukethomas/Desktop/Websites/Artificial%20Anomali/data.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

&

data.json:1 Failed to load resource: net::ERR_FAILED

When i try searching these errors i was unable to find anything. Any help is greatly appreciated.

**Comment by bodymovin** [comment]
hi, for security reasons Chrome doesn't allow loading json files from your file system. you need to load them via a local web server, or uploade them somewhere on the web.

**Comment by bodymovin** [comment]
hi, for security reasons Chrome doesn't allow loading json files from your file system. you need to load them via a local web server, or uploade them somewhere on the web.

**Comment by LukeThomas00** [comment]
Thanks for that! also, there any quick way to disable the animation autoplaying? Im wanting it to start on a mouse click, however it autoplays even when i set the value to false or even remove it.

**Comment by bodymovin** [comment]
autoplay should work for that. If you have a link with your implementation, I can take a look.

**Comment by LukeThomas00** [comment]
i was able to get the autoplay to stop. Is there an easy way to set up the start of the animation from a mouse click?

**Comment by bodymovin** [comment]
if you mean to play the animation, you can add a click event listener to the element you want to listen and call `animation.play()` in that function.

**Comment by developervineetjoshi** [comment]
just launch it on localhost and enjoy
