### ISSUE TITLE
gradient

### ISSUE THREAD

**Issue by workfromhome2020** [airbnb/lottie-web#2106]
**Tell us about your environment**
MacOS Mojave 10.14.6 English

* **After Effects Version:**
CC17.0.4 English

**What did you do? Please explain the steps you took before you encountered the problem.**
1.Made shapes using the basic gradient tool on the top menu. used path tool to reveal the shape. gradient shown as b&w
2.tried to precomp the shape, and used mask to reveal, one shape has the correct color, while the other is wrong.
<img width="199" alt="1" src="https://user-images.githubusercontent.com/63624247/79178691-b27ac200-7dba-11ea-8a1e-14353e5e1c68.png">
<img width="203" alt="2" src="https://user-images.githubusercontent.com/63624247/79178702-bc042a00-7dba-11ea-98a9-b18c2cd34259.png">

**What did you expect to happen?**
gradient shown as in ae (blue gradient should be the right color)

**What actually happened? Please include as much _relevant_ detail as possible.**
gradient either became red or b&w

**Please provide a download link to the After Effects file that demonstrates the problem.**
[3.Question.aep.zip](https://github.com/airbnb/lottie-web/files/4472736/3.Question.aep.zip)

**Comment by bodymovin** [comment]
hi, can you rename your layers in side and side2 to "l2" and "l3" for example?
As long as there is a letter before the number it should work.
Also, remember so save the AE project before exporting.

**Comment by workfromhome2020** [comment]
it works! thanks a bunch!! thanks for developing this magical plugin~~
