### ISSUE TITLE
Inconsistent effect in svg renderer and canvas renderer

### ISSUE THREAD

**Issue by YuriTu** [airbnb/lottie-web#2108]
**Tell us about your environment**
AE CC 2018 mac10.14.6
* **Browser and Browser Version:**
chrome 80
* **After Effects Version:**
2018
**What did you do? Please explain the steps you took before you encountered the problem.**
I rendered the composition using BodyMovin
**What did you expect to happen?**
The render of the JSON file would look like the composition in AE
**What actually happened? Please include as much _relevant_ detail as possible.**
There is a problem with the coloring. text layer not render.
There is different effect in svg and canvas renderer
**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/open?id=1n0IJuzm9q2-nuRJszY8GOdYXmRUWEA9j

**Comment by bodymovin** [comment]
hi, masks are not supported by the canvas renderer

**Comment by YuriTu** [comment]
@bodymovin thanks！
