### ISSUE TITLE
BodyMovin not previewing shatter animation

### ISSUE THREAD

**Issue by tr8b5** [airbnb/lottie-web#2109]
I installed and reinstalled Bodymovin and adobe flash twice. The same thing happened with each version.

I am able to preview lottie animations but for some reason I am unable to view my own custom shatter animation which I really need for my iphone game. 

Please help. Zip attached.
[Shatter LongBar.aep.zip](https://github.com/airbnb/lottie-web/files/4482078/Shatter.LongBar.aep.zip)

**Comment by bodymovin** [comment]
The shatter effect is not supported bu the players unfortunately.
There are very few raster effects that are supported.
