### ISSUE TITLE
Uncaught ReferenceError: verifyGradeperc is not defined  at HTMLInputElement.onblur 

### ISSUE THREAD

**Issue by Ankush1828** [airbnb/lottie-web#2110]
Can anyone assist on this issue,

![image](https://user-images.githubusercontent.com/40284221/79490851-23301180-803b-11ea-92e7-17b072d019ce.png)

Thank you

**Comment by bodymovin** [comment]
hi, that doesn't seem related to the lottie-web library

**Comment by Ankush1828** [comment]
Yes, it's not related to lottie-web library.
This verfyGradeoerc is javascript function which is used on oaf page.

**Comment by bodymovin** [comment]
is there any reason why you are posting it in this github project?

**Comment by Ankush1828** [comment]
i'm not aware of this type of error. I thought someone aware on the same will help here.
