### ISSUE TITLE
Multiple animated masks all play at once in exported file

### ISSUE THREAD

**Issue by ecruhling** [airbnb/lottie-web#2112]
**Tell us about your environment**
OS X Catalina 10.15.4

* **Browser and Browser Version:**
Google Chrome 80

* **After Effects Version:**
17.0.6
Bodymovin 5.6.5
lottie-web 5.6.8

**What did you do? Please explain the steps you took before you encountered the problem.**
AE file is outlined text shapes with multiple masks that animate over the letters in sequence

**What did you expect to happen?**
The bodymovin export should animate the masks in sequence as in the original AE file

**What actually happened? Please include as much _relevant_ detail as possible.**
The bodymovin export works well, except the animated masks all play at once instead of in a sequence

**Please provide a download link to the After Effects file that demonstrates the problem.**
[1b_Whats_your_Signature_lg.aep.zip](https://github.com/airbnb/lottie-web/files/4489640/1b_Whats_your_Signature_lg.aep.zip)

[demo.zip](https://github.com/airbnb/lottie-web/files/4489641/demo.zip)

Is there something that needs to be done in the AE file to make sure the animations play in sequence? I'm not an AE user, this was created by another person, but I can relay the information

**Comment by henriqrossatto** [comment]
Hi @ecruhling.

I checked your file and I suggest you instead use mask and stroke effect to animate it, create the mask as a layers paths and use trim paths to animate each line.

As I know, lottie don't read so well gradient, fill, stroke as effects. You should work with the proprieties inside the layers.

**Comment by ecruhling** [comment]
hi thanks

yes, the animator was using effects for the animation. once she changed each mask to its own layer and set it up on the timeline, it worked perfectly.

thank you
