### ISSUE TITLE
Color Render Problem

### ISSUE THREAD

**Issue by yodaimon** [airbnb/lottie-web#2113]
Hi, 
I´m having issues exporting colors correctly into from my AE project.
All colors are incorrect...
This is my project:
[logo.zip](https://github.com/airbnb/lottie-web/files/4492991/logo.zip)

As a newbie in AE i´m sure that is easy to solve the problem, but i don´t know how to do it.
I hope you can help me.
Thanks in advance

**Comment by henriqrossatto** [comment]
Hi @yodaimon 

Your files has some problems that will be easy to fix. 

About the color, use the native layer fill for it. You're using a a effect control to do it and creating a lot of expression that can create error inside the exportation. I understand that this make simple change the color on project but I'm pretty sure that aren't supported by lottie.

Samething for BG solid layer. Create it already in the yellow color instead use a fill effect for it.

**Comment by yodaimon** [comment]
Thank you so much for your solution.
I will try!
THX!
