### ISSUE TITLE
How to reduce the size of JSON files?(for dummies)

### ISSUE THREAD

**Issue by EsztiP** [airbnb/lottie-web#2115]
Hi! Please can someone write me step by step, how to reduce the size of my lottie animations? because with 800 kb it's not working :/ I found in other issues that I should gzip it but I don't know anything about coding :/ I would like to use my animations on a webflow site.
Thank you in advance for your help!

**Comment by henriqrossatto** [comment]
Could you send you AE file to check what have inside the animation making it heavy? I'm don't know about code but I believe this gzip is more about the player file and not the data.json file. Someone can correct me if I'm wrong.

**Comment by bodymovin** [comment]
You could gzip both the player and the data.json. Usually jsons get reduced to a tenth of their original size when serving them gzipped.
In order to use them gzipped on the web, your web server needs to support serving files gzipped, which is usually the case.
