### ISSUE TITLE
Complete function does not seem to be firing

### ISSUE THREAD

**Issue by ColdstarJoey** [airbnb/lottie-web#2116]
Hey everyone i have made an animation in ae and exported the json but when the animation is finished it says on the screen instead it should be firing the complete function in my script file and destroying it. can anybody tell me why this is happening, the original AE Composition was only 4 seconds

    `var animparams = {
            container: document.getElementById('lottie'),
            renderer: 'svg',
            loop: false,
            autoplay: true,
            path: 'wp-content/themes/foursquaresolutions/js/loader.json',
            rendererSettings: {
                preserveAspectRatio: 'xMinYMin slice',
                clearCanvas: false,
                progressiveLoad: false,
                hideOnTransparent: true,
                className: 'some-css-class-name',
                id: 'some-id',
            }
        };

        var anim;

        anim = lottie.loadAnimation(animparams);

        anim.onComplete = function(){
            anim.destory();
          }`

the web url is http://77.68.78.245/plesk-site-preview/foursquareuk.com/77.68.78.245/

**Comment by bodymovin** [comment]
Hi, have you tried logging to see if the event is fired or something else is going on?
