### ISSUE TITLE
Play animation by percentage or AEP Markers

### ISSUE THREAD

**Issue by shirley737** [airbnb/lottie-web#2118]
Hello @bodymovin , I want to explore and see if there are ways to play animations other than setting frames. Specifically, I am curious if the current Lottie version has features that allow people to play a segment between two markers in AE file, or by setting percentage (e.g: play from 10% to 90%) 

Thank you so much for the clarification!

**Comment by bodymovin** [comment]
hi, you can use playSegments to specify the range of frames you want to play.
https://github.com/airbnb/lottie-web#playsegmentssegments-forceflag
markers are not supported yet, and for percentages, you could roll your own ticker if needed.
