### ISSUE TITLE
[Question] Ability to use an existing SVG element

### ISSUE THREAD

**Issue by kabukki** [airbnb/lottie-web#2120]
Hi, I was wondering if it was possible to use an existing SVG element instead of requiring a container element (in the manner of canvases by passing an existing context, as seen here: https://github.com/airbnb/lottie-web/issues/435). This is mainly for easier and more consistent styling, since wrapping the svg in a `div` element implies that different css to be applied. Specifically in my case I need to upgrade static `svg`s into Lottie svg animations without needing to refactor every CSS style because of the wrapping `div`.

Thanks !

**Comment by bodymovin** [comment]
Hi, not sure if it works on your case, but svgs are valid elements inside other svgs, so you can pass an svg or a g element as the container
