### ISSUE TITLE
thisProperty is not recognized

### ISSUE THREAD

**Issue by mbalex99** [airbnb/lottie-web#2122]
**Tell us about your environment**

Windows 10
Body Movin 5.6.9

* **Browser and Browser Version:**

Version 81.0.4044.113 (Official Build) (64-bit)

* **After Effects Version:**

After Effects Creative Cloud 17.0.6 (35)

**What did you do? Please explain the steps you took before you encountered the problem.**

1. Draw a path with a pen
2. Add dashes to the path
3. Add an offset express with `thisProperty + 60 * time`

**What did you expect to happen?**

A perpetual dashed moving line

**What actually happened? Please include as much _relevant_ detail as possible.**

After rendering with Bodymovin, no animation happens

**Please provide a download link to the After Effects file that demonstrates the problem.**

## Solution 

* `thisProperty` doesn't work with Bodymovin, so this code won't work `thisProperty + 60 * time`
* This **works** `content("Shape** 1").content("Stroke 1").dash.offset + time * 60`

**Comment by bodymovin** [comment]
Hi, you can try `thisProperty.value`, which should work correctly.
