### ISSUE TITLE
Can't export

### ISSUE THREAD

**Issue by rutraq** [airbnb/lottie-web#2123]
Hello. I have a problem. When I want to export to json file I have a problem with one picture. It didn't export, I'm waiting about 5 minutes and nothing happens
![Безымянный](https://user-images.githubusercontent.com/25290984/80191785-e48fed80-861e-11ea-9bde-41a8437dda34.png)

**Comment by d-korolkov** [comment]
I'm not an admin but it seems you trying to export psd with effects. Try to convert original psd files into png, set in settings->assets->Include in json. This might be helpful. Also better not to use Cyrillic in the project and use true vector shapes inside lottie projects but not raster images.

**Comment by rutraq** [comment]
But I'm already made my animation. It will be very hard to make png and do it one more time

**Comment by rutraq** [comment]
> I'm not an admin but it seems you trying to export psd with effects. Try to convert original psd files into png, set in settings->assets->Include in json. This might be helpful. Also better not to use Cyrillic in the project and use true vector shapes inside lottie projects but not raster images.

I made png file instead of PSD, but it doesn't work
![image](https://user-images.githubusercontent.com/25290984/80198695-232aa580-8629-11ea-8ad0-7aeca5c02afa.png)

**Comment by d-korolkov** [comment]
try to turn off **fx** on layers anyway they will not work and share the aep project for better understanding th situation.

**Comment by bodymovin** [comment]
@rutraq hi, did you manage to get it working?
