### ISSUE TITLE
HTML5 File size is to big!?

### ISSUE THREAD

**Issue by Newleech** [airbnb/lottie-web#2124]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by Newleech** [comment]
Hi, i make animationin After Effects with 300x250px size, when i export this one with Bodymovin to html, size in browser is much more bigger than 300x250px. Have any idea what is problem here? tnx

**Comment by Newleech** [comment]
Hi,  i make simple animation in After Effects and export this to html5. The file size is more than 150kb and i can#t use that for Google ADs, any ideas how can i decrase html5 file size?
[Archiv.zip](https://github.com/airbnb/lottie-web/files/4528533/Archiv.zip)

**Comment by bodymovin** [comment]
Hi, 118Kb of the animation consist of the images. Have you tried compressing them and see if size gets reduced?
