### ISSUE TITLE
Images not showing in lottie preview

### ISSUE THREAD

**Issue by maxanastasi** [airbnb/lottie-web#2125]
Hi I am quite new to this, so forgive my ignorance! 

I have tried exporting my comp using bodymovin to upload on lottie but images are not showing. Am I missing something? I have tried googling but cant seem to find the answer.

Thanks,

Max

<img width="1778" alt="Screenshot 2020-04-24 at 15 46 30" src="https://user-images.githubusercontent.com/64269769/80225405-eff51000-8642-11ea-935f-af7e312d42c1.png">

**Comment by henriqrossatto** [comment]
Hi @maxanastasi. 

Isn't working because the lottiefiles site can't read the images folders exported with the data.json file. To solve it you can just zip all together and drop the zip on lottie files or export the images with the data.json going in settings>assets and enabling the option "Include in json"

**Comment by nourhankay** [comment]
Thank you so much @henriqrossatto ! It took me SO long to finally come across this answer and it actually fixed my broken image issue!


> Hi @maxanastasi.
> 
> Isn't working because the lottiefiles site can't read the images folders exported with the data.json file. To solve it you can just zip all together and drop the zip on lottie files or export the images with the data.json going in settings>assets and enabling the option "Include in json"

**Comment by vijaypwr61** [comment]
hi @maxanastasi I am facing the same issue, how did you solve this? Please help

**Comment by potatohands** [comment]
<img width="707" alt="Screen Shot 2022-07-14 at 10 56 59 AM" src="https://user-images.githubusercontent.com/32831388/178879942-ef23702d-2183-435c-b1db-2507a6737c7b.png">
Hi @vijaypwr61 
I solved it. You can set up like this what I uploaded.

> hi @maxanastasi I am facing the same issue, how did you solve this? Please help
