### ISSUE TITLE
How to use one animation with multiple element

### ISSUE THREAD

**Issue by namlq93** [airbnb/lottie-web#2127]
**My problem:**
I'm using lottie-web with reactjs. But i want use one animation with multiple element. Example: Like of posts, animation of like depends on the State being passed. It didn't work as expected

**My code:** 
_App.js:_
```
const [isLiked, setLike] = useState(true);
  const [isLiked2, setLike2] = useState(false);
  return (
    <div className="App">
      <h1>Demo Animation</h1>
      <Like isLiked={isLiked} />
      <button
        onClick={() => setLike(!isLiked)}
        style={{ color: isLiked ? "green" : null }}
      >
        Like
      </button>
      <Like isLiked={isLiked2} />
      <button
        onClick={() => setLike2(!isLiked2)}
        style={{ color: isLiked2 ? "green" : null }}
      >
        Like2
      </button>
    </div>
  );
```
_Like.js:_
```
let likeAnimObj = null;

export default function Like({ isLiked }) {
  const container = useRef(null);
  const loadAnimation = () => {
    likeAnimObj = lottie.loadAnimation({
      container: container.current, // the dom element that will contain the animation
      renderer: "svg",
      loop: false,
      autoplay: false,
      animationData: animationLike // the path to the animation json
    });
  };
  useEffect(() => {
    loadAnimation();
    isLiked
      ? likeAnimObj.goToAndStop(60, true)
      : likeAnimObj.goToAndStop(0, true);
  }, []);

  const firstUpdate = useRef(true);
  useEffect(() => {
    if (firstUpdate.current) {
      firstUpdate.current = false;
      return;
    }
    likeAnimObj.destroy();
    loadAnimation();
    isLiked
      ? likeAnimObj.playSegments([0, 60], true)
      : // : likeAnimObj.playSegments([60, 110], true);
        likeAnimObj.goToAndStop(0, true);
  }, [isLiked]);

  return <div style={{ width: 200, margin: "0 auto" }} ref={container} />;
}
```

You can run my example on **codesandbox**: [here](https://codesandbox.io/s/lottie-web-animation-gotostop-3-hktku?file=/src/Like.js)
I hope your response. Thank you so much!

**Comment by iamhuynq** [comment]
I'm also looking for this issue :(

**Comment by bodymovin** [comment]
Hi, I see a couple of potential issues so far. 
First of all, in Like.js, you are keeping a reference to `likeAnimObj` as part of the module so it will be shared between all instances of your button.
Second, you probably want to pass a new instance of the json animation every time, by doing `JSON.parse(JSON.stringify(animationLike))` 
Third, is there a reason why you load and destroy the animation every time the `isLiked` boolean changes? It will definitely have performance issues and you shouldn't need to do that.
Fourth, when you load the animation the first time, you need to attach a listener to the 'DOMLoaded' event before updating the initial frame or it will be overwritten by the initial values.

**Comment by namlq93** [comment]
@bodymovin 
> First of all, in Like.js, you are keeping a reference to likeAnimObj as part of the module so it will be shared between all instances of your button.

So I have to declare the `likeAnimObj` variables separately for each _like_ button like this?: 
```
const likeAnimObj = lottie.loadAnimation({
    container: container.current, 
    ...
  });
  const likeAnimObj2 = lottie.loadAnimation({
    container: container2.current,
   ...
  });
```

**Comment by bodymovin** [comment]
I'm not that familiar with react hooks, but I think you should have two hooks, one similar to this:
`const [animation, setAnimation] = useState(null)`
and the other:
`useEffect(()=>{setAnimation(loadAnimation())},[])` and make sure that your `loadAnimation` method returns the animation instance.
Here is a version that I think gets closer to what you need, but I'm not a react hooks expert and you probably need to adjust it to your needs.
https://codesandbox.io/s/lottie-web-animation-gotostop-3-g5cq4

**Comment by namlq93** [comment]
@bodymovin Thank you so much. It's very helpful with me. Actually, my output is a little different so I've edited it a bit. You can see [here](https://codesandbox.io/s/lottie-web-animation-gotostop-3-fixed-c02i7?file=/src/Like.js). Even though I still don't fully understand, but it did work anyway. Thank you again <3

**Comment by bodymovin** [comment]
closing the issue. Reopen if needed.
