### ISSUE TITLE
Error when use lottie-web and run test reactjs with Jest.

### ISSUE THREAD

**Issue by namlq93** [airbnb/lottie-web#2133]
I'm using lottie-web library in my reactjs project. When I run test, initially I got error:

```
Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
``` 

![Screen Shot 2020-04-29 at 10 09 21](https://user-images.githubusercontent.com/41458989/80587171-48ac1a80-8a40-11ea-9776-87b8c2c12379.png)

I've reseached and fixed it by install `jest-canvas-mock`:
```
        "setupFiles": [
            "<rootDir>/tests/setupJest.ts",
            "jest-canvas-mock"
        ],

```

But I've got new error: `Error: connect ECONNREFUSED 127.0.0.1:80` :( 

![Screen Shot 2020-04-29 at 10 10 47](https://user-images.githubusercontent.com/41458989/80588215-20252000-8a42-11ea-96e7-e821859e1955.png)

**Comment by bodymovin** [comment]
hi, I think that for testing purposes you'd probably want to mock the lottie library. Otherwise it will try to load the animation through the network, which is probably what is happening in this case.

**Comment by namlq93** [comment]
@bodymovin thank you, but i dont know how to mock the lottie library. I have searched a lot but to no avail :(

**Comment by namlq93** [comment]
> hi, I think that for testing purposes you'd probably want to mock the lottie library. Otherwise it will try to load the animation through the network, which is probably what is happening in this case.

thank you. `jest.mock('lottie-web')` worked for me

**Comment by akash-pal** [comment]
@namlq93 how did you use jest.mock('lottie-web'), can you please provide a snippet.

**Comment by namlq93** [comment]
> @namlq93 how did you use jest.mock('lottie-web'), can you please provide a snippet.

![Screen Shot 2020-07-21 at 10 59 08](https://user-images.githubusercontent.com/41458989/88011321-3e7e5180-cb41-11ea-8bb4-b4bbb3f1dd6f.png)

**Comment by akash-pal** [comment]
@namlq93 In my case i do have even have jest setup, currently its 'mocha-webpack', any idea of how can i do the same thing without jest or if i have to setup jest?
My doubt is jest is there in some internal dependent package which is causing this error.

**Comment by akash-pal** [comment]
@bodymovin @namlq93 for reference i was able to mock the canvas as per this solution [Mock canvas](https://github.com/jsdom/jsdom/issues/1782#issuecomment-337656878)

**Comment by dimosmera** [comment]
You can also try importing `jest-canvas-mock` on your setupTests file

**Comment by DesKevinMendez** [comment]
My solution is: 
it adds the followed code into the setup.js file 
```
HTMLCanvasElement.prototype.getContext = () => { 
  return {
    fillRect: jest.fn(),
    ...
  };
};
```

Note: return what you need.
