### ISSUE TITLE
Animated number count is wrong when exported

### ISSUE THREAD

**Issue by JohnnyBedini** [airbnb/lottie-web#2134]
**Tell us about your environment**
Macbook Pro 15-inch, 2017
2.8 GHz Quad-Core Intel Core i7
16 GB 2133 MHz LPDDR3
Radeon Pro 555 2 GB
Intel HD Graphics 630 1536 MB

* **Browser and Browser Version:**
Chrome 81.0.4044.129 (Official Build) (64-bit)

* **After Effects Version:**
17.0.2 (Build 26)

**What did you do? Please explain the steps you took before you encountered the problem.**
Using expressions found here https://forums.creativecow.net/docs/forums/post.php?forumid=227&postid=33833&univpostid=33833&pview=t I made a number counter that goes up from $0 to $4,503,280. I then isolated this number in a pre-comp to make an animated svg of it.

**What did you expect to happen?**
To see what I saw in after effects in the lottie preview.

**What actually happened? Please include as much _relevant_ detail as possible.**
The numbers went haywire - it seems that it couldn't fully understand the expression, as the numbers go up and down, adding commas in the wrong place, and eventually landing on '$,4,50,20'. You can see the preview here: https://lottiefiles.com/share/pheNT1

**Please provide a download link to the After Effects file that demonstrates the problem.**
[Builder cloud landing page folder.zip](https://github.com/airbnb/lottie-web/files/4559496/Builder.cloud.landing.page.folder.zip)

**Comment by bodymovin** [comment]
Hi, when using expressions combined with text exported as glyphs, you need to provide a separate layer with all the needed characters that will be used to render the expression.
In your case, you probably want another text layer with the character range from 0 to 9 and the comma.
You can put it outside the work area and outside the drawing area so you make sure it doesn't get rendered, but still will be used to render the needed characters.
If you check the console in lottie files you' ll see there are warnings explaining which characters are missing.
