### ISSUE TITLE
Bodymovin License Error and Not Showing in After Effects Extensions

### ISSUE THREAD

**Issue by JulianWells** [airbnb/lottie-web#2135]
Hi,
Downloading BM for the first time so I can use as an extension in Adobe After Effects.
Tried two methods of download - via the CC extensions portal and then using their suggested ExtensionManager if having difficulties.

For the former, the app appears to download, but closing and opening AE, nothing in the Windows > Extension list.

Using ExtensionManager - at least I get an error of sorts for this - says 'Extension license is damaged (error code: 603). Please contact its creators for the assistance.'

Using MacOS High Sierra v10.13.6
Abode AE v17..0.6
Using latest Google Chrome (downloaded today)

Thanks
Jules

**Comment by bodymovin** [comment]
Hi, have you tried using aescript zxp installer?
https://aescripts.com/learn/zxp-installer/

**Comment by JulianWells** [comment]
Thanks bodymovin.
I had been using it yes but was getting the same license error. However, I have now followed the steps as shown on the AirBnB link you have on your GitHub home page and this more recent version of the ZXP and Bodymovin (not the one available on Adobe) is now working and has installed correctly.
Thank you, issue resolved.
