### ISSUE TITLE
All typekit fonts supported?

### ISSUE THREAD

**Issue by stevenyeo1234** [airbnb/lottie-web#2142]
hi Bodymovin, 

can i check that all typekit fonts are supported when export via bodymovin and play using lottiefiles?

Shown below is the screencapture, seems that URW Form font is not being displayed correctly. 
<img width="1467" alt="6may_TESTINGlottie" src="https://user-images.githubusercontent.com/63344698/81151159-4b17f280-8fb3-11ea-9fcf-1c887ffeb834.png">

i had double checked the generated json file. Seems correct, all the 3 fonts points to https://use.typekit.net/ppo2ili.css webproject.

I attached the aep and json file below in case u need a closer look.
[Archive.zip](https://github.com/airbnb/lottie-web/files/4585508/Archive.zip)

**Comment by bodymovin** [comment]
Hi, I've found the issue. I'll have a fix for the next deploy.
Probably tomorrow night.
Thanks for reporting!
If you want it working on your current exporter, don't add `sans-serif `as a second option in the font family and it should work fine.
