### ISSUE TITLE
I can't open the exporting settings and the destination root

### ISSUE THREAD

**Issue by juandelahoz99** [airbnb/lottie-web#2146]
Hi, I have problems when trying to export my Duik animation with Bodymovin, I click on the settings and anything happened, the plugin doesn't show me the options. the same happens when I try to set my destination root of the JSON, the plugin don't open the finder window to set that. 

**Environment:**
AE 17.0.6
Bodymovin 5.6.9
Mac OS Catalina 10.15.3

**Comment by bodymovin** [comment]
Hi, can you share a screenshot of what you are seeing?
