### ISSUE TITLE
Animation file not loading at all

### ISSUE THREAD

**Issue by labedzde** [airbnb/lottie-web#2147]
I'm having issues getting my JSON animation file to load at all. I checked in the Lottie previewer and it appears normally. I'm not getting any console errors or 404 errors. It just simply isn't loading in the container. More details below. 

**Tell us about your environment**

I built a WordPress website using the Trellis/Sage/Roots stack. I am also using Vue to implement some interactivity, though I am not using it for this animation at all. 

* **Browser and Browser Version:**
Chrome v81

* **After Effects Version:**
17.0.6

**What did you do? Please explain the steps you took before you encountered the problem.**

I installed Lottie and Bodymovin through npm. I also uploaded the JSON file to my theme. In my main.js file, I implemented the animation like this: 

`  import bodymovin from 'bodymovin';
  import 'lottie-web';
  const loader = require('../loader.json');
  
  lottie.loadAnimation({
    container: document.getElementById('loaderAnimation'), // Required
    renderer: 'svg',
    loop: true,
    autoplay: true,
    animationData: loader, // Required
  });
`

I added the container to my main template like this: 

`<div id="loaderAnimation"></div>`

And I added some styles like this: 

`#loaderAnimation{
	width:100%;
	height:100%;
}`

**What did you expect to happen?**

I expected the animation to load on this page. [http://www.kiwiartsgroup.kinsta.cloud/](http://www.kiwiartsgroup.kinsta.cloud/) inside the div called "loadAnimation". 

**What actually happened? Please include as much _relevant_ detail as possible.**

The div appears on the site, but it is empty and does not load the animation. 

**Please provide a download link to the After Effects file that demonstrates the problem.**

Here is a link to the JSON file. 
https://drive.google.com/file/d/1MIKktb0MRxRF2XcN0d1AVbfemUzO1FWk/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, it's difficult to debug with this information.
Can you create a simple example of how you are loading it?
If not, I would suggest that you add some logs to see if everything is working as expected.
