### ISSUE TITLE
Animation file not loading

### ISSUE THREAD

**Issue by toxifiedmatrix** [airbnb/lottie-web#2148]
Getting these errors:
Error 1
Access to XMLHttpRequest at 'https://gulaticateringcompany.com/Latest/data.json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Error 2
GET https://gulaticateringcompany.com/Latest/data.json net::ERR_FAILED      lottie.js:13 

What can be done?

**Comment by bodymovin** [comment]
Hi, those are regular CORS issues unrelated to the library. Depending on your setup you should do some research to identify what might be going on in your case.
