### ISSUE TITLE
Animation is not worked

### ISSUE THREAD

**Issue by cashalotkzn** [airbnb/lottie-web#2150]
Hi. Im use lottie-web on my project. But animation is not showing.
Details:
My element:
![image](https://user-images.githubusercontent.com/4135982/81540181-f4773380-9379-11ea-83aa-0786da12d075.png)
My code:
![image](https://user-images.githubusercontent.com/4135982/81540307-1ec8f100-937a-11ea-984e-ab65693d234f.png)
My console:
![image](https://user-images.githubusercontent.com/4135982/81540440-56379d80-937a-11ea-9bdf-1f91c6f2cfe2.png)

I see that the animation is on the page and loaded correctly, but it is marked isLoaded: false
![image](https://user-images.githubusercontent.com/4135982/81540632-9860df00-937a-11ea-9dc9-eebb614f98b1.png)

What am I doing wrong?
Ty for answer )

**Comment by bodymovin** [comment]
Hi, it seems you are passing a jquery reference instead of a DOM element.
can you try changing it to `$('.lottie')[0]` or something similar?

**Comment by cashalotkzn** [comment]
yeap, you're right, thanks) it's worked. but can i make animation for all .lottie elements?

**Comment by bodymovin** [comment]
not sure I understand your question

**Comment by cashalotkzn** [comment]
don't care. thats worked, thank u!
