### ISSUE TITLE
Container resize issue

### ISSUE THREAD

**Issue by AurelienWeb** [airbnb/lottie-web#2152]
**Tell us about your environment**
* **Lottie version : 5.6.5**
* **Browser and Browser Version:**
tested in chrome version 81.0.4044.138

**What did you do? Please explain the steps you took before you encountered the problem.**
I'm trying to set width to the animations's container using CSS. 

My CSS : 
```
.fil-navigation{
  width: 200px;
}
```

My JS : 
```
anim_navigation_elem_1 = document.getElementById("fil-navigation0");
    anim_navigation_1 = bodymovin.loadAnimation({
        container: anim_navigation_elem_1,
        renderer: 'svg',
        loop: true,
        autoplay: false,
        path : '/assets/img/fil-navigation.json',
    });
anim_navigation_1.setDirection(-1);
anim_navigation_1.setSpeed(6);
anim_navigation_1.play();
anim_navigation_1.addEventListener('enterFrame', function() {
if(anim_navigation_1.currentFrame < 100){
     anim_navigation_1.pause();
    }
});
```

**What did you expect to happen?**
The animation should resize and work without rendering issue

**What actually happened? Please include as much _relevant_ detail as possible.**
The animation is perfectly sized but the rendering shows some visual issues, it shows some tangents at each loop as shown in the screen below.

**Please provide a download link to the After Effects file that demonstrates the problem.**
You will find the json file in the archive below.

[fil-navigation.zip](https://github.com/airbnb/lottie-web/files/4608885/fil-navigation.zip)
![rendering](https://user-images.githubusercontent.com/8917980/81549634-56866780-937f-11ea-874e-0b3f3fe3b681.png)

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by AurelienWeb** [comment]
Hello,
Sorry for the delay, here is the aep file. You will find many animations in this aep project. Those involved in this issue are : ligne2_rect, ligne5_rect, ligne6_rect, ligne6

[animations.zip](https://github.com/airbnb/lottie-web/files/4646361/animations.zip)

**Comment by AurelienWeb** [comment]
Actually, I have noticed that it's not a matter of resizing. This happens when I use multiple animations in the same page as follow : 
```
<div id="fil" class="bodymovin"></div>
<div id="fil2" class="bodymovin"></div>
<div id="fil3" class="bodymovin"></div>
<div id="fil4" class="bodymovin"></div>
<div id="fil5" class="bodymovin"></div>
<div id="fil6" class="bodymovin"></div>

<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.6.5/lottie.min.js"></script>
<script type="text/javascript">
    var anim = []; // collecting animation instances in this array
   /**
    *  Animations
    */
   $('.bodymovin').each(function(index, el) {
    
    var params = {
        container: $(this)[0],
        renderer: 'svg',
        loop: true,
        autoplay: true,
        path: 'fil-navigation.json'
    };
    anim[index] = bodymovin.loadAnimation(params);
    anim[index].setDirection(-1);
    anim[index].setSpeed(10);
    anim[index].play();
    
   });
</script>
```

You can see a demonstration here (oviously on firefox it works well but not on Chrome) : 
[http://burgundi.accolade-web.fr/](url)

**Comment by bodymovin** [comment]
it seems to be a Chrome artifact.
But I've noticed that if you explicitly set a height of 126px or 200px the glitch goes away.

**Comment by AurelienWeb** [comment]
Indeed, when in this demo when I set a height of 126px the glitch goes away but not in production. Maybe I have to find correct pixel height and width to make it disappear...

**Comment by AurelienWeb** [comment]
I have noticed that the bug appears in after effects in the bodymovin window as follow : 
![bug2](https://user-images.githubusercontent.com/8917980/82841616-0d81f780-9ed7-11ea-8009-6642f3808292.png)

So it's not completely a problem with google Chrome. I still haven't found how to solve it in after effect though...

**Comment by AurelienWeb** [comment]
I allow myself to bring this post up because I still haven't found how to solve this. Do you have any idea?

Thanks.

**Comment by bodymovin** [comment]
These are svg browser renderer artifacts that unfortunately don't have a good solution.
They usually are related to masks, so you can try to tweak them around or change them with regular masks to see if the issue goes away

**Comment by AurelienWeb** [comment]
Thank you, I will check how to simplify my masks.

**Comment by AurelienWeb** [comment]
After simplifying masks in after effects it works great! Thank you for your help!
