### ISSUE TITLE
Can`t see animation in demo

### ISSUE THREAD

**Issue by 5he1n** [airbnb/lottie-web#2160]
I'm using "demo" option in renderer, but I can't see at least a part of animation in demo file, In my animation there are three objects: two 3D texts with changing position and opientation and one static camera with custom position. I would be really glad if someone could check my file and say any guesses

Checked in Firefox and Chrome

Using AE 2020 and Bodymovin 5.6.9

Attached zip with dem, data and .aep file and image with what I want to see

I had idea that I need to reduce amount of keyframes, but when I launch demo *I see that vars of animation div are changing* 

Still working on reducing number of keys

[problem.zip](https://github.com/airbnb/lottie-web/files/4626994/problem.zip)

![изображение](https://user-images.githubusercontent.com/49807893/81912547-639d9380-95d7-11ea-8938-01c014567b69.png)

**Comment by bodymovin** [comment]
Hi, your project crashes my AE. It looks like it has a lot of keyframes.
I couldn't check the composition, but if you are animating text in 3d, it has limited support

**Comment by 5he1n** [comment]
> It looks like it has a lot of keyframes.
> you are animating text in 3d

Yep, it has lots of keyframes for animated 3D text. Sadly I can't reduce amount of keys. Anyway thanks, will try to do something with it
