### ISSUE TITLE
Animation ID in events callbacks

### ISSUE THREAD

**Issue by Oleg-Tokar** [airbnb/lottie-web#2163]
Hello! It will be nice to have animationId in events handlers. Thanks

**Comment by bodymovin** [comment]
hi, can you ellaborate some more? How are you imagining it would work?
As an extra property on the events passing the name of the animation as id?

**Comment by azeemhassni** [comment]
>  It will be nice to have animationId
By animationId you mean the wrapper element?

**Comment by Oleg-Tokar** [comment]
Hi!

Lottie has AnimationItem type with unique animationID string property. If it will be included in to event callback parameters we can manage animations without using closures.

Example:

```javascript
const animationQueue: AnimationItem[] = [];

const loopCompleteHandler = ({animationID: completedAnimationID}: {animationID: string}) => {
    const currentAnimationIndex = animationQueue.findIndex(({animationID}) => animationID === completedAnimationID);
    animationQueue[currentAnimationIndex].stop();
     animationQueue[currentAnimationIndex + 1].start();
};

animationsData.forEach((animationData) => {
   const animation: AnimationItem = lottie.loadAnimation({
            animationData,
            container: refAnim.current,
            autoplay: false,
        });
   animationQueue.push(animation)
   animation.addEventListener('loopComplete', loopCompleteHandler)
});
```

**Comment by kudanai** [comment]
Hope the above answered the question. If not, please feel free to re-open the issue.

For some more info and tricks check out the [Advanced interactions](https://lottiefiles.github.io/lottie-docs/advanced_interactions/) guide on LottieFiles lottie-docs
