### ISSUE TITLE
Bodymovin not exporting dropshadows

### ISSUE THREAD

**Issue by blamebento** [airbnb/lottie-web#2164]
Its been a few months since I used Bodymovin. Looks like it doesn't export dropshadows anymore?

Am I missing something? is there something I need to check off before exporting my files?

**Comment by bodymovin** [comment]
hi, take a look at the wiki regarding filters:
https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#filtersize-svg-renderer
You probably need to specify the size of the drop shadow container.
