### ISSUE TITLE
Path Renders Differently in Second and Following Loops

### ISSUE THREAD

**Issue by emilbruckner** [airbnb/lottie-web#2165]
**Tell us about your environment**

* **Browser and Browser Version:** Chrome 81
* **After Effects Version:** 16.1.3

**What did you do? Please explain the steps you took before you encountered the problem.**
**What did you expect to happen?**
**What actually happened? Please include as much _relevant_ detail as possible.**

The animation runs fine, but on the second and following loops, paths are off.

1st loop:
<img width="518" alt="Screen Shot 2020-05-16 at 15 51 46" src="https://user-images.githubusercontent.com/9105589/82121652-faf91700-978e-11ea-843a-b37bd180ab95.png">
2nd-nth loop:
<img width="480" alt="Screen Shot 2020-05-16 at 15 52 03" src="https://user-images.githubusercontent.com/9105589/82121657-03515200-978f-11ea-9578-c1f5f71c90f3.png">

I’d expect it to look the same in the first and second loop.

You can use the attached bodymovin json to reproduce.

I’m currently working around this by completely throwing out the animation and reinitiating it after it completes, which gives me a few white frames in the loop. I’d already appreciate a better workaround.

**Please provide a download link to the After Effects file that demonstrates the problem.**
[ae+bodymovin.zip](https://github.com/airbnb/lottie-web/files/4638480/ae%2Bbodymovin.zip)
(loops from 1sec – end)

**Comment by bodymovin** [comment]
Hi, I've found the issue. It will be fixed on the next release.
Thanks for reporting it!

**Comment by emilbruckner** [comment]
Thank you so much!
