### ISSUE TITLE
I cant select a destination folder

### ISSUE THREAD

**Issue by juandelahoz99** [airbnb/lottie-web#2167]
I am having an issue when I open the bodymovin extension and I cannot select a destination folder or the settings.

This means I cannot export the file as it keeps asking to select destination folder.

Mac OS and BodyMovin

**Comment by bodymovin** [comment]
Hi, can you share a screenshot or describe the issue further?
What happens when you try so select the folder?
Also, are the topbar navigation buttons working?

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
