### ISSUE TITLE
Render lottie file on canvas to videos

### ISSUE THREAD

**Issue by sparkmorry** [airbnb/lottie-web#2168]
Hi guys,
     We have a project on rendering videos from Adobe After Effect, and found that **Bodymovin** and  **Lottie** could be a good way to export a AE project and rerender it on web canvas for editing. While Lottie have many effects not supported, which confused me. Is that because of performance or AE support ?  Do you have some plans to full-fill the features?

**Comment by bodymovin** [comment]
Hi, supporting those effects on canvas is unfortunately a very difficult task.
Perhaps a webgl renderer could do it but it would take a long time to develop.

**Comment by sparkmorry** [comment]
> Hi, supporting those effects on canvas is unfortunately a very difficult task.
> Perhaps a webgl renderer could do it but it would take a long time to develop.

ok, thanks hernan, I may fork the repo and try out the extra effects

**Comment by xiaoblack163** [comment]
use puppeteer and FFmpeg  to videos
