### ISSUE TITLE
Having problems to render with Bodymovin

### ISSUE THREAD

**Issue by Pountry** [airbnb/lottie-web#2169]
Hi, I was trying to render a json file with Bodymovin but it wasn't rendered as what I created in Ae.

My Ae version: 16.1.3 (build5)

Frame rate is 30 and with 5 secs duration.
I created a spinning text with the cylinder effect. 
I wanted to use it for the webflow, but the json file I rendered had no effect but only the plain text. 

I am just a beginner and I just couldn't figure out what is the problem.

Here is the video of my steps:
https://youtu.be/St0flgUN_EU
Here is my Ae file.
https://drive.google.com/file/d/1BJbkKZFxB_XU0EIdA73e9c8nvH6QxWBL/view?usp=sharing

Hope somebody can help me out!

**Comment by Bazoogle** [comment]
Not all effects are compatible with bodymovin

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
