### ISSUE TITLE
Animation glitches on android device

### ISSUE THREAD

**Issue by ksmink** [airbnb/lottie-web#2170]
Hi!

Pretty new to Lottie, so hopefully my question isn't too stupid...

I've made an animation in After Effects. Finally managed to make it work with Lottie on Chrome (Mac OSX). Did a victory dance, found out it is't working so well on other devices...
The animation: https://lottiefiles.com/share/ZKDO3S

This it how it looks with the Lottie app on android. (see the legs)
![screenshot01](https://user-images.githubusercontent.com/65669448/82462873-68bd7f80-9abc-11ea-915e-288102d78ede.png)

On the Chrome app on android it looks better but the animation has an 'stutter'. looks like there are missing some frames.

Does anyone have some tips and tricks how to solve it?

Thanks!

**Comment by bodymovin** [comment]
Hi, it seems you are using expressions, which are not supported on the lottie-android and lottie-ios players

**Comment by ksmink** [comment]
Thanks for the reply!
