### ISSUE TITLE
Bodymovin Panel is empty !

### ISSUE THREAD

**Issue by Johnkuttykm** [airbnb/lottie-web#2174]
![Screenshot 2020-05-22 at 3 05 49 PM](https://user-images.githubusercontent.com/65762905/82654727-cda0e300-9c3e-11ea-931b-ceaa32881351.png)

**Tell us about your environment**
MacOs Mojave 10.14.6
* **Browser and Browser Version:**
Firefox 76.0.1 64 bit
* **After Effects Version:**
Adobe After Effects CC 2017.2 Release  Version 14.2.0.198
**What did you do? Please explain the steps you took before you encountered the problem.** 

- Opened the after effects
- done a simple animation
- opened bodymovin from extensions
- empty panel is shown

**What did you expect to happen?**
to launch boymovin smoothly & correctly
**What actually happened? Please include as much _relevant_ detail as possible.**
- Opened the after effects
- done a simple animation
- opened bodymovin from extensions
- empty panel is shown
- uninstalled and reinstalled the bodymovin 
- also edited the registry key [ ~/Library/Preferences/com.adobe.CSXS.6.plist and add a row with key PlayerDebugMode, of type String, and value 1 ]

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/file/d/17RGVwtIw1R2h7GkSEaEY46fxwrg5zjB5/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, there is a problem with AE 2017 and Bodymovin 5.6
Can you try updating your AE version or using version 5.x of Bodymovin?

**Comment by Johnkuttykm** [comment]
5.x means?

**Comment by bodymovin** [comment]
I meant, 5.5.x
you can get it on the relases page
https://github.com/airbnb/lottie-web/releases

**Comment by Johnkuttykm** [comment]
now its working with 5.5.1  

thanks :)
