### ISSUE TITLE
Do Nothing, pls help

### ISSUE THREAD

**Issue by learningdesign23** [airbnb/lottie-web#2175]
![Screenshot_1](https://user-images.githubusercontent.com/65609651/82677037-939d0480-9c71-11ea-978f-ae232c015207.png)

![Screenshot_3](https://user-images.githubusercontent.com/65609651/82677182-d4951900-9c71-11ea-9941-d318ca8f81ee.png)
 
Pls can u help?
 Nothing happen in my browser.
Thanx U

**Comment by axcr** [comment]
I think you should change document.getElementByID to document.getElementsByClassName("bm").

**Comment by learningdesign23** [comment]
Oke Thanx You very much for your help

**Comment by bodymovin** [comment]
Closing. Reopen if needed.
