### ISSUE TITLE
problem during the export

### ISSUE THREAD

**Issue by emamin25** [airbnb/lottie-web#2176]
Good evening, 
I have a problem with bodymovin during the export. 
During export, the plug-in takes a long time to export images even if the composition lasts a few seconds. I activate the permission for script to write file.

**Comment by bodymovin** [comment]
Hi, what version of AE are you using?

**Comment by emamin25** [comment]
Hi, i use AE cc 2018

**Comment by bodymovin** [comment]
Hi, there is a problem exporting images with AE 2018, can you update to a newer version of AE or use an older version of Bodymovin like v5.5.x?

**Comment by emamin25** [comment]
Hi, it's impossible update AE because I have a old version of firmware on mac and the new version it's not compatible. Do you have a link for old version of Bodymovin?

**Comment by bodymovin** [comment]
Here are all releases
https://github.com/airbnb/lottie-web/releases

**Comment by emamin25** [comment]
Which one do you recommend?

**Comment by bodymovin** [comment]
version 5.5.10 should work

**Comment by emamin25** [comment]
thanks, do you have a tutorial for unistall a new version?

**Comment by kudanai** [comment]
It would be the same procedure as the initial install via zxp installer. 

Closing this issue for now. Please feel free to re-open if needed
