### ISSUE TITLE
Playing a lottie animation from beginning which has an initialSegment by default

### ISSUE THREAD

**Issue by hakkim** [airbnb/lottie-web#2177]
I am building a lottie animation. My requirement is when the page loads, a specific frame must be preset by default. And when a user hover the element, the animation should start from the beginning. And after finishing the animation it has to come back to the initially predefined frame. I tried to make it work with goToAndPlay() method, but it is not working.

This is my javascript
```
let iconMenu = document.querySelector('.bodymovinanim1');
let animationMenu = bodymovin.loadAnimation({
        container: iconMenu,
        renderer: 'svg',
        loop: false,
        autoplay: false,
        path: "https://assets2.lottiefiles.com/packages/lf20_txJcSM.json",
        initialSegment: [51.5, 200],
});

iconMenu.addEventListener('mouseenter', (e) => {
animationMenu.goToAndPlay(1, true);
});
```
[This is the fiddle for the same.](https://jsfiddle.net/hakkim/o0tjhzLe/8/)

Can anyone please help me?

**Comment by bodymovin** [comment]
hi, what is it that is not working?

**Comment by hakkim** [comment]
> hi, what is it that is not working?

I want to play the animation starting from the first frame. But right now the animation is playing from 'initialSegment' frame only. How can I make it animate from beginning?

**Comment by bodymovin** [comment]
you can use `animationMenu.playSegments([initialFrame, endFrame])` to set the specific segment you want to play.

**Comment by hakkim** [comment]
> animationMenu.playSegments([initialFrame, endFrame])

I tried to make it work with `animationMenu.playSegments([initialFrame, endFrame])` and it behaves strange. When cursor enter into the icon, the animation starts just from the `initialSegment` and when mouse leaves the animation starts from beginning...
[This is the fiddle.](https://jsfiddle.net/hakkim/o0tjhzLe/11/)

**Comment by bodymovin** [comment]
there is a pending segment that hasn't been player, that's why it will play first the initialSegment and then the segment you provided.
Try passing true as the second argument of playSegments so it will ignore the current segment
`animationMenu.playSegments([0, 200], true)`

**Comment by hakkim** [comment]
> there is a pending segment that hasn't been player, that's why it will play first the initialSegment and then the segment you provided.
> Try passing true as the second argument of playSegments so it will ignore the current segment
> `animationMenu.playSegments([0, 200], true)`

Awesome... Thank you very much....
