### ISSUE TITLE
help for unistall the bodymovin

### ISSUE THREAD

**Issue by emamin25** [airbnb/lottie-web#2185]
Hi, is there a way to uninstall bodymovin?

**Comment by bodymovin** [comment]
Hi, have you tried the zxpinstaller from aescripts?
https://aescripts.com/learn/zxp-installer/

**Comment by emamin25** [comment]
yes, but zxpinstaller is only for install the plugin, not for unistall

**Comment by bodymovin** [comment]
You can uninstall from zxp installer too.
