### ISSUE TITLE
Lottie text animation problem. Changed position, and it separated.

### ISSUE THREAD

**Issue by latif-animoox** [airbnb/lottie-web#2186]
Hi Bodybovin,
https://lottiefiles.com/share/SAupEV
This is my Lottie files.
I animated it in after effect but when I export it animation and font position changed, font changed, the color changed,  The Android version is totally changed. 
I want the same animation on the computer, IOS, Android too.

my query is: My animation will be the same for all and able to editable text.
Font, color, font size.

Please let me know.

![2](https://user-images.githubusercontent.com/65957842/82902375-2fd04f80-9f81-11ea-99ba-8488c9b1d8f0.PNG)
![3](https://user-images.githubusercontent.com/65957842/82902383-319a1300-9f81-11ea-99a0-c9e3c31a6ac7.PNG)

**Comment by bodymovin** [comment]
Hi, I think the android and ios players have very limited font support.

**Comment by kudanai** [comment]
For a breakdown of supported features please check out [https://canilottie.com/](https://canilottie.com/). I'm closing this issue as stale since the author hasn't responded in a while. If this is still relevant feel free to re-open the issue
