### ISSUE TITLE
Lottie light player doesn't play some files

### ISSUE THREAD

**Issue by blobinabottle** [airbnb/lottie-web#2188]
**Tell us about your environment**
Web, latest version of lottie-web, all browsers

**What did you do? Please explain the steps you took before you encountered the problem.**
Trying to load anim from lottiefiles in lottie light player

**What did you expect to happen?**
Load and play animation

**What actually happened? Please include as much _relevant_ detail as possible.**
Not loading animation. Not triggering domLoaded or any error 

**Please provide a download link to the After Effects file that demonstrates the problem.**
See here https://codesandbox.io/s/hungry-browser-i5f94?file=/src/index.js
=> You can switch path to the local JSON file => that animation is working. Not the one from S3. 

If you use import lottie from "lottie-web" it is working in all cases.

Thanks for your help!

**Comment by bodymovin** [comment]
Hi, the lottie light player doesn't support expressions and effects, and it seems that animation is using effects somewhere.

**Comment by blobinabottle** [comment]
Ok make sense then! Thanks for the follow up.
