### ISSUE TITLE
Help regarding documentation

### ISSUE THREAD

**Issue by saurabh-ramola** [airbnb/lottie-web#2190]
**Tell us about your environment**

* **Google Chrome, Version: 80.0.3987.149(64 bit)**
* **After Effects Version: 2020**
* **Lottie Version: 5.6.5**

**What did you do? Please explain the steps you took before you encountered the problem.**
I am trying to map the elements in the JSON file I have exported using the bodymovin extension in Adobe after-effects to the format given in lottie-web/docs/json for a text-layer. 

**What did you expect to happen?**
In the JSON file obtained through bodymovin - [File](https://gist.github.com/saurabh-ramola/90814c10878a33ac7661ddab1e1fce49#file-text-json-L11-L19), I could not find the "fonts"
element in the file given in lottie-web/docs/json/animation.json - [File](https://github.com/airbnb/lottie-web/blob/master/docs/json/animation.json) .

I am trying to export Synfig format text-layer to lottie-web format and therefore I need help in figuring out why "fonts" is present in the JSON file obtained through bodymoving extension in AE2020 but not present in /docs/json/animation.json

@bodymovin Could you help me out here please ^__^

**Comment by AnishGG** [comment]
Just for reference, this is related to: https://github.com/airbnb/lottie-web/issues/1785
Synfig got a project under GSoC for "Improvements in Lottie exporter" this year. This project is pursued by @saurabh-ramola 
@bodymovin we would appreciate any kind of help here. ^__^

**Comment by bodymovin** [comment]
Hi, in AE fonts can be exported as glyphs or font data.
The documentation is missing the font option, that hasn't been described yet.
If you need any help figuring it out, let me know.

**Comment by saurabh-ramola** [comment]
Thank you for clearing my doubt ^__^ . I had a few more doubts regarding the layer :

1. In the following snippet -> [text_layer.json](https://gist.github.com/saurabh-ramola/90814c10878a33ac7661ddab1e1fce49#file-text-json-L72-L102) I could not understand what "j", "tr", "ls" ,"lh", "p" and "m" elements denote. I could not find the documentation for them.

2. If the fonts are exported as glyphs, as I understood the characters are converted to shapes using bezier curves. I wanted to ask if this data is calculated each time or if there are default values which are scaled accordingly with respect to the position,size of the char.

**Comment by saurabh-ramola** [comment]
@bodymovin , is line separation supported in lottie? For example if I had a text :
" Lottie
  Format"
Can I increase the separation between them?
Any help would be appreciated :D

**Comment by bodymovin** [comment]
@saurabh-ramola here you can find what properties map to each of the values
https://github.com/bodymovin/bodymovin-extension/blob/master/bundle/jsx/utils/textHelper.jsx
regarding your last question, that will map to what AE uses as `baselineLocs`

**Comment by saurabh-ramola** [comment]
Thank you for the help ^_^

**Comment by saurabh-ramola** [comment]
@bodymovin , is Gaussian blur supported for paths in shape layer? I tried exporting a Gaussian blur for paths in Shape Layer for version 5.6.5 and it didn't render the blur.
