### ISSUE TITLE
Preview bug in iOS devices

### ISSUE THREAD

**Issue by trkmntnc** [airbnb/lottie-web#2191]
Hi, I'd like to report an issue.
When I try to view [this animation](https://lottiefiles.com/share/CjavDm) in iOS 13.4.1 and macOS with the latest Safari (haven't tried any other browsers) the composition goes all the way to the bottom of the screen for a millisecond and goes back, every 2-3 seconds. 
You can see the issue [here](https://www.youtube.com/watch?v=HAGbDKxJdxI&feature=youtu.be).
However, there is no issue on desktop PC.
I thought that it may be the texts, and I've tried removing all the texts, converting them into shapes, and even removing them all. Unfortunately, none of them did resolve the issue though. 
Thanks.

**Comment by bodymovin** [comment]
hi, can you report the issue on the lottie-ios repository?
They will be more helpful than I can be.
https://github.com/airbnb/lottie-ios
