### ISSUE TITLE
animation from ae exported to json broken

### ISSUE THREAD

**Issue by yurichoe** [airbnb/lottie-web#2194]
@bodymovin hello, I was trying to export a simple blob animation as such using bodymovin and Lottie plugin from ae(latest version), but the final JSON file is not matching with the animation in ae. I rendered with a demo(HTML) and it's absolutely frustrating such as images. (It became flatten, no font/motion effect/shadow came through). The composition is 3 blobs moving for 10 sec(turbulent displacement), and 1 white text on the top with the drop shadow. Please correct me if the plugins aren't supporting any of effect.

And, please do advise me if there's any other way that I could generate the animation.

![Untitled 2](https://user-images.githubusercontent.com/66296936/83489168-a2ef2f80-a473-11ea-8f72-965e23a0d244.png)
![Untitled](https://user-images.githubusercontent.com/66296936/83489170-a2ef2f80-a473-11ea-81b9-acfff6d05ec2.png)

**Comment by bodymovin** [comment]
Hi, unfortunately the players doesn't support those types of effects.
If you need an animation of this type, you are probably better using an mp4 or an image sequence.
