### ISSUE TITLE
PNG Included JSON is not working on Lottie API 

### ISSUE THREAD

**Issue by yigitersoy87** [airbnb/lottie-web#2197]
Hi, i created animation included png image, its working on lottie editor here https://lottiefiles.com/editor but not working with the api we are trying. Is there any difference between these?
https://www.dropbox.com/s/vbfs0yl7ufr0vwd/data-with-picture.json?dl=0

**Comment by cookievscupcake** [comment]
Did you find a solution? I had a similar issue with a png.

**Comment by yigitersoy87** [comment]
> Did you find a solution? I had a similar issue with a png.

Yes. Updated Lottie API. It supports PNG 👍🏻
