### ISSUE TITLE
Bodymovin didn´t show any comp in AE

### ISSUE THREAD

**Issue by WIESBADENAMMEER** [airbnb/lottie-web#2198]
**Tell us about your environment**
Apple iMac / macOS Mojave 10.14.6
* **Browser and Browser Version:**
not important
* **After Effects Version:**
17.0.1
**What did you do? Please explain the steps you took before you encountered the problem.**
I create a simple AE animation and i need SVG export
**What did you expect to happen?**
BM should show me the Comp in the BM Window, so i could render the comp. (as it does before)
![Bildschirmfoto 2020-06-04 um 11 23 43](https://user-images.githubusercontent.com/66413942/83740265-e229a600-a656-11ea-9e22-3cb56625885e.png)

**What actually happened? Please include as much _relevant_ detail as possible.**
It shows nothing. 
**Please provide a download link to the After Effects file that demonstrates the problem.**
http://wp1154867.server-he.de/hafen/github/as_sequenz-for-github.aep

**Comment by bodymovin** [comment]
hi, there seems to be an issue with older versions of AE.
I'd recommend to update AE or use an older version of Lottie. Version 5.5.x should work fine.

**Comment by WIESBADENAMMEER** [comment]
Sorry my fault. I use AE Version 17.1.0. It´s the latest one. I try bodymovin 5.5.x
