### ISSUE TITLE
Nested Compositions

### ISSUE THREAD

**Issue by herrmanneffe** [airbnb/lottie-web#2199]
Hi,
I have an issue exporting a composition with bodymovin. 
When I launch "Render" it freezes after some seconds. The export doesn't finish and I have to quit.
I guess it's beacause I have three comps nested inside each other.
I know that two comps nested into each oder work, I have tried, but maybe three don't?
Is there a tweek to export such a comp? Maybe in the future?
Thank You

**Comment by bodymovin** [comment]
hi, nested comps shouldn't be an issue, can you share the .aep?

**Comment by herrmanneffe** [comment]
Hi @bodymovin,
you're right, the problem aren't the nested comps, instead it had to do with the .ai assets..
Bodymovin gets stuck when tring to convert the .ai into a .png
If I convert to shapes the .ai everithing works fine.

Here is the Ae file
[ae.zip](https://github.com/airbnb/lottie-web/files/4735894/ae.zip)

Thank You

**Comment by bodymovin** [comment]
Hi, I tried to export the animation and it seems to wek fine. Are you using an older version of AE? I know version 2018 has some issues exporting images.

**Comment by herrmanneffe** [comment]
Hi @bodymovin,
yes I'm using AE 2018 Version 15.1.2. maybe I messed up something because I never had problems exporting images.. 
Maybe due to duplication of compositions containing .ai assets?

**Comment by herrmanneffe** [comment]
I think that something broke my bodymovin.. 
I am able to export compositions containing .ai, only if they were loaded before "unknown event".
 Every composition I load after "unknown event" gets stuck when trying to export with BM, in the image export part.
I tried to upgrade BM replacing it's folder with the latest version: v5.6.10. But did't help.
Some cache somewhere? How can I restore it?
Thank You

**Comment by bodymovin** [comment]
That's strange. Perhaps you can try first uninstall it with zxp installer, and then try installing it back again.

**Comment by herrmanneffe** [comment]
I tried unistalling end reinstalling it through AdobeExchange, but nothing. 
I'll also try with zxp installer, but at this point probably the problem is AE..
I tried exporting a new comp from a new AE project pointing to a new .ai file, but the problem remains the same...

Any clue on why mi AE doesn't like BM anymore?

Tnks

**Comment by bodymovin** [comment]
Version 5.6.x has some issues with AE 2018, perhaps you can try with an older version, like any 5.5.x

**Comment by herrmanneffe** [comment]
Problem solved. I tried with BM v5.5.2 and now is exporting images again.  
So can't upgrade to v5.6.x unless I upgrade AE...

Thank you, at least now I know it :)
