### ISSUE TITLE
render to json failed on AE CC(v 15.0.0) on a video jpeg sequence

### ISSUE THREAD

**Issue by vivijojo** [airbnb/lottie-web#2205]
Hi,
I am trying to create a video on scroll website experience
according to instruction of webflow video on scroll(https://www.youtube.com/watch?v=2djbqUOtFgg),

I need to first export a video into a folder with frames of jpeg images, after that I need to open these images in AE with each image set to each frame and then render them in bodymovin with selection of compress image and include image in json, when I click render it fails to move forward, after a while it popped up an error saying: "unable to execute script at line 62"

 I did try to check "allow scripts to write files" and nothing changed. 

Could you help solve this issue please?

**Comment by bodymovin** [comment]
it seems you are using an old version of AE, can you try using bodymovin version 5.5.x?

**Comment by kudanai** [comment]
Closing this issue as stale for now. Feel free to re-open if you're still having issues
