### ISSUE TITLE
Problems with zoom-in/zoom-out

### ISSUE THREAD

**Issue by heniotierra** [airbnb/lottie-web#2210]
Hi,

I'm having troubles with the size of an animation when I zoom in or out the browser window. The expected behavior is resizing the animation, but it shouldn't be that much of a change from 100% to 90% zooming. I tried using the resize method after a window resize, but that didn't help. 

The behavior is inconsistent: sometimes, when I get to this screen with the zoom pre-set, the animation starts with the expected size, sometimes it starts with the size portraited in the second image below and then changes to the expected size, and sometimes it stays in that small size. If I zoom in or out with the animation on screen, it always gets small immediately. 

This is the result with 100% zooming:
![image](https://user-images.githubusercontent.com/4629295/84339823-a8383280-ab75-11ea-847f-cd4e70d749a1.png)

This is the result with 90% zooming:
![image](https://user-images.githubusercontent.com/4629295/84339852-b8501200-ab75-11ea-9999-6db004154e7c.png)

I'm using React, with lottie-web version 5.6.10. I tried this under Chrome and Firefox, with same results.

I'm starting the animation with:

    lottie.loadAnimation({
      container: animContainer.current, // the dom element that will contain the animation
      renderer: "svg",
      loop: true,
      autoplay: true,
      animationData: animationData.default, // the path to the animation json
      rendererSettings: {
        preserveAspectRatio: "xMidYMid slice",
      },
    });

**Comment by heniotierra** [comment]
Seems like I fixed it. For anyone with similar problem, however, I have no idea why the changes I did made it work.

The animation was being rendered inside an absolute positioned div directly inside a relative positioned div. I simply removed this absolute positioned div, and made the animation be rendered inside the relative positioned one.

**Comment by OscarGodson** [comment]
In case anyone comes across this again, this was an issue for us as well. We fixed it like this:

```js
animationInstance.addEventListener('DOMLoaded', (e) => {
    $("#feature-animation-container svg").attr("width", "100%");
    $("#feature-animation-container svg").attr("height", "100%");
})
```
