### ISSUE TITLE
Alpha Inverted Track Matte Problem

### ISSUE THREAD

**Issue by ision-industries** [airbnb/lottie-web#2217]
** Chrome
**After Effects Version: 16.1.3

I am working on a project that is using some shape layers as Alpha inverted Mattes and I am aware that Alpha Inverted track mattes are a supported feature. Although upon rendering and testing the animation I am getting this "blur" or "feathered" issue around the edges. (See Screenshot)

<img width="810" alt="Rounded chat bubbles a inv matte feathering" src="https://user-images.githubusercontent.com/58711145/85930118-a1a0ff00-b887-11ea-9919-629df7048b26.png">

My project is set up with only shape layers and parenting. What would be the cause of the feathering blur around the edges? Check the project file 

[Alpha Inverted Matte Project.aep.zip](https://github.com/airbnb/lottie-web/files/4841101/Alpha.Inverted.Matte.Project.aep.zip)

**Comment by bodymovin** [comment]
Hi, can you post this issue in the lottie-ios repository?
I've reached the devs to look into it.
