### ISSUE TITLE
How to get the updated text from a text layer

### ISSUE THREAD

**Issue by aenfr** [airbnb/lottie-web#2218]
Hi fellows!

I'm using the API to alter a range selector by listening to the X coordinates of the mousemove event. This is made by creating a Slider Control in the selector layer and mapping the start and end position of it to the slider bar. Everything works fine.

At the same time, I have a text layer with a couple of clamped values (1-250) mapped to the Slider Control defined above and it works great.

Now I want to get the current clamped value that is being updated in the text layer because of the Slider Control.

How can I read those values?

Thanks in advance!

**Comment by bodymovin** [comment]
Hi, what do you mean by getting the current clamped value? Do you need to read the text layer?

**Comment by kudanai** [comment]
Closing this issue as stale. Please re-open if you're still having issues
