### ISSUE TITLE
Background image missing in updated animation

### ISSUE THREAD

**Issue by cookievscupcake** [airbnb/lottie-web#2220]
* **Browser and Browser Version:**
Google Chrome V 78.0.3904.97 

* **After Effects Version:**
After Effects 2020 17.1.1
Bodymovin 5.6.10 (old animation used a previous version)

**What did you do? Please explain the steps you took before you encountered the problem.**
I created an animation a couple of months ago and had no issues. However, a revision was requested to change the color of a stroke. That part is fine, but now the (.ai file) background is not showing in the Lottie preview or editor or dev environment. PNG will work if allowed to rasterize in settings, but it loses transparency, which is very important for the face and neck area. It has a disclaimer it will not work with .ai files, but I'm not sure how it worked out in the earlier version.
![image](https://user-images.githubusercontent.com/48743391/86054219-5de0fd80-ba1f-11ea-8a85-1e57a3da3698.png)

The json file from the earlier animation version with an .ai file still works if I put it in preview now.

**What did you expect to happen?**
For the .ai file to show in the preview or to have a .png with transparency. Is there a setting option that will allow me to export like I did with the earlier version? Is there a workaround that will achieve that result?
![image](https://user-images.githubusercontent.com/48743391/86054387-aef0f180-ba1f-11ea-9117-aef3524f015e.png)

**What actually happened? Please include as much _relevant_ detail as possible.**
Background layer is missing or is required to be a non-transparent .png.
![image](https://user-images.githubusercontent.com/48743391/86050327-53236a00-ba19-11ea-98c8-4228feb33001.png)

Thank you!

**Comment by bodymovin** [comment]
Hi, not sure exactly what the issue is. ai layers should work.
Where do you get that disclaimer?

**Comment by cookievscupcake** [comment]
Hello, thanks for taking a look at my post! 

Maybe my export settings are wrong. I've experimented with a few and I saw the .ai layer text here.
![image](https://user-images.githubusercontent.com/48743391/87464607-01620e80-c5d9-11ea-9e99-23f6aacd2e59.png)

Is there an ideal export setting for exporting out the .ai layer or a transparent png? I am not sure what my settings were  before updating the plugin.

**Comment by cookievscupcake** [comment]
I half-way solved the problem and decided to make a follow-up comment, in case it gives a clue to the problem.

I exported both together my png and ai layer of the pink window overlay and now the png retains its transparency in the Lottie editor. The ai layer itself does not work, but if exported without, the png becomes opaque. 
![image](https://user-images.githubusercontent.com/48743391/88107037-10facd80-cb6c-11ea-96b3-7c127f64b825.png)

Unfortunately, my png transparency trick doesn't carry through when brought into our iOS app, so we are still exploring solutions.

**Comment by cookievscupcake** [comment]
Fixed by exporting with obsolete PNG along with AI layer, and then removing PNG manually from JSON file. AI layer will then work correctly.
