### ISSUE TITLE
different browsers different animation performance

### ISSUE THREAD

**Issue by mjuniquecode** [airbnb/lottie-web#2221]
**Tell us about your environment**
WIN 10, Catalina
* **Browser and Browser Version:**
Newest: Chrome, Firefox, Safari
* **After Effects Version:**
Newest one
**What did you do? Please explain the steps you took before you encountered the problem.**
I've created scroll based animation (quite big one - 780 frames) During testing i found out that in different browsers and OS i get different performance results:

Windows 10:
Chrome - okeish performance but visibile lagging (average 15-8 frames per second)
Firefox - "butter" smooth (average 55 frames per second)

macOS:
Chrome - "butter" smooth ( 55 - 58 frames per second)
Firefox - visible lagging
Safari - unusable for most of the animation (last 250 frames were fine)

**What did you expect to happen?**
Consistent performance across devices 

animations setting:

`this.animationSettings= {
  container: this.$animationContainer[0],
                renderer: 'svg',
                loop: false,
                autoplay: false,
                rendererSettings: {
                    clearCanvas: false,
                    imagePreserveAspectRatio: 'xMidYMid meet',
                    viewBoxOnly: false,
                    progressiveLoad: false, // Boolean, only svg renderer, loads dom elements when needed. Might speed up initialization for large number of elements.
                    hideOnTransparent: true //Boolean, only svg renderer, hides elements when opacity reaches 0 (defaults to true)
                }
            };`

Other thing is that if i switch renderer to 'html' or 'canvas' i am getting some weird shapes and masks... Could it be that this is an issue with animation itself ? Unfortunately i can not share the animation data due to legal reasons.

Cheers

**Comment by bodymovin** [comment]
Hi, it's difficult to debug without the animation.
Can you create a similar example that doesn't breach any legal commitments?

**Comment by JannikGM** [comment]
As this issue is aging quickly, and can't be reproduced easily, I think that it should be closed until there's an actual case to reproduce it.
That isn't to say that this problem doesn't exist, but as it stands, the issue is simply impossible to "resolve".
