### ISSUE TITLE
The shape line is shaking on ios devices

### ISSUE THREAD

**Issue by CellularDoor** [airbnb/lottie-web#2223]
![issue screenshot](https://user-images.githubusercontent.com/67799840/86489171-28644900-bd6c-11ea-97a7-970dc47e9a1d.PNG)

**Tell us about your environment**

* **Browser and Browser Version:**
Chrome 83.0.4103.116
* **After Effects Version:**
16.1.3

**What did you do? Please explain the steps you took before you encountered the problem.**
I need the graph to be animated - the gradient colored line that grows about 1-2 seconds (trim path). I did the animation, exported the .json file and it worked perfectly in a web browser and android device as well but when I play the animation at ios device this line becomes shaking. That is how it looks https://drive.google.com/file/d/1NDUpLBiXVpqF6xKpiwBKyGwK42sxp0G5/view?usp=sharing

None of the unsupported features were used in the project, here it is https://drive.google.com/file/d/10XWgtFcxF328hPYDsk7OSFmhgcqoLfj5/view?usp=sharing

That's how it appears (please use ios device)
https://lottiefiles.com/share/4PvGQw

**What did you expect to happen?**
I want this line to grow smoothly at all devices.
 
**What actually happened? Please include as much _relevant_ detail as possible.**
I assumed that my AE version conflicts with Bodymovin extension, so I've sent the .aep file to my friend and asked him to export .json file (he has different versions of AE and Bodymovin) - it doesn't help. 
I figured out that the animation plays ok where the line is straight and even if the trim path is animated, but once I add bezier curves to the path it becomes shaking at ios devices.
I tried to install the latest version of Bodymovin but it didn't work. (I updated to 5.7.0)

I apologize for my grammar.

I'd appreciate any suggestions! 

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/file/d/10XWgtFcxF328hPYDsk7OSFmhgcqoLfj5/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, if you a re using the lottie-ios player, can you post the issue in their repository?

**Comment by CellularDoor** [comment]
> Hi, if you a re using the lottie-ios player, can you post the issue in their repository?

Oh sure, it's done!
