### ISSUE TITLE
lottie.resize() documentation

### ISSUE THREAD

**Issue by kirillSkorodelov** [airbnb/lottie-web#2230]
Hi Hernan, are there any documentation or examples on lottie.resize()  function? I can't find anything I can use. The idea is to use this function to resize an animation instance depending on different conditions. Tried to use viewBoxSize, but couldn't make it work. Thanks a lot in advance.

**Comment by bodymovin** [comment]
Hi, the resize method is something you need to call if you are using the html or canvas renderers in order for them to redraw correctly.
Not sure what you need to do, but using transforms on the svg element, or modifying the viewBox value of the svg element are possible solutions for this as well.

**Comment by kirillSkorodelov** [comment]
Got it, many thanks! Yes, adding a class to svg element and and then changing it with the style.transform does the trick. Thank you!
