### ISSUE TITLE
How can I convert json animation from after effect, to Animated vector drawable to use in android studio

### ISSUE THREAD

**Issue by bethelchimaroke** [airbnb/lottie-web#2241]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, there is an exported with limited features on the bodymovin plugin for after effects
or you can use this script as well
https://github.com/bodymovin/bodymovin-to-avd
