### ISSUE TITLE
Delay to play Lottie animation on Hover

### ISSUE THREAD

**Issue by clementtwobirds** [airbnb/lottie-web#2245]
**Tell us about your environment**
Mac OS Catalina 10.15.5

* **Browser and Browser Version:**
Chrome, Firefox, Edge

* **After Effects Version:**
Adobe CC 2020

**What did you do? Please explain the steps you took before you encountered the problem.**
The animations are fine, it's working as it's suppose to do.
The issue is while playing in the browser (any of them other than Safari).

**What did you expect to happen?**
As the user is hovering the 3 birds on the "How we proceed" section, the animation is suppose to play straight away where ATM it's delayed by less than a second. 

**My question**
How can I get read of this delay?

**Website link**
https://twobirds-6eabe760798f79547441b6cc09089c.webflow.io/?fbclid=IwAR1zq2Ux9FW2rhSuZWgFRuwjdzNiBLDGBs0584xqc4gkaa1KZQyqCnQk3Vw

**Comment by bodymovin** [comment]
Hi, I downloaded the animation and I don't see anything strange.
This looks more of an issue on the hover implementation than the lottie-web library itself.

**Comment by clementtwobirds** [comment]
Hi @bodymovin , thanks for you answer.
Have you ever encounter this problem? and/or know a solution for it?
