### ISSUE TITLE
How to delay lottie playback

### ISSUE THREAD

**Issue by wyfang** [airbnb/lottie-web#2246]
I don't know much about this programming, so can someone help me? Now open the web page, it will automatically play the animation. I want it to play 5 seconds after I open the webpage, how should I modify this code:

```
var animation = bodymovin.loadAnimation({
  container: document.getElementById('glint'),
  renderer: 'svg',
  loop: false,
  autoplay: true,
  path: 'img/lottie/glint.json'
})
```

**Comment by oronevron** [comment]
```
setTimeout(() => {
  var animation = bodymovin.loadAnimation({
    container: document.getElementById('glint'),
    renderer: 'svg',
    loop: false,
    autoplay: true,
    path: 'img/lottie/glint.json'
  })
}, 5000)
```

**Comment by abhi16z** [comment]
I am not aware of delaying the animation programmatically but i have a workaround. you can keep an image placeholder for the lottie file(screenshot of lottie maybe) and replace it with lottie when you have to start the animation.

**Comment by bastiaanv** [comment]
I am a bit late to the party maybe, but I use this as the solution:

```js
const animation = lottie.loadAnimation({
  container: document.getElementById('glint'),
  renderer: 'svg',
  autoplay: false,
  loop: false,
  path: 'img/lottie/glint.json',
});

setTimeout(() => {
  animation.play();
}, 1000);
```

**Comment by wyfang** [comment]
> 我参加聚会可能有点晚了，但我用这个作为解决方案：
> 
> ```js
> const animation = lottie.loadAnimation({
>   container: document.getElementById('glint'),
>   renderer: 'svg',
>   autoplay: false,
>   loop: false,
>   path: 'img/lottie/glint.json',
> });
> 
> setTimeout(() => {
>   animation.play();
> }, 1000);
> ```

Thanks a lot for the answer, I seem to have solved the problem, it was my fault forgot to close it.
