### ISSUE TITLE
Bodymovin extension window is a blank screen 

### ISSUE THREAD

**Issue by aebegins** [airbnb/lottie-web#2247]
Using Google Chrome Version 84.0.4147.89 (Official Build) (64-bit)
Using After Effects CC 2017 

I've downloaded the Bodymovin extension to export the Ai illustration but the extension window is just a blank window as seen in the image, so I'm unable to export my files :( 

![image](https://user-images.githubusercontent.com/68935815/88752923-96463980-d18d-11ea-81a1-209517af6cb0.png)

I first tried it with my existing Ae project file that did not contain vector layers so I thought the problem was that my layers were not vector layers. So I downloaded a file with vector layers but it still did not work.

**Comment by bodymovin** [comment]
Hi, unfortunately AE 2017 is not working with the latest builds.
Can you try updating AE or using an older version of Bodymovin?

**Comment by aebegins** [comment]
> Hi, unfortunately AE 2017 is not working with the latest builds.
> Can you try updating AE or using an older version of Bodymovin?

I see, thanks for the reply! Which older version of Bodymovin would be compatible with AE 2017?
