### ISSUE TITLE
bodymovin render failed 

### ISSUE THREAD

**Issue by sophiayang99** [airbnb/lottie-web#2251]
- MacOS Catalina 10.14.5
- using Adobe After Effects 2020 Version 17.1.2
- Used trapcode form to create particle field animation for website 

**What did you expect to happen?**
Export particle field as .json to upload to webflow

- No render preview in bodymovin plugin 
- Render completed as .json, but nothing actually shows up after

it shows up like this in webflow after being exported: 
<img width="182" alt="Screen Shot 2020-08-02 at 2 15 39 PM" src="https://user-images.githubusercontent.com/53102760/89129341-ad0cc900-d4ca-11ea-864f-ab8ae1ab395b.png">

but it should look like this 
<img width="743" alt="Screen Shot 2020-08-02 at 12 31 17 AM" src="https://user-images.githubusercontent.com/53102760/89129350-bb5ae500-d4ca-11ea-8dd4-d3d31d676786.png">

**Comment by bodymovin** [comment]
Hi, unfortunately, there are very few effects supported by the library
https://github.com/airbnb/lottie-web/wiki/Effects
