### ISSUE TITLE
Track Matte isn't work well on my Lottie file

### ISSUE THREAD

**Issue by farshiddarvishi** [airbnb/lottie-web#2253]
**Tell us about your environment**
macOS Catalina 10.15.4

* **Browser and Browser Version:**
Chrome 84.0.4147.105 (Official Build) (64-bit)

* **After Effects Version:**
17.0.1 

**What did you do? Please explain the steps you took before you encountered the problem.**
I have a motion that it builds with the track matte mask and it works well in After Effects.

**What did you expect to happen?**
Get the Lottie file exactly the same as the motion on After Effects

**What actually happened? Please include as much _relevant_ detail as possible.**
As you can see on the below link my Lottie file is completely broken. I did many searches and do many solutions but I still have the problem, is there anyone to help me to find what is the problem?

**Please provide a download link to the After Effects file that demonstrates the problem.**
Lottie: https://lottiefiles.com/share/Zg5GUs
AE: https://drive.google.com/file/d/1ORo8xpexAT5rUHDfCZY90K4ZhtP0ina-/view?usp=sharing

Thanks,
Farshid

**Comment by farshiddarvishi** [comment]
Is there anyone who can help me?

**Comment by farshiddarvishi** [comment]
I have the problem still, can anyone help me?

**Comment by henriqrossatto** [comment]
Hi @farshiddarvishi. Try to invert the position of shapes and layer on letter. Instead the path alpha matte the letter, adjust for letter alpha matte the path.

**Comment by henriqrossatto** [comment]
Check the letter a and f in this file
[Rafiji.zip](https://github.com/airbnb/lottie-web/files/5045461/Rafiji.zip)

**Comment by farshiddarvishi** [comment]
Ahhh! Great @henriqrossatto, thanks a lot for spend time for me :)
