### ISSUE TITLE
Scene > 5000 items

### ISSUE THREAD

**Issue by djteasdale** [airbnb/lottie-web#2263]
Hello,

I know basic html & css, so I'm wondering if there is another way I can go about this.

I have a scene which is 1920x1080, built in illustrator. I then converted everything to shapes in Ae.
Bare in mind only a few things in the scene are animated.
I then rendered it with bodymovin and ran it through my website.
However in VS code I got a message saying "for performances issues the .json file has been limited to 5000 items." ![Annotation 2020-08-12 222212](https://user-images.githubusercontent.com/55861045/90069509-4cf7fd00-dcea-11ea-85a1-6e137ad58025.png)

Also when running the website it is noticably slow.

Am I approaching this the right way?
I have optimised the scene to as little shapes as possible.
Would it be better to separate the animated bits (.json file) on top of the static scene (.jpeg)?

Any help would be appreciated, I struggle to find information about this.

Thanks,

Dan

**Comment by bodymovin** [comment]
hi, yes, you probably want to have two separate overlapping layers if you have many elements and only some of them animated.
Perhaps instead of a jpeg, you can use a static svg file so it doesn't loses quality.
You can produce that svg by exporting the static layers with bodymovin, then previewing it in bodymovin too and selecting Take Snapshot. That will provide you with an svg file.

**Comment by djteasdale** [comment]
Not sure if I'm doing this right but I hid all the animated layers, then took a Snapshot. 
The .svg file was 1.8mb, whereas if I export as an .svg from illustrator its only 413kb.
I also ran that .svg through the optimizer you recommended, so its now down to 350kb.

So now I have my .svg file and data.json. How do I put them on top of each other? 
Do I use position: absolute and transform: translate to manually align them up?
![image](https://user-images.githubusercontent.com/55861045/90509060-a8921280-e150-11ea-925c-058483db062d.png) 
![image](https://user-images.githubusercontent.com/55861045/90510199-71bcfc00-e152-11ea-8fcb-1f423939bd49.png)

**Comment by bodymovin** [comment]
position absolute with top: 0 and left: 0 should put one on top of the other.

**Comment by djteasdale** [comment]
Thanks for your help. Performance is much better now.
Original data.json file was >2mb. Now the combined Static-bg.svg & data.json (only animated layers) file comes to 540kb.

Also the CPU performance is much better while the website is running: 
![image](https://user-images.githubusercontent.com/55861045/90519615-2e698a00-e160-11ea-9e5b-bfc44aca24a7.png)
