### ISSUE TITLE
Grey Rectangle Layers...

### ISSUE THREAD

**Issue by curryhobo** [airbnb/lottie-web#2264]
![inifinitemindsCOMP03_1](https://user-images.githubusercontent.com/68454700/90089418-347de780-dcd6-11ea-874f-a85b650e8da9.gif)

@Hernan-Dev  

**windows 10**

* **Brave Browser**
* **After Effects 2019:**

**I have created a looping animation from many dozens of shape layers with masks, and a huge amount of animated values, effects, attributes...   was sorta hoping it would the bodymivin plugin would pop out an svg that i could open in a browser and toy with a bit of html... this is for a client who has commissioned me to design the emblem and animation.**

**Many of the layers were just grey rectangles and  i think perhaps some of the animated values lost**

*i will send you project files when i figure out why aftereffects isnt loading...*
**how do i send you aep?...**

**Comment by galipmedia** [comment]
Did you tick the little box in the AE to make sure it renders as vector not image?

**Comment by bodymovin** [comment]
Hi, lottie doesn't support all effects and properties of After Effects, but if you share the .aep I can check what is not working.

**Comment by curryhobo** [comment]
> Hi, lottie doesn't support all effects and properties of After Effects, but if you share the .aep I can check what is not working.

how do i send you .aep ?

**Comment by bodymovin** [comment]
@curryhobo can you attach it here?

**Comment by curryhobo** [comment]
> @curryhobo can you attach it here?

" We don't support that file type. Try again with a GIF, JPG, PNG..... "

**Comment by curryhobo** [comment]
> @curryhobo can you attach it here?

maybe a zip file would work..
[infiniteminds animation bu - Copy.zip](https://github.com/airbnb/lottie-web/files/5676006/infiniteminds.animation.bu.-.Copy.zip)

**Comment by bodymovin** [comment]
@curryhobo it looks like the main issues are related to merge paths that are not supported by the players. Adjustment layers are not supported, but I'm not sure if they are affecting the animation.
I haven't checked beyond that, but if you manage to remove the merge paths I can take another look if it still doesn't work.

**Comment by curryhobo** [comment]
@hernan 
ok, i will continue to plar with it, I dont have a super clear understanding of how merge paths work in after effects..

**Comment by curryhobo** [comment]
> @curryhobo it looks like the main issues are related to merge paths that are not supported by the players. Adjustment layers are not supported, but I'm not sure if they are affecting the animation.
> I haven't checked beyond that, but if you manage to remove the merge paths I can take another look if it still doesn't work.

how do i "remove merge paths" ?

**Comment by bodymovin** [comment]
merge paths are shape properties added to your shape layers. Probably AE documentation will be more detailed than my explanation about them.
