### ISSUE TITLE
Console Log Error: <rect> attribute transform: Expected number, "matrix(NaN,NaN,NaN,NaN,…".

### ISSUE THREAD

**Issue by jasenmpeterson** [airbnb/lottie-web#2267]
I'm having something strange happen, the animation works fine in the demo but when I try to bring it into say Codepen: https://codepen.io/meatjasenmp/pen/NWNxYKZ I get the error above. I also tried to bring it into the site I'll be using it on to make sure it wasn't a fluke and I get the same issue.

The json file can be found here: https://www.dropbox.com/s/y5waffyg1fm6mrj/data.json?dl=0

[TEL_homepageAnimation_v01.aep.zip](https://github.com/airbnb/lottie-web/files/5070436/TEL_homepageAnimation_v01.aep.zip)

Any insight would be much appreciated.

**Comment by jasenmpeterson** [comment]
I can create an additional file and copy all the code over and it works but it doesn't work if I copy that over to codepen. 

AE file is attached.
[TEL_homepageAnimation_v01.aep.zip](https://github.com/airbnb/lottie-web/files/5070434/TEL_homepageAnimation_v01.aep.zip)

**Comment by cruiser12** [comment]
Hello, the same happens with my lottie file and the latest player version.  
Is there any progress on this?
Kind regards

**Comment by bodymovin** [comment]
@cruiser12 hi can you share the .aep and a link with the implementation?

**Comment by hristov296** [comment]
Hello, I am running into the same issue.
I don't have a .aep file, I'm using json.
This is the website - [click](https://demos.supersait.bg/luxdigital/)

**Comment by oDaShuTz** [comment]
the same happens to me....

**Comment by oDaShuTz** [comment]
![image](https://github.com/airbnb/lottie-web/assets/39146254/0de5b1f9-55ea-4aa3-9719-14f89cc3524b)

**Comment by nicomollet** [comment]
I had more or less the same javascript errors.

I switched the lottie player "renderer" from `svg` to `canvas`, and it helped a lot: no more JS errors and lower CPU load.
