### ISSUE TITLE
First layer in AE not exporting

### ISSUE THREAD

**Issue by apoorvasidhu28** [airbnb/lottie-web#2268]
Hi @bodymovin 

I'm using AE CC 2020 and uploading the json file to webflow on a chrome browser (up to date)

I created all the vector layers in illustrator, brought them to AE, converted them to shape layers, animated them. Created text layers in AE for the text and created the background white box in AE. This layer comes first, after which the Illustrator layer (filter calls UI) comes. as seen below 
<img width="537" alt="Screenshot 2020-08-15 at 12 10 32 PM" src="https://user-images.githubusercontent.com/69709283/90307006-67032c80-def0-11ea-8c19-47d73e02a4e0.png">

--> This is how the asset looks in AE
<img width="620" alt="Screenshot 2020-08-15 at 12 01 55 PM" src="https://user-images.githubusercontent.com/69709283/90306950-d88eab00-deef-11ea-815f-ff45e236ad36.png">

--> This is how it looks after the render on webflow
<img width="623" alt="Screenshot 2020-08-15 at 12 06 56 PM" src="https://user-images.githubusercontent.com/69709283/90306961-ecd2a800-deef-11ea-82d2-6562ffb158c3.png">
^
The white box in the background is missing.

[Here is the AE link: ](https://drive.google.com/drive/folders/1qgey7fbP32DdlWjgwC03h66QWonC2UKE?usp=sharing)

@Hernan-Dev

**Comment by bodymovin** [comment]
Hi, the drop shadow from layer styles is not supported.
You can try with the drop shadow effect that should work correctly.

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
