### ISSUE TITLE
Help getting images working in node-lottie

### ISSUE THREAD

**Issue by galipmedia** [airbnb/lottie-web#2269]
This is a node-lottie issue but I thought I would also ask here as someone might know why this is happening. It works well when there are no images but the lottie animation gets isLoaded: false if images are included.
https://github.com/friday/lottie-node/issues/8

**Comment by maximeallanic** [comment]
Hello, 
I am using Lottie-node and therefore lottie to automatically export the projects to video. But this bug limits me in the project, I just can't use lottie-node which will save me a lot of time compared to pupeteer-lottie. I would like to advance in this bug resolution. I went over the code many times without finding a solution. 
Thank you.

**Comment by razvanmitre** [comment]
Fixed in https://github.com/friday/lottie-node/pull/14
