### ISSUE TITLE
Levels not exported

### ISSUE THREAD

**Issue by susana3** [airbnb/lottie-web#2272]
Hello! I used bodymovin to create a lottie animation but I need some help because the result was different than the one I was expecting. **To summarize, I used Levels in After Effects but the feature did not appear in the exported lottie.**

**After Effects Version:** 17.1.2

I created some shapes and applied them Gaussian Blur. Then, I adjusted the Levels and the result in After Effects was this:

<img width="1327" alt="Captura de Pantalla 2020-08-18 a la(s) 8 28 39 p  m" src="https://user-images.githubusercontent.com/55750528/90581693-7a80f280-e191-11ea-87d8-fd333b28eb78.png">

However, when I used the Lottie preview tool to visualize the output, this appeared:

<img width="758" alt="Captura de Pantalla 2020-08-18 a la(s) 8 33 01 p  m" src="https://user-images.githubusercontent.com/55750528/90581912-0c88fb00-e192-11ea-9899-d2d7fed0b49d.png">

I am using Chrome (version 84.0.4147.125).

Could I do something to achieve the expected output? 

Thank you so much!

**Comment by bodymovin** [comment]
Unfortunately, I can't think of an alternative.

**Comment by susana3** [comment]
It's ok, thank you for your help :)
