### ISSUE TITLE
this.elements[i].destroy() is not a function

### ISSUE THREAD

**Issue by WartClaes** [airbnb/lottie-web#2275]
**Tell us about your environment**
It happens on all browsers and all os-es

**What is the issue?**

When using Lottie we encountered a CSP issue when loading animations. This happend because Lottie uses `eval()` to render certain effects. The easy fix then was to make the switch to Lottie light.

Once this CSP issue was resolved, we got a new error when the animation was destroyed:

https://github.com/airbnb/lottie-web/blob/bf8217770e40cedad1f20ed52b24eddea9b82b77/player/js/renderers/SVGRenderer.js#L142-L155

```bash
this.elements[i].destroy() is not a function
```

The error occured because the elements array was not properly constructed and some items just contained the value `true` and `(true).destroy()` triggers the error above.

When looking for the reason why the element contained `true` we noticed that `new SVGEffects()` uses the EffectManager. 

https://github.com/airbnb/lottie-web/blob/a9a82511344a46906a3c17121a019b1ef860b5e6/player/js/elements/svgElements/SVGEffects.js#L30-L33

This function still exists in Lottie light, but is empty. Lottie crashed on this and catches the error so it is not shown immediately. The browser error happens when destroying and not in the initial loading of the animation.

**Solution**

By preventing that we add any effects in Lottie light, the animation is loaded in the same way as before, but doesn't crash when destroying.

I already created a PR (#2234) a while ago but I'm not sure if I should have made an issue first.

**Comment by WartClaes** [comment]
Here is a file with the issue:
https://assets5.lottiefiles.com/packages/lf20_gmgQQi.json

**Comment by WartClaes** [comment]
@bodymovin Any new about this one? It would be nice to have it fixed :-)

**Comment by vitaliiburlaka** [comment]
@bodymovin 

> Hi, can you share an example of an animation that triggers this error?
> I'm trying to reproduce it with the lottie_light.js player and I can't.

@bodymovin I was able to reproduce the issue in my project using the file from @WartClaes.
Would appreciate any updates on that as we're facing similar issue in prod.

**Comment by bodymovin** [comment]
@WartClaes that animation has an effect appliead to a layer. lottie-light is not expecting effects, and that's why it breaks.
Do you have a use case where you need animations with effects played with the light version?

**Comment by WartClaes** [comment]
Now we have removed them from the animations but in the end it would be nice. 

But still it remains the case that it could work perfect without throwing a somewhat hidden error.
I get that the effects won't be applied and I can totally live with that, but it would be nice that we can still see the rest of the animation (which is possible with the fix in the linked PR)

**Comment by WartClaes** [comment]
@bodymovin can you give your opinion on this?

**Comment by vitaliiburlaka** [comment]
@bodymovin the issue for our project was that the Lottie-web calls `eval` without the proper try/catch and possibly without check if  there are expressions to not.

<img width="905" alt="lottie-web-eval" src="https://user-images.githubusercontent.com/10799630/97544181-870f9b80-19c9-11eb-8ccb-96405f5b98dd.png">


With the strict `Content-Security-Policy` that does not allow usage of `'unsafe-eval'` it was just throwing that vague `this.elements[i].destroy() is not a function` error

**Comment by bodymovin** [comment]
@vitaliiburlaka `eval` should be invoked only if the there are expressions on the animation. Regarding try/catch, every frame is rendered wrapped in a try / catch statement to prevent errors propagating upwards, so if I'm not wrong, that shouldn't be the issue.

**Comment by bodymovin** [comment]
@WartClaes I'll see what I can do to prevent this.

**Comment by WartClaes** [comment]
@bodymovin is this fixed in 5.7.4? Because I just tested it and I still get the same error?

**Comment by bodymovin** [comment]
@WartClaes version 5.7.5 should have it fully fixed

**Comment by DAAI093** [comment]
> @WartClaes version 5.7.5 should have it fully fixed

i use the version 5.7.5 ，however i still encounter this problem,  my chrome version is 87.0.4280.88, when i use firefox it prompt that "Content Security Policy: The page's settings blocked the loading of a resource at eval ("script-src"). lottie.js"

**Comment by Dar0n** [comment]
@bodymovin 
Sorry to brining this up again, but I have just updated to 5.7.5 and still getting the error "TypeError: this.elements[i].destroy is not a function". Interestingly, I attach animation to scroll position, and it crashes not immediately (going to the end of animation) but on the way back, when scrolling to the top.

**Comment by Dar0n** [comment]
@bodymovin 
I am sorry to bring this up again, but it happens in our project as well.
However, the errors point to react-lottie package. This is weird, because while the package is part of our project, no component using it is currently loaded and rendered. But still I am getting this error. 
I may assume that react-lottie uses an outdated version of lottie-web, but I don't understand why would it even interfere, when no <Lottie> component is rendered using it.

**Comment by razbensimon** [comment]
still happening (also with `react-lottie`) while our app has a strict Content-Security-Policy... 
Is there any solution?

**Comment by QuocVi1994** [comment]
你的信我已收到,我会尽快阅览并回复，谢谢你的来信！~

**Comment by wadehammes** [comment]
Happening with me, but only when I am trying to move from Yarn to PNPM (Latest Next.js). My yarn installation works fine, but this error happens when using PNPM.

**Comment by ConardLi** [comment]
May I ask if this error will affect the normal use of the program after strict `Content-Security-Policy` is enabled? Because it is difficult for our project to switch to Lottie light version.

**Comment by oguz3** [comment]
i have opened a [pull request](https://github.com/airbnb/lottie-web/pull/2875) for this. 
This does not play the animation, but prevents the application from throwing errors.
that's enough for my scenario

**Comment by Donkfather** [comment]
The issue for me happened in a Chrome extension when moved to MV3. It was because of the Content-Security-Policy which didn't allow unsafe-eval.

**Comment by NilsBaumgartner1994** [comment]
Still having this issue in my Expo app
