### ISSUE TITLE
AE crashing everytime I convert

### ISSUE THREAD

**Issue by designdesign11** [airbnb/lottie-web#2279]
I am using two different After Effects plugins right now, both convert AE compositions into .json. The first is LottieFiles and the second is Bodymovin.

The main problem I'm running into is AE crashes almost every time it tries to convert a composition using one of these plugins. And when it doesn't, the.json is unreadable.

I attached a couple error messages below.

Thanks again!

**Comment by bodymovin** [comment]
Hi, I only maintain the Bodymovin extension.
Can you share the project and AE version you are using?

**Comment by designdesign11** [comment]
> Hi, I only maintain the Bodymovin extension.
> Can you share the project and AE version you are using?

Hi, I can't share the project unfortunately

**Comment by kudanai** [comment]
Closing this issue for now since it's become stale. Please re-open if relevant or file a new one if you're still having issues using the more recent updates
