### ISSUE TITLE
Animation flickers with white rectangles in Chrome

### ISSUE THREAD

**Issue by enkztw** [airbnb/lottie-web#2286]
The bug appears only in Chrome also in Chrome Canary. It's hard to catch because it happens randomly. 
[Video](http://www.mediafire.com/file/fbwyr05du5kpjst/IMG_5655.MOV/file)
[Anim's data](https://lottiefiles.com/share/WWCDBY)

**Comment by enkztw** [comment]
Also i don't think there is a problem with animation's data because it also appears with other big animations

**Comment by enkztw** [comment]
#1635

**Comment by bodymovin** [comment]
Hi, I can't seep to reproduce the issue. Have you tried using the canvas renderer?

**Comment by enkztw** [comment]
> Hi, I can't seep to reproduce the issue. Have you tried using the canvas renderer?

Hi, Hernan. Yes, it's appears the most with the canvas renderer

**Comment by enkztw** [comment]
@bodymovin parent had a `will-change` property for opacity. May be it was the reason
