### ISSUE TITLE
Animation initializing without visibility

### ISSUE THREAD

**Issue by therilomizer** [airbnb/lottie-web#2288]
I'm working with multiple animations that are nearly identical in After Effects, and identical in their implementation on my site. However, one of the animations seems to initialize with the properties that make it visible. So there is a blank space in the div on page load, although it does appear normally after the event listener triggers the animation. EDIT: It doesn't actually appear normally when the mouseEnter triggers - the animation begins before it's visible, so it only becomes visible when the animation if halfway through.

![Screen Shot 2020-09-01 at 2 51 18 PM](https://user-images.githubusercontent.com/17524681/91910006-16ffc600-ec63-11ea-9304-8502e0235c2f.png)

In this screenshot the highlighted line is the element of the initialized SVG that seems to be missing properties. The highlighted group doesn't have opacity or transform elements, and several of the sub-elements are also set to "display: none". Inside the "diamond_fan" div, you can see that the next, almost identical SVG is initialized with all of the proper visibility properties, as well as its sub-elements.

My animations script looks like this.

```
var heartFan = document.getElementById('heart_fan'),
    diamondFan = document.getElementById('diamond_fan'),

var heartFanAnim = bodymovin.loadAnimation({
  container: heartFan, // Required
  path: 'js/heartFan.json', // Required
  renderer: 'svg', // Required
  loop: false, // Optional
  autoplay: false, // Optional
  rendererSettings: {preserveAspectRatio: 'xMidYMid slice' ,}});

var diamondFanAnim = bodymovin.loadAnimation({
  container: diamondFan, // Required
  path: 'js/diamondFan.json', // Required
  renderer: 'svg', // Required
  loop: false, // Optional
  autoplay: false, // Optional
  rendererSettings: {preserveAspectRatio: 'xMidYMid slice' ,}});

function playForward(animName) {
  animName.setDirection(1);
  animName.setSpeed(1.3);
  animName.play();}

function playBackward(animName) {
  animName.setDirection(-1);
  animName.setSpeed(2);
  animName.play();}

heartFan.addEventListener("mouseenter", function(){playForward(heartFanAnim)});
heartFan.addEventListener("mouseleave", function(){playBackward(heartFanAnim)});
diamondFan.addEventListener("mouseenter", function(){playForward(diamondFanAnim)});
diamondFan.addEventListener("mouseleave", function(){playBackward(diamondFanAnim)});
```

Could this be the result of a bug in the JSON file for the animation? Why would Lottie produce this bug in one animation but not in one that's almost identical, exported in exactly the same way?

**Comment by bodymovin** [comment]
Hi, can you share a link with your implementation?

**Comment by therilomizer** [comment]
[Here's a link to the div in question](http://www.doomcrop.com/#heart_fan). Thank you!

**Comment by bodymovin** [comment]
It looks like you have some errors on the expressions and that's why it doesn't render.
It's probably related to this expression, but I can't be sure without the .aep.
`comp('2 spades').layer('2').transform.scale;`
If I understand that expression correctly, it is pointing to another composition that is probably not included in the export. Can you check it?

**Comment by therilomizer** [comment]
I've got it working properly! I went in and replaced that expression in the
relevant comps with expressions that point to a comp local to the export. I
also had to turn off all Extra Comps in the Bodymovin export window to make
the exported json appear properly on the site. Thanks for your help!
