### ISSUE TITLE
please Help with an expression

### ISSUE THREAD

**Issue by Fr4nZ82** [airbnb/lottie-web#2292]
I used ae cursor control to set a number that represents the number of images that in a range of time should fade out, one after another. For example, if images are 4 then at 25% of the time the first must fade out, revealing the second.
I have already used color control and it works fine with the result lottie animation... but the expression on opacity does not works, i see only the first photo and opacity never change

the espression, applied to opacity of each photo, is:
```
var startFadeAt = thisComp.duration/thisComp.layer("Control").effect("numerofoto")("Cursore")*1 //*1 because is the photo number 1
var endFadeAt = thisComp.duration/thisComp.layer("Control").effect("numerofoto")("Cursore")*1+0.4
if(time > startFadeAt){
  if(time < endFadeAt) 100-((100/0.4)*(time-startFadeAt))
  else 0
} else 100
```

**Comment by Fr4nZ82** [comment]
it appears that "thisComp.duration" is not implemented, right? Any workaround?

**Comment by Fr4nZ82** [comment]
solved editing lottie_svg.js:
```
function initiateExpression(elem,data,property){
...
        elem.comp.frameDuration = 1/elem.comp.globalData.frameRate;
        elem.comp.compInterface.duration = elem.data.op * elem.comp.frameDuration // <-- this
        elem.comp.displayStartTime = 0;
...
```
not sure if is the right place, but it works!

**Comment by bodymovin** [comment]
wouldn't that only work if the op equals the real comp duration?

**Comment by Fr4nZ82** [comment]
I saw that op is the duration in frames of the animation .... I don't know if it can take on different values ​​because I don't know very well after effects

**Comment by kudanai** [comment]
closing this issue for now. Please feel free to re-open.

For more information on the Lottie format please refer to [community docs](https://github.com/lottie-animation-community/docs) or [LottieFiles docs](https://lottiefiles.github.io/lottie-docs/)
