### ISSUE TITLE
Lottie Help - Syncing multiple lottie animations

### ISSUE THREAD

**Issue by braedenmeck** [airbnb/lottie-web#2294]
Hey! Thanks in advance for your help!

I am trying to create depth in my home page by layering lottie animations using alpha transparency. My issue is that these animations need to be synced up to make the color transitions match. I can't seem to find a solution anywhere, although [this thread](https://github.com/airbnb/lottie-web/issues/288) may indicate that it's possible? Any help would be amazing!

My site:
https://braedens-blank-site-ae9439.webflow.io/

Thank you!

**Comment by dranitski** [comment]
@braedenmeck hey, do you have any success on syncing multiple lottie animations? Thanks in advance
