### ISSUE TITLE
Bodymovin won't preview render options

### ISSUE THREAD

**Issue by adatri95** [airbnb/lottie-web#2295]
Hey all,

I am trying to export a Json file from of an animation I created in the most recent AE CC version. When I open the bodymovin extension in After effects I am missing all of the options of files to render. How to I make them appear? It worked fine for me last week. 

Any help is appreciated.
Thank you!

@bodymovin 

<img width="614" alt="Screen Shot 2020-09-08 at 11 12 38 AM" src="https://user-images.githubusercontent.com/70970718/92507896-eff64680-f1c4-11ea-8ac4-3392f0742ed4.png">

**Comment by bodymovin** [comment]
Hi, how did you install the extension?

**Comment by adatri95** [comment]
I wasn't able to install it through the Adobe exchange so I downloaded the file and did it that way. But it seems that if I close everything down and restart my computer it works just fine. So I am not sure what the issue is but that seems to help.

**Comment by bodymovin** [comment]
ok, good to know that it got solved. Closing the issue.
