### ISSUE TITLE
What is there for web similar to Dynamic Animation Properties

### ISSUE THREAD

**Issue by pratikbendale** [airbnb/lottie-web#2299]
I have seen the documentation and I found there is a way to change color of animation dynamically or runtime
for IOS/Android ref following URL
http://airbnb.io/lottie/#/ios?id=setting-dynamic-properties

What is there for web-like ios/android
Please suggest 

@bodymovin

**Comment by bodymovin** [comment]
hi, are you looking for something like this?
https://github.com/bodymovin/lottie-api
