### ISSUE TITLE
Gradient Overlay

### ISSUE THREAD

**Issue by Petroni** [airbnb/lottie-web#2302]
Hi I'm currently trying to export an animation that has a gradient overlay on it, unfortunately it is picking up the gradient fill as I'm assuming the gradient overlay is not supported. The only issue is that when exporting from illustrator to after effects.. all the gradient data is being lost and the only way to make it look like the illustrator version is to apply a gradient overlay. Is there  a work around for this issue please? And if no, is it possible for future releases of bodymovin to support gradient overlays
![b3321048-0f36-43c5-b851-a7dc8218d663](https://user-images.githubusercontent.com/42549208/93345104-bcee2b80-f832-11ea-8078-38cfb6e387de.jpg)

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by Petroni** [comment]
Hi, Please find attached the 2 aep that have this gradient
[AEPs.zip](https://github.com/airbnb/lottie-web/files/5260401/AEPs.zip)

**Comment by Petroni** [comment]
Hi, any updates on this please?

**Comment by bodymovin** [comment]
Gradient Overlay from Gradient Styles is not supported unfortunately.
Only Gradient Fill from shapes are.
