### ISSUE TITLE
CC Particle World

### ISSUE THREAD

**Issue by WalidTouil** [airbnb/lottie-web#2305]
Hello , i'm rendering an animation with "CC particle World " and it render with a grey rectangle !
I've checked that this effect wasn't supported in 2017 ! 
I just want to know how can i modify the layers so i get rendered properly .

Here is a link for the ae file :  https://we.tl/t-7ufl2jrwnX
@bodymovin 

Best regards

**Comment by bodymovin** [comment]
Hi, unfortunately that effect is not supported by the library.
Very few effects are.
https://github.com/airbnb/lottie-web/wiki/Effects
