### ISSUE TITLE
Cannot load two (multiple) animations onto the same container and have the second (other) animation play

### ISSUE THREAD

**Issue by cdonley** [airbnb/lottie-web#2307]
**Tell us about your environment**

* **Browser and Browser Version:**
Chrome 85.0.4183.102
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**
Have the following code:
```
var params = {
		container: document.getElementById('lottie'),
		renderer: 'svg',
		loop: false,
		autoplay: false,
		name: 'start',
		path: 'data.json'
	};
    lottie.loadAnimation(params);
	
	params = {
		container: document.getElementById('lottie'),
		renderer: 'svg',
		loop: false,
		autoplay: false,
		name: 'punch',
		path: 'dataPunch.json'
	};
	lottie.loadAnimation(params);
	
	lottie.play('start');
	
	setTimeout(function()
    {
		lottie.play('punch');
    },  5000);
```

The goal is to have one container that can play multiple animation files sequentially/randomly

**What did you expect to happen?**
The "start" animation would play, followed by the "punch" animation

**What actually happened? Please include as much _relevant_ detail as possible.**
The "start" animation plays as expected, but nothing happens when the "punch" animation attempts to play. If you play "punch" first and then "start", "punch" will not play but "start" will. Only the animation in the first loadAnimation will be able to play

**Please provide a download link to the After Effects file that demonstrates the problem.**
[demo.zip](https://github.com/airbnb/lottie-web/files/5272629/demo.zip)

**Comment by iiifinal** [comment]
Or you can try to make a layer of component encapsulation animation so that two animations can be played at the same time

**Comment by bodymovin** [comment]
Hi, it seems to be working, but the second svg is pushed outside the container by the html document flow.
If you add a class to the svg and set it to position: absolute, top: 0; left:0; it should work
