### ISSUE TITLE
Audio export from after effects

### ISSUE THREAD

**Issue by tataclassedge** [airbnb/lottie-web#2308]
Can anyone please share the process of exporting audio asset included json from after effects via bodymovin plugin

**Comment by tataclassedge** [comment]
its now getting exported
I reinstalled the plugin

**Comment by henriqrossatto** [comment]
Hi @tataclassedge,

Did you get understand the process of exporting an audio and make it works?

I was testing this type of exportation but every time I render the file (I'm using 5.7.5) the render failed and appear a new comp inside my AE named "__bodymovin_copy".

I suppose that I have to export this new comp using the Render Queue with the Output Module "__bodymovin_sound_template_16".

But I don't have any clue how to make it works. Any thoughts @bodymovin?

Regards,
Henrique

**Comment by bodymovin** [comment]
@henriqrossatto hi, boydmovin should take care of exporting audios with the animation. What do you see when it fails?

**Comment by henriqrossatto** [comment]
![image](https://user-images.githubusercontent.com/30601233/104824386-edb98e00-582f-11eb-9c95-28253d76a191.png)
This is just happens when I add the settings 

- Audio
  - Enable
  - Rasterize Waveforms
