### ISSUE TITLE
Mouse-hover issue Lottiefile

### ISSUE THREAD

**Issue by Asim740** [airbnb/lottie-web#2314]
* **Version 85.0.4183.121 (Official Build) (64-bit):**
* **After Effects 2020 Version:17.0.6**

**I have created 6 circle animation for mouse hover, my client said that it works on scrolling but not working on mouse hover except number 1 animation.**

** I want it to work all as number 1 do?**

Link for lottiefiles that i have already uploaded: 

https://assets7.lottiefiles.com/packages/lf20_gnvvs3n3.json
https://assets7.lottiefiles.com/packages/lf20_o6kuz2tb.json

Video Example**https://pern-my.sharepoint.com/:v:/g/personal/asim_5981875_talmeez_pk/EeoB7wCwXH1KmY1DCK45jDcB7ImM-cLhS4NBm4G7T5Ecuw?e=xNYmbu**

**After Effects Source file link: https://pern-my.sharepoint.com/:u:/g/personal/asim_5981875_talmeez_pk/EQxjAAmSCsNPi0G5yTMlCrgBb3UIzmsh0ROeKL5tMu61HA?e=F4UsHo.**

**Comment by bodymovin** [comment]
Hi, this looks like it's related to your implementation, and not the library itself.
Perhaps if you share a link with the implementation, someone will be able to help.

**Comment by Asim740** [comment]
Hi, thank you so much for your reply, i think i sort out the problem. All
icons were not working fine,  except icon number one. Because icon number 1
layers were in the start of the comp. And for other icons i just moved comp
area. Now i have send icons to my client and he didn't respond this time. I
think issue has been resolved now.

**Comment by bodymovin** [comment]
good to know. closing the issue. reopen if necessary.
