### ISSUE TITLE
Quick Question - json to aep

### ISSUE THREAD

**Issue by dimograph** [airbnb/lottie-web#2322]
Hey Hernan, a question.

I have a Lottie animation, only .json file available and I need to incorporate this animation into a larger scale animation using after effects. Unfortunately there are no .aep source files for the little animation. 

Little animation: https://lottiefiles.com/9974-sign-up-icon

Is there a way to export .json code into After Effects as an animation?
Can the LottieFiles extension for After Effects solve this task? (I cannot install it right now unfortunately, but I will).

Mucho thanks

**Comment by bodymovin** [comment]
Hi, you should try the bodymovin extension that can import Lottie files to After effects
https://aescripts.com/bodymovin/
I think the LottieFiles extension doesn't have this feature yet
