### ISSUE TITLE
Exported the lottie with old format json and it is not showing up in web player, but works fine on mobile

### ISSUE THREAD

**Issue by taylorling** [airbnb/lottie-web#2324]
**Tell us about your environment**
Mac, AE2020, Bodymovn 5.7.3

* **Browser and Browser Version:** Chrome, v86
* **After Effects Version:** AE2020

**What did you do? Please explain the steps you took before you encountered the problem.**
We did an animation and wanted to export it with old format json (due to some technical issue, we aren't able to update our Android lottie library to the new one), but the exported file doesn't show up in HTML (when I try exporting with demo option, and also trying to preview with lottiefiles.com).

**What did you expect to happen?**
I expect the exported json to just work with both web and mobile, even though the file size is bigger.

**What actually happened? Please include as much _relevant_ detail as possible.**
Trying to preview the lottie in web player and it is completely hidden (doesn't show up), but works fine on mobile player (using both of the lotties app).

**Please provide a download link to the After Effects file that demonstrates the problem.**
I am willing to provide this, but can I send it directly to you instead?

**Comment by bodymovin** [comment]
hi, can you share the .aep and the exported json file?
Yes, you can send it to my email

**Comment by taylorling** [comment]
@bodymovin Just sent, thanks Hernan!

**Comment by bodymovin** [comment]
The old json format is not fully supported on the latest web players. If you need to test it, you should try using an older version.
Probably version 4.13.0
https://github.com/airbnb/lottie-web/tags?after=v5.0.5

**Comment by taylorling** [comment]
@bodymovin Ah got it, so it's not actually broken but just not supported in the latest web player then? Thanks for the info!

**Comment by bodymovin** [comment]
yes, that's correct
