### ISSUE TITLE
Text Stoke over Fill - incorrect/unexpected behavior

### ISSUE THREAD

**Issue by woozygoozy** [airbnb/lottie-web#2325]
So I am trying to create a an animation that I can later update the text/colors in the json editor... and I have several questions in this regard... 

1. I added fill and stroke animators to the text layers and specified that I want fills over strokes, but when it renders, the strokes always overlap the fills, meaning a thicker stroke crops the letters
2. the lottie editor does not let me update the font color only source - is this normal?
3. if I make a bounding box for the text - using "sourceRectAtTime" will this work?

Thanks in advance

**Comment by bodymovin** [comment]
hi,
1. Indeed fills over strokes are not supported yet
2. I'm not familiar with the editor limitations
3. sourceRectAtTime has limited support, not sure if it will work in your scenario

**Comment by woozygoozy** [comment]
Thanks @bodymovin, very good to know!
