### ISSUE TITLE
[docs] clarify which canvasContext is accepted

### ISSUE THREAD

**Issue by DrSensor** [airbnb/lottie-web#2326]
https://github.com/airbnb/lottie-web/blob/b5e10a21c45c43ad32b4731faa287cee4e07da52/README.md#L242
Is it context2d, webgl, or both?
It's not clear which contexts are supported since each [contextType](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#Return_value) have different API.

**Comment by bodymovin** [comment]
it's only context2d for now
