### ISSUE TITLE
Bodymovin export swf files?

### ISSUE THREAD

**Issue by DOTshima** [airbnb/lottie-web#2328]
Hi,

I am running Ae 17.1.4 (Build 37) and am trying to make my first Bodymovin for Telegram Stickers export. The animation consists completely of .swf files, imported from an Adobe Animate .fla and composition layers. 

When I try to export it I get these errors:
"After Effects warning: Could not create the file "/Users/X/file.aep Logs/AE 2020-10-19 03-15-23 CEST.txt'. Access was denied."

"After Effects warning: the rendering log will not be written."

And finally this message:
"**Render failed!
Composition should not include any Images**"

Does Bodymovin not support vector graphics in the form of .swf? Or is the issue something else? Does anyone know a solution?

<img width="570" alt="Skärmavbild 2020-10-19 kl  02 41 19" src="https://user-images.githubusercontent.com/20744316/96391862-7b96c600-11ba-11eb-8523-ea610c668d77.png">

<img width="369" alt="Skärmavbild 2020-10-19 kl  03 20 09" src="https://user-images.githubusercontent.com/20744316/96391716-05925f00-11ba-11eb-9ec6-0697c2faf2bb.png">

These are the layer types:
<img width="681" alt="Skärmavbild 2020-10-19 kl  03 24 19" src="https://user-images.githubusercontent.com/20744316/96391891-9cf7b200-11ba-11eb-923c-07deb1404936.png">

**Comment by bodymovin** [comment]
Hi, unfortunately lottie doesn't support swfs and telegram stickers doesn't support images either

**Comment by TDOBolu07** [comment]
I'm currently having same issues with the "Render Failed, composition should not include any images" Please how can it be solved
