### ISSUE TITLE
Odd glitch in json file when I export with Rubberhose

### ISSUE THREAD

**Issue by Sandrilli** [airbnb/lottie-web#2334]
Hello!
I've done an animation with After Effects, using Rubberhose. It's about a character skidding.

Oddily, when I export the json file with Bodymovin, some weird glitches appear (which are not present in the animation), can you help?
This is the error displayed

https://lottiefiles.com/share/zczp1t22

To preview I'm using Chrome.
I'm using AE 17.1.0
I'm using an Alienware 15 R3

This is the AE file

https://we.tl/t-YveZtccdXP

When I export from bodymovin I set up a standard json, and I turn expression into keyframes otherwise rubberhose breaks.

Can someone help me with this?

Thanks so much!

**Comment by bodymovin** [comment]
Hi, images seem to be missing.
Also, you probably want to call `anim.setSubframe(false)` since keyframe interpolation is rendering inbetween frames.

**Comment by Sandrilli** [comment]
Hi, actually the images are missing yes but my main issue is that glitch that you see in the lottiefiles preview. As these json should be sitting in a web page, you think it's something the developer should be taking care of?

**Comment by bodymovin** [comment]
usually those glitches are due to subframe interpolation, if the developer calls `anim.setSubframe(false)` , they will probably get fixed
