### ISSUE TITLE
Can I pass a parameter for loop with playSegments function?

### ISSUE THREAD

**Issue by Rikazavr** [airbnb/lottie-web#2339]
Hi! I need to play some segments of my animation on DOM Loaded with `loop: true`, but then on click I need to play rest of segments only once ( `loop: false` ). Is there any way to achieve this?

```
var animation = bodymovin.loadAnimation({
    container: document.getElementById('container'),
    renderer: 'svg',
    autoplay: false,
    autoloadSegments: false,
    path: path
  });

animation.playSegments([0, 30], true);

$("#Id").click(function(){
    animation.playSegments([30, 80], true);
});
```

**Comment by Rikazavr** [comment]
I managed to set an `eventlistener` and stop animation after first loop, but maybe there is more elegant solution

```
animation.onLoopComplete = function() {
    animation.goToAndStop(80, true);
};
```

**Comment by bodymovin** [comment]
Hi, using the onLoopComplete is a good way to do it. You can also try changing the `animation.loop` property from true to false when needed.

**Comment by Rikazavr** [comment]
Ok, thank you
