### ISSUE TITLE
New to Bodymovin, render wrong

### ISSUE THREAD

**Issue by FUSEStudioUK** [airbnb/lottie-web#2340]
First time rendering from Bodymovin, just a small logo animation for Navbar but once rendered image is completely different.
Only issue I can think of is the 'liquify' effect Ive used.

Photos attached please help. 
<img width="206" alt="Screenshot 2020-10-23 at 20 19 15" src="https://user-images.githubusercontent.com/73363013/97045152-274e6600-156d-11eb-8fba-c68376402e18.png">
<img width="240" alt="Screenshot 2020-10-23 at 20 19 24" src="https://user-images.githubusercontent.com/73363013/97045155-287f9300-156d-11eb-89bb-241179f8b238.png">
<img width="306" alt="Screenshot 2020-10-23 at 20 19 32" src="https://user-images.githubusercontent.com/73363013/97045156-29182980-156d-11eb-8a48-c6020183b612.png">
<img width="399" alt="Screenshot 2020-10-23 at 20 19 40" src="https://user-images.githubusercontent.com/73363013/97045157-29182980-156d-11eb-9547-994cf8db6915.png">
<img width="747" alt="Screenshot 2020-10-23 at 20 19 54" src="https://user-images.githubusercontent.com/73363013/97045158-29b0c000-156d-11eb-99b3-f44e39e3800d.png">

**Comment by bodymovin** [comment]
Hi, there are very few raster effects that are supported. Liquify is not one of them unfortunately.
https://github.com/airbnb/lottie-web/wiki/Effects
