### ISSUE TITLE
Bodymovin - Gif Animation in AE Composition not working

### ISSUE THREAD

**Issue by spiderbilly** [airbnb/lottie-web#2344]
**Tell us about your environment**
Mac OS Catalina version 10.15.7

* **Browser and Browser Version:**
Google Chrome - Version 86.0.4240.111
Safari - Version 14.0 (15610.1.28.1.9, 15610)

* **After Effects Version:**
Version 17.1.4(Build 37)

* **Bodymovin
Version 5.7.1

**What did you do? Please explain the steps you took before you encountered the problem.**
I am using a duik bassel rigged character and a separate gif in a composition. Trying to render with Bodymovin for web use. Duik Bassel is working fine, however, gif is NOT working in the browsers. I can see this gif uploaded to /images in the root folder, but not loading in the browser.
Why gif in the composition? - Original animation is made in Trapcode MIR and bodymovin doesnt support Trapcode. Hence converted to gif and trying. Any other way?

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by spiderbilly** [comment]
This is now sorted. I found an alternate way out. Thanks

**Comment by bariscc** [comment]
@spiderbilly it would be great if you share your solution
