### ISSUE TITLE
ExpressionManager not safe to be minified

### ISSUE THREAD

**Issue by merryman** [airbnb/lottie-web#2346]
This is a general observation I made, that probably causes a lot of glitches and issues with people using either the minified version of lottie-web or run lottie-web through their custom build process (this more than often involves a final minification step, at least for production).

I noticed this issue when I found that for some animations, lottie-web would not execute several parts of the animations I intended it to play any more as soon as I created a production build.
After investigating, I realized this is because these animations that caused issues in production were making heavy use of expressions, some of which failed to execute.

In this particular case, the issue was that the expression inside the animation exported by AE via the bodymovin plugin contained references to local variables of the scope found in https://github.com/airbnb/lottie-web/blob/6a4b94f5030bf6974e63fa17550c7390a0257ebd/player/js/utils/expressions/ExpressionManager.js#L344

For example `thisComp` was referenced in the expression, but the production build went over and decided to rename the declared variable in https://github.com/airbnb/lottie-web/blob/6a4b94f5030bf6974e63fa17550c7390a0257ebd/player/js/utils/expressions/ExpressionManager.js#L365 to something else, thereby making the expression crash and not affect the animation any more in production.

A general approach to fixing this, is to wrap variable declarations inside `eval()`statements.
So in this particular case I would suggest to "hard code" the variable mapping whenever an expression is evaluated.
This can be achieved quite simply by writing a slightly more enhanced `eval()` that also knows about a var mapping. At runtime it then expands and stringifies the values of the var mapping and assigns them to the vars making sure that the expressions are safe to run:

```
function safeEval(expr, varMapping) {
   
  let varDeclarations = "";

   Object.keys(varMapping).forEach(key => {
      varDeclarations += `var ${key} = varMapping.${key};\n`;
   });

  return eval(`(function () { ${varDeclarations}; return ${expr} })()`); // wrapping inside custom scope via function to keep compatibility with pre ES6 Browsers
}

```

In case expressions perform side effects on these variable declarations (from what I see that is not really the case), they can also be recaptured and returned in a similar fashion. But as far as I understand expression should not perform side effects on the declared variables.

Finally we could go and adjust line 365 as follows and move it to line 650 (where it is executed) to ensure the variables are captured properly.

```
var expression_function = saveEval('[function _expression_function(){' + val+';scoped_bm_rt=$bm_rt}' + ']', { toWorld,fromWorld,fromComp,toComp,fromCompToSurface, position, rotation, anchorPoint, scale, thisLayer, thisComp,mask,valueAtTime,velocityAtTime, loopIn, loop_in, loopOut, loop_out, smooth, inPoint, outPoint, name, width, height })[0];

```

If that sounds decent to you, I can prepare a PR.

**Comment by bodymovin** [comment]
Hi, this makes sense but as far as I know, minifiers don't rename variables if they see eval used in a certain scope.

**Comment by merryman** [comment]
That depends on the minifier. If I use google closure, it basically wipes all of these variables but admittedly, google closure is something more than just a minifier.
However when I use a "normal" minifier like terser, I still encounter issues with this particular module: Concretely the variables starting in here https://github.com/airbnb/lottie-web/blob/6a4b94f5030bf6974e63fa17550c7390a0257ebd/player/js/utils/expressions/ExpressionManager.js#L176 are getting all mangled and can not be recovered inside expressions. I would as a compromise suggest to at least move those closer to the eval, such that they do not get minified.
