### ISSUE TITLE
"cl" property of image layers gone?

### ISSUE THREAD

**Issue by Fr4nZ82** [airbnb/lottie-web#2347]
Hi,
can you confirm me if the "cl" property of image layers (file extension) has been removed in version 5.7.3 of bodymovin? At the moment I can't test myself, i have several json already created and on some I don't find the "cl" property that I used to extrapolate the extension of the original file. These jsons without "cl" have version 5.7.3, while the others have 5.7.1. I can do it in other ways, but I wanted to figure out first if it's an after effects export error or has it been removed entirely.
thanks

**Comment by bodymovin** [comment]
Hi, it should be working. Can you share an example?

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
