### ISSUE TITLE
crop the edges of a Lottie animation

### ISSUE THREAD

**Issue by carmandale** [airbnb/lottie-web#2357]
I would like to create an iPad aspect ratio Lottie animation, and have it fit to 100vh, so that the edges are cropped off for an iPhone screen. I can't seem to get that to work. So, right now, I have to make 2 versions of everything. I don't want to have the Lottie animation stretch at all, but fill the screen vertically and just let the edges be cropped off.

**Comment by bodymovin** [comment]
are you using the web player or the lottie-ios player?
If it's the web player, perhaps the preserveAspectRatio property can help?
https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#preserveaspectratio

**Comment by carmandale** [comment]
Hello! I am using the web player. I have added 

rendererSettings:{ preserveAspectRatio:'xMidYMid slice' } 

which is mostly working. it just doesn't seem to be as precise as I would like, and doesn't work when I rotate into landscape mode.

I have the
<body>
    <div class="lottie-wrapper">
        <div id="bm1"></div>
    </div>

and I have them styled as

.body {
  // nothing specified
}

.lottie-wrapper {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
    overflow: hidden;
}

#bm1 {
    height: 100vh;
    /* width: 100vw; */
}

and I want the Lottie to always fill 100% of the height of the window and just crop the sides.

**Comment by carmandale** [comment]
and it seems that no matter how I pay with the wrapper or Lottie div, I can't get it to be 100% of the viewer height

**Comment by carmandale** [comment]
@bodymovin - also, I want the Lottie to fill the screen on mobile and be un scrollable...just fill the screen. I would think that making the Lottie-wrapper div be overflow:hidden would do the trick, but it doesn't seem to work. I still get a little scrollable area for the page.

**Comment by bodymovin** [comment]
those seem to be common mobile issues unrelated to the library. I'd suggest that you use a static inline svg to adjust your requirements and then replace it with the animation.
