### ISSUE TITLE
How can i set loop from certain number framerate

### ISSUE THREAD

**Issue by stdarkpha** [airbnb/lottie-web#2359]
i want the animation play from frame 0 to 15 then from 15 to end loop ( without starting from number zero again)

how can i archive that ??

**Comment by bodymovin** [comment]
Hi, you can use `playSegments`
you probably want to call `anim.playSegments([[0,15],[15, last frame]])`
https://github.com/airbnb/lottie-web#playsegmentssegments-forceflag
