### ISSUE TITLE
lottie-web: addEventListener with loaded_images is not work for ios

### ISSUE THREAD

**Issue by huanzhiyazi** [airbnb/lottie-web#2362]

**Comment by nihey** [comment]
I had the same issue, it seems that [this event](https://github.com/airbnb/lottie-web/blob/master/player/js/utils/imagePreloader.js#L43) is not being fired on Safari.

I've managed to do a workaround that fires this event through an `Image` object: https://github.com/KasselLabs/lottie-web/commit/b976c9555bc30e5232c979364bedb6227472a8b3

Maybe this could be done here too.

**Comment by huanzhiyazi** [comment]
@nihey I met the same issue on other Android webviews.

**Comment by grapefruit-hellomonday** [comment]
@nihey  i used your fork last week and it works, but it still not work in page of WeChat
