### ISSUE TITLE
Is Skew supported with Lottie web

### ISSUE THREAD

**Issue by mewis** [airbnb/lottie-web#2363]
Hi there, could you please let me know if Skew is supported.
I have an animation that was created for me in after effects, I was provided a gif and the json exported from bodymovin.
In the gif a block rotates but when using lottie-player it does not.

here is the lottie player version
[https://lottiefiles.com/share/co3bjz8u](https://lottiefiles.com/share/co3bjz8u)

Thank you

**Comment by bodymovin** [comment]
Hi, skew as a transforming property of shapes should be supported. But it's not supported as an effect.

**Comment by kudanai** [comment]
Hello. Since this issue has been stale for some time, I'm closing it. Please feel free to re-open it or file a new issue if the problem is still relevant.
