### ISSUE TITLE
Animations Not Appearing on First Page Load

### ISSUE THREAD

**Issue by gpsugy** [airbnb/lottie-web#2364]
**Tell us about your environment**
lottie-web version 5.7.3
iOS Devices such as iPhone/iPad (e.g. iPad 7, iOS 14.1)

* **Browser and Browser Version:**
Latest Safari/Chrome Versions

**What did you do? Please explain the steps you took before you encountered the problem.**
```
$(() => {
    const icon = $('.my-icon');
    const iconPath = 'my-lottie-icon.json'';

    lottie.loadAnimation({
        container: icon[0], // the dom element that will contain the animation
        renderer: 'svg',
        loop: false,
        autoplay: false,
        path: iconPath // the path to the animation json
     });

    $(icon).on('click', () => {
        iconAnimation.goToAndPlay(0);
    });
});
```

**What did you expect to happen?**
That all lottie animations built like this would be visible and appear the _first_ time the website with these animations is loaded.

**What actually happened? Please include as much _relevant_ detail as possible.**
On the _first_ page load - as in, your browser session is new by the time you go to the site - none of the lottie animations appear. There is no CSS that indicates a `visibility: hidden` or `display: none` issue, and the HTML shows that the `svg` has indeed been injected into the proper DOM element. And yet on most - if not all - iOS devices on both Safari/Chrome, they cannot be seen. No console errors, either. All successive refreshes after that first page load, however, result in visible and completely functional animations.

_A possibly helpful note:_ All of these animations are meant to play _only_ on click or hover events, not on page load. On every page load except the very first one (when the animations actually appear), I have verified the animations play correctly with those triggers.

Since the animations work correctly on every successive page load, this issue does not seem to be an issue of syntax, but perhaps either a bug or misunderstanding of the options I am using when calling `loadAnimation`. Any help would be appreciated if this is not a real bug, but a usage issue. Thank you!

**Comment by bodymovin** [comment]
hi, have you tried setting the autoplay to true to check if they work that way?

**Comment by gpsugy** [comment]
Hi, looks like this issue was not due to the lottie-web library, but due to my server having issues with not serving its assets with https protocol on the first page load! Now that this is resolved, there is no issue. Apologies for the confusion, and thank you for your help @bodymovin!
