### ISSUE TITLE
Render failed

### ISSUE THREAD

**Issue by jumostudio** [airbnb/lottie-web#2366]
Bonjour,

J'essaie de faire des rendus de plusieurs animations mais ça ne fonctionne pas.
J'ai lu plusieurs messages de personne qui ont eu ce soucis mais ça ne fonctionne malheureusement toujours pas.

J'ai retiré tous les effets qui pouvait potentiellement poser problème.

Merci d'avance pour votre aide !

**Comment by bodymovin** [comment]
salut, peux-tu envoyer un exemple?

**Comment by theolavaux** [comment]
Je constate aussi ce problème, j'ai mis pas mal d'infos dans mon ticket :smile: 

https://github.com/airbnb/lottie-web/issues/2371

**Comment by jumostudio** [comment]
Merci mais j'ai finalement trouvé une solution. 

J'ai désinstallé Bodymovin et installé LottieFiles qui fonctionne mieux pour ma part. Mon problème : j'ai utilisé l'outil marionnette pour animer des personnages et cet outil n'est pas pris en charge pour un export au format .json. Si jamais vous rencontrez ce problème il faut bien animer chaque tracé et forme sous le format ae. Pour un rendu très propre et non pixelisé il faut bien créer des masques à partir de vos formes vectorielles et éviter de conserver les calques d'Illustrator.
Toutes les animations d'Animation Composer ne sont pas prises en charge ainsi que la plupart des effets il faut vraiment utiliser les masques et basiques d'After. Les précompositions fonctionnent très bien avec Lottie.

J'espère que ça pourra aider certains :)
Bon courage !
