### ISSUE TITLE
Stroke width not being taken into account for path bounding box after a mask has been applied

### ISSUE THREAD

**Issue by gabormagyar** [airbnb/lottie-web#2367]
**Tell us about your environment**
Windows 10, Chrome 86.0.4240.198, After Effects 17.5.1 (Build 47)

**What did you do? Please explain the steps you took before you encountered the problem.**
Issue is reproduceable by doing the following in AE:
- Create shape layer
- Add unclosed Path
- Add Stroke (large stroke, more than 100px)
- Add mask to the layer (any mask, subtractive away from edges makes the issue more visible)

**What did you expect to happen?**
Correct bodymotion render (looking like the same as in after effects):
![image](https://user-images.githubusercontent.com/63397303/99656525-49001780-2a5d-11eb-8298-37b78c77d32b.png)

**What actually happened? Please include as much _relevant_ detail as possible.**
Bounding box incorrect:
![image](https://user-images.githubusercontent.com/63397303/99656930-c6c42300-2a5d-11eb-9846-84e413eb319b.png)

**Workaround**
Adding a rectangle to the shape layer (in additon to the path) that's large enough to be outside the comp viewport. Has to be before the stroke step.

**Please provide a download link to the After Effects file that demonstrates the problem.**
Attached zip with project and outputs
[bodymotion_bug.zip](https://github.com/airbnb/lottie-web/files/5566289/bodymotion_bug.zip)

**Comment by bodymovin** [comment]
svg masks don't account for stroke width to set their size, you need to include a rectangle will a transparent fill on your shape layer that covers the whole stroke size in order to make it work
