### ISSUE TITLE
Drop shadow disabled

### ISSUE THREAD

**Issue by Ahsan93** [airbnb/lottie-web#2368]
<img width="685" alt="截屏2020-11-20 下午1 26 12" src="https://user-images.githubusercontent.com/16192792/99762799-47555300-2b34-11eb-8389-29fd1c81eaea.png">
This is what i want.

<img width="704" alt="截屏2020-11-20 下午1 27 13" src="https://user-images.githubusercontent.com/16192792/99762832-5805c900-2b34-11eb-80e6-6bdaddfe738c.png">
This is what i got.

I use the newest version of AE and Bodymovin. and use the drop shadow from the effects.
when i export the JSON flie and upload it to review, it doesn't look like what i want.

**Comment by bodymovin** [comment]
Hi, you might be missing to set the filterSize when loading the animation
https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#filtersize-svg-renderer
