### ISSUE TITLE
Help With Bodymovin and Rubberhose 2.0 Rigs

### ISSUE THREAD

**Issue by TheRackoon** [airbnb/lottie-web#2369]
Hello I am very lost on how to do something and I would like some help. I made an animation using Rubberhose 2.0 however when I export to .json it doesn't show movement, even after clicking that it should include guides and hidden layers.

I intend to get the .json file so that I can later export to .tgs to use for Telegram, however there are no tutorials explaining this workflow and I am lost after not being able to export my animation.

Here are my files:

Json: https://drive.google.com/file/d/1WL8R6OkSl0rmFUDExMLncj6BlmZaTRXU/view?usp=sharing

AE: https://drive.google.com/file/d/117Wfkgzib0H0DroY1jmIz2Nknd5bxBAv/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, the Puppet effect is not supported unfortunately by the players.

**Comment by TheRackoon** [comment]
Oh ok, I am guessing only certain functions off Rubberhose work then, like hoses because they are just objects and not deformations. Ok I understand why.

**Comment by bodymovin** [comment]
yes, that's right
