### ISSUE TITLE
getElementById() not working

### ISSUE THREAD

**Issue by abn5x** [airbnb/lottie-web#2370]
Hello, the animation loads fine, but when trying to query an element by it's id(made sure to rename layers with # or . at the beginning), the returned object is a null so we can't make interactive animations with Javascript...

the code:

`var animation = lottie.loadAnimation(
    {
        container: document.getElementById("animation"),
        path: "../Resources/search.json",
        renderer: "svg",
        loop: false,
        autoplay: false,
    }
)
animation.addEventListener("DOMLoaded", function () {
    console.log("fired!")
    var lupa = document.getElementById("Lupa")
    lupa.addEventListener("click", alert("wow"))
})`

the error:
Uncaught TypeError: Cannot read property 'addEventListener' of null

**Comment by bodymovin** [comment]
hi, can you share a link with the implementation?

**Comment by abn5x** [comment]
> hi, can you share a link with the implementation?

sure, it's nothing special to be honest

https://codepen.io/abn5x/pen/eYzwxQr

**Comment by abn5x** [comment]
Neverming, fault on my part, it's working right now, thank you anyways 😂

**Comment by 2gud4u** [comment]
@abn5x  could you tell what was the error? I have the same issue
