### ISSUE TITLE
Control different layers independently

### ISSUE THREAD

**Issue by dranitski** [airbnb/lottie-web#2372]
Hi all! Can anyone please advice if I can control different layers/containers independently with `lottie-web`?

Here is what I mean. We have a reference animation
![source](https://user-images.githubusercontent.com/27373393/100338169-4ebfa500-2fe9-11eb-8ec5-e23e96898aa8.gif)

here we can see two layers with two animations
- background layer where the clouds and cactus move
- front layer where the people are animated in a car

I understand that I can stop and play the whole animation, but Is it possible to somehow stop the background animation layer but continue the front animation loop? Or set the loop for background animation for different frames then the front animation do?
I mean, can I somehow control different layers/containers inside my lottie animation separately or should they be two different lottie animations on one web page, positioned one on other, so I could control them individually?

If the only way is to use two different lottie animations, can anyone please point me to the correct example of using two lottie animations on same page being positioned one on top of other?

Thanks in advance!

**Comment by dranitski** [comment]
@bodymovin any advice please? Will be glad to hear from you :pray:

**Comment by bodymovin** [comment]
Hi, if they are two separate parts and you don't need them synced, the easiest solution is to export two animations and place one on top of the other one. In order to do that, you can create two divs with absolute positioning inside another div with relative position, and they should overlap correctly.
If you need something more controlled, you can create two precomps with time remapping, use the lottie-api to control time values and adjust them manually, but that's more complex and will need a good understanding of the libraries and javascript.

**Comment by dranitski** [comment]
Thanks a lot! Second way seems like what we need. I will be glad if you can provide me with code sample for changing time remapping via lottie-api. I guess we can modify the example below to achieve this somehow? Thanks in advance :tada: 

```javascript
// Create the lottie instance for lottie_api to use
const animationData = lottie.loadAnimation({
  wrapper: elt, // The HTML node
  animType: "svg",
  autoplay: true,
  animationData: lottieFile, // the JSON of the lottie file
});

const layerName = "Shape Layer 1";
let newXPosition = 100,
  newYPosition = 100;

const API = lottie_api.createAnimationApi(animationData); // Create the lottie_api instance

// Add a value callback of the keypath to Position for this layer:
API.addValueCallback( 
  API.getKeyPath(`${layerName},Transform,Position`),
  (currentVal) => {
    return [newXPosition, newYPosition]; // Sets the initial value, can use currentVal[0] and [1] for no change
  }
);

// Now any change to the above variables will affect the Lottie animation, like so:
newXPosition = 200;
newYPosition = 200;
```

**Comment by dranitski** [comment]
found some useful info here
- https://github.com/airbnb/lottie-web/issues/1547
- https://codepen.io/airnan/pen/gvBMPV
