### ISSUE TITLE
JSON and preview export: wrong layers poisition

### ISSUE THREAD

**Issue by ienatom** [airbnb/lottie-web#2374]
**Tell us about your environment**

* **Browser and Browser Version:**
Safari Version 14.0 (15610.1.28.1.9, 15610)
Chrome Version 87.0.4280.67 x64

* **After Effects Version:**
Version 17.5.0

**What did you do? Please explain the steps you took before you encountered the problem.**
Trying to create a gif with strokes effects. When exporting in can see the layers but they are misplaced: the alpha levels (or the effects) are out of place. It also looks like the dimensions is incorrect instead of being 1920x1080. I simply try to export via JSON and it shows incorrectly

**What did you expect to happen?**
Screenshots below:
INCORRECT RESULTS
![Schermata 2020-11-26 alle 23 56 09](https://user-images.githubusercontent.com/5008870/100395879-03d27b80-3043-11eb-9c8b-32a12371a7d0.png)
![Schermata 2020-11-26 alle 23 56 12](https://user-images.githubusercontent.com/5008870/100395881-0503a880-3043-11eb-9c49-ee1518357226.png)
CORRECT FINAL RESULT
![Schermata 2020-11-26 alle 23 56 03](https://user-images.githubusercontent.com/5008870/100395882-059c3f00-3043-11eb-8fc9-2ff5b63a7676.png)

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**
The correct composition I am using to export is the one named "V3"
https://drive.google.com/file/d/1FZ6C3YRvZz1WKLUN_XaqEszIhS7e2mYR/view?usp=sharing

**Comment by bodymovin** [comment]
hi, can you share the missing assets?

**Comment by ienatom** [comment]
Sure, here they are: https://drive.google.com/drive/folders/1ilsux6jFlnSgd_XMsRo9hROOfs2R1IFd?usp=sharing

I have also uploaded the exported and incorrect JSON

**Comment by ienatom** [comment]
> hi, can you share the missing assets?

Hi, did you have time to check if there is any error?

Best regards

**Comment by bodymovin** [comment]
Hi, it seems to be related to the aspect ratio of the solids. If you right click on the TRACE solid in the Projects panel in AE, select Interpret Footage > Main, you'll see that it's set as DVCPRO, if you change it to Square Pixels, you'll get the same result as you see on your screenshot.
Lottie doesn't support other pixel ratios besides square ones, so unfortunately you'll need to accommodate the animation changing those values.

**Comment by ienatom** [comment]
Thanks, now the format is correct, altough I have a problem with the sequence of the animations: They all animate at the same time instead of following different masks at different times. Is this a limitation of the plugin as well or might it be me?

**Comment by bodymovin** [comment]
that's right, stroke masks don't support sequential animating unfortunately
