### ISSUE TITLE
Null object + camera

### ISSUE THREAD

**Issue by KirdesMF** [airbnb/lottie-web#2375]
Hello,

Simple question, is it possible to use a null object with a camera ? I mean does lottie support that ?
I checked the docs but I did not find anything, or I've missed something.

Thx

**Comment by bodymovin** [comment]
Hi, in general 3d and cameras don't have full support, but attaching it to a null element should work.
I'd suggest that you try it with a simple example to make sure it works on your case.

**Comment by KirdesMF** [comment]
Thx for this quick answer. I will try it and give a feedback to close this conv.

**Comment by KirdesMF** [comment]
Seems to work. Yeah Next time I should just try myself. Thx again

**Comment by KirdesMF** [comment]
I talked too quickly. its not working, I think I need to fake the camera movement
