### ISSUE TITLE
iOS 9.3.5

### ISSUE THREAD

**Issue by ashley-plott** [airbnb/lottie-web#2376]
Hi I am using the lottie player, and my animations won't work is there a polyfill or is it something that won't work. If it's not supported can someone point me in the direction of showing a fallback (image).

Device: iPad
Software: iOS 9.3.5
Browser: Safari

Thanks

**Comment by bodymovin** [comment]
Hi, does it work on other devices? Have you tried another animation?
Also, if it's not supported, you'll need to roll out a custom fallback, this library at doesn't take care of that part.

**Comment by ashley-plott** [comment]
Hi, I have it working on iOS 10+ but seems it doesn't like the 9.3.5 iOS. I have put fallbacks in already took a while to get the iOS version number. 

https://www.plott.co.uk/

But we love bodymovin and lottie, it's amazing!

**Comment by openmindculture** [comment]
As this issue has been closed, could someone please point me to the solution, how to ensure a fallback?
