### ISSUE TITLE
How to update animationData?

### ISSUE THREAD

**Issue by veeking** [airbnb/lottie-web#2379]
How to update animationData and resume play?
I try to `anim.animationData = data`,  but it not work

**Comment by bodymovin** [comment]
hi, if you want to change an animation, I suggest that you destroy the previous one and load a new one instead

**Comment by veeking** [comment]
> hi, if you want to change an animation, I suggest that you destroy the previous one and load a new one instead

Ok,thanks, if I destroy and reload, the animation will flicker with blank. I will try to find other ways， Thanks.
