### ISSUE TITLE
audio source files and json are renamed 

### ISSUE THREAD

**Issue by rodbs** [airbnb/lottie-web#2380]
**Tell us about your environment**

* **Browser and Browser Version:**
Windows 10, 
Chrome  87

* **After Effects Version:**
Adobe After Effects 2020 
BodyMovin 5.7.4

**What did you do? Please explain the steps you took before you encountered the problem.**
I added standard mp3 audio files
In Bodymovin/ Audio settings, I check off Enabled (export audio layers)

**What did you expect to happen?**
To get  the same source files names in the exported audio files and in the json file

**What actually happened? Please include as much _relevant_ detail as possible.**
Everything is renamed (files, and json)

 "assets": [
    { "id": "audio_0", "u": "images/", "p": "aud_0.mp3", "e": 0 },
    { "id": "audio_1", "u": "images/", "p": "aud_1.mp3", "e": 0 },
    { "id": "audio_2", "u": "images/", "p": "aud_2.mp3", "e": 0 },
    { "id": "audio_3", "u": "images/", "p": "aud_3.mp3", "e": 0 },
    { "id": "audio_4", "u": "images/", "p": "aud_4.mp3", "e": 0 },
    { "id": "audio_5", "u": "images/", "p": "aud_5.mp3", "e": 0 },
    { "id": "audio_6", "u": "images/", "p": "aud_6.mp3", "e": 0 },
    { "id": "audio_7", "u": "images/", "p": "aud_7.mp3", "e": 0 },
    { "id": "audio_8", "u": "images/", "p": "aud_8.mp3", "e": 0 },
    { "id": "audio_9", "u": "images/", "p": "aud_9.mp3", "e": 0 },
    { "id": "audio_10", "u": "images/", "p": "aud_10.mp3", "e": 0 }
  ],

**Please provide a download link to the After Effects file that demonstrates the problem.**
(The text above is from the json)

**Comment by bodymovin** [comment]
Hi, I'm not sure I understood the issues. When switching off the audio option, is it exporting the audio assets but no files?
Renaming of the files is expected.

**Comment by rodbs** [comment]
The export works fine, but everything is renamed. If my file is named 'myfile.mp3", I add it to AE as myfile.mp3, but when it's exported by bodymovin it's renamed to aud_0.mp3 , and in the  json to audio_0.

Is the default behavior? Is it possible to have the files not  renamed in the export?

**Comment by bodymovin** [comment]
yes, it's default behavior. Have you tried selecting `Original Asset Names` from the Assets dropdown in the bodymovin options?

**Comment by rodbs** [comment]
With ` Original Asset Names` it still renames everything.

I think there should be an option not to rename. Basically because when using several animations with its corresponding mp3 files, in every json the audio naming is the same (aud_0 ...), so we need to rename every json manually to point to the correct mp3 files.

**Comment by bodymovin** [comment]
you're right, I've fixed it. It will be available on the next version. Thanks!

**Comment by rodbs** [comment]
Thanks a lot!!

**Comment by bodymovin** [comment]
published!
