### ISSUE TITLE
Gradient not working

### ISSUE THREAD

**Issue by SIMAASdesign** [airbnb/lottie-web#2384]
After effects version:  Version 17.0.2 Adobe After Effects 2020
Bodymovin version: latest
Operating system: Win 10
All languages are in English Program/OS

I've imported vector shapes from Illustrator and animated on after effects. Everything was good. I exported the JSON file via bodymovin and everything shows up nicely, but the gradients disappeared.

I've tried every solution I found: Renaming all group 1/etc to group_1, renaming Gradient Fill 1 to Gradient Fill_1 and etc.
So far what I've found nothing helped me. I'm attaching files, could anyone take a look?

Original:
![image](https://user-images.githubusercontent.com/38739986/101265490-a11e6580-374f-11eb-8a2d-b50c5ee31a7d.png)
How it ends up JSON:
![image](https://user-images.githubusercontent.com/38739986/101265502-b6938f80-374f-11eb-8a01-4d211654629f.png)

Files:
[anim.zip](https://github.com/airbnb/lottie-web/files/5647883/anim.zip)

**Comment by Danjuanlab** [comment]
Check this~https://github.com/airbnb/lottie-web/issues/1201
