### ISSUE TITLE
Alpha inverted matte doesn't work properly in Lottie

### ISSUE THREAD

**Issue by xtremeblvr** [airbnb/lottie-web#2387]
Google Chrome Version 87.0.4280.88 (Official Build)
AE 2019

Created a typography animmation, using strokes and alpha matte.
The animation was quite different from the one I had in AE

After exporting my animation, the lottie preview was showing me the stroke animation I used to mask the text and noot the actual text animation.

AE Fille
[Valency.zip](https://github.com/airbnb/lottie-web/files/5655586/Valency.zip)

Heres the link to the lottie preview 
https://lottiefiles.com/share/1dcj28be 

Screenshot of expected aniimation
![Valency](https://user-images.githubusercontent.com/60433548/101413035-e1aee800-38e3-11eb-9a3d-929bfafba50d.png)

**Comment by bodymovin** [comment]
Hi, unfortunately merge paths are not supported by the player

**Comment by xtremeblvr** [comment]
Hello, thanks. But does that mean my json file is still accurate, I just can't preview it accurately in the player?

**Comment by bodymovin** [comment]
not sure what you mean by accurate. It you're planning to use it with the lottie players, they won't work.

**Comment by xtremeblvr** [comment]
Alright then. Thank you very much
