### ISSUE TITLE
Lottie animation rendering incorrectly

### ISSUE THREAD

**Issue by selectnz** [airbnb/lottie-web#2390]
AE version: 17.5.0

Hi All!
I am having a problem with a Lottie file not rendering part of my image. Here's a link to a screen recording so that you can see the issue.
[https://youtu.be/gbMnIBRDs8I]
 I had to split up the letters into pieces, long story but the short version is there was too much overlap with the stroke width cutting in and making a "t" as the stroke passes where the letter overlaps, hence the separate layers and keyframing workaround.
But I can't figure out why bodymovin isn't rendering the last part of the s correctly... 
I'll attach a zip with the project inside so anyone can take a look if they want.

Thanks in advance.
[final project.aep.zip](https://github.com/airbnb/lottie-web/files/5669514/final.project.aep.zip)

And please bear with me if I've formatted this post wrong, it's my first time using Github, so don't know the etiquette quite yet.

**Comment by bodymovin** [comment]
Hi, in your comp "SG", the layers "S2" and "S3" have a non closed mask applied to it that is preventing the shape to be drawn. If you delete those masks, everything should work fine.
