### ISSUE TITLE
Trying to capture current colors mapped to a Keypath

### ISSUE THREAD

**Issue by chrislworkaccount** [airbnb/lottie-web#2394]
I am working on a project for iOS, Android and RN. I am using the KeyPath object to update colors for a keypath. That piece works fine. I can't seem to find a way to fetch the current color of a layer by Keypath. I need the current colors to create color profiles so I can create different themed versions for the same Lottie animation.

To fetch the color I am hoping to find something as simple as **_KeyPath("my key path").getCurrentColor()_**? Anyway to accomplish that is much appreciated

Below is what I am doing to set the color on Android. 

    fun applyColorForTag(colorMap: Map<String, String>?) {
        mIllustrationView.addValueCallback(
            KeyPath(colorMap?.get("tag"), "**"),
            LottieProperty.COLOR_FILTER,
            object : SimpleLottieValueCallback<ColorFilter?> {
                override fun getValue(frameInfo: LottieFrameInfo<ColorFilter?>?): ColorFilter? {
                    return PorterDuffColorFilter(
                        Color.parseColor(colorMap?.get("color")),
                        PorterDuff.Mode.SRC_ATOP
                    )
                }
            }
        )
    }

**Comment by bodymovin** [comment]
hi, can you post this issue on the lottie-ios repository?
