### ISSUE TITLE
Moving Gradient Background is in blue(composition color) whenever i try to export it

### ISSUE THREAD

**Issue by whizzbbig** [airbnb/lottie-web#2398]
I made a moving gradient background on ae and tried to export it by bodymovin and in preview, it shows it in form of blue as it was my composition color.

I am using macOS big sur which language is set to English us and ae is in English.

SOFTWARE VERSION:
**After Effects latest version (cracked)** 12/2020 

and I have more information to share when I was trying to install both extensions to my after effects by Anatasy extension manager it isn't showing half of the adobe products not even AE only photoshop Idk y but after that, I **direct install** it by ZXP Installer. it was also not showing the compatibility. 

I tried a few more steps to solve this precomposing or renaming gradient I used 4 layer gradient
same like this 
[https://youtu.be/xlFsfHF3Yb4](url) **OPEN IT IN NEW TAB BY COPY AND PASTE** it will not take you to youtube if you click directly.

few snaps:
![Screen Shot 2020-12-16 at 11 01 41 PM](https://user-images.githubusercontent.com/54703305/102384446-b9fe0500-3ff2-11eb-9b00-04c24dc526b6.png)
I want to achieve this

![Screen Shot 2020-12-16 at 11 01 56 PM](https://user-images.githubusercontent.com/54703305/102384476-c5513080-3ff2-11eb-8a98-dd40d7d031e6.png)
preview

please help asap!!

**Comment by bodymovin** [comment]
that effect is not supported by the player
