### ISSUE TITLE
Please add some documentation on the code or add comments

### ISSUE THREAD

**Issue by snorpey** [airbnb/lottie-web#24]
I've been trying to make a few adjustments to the bodymovin player for use in one of my projects.

While experimenting with the player, I noticed that it sometimes takes me quite a while to find the right piece of functionality in the code.

I think it would be immensely helpful for developers if there was a little more documentation about what the individual classes are doing, and how they're tied together.

I know this project is evolving very quickly, and the docs tend to get outdated fast, but a little more information on the inner workings of the code would be greatly appreciated.

Thank you :-)

**Comment by bodymovin** [comment]
@snorpey My bad. I need to document the code, the exported json structure and do a video about how it works.
As soon as I finish implementing expressions, I will do all of them. By then the code will be more stable.
Meanwhile, feel free to email me and ask me anything you need.
cheers!

**Comment by selloutdesign** [comment]
Are the after effect files for the demos some where. I would love to see how these are put together in AE.

**Comment by bodymovin** [comment]
@selloutdesign there is only the bodymovin animation here
https://github.com/bodymovin/bodymovin/tree/master/projects
Are you interested in any in particular?

**Comment by mattkahl** [comment]
Following up on this:
I can't find any documentation of the JSON structure. Does it or any other documentation exist somewhere? Any pointers on where to get started with figuring that out? I've been tracing through the code for a day or so; it's quite a task from scratch.

**Comment by bodymovin** [comment]
@mattkahl Uploaded the documentation for the whole JSON structure.
Took me the whole Sunday :)
Let me know if you need any clarification.
https://github.com/bodymovin/bodymovin/tree/master/docs/json

**Comment by mattkahl** [comment]
@bodymovin Thanks! I'll take a look at this. I had already started to try and document the spec myself. This is tremendously helpful.

**Comment by Jeremy-Knudsen** [comment]
Thanks for working on documentation!!

I would love to see a walkthrough on hooking up interactivity (beyond the basic level of playing the animation) to bodymovin SVGs. For instance, how did you create the interactive inverse kinematic demo of the hand that you can "shake". I see that you are manipulating the JSON data on mousedown, which I wasn't expecting and not sure how actually is working.

**Comment by mattkahl** [comment]
@bodymovin Have you been able to get that JSON documentation to render using something like https://github.com/cloudflare/doca or https://github.com/lbovet/docson? I haven't had any success but haven't tried too hard.

**Comment by 0legg** [comment]
@bodymovin Is your documentation implementing some type of JSON schema? I'm making bodymovin viewer plugin for IDE, and it'll be great if I can add some kind of format validation to it.

**Comment by 0legg** [comment]
@bodymovin Is your documentation compatible with JSON Schema or any other Schema, so, for example, Lottie java parser can be generated automatically?

**Comment by bodymovin** [comment]
Not yet, I've tried to follow the JSON Schema here
http://json-schema.org/
But I haven't validated it yet.
Not sure how to move forward with this. If anyone can point me in the right direction, it'd be great.
If not, as soon as I can, I will continue researching it.

**Comment by 0legg** [comment]
@bodymovin I found [this tutorial](https://spacetelescope.github.io/understanding-json-schema/about.html) just awesome. I'll try to modify existing docs to conform specification (but I'll probably need some help)

**Comment by 0legg** [comment]
@bodymovin It seems to be harder than I thought previously. It'll be very nice of you if you provide data about:

- which fields are required, and which are optional
- which number fields can be integer-only
- number ranges (positive, 0-1, 0-100, 0-255)
- string formats (if have specific format strings, like URI)

On my side I'm trying to update all data to meet JSON Schema requirements and verify that every example can be validated with it.

**Comment by 0legg** [comment]
Also, seems that "v" parameter of animation is not a number, but string. I'll fix every error I'll find (or at least I'll provide information =) )

**Comment by bodymovin** [comment]
@0legg I'll try to add all that information during next week.
the "v" parameter should be a number por single dimension properties, where are you seeing it as a string?

**Comment by 0legg** [comment]
@bodymovin in the root object, "v" parameter stays for plugin/library version, ant it's definitely string like "4.5.8"

**Comment by bodymovin** [comment]
yeah, you're absolutely right. I thought you meant another property. My mistake.

**Comment by kudanai** [comment]
Hey there. As this issue has been stale for some time, I'm closing it. Please re-open it if you feel it still relevant or open a new issue.
