### ISSUE TITLE
Images are not included in Json when include in json setting is enabled

### ISSUE THREAD

**Issue by akashrwx** [airbnb/lottie-web#2400]
Hello,

I am facing a strange issue with bodymovin which has started a few days back. 

Whenever a fresh copy of Bodymovin is installed, the plugin works fine with JSON exported as expected.
Once After Effects is closed and opened again after a while the Renderer gets stuck at Exporting images. Shapes and text are exported fine, only when exporting images in JSON it stops.

If Compression is disabled then the JSON is exported with Images in a separate folder although include in JSON is enabled.

If I remove and reinstall the plugin it works only once and after I restart After effects plugin will stop working again. I have tested this in MAC os and windows os on multiple devices but the issue persists on all of them. Also, this is not a specific project issue. it is happening in any type of project.

I have also tried to use it with previous versions of after effects but the issue is the same. Please have let me know if there is any fix for this.

After Effects 17.5.1
BodyMovin 5.7.4

Settings > Assets
Enabled Compression - 90
Include images in JSON

![image](https://user-images.githubusercontent.com/40183051/102605621-884c8180-414b-11eb-9aab-cc6f319b3326.png)

**Comment by bodymovin** [comment]
hi, version 5.7.6 should have fixed this. Reopen if it's not fixed

**Comment by DirtyWhite** [comment]
still not working with 5.7.6 & 5.7.12

**Comment by vijaypwr61** [comment]
same issue
