### ISSUE TITLE
Precomp and precomp and expressions and essential properties

### ISSUE THREAD

**Issue by AlexeyGfi** [airbnb/lottie-web#2402]
I have a logo animation project, contains two precomp (general scene > precomp > precomp) and list of expressions and essential graphics properties.
In render I set options with expression link to external comp and tried render in any combination but only the most last comp in my nested chain  render correctly.
Is it possible to render (may be without essential graphics properties, I will replace it to manual settings)?
[07_with_white_contour.zip](https://github.com/airbnb/lottie-web/files/5720949/07_with_white_contour.zip)

**Comment by bodymovin** [comment]
hi, Essential properties are not supported. Unfortunately, AE doesn't expose an API to target the original values in order to export them.

**Comment by jetrotal** [comment]
Hi, I'm having the same issue. 
Is there a way to manipulate the properties inside a precomp, using it's layer name as reference?

Let's say I'm using a precomp called 'eyes' twice.

I renamed one as 'eyeA' and the other as 'eyeB'

can I reach eyeB,layer3,Transform,Scale using lottie_api? 
It would let me simulate essential properties through lottie api

**Comment by codysorgenfrey** [comment]
I've made a feature request with Adobe, please upvote if you care about this feature! 
https://community.adobe.com/t5/after-effects-ideas/expose-api-for-essential-graphics-panel-properties-in-comps/idi-p/13577608#M1801

**Comment by bodymovin** [comment]
essential properties are supported now in bodymovin

**Comment by msongz** [comment]
![CleanShot 2023-06-20 at 11 42 14@2x](https://github.com/airbnb/lottie-web/assets/2059694/0dce0ce3-5f87-4509-9e25-f94a7a80a0ef)
@bodymovin hi, am I misunderstand something about this support ?

**Comment by Matoseb** [comment]
The color property is is not working for me too like @nhanchu94

**Comment by JuzioMiecio520** [comment]
Bump, any progress here? Still not working for me (Bodymovin 5.12.1). Does anyone maybe have any alternative in the meantime?
