### ISSUE TITLE
Bodymovin/Lottie doesn't support >ES5 expressions

### ISSUE THREAD

**Issue by Sxxov** [airbnb/lottie-web#2404]
**Tell us about your environment**

* **Browser and Browser Version:** n/a
* **After Effects Version:** CC 2020

**What did you do? Please explain the steps you took before you encountered the problem.**
I tried to export a composition which included expressions that used ES6/ES2017 syntax (supported in the fancy new expressions engine).

Bodymovin tries to export it initially, but it fails when it hits a "controller" null layer with a few "Slider Control" effects, that is referenced in some of my expressions. I found that removing the referenced slider control enables it to export (as it errors out and disables the expression), but renaming it doesn't, as AE renames it across all expressions as well (which makes it so that it's all valid expressions).

Adding `'use javascript'` or `'use strict'` at the top of my expressions didn't help, but It successfully exported after I transpiled everything to ES5 using babel.

**What did you expect to happen?**
Bodymovin successfully exporting it.

**What actually happened? Please include as much _relevant_ detail as possible.**
Bodymovin displays a "Render Failed" error screen, and no file is exported.
![image](https://user-images.githubusercontent.com/50891910/102891416-1cdf1880-4499-11eb-8e84-20a6a3ae73bc.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/file/d/10MxopsSmogXGFzv7JUI8-RA0s7dY2Sld

**Comment by bodymovin** [comment]
him this should be fixed on version 5.7.6
