### ISSUE TITLE
Issue exporting AEE project in Body Movin

### ISSUE THREAD

**Issue by hikom06** [airbnb/lottie-web#2406]
Hello, 

I am beginner using AAE and Lottie 
I am facing an issue trying to export my animation to Bodymovin
the animation is not working

Project -->[Projet sans titre.aep.zip](https://github.com/airbnb/lottie-web/files/5736024/Projet.sans.titre.aep.zip)

MAC OS CATALINA 10.15.7

Chrome Version 87.0.4280.88 (Build officiel) (x86_64)

Adobe after effect 17.5.1

The preview in renderer is not working, and when I export a demo HTML the logo is not animated, 

could you please help ?

![image](https://user-images.githubusercontent.com/76528625/103014665-6e41e300-453f-11eb-90e6-aebb69ed512b.png)

**Comment by bodymovin** [comment]
Hi, unfortunately the write-on effect is not supported by the players.

**Comment by hikom06** [comment]
thanks a lot, 

is there a way or workaround to make this kind of effect ? and supported by the player.

kind Regards, 

Cyrille

**Comment by bodymovin** [comment]
I guess you can try to do a similar effect with masks

**Comment by kudanai** [comment]
Closing this issue for now. Please re-open if it's still relevant
