### ISSUE TITLE
Help me change core functionality to make playSegments reverse working. (Also a Feature request)

### ISSUE THREAD

**Issue by ivanjeremic** [airbnb/lottie-web#2408]
This is an issue for help and also a feature request.

Currently once you `playSegments` there is no way to play from the current frame to a **Specific** frame back, setting the `direction` to negative 1 and calling `play` is not a solution because I need to work precisely frame by frame.

When I go from `15` to `95` I want to be able to do `playSegments([95, 15])` and go from `95` back to `15`.

I found the function in the core library and I hope for sugguestions what we can do better here and if there is any way to work this out in this issue. Thanks

The `playSegments` function from this library.

```AnimationItem.prototype.playSegments = function (arr, forceFlag) {
    if (forceFlag) {
        this.segments.length = 0;
    }
    if (typeof arr[0] === 'object') {
        var i, len = arr.length;
        for (i = 0; i < len; i += 1) {
            this.segments.push(arr[i]);
        }
    } else {
        this.segments.push(arr);
    }
    if (this.segments.length && forceFlag) {
        this.adjustSegment(this.segments.shift(), 0);
    }
    if (this.isPaused) {
        this.play();
    }
};```

**Comment by bodymovin** [comment]
continued here https://github.com/airbnb/lottie-web/issues/1137
