### ISSUE TITLE
playToFrame from current Frame. (Feature Request)

### ISSUE THREAD

**Issue by ivanjeremic** [airbnb/lottie-web#2411]
No matter what Frame I'm currently at I want to have a `playToFrame` function when I want from my first Frame to frame `90` I do `playToFrame(90)` And when I want from `90` back to a smaller frame somewhere in the middle I want to be able to just do `playToFrame(15)` for example.

So no matter what Frame I currently am in, it should play in both directions and not just jump like with `goToAndPlay`

This is needed because `playSegments` does not work in both directions and also setting the direction to negative 1 with `playSegments` has not the same effect and we are not able to target a specific frame in the negative direction once we moved to a specific frame.

Also to do `direction(-1)` and then do `play()` doesn't help here because you can't target a specific Frame.

**Comment by bodymovin** [comment]
discussion continued on another issue
