### ISSUE TITLE
lottie text layer with incorrect char shape path data

### ISSUE THREAD

**Issue by jasonChen1982** [airbnb/lottie-web#2413]
[reference issue](https://github.com/bodymovin/bodymovin-extension/issues/66#L233)

**when i inspect data.json, i found someone has error path data.**
![image](https://user-images.githubusercontent.com/8683772/103351131-2a218600-4add-11eb-9e26-b5ea778ef40a.png)

**and following is lottie render screenshot.**
![image](https://user-images.githubusercontent.com/8683772/103351187-5a692480-4add-11eb-875d-6ef44159cc16.png)

**and this is my .aep file**
[text.zip](https://github.com/bodymovin/bodymovin-extension/files/5752902/text.zip)

After Effects version:17.1.2（Simplified Chinese version）

**maybe is here cause this problem:**

https://github.com/bodymovin/bodymovin-extension/blob/77dc882928bcd11d00afaf14867b066cfd7a5c1d/bundle/jsx/utils/textShapeHelper.jsx#L231-L234

**Comment by bodymovin** [comment]
Hi, those lines are needed to have AE rerender before exporting new chars. I exported your animation and I didn't get the same result. I guess it could be related to having AE in a different language, but I'm not sure.

**Comment by illusate** [comment]
I have the same problem

**Comment by illusate** [comment]
> I have the same problem
I got the problem solved by switching to English version of AE
