### ISSUE TITLE
freeze is not a function

### ISSUE THREAD

**Issue by AlexisMunozC** [airbnb/lottie-web#2422]
When I try to use freeze function i got an error. 'freeze is not a function'

**Comment by bodymovin** [comment]
Hi, `freeze` is a function of the lottie instance, not the animations. Try calling `lottie.freeze()` and see if that works.

**Comment by AlexisMunozC** [comment]
yes, I was using lottie.freeze(), but I remember that I was using lottie-react and it's probably that freeze is not available with that library.
