### ISSUE TITLE
How to avoid animation restarts on complete

### ISSUE THREAD

**Issue by AlexisMunozC** [airbnb/lottie-web#2424]
When my animation is complete it goes to start, how can I avoid that?, I want that when my animation finishes, it stays in the last frame.

**Comment by bodymovin** [comment]
hi, you should set loop to false when loading the animation

**Comment by AlexisMunozC** [comment]
yes, I had false, but when I use lottie.play() the animation starts but when it finishes it goes to the frame 0, and I wanted to keep it in the last frame, I had to use lottie.goToAndStop(lottie.totalFrames), but I recommend to add a prop to define it.
When I use lottie.playSegment I can't use lottie.totalFrames so I had to get manually the last frame of the playSegment, I think this function could be added in the library.
