### ISSUE TITLE
Lottie Displaying error size SVG on all browser iphone (5s, 6, 7, 8)

### ISSUE THREAD

**Issue by treavies** [airbnb/lottie-web#2425]
Hi i just realize there is a bug in ios browser.
i have a screen shot to explain.
![error-lottie](https://user-images.githubusercontent.com/13305718/104127727-5f0fc180-5396-11eb-8aeb-a1a9587992be.jpeg)

lottie version :
`https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.6.5/lottie.min.js`

problem : when i open my website in ios (chrome, safari) the animation icon size become bigger and smaller (blinking). There is no issue when i open in android phone and desktop.

if u want to see the problem please check on https://barong.biz

**Comment by bodymovin** [comment]
Hi, I don't think the issue is related to the library, it looks more related to your html dom tree and css properties. I'd suggest as a test that you do some tests, replacing the lottie animated svg with another static svg element, an animated svg via css and a lottie animation with the canvas renderer instead of svg and observe the results.

**Comment by treavies** [comment]
> Hi, I don't think the issue is related to the library, it looks more related to your html dom tree and css properties. I'd suggest as a test that you do some tests, replacing the lottie animated svg with another static svg element, an animated svg via css and a lottie animation with the canvas renderer instead of svg and observe the results.

there is no problem in another platform. this is only happened in ios.

**Comment by bodymovin** [comment]
@treavies that's helpful information. I still suggest that you try it with those other examples to identify the underlying problem.

**Comment by treavies** [comment]
Thanks i change html structure from html tag player to js player and it solved.
