### ISSUE TITLE
Slick slider with direction check and playSegment

### ISSUE THREAD

**Issue by samuelemarazzita** [airbnb/lottie-web#2433]
I'm trying to create a slider using Slick and .playSegment method to play the lottie from a specific frame to a specific frame.
I'm detecting if the user is clicking the next or prev button to play the lottie backward or forward changing the direction from 1 to -1, but it always plays forward. What am I doing wrong?

https://codepen.io/smarazzita/pen/BaLMNvo

**Comment by bodymovin** [comment]
hi, I think the jquery method `.click()` is not doing what you're expecting it to do. That method is executing the click function on that element and not validating if that was the button that wasclicked.  
Closing the issue because it's not related to the lottie library.

**Comment by samuelemarazzita** [comment]
Ok, I've now correctly triggered the `.click()` event, but as you see in the [example](https://codepen.io/smarazzita/pen/BaLMNvo), the direction is not working properly.

**Comment by samuelemarazzita** [comment]
Ok, I've just fixed it. Updated the example. Seems that `goToAndPlay` doesn't recognize `.setDirection`, instead the `.play` does.
