### ISSUE TITLE
Bodymovin render show no preview and do not work in Wordpress

### ISSUE THREAD

**Issue by to8gal** [airbnb/lottie-web#2434]
Mac OS Big Sur

Safari 14.0.2
After Effects 2020 17.5.1

I selected the composition, render it with the extension, not preview was available when the render was ready. tried anyway to show it on a Wordpress site with this output from the inspector

x = 1 === e.h ? e.s[s] : e.s[s] + (e.e[s] - e.s[s]) * h; < Undefined is not an object (evaluating 'e.e[s]'

The animation was a png with mask and a cylinder text from AE rotating around it.

supposed animation if successful ( as shown fromAE)
![Screenshot 2021-01-18 at 18 17 50](https://user-images.githubusercontent.com/7603472/104945870-a232eb80-59b9-11eb-8506-e8258d0bac8e.png)

result (not moving more likely only the original png file)
![Screenshot 2021-01-18 at 18 17 39](https://user-images.githubusercontent.com/7603472/104945978-b971d900-59b9-11eb-8a26-6367ba501c3c.png)

**Comment by bodymovin** [comment]
hi, can you share the .aep? IT seems you're using features that are not supported by the player, but I want to confirm.

**Comment by to8gal** [comment]
Hi there,

I guess no need to share it, the only feature used is the Cylinder which is a basic on AE, animated so to rotate, u can guess it how by the screenshot I sent, is the Cylinder Approved?

And the mask also sorry, there are 2 layer masked

**Comment by bodymovin** [comment]
unfortunately, the cylinder effect is not supported by the players
