### ISSUE TITLE
DUIK Animations not working in lottie_light

### ISSUE THREAD

**Issue by thejjthejj** [airbnb/lottie-web#2441]
Hi,

Due to the use of CSP (Content security policy) we can’t use the lottie webplayer on our site. So we have to use the light player. But for some reason the animations we made using DUIK are not working anymore. On the webplayer they are working fine but on the light version they don’t. I wanted to export my animations using the setting “Convert expressions to keyframes” I think this might be the solution, but then it stops rendering half way and says Render failed.

What could I do to fix this?

[Animation file link](https://drive.google.com/file/d/1DEC7IekYH_CszAo-eCSPUZabggoZwjO2/view?usp=sharing)

Thanks,

Jesse Johnson

**Comment by bodymovin** [comment]
Hi, I just tried exporting it and it worked correctly.
If you have them selected, can you uncheck guides and hidden layers and try again?
[data.zip](https://github.com/airbnb/lottie-web/files/5877574/data.zip)

**Comment by kudanai** [comment]
Hello. Since this issue has become stale I'm going to close it for now. Please re-open it if it's still relevant.
