### ISSUE TITLE
Drop shadow on moving object

### ISSUE THREAD

**Issue by watziznehm** [airbnb/lottie-web#2442]
I'm unable to get drop shadows to appear on moving objects. I've added in the filter size script.

```
rendererSettings: {
                filterSize: {
                    width: '600%',
                    height: '600%',
                    x: '-200%',
                    y: '-200%',
                },
            },
```

The drops shadows appear on the objects when they are static but disappear once they start to move. The then reappear when the object stops.

Is there any know fix for this.

Thank you!

**Comment by bodymovin** [comment]
hi, can you share a link with your implementation? Also what browser are you testing it on?

**Comment by watziznehm** [comment]
Hey there!

Here's a link to my Ae file along with a demo. https://drive.google.com/drive/folders/1luGAujyL72Izx6tj4Nxxz72E-tlpciKO?usp=sharing

Currently the drop shadows work fine in Chrome but they do not work in Fire fox.

Thank you!

**Comment by watziznehm** [comment]
Hi @bodymovin just wondering if you may have had a chance to take a look into this. I've got a client I'm working with and I'm wondering if I should find another solution.

Thanks so much!

**Comment by bodymovin** [comment]
sorry about the delay. Unfortunately this seems like a glitch from Firefox, and my attempts to solve it haven't succeeded.

**Comment by watziznehm** [comment]
Hey no worries! I ended up using a png and it actually improved the performance of the animation across most browsers so it's kind a win lol. Thanks for trying!
