### ISSUE TITLE
duik rig doesn't work / export

### ISSUE THREAD

**Issue by ErikNorden** [airbnb/lottie-web#2443]
**Tell us about your environment**
big Sur 11.1
After Effects 2020
Bodymovin 
Duik Bassel 16.2.27
* **Browser and Browser Version:**
* Chorme Version 87.0.4280.141
* **After Effects Version:**
17.6.

**What did you do? Please explain the steps you took before you encountered the problem.**
I rigged a comp with Duik Bones and structures

**What did you expect to happen?**
that it would be rendered out and display-able with bodymovin / Lottie-web

**What actually happened? Please include as much _relevant_ detail as possible.**
the duik parts that are done with duik are not exported / don't work

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/drive/folders/1q45ZfprV6tdWTFyWFuQtAP3MuJ-KfKPS?usp=sharing

thanks for any advice.

**Comment by henriqrossatto** [comment]
Hi @ErikNorden trying to access the files

**Comment by ErikNorden** [comment]
https://drive.google.com/file/d/1ELI8ui3k7vbdgZqnT0gvfiYH_re-glaw/view?usp=sharing
https://drive.google.com/file/d/1VGeyX-hreIkT2vcPmy0RZTq43y44kTiw/view?usp=sharing

**Comment by henriqrossatto** [comment]
I'm not so sure if use diuk with the puppet pin will works on lottie. Duik usually works if you create the structures from rigging part
![image](https://user-images.githubusercontent.com/30601233/106032842-beb4df00-60af-11eb-9ad6-c8f10368caf6.png)

and select "guides" on export settings
![image](https://user-images.githubusercontent.com/30601233/106032937-e015cb00-60af-11eb-8152-955e7a3fbd7c.png)

I believe the problem in your animation is the puppet pin

**Comment by ErikNorden** [comment]
okay, thank you for looking at it and sharing your thoughts.
