### ISSUE TITLE
Bodymovin does not render my image sequence

### ISSUE THREAD

**Issue by yorenu** [airbnb/lottie-web#2444]
Hello,

I tried to find an answer to my problem, found related issues but no answer.

Mac OS Mojave
Google Chrome Version 88.0.4324.96
After effect 2018

Following a webflow tutorial I wanted to animate a video on scroll 
https://www.youtube.com/watch?v=2djbqUOtFgg

If I can create a JSON with after effect without a problem, when I use a JPEG sequence, the project doesn't render anymore.
"allow scripts to write file...." is selected

I do not see the difference between the webflow sequence and mine. Any idea?

[calendar_Test folder.zip](https://github.com/airbnb/lottie-web/files/5882591/calendar_Test.folder.zip)

![Screen Shot 2021-01-27 at 7 25 26 PM](https://user-images.githubusercontent.com/78105042/106043693-14ed4680-60df-11eb-8555-c3c40b0cf599.png)
![Screen Shot 2021-01-27 at 7 25 08 PM](https://user-images.githubusercontent.com/78105042/106043716-1a4a9100-60df-11eb-89e9-16f96250acbf.png)
![Screen Shot 2021-01-27 at 7 24 32 PM](https://user-images.githubusercontent.com/78105042/106043737-1f0f4500-60df-11eb-8e5d-b526e6ec79a0.png)

thank you for your time

**Comment by bodymovin** [comment]
Hi, unfortunately exporting images is not support with AE 2018, you'll need to upgrade your version of AE to use this feature.
