### ISSUE TITLE
Workaround for Trim path?

### ISSUE THREAD

**Issue by mpulock** [airbnb/lottie-web#2445]
Trim path animations are not supported in Lottie. Is there any better workaround which replicates trim path? Thank you!

**Comment by henriqrossatto** [comment]
Hi @mpulock. Trim paths works in Lottie.

Could you give more information about the problem or share your file to take a look and understand what problem are you facing?

**Comment by mpulock** [comment]
> Hi @mpulock. Trim paths works in Lottie.
> 
> Could you give more information about the problem or share your file to take a look and understand what problem are you facing?

My bad! It's working fine now! Not sure why, the animations weren't showing before,
