### ISSUE TITLE
circular animation gone crazy

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [airbnb/lottie-web#2448]
Hello,
I'm trying to export this after effects sequence: https://we.tl/t-rwyci0nUYi to lottie and the first half is working fine, but the second which is circular animation is gone crazy (instead of smooth animation it's very fast and flaky). this is the json created https://we.tl/t-yzrifNitt8

**Comment by bodymovin** [comment]
hi, the links have expired. Are you using a wiggle expressions?

**Comment by ahmed-adly-khalil** [comment]
Yes, it uses wiggle. Sorry for posting this before reading the docs in depth.
