### ISSUE TITLE
Old Parser Supposed to Work?

### ISSUE THREAD

**Issue by yoedy108** [airbnb/lottie-web#2460]
Trying to install bodymovin on Win10, After Effects CS6 (have only 4GB RAM)
I know that the Extension is supported starting CC 2014, but I noticed the old jsx parser.
Should that work?

I followed the instructions to put it in ScriptsUI folder, but when I try to use it I get:
"unable to execute script at line 1. Too many brackets"
Is the old parser supposed to work with AE CS6?

**Comment by bodymovin** [comment]
hi, unfortunately the old parser is no longer maintained and is not compatible with the newer players
