### ISSUE TITLE
Animations on Internet Explorer 11 broke on versions ^5.7.5

### ISSUE THREAD

**Issue by pmoore95** [airbnb/lottie-web#2464]
Animations failed to render on IE11 on versions 5.7.5 and up. I noticed the composition inside the svg has changed when upgrading to this version and this is causing issues on IE11.

Downgrading to 5.7.4 fixed the issue for IE11

**Comment by bodymovin** [comment]
hi, can you share a failed animation?

**Comment by pmoore95** [comment]
This is the animation:

<img width="537" alt="Screenshot 2021-02-15 at 09 13 01" src="https://user-images.githubusercontent.com/57687000/107926825-1a1b1400-6f6e-11eb-96fb-bc632644709b.png">

**Markup in version ^5.7.5**

This is the markup generated in Chrome:
<img width="1213" alt="Screenshot 2021-02-15 at 09 26 39" src="https://user-images.githubusercontent.com/57687000/107928338-15eff600-6f70-11eb-9ada-8acc9699cf3d.png">

The animation is just blank in IE11 this is the markup generated: (some elements missing such as the image tags)
<img width="768" alt="Screenshot 2021-02-15 at 10 25 14" src="https://user-images.githubusercontent.com/57687000/107934556-1f7d5c00-6f78-11eb-996e-884f1babd9a0.png">

**Markup in version 5.7.4**

Markup in Chrome:
<img width="1222" alt="Screenshot 2021-02-15 at 10 34 04" src="https://user-images.githubusercontent.com/57687000/107935486-5c961e00-6f79-11eb-8abd-aa4485132e40.png">

The same markup is showing in IE11

**Comment by pmoore95** [comment]
@bodymovin Thanks for fix
