### ISSUE TITLE
Puppet Tools + Duik Add bones not working in json file (Bodymovin)

### ISSUE THREAD

**Issue by GioTay** [airbnb/lottie-web#2469]
Hello!! I know Bodymovin / Lottie doesn't support puppet tool.
However, here's my situation:
I've added puppet tool in my layer and then convert it to "Add Bones" via Duik, it doesn't work in my final json file :-(

After Effects Version : CC2020
Duik Version : 16.2.28

Thank you in advance!! :-*

[GioTay.zip](https://github.com/airbnb/lottie-web/files/6009716/GioTay.zip)

**Comment by bodymovin** [comment]
hi, unfortunately puppet tool is not supported by the players
