### ISSUE TITLE
Ios web loading problems

### ISSUE THREAD

**Issue by mrco-dev** [airbnb/lottie-web#2474]
**Tell us about your environment**
   I'm working on a simple webpage and I use bodymovin to play the animation. Everything worked well till at some point on IOS all browsers, animation started to load for a really long time, and my page is not working till animation is loaded. when the animation loads and the site start to be ready for use the animation is in the last state. I tried to use anim.setLocationHref from the documentation but my website console said that this is not a function. Yesterday (22.2.2021) at 10AM the animation worked fine on all browsers, but then suddenly started the issue on IOS browsers.
   
   Link to webpage:https://petnat.web.app/

* **Browser and Browser Version:**
*  All IOS mobile browser (iPhone,iPad)
* 
* **After Effects Version:**
AE 17.5
**What did you do? Please explain the steps you took before you encountered the problem.**
I was testing my webpage and all was fine, but then at some point on the apple I got an issue that I can't solve

**What did you expect to happen?**
 I expected to work properly like before and like on the android phone where everything works wery well

**What actually happened? Please include as much _relevant_ detail as possible.**

the animation takes about 30s to load and when it is loaded, it is already finished

**Please provide a download link to the After Effects file that demonstrates the problem.**
you can see the issue on https://petnat.web.app/

**Comment by bodymovin** [comment]
hi, this looks like an implementation issue. I don't think I can be of much help.
But regarding setLocationHref, you need to invoke it via `lottie.setLocationHref` since it's a library function.

**Comment by kudanai** [comment]
Hello. Since this issue has become stale I'm going to close it for now. Please re-open it if it's still relevant.
