### ISSUE TITLE
Rendering Never Starts

### ISSUE THREAD

**Issue by code-IM-perfect** [airbnb/lottie-web#2475]
**Tell us about your environment**
Windows 10, Bodymovin 5.7.6, After Effects 2020

* **Browser and Browser Version:**
Firefox 85.0.2

* **After Effects Version:**
* 17.5.0

**What did you do? Please explain the steps you took before you encountered the problem.**

- I tried to export the After Effects Composition named "Code" in the attached AEP.

**What did you expect to happen?**
- I expected it to render and export a JSON file.

**What actually happened? Please include as much _relevant_ detail as possible.**
- It never starts rendering. I've tried leaving it for an hour but it doesn't even start rendering. I have not just tried restarting AE, but have even reinstalled Bodymovin and purged the AE Cache but with no luck

![image](https://user-images.githubusercontent.com/77197959/108819755-3c053e00-75e1-11eb-8682-3aabdd48fe5e.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
[With shape.zip](https://github.com/airbnb/lottie-web/files/6027708/With.shape.zip)
- I exported the composition named "Code"

**Comment by bodymovin** [comment]
Hi, I was able to export the animation correctly. Are you using the default export settings?

**Comment by code-IM-perfect** [comment]
I disabled the Audio and enabled "create a report" and that's it, otherwise the settings were default.
However, I was able to export it correctly with Lottie Files Plugin. I can export other Animations with Bodymovin though. I think it's a problem with my After Effects if you are able to export, thanks for your time!
