### ISSUE TITLE
Gradient Issue even after all the names in English

### ISSUE THREAD

**Issue by mpulock** [airbnb/lottie-web#2476]
Hello,

I ma facing the issue exporting animation containing gradient fill. I checked the issues but didn't get any help. My windows, AE, layers etc everything is in English, so it's not a language issue. All the layers in shape layer. I saved the project before exporting, didn't help. Restarted AE, my PC, reinstalled Bodymovin but it's still having issue. 

May you please help me with the issue, Thank you!

[
![Capture](https://user-images.githubusercontent.com/58793382/108919217-a7123d00-7600-11eb-9371-bfac405afacb.PNG)
](url)

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by mpulock** [comment]
I would love to but weirdly can't replicate the issue anymore. It's rendering fine right now. Will definitely share the file, when it happens again.

**Comment by bodymovin** [comment]
ok, closing for now. Feel free to reopen if the issue reappears.
