### ISSUE TITLE
Only background of animation showing up in exported json file?

### ISSUE THREAD

**Issue by Caeeni** [airbnb/lottie-web#2479]
So i've made an aurora animation in after effects using various effects in the program and with a screen modifyer on to blend in with the PNG image i put as the background. I wanted to use this animation as a lottie animation in webflow. The issue i'm facing now is that when i render it out as a json file with the bodymovin plugin, only the background shows up for some reason. No sign of the aurora animation layer at all. 

[ribbon aurora2 folder.zip](https://github.com/airbnb/lottie-web/files/6053588/ribbon.aurora2.folder.zip)

**Comment by bodymovin** [comment]
Hi, unfortunately those type of effects are not supported by the players.

**Comment by Caeeni** [comment]
I suspected as much I suppose. Is it just those kind of effects that are not supported or all pixel/rasterized animations? It has to be vector?

**Comment by bodymovin** [comment]
there are very few rasterized effects that are supported. This is the list and it's only for web.
https://github.com/airbnb/lottie-web/wiki/Effects
