### ISSUE TITLE
Issue with rendering shape/gradient with bodymovin?

### ISSUE THREAD

**Issue by mandiag** [airbnb/lottie-web#2483]
Hi, I'm using After Effects CC to make a very short animation.

I'm rendering this shape: 

https://user-images.githubusercontent.com/79884456/109584076-ed6b0e80-7ace-11eb-88e8-2a0a90b2506e.mp4

But after render, one of the curves looks like this:

https://user-images.githubusercontent.com/79884456/109584199-1f7c7080-7acf-11eb-9619-53c0f76fd328.mp4

I have all layers and program in English, and is only one of the curves which is acting weird.... are there any solutions?
These are my render settings:

![image](https://user-images.githubusercontent.com/79884456/109584309-463aa700-7acf-11eb-91ad-c33c33524136.png)

Thank you!
aaa

**Comment by bodymovin** [comment]
hi, that loos like a masking issue. Can you share the .aep?

**Comment by mandiag** [comment]
Yep sure,
I'm actually using masks for both curved sections of the hearts, but one is working fine and the other one isn't :(

[animated logo.zip](https://github.com/airbnb/lottie-web/files/6093086/animated.logo.zip)
 Thx!

**Comment by bodymovin** [comment]
hi, unfortunately merge paths are not supported by the players
