### ISSUE TITLE
Does Bodymovin support Effect > Stylize > Glow in After Effects?

### ISSUE THREAD

**Issue by GioTay** [airbnb/lottie-web#2484]
Hi, I noticed that Bodymovin doens't support glow effect but not sure is there any alternative way to apply glow effect ( export to json via BodyMovin )in after effects?

Thanks!!!

**Comment by bodymovin** [comment]
hi, unfortunately there is nothing straightforward. You can try using the drop shadow effect or the gaussian blur effect if it fits your case.
