### ISSUE TITLE
Export problem - Rubberhose - Lottie - iOS & Android

### ISSUE THREAD

**Issue by bastien211** [airbnb/lottie-web#2485]
hi dudes, 

I work on an animation, i'm new on AE and Rubberhose. 
I thought I was following the rules correctly but I have some compatibility problems. 

With the Web player, my animation works well but when I import the JSON on mobile ( or with Lottie App QR CODE ), the character's arms disappear :( 

Someone can help me ? 

Animation : https://lottiefiles.com/share/0myq0zpm
AE file : https://drive.google.com/file/d/1Jf7LUAfDvQmTYgymywEA7PZyv9IK6gKx/view?usp=sharing

**Comment by bodymovin** [comment]
hi, expressions are not supported on the native player. You can try exporting the animation selecting convert expressions to keyframes on the settings of the composition in bodymovin.
