### ISSUE TITLE
Lottie Player Keyframe Render Issue

### ISSUE THREAD

**Issue by ision-industries** [airbnb/lottie-web#2486]
So I can't tell if this is an "issue"  or just a misunderstanding of how the Lottie player works but I will try to explain my scenario as best I can. The "issue" is when I preview my animation on iOS, android or web the animation plays weird compared to how it renders in After Effects. My project is setup with one shape layer and two shape groups. Each group has 5 keyframes on the timeline. The middle 3 keyframes are spaced 1 frame apart on a 60fps timeline. But when the animation is rendered on iOS, android or web its like the animation plays through the 1 frame between each of the three keyframes. Check out this screenshot of my keyframe setup
![Iso Square 8 Timeline keyframe setup](https://user-images.githubusercontent.com/58711145/110142220-ef212480-7da3-11eb-8f07-d745669d5c21.png)

[Here](https://youtu.be/lAdwN4Ld44M) is a screen recording of how I set up my project timeline.[Here](https://youtu.be/W-ZuJl_XPvI) is a screen recording from when I tested the animation on the MacOS app. [Here](https://youtu.be/6BzMEDX9Zmo) is a screen recording of previewing the animation on Google Chrome [Desktop]. [Here ](https://youtu.be/Gj3tHFE6hWY)is a screen recording of how the animation should actually play rendered with the LottieFiles AE extension. As you can see in the screen recording, I am able to scrub between frames 27 & 28 with the lottie web player. What are those "frames" in between frame 27 & 28? In After Effects I am unable to scrub between individual frames. 

The version of After Effects I am using is 17.5

 Here is the link to the after effects [Project](https://drive.google.com/file/d/1g7UqFsCNLkxAvV86t5WeXm_JGV-4HXnF/view?usp=sharing) File

**Comment by bodymovin** [comment]
browsers and native devices usually play at 60fps or more. So all players interpolate between frames. The web animations have a method called `setSubFrame` to prevent that behavior.
https://github.com/airbnb/lottie-web#setsubframeusesubframes
but in order to get the same behavior on all platforms you should use `hold` keyframes on AE which have that intended behavior.

**Comment by ision-industries** [comment]
@bodymovin if I convert the two middle keyframes to hold keyframes then they will lose their easing value right? I rarely ever use hold keyframes

**Comment by bodymovin** [comment]
@ision-industries right, hold keyframes don't have easing because they don't interpolate to the following value.

**Comment by ision-industries** [comment]
@bodymovin would hold (ease in) or hold (ease out) keyframes work best in this scenario? I never even knew these type of keyframes existed until now. ![download.png](https://user-images.githubusercontent.com/58711145/114271813-55234c00-99e1-11eb-92b4-3e33400d083e.png) 

I just found this image reference online.

**Comment by bodymovin** [comment]
it depends on what you need, but as a general answer, yes, any non interpolated transition should use a hold type keyframe

**Comment by ision-industries** [comment]
@bodymovin okay that makes sense. Thank you for your help troubleshooting this with me.
