### ISSUE TITLE
Path arrow animation didn't export correctly

### ISSUE THREAD

**Issue by dmassarellaot** [airbnb/lottie-web#2489]
Hello,

I'm encountering an issue during the animation of an arrow. I think the problem is in the "Path arrow" effect but I can't figure out why and whether to fix it.

On my AE preview, I see the arrow's size correctly but in the export, the tail is too thin while the head is bigger. I tried to export converting the expressions in keyframes without results.

Is there a workaround to get the expected result (that is the arrow that spins like in the preview)?

Thank you.

[Arrow_around.aep.zip](https://github.com/airbnb/lottie-web/files/6103057/Arrow_around.aep.zip)

**Comment by bodymovin** [comment]
hi, unfortunately the "modes" on the Advanced menu of the Range Selectors of text animators are not supported by the players.
