### ISSUE TITLE
How do you prevent Lottie from adding inline styles and attributes to the element?

### ISSUE THREAD

**Issue by IcyFoxe** [airbnb/lottie-web#2492]
Is there a way to prevent Lottie from adding inline styles like `style="width: 100%; height: 100%` to the SVG element that it creates?

Because otherwise adding **id** or **className** to style the element's size is pointless, because inline styles always have priority over external stylesheets and then your last resort is using `!important`, which is usually a bad approach.

Also, is there a way to remove `width` and `height` attributes from the SVG? I know viewbox can be configured, which is great, but these two attributes do harm for responsive design and it would be better if they weren't there.

**Comment by bodymovin** [comment]
hi, does this help for what you need?
https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#viewboxonly-svg-renderer

**Comment by IcyFoxe** [comment]
I somehow completely overlooked the viewBoxOnly option, even though I read this page. Yes, that's what I was looking for. Thank you.
