### ISSUE TITLE
Classname shows success but does not work

### ISSUE THREAD

**Issue by Zoom1111** [airbnb/lottie-web#2499]
* **Browser and Browser Version: Microsoft Edge Version 89.0.774.57 (Official build) (64-bit)**
* **After Effects Version: 2021 18.0.0.39**

**I use rendererSettings:className options, it do show the class name in svg tag, but when I try to change its css style like svg.className{xxxx}, it doesn't work.**

**I hope to get some help to control the svg animation.**

I use this loadAnimation method:
![image](https://user-images.githubusercontent.com/49567307/112131801-e2eef100-8c04-11eb-95c4-e17634e7dfc3.png)
It should be set the className of the animation to "building_1995", it did show:
![image](https://user-images.githubusercontent.com/49567307/112131975-17fb4380-8c05-11eb-9fb6-9bd9637b7be1.png)
However, after I change the style by edit svg.building_1995 css, It didn't change it.
![image](https://user-images.githubusercontent.com/49567307/112132275-61e42980-8c05-11eb-888d-a9b91b940750.png)

**I think this problem has nothin to do with AE files. I hope I can know how to control the svg css style, thanks.**

**Comment by bodymovin** [comment]
hi, css opacity values range from 1 to 0
