### ISSUE TITLE
eval() expression not working.

### ISSUE THREAD

**Issue by mehras1991** [airbnb/lottie-web#2502]
basically I was trying to use a layer's 'text.sourceText' as other layer's expression controller as followed.

_eval(thisComp.layer("script").text.sourceText.value)_

it works in AE, but once exported. it doesn't work in the browser.

**Comment by bodymovin** [comment]
hi, unfortunately lottie uses eval to parse expressions and nested eval can break.
Is there a reason why you need to use eval instead of the actual value or casting it to another primitive type?

**Comment by mehras1991** [comment]
> hi, unfortunately lottie uses eval to parse expressions and nested eval can break.
> Is there a reason why you need to use eval instead of the actual value or casting it to another primitive type?

I do have cases where using eval() benefits. It might sound crazy, I have conditions applied to 81 layers. and they are all connected to one text.sourceText . Let's say the user input says 'Texas'. all 81 layers will react in a certain way. So it's more logical to control animation with one script rather than 81 (multiplied by how many lines of code).


So in my case and research I actually found out the eval() does in fact decreases file size and the pc/mac fans running (as chrome loves to do that).

This is just one of my 3 projects that have massive lines of costume scripts.

Sorry for long explanation. Also the bodymovin export takes too much time when (at least) 81 layes, each have maybe 40 lines of code.

**Comment by bodymovin** [comment]
can you share a .aep with this setup?

**Comment by mehras1991** [comment]
> can you share a .aep with this setup?

The project content is confidential. But I will prepare the same scene with sample shapes and object and share it with you here soon.

**Comment by bodymovin** [comment]
so just to make sure I follow, you have the expression in a single layer and then you want to reuse the same expression on multiple other layers so you reduce file size?

**Comment by mehras1991** [comment]
> so just to make sure I follow, you have the expression in a single layer and then you want to reuse the same expression on multiple other layers so you reduce file size?

exactly

**Comment by bodymovin** [comment]
and how do you know it decreases fans? Have you succeeded in using it?

**Comment by mehras1991** [comment]
I actually found 20 percent faster performance. I tried different scenarios to compare. On another case that I had to use png sequence to make a project look like it has a video in it (basically 25fps png back to back for 30 seconds which is a massive 750 png file) I actually found 50 percent performance improvement.

I may sound crazy doing this with lottie, I'm just standing on experimental grounds with my projects. (and I should say, so far lottie is doing hell of a job, I'm just trying to maximize efficiency and performance)

**Comment by bodymovin** [comment]
interesting data!
So you managed to have some expressions working with this eval solution and some other not?

**Comment by mehras1991** [comment]
with lottie I couln't just get it to work natively. I managed to test it by calling the script other ways.

Which we get to our point with eval() . it's a huge advantage here.

**Comment by mehras1991** [comment]
while I'm preparing the file to send in half an hour. I have another export support (for exporting .json table that is imported to AE) should I open a new issue for that? I can just attach those files and my notes with this one together.

**Comment by bodymovin** [comment]
the json table has already an old ticket, but it didn't get much traction and it's not a simple implementation.
Regarding this scenario, I'll wait for the example and take a look.

**Comment by mehras1991** [comment]
appreciate it

**Comment by mehras1991** [comment]
> the json table has already an old ticket, but it didn't get much traction and it's not a simple implementation.
> Regarding this scenario, I'll wait for the example and take a look.

Hi again Hernan, Sorry for a bit delay in my reply. The files and everything you need to know is in the link.
I dropped a readme for you to get a sence of what's going on in the project and the AE.

[](https://we.tl/t-ehus34Wl3c)

**Comment by bodymovin** [comment]
I've been doing some tests on the animation, and unfortunately the way it's being implemented will not work.
First of all, since the code is being exported as the text source of a text layer, you'll need to write valid JS in order for it to work.
Bodymovin compiles AE expressions into valid ES5 code during export but it doesn't for text layers since it's text.
So you would need for example:
- to explicitly declare variables (`var s = 'aa'` instead of `s='aa'`)
- instead of doing `color1/255` you would need to do `div(color1,255)`  
- find a different way of targeting the each layer. `thisLayer.name` will not work, since some browsers don't allow to rename functions. Bodymovin during export looks for all `.name` references and changes them to `._name`, and assigns the layer name to a `_name` property of the function that represents the layer.
With those 3 changes I achieved to make it work for the "Color Script", but for the third one I had to change the data on the json.

**Comment by bodymovin** [comment]
Regarding the support for json files as footage, would you mind testing this build?
[bodymovin.zip](https://github.com/airbnb/lottie-web/files/6254769/bodymovin.zip)

**Comment by mehras1991** [comment]
> I've been doing some tests on the animation, and unfortunately the way it's being implemented will not work.
> First of all, since the code is being exported as the text source of a text layer, you'll need to write valid JS in order for it to work.
> Bodymovin compiles AE expressions into valid ES5 code during export but it doesn't for text layers since it's text.
> So you would need for example:
> 
> * to explicitly declare variables (`var s = 'aa'` instead of `s='aa'`)
> * instead of doing `color1/255` you would need to do `div(color1,255)`
> * find a different way of targeting the each layer. `thisLayer.name` will not work, since some browsers don't allow to rename functions. Bodymovin during export looks for all `.name` references and changes them to `._name`, and assigns the layer name to a `_name` property of the function that represents the layer.
>   With those 3 changes I achieved to make it work for the "Color Script", but for the third one I had to change the data on the json.
>   EDIT: you could do `var name = thisLayer._name || thisLayer.name;` and it would work for both AE and lottie

Thank so much for the info.knowing the text source can become ES5 just gave me some new ideas to experiment as well. 🍻

**Comment by mehras1991** [comment]
> Regarding the support for json files as footage, would you mind testing this build?
> [bodymovin.zip](https://github.com/airbnb/lottie-web/files/6254769/bodymovin.zip)

Sure, gladly. I will test and get back to you.

**Comment by mehras1991** [comment]
the json is exported and I can see it addressed in the code _(in the .hml)_. But in the browser the text layer name is shown as the text, not the value that supposed to come from the table.

**Comment by bodymovin** [comment]
Are you using the player that comes with the zxp? Have you tried the demo export too?

**Comment by mehras1991** [comment]
Forgot to mention, I exported with demo. that where this is happening

**Comment by bodymovin** [comment]
can you share the exported files?

**Comment by mehras1991** [comment]
[demo.zip](https://github.com/airbnb/lottie-web/files/6255241/demo.zip)

**Comment by bodymovin** [comment]
I see "America/Chicago" as City, which is the value set on the json file. Am I missing something?

**Comment by mehras1991** [comment]
no no, that that part is fine, but opening the html in the browser, for example it just says "city" instead of "America/Chicago".

I expected 5.7.8 to actually show that part, just like inside the AE

**Comment by bodymovin** [comment]
yes, that's how it works. But you need to open it with a web server, since browsers don't allow to load .json files when loaded directly from the file system.

**Comment by mehras1991** [comment]
I'm not familiar with API and how they work in the back (how they do the magic and send the data).
does uploading it to my own host and loading it work? I'm trying to test that now

**Comment by mehras1991** [comment]
> yes, that's how it works. But you need to open it with a web server, since browsers don't allow to load .json files when loaded directly from the file system.

Yea it actually work.
http://mehrasirani.com/Lottie/demo/

I can't buy you a drink here, but on the next build's release I will drop some bucks for you guys
🍻

P.S with more assets supported to lottie with every build. Maybe it's better to saperate file formats by folder, or changing image folder name something else. (me personally I'm used to web app foldering system like rails for example)

**Comment by bodymovin** [comment]
Yes I'll look into managing / renaming folders in a future release.
Glad it works, for now it only supports json files.
