### ISSUE TITLE
Bad performance with 3D Renderings

### ISSUE THREAD

**Issue by FulytheFox** [airbnb/lottie-web#2509]
* **Browser and Browser Version:** Chrome latest version, Firefox latest version
* **After Effects Version:** After Effects CC 2018
* **Local Server:** Visual Studio Code Live Server

**What did you do? Please explain the steps you took before you encountered the problem.**
I have built a after effects-project and made sure that all the functions work with lottie later on the web.

**What did you expect to happen?**
The exported project renders smoothly and well in the browser.

**What actually happened? Please include as much _relevant_ detail as possible.**
Unfortunately, the CPU load is very high and the animation has low FPS. I have figured out that if I change the expressions to keyframes on the export, that the project displays much faster when the page loads.
Among other things, I have tried other render types, but my project only works with html, because it must be rendered in 3D. I also tried to reduce the CPU usage with `animation.subframe(false)` but unfortunately this does not work.
I hope someone can help me with this problem for my project!

![Website-Performance](https://user-images.githubusercontent.com/37185496/113589625-e4bbaa00-9631-11eb-9454-7e32fee7008f.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
Here is the project file and a demo page: [project.zip](https://github.com/airbnb/lottie-web/files/6258821/project.zip)

**Comment by bodymovin** [comment]
Hi, it seems the animation is using around 566 complex expressions, which probably is too much for browsers to render in real time.
