### ISSUE TITLE
Uncaught TypeError: g.getLottie is not a function

### ISSUE THREAD

**Issue by hawk-garethf** [airbnb/lottie-web#2510]
**Tell us about your environment**
I'm building a landing page to be viewed on a web browser. I'm building using bootstrap 4 and VScode. Latest version is here: https://hawk-garethf.github.io/

* **Browser and Browser Version:**
Google Chrome: Version 89.0.4389.90 (Official Build) (x86_64)
* **After Effects Version:**
After Effects Version: 2021

**What did you do? Please explain the steps you took before you encountered the problem.**
I took the example (Sync Lottie with scroll) detailed on this page: https://lottiefiles.com/interactivity
and tried to add my own animation here: https://assets9.lottiefiles.com/packages/lf20_nre2i7dc.json

I added the lottie player to the html and the scroll specific JS to the bottom of the page and then added the Lottie library to the head tag this link: <script src="https://unpkg.com/@lottiefiles/lottie-interactivity@0.1.4/dist/lottie-interactivity.min.js"></script>

**What did you expect to happen?**
I expected the visual to appear for it to animate on scroll.

**What actually happened? Please include as much _relevant_ detail as possible.**
This animations doesn't appear on the screen and when I inspect element it says withing the Console log that there is a Uncaught TypeError: g.getLottie is not a function

<img width="1205" alt="Screenshot 2021-04-06 at 11 49 09" src="https://user-images.githubusercontent.com/67474273/113699940-1eda8980-96ce-11eb-90ec-e5777dd28620.png">

If I click into those error logs I have an error in the library for .getLottie();
<img width="889" alt="Screenshot 2021-04-06 at 11 50 02" src="https://user-images.githubusercontent.com/67474273/113700037-3f0a4880-96ce-11eb-8357-943d35638fe3.png">

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://assets9.lottiefiles.com/packages/lf20_nre2i7dc.json

**Comment by bodymovin** [comment]
hi, this repository is not the location of those libraries.
Can you post the issue of the lottiefiles github repo?
https://github.com/lottiefiles
