### ISSUE TITLE
Rubberhose 2 / Lottie - auto rotate problem

### ISSUE THREAD

**Issue by shokrizorid** [airbnb/lottie-web#2515]
Hello :) 

I worked on an animation with Rubberhose 2 + Lottie.
Everything is ok but except 1 problem. When I check "Auto Rotate" propertie I have a bug on the shoulder and the sword. You can see it in the preview.

Preview https://lottiefiles.com/share/gkmqjsqv
AE File https://www.dropbox.com/s/1l5scfa3py0u1w5/Quick%20Test.aep?dl=0

Have you an idea? 
Thanks a lot!

**Comment by bodymovin** [comment]
hi, if you have a reduced example of the issue, it might get checked faster

**Comment by shokrizorid** [comment]
Here is a reduced example 
If you check the shoulder, you will see a glitch 

AE https://www.dropbox.com/s/1l5scfa3py0u1w5/Quick%20Test.aep?dl=0
Preview https://lottiefiles.com/share/qzgxemux

**Comment by shokrizorid** [comment]
I have found the problem! 
I have seen your answer on another post

-> anim.setSubframe(false); this one fix my problem!

Thanks a lot!
