### ISSUE TITLE
Lottie web player on mobile devices

### ISSUE THREAD

**Issue by Magidorit** [airbnb/lottie-web#2516]
Hi,
This is more of a general question than a specific issue - if a web page containing lottie animation is opened on a mobile device, would it be rendered using lottie web (with all the web features) or the relevant mobile player (ios/android)?

Thanks!

**Comment by bodymovin** [comment]
hi, yes it will be rendered using lottie-web

**Comment by Magidorit** [comment]
Great to know, thanks!
