### ISSUE TITLE
Render issue with toolbar in Safari Version 14.0.3

### ISSUE THREAD

**Issue by segill** [airbnb/lottie-web#2518]
The issue appears to be directly related to the Toolbar and its use of it in Safari Version 14.0.3 (16610.4.3.1.7). Anytime the Toolbar is visible as a UI element, the animation is jittery and stutters. It's possible that the issue just appeared with an update to the Safari browser. I am uncertain if the bug is on Safari, but the issue is directly related to the Toolbar (play, stop button, and timeline). Whenever the Toolbar is removed, the animation plays smoothly. This issue is visible in both desktop and mobile (IOS 14.4.2)

Video below for reference.

Anytime the Toolbar is visible as a UI element, the animation is jittery and stutters. When the Toolbar is removed, the animation works perfectly.

https://user-images.githubusercontent.com/48763455/114936083-982a5880-9e01-11eb-913c-54af710c0981.mov
[RENDER ERROR 12.50.28 PM.zip](https://github.com/airbnb/lottie-web/files/6321024/RENDER.ERROR.12.50.28.PM.zip)

**Comment by bodymovin** [comment]
hi, if you're using the lottiefiles player, can you report the issue to their team?
