### ISSUE TITLE
Lottie animation not showing on the preview 

### ISSUE THREAD

**Issue by chonkyloutre** [airbnb/lottie-web#2519]
Hi, I have a problem with my after effect and lottie extension. 
I made an animation  with some ai layers, and then transformed them into some shape layers. Then I put them into 3d layers and created a camera that zoom onto my layers.
When I export my animation the render is totally transparent and I don't understand why, can someone help me please I absolutely need this animation for school and i'm kind of desperate.

this is what my render show: 
![image](https://user-images.githubusercontent.com/77484472/115061394-6c829d80-9ee9-11eb-949a-0e3b8d3c0782.png)

and it should look like this: 
![image](https://user-images.githubusercontent.com/77484472/115061425-75736f00-9ee9-11eb-93c1-a1657a59b942.png)

**Comment by bodymovin** [comment]
hi, 3d is not supported on the ios and android players

**Comment by chonkyloutre** [comment]
I know that it's not but I'm trying to put it on a wordpress website

**Comment by bodymovin** [comment]
have you tried setting the renderer to `html`?
https://github.com/airbnb/lottie-web/wiki/loadAnimation-options#renderer-default-is-svg
