### ISSUE TITLE
PNG sequence doesn't show up in 5.7.8

### ISSUE THREAD

**Issue by kfitfk** [airbnb/lottie-web#2538]
**Tell us about your environment**

* **Browser and Browser Version:** Chrome 90
* **After Effects Version:** 18.1.0

**What did you do? Please explain the steps you took before you encountered the problem.**
Download the attachment and export comp 1 with image embedded and use canvas renderer to display the result.

I've tried using bodymovin 5.6.2, 5.6.10, and 5.7.8 to export the JSON with images embedded.

With 5.6.2 and 5.6.10, if I change the demo HTML file to use canvas renderer, things are good.

But if I use 5.7.8, and the canvas renderer in the exported demo file, there's an error in the browser console.

**What did you expect to happen?**
PNG sequence animation should render.

**What actually happened? Please include as much _relevant_ detail as possible.**
PNG sequence not rendered.

When using lottie-web 5.7.8, png sequence animation doesn't render.

If I use lottie-web 5.6.10 or 5.6.2, even though I export the JSON using bodymovin 5.7.8, everything looks fine.

**Please provide a download link to the After Effects file that demonstrates the problem.**
[png_sequence.zip](https://github.com/airbnb/lottie-web/files/6439624/png_sequence.zip)

**Comment by bodymovin** [comment]
hi, can you share a link with the implementation or the rendered files?
I exported it and it worked fine here
