### ISSUE TITLE
Track Matte issue with BodyMovin, works with lottie-player

### ISSUE THREAD

**Issue by JimmyDThing** [airbnb/lottie-web#2546]
**Tell us about your environment**
Mac OS 10.15.7

* **Browser and Browser Version:**
* Chrome Version 90.0.4430.93 (and OBS web source)
* **After Effects Version:**
* AE 2021 - 18.2.0

**What did you do? Please explain the steps you took before you encountered the problem.**
I exported a logo animation with track mattes (https://assets2.lottiefiles.com/packages/lf20_82tpxbqw.json).  When I run with lottie-player everything looks correct (left in screenshot), but when I use bodymovin to load and play the animation, the track mattes show up improperly (right in screenshot). 

![image](https://user-images.githubusercontent.com/50872562/118504362-6f93c800-b6f9-11eb-9f8a-b14b5cce64ae.png)

**What did you expect to happen?**
For bodymovin to display the same animation in the same way.

**What actually happened? Please include as much _relevant_ detail as possible.**
It appears as though the track matte shapes are exporting as regular shapes, but I'm not sure.  They are not masking properly and are showing up as the grey shapes I created them as.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/lg30basecc6jam1/UnionLogo.aep?dl=0

**Comment by bodymovin** [comment]
hi, can you share a link with the implementation?

**Comment by JimmyDThing** [comment]
Hey yeah, sorry.  You can see the behavior here:  https://nearlythere.live/BodyMovinIssue

**Comment by bodymovin** [comment]
it seems you're using the canvas renderer that doesn't support track matter masks unfortunately. Can you try with the svg renderer?

**Comment by JimmyDThing** [comment]
Ah yeah sorry I edited the original comment.  I swore I tested this, and this is now working.  I am sorry!  Closing and thanks.
