### ISSUE TITLE
Lottie extention not working (empty panel) after update

### ISSUE THREAD

**Issue by RigonK** [airbnb/lottie-web#2551]
**Tell us about your environment**

* **Browser and Browser Version: Google Chrome Version 90.0.4430.212 (Official Build) (64-bit)**
* **After Effects Version: 18.1.0**

**What did you do? Please explain the steps you took before you encountered the problem.**
Updated to the newest version of Lottie.

**What did you expect to happen?**
I expected Lottie extension to load properly

**What actually happened? Please include as much _relevant_ detail as possible.**
The panel is just empty when I load lottie.
https://imgur.com/Ksbkc7e

**Please provide a download link to the After Effects file that demonstrates the problem.**
Not related to a specific file

**Comment by bodymovin** [comment]
hi, that panel belongs to LottieFiles, can you reach out to the lottieFiles team?
