### ISSUE TITLE
Issue using canvas renderer with some animations

### ISSUE THREAD

**Issue by emabellor** [airbnb/lottie-web#2552]
Problem:

I've found problems rendering some Lottie animations using the canvas renderer provided with the lottie-web library. The problem seems to be only with the canvas renderer, because the same animation, using the SVG renderer works without issues. 

For example, if you try to run the following animation
https://lottiefiles.com/62860-ftx200

![image](https://user-images.githubusercontent.com/6153669/119532344-697d9700-bd4a-11eb-8991-898bb2a01d59.png)

Using the canvas renderer (fiddle provided)
https://codepen.io/edermauricioa/pen/bGqRqwg

![image](https://user-images.githubusercontent.com/6153669/119532273-59fe4e00-bd4a-11eb-8a6e-3c6c99886ed3.png)

You can see that some components of the truck get rendered incorrectly, and also, some components like rectangles start to appear.

As said, this issue occurs only with canvas renderer. Unfortunately, using the SVG renderer in the project that I'm working on is not an option.

Environment:

Browser: Chrome
Browser Version: 90.0.4430.212 
After Effects version: Does not apply

What did I do?
Try to render the following lottie JSON file
https://assets5.lottiefiles.com/private_files/lf30_1mukjnbu.json

Using the canvas renderer.

What did you expect to happen?
I expect that the animation runs exactly as shown in the SVG renderer, and the preview shown in this link
https://assets5.lottiefiles.com/private_files/lf30_1mukjnbu.json

What actually happened? 
Some components of the animation got rendered incorrectly, as described in the problem section

Download link of the lottie JSON file:
https://assets5.lottiefiles.com/private_files/lf30_1mukjnbu.json

Fiddle:
https://assets5.lottiefiles.com/private_files/lf30_1mukjnbu.json

Thank you.

Update:

In the next links, you can find other files which have issues when they're rendered in canvas.

https://lottiefiles.com/62983-glitch
https://lottiefiles.com/62860-ftx200
https://lottiefiles.com/62810-empty-project
https://lottiefiles.com/62423-chameleon 
https://lottiefiles.com/62408-camera-infographic
https://lottiefiles.com/62333-acquire-anim
https://lottiefiles.com/61942-first-electric-battery-was-invented-by-count-alessandro-volta
https://lottiefiles.com/61864-tenis-comprado
https://lottiefiles.com/61918-code-animation
https://lottiefiles.com/61729-man-photography-social-media

Thanks you.

**Comment by bodymovin** [comment]
hi, unfortunately the canvas renderer doesn't support track matte masking. You should use the svg renderer for those.
