### ISSUE TITLE
Stuck on images exporting (5.7.9)

### ISSUE THREAD

**Issue by RealSnowKid** [airbnb/lottie-web#2555]
**Tell us about your environment**
Windows 10

* **Browser and Browser Version:** N/A
* **After Effects Version:** 2021 / 18.1.0

**What did you do? Please explain the steps you took before you encountered the problem.**
Downloaded bodymovin 5.7.9 from aescripts and installed with ZXP Installer. Started to render one of the comps in my project with an empty queue, with a custom name and directory.

**What did you expect to happen?**
I expected it to render everything completely and create a json file with the custom name "teamVersus.json" at the selected directory.

**What actually happened? Please include as much _relevant_ detail as possible.**
Whenever it got to exporting images, it quickly did the first two, but then it got stuck on the last one. Then I removed the all but 1 picture, which was not the initial problematic one, and it still got stuck on exporting it. I have allowed Scripts to write to disk and use network in the settings, tried reinstalling bodymovin, did not change anything.

**Please provide a download link to the After Effects file that demonstrates the problem.**
GDrive: https://drive.google.com/file/d/1cLURHdMpkwDRXarSl_79vATFMmjskzZO/view?usp=sharing

**Comment by kevinbevers** [comment]
I went into settings with the cog wheel and changed the assets option to use original asset and instead of compression and it worked as expected.
![image](https://user-images.githubusercontent.com/25659609/120686098-eaeacd00-c4a0-11eb-86ef-69ac07f88400.png)

**Comment by rotemgrid** [comment]
Checking "copy original assets" works fine for me too
but the project is heavy as it is and any option of reducing it is needed
I hope they'll fix this bug soon

Thanks for the workaround tip!

**Comment by bodymovin** [comment]
hi! version 5.7.10 fixes the issue. Thanks for reporting it and sorry about that!

**Comment by bodymovin** [comment]
version 5.7.10 was still failing on some Macs, version 5.7.11 should work on all systems

**Comment by vickychinghk** [comment]
it seems it's still happening on 5.10.0 :(
![image](https://user-images.githubusercontent.com/63624554/205923212-7341cd18-da28-4276-8fb9-1d962c3f50fc.png)
