### ISSUE TITLE
Question: Is there a way to make only some parts of lottie animation clickable?

### ISSUE THREAD

**Issue by jdobrev** [airbnb/lottie-web#2560]
I would think 'no' but just to make sure. 

I'm using React and referencing the div container with useRef. If I put an 'onClick' on the div the whole animation container would be clickable. Is it possible to make it so you can only listen for events on certain parts of an animation?

I saw that it's possible to put references on certain layers and maybe I should use those but I'm not sure if that would be useful in my case and if yes - how to use that functionality in a React component
https://github.com/airbnb/lottie-web/wiki/SVG-and-HTML-ids-and-classes-to-reference-via-css-or-select-via-Javascript

**Comment by bodymovin** [comment]
Yes, I think the best approach is add a class name or an id to your layer in AE.
Once the animation is loaded you can imperatively look for the element by id and add an event listener to it. Once you have the react Ref, you can do `element.getElementsByClassName()` or directly do `document.getElementById()` and add the listener to that selected element.

**Comment by jdobrev** [comment]
That sounds great, thank you! 
Also, I'm a bit new to Github, am I supposed to close the 'issue' now? I know you're supposed to close when your issue is fixed. Would you prefer to close or leave questions like that open or?

**Comment by jdobrev** [comment]
![image](https://user-images.githubusercontent.com/69385803/122767874-c158e080-d2ab-11eb-904f-4419219380bb.png)
Is it enough to just change 'Fill' here with '#someId' or '.someId' to be able to find the HTML doc?

**Comment by bodymovin** [comment]
you'd need to add new properties: "cl":"someClass", and "id":"someId" to work.
Notice the "#" and "." are not necessary.

**Comment by jdobrev** [comment]
Thanks, it worked!
