### ISSUE TITLE
unable to execute script at line 184

### ISSUE THREAD

**Issue by zfxmgroup** [airbnb/lottie-web#2568]
**Tell us about your environment**

* **Browser and Browser Version:** Chrome
* **After Effects Version:** AE 17.1.4

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?** Render error. "Unable to execute script at line 184. After Effects error. Unable to set "workAreaDuration". Value -0,97 out of ranger 0,03 to 2,27.

**What actually happened? Please include as much _relevant_ detail as possible.** 
![error](https://user-images.githubusercontent.com/86265431/122825319-c4ee6680-d2af-11eb-86d0-c29fc6744f3c.gif)

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
@zfxmgroup there's probably some audio or image sequence or another type of layer that is failing to be exported because of it's duration or position in the work area.
If you can share a reduced version of the project I'll take a look at it.

**Comment by zfxmgroup** [comment]
> @zfxmgroup there's probably some audio or image sequence or another type of layer that is failing to be exported because of it's duration or position in the work area.
> If you can share a reduced version of the project I'll take a look at it.

thank you my friend. Thanks to you I solved the problem.
