### ISSUE TITLE
Export Working fine on web player but does not work when tested on ios

### ISSUE THREAD

**Issue by OferHealthy** [airbnb/lottie-web#2580]
Hello,
I am new to Lottie and this is my first time posting.
I am an animator in my profession, so please forgive me current lack of knowledge in coding.  
Nice to meet you all. 

**Tell us about your environment**
Windows 10, Ae 2021, Bodymovin 5.7.11, 

* **Browser and Browser Version:**
Chrome V 91.0.4472.124

* **After Effects Version:**
2021- V 18.2.1

**What did you do? Please explain the steps you took before you encountered the problem.**
Created a simple animation from Ai. After first failed attempts I deleted all the Ai files and converted them to shapes.
Gradients also had some issues so I replaced them with solid colors.
I used the 'Supported Feature' list to make sure I don't make any other mistakes [hopefully] cross platforms. 
I test the JSON files on web before sending them, however I cannot test them on ios and the files does not work there. 

**What did you expect to happen?**
I expected the files that played on the web to work as well on ios and andriod. 
plus, when I try to export from LottieFiles plugin, it exports the '.json' file as '.file' and not '.json'
 
**What actually happened? Please include as much _relevant_ detail as possible.**
-Bodymovi
Exports well [json file], it plays on web previews but not on ios when tested on 'Xcode'

-LottieFiles 
As mentioned, Exports '.json' file as '.file' and cannot be played on web. When changed the name file type, it does work [web] but still the same issue. Does not play on ios. 

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://we.tl/t-PHm1Ybm0h6

Thank you all.

**Comment by bodymovin** [comment]
@OferHealthy hi, can you report the issue on the lottie-ios repository? They'll be more helpful than me.
https://github.com/airbnb/lottie-ios

**Comment by OferHealthy** [comment]
Of course, Thank you very much.
