### ISSUE TITLE
.json animation is not working on iOS and Android devices

### ISSUE THREAD

**Issue by jeeayay** [airbnb/lottie-web#2581]
<img width="686" alt="Screenshot 2021-07-05 at 17 13 44" src="https://user-images.githubusercontent.com/64981524/124470435-0a815800-ddb5-11eb-8b26-d8f620b34b5f.png">
I am using bodymovin plugin first time. 
what I did:
1. Made an animation in After Effects;
2. Installed bodymovin plugin successfully.
3. Rendered in .json 
4. Provided to developers.
 Issue: Animation shows image but not moving/animating on the device. 
I attached my bodymovin settings and .json file [https://assets8.lottiefiles.com/packages/lf20_xupq82bi.json](url)

**Comment by bodymovin** [comment]
hi, if it's not working with one of the native players, can you report it on their repositories?
