### ISSUE TITLE
SVG and HTML ids and classes to reference via css or select via Javascript

### ISSUE THREAD

**Issue by vijaypwr61** [airbnb/lottie-web#2589]
Reference to the title I have given `class` and `id` to layers in After Effect and exported using Bodymovin. But when tried to get these layers either by `class` or `id` using JavaScript and logged in the console it shows **null**.

SVG is rendered here, it works like a charm, no issue here.

```
<object id="container2"  type="type=" image/svg+xml"></object>
```

Javascript to inject Lottie animation, yes, it works perfectly no issues here,

```
player2 = lottie.loadAnimation({
            container: document.getElementById('container2'),
            renderer: 'svg',
            loop: false,
            autoplay: true,
            path: 'assets/mindmap2.json'
        });
```
**But the issue is When** this function is called, it gets the class and logs in the console but in the console, it shows the zero elements inside the HTMLCollection hence the collection is null even it is logged in the console.

```
 window.addEventListener("load", () => {
        console.log(document.getElementsByClassName('ads'));
    });
```

Chrome Dev tool Screenshot 👇  when  `document.getElementsByClassName('ads');`

![consolelog](https://user-images.githubusercontent.com/25868370/126056248-86a03783-fc37-4d08-a74c-0d9504828b06.png)

Chrome Dev tool Screenshot 👇 when  ```window.addEventListener("load", () => {
            console.log(document.getElementById('ads'));});```
            
![consolelog1](https://user-images.githubusercontent.com/25868370/126056287-cd9545a1-5da7-478a-8959-64352f8c0c39.png)

But here you can see it is rendered and has id too.

![consolelog2](https://user-images.githubusercontent.com/25868370/126056202-f1be8e82-c1ee-4a21-a0e9-cb0e131577f7.png)

**Comment by bodymovin** [comment]
hi, the DOM is not ready on window.load, since it needs to load the json and build it from there. Can you try
player2.addEventListener("DOMLoaded", () => {
        console.log(document.getElementsByClassName('ads'));
    });

**Comment by vijaypwr61** [comment]
Thank you for your response and time.  **It works perfectly and solved my problem**. But now I have a question, how come this 👇  method is not working when it prints in the console the same element?
` window.addEventListener("load", () => {
        console.log(document.getElementsByClassName('ads'));
    });`
    
    **However you can close, without answering**

**Comment by bodymovin** [comment]
if I understand your question correctly, it's for the same reason. At the time it is fired, the animation is not loaded, but when you do it manually, the animation has already been loaded so the element exists.

**Comment by vijaypwr61** [comment]
Thank you, I will close the issue.
