### ISSUE TITLE
Support for emoji skin tone modifier and sequences

### ISSUE THREAD

**Issue by DSalman** [airbnb/lottie-web#2590]
**Tell us about your environment**

* **Browser and Browser Version:** Safari (e.g. WebKit as included with iOS 14.x).
* **After Effects Version:** NA

**What did you do? Please explain the steps you took before you encountered the problem.** Using Lottie web, updateDocumentData method to set or update text. Include an emoji with a skin tone modifier or emoji sequence (2 or more emojis joined with zero-width joiner) in the text string

**What did you expect to happen?** The emoji should be modified with skin tone and/or hair style (hair style is an example of an emoji sequence).

**What actually happened? Please include as much _relevant_ detail as possible.** The proper emoji shows but the skin tone modifier shows as a block next to it. Likewise, modified hair shows the emoji with the hair style emoji next to it. An example of emoji with skin tone: U+270C, U+1F3FB ("victory hand", tan color). An example with hair style: U+1F469,U+200D,U+1F9B0 (women with red hair; U+200D is the ZWJ and U+1F9B0 is the hair style).
[animation.json.zip](https://github.com/airbnb/lottie-web/files/6842199/animation.json.zip)
![skin tone + hair style](https://user-images.githubusercontent.com/1105016/126188110-051e3da3-001d-4df3-9200-a54cc0448fd4.png)
![skin tone modifier](https://user-images.githubusercontent.com/1105016/126188129-f8d0ca22-44ee-47f6-9b3b-22adabbd1305.png)

**Please provide a download link to the After Effects file that demonstrates the problem.** (attached animation json used in examples)

**Comment by bodymovin** [comment]
hi! thanks for reporting and the examples. I've pushed a commit fixing this and it will be available on the next release.
