### ISSUE TITLE
TypeScript error when using loadAnimation() with renderer: canvas

### ISSUE THREAD

**Issue by timofey-m** [airbnb/lottie-web#2591]
**Tell us about your environment**
Win 10, NPM 6.14.10

**Browser and Browser Version:**
N/A

**After Effects Version:**
N/A

**What did you do? Please explain the steps you took before you encountered the problem.**
Upgrade lottie-web from 5.7.11 to 5.7.12

**What did you expect to happen?**
Everything works as before

**What actually happened? Please include as much _relevant_ detail as possible.**
Typescript error when using
`Lottie.loadAnimation() with renderer: 'canvas'`:
`TS2322: Type '"canvas"' is not assignable to type '"svg" | undefined'.  index.d.ts(81, 5): The expected type comes from property 'renderer' which is declared here on type 'AnimationConfigWithPath | AnimationConfigWithData'`

I suspect this commit? https://github.com/airbnb/lottie-web/commit/66ce9e1c147b9ee4dff3ef3b4576e60cafd5cd93 @kcirtaptrick

**Please provide a download link to the After Effects file that demonstrates the problem.**
N/A

**Comment by luckymore** [comment]
have the same question, and [demo](https://www.typescriptlang.org/play#code/KYDwDg9gTgLgBDAnmYcCCA7AlgWwIYxYQYDCxAZlgOYA8AKnKDMBgCYDOcA5OwG5Vc4AH24BjPBl552gkVwAWMHABtBAXm58BAPjgaA3gCg4JuKOIw8WDMCgAuOAFFlwHCxgBuY6agtWt2wB+BzovAF9DQ1BIWARkVExcAiJSCmoAdSwYeQAFAnk9dGx8QmIyDEoqOAAyOCNTODB84Lh2GChrKnDIpBQipNKMAElmHEL60zwHDABXHAAjW27o6HhyGYxRQbhlCDxWRJKUgAomqDwcdgdD5LK0qkzsvOyASmvi2+HRuu8TXxgZlAMHU4FM4ABGOARMJeQy7fY3QbHCYmcwYSzWWwOVgQURzdwAOnmEFYiAANL84L42AF7GIJFIZIYwi8gA) here:

**Comment by kcirtaptrick** [comment]
Sorry about that, thanks for the demo, this is fixed in #2597
