### ISSUE TITLE
SVG to Lottie not working

### ISSUE THREAD

**Issue by jrahma** [airbnb/lottie-web#2596]
Hi,

I have an image which is created using Photoshop. I explored it to SVG and tried your portal to convert SVG to Lottie but there is nothing shown.

Here is my SVG:

[Emirates Angels.svg.zip](https://github.com/airbnb/lottie-web/files/6871451/Emirates.Angels.svg.zip)

Kindly help..

Thanks,
Jassim

**Comment by bodymovin** [comment]
hi, this is the repository for lottie-web, can you reach out to the LottieFiles team directly?
