### ISSUE TITLE
Certain animations do not render. Errors in console.

### ISSUE THREAD

**Issue by Monte47** [airbnb/lottie-web#2606]
I am on latest lottie-web, 5.7.12

My code looks like 

```
import React, { useEffect } from 'react'
import lottie from 'lottie-web'
import animationData from '../assets/lottie/Icon-heart_green.json'
// import animationData from '../assets/lottie/loading.json'

const Lottie = () => {
  useEffect(() => {
    lottie.loadAnimation({
      container: document.querySelector('#lottie-element'),
      renderer: 'svg',
      loop: true,
      autoplay: true,
      animationData,
      rendererSettings: {
        preserveAspectRatio: 'xMidYMid slice',
      },
    })
  }, [])

  return (
    <div>
      <div style={{ height: 200, width: 200 }} id="lottie-element" />
    </div>
  )
}
```

The animation does not render when I use the first imported json file and I get console errors. When I swap them and use the commented one it works fine.

![image](https://user-images.githubusercontent.com/21068946/128262406-476e4615-8d56-4905-963e-e4932a3403eb.png)

lottie.js:6734 Error: <svg> attribute viewBox: Expected number, "0 0 undefined undefi…".
lottie.js:6738 Error: <svg> attribute width: Expected length, "undefined".
lottie.js:6739 Error: <svg> attribute height: Expected length, "undefined".
lottie.js:6766 Error: <rect> attribute width: Expected length, "undefined".
lottie.js:6767 Error: <rect> attribute height: Expected length, "undefined".

**Comment by bodymovin** [comment]
that usually means that the file is not there or it's not a json with the lottie format. Have you tried doing `console.log(animationData)` to check what you get?

**Comment by Monte47** [comment]
Yeah it seems that there was an error with the file. Thanks!
