### ISSUE TITLE
Export Bug

### ISSUE THREAD

**Issue by DenysKurn** [airbnb/lottie-web#2608]
Hey,
When I'm exporting lottie the path is trimmed in unintended way.

**In AE:**
<img width="618" alt="Screen Shot 2021-08-08 at 6 03 12 PM" src="https://user-images.githubusercontent.com/88621809/128634684-a362e3e1-6f03-42b4-9d53-0791b992ff8e.png">

**Exported:**
<img width="456" alt="Screen Shot 2021-08-08 at 6 03 21 PM" src="https://user-images.githubusercontent.com/88621809/128634692-db730fd4-ac4e-403d-8795-0fdeffd507bd.png">

**AE source file here:**
[IFF_4.aep.zip](https://github.com/airbnb/lottie-web/files/6950912/IFF_4.aep.zip)

**System:**
MacOS 11.4
AfterEffects 18.4.0 (Build 41)
Bodymovin 5.7.12

**Comment by bodymovin** [comment]
hi, perhaps this can help
https://github.com/airbnb/lottie-web/wiki/Stroke-and-Masks-issue-with-Svgs

**Comment by DenysKurn** [comment]
Yes! It worked, thanks!
