### ISSUE TITLE
Calling currentFrame after playing a segment return the frame number before the final frame

### ISSUE THREAD

**Issue by JonFranklin301** [airbnb/lottie-web#2613]
**Tell us about your environment**

Chrome 92.0.4515.107, Lottie 5.7.12

**What did you do? Please explain the steps you took before you encountered the problem.**

I have an animation that plays to the end then stops. I then have a function that is used to update text in the animation using `.updateDocumentData()`, but for this to work the animation cannot be paused, therefore I play the `currentFrame - 1` to `currentFrame` (actually use `anim.firstFrame + anim.currentFrame` to get the exact frame of the animation):
``` javascript
anim.playSegments( [ anim.firstFrame + anim.currentFrame - 1, anim.firstFrame + anim.currentFrame ], true );
```

The animation is 50 frames long however calling `anim.firstFrame + anim.currentFrame` returns `49` (i guess this is because 1-50 frames in AE = 0-49 frames in JS?), so you would expect this to play `[48, 49]`, which it does.

The issue is when i do this again. `anim.firstFrame + anim.currentFrame` now returns `48`. so we end up playing the segment  `[47, 48]` instead of  `[48, 49]`.

Running this function again plays  `[46, 47]`. Running again plays  `[45, 46]` and so on...

Not sure if the issue is `currentFrame` returning the wrong frame or if `playSegments` is stopping one frame short of the end?

This is used with multiple animation files of different lengths therefore the start and end frame need to be dynamic. This same issue happens on all other animations of different lengths

**What did you expect to happen?**

`anim.firstFrame + anim.currentFrame` should returns `49` and It should play `[48, 49]` every time.

**What actually happened? Please include as much _relevant_ detail as possible.**

Running the function multiple times results in the animation going back 1 frame each time.
 `[48, 49]`, then  `[47, 48]`, then  `[46, 47]`, then  `[45, 46]`, then,  `[44, 45]`, I think you get the idea....

**Comment by bodymovin** [comment]
hi, is the loop property set to true or false?

**Comment by JonFranklin301** [comment]
Hi, loop is set to false.

**Comment by bodymovin** [comment]
so lottie excludes the outpoint of a segment. It does it in order to support subframe rendering appropriately, since when looping, the whole last frame must be accounted for.
have you tried doing:
`anim.playSegments( [ anim.firstFrame + anim.currentFrame, anim.firstFrame + anim.currentFrame + 1 ], true );`

**Comment by JonFranklin301** [comment]
Thanks for the info.
When doing `anim.playSegments(  [ anim.firstFrame + anim.currentFrame, anim.firstFrame + anim.currentFrame + 1 ], true ); `  as you've suggested does not update the text. I believe it does play the 1 frame as the `complete` event listener fires but the text does not update.

Playing 2 frames, `currentFrame - 1` to `currentFrame +1` seems to do the trick and does not result in the animation going back 1 frame each time as per the original issue.
`anim.playSegments( [ anim.firstFrame + anim.currentFrame - 1, anim.firstFrame + anim.currentFrame + 1 ], true );`

Strange one... Happy to mark this as resolved. Thanks for your help 🙌
