### ISSUE TITLE
Custom Fonts Not Rendering

### ISSUE THREAD

**Issue by C4Framework** [airbnb/lottie-web#2617]
MacOS 10.15.7
Safari 14.0.1, Chrome 89.0.4389.114, Firefox 90.0.2
AE 2021

I have a very simple file I am testing with, it looks like this:

![fontTest](https://user-images.githubusercontent.com/1447498/129310011-b7bf7b60-9a0a-471c-966d-3f9b1ce229b3.png)

I exported the file with **Bundle fonts**.

I expected the rendered file to look like the image above, but it initially rendered completely white.

![image](https://user-images.githubusercontent.com/1447498/129310243-a6c129e9-6441-4d43-88ed-f43465e0cdba.png)

The file structure for the project I am testing with looks like this:

![image](https://user-images.githubusercontent.com/1447498/129310288-a5c102b9-c7dc-4c6c-aaf9-f9b331c37469.png)

The initial JSON file references the fonts like this:

```
"fonts": {
    "list": [
        {
            "origin": 3,
            "fPath": "fonts/Rubik-Medium.ttf",
            "fClass": "",
            "fFamily": "Rubik",
            "fWeight": "",
            "fStyle": "Medium"
            "fName": "Rubik-Medium",
            "ascent": 29.919921875,
        },
        {
            "origin": 3,
            "fPath": "fonts/Rubik-Regular.ttf",
            "fClass": "",
            "fFamily": "Rubik",
            "fWeight": "",
            "fStyle": "Regular"
            "fName": "Rubik-Regular",
            "ascent": 12.15496826171875,
        }
    ]
}
```

Here is a sample of how the text layer is written:

```
"s": {
    "f": "Rubik-Regular",
    "fc": [
        0.9480000000000001,
        0.9480000000000001,
        0.9480000000000001,
        1.0
    ],
    "j": 0.0,
    "lh": 15.0,
    "ls": 0.0,
    "s": 13.0,
    "sz": [
        55.410000000000004,
        15.42
    ],
    "t": "Font 2",
    "tr": 0.0
},
```

**WHAT I'VE TRIED**
I have tried multiple variations of the `fPath` variable, like the following:

```
"fPath": "fonts/Rubik-Regular.ttf"
"fPath": "./fonts/Rubik-Regular.ttf"
"fPath": "../fonts/Rubik-Regular.ttf"
"fPath": "fonts/Rubik-Regular" (<< here i even changed the filename)
```
I have also tried the above variations but changed `fPath` to `fOrigin`

When I used `fOrigin` I was able to see the text, but with the incorrect font like this:

![image](https://user-images.githubusercontent.com/1447498/129311821-ecdf853b-4cf0-4844-b1ee-94cfd67e33bb.png)

Here is a zipped file with my project:
[FontTest.zip](https://github.com/airbnb/lottie-web/files/6980177/FontTest.zip)

**Comment by melino** [comment]
Did you find a solution? I am currently having the same problem.

**Comment by C4Framework** [comment]
Embedded the font using base64 encoding.
