### ISSUE TITLE
Dynamic Render Broken

### ISSUE THREAD

**Issue by aklacar1** [airbnb/lottie-web#2635]
Here is the deal, what I need to do it be able to render multiple Lottie files dynamically over Canvas (not on Canvas), I just need to put random lottie that is chosen as SVG as layer over Canvas + I need to control time of that Lottie to correspond to time of video that is playing on Canvas.

Issue:

Lottie consists of couple of lines of texts.
The way I create it is I create a div as container with relevant styles, div is not hardcoded in app anywhere, but rather created by document.createElement. This div is container for this lottie.

1. When I play video with this Lottie over it, this Lottie seems totally broken, basically it has 4 lines of text but all text over each other in each line.
2. How I know it is not problem with Lottie file: I have a piece of code that can select that same Lottie and pass its Animation Data to react-lottie library, just for preview purposes. The moment this lottie is selected, it gets fixed and now it displays properly over Canvas. After this as long as I stay here and not reload the lottie, it all works.

The only difference between my Lottie creation that I seemed to find seems to be that div is created with document.createElement.

Relevant code:

const animContainer = document.createElement('div');
animContainer.className = 'LottieAnimation';
    animContainer.id = `${animationObject.id}-animation-${generateRandomString(10)}`;
    animContainer.setAttribute('key', `${animationObject.id}-animation-${generateRandomString(10)}`);
    animContainer.style.width = '100%';
    animContainer.style.height = '100%';
    animContainer.style.overflow = 'hidden';
    animContainer.style.display = 'block';
    animContainer.style.margin = '0 auto';
    animContainer.style.outline = 'none';
    animContainer.style.userSelect = 'none';
    animContainer.style.pointerEvents = 'none'; 

    const anim = lottie.loadAnimation({
        container: animContainer,
        renderer: 'canvas',
        loop: true,
        autoplay: true,
        animationData: animationData,
        rendererSettings: {
            preserveAspectRatio: 'xMaxYMax slice',
            progressiveLoad: true,
        },
    });

Using:
"lottie-web": "^5.7.13",
"react": "^16.14.0",
"webpack": "^4.19.1",

**Comment by bodymovin** [comment]
have you tried attaching it to the DOM before loading the animation on the created div?

**Comment by aklacar1** [comment]
Not yet, but will try tomorrow (day after tomorrow at furthest) most likely and give you response on this. Problem is I will have to hide it in DOM since Its not supposed to be shown anywhere except over Canvas (x / 20+ Lottie files)

**Comment by aklacar1** [comment]
@bodymovin 

Thank you, even though I do not prefer this solution, it does seem to work. However, I would appreciate it if possible to add a better fix for it in lottie-web package.
