### ISSUE TITLE
Feature request — append composition name to data.json file name

### ISSUE THREAD

**Issue by vincent-bidaux** [airbnb/lottie-web#2636]
If my Composition is named `05 Serenity Animation`, I would like the bodymovin file to be named after it. Either `05-Serenity-Animation.json` or `05-Serenity-Animation-data.json`.

This can be an appreciable huge time saver at times. Thanks.

**Comment by bodymovin** [comment]
on the latest version of Bodymovin (v5.7.14) there is an option on Project Settings:
`Use comp name`
Does that help?

**Comment by vincent-bidaux** [comment]
Most probably, thank you.

**Comment by vincent-bidaux** [comment]
I actually like this, because for other kind of projects, I have automation to catch the exported files, and predictability of the data.json name helps.
