### ISSUE TITLE
bounding lottie size to container height

### ISSUE THREAD

**Issue by kenbankspeng** [airbnb/lottie-web#2641]
Objective:
To fit a Lottie within the bounds of its parent container div.

Implementation:
Load the animation with a reference to the parent container: lottie.loadAnimation({container: parentRef, renderer: 'svg'})

Observation:
The lottie loads but is only bound to the container width and not the container height. For example, a container div with width: 100px and height: 50px results in a lottie (with a square viewport) of width: 100px and height: 100px.

Desire:
Fit the lottie such that its size is scaled to fit. In the example, produce a lottie scaled to width: 50px and height: 50px.

Notes:
I have a hack to measure the container height and explicitly set the lottie height, but hoping I'm just missing a scaling option.  I tried some preserveAspectRatio options to no avail.

**Comment by bodymovin** [comment]
hi, can you share more information on what is the desired outcome?
Screenshots will be helpful to better understand.
usually preserveAspectRatio has most of the standard solutions for this type of scenarios

**Comment by kenbankspeng** [comment]
Thank you for your fast response. Most appreciated. Great tool.

The video is of me clicking a button for example of width: 100px and height: 50px, and the lottie being width: 100px and height: 100px instead of the desired width: 50px height: 50px.

https://user-images.githubusercontent.com/26904200/133435590-f116f620-aac8-4d61-8f8f-9ba327be83c1.mp4

Note that the semi-transparent background does fit the button dimensions perfectly at 50x100 so my <Overlay> seems correct. The background is not 100x100. But the lottie is 100x100. The viewbox is a square with an offset to pull out the spinner and not the padding within the json.

I am using React/JSX with hooks and styled-components, so not so easy to bring you into the code and I can understand that this will constrain you. Basically I have a <Busy> component which wraps the <Button> component and overlays a black semi-transparent alpha background and the <Lottie> using a css position: relative on the parent and a position: absolute on the overlay.


```
Busy component:
<Group>  // css relative
  <Overlay>  // css absolute, top: 0, left: 0, height: 100%, width: 100%, background: semi-transparent black
    <Lottie data={spinner}  loop={true} command={PLAY} viewBox={'150 150 300 300'} />
  </Overlay>
  <div>{children}</div> // children would contain the button
</Group>

Render with isBusy set after clicking button.
<Busy busy={isBusy}>
  <Button>User</Button>
</Busy>
```

**Comment by bodymovin** [comment]
the loaded svg adapts itself to the container. Perhaps you can try setting the width and height of the container explicitly.
If you have a link with the implementation I can try to check the css.

**Comment by kenbankspeng** [comment]
Well, the SVG certainly adapts itself to the container, but at least in my code, it adapts to the width and not the height. After explicitly setting the height, the SVG adapts itself to the height.

Since my Busy component is a generic component that wraps many components of varying heights, the only solution I have is to measure the wrapped component dynamically at set it's height in js. Seems a bit wrong but it works. Thank you.
