### ISSUE TITLE
Gradient effect doesn't work!

### ISSUE THREAD

**Issue by aghsgnapfzz** [airbnb/lottie-web#2645]
I'm working on:
Macbook Air 2017
After Effects 2021
Bodymovin 5.7.4 (04/2019) & LottieFiles 1.0.0 (03/2020), both acquired on the adobe exchange

I have an animated logo, built with a simple gradient animation on a shape layer. I have tried it both with a Gradient Ramp Effect, and with a Gradient Overlay (after i read that the first isn't supported by bodymovin.
I need the .json to export the file on the web but this are the problems:
 - The render with LottieFiles doesn't work. It starts and never ends.
 - The render with bodymovin of the logo animated on the Gradient Overlay fails.
 - The render with bodymovin of the logo animated on the Gradient Ramp effect is successful, but the file shows just the white shape, no gradient on top of it, both on the website and in the Lottie Files Preview
 
I read many issues on GitHub and tried them all: changed the language to english to avoid unrecognised characters (original: Italian), uninstalled and re-installed the extensions, checked the permission to write scripts. Nothing seems to work...

Here's the file:
[logo animato.aep.zip](https://github.com/airbnb/lottie-web/files/7211940/logo.animato.aep.zip)

**Comment by logabo** [comment]
You need to add a Gradient fill to the shape layer and keyframe the start/end points and colors. Make sure you use RGB colors and save the aep before rendering the lottie. Here is an example: https://lottiefiles.com/share/ovndhskk
![Clipboard01](https://user-images.githubusercontent.com/35307745/134911214-13c915c3-dd9a-42b1-933a-07e01fb556b8.png)

**Comment by aghsgnapfzz** [comment]
Thanks!!
