### ISSUE TITLE
Bodymovin Extension ERROR: Export failed

### ISSUE THREAD

**Issue by mouhandalkadri** [airbnb/lottie-web#2649]
Hello...
I was trying to export after effect sequence to Rive2 project using Bodymovin extension, But every time I get this error
Even though "Allow Script...." option is enabled 

![error](https://user-images.githubusercontent.com/46677048/134931984-ceea9083-25de-4334-84e0-87cad19b327e.PNG)

_I am using After Effect version 16.0.0 and tried bodymovin versions 5.6.1 and 7.11_

**Comment by bodymovin** [comment]
Hi, unfortunately Rive has updated their file format and the exporter is no longer compatible with it. I'll see in the future if I can update it, but it will take some time.

**Comment by gusta34a** [comment]
não consigo exportar uma animação em svg com o bodymovin V. 5.12.1 na versão 23.6.5 do after effects( eu já habilitei a opção de permissão de scripts)
