### ISSUE TITLE
Bodymovin not rendering gradients

### ISSUE THREAD

**Issue by Karan-Kowshik** [airbnb/lottie-web#2665]
Hey, I recently made a gradient animation in after effects and when I render it using Bodymovin all I see is a blank screen. I have attached the AE and the json file
[Gradient.zip](https://github.com/airbnb/lottie-web/files/7395386/Gradient.zip)

**Comment by bodymovin** [comment]
Not really, those raster effects are difficult to emulate, and they wouldn't work great on real time rendering.
