### ISSUE TITLE
how to clear the cache of image when I replay the same Lottie Animation?

### ISSUE THREAD

**Issue by ape-casear** [airbnb/lottie-web#2666]
**Tell us about your environment**
electron:5.0.11

**What did you do? Please explain the steps you took before you encountered the problem.**
step1: play the Lottie-A 
step2: change the image file(example: image/img_0.png) for diversity in the "Lottie-a/images/img_0.png"
step3: play the Lottie-A
you will see the animation still playing with the old img_0.png.

**What did you expect to happen?**
I want to clear the cache and get the new img_0.png

**Comment by deshario9** [comment]
Hi @ape-casear,

How did you solve it? Thanks

**Comment by ape-casear** [comment]
> Hi @ape-casear,
> 
> How did you solve it? Thanks

Yes, I did.

There are two ways:
1. Modify and write the JSON file at which "assets[targetImageIndex].p" just like `"p":"img_2.png"` => `"p":"img_2.png?id=${Date.now()}"`, then it will make the image cache to be unused.
2. Use option `animationData` instead of `path`. In `animationData` Object, change assets item  like this
```
const asset = animationData.assets[0]
asset.u = ''
asset.p = 'https://img/another/image.png'

lottie.loadAnimation({
    animationData: animationData,
    ...otherParams,
})
```
