### ISSUE TITLE
Are multiple Keyframes supported?

### ISSUE THREAD

**Issue by aidanoday** [airbnb/lottie-web#2668]
I'm using AE 14.4.1 with the Lottiefiles Plugin on a 2017 Macbook Pro 17inch

I'm animating a logo that hops up into the air and then falls down off the screen, while spinning counterclockwise.  There are three keyframs, and in the first ten frames, the logo anticipates the hop and rotation a bit- initially falling a bit, and rotating clockwise.

I created two keyframes and animated the movement, and used Lottie to animate a preview.  I then decided I needed some anticipation, moved the initial two keyframes down the timeline 10 frames, and added a new keyframe for each parameter at the start.

A (perhaps unhelpful 😢 ) sketch of expected animation: 
<img width="959" alt="Screen Shot 2021-10-27 at 12 22 05 PM" src="https://user-images.githubusercontent.com/48231947/139132854-b106d0fd-8602-464e-9e42-f762a1e2fc7d.png">

Screenshot of the movement graphs from AE

<img width="1243" alt="Screen Shot 2021-10-27 at 12 11 15 PM" src="https://user-images.githubusercontent.com/48231947/139131378-0d21c6bc-c99a-4b2e-8715-5fe9206110eb.png">

The after effects preview shows my animation working as expected.

But: when I export the composition to lottie withe extensions, lottie, it ignores the first 10 frames of movement, instead holding the logo still 10th or 11th frame.  It then completes the second part of the animation (40 frames) as expected.

I'm wondering why the lottie render seems to ignore the movement in between frame 0 and frame 10.  Did my keyframe adding workflow throw it off?  Does it only support two keyframes?

Thank you for the help!

PS I'm sorry but I don't know how to upload the AE file because Github says that it's an unsupported filetype.

**Comment by bodymovin** [comment]
Unfortunately, lottie doesn't support two consecutive keyframes with the exact same value. If you change the scale on frame 10 to a value slightly different (0.01 difference is enough), it should work correctly

**Comment by aidanoday** [comment]
Thank you!  It worked perfectly :). Here's the finished animation:

https://lottiefiles.com/83551-ilwe-launch-animation

**Comment by bodymovin** [comment]
nice!
