### ISSUE TITLE
Sound from rendered lottie not working

### ISSUE THREAD

**Issue by timcartoonbase** [airbnb/lottie-web#2685]
I have added sound effects to my animation, as I read in the documentation that "If the howler library is in the global scope and lottie finds the Howl constructor, Lottie will take care of the rest". So I npm installed howler, however the sound isn't playing from the Bodymovin preview or in the browser (chrome). I can see in the inspector tool that **the duration is set to 0** which doesn't seem right. 

I don't believe this is to do with the audioContext not being allowed to start, as the user must click a button to get to the animation.

If anyone can help me work out what's going wrong I would greatly appreciate it! Here is the code (React):

```
  function createAudio(assetPath) {
    let a = new Howl({
        src: [assetPath],
        volume: 1
    });
    return a;
  }
  
  const defaultOptions = {
    renderer: 'svg',
    loop: false,
    autoplay: true,
    animationData: currentScene,
    rendererSettings: {
      preserveAspectRatio: "xMidYMid slice"
    },
    audioFactory: createAudio
  };
```

**Comment by bodymovin** [comment]
hi, have you checked if the createAudio method is called?

**Comment by timcartoonbase** [comment]
Hi, yes I have added a console.log in this method to check, and it is being run
```function createAudio(assetPath) {
    console.log(assetPath);
    console.log(`../../../assets/lotties/s${storyId}/${scene}/${assetPath}`);
    let a = new Howl({
        src: [assetPath],
        volume: 1
    });
    return a;
  }```
The second log is the exact path to the mp3 file, but this doesn't work either when I make this the src argument
<img width="541" alt="Screenshot 2021-11-22 at 09 07 55" src="https://user-images.githubusercontent.com/91607506/142825878-e3695d92-26e8-4621-9d14-00815cec94ef.png">

**Comment by timcartoonbase** [comment]
I have figured out what the problem was - I needed to have the sounds in the public folder of the application. Closing this :)
