### ISSUE TITLE
Rotation speed is too fast on Safari

### ISSUE THREAD

**Issue by sneko** [airbnb/lottie-web#2699]
**Tell us about your environment**

* **Browser and Browser Version:**

`Safari desktop v15.1` (but also an issue on Safari on iPhone 7

* **After Effects Version:**

`2021 v25`

**What did you do? Please explain the steps you took before you encountered the problem.**

We created a Lottie file (https://lottiefiles.com/share/naewsvnk) and we tried it on several platforms/browsers. It works on:

* Desktop
* - Firefox
* - Chrome

* Android
* - Firefox
* - Chrome

**But it does not work properly (rotation too fast) on:**

* Desktop
* - Safari

* iOS
* - Safari
* - Chrome

**What did you expect to happen?**

It rotates as for all other platforms/browsers. Any idea what could cause this?

Thank you,

**What actually happened? Please include as much _relevant_ detail as possible.**

-

**Please provide a download link to the After Effects file that demonstrates the problem.**

-

**Comment by sneko** [comment]
Hi @bodymovin , any idea what could cause this (a rotation setting...)? I did not figure it out 😞 

Thank you,

**Comment by bodymovin** [comment]
Hi, I'm not sure why it's rendering like that. But if you set the [subframeRender](https://github.com/airbnb/lottie-web#setsubframeusesubframes) to false it will work fine.
Can you share the .aep?

**Comment by sneko** [comment]
Hi @bodymovin ,

Thank you! You are right about using `.setSubframe(false);` to make it rendering properly!

Could you explain a bit when to change this property in general? Just when we saw a difference between the source animation and the exported one with the Lottie player?

I checked FPS in AE and I'm not sure it's wrong. Please find the file below (cannot upload the `.aep` so it's zipped), I'm interested to know what we did wrong into AE since all other animations play well 😄 
![image](https://user-images.githubusercontent.com/8195958/147662809-28d8d516-b403-4769-b92e-a4ac54752333.png)
[lottie_gear_animation.aep.zip](https://github.com/airbnb/lottie-web/files/7788867/lottie_gear_animation.aep.zip)

Thank you,

**Comment by bodymovin** [comment]
Hi, I had the chance of checking your animation. It seems that on every frame it does 2 spins + 4 degrees. When the player tries to interpolate between frames, since browsers usually are not completely regular on when they schedule the next frame, it looks as if the animation is accelerating or decelerating.
When using setSubframe, it doesn't schedule so many frames and the chances are much lower of getting an irregular frequency.

**Comment by sneko** [comment]
@bodymovin thank you for taking the time of digging into this! It makes things clear for me for the next times 👍
