### ISSUE TITLE
translate3d(0,0,0) can make small SVG blurry

### ISSUE THREAD

**Issue by ColinWhitmarsh** [airbnb/lottie-web#2718]
Hello,

I'm not reporting a bug with lottie, instead I'm filling an issue to help anyone else that might run into the same problem as me. I'm using lottie to render an animated icon. I used the SVG rendering. I found the SVG was blurry, even when it wasn't animating. After debugging for a while, I found that unsetting translate3d(0,0,0) on the SVG fixed the blurriness. I unset translate3d(0,0,0) with `viewBoxOnly: true`.

```
lottie.loadAnimation({
  container: document.getElementById('container'),
  renderer: 'svg',
  path: 'data.json',
  rendererSettings: {
    viewBoxOnly: true,
  },
})
```

I found the blurriness seemed to happen for a variety of SVGs, not just the animated one I was working on. It seems to only happen when the SVG is very small (20px or less). I created a codepen to illustrate the issue https://codepen.io/colinwhitmarsh/pen/eYeWQVg. 

![Screen Shot 2022-02-10 at 12 00 17 PM](https://user-images.githubusercontent.com/14297837/153487847-26a08fe3-bae6-4be0-8e97-cecdaae325ff.png)

Hopefully this helps someone else in their debugging.

**Comment by bodymovin** [comment]
hi, thanks for reporting it!
Those artifacts from browsers are sometimes more noticeable if the svg is not rendered at its original size.
And the translate3d should give better performance but it's true that it can affect the sharpness of the animation.

**Comment by kudanai** [comment]
Closing for now.

**Comment by luanargolodev** [comment]
I'm having problems using on my website. When using it with a lottie animation, I noticed that the svg is applying a transform: translate3d and is applying a blur to the animation.

How do I deactivate?

When you deselect this attribute, the svg returns and has satisfactory quality.

![image](https://github.com/airbnb/lottie-web/assets/10791688/0dcd3a9b-6b88-468c-92a1-009375d2938c)

I'm use <lottie-player>
```js
<lottie-player
      src={animation.value}
      background={background}
      speed={speed}
      style={style}
      direction={direction}
      mode={mode}
      loop={loop}
      autoplay={autoplay}
      preserveAspectRatio={preserveAspectRatio}
    >
    </lottie-player>```

**Comment by kharrop** [comment]
Seeing this issue as well
