### ISSUE TITLE
Make it possible to set the resulting SVG width & height to 1em

### ISSUE THREAD

**Issue by villesau** [airbnb/lottie-web#2719]
When working with SVG icons, their width & height is usually set to em units ( usually 1em ) to follow font size. However, I haven't found a way to set that for SVG Lottie is resulting. When working with animated icons, this would be quite important to make the icons more reusable. We are using https://www.npmjs.com/package/react-lottie-player for rendering the Lottie files.

As a reference, you can check practically any icon from react-icons: https://react-icons.github.io/react-icons/icons
CSS units for the reference: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units

**Comment by bodymovin** [comment]
hi, I've added support to set width and height via config.
It will be available on the next build.
