### ISSUE TITLE
ReferenceError: navigator is not defined     at /node_modules/lottie-web/build/player/lottie.js:211:56

### ISSUE THREAD

**Issue by ticpoi** [airbnb/lottie-web#2731]
**Tell us about your environment**
I use lottie-react-web in next.js React application. It uses lottie-web as requisite

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**
I just made a regular publish of my application today and got an error message on deployment because of newest version of lottie-web as you can see in error message

**What did you expect to happen?**
It should build normally. It was already working regularly. 

**What actually happened? Please include as much _relevant_ detail as possible.**
But downloading new version as node_module made it crashed. I did not update the version of lottie-web but I understand that lottie-react-we uses the latest version as a prerequisite

**Please provide a download link to the After Effects file that demonstrates the problem.**
I do not have and after effects file. I just used an animation downloaded from lottiefiles. You can reach json file if it is helpful
https://riderexpress.ticpoi.com/images/animations/busAnimation1.json

**Comment by bodymovin** [comment]
hi, that's odd. That line doesn't seem to have changed from the previous version.
Is this happening during the build process or at runtime?

**Comment by ticpoi** [comment]
It is happening on the build process
![image](https://user-images.githubusercontent.com/79175938/156719484-06f4e43b-14b4-4689-9c12-d5e94e9f5cd6.png)

**Comment by bodymovin** [comment]
is the project public? Or any chance you can share a simple version that I can test?

**Comment by ticpoi** [comment]
Project code is not public but application uses this feature is public. You can see a bus animation while searching bus tickets in the page below.
https://riderexpress.ticpoi.com
It uses the previous version and works well

![image](https://user-images.githubusercontent.com/79175938/156720882-a8c7a8ba-4120-4465-896a-df50fa63eaec.png)

**Comment by GenesisLQ** [comment]
I have the same problem.
![image](https://user-images.githubusercontent.com/48673814/156721609-3fa204a0-daa6-4107-8557-efaa212d4373.png)

**Comment by bodymovin** [comment]
Do you have a github sample project I can use to reproduce it?

**Comment by bodymovin** [comment]
@GenesisLQ are you using next.js too?

**Comment by GenesisLQ** [comment]
> @GenesisLQ are you using next.js too?

It's a vue server render we built ourselves

**Comment by bodymovin** [comment]
working on a fix. Will be ready soon. Thanks for the help!

**Comment by ticpoi** [comment]
I made a research on npm if there is any other library for react.
I changed the "lottie-react-web" library and Used "lottie-react" instead. It worked correctly on my local like previous one.
But when I send for server build I got the same result.

![image](https://user-images.githubusercontent.com/79175938/156724950-79f7c66b-3e5c-45e2-9450-abc6fb5dde88.png)

Thanks for fix, It is good news. Waiting for that.

**Comment by bodymovin** [comment]
@ticpoi @GenesisLQ fixed on version 5.9.1
can you confirm if it works for you now?

**Comment by ticpoi** [comment]
> @ticpoi @GenesisLQ fixed on version 5.9.1 can you confirm if it works for you now?

Yes 5.9.1 fixed the problem for me. 

Thanks

**Comment by bodymovin** [comment]
thank you!

**Comment by patilbhupesh** [comment]
<img width="716" alt="image" src="https://github.com/airbnb/lottie-web/assets/37431608/f19047f7-4bf2-4737-94b1-c05df95b6737">


i uses  "react-lottie" lib which gives me error of `ReferenceError: navigator is not defined` i have tried it with lazy load lib with `@loadable/component` its work fine 

import loadable from '@loadable/component';

const Lottie = loadable(() => import('react-lottie'));

**Comment by we-shall** [comment]
downgrading(using NVM) to the 20.10.0 version of node solved my problem. But this is a hack.
