### ISSUE TITLE
Marker data not being matched with the correct marker's name.

### ISSUE THREAD

**Issue by nnhk23** [airbnb/lottie-web#2735]
Current browser: Chrome.

Hi! 
I have a JSON blob for an icon with 4 markers:
```
"markers":[
    {
        "tm":0,
        "cm":"clickActivate",
        "dr":100
    }, 
    {
        "tm":100,
        "cm":"clickDeactivate",
        "dr":100
    }, 
    {
        "tm":0,
        "cm":"staticActive",
        "dr":1
    }, 
    {
        "tm":100,
        "cm":"staticInactive",
        "dr":1
    }
]
```
However when I try to interact with the icon, the markers do not work. when I click to interact with this icon, the animation will auto play from start to finish, instead of playing from frame 0 to frame 100 like the first marker indicate. 

After a little digging, I suspect `getMarkerData` function is not mapping to the right name marker value.
![Screen Shot 2022-03-08 at 1 43 02 **PM](https://user-images.githubusercontent.com/69068610/157331037-1f4cd582-8965-4c10-995e-db534e7c9dad.png)

In the [source code](https://github.com/airbnb/lottie-web/blob/master/build/player/lottie.js#L2085), marker's name is being compared to an object (`marker.payload.name`), instead of a string, which cause the bug mentioned above.

**Comment by bodymovin** [comment]
thanks for the fix!

**Comment by BrainCrumbz** [comment]
Hi @nnhk23 , hope it is ok to ask here: do you have a "reference" animation with markers that it is known to be working with lottie-web? And can you share its JSON file?

We're working with a JSON file which definitely has markers:

```json
  "markers": [
    {
      "tm": 0,
      "cm": "1",
      "dr": 25
    },
    {
      "tm": 25,
      "cm": "2",
      "dr": 50
    },
    {
      "tm": 75,
      "cm": "3",
      "dr": 23
    },
    {
      "tm": 98,
      "cm": "4",
      "dr": 0
    }
  ]
```

but for some reason when we launch `goToAndPlay('1')` or `goToAndPlay('2')` markers seems to be ignored, and the whole animation is played (in loop, as we have loop set to true).

Thanks a lot

**Comment by BrainCrumbz** [comment]
Please see #2776 2776
