### ISSUE TITLE
When sourceText is changing old chars is not cleaned

### ISSUE THREAD

**Issue by marcinw788** [airbnb/lottie-web#2738]
There is text layer which is changing over time but old text overlays new text.

It was working fine till lottie 5.8.1. Problem is on 5.9.0 & 5.9.1. 

I'm using 'svg' renderer mode.

![bug](https://user-images.githubusercontent.com/14854458/157445138-b1fa0b59-fc53-4281-90d9-912afc803bcd.jpeg)

[Archiwum.zip](https://github.com/airbnb/lottie-web/files/8214782/Archiwum.zip)

**Comment by bodymovin** [comment]
hi, I found the issue, it will be fixed on the next build. Thanks for reporting it
