### ISSUE TITLE
document is not defined for server side rendering SSR at createTag

### ISSUE THREAD

**Issue by joshunger** [airbnb/lottie-web#2739]
I'm seeing `document is not defined` for server side rendering (SSR).

```
function createTag(type) {
  // return {appendChild:function(){},setAttribute:function(){},style:{}}
  return document.createElement(type);
}

export default createTag;
```

https://github.com/airbnb/lottie-web/blob/master/player/js/utils/helpers/html_elements.js#L3

@bodymovin would it be possible to check for document so it doesn't break SSR when this JavaScript is included in the SSR bundle?

Thanks.

**Comment by sebinievas** [comment]
@bodymovin any response? Thanks!

**Comment by joshunger** [comment]
This is what we ended up doing to workaround the issue -

```javascript
const ChevronDownBouncing = lazy(() => import('./ChevronDownBouncing'));
```

Then -

```javascript
<NoSsr>
  <Suspense fallback={<img alt="" src={chevronDownBouncing} />}>
    <ChevronDownBouncing />
  </Suspense>
</NoSsr>
```

Then -

```typescript
import { useEffect, useRef } from 'react';
import lottieWeb from 'lottie-web';
import ChevronDownBouncingIcon from './ChevronDownBouncingIcon.json';
import * as styles from './ChevronDownBouncing.module.scss';

export default function ChevronDownBouncing() {
  const ref = useRef();

  useEffect(() => {
    lottieWeb.loadAnimation({
      container: ref.current,
      renderer: 'svg',
      loop: true,
      autoplay: true,
      animationData: ChevronDownBouncingIcon
    });
  }, []);

  return <div ref={ref} className={styles.chevron} />;
}
```

And `chevronDownBouncing` is the last frame. We saved the last frame to an svg by doing something like -

```javascript
function SaveLastFrame() {
  const ref = useRef();
  useEffect(() => {
    const animation = lottie.loadAnimation({
      container: ref.current, // the dom element that will contain the animation
      renderer: 'svg',
      loop: true,
      autoplay: true,
      animationData: json // the path to the animation json
    });

    // open json and find op value
    animation.goToAndStop(120, true);
  }, []);

  return <div style={{ width: '100px' }} ref={ref}></div>;
}
```

**Comment by horrylala** [comment]
Same error,have you ever solved it ?
I'm using loadable-component with loadable(() => import(a.jsx)).
Got the same error.

Without dynamic import , it goes all right.
So, what's wrong with dynamic import?

**Comment by djrcawley** [comment]
Maybe this will help someone looking for this similar issue. I accidentally upgraded to node version to the newest version 21.5.0 which caused this error to appear. Downgrading to version 20.10.0 (LTS) and reinstalling all the packages resolved this issue for me.

**Comment by HyatMyat4** [comment]
Thanks very very much  @djrcawley your comment is very helpful 100% work  , how I fix:  after  reinstalling 20.10.0 (LTS) , I delete node_modules , yarn.lock ,  package-lock.json , .next  and  after  reinstalling  these, need to close the vs code and open again  it will work

**Comment by ChaseObserves** [comment]
@djrcawley I want you to know that I've been suffering with this issue in my daily job for months now, I've been in this thread multiple times trying different things to resolve it, but your comment is new as of last week and your fix totally worked for me. THANK YOU. The nightmare of refreshing my NextJS app 3-4 times until the 'document is not defined' error stopped popping up is now just a bad memory.

**Comment by nadeemc** [comment]
Hi!

Another solution specific to Next.js is to wrap the player component using `dynamic` to prevent SSR. This removes the issue without needing to downgrade node:

```ts
'use client';

import dynamic from "next/dynamic";

export const MyComponentWithLottie = () => {
  return (<>
    {/* ... other components ... */}

    <PlayerWithNoSSR
      autoplay
      keepLastFrame
      loop
      src={'https://static3.lottiefiles.com/lotties/01_ramen_character.json'}
    />

    {/* ... other components ... */}
  </>);
};

const PlayerWithNoSSR = dynamic(
  () => import('@lottiefiles/react-lottie-player').then(module => module.Player),
  {ssr: false},
);
```

**Comment by juan-alencar** [comment]
> Hi!
> 
> Another solution specific to Next.js is to wrap the player component using `dynamic` to prevent SSR. This removes the issue without needing to downgrade node:
> 
> ```ts
> 'use client';
> 
> import dynamic from "next/dynamic";
> 
> export const MyComponentWithLottie = () => {
>   return (<>
>     {/* ... other components ... */}
> 
>     <PlayerWithNoSSR
>       autoplay
>       keepLastFrame
>       loop
>       src={'https://static3.lottiefiles.com/lotties/01_ramen_character.json'}
>     />
> 
>     {/* ... other components ... */}
>   </>);
> };
> 
> const PlayerWithNoSSR = dynamic(
>   () => import('@lottiefiles/react-lottie-player').then(module => module.Player),
>   {ssr: false},
> );
> ```

i love you

**Comment by makowey** [comment]
Dynamic imports **Svelte/SvelteKit:**

```js
<script lang="ts">
	const imports = {
		lottieAnimation: () => import('./LottieAnimation.svelte')
	};

	export let options = {
		path: '94729-not-found',
		loop: true
	};
</script>

{#await imports['lottieAnimation']() then module}
	<svelte:component this={module.default} {options} />
{/await}
```

**Comment by jangir-ritik** [comment]
> Maybe this will help someone looking for this similar issue. I accidentally upgraded to node version to the newest version 21.5.0 which caused this error to appear. Downgrading to version 20.10.0 (LTS) and reinstalling all the packages resolved this issue for me.

This saved me...
I wonder what the underlying issue is

**Comment by hewelt** [comment]
@jangir-ritik probably this: [a github issue about lottie checking for typeof navigator which can't work in Node 21](https://github.com/airbnb/lottie-web/issues/3047)

**Comment by RonaldoAlencar** [comment]
> Hi!
> 
> Another solution specific to Next.js is to wrap the player component using `dynamic` to prevent SSR. This removes the issue without needing to downgrade node:
> 
> ```ts
> 'use client';
> 
> import dynamic from "next/dynamic";
> 
> export const MyComponentWithLottie = () => {
>   return (<>
>     {/* ... other components ... */}
> 
>     <PlayerWithNoSSR
>       autoplay
>       keepLastFrame
>       loop
>       src={'https://static3.lottiefiles.com/lotties/01_ramen_character.json'}
>     />
> 
>     {/* ... other components ... */}
>   </>);
> };
> 
> const PlayerWithNoSSR = dynamic(
>   () => import('@lottiefiles/react-lottie-player').then(module => module.Player),
>   {ssr: false},
> );
> ```

thank youu

**Comment by neelp03** [comment]
Hello, if you are using lottie-web in next.js then you can dynamically load it inside useEffect() and the error will go away

```tsx

'use client';

import React, { useEffect, useRef } from 'react';
import { signatureData } from '../constants/index';

const Signature = () => {
  const animationContainerRef = useRef<HTMLDivElement>(null);
  const titleTextRef = useRef<HTMLDivElement>(null);
  const signatureContainerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const loadLottie = async () => {
      if (!animationContainerRef.current || !titleTextRef.current || !signatureContainerRef.current) return;
      
      const lottie = await import('lottie-web');
      const animation = lottie.default.loadAnimation({
        container: animationContainerRef.current,
        renderer: 'svg',
        loop: false,
        autoplay: true,
        animationData: signatureData,
      });

      const titleTextElement = titleTextRef.current as HTMLElement;
      const signatureContainerElement = signatureContainerRef.current as HTMLElement;
      const navElement = document.querySelector('#navbar') as HTMLElement;
      // ......
      return () => {
        animation.destroy();
      };
    };

    loadLottie();
  }, []);

  return (
    <div className="..." ref={signatureContainerRef}>
      <div id="animation" ref={animationContainerRef}></div>
      <div className="..." ref={titleTextRef}>xyz</div>
    </div>
  );
};

export default Signature;

```

**Comment by timlindsk** [comment]
from @hewelt in https://github.com/Gamote/lottie-react/issues/101#issuecomment-1840516520 : 
..Node v21 introduces a new [navigator API](https://nodejs.org/en/blog/announcements/v21-release-announce#navigator-object-integration), previously present only in client-side code. So document is now reached when being run in Node. One solution would be for lottie-web to just change that condition to one that clearly distinguishes between client and server.

**Comment by RabeeAbuBaker** [comment]
This issue is one release away from being fixed. lottie-web [Version 15.3.0](https://github.com/airbnb/lottie-web/pull/3133) was merged but it was never tagged as something went wrong with one of the release actions. It been like this since Nov 18, 2024, and it seems the project is dead and ignored, its maintainers simply don't care. https://github.com/airbnb/lottie-web/issues/3136

**Comment by zacharytyhacz** [comment]
why is this closed?
