### ISSUE TITLE
5.9.1版本会将文案渲染成多个text标签。之前都是tspan标签

### ISSUE THREAD

**Issue by SJ941127** [airbnb/lottie-web#2741]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
hi, the ticket is empty.
Reopen if you can provide more info
