### ISSUE TITLE
Time expressions fail when lottie.js is bundled with Parcel

### ISSUE THREAD

**Issue by Joolyan** [airbnb/lottie-web#2749]
Environment: macOS 11.6.4
Browser and Browser Version: Chrome 99.0.4844.74, Firefox 98.0 
After Effects Version: 22.2.1

Parcel works perfectly for most animations, however if the animation is driven by an expression which includes time, Parcel's bundling of lottie.js causes the animation to fail.

A work around is to replace time with a slider with a keyframed time value. However, the safer work around is probably not to bundle lottie.js with Parcel.

The attached Zip contains two projects (Basic and Parcel) to illustrate the problem. The square is rotated with time * 100 and the triangle with effect("Time")("Slider") * 100.

This may not be a lottie-web issue, but just thought I should share it here. 
[Lottie_Parcel.zip](https://github.com/airbnb/lottie-web/files/8318659/Lottie_Parcel.zip)

**Comment by bodymovin** [comment]
hi, it might be related to this line
https://github.com/airbnb/lottie-web/blob/master/player/js/utils/expressions/ExpressionManager.js#L730
I see I haven't added time to the variables that shouldn't be removed. I'll add it for the next build and hopefully it will get fixed.
Thanks for reporting it
