### ISSUE TITLE
Animation works locally but not in production (no minification)

### ISSUE THREAD

**Issue by adamrneary** [airbnb/lottie-web#2750]
**Tell us about your environment** 
* **Machine**
Mac OS Monterey 12.2.1 
Intel Core i9

* **Browser and Browser Version:** 
Chrome 99.0.4844.51 (Official Build) (x86_64)

* **After Effects Version:**
Latest

**What did you do? Please explain the steps you took before you encountered the problem.**

* We have a Next.js app using Next version `12.1.0`
* We have downloaded https://cdnjs.cloudflare.com/ajax/libs/lottie-web/5.9.1/lottie.min.js and serve it out of the public folder using `<Script src="/scripts/lottie.min.js" strategy="afterInteractive" />`. The library file is being loaded correctly and with no modifications. `console.log(lottie)` returns the lottie object correctly.
* We are calling the lottie library in the product thusly:

```typescript
import intro from './lottie/reportGenIntro';
lottie.loadAnimation({
  container: document.getElementById('lottie_intro'),
  renderer: 'svg',
  loop: false,
  autoplay: true,
  animationData: intro,
});
```

We have tried adding the lottie json to the public directory and importing it from there. We also tried converting to TypeScript and importing directly. Same outcome either way.

Animation data as exported from AE: https://gist.github.com/adamrneary/f00d06f58711fb9b1cb5f65bfa9d29e9
Animation data as converted to TypeScript: https://gist.github.com/adamrneary/f430ad9556142f8a90d47fdb7d380511

`console.log(intro)` returns the same object locally and in production.

**What did you expect to happen?**

We want the animation to work locally and in production

**What actually happened? Please include as much _relevant_ detail as possible.**

The animation works perfectly in local development.
The same code in production renders an <svg /> containing an empty <g/>
No errors log to the console

```
<div id="lottie_intro">
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 200 200"
    width="200"
    height="200"
    preserveAspectRatio="xMidYMid meet"
    style="
      width: 100%;
      height: 100%;
      transform: translate3d(0px, 0px, 0px);
      content-visibility: visible;
    "
  >
    <defs>
      <clipPath id="__lottie_element_2">
        <rect width="200" height="200" x="0" y="0"></rect>
      </clipPath>
    </defs>
    <g clip-path="url(#__lottie_element_2)"></g>
  </svg>
</div>
```

Very strange that it seems to be the same code in both environments running the same animation data input. Not sure where to start!

Very happy to collaborate on a fix, document learnings, etc. Any help would be great!

**Please provide a download link to the After Effects file that demonstrates the problem.**

[File available here
](https://drive.google.com/file/d/17dmkU9fATsyzdF46J5K44p-UR-ONaTrV/view?usp=sharing)

**Comment by bodymovin** [comment]
hi, do you have a link that I can check?
Is the html snippet you shared, what it renders in production?

**Comment by adamrneary** [comment]
@bodymovin thanks so much for the quick response. I managed to put up a temporary page that exhibits the issue here: 

https://dashboard-preview-pr-10992.onrender.com/totallyobscurelottieurl

Again, this works locally, but when deployed does not. Any help sorting this out would be great!

**Comment by bodymovin** [comment]
Hi, thanks for sharing, it seems that the exported json you're using has an expression exported and it looks like this:
`var $bm_rt;\\n$bm_rt = loopOut('cycle', 1);`
I added that same expression and exported it myself and mine looks like this:
`var $bm_rt;\n$bm_rt = loopOut('cycle', 1);`
(notice the double slash on yours)
Not sure why it doesn't break on your local implementation, but if you remove the extra escaped `\` it should work fine.
Can you think of anything in particular that could have added that additional escaped slash to your export?

**Comment by adamrneary** [comment]
Hmm. Very strange indeed. How are you viering the expression exported in the deployed version of the code?

If you check the two gists, both the json and ts versions of the animation data have the correct `\n` value, so I am not sure where the extar `\` could be coming from.

Since it is a newline character, I tried deleting it entirely, which leaves `x: "var $bm_rt;$bm_rt = loopOut('cycle', 0);",`. This, too, is working locally, but the same thing pushed to our live example, it is still not working.

I would love to help diagnose this with you if you could point me in the right direction for diagnosing it. Or if you see anything funky with the refreshed version, I can tweak it accordingly!

Thanks again!

**Comment by bodymovin** [comment]
Ok, I added a breakpoint on the try/catch statement of lottie, and I see a different error now, it's related to using eval:   
`EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' www.google-analytics.com www.googletagmanager.com apis.google.com maps.googleapis.com cdnjs.cloudflare.com".`

**Comment by adamrneary** [comment]
@bodymovin that makes sense!

I read through https://github.com/airbnb/lottie-web/issues/289 and switched to Lottie Light as a result, and we're at least rendering right now, but the animation is not behaving properly (it should not stop after rotating).

To what extent would we have to allow `unsafe-eval` in order to use the normal Lottie library? Do you have a sense for the minimum requirement I could take back to our security team? I am sure we don't want to open up an unsafe security hole for this, but the Light version doesn't seem to render the animation correctly.

Eager to get your thoughts — we would love to figure this one out!

**Comment by bodymovin** [comment]
expressions use eval to execute, so if you have any expression on your animation, you'll need to change the content-policy header to allow for eval to be executed.
Lottie Light doesn't support expressions, and that's why the animation runs, but rotation stops because it is using one.

**Comment by adamrneary** [comment]
Ah. As someone who is brand new to all of this and excited to learn more what does it take in after effects to avoid expressions? Is that something our designer would be able to modify easily? Or do most animations involve expressions, and it's not something we can systematically avoid?

**Comment by bodymovin** [comment]
it depends on the animator. Some make use of them extensively and others don't use them at all.
In this case, it seems there is only one expression used and it should be very simple to replace it with some extra keyframes.

**Comment by adamrneary** [comment]
Awesome. Thanks again for helping us diagnose this, and for explaining the nuances. We can take it from here!
