### ISSUE TITLE
Standalone svg player crashes with Google Tag Manager 

### ISSUE THREAD

**Issue by DzixxxVizlib** [airbnb/lottie-web#2753]
**Tell us about your environment**
latest Mac OS 

* **Browser and Browser Version:** latest chrome
* **After Effects Version:** latest chrome

**What did you do? Please explain the steps you took before you encountered the problem.**
I applied Google Tag Manager script to the index.html

**What did you expect to happen?**
That everything will be working

**What actually happened? Please include as much _relevant_ detail as possible.**
I started facing issue with `TypeError: Cannot read properties of null (reading 'replace')`

**Please provide a download link to the After Effects file that demonstrates the problem.**

Link to problematic lines: https://github.com/airbnb/lottie-web/blob/master/build/player/lottie_svg.js#L5231 
GTM is removing scripts and that's why this standalone block is not working

**Comment by bodymovin** [comment]
hey, thanks. I guess the script that lottie is finding doesn't have a src attribute, and that's why it's null.
I'll add a check for it, and at least prevent the crashing.

**Comment by DzixxxVizlib** [comment]
awesome, thank U <3
