### ISSUE TITLE
Text Issues - getting duplicate letters

### ISSUE THREAD

**Issue by shavacadoo** [airbnb/lottie-web#2762]
**Tell us about your environment**

* **Browser and Browser Version:** Chrome Version 100.0.4896.75 (Official Build) (64-bit)
* **After Effects Version:** 22.2.1

I am trying to render my animation in "Banner" format, I use this very regularly, and have never had this issue before.
I have an animation that has the word "Taste" in it. When I render it out I comes out as "Tastte" with the extra t on top of the e.

I have the Glyphs option turned on in the settings

I have tried a few things to fix it so far with no luck.
* Tried different renderers - SVG and Canvas.
* Tried putting a space in between the t and e then bringing the tracking back.
* Tried putting spaces between every letter.
* Tried changing the font in between the t and the e.
* Removed effects & masks (I was using a stroke effect with masks to do a write-on effect).
* Changed the font to Arial, which worked, but changing back to my original font (Lemongrass) brings the issue back.

![screenshot in after effects](https://user-images.githubusercontent.com/102838373/162665063-034beddb-6f6f-4f48-9bf6-9d3b3444d382.png) <- Screenshot from After Effects
![screenshot play playback on lottiefiles](https://user-images.githubusercontent.com/102838373/162665201-aecceeeb-6b37-4339-89a5-6ba24a834393.png) <- Screenshot from Lottiefiles (it appears the same way in h5validadtor)

Any help would be greatly appreciated.
Thanks!

**Comment by bodymovin** [comment]
hi, can you share the .aep and the font?

**Comment by shavacadoo** [comment]
[Taste-Text-Issues.zip](https://github.com/airbnb/lottie-web/files/8470033/Taste-Text-Issues.zip)
The Font is Lemongrass - an Adobe Font

**Comment by bodymovin** [comment]
it seems to be related to the font and its "t" character in particular.
I'm guessing that AE is messing up converting the character into a shape. Probably related to its ligatures settings, but I'm not sure.
I don't think there's much I can do on my side to fix this.

**Comment by shavacadoo** [comment]
Okay, all good.
Thanks for your help and for making such a great plugin 😄
