### ISSUE TITLE
Wave warp Effect Not working After Export From Bodymovin

### ISSUE THREAD

**Issue by alexis00897** [airbnb/lottie-web#2765]
When I'm trying to export a simple wave FX comp builtin After effects, it will just export a static object I tried with advanced export settings and everything but it looks like bodymovin not supported this effect.

Design file for reference: https://mega.nz/folder/cNNgQB7S#traqVa-c4KyrnPSoDInK-Q

**Comment by alexis00897** [comment]
When I'm trying to export a simple wave FX comp builtin after effects plugin, it will just export a static object I tried with advanced export settings and everything but it looks like a bodymovin not supported this effect.

**Comment by bodymovin** [comment]
Hi, unfortunately those types of effects are not supported by the lottie players.
