### ISSUE TITLE
Drop shadow and fill effects might not be correctly merged in SVG

### ISSUE THREAD

**Issue by WoobyKnou** [airbnb/lottie-web#2773]
Hello dear Lottie team !
First of all thank you for providing this incredible tools that are Bodymovin and lottie !

**Tell us about your environment**
* **Browser and Browser Version:** Chrome 100.0.4896.127
* **After Effects Version:** v22.3

I am testing BodyMovin and Lottie player and during my tests I encountered some troubles on animations that are using multiple effects on the same object.

**What did you do? Please explain the steps you took before you encountered the problem.**
In my example, I have a solid with 1) a Fill effect and 2) a Drop Shadow effect. When watching the result in my browser with the SVG renderer, I can only see the Drop Shadow effect (after putting the renderer settings as adviced here : https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#filtersize-svg-renderer). The Fill effect doesn't show at all.

When I change the order of the effects, however, the result seems correct : I have a Drop Shadow and the Fill effect applied on it.

**What did you expect to happen?**
After digging a little bit in the rendered SVG, I think that the problem comes from the fact that the SVG filters are not merged correctly. I tried to get the result I wanted by changing the SVG by myself and manage to have the result I wanted. Also I'm not sure why there is a sort of duplicated filters in the SVG... But I am a newby in SVG filters so maybe it's just me....

**Please provide a download link to the After Effects file that demonstrates the problem.**
I put the link of my tests hoping that it can help you guys resolve this problem. In the zip you can find the following files : 
- The simplest aep file demonstrating the error
- The lottiefile generated from the aep 
- The html demo generated from the aep with the filtersize adapted to show the Drop Shadow effect
- The report.json file generated
- Two svg files : rendered_svg.svg is the SVG I get in the browser using the demo html file and the expected_svg.svg is the svg I was expecting to get

I hope my tests can help you resolve this problem... I'm still a baby developer so I wish I could help you more but I doubt I can... I wish you all the best !

Knou

[drop_shadow_fill_issue.zip](https://github.com/airbnb/lottie-web/files/8529381/drop_shadow_fill_issue.zip)
![expected_svg](https://user-images.githubusercontent.com/104129615/164418479-5956af95-083b-4272-91a3-04be7be613b0.svg)
![rendered_svg](https://user-images.githubusercontent.com/104129615/164418483-6c59aba2-ccd6-491e-a8b7-e675e06c9ff1.svg)

**Comment by bodymovin** [comment]
Thanks for reporting this! A fix will be available on the next release.

**Comment by WoobyKnou** [comment]
Wow thanks for replying to this issue this quick !
Wish you all the best !
