### ISSUE TITLE
Importing JSON files to re-create AEP files (but PNGs now missing)

### ISSUE THREAD

**Issue by desidem** [airbnb/lottie-web#2788]
I'm working on a Macbook Pro (M1) Monterey.

I don't have a problem per se. I'm re-importing my json files (_successful_ Lottie renders).

I had a catastrophic computer event. A great number of my After Effects 2022 source files (aep) are gone (and my AI files too, etc). However, I successfully re-imported some of these aep files back into AE using the Bodymovin extension (5.7.4) Thank you for this feature!

However, I'm noticing that some are not complete: i.e., those JSON files that I created with PNG files. I am almost 100% positive I created the json files with the **Assets 'include in json'** selected. I know that the JSON file work and include the PNGs in the final animation. However, re-importation of the JSON file back into AE excludes those original PNG files. 

Does the current 'Import Lottie Animation' allow for the png files to be included in the creation of the AE project file? Do I have to update my Bodymovin extension (5.7.4)?

**Comment by bodymovin** [comment]
hi, reimporting the encoded images is not supported yet. What I'd recommend as a workaround is running the animation on the browser, right clicking on the images to save them manually, and then importing them on the project in the correct location.

**Comment by desidem** [comment]
Thank you! I will try that. I love Bodymovin/Lottie.
