### ISSUE TITLE
lottie_canvas_worker destroy() doesn't cleanup offscreen canvas created by loadAnimation (resolveAnimationData)

### ISSUE THREAD

**Issue by RobMeyer** [airbnb/lottie-web#2789]
**Tell us about your environment**
Discovered issue in React app and was able to repro in minimal html+js repro app (https://codesandbox.io/s/lottie-canvas-worker-destroy-bug-4w3oki). 

* **Browser and Browser Version:** Edge 101.0.1210.53 and Chrome 102.0.5005.63
* **After Effects Version:** N/A

**What did you do? Please explain the steps you took before you encountered the problem.**
Switched react app's lottie component implementation from svg (working), to canvas (worked), then to canvas-worker (encountered issue). 

When react component wraps lottie (via useEffect with React.DependencyArray) re-renders with changes to props which need to be passed to `lottie.loadAnimation`, we need to cleanup the useEffect which involves destroying the previously-loaded animation, then call `loadAnimation` again with the new arguments (still using the same `container` element). However, the call to destroy() doesn't clean-up all the initialization that the previous `loadAnimation` call made (in particular, the creation and appending of a canvas element to the container's children). For each call to `loadAnimation` (if `rendererSettings.canvas` is not provided), lottie will create a 'canvas' element and append it to 'container', however, a subsequent call to 'destroy' doesn't remove the created canvas. 

Because React components have specific rules around state and initialization order, uses a virtual dom, and asynchronous callbacks, integration with `lottie.loadAnimation` can require the same 'container' DOM element to be provided to multiple `loadAnimation` calls. lottie should support this workflow, so long as `destroy()` is always called on a previous `loadAnimation` prior to an additional `loadAnimation` using the same `container` element. In other words, I don't see a viable workaround that could be made from client code; a fix to lottie-web would keep the react integration cleaner and more reliable, and I believe would also benefit a pure javascript implementation, as well as other UI frameworks in which a single `container` DOM element may be used to host multiple animations (not at the same time).

**What did you expect to happen?**
Either (a) each call to destroy() should clean up the canvas that was created and appended to container, OR (b) a call to loadAnimation with a container which was previously loadAnimation+destroy'd should re-use the canvas that was previously created and appended rather than appending an additional canvas. I think either strategy could be viewed as valid contracts, though I'd prefer (a) as it feels cleaner, with fewer residual side-effects left visible to clients.

**What actually happened? Please include as much _relevant_ detail as possible.**
Within lottie.destroy(), `animation.container` is undefined so the call to `animation.container.innerHTML = ""` doesn't get executed.
![image](https://user-images.githubusercontent.com/2568938/170798071-2304c39e-115c-42b5-afd9-3fb8922f8688.png)

A subsequent call to `lottie.loadAnimation` with the same `container` will also go through the resolveAnimationData path where a canvas gets created and appended to the container.
![image](https://user-images.githubusercontent.com/2568938/170798178-16a90ddf-8ef0-44ed-97f5-3d9560c077e5.png)
![image](https://user-images.githubusercontent.com/2568938/170798312-d83f9c4e-a8d1-42de-99e5-7fb2c002ef2d.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
This issue doesn't seem related to the underlying json/after effects, but for completeness I reproduced the issue with an internal lottie not available for distribution, and quickly reproduced with a lottie file from lottiefiles, copied here: https://codesandbox.io/s/lottie-canvas-worker-destroy-bug-4w3oki?file=/star.lottie.json

**Comment by bodymovin** [comment]
thanks for the demo! I've fixed the issue and it will be available on the next build.
This only happened if the destroy method was called before the data was loaded.
Having said that, because of the cost of instancing a new animation, whenever possible, it's better to call the loadAnimation as little as possible.
I don't know this specific use case, and perhaps this is intentional, but whatever you can do to memoize the props in order to avoid triggering the useEffect more that it is necessary, it's worth looking into.

**Comment by RobMeyer** [comment]
Great! Do you have a link to the PR? What is lottie's release schedule?

Regarding the use case: There are a lot of ways this could happen, but I tend to see one of three root causes:
1. As you called out, lack of memoization of component props can result in wasted renders and unnecessary cleanup and re-initialization of the lottie animation.
2. The app state may change such that a given piece of app ux that was rendering one lottie animation, may need to render another animation instead (or the same animation with different props/configuration that require lottie.loadAnimation re-initialization). This is pretty rare and typically doesn't happen so quickly to hit this timing issue, where the destroy call is made before the prior load was completed.
3. Starting in v18, React's <StrictMode> in non-production builds results in an extra unmount and remount the first time each component is mounted, as a means of making sure code is robust against unmount and remounting.

**Comment by RobMeyer** [comment]
@bodymovin is there an update on this? Let me know if I can help.

**Comment by RobMeyer** [comment]
@bodymovin looks like this was fixed with [commit ccb3df5b3ae9a2b376658ca4242d10165c1e49c2](https://github.com/airbnb/lottie-web/commit/ccb3df5b3ae9a2b376658ca4242d10165c1e49c2)! Verified working in the sandbox with v5.9.6
