### ISSUE TITLE
Problem with Lottie Export

### ISSUE THREAD

**Issue by ccr-515** [airbnb/lottie-web#2796]
<img width="636" alt="Screen Shot 2022-06-09 at 1 48 30 PM" src="https://user-images.githubusercontent.com/84052709/172921991-09d49d82-ba54-46d8-9d5f-651f148bb1fd.png">

**Tell us about your environment**

* **Browser and Browser Version: Chrome 102
* **After Effects Version: 22.4

**What did you do? Please explain the steps you took before you encountered the problem.**
I created a small animation with no background.  When I try to render it from Bodymovin first it shows up blank in the preview mode (image attached) and then it shows up completely blank in the rendered .JSON

**What did you expect to happen?**
I was expecting a lottie animation to play in the preview or at the very least to be able to use it once it has been rendered.

**What actually happened? Please include as much _relevant_ detail as possible.**
When I go to preview the animation it is completely blank.  After uploading the .JSON to webflow it also shows up completely blank.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/tibda2ba66vy05k/white%20spiral.aep?dl=0

**Comment by bodymovin** [comment]
Video layers are not supported by lottie unfortunately.
