### ISSUE TITLE
Adobe Animate Lottie Preview

### ISSUE THREAD

**Issue by edwardjonesdesign** [airbnb/lottie-web#2802]
I am unable to get the Lottie extension to preview anything. I see the timeline playing but no art/objects are displayed. I have tested using just 1 shape on the timeline (at the root) with no tweening etc and still nothing.

I am using Windows and Adobe Animate CC. 
I used the ExtensionManagerInstaller.exe to install animate-plugin-0.4.0

I export the json to see what happens and get the error:

TypeError: this.elements[n].destroy is not a function This is located at: at n (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:24:235846) at div at or (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:80:1397558) at div at div at Hr (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:94:2495) at ro (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:148:20) at to (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:170:34) at r (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:76:91709) at yn (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:80:19) at r (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:76:92601) at r (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:76:88724) at r (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:76:89639) at div at i (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:24:250309) at Fn (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:80:2102) at Bn (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:80:1074) at xt (file:///C:/Program%20Files%20(x86)/Common%20Files/Adobe/CEP/extensions/com.lottiefiles.animate/index.html:351:1078)

Does anyone have suggestions to try? Thanks for any help!

**Comment by bodymovin** [comment]
hi, can you report this on the lottiefiles adobe animate extension repository?
