### ISSUE TITLE
Svelte: animation not showing when using animationData

### ISSUE THREAD

**Issue by mia-cx** [airbnb/lottie-web#2814]
**Tell us about your environment**
Windows 11 - Visual Studio Code - SvelteKit

* **Browser and Browser Version:**
  * Chrome 103.0.5060.114, Firefox 102.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**
- import json file as object in js
- `loadAnimation()` using said object as `animationData`
```ts
import web from "lottie-web";

import intro from "$lib/assets/lottie/intro.json";

web.loadAnimation({
  container: document.getElementById("lottie")!,
  loop: true,
  autoplay: true,
  renderer: "svg",
  animationData: intro,
  name: "intro",
});

// compare to loadAnimation() using path in stead of animationData, path works fine...
web.loadAnimation({
  container: document.getElementById("lottie2")!,
  loop: true,
  autoplay: true,
  renderer: "svg",
  path: "/assets/lottie/intro.json",
  name: "intro",
});
```

there is a copy of the same file in a static directory so i can use the `path` option in `loadAnimation()` to compare.

**What did you expect to happen?**
I expected lottie to load the animation using `animationData`. and play it in the `#lottie` div

**What actually happened? Please include as much _relevant_ detail as possible.**
The above did not happen. it did work with the `path` option, but I would like to use animationData so I can import the animationData elsewhere.

[intro.json](https://gist.github.com/mia-cx/7e8c30f0e35ba36ea37f4f0d18125d00)

**Comment by bodymovin** [comment]
is the import resolving to a string or an object?

**Comment by mia-cx** [comment]
to an object, when console logging it shows an object

**Comment by bodymovin** [comment]
can you try setting different names to each instance?

**Comment by mia-cx** [comment]
code:
```ts
  import { browser } from '$app/env';
  import web, { type AnimationItem } from 'lottie-web';

  export let lotties: any[];

  lotties.forEach((lottie) => console.log('animationData object: ', lottie));

  let i = 0;

  let animations: AnimationItem[] = [];

  let staticAnimations: AnimationItem[] = [];

  if (browser) {
    for (let lottie of lotties) {
      animations.push(
        web.loadAnimation({
          container: document.getElementById('lottie')!,
          loop: true,
          autoplay: true,
          renderer: 'svg',
          animationData: lotties[i],
          name: 'intro'
        })
      );
    }
    staticAnimations.push(
      web.loadAnimation({
        container: document.getElementById('lottie')!,
        loop: true,
        autoplay: true,
        renderer: 'svg',
        path: '/assets/lottie/intro.json',
        name: 'intro'
      })
    );
    staticAnimations.push(
      web.loadAnimation({
        container: document.getElementById('lottie')!,
        loop: true,
        autoplay: true,
        renderer: 'svg',
        path: '/assets/lottie/headbang.json',
        name: 'intro'
      })
    );
    staticAnimations.push(
      web.loadAnimation({
        container: document.getElementById('lottie')!,
        loop: true,
        autoplay: true,
        renderer: 'svg',
        path: '/assets/lottie/settle.json',
        name: 'intro'
      })
    );

    for (let animation of animations) {
      console.log('AnimationItem (using animationData): ', animation);
    }
    for (let animation of staticAnimations) {
      console.log('AnimationItem (using path): ', animation);
    }
  }
```
log:
![image](https://user-images.githubusercontent.com/42698687/179045867-965f800b-1d66-4157-bd45-16485b3c5bbf.png)

animationData:
![image](https://user-images.githubusercontent.com/42698687/179045922-4c281b41-258f-4c32-a353-96c996d5f09b.png)

path:
![image](https://user-images.githubusercontent.com/42698687/179045963-f989c94f-e1a8-4cdb-a699-184415adee91.png)

**Comment by mia-cx** [comment]
with `name`s set to Math.random(), it still doesn't show when trying with `animationData`
but with `path` it has no issue with different instances with the same `name`

**Comment by mia-cx** [comment]
let me make a dummy repo, will respond in a second

**Comment by mia-cx** [comment]
sveltekit repo with my issue:
https://github.com/mia-cx/svelte-lottieplayer-2814

**Comment by bodymovin** [comment]
I'm not succeeding in running the demo. there seems to be some vite dependency conflict between v2 and v3

**Comment by mia-cx** [comment]
sveltekit hasn't updated to vite v3 yet

**Comment by mia-cx** [comment]
seems that an update on my front should get it working, by manually changing versions, i will push this right now

**Comment by bodymovin** [comment]
I'm seeing this

Error: Vite version 2 is no longer supported. Please upgrade to version 3
    at check_vite_version (file:///C:/Users/tropi/Projects/users/svelte-lottieplayer-2814/node_modules/@sveltejs/kit/dist/vite.js:3170:9)

**Comment by mia-cx** [comment]
I just pushed the package.json to vite v3!

**Comment by bodymovin** [comment]
It seems that something (I guess Svelte) is clearing the content of the `<div/>` that contains the animations on its first render.  
I'm not familiar with svelte, so I can't tell why it is behaving that way.  
But a simple way to check that lottie is working correcrtly is wrapping the for loop on a timeout.  
```js
setTimeout(() => {
    for (let lottie of lotties) {
      animations.push(
        web.loadAnimation({
          container: document.getElementById('lottie')!,
          loop: true,
          autoplay: true,
          renderer: 'svg',
          animationData: lotties[i],
          name: `${Math.random()}`
        })
      );
    }
  }, 0)
```

**Comment by mia-cx** [comment]
yep, [adding the svelte `onMount()` call](https://github.com/mia-cx/svelte-lottieplayer-2814/commit/dc30d7680b9b96820562fa3e3565e4e98cffbdd1) fixes the issue.
