### ISSUE TITLE
Lottie animation (scroll type) is played automatically if you switch to another tab in the browser and come back.

### ISSUE THREAD

**Issue by KPABOOKING** [airbnb/lottie-web#2817]
Lottie animation (scroll type) is played automatically if you switch to another tab in the browser and come back.
Lottie animation call code:
`<lottie-player
  id="firstLottie"
  src="https://assets1.lottiefiles.com/packages/lf20_91DQOE.json"
  style="width:100%; height:100vh;" background="transparent"  speed=".5" width="100%" height="100%" preserveAspectRatio="xMinYMin slice" loop autoplay>
</lottie-player>`

` <script>
        LottieInteractivity.create({
  mode: 'scroll',
  player: '#firstLottie',
  actions: [
    {
      visibility: [0, 1],
      type: 'seek',
      frames: [0, 150],
        loop: false,
        autoplay: false,
    },
  ],
});
        </script>`

**Comment by bodymovin** [comment]
Hey! Can you report this to the lottieFiles team? This repository is not the one for this functionality.
