### ISSUE TITLE
Make my lottie lighter

### ISSUE THREAD

**Issue by Baptou969** [airbnb/lottie-web#2818]
Hello, I am unable to make my export lighter. Currently I am at 340kb on the .json. Could you help me do better ? (here is my files attached)

[OCR-simple.zip](https://github.com/airbnb/lottie-web/files/9150756/OCR-simple.zip)

Thank you :)

**Comment by bodymovin** [comment]
hi, the json file you shared is 270kn, and compressed is only 34kb. Do you need it smaller that that?

**Comment by Baptou969** [comment]
Thank you for your reply.
What do you mean by "compressed"? Is it the fact that it's in a zip file? Because the fact of being in a zip file has no use for me, it is not usable, is it ?
<img width="822" alt="image" src="https://user-images.githubusercontent.com/109677897/181041915-a1f2cd34-19c1-4999-9054-b2b05e180454.png">


Otherwise at home, the file weighs well 340ko.

**Comment by bodymovin** [comment]
Usually web hosts gzip files over the network so the real file size is not that relevant.
How are you planning to use the animations?

**Comment by Baptou969** [comment]
I have a site coded on Hubspot, I made a module that allows you to interpret the .json file that you insert in the backoffice.
It looks like this :
![Capture d’écran 2022-07-26 à 22 42 55 1](https://user-images.githubusercontent.com/109677897/181108386-db47c61e-378d-488a-8415-40e8b823b2cf.png)

You can see here : https://www.asys.fr/gestion-rh/logiciel-de-gestion-de-notes-de-frais

My only goal is to have the fastest possible page load and have smooth animations.

**Comment by bodymovin** [comment]
![image](https://user-images.githubusercontent.com/11096607/181118738-913f9319-a6f4-478b-a05c-e9ce4e29d651.png)
Your web host is indeed compressing the json, so its size through the network ends up being only 32Kb

**Comment by Baptou969** [comment]
Oh thank you, so everything is ok for me :)
Have a good day !
