### ISSUE TITLE
Render failed, weird behavior 

### ISSUE THREAD

**Issue by AniaBerthelot** [airbnb/lottie-web#2820]
![image](https://user-images.githubusercontent.com/59117177/181020837-3c06c290-612e-4b61-b14c-030d166292ec.png)

I wonder what's the issue source, 
Is there a way to get a rendering report with the issue layer source?
I'm using windows and my composition is using trim path and trace path, can this be the issue knowing that i converted all the expressions to keyframes.

**Comment by AniaBerthelot** [comment]
I tried to render a basic composition without animation and it worked like a charm
![image](https://user-images.githubusercontent.com/59117177/181023228-d8ffad73-ebc2-4a26-8134-ba3d7e31334f.png)

**Comment by bodymovin** [comment]
hi, can you share the project that is breaking?

**Comment by AniaBerthelot** [comment]
![image](https://user-images.githubusercontent.com/59117177/181045805-f307a1f7-dcee-47c8-8d67-ab755a4ce69c.png)
After reading the report I 
1 - Converted AI files to shapes and hided original files but it looks like it keeps rendering them + the new shapes aren't ok. How to resolve this pls. Thks
2 - Removed expressions, that part is ok

**Comment by AniaBerthelot** [comment]
[Animation folder.zip](https://github.com/airbnb/lottie-web/files/9191775/Animation.folder.zip)
Is this ok?

**Comment by AniaBerthelot** [comment]
> [Animation folder.zip](https://github.com/airbnb/lottie-web/files/9191775/Animation.folder.zip) Is this ok?

Could please give me a feedback at least? Thks

**Comment by AniaBerthelot** [comment]
I got also a failing render without errors
![image](https://user-images.githubusercontent.com/59117177/181119604-d882df36-c967-46ec-bfd4-42f505300ee1.png)
I really need your help, thks

**Comment by bodymovin** [comment]
Can you share what comp you're rendering and if you configured any special settings?

**Comment by AniaBerthelot** [comment]
Comp 1 is the wanted result, others are adapted compositions for rendering ( example: expression conversion, fill effect removal... ). FYI I tried both LottieFiles and Bodymoving, the latest is more transparent thanks to its progress bar and issues report

**Comment by bodymovin** [comment]
Comp 1 has all layers hidden except for 1, is that correct?
I tried exporting it and it worked correctly

**Comment by AniaBerthelot** [comment]
I edit it immediately and send you a cleaner version, thank you

**Comment by AniaBerthelot** [comment]
> Comp 1 has all layers hidden except for 1, is that correct? I tried exporting it and it worked correctly

Actually it's comp6 my bad.
