### ISSUE TITLE
How to solve the problem that the 22 second animation will stall every 5 seconds or so?

### ISSUE THREAD

**Issue by xiaojhh** [airbnb/lottie-web#2835]
Chrome 104.0.5112.81 （64）
"lottie-web": "^5.9.6",
```

   this.$nextTick(() => {
            this._anima = this.$lottie.loadAnimation({
                container: document.getElementById(`lottie_box`),
                renderer: "svg", 
                loop: true,
                autoplay: false, 
                animationData: ballLottie 
            });
            this._anima.setSubframe(false);
 
            return () => {
                this._anima && this._anima.destroy();
            };
        });
```

**Comment by xiaojhh** [comment]
I tried using 30fps and 60fps

**Comment by xiaojhh** [comment]
I also tried anima.setSubFrame (false)

**Comment by xiaojhh** [comment]
I feel helpless, is it the problem of exporting JSON?

**Comment by xiaojhh** [comment]
I'm desperate for help

**Comment by bodymovin** [comment]
hi, can you elaborate on what stall means? Do you have a working link?

**Comment by xiaojhh** [comment]
> hi, can you elaborate on what stall means? Do you have a working link?

URL The external network cannot access the URL

**Comment by xiaojhh** [comment]
> hi, can you elaborate on what stall means? Do you have a working link?



>

**Comment by xiaojhh** [comment]
> hi, can you elaborate on what stall means? Do you have a working link?

Or is there anything else you need from me
