### ISSUE TITLE
after effect lotiee file not play to start,its play to middle after keep in react native project

### ISSUE THREAD

**Issue by jainrishabh038** [airbnb/lottie-web#2839]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
hi, can you share more information? A link to a reduced example?
