### ISSUE TITLE
Can't use Lottie in webflow, exported with after effects

### ISSUE THREAD

**Issue by jjkauer** [airbnb/lottie-web#2844]
I exported a Lottie with after effect and bodymovin and there is only a question mark in webflow.
<img width="249" alt="Screenshot 2022-08-30 at 2 41 39 PM" src="https://user-images.githubusercontent.com/112487535/187439214-8497a481-6d24-4b3d-9812-99a69865a0a3.png">

**Comment by bodymovin** [comment]
hi, I'd suggest that you ask on webflow forums, they might have more information on how it works.
