### ISSUE TITLE
Problem exporting AE to Bodymovin

### ISSUE THREAD

**Issue by AdrienCSC** [airbnb/lottie-web#2853]
Hi, I'm learning AE to create some animated stuff for my website. 

I have followed along a tutorial to create a type sphere animation. I dropped a screenshot of the animation.

<img width="1790" alt="Capture d’écran 2022-09-14 à 18 58 20" src="https://user-images.githubusercontent.com/113544134/190216660-6d25edff-7068-4117-9cb1-fa8ae6eb555c.png">

I now want to render it with bodymovin to use it on the web, but when I do so, only the first composition with the flat text is rendered. And the sphere effect is left out. I tried to mess with the setting of bodymovin but can't find the way to make it work. 

Anyone has an idea of the issue ? Sorry if it's super obvious, AE is very knew for me and I don't understand most of it for the moment.

Thanks for your help.

A.

**Comment by Hamza-md** [comment]
It is because you are using a 3D effect, which is not supported by Lottie. So when you export it out, It ignores the effect and only exports the layer. 

A list of supported effects in Lottie: https://github.com/airbnb/lottie-web/wiki/Effects

**Comment by AdrienCSC** [comment]
Ok, thanks for your answer ! I will have to do otherwise then.
