### ISSUE TITLE
There is no com.adobe.CSXS.6.plist

### ISSUE THREAD

**Issue by Drjacky** [airbnb/lottie-web#2867]
**Tell us about your environment**
macOS

* **After Effects Version:** After Effect 22.6.0

**What did you do? Please explain the steps you took before you encountered the problem.**
I'm looking for `com.adobe.CSXS.6.plist` according to the **Option 4**
<img width="287" alt="Screenshot 2022-10-26 at 16 37 58" src="https://user-images.githubusercontent.com/2296754/198071443-1e432751-603a-4934-903c-3fd24c6e64c7.png">

**Comment by bodymovin** [comment]
not sure if mac has changed those definitions. I'd try to Google if that's the case.
You should also make sure the `6` is replaced depengind on the AE version you have installed

**Comment by Drjacky** [comment]
Even without doing that, it works and is displayed in AE.
