### ISSUE TITLE
Hello! I'm rendering a file in After Effects 2019 using Bodymovin and it's suddenly started giving me this error, though it was ok with this file just a minute before. It happens with all the files now.

### ISSUE THREAD

**Issue by Julia111-tech** [airbnb/lottie-web#2871]
![001](https://user-images.githubusercontent.com/117319477/199611321-468ed233-2b60-4fc6-ba91-859b95cbdbd4.PNG)

**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
hi, it looks like it's not allowed to create folders. Could it be some permissions issue?

**Comment by Julia111-tech** [comment]
Hi, thanks for the reply. Looks like it, yes, but I've already found out the error. I looked above the comments on that error message and it said to allow AE to write scripts and after that it worked.

**Comment by kudanai** [comment]
Glad it worked out. Can we close this issue if your problem is fixed?
