### ISSUE TITLE
Does `lottie-web` need to have sideEffects?

### ISSUE THREAD

**Issue by Amour1688** [airbnb/lottie-web#2886]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

Use webpack to build the code below:

```ts
import Lottie from "lottie-web"

if (false) {
  Lottie
}
```

**What did you expect to happen?**

The output should not contain any code of `Lottie-web`.

**What actually happened? Please include as much _relevant_ detail as possible.**

<img width="764" alt="image" src="https://user-images.githubusercontent.com/31695475/205342785-205ed63c-9ec3-47d8-a97e-834df9e6f2b3.png">

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
hi, can you share some more details on what that example is revealing?
Would you expect the lottie bundle not to be loaded because it is not being used?

**Comment by Amour1688** [comment]
In my SSR project, I don't want Lottie to be bundled into the server output.
