### ISSUE TITLE
Javascript Expression Engine

### ISSUE THREAD

**Issue by marikreasidigital** [airbnb/lottie-web#2900]
Hi there, 

i have an issue with lottie files that exported from Adobe AE (latest CC), that has Javascript as the Expression engine.
what i need is to get the font color from a text layer, into a shape color, but it does not work as intended

Project settings
![image](https://user-images.githubusercontent.com/47040279/209944056-3bfe67ce-af21-4a65-bb75-9d1a6468353d.png)

on AE, it shows that the shape is getting the text layer font color
![image](https://user-images.githubusercontent.com/47040279/209944130-960ae56f-cae4-4112-8e7c-1f714cf24e35.png)

it is a Fill effect, tied to text style - i also added 'use javascript' 
![image](https://user-images.githubusercontent.com/47040279/209944198-b66d0157-2426-4e01-a16b-106881e13cb3.png)

but when exported, the shape are revert back to its original color
![image](https://user-images.githubusercontent.com/47040279/209944319-5459eb91-0bbb-4356-94ba-6792e026a09a.png)

is there a workaround for this issue? getting the font color using 'Legacy Extendscript' is not possible afaik, so it has to be Javascript expression engine

**Comment by marikreasidigital** [comment]
Bodymovin export settings 
![image](https://user-images.githubusercontent.com/47040279/209944745-3d296a76-d131-401c-9460-2c5d05efea42.png)

**Comment by bodymovin** [comment]
hi, can you share a basic .aep with the issue that I can test?

**Comment by marikreasidigital** [comment]
[Github.zip](https://github.com/airbnb/lottie-web/files/10378431/Github.zip)
Sure, files attached , thank you :)

**Comment by bodymovin** [comment]
the fill color style wasn't supported from expressions. I've added support now, but it will be available on the next version

**Comment by marikreasidigital** [comment]
Working as intended with version 5.10.2
