### ISSUE TITLE
updateDocumentData not triggering re-renders other attributes expect for text. 

### ISSUE THREAD

**Issue by orenlwsc** [airbnb/lottie-web#2902]
Hello, 

I'm trying to use the [updateDocumentData API](https://github.com/airbnb/lottie-web/wiki/TextLayer.updateDocumentData) to update text elements. Currently, passing `t` in the payload updates the text correctly and properly triggers the re-rendering. However, when passing other attributes like `s` for font size and `j` for justifying, the values are updated correctly, but the animation does not update.

I made sure that:

- Values like `s` and `j` receiving *number* values and not *string* values (but I tried strings anyway, just to make sure)
- Inspecting the JSON body shows values were updated correctly
- No errors where thrown in the console

Currently, my workaround is to work directly on the JSON. When I manually update the JSON object by finding the relevant elements, it correctly updates both values and renders. However, the amination flicker and its behavior I prefer to avoid. 

Is there another way to get the values updated without flickering the animation? Am I missing something when using the `updateDocumentData`?

Thanks!

**Comment by bodymovin** [comment]
hi, is the animation playing when the `updateDocumentData` is called? If it is paused it will not update until it renders again

**Comment by orenlwsc** [comment]
@bodymovin actually, no, I'm stopping it, updating, then playing it again. check out the following snippet:
```
const reRender = () => {
    // This is a workaround since in Lottie, while updating text layers on paused animations,
    // rendering isn't occur, and the updated parameters will not be shown until seek to other frame
    // https://github.com/airbnb/lottie-web/issues/2297
    if (lottieInstance.lottie && lottieInstance.lottie.isPaused) {
      const { currentFrame, totalFrames } = lottieInstance.lottie
      const frameToJumpTo = totalFrames > currentFrame ? currentFrame + 1 : currentFrame - 1

      lottieInstance.lottie.goToAndStop(frameToJumpTo, true)
      lottieInstance.lottie.goToAndStop(currentFrame, true)
    }
  }
```

**Comment by bodymovin** [comment]
so using that snippet it is not working?

**Comment by orenlwsc** [comment]
> so using that snippet it is not working?

nope. I'm suspecting it might be related to the animation file itself. if you have any insights or ideas to share with me, would love to hear any possible direction.
