### ISSUE TITLE
bodymovin doesn't queue composition

### ISSUE THREAD

**Issue by anindetube3** [airbnb/lottie-web#2905]
Hello, I have a question about zxp installation.
I reset the new computer and installed body movin, but it doesn't show the queue list as below.

<img width="1916" alt="1673600011" src="https://user-images.githubusercontent.com/122432098/212279247-5460eabd-ed65-464f-a542-d2b3dd9a259c.png">
<img width="570" alt="1673599996" src="https://user-images.githubusercontent.com/122432098/212279262-91f0fcb6-c3de-4ab7-83f9-1683303f3144.png">

is this the version problem? I re-installed bodymovin, but it is still same.

**Comment by bodymovin** [comment]
Hi, I've seen that reported a couple of times before, but I haven't been able to identify the issue. Since you mention that you reinstalled things, could it be related to a user / admin permissions on the device?

**Comment by anindetube3** [comment]
thanks for the answer! I solved the problem with fixing the scripts, but I don't really know how i did... But it works now! thank you!
