### ISSUE TITLE
Request for Event Types for Typescript

### ISSUE THREAD

**Issue by julianwilkinson** [airbnb/lottie-web#2906]
Hi!

Would it be possible to get the typings for events added for use with Typescript?

For example, the event listener for `enterFrame` emits the object `BMEnterFrameEvent` with  
```
{
  type: string, 
  currentTime: number, 
  totalTime: number, 
  direction: number
}
``` 
but this can't be imported from Lottie like the other types.

**Comment by renspoesse** [comment]
This has been implemented in https://github.com/airbnb/lottie-web/pull/2920.

**Comment by julianwilkinson** [comment]
Awesome! Thank you~
