### ISSUE TITLE
Animation fails to render in version 5.10.1

### ISSUE THREAD

**Issue by renspoesse** [airbnb/lottie-web#2916]
**Tell us about your environment**
lottie-web light 5.10.1, using SVG renderer

* **Browser and Browser Version:** Chrome 108
* **After Effects Version:** 5.7.4?

**What did you do? Please explain the steps you took before you encountered the problem.**
The file renders correctly in lottie-web light 5.7.9, but renders nothing in 5.10.1. No console errors.

**What did you expect to happen?**
The animation should render.

**What actually happened? Please include as much _relevant_ detail as possible.**
The animation doesn't render anything. Calling `destroy()` on the animation later throws an error.

**Please provide a download link to the After Effects file that demonstrates the problem.**
[animation.json.zip](https://github.com/airbnb/lottie-web/files/10461718/animation.json.zip)

**Comment by bodymovin** [comment]
can you share the .aep? It looks like there are two consecutive layers acting as masks, which is not supported, but I'd like to confirm

**Comment by bodymovin** [comment]
This should be fixed now!
It was indeed related to two consecutive layers as masks, which is not a defined behavior in AE, nor in lottie, but for backwards compatibility, it is working as before.

**Comment by renspoesse** [comment]
Thank you! Closing as fixed in https://github.com/airbnb/lottie-web/commit/b80ae19854771d1bd9cf4ef6853ac9ff08277a9a.
