### ISSUE TITLE
Ios lottie blank frames

### ISSUE THREAD

**Issue by codeandcore** [airbnb/lottie-web#2948]
https://codeandcore.org/ourwork/lottie/temp.html

First Lottie has a blank frame in the middle of the animation only in IOS. It's working well on android and MacBook. 
Is there anything that I can debug Lottie's animation?
![Screenshot_3](https://user-images.githubusercontent.com/3811883/225533843-eb354629-3098-4915-9196-f5fcc6f969c6.png)

**Comment by bodymovin** [comment]
hi, this seems an issue with the lottie-ios player. Can you create an issue there?
