### ISSUE TITLE
Animation cut off in Edge and IE

### ISSUE THREAD

**Issue by harzkinddev** [airbnb/lottie-web#295]
Hi,

I used bodymovin to create a logo animation for our new website. Everything works fine in Chrome and Firefox. In Edge and IE the edges of the logo are cut off during the animation until you change the viewport size or scroll out of view.

Here's a "working" link: http://harzkind.de/limmo/

Any ideas as to what causes this behaviour and how to fix it?

Best regards.

**Comment by bodymovin** [comment]
are you using some kind of mask? it's probably related to that.
Can you share the .aep?

**Comment by harzkind-kim** [comment]
Hi, thanks for the quick reply. Here's the AEP file: https://1drv.ms/u/s!Ap88Njs5cPjGjjh5Y7fr3nZUFbAD

I used the "precomp" composition for export.

**Comment by bodymovin** [comment]
Edge and Explorer have many issues with alpha and luma masks
I had never seen this one, but it seems like a bug on their end.
I'll see if I can do something on my side.

**Comment by harzkind-kim** [comment]
Nice, thank you very much. Keep me posted in this thread if possible. 👍

**Comment by bodymovin** [comment]
Closing as this should be working now.
