### ISSUE TITLE
bug/updateDocumentData is broken with textLayers including expressions since 5.10.2

### ISSUE THREAD

**Issue by orenlwsc** [airbnb/lottie-web#2958]
Hello, In our company we have been working with lottie version 5.7.3 for the last two years. A few days ago, we updated the lottie to version 5.10.2 mainly due to the new features supported in canvas. 

However, the longtime function `updateDocumentData` seems broken when trying to update `textLayer` that includes expression, even the simplest one. After thorough research, I found the breaking change occurred from version `5.10.1` to `5.10.2`. Unfortunately, I had difficulty tracing the exact commit where the change was implemented.

You can see the bug live in the following code sandbox: https://codesandbox.io/s/competent-fire-bbc3dp
Please check the comments in the script at `src/index.js`; I explained how to reproduce it there.

**To reproduce the bug**: Switch version to 5.10.2.
**To see the expected results**: Switch version to 5.10.1 or older.
(refresh the inner browser after changing the versions so you won't get stuck)

Attached AE file + JSON file for convenient, if it helps.
[text-issue.zip](https://github.com/airbnb/lottie-web/files/11136720/text-issue.zip)

**Comment by bodymovin** [comment]
Hi, this issue should be fixed in version 5.11.0  
thanks for reporting it!
