### ISSUE TITLE
Import Local File button unresponsive

### ISSUE THREAD

**Issue by fergusmeiklejohn** [airbnb/lottie-web#2963]
**Tell us about your environment**

* **OS:** macOS 13.3.1 M1 chip
* **After Effects Version:** AE 23.3.0 (Build 53)
* **Bodymovin Version:** 5.11.0

**What did you do? Please explain the steps you took before you encountered the problem.**
Using the Bodymovin plugin to import a local file

**What did you expect to happen?**
The finder to open so I can choose a file to import
**What actually happened? Please include as much _relevant_ detail as possible.**
Nothing happens. I click the Import Local File button and nothing happens. See the GIF: I'm clicking the button. I can't imagine that this button is broken so maybe this is a permissions problem?
![CleanShot 2023-04-11 at 17 52 41](https://user-images.githubusercontent.com/11864025/231126250-f05885bb-9e9f-4b17-ae88-03d747c38e3d.gif)

**Comment by Automarket272** [comment]
Como se hace esto? cuales son los pasos a seguir para importar mi archivo?

**Comment by xxxgnomicxxx** [comment]
Having the same issue here. I tried toggling "full disk permissions" for after effects, but it made no difference. I'm going to try to post my JSONs online and load them as URLs

**Comment by xxxgnomicxxx** [comment]
Update: trying to load JSONs via URL didn't work, uninstalling and reinstalling didn't work, but downgrading to 5.9.4 did work. Hope this helps!

**Comment by bodymovin** [comment]
Hi, this has been fixed in version 5.12.0

**Comment by edwardluong** [comment]
+1 Unable to import local JSON file. Running After effects v23.1.0 (Build 83) and Bodymovin v5.12.0

Issue: I imported json file from local+URL -> Bodymovin said import finished -> But no file imported to my AE Projects
