### ISSUE TITLE
Scale Skew and Transform Effect 

### ISSUE THREAD

**Issue by woozygoozy** [airbnb/lottie-web#2973]
Ok so this is something I wish we could have as an improvement/enhancement - the ability to use transform effect - and I am not sure why it is not supported - because its just an additional transform option and the addition of Skew and Skew angle - which is what I really am looking for. 

More importantly, while AE does not have skew and skew angle transform on first level objects, Lottie understands it - if I manually add `sk` and `sa` property to a image layer or a precomp lottie will display it no problem... Also, if I add the transform effect and animate the properties they will get recorded in the json - they just won't do anything... so in reality all that needs to be done - at least for skew / skew angle, is to update the parser to put sk and sa options into the main transform group....

that would make life so much easier!

**Comment by woozygoozy** [comment]
feature added in 5.12. 
Thank you @bodymovin

**Comment by LVKrri** [comment]
> feature added in 5.12. Thank you [@bodymovin](https://github.com/bodymovin)

Hello, can you provide a lottie json with a Transform Effect (ty=35)? I'm having trouble with this feature, thanks.

**Comment by LVKrri** [comment]
![Image](https://github.com/user-attachments/assets/1fafd6e1-4e9c-4f86-88dd-f83bc7efdc95)

**Comment by LVKrri** [comment]
> feature added in 5.12. Thank you [@bodymovin](https://github.com/bodymovin)

Hello, can you provide a lottie json with a Transform Effect (ty=35)? I'm having trouble with this feature, thanks.
