### ISSUE TITLE
Import json to recreate AE project

### ISSUE THREAD

**Issue by balinabbb** [airbnb/lottie-web#304]
Hi!

It would be really great, if I could import a JSON into After Effects, and I could edit it like a real project, with layers and so.
Do you plan to do something like this?

**Comment by bodymovin** [comment]
Yes, it's definitely on my wishlist, but it's not one of my priorities right now.

**Comment by scaryguy** [comment]
+1

**Comment by IlirBajrami** [comment]
+1

**Comment by k80** [comment]
+1

I made some edits to an AE file that I exported via Bodymovin, but I failed to save the AE file; now I want to make some minor edits (composition size, and duration), but would have to redo a bunch of work to get back to where I was when I exported the json. 😞

**Comment by weiesky** [comment]
+1

**Comment by dtysky** [comment]
Any progress?

**Comment by anacoxta** [comment]
+1

**Comment by bluepeter** [comment]
+1

**Comment by honeyamin** [comment]
maybe in AE 2018 you can import json file but i'm not sure.like data driven

**Comment by denismullaraj** [comment]
+1

**Comment by Geek4IT** [comment]
+1

**Comment by JUSTINMKAUFMAN** [comment]
+1

**Comment by vmalikov** [comment]
+1

**Comment by MohamedFekryyy** [comment]
ummm?

**Comment by connorbrez** [comment]
+1

**Comment by RenatoMartinsFerreira** [comment]
+1

**Comment by aguzmanballen** [comment]
+1

**Comment by valentinpigeau** [comment]
+1

**Comment by vimaleurakaa** [comment]
+1

**Comment by dhpanteon** [comment]
+1

**Comment by kartikpatelp** [comment]
+1

**Comment by Styrmist** [comment]
any progress?

**Comment by RWOverdijk** [comment]
Please stop saying +1. Use the reaction emoji at the top instead. Or, you know, pick it up. It's open source.

**Comment by foguetes** [comment]
> Yes, it's definitely on my wishlist, but it's not one of my priorities right now.

I know Keyshape already does this, though with limited support:
https://github.com/Pixofield/keyshape-lottie-format

Maybe someone can draw inspiration from it

**Comment by bodymovin** [comment]
Just 3 years later this is finally coming

**Comment by bodymovin** [comment]
Version 5.6.0 is out and Lottie Import is out!

**Comment by vimaleurakaa** [comment]
for real! Cool

**Comment by vimaleurakaa** [comment]
![image](https://user-images.githubusercontent.com/29746413/71987479-b50fcd80-3247-11ea-8ab2-e861aed0f2fd.png)

**Comment by bodymovin** [comment]
@vimaleurakaa :|
remember if you did anything in particular?

**Comment by Inventsable** [comment]
> ![image](https://user-images.githubusercontent.com/29746413/71987479-b50fcd80-3247-11ea-8ab2-e861aed0f2fd.png)
> 
> The latest version seems to have a problem! :|

Can you include the file you were using for Hernan to debug?

**Comment by vimaleurakaa** [comment]
@bodymovin attaching the snippet of the error captured if it helps to understand whats going wrong : https://www.dropbox.com/s/z8oagm3p32tex8w/Error.avi?dl=0

Also found a log file in the Temp folder _/CEPHtmlEngine9-AEFT-16.1.3-com.bodymovin.bodymovin.log_

**[0108/222401.068:ERROR:devtools_http_handler.cc(786)] 
DevTools listening on 127.0.0.1:8092**

Hope this helps :)

**Comment by auxdesigner** [comment]
FWIW I ran into the same problem with @vimaleurakaa. 
Updating my AE to the latest version fixed the issue. 
Now the importer works like a charm! Thanks @bodymovin !

**Comment by bodymovin** [comment]
@vimaleurakaa @auxdesigner I've fixed the issue on version 5.6.1
Nothing would break but apparently for older versions of AE, new projects that are not saved don't have a file in the system so you would get that message every time you focus on the extension.

**Comment by vimaleurakaa** [comment]
> @vimaleurakaa @auxdesigner I've fixed the issue on version 5.6.1
> Nothing would break but apparently for older versions of AE, new projects that are not saved don't have a file in the system so you would get that message every time you focus on the extension.

Cool👍
