### ISSUE TITLE
After Effects scripting support for BodyMovin?

### ISSUE THREAD

**Issue by Majed93** [airbnb/lottie-web#3070]
Is there any support for scripting with the BodyMovin extension? 

I'm trying to create a script which can automate the creation of the json files for a large amount of files.

I can't seem to find anything, closest thing i can find is using app.executeCommand but i would need the command Id of BodyMovin which i don't know.

**Comment by lxrcan** [comment]
There is automation tools that you might be able to use. Not sure if they support bodymovin but you can check.

Templater by dataclay has been used successfully in the past by the amazing folks at algo.tv to produce huge amounts of animations on the fly based on data signals. I’m certain Lottie’s have been one of their outputs too but don’t know for sure.

**Comment by Majed93** [comment]
Yes i had a look at that but unfortunately i couldn't see anything to do with lottie files?
