### ISSUE TITLE
AE expression not coming accross

### ISSUE THREAD

**Issue by RuNpiXelruN** [airbnb/lottie-web#347]
Hey, first of all love what you've created here! I have a problem with an expression not coming over though. I wanting a 'ping pong' effect i've created in after effects to come across in browser. Any ideas why it wouldn't be? I have version 4.6.2 installed

Justin

**Comment by bodymovin** [comment]
can you share the .aep so I can take a look?

**Comment by RuNpiXelruN** [comment]
Oh that was so quick!!..and yes sure thing :)

[backrestMain copy.aep.zip](https://github.com/bodymovin/bodymovin/files/895111/backrestMain.copy.aep.zip)

**Comment by bodymovin** [comment]
The expression valueAtTime is still not supported for shapes. I'll try to include it soon.
sorry :/

**Comment by RuNpiXelruN** [comment]
Oh ok, thanks for looking into that for me, and no need to apologize, you've done an amazing job! :)

**Comment by RuNpiXelruN** [comment]
Hey do you support the CC Particle systems? or is there a way to??

**Comment by bodymovin** [comment]
no, only a few effects are supported. And particle systems are too performance intensive for real time rendering.
But I'll see what I can do in the future.

**Comment by jaredstanley** [comment]
hey! is "Slider Control" supported?

here's the code:
`
num = effect("Slider Control")("Slider");
dec = 10;
nnn = Math.round(num*dec)/dec;
`

Thanks!

**Comment by bodymovin** [comment]
@jaredstanley yes, it is

**Comment by jaredstanley** [comment]
1. +100 for your rapid response time! 
2. Hmm I can't get it to work. 

Here's a zip: https://drive.google.com/file/d/1sCVZMzkszj7i7RPOdJ1AaWZ38Q-p2ZLQ/view?usp=sharing

1. if i add in text manually it works.
2. if i add in text via an expression (i.e. n=45) it works. 
3. i can't get it to update w the file though (code posted in prev comment). 

I assume I'm missing an important step but not sure what it is. LMK if you can help. Thanks!

**Comment by bodymovin** [comment]
@jaredstanley If you're attaching expressions to text sources and exporting characters as glyphs, you need to provide all characters that will be used by the expression to the player.
You can create an extra text layer with the same font with numbers from 0 to 9 and a "." so the expression can render those chars.

Another option is to export text as text data (ie not glyphs) and provide the needed font by loading it separately in the browser or indicating the player where to load it from.

**Comment by weiicai** [comment]
> @jaredstanley If you're attaching expressions to text sources and exporting characters as glyphs, you need to provide all characters that will be used by the expression to the player.
> You can create an extra text layer with the same font with numbers from 0 to 9 and a "." so the expression can render those chars.
> 
> Another option is to export text as text data (ie not glyphs) and provide the needed font by loading it separately in the browser or indicating the player where to load it from.

Do you have a link for the AE expression which is supported for bodymovin now? Because i'm not sure which expression i used is supported.

**Comment by weiicai** [comment]
> no, only a few effects are supported. And particle systems are too performance intensive for real time rendering.
> But I'll see what I can do in the future.

Do you have a link for the AE expression which is supported for bodymovin now? Because i'm not sure which expression i used is supported.

**Comment by claide** [comment]
Hi, I had the same issue on a simple ping pong effect. Is this solved on the latest release?

**Comment by bodymovin** [comment]
@claide Hi, CC Bend It, Grow Bounds and those types of effects are not supported by the player. Very few raster effects are. 
https://github.com/airbnb/lottie-web/wiki/Effects
