### ISSUE TITLE
png images to base64 endcoding?

### ISSUE THREAD

**Issue by bigxixi** [airbnb/lottie-web#372]
can bodymovin provide an option to encode png images into base64 format and put them in the json ?
then it will be a real 'standalong' mode.

**Comment by bodymovin** [comment]
yes, I could add an option for doing that.
I need to find a moment to address exporting pngs from the render queue from your pull request.
And also export to jpgs when images have no transparency.

**Comment by miyime** [comment]
Couldn't be better

**Comment by bigxixi** [comment]
coooool! 
cant wait for it :)
another idea: compress the pictures after they exported using some powerful online library like tinypng. As i know tinypng provides some apis(https://tinypng.com/developers), with some code it can make the 'upload-compress-download-replace' process automatically.
reference:
http://danielsetzermann.com/howto/how-to-compress-png-files/

**Comment by kytwb** [comment]
That would be top as there's many cases where exported images file paths are troublesome.

**Comment by conwaydev** [comment]
Would love this

**Comment by mmskvortsov** [comment]
+1

**Comment by bodymovin** [comment]
Implemented on version 5.1.15

**Comment by kytwb** [comment]
@bodymovin great job, thanks for that! 🎉
