### ISSUE TITLE
Render On Mobile Devices

### ISSUE THREAD

**Issue by cuba87** [airbnb/lottie-web#387]
Hey awesome work loving this tool.
A colleague has used bodymovin on a site she's developing she's used it to create 3 animations (intro/transition/background). They look fine on my laptop/desktop etc but on mobile devices they render super slow and effect the rendering of other animations. I've had a look but can't figure it out.
Is it simply the case that it's just too much for a mobile device to render? 
Any help would be appreciated.
Cheers, 
Cuba

**Comment by bodymovin** [comment]
hi
it really depends on the features you're using, and probably the device.
Can you share the .aep file so I can take a look?

**Comment by cuba87** [comment]
Yeah sure here's the .aep for the background animation

[The Wave.aep.zip](https://github.com/bodymovin/bodymovin/files/966016/The.Wave.aep.zip)

**Comment by zmax91** [comment]
@bodymovin hi, I have same issue here. When I render it on android device, the animation is very slow and shuts down in the middle. Can I send you my file?

**Comment by bodymovin** [comment]
can you share the .aep so I can take a look?

**Comment by zmax91** [comment]
You can download it here:
https://www.dropbox.com/s/uvd9ixek1beg4nx/Sports.aep?dl=0

I've decreased composition duration using time stretch, can it be the reason?

**Comment by bodymovin** [comment]
@zmax91 are you using Lottie to render on Android?

**Comment by zmax91** [comment]
@bodymovin yes

**Comment by zmax91** [comment]
@bodymovin any luck on this issue?

**Comment by bodymovin** [comment]
Yes, time stretch is not yet supported in Lottie

**Comment by zmax91** [comment]
Thanks.

**Comment by zmax91** [comment]
@bodymovin is time stretch supported in Lottie now?

**Comment by bodymovin** [comment]
not yet

**Comment by bodymovin** [comment]
Closing since it's related to lottie-android
