### ISSUE TITLE
bodymovin.js wapper for React, Angular and Vue

### ISSUE THREAD

**Issue by chenqingspring** [airbnb/lottie-web#401]
Thanks for GREAT work of this repo!! 

For more convenient integration to some popular frameworks, I created bodymovin wapper of [React](https://github.com/chenqingspring/react-lottie), [Angular](https://github.com/chenqingspring/ng-lottie) and [Vue](https://github.com/chenqingspring/vue-lottie) which are also inspired by [airbnb lottie](http://airbnb.design/lottie/)

All of them now only implemented some basic features, and I personally don't have enough time to maintain them, so I need some help for improving them. 

I think this is a right place for asking help, hope I didn't offend here.

Thanks a lot.

**Comment by bodymovin** [comment]
this looks nice! I'll take a look at it.

**Comment by chenqingspring** [comment]
Thanks for your support @bodymovin :)

**Comment by mifi** [comment]
Unfortunately now abandoned

**Comment by stescobedo92** [comment]
this looks nice!!!!!!
