### ISSUE TITLE
SVG sequence

### ISSUE THREAD

**Issue by foguetes** [airbnb/lottie-web#411]
Hello,

I have a suggestion for future development. 
If we're currently able to export SVG snapshots from Bodymovin, why not add an option to export as an svg sequence?
We could then create an SVG sprite in case we can't use the bodymovin script.

**Comment by bodymovin** [comment]
Yes, it should be pretty straightforward to implement.

**Comment by proxemics** [comment]
Recently ran into a need for this, curious if this was ever considered or? Be great to be able to save all the frames vs having to save them one by one.
