### ISSUE TITLE
Render Window - enhancement

### ISSUE THREAD

**Issue by themarten** [airbnb/lottie-web#420]
Any chance we can set the Render settings to apply to all comps?
I have multiple comps and must go into each setting and check the options I want.
Is it possible to add an "apply to all" button (next to save and cancel) which would set the same settings (but not destination folder) to all comps in the list? Whether they're ticked or not.

And can we make the Destination Folder column wider? Now it's width is limited so it's not possible to see the full file path if it's long.

And making a button which toggles "select all/none" for comps, perhaps turning the "selected" column label into a button for that.

Thanks for making a great tool.

**Comment by bodymovin** [comment]
I'll see what I can do from these suggestions.
thanks! :)
