### ISSUE TITLE
png alpha dark outline

### ISSUE THREAD

**Issue by themarten** [airbnb/lottie-web#421]
(Sorry if this is a repeat, couldn't find it in the search)

When png's are rendered they get a dark outline. This is especially noticeable when using blurry edges for an image.
![boom_dark](https://cloud.githubusercontent.com/assets/27818725/26094131/f7ec5a62-3a18-11e7-9834-198c16124d18.png)
![alpha_blur](https://cloud.githubusercontent.com/assets/27818725/26094504/952ecbc4-3a1a-11e7-8b62-f482a821df4f.png)

Seems like the export uses premultiplied using black? Changing the comp bg color doesn't make a difference.

Can we save them as "straight" alphas instead?
![boom_correct](https://cloud.githubusercontent.com/assets/27818725/26094146/03d2634e-3a19-11e7-8afe-d046f54ce901.png)
![bluralpha_correct](https://cloud.githubusercontent.com/assets/27818725/26094432/4c82c36c-3a1a-11e7-82d9-a014fecb885d.png)

It is possible to select this in the AE Render Settings/Output/Video Output/Color/Straight(Unmatted), but not in Bodymovin Render.

The only solution now is to resave the pngs from Photoshop.

**Comment by bigxixi** [comment]
@themarten  I try to change the way bodymovin render png, and it works fine for me:
1. download this `sourceHelper.jsx`
https://github.com/bigxixi/bodymovin-extension/raw/master/bundle/jsx/utils/sourceHelper.jsx

2. goto the plugin folder and find the `sourceHelper.jsx` in
WINDOWS:
C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\bodymovin\jsx\utils\ or
C:<username>\AppData\Roaming\Adobe\CEP\extensions\bodymovin\jsx\utils\
MAC:
/Library/Application\ Support/Adobe/CEP/extensions/bodymovin/jsx/utils/

(or just search the name in your machine)

3. back up the original `sourceHelper.jsx` , then replace it with the downloaded one.

4. restart bodymovin and export your comp with png.

Hope that can help.

**Comment by themarten** [comment]
Thanks, but now the Bodymovin extension won't open in After Effects. The Extension is listed in the menu but when I click it no window shows up. Other extensions work fine. If I revert to the old file it works.

**Comment by bigxixi** [comment]
@themarten sorry i havent test it on other machines. 
try restart AE?

**Comment by themarten** [comment]
No luck. I restarted AE and reinstalled Bodymovin multiple times, tried the new and the old sourceHelper.jsx. I'm on a PC, Windows 10, latest After Effects CC 2017 and Bodymovin version. Any ideas?

**Comment by bigxixi** [comment]
I am on Mac, AE CC2014, bodymovin 4.6.7, and works fine...

**Comment by themarten** [comment]
I'm using bodymovin 4.6.9 from 5 days ago.
Any chance you can try on a PC?

**Comment by bodymovin** [comment]
I think the issue is related to how you installed the plugin.
If you did it from the Adobe addons store, it seems to do some check on files and you can't modify them.
Regarding @bigxixi's solution, I'm trying to see how to add it to the project.
I've done some tests and it doesn't work well with CC 2014.
And also you need to tolerate the render chime going crazy if you have more than one asset :)

**Comment by themarten** [comment]
Right. I installed it using Anastasiy's Extension Manager (he makes Magpickpicker for Photoshop, the only way to install that extension) which has worked fine, including the latest bodymovin.

I have lots of assets.... Looking forward to hearing what "chime go crazy" means.

**Comment by themarten** [comment]
Right. I installed it using Anastasiy's Extension Manager (he makes Magpickpicker for Photoshop, the only way to install that extension) which has worked fine including the latest bodymovin.

Render chime? I have lots of assets.... Looking forward to hearing what "go crazy" means.

Thanks for looking into this. Very nice of both of you. Much appreciated.

**Comment by zmax91** [comment]
@bigxixi your solution does not work for me, I'm using CC 2017 on Mac. @bodymovin is there any way to fix this?

**Comment by machinefixer** [comment]
For mac user (I'm using macOS Sierra with AfterEffect CC 2017), just download modified version of bodymovin from @bigxixi 's repo: https://github.com/bigxixi/bodymovin, I installed it through ZXP Installer, replaced original bodymovin, then the black border is gone, everything comes great again.

**Comment by pegeseus** [comment]
Came here to ask the same question about the ability to use straight alpha.  Has there been any progress on this?  The workaround obviously is to export your own pngs with straight alpha and replace them in the folder but that gets tedious after a while.  Thanks!

**Comment by pegeseus** [comment]
Seems to work for me on Windows 7- good work! :D

**Comment by themarten** [comment]
Verified working on Windows 10. THANK YOU!

**Comment by rlxone** [comment]
macOS High Sierra 10.13.4, AE CC 2017 - works fine. Thank you for your fix!

**Comment by IsMrWu** [comment]
@bigxixi  perfect, it works on Window10,AE CC 2018 and Mac OS, AE CC 2017
