### ISSUE TITLE
trim paths 

### ISSUE THREAD

**Issue by helvetica80** [airbnb/lottie-web#438]
I'm trying to create a preloader but there's some weirdness with the stroke. I've attached a screengrab of the weird stroke and the ae file

[preloader-52617.zip](https://github.com/bodymovin/bodymovin/files/1032909/preloader-52617.zip)

**Comment by bodymovin** [comment]
I'm not sure what is going on.
It seems to be related to the Line Cap and a last segment of the shape, I need to keep looking into it.
