### ISSUE TITLE
what's wrong with this error alert.please help me

### ISSUE THREAD

**Issue by zhangfei110** [airbnb/lottie-web#552]
"Unable to execute script at line 314. undefind is not an object"

**Comment by bodymovin** [comment]
When does it happen? While rendering a composition?
Also, what's your OS and AE's language?

**Comment by zhangfei110** [comment]
when I open bodymovin pannel and press any button. OS is  windows and language is English.

**Comment by bodymovin** [comment]
is it AE 2017?

**Comment by zhangfei110** [comment]
Yes

**Comment by katiericc** [comment]
Any update on this? I'm experiencing the same problem but with line 1. It pops up the second I open the bodymovin extension and will not go away.

**Comment by bodymovin** [comment]
What version of bodymovin are you using?

**Comment by katiericc** [comment]
I believe most recent, I followed this link http://aescripts.com/bodymovin/

**Comment by bodymovin** [comment]
@katiericc Are you using CC 2014?

**Comment by katiericc** [comment]
@bodymovin no, cc 2017.
