### ISSUE TITLE
After effect features are not animated properly

### ISSUE THREAD

**Issue by csrol** [airbnb/lottie-web#559]
**Tell us about your environment** mac os x 10.11.6 (15G1510)

* **Browser and Browser Version:** N/A - problem is not browser related
* **After Effects Version:** 2017 CC

**What did you do? Please explain the steps you took before you encountered the problem.** tried to export an after effects project by bodymovin

**What did you expect to happen?** export the after effect project by bodmovin

**What actually happened? Please include as much _relevant_ detail as possible.** some of the letters what were intended to animate (moving along a path) were just appear while others were animated properly, the timing of the effects in the exported result at preview was wrong (delayed vs. original timing)

**Please provide a download link to the After Effects file that demonstrates the problem.** https://drive.google.com/open?id=0B-6XiRhUIggYNTZPR01JLVU3b3M
[Csongvai Roland Logo Sliced final.aep.zip](https://github.com/bodymovin/bodymovin/files/1183538/Csongvai.Roland.Logo.Sliced.final.aep.zip)

**Comment by bodymovin** [comment]
Apparently using an expression that point to a different composition uses the property's expression time instead of the comp's time.
I need to work on this since it's not a simple fix.
Can you use valueAtTime?

**Comment by csrol** [comment]
Thank You for Your response. What do You mean under valueAtTime?

**Comment by bodymovin** [comment]
for example in your composition "o 2", on layer "o 1", instead of using
`FM_controllerLayer.effect("Gilbert Controller")("Color 3")`
use
`FM_controllerLayer.effect("Gilbert Controller")("Color 3").valueAtTime(time)`
but I see there's too many of them.
