### ISSUE TITLE
Animation error with Android

### ISSUE THREAD

**Issue by henriqrossatto** [airbnb/lottie-web#562]
Hi there.

I created some animations for a app and when the developer test on android, the animation had a fill error that didn't have in IOS version. The problem is that there is not any fill where the error occour.

I attached the ae files and the images with the error

I'm a beginner in bodymovin, so I do not know if the way to export to Android is different from the one for IOS

After Effects Version: CC 2015
[report_error.zip](https://github.com/bodymovin/bodymovin/files/1188206/report_error.zip)

**Comment by henriqrossatto** [comment]
I'm a beginner on bodymovin, so I don't know if I exported the files of right way to android

**Comment by bodymovin** [comment]
Hi, if you're using Lottie, I'd suggest that you post the issue directly on their github page.
https://github.com/airbnb/lottie-android

**Comment by henriqrossatto** [comment]
Ok! Thanks!
