### ISSUE TITLE
Mask + Canvas Render

### ISSUE THREAD

**Issue by laygir** [airbnb/lottie-web#564]
Hi, again,

Does canvas renderer have issues with masks? I did a simple mask animation which works well when renderer is SVG and when switched to the canvas, I see masks which are supposed to be hidden.

[CanvasMask.aep.zip](https://github.com/bodymovin/bodymovin/files/1192069/CanvasMask.aep.zip)

Thanks!

**Comment by adamchenwei** [comment]
check this PR, see if its related to you and if you are able to contribute. Thanks https://github.com/bodymovin/bodymovin/pull/382

**Comment by bodymovin** [comment]
track masks are not supported in the canvas renderer.
Only regular AE masks in add mode

**Comment by laygir** [comment]
Hi!
What is a regular AE Mask and how would you mask something without track matte mask? 
Do you mean Merge Paths inside shape layers with add mode?

Another question, does html renderer supports track matte masks?

**Comment by bodymovin** [comment]
if you right click on the layer > Mask >New Mask you will get a clipping mask.
Does that work for your case?

**Comment by matteo-sanfilippo** [comment]
Hernan, thank you for this hint (mask in add mode)! It works very fine now!!!!!!!! Will pay for bodymovin, great work!!!
