### ISSUE TITLE
Android Animated Vector Drawable export fails

### ISSUE THREAD

**Issue by rock3r** [airbnb/lottie-web#571]
**Tell us about your environment**

* **Browser and Browser Version:** N/A
* **After Effects Version:** 14.2.1.34

**What did you do? Please explain the steps you took before you encountered the problem.**
1. Open project from Chris Basha's [blog post](https://www.novoda.com/blog/whole-lottie-love/)
2. Enable AVD exporting for the `Hero` composition in Bodymovin
3. Render `Hero` composition with Bodymovin

**What did you expect to happen?**
I get a JSON (Bodymovin) and an XML (Android AVD) output file.

**What actually happened? Please include as much _relevant_ detail as possible.**
The rendering successfully produces the `data.json` file but gets stuck on "Saving data" indefinitely when it's time to export the AVD:

![image](https://user-images.githubusercontent.com/153802/29003810-9edf69ea-7ab5-11e7-9e40-cc621d979c46.png)

No AVD XML file is created; the only way out of this situation is to click _Cancel_ and give up on using AVD (thankfully we can still use Lottie).

I have had the same problem with other compositions too, and I have had a colleague reproducing the very same issue with the same files. I suspect it may be something with the extension being unable to render something to an AVD and failing silently. I cannot find where logs are kept though so this is pure speculation.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/file/d/0B0w-5ApdB7kBNHVUN0hWeXRUM0U/view

**Comment by bodymovin** [comment]
Hi, I've fixed the error issue and uploaded a new build.
It was related to position being animated in separate dimensions.
Nevertheless, the Hero animation uses features that are not supported by the AVD unfortunately.
Opacity and Drop Shadow in particular.

**Comment by rock3r** [comment]
Thanks mate! I know I know, it was just the first one I could find that reproduced the issue and was publicly available :)
