### ISSUE TITLE
Shape Issues with Rotation + Scale + Position

### ISSUE THREAD

**Issue by lorenappin** [airbnb/lottie-web#574]
I have an AE file that has an animation of a Fish swimming through water doing some turns. I'm using Rotation + Scale + Position, and also making another layer the parent of it (that also has position key frames).

The result is a distorted shape (when using the JSON output) versus what I see very clearly in the AE file.

**Tell us about your environment**
Mac Sierra 10.12.5

* **After Effects Version:**
AE cc2017.1

**Please provide a download link to the After Effects file that demonstrates the problem.**

I've included both the JSON output as well as the AE file.

[Fish Animation.zip](https://github.com/bodymovin/bodymovin/files/1208379/Fish.Animation.zip)

**Comment by bodymovin** [comment]
Hi, I see your animation working fine.
Can you share a link where it fails?

**Comment by lorenappin** [comment]
Hi Bodymovin,

Thanks for taking a look!

How are you testing/rendering the JSON?

Apologies, I'm still new to bodymovin but I discovered it through Lottie, and I'm using Lottie to render the JSON. I'm attaching a video of 1. The Result of what it looks like when rendered, 2. Expected, and 3. The exact JSON I'm using again.

[Fish BM.zip](https://github.com/bodymovin/bodymovin/files/1212701/Fish.BM.zip)

**Comment by bodymovin** [comment]
if you're using Lottie, can you post it in their github?
https://github.com/airbnb/lottie-android
Also make sure you're using the latest version.

**Comment by lorenappin** [comment]
Thanks! Their latest version seems to mess up quite a bit - have posted it there.
