### ISSUE TITLE
 3d layers (and expressions) issues

### ISSUE THREAD

**Issue by cameranebbia** [airbnb/lottie-web#580]
Windows 10, Chrome (60.0.3112.90 ), After Effetcs CC 2015, (using json renamed js with var animData =...)

First of all great work!
I'm having issues with composition containing 3d layer, 
specifically:
-  Two solids, one 3d and the other not:
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

Setting both layers 3d works fine but there seems to be a problem with 3d rotation and expression (position/scale/opacity seem to work fine). 
- Linking  rotationZ to rotationX of the same or another layer ("transform.xRotation" or "thisComp.layer("Green Solid 1").transform.xRotation" ) gives me this:
bodymovin.js:13 Uncaught TypeError: Cannot read property 'length' of undefined
    at s.execute [as getValue] (bodymovin.js:13)
    at Object.m [as getValue] (... 

- Linking position to rotation ("temp = transform.xRotation; [temp, temp, temp]" or "temp = thisComp.layer("Green Solid 1").transform.xRotation; [temp, temp, temp]" ) gives me no error but neither works on setting position.

- Nested precomp works only if not 3d, otherwise (a comp with a 3d precomp with 3d layers) gives me:
Uncaught TypeError: this.addTo3dContainer is not a function

Does it make sense? I can upload files if needed.....

**Comment by bodymovin** [comment]
Hi, yes, can you upload the .aep so I can take a look?

**Comment by doulouUS** [comment]
Hi ! any update on these issues?
