### ISSUE TITLE
Paths not closing correctly in export

### ISSUE THREAD

**Issue by deadlocked247** [airbnb/lottie-web#585]
AE CC 2017 osx
Chrome 

My exports result in a path not appearing to be closed
![image](https://user-images.githubusercontent.com/7194264/29284903-913a44b8-80fa-11e7-8dc9-e950db1c98c4.png)

I expected this to happen
![image](https://user-images.githubusercontent.com/7194264/29284876-77b6b1ac-80fa-11e7-8e1d-398c45eb7693.png)

I'm not doing anything fancy with masks, just using vector shape layers I imported from illustrator.

[project.aep.zip](https://github.com/bodymovin/bodymovin/files/1223052/project.aep.zip)

**Comment by bodymovin** [comment]
You need to erase the merged paths created when converting ai layers to .ae layers and also remove the unnecesary square paths.
Unfortunately bodymovin doesn't support merge paths.
