### ISSUE TITLE
"CVShapeElement.destroy()" function runtime issue

### ISSUE THREAD

**Issue by edouardmercier** [airbnb/lottie-web#594]
Hello.

First of all, congratulations for your remarkable work.

Just to let you know that the `CVShapeElement.destroy()` prototype function is buggy with the v4.10.2 and from v4.6.4, since you attempt to clear the `this.itemData` instead of the `this.itemsData` attribute on the `this.itemData.length = 0` statement.

**Comment by bodymovin** [comment]
Thanks for reporting it.
I'll upload the fix on the next release.
