### ISSUE TITLE
Failing on IE 10

### ISSUE THREAD

**Issue by ochanje210** [airbnb/lottie-web#596]
It seems it doesn't work on IE 10 with the following error message.
```
(unknown): Script error
1 File https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.10.2/bodymovin_light.min.js line (unknown) col 0 in [anonymous]
```

I do not mind its supportability on IE 10 since it is pretty old. However, shouldn't we have a browser compatibility chart somewhere in README?

**Comment by bodymovin** [comment]
It seems to be related to trying to change the window value.
I will try to fit it.

**Comment by piotar** [comment]
In IE9 it also doesn't work.

![image](https://user-images.githubusercontent.com/17828599/30757876-833bf7ae-9fd0-11e7-8ba2-85a381b9c918.png)

The main problem is you want change variable window but you can't.
In old browser we can't redeclare constant variable with name 'window'.

I don't know why you set the same name but, mayby change name to another or put this in line in function in argument.

```
(function(root, factory) {
    if (typeof define === "function" && define.amd) {
        define(factory);
    } else if (typeof module === "object" && module.exports) {
        module.exports = factory();
    } else {
        root.bodymovin = factory();
    }
}((window || {}), function() {
...
```

**Comment by felippenardi** [comment]
Should this be closed?
