### ISSUE TITLE
cannot preview html version of .json file 

### ISSUE THREAD

**Issue by AlmondCupcake** [airbnb/lottie-web#598]
So, I've been hours trying to get the bodymovin file to my html and I was wondering if it has something to do with the file itself. I understand that I can get a html version for a preview of the animation but when I open it I only get a blank page. It's my computer missing something? Or it's just me and need some basic code lessons?

**Comment by bodymovin** [comment]
can you share the .aep so I can take a look?

**Comment by AlmondCupcake** [comment]
sure
here it is
https://drive.google.com/open?id=0B4ufG-4Ws4XYZ3FrdkRkT2wwTG8
also, i'm working on mac os sierra, if it helps

**Comment by AlmondCupcake** [comment]
sure
here it is
https://drive.google.com/open?id=0B4ufG-4Ws4XYZ3FrdkRkT2wwTG8
also, i'm working on mac os sierra, if it helps

**Comment by bodymovin** [comment]
Hi, the animation seems to work fine, although motion blur is not supported by the plugin.
Can you share a link where it fails?

**Comment by AlmondCupcake** [comment]
Sorry, didn't know it doesn't support motion blur.
Here it's working fine, but half the animation. Does it not support time reverse layer either?
https://drive.google.com/open?id=0B9DxE2lkkTLwdy1kYnJuWjdGT0k

**Comment by rashidgd** [comment]
Hi, I am having the same problem, please guide me how do I solve this issue.
i have attached all the files please check this links 
https://drive.google.com/open?id=0B4SltWdb96ozd2xqUjJGUGNqckE
