### ISSUE TITLE
Trim path or pucker and bloat cannot be exported?

### ISSUE THREAD

**Issue by anohitoo** [airbnb/lottie-web#599]
I try to export the trim path animation with offset effect. But the demo.html file doesn't show the animation. Please help.
This is the ae file. 

[a.zip](https://github.com/bodymovin/bodymovin/files/1256952/a.zip)

**Comment by bodymovin** [comment]
Unfortunately, Offset and Pucker and Bloat are not supported yet.
sorry :/

**Comment by johannth** [comment]
@bodymovin is adding those on the feature roadmap? I'm new to this project (and loving your work, thanks!) and would like to contribute. Does this repo contain the code to the After Effect plugin or only the player?

**Comment by bodymovin** [comment]
this one only contains the player.
The AE plugin is here
https://github.com/bodymovin/bodymovin-extension
nevertheless, supporting those effects is complicated. Specially the offset path.
