### ISSUE TITLE
Bugged render of rounded shapes with few anchor points

### ISSUE THREAD

**Issue by gingerhero** [airbnb/lottie-web#601]
**Tell us about your environment**
Windows 10

**Browser and Browser Version**
Chrome 60.0.3112.101, Microsoft Edge 40.15063.0.0

**After Effects Version** 
2017 - 14.2.1.34

I've experienced weird rendering with rounded shapes. While the Bodymovin preview looks just fine, the render in the browser is bugged. The problem seems to be caused by not having enough anchor points on the shape path. See below example.

**Bugged Render (few anchorpoints)**
I'm making the following simple shape (anchor points are circled out):
![buggedrenderanchorpoints](https://user-images.githubusercontent.com/2739527/29930657-473576da-8e6f-11e7-8572-dfa7e1d2359d.jpg)

The preview looks fine (top), however it renders incorrectly in the browser (bottom):
![bodymovinpreviewlooksfine](https://user-images.githubusercontent.com/2739527/29930698-6e1e7080-8e6f-11e7-8fe5-3e94cd23c3b7.jpg)
![butrenderinbrowserisbugged](https://user-images.githubusercontent.com/2739527/29930711-779a4256-8e6f-11e7-8570-6e3569fc85a9.jpg)

It seems that it draws the line directly from the top to the bottom right anchor point somehow. After adding several more anchor points, it renders correctly in the browser.

**Correct render (many anchor points)**
Here's the shape with added anchor points:
![correctrenderanchorpoints](https://user-images.githubusercontent.com/2739527/29930851-e2e8dd38-8e6f-11e7-9acf-2848f122ae13.jpg)

This now displays correctly in my browser.

I'm not sure if this is a well known issue, but I was having trouble finding a solution, so I thought I'd post it here just in case it wasn't.

Is there a better solution to this than manually adding several new anchor points? It gets tedious with a lot of shapes/animations.

**Please provide a download link to the After Effects file that demonstrates the problem**
[https://www.dropbox.com/s/036hnw0bqiv62og/BodymovinBugTest.zip?dl=0](url)

I've added a folder for the bugged as well as the correct render. I've included both the AE-files and the HTML/JS/JSON file for display in the browser (I used MAMP to run servers locally).

**Comment by bodymovin** [comment]
I'll check it later today, but make sure you're using the latest player

**Comment by gingerhero** [comment]
Great. I got the player through the "Get the Player"-button in the Bodymovin extension in AE, so it should be the latest player..?

**Comment by bodymovin** [comment]
yes, it should be fine.
I'll check it later today.

**Comment by gingerhero** [comment]
Hi. Were you able to check this issue yesterday?

**Comment by bodymovin** [comment]
Hi sorry for the delay.
I see in your demo that you're using a really old version of the bodymovin.js.
Can you make sure you're using the one that comes with the extension?
Also, where did you install the AE extension from?

**Comment by gingerhero** [comment]
I see. I'm fairly certain I got the player from inside the extension, but I might be mistaken.  I installed the extension from [https://exchange.adobe.com/addons/products/12557#.WawrZsgjGMo](url).

Do you have a link to the latest version of the player? I'll try to do another test with the newest version and get back to you.

**Comment by gingerhero** [comment]
Using the newest version of the Bodymovin player, the issue was resolved. Thanks for the help!
