### ISSUE TITLE
Chrome specific rendering issue

### ISSUE THREAD

**Issue by RobinSiep** [airbnb/lottie-web#603]
**Tell us about your environment**
macOS Sierra - Version 10.12.5

* **Browser and Browser Version:**
Chrome Version 60.0.3112.113 (Official Build) (64-bit)
Firefox Version 54.0.1

* **After Effects Version:**
After Effects CC 2017 Version 14.2.0.198

**What did you do? Please explain the steps you took before you encountered the problem.**
After exporting the After Effects file downloadable below together with the `demo.html`.

**What did you expect to happen?**
When opening the `demo.html` in both Chrome and Firefox the result should be the same as the render in After Effects. For Firefox this is the case, for Chrome it's not.

**What actually happened? Please include as much _relevant_ detail as possible.**
In Chrome the beginning of the animation renders like this:
![image](https://user-images.githubusercontent.com/5303534/29961622-82d19a5c-8f00-11e7-8c6b-89f3f5e4ce73.png)

While in both Firefox and Safari it renders (correctly) like this:
![image](https://user-images.githubusercontent.com/5303534/29961665-a17a46a2-8f00-11e7-93fc-9da44cbc964d.png)

Seems to me the problem only occurs in Chrome.

**Please provide a download link to the After Effects file that demonstrates the problem.**
All relevant files (the .ae file and exported animation) can be found here:
https://drive.google.com/drive/folders/0B9URH_BggAndeFRHM200UWt0WlU?usp=sharing

Thanks in advance!

**Comment by bodymovin** [comment]
Hi, I need access to the drive folder

**Comment by RobinSiep** [comment]
Woops sorry, my bad. You should have access now.

**Comment by bodymovin** [comment]
Hi, the .aep needs some pngs that seem to be missing, can you share them?
Nevertheless I see you're using the stroke effect that is not fully supported. It might be related to that.

**Comment by bodymovin** [comment]
I tried it in Chrome on Linux and it seems to work.
What is it that you see failing?

**Comment by RobinSiep** [comment]
Hey thanks for your effort so far. Take a look at the two gifs below:

Safari (correct):
![safari](https://user-images.githubusercontent.com/5303534/30024307-7d67b860-9173-11e7-8ee5-a830bf18562d.gif)

Chrome (incorrect):
![chrome](https://user-images.githubusercontent.com/5303534/30024336-98dca43e-9173-11e7-9ab2-dd0a25275e0c.gif)

As you can see in Chrome the lightbulb always colors the bottom of the lightbulb even in the beginning of the animation. The expected result is as shown in the safari gif where the entire lightbulb starts blue, also the bottom of the lightbulb. In Chrome it seems it the bottom half of the lightbulb is just stuck or something.

I've added the needed PNGs that the .aep uses in the drive folder.

**Comment by bodymovin** [comment]
It seems to be related to a chrome issue
https://bugs.chromium.org/p/chromium/issues/detail?id=750252
do you have a link where it fails?
