### ISSUE TITLE
Gradients with wrong colors

### ISSUE THREAD

**Issue by renemini** [airbnb/lottie-web#604]
* **Browser and Browser Version: Chrome 60,Firefox 55 & Safari 10.1
* **After Effects Version: CC 2015

Hi, I have this issue:

I have more than 1 gradient fill with different colors in my file, each one in different shapes. The problem is that the json displays all shapes with the same gradient.

I saved my .aep file before exporting, so I don't know what can be wrong. Can you help me?

I attach both files an screenshots.

Link to the demo: http://renemini.com/animacion/

After Effects:
<img width="576" alt="after effects" src="https://user-images.githubusercontent.com/11739297/29997704-94778526-901a-11e7-8e52-849767d20903.png">

Browser:
<img width="633" alt="json" src="https://user-images.githubusercontent.com/11739297/29997707-a52aa3f8-901a-11e7-8f8c-5f4354a1a7af.png">

[gradients.zip](https://github.com/bodymovin/bodymovin/files/1272385/gradients.zip)

**Comment by bodymovin** [comment]
Hi, yes there seems to be an issue with the way I'm getting the gradient data from the .aep file.
Until I fix it, if you rename the gradient property with a different name each, it will work fine.

**Comment by renemini** [comment]
It works!

Thanks for your job!!

**Comment by vadikzhuk** [comment]
Unfortunately, doesn't work for me :( I've renamed all shapes, gradient properties, saved project file and relaunched AAE.

![gradient_bug](https://user-images.githubusercontent.com/16958648/32213373-a1c98440-be23-11e7-8b86-ec1c69b22b04.png)

Strange that the bug appears only on native aae shapes and doesn't appear on imported ai layers...

I'm using latest english aae on english system and have downloaded bodymovin few days ago (so I guess it is the latest version too)

**Comment by bodymovin** [comment]
@vadikzhuk can you share the .aep?

**Comment by vadikzhuk** [comment]
Sure

https://failiem.lv/u/tvbuv8nv

**Comment by vadikzhuk** [comment]
Ok, I did convert them and did rename all gradients again, now all gradients became black to white :)

https://failiem.lv/u/hwj55fhh

**Comment by bodymovin** [comment]
Hi, I see gradients fine.
What is your OS and AE language?

**Comment by vadikzhuk** [comment]
English for both :(

**Comment by k80** [comment]
I am also seeing this problem, on macOS 10.12.6, AE CC v15.0.0.

**Comment by bodymovin** [comment]
@vadikzhuk Can you try with version 5.0.1?
This might be solved now.

**Comment by vadikzhuk** [comment]
Unfortunately, it didn't work for me :( Sorry for that (

**Comment by notiles** [comment]
Same issue, Black and white gradient on export /  AE CC 2017 / French / Mac OSX Sierra

**Comment by bodymovin** [comment]
@notiles did you save the project before exporting? if so, can you share a screenshot with the layer expanded up to the gradient?

**Comment by d-korolkov** [comment]
> 
> 
> Hi, yes there seems to be an issue with the way I'm getting the gradient data from the .aep file.
> Until I fix it, if you rename the gradient property with a different name each, it will work fine.

Thanks for the solution!

**Comment by asssnatcher** [comment]
> Unfortunately, doesn't work for me :( I've renamed all shapes, gradient properties, saved project file and relaunched AAE.

Try to set the same names for the same color gradients.

**Comment by d-korolkov** [comment]
> Hello
> 
> Installed and learned to use After Effects and Bodymovin today. All good otherwise, yet when exporting the animatin colors are completely off. Been Googling and trying all sorts of tricks, not any changes. Below clips how the rocket should look and how it actually looks:
> 
> ![Näyttökuva 2024-05-19 142108](https://private-user-images.githubusercontent.com/88633021/331867314-01d4a995-f887-4e6d-a620-710708b01e03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDE2ODIsIm5iZiI6MTcxNjIwMTM4MiwicGF0aCI6Ii84ODYzMzAyMS8zMzE4NjczMTQtMDFkNGE5OTUtZjg4Ny00ZTZkLWE2MjAtNzEwNzA4YjAxZTAzLnBuZz9YLUFte%i1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEwMzYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNzkzMjFiMDg0ODJlY2U3YTIzMTExYzg3MjRlOTkzZDVkNzhlNDMzMzRkYmM2NjQzODUwNmNjYzYxZmMyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BN_Mbtfq40gO7kzwlWL7kUBhqToDLRIj8H8DcWypmkQ)
> 
> ![Näyttökuva 2024-05-19 142009](https://private-user-images.githubusercontent.com/88633021/331867315-6a207741-c278-4a0c-ae26-63419b5ec333.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDE2ODIsIm5iZiI6MTcxNjIwMTM4MiwicGF0aCI6Ii84ODYzMzAyMS8zMzE4NjczMTUtNmEyMDc3NDEtYzI3OC00YTBjLWFlMjYtNjM0MTliNWVjMzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIwVDEwMzYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZjE3ODFiN2QyNzc1ZWZlY2YyOTM0ZjUxZDRjMmI2OTgxZDI0MGI0YjU3MTE0MTQyZGEyZDI2Y2Y5MWRhYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yMWUV-N2BOWwlcFicSAmU_phuqgRtgLL1skbtKCoPXY)
> 
> Any ideas?

1) First off all you need recreate/or edit manually (dragging the handles/start end positions of your gradients) in theAE progect before any export. No way of proper automatical export of gradients in 99% of cases.
2) Just in case don't forget to check RGB/CMYK in AI before export into AE.
