### ISSUE TITLE
My Images in animation are weird! :-(

### ISSUE THREAD

**Issue by phantoxe** [airbnb/lottie-web#605]
Hi guys... check my image below...

http://www.dotmidia.com.br/error-bodymovin.png
http://www.dotmidia.com.br/ghost.png

I make a DEMO.HTML and it works perfect... i am lost where i need put the images file using in IONIC PROJECT. I already put on assets/images... and its not working... :-(

I am using ADOBE AFTER EFFECT CC.

I put my json file in my app... the objects are animated but the file is with another image... it is not my ghost... :-) It's like the link was broken.

Can u help me please?

Thanks

**Comment by bodymovin** [comment]
did you upload the pngs?
they seems to be missing.
Nevertheless, if you can, you should convert the layers into vector shapes.
