### ISSUE TITLE
Some layers aren't animating properly

### ISSUE THREAD

**Issue by billyhar** [airbnb/lottie-web#606]
I am trying to export a splash screen animation template from after effects. but some layers aren't rendering as they should. 

Chrome Version 60.0.3112.113
After Effects 14.21

I am exporting it through the usual method except with an HTML demo file attached

The animation from the json file should have been exactly the same as in the After Effects editor

The animations work fine within the ae preview, however when exporting only one of the layers seems to be animating, (there should be at least 3) The presets/effects I am using are:
- Fractal Noise
- Directional Blur
- Wave Warp
- Puppet animation

The elements that are missing animations in the exported version are: The cape (wave warp), The blurred clouds in the background (Fractal noise and D-blur), the superhero's body movements (Puppet animation)

Most of my assets are vector files that have been made in Illustrator hen imported into after effects

After effects preview with animations working:

![screen shot 2017-09-04 at 11 18 26 am](https://user-images.githubusercontent.com/18434464/30007752-0e27207a-916a-11e7-8f69-7080005bb397.png)

Browser screenshot from the demo.html with no animations from clouds and cape flapping
![screen shot 2017-09-04 at 12 09 49 pm](https://user-images.githubusercontent.com/18434464/30007750-02460f46-916a-11e7-885b-909a857e7b1e.png)

**Comment by bodymovin** [comment]
Hi, unfortunately all those effects are not supported.
They are difficult to replicate on svg and for real time rendering they would affect performance significantly.
You can check the supported effects on the wiki page.
