### ISSUE TITLE
After export only black screen

### ISSUE THREAD

**Issue by idanial** [airbnb/lottie-web#607]
My animation doesn't export correctly. After export there is only a black screen and nothing happens. But should be a confetti animation.
I checked animation demo in browser.
There is aep: https://www.dropbox.com/s/st49udmn1mzyvf5/Confetti_Pack%20copy.aep?dl=0

(Mac os, After Effects 14.2.1.34, Bodymovin 4.10.1)

**Comment by bodymovin** [comment]
Hi, unfortunately bodymovin doesn't support those effects.
Sorry :/
