### ISSUE TITLE
Exported .json is looking "wrong" and fails in xcode

### ISSUE THREAD

**Issue by charlesbibi** [airbnb/lottie-web#610]
Hi,

I have a problem after the export from AE with bodymovin, when opening the .json file, it looks like this:
<img width="261" alt="screen shot 2017-09-06 at 11 28 17" src="https://user-images.githubusercontent.com/31690551/30104721-beb47f22-92f6-11e7-89ec-200a7bb352d9.png">
When everywhere else I look in demos, blog posts and all, it should start like this:
<img width="255" alt="screen shot 2017-09-06 at 11 28 40" src="https://user-images.githubusercontent.com/31690551/30104750-d622d64a-92f6-11e7-91e4-06848c37ac98.png">

Am I missing something? Is there something wrong with my comp?

I tried all the different settings in the plugin, doesn't change a thing.
I have AE version 13.2.0.49
Here is my source file:

[payconfirmmaster.aep.zip](https://github.com/bodymovin/bodymovin/files/1280562/payconfirmmaster.aep.zip)

Thanks for the help!

**Comment by bodymovin** [comment]
on the second line there is the assets property.
Can you check if it works with the web version?

**Comment by charlesbibi** [comment]
Yes if I choose "demo" option in settings, the web shows it nicely.

**Comment by bodymovin** [comment]
can you report it in the lottie ios repo?
https://github.com/airbnb/lottie-ios
