### ISSUE TITLE
Multiple Animations

### ISSUE THREAD

**Issue by GeniusIdeas** [airbnb/lottie-web#613]
Hello,

I am trying to add multiple animations to produce overlap animations. For some reason, i can only see first animation. Here are my settings:

var container = document.getElementById("convasContainer");
var param1 = {
        container: container,
    	renderer: "canvas",
    	loop: true,
    	autoplay: true,
    	animationData: animationData
    };

    var param2 = {
        container: container,
    	renderer: "canvas",
    	loop: true,
    	autoplay: true,
    	animationData: animationData1
    };
    var test = bodymovin.loadAnimation(param1, param2);

I really appreciate if you can help out. Thank you very much..

**Comment by bodymovin** [comment]
Hi, loading multiple animations in that way is not supported.
Can you overlap two containers and load one on each?

**Comment by GeniusIdeas** [comment]
Hello,Thank you for immediate response.

You mean styling the elements? Please advise. I am trying to produce the animations stack on top of each other like background animation and foreground animation.
