### ISSUE TITLE
Loop animation after reversed animation completes?

### ISSUE THREAD

**Issue by rpmo** [airbnb/lottie-web#615]
I figured out how to reverse my animation after it completes, but is it possible to loop the whole sequence?

**Code:**
<pre>
<code>var anim;
    var elem = document.getElementById('bodymovin')
    var animData = {
        container: elem,
        renderer: 'svg',
        loop: false,
        autoplay: true,
        rendererSettings: {
            progressiveLoad:false
        },
        path: 'data.json'
    };
    anim = bodymovin.loadAnimation(animData);
    anim.addEventListener("complete", function() {
    bodymovin.setDirection(-1); anim.play();
    })
    </code>
</pre>

**Comment by revolter** [comment]
@bodymovin, Why did you close this issue? I'm pretty sure @rpmo needed something similar to the iOS version's `autoReverseAnimation` property. Is it really not available for the web version too?

**Comment by bodymovin** [comment]
@revolter Hi, `autoReverseAnimation` is not available in the web version.
The issue is closed because there was no action to do and was 6 months old.
Feel free to open an issue requesting that property though.

**Comment by bakdakonusuruz** [comment]
Hi there,
Follow up question is, "how can I loop it like one normal one reveres?"
