### ISSUE TITLE
Blend modes are not displaying well

### ISSUE THREAD

**Issue by aenfr** [airbnb/lottie-web#617]
Hi there,

I have a problem when trying to display an animation that uses blend modes. The intention of this is to change in the future the base color of the robot and then show highlights, middle tones and shadows as the same way between several colors. 

I read through bodymovin wikis and find that blend modes are supported. 

What am I doing wrong?

[robot.txt](https://drive.google.com/file/d/0B6jpid64-XWoYzdVcnYyRXZ2ZGM/view?usp=sharing)

**Comment by aenfr** [comment]
I think I found a solution and it is by using blend modes as parameter of the shape layer and not of the contents of that shape layer itself.

**Comment by bodymovin** [comment]
Yes, blendmode on content of shape layers is not supported yet

**Comment by SVN7H** [comment]
Any ETA of blend mode :D ?

**Comment by bodymovin** [comment]
@SVN7H Coming on the next release for the svg renderer.

**Comment by bodymovin** [comment]
@lewandowskid hi, can you share a simple example of the issue to try to fix it?
