### ISSUE TITLE
Alpha channel masking not working for more than 1 layer

### ISSUE THREAD

**Issue by daltonhurd** [airbnb/lottie-web#620]
I'm trying to use alpha channels to mask some objects within another (I'd rather do this than add a masking path to each and every layer). I've got it to work for 1 layer overtop of the mask layer, but if I unhide any of the other layers that are tied to the "set matte" then it makes all of the layers invisible.

There's not any additional paths, which I know causes issues in Bodymovin. I can't seem to figure out what's causing this. Any help would be appreciated.

AEP: https://www.dropbox.com/s/tkjxd3h6j426y7n/shop-animation.aep?dl=0
AE Version: 14.2.1.34
Chrome Version: 60.0.3112.113

**Comment by bodymovin** [comment]
Hi, unfortunately the set matte effect is not supported

**Comment by remorses** [comment]
Will it be?

**Comment by bodymovin** [comment]
How are you masking more than one layer? Via effects?

**Comment by perky** [comment]
Will the Set Matte effect be supported in the future. Projects can get messy when you have a lot of pre-compositions just so you can mask multiple layers.

**Comment by bodymovin** [comment]
Set Matte support is very limited and will not get further support any time soon,
Closing issue for now.
