### ISSUE TITLE
Layers adapting styles from other layers (solved the problem)

### ISSUE THREAD

**Issue by daltonhurd** [airbnb/lottie-web#621]
So I spent 3 hours trying to figure this out, turns out if a layer has the same phrase as another, it will adapt the style from that layer. Not sure of the ruleset of this, perhaps the top most layer will make the lower layer adapt to it, but to give an example I had a "Roof Right" layer above another not associated layer called "Right" (for a different component in the graphic) and "Right" was adapting the gradient used in "Roof Right". I changed the layer name of "Roof Right" to something completely different and voila... It was back to normal.

Perhaps layer numbers should be added to classes in the code output, so even if the layers have similar or exactly the same name, the numbers would make it so styles aren't crossing paths.

**Comment by bodymovin** [comment]
Gradient values are retrieved from the .aep project itself. There seems to be some validation failing when layers have the same name. Sorry about the waste of time :/

**Comment by daltonhurd** [comment]
@bodymovin Do you think it's possible to write the extension to rename layers, whether that's in the exported code, or within AE itself? Perhaps a "clean up" button. Not sure, just thinking of ways this could be avoided.

At the very least I think it should be mentioned in the extension that you don't name layers the same, or in the docs. I noticed AirBnB has a whole guide for using Bodymovin, but perhaps this could be done for your own site, with more details and possibly a FAQ?

It's a great extension and the best solution for doing SVG animations as far as I can see, but I've had to figure out a lot of problems on my own due to lack of discussion/information, and have also bounced around to a lot of different sources, as there's not one definitive place for Bodymovin info.

**Comment by bodymovin** [comment]
Yes you're right.
I need to write better documentation and more detailed.
Regarding the gradient issue it's a little more complicated than that, but i'll see what I can do.
Sorry about all the frustration.
