### ISSUE TITLE
loopComplete event firing before the animation has completed

### ISSUE THREAD

**Issue by paulyabsley** [airbnb/lottie-web#622]
I'm trying to make icons animate when they are clicked. I would like the animation to complete before it can be restarted.

I build my icons first by selecting elements and then using their id's to load the animation data via the path option:

```
    var icon_containers = document.querySelectorAll('div.icon');
    var icons = [];
    
    function buildIcons() {
    	for (var i = 0; i < icon_containers.length; i++) {
    		element = icon_containers[i];
    		if (element.id !== '') {
    			var params = {
    				container: element,
    				renderer: 'svg',
    				loop: false,
    				autoplay: false,
    				path: element.id + '.json'
    			};
    			var anim = bodymovin.loadAnimation(params);
    			icons.push({
    				anim: anim,
    				element: element,
    				isPlaying: false
    			});
    		}
    	}
    }

    buildIcons();
```

The icons object is then looped through and the animationStart method is called as well as a click handler added to each icon container:

```
    function startAnimation(anim, icon) {
    	anim.setDirection(1);
    	anim.goToAndStop(1);
    	anim.play();
    	// This seems to fire immediately, before the icon has completed its animation?
    	anim.addEventListener('loopComplete', complete(icon));
    }
    
    icons.forEach(function(value, id) {
    	startAnimation(value.anim, id);
    	value.element.addEventListener("click", function(e) {
    		startAnimation(value.anim, id);
    	});
    });
```

The startAnimation method attempts to attach an event handler to fire when the loopComplete event happens.

```
    function complete(icon) {
    	console.log(icon + ' loopComplete');
    }
```

However this seems to fire immediately and I'd like to know how to make it fire after the animation so I can then not start a new animation until it has completed.

I've made a reduced test case here: https://codepen.io/paulyabsley/project/editor/ALEWnK

**Comment by bodymovin** [comment]
You probably need to wait for the animation to be loaded before calling the method startAnimation.
When you call loadAnimation, on the instance do something in the lines of:
```javascript 
icons.forEach(function(value, id) {
        value.anim.addEventListener('DOMLoaded',function(){
	    startAnimation(value.anim, id);
	    value.element.addEventListener("click", function(e) {
	            	startAnimation(value.anim, id);
	    });
        })
});
````
If you call startAnimation without waiting for the animation to be effectively loaded, you'll be starting an empty animation.

**Comment by paulyabsley** [comment]
Thanks for taking a look! I tried adding in the code above like you suggest but it hasn't stopped the loopComplete event listener from firing immediately after clicking the icon. The icon play animation works fine on click. I thought I would be able to listen for it to finish before I allow it to be replayed.

**Comment by bodymovin** [comment]
Do you have a link with the new implementation?

**Comment by paulyabsley** [comment]
Yeah sure: https://codepen.io/paulyabsley/project/editor/ALEWnK

**Comment by bodymovin** [comment]
In line 34, you're executing the method "complete" immediately instead of passing it to the addEventListener function.
You shoud change
`anim.addEventListener('loopComplete', complete(icon));`
with 
`anim.addEventListener('loopComplete', complete);`
Of course that you'll need to solve passing the variable icon some other way if you need it.

**Comment by paulyabsley** [comment]
I adjusted it to how you suggested and created a new function to pass to the event listener on the animation object:

```
    	function newComplete() {
		console.log(' loopComplete');
	}

	function startAnimation(anim, icon) {
		anim.setDirection(1);
		anim.goToAndStop(1);
		anim.play();

		anim.addEventListener('loopComplete', newComplete);
	}
```
But now I don't get anything in the console when the animations complete.

https://codepen.io/paulyabsley/project/editor/ALEWnK

Is this all something to do with me creating an object to hold the animations? Do I need to add the loopComplete event listeners in the loop where I initially make the animation objects? If so I'm not sure how to approach it. Thanks for your help by the way!
