### ISSUE TITLE
Inability to render to one json files

### ISSUE THREAD

**Issue by alexgroupcanada** [airbnb/lottie-web#625]
Hi gurus!
guys, I'm not a programmer or designer of any kind. 
I just learned who to create a basic animation, since all my attempts to order it in a way I need for my project are failed.
Well, I created a source file (in Illustrator), then I created (if I can say so.. ) a composition in AEF (cc2015) and then I tried to render it Bodymovin (4.10.1). 
As a result, I'm getting four files in output (one folder with png and second json, the third one is xml and fourth is "data.json". 
What my developer asks is one file json... with will comprise everything!!!
Folks, can you explain to a "green" boy what should be done here in order to convert a fille into ONE json file which will be used in Android animation?
Thanks in advance for your help.
The file is attached

[Coin.zip](https://github.com/bodymovin/bodymovin/files/1308802/Coin.zip)

**Comment by bodymovin** [comment]
Hi, first of all, you should convert your .ai layers to AE shapes, by right clicking and selecting Convert Layer to Shapes. That will remove the pngs folder.
Second, if you got an xml, you probably checked the AVD format to export. You don't need to check it.
Let me know if it helps
