### ISSUE TITLE
Live rendering failing

### ISSUE THREAD

**Issue by aenfr** [airbnb/lottie-web#630]
I got multiple animations of a Robot that I created. There are ten of them that are rendering well in the browser but only one that is failing. I can't figure out what is causing this issue since I've developed this animations from a base rigging composition. Attached is the JSON file

[dancing.json](https://drive.google.com/file/d/0B6jpid64-XWoUjJMQTlPZHFyTlE/view?usp=sharing)

**Comment by bodymovin** [comment]
It seems to be missing a layer called 'C_Shoulder', if it's hidden or a guide, you'll need to include hidden layers or guided layers as part of the export

**Comment by aenfr** [comment]
Thank you Hernan. I had to recreate the comp and paste the same values and all fine.
