### ISSUE TITLE
false color randering

### ISSUE THREAD

**Issue by vnzapen** [airbnb/lottie-web#631]
Hi, everyone,  I have a **false color** issue like this: can you help me?
i have tried to edit the composition, but nothing happened, please help me. thanks

![issue](https://user-images.githubusercontent.com/32127978/30640658-f386812c-9e2d-11e7-9c9a-08e0dbc57e21.png)

**Comment by vnzapen** [comment]
sure, here you go

[https://drive.google.com/open?id=0B527YRKmLYy0SU1hdUtrUmZrMTA](url)

**Comment by bodymovin** [comment]
some files seem to be missing, can you share them?
Also, what is the Comp I should check?

**Comment by vnzapen** [comment]
hahaha sorry here you go.. thank anw

https://drive.google.com/open?id=0B527YRKmLYy0NWFLcVdSNTF3M0k

**Comment by bodymovin** [comment]
Difference masks are not supported yet, sorry :/

**Comment by bodymovin** [comment]
Can you use subtract instead?

**Comment by bodymovin** [comment]
I see you're using obfuscated expressions. Those won't work either

**Comment by vnzapen** [comment]
ouh ok, just fine i can do that, thank you for your help
