### ISSUE TITLE
Problem with Chrome while rendering the animation from .json data

### ISSUE THREAD

**Issue by sowmyy** [airbnb/lottie-web#632]
**I work with a normal environment setup at office.**

* **Chrome  Version 60.0.3112.78 (Official Build) (64-bit)**
* **After Effects CC 2016**

**The animation dint work locally with respect to chrome, but the same worked locally with Firefox. Then i hosted the file into a local server and that solved the problem of bodymovin support with chrome. But, there is a strange white layer that tends to overlay on top of the animation, when it is playing which doesn't happen in Firefox.**

**I expected the animation to work exactly the same in HTML-5 canvas compared to the output from After effects**

**Any bodymovin demo from codepen faces the same issue of white layer overlay when the animation is playing.**

**Comment by bodymovin** [comment]
Can you share a link with your issue?
Regarding locally playing animations without a web server, that is a browser limitation. You should always use web servers for loading json files.

**Comment by sowmyy** [comment]
I've run the html file using atom's live server package which will host it in a local server. So, I am playing the animations using web server only. I have attached a video. Please see to it, because this is a major bug related with bodymovin. Thanks in advance :)
[screencast_chrome_bug.zip](https://github.com/bodymovin/bodymovin/files/1323627/screencast_chrome_bug.zip)

**Comment by bodymovin** [comment]
Yes, this is a major bug but it's not related to bodymovin, it's related to chrome in their latests versions.
https://bugs.chromium.org/p/chromium/issues/detail?id=750252#c4
From my research it happens with masks and on old graphic cards.
Can you share a codepen with the issue?

**Comment by sowmyy** [comment]
Yeah, the bug is related to chrome. So what could be done to solve it? I am not allowed to post data or code online as per my company's policies. If you could come up with an alternative that solves the problem, please do share me. Thanks in advance. :)

**Comment by sowmyy** [comment]
Been a long time, but is this bug handled by chrome ? 
I guess this issue related with chrome might be a major barrier for Bodymovin.
Number of chrome users in the world is numerous. So I guess this needs to be sorted out. what say @bodymovin ?

**Comment by bodymovin** [comment]
This has already been fixed by chrome and it's working fine now.

**Comment by jbotte** [comment]
which version of chrome is it fixed in, im running electron 1.8.6 and still having some artifact issues

**Comment by bodymovin** [comment]
I think it's chrome 62.
Can you post a screenshot of the artifact and the json file?

**Comment by jbotte** [comment]
ah the latest i can run currently is a version of 59 i was able to find a legacy js file laying around in an old animation a designer sent me, that version of body moving seems to fix my problem so maybe waht i was experiencing isn't the same? I am not able to share the assets unfortunately.

**Comment by jbotte** [comment]
this is the bodymovin that seemed to work for me ... https://gist.github.com/jbotte/3e9da6f8d1f11bbb3499e200aedca19d

**Comment by bodymovin** [comment]
@jbotte hmm not sure what can be going on but it doesn't look like a chrome issue. Probably something related to the player.
If you can share a reduced version of the issue, it would be great.
Do you know if you're using Rubberhose for the animation?

**Comment by MB00design** [comment]
Hi . Please help me . I create animation with rubber hose rig and export with bodymovin but doesn't work. 

(first I rig with pins and convert to rubber hose rig)

**Comment by bodymovin** [comment]
@MB00design puppet effect is not supported by the player unfortunately.

**Comment by alexgnatrow** [comment]
just received this on 73 version of chrome. Works in mozilla like a charm. 
Any updates?

![Screenshot from 2019-04-23 21-34-00](https://user-images.githubusercontent.com/22867443/56606906-f4da4a80-660f-11e9-8672-89a36f8bf358.png)

**Comment by bodymovin** [comment]
@alexgnatrow you're getting that error because you're trying to load the json file from your file system instead of a web server.
Because of security reasons, browsers like chrome won't let you load them this way.

**Comment by MiDoUx9** [comment]
> 
> 
> @alexgnatrow you're getting that error because you're trying to load the json file from your file system instead of a web server.
> Because of security reasons, browsers like chrome won't let you load them this way.

how can we do it then without having to upload the file

**Comment by bodymovin** [comment]
@MiDoUx9 you can run a webserver locally with node or xamp.

**Comment by MiDoUx9** [comment]
Thanks for the reply !
I actually fixed it by linking the .json file from the cloud
Also using a live server works im just too lazy
