### ISSUE TITLE
Bodymovin using HTML Class

### ISSUE THREAD

**Issue by pixelcriativo** [airbnb/lottie-web#638]
Hello,

I'm using bodymovin to work with loaders. so I'll need to use HTML classes.
Example:
```
var animation = bodymovin.loadAnimation({
	container: document.getElementsByClassName('loader'),
	renderer: 'svg',
	loop: true,
	autoplay: true,
	path: 'data.json'
})
```

When will it be possible to do this? Any expected date for the launching? 
Thanks!

**Comment by Jeremy-Knudsen** [comment]
You can do this now. Try assigning the loader to a variable outside of the parameter list, and then load the animation:
`
var loader = document.getElementsByClassName('loader'),
    params = {
        container: loader,
        renderer: 'svg',
        loop: true,
        autoplay: true,
        path: 'data.json'
    },
    animation = bodymovin.loadAnimation(params);

`

**Comment by bodymovin** [comment]
document.getElementsByClassName returns an array, so you'll need to pass an element from the array, not the array itself.
Are you looking to load multiple loader elements with a single animation?

**Comment by pixelcriativo** [comment]
@Jeremy-Knudsen I tried using this solution but it didn't work for me.
Example: https://codepen.io/pixelcriativo/project/editor/ALErGp

@bodymovin exactly!

Thanks for your help!

**Comment by bodymovin** [comment]
@pixelcriativo it's not on the pipeline right now.
You'll need to do the array iteration yourself and pass a copy of the json animation for each.

**Comment by pixelcriativo** [comment]
@bodymovin thank you for the attention.

I think this improvement would be very interesting, especially when used to create the UI of some tool, because I would like to use the same animation several times, with only the classes. For example: <div class = "loader"> </ div> | <div class = "loader"> </ div> | ...

Thanks for your help!

**Comment by skstoyanova** [comment]
Hi,
I'm facing the same problem. Does it already implemented and how should be used?
Even trying to loop does not work.
Thank you.
