### ISSUE TITLE
The animation from .json file not working

### ISSUE THREAD

**Issue by may000088** [airbnb/lottie-web#641]
**Tell us about your environment**
Mac OS , Bodymovin 4.11.0
* **Browser and Browser Version:**
Chrome
* **After Effects Version:**
AE CC 2017
**What did you do? Please explain the steps you took before you encountered the problem.**
I made a test animation and exported a json file with bodymovin.
**What did you expect to happen?**
the animation would move on lottie preview site.
**What actually happened? Please include as much _relevant_ detail as possible.**
the animation not move. If bodymovin not support, is there anyway we can replace with?
**Please provide a download link to the After Effects file that demonstrates the problem.**
pls see attached file.thx.

[Uploading test.aep.zip…]()

**Comment by bodymovin** [comment]
It seems the .aep didn't go through. Can you upload it again?

**Comment by may000088** [comment]
@bodymovin Sorry to bother. I found it is puppet tools‘ problem. It seems bodymovin do not support yet, is there any way we can use to replace with puppet tools?

**Comment by bodymovin** [comment]
I don't know what kind of animation you are doing, but can you use rubberhose?
Puppet pin is very difficult to reproduce indeed.

**Comment by may000088** [comment]
Hi, I upload the aep files，could you kindly help me check it？Can I use rubberhose for this case？ 

[test.aep.zip](https://github.com/bodymovin/bodymovin/files/1335716/test.aep.zip)

**Comment by MARS1** [comment]
Does this mean using the Rubberhose script will allow the animation to render properly after running it through Bodymovin? I too have the Puppet Pin problem and understand it would be hard to recreate via Bodymovin but wanted clarification since you didn't answer may000088 regarding whether Rubberhose is supported. Thank you.
