### ISSUE TITLE
i think i have a mask problem.. 

### ISSUE THREAD

**Issue by nielsgeurs** [airbnb/lottie-web#642]
Hi there!
I have a problem with the maks on export. 
https://www.lottiefiles.com/share/W5rh2H

But how can change it to a 'canvas renderer' as you've mentioned in another threat?
I only have the 'plugin' under extensions in AE.
Also, is it possible to export a part of the animation? 
many thanks!
Niels

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by nielsgeurs** [comment]
https://www.dropbox.com/s/58kqgmtqaqell0b/_Test%20graphic%20animation%20for%20app.aep.zip?dl=0
