### ISSUE TITLE
Looking for suggestions of transition between multiple animations

### ISSUE THREAD

**Issue by babygoat** [airbnb/lottie-web#645]
Hello~ @bodymovin 
I'm currently working on a project with multiple animation json files. After doing some study of the source code, I came with two ideas: first, by loadAnimation onto different "Containers" with the CSS transition style or register the animations into same container to become elements. However, for the latter solution, I haven't find any interface to deal with the animation switching or the transition once the animation complete. I was wondering if you could give me some advice here. Whether to proceed with multiple container or there are some tricks I'm missing. Thanks for your consideration!

P.S, Another question here, was searchAnimations() designed to not return any AnimationItem found? Intuitively, I might expect that the function will give back the AnimtaionItem for the provided params.

**Comment by DaanDirk** [comment]
You could also place everything in one long comp and play different parts of your time line with playSegments.

If you need parts to play simultaneously you can use sliders to manipulate valueAtTime and then set those sliders with javascript.
You place a keyframe and the start and end of the timeline and set the value you need in the json with something like:
> anim.animationData.layers[0].ef[0].ef[0].v.k[0].s[0] = newVal;
anim.animationData.layers[0].ef[0].ef[0].v.k[0].e[0] = newVal;

Does that help you?

**Comment by babygoat** [comment]
@DaanDirk 
Thanks for providing another option!!
I will take the suggestion as a future improvement to play simultaneously with the designers.
It seems to me that the layers defined in json should be involved in this option.
For the time being, I had stepped forward with the multiple containers in the project.
Thanks again for the advice!
