### ISSUE TITLE
Tapered Stroke with expressions freezes in browser

### ISSUE THREAD

**Issue by chee-seng** [airbnb/lottie-web#649]
**iMac (27inch, Mid 2011) // 3.1 GHz Intel core i5 // 12gb 133 MHz DDR3 // AMD Radeon HD 6970M 1024 MB**

* **Google Chrome - Version 60.0.3112.113 (Official Build) (64-bit)**

* **After Effects CC 2017 version 14.2.1.34**

Hi, i'm having trouble with a tapered stroke expression not rendering. When I open my animation in the browser (exported as demo), the animation freezes at the exact moment the tapered stroke element should appear on screen.

I'm not sure whether it is because some of the expressions are not supported. A related question is whether I can 'bake' expression info to keyframes as a workaround.

I have been using a trimmed path to achieve the same effect, which renders fine, but when I changed from that to the path with the tapered line preset, I encountered the problem mentioned above.

Since the preset is built around trimmed paths, I thought it would work just fine, but I'm fairly naive RE html5, so I'm not sure what can and cannot be made for it in AE.

When I exported the animation as demo and opened it in the browser, it would play just fine right up until the offending stroke should appear on screen. I've encounter issues in the past where things render different to how I expect, but this freezes the animation leading me to think it's breaking with expressions

** https://drive.google.com/file/d/0B-kO9Rd8oErpZkMxMlJlMTktck0/view?usp=sharing **

Thanks!

**Comment by cpdt** [comment]
I can replicate this in Firefox 57.0a1. It's not actually freezing the browser (at least for me), but is causing the following error:

```
TypeError: thisProperty.propertyGroup is not a function
```

which is coming from some of the expressions in `2//WLTH_logo (BW)`. I'm guessing this is simply because the `propertyGroup` function is not supported.

**Comment by DaanDirk** [comment]
I guess numProperties isn't supported yet.
Good news: you can work around it.

Add a slider for the number of tapers.
Replace everything like:
> var totalGroups = content("Duplicate Groups").content.numProperties+1; //The +1 accounts for the Master Group, outside the Duplicate Groups folder.

With:
> var totalGroups = effect("number")("Slider") +1; //The +1 accounts for the Master Group, outside the Duplicate Groups folder.

Also the combination of repeater and expressions isn't ideal.
You need to copy the layer and rotate the copies.
All that will however leave you with a large file and a rendering hit.
The logo is 1.2 Mb, quite large.
You might be better off by drawing and animating the bubble/tapered stroke with a path.

fixed file:
http://www.daandirk.com/wp-content/uploads/WLTH_animation_logo-troubleshooting.aep
demo:
http://www.daandirk.com/bm-test-tapered/

**Comment by chee-seng** [comment]
Thank you both for the feedback, great help. Good to know which properties do and do not work. Is there a comprehensive list of which properties are currently supported?

DaanKirk I haven't checked the file yet, I'm curious to have a look at your workarounds. thanks for your time troubleshooting it.

**Comment by bodymovin** [comment]
Hi, numProperties and propertyGroup should work.
I'll take a look at this to see what is going on.

**Comment by bodymovin** [comment]
This should be working now
