### ISSUE TITLE
Error 0 :: 42 After Effect (portable) crash while Render using Bodymovin

### ISSUE THREAD

**Issue by Fatinbunny2** [airbnb/lottie-web#652]
Hello there,

I am trying to use 'bodymovin' for a first time. I am using a crack version of portable Adobe After Effect CC. After downloaded the plugin, then I drag it into After Effect folder under extension name like this..
![body](https://user-images.githubusercontent.com/32445360/31066165-6fb7555c-a77d-11e7-9bf5-f0c0cb046e63.JPG)

Then I installed the "aescript + aeplugins zxp" installer. Then I just try to do some animation and try render using bodymovin. And this error message occur whenever I try render using this. Note that rendering process not even start.
![ae error](https://user-images.githubusercontent.com/32445360/31066238-0177a258-a77e-11e7-8345-47f9827b760a.JPG)

Here my file :
[test 2.zip](https://github.com/bodymovin/bodymovin/files/1348347/test.2.zip)

Download Portable After Effects : 
http://dl.downloadly.ir/Files/Software2/Adobe_After_Effects_CC_2017_v14.2.1.34_x64_Portable_Downloadly.ir.rar

_____________________________________________________________________________________________________________

**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
When is the crash showing up? as soon as you open the extension? or focusing on it?

**Comment by Fatinbunny2** [comment]
As soon as I start render using the extension
