### ISSUE TITLE
Docking Bodymovin panel in AE UI causes AE crash on launch

### ISSUE THREAD

**Issue by mtnoxx** [airbnb/lottie-web#653]
Hello,

First off, thank you for creating Bodymovin; it is truly a game-changer!

AE version: 14.2.1.34
OS: Windows 10 Pro / Version: 1703 / Build: 15063.608

Issue: I docked the Bodymovin panel in the AE UI; on the next application launch and all subsequent launches AE unexpectedly quit with "After Effects has encountered a problem and needs to close."

Resolution: I manually removed Bodymovin from the file structure:
C:\Program Files (x86)\Common Files\Adobe\CEP\extensions\com.bodymovin.bodymovin
On the next launch, AE started as normal. I've had no issues with keeping the floating Bodymovin panel open; this issue only occurs when the panel is docked.

**Comment by DaanDirk** [comment]
There is a bug at the moment which won't allow you to dock more than one panel at the same place in the AE UI.
https://aescripts.com/forums/discussion/comment/17332/#Comment_17332
Maybe that is what is bothering you?

**Comment by mtnoxx** [comment]
I can dock multiple third-party panels in any location of my choosing in the AE UI; Bodymovin is the only panel that is causing repeated crashes on launch. I do appreciate the info, though.

**Comment by bodymovin** [comment]
Closing, reopen if issue is still happening
