### ISSUE TITLE
Slim player does not support Canvas or HTML mode

### ISSUE THREAD

**Issue by lfoscari** [airbnb/lottie-web#655]
Using an exported animation for the web using the full player's file is difficult, because of its weight.
To tackle this issue there's the slim version of the player, but it only supports the SVG mode. Would be really nice to have a slim version for Canvas mode and one for HTML mode as well.

**Comment by bodymovin** [comment]
Yes, it's on my pipeline creating a more fragmented version of the player.
If you're not, gzipping the js and json reduce the filesize considerably.
