### ISSUE TITLE
JSON file exported from AE is not working, tried everything

### ISSUE THREAD

**Issue by klausabio** [airbnb/lottie-web#658]
The plugin seems to be exporting corrupted JSON files. I can't get them to play.

If I use another JSONs from the demos, they work perfectly, but once I replace those with the one I exported, it fails to play.

Yes, I'm using the latest player and plugin.

You can see my JSON data here on this working demo > https://jsfiddle.net/16otprco/

If you change the JSON for one of the demos, it works perfectly.

Here's my AE file > https://www.dropbox.com/s/yhjzch7v4ekdgoa/Test.aep?dl=0

And here's my JSON file > https://www.dropbox.com/s/ft0oiuacj449bvn/data.json?dl=0

**Comment by klausabio** [comment]
The issue is with exported fonts. If I outline the font then the JSON file works.

**Comment by bodymovin** [comment]
Hi, the extension should be able to export text correctly.
I just tried the .aep and it seems to work fine.
Can you share the .json again? It's returning a 404 page.

**Comment by klausabio** [comment]
Here you go

https://www.dropbox.com/s/ke8t282ln8rc4dq/data.json?dl=0

This same json exported with the font as outlines works perfectly

**Comment by bodymovin** [comment]
For some reason the fontStyle is missing.
I have to look into it.

**Comment by klausabio** [comment]
Thanks, 

Is there any way I can add that myself to the JSON file to make it work in the meantime?

**Comment by bodymovin** [comment]
It's not that easy.
Can you try exporting it with a different font?

**Comment by klausabio** [comment]
Already tried that.

The current JSON is exported using Helvetica. Before I tried others.

**Comment by bodymovin** [comment]
Same result?
What version of Bodymovin are you using?
is AE or your OS in a different language than english?

**Comment by klausabio** [comment]
Latest version
AE is CC 2014 in spanish
I'm running macOS High Sierra in spanish

**Comment by bodymovin** [comment]
ok, I'll see if that is related

**Comment by klausabio** [comment]
thanks! I'm just trying to export a 2 digit number, so no weird characters either

**Comment by kshivanku** [comment]
Hi I might have run into this issue as well, were you able to resolve it @klausabio ?

**Comment by bodymovin** [comment]
Closing, reopen if issue is still happening
