### ISSUE TITLE
Json Rendering

### ISSUE THREAD

**Issue by nishuvns** [airbnb/lottie-web#660]
Hey,

I am using saber animation in Adobe after effect when i am rendering two option showing which one i choose . i want to convert it in JON format. Please help

Thank you

https://drive.google.com/file/d/0B8Oq-WaEYK2eVDZMRkpMY18wS1k/view?usp=sharing

**Comment by nishuvns** [comment]
![capture](https://user-images.githubusercontent.com/8512521/31351857-45df563a-ad4a-11e7-958c-8667ddb479cb.PNG)

**Comment by bodymovin** [comment]
Hi, those are the comps of your project you can export.
Nevertheless, your animation uses effects that are not supported unfortunately.

**Comment by munkhorgil** [comment]
@bodymovin Any update on this? Can we use Saber plugin for the Lottie now?

**Comment by bodymovin** [comment]
@munkhorgil unfortunately, it is not supported. Those type of effects are not very performant on real time rendering, and not easy to replicate either

**Comment by yash99thakur** [comment]
is there any update to use saber plugin with bodymovin now ??
coz i still coud not convert the same
