### ISSUE TITLE
"Special" line animation not working

### ISSUE THREAD

**Issue by Rhinomalade** [airbnb/lottie-web#664]
I want to use bodymovin to display animated lines in the background of my site.

_Google chrome Version 61.0.3163.10
After effect Version 14.2.1.34_

I made some lines and used the wiggle path option to animate them.

![image](https://user-images.githubusercontent.com/32507129/31386381-e9b55148-adc6-11e7-9609-1504bb561a36.png)

I expected the lines to move like in my animation.

The lines don't move.

https://www.dropbox.com/s/7zewzhvptkdyx0v/animated%20lines.aep?dl=0

**Comment by bodymovin** [comment]
hi, wiggle path is not yet supported unfortunately
