### ISSUE TITLE
bodymovin as a preloader animation

### ISSUE THREAD

**Issue by rezwanferdous** [airbnb/lottie-web#665]
I wanted to use bodymovin animation as a preloader animation but i have no idea how to use it as a preloader animation. Can anyone help?

**Comment by bodymovin** [comment]
Hi, where are you stuck?
Did you load the javascript player as well?

**Comment by Nick-Fiasco** [comment]
Hi,

I'm interested in this too. But not sure exactly how to run the animation until the page is loaded then stop the animation.

Would like to be able to run the animation on initial page load, then once the rest of the document is ready, have the animation play from wherever it is within the animation loop to the first frame and stop.

Hopefully I have explained myself correctly!

@bodymovin Do you have any tips on how to achieve this?

**Comment by bodymovin** [comment]
@Nick-Fiasco you can use animation.setSpeed(-1) and it will play backwards.
For it to stop in the first frame and not continue looping, you can do animation.loop = false;

**Comment by Nick-Fiasco** [comment]
Hey @bodymovin Since writing that I ended up figuring it out. Needed some maths and timings to get it to run while things were loading then to finish the current loop and then run the animation to stop half way through.

For anyone who may in interested here is my code. Might not be the cleanest as I'm still learning my way in JS.

`var bodymovinContainer = document.getElementById('bodymovin');
        var count = 0;
	var animData = {
		container: document.getElementById('bodymovin'),
		renderer: 'svg',
		loop: true,
		prerender: false,
		autoplay: false,
		autoloadSegments: false,
		path: 'http://path-to-data-file/data.json'
	};
	var anim;
	anim = bodymovin.loadAnimation(animData);

	anim.addEventListener('DOMLoaded', function(){
		anim.goToAndPlay(1,true);
	});

	function loopCompleteHandler(){
		anim.removeEventListener('loopComplete', loopCompleteHandler);
		anim.stop();
	}

	window.addEventListener('load',function() {
		anim.removeEventListener('loopComplete', loopCompleteHandler);
	anim.goToAndPlay(1,true);
		setTimeout(function(){
		anim.goToAndStop(32,true);
		}, 3245);
		$('body').removeClass('siteLoading');
	}, false);`

**Comment by HirenParekh** [comment]
I also want to use lottie-web as a preloader. I think right now animation start after 'DomLoaded' event. But what I want is to show the lottie animation while dom is getting ready and hide it once all my css and javascripts are loaded. is it possible to use lottie-web as a preloader.

**Comment by Nick-Fiasco** [comment]
Hey @HirenParekh I have been using Bodymovin animations as preloaders for a little while, just have to get your script for bodymovin loaded up first and maybe use a function to start your animation. I used pace.js to check when everything was fully loaded and then stop the animation.
