### ISSUE TITLE
render settings for client handover (looking for advice)

### ISSUE THREAD

**Issue by chee-seng** [airbnb/lottie-web#666]
Hi, I have a finished animated logo which i've been testing along the way by rendering a html file via the 'demo' render option.

I'm now ready to export the files for my client who is working with a developer. It will be used on their website as well as part of a loading screen in an app.

What is the recommended render option for this scenario?

I myself am not a developer, so i'm not really sure how something like this is usually packaged for a client to then use how they wish.

*my animation has precomps, but is very simple; just trim paths and alpha mattes. Shown below...

![export_symbol_logo_type_colour](https://user-images.githubusercontent.com/32382201/31433506-edd57f90-aebc-11e7-8cff-f3d6e3df5e4e.gif)

Thanks

**Comment by bodymovin** [comment]
You should provide the dev the json file.
And probably the dev will know how to get the Bodymovin player and Lottie.
Regarding alpha mattes, they translate to masks in svg and in some browsers they are not very performant.
If you can use regular masks instead, it would be better.

**Comment by chee-seng** [comment]
Ok thanks, i'll look into the mask issue to see if i can come up with a solution.

RE my original question, the json file produced by the 'demo' setting is sufficient? What is the difference or purpose of exporting using 'standalone'?

Thanks
