### ISSUE TITLE
Gradients don't work

### ISSUE THREAD

**Issue by Snufkinn** [airbnb/lottie-web#667]
Hi!
When I make gradients, I get this result after export:

BEFORE
 ![pasted image at 2017_10_12 05_56 pm 1](https://user-images.githubusercontent.com/12381251/31503050-47f7e098-af77-11e7-9505-75c5044d1df8.png)

AFTER
![pasted image at 2017_10_12 05_56 pm](https://user-images.githubusercontent.com/12381251/31503049-47d858a4-af77-11e7-9555-c0ac4e3accea.png)

BODYMOVIN last version (4.11.1)

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by Snufkinn** [comment]
Yes

[Gradients.zip](https://github.com/bodymovin/bodymovin/files/1381770/Gradients.zip)

**Comment by bodymovin** [comment]
You're using the effect Gradient Ramp which is not supported.
Supported gradients are shape Gradient Fills and Strokes.
