### ISSUE TITLE
JSON schema is invalid

### ISSUE THREAD

**Issue by stristr** [airbnb/lottie-web#670]
A few of the JSON schema files seem to be invalid or use a syntax I'm not familiar with. Specifically, they are using the syntax `"properties": [{...}, ...]` to describe certain objects, instead of enumerating properties as keys of the `"properties"` object.

Example:

```
    ...
    "t": {
      "title": "Text Data",
      "description": "Text Data",
      "properties": [
        {
          "title": "Animators",
          "description": "Text animators",
          "items": {...},
          ...
          "type": "array"
        },
        ...
      ],
      "type": "object"
    },
    ...
```

It's not clear what the key representing Animators is supposed to be called in the payload. After reading a Bodymovin file with a text layer, I think it's an array keyed by `"a"`...but the correct way to write this would be:

```
    ...
    "t": {
      "title": "Text Data",
      "description": "Text Data",
      "properties": {
        "a": {...}
        ...
      },
      "type": "object"
    },
    ...
```

I noticed this in these files:

 - [#/layers/text](https://github.com/bodymovin/bodymovin/blob/master/docs/json/layers/text.json)
 - [#/properties/shape](https://github.com/bodymovin/bodymovin/blob/master/docs/json/properties/shape.json)
 - [#/properties/shapeKeyframed](https://github.com/bodymovin/bodymovin/blob/master/docs/json/properties/shapeKeyframed.json)
 - [#/properties/valueKeyframed](https://github.com/bodymovin/bodymovin/blob/master/docs/json/properties/valueKeyframed.json)
 - [#/properties/multiDimensionalKeyframed](https://github.com/bodymovin/bodymovin/blob/master/docs/json/properties/multiDimensionalKeyframed.json)
 - [#/sources/chars](https://github.com/bodymovin/bodymovin/blob/master/docs/json/sources/chars.json)

**Comment by dnfield** [comment]
These are definitely invalid.  I've started working through some possible ways to correct them...  I'd like to be able to do some codegen/validation off of them if possible.

**Comment by dnfield** [comment]
I'm not really sure (and don't have examples to work from) on how to fix #/layers/text or #/sources/chars unfortunately.
