### ISSUE TITLE
Only blue square when exporting 

### ISSUE THREAD

**Issue by lfrangart** [airbnb/lottie-web#678]
**Tell us about your environment**

Windows 7

* **Browser and Browser Version:**

Google Chrome

* **After Effects Version:**

CC 2017 newest version

**What did you do? Please explain the steps you took before you encountered the problem.**

I created a animation  from a illustrator file i converted into shapes
and tried to export a file for local demo and standalone.

**What did you expect to happen?**

see my normal animation in my browser.

**What actually happened? Please include as much _relevant_ detail as possible.**

i only received a blue square and cant see anything.

[Pyramiden.zip](https://github.com/bodymovin/bodymovin/files/1387521/Pyramiden.zip)

I hope you can help me with that problem. 
i tried bodymovin on another animation and it worked perfect! 
i got no clue why it didnt work this time. 
thank you for your great work!

**Comment by bodymovin** [comment]
go to Wueste Konturen > Contents > Gruppe 2 
and remove: Pfad 2 and Pfade zusammenführen 1
Merge paths are not supported and it's covering the other layers

**Comment by lfrangart** [comment]
ok it worked, thanks for that! 
but now i have a problem on the Background.
i tried to use your method on "Sonne Konturen" 
but i was unable to remove the merge paths and keep the little rods.
you have a solution for that? 

newest file: 
[Pyramiden.zip](https://github.com/bodymovin/bodymovin/files/1393664/Pyramiden.zip)

**Comment by bodymovin** [comment]
On each group (1 to 6) in that layer erase Pfade zusammenführen 1, Pfade zusammenführen 2 and the path between those two
