### ISSUE TITLE
Uncaught SyntaxError: Unexpected token v in JSON at position 0     

### ISSUE THREAD

**Issue by kevberot** [airbnb/lottie-web#679]
Hey guys, 

I'm trying to implement bodymovin on a webflow project. 

http://threadify-9ad47f.webflow.io/

I've got this error coming up:

Uncaught SyntaxError: Unexpected token v in JSON at position 0
    at JSON.parse (<anonymous>)
    at XMLHttpRequest.r.onreadystatechange (bodymovin.js:9)

any ideas? 

Browser: Chrome
AfterEffects CC 2015

Thanks!

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by kevberot** [comment]
Here it is! 

Thanks! 

[Threadify-Font-Colors.aep.zip](https://github.com/bodymovin/bodymovin/files/1393022/Threadify-Font-Colors.aep.zip)

**Comment by bodymovin** [comment]
Hi, I've tried the animation and it seems to work fine.
It seems it is not finding the json file.
How can I reproduce the error in your site?
