### ISSUE TITLE
Simple animation performance Safari - Tips?

### ISSUE THREAD

**Issue by AndrewCary** [airbnb/lottie-web#681]
Hi there, I've just discovered BodyMovin and it's what I've dreamed of for a while! Awesome!

I've put together a simple logo animation experiment and I've noticed performance issues with Safari on the Mac. On iOS it's worse. Do you have any tips on how I could optimise my file? Thanks!
I've tried using canvas as the renderer but it breaks the animation..

https://www.digital-resonance.co.uk/demo/logo/
[Logo_Ident.aep.zip](https://github.com/bodymovin/bodymovin/files/1394312/Logo_Ident.aep.zip)

Thanks

MacBook Pro (15-inch, 2017) 
2.9 GHz Intel Core i7 
Radeon Pro 560 4096 MB
Intel HD Graphics 630 1536 MB

Safari Version 11.0
After Effects CC 14.2.1.34

**Comment by bodymovin** [comment]
Hi, I think you're using the expansion property of masks, right?
That gets converted in svg to a filter and a mask instead of a clipping path.
Some browsers like Safari don't have good performance with filters, if you can redo the animation only changing the mask shape, it will perform much better.

**Comment by blobinabottle** [comment]
Is it the same as using alpha Track Matte? I got bad performances in Safari with this animation:
https://www.lottiefiles.com/share/hRuaty which is using alpha track matte

**Comment by blobinabottle** [comment]
Ok never mind I found other ticket about the track matte and it's the same issue :-) 
Maybe we should report this to Apple?

**Comment by bodymovin** [comment]
@blobinabottle I wish they would hear...
