### ISSUE TITLE
BodyMovin Index Page is Blank

### ISSUE THREAD

**Issue by tommyc325** [airbnb/lottie-web#682]
Hi Everyone

I'm having an issue getting my animation to show up correctly. When I export out the data.json and the demo.html file everything works great but the file is very robust. Im now trying to get this to work in a html file. I am not having any luck even though i followed the tutorial correctly. I attached a zip file with all files. Any help would be appreciated.

[BodyMovin.zip](https://github.com/bodymovin/bodymovin/files/1396792/BodyMovin.zip)

**Comment by bodymovin** [comment]
Hi, I see it working fine.
Are you using a web server to load your index.html file?

**Comment by tommyc325** [comment]
that's the problem. Thank you
