### ISSUE TITLE
Most Installation methods fail for After Effects CC2018

### ISSUE THREAD

**Issue by scisci** [airbnb/lottie-web#683]
On Mac OS:

Using the latest After Effects CC 2018, the only installation method that worked was via adobe creative cloud installation. All manual zxp installers seemed to be ineffective.

**Comment by bodymovin** [comment]
Hi, I've tried using the zxp installer and it seems to work fine.
Is it not showing up?

**Comment by scisci** [comment]
Maybe it’s just my system then. The zxp installer would show it as installed but it would never show up in the extensions menu.

**Comment by Pubard** [comment]
Nothing work for me. Any idea ?

**Comment by scisci** [comment]
If you have adobe creative cloud, try adding the add-on here:
https://exchange.adobe.com/addons/products/12557

**Comment by tuna-f1sh** [comment]
No luck for me either - doesn't work with CC addon manager, Extensions CC or ZXP installer (complains about manifest).

**Comment by bodymovin** [comment]
@tuna-f1sh The ZXP installer got an update lately, can you try with the new version?

**Comment by tuna-f1sh** [comment]
This actually resolved itself after a performing pretty much all the install methds:

* Using the Exmancmd tool listed here: https://helpx.adobe.com/creative-cloud/kb/installingextensionsandaddons.html (this appeared to do something but hung when trying to list addons)
* Editing the registry fields (open the registry key HKEY_CURRENT_USER/Software/Adobe/CSXS.8 and add a key named PlayerDebugMode, of type String, and value 1.)
* Using CC add-on installer
* Using zxf installer

None of them seemed to do anything until a reboot. After which, both CC addons listed it as installed and the zxf installer. Not sure if the registry edit was what did it.

**Comment by tuna-f1sh** [comment]
Just to help others: a colleague had the same problem and it was the registry key, followed by reboot that allowed it to sync via Creative Cloud.

**Comment by mrondina** [comment]
I encountered the same issue and none of the above fixes were able to resolve it. I'm on a Mac running 10.13.2 and AE 15.0.1 build 73 with the latest ZXP installer

**Comment by abkoradiya** [comment]
can i use this plugin for After Effects CS6??

**Comment by bodymovin** [comment]
@mrondina can you file an issue in the aescripts forum? Perhaps they can help you with the zxp installer.
@abkoradiya no, sorry, it doesn't work with CS6

**Comment by mrondina** [comment]
Thanks. I found a work around. I converted the .zxp file to a .zip and then moved the script to the correct folder and restarted AE. It's been working so far

**Comment by taylorling** [comment]
Have the same issue installing bodymovin for AA 2018.

ZXP installer says it can't find any compatible apps for the installation (but I do have AA2018 installed), so I think it 'might' be the issue. But when I tried manual installation like how @mrondina suggested, I can see the Bodymovin options in Extension for AA2018, but it doesn't launch anything, is it compatible with AA2018 @bodymovin?

I then installed AA2017, and ZXP installer sees it correctly and I am able to install latest bodymovin zxp.

**Comment by bodymovin** [comment]
@taylorling probably you needed to restart AE or your OS. Sometimes, specially on Macs, you need to do that so registers get renewed.

**Comment by taylorling** [comment]
@bodymovin Got it - will keep that in mind, for now, it's working for me by installing AA2017 :)

Thanks!

**Comment by abkoradiya** [comment]
hello I have installed After Effects CC, but, plugin can not installed on it.
