### ISSUE TITLE
Colour / Animation issues

### ISSUE THREAD

**Issue by Booyah75** [airbnb/lottie-web#684]
Hello gang!

I am trying to get this simple animation working (http://recordit.co/iojs4om76c), but I am having a few issues.

1. The background gets a fill colour and the body of the character becomes transparent. 
2. Bodymovin JSON export doesn't animate at all, just a still image.

Bodymovin export: https://i.imgur.com/9Yz2bKf.png

What am I doing wrong here? :( 

Here are the AE files: https://drive.google.com/drive/folders/0B-C01MPW7JVrRngzLVdSUHZRclk?usp=sharing

Thank you!

**Comment by bodymovin** [comment]
Hi, in your layer > Contents > Group 12
remove Merge Paths 1, Path 12 and Merge Paths 2
2. Bodymovin doesn't support the wiggle Effect. Not many effects are supported for now.

**Comment by Booyah75** [comment]
Thank you!
