### ISSUE TITLE
Canvas VS SVG renderer

### ISSUE THREAD

**Issue by kerrylofton** [airbnb/lottie-web#685]
After going through and fixing all the issues I could think of, I still can't get some of my masks to export and work right. The mask that I am using is difference (it won't work with add mask). I saw in another issue that it does work with the canvas renderer. How do I use that or switch between the two?

**Comment by bodymovin** [comment]
take a look here:
https://github.com/bodymovin/bodymovin#other-loading-options
where it says 'svg', change it to 'canvas'
