### ISSUE TITLE
How to add bodymovin files into a wordpress site

### ISSUE THREAD

**Issue by lakeelo** [airbnb/lottie-web#690]
Hi everyone, 

I've been trying to put up an animations into my website (offline) but I haven't found the solution.
The problem is that I can't find the way to add the Js ans json files and link them to wherever I want.
Can somebody help?

**Comment by bodymovin** [comment]
Hi, where are you stuck? Can you share a link?
perhaps this can help:
https://codepen.io/airnan/project/editor/ZeNONO

**Comment by lakeelo** [comment]
Hi, sorry I should've said that it’s on a WordPress child theme that I want to incorporate these files. So what I did is to create a JS file where I put de bodymovin.js and the json. I’ve been trying all sorts of code to link these files to the functions.php but it’s not working. Or the problem comes from the html that incorporates some scripts and I don’t write it well in the WordPress. 
By itself the animation works on the internet;) 
Thanks I hope I have been clear ;)

**Comment by bodymovin** [comment]
Can you share a link to see what is going on?

**Comment by lakeelo** [comment]
Hi there it is: http://los-website.com

**Comment by lakeelo** [comment]
thank you

**Comment by bodymovin** [comment]
It seems you're passing an "animationData" object that doesn't exist

**Comment by lakeelo** [comment]
I know, I saw that,  what can I do to make it work. It's the code given by the plugin, I have just add the path to the json and that's all.
