### ISSUE TITLE
No animation is happening

### ISSUE THREAD

**Issue by rezwanferdous** [airbnb/lottie-web#693]
I exported as glyph and demo but there's no animation. I tried it with index as well but i think the problem is with something else i'm not sure. i'm not using any third-party plugin. I used some vector shape which i converted from illustrator. Please help!!!!!!

[Exported_json&demo_File](https://www.dropbox.com/s/6thw40kp3rj86xk/webani.zip?dl=0)

**Comment by bodymovin** [comment]
Hi, can you share the .aep?
