### ISSUE TITLE
The animations are not working as we expected. We can describe the problem as a lag or jump on them

### ISSUE THREAD

**Issue by alexrodh** [airbnb/lottie-web#696]
**Tell us about your environment**

* **Browser and Browser Version:**
Google Chrome 62.0.3202.75

* **After Effects Version:**
Adobe After Effects CC 2017.2 Release
Version 14.2.1.34

**What did you do? Please explain the steps you took before you encountered the problem.**
First I separated the AI into single layers, imported it into AE and animated the objects using Masks, Stroke, Tint and Radial Wipe. Each element in a single layer and different compositions, using the vectorized .AI project with the continuously rasterize option on. I exported the animations with the Bodymoving extension into .json files with their respective .png images and sent it to the programmer.

**What did you expect to happen?**
I expected the animations to look like the GIF I'm attaching here, but instead they are not animating how they should be. Seems to me like it's not interpreting/recognizing the effects the right way. 
[gifs](https://goo.gl/Pecp9C)

**What actually happened? Please include as much _relevant_ detail as possible.**
We attached the links to the final results in HTML, our animations are not performing properly. If you compare each of them with their GIF, you will see the bad performance.
[seo](https://designheaps.com/new/SEO/)
[seo on page](https://designheaps.com/new/seo-on-page/)
[gigs](https://designheaps.com/new/GIGS/)
[ux](https://designheaps.com/new/UX/)
[visual design](https://designheaps.com/new/visual-design/)
[prototype](https://designheaps.com/new/prototype/)
[business analysis](https://designheaps.com/new/business-analysis/)
[seo off page](https://designheaps.com/new/seo-off-page/)
[digital marketing](https://designheaps.com/new/digital-marketing/)
[content strategy](https://designheaps.com/new/content-strategy/)

**Please provide a download link to the After Effects file that demonstrates the problem.**
[AfterEffects](https://goo.gl/Af1opL)

**Comment by bodymovin** [comment]
Hi, unfortunately radial wipe is not yet supported by the plugin
