### ISSUE TITLE
Particles  animation not working after bodymovin rendering

### ISSUE THREAD

**Issue by rashidgd** [airbnb/lottie-web#697]
I am trying to create animation using particles effect which changes one image to another. After Effects rendering is working fine but when applying bodymovin plugin it is not rendering and just showing the blank image, even exporting to the JSON file and running it through player is not solving the issue. I have attached all the files related to the scenario. 

https://drive.google.com/open?id=0B4SltWdb96ozd2xqUjJGUGNqckE

I am using following tools.
After Effects CC 13.5.0.347
Bodymovin plugin version 4.12.3

**Comment by bodymovin** [comment]
Hi, unfortunately, particles are not supported by the plugin.

**Comment by mudassir93** [comment]
Is there any support for particles animation in bodymovin now?

**Comment by bodymovin** [comment]
@mudassir93 no, not yet

**Comment by dawariley** [comment]
how about now? i'm trying to render a particle animation in bodymovin and it doesn't show up in the player. also notice that it masks any layers below it which are non particle animations.

**Comment by bodymovin** [comment]
@dawariley still not. It probably masks other layers because, without the effect, it's a solid that covers the whole canvas.

**Comment by paucc** [comment]
Maybe it will be of help to you the [comment on issue #1410](https://github.com/airbnb/lottie-web/issues/1410#issuecomment-445182428) by @Danjuanlab 

> But if you want to try irregular shapes, or much more particle effects than in this case, you can try to simulate the operation. First, use the particle plug-in to simulate the effect you want, then use Auto-trace to track all paths to generate mask animation, and then adjust the color.

I managed to export a particle sequence, but the problem is that it's 1,5 MB for 7 seconds.
