### ISSUE TITLE
Flicker on scroll

### ISSUE THREAD

**Issue by byjoh** [airbnb/lottie-web#700]
I have a pretty simple animation running through bodymovin against a black background and I'm noticing a white bar flickering across the screen as I scroll past the section with the animation.  When I remove bodymovin from the page it is gone.  This happens with every animation I try (demos as well as my own).  It is is obviously only really noticeable on a dark background since the flicker is white.  It occurs towards the top of the screen as I'm scrolling up and the bottom as I'm scrolling down.  Any idea how I might get rid of this?

**Comment by bodymovin** [comment]
can you share the .aep or a link with the issue so I can check it?
This is usually related to .ai layers that take the whole comp size.

**Comment by bodymovin** [comment]
closing. reopen if necessary
