### ISSUE TITLE
Clear animation when its done

### ISSUE THREAD

**Issue by icebasic** [airbnb/lottie-web#701]
Hi

Im just trying out bodymovin and it works fine. But as a test i want a animation to start when i press a button and then end/clear when its done. I can start one with a button but when its done you can still see it. I have read the documentation but can figure it out. I have also tried a few of things.

Js code:
`let ani = bodymovin.loadAnimation({
container: document.getElementById('bm'),
renderer: 'svg',
loop: false,
autoplay: false,
path: 'data.json',
  })
``
 document.getElementById("btn").addEventListener("click", function() { 
    ani.play()
  });
`

**Comment by bodymovin** [comment]
you can do:
```javascript
ani.addEventListener('complete', function(){
    ani.destroy()
})
```
