### ISSUE TITLE
"Image File are not Supported" Cannot Preview Image of JSON in LottieFiles preview website

### ISSUE THREAD

**Issue by Fatinbunny2** [airbnb/lottie-web#706]
![screenshot_2017-11-02-14-20-11](https://user-images.githubusercontent.com/32445360/32363689-779abf4c-c0ab-11e7-97dc-320b074cb325.jpg)

Hello there,
As per image above, I am not only can't preview the image from website, but also in Lottie Preview app on android phone after dragging the .JSON file into it.

This is my first time using BodyMovin and also a newbie for After Effects. If I miss anything, feel free to share me some advice. Thanks!

AE file : 
[test lottie.zip](https://github.com/bodymovin/bodymovin/files/1440314/test.lottie.zip)

**Comment by bodymovin** [comment]
Hi, you haven't atached the .ai file you're using with your animation, but it's usually better to convert ai layers to shapes when using them in AE.
Right click on the layers and select Create Shapes from Vector Layers.

**Comment by Fatinbunny2** [comment]
Oh sorry. here~

[test lottie (update).zip](https://github.com/bodymovin/bodymovin/files/1444757/test.lottie.update.zip)

Ok, I'll try. Thank you!

**Comment by akhilkomath** [comment]
Hi,
I have tried the method suggested by you - using created shapes. The resulting Lottie preview is a blank white area. I have to see the layers and their respective colours in Lottie editor but not the animation. Need help ASAP. Attaching Screenshots.

![image](https://user-images.githubusercontent.com/49190076/55401966-e00a1a00-556f-11e9-84fd-e51cac19ab2b.png)

![image](https://user-images.githubusercontent.com/49190076/55402002-f4e6ad80-556f-11e9-9abd-c45b6b32c2c4.png)

**Comment by akhilkomath** [comment]
You can find the AE file here: [Sim Order Success.ae](https://drive.google.com/open?id=1P-47pW3xQQ8U2ZVVOzRawM3rQRUHQegN)

**Comment by bodymovin** [comment]
@akhilkomath If you have exported the animation with the latest player, it won't work until they update the player on their side.
They'll probably do it soon.
Have you tried exporting the demo.html to see if it works correctly?

**Comment by akhilkomath** [comment]
@bodymovin **demo.html** is working fine. But the JSON files aren't loading properly in Lottie. I have exported the animation using Bodymovin plugin version 5.5.0. Attaching screenshot for reference. So are you sure the issue's with Lottie Files' player/editor and not the JSON file rendered by Bodymovin?

<img width="1440" alt="Screen Shot 2019-04-03 at 9 59 50 AM" src="https://user-images.githubusercontent.com/49190076/55452965-81887e80-55f7-11e9-94c7-e14c60362dfc.png">

**Comment by bodymovin** [comment]
if the demo.html is working fine, then yes, I'm pretty sure.
I know they have updated the player, so you can try it out to see if it works now.
