### ISSUE TITLE
AE 2018 does not support gradient color?

### ISSUE THREAD

**Issue by wyfang** [airbnb/lottie-web#708]
AE 2018 does not support gradient color?
<img width="905" alt="2017-11-06 10 23 00" src="https://user-images.githubusercontent.com/17900420/32422759-e59fb836-c267-11e7-91c5-b91046e320b4.png">

**Tell us about your environment**
MacOS High Sierra 10.13
* **Browser and Browser Version:**
Null
* **After Effects Version:**
Adobe After Effects CC 2018(15.0.0)
**What did you do? Please explain the steps you took before you encountered the problem.**
I used a gradient color, but the project is ok before upgrading ae 2018.
**What did you expect to happen?**
Display the correct color

**Comment by bodymovin** [comment]
can you try renaming your gradient property and layer containing it?

**Comment by wyfang** [comment]
@bodymovin I tried it useless.

**Comment by bodymovin** [comment]
Can you share the .aep so I can check it out?

**Comment by wyfang** [comment]
@bodymovin Well, thanks, I use AE to create a simple circle, fill the gradient color, and output json file, help to see where the error occurred.
[Test.zip](https://github.com/bodymovin/bodymovin/files/1469839/Test.zip)

**Comment by bodymovin** [comment]
@wyfang I get the animation exported correctly.
What are your OS or AE languages?

**Comment by wyfang** [comment]
@bodymovin MacOS High Sierra 10.13.1 and Chinese, So is it not to support the Chinese version of AE?

**Comment by euppi98** [comment]
Hello, I have the same mistake. I use a color gradient, and the output is a black and white gradient.

After Effects
[https://imgur.com/i872EhD](url)

Web
[https://imgur.com/CrZKuG1](url)

**Comment by Martinhuleux** [comment]
Hi!, I have same problem .. with the last After effect version (V 15.O.O . build 180) , the gradient it's not readable JSon files. Very very complicated ! Lottie we need your reaction

**Comment by bodymovin** [comment]
@Martinhuleux did it work before?
How was your configuration when it worked?

**Comment by Martinhuleux** [comment]
My colleague and my(before) works with V14.2.0 . 198  after effect

**Comment by bodymovin** [comment]
language of your current and previous OS and AE?

**Comment by Martinhuleux** [comment]
Ok, Mac OS Sierra 10.12.6 actual. and same previous . Before I used the same version ( 14.2.0 198 ) . The problem comes from New Version After

**Comment by bodymovin** [comment]
@Martinhuleux I meant in what language is your current AE installed and what was it before?

**Comment by Martinhuleux** [comment]
Ha! French

**Comment by bodymovin** [comment]
both current and previous AE?

**Comment by Martinhuleux** [comment]
Yep

**Comment by Martinhuleux** [comment]
???

**Comment by bodymovin** [comment]
@Martinhuleux I can't reproduce the issue so it's hard to fix it.
Happy to help if you want to do a PR

**Comment by Martinhuleux** [comment]
Ohh ...

**Comment by bodymovin** [comment]
Can you try with version 5.0.1?
This might be solved now.

**Comment by Martinhuleux** [comment]
I do not understand which version are you talking about?

**Comment by zaheerprince** [comment]
bodymovin not working in AE 2018
Any solution please

**Comment by wyfang** [comment]
@bodymovin version 5.0.1 the same, I think this should be plug-in ae2018 support there is a problem. Still thank you. However, I am looking forward to fixing this problem. Because the gradient is a very important feature support.

**Comment by bibubi** [comment]
well, I have same problem! I use AE CC 2018 and bodymovin version is 5.0.1..
btw, both of my OS and AE language is Chinese

**Comment by wyfang** [comment]
@bibubi 目前只能临时将渐变的用纯色来设计，渐变色也不用删，把小眼睛关了即可。

**Comment by bibubi** [comment]
@wyfang 但是我看有人说同一个文件,在MacOS系统下,可以渐变..我现在在更新我的Macbook试试看

**Comment by alexlufa** [comment]
@wyfang 请问现在这个问题解决了吗？我之前版本不行，貌似更新到5.0.3是ok的，但现在2018 v5.0.6又出现这个问题

**Comment by alexlufa** [comment]
@wyfang  貌似找到原因了，合成的名字必须带“comp”是不是要开头还没试。用comp就正常显示了2018
v5.0.6版本

**Comment by wyfang** [comment]
@alexlufa 还有这种操作？你是怎么发现这个的？

**Comment by BingoDesinger** [comment]
@alexism 我把合成改成了「comp」还是有同样的问题。
***
macOS 10.13.2
bodymovin 5.0.6

**Comment by alexlufa** [comment]
OS 10.12.4
ae2018 英文版
bodymovin 5.0.6

我是看了作者说数值是有的，但可能索引出了问题，于是就试试改成默认的合成命名，要改project里面的那个名字哦，那个才是id，“
「comp」”这个貌似只是命名而已
我这几天试了都还行，只要不是comp，甚至后面加其他单词都会变黑白渐变


2017-12-27 18:49 GMT+08:00 BingoDesinger <notifications@github.com>:

**Comment by BingoDesinger** [comment]
@alexism alex 学习了，等会试试看！感谢了！

**Comment by wyfang** [comment]
@BingoDesinger @alexlufa 我修改合成comp也是没效果，哪里是projiect？

**Comment by BalzacV** [comment]
Did you maybe solved that?

**Comment by wyfang** [comment]
@BingoDesinger 我还是不行啊。修改了和你一样的东西，把项目也改成中文也不行。

**Comment by alexlufa** [comment]
确保这里是这个命名

2018-03-26 15:51 GMT+08:00 Player <notifications@github.com>:
