### ISSUE TITLE
Convert unsupported expressions to keyframes?

### ISSUE THREAD

**Issue by danielbayley** [airbnb/lottie-web#709]
I notice that certain expressions, like `wiggle()`, don't play nice with bodymovin…

Why not automatically convert unsupported expressions to keyframes as in `Animation > Keyframe Assistant > Convert Expression to Keyframes`?

Maybe taking that a step further… it could then delete the generated keyframes after export and re-enable the expressions (since `Convert Expression to Keyframes` disables them).

**Comment by bodymovin** [comment]
Yes, it's a possibility, but I prefer to leave that decision to the user at the moment.
Not all expressions are simple to identify if they will work.
And those that are, it might be better to use another way of animating, instead of converting to keyframes.
