### ISSUE TITLE
Document another (easy!) install option?

### ISSUE THREAD

**Issue by danielbayley** [airbnb/lottie-web#710]
So I maintain an Adobe [Homebrew] _[tap]_ [here], and recently added a _[Cask]_ for bodymovin. This makes it super easy to install with just:
~~~ sh
brew tap danielbayley/adobe
brew cask install bodymovin
~~~
@bodymovin Would you want to add this to the documented install options? Or maybe even you would rather separate the cask to it's own repo under this organization instead? Then it could be something like `brew tap bodymovin/bodymovin`…

[homebrew]: https://brew.sh
[tap]: https://docs.brew.sh/Formula-Cookbook.html
[here]: https://github.com/danielbayley/homebrew-adobe
[cask]: https://github.com/danielbayley/homebrew-adobe/blob/master/Casks/lottie.rb

**Comment by conor909** [comment]
I'v been trying to install the plugin for over an hour now.  I'm wondering why it's so hard to install, so I think this could be a good suggestion.

**Comment by gengxuelei** [comment]
@danielbayley @bodymovin 

**env：**
MacOS Mojave 10.14.6
Homebrew 2.1.9

**err msg：**
```
==> Satisfying dependencies
==> Installing Formula dependencies: exmancmd
==> Installing danielbayley/adobe/exmancmd
==> Downloading https://adobe.com/go/ExManCmdMac
==> Downloading from http://download.macromedia.com/pub/extensionmanager/ExManCmd_mac.zip
######################################################################## 100.0%
Error: An exception occurred within a child process:
  ChecksumMismatchError: SHA256 mismatch
Expected: bf092874723f1a61c7ca76db0a9f75a8a65ae805ef6568cf54c8189b6c40b507
  Actual: 7be376aec900c1b4998d41b7d5e07f51cbd84c99cc8c3e46a582ab1c0c715dfc
 Archive: /Users/lei/Library/Caches/Homebrew/downloads/8502753217f8460d1cc47feef6250080b300b84f56d35c55818b0525486d0af7--ExManCmd_mac.zip
To retry an incomplete download, remove the file above.

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
```
