### ISSUE TITLE
Can´t export json file properly

### ISSUE THREAD

**Issue by lejuane** [airbnb/lottie-web#711]
Hi, I tried to export json file and can´t play it. Tried different export options and it seems to be a problem, but i didn´t find it yet. Can you help me?
I send you AE file project and gif file that shows how json file results.
Thanks!

[Sketch Logo precomp shapes.aep.zip](https://github.com/bodymovin/bodymovin/files/1447811/Sketch.Logo.precomp.shapes.aep.zip)

![screencast 2017-10-30 at 16 45 50 1](https://user-images.githubusercontent.com/33433757/32464293-2ec47b12-c305-11e7-822e-6fe1c0f41eae.gif)

**Comment by EW001** [comment]
Did you solve this? I'm having the same problem.

**Comment by bodymovin** [comment]
@EW001 can you share a link to see how you implemented it?
