### ISSUE TITLE
AE2018 can not analyse text layer, but AE2014 can do it

### ISSUE THREAD

**Issue by alexlufa** [airbnb/lottie-web#712]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Can you share an .aep?
I've had no issues with text layers on AE2018

**Comment by alexlufa** [comment]
like that, this one is making by AE2014, and it's useful. But I use AE2018 bodymovin4.13.0 to export the json ,that it open in lottie be crash 

[Untitled Project.aep.zip](https://github.com/bodymovin/bodymovin/files/1459875/Untitled.Project.aep.zip)

**Comment by bodymovin** [comment]
Can you share the fonts?

**Comment by alexlufa** [comment]
[HYLI.ttf.zip](https://github.com/bodymovin/bodymovin/files/1464445/HYLI.ttf.zip)

**Comment by alexlufa** [comment]
hi， Whether this issue has been fixed ？

**Comment by bodymovin** [comment]
STBaoliSC-Regular still seems to be missing still
but I exported it like this and it seems to be working fine..
Are you using lottie-android or lottie-ios?

**Comment by zaheerprince** [comment]
bodymovin not working in AE 2018
Any solution please

**Comment by bodymovin** [comment]
@zaheerprince you're using an expression to set the text value.
In order to do that, you need to export a layer with all characters needed to render that layer.

**Comment by RhysyG** [comment]
@bodymovin 

Hi there,

I have tried to export all the characters needed to count from 1-10 but it still doesn't seem to work. I've tried a HIDDEN layer (with export hidden layers) and even a visible layer but it still doesn't export.

https://drive.google.com/file/d/1phzehOpdNXnAwUL3B41p4-LtA-Bwjfw5/view?usp=sharing

**Comment by bodymovin** [comment]
Hi @RhysyG , I tried setting the layer visible and it works fine.
When you say it doesn't export, what is exactly going on?

**Comment by RhysyG** [comment]
Thanks for the reply @bodymovin 

Sorry you're right, it does work. I was testing the animations on proto.io and it did nothing. Once I exported the demo  I can now see it playing.

https://drive.google.com/open?id=14RSa9xHkCab2dw2zrOZru3XEJDbdseJa

It must be something wrong with proto.io.

Also thanks for the update, after installing 5.1.10 I can export text as glyphs.

**Comment by RhysyG** [comment]
@bodymovin 

How did you test this to see if it worked?

If I upload this to https://www.lottiefiles.com/preview it doesn't seem to work.

**Comment by bodymovin** [comment]
can you share the link so I can check it out?

**Comment by RhysyG** [comment]
@bodymovin 

Thanks! Yeah sure the preview is here:
https://lottiefiles.com/share/MrwTk1
Note: You have to click pause play to get the 0 to appear

Strange thing is the download link preview works:
(you have to click pause play to get the 0 to appear)

**Comment by bodymovin** [comment]
Closing issue. Reopen if necessary.
