### ISSUE TITLE
Supported browser / fallback

### ISSUE THREAD

**Issue by fnagel** [airbnb/lottie-web#714]
Is there any information available which browsers should be supported? Any fallback if bodymovin is not able to run? 

Currently thinking about creating some simple fallback to gif based on some modernizr checks for SVG and canvas. Any more things that are needed by bodymovin to work?

Thanks for any input!

**Comment by fnagel** [comment]
@bodymovin Sorry for bothering you but are you able to give some input here? Would be highly appreciated!

**Comment by wonderment** [comment]
It's based on SVG support, so you can run those checks and caniuse.com, of course. Maybe the author has more key details but BM wouldn't be able to dictate what a browser or device can support.
