### ISSUE TITLE
json file is not correct

### ISSUE THREAD

**Issue by hdyluo** [airbnb/lottie-web#717]
<img width="941" alt="wx20171113-12445" src="https://user-images.githubusercontent.com/13846818/32710109-50bcafdc-c7fb-11e7-830f-564767f4deb0.png">

**Comment by bodymovin** [comment]
did you save your project before exporting?
Can you send a screenshot of the layer expanded up to the gradients?

**Comment by bodymovin** [comment]
this might be solved in version 5.0.1
If not feel free to reopen
