### ISSUE TITLE
animation not loaded/played using lottie on iOS

### ISSUE THREAD

**Issue by musa8i** [airbnb/lottie-web#718]
**Mac OS Sierra 10.12.5, Bodymovin 4.13.0**

* ** Adobe After Effects 2017:**

**Created a simple after effects project with a radial wipe animation. Exported the composition to json using the bodymovin plugin. The animation doesn't play in iOS app (both simulator and device), only shape appears using lottie framework**

**The animation to play when loaded with lottie**

I have attached the json file
[data1.zip](https://github.com/bodymovin/bodymovin/files/1469690/data1.zip)

**Comment by bodymovin** [comment]
Hi, radial wipe effect is not supported yet.

**Comment by musa8i** [comment]
Hello,
Thanks for the reply, :+1:  I should have closed this as I found out it wasn't supported yet and used trim paths to achieve the same effect :)
