### ISSUE TITLE
Gradient color can  not  randering

### ISSUE THREAD

**Issue by bfayangyang** [airbnb/lottie-web#719]
hi
   this problem always be here ， I creat a gradient layer ,but when I rander .it  ,it always be a  white-black one.

**Comment by bfayangyang** [comment]
I downloaded someone else with a gradient file, with my AE output json file is still black and white, I guess it may be my AE by some permissions, do not know if you can help me?

**Comment by bfayangyang** [comment]
By the way, before I saw someone asked a similar question, I also AE2017, English, Window10 operating system

**Comment by bfayangyang** [comment]
I send the same file to others.His computer is mac and he can rander it with no problem.

**Comment by wyfang** [comment]
https://github.com/airbnb/lottie-web/issues/708

**Comment by bodymovin** [comment]
Can you try with version 5.0.1?
This might be solved now.

**Comment by Attitrue** [comment]
hi,i also have the same problem. I've tried the latest version but it still doesn't work. it seems we have to wait for the update.but if there is a pressing need to use JSON to apply in a project,you can modify the JSON file directly with code/docs/json .for example,i modify the value of array"K"  in array"G" then it can be parsed by LOTTIE correctly.

**Comment by bfayangyang** [comment]
I tried the new version，but it still not work

**Comment by MadGraph** [comment]
Hey guys, I know why it's black and white !! 

I spent 2 hours playing with the json file.

which renders 
"k":[0,1,1,1,1,1,1,1]
=> positionColor1,r,g,b,positionColor2,r,g,b

I replaced that using my RGB colors:

Taking R / 255, then G / 255 etc...
I got that:
"k":[0,0.85,0.27,0.98,1,0.26,0.93,0.99]
![capture d ecran 2018-02-11 a 20 47 32](https://user-images.githubusercontent.com/8480975/36077567-d348a9d4-0f6c-11e8-81c8-5f7920f94746.png)

It worked...

=> Next step was understanding why ae/bodymovin output for my gradient was black&white

**ANSWER:**

In after effects, Go to your gradient colors and make sure you clicked RGB instead of TSL. Do a render again and you're all set. No more black and white!!

![capture d ecran 2018-02-11 a 20 41 52](https://user-images.githubusercontent.com/8480975/36077578-e02917f6-0f6c-11e8-9baa-adf3fbe684b8.png)

Hope that will help you :)

**Comment by yizihan** [comment]
@MadGraph your **ANSWER** is very helpful!

**Comment by bodymovin** [comment]
@tehfailsafe have you tried saving the project before exporting?

**Comment by tehfailsafe** [comment]
I'm not at my desk at the moment to check, but I suspect I forgot to save since I was just working on a test project... That cost me an hour or so... Jeez hahah

**Comment by BalzacV** [comment]
From our tests it sees that if you change color of the gradient of a single object than you get the blackwhite results. We didnt find a solution for changing the color of a gradient on a single object.

**Comment by MadGraph** [comment]
@tehfailsafe Otherwise you can modify it directly in the json file
That works for sure 100% of the time :)

Taking R / 255, then G / 255 etc...
I got that:
"k":[0,0.85,0.27,0.98,1,0.26,0.93,0.99]

**Comment by rifton007** [comment]
Hello everyone,
Someone can help me, I have same problem.

I want just apllied gradient ramp to a simple solid layer.
here is the output data.json
```
  "ef": [
                        {
                            "ty": 3,
                            "nm": "Start of Ramp",
                            "mn": "ADBE Ramp-0001",
                            "ix": 1,
                            "v": {
                                "a": 0,
                                "k": [
                                    960,
                                    0
                                ],
                                "ix": 1
                            }
                        },
                        {
                            "ty": 2,
                            "nm": "Start Color",
                            "mn": "ADBE Ramp-0002",
                            "ix": 2,
                            "v": {
                                "a": 0,
                                "k": [
                                    0.176470592618,
                                    0.176470592618,
                                    0.176470592618,
                                    1
                                ],
                                "ix": 2
                            }
                        },
                        {
                            "ty": 3,
                            "nm": "End of Ramp",
                            "mn": "ADBE Ramp-0003",
                            "ix": 3,
                            "v": {
                                "a": 0,
                                "k": [
                                    960,
                                    1018
                                ],
                                "ix": 3
                            }
                        },
                        {
                            "ty": 2,
                            "nm": "End Color",
                            "mn": "ADBE Ramp-0004",
                            "ix": 4,
                            "v": {
                                "a": 0,
                                "k": [
                                    1,
                                    0.298039227724,
                                    0.57647061348,
                                    1
                                ],
                                "ix": 4
                            }
                        },
                        {
                            "ty": 7,
                            "nm": "Ramp Shape",
                            "mn": "ADBE Ramp-0005",
                            "ix": 5,
                            "v": {
                                "a": 0,
                                "k": 1,
                                "ix": 5
                            }
                        },
                        {
                            "ty": 0,
                            "nm": "Ramp Scatter",
                            "mn": "ADBE Ramp-0006",
                            "ix": 6,
                            "v": {
                                "a": 0,
                                "k": 0,
                                "ix": 6
                            }
                        },
                        {
                            "ty": 0,
                            "nm": "Blend With Original",
                            "mn": "ADBE Ramp-0007",
                            "ix": 7,
                            "v": {
                                "a": 0,
                                "k": 0,
                                "ix": 7
                            }
                        },
                        {
                            "ty": 6,
                            "nm": "",
                            "mn": "ADBE Ramp-0008",
                            "ix": 8,
                            "v": 0
                        },
                        {
                            "ty": 7,
                            "nm": "GPU Rendering",
                            "mn": "ADBE Force CPU GPU",
                            "ix": 9,
                            "v": {
                                "a": 0,
                                "k": 1,
                                "ix": 9
                            }
                        }
                    ]
```

I have already tried and nothing worked:

- Save the project before render
- Change values of *k:*

Thanks for your help,

**Comment by N0t-Simon** [comment]
Hi guys, hope you'r all fine.

I can't create a gradient layer from AE. It always display a black & white gradient. 

i tried @MadGraph solution, with no results..

Does someone have an idea ?

Help is welcome haha :)

**Comment by bodymovin** [comment]
@N0t-Simon hi, can you share the .aep?

**Comment by ccchenlll** [comment]
how
