### ISSUE TITLE
goToAndStop messing up currentFrame/renderedFrame

### ISSUE THREAD

**Issue by major-m** [airbnb/lottie-web#720]
I'm trying to build a search form on a website and got this magnifying glass animation you can look at here: https://codepen.io/anon/pen/GOvKOJ

I was trying to set some initial states for the animation giving the user visual feedback wether the search bar is open or not. In other words: if it is open, the animation should stop at the final frame and otherwise should stop at the first frame. 

However I discovered, that .goToAndStop() (without .play() anywhere) is not properly working on my server while it is on the Codepen above. 

Doing…
`console.log(anim);
		anim.goToAndStop(14, 1);
		console.log(anim);`

is causing the following output:

![screenshot 2017-11-14 16 29 03](https://user-images.githubusercontent.com/33663136/32788258-047301a8-c959-11e7-8428-17138e6fd037.png)

(see currentFrame is either 0 **before** goToAndStop or -0.01 **after** goToAndStop, the latter resulting in the whole SVG to disappear on my site. 

I would be glad if anybody could help.

**Comment by bodymovin** [comment]
not sure how your implementation is on your server, but can you try waiting for the DOMLoaded event before setting the frame position?
something like: 
````javascript
anim.addEventListener('DOMLoaded', function(){anim.goToAndStop(14,true)})
````

**Comment by major-m** [comment]
Sorry for not responding earlier but I ran into some other problems after adding your suggestion to my code. But to answer your question: Yes, this solved the problem of not being able to stop my animation at a specific frame. Thank you!
