### ISSUE TITLE
Merge path support for Lottie-web?

### ISSUE THREAD

**Issue by daveobrien-EB** [airbnb/lottie-web#723]
More of a question than a bug..

Does Lottie-web support merge paths ?

**Comment by bodymovin** [comment]
it doesn't yet, unfortunately

**Comment by daveobrien-EB** [comment]
I believe it's available now for native? do you have an idea of when we might support? 
Thanks for the info

**Comment by bodymovin** [comment]
It's supported for Android. Not sure it is for iOS.
In web it's pretty complicated to support it. I'm not sure it's coming any time soon.

**Comment by daveobrien-EB** [comment]
ok thanks!

**Comment by Bijiabo** [comment]
does lottie-web support it now?

**Comment by vitpankin** [comment]
And now?!

**Comment by godhongkemangi** [comment]
Lottiefiles doesn't actually support it, but hey, no worries! You can totally make that Lottie animation work like a charm with Bodymovin. Oh, and when you're dealing with trim path animation, just make sure to set it individually, not all at once. And guess what? After waiting for a long 6 years, it's finally paying off, my friend!
