### ISSUE TITLE
5.0 ZXP installing but not appearing in extensions window

### ISSUE THREAD

**Issue by sqott** [airbnb/lottie-web#724]
**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**
15.0.0
**What did you do? Please explain the steps you took before you encountered the problem.**
Installed 5.0 ZXP
**What did you expect to happen?**
Bodymovin/Lottie extension to appear in Windows > Extensions
**What actually happened? Please include as much _relevant_ detail as possible.**
Installed 5.0 ZXP successfully through ZXP Installer - does not show up in Window > Extensions. Attempting to install 4.12.0 from Adobe Exchange gives message that a newer version of the extension is already installed, but I don't see it. 
**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Are you on a Mac?

**Comment by sqott** [comment]
Indeed, 10.12.6

**Comment by bodymovin** [comment]
can you try restarting?

**Comment by sqott** [comment]
No luck sadly

**Comment by pseudonymcp** [comment]
I have the same problem on Windows 10 Pro 64bit (1709) with After Effects 15.0.0.

**Comment by sqott** [comment]
Fixed with 5.0.3 and ZXP installer update
