### ISSUE TITLE
Export shows white outline on each object

### ISSUE THREAD

**Issue by juliesunshine** [airbnb/lottie-web#725]
Hi, I recently exported an ae animation with bodymovin to an json file. The export shows all the way an white outline on each object in my file. How do I get rid of that??

I use mac, the animation tool was after effects, i used bodymovin for export to an json file.

**Comment by bodymovin** [comment]
Hi can you share the .aep?

**Comment by juliesunshine** [comment]
Here it is: https://drive.google.com/open?id=1lZc9H1EvDScbm3s4z-eIypqxPbrXn28F

**Comment by bodymovin** [comment]
I can't find the white line.
Can you share a link where it is displaying incorrectly?

**Comment by juliesunshine** [comment]
Here's the link to the export file displaying these outlines: https://drive.google.com/open?id=1lwx4K4Zbxp7jbCXT5txCVwG61FjkCLT6

**Comment by bodymovin** [comment]
Is it possible that you have selected to export hidden layers on the bodymovin panel in the comp settings?
if you uncheck it, it should work fine

**Comment by juliesunshine** [comment]
That was great help! Thanks a lot for answering it worked out fine!

**Comment by Bananats** [comment]
Hi, I am having the same problem as Julie but the hidden layers are not selected.

**Comment by bodymovin** [comment]
@Bananats hi, can you share the .aep?

**Comment by Bananats** [comment]
@bodymovin Hey I figured it out! I was working with shape layers and didn't delete the stroke (it wasn't visible but it still was rendering) Thank you :)
