### ISSUE TITLE
Animation in Basic HTML Page not Working

### ISSUE THREAD

**Issue by tarlyo** [airbnb/lottie-web#728]
I am ultimately trying to get my animation working on Webflow, but thought I would test it out with a basic HTML page like in the YouTube demo.

For some reason, I am getting the error:
    Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at SVGRenderer.configAnimation (bodymovin.js:6)
    at AnimationItem.configAnimation (bodymovin.js:7)
    at XMLHttpRequest.s.onreadystatechange (bodymovin.js:7)
        SVGRenderer.configAnimation @ bodymovin.js:6
        AnimationItem.configAnimation @ bodymovin.js:7
        s.onreadystatechange @ bodymovin.js:7

Can you offer any support?

**Comment by bodymovin** [comment]
can you share a link?
it seems that the container element doesn't exist

**Comment by tarlyo** [comment]
I'm not sure what was wrong, but I just tried exporting the demo HTML file from After Effects and that is working very nicely. 

I was wondering if you might be able to help me add my animation to my Webflow site? I am not a JavaScript expert, nor am I very familiar with Webflow, so any help would be much appreciated!

**Comment by tarlyo** [comment]
I have been playing around with custom code in my Webflow designer as well as trying to add embed code. Nothing seems to work. Here is the code in my embed code:

```
<div id="bm" style="width: 100%; height: 100%; background: red;"></div>
<script type="text/javascript" src="http://yourjavascript.com/15615187193/data.js"></script>
<script>
    var animation = bodymovin.loadAnimation({
    container: document.getElementById('bm'),
    renderer: 'svg',
    loop: true,
    autoplay: true
    })
</script>
```

Nothing displays at all with this code. Any ideas?

**Comment by tarlyo** [comment]
Okay, now I've realized that the animation doesn't display because it has been flagged as "unsecure" because of where I am hosting my Javascript files. However, when I agree to show unsecure scripts, my animation appears like this:
<img width="1440" alt="screen shot 2017-11-18 at 6 32 14 pm" src="https://user-images.githubusercontent.com/33792332/32985730-eb6c27b4-cc8e-11e7-8e67-0ec7ce405289.png">

**Comment by bodymovin** [comment]
there seems to be missing files. Did you upload the images folder?

**Comment by tarlyo** [comment]
Thank you for your speedy responses! I seem to have finally figured it out but have one last question- how might I move my animation to the bottom of the screen? 

Right now it sits directly in the vertical middle, and I can't seem to move it. You can see what I'm talking about here: https://www.yaelhubert.com/ (please don't mind the unfinished site)

**Comment by tarlyo** [comment]
Nevermind, I got it! Sorry to bother you!

**Comment by smallpotatos** [comment]
@tarlyo 
Hi there.
I have been trying to get my bodymovin animation to work on webflow, and I'm running into a bit of a block. Looking at your website, its looking so good! Hoping that you can shed some light on the webflow integration.

The two things i'm having trouble with are:
1. how did you make the animation responsive to the browser? (my ratio stays the same as I resize and create white strips bottom and top)
2. my animation isn't looping for some reason.

Thanks in advance,
Thomas

**Comment by tarlyo** [comment]
Hi Thomas (@smallpotatos), 

Thank you for the compliment! I am not sure about how to fix your issues specifically, as my animation just seemed to magically work, but I will share the steps I took to get it to work the way it does, and hopefully that will help you!

1. I put this line in the custom code section labelled "inside head tag":
`<script src='https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.10.2/bodymovin.js'></script>`

2. I uploaded my bodymovin data.json file as a secret gist on github, copied, and changed the first part of the URL to "https://cdn.rawgit.com"

3. I created a div block with class "bodymovin" and gave it the following four "custom div attributes" (see steps 4-7): 

4. Name: `data-animation-path`, Value: [your secret gist URL, with the beginning changed to "https://cdn.rawgit.com"]

5. Name: `data-bm-renderer`, Value: `svg`

6. Name: `data-bm-loop`, Value: `true`

7. Name: `data-bm-autoplay`, Value: `true`

8. I gave these settings to the div: 
![image](https://user-images.githubusercontent.com/33792332/37605030-b86a290e-2b68-11e8-801f-f461ea9aa3f8.png)

9. And gave these settings to the div in which my bodymovin div was nested (also, my position is set to relative, with a z-index of 600):
![image](https://user-images.githubusercontent.com/33792332/37605080-d18d79c2-2b68-11e8-8a98-c819a661f807.png)

Hope this helps and best of luck! Not sure what else I can offer but please let me know if you have any more questions and I will do my best!

**Comment by AndreaG91** [comment]
Hi, I created an animation with after effect, I did the render and I obtained two files named lottie.js and data.json. I tried to make it starts in a new file html, following the instruction of the guide, but when I started in localhost the animation didn't appear. Someone could tell me the right steps that I have to follow to make it works?

![ss](https://user-images.githubusercontent.com/41064309/51799886-654b1880-2227-11e9-8179-a2a7869afee5.PNG)

**Comment by bodymovin** [comment]
@AndreaG91 hi, it seems you're not using the correct path for lottie.
go to https://cdnjs.com/libraries/bodymovin and select one of the listed players you need.
try for example with `https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.4.3/lottie.min.js`
