### ISSUE TITLE
Pre-comps not working v5.0.1

### ISSUE THREAD

**Issue by marcvs90** [airbnb/lottie-web#729]
Hi, 
thank you for your great job.
Unfortunetely precomps in my case are not working. I attach the project.
If I render what's inside "Precomp" the animation works perfectly but if I render "AAA" that contains "Precomp" nothing happens on the browser (Edge and Chrome), despite it works perfectly on the preview in bodymovin window. I've selected all the Extra Comps and other settings but nothing again.
I'm using v 5.0.1 on AE 2017.2
Thank you my friend

Marco
[Uponadream_json.zip](https://github.com/airbnb/lottie-web/files/1490887/Uponadream_json.zip)

**Comment by bodymovin** [comment]
Hi, you don't need to add Precomps as Extra Comps if they are part of the rendering tree.
I just tried your animation and it seems to work fine.
Can you share a link where it fails?
Keep in mind that if you try it locally, you need a web server for it to work.

**Comment by guaard** [comment]
Hello, I have a problem when I do the exportation. I have only a fix background ...
I think is related to my precomps. I have the version 5.3.4. 
Thank you in advance for your help !

[test.aep.zip](https://github.com/airbnb/lottie-web/files/2764299/test.aep.zip)
