### ISSUE TITLE
3D orientation glitching when going below zero value.

### ISSUE THREAD

**Issue by LukeCThompson** [airbnb/lottie-web#731]
**Tell us about your environment**
Mac OSX

* **Browser and Browser Version:**
Safari and Chrome latest vesions.

* **After Effects Version:**
AE CC2018

**What did you do? Please explain the steps you took before you encountered the problem.**
Created character model using 2.5d animation. Used 3D orientation in AE to make the head move.

**What did you expect to happen?**
Expected animation to look the same in browser as in AE.

**What actually happened? Please include as much _relevant_ detail as possible.**
The animation glitches and moves quickly all over the place. I think it's due to how AE handles a below 0 value. AE wraps 0deg back to 360deg, so animating from 10deg to -10 is actually animating from 10deg to 350deg. In the browser I think it animates the wrong way around to meet the keyframes.

**Please provide a download link to the After Effects file that demonstrates the problem.**
Link contains AE file and demo html/json files as exported.
https://ufile.io/4awhd

**Comment by bodymovin** [comment]
fixed in version 5.0.4

**Comment by LukeCThompson** [comment]
Amazing. Thank you!!!
