### ISSUE TITLE
Unnecessary  rasterization when using mask (8bit PNGs instead of vector paths)

### ISSUE THREAD

**Issue by 1GR3** [airbnb/lottie-web#732]
I've created a logotype in Illustrator, and put each letter on a separate layer. Then, I've imported it into the After Effects, and created an animated mask of each layer (no feather) to simulate letters appearing stroke by stroke.
I've got animation as expected, except for the quality, because each letter was exported as a separate 8bit PNG image and it looks very pixelated if it's not the exact size, downscaled as well.

There's no need for rasterization from the point of SVG mechanics so why didn't Bodymovin just used vector mask of vector path?

Made in Adobe After Effects CC2015 @ OS X El Capitan

**Comment by bodymovin** [comment]
Hi, .ai layers can't be exported as shapes because their vector information is not available.
In AE you need to right click on them and select "Create Shapes from Vector Layer" and it will work.

**Comment by 1GR3** [comment]
Thank you, I'll keep that in mind next time! I tried to copy masks but they're not aligned with the original layers.
