### ISSUE TITLE
Sketch2AE plugin problem

### ISSUE THREAD

**Issue by alexszyperrek** [airbnb/lottie-web#733]
Hey guys,

it seems like there is a problem using Sketch2AE Plugin by google and exporting the animation via bodymovin. Implementing it on Android & iOS is repositioning the animation (which can't be fixed/positioned correctly by developer). As I build it directly in AE it worked fine again.

AE 2017 (14.2.1)
Bodymovin 5.0.2

Cheers

**Comment by bodymovin** [comment]
I think sketch2AE creates expressions for some properties.
Can you share your .aep?

**Comment by thewaterbear** [comment]
Sketch2AE does use some expressions that can conflict with Bodymovin. The latest version (0.53) of Sketch2AE tries to fix that.
https://github.com/google/sketch2ae/commit/7796ae3a5e41f98c11b7540f51c63374f6a9e69b

**Comment by bodymovin** [comment]
@alexszyperrek are you using the latest version of Sketch2AE?

**Comment by alexszyperrek** [comment]
@bodymovin Good call. I had version 0.52 ... I updated to v0.53 now. I'll test if that works properly.

I'll attach the file with a simple pulsing animation just in order for to test as well.
[pulsing.aep.zip](https://github.com/airbnb/lottie-web/files/1502554/pulsing.aep.zip)
