### ISSUE TITLE
Play animation after some time.

### ISSUE THREAD

**Issue by rezwanferdous** [airbnb/lottie-web#735]
Hello,
I am new to this plugins, it's a wonderful plugin. i just love using it.
i'm facing a issue to make the animation start after 10 sec. Can you help me to solve this?

**Comment by bodymovin** [comment]
Hi, I'm not sure I fully understand the problem. Can you share a link to see what you're trying to accomplish?

**Comment by rezwanferdous** [comment]
i have added a animation .as usual it starts when the website loads but i want it start after 10 sec after the website load. how can i do that?

**Comment by bodymovin** [comment]
how do you add the animation?

**Comment by rezwanferdous** [comment]
It's a wordpress site which i'm developing locally,
 i have put these js code to run the animation 

```
var anim;
    var elem = document.getElementById('body')
    var animData = {
        container: elem,
        renderer: 'svg',
        loop: false,
        autoplay: true,
        rendererSettings: {
            progressiveLoad:true
        },
        path: 'data.json'
    };
    anim = bodymovin.loadAnimation(animData);

```

**Comment by bodymovin** [comment]
so a quick solution is calling bodymovin.loadAnimation inside a setTimeout function that waits for 10s.
Would that be enough?

**Comment by rezwanferdous** [comment]
yes, that will be perfect. Thank you
