### ISSUE TITLE
SVG: Add Filters which can't be added with AE per javascript

### ISSUE THREAD

**Issue by StefanKern** [airbnb/lottie-web#736]
Is there a possibility to add Filters, like [dropshadow ](https://stackoverflow.com/a/6094674) per javascript after the animation is loaded. The reason is, that a drop shadow  filter can't be created with After effects, so it must be added by hand.
I intended to do this, by adding Classes to the element, which should have the drop shadow filter and then add the filter to the elements. However I didn't find any possibility to do this.

**Comment by bodymovin** [comment]
The drop shadow effect is supported from AE.
But as a general question for other effects, I'm not sure if applying CSS filter will work for all cases.
But you could add filters to the svg element and add a "filter" attribute via javascript to a layer that points to that specific filter.
