### ISSUE TITLE
Does Bodymovin Export works with After Effects Template with Expressions? .json file is like 13MB big and doesn't play

### ISSUE THREAD

**Issue by armiaka** [airbnb/lottie-web#738]
Hi, 

I just tried to export a Animation, which is based on an After Effects Template. 
The Template is packed with Expressions and my Animation is built by multiple compositions.

After waiting for 10 minutes to export the .json file, I tried the official Bodymovin Preview Tool to test the animation, but it didn't worked. 
I seriously don't know where the problem is, I tried everything.

I am using After Effects CC 2018 and working on a MacBook Pro.

Would be nice, if I could send you the .ae file. 

Thanks in advance!!!

**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, it depends on what features the template is using.
If you want, you can send me the .aep and I will check it out

**Comment by armiaka** [comment]
Hi and thank you for your quick answer!!
How do you want me to send it over to you? Wetransfer?

**Comment by bodymovin** [comment]
sure

**Comment by armiaka** [comment]
then I need your email, buddy :)

**Comment by armiaka** [comment]
https://we.tl/2IFqBb8vp8

**Comment by armiaka** [comment]
Hi, dient find a solution hm? :(

**Comment by bodymovin** [comment]
Hi, unfortunately the puppet pin effect is not supported.

**Comment by armiaka** [comment]
can i do something to make it work?

**Comment by bodymovin** [comment]
I don't think you can.
That effect seems heavily used throughout the animation.

**Comment by armiaka** [comment]
thank you very much for your help!

**Comment by lycheekatory** [comment]
Please help me !  create motion file in after effect cc 2017 from the design file Ai. But when exporting the .json file,  animation demo file .html5 play wrong with me creating key animation in AE. File . json faulty.
Please help me fix this. I use the windows operating system.
Thanks bro...
