### ISSUE TITLE
Gradient colors not exporting in Lottie

### ISSUE THREAD

**Issue by tslil1230** [airbnb/lottie-web#739]
Hello,
I know it had been asked before but it's just not working
I'm trying to export an animation with gradient and in Lottie preview I see it in black&white.
I saved my project before exporting but it's still b&w.
I'm using the latest version of bodymovin

Please help me!

**Comment by bibubi** [comment]
i have the same problem

**Comment by bodymovin** [comment]
hi, a couple of questions: 
what version of bodymovin are you using?
and is AE in English or another language?

**Comment by bibubi** [comment]
@bodymovin I'm using bodymovin 5.0.3 and AE in Chinese.

**Comment by bodymovin** [comment]
@bibubi I think there's a problem with layers and shape properties named in Chinese.
I don't know yet how to fix it.
Can you try naming your comp, the layer with the gradient and the inner content with latin characters and see if it works?

**Comment by bibubi** [comment]
@bodymovin I try it, but problem is still here

**Comment by bodymovin** [comment]
@bibubi can you share a screenshot of the gradient layer tree expanded?

**Comment by bibubi** [comment]
![qq 20171130094106](https://user-images.githubusercontent.com/18078927/33408656-a2a10450-d5b2-11e7-9ceb-fd2a4a8d7bd4.png)

**Comment by bodymovin** [comment]
@bibubi which one is the gradient info?

**Comment by bibubi** [comment]
![qq 20171130094654](https://user-images.githubusercontent.com/18078927/33408830-6bc205d2-d5b3-11e7-9298-0e21de0b09c9.png)
@bodymovin layer b

**Comment by bodymovin** [comment]
@bibubi I'm out of ideas. If you can share the .aep, I'll see if it exports fine here.

**Comment by bibubi** [comment]
[test.zip](https://github.com/airbnb/lottie-web/files/1516270/test.zip)
@bodymovin here is my .aep

**Comment by tslil1230** [comment]
hello everyone!
thank you for all the answers, the problem is solved!!
Have a nice day :)

**Comment by bibubi** [comment]
@tslil1230 Hello, could you tell me how to solve this problem? plz~

**Comment by sueLan** [comment]
@tslil1230 hi,  I'm trying to export an animation with gradient and in Lottie preview I see it in black&white.  Could you tell me how to solve this problem?

**Comment by bodymovin** [comment]
@bibubi I've renamed the gradient tree and it worked fine.
My guess is that since you can't rename the "Content" node it is making the traversing of the tree to fail.
I'll work on it this weekend to try to skip that node or find a way to support non common characters.

**Comment by bibubi** [comment]
@bodymovin i try it again, but it does work. could you share the .ape?

**Comment by sueLan** [comment]
It seem there is some bug in bodymovin v5.0.3 ..  One aep , Diffrent json from v5.0.0 to v5.0.3


![image](https://user-images.githubusercontent.com/7471672/33514742-3ae5aa3a-d794-11e7-8fb9-6b5a0e1e06dc.png)

![image](https://user-images.githubusercontent.com/7471672/33514745-4302ea52-d794-11e7-963f-59f4f30f87f3.png)

**Comment by bodymovin** [comment]
@sueLan Yes, it's the same issue. Since the plugin doesn't find the actual gradient values, it defaults to a B&W gradient.

**Comment by sueLan** [comment]
Hi ~   This bug  still exits  in  bodymovin v5.0.4 .

**Comment by alexlufa** [comment]
maybe i knowed it, the comp's name must be"comp"
@sueLan @bodymovin

**Comment by sueLan** [comment]
![image](https://user-images.githubusercontent.com/7471672/36578659-a232e0e0-1899-11e8-9c40-e646d099a753.png)

if gradStrokeIndex === -1 , gradFillIndex === x,  then (gradientIndex > limitIndex) is true . is it right here to output default  value  as (0,1,1,1) (1,0,0,0) ?

**Comment by BalzacV** [comment]
Hi guys. We have same problem here. Fill object with linear and radial gradient. Anyone solved it? Is it really version of bodymovin? Thanks!

@bodymovin @sueLan

**Comment by sueLan** [comment]
1. rename a unique name for any comp , any layer in English 
2. control + s to save project
3. export JSON file 

@BalzacV  It works for me.

**Comment by flickator** [comment]
Hi there, I have a gradient stroke that is export black and white. What do i need to rename? (definitely have saved the file)

**Comment by flickator** [comment]
FYI for others: found my fix, preview in bodymovin is black and white, but JSON file renders the gradient IRL.

**Comment by sueLan** [comment]
Each layer should have a unique name.

**Comment by xyonko** [comment]
> Each layer should have a unique name.
yes you need to rename your layer or comp and render then preview it worked thank you so much

**Comment by nodegin** [comment]
@sueLan thanks, turns out the project must be saved first
