### ISSUE TITLE
Export come out black, bitmap and ai layer

### ISSUE THREAD

**Issue by hoangng102** [airbnb/lottie-web#740]
Hi!

I cannot export in correct color. im using ae 2018. i remember that i can export normally on ae 2017 (including bitmap + ai layer) but can not do after upgrade to ae 2018.
real color: [https://i.imgur.com/t9VIMQN.png](url)
![image](https://user-images.githubusercontent.com/8787664/33396169-508f8516-d57a-11e7-8646-ab29da462a9b.png)

preview: [https://i.imgur.com/KX7gDIE.png](url) 
![image](https://user-images.githubusercontent.com/8787664/33396193-6080694a-d57a-11e7-9099-737bdbb41ecf.png)

the manigfy was converted to shape (it works well) but can do that for whole (because  i use pattern for some elements) so i tried to export to bitmap.
also attach the aep file
[Full Animation folder.zip](https://github.com/airbnb/lottie-web/files/1515340/Full.Animation.folder.zip)

Thanks :)

**Comment by bodymovin** [comment]
Hi, did this same animation work fine in AE 2017, or was it another one?
I don't know why it looks like this.
Can you replace the exported pngs with your layers exported from ai?

**Comment by hoangng102** [comment]
Hi, have not did on ae 2017 yet, ill try.
tried to replace the exported pngs and i works: 
![image](https://user-images.githubusercontent.com/8787664/33415456-4609f49c-d5c9-11e7-8aa7-e35a1822104f.png)

but the issue is the exported png have a black overlay

**Comment by AG013** [comment]
Same issue!!! Help

**Comment by bodymovin** [comment]
@AG013 Hi, can you share the .aep?
