### ISSUE TITLE
Responsive final position of SVG 

### ISSUE THREAD

**Issue by christopherjnewman** [airbnb/lottie-web#741]
I have an SVG animation with multiple shapes that start out in the center of the browser and move out to the left and right edges of the browser window. 

This is the MOV from the AE project:
https://www.dropbox.com/s/w4z3gqne2lnfysh/MR-Clients-BM-v01.mov?dl=0

Is it possible to use media queries to change only the final position of the shapes without changing their position during the animation?

I don't think it's possible with just CSS, but this was my attempt:

#bodymovin > svg > g > g:nth-child(1) {
     transform: matrix(1,0,0,1,0,0);
}

@media (max-width: 1023px) {
     #bodymovin > svg > g > g:nth-child(1) {
     transform: matrix(1,0,0,1,500,0);
     }
}

This works great on the final position, but it changes the first position of the SVG. 

Any guidance would be greatly appreciated! Thanks!

**Comment by bodymovin** [comment]
Hi, unfortunately it is not possible.
Are you looking for a way to dynamically control the final position of an interpolation?
