### ISSUE TITLE
How does "Split" work?

### ISSUE THREAD

**Issue by zhengs** [airbnb/lottie-web#743]
Can someone explain how the "Split" setting works? I tried enabling it and setting the every X seconds value to 2. Suppose my animation is 8 seconds long, should I expect to have 4 (i.e. 8/2 = 4) data.json files exported? But I always see just one file exported.

**Comment by bodymovin** [comment]
Split won't break a single layer into multiple files. 
It will look for layers in the main comp that start after X seconds in the timeline and store them in separate json files.
So if you set X to 2: all layers that start between 0 and 2 will be in data.json
layers between 2 and 4 in data_0.json
layers between 4 and 6 in data_1.json
layers between 6 and 8 in data_2.json

**Comment by zhengs** [comment]
I see. Thanks, @bodymovin !

**Comment by Denis-Frolov** [comment]
Nope, doing exactly what  @bodymovin is saying still just one data.json file (((((((.

Given: timeline 6 seconds, 10 layers altogether.  
Top 5 - have key frames within first 3 (0-3) seconds. Start at 0 end at 2.5 seconds.
Bottom 5 - have key frames within last 3 (3-6) seconds accordingly. Start at 3.5 end at 6 seconds.

Tried cutting layers precisely at 3 seconds mark, same thing, just one file.

Any magic trick I am missing?

**Comment by bodymovin** [comment]
@Denis-Frolov can you share the .aep so I can take a look?
Make sure the layers start after the 3s, not just their keyframes.

**Comment by AVTPJ** [comment]
Does lottie-web somehow automatically treat each section as part of the same animation (reference only one file to load) or do you have to deal with them separately via code?
