### ISSUE TITLE
Lottie Animation Lags

### ISSUE THREAD

**Issue by Dilany** [airbnb/lottie-web#744]
Hi,
I ve made an animation only from shapes in after effects and exported the json file with bodymovin. Our developers implemented it for IOS and Android. But the animation lags in both platforms. What might be the reason?

Note: I didnt use any unsuported effects. In after effects I have 3 shapes and 2 masks and thats it. I attached the json file in a zip folder. 
[chekmark_2.zip](https://github.com/airbnb/lottie-web/files/1521427/chekmark_2.zip)

Hope to hear from you soon.

Best

**Comment by bodymovin** [comment]
@Dilany Hi, can you create the issue on the Android or iOS repo so they can follow it?

**Comment by Dilany** [comment]
Yes we can do that. Let me return you when we have it.

**Comment by Dilany** [comment]
Hi we have another problem, I use masks in order to have the fill color in corret placement and it is subtract funtion on mask. You can see it on the aep. But when our developers put the code it is acting like there is not mask on it on both platforms. Meaning if i d delete all the masks it d exactly look like the test.mp4 but on your website it says that lottie supports mask subtract. Can you help us what might be the problem here. 
Best
[test.zip](https://github.com/airbnb/lottie-web/files/1530686/test.zip)

**Comment by brienhopkins** [comment]
@Dilany What was the problem with the mask? I'm running into a similar lag issue. I have a couple masks in my animation.

**Comment by Dilany** [comment]
Funny but it was because the composition was smaller than the boundaries of the mask. 

Also make the masks on different layers. In some cases I faced with a problem where there were masks on top of eachother and that created the problem. 

It seems that there is no regular explanation with mask errors. 
Good luck
