### ISSUE TITLE
Rendering issues in Chrome, Firefox and Edge on windows

### ISSUE THREAD

**Issue by anfalk462** [airbnb/lottie-web#745]
When viewing the exported file on the web, i am getting mystery lines that are emitting to random center/anchor points. It only happens on browsers on windows machines, not on Mac.
Is this a browser issue specific to Windows machines? is there a work around for this?

![thumbnail_image003](https://user-images.githubusercontent.com/28629191/33499490-ec3e9c80-d689-11e7-98aa-0c5df120f27f.jpg)
![thumbnail_image004](https://user-images.githubusercontent.com/28629191/33499491-ec577e3a-d689-11e7-9089-2e6106125fed.jpg)

**Comment by bodymovin** [comment]
hi, can you share the exported .json and the .aep?

**Comment by anfalk462** [comment]
do you have somewhere i can upload them privately? NDA and whatnot, i cant share them publicly.

**Comment by bodymovin** [comment]
can you email it to me?
hernantorrisi[at]gmail.com

**Comment by anfalk462** [comment]
also, the issue gets worse as you scale down the browser window


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by bodymovin** [comment]
Hi, I'm trying it on Windows Chrome and it's working fine.
A week ago someone reported a bug to Chrome very similar to this. It seems to happen on certain hardware + windows combos.
Can you confirm if the issue is visible on all browsers in that computer like IE and Firefox?
Also, can you disable Hardware Acceleration in Chrome and see if the issue is fixed?

**Comment by bodymovin** [comment]
this is the chrome issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=784310
and this is an animation that also failed in chrome:
https://codepen.io/chrisgannon/pen/6c932fda8d8fca3e253b655033d86645
(the antennae should be circles if it works)

**Comment by anfalk462** [comment]
i get the same issues, yet not as drastic in Firefox and Edge. But they work fine on Chrome for Mac, Firefox for Mac and Safari. WE also tested on Some other Windows machines and cant reproduce the bugs, wondering if it has something to do with the HP work stations we have tested it on?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by Spirik** [comment]
Upgrading to Chrome 63 fixed my issues ("bleeding polygons"), however test case Worm from the link above still has weird diagonal lines (that disappear once hardware acceleration is turned off).

**Comment by Spirik** [comment]
BTW, Android versions of Chrome prior v63 were also experiencing this issue.
