### ISSUE TITLE
svg text-anchor

### ISSUE THREAD

**Issue by Adam-Burke** [airbnb/lottie-web#746]
Is it possible to export the text-anchor for use with the svg renderer? That would be extremely useful for me.

**Comment by bodymovin** [comment]
hi, what do you mean text-anchor? which property would that be?

**Comment by Adam-Burke** [comment]
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor

**Comment by bodymovin** [comment]
The text-anchor is supported by the plugin.
Is there something that isn't working?

**Comment by Adam-Burke** [comment]
Oh I think maybe I'm just confused. I couldn't see the attribute on the produced svg. When dynamically updating text using updateTextDocumentData, if the text is anchored to the right/end in ae will that be preserved if the text char count changes on the update?

**Comment by bodymovin** [comment]
yes, it will

**Comment by Adam-Burke** [comment]
very cool. Thank you
