### ISSUE TITLE
Unable to execute script at line 5375

### ISSUE THREAD

**Issue by Xentropics** [airbnb/lottie-web#750]
**Tell us about your environment**

Windows 10 Pro
Version 1703
Build 15063.726

* **Browser and Browser Version:**

Chrome Version 62.0.3202.94 (Official Build) (64-bit)

* **After Effects Version:**

CC 2018 (15.0.0, build 180)

**What did you do? Please explain the steps you took before you encountered the problem.**

- Opened project including AI artwork and sound
- Opened Bodymovin panel
- Selected output dir
- Tried different settings for main comp
- Hit render button

**What did you expect to happen?**

- Everything rendering OK

**What actually happened? Please include as much _relevant_ detail as possible.**

- Everything looked smoothly
- Loads of stuff rendering
- Then one layer stops at 50%
- After a while: when I click the panel a message box appears:

![20171204_microsoft store_000030](https://user-images.githubusercontent.com/34250337/33574084-2f694658-d938-11e7-9048-e0219f415ce5.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**

- Well, it's not my file and I can't reproduce this. Do you have any idea?

**Comment by bodymovin** [comment]
hi, can you share the .aep?
