### ISSUE TITLE
Mask Substract wont work even though it is supported 

### ISSUE THREAD

**Issue by Dilany** [airbnb/lottie-web#751]
Hi we have a problem, I use masks in order to have the fill color in corret placement in ae and it is subtract funtion on mask. You can see it on the aep. But when our developers put the code it is acting like there is no mask on it on both platforms. Meaning if i d delete all the masks it d exactly look like the test.mp4 (attached)but on your website it says that lottie supports mask subtract. Can you help us what might be the problem here.
Best
[test.zip](https://github.com/airbnb/lottie-web/files/1530938/test.zip)

**Comment by bodymovin** [comment]
Hi, can you create an issue in the lottie-android repository?
https://github.com/airbnb/lottie-android

**Comment by Dilany** [comment]
Sorry we are not allowed to share code but we have this code (below) in the layout file and the lottie version we are using is 2.3.1 the latest from a day ago. So it displays the image right but now it wont play the animation.  (so basically the problem with its displaying image wrong is fixed but now the animation wont start) and only on android. It displays correct and plays correct on IOS. 

<com.airbnb.lottie.LottieAnimationView
    android:id="@+id/animationView"
    android:layout_width="200dp"
    android:layout_height="300dp"
    app:lottie_autoPlay="false"
    android:layout_gravity="center"
    app:lottie_fileName="animation/reset_ha_detailed.json"
    android:layout_marginTop="48dp"
    app:lottie_loop="true" />
 
animationView.playAnimation();      (This line is used in Java to start the animation)

**Comment by bodymovin** [comment]
This is the repository for the web player. Can you create the issue in the android player repository?They'll be more helpful than me.  
https://github.com/airbnb/lottie-android

**Comment by Dilany** [comment]
Sure I will thank you

**Comment by itslenny** [comment]
This issue seems to be a problem on web too. I've got an animation using a subtract mask that isn't working in the web / canvas player.
