### ISSUE TITLE
After Effects Joystick plugin.

### ISSUE THREAD

**Issue by Kamieniu** [airbnb/lottie-web#753]
**Tell us about your environment**
OS: Linux Ubuntu

* **Browser and Browser Version:**
Chrome  62.0.3202.62
* **After Effects Version:**
15.0.0 Build 180
**What did you do? Please explain the steps you took before you encountered the problem.**
1. Created an animation.
2. Injected Joystick plugin into my project.
3. Added animation through Joystick plugin.
4. Exported project into json file.
**What did you expect to happen?**
I wanted to animation move.
**What actually happened? Please include as much _relevant_ detail as possible.**
I occured an error: 

VM122619:5 Uncaught TypeError: contrl is not a function
    at joystick (eval at initiateExpression )

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://we.tl/jza6o6OBqY

**Here is a rendered / exported json
https://we.tl/PktYcqU4DL

I guess there is a problem with exporting JoyStick animation into simply KeyFrames

**Comment by bodymovin** [comment]
Hi, you need to include guided layers as part of the export.
Go to the comp settings gear in the AE extension and select "Guided"
