### ISSUE TITLE
Effects can't be rendered in .json ?

### ISSUE THREAD

**Issue by Niloalexandre** [airbnb/lottie-web#755]
Hello,

I'm actually working on a project and using bodymovin for a week.
This plug in has been a life saver so far, thanks a lot to the dev team !

I'm using After Effects CC 2017 and sadly, i've encountered a problem !
I've been using effects on my shapes and realized they don't render well in .json

For the most part, I've managed to find a solution but on this one i'm totally in the black.
I want to make a radio viewer for an alarm clock, pretty simple :

<img width="556" alt="capture d ecran 2017-12-08 a 17 40 04" src="https://user-images.githubusercontent.com/34301983/33775735-96e40d18-dc3f-11e7-85b6-80d96ef11606.png">

Sadly, when i render it in Bodymovin, this appears :

<img width="389" alt="capture d ecran 2017-12-08 a 17 40 34" src="https://user-images.githubusercontent.com/34301983/33775756-a4ee9518-dc3f-11e7-9916-42790474d7a8.png">

The background is not a problem, it's the Equalizer that bothers me.
Is there a way to export it in .json ?

For now, it's just a black solid, with a mask and an "Audio Spectrum" effect applied on it.

Thanks a lot !

--

Sorry for my approximative English !

**Comment by bodymovin** [comment]
Hi, if the layer is linked to an Audio layer via expressions, I'm afraid it's not going to work.
Audio layers and analyzing audio data are not supported.
Perhaps if you can use an external library that leverages that part on the browser side, you might update slider values on the animation which would be read by the layer's expression.

**Comment by Niloalexandre** [comment]
Thanks a lot, that's very helpful !

**Comment by bhram** [comment]
do you solve this issue ? i relay need the solve

**Comment by seanmpm** [comment]
Is there a way to bake or flatten an audio spectrum to a way that AE can export to body moving?

**Comment by seanmpm** [comment]
I found a solution to this : You can auto-trace your spectrum animation and export that to bodymovin. 

This takes a little time but is easier than any other alternative.
