### ISSUE TITLE
why the shapes does not show correct on json file ?

### ISSUE THREAD

**Issue by rezapordel** [airbnb/lottie-web#756]
**I import vector files  as "ai" format to after effect,then "create shape from vector layers" and render by bodymovin plugin but show the file like this picture,whats rong?**

![photo_2017-12-10_12-52-44](https://user-images.githubusercontent.com/34413210/33803736-01fe5cbc-ddac-11e7-99c6-432d110baf39.jpg)

**my design is this picture:**
![page21](https://user-images.githubusercontent.com/34413210/33803732-e0eef1a8-ddab-11e7-8f18-4645631bcf90.jpg)

**Comment by bodymovin** [comment]
Hi, when converting .ai layers to shapes, AE sometimes adds an extra square shape and a merge path element.
Try deleting those merge paths and square shapes.

**Comment by rezapordel** [comment]
Hi,Thanks,how can i delet this path and square shapes,dont show in AE

![screenshot 105](https://user-images.githubusercontent.com/34413210/33819014-5ee241d0-de5d-11e7-856b-1b5fda92302d.png)
