### ISSUE TITLE
how to make the final width equal to the exact width of the animation

### ISSUE THREAD

**Issue by ctf0** [airbnb/lottie-web#757]
for example 
https://www.lottiefiles.com/61-octopus

the animation it self is **220** wide, while the svg is **800x600**, this makes it very hard to reason about if we want to make the animation responsive to different screen sizes, specially if we have some text anywhere near the animation.

is there a way to achieve that through the api ? or maybe editing the json file directly ?

**Comment by bodymovin** [comment]
It's complicated to change the composition's size because all property values are relative to the original size.
The easiest way I can think of is to change the viewBox and preserveAspectRatio values after the animation is loaded.

**Comment by ctf0** [comment]
is there a formula to do that ? maybe a link to some guide that describe the process ?

atm a very hacky way would be resize the wrapper div with overflow hidden and scale the svg, but will fail big time if you have a text that needs to align with the animation.

**Comment by bodymovin** [comment]
I don't think there's a formula. It really depends on what you're looking for and the context of the animation.
I'd suggest that you try it to see if it fits your needs.

**Comment by ctf0** [comment]
okay, np, maybe u can tell me how would u achieve that with the above example so i can use it as a guide ?

**Comment by bodymovin** [comment]
What are you trying to achieve in the above example? do you have a more precise case somewhere to check out?

**Comment by ctf0** [comment]
this is the current with most of the examples on lottie, the animation is `800x600`

![1](https://user-images.githubusercontent.com/7388088/33809724-f97b3418-de03-11e7-9c74-e64bd1b365d9.jpg)

this is the actually size of the animation which is what am trying to achieve instead of the above image

![2](https://user-images.githubusercontent.com/7388088/33809725-fab94b30-de03-11e7-92eb-05452e52e0a7.jpg)

**Comment by bodymovin** [comment]
in the console set the svg parent's width to 220px;
and change the viewBox to "290 0 220 600"

**Comment by ctf0** [comment]
perfect, last questions

- is there a way to change the viewBox through body movin ?

**Comment by bodymovin** [comment]
no, there is not at the moment

**Comment by ctf0** [comment]
😞 , okay np thanx for all your help, appreciated 🏆
