### ISSUE TITLE
ActionScript error 

### ISSUE THREAD

**Issue by abnerCrack** [airbnb/lottie-web#758]
hey ! I have an animation exports in HTML using Bodymovin, tried to export and it gives the follow error 

![image](https://user-images.githubusercontent.com/8336662/33814519-ac3e4f66-de65-11e7-9422-94c0599e4ff2.png)
[export.aep.zip](https://github.com/airbnb/lottie-web/files/1546447/export.aep.zip)

**Comment by bodymovin** [comment]
There seems to be some layers missing in the export.
Make sure you don't have hidden layers that are used by expressions.

**Comment by abnerCrack** [comment]
ie delete the hidden layers, but get an new error
![image](https://user-images.githubusercontent.com/8336662/33815021-452c9144-de69-11e7-974b-21c00cc18956.png)

**Comment by bodymovin** [comment]
you don't have to delete them. you should include them if expressions are pointing to them.

**Comment by abnerCrack** [comment]
Is there any template for me to download?  Let me refer to this

**Comment by bodymovin** [comment]
sorry, not sure I understand the question
