### ISSUE TITLE
Trapcode not support?

### ISSUE THREAD

**Issue by smallma** [airbnb/lottie-web#759]
**Tell us about your environment**
MacOS

* **Browser and Browser Version:**
Chrome 62

* **After Effects Version:**
CC 2018 w/ trapcode

**What did you do? Please explain the steps you took before you encountered the problem.**
Try to draw a line follow path to move by trapcode plugin, but show nothing with bodymovin on website.

**What did you expect to happen?**
Bodymovin support it for move possibility.

**What actually happened? Please include as much _relevant_ detail as possible.**
Show nothing on web with bodymovin.

**Comment by bodymovin** [comment]
hi, unfortunately trapcode is not supported. Not many rasterized effects are.
here's a list of the current supported ones with the svg renderer
https://github.com/airbnb/lottie-web/wiki/Effects

**Comment by spipergoldberg** [comment]
Hi, is trapcode still not supported? If not, are there any similar effects that are?

**Comment by bodymovin** [comment]
@spipergoldberg unfortunately there are not at the moment

**Comment by eddienubes** [comment]
Sorry for brining up the old thread, but is it still not supported? It's been about 5 years..
