### ISSUE TITLE
updateDocumentData doesn't handle screen scale correctly

### ISSUE THREAD

**Issue by Adam-Burke** [airbnb/lottie-web#760]
**Tell us about your environment**
Mac and bodymovin 5.03, svg renderer
 
* **Browser and Browser Version:**
chrome 62

* **After Effects Version:**
15

**What did you do? Please explain the steps you took before you encountered the problem.**
updateDocumentData whilst the browser was scaled < 100%

**What did you expect to happen?**
svg text should be update with the same spacing as when screen is at 100%

**What actually happened? Please include as much _relevant_ detail as possible.**
100% scale of browser tab
![screen shot 2017-12-12 at 1 18 30 am](https://user-images.githubusercontent.com/11741126/33835603-1ef97498-dedb-11e7-98af-47bb46ddd7a1.png)

50% scale of browser tab
![screen shot 2017-12-12 at 1 23 25 am](https://user-images.githubusercontent.com/11741126/33835741-8c2c05a8-dedb-11e7-9dcd-62e64e007875.png)

**Please provide a download link to the After Effects file that demonstrates the problem.**
Seems unnecessary but can be included if requested

**Comment by bodymovin** [comment]
I don't think it's related to the screen size. Probably some font data needed.
Can you share a reduced json with the issue?

**Comment by Adam-Burke** [comment]
Yeah I think you are correct. Here is a small example. But I think it only happens when using updateDocumentData. I can't quite tell tbh.

[bug.zip](https://github.com/airbnb/lottie-web/files/1548496/bug.zip)

**Comment by bodymovin** [comment]
I've just tried it and it seems to update fine.
Do you have a link I can check?

**Comment by Adam-Burke** [comment]
I'm not sure if you can get anything out of this link but at least it shows the issue. Let me know if I can produce anything easier. https://goofy-archimedes-ffcf8f.netlify.com/.

AE views:
![screen shot 2017-12-12 at 6 00 48 pm](https://user-images.githubusercontent.com/11741126/33871409-8a7a521a-df66-11e7-9656-7c57404a35b1.png)

![screen shot 2017-12-12 at 6 02 53 pm](https://user-images.githubusercontent.com/11741126/33871465-b836c5da-df66-11e7-9006-1c7b6a593e59.png)

Now it appears only all the un updated text layers are spaced incorrectly.

**Comment by bodymovin** [comment]
Just to confirm: when you say the un updated, you mean on those that you haven't called "updateDocumentData" on?

**Comment by Adam-Burke** [comment]
Yep that's right. I think it's a font issue with them not loading until after initial render. Sorry I confused myself, I thought I was bundling my font files, but I wasn't.
