### ISSUE TITLE
Wordpress

### ISSUE THREAD

**Issue by hjundaj** [airbnb/lottie-web#761]
Hello.
I am running website based on wordpress.

Came across your project and wanted to implement but have major difficulties. 

It is piece a cake to create HTMP website like http://hjundaj.com/bodymovin/index.html

But I have no idea how to add bodymovin into wordpress post.
I added couple of lines into global css

I am trying to add into post those 3 lines

<div id="bm"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.13.0/bodymovin.js" type="text/javascript"></script>
<script src="http://hjundaj.com/bodymovin/animator.js" type="text/javascript"></script>

I called index.js as animator.js ( easier for me to manage all names)

and if I do have those lines in HTML file all works fine but when those 3 lines are in post in wordpress nothing happens. 
http://hjundaj.com/mods/mod-installation-world_of_tanks

For test pourpouses I added them into that post. and I also tried to use RAW HTML plugin. No joy.  Is there any chance for help?

Regards.

**Comment by wonderment** [comment]
Hey there.

To be fair, this isn't a Bodymovin issue. You'd want to look at enqueuing Javascript in WP.

If it doesn't work, it's either queuing it up in WP, your HTML syntax or check the console log.
