### ISSUE TITLE
Export issue, unable to execute script at line 215

### ISSUE THREAD

**Issue by hellojoey** [airbnb/lottie-web#763]
**Tell us about your environment**

* **Browser and Browser Version:**Chrome
* **After Effects Version:**CC 2017

**What did you do? Please explain the steps you took before you encountered the problem.**
Tried to export a character animation, selected destination and picked hidden file and demo settings for render. Then hit render, render stalls and error comes up with unable to execute script at line 215. 
**What did you expect to happen?**
It to render out.
**What actually happened? Please include as much _relevant_ detail as possible.**
ender stalls and error comes up with unable to execute script at line 215.
**Please provide a download link to the After Effects file that demonstrates the problem.**

[BERT_ANIMATION copy.aep.zip](https://github.com/airbnb/lottie-web/files/1554186/BERT_ANIMATION.copy.aep.zip)

Any help would be amazing! Great plugin though.

**Comment by bodymovin** [comment]
This should be fixed in the latest version 5.0.6
