### ISSUE TITLE
Suggestions for responsive PNG usage

### ISSUE THREAD

**Issue by wonderment** [airbnb/lottie-web#767]
Hello, @bodymovin !
 
Firstly, SVG animation with Bodymovin from After Effects to a web page is dreamy. Thank you for that.

That being said, when SVGs aren't available and PNGs are the back-up, what are your suggestions for adding/optimizing/delivering non-vector content for the responsive web?

In raster-based images, we can use srcset, @2x and other means but is this handled by Bodymovin in any shape or form?

My approach is to use SVG animation via BM but for scenarios where it just isn't possible (e.g. 3D animation), I would like to interweave the sequenced PNGs into the final output with reliable responsive web support.

I _did_ try everything under the sun to prevent resorting to PNGs including tracing in Illustrator to convert to a shape layer in AE but it just isn't practical for advanced objects.

Do you have any tips, pointers, suggestions, thoughts?

Thank you!

**Comment by bodymovin** [comment]
not sure if bodymovin is the right tool for that. Would you be exporting an AE animation with a sequence of images as the source?

**Comment by wonderment** [comment]
Yes, basically, it's a series of frames which aren't able to be 'vectorized' due to the complexity. They are exported out as PNGs and imported as separate PNG layers that are then sequenced via the keyframe assistant.

It's somewhat of a hybrid using SVG rendering for the majority to keep the file size down but also interweaving images when necessary.

My uncertainty is whether I can properly use scaled down hi-res PNGs for the sake of larger device format delivery -- e.g. HD, 4K monitors, etc. -- as well as if there is already handling by Bodymovin for something such as this.

**Comment by bodymovin** [comment]
if you can identify the files you want to serve with javascript, you can pass a different asset path for each case when you load the animation by using the "assetsPath" param of the config object.

**Comment by wonderment** [comment]
The assets path param is the ticket. I haven't tested but being able to potentially serve up device friendly raster graphics is the best we can do for right now.

Thanks for taking the time to reply and keep up the great work!
