### ISSUE TITLE
[URGENT] Bodymovin doesnt work for me><

### ISSUE THREAD

**Issue by billycheuk93** [airbnb/lottie-web#768]
I would like to ask 
1. if bodymovin supports effects like CC page turn 
2. if I insert a mp3 as the background music in after effect , i cant hear any sounds after exported as html.

plz help><

**Comment by therealsalih** [comment]
effects like CC page turn arent supported
Also audio isn't supported

Here is a list of supported features
http://airbnb.io/lottie/supported-features.html
