### ISSUE TITLE
Bodymovin can't get a animation with gradients and masks to work. Very simple Animation!

### ISSUE THREAD

**Issue by armiaka** [airbnb/lottie-web#770]
Hi,

here is the file to download:
https://we.tl/L2RDkWlMNa

here is a comparison between the Lottie preview and my actual animation:

actual animation:
<img width="209" alt="animationaftereffects" src="https://user-images.githubusercontent.com/19413079/34009445-4785da48-e109-11e7-86b2-147611c26d64.png">

Lottie preview:
<img width="208" alt="lottie preview" src="https://user-images.githubusercontent.com/19413079/34009360-e1996cfe-e108-11e7-893b-c2bb81c3f952.png">

would be very nice if you would download the project and would tell me what my problem is. I appreciate your help!

**Comment by bodymovin** [comment]
Hi, can you share the .aep?
If you're using feather on masks, they are not supported indeed

**Comment by armiaka** [comment]
Hi! https://we.tl/6kMsGszjio
