### ISSUE TITLE
Inlining assets

### ISSUE THREAD

**Issue by wwselleck** [airbnb/lottie-web#771]
I have an animation that will appear on a loading screen of a web app. Since it's the first thing the user sees, the animation needs to appear as quickly as possible, so I'd want the entire thing to be loaded inlined in the index.html. It looks like the default behavior is to load all of the assets over the network on `loadAnimation`. Is there any way to export an animation so that all of the assets are inlined into the `data.json` file? If I'm reading the code correctly, it seems like this could be done by manipulating the `assets` field of the JSON file to use a data URI instead of a URL. But if there is already a built in way to achieve this it'd be preferred. 

Thanks!

**Comment by bodymovin** [comment]
does your animation have rasterized pngs?

**Comment by wwselleck** [comment]
@bodymovin Yes.

**Comment by bodymovin** [comment]
right now there is no built in way to solve it, unfortunately.

**Comment by wwselleck** [comment]
If the assets were SVGs (or something else, I am not too knowledgable on the AE side of things), would the answer be different?

**Comment by bodymovin** [comment]
AE doesn't support svgs, but any rasterized layer, would be the same
