### ISSUE TITLE
Poor performance - How to improve?

### ISSUE THREAD

**Issue by Luc45** [airbnb/lottie-web#772]
Hello,

We are starting to use Bodymovin here in the agency, I'm a PHP developer and we have some guys that do TV animations, these two sectors are starting to work together, with them creating animations and exporting with Bodymovin for us developers to use.

Our first test looked nice, we are using it in a client's site, but the performance is terrible, specially in slow computers. The client said that it looks nice but if we couldn't solve the performance issues we should remove it. I'm pretty sure we are doing something wrong, but I don't know what.

Here's the client website:
https://www.bs2.com/

The animation is the "BS2" logo that appears in the middle of the screen right when you load the page.

If you have further questions about the After Effects part, I can ask the guys from the other sector to answer.

Thanks a lot for your support

PC with 8gb ram: Looks nice
Notebook with 4gb ram: Feels laggy
Mobile: Terribly laggy

**Comment by bodymovin** [comment]
Hi, I should take a look at the .aep project itself but it seems you're using a lot of track matte masks or stroke effects.
Those translate in svg to masks and filters that have very poor performance across browsers.
I'm not sure if you can achieve the same animation without them, but you should stick to regular AE masks and shape animations for best performance.

**Comment by Luc45** [comment]
I talked with the animation guys, they said they first tried to make it with regular AE masks and shape animations, but the output was weird, with rough, aliased edges, for what I understood. The track matte masks and stroke effects were a workaround for this, but with performance issues. They prepared a file with both versions for you to analyse, if you could:

http://www.lucasbustamante.com.br/uploads/ftp/bs2.aep

**Comment by bodymovin** [comment]
On both you're still using track matte masks so it's not ideal regarding performance, but the trim path version will probably work much better.
The weird output in that case is because browsers don't calculate well stroke sizes when masking. You need to add a transparent rectangle shape on each content layer so browsers do the correct measuring.
I've added it in your animation so you can check it out.
[bs2.zip](https://github.com/airbnb/lottie-web/files/1564352/bs2.zip)
