### ISSUE TITLE
CVShapeElement.destroy - TypeError: Cannot set property 'length' of undefined

### ISSUE THREAD

**Issue by SvetlozarKalchev** [airbnb/lottie-web#773]
Hi! I always get the error I've put in the title when using a canvas renderer and calling the `destroy()` method on a lottie animation.

Here's how I setup the animation:

```
this.animationData = {
	container: <DOM_ELEMENT_REFERENCE>,
	animationData: <ANIMATION_JSON>,
	renderer: "canvas",
	loop: true,
	autoplay: true
};
this.refLottieAnimation = lottie.loadAnimation(this.animationData);
```

The error occurs when I call `this.refLottieAnimation.destroy()`;

I get this issue in Chrome 63, on OSX in a React project. However, I don't think the error has anything to do with React or my browser version. Also, it doesn't matter what JSON animation data I am using - I've tried a few different files and I always get this error.

Here's a screenshot of the stack trace:

<img width="729" alt="screen shot 2017-12-15 at 15 38 37" src="https://user-images.githubusercontent.com/3620037/34046892-d88ebe56-e1ae-11e7-9536-f197cb361db1.png">

**Comment by bodymovin** [comment]
Thanks!
Fixed in version 5.0.6
Will upload it later tonight.
