### ISSUE TITLE
PNG images quadrupled in size on export

### ISSUE THREAD

**Issue by wonderment** [airbnb/lottie-web#775]
Greetings!

PNGs used in the composition are exported out under /images with the original pathnames, which is lovely, but the export process seems to be adjusting the PNG source files by compressing or another means of file manipulation.

The source PNG files are 4kb but the export appears to quadruple them in size to around 18kb each.

Can this manipulation be turned off? Or, is there a loadAnimation parameter to point to reference an image assets folder to bypass what Lottie/BM exports? 

PS. This is using v5.05 on AE 2k18.

**Comment by bodymovin** [comment]
you can use the parameter "assetsPath" in the config object to indicate a different source for the images.

**Comment by wonderment** [comment]
Thanks!

Will I need to tweak anything as far as the asset names in After Effects or can I simply dump all the PNGs in use in the Composition and Lottie will match them up?

Apologies if these are basic questions. I tried searching around for quite some time to piece things together.

**Comment by bodymovin** [comment]
there is a property in the plugin panel on the comp settigns to use original source name.
You can check the images folder and see how they export.

**Comment by wonderment** [comment]
Ok, so the images can just be swapped in the assetsPath/folder. Solid. Thank you!

**Comment by weehan777** [comment]
Hi do you have an example of: changing the parameter "assetsPath" in the config object to indicate a different source for the images, I am curious as to where this is done.
