### ISSUE TITLE
What do some animations have images generated along with them and some do not?

### ISSUE THREAD

**Issue by XBLDev** [airbnb/lottie-web#777]
What is the difference? What causes bodymovin to generate png files for some animations but not for other animations?

In one of the post I found here: https://github.com/airbnb/lottie-android/issues/235

It says "hen you import an Illustrator layer, convert your AI layer to a shape layer or else bodymovin will export it as a png".

Is that the only reason? Or is there something else?

Thanks in advance for any answer!

**Comment by bodymovin** [comment]
If you're using photoshop layers or rasterized images of any kind in your animation, they will get exported as external png assets.
Illustrator layers too unless you convert them to shapes as that post says.
