### ISSUE TITLE
Animation produced with Rubberhose and Bodymovin in AE is not displayed correctly on IOS

### ISSUE THREAD

**Issue by dgkit** [airbnb/lottie-web#778]
Seems to be displaying correctly in render demos but not on IOS.
Was produced in After Effects with Rubberhose, rendered with Bodymovin including hidden layers as instructed for rubberhose.

<img width="360" alt="screen shot 2017-12-19 at 11 20 51" src="https://user-images.githubusercontent.com/26896326/34154954-5a8578de-e4af-11e7-8c91-808263cd8b07.png">
[05_Loader.zip](https://github.com/airbnb/lottie-web/files/1571455/05_Loader.zip)

**Tell us about your environment**

* **Browser and Browser Version:**
* **After Effects Version:**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**

**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, expressions are not yet supported by lottie-ios and lottie-android
