### ISSUE TITLE
Drop shadow support?

### ISSUE THREAD

**Issue by ncwalls** [airbnb/lottie-web#779]
Hi, first of all bodymovin is amazing thank you!

Maybe I misunderstood but I've seen a few comments suggesting drop shadows are supported. However I can't get it to render.  I've added a layer style drop shadow.  Is there some other way I should do it? (I've been a web dev for 9 years but am a newbie at AE.)

I thought about manually adding an svg filter but I'm not sure how to do that since the svg code is all created dynamically from the json.

**Comment by bodymovin** [comment]
Hi, the supported drop shadow is the layer effect, the layer style is not supported.

**Comment by ncwalls** [comment]
Sorry, I don't quite understand. Is "layer effect" something in AE?
(Anyway, I was able to add a shadow by adding svg filters with js, but that is not ideal.)

**Comment by bodymovin** [comment]
Sorry if I wasn't clear, you can add the drop shadow as an effect from the effects panel in AE.

**Comment by ncwalls** [comment]
Ah, ok. Thanks.

**Comment by blamebento** [comment]
I have added the Drop Shadow as an effect from the effects panel, When I export with Body moving the dropshadow are missing.

This was an old thread, but seems to be an issue with the current version of Bodymovin

**Comment by bodymovin** [comment]
@blamebento hi, take a look at the wiki regarding filters:
https://github.com/airbnb/lottie-web/wiki/Renderer-Settings#filtersize-svg-renderer
You probably need to specify the size of the drop shadow container.

**Comment by shortshots** [comment]
@bodymovin Hey, thanks for the great product. I've been using it for over 3 years. And now, for the first time, I have the same shadow problem. Maybe you have a solution. Thank you. 
![Screenshot 2020-07-29 at 15 16 14](https://user-images.githubusercontent.com/68953646/88798980-7410e380-d1ae-11ea-8f3b-1d400f1c5375.png)
![Screenshot 2020-07-29 at 15 15 39](https://user-images.githubusercontent.com/68953646/88798999-7b37f180-d1ae-11ea-8b3d-e91dbc5d19e3.png)

**Comment by bodymovin** [comment]
hi @shortshots did you check the link shared on the previous message?

**Comment by shortshots** [comment]
@bodymovin Yeah, I saw the link in the last post. But I'm not a developer, and I don't understand anything about it. Could you tell us a bit more about solving this problem? Thank you.

**Comment by tom-watso** [comment]
Hey! I am having this issue and cant work out how to implement the code to fix this, could anyone help please?
