### ISSUE TITLE
Bodymovin render with external footage

### ISSUE THREAD

**Issue by guykes** [airbnb/lottie-web#781]
Hi there

I have an AE file with external footage (pngs from folder on disk) that is being loaded into my file. When i render it to .mov it shows the external png sequence. When i render it with bodymovin, it doesn't.

Could you please help me out here and tell me what i'm doing wrong?

Thanks!
G.
[KBC_Selfie_Comp_v1_converted_EN.aep.zip](https://github.com/airbnb/lottie-web/files/1578896/KBC_Selfie_Comp_v1_converted_EN.aep.zip)

**Comment by guykes** [comment]
OK, stupid question as it seems that Bodymovin only exports paths. So i need to recreate the png sequence in after effects from scratch.

If you got a workaround, it would be highly appreciated!

Thanks!
G.

**Comment by bodymovin** [comment]
Hi, bodymovin doesn't support png sequences at the moment.
It does support individual rasterized files.
But I'm not sure it makes much sense to use bodymovin if your animation is png based.

**Comment by guykes** [comment]
Exactly, figured it out.
I need to recreate the sequence from scratch with shapes and effects and stuff like that.

Thanks for the reply!
