### ISSUE TITLE
Lottie embedded in WordPress

### ISSUE THREAD

**Issue by brundea** [airbnb/lottie-web#784]
Hi, I've searched everywhere, including the Issues section here in GitHub. I can't find the way to display a lottie animation in my WordPress site.

I've uploaded both .js files (lottie.js and the animation initializer .js file) as well as data.json.

anim-init.js
`var animation = lottie.loadAnimation({
    container: document.getElementById('bm'),
    renderer: 'svg',
    loop: true,
    autoplay: true,
    path: 'https://seguramente.com.ar/wp-content/uploads/2017/12/logo-animation.json'
})`

Then, on my index page, I wrote this
<div id="bm"></div>
<script src="https://seguramente.com.ar/wp-content/uploads/2017/12/lottie.js"></script>
<script src="https://seguramente.com.ar/wp-content/uploads/2017/12/anim-init.js"></script>

I styled the div#bm like this
`#bm {
  background-color: gray;
  width: 100%;
  height: 50vh;
}`

I also added this to functions.php, so I could import .js and .json files
`function my_myme_types($mime_types){
$mime_types['json'] = 'json'; //Adding json extension
$mime_types['js'] = 'js'; //Adding js extension
return $mime_types;
}
add_filter('upload_mimes', 'my_myme_types', 1, 1);`

This works perfectly fine on a blank .html document done locally. But when doing it in Wordpress, nothing happens. The div#bm with it's corresponding CSS works fine. But no animation is shown.

Thanks by forehand.

**Comment by Nessjk** [comment]
Thanks Brundea for posting this! I have the exact same problem at this exact same moment, and followed the exact same steps!

I get an error though: 

Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at SVGRenderer.configAnimation (bodymovin.js?ver=4.9.1:3)

I tried implementing a "wp_localize_script" due to the potential .json security issues; in order to grab the .json using "get_stylesheet_directory_uri()". The script works but the animation still isn't rendering. 

Thanks

**Comment by bodymovin** [comment]
Do you have a link I can check out?

**Comment by Nessjk** [comment]
Hi! Not original poster...but here is my link. http://artisanplus.fr/

**Comment by brundea** [comment]
Yes! Check: https://seguramente.com.ar

Glad to be having the same problem as you, Nessjk!

**Comment by Nessjk** [comment]
Hey Brundea! 

You are concatenating where you don't need to concatenate...as you are giving the full http address. Try `wp_enqueue_script( 'lottie', 'https://seguramente.com.ar/wp-content/scripts/lottie.js' );`

Try that and let me know

**Comment by bodymovin** [comment]
@Nessjk it seems you got it working right?
There are some animations that aren't being loaded because the document.getElementById doesn't find the container.

**Comment by brundea** [comment]
@Nessjk with your code, it seems now that lottie.js is being loaded, but not anim-init.js which is the one that basically plays the animation. It seems you got it working, though. What did you change? Thank you!

@bodymovin that reply was for Nessjk, right?

Thank you guys. I'm gonna keep looking further into it. More help is much appreciated.

**Comment by bodymovin** [comment]
@brundea it seems to be looking for the json file here:
https://seguramente.com.ar/logo-animation.json
Where is it actually located?

**Comment by brundea** [comment]
@bodymovin it is located exactly where the other two .js files are. Here: https://seguramente.com.ar/wp-content/scripts/logo-animation.json

Should I put that directory in the path: '' value of anim-init.js ?? Thanks!

**Comment by bodymovin** [comment]
@brundea yes, try passing the full path

**Comment by brundea** [comment]
Ok, there seems to be a problem... For some reason, wordpress adds to the URL ?ver=4.9.1, but if I delete that then I can see the file (anim-init.js) updated with the new full path. But it still loads the old anim-init.js with the old path route. Don't know why this happens really.

**Comment by Nessjk** [comment]
Hi @brundea ! Glad to know we finally got it!

Would definitely be interested to see your explanation. @bodymovin where's it best to do one of those?

For those struggling right now here's my work around:

**index.js**
```
 var templateUrl = object_name.templateUrl;
//Animation
    var warning = {
       container: document.getElementById('warning'),
       renderer: 'svg',
       loop: true,
       autoplay: true,
       path: templateUrl + '/json/warning_sign.json' 
     }
     var animWarning = bodymovin.loadAnimation(warning);
```

**functions.php**
Same as Brundea, as was having security issues and Cross-Origin Resource Sharing (CORS) especially developing on a localhost.
```
function my_myme_types($mime_types){ $mime_types['json'] = 'json'; //Adding json extension $mime_types['js'] = 'js'; //Adding js extension return $mime_types; } add_filter('upload_mimes', 'my_myme_types', 1, 1);

function aplus_theme_scripts() {
  wp_enqueue_script ('bodymovin' , get_template_directory_uri() . '/scripts/lottie.js', '', false );
  wp_enqueue_script ('index' , get_template_directory_uri() . '/scripts/index.js', array('jquery'), false );
}
add_action('wp_enqueue_scripts', 'aplus_theme_scripts');
```

I still had nothing rendering. Something was wrong with the path and bodymovin was loading a at different time than my animation. Using devtools => network tab to see what's happening was very useful. Finally, I used wp_localize_script. I highly recommend to get to know more about it. See here https://pippinsplugins.com/use-wp_localize_script-it-is-awesome/

Thus added in functions.php:
```
wp_register_script( 'my-script', get_stylesheet_directory_uri().'/scripts/index.js' );
wp_enqueue_script( 'my-script' );
```
`$translation_array = array( 'templateUrl' => get_stylesheet_directory_uri() );
`//after wp_enqueue_script
`wp_localize_script( 'my-script', 'object_name', $translation_array );
`

This allowed me to use the " get_stylesheet_directory_uri()" which is php but used inside of my javascript function...very useful in this case...as it works now!

Hope this helps.

**Comment by brundea** [comment]
@Nessjk that's awesome! Glad to see you got it working, and thanks for the explanation.

All the files were uploaded by FTP. Here's how my code ended up being.

Added to **functions.php**
```php
wp_deregister_script( 'jquery' );
wp_register_script( 'jquery', "https://code.jquery.com/jquery-3.1.1.min.js", array(), '3.1.1' );
wp_enqueue_script( 'lottie', 'https://seguramente.com.ar/wp-content/scripts/lottie.js', array( 'jquery' ) );
wp_enqueue_script( 'anim-init', 'https://seguramente.com.ar/wp-content/scripts/anim-init.js', array(), 1.1 );
```
I deregistered jquery because on the www.lottiefiles.com site, when you preview an animation, you can copy the iframe code and paste it into your site. I did this, and found out that they use jquery 3.1.1. Probably this step isn't necessary, but I don't have time to check right now.

**anim-init.js**
```javascript
$(document).ready(function(){
	var animData = {
		container: document.getElementById('bm'),
		renderer: 'svg',
		loop: true,
		autoplay: true,
		path: "https://seguramente.com.ar/wp-content/scripts/logo-animation.json"
	};
	var anim = lottie.loadAnimation(animData);
});
```

**logo-animation.json** is the animation exported from After Effects.
Then of course, on the home page of my site I simply created a div#bm as container for the animation. Styled it a bit with CSS and that was it.

Thank you for all the help guys!

**Comment by tyt2y3** [comment]
lottie.js is not depending on jQuery, so there is no need to deregister and replace it
just reduce it to 
```
wp_enqueue_script( 'lottie', 'https://seguramente.com.ar/wp-content/scripts/lottie.js', array( '' ) );
wp_enqueue_script( 'anim-init', 'https://seguramente.com.ar/wp-content/scripts/anim-init.js', array(), 1.1 );
```
Anyway, don't touch on php if not strictly necessary. Using a plugin that manages custom js, like the [CJT](https://wordpress.org/plugins/css-javascript-toolbox/).

**Comment by Jackmile** [comment]
Hello. Is there a solution for this ? When I export from after effects to wordpress, I only get a white area, but demo works. It also does not generate shortcode on WP bodymovin. Could you please help me ?

**Comment by AdrienAlva** [comment]
> @Nessjk that's awesome! Glad to see you got it working, and thanks for the explanation.
> 
> All the files were uploaded by FTP. Here's how my code ended up being.
> 
> Added to **functions.php**
> 
> ```
> wp_deregister_script( 'jquery' );
> wp_register_script( 'jquery', "https://code.jquery.com/jquery-3.1.1.min.js", array(), '3.1.1' );
> wp_enqueue_script( 'lottie', 'https://seguramente.com.ar/wp-content/scripts/lottie.js', array( 'jquery' ) );
> wp_enqueue_script( 'anim-init', 'https://seguramente.com.ar/wp-content/scripts/anim-init.js', array(), 1.1 );
> ```
> 
> I deregistered jquery because on the [www.lottiefiles.com](http://www.lottiefiles.com) site, when you preview an animation, you can copy the iframe code and paste it into your site. I did this, and found out that they use jquery 3.1.1. Probably this step isn't necessary, but I don't have time right now to check if it also works with the core jquery that Wordpress uses.
> 
> **anim-init.js**
> 
> ```js
> $(document).ready(function(){
> 	var animData = {
> 		container: document.getElementById('bm'),
> 		renderer: 'svg',
> 		loop: true,
> 		autoplay: true,
> 		path: "https://seguramente.com.ar/wp-content/scripts/logo-animation.json"
> 	};
> 	var anim = lottie.loadAnimation(animData);
> });
> ```
> 
> **logo-animation.json** is the animation exported from After Effects.
> Then of course, on the home page of my site I simply created a div#bm as container for the animation. Styled it a bit with CSS and that was it.
> 
> Thank you for all the help guys!

Adding 'wp-content' to my path was the solution for me while working with localhost.

`path: 'http://localhost/root-directory/wp-content/themes/theme-name/data.json'`
