### ISSUE TITLE
how to preview the json with image folder onto the lottiefiles.com?

### ISSUE THREAD

**Issue by punskhit120** [airbnb/lottie-web#785]
How to preview the json with image folder onto the lottiefiles.com

**Comment by bodymovin** [comment]
Hi, you can use the submit feature and upload the files as a zipped files
https://www.lottiefiles.com/submit

**Comment by Nihalgraphics** [comment]
![Screenshot 2019-04-03 at 11 55 47 AM](https://user-images.githubusercontent.com/18048010/55457413-72a9c800-5607-11e9-9335-17526b4b2043.png)


> Hi, you can use the submit feature and upload the files as a zipped files
> https://www.lottiefiles.com/submit

**Comment by cedrickbae** [comment]
Here, https://lottiefiles.com/preview
