### ISSUE TITLE
EnterFrame event using Wordpress

### ISSUE THREAD

**Issue by brundea** [airbnb/lottie-web#786]
Hi! I'm trying to accomplish an animation playing when the user scrolls to a certain section of the site, that being the same as the animation entering the frame.

I'm using this code:
```javascript
$(document).ready(function(){
	var animData = {
		container: document.getElementById('bm'),
		renderer: 'svg',
		loop: true,
		autoplay: true,
		path: "https://seguramente.com.ar/wp-content/scripts/logo-animation.json"
	};
	var anim = lottie.loadAnimation(animData);
});

anim.addEventListener('enterFrame', enterframe);

function enterframe() {
	console.log('In Frame');
}
```

However I get the following error code:

![image](https://user-images.githubusercontent.com/34754712/34322525-e8eb7492-e807-11e7-9c73-1f5ad83359cc.png)

Here you can check the site: https://seguramente.com.ar

As you can see, I don't know much about jQuery, or JavaScript, or Wordpress itself. Any help is much appreciated!

**Comment by bodymovin** [comment]
it's a matter of variable scope.
Since you're declaring the var anim inside a function attached to the document ready, it's not accessible from outside the scope function.
You can add the line 
````javascript
anim.addEventListener('enterFrame', enterframe);
````
inside the function and it should work
