### ISSUE TITLE
Works in preview but not in browser

### ISSUE THREAD

**Issue by icebasic** [airbnb/lottie-web#787]
Hi

Im trying to do a thing with alpha matte in works fine in the preview window in after effects. But in the browser there is no text.

Preview window
![cd5d68faf68a946b860e180b27a87bf0](https://user-images.githubusercontent.com/33295013/34325671-74fb0624-e898-11e7-9670-e0b9aeb950c1.png)

Browser (Chrome)
![100dadcd04ecd66e85024894e9864aca](https://user-images.githubusercontent.com/33295013/34325675-84d1e91e-e898-11e7-8c4c-a11205af7fa0.png)

js
`const ani = document.getElementById("ani")`
`let animation = bodymovin.loadAnimation({`
 `   container: ani, `
`    renderer: 'svg',`
 `   loop: false,`
  `  autoplay: true,`
 `   path: 'data.json',`
 ` });`

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by icebasic** [comment]
> Hi, can you share the .aep?

Yes, absolutely! I tried a couple of things so i can be a bit messy but Im sure you will figure it out. :)
[yay.zip](https://github.com/airbnb/lottie-web/files/1586163/yay.zip)

**Comment by bodymovin** [comment]
You're using an older version of the player and extension.
Can you try updating it to the latest version?
I've tried it and it seems to work fine

**Comment by icebasic** [comment]
> You're using an older version of the player and extension.
> Can you try updating it to the latest version?
> I've tried it and it seems to work fine

I've updated both after effects to 2018 and the extension to version: 5.0.6 and it still do not work.  Am I suppose to have any special settings or something?  I have tried the demo to and it do not work there.

**Comment by bodymovin** [comment]
Can you share a link with the animation not working?
