### ISSUE TITLE
Continues play N number of JSON file.

### ISSUE THREAD

**Issue by gajjar8055** [airbnb/lottie-web#788]
How to load second JSON file on the same element?
Like I have three files of json. I want to play without any hassle.
Is it possible?

**Comment by bodymovin** [comment]
It's probably better if you load each one on a different element and show and hide them when needed.
If you load them on the same element, you have to destroy the previous one, and it might be noticeable until the next one is loaded.
Depending on your animation you can also export all of them in a single json file and play them sequentially.

**Comment by gajjar8055** [comment]
How could  I play sequentially I don't have any idea about how to do it ?

**Comment by bodymovin** [comment]
It depends on your setup.
You can attach to the onComplete event and play the next animation once the first one ends.

**Comment by dev31** [comment]
Is there any example how to play several json files by turns?
