### ISSUE TITLE
Multiple animations not working

### ISSUE THREAD

**Issue by cwahlfeldt** [airbnb/lottie-web#789]
**Tell us about your environment**
`lottie-web: 5.0.5` static html, using gulp and webpack for builds.

* **Browser and Browser Version:**
Firefox 58.0b12 (64-bit)

* **After Effects Version:**
I used lottiefiles

**What did you do? Please explain the steps you took before you encountered the problem.**
I loaded an animation with lottie for a hamburger menu. Then attempted to load a second animation for a loading graphic from lottie files.

**What did you expect to happen?**
I expected the loading graphic to work.

**What actually happened? Please include as much _relevant_ detail as possible.**
The second animation wasnt propagating the container div and the console is giving me this error `TypeError: this.animationItem.wrapper is undefined`. 

Here is my code for all the animations. The `burgerAnimation` works fine but the second `loadingAnim` spits out the error mentioned earlier. I have tried using the loading json file in place of the burger animation and it works fine so I dont think its the json file. I feel as though I'm missing something very basic...
```
import lottie from 'lottie-web';
import burgerData from './burger/burger.json';
import loadingData from './loading/loading.json';

const burger = document.getElementById('burger');
const loading = document.getElementById('loading');

const burgerAnimation = lottie.loadAnimation({
  container: burger,
  renderer: 'svg',
  loop: true,
  autoplay: true,
  animationData: burgerData,
});

const loadingAnim = lottie.loadAnimation({
  container: loading,
  renderer: 'svg',
  loop: true,
  autoplay: true,
  animationData: loadingData,
});
```

**Please provide a download link to the After Effects file that demonstrates the problem.**
Burger animation that works fine https://www.lottiefiles.com/255-menu-button-alt
The loading animation thats not working. https://www.lottiefiles.com/27-loading

**Comment by bodymovin** [comment]
That error seems related to not finding the container element. Can you check if document.getElementById('loading') returns something before loading the animation?

**Comment by JamesCastrejon** [comment]
I don't know how relevant this issue is anymore but I'm having the same problem on my iOS app.
