### ISSUE TITLE
Layer's 'inPoint' not available in expression and hence causing error

### ISSUE THREAD

**Issue by ssanthos** [airbnb/lottie-web#790]
**Tell us about your environment**
Mac OS 10.13 High Sierra

* **Browser and Browser Version:**
Chrome 63
* **After Effects Version:**
CC 2018 (15.0.0)

**What did you do? Please explain the steps you took before you encountered the problem.**
Used an expression in a comp like this -

s=thisComp.layer("Hello text");
x=s.sourceRectAtTime(time-s.inPoint,true).width;
y=s.sourceRectAtTime(time-s.inPoint,true).height;
[x,y]

**What did you expect to happen?**
I should be able to load and play the exported JSON data using lottie.

**What actually happened? Please include as much _relevant_ detail as possible.**
When loading data using lottie, it throws an error and doesn't work.
Here's the error string - 
Uncaught TypeError: Cannot read property 'constructor' of undefined

And it seems to be occuring when evaluating the expression above at the line
x=s.sourceRectAtTime(time-s.inPoint,true).width;
Upon inspection, s.inPoint is undefined.

**Please provide a download link to the After Effects file that demonstrates the problem.**
[Demo file.aep.zip](https://github.com/airbnb/lottie-web/files/1591876/Demo.file.aep.zip)

**Comment by bodymovin** [comment]
I will add the inPoint to the layers, but nevertheless, sourceRectAtTime with a time different than the current time is not supported yet, so it won't work for now.

**Comment by ssanthos** [comment]
@bodymovin That's too bad.
If 'inPoint' is used in expressions other than sourceRectAtTime, it makes sense to add still. But I don't know if that's the case.
You're probably in a better position to take a call.

**Comment by bodymovin** [comment]
you can use inPoint with valueAtTime for example.

**Comment by ssanthos** [comment]
Oh cool. In that case, could you add `inPoint`?

It seems like the lack of support of non-current time in `sourceRectAtTime` (and possibly valueAtTime?) is an independent issue, since even something like `layer.sourceRectAtTime(time - 5)` wouldn't work as well.

Also, currently the animation throws errors when loading due to a lack of these values which might not be desirable.
