### ISSUE TITLE
After effects Pre comps and Bodymovin

### ISSUE THREAD

**Issue by Sdhulip** [airbnb/lottie-web#793]
I have tried a rendering a comp with multiple precomps in it which doesn't have any effects except any scale or rotation values. It isn't rendering any of it! I've tried bunch of different ways like deleting rest of the precomp except one. It seems like precomps are an issue in both 2017 and 2018 ae version. The precompos just have shape layer with collapse transformations and 3D layer switched. Can anyone please help me regarding this as soon as possible ?

update 1:

I tried switching of 3d to precomp and all the layers in side the it and it worked, i also tried 3d layer only for the precomp, worked that way too, it seems like if the layers inside the precomp are 3d then its not rendering.

Thankyou!

**Comment by bodymovin** [comment]
Hi, indeed, precomps with 3d layers are not yet supported :/

**Comment by Sdhulip** [comment]
Hope to see the support soon! I have rendered the animation with some tweaks but the problem is, it lags. Any solution for that ?

**Comment by scottahn** [comment]
I'm having trouble rendering a comp with just 2 precomps. Is there a secret in how to accomplish this?

**Comment by Sdhulip** [comment]
Hello Scott,

Body movin supports basic after effects things for now as they are adding more in the updates... just go through comp and check if everything’s supported by Bodymovin and it should would work I suppose! 👍

Best,
SD

________________________________

**Comment by bodymovin** [comment]
@scottahn Hi, empty shape layers don't work with the player.
And using the fill effect, although it works, might have some performance issues.
Can you use regular paths instead of this type of solution?

**Comment by bahargh** [comment]
Hi, I have tried a rendering a comp and when I put CC light sweep effect on the text(or any effects & preset) but unfortunately it doesn't happen after rendering. it just show me the text without any effects.
please help me, Thanks.

**Comment by Sdhulip** [comment]
Hello!

I guess bodymovin doesn’t yet support effects.. the only solution is to simply as much as you can without effects.

Best,
Sd

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Sdhulip** [comment]
@bahargh I would probably feather out edges of the mask and try the modes like overlay/screen or play around until you find the right one and it should get the work done .

**Comment by bahargh** [comment]
@Sdhulip Thanks a lot.

**Comment by Sdhulip** [comment]
@bahargh Hope that helped! :D

**Comment by bahargh** [comment]
Hi again, I have problem with text align after rendering with bodymovin. it's not in correct place.

**Comment by Sdhulip** [comment]
@bahargh I personally haven’t experienced that but as of my research which obviously redirected me to one of the questions on GitHub Lottie (https://github.com/airbnb/lottie-web/issues/783). I haven’t tested it but hope this will help solve your problem!

**Comment by bahargh** [comment]
@Sdhulip Thanks for your help, finally I created shapes from text and solve it.

**Comment by guaard** [comment]
Hello, I have a problem when I do the exportation. I have only a fix background ...
I think is related to my precomps. I have the version 5.3.4.
Thank you in advance for your help !

[test.aep.zip](https://github.com/airbnb/lottie-web/files/2764315/test.aep.zip)

**Comment by bodymovin** [comment]
@guaard Hi, there are missing files o the project, can you share them?
