### ISSUE TITLE
Weird grey box around shapes

### ISSUE THREAD

**Issue by Motionmofo** [airbnb/lottie-web#795]
Hello, 
I'm trying to render a animation, but parts of the animation have a grey box around them. The shapes (legs) with the grey box around them is Rubberhose 2's leg hoses, but the arms are also Rubberhose 2 as well but aren't affected with the grey box. The animation also has a few pre-comps each with one of the characters. Not sure what's going on. I've checked the files thoroughly, but couldn't find what could be the problem.

FYI. In settings am turn on Hidden for Rubberhose 2 and Guides for Joysticks and sliders.

I am using the latest After Effects as well as Bodymovin.

![bodymovi problem](https://user-images.githubusercontent.com/35042886/34498594-33bc0020-efb7-11e7-8926-480f7c54dc63.png)

**Comment by bodymovin** [comment]
Hi, can you share the .aep so I can take a look?

**Comment by Motionmofo** [comment]
Sure. Here

[Headache Peeps Web Animations folder.zip](https://github.com/airbnb/lottie-web/files/1598649/Headache.Peeps.Web.Animations.folder.zip)

**Comment by Motionmofo** [comment]
I found the problem, the feet and hand shapes layers had groups of layers that were hidden that became unhidden due to using Hidden in Bodymovin settings. I forgot about those hidden layers. I deleted them and everything is good.  My bad lol.

**Comment by bodymovin** [comment]
Hi, I was going to comment on that :)
You can export only guided layers and it should be fine too.

**Comment by Motionmofo** [comment]
Thanks!

**Comment by Jparrgam** [comment]
Hi @Motionmofo, I'm having the same problem, but can't find the hidden groups, can you share a screenshot in order to know here I can find those hidden groups? ty for your help buddy.
