### ISSUE TITLE
Repeater not displayed on iOs and Android

### ISSUE THREAD

**Issue by charlesbail** [airbnb/lottie-web#797]
**Tell us about your environment**
Bodymovin 5.0.4
App's Lottie verison 2.0.3

* **Browser and Browser Version:**
Using LottiePreview app

* **After Effects Version:**
CC2018

**What did you do? Please explain the steps you took before you encountered the problem.**
Baked the expressions with EasyBake
Disabled all effects
Only effects is the Repeater applied on the shape

**What did you expect to happen?**
Display the circle burst with a repeater. It works on the web version

**What actually happened? Please include as much _relevant_ detail as possible.**
Preview on web = perfect
Preview on ios = repeater not working. Displaying only one instance of the object

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.lottiefiles.com/share/pHHbLV
A more simple file with just a square repeated 3 times with the Repeater. Displayed on LottiePreview on the web. But on mobile, you will only see one instance of the square

**Comment by bodymovin** [comment]
Hi, repeaters are not yet supported in iOS, but they should be in Android.
Is it not working there?

**Comment by charlesbail** [comment]
Hello! Thank you for your answer
We didn't try on android, we will give it a shot and will stay tuned for the support of repeaters for android
