### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by XBLDev** [airbnb/lottie-web#798]
It seems that this is a very common issue? I've checked several posts, lots of them are related to AE versions it seems? Anyway can someone have a look at the JSON file and find out what's the problem? I'm not AE expert myself so I don't really know what's going on.

Thanks in advance for all the answers!
[Group1Image7BatteriesV3.zip](https://github.com/airbnb/lottie-web/files/1606094/Group1Image7BatteriesV3.zip)

**Comment by bodymovin** [comment]
Hi, the animation seems to be working fine.
Can you share a link where it is failing or try useing the latests version of the player?

**Comment by XBLDev** [comment]
Hi @bodymovin thanks for the reply, I run it with the very minimum setup like the example here: 
https://codepen.io/airnan/project/editor/ZeNONO

And the error log:

bodymovin.min.js:4 Uncaught TypeError: Cannot read property 'length' of undefined
    at ICompElement.BaseRenderer.buildAllItems (bodymovin.min.js:4)
    at new ICompElement (bodymovin.min.js:1)
    at ICompElement.SVGRenderer.createComp (bodymovin.min.js:4)
    at ICompElement.BaseRenderer.createItem (bodymovin.min.js:4)
    at ICompElement.SVGRenderer.buildItem (bodymovin.min.js:4)
    at ICompElement.BaseRenderer.buildAllItems (bodymovin.min.js:4)
    at new ICompElement (bodymovin.min.js:1)
    at SVGRenderer.createComp (bodymovin.min.js:4)
    at SVGRenderer.searchExtraCompositions (bodymovin.min.js:4)
    at AnimationItem.configAnimation (bodymovin.min.js:5)

I've attached my aep file, maybe this could help identifying the problem?
[Group1Image7Batteries.zip](https://github.com/airbnb/lottie-web/files/1611020/Group1Image7Batteries.zip)

**Comment by bodymovin** [comment]
It might be a version of the player older than the version of the json file.
Can you share a link where I can see the error?

**Comment by XBLDev** [comment]
Hi @bodymovin I've added the minimal version of the app in my git: https://github.com/XBLDev/EddyApp/tree/master/EddyWebMinimal

Thank you for your help!

**Comment by bodymovin** [comment]
I don't think it is.
But you should try using a newer version of the player and see if it works.

**Comment by XBLDev** [comment]
Hi @bodymovin by "newer version of the player" do you mean the js file I can get from the CDN?:
https://cdnjs.com/libraries/bodymovin

I'm already using 4.13.0, which according to the website is the latest version. I include it in my html file:

<body>
  <div id="bm"> </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.13.0/bodymovin.min.js"></script>  
  <script src="lottieAnimation.js"></script>  
</body>

**Comment by XBLDev** [comment]
Update 16/01/2018: still no clue why it's not working, can someone please help have a look at it?

**Comment by Masner** [comment]
Hello, 
i am having same issue: https://codepen.io/masner/project/editor/AjWmPy 
What it should look like is here : http://zeifart.com/trash/bodymovin/master/demo.html (generated by After effects plugin) 
I am using lottie.js v 5.1.16

**Comment by Masner** [comment]
So our issue was resolved by updating plugin in Adobe Aftereffects. So i think @XBLDev had same problem and you can close this issue.
