### ISSUE TITLE
Was trying out changing text of a lottie animation . How can we add line-breaks

### ISSUE THREAD

**Issue by sbsomya** [airbnb/lottie-web#799]
Eg: If we had text like 

I want a big linebreak
here 
and some more text 

And animate this is this possible?

**Comment by bodymovin** [comment]
Hi, you have to add "\r" for line breaks.
How are you updating texts?

**Comment by sbsomya** [comment]
Doing it by updating the bodymovin json 
` bodymovinData.layers[0].t.d.k[0].s.t = text;`
Also wanted to know if there is a possibility to add a text alignment  property like left align , right align

**Comment by sbsomya** [comment]
@bodymovin it works adding \r thanks

**Comment by sbsomya** [comment]
@bodymovin text alignment if there is a property would be ideal 
Also any documentation regarding the bodymovin json to understand the elements

**Comment by sbsomya** [comment]
Closing as works with \r
