### ISSUE TITLE
Bodymovin - The render demo doesn't work with ease and wizz

### ISSUE THREAD

**Issue by RobertoAnimation** [airbnb/lottie-web#800]
When I render the animation, the demo.html version doesn't work when using ease and wizz plugin.

Im using Safari as a browser.

Help!

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by RobertoAnimation** [comment]
Yes.

[Test.aep.zip](https://github.com/airbnb/lottie-web/files/1609221/Test.aep.zip)

**Comment by bodymovin** [comment]
It's because lottie is running in strict mode and the ease and wizz expression doesn't declare a couple of variables. 
I'll have it fixed later today.
In the meantime, you can declare those variables yourself in the extension (var2 and var3) or delete 'use strict' from the lottie player code.

**Comment by RobertoAnimation** [comment]
Ok, can you please tell me how can I delete 'use strict' form the lottie player code?

**Comment by bodymovin** [comment]
just search for that string 'use strict' in the code and delete it.
It should be there twice.

**Comment by RobertoAnimation** [comment]
Ok.

When you said you will have it fixed later today, does the plug in update itself or I have to do something in order to fix the issue?

**Comment by bodymovin** [comment]
You'll have to install a new version.
Where did you get it from?

**Comment by RobertoAnimation** [comment]
From this same page.
https://github.com/airbnb/lottie-web

When do you think the new version will be ready?

**Comment by bodymovin** [comment]
Fixed and uploaded in version 5.1.2
