### ISSUE TITLE
'Fast blur' and 'simple choker' does not working on bodymovin.

### ISSUE THREAD

**Issue by Inseok00** [airbnb/lottie-web#802]
'Fast blur' and 'simple choker' does not working on bodymovin.

These are not supported yet?

Or any other solutions on AfterEffect?

**Comment by bodymovin** [comment]
They are not, and for real time rendering, performance would be terrible.
for now those kind of effects are not possible.

**Comment by Inseok00** [comment]
@bodymovin Thank you!!! ㅜㅜ
