### ISSUE TITLE
ImageElement missing ID and Class

### ISSUE THREAD

**Issue by miszmaniac** [airbnb/lottie-web#803]
Hi,

Sometime ago I send you pull request https://github.com/airbnb/lottie-web/pull/749

There is discussion there how to create layer names to make them use ID and class accordingly. 

In one of latest releases you've removed those lines inside ImageElement.js
```
if(this.data.ln){
    this.layerElement.setAttribute('id',this.data.ln);
}
if(this.data.cl){
    this.layerElement.setAttribute('class',this.data.cl);
}
```

It looks like bug because all rest of the layers still use those attributes.
Can you put those back?

**Comment by bodymovin** [comment]
Yes, I'll upload a fix tonight.

**Comment by miszmaniac** [comment]
Thanks;)
