### ISSUE TITLE
Bodymovin not exporting composition with single swf file on it 

### ISSUE THREAD

**Issue by KanishkVashisht** [airbnb/lottie-web#804]
Hi,
I'm using bodymovin on a MacBook Pro with the latest AfterEffects. 
I'm trying to export a composition from footage that is just an .swf file to .json using bodymovin. However, bodymovin preview shows nothing and bodymovin exports a data.json that does not load on any preview website. 

Here's a ZIP with the erroneous AE project and the output data.json: 
[error.zip](https://github.com/airbnb/lottie-web/files/1611193/error.zip)

Thanks a lot

**Comment by tyt2y3** [comment]
Lottie is designed for AE animation, meaning one should make use of the AE timeline, comps and the like.
If you have a swf animation, why not use Animate and take advantage of its ability to export to HTML5?
There is no simple way to convert swf into native AE animations (ask Adobe) and simply importing a swf onto the AE timeline is no different from importing a mp4 video. They are just pixels.

**Comment by riscovo** [comment]
Hey there, I had the same problem. Adobe has recently updated an After Effects feature of importing Animate (FLA) animations in the AE timeline. But, at a first try, it does not look like solving the problem. I am more keen to believe that the Bodymovin plugin should be released also for Animate. Have a look here: https://github.com/airbnb/lottie-web/issues/1604
