### ISSUE TITLE
Is there  a possibility to add a text alignment property like left align , right align

### ISSUE THREAD

**Issue by sbsomya** [airbnb/lottie-web#805]
Updating data for text like 

`bodymovinData.layers[0].t.d.k[0].s.t = text;`

Can we specify the text alignment in a similar way ?

**Comment by bodymovin** [comment]
yes, it's the "j" property in bodymovinData.layers[0].t.d.k[0].s

**Comment by sbsomya** [comment]
Ohh really thanks it works
