### ISSUE TITLE
Lottie Light not running animations

### ISSUE THREAD

**Issue by FelixAnimations** [airbnb/lottie-web#806]
Hello, I've been using bodymoving and lottie for a while now and it's gone well, since the last update where the web player was updated there seem to be some problems, my animations run fine if it's the standart lottie player on the website, but they don't run at all if it's lottie light, i'm not using any effects it's simple shape animations, and i've even tested just a shape circle and nothing at all renders in the website, is there any info on this? I couldn't seem to find anyone complaining about this issue.

**Comment by tyt2y3** [comment]
perhaps check your params making sure you are using the 'svg' renderer but not 'html'?
```
bodymovin.loadAnimation({
    renderer: 'svg'
});
```

**Comment by bodymovin** [comment]
Thanks, indeed the light version was not working.
I will upload a fix today.
