### ISSUE TITLE
Hidden bodymovin animations, play when vissible?

### ISSUE THREAD

**Issue by markusreklambyra** [airbnb/lottie-web#807]
Hi,

I have a couple of animations _(four icons)_ on one of my wordpress websites and they are staying in a hidden div _(opens with jQuery toggleClass)._

1. Is it possible to start the animation when the div is open?
2. Can I make the four animations play after eachother, one at the time?
3. Can I change the animation time in some way?

https://culture.niradynamics.se/ _(scroll down to number 5. people)_

Thanks in advance,
Daniel

**Comment by bodymovin** [comment]
I see you're loading each icon in a separate js
for example here:
https://culture.niradynamics.se/wp-content/themes/nira-culture-book/bodymovin/ICON_2/index.js
you can set autoplay to false, and probably you want to set loop to false too, and also name each animation animation instance with a different name, for example: 
````
var animation1 = bodymovin.loadAnimation({...})
````
When you call the toggle class on jquery, you can also call all four animations to play:
````
animation1.play()
animation2.play()
animation3.play()
animation4.play()
````
provided you name each instance animation1,2,3 and 4

**Comment by markusreklambyra** [comment]
Thank you so much, that works beautifully!

Can I 


––––––––––––––––––––––––
Daniel Melin
Webbdesigner / Fotograf 



Mobil 0721-63 08 61
Vxl 013-25 44 40
· · · · · · · · · · · · · · · · · · · · · ·
Markus Reklambyrå
Repslagaregatan 24
582 22 Linköping
· · · · · · · · · · · · · · · · · · · · · ·
E-post daniel@markus.se
 <mailto:daniel@markus.se>www.markus.se <http://www.markus.se/>
