### ISSUE TITLE
A first rendering should not be run when the "autoplay" parameter is false

### ISSUE THREAD

**Issue by edouardmercier** [airbnb/lottie-web#809]
Hello.

Even with the latest version of bodywin v5.1.3, when created an animation via the `bodymovin.loadAnimation()` function with a parameter with field `autoplay`set to `false`, a first rendering is done on the `CanvasRenderer`, i.e. the `CanvasRenderer.renderFrame()` method is invoked. This seems to be due to the `AnimationItem.waitForFontsLoaded()` method…

Could you check whether this can be fixed. The current work-around is to render the HTML5 canvas to its original state after having loaded the animation.

Thank you for your support.

**Comment by bodymovin** [comment]
Hi not sure I follow.
If autoplay is set to false it renders the first frame or does it play the whole animation?

**Comment by edouardmercier** [comment]
You are right, the first frame is rendered, but I wish it would not because the auto-play is false: does it make sense to you? Do you think the current behavior may be changed?

**Comment by bodymovin** [comment]
no sorry, by design autoplay set to false will render the first frame and stop there.
But you can hide the canvas using display none until you want to show it on your side.

**Comment by edouardmercier** [comment]
OK. I cannot hide the canvas because I render the animation over a canvas on which I already draw something by using the `onEnterFrame` callback. An extra option which enables to disable the first drawing would be great, in addition to the `autoplay` parameter.
