### ISSUE TITLE
Playback cut off bug

### ISSUE THREAD

**Issue by phantomboogie** [airbnb/lottie-web#811]
I want to report a bug where animations would cut off and go blank at the end of playback.

On page load, all the animations would load. 
On initial playback, the animation gets cut off at the end. 
When I trigger the animation on hover, it becomes visible, plays through but will cut off again. 

I managed to fix this problem by extending my layers/precomps beyond the set the timeline.

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by phantomboogie** [comment]
Yup, here you go.  - https://github.com/airbnb/lottie-web/files/1620178/Illust_ForHernan.zip

The leaf animation layers go beyond the set timeline while the mountain animation doesn't. By extending the layers past the end of the comp, I was able to fix the issue. 

I also noticed when the animations were set to autoplay and loop, that the bug didn't happen.

**Comment by bodymovin** [comment]
Hi, this is fixed on version 5.1.7
