### ISSUE TITLE
Blank/white screen once rendered and viewing the html demo

### ISSUE THREAD

**Issue by joelfriendy** [airbnb/lottie-web#813]
[sip.aep.zip](https://github.com/airbnb/lottie-web/files/1621476/sip.aep.zip)

I am trying to render and export this file in after effects but a blank white screen appears when I render and view the html demo. I was expecting to see the 3 second animation which I created in after effects, which I have done successfully before. I rendered the file using the demo setting and was unable to see the animation. Any help with this would be very useful.

**Comment by joelfriendy** [comment]
[sip.json.zip](https://github.com/airbnb/lottie-web/files/1625782/sip.json.zip)

The json file generated is very short and doesn't look complete for the after effects file.

**Comment by bodymovin** [comment]
I see there is a "sip" comp with no layers on it.
Is it possible that you've tried exporting that one?

**Comment by joelfriendy** [comment]
Oh yes thank you so much!

**Comment by clincdrew** [comment]
My bodymovin HTML preview is also showing up blank...I have no idea why. I have exported other animations using it and they all have been fine. I'm stumped
[GoMarket.zip](https://github.com/airbnb/lottie-web/files/2312162/GoMarket.zip)

**Comment by Dre-121** [comment]
I'm now currently having this issue with the latest vers 5.6.10. It was creating HTML files ok but now I have worked a little more on the animation it's just spitting out a blank white HTML page. Any help pls? Tried so many different things but also stumped.

**Comment by bodymovin** [comment]
@Dre-121 can you share the json or the .aep?

**Comment by Dre-121** [comment]
[JSON files_v1.zip](https://github.com/airbnb/lottie-web/files/4710204/JSON.files_v1.zip)
Thanks

**Comment by bodymovin** [comment]
@Dre-121 I see the animation working fine. If you are having trouble using the demo.html, it's because browsers block images from being loaded from local file systems. If you upload the animation to a web server, you'll see it working fine.

**Comment by geoffkhli** [comment]
Hi @bodymovin, I'm trying to create an animated web banner for use on Adwords, and am also getting a white screen when I export from AE using Bodymovin – if I share the packaged files with you, would you be able to let me know what I'm doing wrong?

**Comment by verakoss** [comment]
Hi, @bodymovin I'm trying to export a simple animation to .json and for some reason, after render and during the preview, it shows only a white screen. Can you tell me what's wrong? I'm using AE 2021 (build 8).
[kids app.zip](https://github.com/airbnb/lottie-web/files/7025805/kids.app.zip)
Attached the files
