### ISSUE TITLE
Is there a way to export a frame as a svg file ?

### ISSUE THREAD

**Issue by ChloeLuminet** [airbnb/lottie-web#814]
Hi, I guess the title says it all.
I would like to display a svg image of the first frame of my animation in case it takes some time to load the whole animation. It would be great if I could export this first frame from ae, or extract it from the .json. Do you have any idea of how to do that ?

Please avoid technical terms, graphic designer here :)
(or talk technical and I'll repeat to my developer)

Thanks !

**Comment by bodymovin** [comment]
On the AE extension, if you go to Preview, there is a button that says "screenshot" that will get you a single frame of the animation as an svg.

**Comment by ChloeLuminet** [comment]
Wow, cool. Thanks !

**Comment by mattpetri** [comment]
This is an extremely useful feature, and actually it took quite a lot of googling to arrive here. We've used this for the exact same reason. Many times a bodymovin animation is a 150k+ and if you have multiple on a page, you definitely want a placeholder of the first frame. 

I would suggest to the team that you improve the UX of this, possibly even just by relabeling buttons to make more sense, as this is a feature many people could use. To my knowledge, this is also the only way to get an SVG out of After Effects in general. As After Effects becomes a more common tool for more types of designers, SVG export is needed functionality.

**Comment by carlos-dubon** [comment]
you can do the same with the Figma extension
