### ISSUE TITLE
Help with exports

### ISSUE THREAD

**Issue by kerrylofton** [airbnb/lottie-web#815]
I'm having quite a few issues with exporting. We are using bodymovin to create an interactive app with various scenes. Unfortunately although all the animation is done we can't seem to get it to export. We've run into tons of issues involving merge paths and converting illustrator layers to shape paths and I believe we got it all figured out but now I'm not sure what the issue is. We first got the following error about 3D cameras-  "You're using a 3d camera. Try the html renderer."

There are no cameras in the project at all and even after deleting 3D layers hoping that would fix it, it gave me the following error- Uncaught TypeError: Cannot read property 'length' of undefined

The project is extremely hefty with tons of layers and precomps and after hours of hiding, deleting and rearranging layers I still don't have a solution. Any thoughts on what I could be missing?

**Comment by bodymovin** [comment]
Hi, can you share the .aep so I can take a look?

**Comment by kerrylofton** [comment]
Can I email them to your email on your account? The project is still confidential at this point. I;m sending AEP as well as the graphics folder. Also, we did do some more trouble shooting and this is the error we are dealing with - Cannot read property 'viewData' of undefined

**Comment by psql** [comment]
Same issue... The composition called 'confuzzle' doesn't work. It works in the Preview panel though..

Here's my file: https://cl.ly/ouVJ

![image](https://user-images.githubusercontent.com/688842/35074250-f8d7de92-fbba-11e7-84b1-2a21996125cb.png)
