### ISSUE TITLE
Issues with different language

### ISSUE THREAD

**Issue by sbsomya** [airbnb/lottie-web#816]
Having issue with different language like hindi (devnagri)
The each glyph is seperated is there any possibility of a fix with this

Error image u can see the matra's in hindi are seperated
![Error image](https://user-images.githubusercontent.com/15935666/34879156-5767f9d4-f7d2-11e7-996d-a109f1257212.png)

Correct Image for reference 
![Correct Image](https://user-images.githubusercontent.com/15935666/34879206-75d301ca-f7d2-11e7-90ef-bc4d87fafac9.png)

**Comment by bodymovin** [comment]
Hi can you share the project and the font you're using?

**Comment by sbsomya** [comment]
Hi actually modifying the data at run time before initializing the original data json is 
[title 6.txt](https://github.com/airbnb/lottie-web/files/1627966/title.6.txt)
(Sorry modified the extension to txt as json was not acceptable)

And the code is 
```
bodymovinData.layers[0].t.d.k[0].s.t = "यह मेरी पहली कैप्शन है";
bodymovinData.fonts.list[0].fFamily = "Noto Sans";
```

[Noto Sans Font](https://fonts.google.com/?subset=devanagari&selection.family=Noto+Sans)

**Comment by bodymovin** [comment]
After some research it seems that "े" is an intra-syllabic vowel.
Do you know if this is the only character that should be rendered as part of the following letter?

**Comment by sbsomya** [comment]
I know hindi so there are many characters like this
http://jrgraphix.net/r/Unicode/0900-097F
You can check out here
Also other languages have this case actually somehow need to find out if a character is a fresh character or is being added as an addition to the previous character 

In this case   "म" is a character and  "े" is added to the previous character

**Comment by bodymovin** [comment]
Does all those characters always get combined with the previous character?

**Comment by sbsomya** [comment]
Not all just the ones which have a dotted circle in it

**Comment by sumitbatwani** [comment]
Hi, 
We have been using lottie-web extensively for various font types. This issue is fixed for hindi text but still facing same issue for tamil and telugu text. 

Please look into this. Let me know if you need more information. 
Thanks

**Comment by bodymovin** [comment]
@sumitbatwani hi, can you provide some examples? And fonts if needed for the examples

**Comment by sumitbatwani** [comment]
Hi, I tried the **Tamil and Telugu** translation of the word **TEST** using the font **Noto Sans**

Error Images
1. Telugu (పరీక్ష)

<img width="358" alt="Screenshot 2020-11-24 at 1 15 52 AM" src="https://user-images.githubusercontent.com/42246821/100008488-8a911980-2df3-11eb-9666-17aead5e84d0.png">

2. Tamil (சோதனை)

<img width="355" alt="Screenshot 2020-11-24 at 1 21 21 AM" src="https://user-images.githubusercontent.com/42246821/100008537-954bae80-2df3-11eb-98f7-0efffbaf2ee4.png">

Expected Output to render word in the given format

**పరీక్ష** (Telugu translation for the word Test)
**சோதனை** (Tamil translation for the word Test)

Please look into this issue and let me know if more information is required. Thank You.

**Comment by bodymovin** [comment]
@sumitbatwani an .aep with the appropriate font would be very helpful to address this.

**Comment by anilkchandra** [comment]
@bodymovin Hi, Any updates on Telugu & Tamil fonts? thanks.
