### ISSUE TITLE
Roving Keyframe Issue

### ISSUE THREAD

**Issue by alexr8** [airbnb/lottie-web#817]
* **Browser and Browser Version:** Chrome (63.0.3239.132) / FF (57.0.4)
* **After Effects Version:**  14.2.0.198

Hi, there seems to be an issue with roving keyframes, the electrons moving around the outside of the centre blob in the attached example are very jolted whereas in the after effects file it is smooth movement (using roving across time). It says roving across time is supported in this version, am i doing something wrong?

https://www.dropbox.com/s/sxeihlc7rq3pyms/bodymovin%20test.zip?dl=0

**Comment by bodymovin** [comment]
Hi, fixed in version 5.1.17
