### ISSUE TITLE
Bodymovin renders only solid color

### ISSUE THREAD

**Issue by ghost** [airbnb/lottie-web#818]
Hi! 
Does anyone know why Bodymovin renders only a solid color from this project?
[Fire Sparks.zip](https://github.com/airbnb/lottie-web/files/1628813/Fire.Sparks.zip)

UPDATE
I think that the particle effect is not supported...

**Comment by alexr8** [comment]
There is a handy guide of the supported AE features here: http://airbnb.io/lottie/supported-features.html

**Comment by bodymovin** [comment]
Hi, yes unfortunately lottie doesn't support many effects.
This are the only ones supported and only by the web version
https://github.com/airbnb/lottie-web/wiki/Effects
