### ISSUE TITLE
The tips and corners of strokes are wiggling/shaking when exported

### ISSUE THREAD

**Issue by porkbutt** [airbnb/lottie-web#819]
Hello,

I'm using AE CC 2018 on a Mac and Bodymovin 5.0.1. I have an animation made from masks and the stroke effect in AE that, when exported, causes some odd behavior with strokes (everything should be smooth, but instead the lines stutter on export). Forgive me if it has already been asked and answered, but I can't seem to locate a thread that solves this issue. I have attached a .zip of the AE and Bodymovin files. Thank you for any help.

[Portrait_Bodymovin.zip](https://github.com/airbnb/lottie-web/files/1628823/Portrait_Bodymovin.zip)

**Comment by DaanDirk** [comment]
https://www.dropbox.com/s/vstnpxtxjexc5oi/Portrait_Bodymovin%20DD.zip?dl=0

I tried setting the spacing to 0 on the stroke effect. But it remains a little jittery.
The effect stoke consists of a sting of dots along the path.
It seems that bodymovin mimics that quite accurately. 

You want to convert it to a shape layer.
Those strokes work like real strokes/lines. 

Nice portrait!

**Comment by porkbutt** [comment]
Very helpful, thank you!
