### ISSUE TITLE
My gzip file is not working

### ISSUE THREAD

**Issue by julianebrazil** [airbnb/lottie-web#820]
I save the file from the option "Get the player gzipped" from the after effects, and it don't works.

The image file is below, what could have happened?

![gzip](https://user-images.githubusercontent.com/35423233/34916320-7fdae97a-f91d-11e7-9c40-69c94533d5b6.png)

**Comment by bodymovin** [comment]
Gzipped files need to be served from a web server with the appropiate headers.
How are you trying to load it?
