### ISSUE TITLE
Bodymovin in WordPress Ninja Forms

### ISSUE THREAD

**Issue by cdweb** [airbnb/lottie-web#821]
A designer I'm working for loves animation and has sent me bodymovin json files to replace all the buttons and links on a site. I was able to replace all the links except the submit button on Ninja Forms inside WordPress. 

I tried everything from adding a class to the input through the plugin dashboard, from trying to add the class through javascript, to even editing the plugin myself and adding a div with the class I need. In the end nothing happens. But I never got it to display. 

The button is an input button, and I went as far as creating a div under the button and align it on top with css. But Ninja Forms adds error text both above and below the submit button and it just throws the alignment off.

Is there any suggestion that you have to replace input buttons from a form with the bodymovin asset? Of if there was a way I could use it as a background image so I can apply it in CSS on hover, that would solve this problem without having to mess with another plugin's javascript.

Thanks

Its WordPress 4.9.1, plugin is Ninja Forms 3.2.8.

Browser is Chrome 63.0.3239.132
Not sure what After Effects the designer used, but it might be the latest from the cloud.

**Comment by bodymovin** [comment]
If you can target the button with javascript, for example selecting it by class or id, you should be able to load the animation directly in the button element.
If you have a link of what you got so far, I can take a look.

**Comment by cdweb** [comment]
I did try. I just went back and added the class that I need to get the
button going. This link is for the homepage, and the button is in the
footer. If you hover over the other buttons on the page, they animate. But
not the contact form. The class I'm using is btn_submit.

http://catcontracting.cubismedia.com/

Thanks


*Coraliz Dereta*
Web Designer and Web Developer
Cubis Media LLC
E: cora@cubismedia.com
P: 602.625.5043

**Comment by bodymovin** [comment]
It's hard to debug, but it seems that the form button is being recreated multiple times, so the animation gets discarded together with the previous version of the button.
Also, you probably need to use the animation in a label that targets the button element.
Something in the lines of this:
https://chodounsky.net/2015/05/12/svg-as-a-submit-button/

**Comment by cdweb** [comment]
Yeah, I thought that and I went as far as to add a div with the class right
under the input field, so that it shares the same parent div and I could
use css to just put the button on top through position absolute. But it
didn't render it either. Thanks for checking.


*Coraliz Dereta*
Web Designer and Web Developer
Cubis Media LLC
E: cora@cubismedia.com
P: 602.625.5043
