### ISSUE TITLE
Bodymovin editor doesn't identify animation layers

### ISSUE THREAD

**Issue by henriqrossatto** [airbnb/lottie-web#822]
* **Browser and Browser Version: Chrome  63.0.3239.132
* **After Effects Version: CC 2015

I develop a simple animation, and when I test if on lottie preview I notice that the bodymovin editor doesn't identify the layer animation for changing colors. I didn't last week a much more complex animation and the editor work normally.  

I'm providing the After Effects file and the data.json of one of the nine animations that are occurring the error.

[Animation_error.zip](https://github.com/airbnb/lottie-web/files/1632887/Animation_error.zip)

**Comment by DaanDirk** [comment]
Hmm, I don't see anything that changes color in the project.
For website integration you can change a layers name to #myName to have a css id that is #myName or .myName for a class.
That way you can target stuff in your project through css.
Is that your question?

**Comment by henriqrossatto** [comment]
Sorry, I think 

I would like to understand about how the exportation work with lottie editor 0.0.4 (bodymovin editor). I export my animation on black, but with the editor, my client can just drop the .json file on lottie preview and customize the color.

My problem is that in this project, when I drop the data.json on lottie preview and try to customize, the editor don't recognize my project or just the text part. But the main animation don't appear for editing the color. 

The animations works good on lottie preview, but my client can't edit the color  in the lottie editor if he needs.

**Comment by DaanDirk** [comment]
Ah.
I'm not sure but I think the inverse alpha matte doesn't help.
When I put those holes directly into a shape layer, it works fine:

https://www.dropbox.com/s/uym09p00h6lng5q/Animation%20%232%20DD.zip?dl=0

color away!

**Comment by henriqrossatto** [comment]
I don't know why, but the error was on the shape layer. One of the animations that I did works, and the other didn't. I import the shape that works to test and fix the problem.

About the alpha matte, I tested before with other animation and works ok too.

Thanks about the feedback
