### ISSUE TITLE
Gradient Effect isn't working!

### ISSUE THREAD

**Issue by armiaka** [airbnb/lottie-web#823]
USING: 
Macbook Pro 2017
After Effects CC 2018
newest Bodymovin (15.1.18)

Hi.

I have a very basic simple animation, which is changing the gradient color of a rectangle:

<img width="783" alt="bildschirmfoto 2018-01-15 um 21 33 28" src="https://user-images.githubusercontent.com/19413079/34960607-d5e4e5ae-fa3b-11e7-8ef0-1d5d30bb37f0.png">

<img width="364" alt="bildschirmfoto 2018-01-15 um 21 33 41" src="https://user-images.githubusercontent.com/19413079/34960609-d60693b6-fa3b-11e7-9671-93da7b15376f.png">

i pull it in the Lottie-Preview Website, to see if its working, and i see this:

<img width="799" alt="bildschirmfoto 2018-01-15 um 21 34 50" src="https://user-images.githubusercontent.com/19413079/34960630-f2022076-fa3b-11e7-82f3-671aec3ec35f.png">

i seriously dont know what i did wrong. I checked, if gradient effect is supported by bodymovin..it is. there is no mask or something. Just a simple rectangle, changing its color.

Please help.

Here is the link to the .aep-file:

https://www.dropbox.com/s/gk1l4rkmvxto3yz/Sterne%20Kopie.aep?dl=0

thank you!

**Comment by armiaka** [comment]
okay, i got a solution. i went for "gradient" in the fill setting. But i would still like to know if it will work with the gradient EFFECT ?

**Comment by armiaka** [comment]
okay, now i tried the gradient fill. so NOT the gradient-effect from the effect panel.

what i got is this:

<img width="289" alt="bildschirmfoto 2018-01-15 um 22 18 57" src="https://user-images.githubusercontent.com/19413079/34961998-2bb42a52-fa42-11e7-93c7-05d2daaaddfb.png">

**Comment by armiaka** [comment]
here is a link for a working file:

https://www.lottiefiles.com/434-gradient-animated-background

**Comment by bodymovin** [comment]
Hi, can you share the .aep with the gradient fill as part of the shape content instead of the effect?
For now, gradient effect is not supported.

**Comment by armiaka** [comment]
https://we.tl/weBQ07bFYt

Go on TESTBODYMOVIN
Am 17.01.2018 um 01:04 schrieb hernan <notifications@github.com<mailto:notifications@github.com>>:


Hi, can you share the .aep with the gradient fill as part of the shape content instead of the effect?
For now, gradient effect is not supported.

**Comment by bodymovin** [comment]
Thanks! Found the issue, will upload a fix soon.

**Comment by armiaka** [comment]
NICE THANK YOU SO MUCH!!!


Am 17.01.2018 um 02:16 schrieb hernan <notifications@github.com<mailto:notifications@github.com>>:


Thanks! Found the issue, will upload a fix soon.

**Comment by armiaka** [comment]
Hey! Any updates?


Am 17.01.2018 um 02:16 schrieb hernan <notifications@github.com<mailto:notifications@github.com>>:


Thanks! Found the issue, will upload a fix soon.

**Comment by armiaka** [comment]
Hi, unfortunately, you fixed the gradient issue only partly. Now, the transition works, but only in black and white!

**Comment by bodymovin** [comment]
make sure you save the .aep project before exporting.
Gradient data is taken from the .aep file directly

**Comment by armiaka** [comment]
lottie preview (after saving):

<img width="641" alt="bildschirmfoto 2018-01-18 um 19 21 07" src="https://user-images.githubusercontent.com/19413079/35114405-dfae3310-fc84-11e7-9b17-4a2a5aa568fe.png">


ae:
<img width="237" alt="bildschirmfoto 2018-01-18 um 19 21 55" src="https://user-images.githubusercontent.com/19413079/35114406-dfca01bc-fc84-11e7-8d91-276336e0d087.png">

**Comment by bodymovin** [comment]
.aep?

**Comment by armiaka** [comment]
https://www.dropbox.com/s/vipxogcsk4v0udb/Sterne%20Kopie%202.aep?dl=0


go on Komp1

**Comment by bodymovin** [comment]
I see it fine when I export it here. But I know sometimes users can' t get to export gradient data correctly.
It might be a couple of reasons
- OS not in English
- AE not in English
- AE and project file in different drives
- Layer names or properties with special characters (which might be related to AE not being in english)
 but I haven't figured out yet what is going on

**Comment by armiaka** [comment]
okay, my AE is in english now, still doesnt work, can you send me the json?

**Comment by bodymovin** [comment]
[data.zip](https://github.com/airbnb/lottie-web/files/1644885/data.zip)
sure
here it goes

**Comment by aivanchu** [comment]
Bro this is my aep
[https://drive.google.com/open?id=1fu36WuZ_nxT_yP8rYMSx2Rn9TqpGzS00](url)
my AE is English too but my gradient stroke still doesnt work on Lottie viewer app

**Comment by bodymovin** [comment]
@aivanchu Hi, I see your animation working fine. Here is the json
[data.zip](https://github.com/airbnb/lottie-web/files/1654013/data.zip)

**Comment by aivanchu** [comment]
@bodymovin WOW Thanks for your help.
How do you do it? Where is my problem?
Can you provide me the aep file?

**Comment by Manasissue** [comment]
hey i also have that gradient problem. Evrerything seems to be right: english, shapes, precomps, bits etc. Did u get any gradient json?

**Comment by fionalien** [comment]
I  have the same problem, I use windows / after effects cc2018 I tried what eveyone said and the gradient doesnt work. so I change work my project on Macbookpro / after effects cc 2015 and now it works....perfectly :dancing_women:

**Comment by Troepster** [comment]
I have the same problem After Effects cc 2018, what I've done as a workaround is duplicating the layer, and changing the opacity of the one layer to reveal the other gradient color.

The the right way of doing it, but it works.

**Comment by MZ166** [comment]
Hello, 

I'm having the same problem, I'm animating a logo that has a gradient, I tried both the '4-Color Gradient' and 'Gradient Ramp', but when I export the lottie file, the layer goes back to it's original solid color, and the gradient effect doesn't get rendered. 

Link to the file to download: https://we.tl/t-iq7nYteN21

I'm using Macbook 2013, After Effects CC 2017. 

I tried most of the options suggested above, and tried to save the file as CC 2013, and export the lottie files from there, but it didn't work. I also tried to import the extension to my old laptop that has After Effects CS5, but the extension isn't supported. 

Please let me know what can I do so that the gradient effect can be exported into a JSON extension. 

Thank you!

**Comment by bodymovin** [comment]
Hi @MZ166, are you using the gradient property of shape layers? That's the one that is supported.
Gradient Effects are not

**Comment by MZ166** [comment]
OMG thank you!! I didn't get that when reading the thread! It is working now

**Comment by ralts00** [comment]
@MZ166 please, send me your .aep :)

**Comment by ssjeevanraj** [comment]
Hi, I am facing the same issue. I've tried all the methods from what you said above. but it was not still working. I'm using Aftereffects cc 2017 in windows 10 OS. Help me to find the Solution

**Comment by okapii** [comment]
For me colored gradients show up as black and white. Any updates on the situation?

**Comment by amyxhuang** [comment]
> Hi @MZ166, are you using the gradient property of shape layers? That's the one that is supported.
> Gradient Effects are not

I'm experiencing the same issue here. Gradient wouldn't show up in the exported html/json. I made sure the language is all in English... Any other tips as to how I can make the gradient show?

**Comment by samdiener** [comment]
There is a feature in the Lottiefiles Preview Window (German):
<img width="186" alt="Bildschirmfoto 2020-03-31 um 18 24 55" src="https://user-images.githubusercontent.com/10726410/78051628-40e45200-737e-11ea-9871-9e1c794849ed.png">

There you are able to change the gradients of single objects:
<img width="842" alt="Bildschirmfoto 2020-03-31 um 18 27 30" src="https://user-images.githubusercontent.com/10726410/78051719-62ddd480-737e-11ea-9fbf-f04cb17ad173.png">

**Comment by FilipeBranco18** [comment]
Hi. I am having the same problem. I have a shape with a gradient fill in after effects, and when i test it in Lottie App it shows only the first color of the gradient.
I've tried every possible solution already mentioned here.
Thank you.

**Comment by bodymovin** [comment]
@FilipeBranco18 hi, can you share your .aep project?

**Comment by FilipeBranco18** [comment]
Thank you for your reply, but my schedule was tight, so i went and eliminate the gradient from my project.

**Comment by hamed4393** [comment]
![Ramp Gradient Test for lottiefiles HMD 01](https://user-images.githubusercontent.com/64668295/80851737-ccc8f280-8c38-11ea-85fd-b53b13ef48c0.PNG)

1- use and add Gradient Fill(or Gradient Stroke) to your shape (don`t use ramp effect)
2- Edit Gradient in it
3- Before rendering via Bodymovin Save your After Effect`s Project

**Comment by oleklaenfoth** [comment]
Hey, i have the same problem with the gradients.. I tried everything as described above, but the gradients are still displayed in black and white :(

Additionally there is a problem with the animated mask layers which I cannot solve.

Can anyone help me? [Here](https://we.tl/t-U5ThKvQXNi) the After Effects project.
Thanks a lot in advance!

**Comment by bodymovin** [comment]
@oleklaenfoth I guess your OS is in German because when opening the project I see many properties set in that language.
That usually is a problem when exporting gradient data because of the way it is retrieved.
I don't have a solution, but you can try renaming the gradient property tree and see if it gets fixed.
Regarding the mask, it's because you are using an inverted mask masked with a matte mask and that is not fully supported. Perhaps you can achieve the same solution with shape paths and changing the path direction.

**Comment by oleklaenfoth** [comment]
@bodymovin Hey, thanks for the quick response! I had changed AE to English and then exported it, but unfortunately this didn't help either. I will try the renaming again!

Thanks for the tips!

**Comment by deborahdiazr** [comment]
I found out that if you remove the stroke from your shape, the gradient works

![image](https://user-images.githubusercontent.com/1519086/87600932-5f622500-c6b1-11ea-8ffd-a298cc1e7601.png)

**Comment by whizzkkid** [comment]
I made a moving gradient background here using after effects and it is not working 

heres a link to a video
[https://www.dropbox.com/s/q7wr1pi2vtmdjgl/Screen%20Recording%202020-12-16%20at%207.34.42%20PM.mov?dl=0](url)

I try few steps to fix it by precomposing the layers and also to rename the the 4 layer gradient effect
but it didn't resolve the issue

heres a link to the snap
![Screenshot 2020-12-16 at 8 00 40 PM](https://user-images.githubusercontent.com/54703305/102361740-911d4600-3fd9-11eb-9021-c244a33338c4.png)

**Comment by Spicygeorge** [comment]
@whizzbbig I'm working on an animated gradient background and have the same issue, did you find a solution?

**Comment by whizzbbig** [comment]
> @whizzbbig I'm working on an animated gradient background and have the same issue, did you find a solution?

No there is no solution for that I talked to the Lottie developer he said that the preset 4-color-gradient is not supported at the moment he said they are many bugs to fixed in Lottie. As I want to make it eligible on web I just end up watching a tut to make a moving gradient.

**Comment by skriv** [comment]
Hey guy's 
The gradient is working. 
1. Fill to gradient, Lottie showed BW colors
2. Save the project
3. Profit

![image](https://user-images.githubusercontent.com/5947053/121392601-5c2ef200-c971-11eb-9009-9c75faf34afa.png)
![image](https://user-images.githubusercontent.com/5947053/121392678-6cdf6800-c971-11eb-8803-fd79a9158212.png)

**Comment by sreuter** [comment]
Just had a file where gradients were not working. That file was originally created on a Mac configured to German (where the export actually worked fine). Finding all objects with Umlauts and replacing them made the export work!

**Comment by paulfg1** [comment]
**Same problem** here... tried all steps above me. I changed my version from **German** to **English**, but I think that you have to **create** the **file** **again** or??

<img width="599" alt="Screen Shot 2022-08-12 at 10 01 12" src="https://user-images.githubusercontent.com/111115286/184311869-69a94149-83c9-4ce6-abd7-89d6b7986987.png">

**Comment by Ahmadss2020** [comment]
Hi, I had the same problem and I solved it, first, you have to check the order of the shape like you have to be sure that the gradient file or gradient stroke comes ofter the path or the rectangle ..., then you have to save the file before exporting the Lottie ...then you ll get the gift ::))

**Comment by Ahmadss2020** [comment]
Hi, I had the same problem and I solved it, first, you have to check the order of the shape , for example >> you have to be sure that the gradient file or gradient stroke comes after the path or the rectangle ..., then you have to save the file before exporting the Lottie ...then you ll get the gift ;)
