### ISSUE TITLE
Javascript error - Uncaught TypeError: thisComp.layer(...).effect is not a function

### ISSUE THREAD

**Issue by davidhill001** [airbnb/lottie-web#824]
**Tell us about your environment**
MacBook Pro Retina 2015

* **Browser and Browser Version:** Chrome 63.0.3239.132 (Official Build) (64-bit)
* **After Effects Version:** CC 2017

**What did you do? Please explain the steps you took before you encountered the problem.**
I exported my project with Bodymovin 4.10.2 and added the following code to my page:

Head:
<script src="https://cdnjs.cloudflare.com/ajax/libs/bodymovin/4.13.0/bodymovin.js"></script>

Body:

<div id="logo"></div>

    <script>

        $(function() {

            bodymovin.loadAnimation({
                container: document.getElementById("logo"), // the dom element that will contain the animation
                renderer: 'svg',
                loop: true,
                autoplay: true,
                path: 'data.json' // the path to the animation json
            });

        });

    </script>

**What did you expect to happen?**
The animation be displayed on my webpage.

**What actually happened? Please include as much _relevant_ detail as possible.**

I receive an error in the console which says:
Uncaught TypeError: thisComp.layer(...).effect is not a function
    at ValueProperty.eval (eval at initiateExpression (bodymovin.js:12537), <anonymous>:2:36)
    at ValueProperty.executeExpression [as getValue] (bodymovin.js:12756)
    at TransformProperty.processKeys [as getValue] (bodymovin.js:2494)
    at ICompElement.BaseElement.prepareFrame (bodymovin.js:6142)
    at ICompElement.prepareFrame (bodymovin.js:8121)
    at ICompElement.prepareFrame (bodymovin.js:8141)
    at SVGRenderer.renderFrame (bodymovin.js:5809)
    at AnimationItem.renderFrame (bodymovin.js:8820)
    at AnimationItem.gotoFrame (bodymovin.js:8812)
    at AnimationItem.checkLoaded (bodymovin.js:8786)
[Archive.zip](https://github.com/airbnb/lottie-web/files/1636059/Archive.zip)
<img width="1351" alt="screen shot 2018-01-16 at 17 01 49" src="https://user-images.githubusercontent.com/23187700/35001570-fd1f7eec-fade-11e7-8211-69366afe78ef.png">

**Comment by bodymovin** [comment]
Hi, I'll check it when I get home, but make sure your expressions are not targetting a hidden layer, or any layer that won't get exported.

**Comment by olemartin** [comment]
@bodymovin 

This is my code
```
const bodymovin = require('bodymovin');
        var animData = {
            container: document.getElementById('highfive'),
            renderer: 'svg',
            loop: false,
            autoplay: true,
            animationData: highfive,
        };
        bodymovin.loadAnimation(animData);
```
The json is loaded through import
[highfive.aep.gz](https://github.com/airbnb/lottie-web/files/2266016/highfive.aep.gz)
Had to rename the file to .gz in order to upload it here.

**Comment by bodymovin** [comment]
@olemartin the extension doesn't support adjustment layers.
Try changing the layer "Physics Adjustment" to a regular layer and set the opacity to 0 and it should work.

**Comment by olemartin** [comment]
@bodymovin thanks!

It seems to work here though: https://codepen.io/olemartin/pen/NBLmLN
