### ISSUE TITLE
Mask Problem with Animation bodymovin export 

### ISSUE THREAD

**Issue by elisathielemann** [airbnb/lottie-web#825]
Hey, I have the same problem :( Did my animation with Masks and in the bodymovin preview everything works fine. But when I put the .json in the lottie editor, the mask did not work anymore. I need to export as a svg file, because I need the logo animation for my mobile app. Do you have any idea how to fix? Here is the link in lottie: not working in any browser sadly :(

In the screenshot preview in after effects bodsymovins shows me the correct animation. when I use the .json file in lottie, the mask are not used anymore :(

https://www.lottiefiles.com/share/2SpDDe

**Comment by bodymovin** [comment]
Closing, reopen if needed.
