### ISSUE TITLE
AI's shapes broke my animation?

### ISSUE THREAD

**Issue by Isaaaaaaaaaaac** [airbnb/lottie-web#826]
**Tell us about your environment**
iMac 2011 21inch

* **Browser and Browser Version:**
I'm using my animation in React Native

* **After Effects Version:**
AE CC 2018

**What did you do? Please explain the steps you took before you encountered the problem.**
Hello, I'm making some animations for an app starting from Ai's vector levels, I noticed that at the moment of rendering will be exported a repository with images if those levels are not turned into shape layers on Ae. But turning my Ai levels into form levels  causes the app crashes... so my solution was to remove all Ai levels from the composition, but this made the animation still.

**What actually happened? Please include as much _relevant_ detail as possible.**
Or the app crashes or the animation is still.

[animazione-case.zip](https://github.com/airbnb/lottie-web/files/1638684/animazione-case.zip)

**Comment by bodymovin** [comment]
Have you converted the layers to shapes in AE?
