### ISSUE TITLE
organic animations (puppet)

### ISSUE THREAD

**Issue by vitorlinte** [airbnb/lottie-web#827]
hi,

I need the dynamic puppet animations of this plant (gif below) and some others to be displayed on the .json generated by bodymovin; 

![plant_preview](https://user-images.githubusercontent.com/31015829/35066305-49249600-fbb7-11e7-8b92-f8fa19bca38e.gif)

any suggestions on how to animate/implement this kind of animation with bodymoving?

thanks,

**Comment by alexsandro-xpt** [comment]
I don't know if is possible because it is a gif imagem.
