### ISSUE TITLE
Does not want to render, the fill effect

### ISSUE THREAD

**Issue by euppi98** [airbnb/lottie-web#828]
Faced such a problem that the lottie does not want to work with the fill effect. Although the wiki indicates that it can.

p.s. Stroke effect its works

![screen shot 2018-01-18 at 12 30 34](https://user-images.githubusercontent.com/23306157/35090761-b268e71c-fc4b-11e7-87b7-3a340952c0e2.png)
![screen shot 2018-01-18 at 12 31 39](https://user-images.githubusercontent.com/23306157/35090763-b615338e-fc4b-11e7-8664-661463365fd9.png)

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by euppi98** [comment]
here
[fill.aep.zip](https://github.com/airbnb/lottie-web/files/1645779/fill.aep.zip)

**Comment by euppi98** [comment]
What say?

**Comment by bodymovin** [comment]
Hi, I'm checking your file.
That shape layer has no content, only a mask and the fill effect is being applied to the mask directly.
I didn't even know this was possible.
Is there a reason why you're creating your shapes this way?

**Comment by james-lane** [comment]
I'm also getting this issue. Does it work if you try dragging the data.json file into https://www.lottiefiles.com/preview ?

**Comment by james-lane** [comment]
I can get mine working by using the old https://github.com/chenqingspring/bodymovin version instead of the latest lottie!?

bodymovin.js seems to load <defs> before <g clip-path...> rather than the opposite which happens when you use lottie.js.

**Comment by euppi98** [comment]
I watched this video - https://youtu.be/67ZP3PZ0l2I and thought it would work for Lottie.

**Comment by bodymovin** [comment]
Using a regular shape with a normal fill should work for this cases.
