### ISSUE TITLE
Lottie Does not work with the Adjustment layer?

### ISSUE THREAD

**Issue by euppi98** [airbnb/lottie-web#829]
![screen shot 2018-01-18 at 12 48 02](https://user-images.githubusercontent.com/23306157/35091485-da73fd4e-fc4d-11e7-9fb0-cd36ac3f9ee5.png)
![screen shot 2018-01-18 at 12 47 14](https://user-images.githubusercontent.com/23306157/35091490-dba0344e-fc4d-11e7-834b-4aac800b52e4.png)

**Comment by jamesdeantv** [comment]
Lottie doesn't work with adjustment layers.  You will need to add the adjustments to the individual layers.

**Comment by euppi98** [comment]
Thank you)

**Comment by num3ric** [comment]
Is the exporter extension source code available somewhere to allow users to make such additions (adjustment layer support)?

**Comment by bodymovin** [comment]
@num3ric here is the code.
https://github.com/bodymovin/bodymovin-extension
Adjustment layers are now being exported but as null layers for now. How are you thinking of using them?

**Comment by num3ric** [comment]
@bodymovin Ah wonderful, I'll have look!

We're writing our own importer and renderer in OpenGL/C++, so far so good!  The goal would be to support a few adjustment layer effects. Currently, I'm converting layers below an adjustment layer into a precomp, which I believe yields the same result and is supported by the exporter (v5.6.5). However, exporting the adjustment layer as a bare layer object with an `effects` array would be sufficient for our needs. This would minimize disruptions to our designers' workflow.

**Comment by num3ric** [comment]
@bodymovin I see that this was already changed in v5.6.6. I will simply update to the latest, thanks!

**Comment by bodymovin** [comment]
@num3ric It was, but you won't be able to identify if it is an adjustment layer or a null layer. Would that be enough for you?
If not, for now you can name the layer somehow.

**Comment by lfireflyl** [comment]
Hi, i add the adjustments to the individual layers, but after render I don't see any changes, whats problems could be?
