### ISSUE TITLE
Bodymovin opens but doesn't show the interface

### ISSUE THREAD

**Issue by alinafs** [airbnb/lottie-web#830]
I installed today the bodymovin, but when I opened in after effects CC 2018 the interface is blank. I can click in the buttons, but they doesn't show up. I tried reinstall and didn't fixed

![prova](https://user-images.githubusercontent.com/35572790/35109621-07111390-fc5e-11e7-86c1-33fb4329ea4a.PNG)

**Comment by bodymovin** [comment]
Hi, what is your OS, and OS language?

**Comment by alinafs** [comment]
Actually is Windows 10 and the language is portuguese. In my mac is working perfectly.

**Comment by bodymovin** [comment]
I'm guessing it might be related to that, but I'm not totally sure.
Is AE in portugese too?

**Comment by alinafs** [comment]
Yes, is in portuguese too

**Comment by bodymovin** [comment]
I'm not sure what could be going on.
Do you have any other CEP plugins that work correctly?

**Comment by alinafs** [comment]
Actually, I just noticed that the AE initial window is in the same way... So, maybe this is not a problem with the plugin. I don't know.

![prova 2](https://user-images.githubusercontent.com/35572790/35251630-2ada29b6-ffc3-11e7-9afa-cb0270fe2fe2.PNG)

**Comment by pegeseus** [comment]
FWIW, I have an issue where I need to alt-tab out and back in to AE every time I click the "destination folder" icon in bodymovin.  The dialog does not appear until I do this- 100% repeatable.
I'm on Windows 7, AE CC 2017.  Not sure if it's related.

**Comment by bodymovin** [comment]
closing. Reopen if issue is still happening
