### ISSUE TITLE
Does not animate points to nulls dynamic connection

### ISSUE THREAD

**Issue by psql** [airbnb/lottie-web#831]
After Effects 2018, Bodymovin 5.1.4

I have nulls connected to path points for animation via expression. I was just using the .jsx that ships with After Effects 2018.

When I render my comp with bodymovin, it doesn't animate the path points. Had to resort to baking _each_ keyframe for the moment, but this is not ideal, because of the large filesize.

json output baked: https://cl.ly/ovFB
json output unbaked: https://cl.ly/ovSk
.aep: https://cl.ly/ovwE 

(comp name is `irene`)
![image](https://user-images.githubusercontent.com/688842/35123411-0f00bce2-fc70-11e7-97fb-8b06339a6f7f.png)

Thanks for making Bodymovin, it's been really awesome on [screenhole.net](screenhole.net), our experimental project

**Comment by bodymovin** [comment]
Hi, there's a couple of issues going on.
First there's an expression using "ADBE Position_0" to target the x position of an element.
I'm implementing it right now so it will be supported on the next version. For now, you can replace on the expression in the "blink" layer this line:
`
var myMaster = thisComp.layer("Slider Control")("ADBE Transform Group")("ADBE Position_0");
`
with this line
`
var myMaster = thisComp.layer("Slider Control")("ADBE Transform Group").xPosition;
`

Second, there are three consecutive layers that have TrkMatte set.
That doesn't work in AE and breaks with the plugin.
If you remove the TrkMatte to layer "---matte 2" by setting it to none, it should work

**Comment by psql** [comment]
Worked perfectly thanks so much!
