### ISSUE TITLE
how to redirect to different page

### ISSUE THREAD

**Issue by m-mokhtar** [airbnb/lottie-web#834]
**Tell us about your environment**
windows 8.1
* **Browser and Browser Version:**
 firefox latest version
* **After Effects Version:**
CC 2015
**What did you do? Please explain the steps you took before you encountered the problem.**
i can't redirect to a different page when clicking on an element on my loaded page using this code:
  var animationData = 'animation data here'
    var params = {
        container: document.getElementById('lottie'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        animationData: animationData
    };

    var anim;

    anim = lottie.loadAnimation(params);
	
	anim.addEventListener('DOMLoaded', function(){

$("#buttons").on("click", function () {
  window.location.replace('contactus.html');
  });
})
**What did you expect to happen?**
redirect to a different page
**What actually happened? Please include as much _relevant_ detail as possible.**
nothing happened at all, although the style for the pointer changed for the element (buttons) it doesn't redirect to a different page.
**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by m-mokhtar** [comment]
never mind, jquery libraries was not loaded, in case anybody needs help with this again, you have to include
<script src="jquery.js"></script>
<script src="jquery-ui.js"></script>
<script src="jquery-ui.min.js"></script>
in the code or call it from it's link to get the latest version

**Comment by bodymovin** [comment]
Glad you figured it out.
