### ISSUE TITLE
Error in Console

### ISSUE THREAD

**Issue by tarlyo** [airbnb/lottie-web#836]
Hi,

I am getting the following error in my console:

`Uncaught SyntaxError: Invalid or unexpected token (bodymovin.js:7)`

Everything seems to be working fine, but I am worried that the error is slowing down my site. The link to my site is https://www.yaelhubert.com/.

Please let me know what I can do to resolve the error!

Thanks in advance!

**Comment by bodymovin** [comment]
Hi, nice animations!
Any reason why you're loading the player from many different places in your site?

**Comment by tarlyo** [comment]
I'm not the best at coding so that was the only way I could figure out how to load multiple animations on the same page. Is there a better way to do this? The way I figured was to change the ID (or class, I can't remember) in the bodymovin.js file to the ID (or class) of my bodymovin element.

**Comment by tarlyo** [comment]
@bodymovin do you have any insight for me?

**Comment by bodymovin** [comment]
You should load the js player only once.
No need to load one per animation.
