### ISSUE TITLE
Firefox ESR (52) - Lib broken 

### ISSUE THREAD

**Issue by marcomattes** [airbnb/lottie-web#840]
I have a problem with Lottie. In Firefox ESR (52.6.0, 53, 54 (64-Bit)) Mac (10.13.2) & Windows (7, 10), the animations do not load.
An error in the console is displayed for this. Error did not occur with version 4, but unfortunately can not return to v4 because we have dependencies to version 5.

Used: lottie-web version 5.1.4 jQuery 1.12.4 (same on 2.X) 

TypeError: invalid arguments  lottie.js:281:11
	createTypedArray http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:281:11
	DashProperty http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:3913:22
	SVGStrokeStyleData http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:6361:11
	SVGShapeElement.prototype.createStyleElement http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:7274:23
	SVGShapeElement.prototype.searchShapes http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:7377:32
	SVGShapeElement.prototype.createContent http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:7264:5
	_prototype.initElement http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:6277:13
	SVGShapeElement http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:7248:5
	SVGRenderer.prototype.createShape http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:5606:12
	BaseRenderer.prototype.createItem http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:5482:20
	SVGRenderer.prototype.buildItem http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:5703:19
	BaseRenderer.prototype.buildElementParenting http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:5535:17
	HierarchyElement.prototype.checkParenting http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:6068:10
	HierarchyElement.prototype.initHierarchy http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:6041:6
	_prototype.initElement http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:6272:13
	SVGShapeElement http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:7248:5
	SVGRenderer.prototype.createShape http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:5606:12
	BaseRenderer.prototype.createItem http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:5482:20
	SVGRenderer.prototype.buildItem http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:5703:19
	BaseRenderer.prototype.buildAllItems http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:5498:9
	BaseRenderer.prototype.initItems http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:5525:9
	AnimationItem.prototype.checkLoaded http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:8677:9
	checkFontsLoaded http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:8652:13
	bound checkFontsLoaded self-hosted:913:17
	AnimationItem.prototype.waitForFontsLoaded</< http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:8659:9
	AnimationItem.prototype.configAnimation http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:8640:9
	AnimationItem.prototype.setParams http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:8455:9
	loadAnimation http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:8242:9
	loadAnimation http://localhost:3000/wp-content/themes/dottheme/js/jquery/lottie.js:13465:16
	loadAnimations/< http://localhost:3000/wp-content/themes/dottheme/dist/bundle.js:1568:32
	forEach self-hosted:251:13
	loadAnimations http://localhost:3000/wp-content/themes/dottheme/dist/bundle.js:1559:7
	init/this.p< http://localhost:3000/wp-content/themes/dottheme/dist/bundle.js:1490:9
	.Deferred/d.then/</</< http://localhost:3000/wp-includes/js/jquery/jquery.js:2:28766
	n.Callbacks/i http://localhost:3000/wp-includes/js/jquery/jquery.js:2:27444
	n.Callbacks/j.fireWith http://localhost:3000/wp-includes/js/jquery/jquery.js:2:28213
	.Deferred/d.then/</</< http://localhost:3000/wp-includes/js/jquery/jquery.js:2:28879
	n.Callbacks/i http://localhost:3000/wp-includes/js/jquery/jquery.js:2:27444
	n.Callbacks/j.fireWith http://localhost:3000/wp-includes/js/jquery/jquery.js:2:28213
	y http://localhost:3000/wp-includes/js/jquery/jquery.js:4:22719
	.send/c http://localhost:3000/wp-includes/js/jquery/jquery.js:4:26925

**Comment by bodymovin** [comment]
Hi, can you share the animation which is causing the issue and a link so I can try to reproduce it?

**Comment by pstinnett** [comment]
Any resolution to this one?

**Comment by bodymovin** [comment]
@pstinnett are you having the same issue?

**Comment by bodymovin** [comment]
Hi, this will be fixed on version 5.1.8
