### ISSUE TITLE
Firefox animation bug

### ISSUE THREAD

**Issue by tonysar** [airbnb/lottie-web#841]
**Tell us about your environment**
lottie-web: 5.0.5 static html, using gulp and webpack for builds.

**Browser and Browser Version:**
Firefox 58.0b12 (64-bit)

**After Effects Version:**
I used lottiefiles

**What did you do? Please explain the steps you took before you encountered the problem.**
We create an animation with mask in AE

**What did you expect to happen?**
I expected the loading graphic to work in firefox like in Chrome or others browsers

**What actually happened? Please include as much relevant detail as possible.**
The second animation wasnt propagating the container but in chrome, it's ok
. If we just change something in the browser console, the animation is ok...

The exemple 

https://www.pamplemousse.com/
![capture d ecran 2018-01-24 a 13 24 30](https://user-images.githubusercontent.com/31902861/35332132-314e7160-010a-11e8-9fb9-267c2873b9e7.png)

**Comment by bodymovin** [comment]
Hi, I can't see the issue.
Do you have a reduced case I can check?

**Comment by tonysar** [comment]
Hi,
We have updated Firefox...and now it seems to be ok.
Thx.
