### ISSUE TITLE
Text appears in top corner in browser in first loop but disappears after?

### ISSUE THREAD

**Issue by Dcoppins94** [airbnb/lottie-web#842]
After ive completed my animation in After Effects and preview it, all runs smoothly.

As soon as ive rendered and open the .html file in a browser, some of the text elements overlap each other in the top left corner when theyre not supposed to be showing, but then disappear after the first loop. Once theyve disappeared on the first loop the animation works perfectly, but I need to remove this issue so that it doesnt show at all?

Thanks in advance!

**Comment by bodymovin** [comment]
Hi, can you share a link where it's failing?

**Comment by Dcoppins94** [comment]
Sorry not too sure how to share the html link because it doesnt work when I send the link,

Ive screenshotted the top corner, its text that shouldnt be positioned there or even appear at that time, but disappears after the first loop?

Ive checked the canvas etc and it doesn't appear in there

![ss](https://user-images.githubusercontent.com/35776108/35346890-6eb6a11e-012b-11e8-8609-c4f985e913e0.jpg)

**Comment by bodymovin** [comment]
can you create a codepen or is there some way I can test it?

**Comment by MyGoodUserName** [comment]
I had the same problem with appearance of the text on top corner,
So i tried (precomp)ing that text
and seems to work fine for me!!
