### ISSUE TITLE
Random glitches in .json final export

### ISSUE THREAD

**Issue by kerrylofton** [airbnb/lottie-web#843]
First and foremost thanks so much for all the help with this huge project. The assistance we have received here has helped to save us tons of time and energy with this project. We are in the home stretch but unfortunately we are having some issues in the final .json export. I am attaching screenshots but there are a few places where there random glitches. For example, one scene where text pops up in the top left corner then disappears. It is mostly stutters and text popping off and reappearing. There is also an issue with one animation i have where some text comes in from the bottom but the a gets stuck out of place(Second screenshot). I notice that the text also seems to lost its spacing.  None of this occurs in my AE composition or in the pro res export. We only see these glitches in the code export. Any idea on how I can fix this? I've tried everything. Any and all help is appreciated and if necessary I can email you the .AEP file.

![image002](https://user-images.githubusercontent.com/32747720/35355494-1506c38c-0113-11e8-8531-385e5ccfa820.png)
![image004](https://user-images.githubusercontent.com/32747720/35355500-190476a0-0113-11e8-860e-d21cb4d0fb3e.png)

**Comment by bodymovin** [comment]
hi, yes can you send me the .aep and a link where it fails?

**Comment by kerrylofton** [comment]
Email sent! Thank you so much!
