### ISSUE TITLE
Placing Bodymovin animation to WordPress site

### ISSUE THREAD

**Issue by Anatten** [airbnb/lottie-web#844]
[AI icon.zip](https://github.com/airbnb/lottie-web/files/1663706/AI.icon.zip)
Hi ! I would really appreciate your help.

I'm a motion graphic designer and It's my first time with WordPress. I would like to add an animation I made in After Effects and exported it with Bodymovin and insert it into the WordPress site. 
I'm using Elementor.
I searched online how to do it but I still have no clue. I'm attaching the files and also a gif I exported.

Thank you so much and I wish you an amazing day!
Anat.
![ai-icon](https://user-images.githubusercontent.com/35800596/35385370-5e1b9dd0-01c8-11e8-8f28-2735b384052c.gif)
[AI icon.zip](https://github.com/airbnb/lottie-web/files/1663707/AI.icon.zip)

**Comment by tesla4** [comment]
[https://github.com/airbnb/lottie-web/issues/549](url) Hope this helps. BR

**Comment by Anatten** [comment]
Hi Chris @tesla4 ,
Thank you so much. I did what you wrote but I still can't understand how to upload it, I'm using Elementor.
This is the site: https://ted4b.com/ and I would like to change the illustration at the top with the js file.
Do you think you could help me?

**Comment by tesla4** [comment]
Unfortunately I don't know about Elementor, so I cannot guarantee that step 3 will work. But there should be a media uploader as well (where you upload images). If you don't know how to change permalinks there, it shouldn't be a problem (without images). Just change the urls (in step 4 and 8) correspronding to the media folder (could be something like "/wp-content/uploads/elementor/2018/01/31/"). In normal Wordpress you can get the url of the uploaded file by clicking on it in the media uploader section: 
![grafik](https://user-images.githubusercontent.com/35953387/35617824-73ddee10-0679-11e8-8544-2c056c15b98b.png)
At the end, change the image on your site to a the <div id = "lottie"></div> element and size it with css. 

BR

**Comment by Anatten** [comment]
Thank you for your help!
I think it doesn't work with the Elementor page builder so I used GIF animation with an alpha channel :/
