### ISSUE TITLE
Text Tracking Animation

### ISSUE THREAD

**Issue by esbensohl** [airbnb/lottie-web#845]
Hi there.

I'm experiencing an issue with animating the text tracking (letterspacing). 

Trying to re-create this: [https://tympanus.net/Development/OpeningSequence/](https://tympanus.net/Development/OpeningSequence/) 

Within AE it is all good, tracking animates from center as the text is aligned to center:

![alt](http://esbensohl.dk/lottie/dummy_ae1.png)
![alt](http://esbensohl.dk/lottie/dummy_ae2.png)
![alt](http://esbensohl.dk/lottie/dummy_ae3.png)

Here is the issue, when rendering it is animating the tracking left aligned.

Bodymovin render:
![alt](http://esbensohl.dk/lottie/dummy_1.png)
![alt](http://esbensohl.dk/lottie/dummy_2.png)
![alt](http://esbensohl.dk/lottie/dummy_3.png)

What is causing this ?

[AE: file](http://esbensohl.dk/lottie/dummy.aep)
[Json: file](http://esbensohl.dk/lottie/dummy_data.json)

**Comment by KasperAndersson** [comment]
Recreated the issue https://codepen.io/KasperAndersson/project/editor/XqOQKe

**Comment by bodymovin** [comment]
Hi, I can't seem to download the files.
Can you check if they are still available?

**Comment by KasperAndersson** [comment]
Hi @bodymovin, I recreated the issue with @esbensohl's file. See comment above.

**Comment by esbensohl** [comment]
Hep  @bodymovin

Links are updated

**Comment by bodymovin** [comment]
this should be working on latest version.

**Comment by KasperAndersson** [comment]
Sweet

**Comment by MichaelMichaelsOffice** [comment]
Hey there,
I still seem to be having issues with this :/ 
Currently running v5.2.0 (Mac)

**Required Result:**
<img width="454" alt="required result - a" src="https://user-images.githubusercontent.com/42221003/43862965-8e63b360-9b5b-11e8-8aa7-e8cebb72b87e.png">
<img width="451" alt="required result - b" src="https://user-images.githubusercontent.com/42221003/43862967-8ea26ef2-9b5b-11e8-933c-d94185f1e771.png">

Html Demo Result:
<img width="546" alt="demo result - a" src="https://user-images.githubusercontent.com/42221003/43863016-b4da7a06-9b5b-11e8-86a3-7285b76f05c5.png">
<img width="540" alt="demo result - b" src="https://user-images.githubusercontent.com/42221003/43863018-b51a11c0-9b5b-11e8-8e19-361725159d6d.png">

Any help would be much appreciated!

**Comment by bodymovin** [comment]
@MichaelMichaelsOffice can you share the .aep file?

**Comment by MichaelMichaelsOffice** [comment]
Sure! You'll find everything [HERE](https://www.dropbox.com/sh/tdewdw1oveu1ik3/AADcc0voK6YDkcw_LrrHP3Gra?dl=0)

**Comment by bodymovin** [comment]
@MichaelMichaelsOffice there is a horizontal scale of 90% applied to the text that is not yet supported by the player.
If you change it back to 100% it should look fine.

**Comment by MichaelMichaelsOffice** [comment]
Thanks for looking into this! Unfortunately, i'm still getting the same result :/

**Comment by bodymovin** [comment]
can you share the updated .aep?

**Comment by MichaelMichaelsOffice** [comment]
Should be updated now: [HERE](
https://www.dropbox.com/sh/tdewdw1oveu1ik3/AADcc0voK6YDkcw_LrrHP3Gra?dl=0)

**Comment by bodymovin** [comment]
I still see the horizontal scale applied to the text at 90%.
Check the Character tab and change it to 100% with the text layers selected.

**Comment by MichaelMichaelsOffice** [comment]
Unfortunately, I had no luck changing the horizontal scale. 

I tested the same piece of text again however this time it's not running along a path and it worked (V2). It seems as though the issue i'm having is related to the text being connected to a path? 

Is there anyway this issue could be resolved, would be hugely appreciated!

You can see this working in 'Demo (V2)'
I've updated the AE file - It now holds both V1 and V2
You can find this all [HERE](https://www.dropbox.com/sh/tdewdw1oveu1ik3/AADcc0voK6YDkcw_LrrHP3Gra?dl=0)

**Comment by MichaelMichaelsOffice** [comment]
Just circling back here :)

**Comment by bodymovin** [comment]
unfortunately not, centered text following a path is not trivial to fix.

**Comment by MichaelMichaelsOffice** [comment]
Alright, thanks for looking into it - I guess it is sort of specific. Do you see a this issue being addressed in an update sometime in the near future?

**Comment by bodymovin** [comment]
@MichaelMichaelsOffice I think I have it working. At least for a good amount of scenarios.
If you want to try it out, here's a build of the player
[lottie.min.txt](https://github.com/airbnb/lottie-web/files/2305954/lottie.min.txt)
you need to rename the extension to .js

**Comment by MichaelMichaelsOffice** [comment]
Apologies for the delayed response! Thank you so much for this, it's workign perfectly!
