### ISSUE TITLE
Lottie animation lagging on android

### ISSUE THREAD

**Issue by vnzapen** [airbnb/lottie-web#846]
hi there
my lottie animation works fine on lottie preview, but being lag (not run smoothly) when played on android devices. is there any solution for this?
please help... thanks 

regards,

**Comment by bodymovin** [comment]
Hi, are you using lottie-android or are you running the animation on the browser?
Some features are really performance intensive and might not work well on devices through the browser.
Can you share the .aep?

**Comment by vnzapen** [comment]
I tested the json file at android-devices, when it got lag, 
but when it run on lottie-files, the json file ran smoothly
here the aep, thank you
[registered.zip](https://github.com/airbnb/lottie-web/files/1684093/registered.zip)
