### ISSUE TITLE
How to freeze the last frame in animation after it's done playing?

### ISSUE THREAD

**Issue by rajthakkar77** [airbnb/lottie-web#847]
I am loving the lottie plugin so far. However, the animation disappears after it plays out. How can i freeze it at the last frame when it's done playing? Thanks in advance!

**Comment by dutscher** [comment]
hey rajthakkar77,

i used this javascript snippet ;)

`var container = document.getElementById("logo"),
        anim = lottie.loadAnimation({
            container: container,
            renderer: "svg",
            loop: false,
            autoplay: true,
            path: "static/logo.08.json"
        });

    anim.addEventListener("enterFrame", function (animation) {
         if (animation.currentTime > (anim.totalFrames - 1)) {
            anim.pause();
         }
    });`

cheers

**Comment by rajthakkar77** [comment]
Hi @dutscher 
Thanks a lot! Works like magic 💯

**Comment by bodymovin** [comment]
Hi, this has been fixed on the player side too on version 5.1.7, so no need to do this workaround anymore

**Comment by mlaurita** [comment]
Hi, I'm still seeing this issue with the web player. Is this fixed?

**Comment by bodymovin** [comment]
@mlaurita can you share an example?

**Comment by mlaurita** [comment]
`<script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
<lottie-player 
    src="https://assets2.lottiefiles.com/packages/lf20_BYtDqx.json"  background="#00A9DA"  speed="1"  style="width: 300px; height: 300px;"    autoplay >
</lottie-player>`

**Comment by mlaurita** [comment]
@bodymovin any news?

**Comment by bodymovin** [comment]
@mlaurita I'm not the maintainer of the lottie-player by lottiefiles, but someone already asked me about this before.
Apparently they are resetting the play position of the animation once it is finished, no idea why, I suggest that you open an issue on their repository.

**Comment by hanz-ss** [comment]
Hello, I'm very new to code

So far my issue is I want pause at a frame for few seconds and then continue playing the animation.

There are three pause-and-play I want to insert on to my animation. Thanks for your work and support. This plugin is phenomenal.

**Comment by dantaylor** [comment]
For those looking for the same solution but in TypeScript / React world, I was able to successfully "pause" the animation with the same approach mentioned earlier on the thread, the code is like so: 
`
const handlePlayerEvent = (e: PlayerEvent) => {
        if (e === "frame") {
            if (playerRef.current && playerRef.current.state.instance) {
                const { currentFrame, totalFrames } = playerRef.current.state.instance
                console.log("currentFrame", currentFrame, " totalFrames", totalFrames)
                if (currentFrame >= totalFrames - 4) {
                    playerRef.current.pause()
                }
            }
        }
    }
`
It assumes, having a ref to the player object like so:
` const playerRef = useRef<Player>(null) `
Also, I am stopping the head almost 4 frames before the animation ends, this was the only way to actually stop every time I believe it has to do with the way events bubble on the React ecosystem  vs the internal lottie playhead timing. So playing with that number ( 4 ) to fine tune to your needs is required and a bit of trial & error. 

Finally, at the Component, tie everything like so:
<Player
      src={"/images/cap-first.json"}
      autoplay
      style={{ width: "80px", height: "80px" }}
      ref={playerRef}
      onEvent={handlePlayerEvent}
  />
