### ISSUE TITLE
Cannot read property 'mProp' of undefined

### ISSUE THREAD

**Issue by ateamtip** [airbnb/lottie-web#849]
I updated to the new script version, and I'm getting error message.

![screen shot 2018-01-30 at 8 26 46](https://user-images.githubusercontent.com/3693755/35552460-9d2fc0b4-059c-11e8-97bf-27ab71627a78.png)

I have a JSON animation that is working when I configure renderer as 'SVG', but I'm getting an error message when I'm using the 'HTML' renderer option.

This animation worked perfectly on 5.06 version, but it doesn't work in the new version.

New script (5.15) - SVG renderer - working
https://s3.amazonaws.com/vidgeos-2747/test/demo.html

New script (5.15) - HTML renderer - not working
https://s3.amazonaws.com/vidgeos-2747/test/demo-html.html

Old Script (5.06)  - HTML renderer - working
https://s3.amazonaws.com/vidgeos-2747/test/demo-html-old.html

**Comment by bodymovin** [comment]
Hi can you share the .aep?

**Comment by lior-powerbusiness** [comment]
Hi @bodymovin,

Thank you for your reply, I just sent you the project to your email.

**Comment by ateamtip** [comment]
Hi @bodymovin,

Thank you for your reply, I just sent you the project to your email.

**Comment by bodymovin** [comment]
Found the issue. Will be fixed in the next build.
