### ISSUE TITLE
Animations not running on ios mobile web

### ISSUE THREAD

**Issue by joelponce** [airbnb/lottie-web#850]
Hello,

We are working on a Vue web app with svg animations. Our ae animations are working great on desktop web and android web, but do not render on ios devices (testing on Safari and Chrome on iPhone 5C and 8+). When I inspect these elements, I notice that all the g tags in the svg file are given a `display: none` property. When I manually remove these in the Safari dev tools, the image appears but does not animate. 

This is my options object:
```
{
    container: this.$refs.lavContainer, // using a modified version of lottie-vue wrapper
    renderer: 'svg',
    loop: true,
    autoplay: true,
    path: '/images/json/test.json'
}
```
Installed through `npm install lottie-web`

I've been working with our custom animations as well as testing with other files like this: https://editor.lottiefiles.com/?src=https://www.lottiefiles.com/download_public/1314

I searched through other issues and couldn't find someone with a similar problem. Any ideas what's keeping these animations from rendering on ios mobile web browsers?

**Comment by bodymovin** [comment]
Hi, can you share a link where it fails?

**Comment by joelponce** [comment]
I was hoping we'd have a public site to share but we do not yet :/
In recent tests I've noticed this happens not just on ios devices but any mobile-size screen.

**Comment by statik** [comment]
@joelponce I'm running into this same problem, were you able to resolve it?

**Comment by joelponce** [comment]
Hey @statik I was not able to solve this and am no longer working on this project.

**Comment by gultyayev** [comment]
Unexpectedly, there is an answer on Reddit https://www.reddit.com/r/ionic/comments/1ccnywh/lottie_animation_not_working_on_device/.

Using the `animationData` fixes the problem.
