### ISSUE TITLE
Export animation from after effect to file  .json file .demo failed

### ISSUE THREAD

**Issue by lycheekatory** [airbnb/lottie-web#851]
Please help me ! create motion file in after effect cc 2017 from the design file Ai. But when exporting the .json file, animation demo file .html5 play wrong with me creating key animation in AE. File . json faulty.
Please help me fix this. I use the windows operating system.
Thanks bro...

**Tell us about your environment*
ell us about your environment**

* **Browser and Browser Version: Window 10**
* **After Effects Version: CC 2017**

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by same23091** [comment]
Hello all, i have made a animation using loop expression, It is not working after exporting using "Bodymovin" ?

**Comment by bodymovin** [comment]
@same23091 can you share your project?

**Comment by same23091** [comment]
> @same23091 can you share your project?

Sure, Thanks

**Comment by same23091** [comment]
[Project.zip](https://github.com/airbnb/lottie-web/files/2762568/Project.zip)
Sorry for sending late, kindly help, when i export it in JSON, it doesn't work??

**Comment by same23091** [comment]
I used bodymovin plugin.

**Comment by same23091** [comment]
Hi,
@bodymovin Have you checked that?

**Comment by bodymovin** [comment]
@same23091 Not yet, I'll check it when I get back from work

**Comment by same23091** [comment]
ok @bodymovin

**Comment by bodymovin** [comment]
@same23091 CC Cylinder effect is not supported.
Not many effects are. You can check the wiki to see which one are partially supported.
https://github.com/airbnb/lottie-web/wiki/Effects

**Comment by Homanshab** [comment]
Hello, @bodymovin I am using AE CC 2018, no way to export one single animation with the plugin, it can be read by the viewer from BM but I cannot see the HTML. I tried only with shape, solid colours and text.  Is there something missing from my side? Can you help me?
