### ISSUE TITLE
Animation is Frozen

### ISSUE THREAD

**Issue by reybufon** [airbnb/lottie-web#852]
I exported an animation using BodyMovin, but I get this error on the Console:

Uncaught ReferenceError: smooth is not defined     at _expression_function (eval at initiateExpression

The animation is completely frozen. What could be happening?
I attach files as reference

Thanks!

[animation.zip](https://github.com/airbnb/lottie-web/files/1680839/animation.zip)

**Comment by bodymovin** [comment]
hi, the smooth method is not supported yet.
Do you have an expressions using it?
