### ISSUE TITLE
Animation behaving differently, when set the same data on "path" or "animationData" param

### ISSUE THREAD

**Issue by murugavelmca** [airbnb/lottie-web#854]
We are loading the JSON data file through "path" param.  The initial segment of animation repeat twice and then it loop properly.  

If we load same JSON data through "animationData" param then it is working fine as expected. 

Browser version: 64.0
Lottie version: 5.0.4

Sample code to reproduce issue: (Just change below file to load the data through "path" instead of "animationData")
https://github.com/murugavelmca/demo/blob/master/issue_demo.html

**Comment by murugavelmca** [comment]
AE file: https://github.com/murugavelmca/demo/tree/master/computer%20test%20to%20github

**Comment by bodymovin** [comment]
Hi, it's possible that you have to wait for the DOMLoaded event to be fired before setting the segment range or it will be overwritten once the animation is actually loaded.
Can you try that and let me know?

**Comment by bodymovin** [comment]
Try
anim.addEventListener('DOMLoaded', function(){...})

**Comment by murugavelmca** [comment]
Thanks @bodymovin.  It working fine 👍
