### ISSUE TITLE
Lottie video as full background

### ISSUE THREAD

**Issue by chromafunk** [airbnb/lottie-web#855]
Can I have a lottie animation as background of a DIV ? 

I would like to create a section with a full screen video and on top of that section to have containers with text and other elements. Is this possible somehow ?

**Comment by bodymovin** [comment]
You can't add a lottie animation with css because it needs javascript to work.
But you could create a div with position absolute and load the lottie animation on that element as the container.
Would that work for your case?

**Comment by BJagatNayan** [comment]
Can we call the json file as a background image ? like background: url(path/data.json) ??

**Comment by syedshadaabhusain** [comment]
Try this attribute:
android:scaleType="fitXY"
