### ISSUE TITLE
Is it true that all effects under the Effect dropdown list are not support?

### ISSUE THREAD

**Issue by zhengs** [airbnb/lottie-web#856]
Correct me if I'm wrong -- is it true that all effects under the Effect dropdown list in After Effects are not supported? If it's not true, which ones are supported?

Thanks!

**Comment by bodymovin** [comment]
There are very few effects that are supported right now, indeed.
On the Wiki/Effects page you can see the ones supported
https://github.com/airbnb/lottie-web/wiki/Effects
