### ISSUE TITLE
React using bodymovin encountering problem

### ISSUE THREAD

**Issue by jefflung** [airbnb/lottie-web#859]
TypeError: Cannot read property 'appendChild' of undefined
SVGRenderer.configAnimation
http://localhost:3000/static/js/bundle.js:6681:32
  6678 | this.layerElement.setAttribute('preserveAspectRatio',this.renderConfig.preserveAspectRatio);
  6679 | //this.layerElement.style.transform = 'translate3d(0,0,0)';
  6680 | //this.layerElement.style.transformOrigin = this.layerElement.style.mozTransformOrigin = this.layerElement.style.webkitTransformOrigin = this.layerElement.style['-webkit-transform'] = "0px 0px 0px";
> 6681 | this.animationItem.wrapper.appendChild(this.layerElement);
       |                            ^  6682 | //Mask animation
  6683 | var defs = document.createElementNS(svgNS, 'defs');
  6684 | this.globalData.defs = defs;
View source
AnimationItem.configAnimation
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/node_modules/bodymovin/build/player/bodymovin.js:8717
  8714 | this.animationData = animData;
  8715 | this.totalFrames = Math.floor(this.animationData.op - this.animationData.ip);
  8716 | this.animationData.tf = this.totalFrames;
> 8717 | this.renderer.configAnimation(animData);
  8718 | if(!animData.assets){
  8719 |     animData.assets = [];
  8720 | }
View compiled
AnimationItem.setParams
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/node_modules/bodymovin/build/player/bodymovin.js:8559
  8556 | this.prerenderFramesFlag = 'prerender' in params ? params.prerender : true;
  8557 | this.autoloadSegments = params.hasOwnProperty('autoloadSegments') ? params.autoloadSegments :  true;
  8558 | if(params.animationData){
> 8559 |     self.configAnimation(params.animationData);
  8560 | }else if(params.path){
  8561 |     if(params.path.substr(-4) != 'json'){
  8562 |         if (params.path.substr(-1, 1) != '/') {
View compiled
loadAnimation
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/node_modules/bodymovin/build/player/bodymovin.js:8337
  8334 |    function loadAnimation(params){
  8335 |        var animItem = new AnimationItem();
  8336 |        setupAnimation(animItem, null);
> 8337 |        animItem.setParams(params);
  8338 |        return animItem;
  8339 |    }
  8340 | 
View compiled
loadAnimation
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/node_modules/bodymovin/build/player/bodymovin.js:14251
  14248 |        if (standalone === true) {
  14249 |            params.animationData = JSON.parse(animationData);
  14250 |        }
> 14251 |        return animationManager.loadAnimation(params);
  14252 |    }
  14253 | 
  14254 |    function destroy(animation) {
View compiled
./src/util/index.js
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/src/util/index.js:18
  15 |     loop: false,
  16 |     animationData: animationData
  17 | };
> 18 | let anim = bodymovin.loadAnimation(animData);
  19 | 
  20 | const index ={
  21 |   componentDidMount(){
View compiled
__webpack_require__
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/webpack/bootstrap d9a83dcc569c22f3a681:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
fn
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/webpack/bootstrap d9a83dcc569c22f3a681:88
  85 | 		console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
  86 | 		hotCurrentParents = [];
  87 | 	}
> 88 | 	return __webpack_require__(request);
  89 | };
  90 | var ObjectFactory = function ObjectFactory(name) {
  91 | 	return {
View compiled
./src/App.js
http://localhost:3000/static/js/bundle.js:57476:70
__webpack_require__
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/webpack/bootstrap d9a83dcc569c22f3a681:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
fn
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/webpack/bootstrap d9a83dcc569c22f3a681:88
  85 | 		console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
  86 | 		hotCurrentParents = [];
  87 | 	}
> 88 | 	return __webpack_require__(request);
  89 | };
  90 | var ObjectFactory = function ObjectFactory(name) {
  91 | 	return {
View compiled
./src/index.js
http://localhost:3000/static/js/bundle.js:57737:63
__webpack_require__
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/webpack/bootstrap d9a83dcc569c22f3a681:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
fn
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/webpack/bootstrap d9a83dcc569c22f3a681:88
  85 | 		console.warn("[HMR] unexpected require(" + request + ") from disposed module " + moduleId);
  86 | 		hotCurrentParents = [];
  87 | 	}
> 88 | 	return __webpack_require__(request);
  89 | };
  90 | var ObjectFactory = function ObjectFactory(name) {
  91 | 	return {
View compiled
0
http://localhost:3000/static/js/bundle.js:57958:18
__webpack_require__
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/webpack/bootstrap d9a83dcc569c22f3a681:678
  675 | };
  676 | 
  677 | // Execute the module function
> 678 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  679 | 
  680 | // Flag the module as loaded
  681 | module.l = true;
View compiled
./node_modules/ansi-regex/index.js.module.exports
C:/Users/Jeff.Lung/Desktop/react gsap/react_gsap/webpack/bootstrap d9a83dcc569c22f3a681:724
  721 | __webpack_require__.h = function() { return hotCurrentHash; };
  722 | 
  723 | // Load entry module and return exports
> 724 | return hotCreateRequire(0)(__webpack_require__.s = 0);
  725 | 
  726 | 
  727 | 
View compiled
(anonymous function)
http://localhost:3000/static/js/bundle.js:728:10
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by bodymovin** [comment]
It looks like you're not passing a real DOM element as the container of the animation.
Could that be the case?

**Comment by jefflung** [comment]
@bodymovin Thanks for your inspiration. Let me check!

**Comment by pinzonjulian** [comment]
Hi
I had the same issue and it was related with the placement of the JS libraries. You can place your scripts just before the closing `body` tag or in the `head` making sure you run your animation script on page load.

**Comment by mfundo** [comment]
> It looks like you're not passing a real DOM element as the container of the animation.
> Could that be the case?

Apologies for being dumb. Can't seem to resolve this.

`const conf = {
			container: document.getElementById('something'),
			renderer: 'svg',
			loop: true,
			autoplay: true,
			path: 'animation/animation1.json'
		}`

But I still get the error, is there a way to get the 'container' as a real DOM element in React?

**Comment by bodymovin** [comment]
you can use ref
https://reactjs.org/docs/refs-and-the-dom.html

**Comment by mfundo** [comment]
@bodymovin For some reason it didn't like my setup, I made a service that I returned an instance of Lottie, think thats where it all went wrong. Thanks for the assistance.
