### ISSUE TITLE
Line height value doesn't export correctly

### ISSUE THREAD

**Issue by royhs** [airbnb/lottie-web#860]
Hey,

Is there a possibility that lottie will export a font's line height that I set in after effect even if there's only one text line exported? Right now if there's only 1 line of text it automatically exports the auto value, but if there are more lines it exports the value that I set in after effects.

I'm using the latest version (5.1.7)

Thanks!

**Comment by royhs** [comment]
After checking again, exporting the tracking is ok, the problem is just with the line height.

**Comment by bodymovin** [comment]
Hi, unfortunately it's an AE bug that doesn't report line height correctly for single lines, so I have no way of measuring it accurately.

**Comment by royhs** [comment]
@bodymovin yeah, I figured... but it was worth a shot - thanks for that

**Comment by sanketkoladiya** [comment]
@royhs  what is the solution ? have you resolved ?
