### ISSUE TITLE
sourceRectAtTime for height doesn't give right value

### ISSUE THREAD

**Issue by royhs** [airbnb/lottie-web#861]
Hey,

I've been working with sourceRectAtTime for the width of text layers and it works perfectly. For some reason when I use it for height values, I don't get the right values in the json as the ones I get in after effects.

Any idea why?
Thanks!
/R

**Comment by bodymovin** [comment]
Hi, can you share the .aep?

**Comment by royhs** [comment]
@bodymovin here's a simplified example of the problem I'm having - in after effects the box is the right size but when I play the json it has different proportions

[Hello_world.zip](https://github.com/airbnb/lottie-web/files/1706571/Hello_world.zip)

**Comment by bodymovin** [comment]
Hi, it seems to be working fine here.
Can you share a link where it fails?

**Comment by igor-nikolic** [comment]
Hi, 
Can someone explain how can I implement this function "getRectAtTime" with lottie?
