### ISSUE TITLE
Weird Clipping Issue When Using Trim Paths

### ISSUE THREAD

**Issue by lpgraphix** [airbnb/lottie-web#863]
* **Browser and Browser Version:**
Chrome Version 64.0.3282.140 (Official Build) (64-bit)

* **After Effects Version:**
Version 15.0.0

I've been animating the start and end of several trim paths and I can't get the piece to render without strange clipping in the paths. There is only one path er shape layer and even still the Trim Multiple Paths is set to Simultaneously for good measure. The issue is almost like a rectangular mask over each trim? I tried a weird solve mentioned sometime last year where I placed a rectangle with a fill but no opacity under one of my paths to test it. There were no noticeably different results.

**What did you expect to happen?**
Clean circular trimming like in the viewport: [https://drive.google.com/open?id=1J8ZIM](url)

**What actually happened? Please include as much _relevant_ detail as possible.**
Weird, clipped trimpaths: [https://drive.google.com/open?id=1kCgrOe9SkcOBhBE7CK-myV0r5l-YPSvZ](url)

**Please provide a download link to the After Effects file that demonstrates the problem.**
The COMP020_LOGO 2 contains the original shape animations. https://drive.google.com/open?id=1gB3vub9aQuvnZfPz3fPZBix1y64mpenp

**Comment by lpgraphix** [comment]
After a bit more exploring, I realized I had the issue on all objects with a stroke as I had been coloring them with the Fill Effect. Deleted the Fill effect on all objects and set the actual stroke colors to what I need, render worked beautifully!

**Comment by bodymovin** [comment]
Hi! glad you solved it.
Stroke and fill effects don't go well together indeed.
