### ISSUE TITLE
slow animation on chrome only (and maybe safari)

### ISSUE THREAD

**Issue by m-mokhtar** [airbnb/lottie-web#864]
**Tell us about your environment**
windows 8.1 , AE cc 2015 , illustrator cc 2015 
* **Browser and Browser Version:**
chrome Version 64.0.3282.140 (Official Build) (64-bit)

* **After Effects Version:**
cc 2015

**What did you do? Please explain the steps you took before you encountered the problem.**
animation is so slow on chrome only, it works more than perfect on firefox and acceptably good on IE , not sure of safari yet but i believe it will act like chrome, the effects i am using are simple, scale and opacity of several objects
**What did you expect to happen?**
with or without masks (in AE) the objects in the animation are really loading super slow on chrome only while working perfectly on firefox and really good on IE, i tried split comp and without , i also tried to make each object with precomp but still so really slow on chrome.
**What actually happened? Please include as much _relevant_ detail as possible.**
the objects on the comp are several circles (vector) designed with illustrator, then after turning them into shapes and masking (also without masking) + some basic effects like scale and opacity , they work perfect on firefox and IE but as i mentioned so so so slow on chrome for a reason i dunno, and i enabled gpu usage on chrome still the same performance.
**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, can you share a link so I can take a look?

**Comment by m-mokhtar** [comment]
i uploaded you a demo here : 
https://transsample.mybluemix.net/

sorry if it loops, but local one doesn't loop and still chrome is killing me, thank you very much for your quick response btw, and for the revolutionary plugin .

**Comment by bodymovin** [comment]
How are you exporting your letters?
Could you share the .aep so I can take a look?

**Comment by m-mokhtar** [comment]
if you mean letters as the text in the page, i make shape from it (not shape from text but from object because "make shape from text" is grayed for me) , the text is from an illustrator design (outlined and everything)  , i will try to upload the file if you really need to take a look at it, i'm currently not on the pc that got AE, but if you have any suggesting please guide me , thanks.

**Comment by m-mokhtar** [comment]
i really wonder why chrome is such a bad browser specially with animations in general, maybe they are over-doing everything so it breaks? i am not sure, it was an eye opener for me to find IE outperforms chrome with this sample page i am trying to fix .

**Comment by bodymovin** [comment]
I tried it in firefox and it wasn't great either. My guess is that some extra shapes on every letter are affecting performance.

**Comment by m-mokhtar** [comment]
on every letter of text? it renders great on AE , anyway i will asap upload the aep file anyway so you can take a look, thanks.

**Comment by m-mokhtar** [comment]
here is the link for the aep : 
https://www.dropbox.com/s/uz28640rvyt0tes/whatwegoodat.aep?dl=0
, btw i tried several things like deleting the text and the text boxes, also tried to work with PSD file with text edit enabled, no luck, i have no idea why it is being so slow on chrome and hopefully someone would be able to help me, sorry for being a noob with AE.

**Comment by bodymovin** [comment]
Yes, indeed all your letters and all your shapes have a surrounding group together with a merge path that are affecting performance.
You should remove those merge paths and extra groups in order to get a better experience.
Since there are hundreds of them you might want to use something like. I think it removes all of them automatically.
https://aescripts.com/explode-shape-layers/

**Comment by m-mokhtar** [comment]
thank you very much, i tried the tool (ESL) and it really helped with some manual work, after deleting some merge paths and un-used groups and converting the shapes in a right way it runs better now, i will report back after i am totally done in order to demonstrate all the steps i took cleaning my AE project, btw bodymovin rocks and you are all awesome.
