### ISSUE TITLE
Animation Freezing Up in Export

### ISSUE THREAD

**Issue by toocreative** [airbnb/lottie-web#865]
Hey, love the plugin to bits, just having a bit of trouble working out where I'm going wrong!

- PC Windows 10
- Chrome,
- AE CC2015

I've made this animation that renders fine in AE, but doesn;t render in Bodymovin correctly. I expected 15 seconds of animation, looping, but its only  animating only 2-3 sedonds then freezing up.

I've used shape layers, trim paths, loopOut(), time remap. Rubberhose, Alpha Matte, Alpha Inverted Matte. My understanding is that these are all supported.

You can download the AE file and .json here: https://www.dropbox.com/s/wqv6e9j2gttxdyi/Animation%20V3.aep?dl=0

Let me know what you think, thanks for the great work.

**Comment by bodymovin** [comment]
Hi, it seems to work fine here.
Can you share a link where it fails?
Remember to include hidden and guided layers when exporting rubberhose animations.

**Comment by toocreative** [comment]
It plays for the full 15 seconds? That's weird, my demo.html is locking up a few seconds in (in Edge/Chrome). 

Does it ever occur that a file works when hosted online, but not locally?

I actually just ended up successfully rebuilding it without using some of those features. Should they have all worked okay?

Thanks for looking into it.

**Comment by bodymovin** [comment]
It might happen, but I tested the demo.html and it looks fine too.
Can you share your demo.html so I can take a look?

**Comment by toocreative** [comment]
Weird!

I've thrown the demo.html in here: https://www.dropbox.com/sh/p8kpum25z8liuoe/AAD9xeqUIjy5POL0uXJu2ukia?dl=0

**Comment by bodymovin** [comment]
Looks like you're using an old version of bodymovin.
Can you update to the latest one?
