### ISSUE TITLE
Unable to view json animations | Exported Demo.html from AE renders perfectly

### ISSUE THREAD

**Issue by Dsit3056** [airbnb/lottie-web#866]
**Tell us about your environment**
lottie 14.3.0

* **Browser and Browser Version:**

Google Chrome | 64.0.3282.119 (Official Build) (64-bit

* **After Effects Version:**
After Effects CC 15.0.0 build 180

**What did you do? Please explain the steps you took before you encountered the problem.**
I created a simple shape in after effects and scaled the animation over time, I used bodymovin to render the animation and exported it to my desktop. I downloaded the lottie from github and followed the instructions from a youtube video found here https://www.youtube.com/watch?v=5XMUJdjI0L8
and tested it on codepen.io

.json animations not loading in browser. Demo.html exported from AE loads fine.

I have tested with .json from https://www.lottiefiles.com/ and was unable to have them render as well.

**What did you expect to happen?**
To view the json animation in my codepen profile
**What actually happened? Please include as much _relevant_ detail as possible.**

No animation was present in the codepen.io preview panel

**Please provide a download link to the After Effects file that demonstrates the problem.**
Attaching codepen project as well as AE project of test animation.
[project.zip](https://github.com/airbnb/lottie-web/files/1713716/project.zip)

**Comment by bodymovin** [comment]
Hi, if you're trying it locally, make sure you are using a web server to load the json file.

**Comment by stopitjon** [comment]
I have the same issue.

**Comment by bodymovin** [comment]
@stopitjon the LottieFiles team needs to update the player so it supports newer animations.
They'll probably be doing it soon.

**Comment by kudanai** [comment]
Closing since status of players and tooling has changed significantly since last post
