### ISSUE TITLE
Incorrect rendering

### ISSUE THREAD

**Issue by Hapun** [airbnb/lottie-web#867]
* **Browser and Browser Version:**
Chrome 63.0.3239.132

* **After Effects Version:**
15.0.1 (build 73)

**What did you do? Please explain the steps you took before you encountered the problem.**
I drew an image in Clip Studio Paint Pro (Raster Graphic Editor), which I then imported to Adobe Illustrator where I image traced it with "Low Fidelity" template to vectorize it. I then imported .ai file into After Effect, created outlines and rendered with bodymovin

**What did you expect to happen?**
I expected to see the render displaying correctly

**What actually happened? Please include as much _relevant_ detail as possible.**
Majority of the render is filled with black space, as if the background was black. This black space is covering majority of the elements. I have tried multiple .ai files and i believe it has to do with the image trace from illustrator, since with different .ai files there are different elements that can show up in the bodymovin render.

**Please provide a download link to the After Effects file that demonstrates the problem.**
In the .zip I included the .aep file, .json and .ai just in case.

Thank you very much for your time!
[incorrect_render.zip](https://github.com/airbnb/lottie-web/files/1715768/incorrect_render.zip)

**Comment by MReda909** [comment]
I have the same problem. Please tell me if you solved this issue... 

Thanks

**Comment by bodymovin** [comment]
Hi, the plugin doesn't support merge paths, so you need to remove in "Layer 1/мига3 Outlines" > "Group 24", properties Path 2 and Merge Path and it will look fine.
Nevertheless, puppet pin is not supported either.
