### ISSUE TITLE
Firefox changed their rendering?

### ISSUE THREAD

**Issue by JHaland** [airbnb/lottie-web#868]
**Tell us about your environment**
Windows 7, MacOS Sierra
* **Browser and Browser Version:**
Windows 7 Firefox 58.0.2 (64-bit), MacOS Firefox 58.0.1 (64-bit), 
* **After Effects Version:**
14.0.0.2017
**What did you do? Please explain the steps you took before you encountered the problem.**
Visited a published site where animation has looked great in the past (2017) and now with firefox (chrome looks good)there are jagged edges when it's animating. 

http://dev.jhaland.com/img/example.jpg

And on Mac Firefox there are some weird lines rendering on top of the clean graphics when animating 

http://dev.jhaland.com/img/firefox%2058%200%200%202_mac.png. 

Visit the site using firefox, scroll to the bottom of the site and scroll up again and look at the logo animation. https://www.filmskolen.no/

**What did you expect to happen?**
That the anti-alising looked good, and similar to chrome. 

Is there any CSS code to add to clean up jagged edges or is it just a firefox issue we have to wait out?

**Comment by bodymovin** [comment]
I've tried it in two different computers and I haven't seen that behavior on any of them using Firefox.
Regarding the antialiasing, indeed they seem to have done something that breaks the antialias on some frames.

**Comment by JHaland** [comment]
@bodymovin Yes, I've tried different versions, and 57 seems to work as expected. 58 doesn't. So I've sent a bug report directly to Firefox and hope they fix this soon.

**Comment by i5heu** [comment]
@JHaland  can you provide the link to the bugzilla bugreport?

**Comment by JHaland** [comment]
@i5heu This is the last one. I've filed it twice. https://bugzilla.mozilla.org/show_bug.cgi?id=1469794
