### ISSUE TITLE
Suggestion: Sort comps by Selected or favorites

### ISSUE THREAD

**Issue by pegeseus** [airbnb/lottie-web#869]
I'm using bodymovin in AE projects with 100s of precomps.  Each time I want to render a comp I have to search by name to narrow it down.  It would be extremely handy to have the ability to sort the comp list by "Selected" so I can easily access the handful of comps I'm rendering and make sure only the ones I want to render are currently selected.  Conversely it would also be awesome to be able to "favorite" or "pin" certain comps so that they stay surfaced in the list even if I don't want to render them.

**Comment by bodymovin** [comment]
Yes, I also have wanted this for a long time. I'll work on a selected filter.
Would that be enough for the first issue?
Regarding pinning comps, it's not a priority right now but I gladly accept PR :)

**Comment by pegeseus** [comment]
A selected filter would be a fantastic first step and a big time saver! :)

**Comment by bodymovin** [comment]
Done, I'll upload it in the next build

**Comment by pegeseus** [comment]
Wow! Now THAT'S what I call customer service. Thanks very much! :D

**Comment by bodymovin** [comment]
haha I've needed it myself for a long time. :)
