### ISSUE TITLE
JSON behaves differently on Android, iOS) and Web

### ISSUE THREAD

**Issue by iamsibtehassan** [airbnb/lottie-web#870]
Hello,
I've used this great extension but somehow it started pissing me off when I tried to use the .json file (extracted using bodymovin).
The problem I am having here is: when I upload my file (a simple dropping duck animation) on lottiefiles.com it works fine(https://www.lottiefiles.com/share/5B4vWj), but when I use it in iOS, its Eye disappears and doesn't show the head rotation (3d). On Android, it shows the eye but the head rotation is missing here too.

**Comment by bodymovin** [comment]
Hi, I'm sorry that it frustrated you.
lottie-android and lottie-ios don't support 3d animations.
Regarding the eye issue, I suggest that you open a ticket on the lottie-ios repository.
https://github.com/airbnb/lottie-ios

**Comment by iamsibtehassan** [comment]
Okay, but I also used for SVG but it doesn't seem to support that either. For example, the "supported features list" (http://airbnb.io/lottie/supported-features.html) says that it supports Matte in Web(SVG) but it Messes up with this either. Can you please help with that?

**Comment by bodymovin** [comment]
Hi, can you share a link where it fails?
