### ISSUE TITLE
Lagging animation (parent/child, transparency, png/shapes)

### ISSUE THREAD

**Issue by Kalamax** [airbnb/lottie-web#871]
Hello everybody!

**Tell us about your environment**

Windows 10.0.16299 Build 16299

* **Browser and Browser Version:** 

Same behavior on Edge, Chrome, Firefox

* **After Effects Version:**

After Effects CC 15.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**

I'm experiencing some issues with the bodymovin export on a after effects composition. I use:
- simple expression to move objects in isometric directions  
- parant/child connection between a few objects
- transparency 
- The assets are a mix of png files and shapes. 

**What did you expect to happen?**

Animation should work smoothly without any lagging. 

**What actually happened? Please include as much _relevant_ detail as possible.**

The animation is lagging. I would greatly appreciate if someone could take a look at the project and give me feedback, as I simply cannot isolate the root cause of the problem.

[issue_composition.zip](https://github.com/airbnb/lottie-web/files/1731331/issue_composition.zip)

**Comment by bodymovin** [comment]
Hi, you're using 14 3200x2400 png files.
Browsers will have a hard time animating them.
Can you reduce the size of those textures to remove all the transparent area on them?

**Comment by Kalamax** [comment]
Oh, it works a lot better now. Thank you!
