### ISSUE TITLE
3d layer extrusion

### ISSUE THREAD

**Issue by dunnbro** [airbnb/lottie-web#873]
Hi, thanks for a fantastic product. 

The extruded parts of extruded layers aren't rendering on export (but the layer itself is). I've tried both the ray-traced 3d and cinema 4d renderers. Am I missing something, or is this just not supported? Thanks.

**Comment by bodymovin** [comment]
Hi, unfortunately those effects are not supported by the player.

**Comment by dunnbro** [comment]
Ok, thanks.
