### ISSUE TITLE
Clipping in firefox

### ISSUE THREAD

**Issue by simonpeters** [airbnb/lottie-web#876]
**Tell us about your environment**
ottie-web: 5.1.7 angular 5 using CLI.

**Browser and Browser Version:**
Firefox 58.0.1 and 58.0.2 

**After Effects Version:**
adobe after effects build 73

**What did you do? Please explain the steps you took before you encountered the problem.**
I created a scene with multiple animations, fully created of SVG's. 

**What did you expect to happen?**
The animations to run smoothly

**What actually happened? Please include as much _relevant_ detail as possible.**
Some SVG's are clipped until I click and I trigger a repaint, then they show up fully. It only occurs in firefox.

![screen shot 2018-02-21 at 11 33 48](https://user-images.githubusercontent.com/714733/36475659-a573d984-16fb-11e8-9f79-b17cdf8f4e0a.png)
![screen shot 2018-02-21 at 11 33 50](https://user-images.githubusercontent.com/714733/36475660-a58aa3bc-16fb-11e8-9de8-bc24ee6c2739.png)

[video link](https://streamable.com/d0cd6)
[staging link](https://watergroep-app-staging.spaced.be/lesson/m3N/map)

**Comment by bodymovin** [comment]
Hi, I see it running well on Firefox in my computer.
On what OS are you testing it?

**Comment by simonpeters** [comment]
I'm running on mac OS 10.13.2

If also copied the demo.html to jsfiddle and I have the same clipping going on.

[link](https://jsfiddle.net/8wz8ncty/1/)

**Comment by simonpeters** [comment]
If just tested on 2 other mac's and they have the same issue (firefox 57 & 59), running it on firefox windows doesn't seem to have the issue.

**Comment by bodymovin** [comment]
It's the second issue I see related to the latest Firefox on Mac OS.
I'll have to look into it and probably file a bug to the Firefox team.
Can you try forcing a relayout on the svg element once it's loaded?

**Comment by simonpeters** [comment]
How do you propose I force a relayout on the svg element?

**Comment by bodymovin** [comment]
for example by setting it's width or height via javascript.

**Comment by simonpeters** [comment]
I have added the snippet below, but the problem still exists in firefox.

`setInterval(() => {
	const svgs = document.getElementsByTagName('svg');

  Array.from(svgs).forEach((svg) => {
      svg.setAttribute('height', "100%");
    });
}, 10);`

**Comment by bodymovin** [comment]
Can you try setting it to 1439 for example to see what happens?
