### ISSUE TITLE
Nothing is loading at all

### ISSUE THREAD

**Issue by justhassankhan** [airbnb/lottie-web#877]
Hi guys,

I used Bodymovin today for the first time today, Nothing is working at all. Here is the link of the demo.html file:
http://coolhtmlad.atwebpages.com/demo.html

and JSON file: http://coolhtmlad.atwebpages.com/data.json

Please help

**Comment by bodymovin** [comment]
Hi you're using encrypted expressions which are not supported by the player unfortunately because they can't be eval'd.
Also, an images folder should have been exported together with the json file that it seems to be missing.

**Comment by justhassankhan** [comment]
Wow, you are very fast. I love your support. The images are also in the same directory

**Comment by bodymovin** [comment]
the console is showing 404 errors when trying to load the images. For example here:
http://coolhtmlad.atwebpages.com/images/img_34.png

**Comment by justhassankhan** [comment]
<img width="1357" alt="screen shot 2018-02-22 at 12 23 34 am" src="https://user-images.githubusercontent.com/25118775/36500655-ab67ee14-1766-11e8-8ec1-d35a60b9dc4b.png">

**Comment by bodymovin** [comment]
there's not much I can do about that. I don't know what kind of permissions you need to handle on your server.
Try accessing the files inside that folder from your browser to confirm they work.

**Comment by justhassankhan** [comment]
By encrypted expressions, do you mean from plugins and stuff? Also, it is not even displaying other animations and the background is not displaying either :(

**Comment by justhassankhan** [comment]
Ok, I will see what is the problem with the images

**Comment by bodymovin** [comment]
by encrypted expressions, it really depends on the plugins you're using.
Some of them indeed are encrypted because the owner doesn't want the code to be public.

**Comment by justhassankhan** [comment]
I see, some animations are taken from the plugin named Animation composer. I will try to get them out but it should animate the position and scaling of the stuff atleast.
Loved your support man :)

**Comment by justhassankhan** [comment]
Hey man, so now you can see the images are showing up here: http://coolhtmlad.000webhostapp.com/images/

this is demo file: http://coolhtmlad.000webhostapp.com/
JSON FILE: http://coolhtmlad.000webhostapp.com/data.json

Please help. Can you give me any clue on this other than encrypted expressions, what could be causing this

**Comment by justhassankhan** [comment]
This is the whole ad in video
[Consumer_336x280.mp4.zip](https://github.com/airbnb/lottie-web/files/1745471/Consumer_336x280.mp4.zip)

**Comment by bodymovin** [comment]
Animation Composer is probably the one that's failing indeed.
I don't know how large is your comp, but if you look for those properties, try disabling their expressions in AE

**Comment by justhassankhan** [comment]
Ok I will do that

**Comment by justhassankhan** [comment]
So I removed all the encrypted expressions and it still does not work :( 
What is even weird is that it does nt even load the background image which is if blue color and no animation or effect is applied on it.

**Comment by bodymovin** [comment]
Can you share a link where it fails?
