### ISSUE TITLE
joystick n sliders addons AE not working together with bodymovin

### ISSUE THREAD

**Issue by ardianfakhru** [airbnb/lottie-web#878]
hi guys,
I used Bodymovin today for the first time today, so I was working on with my animation and tried to export it to .json file using bodymovin.
i made my animation using joystick n slider addons for AE, in AE it work just fine. But right when i tried to render it, the animations is not working, it scattered all around the place.  
i already ticked the "demo"and"glyphs" in the setting before export .
i tried to render it and replace the clip with .mov, made a new composition and put it under my new composition, still doesn't work.
please help, thank you.
[rigging.zip](https://github.com/airbnb/lottie-web/files/1762198/rigging.zip)

ps. english is not my first language, sorry.

**Comment by bodymovin** [comment]
Hi, if you use JnS you need to select Hidden and Guided layers on the exporting settings.

**Comment by ardianfakhru** [comment]
hi! sorry for late reply i've been busy lately.
i'll let you know if this works, thank you very much
