### ISSUE TITLE
Question regarding support of texture handling

### ISSUE THREAD

**Issue by kayson** [airbnb/lottie-web#880]
I want to develop a parameter specified system that renders a dynamic video for the user. Instead of setting up a render farm with parameters and generating URLs I wanted to try the real time approach first. 

I have used bodymovin / lottie before but in this case I want to change a texture in the AE scene with an image provided from frontend. Is this technically possible?

**Comment by bodymovin** [comment]
hi, would you be replacing an image exported on the AE composition with a different one client side?
If so, you could prefix the image layer name in AE with a "#" and the layer will be exported with an "id".
Then you can change it at runtime.
Another way is editing the "assets" property in the json file to point to another file.
It depends on whether you need the image to be replaced before or after the animation is loaded.

**Comment by kayson** [comment]
I am afraid the image has to be added at runtime.

**Comment by bodymovin** [comment]
And does it need to be added after the animation has been loaded, or can it be done before?

**Comment by kayson** [comment]
We only want to change a texture / image in the animations. I am not sure if it can be done after the animation has loaded but I would guess yes.

**Comment by pareshchouhan** [comment]
Interested in this, can we map the image as a texture to the shape before animation and make it keep mapped over it?

**Comment by bodymovin** [comment]
closing. Reopen if needed.
