### ISSUE TITLE
Question:Effects Tint

### ISSUE THREAD

**Issue by Thayonn** [airbnb/lottie-web#881]
HI, 
I am doing a project where I am wanting to tint an object at runtime.
do you have any examples of adding an Effect to a Renderer Element.
Also does this work on an Image asset, aka png

Thank you in advance

**Comment by bodymovin** [comment]
Hi, how are you thinking of tinting it? using css or svg filters?

**Comment by Thayonn** [comment]
I have worked it out using the ef tag and adding the Adobe tint. I am ideally looking for a more elegant way. Like anim.effects.add etc but using the animationdata is fine

**Comment by bodymovin** [comment]
an api is coming, but for effects it's not there yet. Will add it to the pipeline.

**Comment by Thayonn** [comment]
Thanks
