### ISSUE TITLE
Locking Up Using 

### ISSUE THREAD

**Issue by MikeHeighway** [airbnb/lottie-web#882]
**Tell us about your environment**
Mac OS High Sierra with MAMP

* **Browser and Browser Version:**
Chrome Version 64.0.3282.167

* **After Effects Version:**
AE 15.0.1 (Build 73)

**What did you do? Please explain the steps you took before you encountered the problem.**
This is my first attempt at Lottie. I have set everything up using MAMP and and in the latest version of AE. I'm pretty reasonable in AE, but this is new territory for me exporting into the web environment. 

I built up a comp using what I thought were supported features (ultimately Trim Paths, Scale and Opacity), and integrated Ease & Wizz for my easing. Nothing too fancy, there are 4 shape layers, not doing anything too terribly advanced. I am experiencing animation freezes when I test locally in Chrome and on LottieFiles.com

**What did you expect to happen?**
I expected this to play out like the AE comp does natively. 

**What actually happened? Please include as much _relevant_ detail as possible.**
Exporting from the attached Ease & Wizz comp in AE results in the animation freezing part way. For some reason, it seems the transforms (scale) are the culprit, though I cannot figure out why.

Comp "Fail-Ease & Wizz" fails in Chrome and on LottieFiles.com
Comp "Success-Outlines" succeeds locally in Chrome and on LottieFiles.com

It seems that the transforms (specifically, "Scale") are what are mucking up the animation.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/lispzj97ypm0brt/Checkmark%20Animation%20Problems.zip?dl=0

Thanks for the help! Please let me know if I've omitted something.
Mike

**Comment by bodymovin** [comment]
Hi, since version 5.x.x I'm using strict mode in Javascript and some expressions broke. If you export the animation with the latest version of bodymovin (5.1.7 instead of 5.1.1), it should work fine.

**Comment by MikeHeighway** [comment]
Oh, perfect. Thank you!
