### ISSUE TITLE
Animations not rendering in iOS Safari

### ISSUE THREAD

**Issue by johansuperstar** [airbnb/lottie-web#883]
**Tell us about your environment**

* **Browser and Browser Version:**
Safari on iOS 10.2

* **After Effects Version:**
Not sure, I didn't export the animations

**What did you do? Please explain the steps you took before you encountered the problem.**
When upgrading to the latest lottie_light build (I was previously using bodymovin), however the same happened for the full build, I noticed that my animations wouldn't run in Safari on iOS 10.2. 

**What did you expect to happen?**
That they would run

**What actually happened? Please include as much _relevant_ detail as possible.**
Noticed that the following line https://github.com/airbnb/lottie-web/blob/master/build/player/lottie_light.js#L281 was frequently called with NaN, this caused no issue other browsers, but in mobile Safari an exception was thrown. When I added a try catch to swallow the exception the animations rendered correctly.

**Please provide a download link to the After Effects file that demonstrates the problem.**
I've only got the JSON file https://gist.github.com/johansuperstar/da54b0aee08412ae47193b42c3fafca2

**Comment by bodymovin** [comment]
Hi, this will be fixed on version 5.1.8

**Comment by mcdappdev** [comment]
When does 5.1.8 come out?

**Comment by bodymovin** [comment]
later today :)

**Comment by mcdappdev** [comment]
Great thank you :)

**Comment by ShreyaSa** [comment]
Do we have the cdnjs link to version 5.1.8?
