### ISSUE TITLE
Animation glitches in Safari. Causing other scripts to not load correctly only in Safari

### ISSUE THREAD

**Issue by itshamy** [airbnb/lottie-web#884]
My site http://nvelupredesign.wpengine.com has 5 lottie svg animation on the homepage slider. Animation works fine in chrome etc. but glitches in Safari, especially the first and 3rd slide. The first slide's animation has some random glitching white lines on them and the animation is very fast. I've tried setting lottie.setSpeed(10); but it's still too fast.

I'm on a MacOS. This site is WordPress. There's no error in console. Expected behavior is supposed to be smooth like in Chrome. Unexpected behavior is the glitches in Safari.

I want to slow down animation on slide 1 as well. How do I go about correctly setting it?

Thanks

**Comment by bodymovin** [comment]
Hi, when you say the animation is very fast, is that happening only on Safari, or everywhere?
Regarding glitches, can you share a screenshot of the glitch and also the .aep?

**Comment by itshamy** [comment]
<img width="848" alt="screen shot 2018-02-26 at 8 45 21 am" src="https://user-images.githubusercontent.com/26393972/36818364-9c3474d4-1c99-11e8-9977-be394181ca3f.png">

<img width="1440" alt="screen shot 2018-02-25 at 11 05 33 am" src="https://user-images.githubusercontent.com/26393972/36818552-602fb358-1c9a-11e8-99c5-0b5894a79115.png">

There are random horizontal white lines that interrupting the animation. It's the first slide with the space needle. And on the last slide, there's a delay on the right sides of growing columns. On chrome and other browsers, all my scripts load correctly. On mobile safari, scripts load fine even though the first slide still glitches. But on desktop safari, my scripts get delayed and some of the bullets on the side of the slider don't even show. I think the glitch is causing it.

Here's my scripts for the slider
`$(document).ready(function(){
      $(window).trigger('resize');
      if ($(window).width() / $(window).height() < (1660 / 1020)) {
            $('.slide-image').addClass('tall');
        } else {
             $('.slide-image').addClass('wide');
        }
var ImageTechnology = function() {
      var element = document.getElementById('slide-image-technology');
      lottie.loadAnimation({
      container: element, // the dom element that will contain the animation
      renderer: 'svg',
      loop: true,
      autoplay: true,
      path: '/wp-content/themes/enfold-child/js/slide4_3.json' // the path to the animation json
      });
    };
    var ImageServices = function() {
      var element = document.getElementById('slide-image-services');
      lottie.loadAnimation({
      container: element, // the dom element that will contain the animation
      renderer: 'svg',
      loop: true,
      autoplay: true,
      path: '/wp-content/themes/enfold-child/js/Slide_3.json', // the path to the animation json
      preserveAspectRatio: 'slice'
      });
    };
    var ImagePeople = function() {
      var element = document.getElementById('slide-image-people');
      lottie.loadAnimation({
      container: element, // the dom element that will contain the animation
      renderer: 'svg',
      loop: true,
      autoplay: true,
      path: '/wp-content/themes/enfold-child/js/Slide 2.json' // the path to the animation json
      });
    };
    var ImageFinances = function() {
      var element = document.getElementById('slide-image-finances');
      lottie.loadAnimation({
      container: element, // the dom element that will contain the animation
      renderer: 'svg',
      loop: true,
      autoplay: true,
      path: '/wp-content/themes/enfold-child/js/Slide 1.json' // the path to the animation json
      });
    };
    var ImageSupply = function() {
      var element = document.getElementById('slide-image-supply');
      lottie.loadAnimation({
      container: element, // the dom element that will contain the animation
      renderer: 'svg',
      loop: true,
      autoplay: true,
      path: '/wp-content/themes/enfold-child/js/Slide 5.json' // the path to the animation json
      });
    };
    var homeSlider = $('#home-slider');
    var slides = homeSlider.find('.slides li');
    var bullets;
    var current = 0;
    var timeToChange = 12000;
    var isPlaying = true;
    var lastMillis = 0;
    var timerMillis = 0;
    var snap;
    var timerOutline;
    if (homeSlider.length > 0) {
        setup();
    }

    function setup() {
        var bulletsContainer = homeSlider.find('.bullets');
        snap = Snap(40, 40).attr({
            transform: 'translate(-20)',
            class: 'timer',
        });
        snap.append(Snap.parse('<g class="play">' + '    <path  fill="#FFFFFF" d="M15,10.5v19L29,20L15,10.5z M17,14.5l8.4,5.5L17,25.5V14.5z"></path>' + '</g>' + '<g class="pause">' + '    <rect x="15" y="14" fill="#FFFFFF" width="3" height="13"></rect>' + '    <rect x="21" y="14" fill="#FFFFFF" width="3" height="13"></rect>' + '</g>'));
        snap.circle(20, 20, 18).attr({
            fill: 'none',
            stroke: '#ffffff',
            strokeWidth: 3,
        });
        timerOutline = snap.path().attr({
            fill: 'none',
            stroke: '#00d961',
            strokeWidth: 3,
            d: getArcOutlinePath(18, 0),
            transform: 'translate(20 20)',
        });
        $(snap.node).click(toggleTimer);
        bulletsContainer.append(snap.node);
        slides.each(function() {
            var slide = $(this);
            var imageClass;
            switch (slide.attr('data-id')) {
                case 'people':
                    imageClass = new ImagePeople();
                    break;
                case 'finances':
                    imageClass = new ImageFinances();
                    break;
                case 'services':
                    imageClass = new ImageServices();
                    break;
                case 'supply':
                    imageClass = new ImageSupply();
                    break;
                case 'technology':
                    imageClass = new ImageTechnology();
                    break;
            }
            if (imageClass) {
                slide.data('slide-image', imageClass);
            }
            bulletsContainer.append('<li></li>');
        });
        bullets = bulletsContainer.children('li')
        bullets.click(function() {
            var index = $(this).index() - 1;
            changeSlide(index);
            pauseTimer();
        })
        $(window).resize(onResize);
        slideIn(0, true);
        playTimer();
    }

    function playTimer() {
        snap.attr({
            class: 'timer'
        });
        lastMillis = new Date().getTime();
        isPlaying = true;
        animateTimer();
    }

    function pauseTimer() {
        snap.attr({
            class: 'timer paused'
        });
        isPlaying = false;
    }

    function toggleTimer() {
        if (isPlaying) {
            pauseTimer();
        } else {
            playTimer();
        }
    }

    function animateTimer() {
        if (isPlaying) {
            var millis = new Date().getTime();
            timerMillis += millis - lastMillis;
            lastMillis = millis;
            timerOutline.attr({
                d: getArcOutlinePath(18, Math.min(359 * timerMillis / timeToChange))
            })
            if (timerMillis > timeToChange) {
                changeSlide(current + 1);
            }
            requestAnimationFrame(animateTimer);
        }
    }

    function changeSlide(newIndex) {
        if (current > -1 && current < slides.length) {
            slideOut(current);
        }
        current = newIndex;
        if (current < 0) {
            current = slides.length - 1;
        }
        if (current > slides.length - 1) {
            current = 0;
        }
        TweenMax.killDelayedCallsTo(slideIn);
        TweenMax.delayedCall(0.5, slideIn, [current]);
        timerMillis = 0;
        playTimer();
    }

    function slideOut(index) {
        var slide = slides.eq(index);
        slide.removeClass('current');
        var slideImage = slide.data('slide-image');
        bullets.eq(index).removeClass('selected');
    }

    function slideIn(index, isFirst) {
        var slide = slides.eq(index);
        if (!isFirst) {
            slide.addClass('current');
            $(document).trigger('class_current');
        }
        var slideImage = slide.data('slide-image');
        bullets.eq(index).addClass('selected');
    }

    function onResize() {
        if ($(window).width() / $(window).height() < (1660 / 1020)) {
            slides.children('.slide-image').children().attr('class', 'tall');
        } else {
            slides.children('.slide-image').children().attr('class', 'wide');
        }
    }

    function getArcOutlinePath(radius, angle) {
        var centre = 0,
            startY = centre - radius;
        var d = angle,
            dr = d - 90;
        radians = Math.PI * (dr) / 180, endx = centre + radius * Math.cos(radians), endy = centre + radius * Math.sin(radians), largeArc = d > 180 ? 1 : 0;
        var path = "M" + centre + "," + startY + " A" + radius + "," + radius + " 0 " + largeArc + ",1 " + endx + "," + endy;
        return path;
    }
});`

**Comment by itshamy** [comment]
I will send you the .aep later when I get a hold of the person that has it

**Comment by itshamy** [comment]
Here's the link to aep file https://drive.google.com/file/d/1_7TUSsH0Dae6FrwU3wEOxRGhmtxt4yBp/view?usp=sharing

**Comment by bodymovin** [comment]
This has probably been solver in version 5.1.18
Closing for now
