### ISSUE TITLE
Transform Expression Shortcuts Broken

### ISSUE THREAD

**Issue by paulslemmer** [airbnb/lottie-web#885]
Easy enough to get around but errors like this are hard to hunt down when you have a layer with a lot of expressions.

**Tell us about your environment**
macOS Sierra 10.12.6

* **Browser and Browser Version:** Chrome 64-Bit 64.0.3282.186 
* **After Effects Version:** 15.0.0

**What did you do? Please explain the steps you took before you encountered the problem.**
Used a shortcut expression "scale[0]" instead of "transform.scale[0]".

**What did you expect to happen?**
Exported animation would reference the layer's scale.

**What actually happened? Please include as much _relevant_ detail as possible.**
Layer with expression creates an error and does not appear in the exported animation.

**Comment by bodymovin** [comment]
Hi, expressions seem to have an endless amount of cases and I'm adding them whenever I find new ones.
If you can share the .aep with the expressions that break I'll make sure to add them on the next release.
