### ISSUE TITLE
Short circuit fetching a JSON file if passed a JSON object

### ISSUE THREAD

**Issue by nainar** [airbnb/lottie-web#886]
Hi, I am from the AMP team and we are considering adding an `<amp-bodymovin-player>` element for which we are using the lottie player. However, I am coming across a problem:
* The fetch happens from a local JSON file, however due to AMP CORS policy and the fact AMP fetches local files from cache, I was wondering if we(AMP or any other user of the playr) could instead perform the fetch and pass the JSON object to the API and then have the API skip the fetch if it is being passed a JSON object?

**Comment by nainar** [comment]
Issue regarding implementing `<amp-bodymovin-player>` is here: https://github.com/ampproject/amphtml/issues/12309

**Comment by bodymovin** [comment]
Hi! Instead of using the "path" which expects a path to a json file, you can use "animationData" which expects a javascript object exactly with the same format as an external json.
Would that solve the issue?

**Comment by nainar** [comment]
Yes it would thank you! :)
