### ISSUE TITLE
animation does not work correctly in IE

### ISSUE THREAD

**Issue by ihaichao** [airbnb/lottie-web#888]
**Tell us about your environment**   windows10

* **Browser and Browser Version:**  IE11
* **After Effects Version:**  2017             

**What did you do? Please explain the steps you took before you encountered the problem.**
```
  const animation = lottie.loadAnimation({
      container: document.getElementById('base-bubble'),
      renderer: 'svg',
      // autoplay: true,
      // loop: true,
      animationData: animationData
    })
```
**What did you expect to happen?**

![chrome](https://user-images.githubusercontent.com/8586268/36889052-2252a19a-1e33-11e8-9c77-63dc84076640.gif)

**What actually happened? Please include as much _relevant_ detail as possible.**

In ie11, it renders like the gif below
![ie](https://user-images.githubusercontent.com/8586268/36889150-9c9b1644-1e33-11e8-913e-fe403b4a2ede.gif)

**Please provide a download link to the After Effects file that demonstrates the problem.**

[gift.zip](https://github.com/airbnb/lottie-web/files/1774111/gift.zip)

**Comment by bodymovin** [comment]
Hi, can you share a link or the json? I see it running fine in my ie11

**Comment by ihaichao** [comment]
[animation.zip](https://github.com/airbnb/lottie-web/files/1779329/animation.zip)

**Comment by icdindia** [comment]
any fix? We are facing the same problem.

**Comment by bodymovin** [comment]
This is an IE issue that can't be fixed by the library unfortunately
