### ISSUE TITLE
swf, fla, svg, snap or sprite animations to bodymovin

### ISSUE THREAD

**Issue by twistedinferno** [airbnb/lottie-web#889]
I have a bunch of animated vector graphic files that I would like to convert to bodymovin (I assume I would need to convert them into after effects first and use the bodymovin extension).  My animated files are in swf, fla, svg (using the animate element inside the svg), snap and sprite.js html5 formats. I need to preserve the animations (recreating them is not really an option).  Is there a way to achieve this?

_(apologies if this kind of question doesn't belong here...I'll humbly delete it if not appropriate :-)_

**Comment by twistedinferno** [comment]
Here is a link to the same image in four different formats
https://drive.google.com/open?id=16RxvtkpythKIxuad6oIPDDjDz2ogw72M

**Comment by bodymovin** [comment]
Hi, unfortunately there is no way to convert those formats to the bodymovin format yet.

**Comment by sebinievas** [comment]
Is there a roadmap for any of these? I've found this vendor that seems to be more promising than using AE/bodymovin.
