### ISSUE TITLE
Track mattes not rendering correctly in Firefox & Chrome

### ISSUE THREAD

**Issue by andy-88** [airbnb/lottie-web#890]
**Tell us about your environment**
Mac Pro, OS Sierra 10.12.6
* **Browser and Browser Version:** Firefox 58.0.2 / Chrome 64.0.3282.186
* **After Effects Version:** CC 2018, Version 15.0.0

**What did you do? Please explain the steps you took before you encountered the problem.**
Hi, I've been working on an animation where I've been creating shapes from imported vector layers and then using track mattes to reveal the shapes during the animation. This is all fine and fairly standard and works perfectly in After Effects and as rendered video. However if I render the composition out through bodymovin the track mattes no longer work/display. This is specifically evident in Firefox and Chrome. Seems to work as it should in Safari.

What's even more weird (and it took flippin' ages to figure this out!) is that the issue only seems to apply to horizontal and vertical track mattes. If I render out a track matte that is on an angle such as 45 degrees it works and displays fine in Firefox and Chrome.

Any help on this would be greatly appreciated. Below are links to my source files.

**Please provide a download link to the After Effects file that demonstrates the problem.**

aep and bodymovin file here – https://nofile.io/f/9FykoWxuAAE/track-matte-issue.zip

**Comment by bodymovin** [comment]
Hi, this is an issue with browsers and strokes.
If you create a transparent shape that measures the size of the stroke, it should work fine.
On the 45 degree shape, since you have a path of a single line, it solves this issue by chance.
You can modify the path on your layer line-2 Outlines > Contens > Group 2 > Path 1 to make it oblique and as long as it covers the size of the stroke, it will work fine.

**Comment by andy-88** [comment]
Hi, thanks for the feedback, but I'm still having trouble getting this to work. Where would I be creating the transparent shape that's the same size as the stroke? I've tried creating one within the contents of the line-2 Outlines layer and one as a separate layer all together but I still can get the track matte to work. Apologies if this is a really simple fix! Thanks.

**Comment by bodymovin** [comment]
It should be in the same layer than the one that has the stroke.
And by transparent I mean it needs a fill but with it's opacity set to 0.
so for example:
> Contents
- Group
  - path
  - stroke
- Group 2
  - rectangle
  - fill
    - opacity: 0

**Comment by andy-88** [comment]
Perfect, thank you for that, it seems to solve the issue even if a little bit of a messy workaround. Thanks.
