### ISSUE TITLE
Cannot Destroy Instance of Animation

### ISSUE THREAD

**Issue by aakey7** [airbnb/lottie-web#893]
I have 3 functions connected to buttons to control my animation. The first 2 play the animation how it should however the 3rd one throws an error when i try to destroy the animation to load a new .json file.

If i type the exact same commands in google command line they execute fine. Anybody have any ideas why the button fails to destroy the animation?

```
function playIn() {
      animation.setDirection(1);
      animation.playSegments([
        [0, 85]
      ], true);
    }

    function playOut() {
      animation.goToAndStop(75, true);
      animation.setDirection(-1);
      animation.play();
    }

    function load2() {
      animation.destroy();
      var animation = lottie.loadAnimation({
        container: document.getElementById('bm'),
        renderer: 'svg',
        loop: false,
        autoplay: false,
        path: 'data2.json'
      });
    }
```

**Comment by bodymovin** [comment]
Hi, can you share a link?

**Comment by wst-shorty** [comment]
http://kick-push.co.uk/bodymovin/superbowl/

**Comment by bodymovin** [comment]
It's because of Javascript's hoisting.
You're declaring a variable called animation inside that function that is scoped in the same function where you're calling animation.destroy
Even if you're calling it before, javascript promotes all variable declarations to the top of function, so what is actually happening behind the scenes is the following:
````javascript

function load2() {
 var animation; // variable is declared here
 animation.destroy(); // so here animation is undefined
 animation = lottie.loadAnimation({
 container: document.getElementById('bm'),
 renderer: 'svg',
 loop: false,
 autoplay: false,
 path: 'data2.json'
 });
}


````

**Comment by wst-shorty** [comment]
Would splitting them into 2 function calls prevent it? Or is there a better way to prevent hoisitng?


```
    function destroy() {
      animation.destroy();
    }

    function load2() {
      var animation = lottie.loadAnimation({
        container: document.getElementById('bm'),
        renderer: 'svg',
        loop: false,
        autoplay: false,
        path: 'data2.json'
      });
    }
```

**Comment by wst-shorty** [comment]
Ok silly me! Thanks. for helping with that. Problem solved!
