### ISSUE TITLE
hello，from china，Apple handset displays are different from chrome and Android mobile phones

### ISSUE THREAD

**Issue by callren** [airbnb/lottie-web#894]
Can you understand Chinese？

**Comment by ljharb** [comment]
Can you elaborate on your issue?

**Comment by callren** [comment]
你好开发者，我在使用AE导出文件之后，加载到页面中，手机端显示和chrome网页端不一致，两张图对比

chrome显示
![chrome](http://github.renyanan.com/issues/chrome.png)

iPhone显示
![phone](http://github.renyanan.com/issues/phone.jpeg)

看出中间一块区域是不存在的
demo地址:http://github.renyanan.com/issues/AEDemo.zip
[demo](http://github.renyanan.com/issues/AEDemo.zip)

**Comment by bodymovin** [comment]
Hi, I can't access the AEDemo.zip file
