### ISSUE TITLE
Json animation not working when masks applied

### ISSUE THREAD

**Issue by kloskow** [airbnb/lottie-web#895]
Hi there, my .json file does not appear in Lottiefile preview nor standalone LottieUWP.sample. On the other hand everything looks totally in order when I run html via a browser. I use subtract masks to achieve the reveal effect. When the mask layer is fully removed from the composition within AE and exported with no mask layer, image shows up with no issues.
any help would be greatly appreciated.

Please find the attached project files.
[demo(1).zip](https://github.com/airbnb/lottie-web/files/1789268/demo.1.zip)

**Comment by bodymovin** [comment]
Hi, can you share the LottieFile editor url?

**Comment by kloskow** [comment]
Sorry, I made a mistake in the post above. I meant Lottiefile preview not editor. The .json file appears as intended in the editor but Lottiefile preview as well as LottieUWP standalone app does not show the animation at all. The demo zip folder includes the .json file.

**Comment by bodymovin** [comment]
It doesn't seem to be an issue with the web version, then.
Can you post this issue in the android repo?
https://github.com/airbnb/lottie-android

**Comment by kloskow** [comment]
hi there, sorry for such a late reply. Yes sure I will, thank you.
