### ISSUE TITLE
Documentation on TextLayer.updateDocumentData

### ISSUE THREAD

**Issue by BillyTheGit** [airbnb/lottie-web#896]
I want to dynamically change the text in an animation, I tried to find any information, but the documentation on the wiki seems to be very minimal or maybe I'm not experienced enough.

It is unclear what the path should be or where to find it. The example (anim.elements[0].) isn't making it clear since it also hold variables (at least, I think they do). So I think it can be clarified a bit more.

I wouldn't mind writing a bit more detailed explanation myself, when I'm able to understand it.
Thank you in advance.

**Comment by bodymovin** [comment]
Hi, I'm working on an API that will make this more understandable.
https://github.com/bodymovin/lottie-api
As soon as it's ready and well documented I'll let you know

**Comment by BillyTheGit** [comment]
@bodymovin That is great! I realized I had to put it in domloaded for it to work. Not sure how I skipped that, but it is working now. 

But thanks for letting me now! Looking forward to the api and thanks for all the work you are putting into this.

**Comment by robbbsen** [comment]
Is there any update to this topic? I've searched for that function but couldn't find anything. I've created a example (forked a animation) and logged the first element to the console. There is no "updateDocumentData" function.

https://codepen.io/anon/pen/JzeYJW?editors=0110
