### ISSUE TITLE
Checkboxes drawn as radio buttons

### ISSUE THREAD

**Issue by amn** [airbnb/lottie-web#902]
In the "Settings"-pane of Bodymovin plugin for After Effects, what works as checkboxes is drawn with round circles and disks, fooling anyone who has ever used a modern computer interface, to believe that they're dealing with radio buttons.

Why can't these elements drawn as checkboxes, since they are, well, checkboxes?

Image for reference:

![bodymovin-1](https://user-images.githubusercontent.com/471489/37280161-45839f7c-25ed-11e8-8876-738bb23fea9a.PNG)

**Comment by bodymovin** [comment]
good catch!
I had that animation and that's why I used it.
Glad to change it if you have a better one to propose :)
