### ISSUE TITLE
Bodymovin - My animations are exporting without capturing the details that are including in the animation created in after effects.

### ISSUE THREAD

**Issue by natepanetti** [airbnb/lottie-web#903]
![image](https://user-images.githubusercontent.com/37312642/37310970-aca85b04-2613-11e8-8edf-0075bdfdc03a.png)
This is how my animation appears in after effects
![image](https://user-images.githubusercontent.com/37312642/37311012-cb136d18-2613-11e8-85ee-065a6af198f3.png)
This is how the animation is when I view it in the browser. 

I'm using bodymovin and everything seems to be running smoothly. I have followed this tutorial and my animation comes out without the initial detail included in the animation. 

https://www.youtube.com/watch?v=3PbUL3z9bIs&ab_channel=MotionPlus

**Tell us about your environment**
I am working on a macbook in after effects and using bodymovin as the SVG animation extension. 
* **Browser and Browser Version:**
Google chrome - the latest version
* **After Effects Version:**
Creative Cloud - latest updated version
**What did you do? Please explain the steps you took before you encountered the problem.**
I created the animation, opened the bodymovin extension in after effect, went to settings of the extension popup and enabled the demo option. When I opened the demo in my browser, the animation was far from how it appeared in my after effects file. I was using vectored layers in the AE file. 
**What did you expect to happen?**
I expected my animation to look as it should in the browser. 
**What actually happened? Please include as much _relevant_ detail as possible.**
The imagery was almost inverted from how it was supposed to look and I don't know how it happened. From being a filled shape, to being basically an outlined shape. It seems as though it isn't processing the imagery properly. 
**Please provide a download link to the After Effects file that demonstrates the problem.**
https://drive.google.com/file/d/1rVJkXT5ohyN5Nunczhtz1t6OozfquET-/view?usp=sharing

**Comment by bodymovin** [comment]
Hi, I don't have access to that drive file, but this is probably related to converting your illustrator layers to vector shapes.
Sometimes AE adds unnecessary groups and merge paths. Since Lottie doesn't support merge paths, you get this type of results.
If you remove the extra group and merge path from your shape layers, it will work fine.
There is a tool called explode shape layers that does this automatically.

**Comment by natepanetti** [comment]
Awesome, I will give this a shot! Thank you for getting back to me so quickly :)
