### ISSUE TITLE
Bodymovin ignores nested composition size and changes layers order

### ISSUE THREAD

**Issue by IlyaMelnix** [airbnb/lottie-web#904]
Hi there!

Firstly, I would like to thank you for such a convenient plugin 👍 

I got a trouble and I can't find the causes. When rendering JSON with bodymovin, the result ignores the borders of the nested composition and changes layers order. Here is a quick video-demo:

https://youtu.be/7OcK2GBVdHk

Here is a link to a project file and video demos:
https://yadi.sk/d/nqZ1Rkwb3TL8bp

Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
After Effects version 15.0.0 (Build 180)

**Comment by bodymovin** [comment]
Hi, this is an issue from combining 2d and 3d layers.
It will be fixed on the next build.

**Comment by IlyaMelnix** [comment]
Ok, understood. Thank you! Great job!
