### ISSUE TITLE
Undo Group Around Render in AE Extension?

### ISSUE THREAD

**Issue by paulslemmer** [airbnb/lottie-web#906]
There's no undo group around the render scripting in the bodymovin AE Extension. For complex scenes, this makes it effectively impossible to undo back to anything before you hit Render.

**After Effects Version:**
After Effects CC 2018 15.0.1

**What did you do? Please explain the steps you took before you encountered the problem.**
Rendered a comp with Bodymovin. Tried to Undo.

**What did you expect to happen?**
Takes you back to the state before render.

**What actually happened? Please include as much _relevant_ detail as possible.**
After Effects treats each step of the Render process as its own action for undo.

**Comment by bodymovin** [comment]
The extension usually doesn't perform any AE action that goes to the history stack.
Unless you're using text or images, it should be fine.
In those cases I've tried fixing it, but I haven't been able to group all the actions it needs to do.
I'll take another look at it.

**Comment by paulslemmer** [comment]
I think the issue I'm running into is with glyph conversion. The undo command steps back through every scripted action in the font/character helper comps. If those could be wrapped in an undo group I think that would solve it.

**Comment by bodymovin** [comment]
Yeah, glyphs are indeed a problem. I'll give it another shot.

**Comment by bodymovin** [comment]
Ok, I think I have it working.
For now it's an undo per rendered composition.
It will be released on the next build.

**Comment by jetrotal** [comment]
@bodymovin 
Render button messes with my undo history too.

Here, this is my undo history, I just openned a project and hit bodymovin's render button:

![image](https://user-images.githubusercontent.com/45118493/181774897-cb6b1572-c3d0-4899-b9ba-d7b6fa1bf099.png)

I use undo a lot to change visual stuff. 
I guess the ideal scenario is one where the render button never generates any undo task at all... 

Thanks in advance.
