### ISSUE TITLE
Hello, how does this plug-in know how many frames have been played

### ISSUE THREAD

**Issue by callren** [airbnb/lottie-web#907]
The corresponding method is performed on the number of frames, but the animation does not stop

**Comment by callren** [comment]
已经解决，感谢，用enterFrame

**Comment by bodymovin** [comment]
Hi, not sure I understand the question.
Each animation instance has an internal time keeping track of the elapsed time of the animation.

**Comment by callren** [comment]
Use enterFrame to listen?
example：
lottie.addEventListener('enterFrame', function (e) {
    var num = parseInt(e.currentTime);
    console.log(num);
    if (num == '20') {
        console.log('do something');
    };
});
