### ISSUE TITLE
Handwriting effect does not work correctly

### ISSUE THREAD

**Issue by guitar9** [airbnb/lottie-web#911]
Hi,
I've been trying to do a simple handwriting animation test in after effects but when loading the export in chrome it writes all letter at the same time. I'm using the stroke effect. When i play it at adobe after effect it works correctly. I did exactly this steps like in this video. I used bodymovin at export the demo.html.
[https://www.youtube.com/watch?v=zSlXOIsfjLY](Link)

Somebody can help me?

**Comment by guitar9** [comment]
nobody has an idea?

**Comment by bodymovin** [comment]
Hi, the stroke effects is not fully supported.
Can you share the .aep so I can check it out?

**Comment by AntonVoltchok** [comment]
hey bud, I recently switched over from stroke to using trim path instead to animate that type of effect, great performance even with 30 other objects moving at the same time synced to page scroll, so I would suggest going down that route.  (Also trim path works flawlessly across all browsers even internet explorer.)  Post your files , happy to help.

@bodymovin amazing job with this library brother, I haven't had this much fun with a lib in a very very long time. Started reading the source code recently whenever I get a little bit of free time so eventually I can help contribute.   

Do you think there's any way this concept can roll over to exporting 3D work in aftereffects to a web gl renderer? Another reason I started reading the source was to see if that was a possibility.

**Comment by guitar9** [comment]
here is the project
https://ufile.io/3oc17

**Comment by guitar9** [comment]
so i should use trim path instead?

**Comment by bodymovin** [comment]
I couldn't download the file from that link. Can you attach it here?

**Comment by guitar9** [comment]
here is it
[handwriting.zip](https://github.com/airbnb/lottie-web/files/1849907/handwriting.zip)

**Comment by bodymovin** [comment]
Hi, the stroke effect is not fully supported. and the sequential option is unfortunately not supported.
Can you user three different layers instead?

**Comment by guitar9** [comment]
i dont have much experience with adobe after effect. I just did this steps
in the Tutorial. Maybe if have time i will try it. An little exmample would
nice. For example just hello or something else.

**Comment by OlafHaalstra** [comment]
Did you eventually come up with a solution? I'm facing the same problem currently as well. What exactly is and isn't supported? Since it says that the stroke effect is partially supported.
