### ISSUE TITLE
Pink background issue

### ISSUE THREAD

**Issue by XBLDev** [airbnb/lottie-web#912]
Hi all

Some of my animations have pink backgrounds when they are not supposed to.

For example, one of them is supposed to look like:
![2](https://user-images.githubusercontent.com/26809749/37464335-1f7945ea-28ac-11e8-9633-2a52c222bb46.png)
But instead, it comes with a pink background that covers most of the screen:
![1](https://user-images.githubusercontent.com/26809749/37464370-3c2a1b2e-28ac-11e8-8b26-e8a59abbb642.png)

I looked through some of the posts here about pink background, it seems to have something to do with some effect called linear gradient? I'm no expert on After Effect so I don't know much about it.

My json file is attached below and it would be nice if someone can have a look at it and tell me what's wrong and how to fix the problem. Thanks in advance for your answers!

[pinkbackground.zip](https://github.com/airbnb/lottie-web/files/1815416/pinkbackground.zip)

**Comment by bodymovin** [comment]
Hi, can you share the .aep?
It's probably related to converting ai layers to shapes, but I can't be sure.

**Comment by XBLDev** [comment]
Hi @bodymovin thanks, my aep file is attached :-)

[Group 2 Image 5 Lighting and Cogs.zip](https://github.com/airbnb/lottie-web/files/1837488/Group.2.Image.5.Lighting.and.Cogs.zip)

**Comment by bodymovin** [comment]
yes, indeed if you check you layer "Arms Outlines" for example, there are two properties you need to erase:
Arms Outlines > Contents > Group 1 > Path 2
Arms Outlines > Contents > Group 1 > Merge Paths 1

if you do this with all contents of your layers, it should get fixed.
There is an AE script called Explode Shape Layers that I think that does this automatically.
https://aescripts.com/explode-shape-layers/

**Comment by XBLDev** [comment]
@bodymovin thanks so much! I'll see if it works and report back!
