### ISSUE TITLE
Animation not working, Only visible when logged in as admin

### ISSUE THREAD

**Issue by dalewesdorp** [airbnb/lottie-web#913]
Character scrolling effect not working. I have tried to implement it today for several hours, and maged to get it working when logged in as administrator using this post: https://github.com/airbnb/lottie-web/issues/549#issuecomment-361544571.

After trying to get it to work for users who are not logged in it stopped working all together. When i preview it in body movin it doesnt seem to animate aswell. i have uploaded the demo on this link:

https://dalewesdorp.nl/demo.html

**Windows 10**

* **Google Chrome**
* **After Effects Version: 15 (CC2018)**

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by dalewesdorp** [comment]
Got the bodymovin.js and data.json files in the upload directory. In the beginning the animation was actually running on https://dalewesdorp.nl/43-2/ when logged in as an administator. When logged out it would show the same it does now. Is this a problem with the rendering or the way its embedded on the page?

**Comment by dalewesdorp** [comment]
https://we.tl/x7c07n2eXi we transfer link to .aep file

**Comment by bodymovin** [comment]
I've found the issue. It'll be fixed in the next release.
There is an undeclared variable in use.
Meanwhile, as a workaround, if you delete the 'strict mode' string from the lottie.js, it should work fine.

**Comment by dalewesdorp** [comment]
Thank you! It's Working fine now

**Comment by dalewesdorp** [comment]
Hey Bodymovin,

Thanks for the solution. Just another question. I want te moving border to be responsive so i set the preserveAspectRatio to 'none'. On the demo (http://www.zeezoutfestival.nl/demo.html) you can see it is working fine. When i try to implement this with a fixed div on the main site it stops scaling. (http://www.zeezoutfestival.nl/zeezout-festival-2017/) What can be te reason it does that?

Kind regards,

Dale

**Comment by bodymovin** [comment]
Hi, apparently your container is setting the width and height of the animation.
I'm not sure what you're trying to achieve, but it looks like you need to check your implementation on the fusion library
