### ISSUE TITLE
Data.jason File not Previewing Correctly

### ISSUE THREAD

**Issue by tdhl** [airbnb/lottie-web#915]
**Tell us about your environment**

* **Browser and Browser Version:**
Google Chrome	64.0.3282.186 (Official Build) (64-bit) (cohort: Stable)

* **After Effects Version:**
Adobe After Effects CC 2018 (15.0.1)

**What did you do? Please explain the steps you took before you encountered the problem.**

1. I made my assets in AI and imported the layers into AE, started animating it with Joystick n Sliders. 
2. Installed bodymovin v5.1.8. 
3. Selected my comp and rendered a data.jason file with bodymovin
4. The tried to view the data.jason in the "Preview" option of bodymovin but the shapes are not set up and there is no animation. 

![bodymovin_issue](https://user-images.githubusercontent.com/8474558/37503239-1cb8a6b6-28cf-11e8-9809-7b134e86e5c0.jpg)

I also tried adding the data.jason in my index.js. 

**What did you expect to happen?**
The animation would play in the web browser and preview option of bodymovin in AE

**What actually happened? Please include as much _relevant_ detail as possible.**
Animation preview did not work in AE, and when I load the index.html file nothing appears in the browser.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/hlk8j2os2r7xb65/bodymovin.zip?dl=0

**Comment by bodymovin** [comment]
Hi, make sure you include Guided layers as part of the setting in the bodymovin panel.
JnSliders use guided layers that don't get exported by default.

**Comment by tdhl** [comment]
That fixed my problem, thank you!

**Comment by rotemda** [comment]
Hi, I have an issue with jason file I exported with bodymovin.
animation seems to work fine at the begining but at the end the 2 last elements are crossing behind the pacman.
How I can solve this? all elements are shapes - see attached files:
[pacman files.zip](https://github.com/airbnb/lottie-web/files/2849086/pacman.files.zip)

**Comment by bodymovin** [comment]
@rotemda hi, I see it working fine. What do you mean crossing behind?

**Comment by rotemda** [comment]
@bodymovin Hi, see screenshoot:
![image](https://user-images.githubusercontent.com/47501824/52769899-60b19d00-303a-11e9-87b5-b46fbde14a10.png)

**Comment by bodymovin** [comment]
I see it working fine. Can you share a working link with the problem?

**Comment by rotemda** [comment]
@bodymovin in the file I attached there is a video describing the problem.
can you run the jason file and see?
https://github.com/airbnb/lottie-web/files/2849086/pacman.files.zip

**Comment by bodymovin** [comment]
Hi, is this using the lottie-ios or lottie-android players?

**Comment by rotemda** [comment]
@bodymovin lottie-ios

**Comment by bodymovin** [comment]
you should report it on the ios repo
https://github.com/airbnb/lottie-ios
