### ISSUE TITLE
Animation not going to last frame using goToAndStop

### ISSUE THREAD

**Issue by ferusinfo** [airbnb/lottie-web#917]
**Tell us about your environment**

* **Browser and Browser Version:** Safari on Mac OSX, Version 10.1.2 (12603.3.8)
* **After Effects Version:** n/a

**What did you do? Please explain the steps you took before you encountered the problem.**
I've loaded the animation and wanted it to go to the last frame.
I am loading the animation through `animationData` parameter.

**What did you expect to happen?**
Animation to go to the last frame (or any  by using `animation.goToAndStop(animation.totalFrames-1, true)`

**What actually happened? Please include as much _relevant_ detail as possible.**
Animation did not change the frame.
When using the `animation.goToAndStop(frameNumber, true)`, the animation changes up to frame around 80-100, and then the method stop working. 
**Note: When using the `play()` method the animation is viewed correctly and loops as desired without problems**

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://www.dropbox.com/s/268gzj195jw1wbb/animation_issue.json?dl=1

**Screenshots.**

Correct last frame
![correct_frame](https://user-images.githubusercontent.com/1098045/37520555-d44b3b74-291d-11e8-8577-c46af7de9d49.png)

Wrong last frame
![wrong_frame](https://user-images.githubusercontent.com/1098045/37520556-d4696590-291d-11e8-976d-95b6e09ea44f.png)

**Demo player file**
https://www.dropbox.com/s/qwdg5r49vrbpqga/demo_issue.html?dl=1

**AEP file**
https://www.dropbox.com/s/gwsawzvh4gnoqer/animation_issue.aep?dl=0

**Comment by ferusinfo** [comment]
Works correctly under `bodymovin v4.13.0`, going to find out when it is breaking down.

**Comment by ferusinfo** [comment]
I've found out that the version that the bug occurs starts at version `5.1.0`. Under `5.0.6` I am unable to reproduce the bug.

**Comment by bodymovin** [comment]
Hi, can you share a link with the implementation?
on thje demo_issue file I don't see that you're calling the method ````goToAndStop()````

**Comment by ferusinfo** [comment]
@bodymovin I am calling the method in the safari inspector `animation.goAndStop(animation.totalFrames-1,true)`

**Comment by bodymovin** [comment]
I just tried it but I'm not able reproduce the issue.
Closing it for now.
If you can provide an example, please reopen.

**Comment by ferusinfo** [comment]
[issue.zip](https://github.com/airbnb/lottie-web/files/2080406/issue.zip)

I am attaching the issue again, since we cannot use the newer versions of lottie. 
Steps to reproduce:
- Open the html file in Safari (Disable local file restrictions under Safari Develop)
- Click Play
- Click Stop
- Click Last Frame - on thist step the animation will not show last frame.

**Comment by marcolussetti** [comment]
Probably not idea but I found that a call .setCurrentRawFrame works pretty well for getting to the end.

**Comment by bodymovin** [comment]
I've been trying to reproduce it but I don't have a Mac and it's complicated to debug.
I'll see if I can get one and test it there.

**Comment by bodymovin** [comment]
@miszmaniac thanks! I've merged it to master.

**Comment by bodymovin** [comment]
this should be fixed with version 5.1.18
