### ISSUE TITLE
Rig animation with Rubberhose is not working

### ISSUE THREAD

**Issue by pizza0502** [airbnb/lottie-web#919]
I've animated a rig hand with Rubberhose but once I export with Bodymovin and preview in the Lottie web, there is no animation at all.

Here is my AE file: https://www.dropbox.com/s/jbskur1gm4wyc7r/ElonWave.aep.zip?dl=1

**Comment by bodymovin** [comment]
Hi, that link doesn't seem to work.
If you're using Rubberhose 2, make sure you include guides and hidden layers on the export.
