### ISSUE TITLE
animated text split into two lines

### ISSUE THREAD

**Issue by amnonikatoni** [airbnb/lottie-web#920]
I'm using Google Chrome Version 64.0.3282.186, with After Effects Version 15.0.0

I am creating an animation that includes words turning into numbers and then into words again. Example GIF below:
![justlikecash](https://user-images.githubusercontent.com/33703612/37616285-d0fab976-2b85-11e8-8498-788b62d72b07.gif)

When I exported to a json file using bodymovin, it came out like this:

![justlikecash_json](https://user-images.githubusercontent.com/33703612/37616547-b1224aaa-2b86-11e8-8f93-fe5748e544c4.gif)

Any ideas what may be causing this?

Thanks!

**Comment by bodymovin** [comment]
hi, can you share the .aep and the implementation?

**Comment by amnonikatoni** [comment]
Here is the aep file:

https://github.com/amnonikatoni/AE_JSON/blob/master/JLC_Solo.aep

I'm a bit new to this - could you specify what you mean by implementation?

Thanks again

**Comment by bodymovin** [comment]
closing. This is fixed in current version.
