### ISSUE TITLE
Source text expression isn't rendering

### ISSUE THREAD

**Issue by 448jp** [airbnb/lottie-web#922]
**Tell us about your environment**

* **Browser and Browser Version:** Google Chrome 65.0.3325.181
* **After Effects Version:** CC 2018 (15.0.1)

**What did you do? Please explain the steps you took before you encountered the problem.**
1. Add text layer and slider control.
1. Add key frame to slider control, and count up number.
1. In source text expression, write "Math.floor, and add comma" code.
1. Render, and open browser, but number isn't rendering.

**What did you expect to happen?**
Render and count up number.

**What actually happened? Please include as much _relevant_ detail as possible.**
Number isn't rendering.

**Please provide a download link to the After Effects file that demonstrates the problem.**
https://448.jp/tmp/github/text.aep

**Comment by bodymovin** [comment]
I've fixed some text issues and they'll be deployed on the next build.
But your expression is returning an array as the source text and this breaks the expression on the browser side.
If there a reason why you return `[num]` instead of `num`?

**Comment by 448jp** [comment]
Thank you for your reply. I expect the next build.
Return value is my mistake. As you say, it's correct to return as a number.
