### ISSUE TITLE
SyntaxError: Invalid character: '@'

### ISSUE THREAD

**Issue by thaislescano** [airbnb/lottie-web#923]
I am following this GitHub tutorial to add the animation to my page.
My code right now looks like this:

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <style>
        body, html{
            background-color:#000;
            margin: 0px;
            height: 100%;
            overflow-x: hidden;
            overflow-y: auto;
        }

        #lottie{
            background-color:#000;
            width:100%;
            height:100%;
            width:1280px;
            height:1024px;
            display:block;
            overflow: hidden;
            transform: translate3d(0,0,0);
            margin: auto;
            /*display:none;*/
        }

        .botas_loop_3,.botas_loop_2{
            display:none
        }

        #bird_element.ready, #piano_element.ready, #cat_element.ready {
            opacity: 1;
            transition: opacity .6s ease-out;
            cursor: pointer;
        }

        #bird_text_element, #piano_text_element, #cat_text_element {
            opacity: 0;
            transition: opacity .6s ease-out;
        }

        #bird_element.ready:hover ~ #bird_text_element,
        #piano_element.ready:hover ~ #piano_text_element,
        #cat_element.ready:hover ~ #cat_text_element {
            opacity: 1;
        }

        #bird_element.ready:hover,
        #piano_element.ready:hover,
        #cat_element.ready:hover {
            opacity: 0.2;
        }

        button {
            padding: 0;
            border: none;
            background-color: transparent;
        }

    </style>
    
     <script src="lottie.js"></script>

</head>
<body>
<div id="lottie"></div>

<script>
    var anim;
    var elem = document.getElementById('lottie');
    var animData = {
        container: elem,
        renderer: 'html',
        loop: true,
        autoplay: true,
        rendererSettings: {
            progressiveLoad:false,
        },
        path: 'agenda.json'
    };
    anim = lottie.loadAnimation(animData);
</script>
</body>
</html>

When we export simple animations
https://github.com/airbnb/lottie-web/files/1834490/AGENDA.3.zip)
, with shape layers, it works fine. When we use illustrator files in the animation, it doesn't work and shows the SyntaxError: Invalid character: '@'.
The beginning of the animation is showed but it quickly stops and shows the error

I hope you can understand what I am trying to say :)

Attached is the AE file.

Thanks!
[AGENDA 3.zip](https://github.com/airbnb/lottie-web/files/1834495/AGENDA.3.zip)

**Comment by bodymovin** [comment]
It seems you are using an encrypted expression.
Unfortunately, they are not supported by the player.
