### ISSUE TITLE
Help Wanted: With After Effects to Bodymovin [Lottie] Render #First Issue

### ISSUE THREAD

**Issue by Sharan-Ajith** [airbnb/lottie-web#924]
Hey Guys,

Have an issue with the @lottie conversion of one of my projects.
Made character parts in Illustrator [Separately] and joined them together in After effects, converted them all into shapes and tried rendering into Json via @bodymovin Plugin.

https://user-images.githubusercontent.com/33069268/37693163-e8962af2-2ce3-11e8-9900-70e62df0c836.gif

^ This is the Actual Render in GIF Format [this is how its supposed to uncover]

But this is how the Json is rendering: https://lottiefiles.com/share/sYnWej

Don't know whats wrong as there is no fancy effects or anything, just straightforward transform function related animations. Please do let me know whats going wrong and how to solve it. :) Any help would be appreciated.

Im Using Adobe After Effects CC 2018 & Bodymovin V5.1.1

Thanks & Regards
Sharan

**Comment by bodymovin** [comment]
Hi, this is usually related to converting ai layers to shapes in AE.
On some cases (for example if your layers in AI exceed the artboard), AE creates a merge path and an additional large square path (sometimes insidea group).
Since lottie-web doesn't support merge paths, you get this kind of artifacts.
If you remove the merge path and the extra squares from your AE layer contents, it should work fine.

**Comment by Sharan-Ajith** [comment]
Hi there!

Thank you soo much for that piece of knowledge.. :) worked like a charm when i deleted the extra squares and the merge paths.
Looks just like how it should -> https://www.lottiefiles.com/share/P7uVh2

Although I have 2 more concerns:

1. If u chk the Gif I had posted -> https://user-images.githubusercontent.com/33069268/37693163-e8962af2-2ce3-11e8-9900-70e62df0c836.gif has the Ninja swaying side to side dodging shurikens.. Its not happening in the bodymovin render... its a **3D file**... is it because of that..? 

2. The Speed Lines on top and behing the ninja layer giving it a sense of speed is also not rendering. Its a layer with 4 Effects namely A) Fractal Noise, B) Transform, C) CC Threshold & D) CC Linear Color Key

Thanks again for the help and responding to my silly questions with ur valuable time :)

Regards
Sharan

**Comment by Sharan-Ajith** [comment]
Oh.. Ohk Ohk.. got it... its kind of unfortunate but its fine... :) will have to make do with the doable stuff..

Again thank you so much for the info!

will be marking this issue closed. :) 

Thanks & Regards
Sharan
