### ISSUE TITLE
setting triggers based on class or id

### ISSUE THREAD

**Issue by samiam2017** [airbnb/lottie-web#925]
I’m a motion designer so don’t have all the programming knowledge but I was looking for insights to help make the devs job easier (they tend to be apprehensive with using these new tools).
 
I was looking to doing a number of tests by switching out an interactive onboarding animation with the goal of not having to adjust the code.
 
The hook is that for these tests we want to retain flexibility in the way the code looks at the animation so that it could have 3 clickable segments on one version and potential 4 or 5 segments on the next version, all without updating the code. Is it possible for code to look at markers or triggers to perform an action instead of frames or percentage? Like when you get to a marker stop playback till clicked. That way we could dump in an animation that had 4 or 5 or 10 segments and it would behave correctly without changing the code.
 
Any insights would be appreciated.

**Comment by bodymovin** [comment]
Hi, composition markers are on their way, but they are not ready yet.
