### ISSUE TITLE
Bodymovin - glitches with Drop Shadow

### ISSUE THREAD

**Issue by kazuser** [airbnb/lottie-web#926]
AE 15.0.0.180

**1**. Start a new project
**2**. Create Ellipse;
**3**. Add "Drop Shadow" to Ellipse (aka "Shape Layer 1" in my case)
**4**. Set:
a) Distance = 25,0
b) Softness = 50,0
c) Shadow Only = true (**IMPORTANT!**)
**5**. Export:
 ![1](https://user-images.githubusercontent.com/3335273/37807664-d406c928-2e70-11e8-8024-350ea46ba8e0.png)

**6**. Now change Distance to 150,0 and Shadow Only = false and Export it again:
![2](https://user-images.githubusercontent.com/3335273/37807728-24fc229c-2e71-11e8-87a4-23dc7f978125.png)

Yep - it's clear screen only without any object/shadow :(

Could you fix it please?

**Comment by kazuser** [comment]
Test AE-project in attach:
[Untitled Project.zip](https://github.com/airbnb/lottie-web/files/1839896/Untitled.Project.zip)

**Comment by bodymovin** [comment]
Hi, there seems to be some issues with drop shadow and scaling.
I'll have to look into this but it doesn't look like an easy fix.
