### ISSUE TITLE
Precomp ref ID doesnt always start at 0

### ISSUE THREAD

**Issue by therealsalih** [airbnb/lottie-web#927]
When you export an animation the Precomp ref IDs don't reset each time unless you quit AE. For example: If i export the same JSON twice in a row the ref ID will be comp_0 and then comp_1 on the next. This could cause issues if i'm using dynamic properties and referencing a specific ID

<img width="1244" alt="screen shot 2018-03-22 at 9 21 10 pm" src="https://user-images.githubusercontent.com/5893643/37811369-034103e8-2e17-11e8-8030-563aaf9f9877.png">

**Comment by bodymovin** [comment]
Hi, I'll have this fixed for next build by tomorrow.
But I think this id shouldn't be part of paths used by dynamic properties.
A preComp can have different names on different instances, so it would be best to use the layer's name and not this generic name.

**Comment by Inventsable** [comment]
Hello @bodymovin, is this still open or has it been fixed?

<img width="306" alt="ice_screenshot_20190421-165625" src="https://user-images.githubusercontent.com/37279677/56477091-9ddd4580-6456-11e9-8cd6-4fe5536b2f75.png">

I'm in a situation where I'd like to detect precomps by name or detect which entries inside assets are currently in use (while experimenting with dynamically changing data) to know what is redundantly inflating file size, but I don't see any clear way of doing so.
