### ISSUE TITLE
Jagged Issue

### ISSUE THREAD

**Issue by henriqrossatto** [airbnb/lottie-web#930]
*ADOBE AE CC 2017

I'm developing an animation and the suit look jagged when I exported on lottie. All the elements are shape layers. Trying some corrections, I notice that this would be happening because the angle. Is it correct? Is there any way for me to leave less jagged?

Here a preview https://www.lottiefiles.com/share/mLudoj

This animation will be used on Android and iOS

**Comment by bodymovin** [comment]
Yes, it is probably related to the rotation of the element.
But each browser handles it differently.
And android and ios too.
You should check how it looks there.
