### ISSUE TITLE
Optimization Isuues and gzipping

### ISSUE THREAD

**Issue by ghosper** [airbnb/lottie-web#932]
Hi there! Firstly, you did an amazing job, guys...Kudos!

It happened to play with your bodymovin player and encountered several issues I'd love to fix.

1. How do I serve gzipped json file? I added the mod_gzip_item_include file .(html?|txt|css|js|php|pl|json)$ but it didn't helped. My json file is about 1 MB. Huge!

2. The animations are lagging. You can check them in action at https://249labs.intl-l.com/

Please help.

Chris.

**Comment by ghosper** [comment]
Thanks! It helps. Also...I'm using Wordpress and load the player through the <head> of the page and play the animations through the standard bodymovin.loadAnimation(). The animations are playing fine on the homepage but when I add new ones to other pages, they do not work.

**Comment by bodymovin** [comment]
can you share a link?

**Comment by ghosper** [comment]
Sure! Look I'm using the same:

var teamanim = bodymovin.loadAnimation({
  container: document.getElementById('team'),
  renderer: 'svg',
  loop: true,
  autoplay: true,
  path: 'wp-content/bodymovin/team.json',
  assetsPath: 'wp-content/bodymovin/images/'
})

But the idea is that player works on the homepage which is https://249labs.intl-l.com/ but, don't play on other pages like https://249labs.intl-l.com/open-lantern/

Also, when I load an external .json file everything works, just like:
path: 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/1229210/waypointanim1.json'

I don't understand why the (path: 'wp-content/bodymovin/team.json',) that use an internal .json from Wordpress directory works but, when I add the same path structure to another page (the one I've post above( it doesn't work

**Comment by ghosper** [comment]
UPDATE: @bodymovin looks like the problem was in the "/" path symbol. All I did was adding the"/" right at the start of "wp-content/", just like:

path: '/wp-content/bodymovin/team.json',

But, now...I don't understand why homepage works with "path: 'wp-content/bodymovin/team.json'," (without the backslash)

**Comment by bodymovin** [comment]
when you don't add the initial "/", you' re targeting a relative path.
it works in the root because that path, relative to the root, exists.
but relative to /open-lantern/ doesn't

**Comment by ghosper** [comment]
@bodymovin got that! Thanks
