### ISSUE TITLE
Data.json - Uncaught SyntaxError: Unexpected token : data.json:1

### ISSUE THREAD

**Issue by jamesdanstone** [airbnb/lottie-web#934]
**Dev environment**
Jekyll build
Gulp
Jade
Sass

[relevant branch](https://github.com/jamesdanstone/Design-Code/tree/Skills-lottie-animation)

Chrome Version 65.0.3325.181 (Official Build) (64-bit)

I created a test animation as both a placeholder and to check I could link it all up correctly, the animation exported properly and worked as a demo.

I then tried to add this to my site, but the animation won't show. Debug revealed **Data.json - Uncaught SyntaxError: Unexpected token : data.json:1** 
Which causes the definition error in the functions.js file

![image](https://user-images.githubusercontent.com/35380904/37965026-8c4750d2-31bb-11e8-94fe-eff54de8c480.png)

**Comment by bodymovin** [comment]
Hi, do you have a working version uploaded somewhere I can check?

**Comment by jamesdanstone** [comment]
Yes it's [here](https://jamesdanstone.github.io/Portfolio-Project/#contact)

Please excuse the missing images!

**Comment by bodymovin** [comment]
no problem
you need to pass the path as a string. Change this:
````javascript
var params = {
  container: document.getElementById('lottie'),
  renderer: 'svg',
  loop: true,
  autoplay: true,
  path: assets/js/data.json
};
````
to this:
````javascript
var params = {
  container: document.getElementById('lottie'),
  renderer: 'svg',
  loop: true,
  autoplay: true,
  path: 'assets/js/data.json'
};
````

**Comment by jamesdanstone** [comment]
Ah yeah thank you I've changed that, but I am still getting the error for data.json and now an error on the function? Thanks for your help!

**Uncaught SyntaxError: Unexpected token :**
**Uncaught TypeError: lottie.loadAnimation is not a function**

![image](https://user-images.githubusercontent.com/35380904/37980512-355f590e-31e3-11e8-85df-0160a733fb15.png)

**Comment by bodymovin** [comment]
you're loading functions before lottie, so lottie doesn't exist yet when you're calling it.
Try inverting the order of the js files.

**Comment by jamesdanstone** [comment]
Brilliant I'm all sorted! Thanks very much.
