### ISSUE TITLE
Can bodymovin export png images ?

### ISSUE THREAD

**Issue by RyserCa** [airbnb/lottie-web#937]
Hi,

I have a simple animation with images behind. When I export with bodymovin, I have a .json and a "Images" file. But when I open my HTML, theses images don't appear.

My question is, how do you, if it's possible, link these images in the script ?

(Sorry if my english is bad)

**Comment by bodymovin** [comment]
If the "images" folder is at the same path as the json, they should be loaded automatically.
Do you have a link I can check to see why they don't load?

**Comment by guyenner** [comment]
Im not sure if the issue was solved since Mar 29? I have pngs in the same folder as the json and when I tried to render out it's always halted mid-way through. I know bodymoving works with shape layers but not sure it could work with pngs? 
Thanks!

**Comment by bodymovin** [comment]
@guyenner hi, it should work fine with pngs.
Can you share the animation?
