### ISSUE TITLE
Mask & Drop shadow mismatch

### ISSUE THREAD

**Issue by colorage** [airbnb/lottie-web#938]
**AE CC 2018, Bodymovin 5.1.9**

![image](https://user-images.githubusercontent.com/5142176/38086977-154a7d56-335f-11e8-9af4-c66e77654249.png)

![image](https://user-images.githubusercontent.com/5142176/38086884-bbe50308-335e-11e8-8c7f-41ac4586270f.png)

[test.zip](https://github.com/airbnb/lottie-web/files/1859918/test.zip)

**Comment by bodymovin** [comment]
Subtracting masks generate a mask that doesn't take precedence over the svg filter.
I'll see what I can do.
Meanwhile, you can replicate the same effect by overlapping two ellipses with their path directions in opposite directions, and removing the mask altogether.
You will get much better performance in the process too.
