### ISSUE TITLE
problem bodymovin wordpress

### ISSUE THREAD

**Issue by lollone017** [airbnb/lottie-web#939]
Hi, I have a problem with bodymoving on wordpress. I have followed many discussions but I just can not see the animation, here I put the link of the page:

http://getidea.byethost7.com/wp/bozza-automatica-2/

In fact, instead of displaying the animation with after effect, it shows me only a blank screen.
Below the two js files:

http://getidea.byethost7.com/wp/wp-content/uploads/2018/03/bodymovin.js

File json:
http://getidea.byethost7.com/data.json

If I do not insert it on wordpress but on a normal html page the animation works:

http://getidea.byethost7.com/demo.html

How can I solve?
Thank you

**Comment by lollone017** [comment]
I have deleted the script whit the lottie.js file and i have change the file bodymovin, now the jason file is being loaded:
http://getidea.byethost7.com/wp/wp-content/uploads/2018/03/bodymovin.js

**Comment by bodymovin** [comment]
There seems to be missing an "assets" property on the json file with the images information.
Can you share the .aep?

**Comment by lollone017** [comment]
I upload the file here:
https://wetransfer.com/downloads/559c587e207524b8c6aa8162dd8f682420180401135621/6dbe5fe3410473ec10c86f830b76ae5720180401135621/b6fa13?utm_campaign=WT_email_tracking&utm_content=general&utm_medium=download_button&utm_source=notify_recipient_email

**Comment by bodymovin** [comment]
I don't know how that could be happening.
Maybe wordpress is messing with the file upload.
can you compare them to make sure they are exactly the same?
