### ISSUE TITLE
Time-Reverse and JSON

### ISSUE THREAD

**Issue by ctgstudios** [airbnb/lottie-web#940]
I am attempting to have an animation play and then reverse using time-reverse in After Effects CC 2018.
When exporting using Bodymovin as a JSON file, the animation plays just fine the first way through, but when it hits what should be the layer with time-reverse on it, it goes blank.
Link to the exported file can be found here:
http://www.colorthegrayscale.com/holly.json
Any help with this would be greatly appreciated.

**Comment by ctgstudios** [comment]
Time remapping did the trick. Thanks so much!

I also have a small question, but I'm not sure if it warrants creating a new issue for it. Are strokes on shape layers not supported in JSON? They don't seem to be exporting (I can create a new issue for this if you believe I should).

**Comment by bodymovin** [comment]
if you mean the stroke property of a shape content, yes it should work fine.

**Comment by ctgstudios** [comment]
Yea, that's what I'm looking to do. 
You can take a look at the AEP file here: www.colorthegrayscale.com/tmg-hollyanimation01.aep

**Comment by bodymovin** [comment]
Hi, the Stroke Layer Style is not supported unfortunately.
What is supported is the stroke property of the shape contents.

**Comment by ctgstudios** [comment]
Okay that works, thanks for the help!
