### ISSUE TITLE
Alpha Matte Export Issue

### ISSUE THREAD

**Issue by bryanltrang** [airbnb/lottie-web#943]
I'm trying to create an path animation using an Alpha Matte on two shape layers, the top layer contains the path and is hidden, but when I export to JSON the hidden layer containing the path on the Alpha Matte is still showing.

Here's what the shape looks like with the mask.
<img width="433" alt="screen shot 2018-04-01 at 4 32 22 pm" src="https://user-images.githubusercontent.com/16245945/38178570-79622f74-35ca-11e8-977e-66a6375397bd.png">
<img width="878" alt="screen shot 2018-04-01 at 4 32 17 pm" src="https://user-images.githubusercontent.com/16245945/38178572-7cce54ee-35ca-11e8-86e9-8655134f6acc.png">

Here's what it looks like when I export
<img width="861" alt="screen shot 2018-04-01 at 4 34 45 pm" src="https://user-images.githubusercontent.com/16245945/38178579-a04f257e-35ca-11e8-96b3-4ba1627cde87.png">

Here's the AE file
[loader.zip](https://github.com/airbnb/lottie-web/files/1866798/loader.zip)

**Comment by bodymovin** [comment]
Hi, merge paths are not supported, on your layer:
workclout-icon Outlines there is a Merge Path applied to two paths: Path 1 and Path 2
If you remove the Merge Path and Path 2, it should work fine.
