### ISSUE TITLE
Delay based on previous layer (Is valueAtTime working in bodymovin now?)

### ISSUE THREAD

**Issue by jinwuportfolio** [airbnb/lottie-web#944]
Hi guys,

I'm trying to make a simple animation of cubes moving and each of them has a little delay. So I wrote the following expression to the xPosition attribute:
**thisComp.layer(index-1).transform.xPosition.valueAtTime(time-.05);**

When I exported it as video, it worked perfectly. But when I exported into JSON file and render through bodymovin, the expression didn't work. I tried converting expression into keyframes, it worked well. But I have way too many layer, so it would be great if I can use the expression.

I saw other folks have raised this issue before and I saw the response saying valueAtTime was not supported yet, but that was almost a year ago. So I'm wondering if this is still the case? 

Thanks a lot!!

**Comment by bodymovin** [comment]
Hi, can you share the .aep so I can take a look?
valueAtTime works in certain scenarios and not on others.
There might be another problem with your expression.

**Comment by jinwuportfolio** [comment]
Thanks a lot for the fast response! I have attached the AE file. There are two comps inside, which throw me different errors.

For "experiment", the developer console doesn't throw any error, but the expression doesn't work properly.

For "experiment2", where I used an adjustment layer, the console threw me some error messages (also attached here), so the whole animation didn't show up on the web page.

Let me know if what I said here doesn't make sense. Thank you so much for the rescue!!

[democode.aep.zip](https://github.com/airbnb/lottie-web/files/1871030/democode.aep.zip)

<img width="532" alt="developer_tools_-_http___localhost_9006_" src="https://user-images.githubusercontent.com/11760352/38242887-835d7c00-3768-11e8-921a-0d6da3e13ec2.png">

**Comment by bodymovin** [comment]
Hi, for experiment2, Adjustment Layers aren't exported, if you convert it to a regular layer, it should work fine.
Regarding experint, yes, valueAtTime inside an expression that targets another layer with an expression will use the regular value without evaluating the second expression. It's a limitation for now I need to work on.
