### ISSUE TITLE
Calling playSegment in the middle of an animation plays last frame then next animation

### ISSUE THREAD

**Issue by dsudzy** [airbnb/lottie-web#947]
lottie-web: 5.1.9

When I call the function `anim.playSegments([[1,2], [3, 4]], true);` and I play another segment in the middle of the animation say `anim.playSegments([5,6], true);` it plays the 3,4 frames quickly before playing the next segment 5,6 and looks kind of like a glitch.

**Comment by bodymovin** [comment]
should be fixed now. Reopen if necessary.
