### ISSUE TITLE
Bug exporting out a shape layer with animated mask. 

### ISSUE THREAD

**Issue by annKwilinski** [airbnb/lottie-web#948]
Hello,

I'm working in AE CC.

I have a simple tap gesture composition made from a shape layer and a mask, when exporting out through bodymovin it does not appear in json file. 

Can you take a look at my files and let me know if this is possible with bodymovin? 

I have a link to my aep files, the intended animation mp4, and the exported json and html here:
https://www.dropbox.com/s/ptezbdewbaq2jj8/AE_Files_for_github.zip?dl=0

Any help or explaination is appreciated!!

Thank you.
-Ann

**Comment by bodymovin** [comment]
Hi, subtract masks are not fully supported.
Can you use a shape with two ellipses sharing the same fill and with their path directions opposite between each other?
I think you can get to the same result.

**Comment by annKwilinski** [comment]
Thanks! 
 I will try that out now.  Let you know if I have any more issues.
-Ann

**Comment by annKwilinski** [comment]
@bodymovin this worked perfectly thank you. I need to make that gesture a comp and save it as I'm sure I will need it again.

**Comment by Rayspro** [comment]
i have an issue with this attached .aep file when i export it to JSON , the masking part unable to show on preview how can it be solved?
please solved this issue




[final loader.zip](https://github.com/airbnb/lottie-web/files/3539820/final.loader.zip)

**Comment by bodymovin** [comment]
@Rayspro hi, negative stretching is not supported unfortunately. Can you use time remapping instead?
