### ISSUE TITLE
Unable to get font outline

### ISSUE THREAD

**Issue by LjxTttt** [airbnb/lottie-web#949]
Some simple layers are parsed into text hints and cannot get text outlines

**Comment by bodymovin** [comment]
the exporter should convert the font to shapes if you select glyphs on the settings.
I'd suggest that you let bodymovin export the font because it won't duplicate letters.
But I'm not sure I understand what your original issue is with this.

**Comment by LjxTttt** [comment]
Thank you very much,my issue, you understand it very well

**Comment by WingGao** [comment]
Same issue here and I used only one font

**Comment by bodymovin** [comment]
@WingGao I'm closing this issue. If needed, can you open a new one with more details of your case?
