### ISSUE TITLE
Set destination folder and filenames for multiple exports at once

### ISSUE THREAD

**Issue by ZachSaucier** [airbnb/lottie-web#95]
When exporting multiple animations from the same AE file, it's inconvenient to manually click on each's destination folder, find the directory to save it to, change the name, and save it. 

It would be great to have an ability to set the destination folder for all (or several selected) the same and base the exported file name on the comp name.

**Comment by bodymovin** [comment]
Yes, absolutely, this is something I need to work on and see how to solve.
Thanks for the suggestion.

**Comment by ZachSaucier** [comment]
In terms of how users should select whether or not they want this to happen, I would think after they save using the destination dialog asking, "Would you like all comps to use this same destination folder? <sub>Don't ask me again <input type='checkbox'/></sub>" would be best.

In terms of actually setting the other's, from what I understand viewing [how you set the destination](https://github.com/bodymovin/bodymovin/blob/61d769f63f0d2f18f33ef7298709a56869db0a4b/extension/jsx/compsManager.jsx#L71), it looks like you could just loop through all (or the selected) comps and update the `compData.absoluteURI`, `compData.settings.fsName`, and `compData.destination` for each.
