### ISSUE TITLE
Unable to execute script at line 280. null is not an object

### ISSUE THREAD

**Issue by DustinStrunk** [airbnb/lottie-web#950]
When attempting to render a project with any text I get the error described in the title.

Env:
Windows 10 
AE version 15.1
BM version 5.1.1

Download: https://drive.google.com/open?id=1PDnqYgX5tZspd-HmA9kITmpknc8KyxL-
If you remove the  layer named 0 it should render correctly. 

As you should see I am not using any font or effects or anything. I've already reset the character preferences through AE.

**Comment by bodymovin** [comment]
It's a problem with the latest AE version.
I'll have a fix later tonight.

**Comment by bodymovin** [comment]
fixed

**Comment by KGrastorf** [comment]
Hi. I just had the same problem with version 5.1.1. Is there something else I need to do to fix it?

**Comment by bodymovin** [comment]
Hi, try updating to version 5.1.10 or higher.

**Comment by janschloss** [comment]
Got the same problem, current version.

The project only has some text and keyframes.

**Comment by luoser** [comment]
@janschloss the export worked after i unchecked `Glyphs` in the render settings
