### ISSUE TITLE
Call Bodymovin from AE scripts

### ISSUE THREAD

**Issue by zhengs** [airbnb/lottie-web#951]
Hi,

We are writing an AE script that would iterate through each AE layer and export metadata. For some certain layer types (such as text), we are thinking about directly using Bodymovin to export those layers. Is there a way to call Bodymovin from inside an AE script?

**Comment by bodymovin** [comment]
I haven't really tried it, but bodymovin exposes some methods to the global scope, so you probably can call
`bm_compsManager.renderComposition(compositionData)`
where compositionData is an object with the data bm needs to render.

**Comment by zhengs** [comment]
Hi @bodymovin ,

Thanks for the reply. I was trying to call `renderComposition` and was looking into Bodymovin's source code. I found there's a `older_parser/bodymovin_parser.jsx` under the `build` folder. Is it the old "script" version of Bodymovin? Does it provide similar (or perhaps a subset of) functionalities to the current extension? The source code of the extension is well structured. If I were to start reading the source code, which folder/file would you suggest I begin with?

**Comment by bodymovin** [comment]
that version is really old. It wouldn't be compatible at all with the current renderer unfortunately.
Did you get somewhere calling renderComposition?

**Comment by OlehMysak** [comment]
@zhengs Did it work out?
