### ISSUE TITLE
Animation breaks on Android with meta tag viewport

### ISSUE THREAD

**Issue by Wakko90** [airbnb/lottie-web#952]
Hi there, I' building a site using lottie-web to animate aep animations exportend in JSON.

Everything works fine on iOS and desktop but on Android+Chrome (tablet and mobile) some parts of the animations are not visible.

We found out that removing this meta tag solved the issue:

`<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'  />`

but obviously the site was not well-scaled.

The animations are also scaled with css.

this is what I see on android
https://drive.google.com/file/d/1gSWn65YnASOv9ivG4Bv22-bkTxka-CEg/view?usp=sharing

this is the expected behavior
https://drive.google.com/open?id=1d6dpAlzATgbcfmcVYpj-4NQB2YmU5iHE

here is a link to the site: stage.oneupstud.io/wow10

and this is the aep file
https://drive.google.com/open?id=1Q8x0C9l-9WijwIlhfCdfjDpIVqv3wMmk

thanks for any help

**Comment by Wakko90** [comment]
I'm sorry but i can't create it right now.

Anyway I see the link I wrote was not referred to the right page.

this is the correct one, you can find the animation at the bottom of the page.
stage.oneupstud.io/wow11/philippines.html

sorry for my mistake :)

**Comment by IveSix** [comment]
i gave same issue

**Comment by Wakko90** [comment]
Hi there, I just realized i have the same issue on Edge. 
I read the problem is caused by masks. Maybe is the same issue?

**Comment by bodymovin** [comment]
are you using the base tag?

**Comment by Wakko90** [comment]
No, I'm not using it. Is it necessary?

you can check all the tags in [this page](http://stage.oneupstud.io/wow11/philippines.html)

**Comment by aiyadingya** [comment]
Modify it to (renderer: 'canvas' )

**Comment by natedigrate** [comment]
Has there been any update to this? Same thing is happening to me. I am using inverted alpha masks, which work fine on desktop, work on android without the meta tag, but break when in mobile mode. Switching to canvas renderer also messes up the masks in the animation.

**Comment by enricobuehler** [comment]
Also having the same issue. Still no update on this?

**Comment by bodymovin** [comment]
Hi @enricobuehler can you share a link with the issue?
