### ISSUE TITLE
Gradient change when I export .json files

### ISSUE THREAD

**Issue by henriqrossatto** [airbnb/lottie-web#953]
I'm doing a few animations using and animating gradient color. My problem occurs when I try to export my .json files. Some are reading the gradient effect of other compositions. 

Browser: Google Chrome
After Effects Version: CC 2017

Here some examples. It's starting with orange gradient on comps that doesn't have orange gradient.
https://www.lottiefiles.com/share/jG0tDp
https://www.lottiefiles.com/share/mXuwTL
[Animation_Gradient_Problem.zip](https://github.com/airbnb/lottie-web/files/1881003/Animation_Gradient_Problem.zip)

**Comment by bodymovin** [comment]
Hi, gradient data is read from the .aep file itself.
Make sure to save it before exporting if you edit any gradient.
If the problem still occurs, try renaming the gradient property so they don't conflict.
