### ISSUE TITLE
Can different characters in the bodymovin text have different font sizes 

### ISSUE THREAD

**Issue by sbsomya** [airbnb/lottie-web#955]
Hi had a requirement of like differentc characters with different font-size like 

"My name is SOMYA" 

Here i want SOMYA in 1.5 the font-size so can we update the data for the same or send something

**Comment by bodymovin** [comment]
Hi, unfortunately AE doesn't expose char data. It only works at the textbox level.

**Comment by sbsomya** [comment]
True internally in the code wanted to see if we can modify the xPos and yPos to achieve the same 
Saw each character was a text svg element with some matrix() associated if we can dynamically update it

**Comment by sbsomya** [comment]
Actually the functionality was AE we export in the format we want and change the text and it's font size dynamically for the same AE file
