### ISSUE TITLE
How to use data.json file instead of using animationData in demo.html file? 

### ISSUE THREAD

**Issue by ritsraghani** [airbnb/lottie-web#957]
My HTML file contains : 

```
<body>
<script src="js/lottie.js"></script>

<div id="lottie"></div>

<script>
   
    var params = {
        container: document.getElementById('lottie'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
        // animationData: JSON.parse('js/data.json')
        // animationData: animationData
        path: 'js/data.json'
    };

    var anim;

    anim = lottie.loadAnimation(params);

</script>
</body>

```
and I have 2 files in js folder : lottie.js and data.json. 

But this code is giving me an error:

`lottie.js:5 Failed to load file:///home/auxesis04/Desktop/animation/Web_animation_Trial/js/data.json: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

Please Help

**Comment by AddeNordh** [comment]
Hello @ritsraghani!
Are you loading you HTML file through a web server?
If you are loading it through __file://__ you don't have permission to load a __json__ file.

**Comment by Duckrinium** [comment]
Is there a way to avoid using server?

**Comment by bodymovin** [comment]
you can load the json as a js object and pass the value as `animationData` instead of `path`

**Comment by emilolsson** [comment]
Can you give us an example of how this is done? I have Cors error problems with loading it as an external file through path, so trying to load it as a js object through animationData instead as you suggest above. But no luck. Do I need to reformat the json output to use it as a js object? Thanks
