### ISSUE TITLE
Cannot read property 'v' of undefined

### ISSUE THREAD

**Issue by AddeNordh** [airbnb/lottie-web#958]
![alt](https://image.prntscr.com/image/R8KJ0aGLR3CFtud1H576bQ.png)

I have another bodymoving animation on another place which works just fine and i can't figure out why this one won't work.

The code for both animations looks almost identical

## Animation that works
```js
const animation = bodymovin.loadAnimation({
  container: document.getElementById("loader"),
  renderer: "svg",
  loop: true,
  autoplay: true,
  path: "themes/iplay/assets/data/loader/data.json"
});
```

## Animation that don't work 
```js
const animation = bodymovin.loadAnimation({
  container: document.getElementById("timeline-svg"),
  renderer: "html",
  loop: true,
  autoplay: true, 
  path: "themes/iplay/assets/data/timeline/data.json",
});
```

The problem seems to be on line **11503**
```js
this.mat.rotateX(-mTransf.rx.v).rotateY(-mTransf.ry.v).rotateZ(mTransf.rz.v);
```

From what i could debug myself __(only using `console.log()`,  your code base is to big and complicated for me to debug myself)__ 
I couldn't find a definition for `this.hierarchy[i].finalTransform.mProp.rx`, all the others `.p .s .v` are defined when you __log__ the object but `.rx` is nowhere to be found.
![alt](https://image.prntscr.com/image/cU5X8mKmRmChR5hfg5r9Kg.png)

Does anybody have any idea what's going on?

**Comment by bodymovin** [comment]
hi, can you share the .aep?

**Comment by AddeNordh** [comment]
[timeline.zip](https://github.com/airbnb/lottie-web/files/1895955/timeline.zip)

**Comment by bodymovin** [comment]
Hi, the camera is parented to a 2d null Layer
The player expects that 3d parenting is also a 3d layer.
I'll see if I can fix this on my side, but if you change your Null Layer to 3d, it should work fine.

**Comment by chintu3535** [comment]
Hi, please help me i am also having same error. Thanks

**Comment by bodymovin** [comment]
@chintu3535 can you share the project?

**Comment by chintu3535** [comment]
[sampleanimtion.aep.zip](https://github.com/airbnb/lottie-web/files/3520168/sampleanimtion.aep.zip)

**Comment by chintu3535** [comment]
Please let me know have you got any solution. Thanks

**Comment by bodymovin** [comment]
@chintu3535 Hi, I ofund the issue, it will be fixed on the next deploy. It is related to having separate position properties on the camera.
