### ISSUE TITLE
AE Expression for getting sample pixel color not work

### ISSUE THREAD

**Issue by tonywei92** [airbnb/lottie-web#959]
Windows 10 Latest update 64bit

* **Chrome 65:**
* **After Effects Version: CC 2017**

Im trying to do this tutorial: https://www.youtube.com/watch?v=4OQN2mHQuD0&t=675s

but the control layer expression not work on BodyMovin Render. here is the project files:
[https://drive.google.com/open?id=1ElhV9W2HcojR3qruIcgws7LfCBC_VDB1](url)
please help.

**Comment by bodymovin** [comment]
Hi, unfortunately the sampleImage method is not yet supported by the player

**Comment by tonywei92** [comment]
@bodymovin, any alternative to that? Im just trying make a wave
