### ISSUE TITLE
Text change for percentage counter

### ISSUE THREAD

**Issue by ryanmclaughlin** [airbnb/lottie-web#960]
Hi there, I've got an animation that includes a percentage number that counts from '0%' to '100%' using a simple expression. It doesn't work on the export with the glyphs option on or off, which I didn't expect it to. Is there something I can do manually in AE to get the counter to export properly?

**Comment by ryanmclaughlin** [comment]
Sure, [here's the .aep](https://s3-us-west-2.amazonaws.com/s.cdpn.io/68366/charge.aep). It won't export with glyphs off as it gets hung up on the text.

**Comment by ryanmclaughlin** [comment]
@bodymovin 5.1.1

Mine hangs here: 
![image](https://user-images.githubusercontent.com/451112/38625177-7ee46ab4-3d6f-11e8-801b-b7e87c95b2ba.png)

**Comment by bodymovin** [comment]
if you're on the latest version of AE, you'll need to upgrade to version 5.1.10 of bodymovin.
they did some changes and it broke the text exporter.

**Comment by ryanmclaughlin** [comment]
@bodymovin Great that fixed the render issue, but it's not animating the text (it's supposed to go from 0-100%). It only renders what is currently the frame in AE. Is there something I need to do manually?
