### ISSUE TITLE
Issue we text glyph conversion

### ISSUE THREAD

**Issue by samiam2017** [airbnb/lottie-web#961]
**Tell us about your environment**

MacBook Pro
Mac OS Version 10.13.3

* **After Effects Version:**

Adobe After Effects CC Version 15.1.0(Build 166)

Bodymovin Version 5.0.4

**Comment by samiam2017** [comment]
I'm getting this error message: (unable to execute script at line 280. null is not an object), when I try to render a json with a text layer that is set to convert to glyph. 

I'm not sure if that means that the font is unsupported, or if it's something else.

![screen shot 2018-04-10 at 11 31 54 am](https://user-images.githubusercontent.com/29287850/38588593-99968962-3cdb-11e8-8a3f-7ec393c0dd32.png)

**Comment by bodymovin** [comment]
what version of the extension are you using?

**Comment by samiam2017** [comment]
Bodymovin Version 5.0.4

**Comment by bodymovin** [comment]
^

**Comment by samiam2017** [comment]
yeah let me try that, we had some errors occur with a newer version of the web based lottie library a few months back so we stayed on this version.

**Comment by samiam2017** [comment]
K that fixed it. Thank you!

**Comment by bodymovin** [comment]
can you share a link?
I think browsers don't apply antialiasing to texts with opacity, but I'm not certain about it.

**Comment by samiam2017** [comment]
Hmm only does it when it's scaled up but not at the actual playback size I that I'd want to run it at so not a big deal. 
Thanks again for all your help. This thing has saved my life!!!

**Comment by RhysyG** [comment]
I'm now getting this error.

I've also got the latest updates.
Adobe After Effects 15.1.0 (Build 166)
Bodymovin 5.1.1

Can't export any text without getting:
**Unable to execute script at lie 280. null is not an object.**

**Comment by halbano** [comment]
@RhysyG Did you found any solution to this error? I am struggling on this too.

**Comment by bodymovin** [comment]
@halbano if you updated to the latest version of AE, you need to update the extension too to v.5.1.10 or higher

**Comment by timosina** [comment]
Hi @bodymovin I think I have the same error with text exporting and opening bm_charHelper. 
I use After Effects CC 2018 and just updated bodymovin to the latest version (5.3.3) but didn't help unfortunately. 
As I press OK on After Effects warning the next message that appears is 'Unable to execute script at line 673. undefinesd is not an object'. 

![gh](https://user-images.githubusercontent.com/43249315/46605265-9b8e4c00-cb01-11e8-8e52-856e37b682c8.jpg)

**Comment by bodymovin** [comment]
@timosina some fonts can't be converted to shapes. It might be that or it's a special character that should be skipped.
Can you share the .aep?

**Comment by bodymovin** [comment]
@timosina  the issue is related to using a character that can't be converted to glyphs: _End of Text_  
I'm fixing it on the next build, but if you want, you can change your texts and remove them.  
For example on the layer 'Congratulations Jim! Your mortgagehas been pre-approved. '
Change the character between **mortgage** and **has** with an _Enter_
