### ISSUE TITLE
Not the same JS files shown in tutorials

### ISSUE THREAD

**Issue by seriouslyjunk** [airbnb/lottie-web#962]
All the tutorials for BodyMovin I see show that once an animation is exported, you get a data.js file & when you download the player, you get a Bodymovin.js file.

I get a data file with an "Images" folder. The data file shows as a filetype "After Effects JSON" (so I *guess* it's a JSON file even though it doesn't show the file extension), and the Images folder contains all the images relevant to the exported animation. When I "Get Player" what I get is  Lottie file that I have no idea what to do with. If I double click it or drag the JSON file to it, I get a Javascript Jscript Runtime Error, Code 800A1391. I looked up that error, and all I can find is complicated solutions that I do not understand and don't even know will work with this issue.

I don't understand why I'm not getting the same files as the tutorials show.

I am new to Windows, so please be kind.
Thank you!

**Windows 10 Pro MSI GT73 Titan**
* **After Effects Version CC2017:**

**Comment by seriouslyjunk** [comment]
Hi! Thank you very much for replying!

Unfortunately, I know nothing about web development. My end goal is to create a banner ad for a client. Whether they are going to take the AE file & create what's needed or I have to do it remains to be seen. I didn't know enough about this process to ask at the time. I just started a test today to let them see that I can do the animation (that was the part that was in question). They can't expect me to do coding because we never talked about that, and I don't know how anyway. 

I just got a bit panicked about what I was seeing as my exports. So, if the Images folder are non-vectors (and they are), how will that translate to when this piece ultimately gets turned into an HTML5 banner ad? There are images the client needs to use which are not and, I assume, cannot be vectors.

**Comment by bodymovin** [comment]
you will probably need to provide the json, the js player and the images folder together in a zip file.
In order for you to try it out, you can select to export the Demo.html file on the settings of the extension so you can preview it.

**Comment by seriouslyjunk** [comment]
My AE comp is 728x90. When I do the Demo export, I guess the preview is scaling up the animation because the edges of everything look really rough looks like it has a nasty thin black stroke on them. Is that typical for a demo preview? Do I have to figure out the coding part to get it to play at size?

I can export just a movie file for the client to see the animation, but I wouldn't dare show them the preview looking like that.

**Comment by bodymovin** [comment]
Yes, the demo.html shows the animation full screen.
Since you're using rasterized assets, you should probably create your own html with the correct size.
Regarding the black stroke around images, that's an issue with AE with certain assets with transparency, to fix it, you can replace the files in the images folder with the original ones.
