### ISSUE TITLE
Wrong sentence in demo image

### ISSUE THREAD

**Issue by abejfehr** [airbnb/lottie-web#963]
This is hardly a bug in the library, but it's something that seems wrong (and unintended) so I wanted to point it out:
The text in [this image](https://github.com/airbnb/lottie-web/blob/master/gifs/Example4.gif) displayed in the README.md is (probably) meant to be a pangram but isn't one. 

If it said "jumps" instead of "jumped" then the sentence would contain every letter in the alphabet, but now it's missing an "s".

Sorry if this is meant _strictly_ for code-related bugs and not the demos

**Comment by bodymovin** [comment]
lol good catch!
This animation comes from the Airbnb team, I'm closing the issue because there's no action item currently.
