### ISSUE TITLE
a performance issue in low version android

### ISSUE THREAD

**Issue by StudentWan** [airbnb/lottie-web#965]
**Tell us about your environment**
Android 5.1, or lower

* **Browser and Browser Version:**
Sorry, I don't know...
* **After Effects Version:**
Just some examples from LottieFiles

**What did you do? Please explain the steps you took before you encountered the problem.**
Firstly, thanks for your excellent work!

I tried to use lottie to load some animation on mobile device, it works well with my iphone 6s, but when comes to android 5.1 and lower, it somehow becomes glitche...I tested some kinds of android phone and inspect them with Chrome, some browsers spend too much time on Compositor Raster Worker with painting, some browsers spend too much time scripting, so i can not make sure where the performance issue really happens...

besides, canvas seems more smoothly than svg? but when loading some animation which "draw some words", the canvas version doesn't work properly..

**What did you expect to happen?**
smooth animation on mobile device, android and iphone both

**What actually happened? Please include as much _relevant_ detail as possible.**
here is the demo url:
[demo](http://danielwan.me/demo/lottie/)

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, svg has more features than canvas, but canvas can indeed be more performant in some scenarios.
For your animation, I'd suggest that you try also the "html" renderer, it might be more performant than the other two.
