### ISSUE TITLE
Demo HTML not running

### ISSUE THREAD

**Issue by re-LIFE** [airbnb/lottie-web#966]
**Tell us about your environment**

* **Browser and Browser Version:** 
    **Edge and mozilla**
* **After Effects Version:** 
   **After effect 2018**

**What did you do? Please explain the steps you took before you encountered the problem.**

**What did you expect to happen?**
**I'm success render in bodymovin , but HTML nor running in browser**
**What actually happened? Please include as much _relevant_ detail as possible.**

**Please provide a download link to the After Effects file that demonstrates the problem.**

**Comment by bodymovin** [comment]
Hi, can you provide the file?

**Comment by re-LIFE** [comment]
[file.zip](https://github.com/airbnb/lottie-web/files/1918105/file.zip)

and bodymovin doesnot support for glitch efect for text??

can you give me suggest plugin fot fect text wich support fo bodymovin?

**Comment by bodymovin** [comment]
Hi, I'm not sure what effect you're referring to, but not many AE effects are supported by the plugin

**Comment by re-LIFE** [comment]
Can you suggest me the plugin for text ??

**Comment by re-LIFE** [comment]
I want use it for my splascreen android

**Comment by bodymovin** [comment]
Sorry I can't I, don't know exactly what you're looking for.
I'd suggest that you check the supported features here to see what you can do.
http://airbnb.io/lottie/supported-features.html
