### ISSUE TITLE
enterFrame event trigger count

### ISSUE THREAD

**Issue by hkericb** [airbnb/lottie-web#967]
**Tell us about your environment**
Chrome v65

For an animation with 30 frames, it is expected that the event 'enterFrame' would be triggered 30 times, and for each time the event should return the frame number sequentially.

However, the actual result comes out that the event count would also depend on the frame rate and also sometimes several frames would be skipped.

https://codepen.io/anon/pen/bvygWy

**Comment by bodymovin** [comment]
enterFrame will trigger every time requestAnimationFrame is triggered. 
If it skips frames it's because the time budget for that frame took longer than expected so the next available frame is not consecutive.
console logs are pretty expensive so you won't get an accurate value.
try changing your code to something like this to have a more real case scenario:
````javascript
animation.setSubframe(false);
var frames = [];

animation.addEventListener('DOMLoaded', function() {
    animation.play();
});
animation.addEventListener('complete', function() {
    console.log(frames);
});

let i = 0;

animation.onEnterFrame = function(e) {
  frames.push('yo' +  e.currentTime + ' ' + i++)
};
```

**Comment by hkericb** [comment]
```
1: BMEnterFrameEvent {type: "enterFrame", currentTime: 0, totalTime: 30, direction: 1}
2: BMEnterFrameEvent {type: "enterFrame", currentTime: 0, totalTime: 30, direction: 1}
3: BMEnterFrameEvent {type: "enterFrame", currentTime: 1, totalTime: 30, direction: 1}
4: BMEnterFrameEvent {type: "enterFrame", currentTime: 1, totalTime: 30, direction: 1}
5: BMEnterFrameEvent {type: "enterFrame", currentTime: 2, totalTime: 30, direction: 1}
6: BMEnterFrameEvent {type: "enterFrame", currentTime: 2, totalTime: 30, direction: 1}
7: BMEnterFrameEvent {type: "enterFrame", currentTime: 3, totalTime: 30, direction: 1}
8: BMEnterFrameEvent {type: "enterFrame", currentTime: 3, totalTime: 30, direction: 1}
9: BMEnterFrameEvent {type: "enterFrame", currentTime: 4, totalTime: 30, direction: 1}
10: BMEnterFrameEvent {type: "enterFrame", currentTime: 4, totalTime: 30, direction: 1}
11: BMEnterFrameEvent {type: "enterFrame", currentTime: 5, totalTime: 30, direction: 1}
12: BMEnterFrameEvent {type: "enterFrame", currentTime: 5, totalTime: 30, direction: 1}
13: BMEnterFrameEvent {type: "enterFrame", currentTime: 6, totalTime: 30, direction: 1}
14: BMEnterFrameEvent {type: "enterFrame", currentTime: 6, totalTime: 30, direction: 1}
15: BMEnterFrameEvent {type: "enterFrame", currentTime: 7, totalTime: 30, direction: 1}
16: BMEnterFrameEvent {type: "enterFrame", currentTime: 7, totalTime: 30, direction: 1}
17: BMEnterFrameEvent {type: "enterFrame", currentTime: 8, totalTime: 30, direction: 1}
18: BMEnterFrameEvent {type: "enterFrame", currentTime: 8, totalTime: 30, direction: 1}
19: BMEnterFrameEvent {type: "enterFrame", currentTime: 9, totalTime: 30, direction: 1}
20: BMEnterFrameEvent {type: "enterFrame", currentTime: 9, totalTime: 30, direction: 1}
21: BMEnterFrameEvent {type: "enterFrame", currentTime: 10, totalTime: 30, direction: 1}
22: BMEnterFrameEvent {type: "enterFrame", currentTime: 10, totalTime: 30, direction: 1}
23: BMEnterFrameEvent {type: "enterFrame", currentTime: 11, totalTime: 30, direction: 1}
24: BMEnterFrameEvent {type: "enterFrame", currentTime: 11, totalTime: 30, direction: 1}
25: BMEnterFrameEvent {type: "enterFrame", currentTime: 12, totalTime: 30, direction: 1}
26: BMEnterFrameEvent {type: "enterFrame", currentTime: 12, totalTime: 30, direction: 1}
27: BMEnterFrameEvent {type: "enterFrame", currentTime: 13, totalTime: 30, direction: 1}
28: BMEnterFrameEvent {type: "enterFrame", currentTime: 13, totalTime: 30, direction: 1}
29: BMEnterFrameEvent {type: "enterFrame", currentTime: 14, totalTime: 30, direction: 1}
30: BMEnterFrameEvent {type: "enterFrame", currentTime: 14, totalTime: 30, direction: 1}
31: BMEnterFrameEvent {type: "enterFrame", currentTime: 15, totalTime: 30, direction: 1}
32: BMEnterFrameEvent {type: "enterFrame", currentTime: 15, totalTime: 30, direction: 1}
33: BMEnterFrameEvent {type: "enterFrame", currentTime: 16, totalTime: 30, direction: 1}
34: BMEnterFrameEvent {type: "enterFrame", currentTime: 16, totalTime: 30, direction: 1}
35: BMEnterFrameEvent {type: "enterFrame", currentTime: 17, totalTime: 30, direction: 1}
36: BMEnterFrameEvent {type: "enterFrame", currentTime: 17, totalTime: 30, direction: 1}
37: BMEnterFrameEvent {type: "enterFrame", currentTime: 18, totalTime: 30, direction: 1}
38: BMEnterFrameEvent {type: "enterFrame", currentTime: 18, totalTime: 30, direction: 1}
39: BMEnterFrameEvent {type: "enterFrame", currentTime: 19, totalTime: 30, direction: 1}
40: BMEnterFrameEvent {type: "enterFrame", currentTime: 19, totalTime: 30, direction: 1}
41: BMEnterFrameEvent {type: "enterFrame", currentTime: 20, totalTime: 30, direction: 1}
42: BMEnterFrameEvent {type: "enterFrame", currentTime: 20, totalTime: 30, direction: 1}
43: BMEnterFrameEvent {type: "enterFrame", currentTime: 21, totalTime: 30, direction: 1}
44: BMEnterFrameEvent {type: "enterFrame", currentTime: 21, totalTime: 30, direction: 1}
45: BMEnterFrameEvent {type: "enterFrame", currentTime: 22, totalTime: 30, direction: 1}
46: BMEnterFrameEvent {type: "enterFrame", currentTime: 22, totalTime: 30, direction: 1}
47: BMEnterFrameEvent {type: "enterFrame", currentTime: 23, totalTime: 30, direction: 1}
48: BMEnterFrameEvent {type: "enterFrame", currentTime: 23, totalTime: 30, direction: 1}
49: BMEnterFrameEvent {type: "enterFrame", currentTime: 24, totalTime: 30, direction: 1}
50: BMEnterFrameEvent {type: "enterFrame", currentTime: 24, totalTime: 30, direction: 1}
51: BMEnterFrameEvent {type: "enterFrame", currentTime: 25, totalTime: 30, direction: 1}
52: BMEnterFrameEvent {type: "enterFrame", currentTime: 25, totalTime: 30, direction: 1}
53: BMEnterFrameEvent {type: "enterFrame", currentTime: 26, totalTime: 30, direction: 1}
54: BMEnterFrameEvent {type: "enterFrame", currentTime: 26, totalTime: 30, direction: 1}
55: BMEnterFrameEvent {type: "enterFrame", currentTime: 27, totalTime: 30, direction: 1}
56: BMEnterFrameEvent {type: "enterFrame", currentTime: 27, totalTime: 30, direction: 1}
57: BMEnterFrameEvent {type: "enterFrame", currentTime: 28, totalTime: 30, direction: 1}
58: BMEnterFrameEvent {type: "enterFrame", currentTime: 28, totalTime: 30, direction: 1}
59: BMEnterFrameEvent {type: "enterFrame", currentTime: 29, totalTime: 30, direction: 1}
```

@bodymovin I'm getting this result with your code. Why would a frame being entered twice?

**Comment by bodymovin** [comment]
It fires the event every time it calculates a new time. Since you're probably using setSubframe(false), the frame repeats itself and the event is fired with the same values as the previous one.
It might make sense to skip those frames in this case.
Meanwhile you can skip them on your side by storing the previous frame.

**Comment by hkericb** [comment]
@bodymovin i am using setSubframe(false) because of not getting an integer value of frame number. any solution to this?

`1: BMEnterFrameEvent {type: "enterFrame", currentTime: 0.4999799999999982, totalTime: 30, direction: 1}
2: BMEnterFrameEvent {type: "enterFrame", currentTime: 0.9999600000000032, totalTime: 30, direction: 1}
3: BMEnterFrameEvent {type: "enterFrame", currentTime: 1.4999400000000014, totalTime: 30, direction: 1}
4: BMEnterFrameEvent {type: "enterFrame", currentTime: 1.9999199999999995, totalTime: 30, direction: 1}
5: BMEnterFrameEvent {type: "enterFrame", currentTime: 2.4999000000000047, totalTime: 30, direction: 1}
6: BMEnterFrameEvent {type: "enterFrame", currentTime: 2.9998800000000028, totalTime: 30, direction: 1}
7: BMEnterFrameEvent {type: "enterFrame", currentTime: 3.499860000000001, totalTime: 30, direction: 1}
8: BMEnterFrameEvent {type: "enterFrame", currentTime: 3.999839999999999, totalTime: 30, direction: 1}
9: BMEnterFrameEvent {type: "enterFrame", currentTime: 4.499820000000004, totalTime: 30, direction: 1}
10: BMEnterFrameEvent {type: "enterFrame", currentTime: 4.999799999999995, totalTime: 30, direction: 1}
11: BMEnterFrameEvent {type: "enterFrame", currentTime: 5.49978, totalTime: 30, direction: 1}
12: BMEnterFrameEvent {type: "enterFrame", currentTime: 6.020880000000004, totalTime: 30, direction: 1}
13: BMEnterFrameEvent {type: "enterFrame", currentTime: 6.520860000000002, totalTime: 30, direction: 1}
14: BMEnterFrameEvent {type: "enterFrame", currentTime: 7.02084, totalTime: 30, direction: 1}
15: BMEnterFrameEvent {type: "enterFrame", currentTime: 7.520820000000005, totalTime: 30, direction: 1}
16: BMEnterFrameEvent {type: "enterFrame", currentTime: 8.020799999999996, totalTime: 30, direction: 1}
17: BMEnterFrameEvent {type: "enterFrame", currentTime: 8.52078, totalTime: 30, direction: 1}
18: BMEnterFrameEvent {type: "enterFrame", currentTime: 9.02076, totalTime: 30, direction: 1}
19: BMEnterFrameEvent {type: "enterFrame", currentTime: 9.520739999999998, totalTime: 30, direction: 1}
20: BMEnterFrameEvent {type: "enterFrame", currentTime: 10.020720000000003, totalTime: 30, direction: 1}
21: BMEnterFrameEvent {type: "enterFrame", currentTime: 10.520700000000001, totalTime: 30, direction: 1}
22: BMEnterFrameEvent {type: "enterFrame", currentTime: 11.02068, totalTime: 30, direction: 1}
23: BMEnterFrameEvent {type: "enterFrame", currentTime: 11.52066, totalTime: 30, direction: 1}
24: BMEnterFrameEvent {type: "enterFrame", currentTime: 12.020640000000004, totalTime: 30, direction: 1}
25: BMEnterFrameEvent {type: "enterFrame", currentTime: 12.520620000000003, totalTime: 30, direction: 1}
26: BMEnterFrameEvent {type: "enterFrame", currentTime: 13.020600000000002, totalTime: 30, direction: 1}
27: BMEnterFrameEvent {type: "enterFrame", currentTime: 13.520580000000006, totalTime: 30, direction: 1}
28: BMEnterFrameEvent {type: "enterFrame", currentTime: 14.020559999999998, totalTime: 30, direction: 1}
29: BMEnterFrameEvent {type: "enterFrame", currentTime: 14.520540000000002, totalTime: 30, direction: 1}
30: BMEnterFrameEvent {type: "enterFrame", currentTime: 15.020520000000001, totalTime: 30, direction: 1}
31: BMEnterFrameEvent {type: "enterFrame", currentTime: 15.520500000000006, totalTime: 30, direction: 1}
32: BMEnterFrameEvent {type: "enterFrame", currentTime: 16.020480000000003, totalTime: 30, direction: 1}
33: BMEnterFrameEvent {type: "enterFrame", currentTime: 16.52046, totalTime: 30, direction: 1}
34: BMEnterFrameEvent {type: "enterFrame", currentTime: 17.020440000000004, totalTime: 30, direction: 1}
35: BMEnterFrameEvent {type: "enterFrame", currentTime: 17.520419999999994, totalTime: 30, direction: 1}
36: BMEnterFrameEvent {type: "enterFrame", currentTime: 18.0204, totalTime: 30, direction: 1}
37: BMEnterFrameEvent {type: "enterFrame", currentTime: 18.520379999999996, totalTime: 30, direction: 1}
38: BMEnterFrameEvent {type: "enterFrame", currentTime: 19.020359999999993, totalTime: 30, direction: 1}
39: BMEnterFrameEvent {type: "enterFrame", currentTime: 19.520339999999997, totalTime: 30, direction: 1}
40: BMEnterFrameEvent {type: "enterFrame", currentTime: 20.020319999999995, totalTime: 30, direction: 1}
41: BMEnterFrameEvent {type: "enterFrame", currentTime: 20.52029999999999, totalTime: 30, direction: 1}
42: BMEnterFrameEvent {type: "enterFrame", currentTime: 21.02027999999999, totalTime: 30, direction: 1}
43: BMEnterFrameEvent {type: "enterFrame", currentTime: 21.520259999999993, totalTime: 30, direction: 1}
44: BMEnterFrameEvent {type: "enterFrame", currentTime: 22.02023999999999, totalTime: 30, direction: 1}
45: BMEnterFrameEvent {type: "enterFrame", currentTime: 22.520219999999988, totalTime: 30, direction: 1}
46: BMEnterFrameEvent {type: "enterFrame", currentTime: 23.020199999999992, totalTime: 30, direction: 1}
47: BMEnterFrameEvent {type: "enterFrame", currentTime: 23.52017999999999, totalTime: 30, direction: 1}
48: BMEnterFrameEvent {type: "enterFrame", currentTime: 24.020159999999986, totalTime: 30, direction: 1}
49: BMEnterFrameEvent {type: "enterFrame", currentTime: 24.520139999999984, totalTime: 30, direction: 1}
50: BMEnterFrameEvent {type: "enterFrame", currentTime: 25.020119999999988, totalTime: 30, direction: 1}
51: BMEnterFrameEvent {type: "enterFrame", currentTime: 25.520099999999985, totalTime: 30, direction: 1}
52: BMEnterFrameEvent {type: "enterFrame", currentTime: 26.020079999999982, totalTime: 30, direction: 1}
53: BMEnterFrameEvent {type: "enterFrame", currentTime: 26.52005999999998, totalTime: 30, direction: 1}
54: BMEnterFrameEvent {type: "enterFrame", currentTime: 27.020039999999984, totalTime: 30, direction: 1}
55: BMEnterFrameEvent {type: "enterFrame", currentTime: 27.52001999999998, totalTime: 30, direction: 1}
56: BMEnterFrameEvent {type: "enterFrame", currentTime: 28.01999999999998, totalTime: 30, direction: 1}
57: BMEnterFrameEvent {type: "enterFrame", currentTime: 28.519979999999983, totalTime: 30, direction: 1}
58: BMEnterFrameEvent {type: "enterFrame", currentTime: 29, totalTime: 30, direction: 1}`
