### ISSUE TITLE
Rendering issue when converting ai imported images to 'shapes from vector layers'

### ISSUE THREAD

**Issue by DhiaNHM** [airbnb/lottie-web#969]
Hi all,

Currently we're investigating how we can work with Lottie (bodymovin plugin v5.1.7) to produce simple SVG animations and can't get past a rendering issue (seen in the AE Lottie preview window and replicated when loaded into a webpage).
When we convert the imported Illustrator assets (which were saved as separate ai files) into 'shapes from vector layer' as recommended so that the lottie output is in pure SVG JSON format without the separate PNG assets folder. 

preview screenshots with the original illustrator assets (the rendered output produces separate PNG assets which we want to avoid)
![1-after-effects-insect-test-illustrator-original](https://user-images.githubusercontent.com/8833327/38729394-c3882f1a-3f0a-11e8-965f-5f6e42970330.png)
![4-after-effects-insect-test-illustrator-original](https://user-images.githubusercontent.com/8833327/38729396-c676de7e-3f0a-11e8-8220-c760331509f9.png)

screenshots after converting the assets to 'shapes from vector layers' (note the light switch ai asset renders correctly):
![1-after-effects-insect-test-converted-to-shape-layers](https://user-images.githubusercontent.com/8833327/38729481-0a1aa69c-3f0b-11e8-95c1-0a8fe4e78a16.png)
![3-after-effects-insect-test-converted-to-shape-layers](https://user-images.githubusercontent.com/8833327/38729484-0c78ac0e-3f0b-11e8-9670-325f54515206.png)

Original AEP:
https://dhianhm.github.io/scroller-demos/design-assets/After-Effects-insect-test-illustrator-original.aep

AEP after converting to shapes from vector layers:
https://dhianhm.github.io/scroller-demos/design-assets/After-Effects-insect-test-converted-to-shape-layers.aep

We're new to After Effects so any advice would be great, we've seen one similar issue where the solution was to delete the merge paths in the converted layers which we tried to no success.

**Comment by bodymovin** [comment]
Hi, when you convert .ai layer to AE shapes, if they exceed the .ai artobard, AE adds an extra Path and Merge path to the shape.
Since Lottie doesn't support merge paths, you get those square shapes on top.
To solve this, you have to remove the unnecessary properties in AE.
For example remove in your project:
hand Outlines > Contents > Group > Path 2
hand Outlines > Contents > Group > Merge Paths 1

Same for the other layers and it should work fine.

**Comment by PrimeTimeTran** [comment]
Hi all,
Hey, thanks for your work with Bodymovin. I'm facing a similar issue. I've attempted to do what is suggested in your answer to @DhiaNHM(delete/hide merge paths) but it doesn't seem to work. I'm uncertain as to what "Path 2" would be in my project so I removed all the paths one at a time but still face the same problem. 

I cannot open the file @DhiaNHM provided to mimic your solution as it's a newer version of AE then I have on my machine.

I also seem to have an image that looks fine before I attempt to "Create Shapes from Vector Layer". 

![screen shot 2018-09-17 at 1 51 35 pm](https://user-images.githubusercontent.com/16382165/45607791-44a4d200-ba81-11e8-91ab-c8a815d7483a.jpg)

However, when I create shapes from Vector I end up with this. 
![screen shot 2018-09-17 at 1 52 03 pm](https://user-images.githubusercontent.com/16382165/45607818-7c137e80-ba81-11e8-8e50-c03a5469da93.jpg)

Please advise and thank you in advance~!

**Comment by bodymovin** [comment]
@PrimeTimeTran hi, can you share the missing ai files?

**Comment by PrimeTimeTran** [comment]
Thanks for getting back to me so quickly @bodymovin!
Yep, here you go,
https://drive.google.com/file/d/1fATzfXFUZh9s_Ik9knRMPKbx36CL0vsW/view?usp=sharing

**Comment by PrimeTimeTran** [comment]
Whoops, I actually renamed it to organize my project.

Here's the single light:
https://drive.google.com/file/d/1zhvAgq6dVFRL445rWkU3WZQB5M_ropsG/view?usp=sharing

Here's the background:
https://drive.google.com/file/d/1Le5viSutVHxPZit3ZDPte0CyWh_WMc2l/view?usp=sharing

Here's the AE file before
https://drive.google.com/file/d/11q66iS-dff_5FwgF_WxXSZu_Dfg77T6u/view?usp=sharing

**Comment by bodymovin** [comment]
the missing files seem to be named
stage-background.ai and stage.ai
but those are not the ones you sent
Can you take a look at it?

**Comment by PrimeTimeTran** [comment]
Hi @bodymovin I just added 3 files to this [google drive](https://drive.google.com/drive/folders/1WaHZxMH3TEo4wURmvLtLCYyzcygE9LBJ?usp=sharing).

I removed a lot of the elements I want to have in it to help you guys out. Thanks for your help once again

**Comment by DraftProducts** [comment]
Hi, i think that i've the same issue with my AE project, gifs, are removed from the render and the masks don't work too, can someone help me ? 
I didn't understood what i had to do in my AE composition with the merge paths...
