### ISSUE TITLE
Circle not smooth when resized to small

### ISSUE THREAD

**Issue by creephanger** [airbnb/lottie-web#972]
**used both react-lottie wrapper, react-bodymovin wrapper**

* **Chrome 65.0**
* **After Effects CC 2018**

**Hi I love lottie-web, I think it is super amazing, I've noticed that the circle being rendered is not smooth when resized. I tried resizing the image itself to 100px but still the same when image is set to 100px by 100px, I noticed that when the image is bigger it looks very crisp and smooth for the circle but when it is smaller it appears to have rugged edges. Just hoping to find out why or if I am doing something wrong. Thank you and Keep it up.**

[zipped.zip](https://github.com/airbnb/lottie-web/files/1915086/zipped.zip)

**Comment by bodymovin** [comment]
Hi, I see it fine here. Can you send a screenshot of how it looks on your computer?

**Comment by creephanger** [comment]
![differencecircle](https://user-images.githubusercontent.com/25316136/38908887-d4973e7a-42f4-11e8-90ef-bc76bbcefbef.png)

**Comment by bodymovin** [comment]
Hi, yes that's how browsers handle non rounded pixels.
If you try it in different browsers you will probably get slightly different results.
You can try resizing your animation container in the web version and see if it works better on certain resolutions.

**Comment by creephanger** [comment]
Oh I see, thank you!!! Keep it up!! :)
