### ISSUE TITLE
How to loop playSegments?

### ISSUE THREAD

**Issue by thecosss** [airbnb/lottie-web#973]
It's not a bug, I'm just asking for help about playSegments. I have exported all the animation in json, but i need to loop the first 14 frames before a user clicks on a button. I need to loop from 1 to 14, and then back to 1. How can i do that? When i call `playSegments([[1,14],[14,1]], true)` with loop: true, it plays 1-14, 14-1 and than snaps to 1 frame after 14 in a loop.

**Comment by bodymovin** [comment]
Hi, can you share a link with the implementation?

**Comment by Alfonsaurus** [comment]
Hi! I'm using this and it works for me ;)


```
anim.addEventListener('DOMLoaded', function () { 
    anim.addEventListener('enterFrame', repeat);
    anim.play();

    function repeat() {
        if (anim.currentRawFrame > frameToStop) {
            anim.addEventListener('enterFrame', repeat);
            anim.goToAndPlay(0,true);
        }
    }
}

```
Hope it helps, i'm still learning js and lottie :P

**Comment by Air-Sidney** [comment]
My example
https://github.com/airbnb/lottie-web/issues/581#issuecomment-763554735
