### ISSUE TITLE
Can't Render Properly on Export

### ISSUE THREAD

**Issue by strategicmedia** [airbnb/lottie-web#974]
So, I'm pretty new to After Effects and this issue very well may be something that can't be controlled.

Environment: I'm using After Effects CC and had to convert the original .aep from a CS5 Version. I've attached a ZIP holding both files. [aep files.zip](https://github.com/airbnb/lottie-web/files/1921470/aep.files.zip)

Browser and Browser Version: Chrome Version 65.0.3325.181 (Official Build) (64-bit)
After Effects Version: After Effects CC 15.1.0 (Build 166)

What I Did: I opened the Comp for the shopping cart icon (Path: [ICONS]>Shopping Cart). The original icon only animated in, but not out, so I copied the 4 existing layers and made them into Time Reverse layers, timed everything, etc. Then I tried to Export to Bodymovin and I made sure to include the Control Comp (Path: CONTROL).

What I Expected: For the animation to transition in, then out, with a small pause in between.

What Actually Happened: 
The exit animation that I set up doesn't appear to happen at all, the beginning animation works okay, but then it just disappears where my copied layers were supposed to take effect. Also, the shapes themselves don't seem to be rendering the way they're supposed to. Here's a comparison screenshot. The one on the right (with the highlight) is the way I'd like it to be rendered.
![comparison](https://user-images.githubusercontent.com/24843744/38895714-c49d082e-425e-11e8-9efc-9a41477a0df7.jpg)

I attached a ZIP above of my After Effects files, and here is the link for the Lottie render as well: https://www.lottiefiles.com/share/W0sKnx

EDIT: Not sure if this helps, but here's the link to where this file/icon set was purchased: https://videohive.net/item/110-animated-line-icons-set/12003002

**Comment by bodymovin** [comment]
Hi, there are two things that the animation is using that are not supported by the player.
- stretching layer time with negative values (Time Reverse layers). You can solve this by enabling time remap on the layer and adding two keyframes.
- Offset paths. This is not supported by the player, and I don't know exactly why you need it for this animation, but perhaps you can replicate the same animation without it.
