### ISSUE TITLE
Gradient issue with animations in Safari with website built on angular 

### ISSUE THREAD

**Issue by phantomboogie** [airbnb/lottie-web#975]
I'm running into an issue where the gradients in my animations are turning into black. 

My current page is also running on an older version of the script - bodymovin 4.13.0. Maybe this might be the issue? 

I ran this version on chrome and the gradients rendered fine which is why I'm guessing it might be something else. I read in a few other posts that the combination of angular 1.x and safari can create visual or playback issues. Any ideas on working around this? 

Here's a screenshot of what I'm getting
<img width="322" alt="screenshot 2018-04-17 16 10 06" src="https://user-images.githubusercontent.com/15187147/38904129-73543038-425d-11e8-8dff-3f488c2dda85.png">

Thanks!

**Comment by bodymovin** [comment]
Hi, can you share a link with the issue?

**Comment by yqset** [comment]
checkout https://account.microsoft.com/ and sign in with any personal Microsoft account, should be able to see it once you signed in on the home page

**Comment by yqset** [comment]
Will give it a shot and report back, thanks!
