### ISSUE TITLE
Play the same animation in multiple containers

### ISSUE THREAD

**Issue by philipstampe** [airbnb/lottie-web#977]
Is it possible to have one animation, that plays it in several different containers on the same page? 
and in case, it's possible how is it done? or do I need to create serval instances of the same animation in order to achieve this?

**Comment by bodymovin** [comment]
Yes, you can load the animation data multiple times in different instances.

**Comment by jamslevy** [comment]
@bodymovin is there any recommendations to improve performance, for example if the animation is repeated more than a few times in a list view?

**Comment by bodymovin** [comment]
@jamslevy If they're all playing synchronously and you can use the canvas renderer, you might want to have a single render and copy the canvas on the other instances.
Same thing for the innerHTML svg, but it might get a little more complicated.
You might also explore caching frames of an off screen version of the animation and reusing them on the different instances.
If not, I'm not sure there is a solution for this.

**Comment by imanyari** [comment]
how it's possible to load animation once (to save memory and process) and use it in different containers & control each container to play on mouse over?
I want to use it as hover effect

**Comment by bodymovin** [comment]
@imanyari hi, not sure there is an easy way to do this.
If you can use the canvas renderer, you could create multiple canvas elements in multiple places and draw the animation on each of those instances.
Then you can update the canvas instance you need by drawing the canvas context on that specific one.
