### ISSUE TITLE
Method updateDocumentData (explain)

### ISSUE THREAD

**Issue by igor-nikolic** [airbnb/lottie-web#978]
Hi!
Can someone explain how can I find all text in JSON data that can be updated on the animation and path to them? Also I don't understand the second argument of a method **updateDocumentData**.

**Comment by bodymovin** [comment]
Hi, for now you will have to traverse the animation instance to find the layer that has the text data.
If you have an animation I can help you find it.

**Comment by igor-nikolic** [comment]
https://plnkr.co/edit/fFQvwgphcd6bxkYBFLJ9?p=info

**Comment by bodymovin** [comment]
Hi, you're using and old version of the player.
Can you update the plunkr with the latest one?

**Comment by igor-nikolic** [comment]
Hi, I have added lottie.js player and the graphic broke a bit, but it can display somehow. When I add a bodymovin.js player(V 4.13.) from cdnjs the animation won't start. It says "t.path.substr is not a function".
https://plnkr.co/edit/JagMutHFyRTT0K8CC369

**Comment by bodymovin** [comment]
Can you export the animation again with a newer extension?

**Comment by igor-nikolic** [comment]
Hi,
Sorry I can't export it cause I don't have Adobe AE. I got the animation file from a designer. I just needed to look at the logic (traversing the animation instance to find the layer that has the text data) as you said.
