### ISSUE TITLE
Problem with masks in After Effects

### ISSUE THREAD

**Issue by oleglabunsky** [airbnb/lottie-web#979]
Hi!
I have a problem with exporting animations with masks to Bodymovin.
I used 2 options: Alpha Matte  and simple Mask shape — and none of it works. 
Preview in aftereffects looks good, but when iOS developer open json, it all breaks all masks.
Maybe I have to make some tricky actions with masks?

After Effects file attached.
[tasks_03.zip](https://github.com/airbnb/lottie-web/files/1927856/tasks_03.zip)

**Comment by Aksirob** [comment]
Remove **Merge Paths** in Group 2 of bell_01Outlines and it will work
![1](https://user-images.githubusercontent.com/24473562/39114084-70d906de-46e6-11e8-87e5-ff356fb84c38.jpg)

**Comment by oleglabunsky** [comment]
Ok, thanks for advice! It really works, and also one thing — you don`t need to use inverted mask. Only non-inverted. So untick the checkbox "Inverted".
