### ISSUE TITLE
Lottie AE JSON file not rendering/playing on web viewer tool

### ISSUE THREAD

**Issue by Jvalal** [airbnb/lottie-web#980]
Tell us about your environment
MAC - High Sierra
2.9 . 16 GB 2133 MHz LPDDR3

Browser and Browser Version:
Chrome - 16 GB 2133 MHz LPDDR3

After Effects Version:
15.0.0 build 180

What did you do? Please explain the steps you took before you encountered the problem.
I create a simple countdown animation in AE and export/render via body movin.
output is 11kb

What did you expect to happen?
I expect to be able to drag this to the website "view file" page and see my file.

What actually happened? Please include as much relevant detail as possible.
nothing happens.

Please provide a download link to the After Effects file that demonstrates the problem. . Attached
[timer.json.zip](https://github.com/airbnb/lottie-web/files/1930008/timer.json.zip)
[Lottie.zip](https://github.com/airbnb/lottie-web/files/1930009/Lottie.zip)

**Comment by bodymovin** [comment]
The LottieFiles player is outdated, but I've tried the animation and it runs with a newer player.

**Comment by Jvalal** [comment]
How would I test this? @bodymovin

**Comment by bodymovin** [comment]
On the composition settings in the bodymovin AE panel, you can select to export the demo.html file to quickly test it.

**Comment by sabartooth11** [comment]
im also encountering same issue
[data.json.zip](https://github.com/airbnb/lottie-web/files/2965049/data.json.zip)
[Wave.aep.zip](https://github.com/airbnb/lottie-web/files/2965050/Wave.aep.zip)

**Comment by bodymovin** [comment]
@sabartooth11 unfortunately the wave warp effect is not supported. Not many rasterized effects are supported by the players.
