### ISSUE TITLE
Render with bodymovin - no animation

### ISSUE THREAD

**Issue by ArnoHK** [airbnb/lottie-web#981]
**Tell us about your environment**
- MacOS High Sierra 10.13.1
- Bodymovin is the last version available.

* **Browser and Browser Version:**
* **After Effects Version:**
15.1.0 (build 166)
**What did you do? Please explain the steps you took before you encountered the problem.**
Select Render. Try preview on the Bodymovin windows
Try to preview as well on Lottiefile - display "?"

**Please provide a download link to the After Effects file that demonstrates the problem.**
[Animated Button.aep 2.zip](https://github.com/airbnb/lottie-web/files/1930384/Animated.Button.aep.2.zip)

**Comment by ArnoHK** [comment]
Thanks  !! It works

**Comment by ArnoHK** [comment]
Actually I can see it on the Bodymovin Preview windows. But when I try to upload to LottiesFiles, it displays a "blue ?" rotation... 
Do you thin you could help again ? 

I have attached the json file. 
![screen shot 2018-04-21 at 21 59 37](https://user-images.githubusercontent.com/38546745/39084957-51df4fd2-45af-11e8-96da-6885bcae2396.png)
![screen shot 2018-04-21 at 21 59 41](https://user-images.githubusercontent.com/38546745/39084958-5215693c-45af-11e8-844c-09f83b9b7d09.png)
![screen shot 2018-04-21 at 21 56 12](https://user-images.githubusercontent.com/38546745/39084965-5e2149da-45af-11e8-8b03-0f329b889d5d.png)

[button.json.zip](https://github.com/airbnb/lottie-web/files/1934593/button.json.zip)

**Comment by bodymovin** [comment]
It doesn't find the assets exported in the images folder with the json file.
I think lottieFiles doesn't support this type of animation.
