### ISSUE TITLE
TypeError: script.loadAnimation is not a function

### ISSUE THREAD

**Issue by Venutoloon** [airbnb/lottie-web#982]
Hi!

I uploaded this simple animated logo to WordPress from bodymovin plugin. And it is not showing anything in there. I did add an id to the div tag. I also followed the instruction by allowing an upload of .json and .js files. I did enqueue scripts from functions.php. I am just getting these errors. 

"TypeError: script.loadAnimation is not a function"
"TypeError: this.animationItem.wrapper is undefined"

So I am not sure what they actually mean. It might be a problem with jquery or something wrong with lottis.js functions that are not found. I would be really appreciated if you can help me with that.

So here's what i did add to functions.php:

	wp_deregister_script( 'jquery' );
	wp_register_script( 'jquery', "https://code.jquery.com/jquery-3.1.1.min.js", array(), '3.1.1' );
	//wp_enqueue_script( 'jquery' );
	
	wp_enqueue_script( 'lottie', 'http://lavaacai.com/wp-content/uploads/2018/04/lottie.js', array( 'jquery' ) );
	wp_enqueue_script( 'runlogo', 'http://lavaacai.com/wp-content/uploads/2018/04/runlogo.js', array(), 1.1 );

And this javascript to run logo with .json file:
**$(document).ready(function(){
	var animation = {
		container: document.getElementById('animatedLogo'),
		renderer: 'svg',
		loop: true,
		autoplay: true,
		path: '/wp-content/uploads/2018/04/logo.json',
    assetsPath: '/wp-content/uploads/'
	};
	var anim = lottie.loadAnimation(animation);
});**

I tried to change the url to full url to fix it, but none works. -_-.

Looking forward to hear from your advice and thank you for your time

**Comment by bodymovin** [comment]
Hi, can you share the link so I can check what might be going on?

**Comment by Venutoloon** [comment]
Oh, yeah sure. here's the http://lavaacai.com. Actually, that url is also found on functions.php. haha, everyone always have a long day tho.

**Comment by bodymovin** [comment]
The first thing I see is that you're calling
`script.loadAnimation`
instead of
`lottie.loadAnimation`
once you have that solved, I can keep checking what else might be going on if there is something else

**Comment by Venutoloon** [comment]
Interesting. You are right. Also, I knew that I was right whole time. It might be the cache. Lemma clean the cache. I'll let you know

**Comment by Venutoloon** [comment]
Ok, I realized I left my old script in page builder's javascript module. haha - my apologize. I deleted it anyway then we are at this last error now. It might be an issue with parameters or you have a better idea?
![image](https://user-images.githubusercontent.com/18520573/39063867-5f94cfbe-449a-11e8-9437-7bc7d91ef3e2.png)

**Comment by Venutoloon** [comment]
I updated runlogo.js a bit better since that error shows the variable is undefined or there might be one little thing I'm missing. And I'm still having the same error.
**var animation = lottie.loadAnimation({
		wrapper: document.getElementById('animatedLogo'),
		renderer: 'svg',
		loop: true,
		autoplay: true,
		path: '/wp-content/uploads/2018/04/logo.json',
    assetsPath: '/wp-content/uploads/'
	});**

**Comment by Venutoloon** [comment]
Ok, I believe that it couldn't find the container element. Pathing to home page's div tag's ID might be tricky on Wordpress platform. Do you have advice for writing the pathing within Wordpress APIs?

**Comment by Venutoloon** [comment]
Had to delete some comments cuz I was fixing ongoing and came to this final problem so far.

Ok, here's what i found is the problem is the animationItem couldn't find .json file even so if the path is correct in runlogo.js file. mhmm...
Here's my latest runlogo.js:
**$(document).ready(function(){
	var data = {
		container: document.getElementById('animatedLogo'),
		renderer: 'svg',
		loop: true,
		autoplay: true,
		path: "http://lavaacai.com/wp-content/uploads/2018/04/logo.json"
	}
	var anim = lottie.loadAnimation(data);
});**

**Comment by bodymovin** [comment]
`document.getElementById('animatedLogo')`
is returning null. Is it possible that the element is missing?
