### ISSUE TITLE
Creating .JSON without Images Folder +/- Linking to External Images

### ISSUE THREAD

**Issue by ParkerSch** [airbnb/lottie-web#985]
Bodymovin -- 

I'm working with a cool application called Proto.io to build out a prototype for a new mobile application.  They support animations through your Bodymovin AE extension.  https://blog.proto.io/lets-get-bodymovin/

I've created a couple animations in After Effects, and used the Bodymovin extension to successfully export them for use with Proto.io.  This article was particularly helpful to get my existing designs from Adobe Illustrator into Bodymovin, using the Create Shapes from Vector Layer function such that I didn't have to deal with the "Images" folder.  https://github.com/airbnb/lottie-web/issues/589

While all my vector animations are working great, I'm now trying to animate an "actual" image (.PNG) for use in the prototype, and having trouble figuring out how to do so in a way that doesn't use the "images" subfolder.  (I'm creating a mock "camera" screen and using AE to represent the effect)

I saw a couple support articles where one can change the path of the image.  My problem is that in Proto.io it only allows you to add the "core" JSON file that the Bodymovin extension exports.  You can't add any code around it, only the base JSON file itself.

I created a really simple animation for testing purposes and opened the JSON:

{"v":"5.1.11","fr":60,"ip":0,"op":123,"w":600,"h":900,"nm":"receiptFocusing","ddd":0,"assets":[{"id":"image_0","w":2448,"h":3264,"u":"images/","p":"img_0.png"}],"layers":[{"ddd":0,"ind":1,"ty":2,"nm":"IMG_4116.JPG","cl":"JPG","refId":"image_0","sr":1,"ks":{"o":{"a":0,"k":100,"ix":11},"r":{"a":0,"k":0,"ix":10},"p":{"a":0,"k":[300,450,0],"ix":2},"a":{"a":0,"k":[1224,1632,0],"ix":1},"s":{"a":1,"k":[{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":0,"s":[24,24,100],"e":[35,35,100]},{"i":{"x":[0.833,0.833,0.833],"y":[0.833,0.833,0.833]},"o":{"x":[0.167,0.167,0.167],"y":[0.167,0.167,0.167]},"n":["0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167","0p833_0p833_0p167_0p167"],"t":35,"s":[35,35,100],"e":[24,24,100]},{"t":76}],"ix":6}},"ao":0,"ip":0,"op":300,"st":0,"bm":0}],"markers":[]}

I was then looking at the JSON (above) to see if there was a way I could change the core JSON to reference a file Proto.io was storing in AWS.  //*Edited, proto.io link expires if not logged in* For example, I uploaded the same image I used in my AE composition and located the path that the Proto.io stores it in. // Here is just a random URL with an image picture in it for the same effect: http://sunnymoney.weebly.com/uploads/1/9/6/4/19645963/veggie-grocery-receipt_orig.jpeg

Is this possible, editing the core JSON statement above such that it will reference the sunnymoney.weebly.com path?  If so, are you able to assist using the example path above?  I tried substituting it in a few places in the JSON statement without much luck.

Many thanks!

**Comment by bodymovin** [comment]
Hi, you can use the assetsPath parameter that you pass when you call loadAnimation
https://github.com/airbnb/lottie-web/wiki/loadAnimation-options#assetspath
together with editing the image name in the json that is in the assets array

**Comment by ParkerSch** [comment]
Bodymovin - 

Thanks.  Feeling like a noob, but not sure how to add the assetspath parameter to the JSON statement above?

Also to clarify, Proto.io doesn't allow for one to write additional code outside of the main .JSON file. 
So anything I add would have to be in the core JSON statement above.

Actually, thinking this might be easier -- would it be possible to see an example using the short JSON statement I provided above, and the URL I provided above?

Many thanks!

**Comment by bodymovin** [comment]
I don't think you're going to be able to do it, then.
Unless you specify an assetsPath, the player looks for all images relative to the json path.

**Comment by ParkerSch** [comment]
Bodymovin,

Ok, thanks.  I ended up tricking it a bit by exporting MOV from AE, then converting it to a .GIF, and timing hide/show effects in Proto.io.  Not ideal, but it works.

Appreciate your time and the bodymovin extension works perfectly for vectors with Proto.io! :-D

**Comment by aakey7** [comment]
@bodymovin is it possible to load some assets from a local images folder, but then also able to load one from an online resource? I am trying to use contentful to hold some of my images which I'm hoping to change dynamically. If its not possible to have files from seperate locations, how can i link to assets online?
