### ISSUE TITLE
Is Layer Control supported?

### ISSUE THREAD

**Issue by aenfr** [airbnb/lottie-web#987]
I'm using Layer Control to control parenting through some expressions and a blank page is rendered.

**Comment by bodymovin** [comment]
hi, what do you mean by Layer Control?
can you share the .aep?

**Comment by aenfr** [comment]
By Layer Control I mean a type of Expression Control that is available in AE. Here's the project https://drive.google.com/file/d/1wtUYAAjvIcDGlXeDWwpHjulmb5zj3zWg/view?usp=sharing

**Comment by aenfr** [comment]
Thanks in advance Hernan!

**Comment by bodymovin** [comment]
This should be fixed on the latest version 5.1.13
