### ISSUE TITLE
Animating SVG get exported as PNG

### ISSUE THREAD

**Issue by parredondov** [airbnb/lottie-web#989]
When animating an .ai, all elements in the animation get exported as single PNG files. I get why that is done but if you export as svg the animation still works and is also resizable 

![capture](https://user-images.githubusercontent.com/12090580/39210912-bc178154-47cf-11e8-8adf-b23c1da92aa7.JPG)

I couldn't find an option to export assets as svg is there way to do this with the plugin instead of manually doing it with every animation?

**Comment by parredondov** [comment]
yes, after that the export is still as png

Main .ai file

![image](https://user-images.githubusercontent.com/12090580/39212715-2863daf6-47d5-11e8-91b1-e85ee81897af.png)
 
Timeline

![image](https://user-images.githubusercontent.com/12090580/39212756-425faad4-47d5-11e8-8e9e-b6cf48a8ca6f.png)

**Comment by bodymovin** [comment]
can you share the .aep?

**Comment by parredondov** [comment]
I apologize, converting to shapes was the solution, i was exporting to the same destination

**Comment by herrmanneffe** [comment]
Hi, maybe for further implementation it whoud be useful to export assets as .svg, directly from the plugin.
From a workflow point of view, if I work with many animated elements I prefer to work with .ai layers inside Aftereffects. That gives me the possibility to make changes to the .ai file while AE automatically updatesthe composition. This is not possible if I have converted to shapes the layer. 
Moreover I if you have all your assets in a folder, instead having inline svg (convert to shapes option), you can easily update some .svg by overwriting them. 
You can already do all of this exporting .png or .jpg, but of course you dont get the vector quality. Which is a cool part :)

**Comment by bodymovin** [comment]
@herrmanneffe Unfortunately, I can't convert .ai layers to svgs from the plugin inside AE.
But after export, you could replace pngs with svgs and eventually edit the json file with the paths

**Comment by herrmanneffe** [comment]
I understad, you can only export raster images from AE...  I’ll do as you say
