### ISSUE TITLE
Cant trigger animations on scroll

### ISSUE THREAD

**Issue by enricobuehler** [airbnb/lottie-web#991]
Hello, im currently building a website using fullpage.js with animations using lottie. Fullpage.js has a callback when switching the slide/page, but i just cant figure out how to combine this with the lottie anim.play();

It works fine triggering CSS animations, but if i put in anim.play nothing happens.

Heres the Code how my CSS animations are triggered:

`
$(document).ready(function($) {
    
    var params = {
        container: document.getElementById('k3an'),
        renderer: 'svg',
        loop: true,
        autoplay: true,
		path: 'k3an.json',
    };

    anim = lottie.loadAnimation(params);

              var $isAnimatedSecond = $('.zweite .is-animated'),
      $isAnimatedSecondSingle = $('.zweite .is-animated__single'),
      $isAnimatedSecondSingle2 = $('.zweite .is-animated__single2'),
      $isAnimatedThird = $('.dritte .is-animated'),
      $isAnimatedThirdSingle = $('.dritte .is-animated__single'),
      $isAnimatedFourth = $('.vierte .is-animated'),
      $isAnimatedFourthSingle = $('.vierte .is-animated__single'),
      $isAnimatedFifth = $('.fuenfte .is-animated'),
      $isAnimatedFifthSingle = $('.fuenfte .is-animated__single'),
      $isAnimatedSixth = $('.sechste .is-animated'),
      $isAnimatedSixthSingle = $('.sechste .is-animated__single'),
      $isAnimatedSixthSingle2 = $('.sechste .is-animated__single2'),
      $isAnimatedSeventh = $('.siebte .is-animated'),
      $isAnimatedSeventhSingle = $('.siebte .is-animated__single');
            
			$('#fullpage').fullpage({
				sectionsColor: ['white', '#174180', 'white','#174180', 'white', '#174180', 'white','#174180', 'white'],
				anchors: ['startseite','pers_vermittler','team','konzept','rechner','mod_portfolio','sicherheit','absatz'],
                onLeave: function(index, nextIndex, direction) {
                    
    if( index == 1 && nextIndex == 2 ) { 
        $isAnimatedSecond.addClass('animated zoomIn'); 
        $isAnimatedSecond.eq(1).css('animation-delay', '.3s');
        $isAnimatedSecondSingle.addClass('animated fadeInRight').css('animation-delay', '.7s');
        $isAnimatedSecondSingle2.addClass('animated bounceIn').css('animation-delay', '1.3s');
      }

      else if( index == 2 && direction == 'down' )  { 
        $isAnimatedThird.addClass('animated zoomIn'); 
        $isAnimatedThird.eq(0).css('animation-delay', '.3s');
        $isAnimatedThird.eq(1).css('animation-delay', '.6s');
        $isAnimatedThird.eq(2).css('animation-delay', '.9s');
        $isAnimatedThird.eq(3).css('animation-delay', '1.2s');
        $isAnimatedThird.eq(4).css('animation-delay', '1.5s');
        $isAnimatedThirdSingle.addClass('animated rollIn').css('animation-delay', '1.7s');
      } }

  });
        });
`

My animations work if i set autoplay to true and loop.

I've searched everywhere and didnt find an answer, and im also very new to js, so sorry if this is a stupid question.

**Comment by bodymovin** [comment]
Hi, can you share a link to try to reproduce the issue?
