### ISSUE TITLE
Ok on HTML - Don't move on IOS

### ISSUE THREAD

**Issue by ArnoHK** [airbnb/lottie-web#994]
Hi, 
I have done a animated logo which works on HTML (on Lotties preview web site) but doesn't move on IOS Lotiies preview APP's

https://www.lottiefiles.com/1825-whitecircles

Any idea ? 

Thanks again for your help !! 

Arnault

**Tell us about your environment**

* **After Effects Version:**
15.1.0 (build 166)

[Rond White 2704.json.zip](https://github.com/airbnb/lottie-web/files/1954365/Rond.White.2704.json.zip)

**Comment by bodymovin** [comment]
Hi, can you post this in the lottie-ios github repo?
https://github.com/airbnb/lottie-ios

**Comment by ArnoHK** [comment]
The command time*360 is not supported. I have changed, it works now.
