### ISSUE TITLE
gotoAndPlay to layer/composition marker

### ISSUE THREAD

**Issue by subpublic** [airbnb/lottie-web#995]
Hi!

It would be really useful to be able to call some kind of `animation.gotoAndPlay('state-open')` based on timeline markers.
I haven't found any such support, or have I just not found it? 

I'm thinking of using XMP data to match markers and keyframes, but it would be awesome if Bodymovin could include/support that in the export.

**Comment by bodymovin** [comment]
composition markers are on the pipeline, but not ready yet.

**Comment by subpublic** [comment]
Ok great, I'll keep an eye out for that then!

**Comment by Mudassir-23** [comment]
> composition markers are on the pipeline, but not ready yet.
@bodymovin , at the moment do we have support for composition markers ?

**Comment by bodymovin** [comment]
@Mudassir-23 not yet

**Comment by shirley737** [comment]
Is the play by marker method ready yet? Thanks! 

Also, is there a function that I can play by progress? So I can define a segment by two percentage numbers and play the segment?

**Comment by delasierra** [comment]
Is there any update on navigating to markers in the animation timeline?
Cheers!

**Comment by BrainCrumbz** [comment]
@delasierra and future comers: please see https://github.com/airbnb/lottie-web/wiki/Markers
