### ISSUE TITLE
Animation is overlapping the sticky navigation

### ISSUE THREAD

**Issue by creativedesignseurope** [airbnb/lottie-web#996]
Browser: Chrome
AE 17

Hi,
I created a website with sticky navigation and the issue is that the animation is overlapping the sticky navigation on scroll. I tried to fix it with _position_ property on the animation div container, but the result is always the same - the animation is showed on top of the sticky navigation and the div container is moving under the sticky navigation like it should . Here is the screenshot

The animation works fine, exept IE but I hope to fix this one first. Thanx for the help and I love this plug-in.

![lottie_overlap](https://user-images.githubusercontent.com/34140313/39396699-7af5f486-4af3-11e8-925d-2005fc8ea78d.jpg)

**Comment by bodymovin** [comment]
Hi, can you share a link with the issue?

**Comment by creativedesignseurope** [comment]
Unfortunately no, because I still got my files saved localy. I could use a little help to make your job easier, so, please, tell me what you need. The whole code is set up strictly as it is written in your guide and based on the demo that I exported from AE. So just the basic JS code. It seems to me like the lottie.js overwrites the positioning of the animation and only the animation behaves weird - shows on top of the navbar. I put Lorem Ipsum into the animation div container and its behaving on scroll as it should, but when it gets to the animation only the animation overlaps the navbar. So weird : D

Note: I'm new to GitHub so I apologise if I did't write my issue straightforward.

**Here's the JS:**
`// sticky navbar
window.onscroll = function() {myFunction()};

var navbar = document.getElementById("sticky-nav");
var sticky = navbar.offsetTop;

function myFunction() {
  if (window.pageYOffset >= sticky) {
    navbar.classList.add("sticky")
  } else {
    navbar.classList.remove("sticky");
  }
}
// sticky navbar

// hero page animation (bodymovin)
var animation = bodymovin.loadAnimation ({
    container: document.getElementById('hero-anim'),
    renderer: 'svg',
    loop: true,
    autoplay: true,
    path: 'js/data.json'
});
// hero page animation (bodymovin)`

**Comment by bodymovin** [comment]
without the code it's difficult to assess, but perhaps if you set position: relative to the div containing the animation, the one with id hero-anim, it might solve the issue.

**Comment by creativedesignseurope** [comment]
Can I attach the code in a ZIP? If it's help here it is. Tried your suggestion but no success.
[website.zip](https://github.com/airbnb/lottie-web/files/1957801/website.zip)

**Comment by bodymovin** [comment]
The svg has a css property `transform: translate3d(0,0,0)` that promotes it to a separate composing layer.
This conflicts with the sticky top bar.
There are different things you can do to fix it, but the simplest one seems to be to add a `z-index` value of 1 to the sticky bar.
