### ISSUE TITLE
Force drawing the same frame

### ISSUE THREAD

**Issue by giuseppelt** [airbnb/lottie-web#998]
Hi, I'm using this lib to manage animations in my game.
I'm using the canvas renderer, I manage myself the playback, I call the `advanceTime` directly (which renders the frame).
All animation render on the same game canvas, I manage myself (clear and render on each frame).
All works fine, except when I want the game to pause, i.e. all animations must render the same frame.

But looking actual code here:
https://github.com/airbnb/lottie-web/blob/9102061388f5ab84163f6759d98e77dbc2f5ff1d/player/js/renderers/CanvasRenderer.js#L296

It seems if there're no modification, the rendering will be skipped.

Because, the `globalData._mdf` flag get reset on any frame, I have no means to edit it and force to true. 
Actually I'm using the hack to advance time by 0.001, but I get frame skips sometimes (a frame is not rendered).

I would like to avoid to fork and manage my copy to just add a flag (forceRender), somewhere.
Have you some solution in mind?

My proposed solution is to add a flag `forceRender○ to `globalData` of the `CanvasRenderer` and put use the flag as starting value of `_mdf`.

**Comment by bodymovin** [comment]
Hi, I'm thinking if it makes sense to use the clearCanvas boolean to force render instead of passing a new one.
Are you passing clearCanvas as false when you initiate animations?

**Comment by giuseppelt** [comment]
I edited the issue, while you responded.

Here the clarifications:
All animation render on the same game canvas, I manage myself (clear and render on each frame).
So, yes, clearCanvas = false. I clear the whole canvas, advance time, and render the new frame.

My proposed solution is to add a flag forceRender to globalData of the CanvasRenderer and use the flag as starting value of_mdf`.

**Comment by bodymovin** [comment]
I'm thinking of using the `clearCanvas = false` as an indication that every tick needs to be rendered regardless of the fact that it has changed.
It's being used [here](https://github.com/airbnb/lottie-web/blob/9102061388f5ab84163f6759d98e77dbc2f5ff1d/player/js/renderers/CanvasRenderer.js#L275) already to re-render even if it's the same frame, so it makes sense to also use it to force every frame.
Do you see any downside to implementing it like this?
