### ISSUE TITLE
Reverse play bodymovin

### ISSUE THREAD

**Issue by CharlieGlez** [airbnb/lottie-web#999]
Hello, 
first of all I have to say lottie is awesome! :)
So I made this pen where I forked one of your demos and made it clickable so it will play either clicking the animation or the button. My issue is I want to have the same click go reverse but I can't find the way. Example, like Optimus Prime transforms from a vehicle to a robot and from robot to vehicle. (Strange example!). Is there any of the "usage" items from lottie I could use for this.
Here is my fork.
[https://codepen.io/CharlieCode/pen/VxjbXa](https://codepen.io/CharlieCode/pen/VxjbXa)

Cheers :)

**Comment by bodymovin** [comment]
Hi, you can use anim.setDirection(-1) to play the animation backwards.

**Comment by CharlieGlez** [comment]
Hi, thanks for the quick feedback! :) And one other doubt if I use anim.setDirection(-1) I have to set up the 'gotoandstop' manually right (with the actual frame rates befor and after)?

**Comment by bodymovin** [comment]
calling it like this where `dir` would be the direction of the animation, should be enough.
````javascript
anim.setDirection(dir);  
anim.play();
````

**Comment by CharlieGlez** [comment]
Oh thank you very much! :)

**Comment by itsadityasharma** [comment]
Hello @CharlieGlez Please can you help me with this issue, I want to play only certain frames.
Sometimes when a Lottie is repeating its 1st Frame in the end, it doesn't seem like Reverse
Eg. https://lottiefiles.com/5145-menu-open-and-close

I just want to Play 0 to Frame 85 and reverse on frame 85 to 0
